### ISSUE TITLE
Flutter run is not looking for android sdk in the right place

### ISSUE THREAD

**Issue by Grzegorz-l90** [flutter/flutter#10046]
Trying to run an example app, but getting following error while running flutter run

```
Launching lib/main.dart on D5503 in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/nowy/Documents/workspace/Flutter/flutter_app_4/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > The SDK directory '/Users/nowy/Library/Android/sdk' does not exist.
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /Applications/Android Studio 2.app/Contents/gradle/gradle-3.2/bin/gradle app:properties
Running 'gradle assembleDebug'...                         

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/nowy/Documents/workspace/Flutter/flutter_app_4/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > The SDK directory '/Users/nowy/Library/Android/sdk' does not exist.
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

Everything looks fine with flutter doctor 

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Development/flutter
    • Framework revision bc390ef4d0 (2 days ago), 2017-05-10 13:42:26 +0200
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Development/android-sdk-macosx
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Development/android-sdk-macosx
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode 8.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
        brew update
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew update
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew update
        brew install cocoapods
        pod setup

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • D5503 • CB5A1XSSB0 • android-arm • Android 5.1.1 (API 22)

```

The problem here is that for some reason, run command is looking for the sdk at /Users/nowy/Library/Android/sdk while it is at /Development/android-sdk-macosx, I couldn't find a way to config that

Edit

As a workaround I created symbolic link with correct location, and now it works fine, but I would like to fix that

**Comment by eseidelGoogle** [comment]
Looks like this is a problem in our gradle files?  @jakobr-google or @jason-simmons would know.

**Comment by jakobr-google** [comment]
@Grzegorz-l90 what's the contents of `android/local.properties`? It should specify where Gradle gets the Android SDK from.

I'm not sure why it doesn't match your environment, but you could try deleting the local.properties file and run `flutter run` again. That should re-create the file, hopefully now pointing at the right location.

**Comment by Grzegorz-l90** [comment]
Deleting android/local.properties and running flutter run again fixed the problem.

**Comment by albertog** [comment]
Deleted not work for me throw this error

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bbb/Downloads/plugins-master/packages/firebase_database/example/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_auth'.
...

**Comment by mit-mit** [comment]
Sounds like the original problem experienced by @Grzegorz-l90 was resolved, so going to close this bug.

@albertog can you please open a new bug with details on your issue (steps you are running, flutter doctor output, etc.).

**Comment by rakz25** [comment]
Deleting local.properties from Android did not solved the problem.
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

**Comment by Krishnangshu17** [comment]
Hi rakz25,
Please check the blog -
https://indianjackofalltrade.com/a-problem-occurred-evaluating-root-project-android-flutter/

Hope, it will help you.
