### ISSUE TITLE
PlatformException(NoSuchMethodError, java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder;

### ISSUE THREAD

**Issue by rahulkhot108** [flutter/flutter#101198]
Issue at Initializing the player controller as follow :

```
PlatformException(NoSuchMethodError, java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /data/app/com.artnskills-kgrQBAbJiAYeZaTdJvwYGw==/base.apk!classes6.dex), Cause: null, Stacktrace: java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /data/app/com.artnskills-kgrQBAbJiAYeZaTdJvwYGw==/base.apk!classes6.dex)at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$MediaPeriodQueueTracker.updateMediaPeriodTimelines(DefaultAnalyticsCollector.java:1130)
at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$MediaPeriodQueueTracker.onTimelineChanged(DefaultAnalyti
```

Please give the solution for this issue. I stuck in this issue. please help

Thank You...

**Comment by denid88** [comment]
I've caught same problems.

**Comment by darshankawar** [comment]
@rahulkhot108 
Can you provide `flutter doctor -v`, plugin version and a complete minimal code sample that shows the exception ?

**Comment by rahulkhot108** [comment]
> @rahulkhot108 Can you provide `flutter doctor -v`, plugin version and a complete minimal code sample that shows the exception ?

**Comment by darshankawar** [comment]
Did you close this by accident or it has been resolved ?

**Comment by denid88** [comment]
No, I'm not the author of this issue,  but I've joined the current topic
with a similar problem. My problem didn't solve, and i we can, we should
keep this issue with my question.

пн, 4 апр. 2022 г. в 16:25, darshankawar ***@***.***>:

**Comment by rahulkhot108** [comment]
Sorry This closed by me accidentally. 
But I got the solution as follow : 
 
configurations.all {
    exclude group: 'com.google.guava', module: 'failureaccess'

    resolutionStrategy {
        eachDependency { details ->
            if('guava' == details.requested.name) {
                details.useVersion '27.0-android'
            }
        }
    }
}

The above block of gradle script responsible for issue

just commented and worked for me

Thank You....

**Comment by denid88** [comment]
My issue was related with exclude group: 'com.google.guava' too, I solved it. Seems, issue should be closed.
