### ISSUE TITLE
[go_router] Process redirects for each route

### ISSUE THREAD

**Issue by aoatmon** [flutter/flutter#101183]
## Steps to Reproduce

I don't know if this is a bug, or my expectations are wrong,
if the latter please consider this issue as a feature request

1. `flutter run -d chrome` the code sample or this [repo](https://github.com/aoatmon/navigation_redirect)
2. from `foo` page 
    - don't touch the switch
    - tap `bar`: does not navigate, that's ok
    - tap `bar/baz`: it does navigate (?)
3. once on `bar/baz` tap the back button: it does navigate to `bar` (!?)
4. once on `bar` navigate to `foo` (ok)
5. once back on `foo` verify activating switch tapping on `foo` works

**Expected results:** 
- from `foo` when swich is "off" tapping on `bar/baz` won't navigate, because "behind" `bar` protected by redirect
- from `bar/baz` back button shouldn't pop to `bar`, but be redirected to `foo`

**Actual results:**
- from `foo` I can navigate to `bar/baz` even when switch is "off"
- redirection doesn't work on "pop"

<details>
<summary>Code sample</summary>

```dart
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const AllowedWidget(child: MyApp()));

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late final GoRouter _router;

  @override
  void dispose() {
    _router.dispose();
    super.dispose();
  }

  @override
  Widget build(context) {
    final allow = InheritedAllowedWidget.of(context).notifier;
    _router = GoRouter(
      routes: <GoRoute>[
        GoRoute(path: '/', redirect: (state) => '/foo'),
        GoRoute(
          path: '/foo',
          builder: (context, state) => MyPage(
            key: state.pageKey,
            nexts: const ['/bar', '/bar/baz'],
          ),
        ),
        GoRoute(
          path: '/bar',
          builder: (context, state) => MyPage(
            key: state.pageKey,
            nexts: const ['/bar/baz'],
          ),
          redirect: (state) => allow.value ? null : '/foo',
          routes: [
            GoRoute(
              path: 'baz',
              builder: (context, state) => MyPage(
                key: state.pageKey,
                nexts: const ['/foo'],
              ),
            ),
          ],
        ),
      ],
    );
    return MaterialApp.router(
      routeInformationParser: _router.routeInformationParser,
      routerDelegate: _router.routerDelegate,
    );
  }
}

class MyPage extends StatelessWidget {
  final Iterable<String> nexts;
  const MyPage({
    required this.nexts,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(context) {
    final allow = InheritedAllowedWidget.of(context).notifier;
    return Scaffold(
      appBar: AppBar(
        title: Text(GoRouter.of(context).location),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          for (final next in nexts)
            Center(
              child: TextButton(
                child: Text(next),
                onPressed: () => context.go(next),
              ),
            ),
          Center(
            child: ValueListenableBuilder<bool>(
              valueListenable: allow,
              builder: (context, allowed, _) => Switch(
                value: allowed,
                onChanged: (value) => allow.value = value,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class InheritedAllowedWidget extends InheritedWidget {
  const InheritedAllowedWidget({
    Key? key,
    required this.notifier,
    required Widget child,
  }) : super(
          key: key,
          child: child,
        );

  final ValueNotifier<bool> notifier;

  static InheritedAllowedWidget of(BuildContext context) {
    final InheritedAllowedWidget? result =
        context.dependOnInheritedWidgetOfExactType<InheritedAllowedWidget>();
    assert(result != null, 'No InheritedAllowedWidget found in context');
    return result!;
  }

  @override
  bool updateShouldNotify(InheritedAllowedWidget oldWidget) =>
      notifier.hashCode != oldWidget.notifier.hashCode;
}

class AllowedWidget extends StatefulWidget {
  final Widget child;
  const AllowedWidget({
    required this.child,
    Key? key,
  }) : super(key: key);

  @override
  State<AllowedWidget> createState() => _AllowedWidgetState();
}

class _AllowedWidgetState extends State<AllowedWidget> {
  late final ValueNotifier<bool> _notifier;

  @override
  void initState() {
    _notifier = ValueNotifier(false);
    super.initState();
  }

  @override
  void dispose() {
    _notifier.dispose();
    super.dispose();
  }

  @override
  Widget build(context) => InheritedAllowedWidget(
        notifier: _notifier,
        child: widget.child,
      );
}

```

</details>

<details>
  <summary>doctor & pubspec</summary>

```yaml
name: navigation_redirect
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  go_router: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
```

```console
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-EE)
    • Flutter version 2.10.4 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
> ```dart
> import 'package:flutter_riverpod/flutter_riverpod.dart';
> ```

I see that you are using this plugin which is third party. Does the behavior you are seeing replicate without using this plugin and only with `go_router` and core framework code ?

**Comment by aoatmon** [comment]
@darshankawar 
I've updated the code sample removing riverpod

**Comment by darshankawar** [comment]
Thanks for the update.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.366, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.366 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b97874895 (2 days ago), 2022-04-01 21:20:01 -0400
    • Engine revision 801d8c530f
    • Dart version 2.17.0 (build 2.17.0-265.0.dev)
    • DevTools version 2.12.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by johnpryan** [comment]
Thanks for filing an issue - this is because go_router only invokes the redirect on the last-most matching GoRoute. So when you navigate to `/bar/baz` the redirect for `/bar` is ignored. 

I agree that this should be fixed. We need to ensure that all of the redirects are honored if we are going to attempt to display them.

I created a smaller snippet in [this comment](https://github.com/flutter/flutter/issues/99096#issuecomment-1090593268), which shows the same problem you are describing.

**Comment by johnpryan** [comment]
You can work around this issue by using the top-level `redirect` parameter instead.

**Comment by irizzaflutter** [comment]
blank black page when pop

**Comment by iapicca** [comment]
> You can work around this issue by using the top-level redirect parameter instead.

@johnpryan 
the problem with this workaround is that if the redirect logic cannot access a "non-top-level" dependency
which means every `InheritedWidget`, `Bloc`, `Provider` will have to be above `GoRouter`
and potentially never be disposed (even `riverpod` is affected by this!)

**Comment by johnpryan** [comment]
@iapicca we aren't planning to support local BuildContexts in redirects. Right now we are only planning to provide the BuildContext used to build MaterialApp in redirects. See this issue for details: https://github.com/flutter/flutter/issues/99121

**Comment by megamaddu** [comment]
I'm not sure if this is the same problem, but I'm having a similar issue with redirect not working which results in a blank page (with no debug route info logged) like @irizzaflutter mentions.

Debug logs:
```
[GoRouter] known full paths for routes:
[GoRouter]   => /
[GoRouter]   =>   /settings
[GoRouter]   => /listings
[GoRouter]   =>   /listings/:listingId
[GoRouter] known full paths for route names:
[GoRouter]   settings => /settings
[GoRouter]   listings => /listings
[GoRouter]   listing-detail => /listings/:listingId
[GoRouter] setting initial location /settings
[GoRouter] MaterialApp found
[GoRouter] popping /settings
```

Routes:
```dart
        GoRouter(
          initialLocation: '/settings',
          debugLogDiagnostics: true,
          redirect: (state) {
            if (state.location == '/') {
              print('redirect from root');
              return '/listings';
            }
            return null;
          },
          routes: [
            GoRoute(
              path: '/',
              redirect: (_) {
                print('redirect from /');
                return '/listings';
              },
              routes: [
                GoRoute(
                  path: 'settings',
                  name: SettingsView.routeName,
                  builder: (context, state) =>
                      SettingsView(controller: settingsController),
                ),
              ],
            ),
            GoRoute(
              path: '/listings',
              name: ListingListView.routeName,
              builder: (context, state) => const ListingListView(),
              routes: [
                GoRoute(
                  path: ':listingId',
                  name: ListingDetailsView.routeName,
                  builder: (context, state) {
                    final listingId =
                        ListingID.fromJson(state.params['listingId']!);
                    return ListingDetailsView(listingId);
                  },
                ),
              ],
            ),
          ],
          errorPageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: Scaffold(
              body: Text(state.error.toString()),
            ),
          ),
        )
```

The error builder and both redirects (root and `/`) are not being hit. This happens everywhere I've tested (macOS, iOS, and web). On web, the url does change to `/`, but they all pop to blank screens. This can also be reproduced on web by refreshing the page while on the settings page, then popping (instead of using `initialRoute: '/settings'`). I would guess a deep link would have the same behavior.

I also tried a custom back button from the settings route, using `context.canPop()`, but it returns true and still pops to the blank screen.

**Comment by chunhtai** [comment]
There is also an issue that the pop does not honor the redirect. we also need to make sure we account for that when we fix this issue

**Comment by iapicca** [comment]
> There is also an issue that the pop does not honor the redirect. we also need to make sure we account for that when we fix this issue

@chunhtai
I think the missing redirection on pop is integral part of the issue

> ## Steps to Reproduce
> [ ...]
> 3. once on `bar/baz` tap the back button: it does navigate to `bar` (!?)

**Comment by chunhtai** [comment]
fixes has been merged into v5 feature branch https://github.com/flutter/packages/pull/2398, since it may be considered as breaking change.

Merge the feature branch back to main is tracked in https://github.com/flutter/flutter/issues/108044. Closing this issue

**Comment by iapicca** [comment]
@chunhtai 
it seems that the issue at [step 3](https://github.com/flutter/flutter/issues/101183#issue-1189690710) still occurs

### to reproduce
 
 1. enable the switch
 2. navigate to `bar/baz`
 3. deactivate the switch
 4. tap the back button
 
 ### expected result
 
 should redirect to `foo`
 
 ### actual result
 
 navigates to `bar`

<details>
  <summary>updated code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const AllowedWidget(child: MyApp()));

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late final GoRouter _router;

  @override
  void dispose() {
    _router.dispose();
    super.dispose();
  }

  @override
  Widget build(context) {
    final allow = InheritedAllowedWidget.of(context).notifier;
    _router = GoRouter(
      routes: <GoRoute>[
        GoRoute(path: '/', redirect: (state) => '/foo'),
        GoRoute(
          path: '/foo',
          builder: (context, state) => MyPage(
            key: state.pageKey,
            nexts: const ['/bar', '/bar/baz'],
          ),
        ),
        GoRoute(
          path: '/bar',
          builder: (context, state) => MyPage(
            key: state.pageKey,
            nexts: const ['/bar/baz'],
          ),
          redirect: (state) => allow.value ? null : '/foo',
          routes: [
            GoRoute(
              path: 'baz',
              builder: (context, state) => MyPage(
                key: state.pageKey,
                nexts: const ['/foo'],
              ),
            ),
          ],
        ),
      ],
    );
    return MaterialApp.router(
      routeInformationParser: _router.routeInformationParser,
      routerDelegate: _router.routerDelegate,
      routeInformationProvider: _router.routeInformationProvider,
    );
  }
}

class MyPage extends StatelessWidget {
  final Iterable<String> nexts;
  const MyPage({
    required this.nexts,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(context) {
    final allow = InheritedAllowedWidget.of(context).notifier;
    return Scaffold(
      appBar: AppBar(
        title: Text(GoRouter.of(context).location),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          for (final next in nexts)
            Center(
              child: TextButton(
                child: Text(next),
                onPressed: () => context.go(next),
              ),
            ),
          Center(
            child: ValueListenableBuilder<bool>(
              valueListenable: allow,
              builder: (context, allowed, _) => Switch(
                value: allowed,
                onChanged: (value) => allow.value = value,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class InheritedAllowedWidget extends InheritedWidget {
  const InheritedAllowedWidget({
    Key? key,
    required this.notifier,
    required Widget child,
  }) : super(
          key: key,
          child: child,
        );

  final ValueNotifier<bool> notifier;

  static InheritedAllowedWidget of(BuildContext context) {
    final InheritedAllowedWidget? result =
        context.dependOnInheritedWidgetOfExactType<InheritedAllowedWidget>();
    assert(result != null, 'No InheritedAllowedWidget found in context');
    return result!;
  }

  @override
  bool updateShouldNotify(InheritedAllowedWidget oldWidget) =>
      notifier.hashCode != oldWidget.notifier.hashCode;
}

class AllowedWidget extends StatefulWidget {
  final Widget child;
  const AllowedWidget({
    required this.child,
    Key? key,
  }) : super(key: key);

  @override
  State<AllowedWidget> createState() => _AllowedWidgetState();
}

class _AllowedWidgetState extends State<AllowedWidget> {
  late final ValueNotifier<bool> _notifier;

  @override
  void initState() {
    _notifier = ValueNotifier(false);
    super.initState();
  }

  @override
  void dispose() {
    _notifier.dispose();
    super.dispose();
  }

  @override
  Widget build(context) => InheritedAllowedWidget(
        notifier: _notifier,
        child: widget.child,
      );
}

```

</details>

<details>
  <summary>updated pubspec</summary>

```yaml
name: issues_101183
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
    git:
     url: https://github.com/flutter/packages.git
     path: packages/go_router
     ref: go_router_v5


dev_dependencies:
  flutter_lints: ^2.0.1
  
flutter:
  uses-material-design: true
```

</details>
