### ISSUE TITLE
[TabController]The following assertion was thrown while notifying listeners for AnimationController: Build scheduled during frame

### ISSUE THREAD

**Issue by kulny** [flutter/flutter#102600]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press the add (+) button to add a tab.  
3. Select the new tab.
4. Press the add button again.

**Expected results:** 
A new tab appears without any additional issue.

**Actual results:** 
Unexpected calls on a disposed controller.

**Additional Information**
I am trying to create a dynamic tab system for a flutter windows app. I have managed to get it mostly working, however there are some major flaws in the implementation that I am unsure how to handle. 

First, this is sort of a second step in another issue I had, which can be further explained by https://stackoverflow.com/questions/72006417/build-scheduled-during-frame-after-changing-tab-in-tab-bar?noredirect=1#comment127252356_72006417. Without  asking you to go and check that question for the details, though, the root of the issue was that an animation controller seemed to be getting built when it should not be, even though the TabController was given a Duration.zero value for the animation duration. 

Eventually, I did manage to (seemingly) fix this, however it required me to change the index setter for an extended TabController: 

```dart
set index(int value) {
    WidgetsBinding.instance?.addPostFrameCallback(
      (timeStamp) {
        _changeIndex(value);
      },
    );
  }
```
This change can be seen in the test.dart code below.

After this change, the issue with setstate during build calls was managed, however another issue cropped up: calls on a disposed controller. 

The code I have been using to manage the state of the TabBar (which is a custom version of a tab bar that I have modified slightly from that of Yuriy Luchaninov's answer in [How to create a dynamic TabBarView/ Render a new Tab with a function in Flutter?](https://stackoverflow.com/questions/50036546/how-to-create-a-dynamic-tabbarview-render-a-new-tab-with-a-function-in-flutter) does not seem to have any issues in terms of disposal timing, so far as I can tell. 

I'm pretty lost with this issue, so please let me know if I've completely missed anything fundamental. Please let me know if there's any more information I need to add.

<details>
<summary>Code sample</summary>
main.dart

```dart
// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:oddisy_tabs_prototype/providers.dart';
import 'package:oddisy_tabs_prototype/test.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FocusNode currentTabFocusNode = FocusNode();
  List<TabObject> tabs = [
    TabObject(
      tabType: TabOjectType.CURRENT_PROJECT,
      tabName: 'Current Project',
    ),
    TabObject(
        tabType: TabOjectType.ENTRY,
        prefixImagePlaceholder: Icon(Icons.auto_awesome),
        tabName: 'test1'),
    // TabObject.createNew(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Consumer(builder: (context, ref, child) {
        // final tabs = ref.watch(tabsNotifierProvider);
        // if (tabs.isEmpty) {
        //   Future.delayed(
        //     Duration.zero,
        //     () => ref.read(tabsNotifierProvider.notifier).addTab(
        //         TabObject(tabType: TabOjectType.ENTRY, tabName: 'default')),
        //   );
        // }
        return CustomTabView(
            onAddPressed: () {
              // Future.delayed(
              //     Duration.zero,
              //     () => ref
              //         .read(tabsNotifierProvider.notifier)
              //         .addTab(TabObject(tabType: TabOjectType.EMPTY)));
              // tabs.add(TabObject(tabType: TabOjectType.EMPTY));

              // WidgetsBinding.instance?.addPostFrameCallback(
              //   (timeStamp) => setState(() {
              //     print(tabs.length);
              //     // tabs.add(TabObject(tabType: TabOjectType.EMPTY));
              //     // tabs.add(TabObject(tabType: TabOjectType.EMPTY));
              //     print(tabs.length);
              //   }),
              // );
              setState(() {
                tabs.add(TabObject(tabType: TabOjectType.EMPTY));
              });
            },
            onMiddleMouseButtonTapUp: (index) {
              // Future.delayed(
              //     Duration.zero,
              //     (() => ref
              //         .read(tabsNotifierProvider.notifier)
              //         .removeTabByIndex(index)));

              setState(() {
                tabs.removeAt(index);
              });
            },
            // onPositionChange: (value) {
            //   print(tabs[value].tabType);
            //   if (tabs[value].tabType == TabOjectType.CREATE_NEW) {
            //     print('create new tab pressed');
            //     setState(() {
            //       tabs[value] = TabObject(tabType: TabOjectType.EMPTY);
            //       tabs.add(TabObject.createNew());
            //     });
            //   }
            // },
            itemCount: tabs.length,
            tabBuilder: (context, index) {
              if (tabs[index].tabType == TabOjectType.CREATE_NEW) {
                return tabs[index].prefixImagePlaceholder;
              } else {
                return Row(
                  children: [
                    ConstrainedBox(
                        constraints:
                            const BoxConstraints(maxHeight: 25, maxWidth: 25),
                        child: tabs[index].prefixImagePlaceholder),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 8),
                      child: Text('${tabs[index].tabName}'),
                    ),
                    TextButton(
                        style: TextButton.styleFrom(
                          padding: EdgeInsets.zero,
                          minimumSize: Size.zero,
                          tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                          shape: BeveledRectangleBorder(
                              borderRadius: BorderRadius.circular(5)),
                        ),
                        onPressed: () {
                          if (index != 0) {
                            setState(() {
                              tabs.removeAt(index);
                            });
                          } else {
                            // TODO close whole project
                          }
                        },
                        child: const Icon(
                          Icons.close,
                          color: Colors.grey,
                        ))
                  ],
                );
              }
            },
            pageBuilder: (context, index) {
              return RawKeyboardListener(
                focusNode: currentTabFocusNode,
                onKey: (value) {
                  if (value is RawKeyDownEvent) {
                    if (value.isControlPressed &&
                        value.logicalKey == LogicalKeyboardKey.keyW) {
                      print('ctrl w pressed');
                      setState(() {
                        tabs.removeAt(index);
                      });
                    }
                  }
                },
                child: Center(
                  child: Text('tab $index'),
                ),
              );
            });
      }),
    );
  }
}

enum TabOjectType {
  CREATE_NEW,
  ENTRY,
  HIGH_LEVEL,
  HOME,
  CURRENT_PROJECT,
  EMPTY,
}

class TabObject {
  static TabObject createNew() {
    return TabObject(
        tabType: TabOjectType.CREATE_NEW,
        prefixImagePlaceholder: Icon(Icons.add),
        tabName: '');
  }

  Widget prefixImagePlaceholder;

  /// this is the optionally provided actual object which the tab is referencing -- such as the entry of an entry page or its id
  dynamic object;
  String? tabName;
  TabOjectType tabType;

  TabObject(
      {required this.tabType,
      this.prefixImagePlaceholder = const Placeholder(
        fallbackHeight: 10,
        fallbackWidth: 10,
      ),
      this.object,
      this.tabName});
}

class CustomTabView extends StatefulWidget {
  final int itemCount;
  final IndexedWidgetBuilder tabBuilder;
  final IndexedWidgetBuilder pageBuilder;
  final Widget? stub;
  final ValueChanged<int>? onPositionChange;
  final int? initPosition;
  final void Function(int tabIndexPosition)? onMiddleMouseButtonTapUp;
  final VoidCallback onAddPressed;

  /// referenced from https://stackoverflow.com/questions/50036546/how-to-create-a-dynamic-tabbarview-render-a-new-tab-with-a-function-in-flutter
  /// with edits for our usage
  const CustomTabView({
    required this.itemCount,
    required this.tabBuilder,
    required this.pageBuilder,
    this.stub,
    this.onPositionChange,
    this.initPosition,
    this.onMiddleMouseButtonTapUp,
    required this.onAddPressed,
  });

  @override
  _CustomTabViewState createState() => _CustomTabViewState();
}

class _CustomTabViewState extends State<CustomTabView>
    with TickerProviderStateMixin {
  late TabControllerCustom controller;
  late int _currentCount;
  late int _currentPosition;

  @override
  void initState() {
    _currentPosition = widget.initPosition ?? 0;
    controller = TabControllerCustom(
        length: widget.itemCount,
        vsync: this,
        initialIndex: _currentPosition,
        animationDuration: Duration.zero);
    // controller.addListener(onPositionChange);
    _currentCount = widget.itemCount;
    super.initState();
  }

  @override
  void didUpdateWidget(CustomTabView oldWidget) {
    print(
        'current count = $_currentCount and widget count = ${widget.itemCount}');
    if (_currentCount != widget.itemCount) {
      print('did not equal previous item count');
      // controller.removeListener(onPositionChange);
      final oldController = controller;
      // controller.dispose();

      if (widget.initPosition != null) {
        _currentPosition = widget.initPosition!;
      }

      if (_currentPosition >= widget.itemCount - 1) {
        _currentPosition = widget.itemCount - 1;
        _currentPosition = _currentPosition < 0 ? 0 : _currentPosition;
        if (widget.onPositionChange is ValueChanged<int>) {
          WidgetsBinding.instance?.addPostFrameCallback((_) {
            if (mounted) {
              // widget.onPositionChange!(_currentPosition);
            }
          });
        }
      }

      _currentCount = widget.itemCount;
      setState(() {
        controller = TabControllerCustom(
            length: widget.itemCount,
            vsync: this,
            initialIndex: _currentPosition,
            animationDuration: Duration.zero);
        // controller.addListener(onPositionChange);
      });
      print('controller index ${oldController.hasListeners}');
      oldController.dispose();
    } else if (widget.initPosition != null) {
      print('did equal previous item count');

      controller.animateTo(widget.initPosition!);
    }

    super.didUpdateWidget(oldWidget);
  }

  @override
  void dispose() {
    // controller.removeListener(onPositionChange);
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (widget.itemCount < 1) return widget.stub ?? Container();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Row(
          children: [
            Container(
              alignment: Alignment.centerLeft,
              child: GestureDetector(
                onTertiaryTapUp: (details) {
                  if (widget.onMiddleMouseButtonTapUp != null) {
                    widget.onMiddleMouseButtonTapUp!(_currentPosition);
                  }
                },
                child: TabBar(
                  padding: EdgeInsets.zero,
                  labelPadding: EdgeInsets.zero,
                  isScrollable: true,
                  controller: controller,
                  indicator: BoxDecoration(
                    color: Colors.grey.withOpacity(1),
                  ),
                  tabs: List.generate(
                    widget.itemCount,
                    (index) => widget.tabBuilder(context, index),
                  ),
                ),
              ),
            ),
            TextButton(
              onPressed: () {
                WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
                  widget.onAddPressed();
                });
              },
              child: const Icon(Icons.add),
              style: TextButton.styleFrom(
                padding: EdgeInsets.zero,
                minimumSize: Size.zero,
                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                shape: BeveledRectangleBorder(
                    borderRadius: BorderRadius.circular(5)),
              ),
            )
          ],
        ),
        Expanded(
          child: TabBarView(
            controller: controller,
            children: List.generate(
              widget.itemCount,
              (index) => widget.pageBuilder(context, index),
            ),
          ),
        ),
      ],
    );
  }

  // onPositionChange() {
  //   if (!controller.indexIsChanging) {
  //     _currentPosition = controller.index;
  //     if (widget.onPositionChange is ValueChanged<int>) {
  //       widget.onPositionChange!(_currentPosition);
  //     }
  //   }
  // }
}

```
test.dart (which is where I have some widgets that I built to test some ideas for the issue)
```dart
import 'package:flutter/animation.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class TabControllerCustom extends TabController {
  TabControllerCustom(
      {int initialIndex = 0,
      Duration? animationDuration,
      required this.length,
      required TickerProvider vsync})
      : assert(length != null && length >= 0),
        assert(initialIndex != null &&
            initialIndex >= 0 &&
            (length == 0 || initialIndex < length)),
        _index = initialIndex,
        _previousIndex = initialIndex,
        _animationDuration = animationDuration ?? kTabScrollDuration,
        _animationController = AnimationController.unbounded(
          value: initialIndex.toDouble(),
          vsync: vsync,
        ),
        super(
            length: length,
            vsync: vsync,
            animationDuration: animationDuration,
            initialIndex: initialIndex);

  Animation<double>? get animation => _animationController?.view;
  AnimationController? _animationController;

  Duration get animationDuration => _animationDuration;
  final Duration _animationDuration;

  final int length;

  void _changeIndex(int value, {Duration? duration, Curve? curve}) {
    assert(value != null);
    assert(value >= 0 && (value < length || length == 0));
    assert(duration != null || curve == null);
    assert(_indexIsChangingCount >= 0);
    if (value == _index || length < 2) return;
    _previousIndex = index;
    _index = value;
    if (duration != null && duration > Duration.zero) {
      // _indexIsChangingCount += 1;
      // notifyListeners(); // Because the value of indexIsChanging may have changed.
      // _animationController!
      //     .animateTo(_index.toDouble(), duration: duration, curve: curve!)
      //     .whenCompleteOrCancel(() {
      //   if (_animationController != null) {
      //     // don't notify if we've been disposed
      //     _indexIsChangingCount -= 1;
      //     notifyListeners();
      //   }
      // });
    } else {
      _indexIsChangingCount += 1;
      if (_animationController != null) {
        _animationController!.value = _index.toDouble();
      }
      _indexIsChangingCount -= 1;
      notifyListeners();
    }
  }

  int get index => _index;
  int _index;
  set index(int value) {
    WidgetsBinding.instance?.addPostFrameCallback(
      (timeStamp) {
        _changeIndex(value);
      },
    );
  }

  int get previousIndex => _previousIndex;
  int _previousIndex;

  bool get indexIsChanging => _indexIsChangingCount != 0;
  int _indexIsChangingCount = 0;

  void animateTo(int value, {Duration? duration, Curve curve = Curves.ease}) {
    _changeIndex(value, duration: duration ?? _animationDuration, curve: curve);
  }

  double get offset => _animationController!.value - _index.toDouble();
  set offset(double value) {
    assert(value != null);
    assert(value >= -1.0 && value <= 1.0);
    assert(!indexIsChanging);
    if (value == offset) return;
    _animationController!.value = value + _index.toDouble();
  }

  @override
  void dispose() {
    print('controller dispose called and has listeners is $hasListeners');
    _animationController?.dispose();
    _animationController = null;
    super.dispose();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
info - Unused import: 'package:oddisy_tabs_prototype/providers.dart' - lib\main.dart:6:8 - unused_import
   info - Prefer const with constant constructors - lib\main.dart:45:33 - prefer_const_constructors        
   info - Avoid `print` calls in production code - lib\main.dart:151:23 - avoid_print
   info - Prefer const with constant constructors - lib\main.dart:181:33 - prefer_const_constructors       
   info - Use key in widget constructors - lib\main.dart:214:3 - use_key_in_widget_constructors
   info - Avoid `print` calls in production code - lib\main.dart:251:5 - avoid_print
   info - Avoid `print` calls in production code - lib\main.dart:254:7 - avoid_print
   info - Avoid `print` calls in production code - lib\main.dart:289:7 - avoid_print
   info - The member 'hasListeners' can only be used within instance members of subclasses of 'package:flutter/src/foundation/change_notifier.dart' - lib\main.dart:289:47 - invalid_use_of_protected_member        
   info - Avoid `print` calls in production code - lib\main.dart:292:7 - avoid_print
   info - The import of 'package:flutter/animation.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/cupertino.dart' - lib\test.dart:1:8 -
          unnecessary_import
   info - The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\test.dart:2:8 - unnecessary_import   info - The operand can't be null, so the condition is always true - lib\test.dart:11:23 - unnecessary_null_comparison
   info - The operand can't be null, so the condition is always true - lib\test.dart:12:29 - unnecessary_null_comparison
   info - Annotate overridden members - lib\test.dart:28:26 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:31:16 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:34:13 - annotate_overrides
   info - Don't override fields - lib\test.dart:34:13 - overridden_fields
   info - The operand can't be null, so the condition is always true - lib\test.dart:37:18 - unnecessary_null_comparison
   info - Annotate overridden members - lib\test.dart:66:11 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:68:7 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:76:11 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:79:12 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:82:8 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:86:14 - annotate_overrides
   info - Annotate overridden members - lib\test.dart:87:7 - annotate_overrides
   info - The operand can't be null, so the condition is always true - lib\test.dart:88:18 - unnecessary_null_comparison
   info - Avoid `print` calls in production code - lib\test.dart:97:5 - avoid_print

28 issues found. (ran in 12.0s)
```

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 2.10.5 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\Cody\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.66.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.75

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @kulny, Thanks for filing the issue. Managing a custom `TabController` to handle all the logic would be too much work, I am wondering why not try something as fundamental as this with the built in TabController. 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Widget> _tabs = [];

  @override
  void initState() {
    super.initState();
    List.generate(3, (index) => _addTab());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Default Tab Controller"),
      ),
      body: DefaultTabController(
        length: _tabs.length,
        child: TabBar(tabs: _tabs),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _addTab(),
        child: const Icon(Icons.add),
      ),
    );
  }

  void _addTab() {
    setState(() {
      _tabs.add(Text("Tab ${_tabs.length}",
          style: const TextStyle(color: Colors.black)));
    });
  }
}
```

**Comment by kulny** [comment]
While something simpler would absolutely be ideal, I'm actually having trouble getting your suggested solution to work as expected. When attempting to add a tab, the tab bar immediately tries to rebuild and throws an out of bounds error on the array. I think this is why the more complex TabController state management is necessary.

**Comment by kulny** [comment]
Looking at it some more, I _think_ this is caused by the fact that TabBar directly references the array which holds the 'tabs', and thus both the oldWidget and new widget that are called in didUpdateWidget are looking at the same list for size. This means that didUpdateWidget is not properly seeing the difference in tab size, and then later calls an out of index error because the new global keys that TabBar would build for new tabs have not been built. 

Maybe that suggests there must be some slightly more complex state management on the array itself?

**Comment by kulny** [comment]
Here's an example of the solution you provided with a basic riverpod state management. This solves the issue with out of bound errors on the tab bar.

<details>
<summary>solution using riverpod</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const ProviderScope(child: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, ref, child) {
        final _tabs = ref.watch(tabsNotifierProvider);
        return Scaffold(
          appBar: AppBar(
            title: const Text("Default Tab Controller"),
          ),
          body: DefaultTabController(
            length: _tabs.length,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TabBar(
                  tabs: _tabs,
                  isScrollable: true,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              setState(() {
                ref.read(tabsNotifierProvider.notifier).addTab(Text(
                    "Tab ${_tabs.length}",
                    style: const TextStyle(color: Colors.black)));
              });
            },
            child: const Icon(Icons.add),
          ),
        );
      },
    );
  }
}

final tabsNotifierProvider =
    StateNotifierProvider<TabsNotifierTest, List<Widget>>(
        ((ref) => TabsNotifierTest()));

class TabsNotifierTest extends StateNotifier<List<Widget>> {
  TabsNotifierTest() : super([]);

  void addTab(Widget widget) {
    state = [...state, widget];
  }
}
```

</details>
However, when I attempt to expand this solution to fit my ultimate goals - no animation, removable tabs, a more embedded add button, etc - I run into a similar issue as one hinted in the original issue. This issue is that TabController runs into an error with <details>
<summary>error screenshot</summary>

![image](https://user-images.githubusercontent.com/27989807/165589204-222727c5-164b-4025-ae47-3bfdcb0e44e6.png)

</details>

As noted in the original post, this issue might be fixed by extending a TabController to override `set index` to use `addPostFrameCallback` 
<details>
<summary>TabController override code</summary>

```dart
  set index(int value) {
    WidgetsBinding.instance?.addPostFrameCallback(
      (timeStamp) {
        _changeIndex(value);
      },
    );
  }
```

</details>

However, this is quickly becoming a bit different than the spirit of your original solution.

**Comment by maheshmnj** [comment]
> While something simpler would absolutely be ideal, I'm actually having trouble getting your suggested solution to work as expected. 

Ah, Sorry I should have mentioned, The code sample I shared above works fine on the latest master channel Here is the output 


https://user-images.githubusercontent.com/31410839/165679777-9a66a9b8-a92b-4e50-91fe-ef5b805a5525.mov

It was fixed here https://github.com/flutter/flutter/pull/94623, if the above output is exactly what you are trying to achieve then I would suggest using the fix from the PR

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.712, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.0.pre.712 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c22f5648a (77 minutes ago), 2022-04-25 05:34:07 -0400
    • Engine revision 10efa195bf
    • Dart version 2.18.0 (build 2.18.0-44.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.4:5533 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by kulny** [comment]
Your solution provides some of what I'm looking to do, but is still missing several key features. First among those is a tab bar view that can be dynamically built depending on the selected tab. However, even on the master branch, a tab bar view does not rebuild itself properly to use the expected state of a list, and I am required to use riverpod to manage the list state in order to force the tab bar view to rebuild. 

<details><summary>riverpod state management solution for tab bar view</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final tabsNotifierProvider =
    StateNotifierProvider<TabsNotifierTest, List<Widget>>(
        ((ref) => TabsNotifierTest()));

class TabsNotifierTest extends StateNotifier<List<Widget>> {
  TabsNotifierTest() : super([]);

  void addTab(Widget widget) {
    state = [...state, widget];
  }
}

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Default Tab Controller"),
      ),
      body: Consumer(
        builder: (context, ref, child) {
          final _tabs = ref.watch(tabsNotifierProvider);
          return DefaultTabController(
            length: _tabs.length,
            animationDuration: Duration.zero,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Flexible(child: TabBar(tabs: _tabs)),
                    TextButton(
                      onPressed: (() => _addTab(ref)),
                      child: const Icon(Icons.add),
                    )
                  ],
                ),
                Flexible(child: TabBarView(children: _tabs)),
              ],
            ),
          );
        },
      ),
    );
  }

  void _addTab(WidgetRef ref) {
    ref
        .read(tabsNotifierProvider.notifier)
        .addTab(Text('hi ${ref.read(tabsNotifierProvider).length}'));
  }
}
```

</details>

With that fixed, another problem seems to be consistent among both stable and master branches - setting `DefaultTabController` to use `animationDuration` of `Duration.zero` will cause a build to be scheduled by the animation controller during a build in some cases. As referenced in my original post, this can be fixed by overriding the `set index` of a `TabController` to use 
<details><summary>tab controller set index fix</summary>

```dart
set index(int value) {
    WidgetsBinding.instance?.addPostFrameCallback(
      (timeStamp) {
        _changeIndex(value);
      },
    );
  }
```
</details>

<details><summary>reproducible issue with set state called during build error (same code as above, but added in this section for clarity)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final tabsNotifierProvider =
    StateNotifierProvider<TabsNotifierTest, List<Widget>>(
        ((ref) => TabsNotifierTest()));

class TabsNotifierTest extends StateNotifier<List<Widget>> {
  TabsNotifierTest() : super([]);

  void addTab(Widget widget) {
    state = [...state, widget];
  }
}

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Default Tab Controller"),
      ),
      body: Consumer(
        builder: (context, ref, child) {
          final _tabs = ref.watch(tabsNotifierProvider);
          return DefaultTabController(
            length: _tabs.length,
            animationDuration: Duration.zero,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Flexible(child: TabBar(tabs: _tabs)),
                    TextButton(
                      onPressed: (() => _addTab(ref)),
                      child: const Icon(Icons.add),
                    )
                  ],
                ),
                Flexible(child: TabBarView(children: _tabs)),
              ],
            ),
          );
        },
      ),
    );
  }

  void _addTab(WidgetRef ref) {
    ref
        .read(tabsNotifierProvider.notifier)
        .addTab(Text('hi ${ref.read(tabsNotifierProvider).length}'));
  }
}
```

Unfortunately, it becomes quite troublesome to extend the entire `DefaultTabController` widget in order to fix this issue (which also requires extending `TabController` itself) and copying them wholesale seems like a bad long-term fix.

**Comment by kulny** [comment]
Here is an implementation that does not use riverpod which also causes this error where animation controller throws an error `Build scheduled during frame.`.

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<int> _tabs = [];

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Default Tab Controller"),
      ),
      body: DefaultTabController(
        length: _tabs.length,
        animationDuration: Duration.zero,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Flexible(
                  child: TabBar(
                    labelColor: Colors.black,
                    unselectedLabelColor: Colors.black,
                    isScrollable: true,
                    tabs: List.generate(
                      _tabs.length,
                      (index) => Builder(
                        builder: (context) {
                          return Text('tab $index');
                        },
                      ),
                    ),
                  ),
                ),
                TextButton(
                  onPressed: (() => _addTab()),
                  child: const Icon(Icons.add),
                )
              ],
            ),
            Flexible(
                child: TabBarView(
                    children: List.generate(
                        _tabs.length, (index) => Text('tab $index'))))
          ],
        ),
      ),
    );
  }

  void _addTab() {
    setState(() {
      _tabs.add(_tabs.length);
    });
  }
}
```
</details>

Steps to reproduce:
1. Run the program above.
2. Add 3 tabs (final tab should be tab 2, starting from tab 0).
3. Click the tab titled 'tab 2'.

<details><summary>error log</summary>

```
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

When the exception was thrown, this was the stack
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure>
package:flutter/…/widgets/binding.dart:731
#1      WidgetsBinding._handleBuildScheduled
package:flutter/…/widgets/binding.dart:754
#2      BuildOwner.scheduleBuildFor
package:flutter/…/widgets/framework.dart:2479
#3      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4496
#4      State.setState
package:flutter/…/widgets/framework.dart:1129
#5      _AnimatedState._handleChange
package:flutter/…/widgets/transitions.dart:127
#6      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:155
#7      AnimationController.value=
package:flutter/…/animation/animation_controller.dart:365
#8      TabController._changeIndex
package:flutter/…/material/tab_controller.dart:201
#9      TabController.index=
package:flutter/…/material/tab_controller.dart:219
#10     _TabBarViewState._handleScrollNotification
package:flutter/…/material/tabs.dart:1509
#11     _NotificationElement.onNotification
package:flutter/…/widgets/notification_listener.dart:130
#12     _NotificationNode.dispatchNotification
package:flutter/…/widgets/framework.dart:3074
#13     _NotificationNode.dispatchNotification
package:flutter/…/widgets/framework.dart:3077
#14     _NotificationNode.dispatchNotification
package:flutter/…/widgets/framework.dart:3077
#15     Element.dispatchNotification
package:flutter/…/widgets/framework.dart:4376
#16     Notification.dispatch
package:flutter/…/widgets/notification_listener.dart:60
#17     ScrollActivity.dispatchScrollEndNotification
package:flutter/…/widgets/scroll_activity.dart:104
#18     ScrollPosition.didEndScroll
package:flutter/…/widgets/scroll_position.dart:907
#19     ScrollPosition.beginActivity
package:flutter/…/widgets/scroll_position.dart:876
#20     ScrollPositionWithSingleContext.beginActivity
package:flutter/…/widgets/scroll_position_with_single_context.dart:108
#21     ScrollPositionWithSingleContext.goIdle
package:flutter/…/widgets/scroll_position_with_single_context.dart:123
#22     ScrollPositionWithSingleContext.goBallistic
package:flutter/…/widgets/scroll_position_with_single_context.dart:142
#23     BallisticScrollActivity.applyNewDimensions
package:flutter/…/widgets/scroll_activity.dart:548
#24     ScrollPosition.applyNewDimensions
package:flutter/…/widgets/scroll_position.dart:623
#25     ScrollPositionWithSingleContext.applyNewDimensions
package:flutter/…/widgets/scroll_position_with_single_context.dart:98
#26     ScrollPosition.applyContentDimensions
package:flutter/…/widgets/scroll_position.dart:553
#27     _PagePosition.applyContentDimensions
package:flutter/…/widgets/page_view.dart:466
#28     RenderViewport.performLayout
package:flutter/…/rendering/viewport.dart:1485
#29     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1831
#30     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:955
#31     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:504
#32     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:867
#33     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:370
#34     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#35     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1083
#36     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:997
#37     _invoke (dart:ui/hooks.dart:148:13)
#38     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#39     _drawFrame (dart:ui/hooks.dart:115:31)
The AnimationController notifying listeners was: AnimationController#92910(▶ 2.000; paused)
════════════════════════════════════════════════════════════════════════════════
```
</details>

<details><summary>flutter doctor -v master branch</summary>

```
[√] Flutter (Channel master, 2.13.0-0.0.pre.800, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 2.13.0-0.0.pre.800 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80849adee1 (4 hours ago), 2022-04-28 10:44:06 -0700
    • Engine revision 966757c6cc
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\Cody\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.66.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.75

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
