### ISSUE TITLE
[iPadOS] Keyboard shortcut actions are disabled

### ISSUE THREAD

**Issue by trucnguyenlam** [flutter/flutter#102940]
On iPad, the copy, cut & paste icons which display at the top of the keyboard are always greyed out when interacting with a TextField, even when content is on the clipboard or text is highlighted.

These icons should be able to be used.

Steps to Reproduce
Install 'Flutter Catalog' app on an iPad (or any flutter app with a text field).
Focus on a textfield widget.
Insert and highlight some text.

**Expected results:** The copy/cut icons at the top of the onscreen keyboard should be functional.
**Actual results:** The icons are greyed out and are not functional.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`.

The issue reproduces with both `TextField` and `CupertinoTextField`, so this is likely an issue with the lower `EditableText` widget. See screen recordings below.

<details>
<summary>videos</summary>

| Native Reminders App | Flutter | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/166427347-c52de586-9600-4ce7-8ae9-0cf756f9bccf.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/166427573-ea62a1c2-b1a6-480a-a649-930fb27a9a22.mov" /> |

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.light,
      ),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Dropdown'),
      ),
      body: Column(
        children: const [
          TextField(),
          CupertinoTextField()
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (3rd generation) (mobile) • B15839B3-904C-41E2-9323-3FDF0C7C64C1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.867, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.867 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8ad88f162d (3 hours ago), 2022-05-03 01:09:11 -0400
    • Engine revision 53eeb5a1c7
    • Dart version 2.18.0 (build 2.18.0-78.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (3rd generation) (mobile) • B15839B3-904C-41E2-9323-3FDF0C7C64C1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by cyanglaz** [comment]
cc @justinmc @LongCatIsLooong

**Comment by trucnguyenlam** [comment]
@justinmc @LongCatIsLooong please let me know if there is new update on this? thanks :)

**Comment by jmagman** [comment]
@justinmc this is related to https://github.com/flutter/flutter/issues/98832 and https://github.com/flutter/engine/pull/24224, the keyboard toolbar is disabled because `canPerformAction:` for `paste:` and `cut:` are returning `NO` since scribble is enabled.

https://github.com/flutter/engine/blob/9d784a8b0f77a40829ee38e5914cc9154f241bfb/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1080-L1082

**Comment by trucnguyenlam** [comment]
@jmagman I have taken a look at the two links but I'm still confused whether this issue is already fixed or not.

**Comment by jmagman** [comment]
> I have taken a look at the two links but I'm still confused whether this issue is already fixed or not.

It's not fixed, those links were a note for @justinmc who was involved in the other PRs.

**Comment by trucnguyenlam** [comment]
Thanks for the explanation 🙂

**Comment by justinmc** [comment]
It looks like the native toolbar was showing up when canPerformAction was returning YES for cut/paste?  CC @fbcouch

I can try this out when I'm at home with a Mac/iPad.  Maybe the toolbar problem is gone and this can just be removed.

**Comment by fbcouch** [comment]
Yes, I believe you are correct about why that was added. I don't remember now whether that was an issue all the time or just when using the apple pencil, though my guess would be the former.

**Comment by trucnguyenlam** [comment]
@justinmc @fbcouch based on the comments above, I guess this should be fixable? thanks :)

**Comment by fbcouch** [comment]
So, taking another look at this...I think @justinmc is right that the native toolbar showing up doesn't seem to be an issue anymore (thought I was trying this on a branch off of 3.0.0, rather than master) – that said, I tried disabling the scribble interactions and still got those funny notifications about pasting. I wonder if that's something to do with focus and/or inserting text and it just happened that the scribble changes prevent that from showing up?

**Comment by biancashouse** [comment]
Cut, Copy Paste disabled at top left of ipados soft keyboard.

This Flutter sample shows bug: flutter create --sample="material.InputDecoration.4" textsample

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

iPad Pro 12.9, 5th Gen running iOS 16.5

**Comment by obiwan007** [comment]
Is this still worked on?
Seems to be still a problem.

**Comment by justinmc** [comment]
Any reason not to just remove that NO? https://github.com/flutter/engine/pull/50923

We'll see if the tests pass, and I'll try to test it out on a physical Apple Pencil when I can get my hands on one.
