### ISSUE TITLE
an image with opacity 0.1 does render with opacity 1 on web on phone browser

### ISSUE THREAD

**Issue by mklepaczko** [flutter/flutter#104114]
Sample code to reproduce

import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  const Test({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        image: DecorationImage(image: AssetImage(sampleImage), opacity: 0.5),
      ),
    );
  }
}

This widget renders correctly on IOS app, Android App, web browser on computer.
This widget renders with opacity 1 on web browser on Android or IOS devices

**Comment by gevoid** [comment]
+++1

**Comment by gevoid** [comment]
use like this worked for me

`decoration: new BoxDecoration(
              color: const Color(0xff7c94b6),
              image: new DecorationImage(
                fit: BoxFit.cover,
                colorFilter: new ColorFilter.mode(Colors.black.withOpacity(0.2), BlendMode.dstATop),
                image: new NetworkImage(
                  'http://www.allwhitebackground.com/images/2/2582-190x190.jpg',
                ),
              ),
            ),`

**Comment by Boma123** [comment]
Fwiw: colorFilter does not work on Safari (on iOS) and opacity does not work on Chrome. We solved this issue by detecting the browser type and conditionally switching between the two approaches - which works but is ugly and heavy. Would be great to have this ironed out in the HTML renderer.

**Comment by adventure-it** [comment]
We're also running into this problem. Thanks for the workaround, but agreed that this is only a workaround and a proper fix would be appreciated

> Fwiw: colorFilter does not work on Safari (on iOS) and opacity does not work on Chrome. We solved this issue by detecting the browser type and conditionally switching between the two approaches - which works but is ugly and heavy. Would be great to have this ironed out in the HTML renderer.

**Comment by gmae199boy** [comment]
I am also experiencing this problem now. Still not fixed?

**Comment by Ezteras** [comment]
I fixed my problem with this on a more powerpoint-like way. I've set the opacity in Apple's preview app and then uploaded that edited picture as an asset. Not the best way but it worked for my apps background picture :)

**Comment by codingiswhyicry** [comment]
Jumping in here to say this problem still exists and I'm dealing with it currently. Not replicable on CanvasKit but visible with HTML renderer on Safari / Chrome on desktop & mobile.
