### ISSUE TITLE
Flutter web - Need documentation on how to programmatically clear cache

### ISSUE THREAD

**Issue by Zelfapp** [flutter/flutter#104509]
We need to be able to force a cache refresh easily through versioning.

If we can't force a refresh through versioning, then we need documentation on how to prompt a user to "refresh for a new version" like Google Messenger or other web interfaces detect a new version. This is a serious issue, for obvious reasons. If users are not getting updated code after a build and deploy to live hosting and we have to hope that users will press their browser cache refresh button then there will be all sorts of problems. 

In typical html sites the foolproof way to force js/css updates is to change the js/css filename reference, which forces a download of the new js/css code, but I'm not seeing any info on how to do this in the Flutter web sections on flutter.dev.

## This is `web/index.html`

`var serviceWorkerVersion = null;` after running `flutter build web` does get a new version number on each build, but this is not forcing the serviceWorker to refresh `main.dart.js` where all code updates should be after a new build and deploy to live hosting. Only a browser refresh where the user is required to press the browser refresh button or clear the cache does `main.dart.js` update with new deployed code.

The `console.log('Installed new service worker.');` only runs when you do a full browser refresh. This never runs after a deploy with new code to hosting without a full browser refresh. E.g. if you deploy new code to hosting and then click around without a browser refresh it will not log a new service worker is installed.

```javascript
<script>
  var serviceWorkerVersion = null;
  var scriptLoaded = false;
  function loadMainDartJs() {
    if (scriptLoaded) {
      return;
    }
    scriptLoaded = true;
    var scriptTag = document.createElement('script');
    scriptTag.src = 'main.dart.js';
    scriptTag.type = 'application/javascript';
    document.body.append(scriptTag);
  }

  if ('serviceWorker' in navigator) {
    // Service workers are supported. Use them.
    window.addEventListener('load', function () {
      // Wait for registration to finish before dropping the <script> tag.
      // Otherwise, the browser will load the script multiple times,
      // potentially different versions.
      var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
      navigator.serviceWorker.register(serviceWorkerUrl)
        .then((reg) => {
          function waitForActivation(serviceWorker) {
            serviceWorker.addEventListener('statechange', () => {
              if (serviceWorker.state == 'activated') {
                console.log('Installed new service worker.');
                loadMainDartJs();
              }
            });
          }
          if (!reg.active && (reg.installing || reg.waiting)) {
            // No active web worker and we have installed or are installing
            // one for the first time. Simply wait for it to activate.
            waitForActivation(reg.installing || reg.waiting);
          } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
            // When the app updates the serviceWorkerVersion changes, so we
            // need to ask the service worker to update.
            console.log('New service worker available.');
            reg.update();
            waitForActivation(reg.installing);
          } else {
            // Existing service worker is still good.
            console.log('Loading app from service worker.');
            loadMainDartJs();
          }
        });

      // If service worker doesn't succeed in a reasonable amount of time,
      // fallback to plaint <script> tag.
      setTimeout(() => {
        if (!scriptLoaded) {
          console.warn(
            'Failed to load app from service worker. Falling back to plain <script> tag.',
          );
          loadMainDartJs();
        }
      }, 4000);
    });
  } else {
    // Service workers not supported. Just drop the <script> tag.
    loadMainDartJs();
  }
</script>
```

## Logs

<details>
<summary>flutter doctor -v</summary>

```dart
[✓] Flutter (Channel stable, 3.0.1, on Manjaro Linux 5.4.192-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /home/nate/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc2
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /home/nate/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Linux (desktop)                  • linux         • linux-x64      • Manjaro Linux 5.4.192-1-MANJARO
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Zelfapp** [comment]
@darshankawar unless I'm missing something, [this](https://github.com/flutter/flutter/issues/57391#issuecomment-981060296) does not run without a browser refresh.

```javascript
if (serviceWorker.state == 'activated') {
  // This does not run without a browser refresh, so newly deployed code will not be downloaded.
  console.log('Installed new service worker.');
  loadMainDartJs();
          // if there's an existing controller (previous Service Worker), show the prompt 
        // you can tweak this and delay the notification once the page is load you can show a notification and ask for a new refresh
            if (navigator.serviceWorker.controller) {
              // you have a better UI here, reloading is not a great user experince here.
              const confirmed = alert('New version of the app is available. Refresh now');
              if (confirmed == true) {
                window.location.reload();
              }
        }
}
```

[This](https://github.com/flutter/packages/pull/150/files) is interesting, but where is the documentation on flutter.dev to implement this for flutter web?

**Comment by darshankawar** [comment]
Thanks. The PR you linked above was pretty old and seems he never came back to it, so the status still stands as-is.
I am going to label this as documentation request.

**Comment by MingSern** [comment]
Any updates on this?

**Comment by kevmoo** [comment]
I'm adding this to my tracking list. We'll either update the docs or fix the framework – or both if needed! Thanks for your patience!

**Comment by yogeshPutman** [comment]
Any changes in version 3.x?

**Comment by kevmoo** [comment]
Nothing new. We're focused on some more core things.

I need to dig in through https://web.dev/learn/pwa/update/

**Comment by zs-dima** [comment]
Here is a temporary solution, but I hope this issue will be closed soon finally:
https://zs-dima.medium.com/flutter-web-new-website-version-is-available-press-update-to-refresh-81b778d6a4fd

**Comment by faFrafa** [comment]
Looking forward to have this feature for the web without much extra-coding and workarounds.

The strange thing is that sometimes our Flutter web apps stop working on Chrome after deploying a new version, even after clearing completely the Chrome's cache. 
It's quite random, and cannot reproduce it, because it stops only for few Chrome users (that have completely cleared their cache). They have to switch to another browser.

**Comment by kevmoo** [comment]
@zs-dima – great to see your demo!

Would you outline the bits needed that could help get this going? Looks like exposing the version information in the output is a good first step to enabling your work.

**Comment by zs-dima** [comment]
@kevmoo sure,
There are several ways to obtain the application version:
1. From the application scripts itself, for example using package_info_plus.
    In this case, you will get the application version related to the application java scripts currently loaded in the browser.
2. By requesting 'https://your_app.com/version.json' with http.get(uri), for example. This version.json file Flutter generates by default.
    In this case you will get the currently deployed version number, which may be different from the (1) if a new version of a web application version has been deployed.

Note that html.window.location.reload() is used 2 times to completely reload all application scripts.

Please let me know if I can clarify this further.

**Comment by kj415j45** [comment]
> 1. From the application scripts itself, for example using package_info_plus.
>    In this case, you will get the application version related to the application java scripts currently loaded in the browser.
> 2. By requesting 'https://your_app.com/version.json' with http.get(uri), for example. This version.json file Flutter generates by default.
>    In this case you will get the currently deployed version number, which may be different from the (1) if a new version of a web application version has been deployed.

@zs-dima Did not test your demo yet but I wonder if it actually works? I tried to dive into `package_info_plus`'s source before and found that they use `/version.json` as app version too.

https://github.com/fluttercommunity/plus_plugins/blob/0a894551454346745953828786a96efef83adf8e/packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart#L23-L50

It may be useless as it is not cached by service worker, so the result may always be the latest version, while the `main.dart.js` is out-dated. (Image is an app using `package_info_plus`)

![image](https://user-images.githubusercontent.com/18349191/236109167-0d6fbb2c-ea90-451a-9f24-76b3cfd8f29c.png)

My opinion is that flutter/dart compile chain should inject two constant `kBuildVersion` and `kBuildNumber` at build-time just like other constant like `kDebugMode` and `kIsWeb` so that application can get precise build state (and may request a user update).

**Comment by zs-dima** [comment]
@kj415j45, application actually works, although this solution of reloading the application twice is far from ideal. 
Another improvement can be made by using `--dart-define-from-file=keys.json`.

**Comment by RoarGronmo** [comment]
I am not sure if any has asked before; will there be any "out-of-the-box" solution for this situation? Quite frustrating to tell users to hit "Ctrl+F5" each time we publish a new version of our web-app...

Even more tricky when the users are on a tablet, pad or mobile to guide them to refresh with correct method "forcer refresh", and that either isn't done the same way on different browsers (chrome vs safari etc). 

And upon that again, when the users have "installed" the web app, how to "force" refresh the page then, to reload the "static parts" ?.

I really hope for an "out-the-box" solution in near future !! It should be prioritized !!

**Comment by AndryHTC** [comment]
> I am not sure if any has asked before; will there be any "out-of-the-box" solution for this situation? Quite frustrating to tell users to hit "Ctrl+F5" each time we publish a new version of our web-app...
> 
> Even more tricky when the users are on a tablet, pad or mobile to guide them to refresh with correct method "forcer refresh", and that either isn't done the same way on different browsers (chrome vs safari etc).
> 
> And upon that again, when the users have "installed" the web app, how to "force" refresh the page then, to reload the "static parts" ?.
> 
> I really hope for an "out-the-box" solution in near future !! It should be prioritized !!

Absolutely agree. Flutter Web is considered stable but too many minimum features are missing

**Comment by z8888-sharkfin** [comment]
Don't really understand why this issue cannot be solved soon?

**Comment by adriank** [comment]
We just need simple access to window.location.reload(). Apps shouldn't force update and auto-reload, because users could be in the middle of writing some text or filling up some form. Reload would probably reset the progress. Google cloud console does updates best and Flutter apps should provide similar UX - a button telling the user to refresh when they're ready for it.

**Comment by Martin-QPT** [comment]
Agreed - this is something that really should be in place.

**Comment by NashIlli** [comment]
+1

**Comment by diogoroos** [comment]
+1

**Comment by yogeshPutman** [comment]
+1

**Comment by felipeduarte26** [comment]
still having the same problem

**Comment by felipeduarte26** [comment]
I'm still having the same problem, I'm testing some solutions, if it works I'll try to create a PR

**Comment by josh-burton** [comment]
Has anyone found a solution or workaround?

**Comment by Martin-QPT** [comment]
Yes, I have a work around - clunky, but it works. 
I use RiverPod for State management and Firestore as my backend. What I have is a "version check" Widget that sits inside any Scaffold.  I then have a Stream Provider that watches a "version" value in Firestore. 
Because the Firebase console provides a dummy proof way of setting dateTime values, I've set the version number to be a dateTime. I then have a corresponding dateTime value baked into the source code that is deployed. 
This datetime must be after the latest version number that is sitting inside Firestore. Once the code is deployed (with a newly updated date) I then change the dateTime version value inside of Firestore. 
This change in the Firestore value forces a block of code to run. This code then checks to see if the value inside the newly deployed source code is **after** the Firestore version. This means the user has a cached version of the WebApp due to the source code app version.
If that is true then I show a dialog letting the user know that there is a new version of the app and the user should hit a "Get the new version" button that refreshes the web browser. 
Been using this for several months on a few Web Applications for Clients and it seems to work like a champ.

**Comment by alexdess** [comment]
I had the same problem in production with a customer who uses the Web PWA on a Samsung tablet. I relied on the version, but this obviously wasn't enough, as sometimes the pages didn't have the latest modifications, which was annoying.
Could you take care of this ticket?

**Comment by adriank** [comment]
It was surprisingly easy to do this. You just need a package with this code in src/refresh_web.dart:
```dart
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;

void refresh() {
  html.window.location.reload();
}
```
refresh.dart:
```dart
export 'refresh_empty.dart' if (dart.library.html) 'refresh_web.dart';
```

and refresh_empty.dart:
```dart
void refresh() {}
``` 
Runs in production without any trouble.

**Comment by huanghui1998hhh** [comment]
@adriank, yes, `refresh` is easy. But the difficulty is "how to know we need refresh" not "how to refresh"

**Comment by adriank** [comment]
@huanghui1998hhh it's even simpler than that. You get version number from package_info_plus and then use Future.delayed in an infinite while loop to check if the newer version is available on yourdomain.com/version.json.

**Comment by huanghui1998hhh** [comment]
@adriank, maybe they are always equal? `package_info_plus` [get](https://github.com/fluttercommunity/plus_plugins/blob/0511a6a0922d2e0fcda9496426c4f7bf202f8b4a/packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart#L52) the version info from `/version.json` too.

**Comment by adriank** [comment]
They are not equal. Save the version that you've read just after app started. Then get the version periodically and check if they're different.

**Comment by RoarGronmo** [comment]
> They are not equal. Save the version that you've read just after app started. Then get the version periodically and check if they're different.

I've checked this situation, and found that package_info_plus seems to pick the `/version.json` version from your apps url, not the actual version which belongs to your static parts of the web page cached in the browser. The best was if package_info_plus had an option to read that version info also, and we could use that one to compare.

In the other hand, you may need to "hard-code" the version number somehow, the best was to collect it from the `pubspec.yaml` file somehow, so it could follow the static (cached) parts.

**Comment by RoarGronmo** [comment]
Referencing to an ongoing issue at package_info_plus
https://github.com/fluttercommunity/plus_plugins/issues/2675

**Comment by kamranbekirovyz** [comment]
> It was surprisingly easy to do this. You just need a package with this code in src/refresh_web.dart:
> 
> ```dart
> // ignore: avoid_web_libraries_in_flutter
> import 'dart:html' as html;
> 
> void refresh() {
>   html.window.location.reload();
> }
> ```
> 
> refresh.dart:
> 
> ```dart
> export 'refresh_empty.dart' if (dart.library.html) 'refresh_web.dart';
> ```
> 
> and refresh_empty.dart:
> 
> ```dart
> void refresh() {}
> ```
> 
> Runs in production without any trouble.

This works like a charm! Thanks.

**Comment by rsegecin** [comment]
This is a problem specially when the site sits behind a reverse proxy that tries to keep everything on cache, but there's a workaround. Before the update of flutter I believe to version 3.22, when the flutter's index.html had "flutter.js" you could and still can add the code below that will append a version parameter to the flutter's `main.dart.js` url making it `main.dart.js?version=Release-2`, even though this new parameter won't serve any purpose to main.dart.js but it will update the file names  triggering the reverse proxy to look a new version of it. 

swap `<script src="flutter_bootstrap.js" async></script>` to `<script src="flutter.js" defer></script>` and add the code below.

```

    var scriptLoaded = false;
    
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js' + "?version=" + getRelease();
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              waitForActivation(reg.installing || reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      loadMainDartJs();
    }
``` 

Unfortunately I think its currently adding a bit of a lag for the flutter boot that wasn't a problem before. I'm looking for ways to improve it.

**Comment by AndryHTC** [comment]
The real issue isn’t checking if a new version is available—that’s the easy part. Here’s my flow:

- The deployment workflow automatically pulls the version from `pubspec.yaml` and updates a Firestore document with that version.
- In the UI, I use a stream subscription on that document to compare the web app’s version with the one in Firestore.

Setting this up in Firestore (or any reactive DB) is super straightforward.

The **real** problem? Refreshing the page isn’t enough. In my 3 years with Flutter web, refreshing aligns the pubspec version (causing the version checker to be off the game), but not always the entire web app. Sometimes, it takes 2-3 refreshes (or even a CTRL + F5) to get the latest changes.

I don't know what do you all think. This is a **huge** problem. Today, I had to do an urgent fix and instruct my customer’s HR to tell users to refresh the page multiple times until they saw the update. It’s frustrating and embarrassing. Honestly, I’ve considered leaving Flutter just because of this issue.

**Comment by RoarGronmo** [comment]
Agreement with you. I filed a suggestion https://github.com/dart-lang/sdk/issues/56017 once, and I hope they will take that into consideration.

**Comment by rsegecin** [comment]
I was having this problem that after deploying my flutter project on the web where it wouldn't update to the latest version. My problem was reverse proxy caching, you need to clear `main.dart.js` after a release for its content to be updated. If you're using cloudflare here's an example to user their API to clear flutter's cache.

```
ZONES=$(curl -X GET "https://api.cloudflare.com/client/v4/zones" -H "Authorization: Bearer $CLOUDFLARE_PURGE_TOKEN" | jq -r '.result[].id')

for ZONE in $ZONES; do
    curl -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE/purge_cache" \
         -H "Authorization: Bearer $CLOUDFLARE_PURGE_TOKEN" \
         -H "Content-Type: application/json" \
         --data '{"files":["https://[YOUR_DOMAIN]/main.dart.js"]}'
done
```

**Comment by huanghui1998hhh** [comment]
> The real issue isn’t checking if a new version is available—that’s the easy part. Here’s my flow:
> 
> * The deployment workflow automatically pulls the version from `pubspec.yaml` and updates a Firestore document with that version.
> * In the UI, I use a stream subscription on that document to compare the web app’s version with the one in Firestore.
> 
> Setting this up in Firestore (or any reactive DB) is super straightforward.
> 
> The **real** problem? Refreshing the page isn’t enough. In my 3 years with Flutter web, refreshing aligns the pubspec version (causing the version checker to be off the game), but not always the entire web app. Sometimes, it takes 2-3 refreshes (or even a CTRL + F5) to get the latest changes.
> 
> I don't know what do you all think. This is a **huge** problem. Today, I had to do an urgent fix and instruct my customer’s HR to tell users to refresh the page multiple times until they saw the update. It’s frustrating and embarrassing. Honestly, I’ve considered leaving Flutter just because of this issue.

This is desperate. 

I think the root cause is because [`ServiceWorker`](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)'s lifecycle is a **Black Box**. 

In [this artical](https://web.dev/articles/service-worker-lifecycle?hl=zh-cn), it mentions that _if no tabs use a certain ServiceWorker, this ServiceWorker will active the new version of data when next launch_. But after all the hardships I've gone through (means ensure the current `flutter_service_worker_version` in `index.html` is newest) and there is no timeout, it is still a probability to active the old version of `main.dart.js`. All I can do is check a constant value like `flutter_service_worker_version`(i hardcoded it in `main.dart.js` when compile) to tell my users "Hey, there's new version here, plz refresh _**UNTIL**_ this tips no longer appears". This is a disaster.

We just want a **robust** way to control our app's version.

**Comment by jezell** [comment]
So many people hit this problem.  --pwa-strategy none should be the default, because the default caching logic isn't good at all and is quite surprising to anyone who deploys web apps on a daily basis. PWA should be opt in, not opt out like it is with normal web apps.

**Comment by chaudharydeepanshu** [comment]
We've been running into this issue for some time. Right now, telling QA to do a triple refresh before testing a new version doesn't work. It used to work, but now moving closer to release QA understands that they can't skip a crucial testing process, leading to a **FAIL** and creating a **BLOCKER** for the web app.

The core issue is Flutter’s update behavior. Sometimes it updates fine, other times it needs a refresh, and occasionally it requires 2-3 refreshes. This unpredictability makes it difficult to determine if this behaviour is intentional or if there’s a bug in Flutter Web. What’s clear is that this isn’t what customers would expect.

Also, there’s a lack of documentation/guide/tutorial on handling updates for Flutter Web, which doesn’t help clarify update behaviour.

Here’s what I expect:
1. The app shouldn’t auto-update in any way. It should function like older versions on Android or iOS.
2. There should be a built-in way to detect updates and show an update banner, informing users of a new version and providing a one-click option to update.
3. After the update, it should function like newer versions on Android or iOS.
4. Official documentation of the above steps, if they are already possible or once they are implemented.

### Other notes:
- We’d like to request a re-evaluation of this issue’s priority. It’s impacting Flutter web deployment and blocking many developers from going to production.
- It would be helpful if other Flutter web users shared a **working** workaround that they are confident using in production.

**Comment by CodingWill0** [comment]
Just here to say I agree this should be prioritized, at least a clear documentation on the case.

**Comment by jeffscaturro-aka** [comment]
I've been using Flutter since its beta release for both personal and enterprise-level applications, but this issue has become a critical blocker with no reliable solution in sight. We've tried numerous workarounds suggested here and in other resources, but none have resolved it.

To highlight the urgency of this issue, consider a familiar scenario:

Imagine if Gmail were built in Flutter, and a client-side web app bug prevented users from opening emails, replying, or composing new ones. Suppose we identified this mission-critical bug, implemented a fix, and released it. However, every single user would then have to clear their browser cache files manually to see this fix in action. Until they do, the app remains broken.

This hypothetical emphasizes the impact on user experience and illustrates the need for prioritizing a solution, which should resonate with your key stakeholders.

**Comment by kevmoo** [comment]
@jeffscaturro-aka – are you unable to remove the flutter worker AT ALL?

We're moving to a space where we WON'T ship the worker and we'll make it possible to "bring your own".

**Comment by jeffscaturro-aka** [comment]
Hey @kevmoo,

In the latest stable version, we’re finding that shipping the bootstrap file seems necessary, which I believe is responsible for installing the service worker. Removing it with a listener doesn’t seem to resolve the user experience issue we’re facing. This is impacting some of our production admin and critical response experiences—users are stuck on older code, and they’d need to fully clear their cached files to get the latest version. This is the main issue we’re trying to solve, and I think it’s a pain point for others as well.

With the different approaches we’ve tried, we might have muddied things up or introduced conflicting ideas. Any guidance on best practices here, or clarification on whether shipping without the bootstrap file is possible, would be really helpful!

We’ve been referencing [Flutter Web Initialization](https://docs.flutter.dev/platform-integration/web/initialization), [Embedding Flutter on the Web](https://docs.flutter.dev/platform-integration/web/embedding-flutter-web), and the [Flutter Web FAQ](https://docs.flutter.dev/platform-integration/web/faq), which mentions:
> This file contains the JavaScript code needed to initialize and run your Flutter app.

Thanks in advance for any insights!

**Comment by kevmoo** [comment]
@jeffscaturro-aka – I emailed the inquiry@ email on your site. Let's chat.

**Comment by jroitgrund** [comment]
@jeffscaturro-aka `flutter build web --pwa-strategy=none`

**Comment by jeffscaturro-aka** [comment]
@kevmoo Thanks, looking forward to chatting.

@jroitgrund We have included that, but we still run into the issue with it using cached code.

**Comment by MichaelJHodge** [comment]
Hey @jeffscaturro-aka, my situation sounds very similar to yours. After trying various combinations of approaches, I’m also concerned about the possibility of conflicting solutions at this point. I'd appreciate any updates or guidance if you make progress with @kevmoo. Thank you!

**Comment by jeffscaturro-aka** [comment]
Thanks, @kevmoo, for taking the time to chat! It was truly enlightening and very helpful. For anyone else coming across this thread, including @MichaelJHodge, the Flutter team is actively working on this. Here are some resources that might help:

1. **Tracking Issue**: I recommend reading this tracking issue fully: [flutter/flutter#156910](https://github.com/flutter/flutter/issues/156910).
2. **Key Comment**: These comments offer crucial context: [#156910 (comment 1)](https://github.com/flutter/flutter/issues/156910#issuecomment-2421078622) & [#156910 (comment 2)](https://github.com/flutter/flutter/issues/156910#issuecomment-2427653575).
3. **Cleanup Guidance**: Additionally, look at their linked document for service worker cleanup: [Web Cleanup Service Worker](https://flutter.dev/go/web-cleanup-service-worker).

For those facing issues with updating or “busting” old cached assets, especially if you previously shipped without `--pwa-strategy=none`, a **post-build fix** is likely necessary to ensure users aren’t served outdated assets. The web cleanup service worker doc will shed more light into how you can also fix it now while waiting for out-of-the-box support.

**Comment by MichaelJHodge** [comment]
Thanks for all the info, @jeffscaturro-aka! I’ve been monitoring #156910 for a few weeks now, but I’ll revisit the doc to see if there’s a workable solution for the time being.

And @kevmoo, thank you as well for taking the time to clarify things for everyone. Looking forward to seeing how the Flutter team addresses this!

**Comment by jeffscaturro-aka** [comment]
@MichaelJHodge no problem! 

What we did to resolve the issue was a few steps:
- Implement a cleanup service worker that removes any existing service workers on the client side and then reloads the page. 
- Make sure that this service worker replaced the existing service worker in the `build/web` directory **post-build**.
- Ensured our CDN was using the proper cache-control headers for the relevant compiled js files. Use the proper headers that suits **_your specific cache needs_** .

Example cleanup service worker (modify as needed):
```.js
// https://flutter.dev/go/web-cleanup-service-worker
// https://vite-pwa-org.netlify.app/guide/unregister-service-worker
self.addEventListener('install', (e) => {
    self.skipWaiting();
});

self.addEventListener('activate', (e) => {
    e.waitUntil(self.clients.claim());

    e.waitUntil(self.registration.unregister());

    e.waitUntil(
        // Step 1: Delete all caches
        self.caches.keys().then((cacheNames) => {
            return Promise.all(
                cacheNames.map((cacheName) => self.caches.delete(cacheName))
            );
        })
            // Step 2: Unregister the service worker
            .then(() => self.registration.unregister())
            // Step 3: Navigate each client to refresh with the latest assets
            .then(() => self.clients.matchAll())
            .then((clients) => {
                clients.forEach((client) => {
                    if (client instanceof WindowClient) {
                        // Reload to get latest assets
                        client.navigate(client.url);
                    }
                });
            })
    );
});
```

**Comment by Lopuhan** [comment]
Hi everyone.

I've been bashing my head for 3 days against pages not loading new content after the new build and deploy.
I think I might've found a solution.

As per [official web initialization guide](https://docs.flutter.dev/platform-integration/web/initialization), you can create custom flutter_bootstrap.js and override some of the logic for builder. 

Looking at the output of the builder, take note of the output of the builder token `{{flutter_build_config}}`.

```
_flutter.buildConfig = {"engineRevision":"36335019a8eab588c3c2ea783c618d90505be233","builds":[{"compileTarget":"dart2js","renderer":"canvaskit","mainJsPath":"main.dart.js"}]};
```

In our web/flutter_bootstrap.js we can then override these config values and append version number to `main.dart.js`.

```
{{flutter_js}}
{{flutter_build_config}}

_flutter.buildConfig["builds"][0].mainJsPath += "?v=" + serviceWorkerVersion;

_flutter.loader.load({
    serviceWorkerSettings: {
        serviceWorkerVersion: serviceWorkerVersion
    }
});
```

Here's the body element in the web/index.html
```
<body>
  <script>
    var serviceWorkerVersion = {{flutter_service_worker_version}};
    {{flutter_bootstrap_js}}
  </script>
</body>
</html>
```

Now every time new build is published, all clients on refresh will download a new version of the app.

PS: I absolutely hate that I had to spend three days researching this problem. This is not okay. It should be a P1 issue for the flutter team. Who in the right mind would think that users should not be able to get the new version.

**Comment by cephyn** [comment]
> Here's the body element in the web/index.html
> 
> ```
> <body>
>   <script>
>     var serviceWorkerVersion = {{flutter_service_worker_version}};
>     {{flutter_bootstrap_js}}
>   </script>
> </body>
> </html>
> ```
> 
> Now every time a new build is published, all clients on refresh will download a new version of the app.


Thank you for researching all this - when I put this part into my web/index.html, its telling me a property assignment is expected, and I'm not sure how to resolve this, I'm very unfamiliar with these scripts. Any guidance?

**Comment by Lopuhan** [comment]
Hey @cephyn 
> Thank you for researching all this - when I put this part into my web/index.html, its telling me a property assignment is expected, and I'm not sure how to resolve this, I'm very unfamiliar with these scripts. Any guidance?

I can ignore this html error, because after the compiler run `{{flutter_service_worker_version}}` would be replaced by an actual string representing the build version.

These double curly brackets are inline replacements on the compilation step.

Just try and launch it locally. In debug on localhost your version is always `null`, but your version is always the most recent one anyways. After deployment, you could check in the inspector which js file is loaded. If it's `main.dart.js?v=random_number`, everything's working as expected. Even in local debug you should be able to see `main.dart.js?v=null`

Edit: You don't need spaces between double curly brackets.

**Comment by Katletos** [comment]
Solution in https://github.com/flutter/flutter/issues/149031#issuecomment-2623126562.
I think this issue should be resolved

**Comment by quyenvsp** [comment]
> Lopuhan
> Hi everyone.
> 
> I've been bashing my head for 3 days against pages not loading new content after the new build and deploy. I think I might've found a solution.
> 

It should be
```
{{flutter_js}}
{{flutter_build_config}}

var serviceWorkerVersion = '{{flutter_service_worker_version}}'.replaceAll('"', '');

_flutter.buildConfig.builds[0].mainJsPath += "?v=" + serviceWorkerVersion;

_flutter.loader.load({
    serviceWorkerSettings: {
        serviceWorkerVersion: serviceWorkerVersion
    }
});
```
But still wrong approach, only add `?v=...` to `mainJsPath` will lead to problem because these are other resources like custom.js, assets, images,...
When resources not available and you force load new mainJsPath it will not found.
Correct way is check `version.json` https://github.com/flutter/flutter/issues/149031#issuecomment-2631522137

**Comment by quyenvsp** [comment]
This is way show update confirm popup I used, confirm dialog will show on Next update after this code published.
`controllerchange` event only fire when service worker updated new version

```
class JsUtil {
  static Future<bool> get newWorkerInstalled async {
    final Completer<bool> completer = Completer<bool>();
    void callback(event) {
      completer.complete(true);
    }

    window.navigator.serviceWorker
        ?.addEventListener('controllerchange', callback);
    final result = await completer.future
        .timeout(Duration(seconds: 20), onTimeout: () => false);
    window.navigator.serviceWorker
        ?.removeEventListener('controllerchange', callback);
    return result;
  }

  static void reload() {
    window.navigator.serviceWorker?.ready.then(
      (registration) => registration.waiting?.postMessage('skipWaiting'),
    );
    window.location.href = '/';
  }
}
```

```
class UpgraderHandler {
  const UpgraderHandler();

  Future<void> updateIfNecessary() async {
    final shouldUpdate = await JsUtil.newWorkerInstalled;
    if (!shouldUpdate) {
      return;
    }
    await DialogUtil.confirm(
      MyApp.appContext!,
      'New version updated, refresh now?',
      onSubmit: JsUtil.reload,
    );
  }
}
```
Then use in home page or main,...
```
// Should not await here
UpgraderHandler().updateIfNecessary();
```

**Comment by shatanikmahanty** [comment]
For anyone facing issues on MacOS running the workaround script, you can use the one below it adds empty string after -i to make MacOS properly execute it.

```
#!/bin/bash

# Based on: https://github.com/doonfrs/flutter-build-web-cache-problem/blob/main/build-web.sh
# and https://www.reddit.com/r/FlutterDev/comments/1euenbd/avoiding_caching_issues_after_a_new_web_flutter/
#
# Run only ONCE after 'flutter build web' as: ./prepare.sh
# Expected folder structure:
#   build
#     web
#   prepare.sh
#   pubspec.yaml

echo "Reading version from pubspec.yaml without + sign"
version=$(grep version: pubspec.yaml | sed 's/version: //g' | sed 's/+//g')
echo "$version"

echo
echo "Calculating MD5"
md5_0=($(md5 -q build/web/main.dart.js))
echo "main.dart.js   $md5_0"

md5_1=($(md5 -q build/web/flutter.js))
echo "flutter.js   $md5_1"

md5_2=($(md5 -q build/web/index.html))
echo "index.html   $md5_2"

md5_3=($(md5 -q build/web/flutter_bootstrap.js))
echo "flutter_bootstrap.js   $md5_3"
echo

echo "Patching version in js partial urls in main.dart.js"
sed -i '' -E 's/\.createScriptURL\([[:graph:]]+\++[[:space:]]*\+[[:graph:]]/&+"?v='"$version"'"/g' build/web/main.dart.js

echo "Patching main.dart.js path in flutter.js and flutter_bootstrap.js (Flutter 3.22, 3.24)"
sed -i '' 's|\(${w}main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter.js
sed -i '' 's|\(??"main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter.js
sed -i '' 's|\(:"main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter.js

sed -i '' 's|\(${w}main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter_bootstrap.js
sed -i '' 's|\(??"main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter_bootstrap.js
sed -i '' 's|\(:"main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter_bootstrap.js

echo "Patching main.dart.js path in flutter.js (Flutter 3.19)"
sed -i '' 's|\(${l}main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter.js

echo "Patching main.dart.js path in flutter.js (Flutter 3.7, 3.10, 3.13, 3.16)"
sed -i '' 's|\(${baseUri}main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter.js

echo "Patching main.dart.js path in flutter.js (for obsolete Flutter 3.3)"
sed -i '' 's|\(= "main\.dart\.js\)|\1?v='"$version"'|g' build/web/flutter.js

echo "Patching index.html for flutter.js"
sed -i '' 's/"flutter\.js"/"flutter.js?v='"$version"'"/' build/web/index.html

echo "Patching index.html for flutter.js"
sed -i '' 's/"flutter_bootstrap\.js"/"flutter_bootstrap.js?v='"$version"'"/' build/web/index.html

echo "Patching assets loader with v= in main.dart.js"
sed -i '' "s/self\.window\.fetch(a),/self.window.fetch(a + '?v=$version'),/g" build/web/main.dart.js

# --profile unobfuscated code:
# fontFace = A.createDomFontFace(family, "url(" + t1.getAssetUrl$1(asset) + ")", descriptors);
#
echo "Patching html font loading with v= in main.dart.js"
sed -i '' 's/"url("+[[:graph:]]\++"/&?v='"$version"'/g' build/web/main.dart.js

echo "Adding v= to manifest.json"
sed -i '' 's/"manifest.json"/"manifest.json?v='"$version"'"/' build/web/index.html

echo "Adding v= to favicon.png"
sed -i '' 's/"favicon.png"/"favicon.png?v='"$version"'"/' build/web/index.html

echo
echo "Calculating new MD5"
md5_n0=($(md5 -q build/web/main.dart.js))
echo "main.dart.js   $md5_n0"

md5_n1=($(md5 -q build/web/flutter.js))
echo "flutter.js   $md5_n1"

md5_n2=($(md5 -q build/web/index.html))
echo "index.html   $md5_n2"

md5_n3=($(md5 -q build/web/flutter_bootstrap.js))
echo "flutter_bootstrap.js   $md5_n3"
echo

echo "Patching MD5 in flutter_service_worker.js"
sed -i '' 's/'"$md5_0"'/'"$md5_n0"'/' build/web/flutter_service_worker.js
sed -i '' 's/'"$md5_1"'/'"$md5_n1"'/' build/web/flutter_service_worker.js
sed -i '' 's/'"$md5_2"'/'"$md5_n2"'/' build/web/flutter_service_worker.js
sed -i '' 's/'"$md5_3"'/'"$md5_n3"'/' build/web/flutter_service_worker.js
```

**Comment by dsyrstad** [comment]
After over a year of fighting this problem, trying cache headers, cache busting, etc. to no complete success, I finally have a solution. We have an app that is deployed to the web, Android, and iOS.  This works for us, YMMV.

0. We build the web app with `flutter build web --release --pwa-strategy=none`. Note that we had to build the web app with this one release _prior_ to this solution working. This is so the flutter service worker is disabled (specifically, the service worker caching) on clients' browsers, prior to the rest of the code below executing.  

1. We have a REST service that reports the current version of the app. By using a service API, we avoid any CDN caching issues, etc. We know we will always obtain the current version of the app. This endpoint can also return different versions for web, Android, and iOS, with effective dates. This is due to delays in some mobile stores making a new version available. We also have a minimum required version and a effective date for that, but it's not directly relevant to fixing the caching issue.

2.  The client app polls the REST endpoint every 10 minutes to check if there is a version newer than the one that is currently running, and if the "version effective date" is not in the future. If there is a new version, we display a banner to the user that they can either dismiss or tap "Install".

3. When the user taps "Install", we call the `updateApp()` method below. For web, this clears any service worker caches and unregisters  the service worker. This is older code that I gleaned from the comments on this issue, but I don't think it's necessary anymore now that the flutter service worker is not caching assets anymore. Finally, it tells the browser to reload (refresh) the page. For mobile, it directs the user to the app store to install the latest version.

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';

import 'package:universal_html/html.dart' as html;
import 'package:url_launcher/url_launcher.dart';

// ...

  Future<void> updateApp() async {
    if (kIsWeb) {
      // In the browser, refresh the app after removing service workers and clearing all caches.
      // Service workers and browser caches can prevent the latest version of resources from loading.

      // Clear all caches to ensure fresh assets are loaded
      try {
        _log.info('updateApp: Clearing all caches.');

        // Get all cache names and delete them
        final cacheNames = await html.window.caches!.keys();
        _log.info('updateApp: Found ${cacheNames.length} caches to clear.');

        for (final cacheName in cacheNames) {
          await html.window.caches!.delete(cacheName);
          _log.info('updateApp: Deleted cache: $cacheName');
        }

        _log.info('updateApp: Cleared all caches.');
      } catch (e) {
        _log.warning('updateApp: Error clearing caches', e);
      }

      // Unregister all service workers
      final serviceWorker = html.window.navigator.serviceWorker;
      if (serviceWorker == null) {
        _log.info('updateApp: No service worker found.');
      } else {
        final registrations = await serviceWorker.getRegistrations();
        _log.info(
            'updateApp: Found ${registrations.length} service worker registrations.');
        for (final registration in registrations) {
          _log.info(
              'updateApp: Unregistering service worker: ${registration.scope}');
          await registration.unregister();
        }

        _log.info('updateApp: Unregistered all service workers.');
      }

      _log.info('updateApp: Reloading page to apply update.');
      html.window.location.reload();
    } else if (Platform.isAndroid) {
      await launchUrl(androidPlayStoreAppUrl);
    } else if (Platform.isIOS) {
      await launchUrl(iosAppStoreAppUrl);
    }
  }
```

We found the flutter service worker cache extremely sticky when the user already had the app open prior to a new release. We could not get updated  assets to reload unless we had the user do a hard browser refresh ("Empty Cache and Hard Reload" with Chrome DevTools open), or the user waited a long time (over 24 hours?), and then refreshed.

**Comment by zs-dima** [comment]
@Zelfapp @kevmoo please, take a look, this package solves Cache invalidation and helps easily implement "Refresh. New Version is available." for your application:
https://pub.dev/packages/sw

**Comment by phutucthinh0** [comment]
From flutter find a way to execute this js code in your web app.
This JS code works for me.
```
if ('serviceWorker' in navigator) {
  caches.keys().then(names => {
    for (let name of names) caches.delete(name);
  });

  navigator.serviceWorker.getRegistrations().then(registrations => {
    for (let reg of registrations) {
      reg.unregister();
    }
  });
}
```

**Comment by dsyrstad** [comment]
@kevmoo @DavidOrakpo  For a solution, see my comment above: https://github.com/flutter/flutter/issues/104509#issuecomment-3065396627. This solution has been working for us for a few months now.

**Comment by zs-dima** [comment]
@Zelfapp @kevmoo, please, take a look at a significantly improved solution:
https://pub.dev/packages/sw 
this package solves Cache invalidation and displays an example "Refresh. New Version is available."

**Comment by philitell** [comment]
Is there an official recommendation from flutter how to solve this?

**Comment by seba-db** [comment]
Here is my solution. Has been working great so far. The solution works by creating a version.json file that stores the last version and storing the last detected in SharedPreferences. Then polls the last version every 5 minutes. The key files (main and bootstrap) are renamed to include a hash, so every new commit has a new file, and the cache invalidates them. 

I am including here the script to run after the build, the service, provider and banner to add to your app. Took me several tries to have something that truly works. Working now on Vercel. 

Cache Buster:

```#!/bin/bash

# cache-buster.sh
# Generates version.json and renames Flutter build artifacts with hash for cache-busting
# Usage: bash scripts/cache-buster.sh build/web

set -e

BUILD_DIR="${1:-build/web}"

if [ ! -d "$BUILD_DIR" ]; then
  echo "Error: Build directory not found: $BUILD_DIR"
  exit 1
fi

# Extract git info
COMMIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
BUILD_HASH="${COMMIT_SHA:0:7}"
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create deployment ID from timestamp and hash
DEPLOYMENT_ID="flutter-$(date +%Y%m%d)-${BUILD_HASH}"

# Generate version.json
VERSION_JSON=$(cat <<EOF
{
  "deploymentId": "$DEPLOYMENT_ID",
  "buildHash": "$BUILD_HASH",
  "buildTimestamp": "$BUILD_TIMESTAMP",
  "commitSha": "$COMMIT_SHA"
}
EOF
)

# Write version.json to build output
echo "$VERSION_JSON" > "$BUILD_DIR/version.json"

echo "✓ Generated $BUILD_DIR/version.json"
echo "  Deployment ID: $DEPLOYMENT_ID"
echo "  Build Hash: $BUILD_HASH"
echo "  Timestamp: $BUILD_TIMESTAMP"

# Cache-bust main files by renaming with hash
# NOTE: Do NOT rename flutter_service_worker.js - it must stay at a known path for browser registration
echo ""
echo "🔄 Renaming artifacts for cache-busting..."

# Step 1: Update flutter_bootstrap.js to reference the hashed main.dart.js BEFORE renaming
if [ -f "$BUILD_DIR/flutter_bootstrap.js" ]; then
  MAIN_DART_NEW_NAME="main.dart-${BUILD_HASH}.js"
  sed -i.bak "s|main\.dart\.js|${MAIN_DART_NEW_NAME}|g" "$BUILD_DIR/flutter_bootstrap.js"
  rm -f "$BUILD_DIR/flutter_bootstrap.js.bak"
  echo "  ✓ Updated flutter_bootstrap.js to reference $MAIN_DART_NEW_NAME"
fi

# Step 2: Rename main.dart.js and flutter_bootstrap.js with hash
if [ -f "$BUILD_DIR/main.dart.js" ]; then
  mv "$BUILD_DIR/main.dart.js" "$BUILD_DIR/main.dart-${BUILD_HASH}.js"
  echo "  ✓ main.dart.js → main.dart-${BUILD_HASH}.js"
fi

if [ -f "$BUILD_DIR/flutter_bootstrap.js" ]; then
  mv "$BUILD_DIR/flutter_bootstrap.js" "$BUILD_DIR/flutter_bootstrap-${BUILD_HASH}.js"
  echo "  ✓ flutter_bootstrap.js → flutter_bootstrap-${BUILD_HASH}.js"
fi

# Step 3: Update index.html to reference renamed flutter_bootstrap file
if [ -f "$BUILD_DIR/index.html" ]; then
  sed -i.bak "s|flutter_bootstrap\.js|flutter_bootstrap-${BUILD_HASH}.js|g" "$BUILD_DIR/index.html"
  rm -f "$BUILD_DIR/index.html.bak"
  echo "  ✓ Updated index.html to reference flutter_bootstrap-${BUILD_HASH}.js"
fi

echo ""
echo "✅ Cache-busting complete"
```


Version Check Service:

```import 'dart:convert';
import 'package:http/http.dart' as http;

class VersionCheckService {
  final http.Client _httpClient;
  final Duration timeout;

  VersionCheckService({
    http.Client? httpClient,
    this.timeout = const Duration(seconds: 5),
  }) : _httpClient = httpClient ?? http.Client();

  /// Fetches version.json from the same origin as the Flutter web app.
  /// Returns the deploymentId if successful, null if any error occurs (silently).
  Future<String?> fetchDeploymentId(String baseUrl) async {
    try {
      // Construct URL with cache-busting query parameter (current timestamp in ms)
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final versionUrl = Uri.parse('$baseUrl/version.json?t=$timestamp');

      final response = await _httpClient
          .get(versionUrl)
          .timeout(timeout);

      if (response.statusCode != 200) {
        return null;
      }

      final json = jsonDecode(response.body) as Map<String, dynamic>;
      final deploymentId = json['deploymentId'] as String?;

      return deploymentId;
    } catch (e) {
      // Silently fail on any error (network, parsing, etc.)
      return null;
    }
  }

  /// Fetches the full version.json object.
  /// Returns null if any error occurs (silently).
  Future<VersionJson?> fetchVersion(String baseUrl) async {
    try {
      // Construct URL with cache-busting query parameter (current timestamp in ms)
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final versionUrl = Uri.parse('$baseUrl/version.json?t=$timestamp');

      final response = await _httpClient
          .get(versionUrl)
          .timeout(timeout);

      if (response.statusCode != 200) {
        return null;
      }

      final json = jsonDecode(response.body) as Map<String, dynamic>;

      return VersionJson(
        deploymentId: json['deploymentId'] as String? ?? '',
        buildHash: json['buildHash'] as String? ?? '',
        buildTimestamp: json['buildTimestamp'] as String? ?? '',
        commitSha: json['commitSha'] as String? ?? '',
      );
    } catch (e) {
      // Silently fail on any error
      return null;
    }
  }
}

class VersionJson {
  final String deploymentId;
  final String buildHash;
  final String buildTimestamp;
  final String commitSha;

  VersionJson({
    required this.deploymentId,
    required this.buildHash,
    required this.buildTimestamp,
    required this.commitSha,
  });

  @override
  String toString() {
    return 'VersionJson(deploymentId: $deploymentId, buildHash: $buildHash, buildTimestamp: $buildTimestamp, commitSha: $commitSha)';
  }
}
```

Version Check provider:

```import 'dart:async';
import 'dart:html' as html;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/version_check_service.dart';
import '../utils/logger_utils.dart';

class VersionCheckProvider extends ChangeNotifier {
  static const String _storageKey = 'app_deployment_id';

  final VersionCheckService _versionService;
  final String _baseUrl;

  Timer? _pollTimer;
  String? _storedDeploymentId;
  String? _latestServerDeploymentId;
  bool _isUpdateAvailable = false;
  bool _hasInitialized = false;

  VersionCheckProvider({
    required VersionCheckService versionService,
    required String baseUrl,
  })  : _versionService = versionService,
        _baseUrl = baseUrl;

  bool get isUpdateAvailable => _isUpdateAvailable;

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

  /// Initialize polling based on environment (prod vs dev).
  /// Should be called after app initialization is complete.
  Future<void> startPolling() async {
    // Skip version checking when running on localhost (local development)
    if (_isLocalhost()) {
      LoggerUtil.d('[VersionCheck] Skipping version check — running on localhost');
      return;
    }

    // Load stored deployment ID from SharedPreferences
    await _loadStoredDeploymentId();

    // Perform first check immediately
    _checkVersion();

    // Then set up periodic polling
    final pollInterval = _getPollInterval();
    _pollTimer = Timer.periodic(pollInterval, (_) {
      _checkVersion();
    });

    // Handle app lifecycle pausing/resuming
    _setupLifecycleListener();
  }

  /// Load the stored deployment ID from SharedPreferences
  Future<void> _loadStoredDeploymentId() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      _storedDeploymentId = prefs.getString(_storageKey);
      if (!_isProdEnvironment()) {
        LoggerUtil.d(
          '[VersionCheck] Loaded stored deploymentId: $_storedDeploymentId',
        );
      }
    } catch (e) {
      if (!_isProdEnvironment()) {
        LoggerUtil.w('[VersionCheck] Failed to load stored deploymentId: $e');
      }
    }
  }

  /// Save deployment ID to SharedPreferences
  Future<void> _saveDeploymentId(String deploymentId) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_storageKey, deploymentId);
      if (!_isProdEnvironment()) {
        LoggerUtil.d('[VersionCheck] Saved deploymentId: $deploymentId');
      }
    } catch (e) {
      if (!_isProdEnvironment()) {
        LoggerUtil.w('[VersionCheck] Failed to save deploymentId: $e');
      }
    }
  }

  /// Pause polling when app is backgrounded
  void pausePolling() {
    _pollTimer?.cancel();
    _pollTimer = null;
  }

  /// Resume polling when app is foregrounded
  void resumePolling() {
    if (_pollTimer == null) {
      startPolling();
    }
  }

  void _setupLifecycleListener() {
    WidgetsBinding.instance.addObserver(
      _AppLifecycleObserver(
        onPaused: pausePolling,
        onResumed: resumePolling,
      ),
    );
  }

  /// Fetch and compare current version against stored version
  Future<void> _checkVersion() async {
    final serverDeploymentId =
        await _versionService.fetchDeploymentId(_baseUrl);

    final isProd = _isProdEnvironment();

    if (!isProd) {
      LoggerUtil.d(
        '[VersionCheck] Fetch result: serverDeploymentId=$serverDeploymentId, '
        'storedDeploymentId=$_storedDeploymentId, '
        'hasInitialized=$_hasInitialized',
      );
    }

    if (serverDeploymentId != null) {
      // First time seeing any deployment ID: just store it, don't show banner
      if (_storedDeploymentId == null) {
        _storedDeploymentId = serverDeploymentId;
        await _saveDeploymentId(serverDeploymentId);
        _hasInitialized = true;
        _isUpdateAvailable = false;
        if (!isProd) {
          LoggerUtil.d(
            '[VersionCheck] First initialization - stored serverDeploymentId=$serverDeploymentId, '
            'banner will NOT show on first load',
          );
        }
        return;
      }

      // Subsequent checks: compare stored vs server and show banner if different
      final updateAvailable = _storedDeploymentId != serverDeploymentId;

      if (!isProd) {
        LoggerUtil.d(
          '[VersionCheck] Comparing: storedDeploymentId=$_storedDeploymentId '
          'vs serverDeploymentId=$serverDeploymentId, '
          'updateAvailable=$updateAvailable, wasAvailable=$_isUpdateAvailable',
        );
      }

      if (updateAvailable) {
        _latestServerDeploymentId = serverDeploymentId;
      }

      if (updateAvailable != _isUpdateAvailable) {
        _isUpdateAvailable = updateAvailable;
        if (!isProd) {
          LoggerUtil.i(
            '[VersionCheck] Update status changed: isUpdateAvailable=$_isUpdateAvailable',
          );
        }
        notifyListeners();
      }
    } else {
      if (!isProd) {
        LoggerUtil.w(
          '[VersionCheck] Failed to fetch deploymentId from $_baseUrl/version.json',
        );
      }
    }
    // If fetch fails (null), keep existing state and try again next interval
  }

  /// Whether the app is running on localhost (local development).
  /// When true, version checking is skipped entirely since there's no
  /// deployed version.json to compare against.
  bool _isLocalhost() {
    return _baseUrl.contains('localhost') || _baseUrl.contains('127.0.0.1');
  }

  bool _isProdEnvironment() {
    final graphqlServer = dotenv.env['GRAPHQL_SERVER'] ?? '';
    return graphqlServer.contains('.prod.') ||
        graphqlServer.contains('yourdomain.com');
  }

  /// Determine poll frequency based on environment
  Duration _getPollInterval() {
    final graphqlServer = dotenv.env['GRAPHQL_SERVER'] ?? '';
    final isProd = graphqlServer.contains('.prod.') ||
        graphqlServer.contains('yourdomain.com');

    final interval =
        isProd ? const Duration(minutes: 5) : const Duration(seconds: 30);

    if (!isProd) {
      LoggerUtil.d(
        '[VersionCheck] Poll interval: ${interval.inSeconds}s (dev mode), '
        'fetching from: $_baseUrl/version.json',
      );
    }
    return interval;
  }

  /// Save the latest server deployment ID and reload the app
  Future<void> reloadApp() async {
    if (_latestServerDeploymentId != null) {
      await _saveDeploymentId(_latestServerDeploymentId!);
    }
    html.window.location.reload();
  }
}

/// App lifecycle observer to pause/resume polling
class _AppLifecycleObserver with WidgetsBindingObserver {
  final VoidCallback onPaused;
  final VoidCallback onResumed;

  _AppLifecycleObserver({
    required this.onPaused,
    required this.onResumed,
  });

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.paused:
        onPaused();
      case AppLifecycleState.resumed:
        onResumed();
      default:
        break;
    }
  }
}
```

Banner Widget:

```import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/version_check_provider.dart';
import '../theme/text_styles.dart';

class VersionCheckBanner extends StatelessWidget {
  const VersionCheckBanner({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer<VersionCheckProvider>(
      builder: (context, provider, _) {
        if (!provider.isUpdateAvailable) {
          return const SizedBox.shrink();
        }

        return Material(
          color: const Color(0xFFFFA500), // Amber/orange
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            child: Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      BodyLarge(
                        'A new version of the app is available.',
                        color: TextStyleColor.white,
                        isBold: true,
                      ),
                      const SizedBox(height: 4),
                      BodySmall(
                        'Please reload to update.',
                        color: TextStyleColor.white,
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 12),
                ElevatedButton(
                  onPressed: () => provider.reloadApp(),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.white,
                    foregroundColor: const Color(0xFFFFA500),
                    padding:
                        const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  ),
                  child: const BodyMedium('Reload', isBold: true),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
```

**Comment by Ortes** [comment]
For anyone landing here: the underlying blocker for a reliable "new version available" prompt on web is that the running bundle can't know its own version — `package_info_plus` reads `version.json`, fetched from the server, which reflects the deployed version rather than the executing (cached) bundle.

Proposals to fix this at the source: flutter/flutter#187935 (tool injects `FLUTTER_BUILD_NAME`/`FLUTTER_BUILD_NUMBER`, like `appFlavor`) and dart-lang/sdk#38855 (+CL https://dart-review.googlesource.com/c/sdk/+/512380, `dart.package.version` for the Dart CLI). Either makes the running-vs-deployed comparison trivial; `package_info_plus` is ready to consume them (fluttercommunity/plus_plugins#3874).
