### ISSUE TITLE
Webview page not disappear when open another page run on low version Android device

### ISSUE THREAD

**Issue by bailyzheng** [flutter/flutter#104886]
https://user-images.githubusercontent.com/3355710/170821970-997da242-1d06-4ef5-ab37-b3f46bdfd74e.mp4

Android version: 5.1.1
webview_flutter: ^3.0.4

My another Android 4.4 device got the same problem and it can repeat on virtual devices too.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:untitled3/page_mhtc_color.dart';
import 'package:webview_flutter/webview_flutter.dart';

class MhtcWebPage extends StatefulWidget {
  MhtcWebPage({Key? key}): super(key: key);

  @override
  MhtcWebPageState createState() => MhtcWebPageState();
}

class MhtcWebPageState extends State<MhtcWebPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          onTap: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (ctx) {
              return MhtcColorPage();
            }));
          },
          child: Text("Title"),
        ),
      ),
      backgroundColor: Colors.transparent,
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: "https://bing.com/",
          javascriptMode: JavascriptMode.unrestricted,
        );
      }),
    );
  }
}
```

**Comment by faizanMayo786** [comment]
can you show me the complete code for better understanding?

**Comment by bailyzheng** [comment]
@faizanMayo786  OK. There are 3 files.
main.dart
```
import 'package:flutter/material.dart';
import 'package:untitled3/page_mhtc_web.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    // setState(() {
    //   // This call to setState tells the Flutter framework that something has
    //   // changed in this State, which causes it to rerun the build method below
    //   // so that the display can reflect the updated values. If we changed
    //   // _counter without calling setState(), then the build method would not be
    //   // called again, and so nothing would appear to happen.
    //   _counter++;
    // });
    Navigator.of(context).push(MaterialPageRoute(builder: (ctx) {
      return MhtcWebPage();
    }));

  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
page_mhtc_web.dart
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:untitled3/page_mhtc_color.dart';
import 'package:webview_flutter/webview_flutter.dart';

class MhtcWebPage extends StatefulWidget {
  MhtcWebPage({Key? key}): super(key: key);

  @override
  MhtcWebPageState createState() => MhtcWebPageState();
}

class MhtcWebPageState extends State<MhtcWebPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          onTap: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (ctx) {
              return MhtcColorPage();
            }));
          },
          child: Text("Title"),
        ),
      ),
      backgroundColor: Colors.transparent,
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: "https://bing.com/",
          javascriptMode: JavascriptMode.unrestricted,
        );
      }),
    );
  }
}
```

page_mhtc_color.dart
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MhtcColorPage extends StatelessWidget {
  const MhtcColorPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      body: Text("color"),
    );
  }
}

```

**Comment by faizanMayo786** [comment]
Thanks also please explain a bit what's your expected output

**Comment by bailyzheng** [comment]
I use this code to jump to the color page. It should goto the new page and the webview should disappear completely. But there is some view left where the new color page was shown under the old webview page as the video show.
```
            Navigator.of(context).push(MaterialPageRoute(builder: (ctx) {
              return MhtcColorPage();
            }));
```

**Comment by faizanMayo786** [comment]
ok I will check and let you know

**Comment by faizanMayo786** [comment]
Its working fine on my side, my device is pixel2_XL API-25,
![image](https://user-images.githubusercontent.com/89972827/170830969-857dc93d-bae8-4cfa-827d-083ee8644845.png)
![image](https://user-images.githubusercontent.com/89972827/170830996-6e056ad6-ec07-4d39-a54b-d027fed47226.png)

Butt I suggest trying you with this code  and let me know if it works
```
class MhtcWebPageState extends State<MhtcWebPage> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    if (Platform.isAndroid) WebView.platform = AndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          onTap: () {
            Navigator.of(context)
                .pushReplacement(MaterialPageRoute(builder: (ctx) {
              return MhtcColorPage();
            }));
          },
          child: Text("Title"),
        ),
      ),
      backgroundColor: Colors.transparent,
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: "https://bing.com/",
          javascriptMode: JavascriptMode.unrestricted,
        );
      }),
    );
  }
}
```

**Comment by bailyzheng** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/3355710/170831190-e8d9cb9d-670d-456a-a383-2ae26eeb1b0f.png">

@faizanMayo786  It is the same on virtual device api-22.

**Comment by faizanMayo786** [comment]
Ok let me check

**Comment by bailyzheng** [comment]
@faizanMayo786 I have pushed this code to https://github.com/bailyzheng/webviewNotDisappear

I tried set webview.platform. Not work.

**Comment by faizanMayo786** [comment]
The Error is resolved on my side using your code I have made the pull request for code in your repository.
https://user-images.githubusercontent.com/89972827/170882894-235589c3-fe4f-4db8-b47d-8c3a573adbc8.mp4

**Comment by bailyzheng** [comment]
@faizanMayo786 I can not use pushReplacement according to user experience. This is not resolved. It runs ok when the web page pop from the page stack, but it should stay in the stack according to my application scenarios.

**Comment by faizanMayo786** [comment]
Ok let me try

**Comment by faizanMayo786** [comment]
Now this works fine according to your requirements. Complete code is also pushed [here](url)
Code and Video
https://user-images.githubusercontent.com/89972827/170930046-b81a43f5-91ba-40dd-a6f3-5b09248c6e9d.mp4


```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:untitled3/page_mhtc_color.dart';
import 'package:webview_flutter/webview_flutter.dart';

class MhtcWebPage extends StatefulWidget {
  MhtcWebPage({Key? key}) : super(key: key);

  @override
  MhtcWebPageState createState() => MhtcWebPageState();
}

class MhtcWebPageState extends State<MhtcWebPage> {
  bool isVisible = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          onTap: () {
            setState(() {
              isVisible = false;
            });
            Navigator.of(context) //Done
                .push(
              MaterialPageRoute(
                builder: (context) {
                  return MhtcColorPage();
                },
              ),
            ).then((value) => setState(() {
                      isVisible = true;
                    }));
          },
          child: Text("Title"),
        ),
      ),
      backgroundColor: Colors.transparent,
      body: Builder(builder: (BuildContext context) {
        return Visibility(
          visible: isVisible,
          child: WebView(
            initialUrl: "https://bing.com/",
            javascriptMode: JavascriptMode.unrestricted,
          ),
        );
      }),
    );
  }
}

```

**Comment by huycozy** [comment]
Hi @bailyzheng,
I can reproduce this issue on the latest `stable` and `master` channels with device: Android Emulator (Nexus 5, API 22)

<details>
<summary>Demo</summary>

![Screenshot_1653898709](https://user-images.githubusercontent.com/104349824/170951490-edd9af57-9c40-408b-b92c-c76db7960780.png)

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.1 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (8 hours ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1004, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1004 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2a188eb1f6 (13 minutes ago), 2022-05-29 23:13:09 -0400
    • Engine revision 65e6a45fda
    • Dart version 2.18.0 (build 2.18.0-151.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

But this is not reproducible on Flutter `2.10.5`. This is a regression issue and has been tracking here #104686.
Please follow up on that issue, I'm closing the current one as a duplicate. 

Thanks!
