### ISSUE TITLE
Packages/plugins builders hit `fatal: couldn't find remote ref master`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#105239]
See this issue in CQ of a recipe change: https://ci.chromium.org/ui/p/flutter/builders/try/recipes-with-led/b8812495421270460417/overview

Multiple builders have been failing checking out packages/plugins repo:
```
fatal: couldn't find remote ref master
[W git.go:289] Transient error string identified in STDERR: "fatal: couldn't find remote ref master\n"
```

One example build: [Windows custom_package_tests master - packages](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/ba1e5bcddbeaf97a8002416c41a298b1a40a0af29a66a53af9890c01e7b54c33/+/build.proto?server=chromium-swarm.appspot.com)

**Comment by stuartmorgan** [comment]
Sounds like we were missing some places where CI was assuming `master`. @godofredoc do you want to un-archive `master` while we figure this out, or fix it forward?

**Comment by godofredoc** [comment]
Sure, let me do it,

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/30880 to fix forward.

**Comment by godofredoc** [comment]
Sent https://github.com/flutter/plugins/pull/5886 to revert mirroring, master_archive was renamed back to master

**Comment by keyonghan** [comment]
This has been resolved.

**Comment by godofredoc** [comment]
Wondering what was the fix?

**Comment by godofredoc** [comment]
The issue was mitigated but not fixed. Please update the checkout method to use main for plugins and packages.

**Comment by keyonghan** [comment]
Ah, seems the fix cl was not landed: https://flutter-review.googlesource.com/c/recipes/+/30880

**Comment by keyonghan** [comment]
We need to land the mirror PR: https://github.com/flutter/plugins/pull/5886 first, which then should unblock https://github.com/flutter/flutter/issues/105238, and then unblock https://flutter-review.googlesource.com/c/recipes/+/30880.

Quite some places in packages are still referencing `master` ([example](https://github.com/flutter/packages/blob/main/.ci/scripts/prepare_tool.sh#L7)), which caused https://github.com/flutter/flutter/issues/105238

**Comment by keyonghan** [comment]
This is now fixed with https://flutter-review.googlesource.com/c/recipes/+/30880 and https://github.com/flutter/packages/pull/2200
