### ISSUE TITLE
[Firefox] Composing down to a single character from multiple characters does not replace the composing text until a new event fires.

### ISSUE THREAD

**Issue by antholeole** [flutter/flutter#105244]
Composing region on web for firefox using delta model. This issue is very specific and a little hard to pin down.

If the amount of text inputted during composing is more than one character, and it composes down to one character, the text inputting does not replace until the next keypress. Here is a list of "triagable" cases:

- Type 'ni' into the composing keyboard, then select the composition. This will _not_ replace properly, as it is more than one character (ni.length == 2) and composes down into a single symbol.
- Type 'n' into the composing keyboard, then select the composition. This _will_ replace properly, as it is one character composing down into one character.
- Type 'ni ho' into the composing keyboard, then select the composition. This _will_ replace properly, as it is more than one character composing down into more than one character.

## Steps to Reproduce

1. Execute `flutter run` on the delta model sample [found here ](https://github.com/flutter/samples/tree/main/simplistic_editor)
2. Activate the Chinese composing keyboard "Pinyin - simplified" on Mac
3. Run the above examples

**Expected results:** 

Compose the characters "ni -> 霓" see that text replacement works properly, and the entirely of "ni" is replaced with the composed symbol. 

**Actual results:**

'ni' is not replaced with '霓' until a new event is fired after the composition - see that 'ni' stays in the text field along with it's composing output, 霓: something like 'ni霓'. Then when you type a new character such as n, you get '霓n'.

no MVP for this, since setting a delta keyboard up is pretty involved. It is better to just use the Delta Model example linked above and [here](https://github.com/flutter/samples/tree/main/simplistic_editor).

Examples:

working case: 
https://user-images.githubusercontent.com/48811365/171703331-59953541-5c50-4352-9394-aea94a582370.mov
See that 'n' composes to one character and fully replaces. The same is true for 'ni ho', which composes down into two characters (maybe it is another bug that 'ho' is not being displayed onto the text field) and also replaces fine.

not working case:
https://user-images.githubusercontent.com/48811365/171703788-ebb65486-61d5-4e04-b187-cfb29bed41cb.mov
See that 'ni' is not replaced by it's composed text '你‘ until a new character is placed. The same is true for longer composing text like 'song' which composes down into one symbol.

**Comment by antholeole** [comment]
@mdebbar @Renzo-Olivares 

Hopefully this issue gets fixed by https://github.com/flutter/flutter/issues/105243.

**Comment by Renzo-Olivares** [comment]
<img width="1715" alt="Screen Shot 2022-06-02 at 12 10 05 PM" src="https://user-images.githubusercontent.com/948037/171718844-abded60c-ba1c-4aca-a9e9-5a2f6906632b.png">

These are some of the logs I pulled from typing `ni hao ma`. Chrome on the left, Firefox on the right. Looks like when the text is committed on Chrome, the composing region adjusts to length of the composed text, and then another update is sent to null the composing region. On Firefox, the composing region is nulled within the same message that sends the final committed text to the framework.

**Comment by yjbanov** [comment]
@Renzo-Olivares Was this fixed by https://github.com/flutter/engine/pull/33590?

**Comment by mdebbar** [comment]
> @Renzo-Olivares Was this fixed by [flutter/engine#33590](https://github.com/flutter/engine/pull/33590)?

@yjbanov no. This issue was discovered in that PR, but it's not fixed yet.
