### ISSUE TITLE
iOS 15 crash: The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)

### ISSUE THREAD

**Issue by boluokvmd** [flutter/flutter#106404]
App crashes on iOS 15.0.0 and above

Steps to Reproduce
I do not have a clear way to reproduce this issue but i get crash reports from firebase Crashlytics here is the stack trace:
```
Fatal Exception: NSInternalInconsistencyException
The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)
```
This same crash was reported in a [previous issue](https://github.com/flutter/flutter/issues/87809) and should be resolved in the latest flutter rollout but is still happening. Also for context my app is a custom add2app scenario and this crash happens when my flutter application hands over control back to the native app

<details>
  <summary>crash logs</summary>
  
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x92d0c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  Foundation                     0x124c90 _userInfoForFileAndLine
3  Flutter                        0x28874 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x28dd4 (Missing UUID bab62788d88339b192aed18e13dece71)
5  Flutter                        0x2797c (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x55a33c (Missing UUID bab62788d88339b192aed18e13dece71)
7  Flutter                        0x424e8 (Missing UUID bab62788d88339b192aed18e13dece71)
8  libdispatch.dylib              0x63094 _dispatch_call_block_and_release
9  libdispatch.dylib              0x64094 _dispatch_client_callout
10 libdispatch.dylib              0x10d44 _dispatch_main_queue_drain
11 libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp
12 CoreFoundation                 0x4e0c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0xb5e8 __CFRunLoopRun
14 CoreFoundation                 0x1e240 CFRunLoopRunSpecific
15 GraphicsServices               0x1988 GSEventRunModal
16 UIKitCore                      0x4e541c -[UIApplication _run]
17 UIKitCore                      0x27eb88 UIApplicationMain
18 SwiftUI                        0x1f0d68 closure #1 in KitRendererCommon(_:)
19 SwiftUI                        0x13b83c runApp<A>(_:)
20 SwiftUI                        0x1211dc static App.main()
21                 0xae10 main (<compiler-generated>)
22 ???                            0x1070dc3d0 (Missing)
```

</details>

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3 21E230 darwin-arm, locale
    en-NG)
    • Flutter version 3.0.2 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at 
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart



```

</details>

<details>
  <summary>pubspec.yaml</summary>
  
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  mockito: ^5.0.7
  mask_text_input_formatter: ^2.0.0
  http: ^0.13.2
  loading_overlay: ^0.2.1
  url_launcher: ^6.0.12
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  pin_code_fields: ^7.3.0
  lottie: ^1.1.0
  sms_autofill: ^2.2.0
  connectivity_plus: ^2.0.2
  flutter_html: ^2.2.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  encrypt: ^5.0.1
  flutter_markdown: ^0.6.10
  firebase_crashlytics: ^2.8.1
  firebase_core: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1

flutter:
  uses-material-design: true


```

</details>

**Comment by huycozy** [comment]
@flutter-symbolizer-bot this force ios flutter#v3.0.2 release arm64

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x92d0c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  Foundation                     0x124c90 _userInfoForFileAndLine
3  Flutter                        0x28874 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x28dd4 (Missing UUID bab62788d88339b192aed18e13dece71)
5  Flutter                        0x2797c (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x55a33c (Missing UUID bab62788d88339b192aed18e13dece71)
7  Flutter                        0x424e8 (Missing UUID bab62788d88339b192aed18e13dece71)
8  libdispatch.dylib              0x63094 _dispatch_call_block_and_release
9  libdispatch.dylib              0x64094 _dispatch_client_callout
10 libdispatch.dylib              0x10d44 _dispatch_main_queue_drain
11 libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp
12 CoreFoundation                 0x4e0c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0xb5e8 __CFRunLoopRun
14 CoreFoundation                 0x1e240 CFRunLoopRunSpecific
15 GraphicsServices               0x1988 GSEventRunModal
16 UIKitCore                      0x4e541c -[UIApplication _run]
17 UIKitCore                      0x27eb88 UIApplicationMain
18 SwiftUI                        0x1f0d68 closure #1 in KitRendererCommon(_:)
19 SwiftUI                        0x13b83c runApp<A>(_:)
20 SwiftUI                        0x1211dc static App.main()
21                 0xae10 main (<compiler-generated>)
22 ???                            0x1070dc3d0 (Missing)
```

**Comment by huycozy** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/106404#issue-1280004304 force flutter#v3.0.2 ios release arm64

**Comment by huycozy** [comment]
@flutter-symbolizer-bot force ios arm64 flutter#v3.0.2 https://github.com/flutter/flutter/issues/106404#issue-1280004304

**Comment by huycozy** [comment]
@boluokvmd 
This issue may be a regression of #87809 as you found. 
Could you please provide full crash log?

**Comment by boluokvmd** [comment]
@huycozy Here is the full crash log below

<details>
  <summary>Full crash logs</summary>
  
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  Foundation                     0x132360 _userInfoForFileAndLine
3  Flutter                        0x28874 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x28dd4 (Missing UUID bab62788d88339b192aed18e13dece71)
5  Flutter                        0x2797c (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x55a33c (Missing UUID bab62788d88339b192aed18e13dece71)
7  Flutter                        0x424e8 (Missing UUID bab62788d88339b192aed18e13dece71)
8  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
9  libdispatch.dylib              0x3a30 _dispatch_client_callout
10 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain
11 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF
12 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0xb704 __CFRunLoopRun
14 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
15 GraphicsServices               0x1374 GSEventRunModal
16 UIKitCore                      0x514648 -[UIApplication _run]
17 UIKitCore                      0x295d90 UIApplicationMain
18 SwiftUI                        0x23ff24 closure #1 in KitRendererCommon(_:)
19 SwiftUI                        0x16de08 runApp<A>(_:)
20 SwiftUI                        0x14f0f4 static App.main()
21 MD              0xae10 main (<compiler-generated>)
22 ???                            0x106979ce4 (Missing)

Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x1f50c FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1f8ec FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x168ec FIRCLSHandler + 48
3  FirebaseCrashlytics            0x10d8c __FIRCLSExceptionRecord_block_invoke + 92
4  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
5  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  FirebaseCrashlytics            0x10534 FIRCLSExceptionRecord + 204
7  FirebaseCrashlytics            0x10834 FIRCLSExceptionRecordNSException + 548
8  FirebaseCrashlytics            0x10134 FIRCLSTerminateHandler() + 404
9  Village Medical                0x11c4280 kotlin::ThreadStateGuard::~ThreadStateGuard() + 22
10 Village Medical                0x11c4178 void (anonymous namespace)::$_0::operator()<(anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()>((anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()) + 76
11 Village Medical                0x11c412c void (anonymous namespace)::$_0::operator()<(anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()>((anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()) + 10
12 Village Medical                0x11c3ebc (anonymous namespace)::TerminateHandler::kotlinHandler() + 304
13 libc++abi.dylib                0x10f18 std::__terminate(void (*)()) + 20
14 libc++abi.dylib                0x10eb4 std::terminate() + 64
15 libobjc.A.dylib                0x2d248 objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
16 libdispatch.dylib              0x3a44 _dispatch_client_callout + 40
17 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
18 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
19 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
20 CoreFoundation                 0xb704 __CFRunLoopRun + 2532
21 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
22 GraphicsServices               0x1374 GSEventRunModal + 164
23 UIKitCore                      0x514648 -[UIApplication _run] + 1100
24 UIKitCore                      0x295d90 UIApplicationMain + 364
25 SwiftUI                        0x23ff24 closure #1 in KitRendererCommon(_:) + 164
26 SwiftUI                        0x16de08 runApp<A>(_:) + 252
27 SwiftUI                        0x14f0f4 static App.main() + 128
28 MD                0xae10 main + 64 (<compiler-generated>:64)
29 ???                            0x106979ce4 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Foundation                     0x19464 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x5ae2c -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x48e770 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6943c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19ac _pthread_start + 148
10 libsystem_pthread.dylib        0xe68 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  FirebaseCrashlytics            0x191c4 FIRCLSMachExceptionServer + 104
3  libsystem_pthread.dylib        0x19ac _pthread_start + 148
4  libsystem_pthread.dylib        0xe68 thread_start + 8

my flutter engine.1.ui
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

my flutter engine.1.raster
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

my flutter engine.1.io
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8


io.worker.4
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2e18 kevent + 8
1  Flutter                        0x4ec010 (Missing UUID bab62788d88339b192aed18e13dece71)
2  Flutter                        0x51a93c (Missing UUID bab62788d88339b192aed18e13dece71)
3  libsystem_pthread.dylib        0x19ac _pthread_start + 148
4  libsystem_pthread.dylib        0xe68 thread_start + 8

signup_engine.2.ui
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

signup_engine.2.raster
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

signup_engine.2.io
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8


com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x27823c _CFURLStorageSessionDisableCache + 60032
6  Foundation                     0x6943c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

DartWorker
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x82c4 _pthread_cond_wait + 1280
2  Flutter                        0x617764 (Missing UUID bab62788d88339b192aed18e13dece71)
3  Flutter                        0x658c14 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x61708c (Missing UUID bab62788d88339b192aed18e13dece71)
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x82c4 _pthread_cond_wait + 1280
2  Flutter                        0x617764 (Missing UUID bab62788d88339b192aed18e13dece71)
3  Flutter                        0x658c14 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x61708c (Missing UUID bab62788d88339b192aed18e13dece71)
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

com.apple.root.utility-qos
0  ???                            0x10696858c (Missing)
1  ???                            0x106966f48 (Missing)
2  ???                            0x106963d28 (Missing)
3  ???                            0x106962948 (Missing)
4  libswiftCore.dylib             0x3d15a0 swift_conformsToProtocolMaybeInstantiateSuperclasses(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, bool) + 164
5  libswiftCore.dylib             0x3d1180 swift_conformsToProtocol + 136
6  AttributeGraph                 0x6618 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 236
7  AttributeGraph                 0x820c AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 616
8  AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
9  AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
10 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
11 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
12 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
13 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
14 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
15 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
16 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
17 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
18 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
19 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
20 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
21 AttributeGraph                 0x820c AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 616
22 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
23 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
24 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
25 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
26 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
27 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
28 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
29 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
30 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
31 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
32 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
33 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
34 AttributeGraph                 0x882c AG::LayoutDescriptor::make_layout(AG::swift::metadata const*, AGComparisonMode, AG::LayoutDescriptor::HeapMode) + 596
35 AttributeGraph                 0x9bec AG::(anonymous namespace)::LayoutCache::drain_queue(void*) + 152
36 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
37 libdispatch.dylib              0x15280 _dispatch_root_queue_drain + 680
38 libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
39 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
40 libsystem_pthread.dylib        0xe5c start_wqthread + 8
```

</details>

**Comment by huycozy** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/106404#issuecomment-1164001403 force flutter#v3.0.2 ios release arm64

**Comment by huycozy** [comment]
@flutter-symbolizer-bot this force ios flutter#v3.0.1 arm64 release

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  Foundation                     0x132360 _userInfoForFileAndLine
3  Flutter                        0x28874 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x28dd4 (Missing UUID bab62788d88339b192aed18e13dece71)
5  Flutter                        0x2797c (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x55a33c (Missing UUID bab62788d88339b192aed18e13dece71)
7  Flutter                        0x424e8 (Missing UUID bab62788d88339b192aed18e13dece71)
8  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
9  libdispatch.dylib              0x3a30 _dispatch_client_callout
10 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain
11 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF
12 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0xb704 __CFRunLoopRun
14 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
15 GraphicsServices               0x1374 GSEventRunModal
16 UIKitCore                      0x514648 -[UIApplication _run]
17 UIKitCore                      0x295d90 UIApplicationMain
18 SwiftUI                        0x23ff24 closure #1 in KitRendererCommon(_:)
19 SwiftUI                        0x16de08 runApp<A>(_:)
20 SwiftUI                        0x14f0f4 static App.main()
21 MD              0xae10 main (<compiler-generated>)
22 ???                            0x106979ce4 (Missing)

Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x1f50c FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1f8ec FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x168ec FIRCLSHandler + 48
3  FirebaseCrashlytics            0x10d8c __FIRCLSExceptionRecord_block_invoke + 92
4  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
5  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  FirebaseCrashlytics            0x10534 FIRCLSExceptionRecord + 204
7  FirebaseCrashlytics            0x10834 FIRCLSExceptionRecordNSException + 548
8  FirebaseCrashlytics            0x10134 FIRCLSTerminateHandler() + 404
9  Village Medical                0x11c4280 kotlin::ThreadStateGuard::~ThreadStateGuard() + 22
10 Village Medical                0x11c4178 void (anonymous namespace)::$_0::operator()<(anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()>((anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()) + 76
11 Village Medical                0x11c412c void (anonymous namespace)::$_0::operator()<(anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()>((anonymous namespace)::TerminateHandler::queuedHandler()::'lambda'()) + 10
12 Village Medical                0x11c3ebc (anonymous namespace)::TerminateHandler::kotlinHandler() + 304
13 libc++abi.dylib                0x10f18 std::__terminate(void (*)()) + 20
14 libc++abi.dylib                0x10eb4 std::terminate() + 64
15 libobjc.A.dylib                0x2d248 objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
16 libdispatch.dylib              0x3a44 _dispatch_client_callout + 40
17 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
18 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
19 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
20 CoreFoundation                 0xb704 __CFRunLoopRun + 2532
21 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
22 GraphicsServices               0x1374 GSEventRunModal + 164
23 UIKitCore                      0x514648 -[UIApplication _run] + 1100
24 UIKitCore                      0x295d90 UIApplicationMain + 364
25 SwiftUI                        0x23ff24 closure #1 in KitRendererCommon(_:) + 164
26 SwiftUI                        0x16de08 runApp<A>(_:) + 252
27 SwiftUI                        0x14f0f4 static App.main() + 128
28 MD                0xae10 main + 64 (<compiler-generated>:64)
29 ???                            0x106979ce4 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Foundation                     0x19464 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x5ae2c -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x48e770 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6943c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19ac _pthread_start + 148
10 libsystem_pthread.dylib        0xe68 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  FirebaseCrashlytics            0x191c4 FIRCLSMachExceptionServer + 104
3  libsystem_pthread.dylib        0x19ac _pthread_start + 148
4  libsystem_pthread.dylib        0xe68 thread_start + 8

my flutter engine.1.ui
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

my flutter engine.1.raster
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

my flutter engine.1.io
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8


io.worker.4
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd28c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x3029fc (Missing UUID bab62788d88339b192aed18e13dece71)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2e18 kevent + 8
1  Flutter                        0x4ec010 (Missing UUID bab62788d88339b192aed18e13dece71)
2  Flutter                        0x51a93c (Missing UUID bab62788d88339b192aed18e13dece71)
3  libsystem_pthread.dylib        0x19ac _pthread_start + 148
4  libsystem_pthread.dylib        0xe68 thread_start + 8

signup_engine.2.ui
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

signup_engine.2.raster
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

signup_engine.2.io
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  Flutter                        0x308230 (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x307c14 (Missing UUID bab62788d88339b192aed18e13dece71)
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8


com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  CoreFoundation                 0x6d30 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb1bc __CFRunLoopRun + 1180
4  CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x27823c _CFURLStorageSessionDisableCache + 60032
6  Foundation                     0x6943c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1a74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1108 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe5c start_wqthread + 8

DartWorker
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x82c4 _pthread_cond_wait + 1280
2  Flutter                        0x617764 (Missing UUID bab62788d88339b192aed18e13dece71)
3  Flutter                        0x658c14 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x61708c (Missing UUID bab62788d88339b192aed18e13dece71)
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x82c4 _pthread_cond_wait + 1280
2  Flutter                        0x617764 (Missing UUID bab62788d88339b192aed18e13dece71)
3  Flutter                        0x658c14 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x61708c (Missing UUID bab62788d88339b192aed18e13dece71)
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

com.apple.root.utility-qos
0  ???                            0x10696858c (Missing)
1  ???                            0x106966f48 (Missing)
2  ???                            0x106963d28 (Missing)
3  ???                            0x106962948 (Missing)
4  libswiftCore.dylib             0x3d15a0 swift_conformsToProtocolMaybeInstantiateSuperclasses(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, bool) + 164
5  libswiftCore.dylib             0x3d1180 swift_conformsToProtocol + 136
6  AttributeGraph                 0x6618 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 236
7  AttributeGraph                 0x820c AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 616
8  AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
9  AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
10 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
11 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
12 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
13 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
14 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
15 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
16 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
17 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
18 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
19 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
20 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
21 AttributeGraph                 0x820c AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 616
22 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
23 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
24 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
25 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
26 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
27 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
28 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
29 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
30 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
31 AttributeGraph                 0x66e0 AG::LayoutDescriptor::Builder::visit_element(AG::swift::metadata const*, AG::swift::metadata::ref_kind, unsigned long) + 436
32 AttributeGraph                 0x9b18 AG::swift::metadata_visitor::visit_field(AG::swift::metadata const*, AG::swift::field_record const&, unsigned long) + 128
33 AttributeGraph                 0x83b8 AG::swift::metadata::visit(AG::swift::metadata_visitor&) const + 1044
34 AttributeGraph                 0x882c AG::LayoutDescriptor::make_layout(AG::swift::metadata const*, AGComparisonMode, AG::LayoutDescriptor::HeapMode) + 596
35 AttributeGraph                 0x9bec AG::(anonymous namespace)::LayoutCache::drain_queue(void*) + 152
36 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
37 libdispatch.dylib              0x15280 _dispatch_root_queue_drain + 680
38 libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
39 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
40 libsystem_pthread.dylib        0xe5c start_wqthread + 8
```

**Comment by huycozy** [comment]
Thank you! Labeling the issue for further investigation from the team.

**Comment by cyanglaz** [comment]
Looks like https://github.com/flutter/engine/pull/30580 should fix it and it doesn't seem to be rolled into stable yet. 
cc @LongCatIsLooong

**Comment by boluokvmd** [comment]
I tried recreating the crash on the latest pre (3.1.0-9.0.pre) and the latest master (3.1.0-0.0.pre.1397) roll out and it still happened, looks the PR doesn't fix this exact issue 
cc @cyanglaz  @jmagman

**Comment by cyanglaz** [comment]
Looks like the bot wasn't able to successfully symbolize the crash. Maybe the flutter version that was used wasn't correct? @boluokvmd Could you provide a crash log along with the flutter version that produced the crash log?

**Comment by jmagman** [comment]
Duplicate https://github.com/flutter/flutter/issues/109208 is symbolicated:
```
#00 0000000000028874 Flutter Flutter + 166004
                             -[FlutterTextInputPlugin hostView]
                             flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:0:3
#01 0000000000028dd4 Flutter Flutter + 167380
                             -[FlutterTextInputPlugin addToInputParentViewIfNeeded:]
                             flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2380:29
#02 00000000000287bc Flutter Flutter + 165820
                             -[FlutterTextInputPlugin getOrCreateAutofillableView:isPasswordAutofill:]
                             flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2293:5
#03 00000000000284b8 Flutter Flutter + 165048
                             -[FlutterTextInputPlugin updateAndShowAutofillViews:focusedField:isPasswordRelated:]
                             flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2250:15
#04 0000000000028224 Flutter Flutter + 164388
                             -[FlutterTextInputPlugin setTextInputClient:withConfiguration:]
                             flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:0:0
#05 00000000000278ac Flutter Flutter + 161964
                             -[FlutterTextInputPlugin handleMethodCall:result:]
                             flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2059:5
#06 000000000055a33c Flutter Flutter + 5612348
                             __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke
                             flutter/shell/platform/darwin/common/framework/Source/FlutterChannels.mm:291:5
#07 00000000000424e8 Flutter Flutter + 271592
                             ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke
                             flutter/shell/platform/darwin/ios/platform_message_handler_ios.mm:65:7
#08 0000000000006b30 NamedApp main + 56 (AppDelegate.swift:5)
#09 00000001051fc250 ??? (Missing)
```

**Comment by zackhsuan** [comment]
@jmagman @cyanglaz thanks for looking into this, any updates so far?

**Comment by daQiuQiu** [comment]
any update? still facing this issue

**Comment by boluokvmd** [comment]
Nope issue still existing till now

> any update? still facing this issue

**Comment by cyanglaz** [comment]
The potential fix was rolled in https://github.com/flutter/flutter/commit/050c1540e1bf89c94a12c8a65a96725ca9917afe, can we verify the issue is fixed on master?

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/commit/050c1540e1bf89c94a12c8a65a96725ca9917afe is available in 2.11.0-0.1.pre.
@daQiuQiu and @boluokvmd what version of Flutter are you on?

**Comment by daQiuQiu** [comment]
> 

using 3.0.2 @jmagman

**Comment by jmagman** [comment]
So https://github.com/flutter/engine/pull/30580 didn't fix this one.

**Comment by mpos-zenoti** [comment]
Any Update on this?

**Comment by LeesimEverglow** [comment]
3.0.1  also facing this issue . 

Application threw exception NSInternalInconsistencyException: The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)

**Comment by luckysmg** [comment]
I still facing this issue. The crash trigger by `hostView` method.

Here is stack trace:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)'
Last Exception Backtrace:
0   CoreFoundation                  0x000000018160504c 0x000000018156c000 + 626764
1   libobjc.A.dylib                 0x0000000199c79f54 0x0000000199c64000 + 89940
2   Foundation                      0x0000000182ebe6cc 0x0000000182d8e000 + 1246924
3   Flutter                         0x000000010d1d6208 -[FlutterTextInputPlugin hostView] FlutterTextInputPlugin.mm:2390 (in Flutter)
4   Flutter                         0x000000010d1d6768 -[FlutterTextInputPlugin addToInputParentViewIfNeeded:] FlutterTextInputPlugin.mm:2467 (in Flutter)
5   Flutter                         0x000000010d1d6150 -[FlutterTextInputPlugin getOrCreateAutofillableView:isPasswordAutofill:] FlutterTextInputPlugin.mm:2383 (in Flutter)
6   Flutter                         0x000000010d1d5e48 -[FlutterTextInputPlugin updateAndShowAutofillViews:focusedField:isPasswordRelated:] FlutterTextInputPlugin.mm:2337 (in Flutter)
7   Flutter                         0x000000010d1d5bb8 -[FlutterTextInputPlugin setTextInputClient:withConfiguration:] FlutterTextInputPlugin.mm:2278 (in Flutter)
8   Flutter                         0x000000010d1d51a8 -[FlutterTextInputPlugin handleMethodCall:result:] FlutterTextInputPlugin.mm:2132 (in Flutter)
```

**Comment by luckysmg** [comment]
Fixed by 
- https://github.com/flutter/engine/pull/39768
