### ISSUE TITLE
After upgrading to flutter 3.0 AndroidView is always on top of other widgets on Android

### ISSUE THREAD

**Issue by usamashafiqs** [flutter/flutter#106458]
## Steps to Reproduce

1.  Current flutter v3.0.3
2. Work fine with flutter v2.10.5

**Expected results:** 
<details>
<summary>before</summary>
<img width="400" src="https://user-images.githubusercontent.com/18592683/175222929-6804fd27-9568-4a6c-bd2e-57b908f1963a.png">

</details>

**Actual results:** 
<details>
<summary>after</summary>
<img width="400" src="https://user-images.githubusercontent.com/18592683/175223022-1b3938f6-39ca-40d0-b8c0-3b7151212be1.png">

</details>

<details>
<summary>Code sample</summary>

```
Scaffold(
      body: Stack(
        children: <Widget>[
         AndroidView(),
          if (_anchors.isNotEmpty)
            Column(
              mainAxisAlignment: MainAxisAlignment.end,
              children: <Widget>[
                if (_isPannedNode)
                  Slider(
                    min: 0.2,
                    max: 5.0,
                    value: 0.3,
                    activeColor: primaryColorDark,
                    inactiveColor: primaryColorDark,
                    onChanged: (value) => _onChanged,
                  ),
                Container(
                  alignment: Alignment.center,
                  padding: EdgeInsets.only(
                    top: _isPannedNode ? 0.0 : 8.0,
                    bottom: 8.0,
                  ),
                  child: ElevatedButton(
                    style: ButtonStyle(
                      backgroundColor:
                          MaterialStateProperty.all(secondaryColor),
                    ),
                    onPressed: () => _onRemoveEverything(),
                    child: Text(
                      'Remove',
                      style: TextStyle(color: primaryColor),
                    ),
                  ),
                ),
              ],
            ),
        ],
      ),
    );
```

</details>

**Comment by huycozy** [comment]
@usamashafiqs 
There's an issue addressing the case you described #103630 that has been fixed recently and the patch fixes is available on master channel.

Please try the issue again on the latest master channel and confirm if this issue is fixed on your side.

**Comment by sirmamedical** [comment]
I can confirm too that this is still valid for the latest master pull at the moment of writing this comment. All AndroidViews are stacked at position 0,0 on top of all flutter widgets, completely detached from the flutter tree.

**Comment by usamashafiqs** [comment]
> @usamashafiqs There's an issue addressing the case you described #103630 that has been fixed recently and the patch fixes is available on master channel.
> 
> Please try the issue again on the latest master channel and confirm if this issue is fixed on your side.

I try the master channel the issue is still there

**Comment by usamashafiqs** [comment]
I try the  master Flutter v3.1.0-0.0.pre.1372 and the issue is fixed there. Thank you !

**Comment by phanbaohuy96** [comment]
this issue is still not fixed on my side. 
I use Flutter v3.1.0-0.0.pre.1376 
![image](https://user-images.githubusercontent.com/45892907/175861956-8784e68e-97d7-405f-ac11-c4798e113c9d.png)

**Comment by phanbaohuy96** [comment]
any update for this, I tried to use Flutter v3.1.0-0.0.pre.1493 but this issue is still there.
