### ISSUE TITLE
Website has unusual truncations when resetted from certain zoom levels

### ISSUE THREAD

**Issue by frostytmtm** [flutter/flutter#106730]
Used flutter framework to implement web application and found out that there will be unusual truncations when resetted from certain zoom levels.

Test Steps:
1. Zoom in/out page to different zoom levels
2. Click on reset button

Expected Results:
1. Page should adjust as accordingly to zoom levels.
2. No truncation of any UI should be seen.

Actual Result:
1. Page should adjust as accordingly to zoom levels. ✓
2. No truncation of any UI should be seen. ✕ (Issue is seen here, at certain zoom in/out levels there are weird truncations to the top bar, some will align the page diagonally, some even made the content disappear)

**Comment by exaby73** [comment]
Hi @frostytmtm, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by exaby73** [comment]
I can reproduce this issue with the [Gallery app](https://gallery.flutter.dev/#/)

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/176165724-932a9ee0-a0de-4342-b68a-61d4b09b5920.mov

</details>

**Comment by exaby73** [comment]
I cannot reproduce this issue on master. Since it's fixed in master, I am closing this issue. Thanks for filing it :)

**Comment by frostytmtm** [comment]
I've tried again, it's resetting the zoom, cause in the video that you've done, refreshing will fix the issue, but if i hit the reset button in the zoom field, the problem is still seen. I've recorded my findings :)
Uploading Screen Recording 2022-07-04 at 11.21.36 AM.mov…

**Comment by frostytmtm** [comment]
https://user-images.githubusercontent.com/108334975/177082683-4c38d0ab-807d-4113-88dc-cbbe3b84ded0.mov

**Comment by exaby73** [comment]
I can see it now. Though it only occurs when I reset from 50% or lower. You can see in the video below.

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/177096671-6bd39d74-6b5a-458c-9b98-65b861cbab8c.mov

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.4 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1493, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1493 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 66c9d44bc0 (5 minutes ago), 2022-07-04 02:34:04 -0400
    • Engine revision 90376212bf
    • Dart version 2.18.0 (build 2.18.0-250.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by yjbanov** [comment]
This is probably going to be fixed by https://github.com/flutter/engine/pull/33695/files

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/77084
