### ISSUE TITLE
Error in joinMulticast when running under Windows 7/10

### ISSUE THREAD

**Issue by andyduke** [flutter/flutter#106881]
When using multicast_dns on Windows 7/10, the error "_OS Error: An invalid argument was supplied._" occurs.
This happens in the `joinMulticast` call inside the `start` method of the `MDnsClient` class.

This problem can be avoided by not using `joinMulticast` on Windows, like so:
```
Future<void> start({
    InternetAddress? listenAddress,
    NetworkInterfacesFactory? interfacesFactory,
    int mDnsPort = mDnsPort,
    InternetAddress? mDnsAddress,
  }) async {
  // ... skipped

  // Array to collect addresses
  final List<InternetAddress> addresses = [];

  for (final NetworkInterface interface in interfaces) {
    // ... skipped

    // Join multicast on this interface.
    if (!Platform.isWindows) {
      incoming.joinMulticast(_mDnsAddress!, interface);
    } else {
      // Collect addresses
      addresses
        ..add(_mDnsAddress!)
        ..addAll(interface.addresses);
    }
  }

  if (Platform.isWindows) {
    // Convert addresses to Uint8List
    final Uint8List rawAddresses =
        Uint8List.fromList(addresses.map<List<int>>((a) => a.rawAddress).reduce((all, a) => all + a));

    // Set addresses for datagram socket
    incoming.setRawOption(RawSocketOption(RawSocketOption.levelIPv4, 12, rawAddresses));
  }

  incoming.listen((RawSocketEvent event) => _handleIncoming(event, incoming));
  _started = true;
  _starting = false;
}
```

**Comment by maheshmnj** [comment]
Hi @andyduke, Thanks for filing the issue. Can you please share a minimal and complete sample code along with the steps to reproduce the issue? Also please share the output of `flutter doctor -v`.

**Comment by andyduke** [comment]
This also happens with examples from the package: https://pub.dev/packages/multicast_dns/example

<details>
  <summary>flutter doctor output</summary>

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.17134.1], locale ru-RU)
    • Flutter version 3.0.1 at D:\Flutter2Live\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Flutter2Live\android-sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = D:\Flutter2Live\android-sdk
    • ANDROID_SDK_ROOT = D:\Flutter2Live\android-sdk
    • Java binary at: D:\Flutter2Live\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = D:\Chromiums\89\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
                                                                                                                                                                         Scanning for devices is taking a long time...[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17134.1]
    • Chrome (web)      • chrome  • web-javascript • unknown
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by andyduke** [comment]
This is fixed by specifying a custom factory in the `rawDatagramSocketFactory` parameter when creating the `MDnsClient` object, like this:
```dart
final MDnsClient client = MDnsClient(
  rawDatagramSocketFactory: (dynamic host, int port,
      {bool reuseAddress = true, bool reusePort = true, int ttl = 10000}) {
    return RawDatagramSocket.bind(host, port,
        reuseAddress: true, reusePort: Platform.isWindows ? false : reusePort, ttl: ttl);
  },
);
```

**Comment by maheshmnj** [comment]
Thanks for the info @andyduke, I am still seeing socket exception (slightly different error from previous triage), Probably this could be related to my network or some network permission for windows? Labeling this issue for further investigation from the team.

<details>
<summary>code sample</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Example script to illustrate how to use the mdns package to discover the port
// of a Dart observatory over mDNS.

import 'dart:io';

import 'package:multicast_dns/multicast_dns.dart';

Future<void> main() async {
  // Parse the command line arguments.

  const String name = '_dartobservatory._tcp.local';
  final MDnsClient client = MDnsClient(
  rawDatagramSocketFactory: (dynamic host, int port,
      {bool reuseAddress = true, bool reusePort = true, int ttl = 10000}) {
    return RawDatagramSocket.bind(host, port,
        reuseAddress: true, reusePort: Platform.isWindows ? false : reusePort, ttl: ttl);
  },
);
  // Start the client with default options.
  await client.start();

  // Get the PTR record for the service.
  await for (final PtrResourceRecord ptr in client
      .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
    // Use the domainName from the PTR record to get the SRV record,
    // which will have the port and local hostname.
    // Note that duplicate messages may come through, especially if any
    // other mDNS queries are running elsewhere on the machine.
    await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(
        ResourceRecordQuery.service(ptr.domainName))) {
      // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
      final String bundleId =
          ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
      print('Dart observatory instance found at '
          '${srv.target}:${srv.port} for "$bundleId".');
    }
  }
  client.stop();

  print('Done.');
}
```
</details>  

<details>
<summary>logs</summary>

```
Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:51117/CsolSjcnb5w=/ws
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: The requested address is not valid in its context.
, errno = 10049), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start
<asynchronous suspension>
#2      main
<asynchronous suspension>

```
</details>

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 3.0.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (8 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

C:\Users\mahesh>
```
</details>

**Comment by andyduke** [comment]
You can try skipping some network interfaces by adding the `interfacesFactory` parameter to `start`:

```dart

await client.start(
      interfacesFactory: (type) async {
        final interfaces = await NetworkInterface.list(
          includeLinkLocal: false,
          type: type,
          includeLoopback: false,
        );
        return interfaces;
      },
    );

```

**Comment by andyduke** [comment]
Hello, any progress on this issue?

**Comment by Alivon** [comment]
### Based on the above reflection, the code that can be run
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Example script to illustrate how to use the mdns package to discover the port
// of a Dart observatory over mDNS.

import 'dart:io';

import 'package:multicast_dns/multicast_dns.dart';

Future<void> main() async {
  // Parse the command line arguments.

  const String name = '_dartobservatory._tcp.local';
  final MDnsClient client = MDnsClient(
    rawDatagramSocketFactory: (dynamic host, int port,
        {bool reuseAddress = true, bool reusePort = true, int ttl = 10000}) {
      return RawDatagramSocket.bind(host, port,
          reuseAddress: true,
          reusePort: Platform.isWindows ? false : reusePort,
          ttl: ttl);
    },
  );
  // Start the client with default options.
  await client.start(
    interfacesFactory: (type) async {
      final interfaces = await NetworkInterface.list(
        includeLinkLocal: false,
        type: type,
        includeLoopback: false,
      );
      return interfaces;
    },
  );

  // Get the PTR record for the service.
  await for (final PtrResourceRecord ptr in client
      .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
    // Use the domainName from the PTR record to get the SRV record,
    // which will have the port and local hostname.
    // Note that duplicate messages may come through, especially if any
    // other mDNS queries are running elsewhere on the machine.
    await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(
        ResourceRecordQuery.service(ptr.domainName))) {
      // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
      final String bundleId =
          ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
      print('Dart observatory instance found at '
          '${srv.target}:${srv.port} for "$bundleId".');
    }
  }
  client.stop();

  print('Done.');
}
