### ISSUE TITLE
PlatformView(Hybrid-composition) has black background when being loaded 

### ISSUE THREAD

**Issue by tareq3** [flutter/flutter#107124]
### I was trying to embeded some EditText(Android) and TextView(Android) into my flutter plugin/app. But I noticed when it is being loaded up or changing activity/pages, It renders over a black background container.  It occurs when there are multiple platform widget on a single page. I believe it occurs because PlatformView/hybrid-composition is heavy a lot and the framework needs some time to render it up. 

But instead of black background, shouldn't it be transparent? It causes some pretty ugly effect when the screen is being loaded.

 I have tested it on Samsung A30 smartphone and on emelator. The problem occurs in debug and release both versions.
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on go next  
3. you will see black background container behind platform widgets 

**Expected results:**  Instead of black background container, It should be transparent.

**Actual results:**  I see black background container behind Platform widgets.

<details>
<summary>Code sample</summary>

[github repo](https://github.com/tareq3/hybrid_composition_ex.git)

</details>

<details>
  <summary>Logs</summary>

```


ts/flutter-apk/app.apk AndroidManifest.xml
[  +14 ms] Exit code 0 from:
/Users/tareq/Library/Android/sdk/build-tools/32.1.0-rc1/aapt dump xmltree
/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/build/app/outpu
ts/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.mti.hybrid_composition_ex_example" (Raw:
               "com.mti.hybrid_composition_ex_example")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="hybrid_composition_ex_example"
                 (Raw: "hybrid_composition_ex_example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw:
                 "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.Core
                 ComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.mti.hybrid_composition_ex_examp
                   le.MainActivity" (Raw:
                   "com.mti.hybrid_composition_ex_example.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type
                   0x12)0xffffffff
                   E: meta-data (line=38)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.Norm
                     alTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHE
                       R" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions"
                   (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw:
                   "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +3 ms] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell -x logcat -v time -t 1
[   +8 ms] <- compile package:hybrid_composition_ex_example/main.dart
[  +59 ms] --------- beginning of main
           07-06 00:01:00.048 D/EGL_emulation(  749): app_time_stats:
           avg=60001.29ms min=60001.29ms max=60001.29ms count=1
[   +6 ms] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb
version
[  +11 ms] Android Debug Bridge version 1.0.41
           Version 33.0.2-8557947
           Installed as /Users/tareq/Library/Android/sdk/platform-tools/adb
[   +1 ms] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb
start-server
[  +12 ms] Building APK
[   +6 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] Using gradle from
/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/android/gradlew
.
[  +42 ms] executing: /usr/bin/plutil -convert xml1 -o - /Applications/Android
Studio.app/Contents/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o -
/Applications/Android Studio.app/Contents/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
           "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>English</string>
           	<key>CFBundleDocumentTypes</key>
           	<array>
           		<dict>
           			<key>CFBundleTypeExtensions</key>
           			<array>
           				<string>ipr</string>
           			</array>
           			<key>CFBundleTypeIconFile</key>
           			<string>studio.icns</string>
           			<key>CFBundleTypeName</key>
           			<string>Android Studio Project File</string>
           			<key>CFBundleTypeRole</key>
           			<string>Editor</string>
           		</dict>
           		<dict>
           			<key>CFBundleTypeExtensions</key>
           			<array>
           				<string>*</string>
           			</array>
           			<key>CFBundleTypeName</key>
           			<string>All documents</string>
           			<key>CFBundleTypeOSTypes</key>
           			<array>
           				<string>****</string>
           			</array>
           			<key>CFBundleTypeRole</key>
           			<string>Editor</string>
           			<key>LSTypeIsPackage</key>
           			<false/>
           		</dict>
           	</array>
           	<key>CFBundleExecutable</key>
           	<string>studio</string>
           	<key>CFBundleGetInfoString</key>
           	<string>Android Studio 2021.2, build AI-212.5712.43.2112.8609683.
           	Copyright JetBrains s.r.o., (c) 2000-2022</string>
           	<key>CFBundleIconFile</key>
           	<string>studio.icns</string>
           	<key>CFBundleIdentifier</key>
           	<string>com.google.android.studio</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>Android Studio</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
           	<string>2021.2</string>
           	<key>CFBundleSignature</key>
           	<string>????</string>
           	<key>CFBundleURLTypes</key>
           	<array>
           		<dict>
           			<key>CFBundleTypeRole</key>
           			<string>Editor</string>
           			<key>CFBundleURLName</key>
           			<string>Stacktrace</string>
           			<key>CFBundleURLSchemes</key>
           			<array>
           				<string>idea</string>
           			</array>
           		</dict>
           	</array>
           	<key>CFBundleVersion</key>
           	<string>AI-212.5712.43.2112.8609683</string>
           	<key>JVMOptions</key>
           	<dict>
           		<key>ClassPath</key>
           		<string>$APP_PACKAGE/Contents/lib/bootstrap.jar:$APP_PACKAGE/Conten
           		ts/lib/util.jar:$APP_PACKAGE/Contents/lib/jna.jar</string>
           		<key>JVMVersion</key>
           		<string>1.8*,1.8+</string>
           		<key>MainClass</key>
           		<string>com.intellij.idea.Main</string>
           		<key>Properties</key>
           		<dict>
           			<key>idea.executable</key>
           			<string>studio</string>
           			<key>idea.home.path</key>
           			<string>$APP_PACKAGE/Contents</string>
           			<key>idea.jre.check</key>
           			<string>true</string>
           			<key>idea.paths.selector</key>
           			<string>AndroidStudio2021.2</string>
           			<key>idea.platform.prefix</key>
           			<string>AndroidStudio</string>
           			<key>idea.vendor.name</key>
           			<string>Google</string>
           			<key>java.system.class.loader</key>
           			<string>com.intellij.util.lang.PathClassLoader</string>
           			<key>splash</key>
           			<string>true</string>
           		</dict>
           	</dict>
           	<key>LSApplicationCategoryType</key>
           	<string>public.app-category.developer-tools</string>
           	<key>LSArchitecturePriority</key>
           	<array>
           		<string>arm64</string>
           		<string>x86_64</string>
           	</array>
           	<key>LSMinimumSystemVersion</key>
           	<string>10.8</string>
           	<key>LSRequiresNativeExecution</key>
           	<string>YES</string>
           	<key>NSBluetoothAlwaysUsageDescription</key>
           	<string>An application in Android Studio requests access to
           	Bluetooth.</string>
           	<key>NSCameraUsageDescription</key>
           	<string>An application in Android Studio requests access to the
           	device's camera.</string>
           	<key>NSDesktopFolderUsageDescription</key>
           	<string>An application in Android Studio requests access to the
           	user's Desktop folder.</string>
           	<key>NSDocumentsFolderUsageDescription</key>
           	<string>An application in Android Studio requests access to the
           	user's Documents folder.</string>
           	<key>NSDownloadsFolderUsageDescription</key>
           	<string>An application in Android Studio requests access to the
           	user's Downloads folder.</string>
           	<key>NSHighResolutionCapable</key>
           	<true/>
           	<key>NSLocationUsageDescription</key>
           	<string>An application in Android Studio requests access to the
           	user's location information.</string>
           	<key>NSMicrophoneUsageDescription</key>
           	<string>An application in Android Studio requests access to the
           	device's microphone.</string>
           	<key>NSNetworkVolumesUsageDescription</key>
           	<string>An application in Android Studio requests access to files on
           	a network volume.</string>
           	<key>NSRemovableVolumesUsageDescription</key>
           	<string>An application in Android Studio requests access to files on
           	a removable volume.</string>
           	<key>NSSupportsAutomaticGraphicsSwitching</key>
           	<true/>
           </dict>
           </plist>
[   +7 ms] executing: /Applications/Android
Studio.app/Contents/jre/Contents/Home/bin/java -version
[  +55 ms] Exit code 0 from: /Applications/Android
Studio.app/Contents/jre/Contents/Home/bin/java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+0-b1504.28-7817840, mixed
           mode)
[   +1 ms] executing:
[/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/android/]
/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/android/gradlew
-Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/lib/ma
in.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +731 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[+5996 ms] > Task :app:compileFlutterBuildDebug
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :hybrid_composition_ex:preBuild UP-TO-DATE
[        ] > Task :hybrid_composition_ex:preDebugBuild UP-TO-DATE
[        ] > Task :hybrid_composition_ex:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :hybrid_composition_ex:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :hybrid_composition_ex:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :hybrid_composition_ex:mergeDebugShaders UP-TO-DATE
[        ] > Task :hybrid_composition_ex:compileDebugShaders NO-SOURCE
[        ] > Task :hybrid_composition_ex:generateDebugAssets UP-TO-DATE
[        ] > Task :hybrid_composition_ex:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +300 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :hybrid_composition_ex:compileDebugRenderscript NO-SOURCE
[        ] > Task :hybrid_composition_ex:generateDebugResValues UP-TO-DATE
[        ] > Task :hybrid_composition_ex:generateDebugResources UP-TO-DATE
[        ] > Task :hybrid_composition_ex:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :hybrid_composition_ex:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :hybrid_composition_ex:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :hybrid_composition_ex:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :hybrid_composition_ex:parseDebugLocalResources UP-TO-DATE
[        ] > Task :hybrid_composition_ex:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :hybrid_composition_ex:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :hybrid_composition_ex:compileDebugKotlin UP-TO-DATE
[        ] > Task :hybrid_composition_ex:javaPreCompileDebug UP-TO-DATE
[        ] > Task :hybrid_composition_ex:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :hybrid_composition_ex:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[  +98 ms] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :hybrid_composition_ex:processDebugJavaRes NO-SOURCE
[        ] > Task :hybrid_composition_ex:bundleLibResDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :hybrid_composition_ex:bundleLibRuntimeToJarDebug UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :hybrid_composition_ex:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :hybrid_composition_ex:mergeDebugNativeLibs NO-SOURCE
[        ] > Task :hybrid_composition_ex:copyDebugJniLibsProjectOnly UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:writeDebugAppMetadata UP-TO-DATE
[        ] > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
[        ] > Task :hybrid_composition_ex:stripDebugDebugSymbols NO-SOURCE
[        ] > Task :hybrid_composition_ex:copyDebugJniLibsProjectAndLocalJars
UP-TO-DATE
[  +93 ms] > Task :hybrid_composition_ex:extractDebugAnnotations UP-TO-DATE
[        ] > Task :hybrid_composition_ex:mergeDebugGeneratedProguardFiles
UP-TO-DATE
[        ] > Task :hybrid_composition_ex:mergeDebugConsumerProguardFiles
UP-TO-DATE
[        ] > Task :hybrid_composition_ex:prepareDebugArtProfile UP-TO-DATE
[        ] > Task :hybrid_composition_ex:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :hybrid_composition_ex:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :hybrid_composition_ex:syncDebugLibJars UP-TO-DATE
[        ] > Task :hybrid_composition_ex:bundleDebugAar UP-TO-DATE
[        ] > Task :hybrid_composition_ex:assembleDebug UP-TO-DATE
[ +295 ms] > Task :app:compressDebugAssets
[        ] Execution optimizations have been disabled for task
':app:compressDebugAssets' to ensure correctness due to the following reasons:
[        ]   - Gradle detected a problem with the following location:
'/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/build/app/inte
rmediates/assets/debug/mergeDebugAssets'. Reason: Task
':app:compressDebugAssets' uses this output of task
':app:copyFlutterAssetsDebug' without declaring an explicit or implicit
dependency. This can lead to incorrect results being produced, depending on what
order the tasks are executed. Please refer to
https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependen
cy for more details about this problem.
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
[  +54 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it
incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation
warnings and determine if they come from your own scripts or plugins.
[        ] See
https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_li
ne_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of
work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 7s
[        ] 63 actionable tasks: 6 executed, 57 up-to-date
[ +386 ms] Running Gradle task 'assembleDebug'... (completed in 8.1s)
[  +32 ms] calculateSha: LocalDirectory:
'/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/build/app/outp
uts/flutter-apk'/app.apk
[ +461 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing:
/Users/tareq/Library/Android/sdk/build-tools/32.1.0-rc1/aapt dump xmltree
/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/build/app/outpu
ts/flutter-apk/app.apk AndroidManifest.xml
[  +10 ms] Exit code 0 from:
/Users/tareq/Library/Android/sdk/build-tools/32.1.0-rc1/aapt dump xmltree
/Users/tareq/code/flutter-projects/hybrid_composition_ex/example/build/app/outpu
ts/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.mti.hybrid_composition_ex_example" (Raw:
               "com.mti.hybrid_composition_ex_example")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="hybrid_composition_ex_example"
                 (Raw: "hybrid_composition_ex_example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw:
                 "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.Core
                 ComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.mti.hybrid_composition_ex_examp
                   le.MainActivity" (Raw:
                   "com.mti.hybrid_composition_ex_example.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type
                   0x12)0xffffffff
                   E: meta-data (line=38)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.Norm
                     alTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHE
                       R" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions"
                   (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw:
                   "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +2 ms] Stopping app 'app.apk' on sdk gphone64 arm64.
[        ] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell am force-stop com.mti.hybrid_composition_ex_example
[  +57 ms] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell pm list packages com.mti.hybrid_composition_ex_example
[  +40 ms] package:com.mti.hybrid_composition_ex_example
[        ] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell cat
/data/local/tmp/sky.com.mti.hybrid_composition_ex_example.sha1
[  +19 ms] 4e063033b7ac2c05fd0ae0055502fe2319547178
[        ] Latest build already installed.
[        ] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell -x logcat -v time -t 1
[  +39 ms] --------- beginning of main
           07-06 00:01:35.432 I/GoogleInputMethodService( 1415):
           GoogleInputMethodService.onFinishInput():3269
[   +8 ms] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true
com.mti.hybrid_composition_ex_example/com.mti.hybrid_composition_ex_example.Main
Activity
[  +33 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.mti.hybrid_composition_ex_example/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +231 ms] Observatory URL on device: http://127.0.0.1:45179/oG1qa1fMl7c=/
[        ] executing: /Users/tareq/Library/Android/sdk/platform-tools/adb -s
emulator-5554 forward tcp:0 tcp:45179
[  +10 ms] 58968
[        ] Forwarded host port 58968 to device port 45179 for Observatory
[   +3 ms] Caching compiled dill
[  +13 ms] Connecting to service protocol: http://127.0.0.1:58968/oG1qa1fMl7c=/
[  +89 ms] Launching a Dart Developer Service (DDS) instance at
http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:58968/oG1qa1fMl7c=/.
[  +67 ms] DDS is listening at http://127.0.0.1:58971/g4-mRdT_QRU=/.
[  +25 ms] Successfully connected to service protocol:
http://127.0.0.1:58968/oG1qa1fMl7c=/
[  +33 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.mti.hybrid_composition_ex_example/code_cache/exampleISF
HRW/example/)
[   +1 ms] Updating assets
[  +36 ms] Manifest contained wildcard assets. Inserting missing file into build
graph to force rerun. for more information see #56466.
[   +2 ms] Syncing files to device sdk gphone64 arm64...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:hybrid_composition_ex_example/main.dart
eaa2b03f-3690-4c1c-accd-a52578559214
[        ] <- eaa2b03f-3690-4c1c-accd-a52578559214
[        ] Bundle processing done.
[  +37 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device sdk gphone64 arm64... (completed in 40ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0xb400006f95ecc6a0.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on sdk gphone64 arm64 is
available at:
           http://127.0.0.1:58971/g4-mRdT_QRU=/
[ +163 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +2 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +4 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +3 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +5 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +2 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[  +58 ms] The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is
available
           at: http://127.0.0.1:9100?uri=http://127.0.0.1:58971/g4-mRdT_QRU=/
[  +40 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[        ] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[        ] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[        ] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +3 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +2 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[  +34 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +2 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +1 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[        ] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
[   +1 ms] E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
```

```
no error found

```

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale
    en-BD)
    • Flutter version 3.0.2 at /Users/tareq/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/tareq/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/tareq/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.4
      21F79 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<img src="https://raw.githubusercontent.com/tareq3/hybrid_composition_ex/master/gifs/black_back_behind_hybrid_composition.gif" width="30%" height="30%"/>

**Comment by maheshmnj** [comment]
Hi @tareq3, Thanks for filing the issue. I am able to reproduce the issue on the latest stable channel but not on the master. So I believe this is fixed, Could you please verify this on the master channel by running 
```
flutter channel master
flutter upgrade
```

 _note: slow down the playback speed to 0.5 to see the black containers_


stable | master
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/177524136-7efd527e-02a7-4458-8f0f-81dc2a4213b5.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/177524738-96353f83-bd41-4124-8b10-d4767d1b3511.mov' width=180/> 





 
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1494, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1494 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 829bddf616 (3 hours ago), 2022-07-04 03:49:08 -0400
    • Engine revision e78ed7f1c9
    • Dart version 2.18.0 (build 2.18.0-251.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by tareq3** [comment]
Thanks a lot @maheshmnj  I tried with master channel it seems the issue has been solved for Hybrid Composition but still exists for virtual display. anyway, thanks a lot.
