### ISSUE TITLE
[Web]TextField is unusable within a dialog on few samsung devices

### ISSUE THREAD

**Issue by nitroplr** [flutter/flutter#107786]
## Steps to Reproduce

Every single TextField that is in an AlertDialog shown by showDialog or showGeneralDialog is broken on Chrome when used by mobile.  The keyboard seems like it is tyring to pop up repeatedly.  This does not happen with the exact same code on either Firefox or Brave.  I ran into this problem first when I upgraded to Flutter 3.0.4.  I was able to solve it by declaring my TextEditingControllers in my widget's state and passing them through the showGeneralDialog to my alertDialog method.  After upgrading to Flutter 3.0.5 this no longer works, even by doing the same with the FocusNode for the alertDialog textfields as well.  Also, on Flutter web in a mobile browser, the number keyboard does not pop up by default in either Chrome or Firefox like it does in Brave(on mobile) and on Android.  

Also, many TextFields in a listview is buggy on Chrome and will randomly auto scroll back to the focused TextField in Chrome but not in other browsers on a mobile device.  

I have two videos below that demonstrate what happens in the two browsers for mobile.  I am using the add to home shortcut in both cases so it looks more like an Android app, however the same behavior happens if I use the browser I used to create the shortcut instead.

On Chrome for Mobile:

https://user-images.githubusercontent.com/48568777/179368650-bf727ecf-bdf8-4635-b556-1248ad244f26.mp4

On Brave for Mobile:

https://user-images.githubusercontent.com/48568777/179368658-44ca8c02-7002-4c0c-8d34-bf407d98adf8.mp4

Unfortunately this is difficult to reproduce since it is happening on web browsers for mobile, however when I launch a web browser on my Android emulator and navigate to my site from my Android app, every time I focus a TextField, whether it is in a showDialog or just on a normal page, I get this error:

I/chromium(24552): [INFO:CONSOLE(36057)] "Uncaught TypeError: Cannot read property 'toString' of null", source: https://mywebsite.app/main.dart.js (36057)

Any help would be great!

Code for the TextField that bugs out in Chrome but works fine on Brave and Firefox:

```dart
   Widget _setOwnDKPDialog(
      {required BuildContext context,
      required TextEditingController controller,
      required FocusNode focusNode}) {
    bool setOwnDKPTipVisible = false;
    return AlertDialog(
      scrollable: true,
      content: StatefulBuilder(builder: (BuildContext context, StateSetter setState) {
        return Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(0, 10, 0, 10),
              child: TextField(
                style: Theme.of(context).textTheme.bodyText2,
                keyboardType: TextInputType.number,
                inputFormatters: <TextInputFormatter>[FilteringTextInputFormatter.digitsOnly],
                decoration: InputDecoration(
                  labelText: 'New DKP Value',
                ),
                controller: controller,
                focusNode: focusNode,
              ),
            ),
            AnimatedCrossFade(
              duration: Duration(milliseconds: 500),
              secondChild: SizedBox(),
              firstChild: Padding(
                padding: const EdgeInsets.fromLTRB(0, 0, 0, 10),
                child: Text(
                  'Set your own DKP value to set a limit on what your auto bidders can spend.',
                  style: Theme.of(context).textTheme.bodyText2,
                ),
              ),
              crossFadeState: setOwnDKPTipVisible ? CrossFadeState.showFirst : CrossFadeState.showSecond,
              firstCurve: Curves.easeIn,
              secondCurve: Curves.easeOut,
              sizeCurve: Curves.fastOutSlowIn,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                    splashRadius: 20,
                    highlightColor: Colors.blue[100],
                    splashColor: Colors.blue[200],
                    hoverColor: Colors.blue[100],
                    onPressed: () {
                      setState(() {
                        setOwnDKPTipVisible ? setOwnDKPTipVisible = false : setOwnDKPTipVisible = true;
                      });
                    },
                    icon: Icon(CupertinoIcons.question)),
                ElevatedButton(
                  child: Text('Submit'),
                  onPressed: () async {
                    if (controller.text.length > 0) {
                      int newDKPValue = int.parse(controller.text);
                      int adjustmentValue = newDKPValue - memberDKP.dkpStats.dkp.toInt();
                      Raid currentRaid = await RaidDB().getMostRecentRaid(guild.name);
                      DKPDB().addManualAdjustment(
                          manualAdjustment: ManualAdjustment(
                              userIDOfAdjusted: FirebaseAuth.instance.currentUser!.uid,
                              userIDOfAdjuster: FirebaseAuth.instance.currentUser!.uid,
                              userNameOfAdjuster: this.thisMember.guildUserName,
                              adjustmentDescription: 'Self DKP Total Set',
                              adjustmentCreated: DateTime.now().millisecondsSinceEpoch,
                              adjustmentValue: adjustmentValue,
                              raidDocCreated: currentRaid.raidDocCreated),
                          guild: guild);
                      Navigator.of(context).pop();
                    } else {
                      Navigator.of(context).pop();
                    }
                  },
                )
              ],
            ),
          ],
        );
      }),
    );
  }

```
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale en-US)
    • Flutter version 3.0.5 at C:\Users\nitro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:\Users\nitro\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • ANDROID_HOME = C:\Users\nitro\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\nitro\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8512546\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.
                                                                                                                                  
[√] Chrome - develop for the web                                                                                                  
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.36)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1525
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\nitro\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5787.37

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 102.0.1245.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision f1875d570e (3 days ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c                                            
Tools • Dart 2.17.6 • DevTools 2.12.2                                   

Flutter channels:
  master
  beta
* stable

**Comment by nitroplr** [comment]
I am trying to come up with a minimal reproducible example, thank you for some working code.  I do not get the error when I navigate to your test code from within my app.  However, currently every single TextField is my project throws the error the first time I enter it and if I click the same textfield a second time and then after those first two errors, the same textfield will not throw the error again until I enter a different textfield.

I/chromium(24552): [INFO:CONSOLE(36057)] "Uncaught TypeError: Cannot read property 'toString' of null", source: https://mywebsite.app/main.dart.js (36057)

This error does not happen in either my Chrome emulator or my Android emulator until I use the Android emulator to navigate to my deployed site.  

So far I have tried adding one of your TextFields to my project, and the error still happens.  I tried moving the textfields outside of a listview I have on my login page and the error still happens.  I tried adding the const keyword in front of my InputDecoration, and the error still happens.  I have tried having 1 TextField and 1 TextFormField on my log in page and the error still happens.

After all of this, I tried building and deploying my website without using my github action and instead did it using the command line.

I received a warning that my version of npm was out of date so I upgraded that using:
npm install -g firebase-tools
Now when I build and try to deploy my website using:
firebase deploy --only hosting
I get this error:
Firebase CLI v11.3.0 is incompatible with Node.js v14.17.0 Please upgrade Node.js to version ^14.18.0 || >=16.4.0
So now I am trying to figure out how to upgrade my version of Node...

When I run npm install -g n I get this error:
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.0.0: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

And now when I run npm install -g firebase-tools  I get these warnings
npm WARN notsup Unsupported engine for firebase-tools@11.3.0: wanted: {"node":"^14.18.0 || >=16.4.0"} (current: {"node":"14.17.0","npm":"6
.14.13"})
npm WARN notsup Not compatible with your version of node/npm: firebase-tools@11.3.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\firebase-tools\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os"
:"win32","arch":"x64"})

The internet has been extremely unhelpful with all of this so hopefully I will stumble into something soon but I have a feeling that this is why I am getting such strange errors with my TextFields.

**Comment by nitroplr** [comment]
To upgrade my Node.js I uninstalled my current version using the task manager and went to https://nodejs.org/en/download/ and got the new version.  After this upgrade my TextField error has gone away.  The bouncing keyboard is still there in my showdialogs when I use my phone, but hopefully I can get this to go away by emulating how you made yours.

**Comment by nitroplr** [comment]
This is what happens when I open your dialog on my Galaxy Note 20 using the Chrome app:

https://user-images.githubusercontent.com/48568777/179649250-409cf0c6-6115-400b-8ba2-f8cf40836e4c.mp4

**Comment by maheshmnj** [comment]
@nitroplr I verified the same app on samsung galaxy= I couldn't reproduce it. 

https://user-images.githubusercontent.com/31410839/179679787-89ba334a-be2e-4f16-af94-a816233e0efe.MP4

What keyboard are you using? Does the issue occur when you use the Samsung keyboard?

**Comment by nitroplr** [comment]
Normally I use the Gboard, but the same thing does happen with the Samsung keyboard.

**Comment by nitroplr** [comment]
After adding autofocus true to the first TextField in my login screen and giving each TextField a controller I can't even type in the TextFields on my phone in either Chrome or Brave until some refreshing.  It works perfectly fine on my Android emulator to type using the emulator's keyboard.

https://user-images.githubusercontent.com/48568777/179880738-7f217242-9e52-47b9-aedd-1a8e248d05d4.mp4

**Comment by nitroplr** [comment]
I tried my app using an identical note 20...the keyboard only bounces around a little bit and then it resolves...on this note 20 you'll notice that the little key above the top left of the keyboard is not there.  I'm not sure what phone setting it is to make that key show up but it is for suggested passwords.  On my phone where the bouncing doesn't resolve, it appears to be just that little key on the keyboard that is popping up repeatedly.  

https://user-images.githubusercontent.com/48568777/179894088-a3bdc0ec-0f30-41e6-aded-2bd634d9064e.mp4

**Comment by maheshmnj** [comment]
Thanks for the info, looks like it is a device-specific bug, Labeling for further investigation from the team.

**Comment by nghuyy** [comment]
I'm suggest using TextFormField, before bug was fixed

**Comment by yjbanov** [comment]
Does anyone have a Samsung device to try this again? I'm curious if https://github.com/flutter/engine/pull/35205 had any effect.

**Comment by nitroplr** [comment]
This still happens to me on the stable channel, however on master it no longer happens and the numbers only keyboard comes up for the chrome mobile browser like it is supposed to whereas before it seemed like it got stuck toggling between the normal alpha keyboard and the numbers only one.

**Comment by GaryQian** [comment]
If this issue is resolved on master, it should be rolled out in the next stable release. If there is nothing left to do here, I will close this issue for now. Please feel free to comment if there is anything else regarding this issue and we can re-open.
