### ISSUE TITLE
` Linux_samsung_a02 openpay_benchmarks__scroll_perf ` keeps failing

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108391]
https://ci.chromium.org/p/flutter/builders/staging/Linux_samsung_a02%20openpay_benchmarks__scroll_perf

@iskakaushik could you help take a look? This has been causing testbed quarantine: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-18 (/cc on call @godofredoc )

**Comment by iskakaushik** [comment]
Seems like the error is:

```
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] FINE: Resolving dependencies finished (1.282s).
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] ERR : Git error. Command: `git clone --mirror git@github.com:dnfield/vector_graphics.git /opt/s/w/ir/x/w/.pub-cache/git/cache/vector_graphics-48544a7914590401ff4792b7518970cfb4e75e40`
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | stdout: 
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | stderr: Cloning into bare repository '/opt/s/w/ir/x/w/.pub-cache/git/cache/vector_graphics-48544a7914590401ff4792b7518970cfb4e75e40'...
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | Host key verification failed.
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | fatal: Could not read from remote repository.
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | 
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | Please make sure you have the correct access rights
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | and the repository exists.
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]     | exit code: 128
```

**Comment by iskakaushik** [comment]
@keyonghan looks like pub is failing to resolve dependencies from github. This works for me locally. Are we allowed to clone from github.com in the LUCI bots?

@dnfield if we are not allowed to clone from github.com, is `package:vector_graphics` published somewhere? Maybe I can update the deps in openpay.

**Comment by jonahwilliams** [comment]
Its not published yet, but we could publish a new version to work around this issue

**Comment by keyonghan** [comment]
Our bots are not configured to clone from github.com by default:
```
git clone --mirror git@github.com:dnfield/vector_graphics.git vector_graphics-48544a7914590401ff4792b7518970cfb4e75e40
Cloning into bare repository 'vector_graphics-48544a7914590401ff4792b7518970cfb4e75e40'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

**Comment by iskakaushik** [comment]
@jonahwilliams could you please publish `vector_graphics`?

@keyonghan in that case I'll wait for the package to be published and update `openpay` to use that. Is there a way to reduce the amount of retries in the interim? Looks like its unbounded now.

**Comment by jonahwilliams** [comment]
I've published 0.0.1 for all vector graphics packages, you should be able to update the pubspec to reference these. There may be an additional git constraint for visibility_detector, but that can be removed as long as the package is updated to the latest version

**Comment by iskakaushik** [comment]
Updated OpenPay here: https://dash-internal-review.googlesource.com/c/openpay/+/1080, @keyonghan once this lands can we rerun one of the jobs and see if the issue gets resolved?

**Comment by keyonghan** [comment]
With the above CL, the test still fails: https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_samsung_a02%20openpay_benchmarks__scroll_perf/209/overview, but it is not clear to me what the error is as we are suppressing logs.

**Comment by iskakaushik** [comment]
@keyonghan  is there a way to enable the logs for some users? to enable debugging this?

**Comment by keyonghan** [comment]
Here is one led run with logs: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/43a322025aa9e31c86541b291f1490ca2b3361cd40c872c22100a45d0547ed75/+/build.proto 

```
     ] [   +9 ms] Skipping target: gen_dart_plugin_registrant
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [ +477 ms] kernel_snapshot: Starting due to {}
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [   +8 ms] /opt/s/w/ir/x/w/recipe_cleanup/tmpomvjfgv4/flutter sdk/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/s/w/ir/x/w/recipe_cleanup/tmpomvjfgv4/flutter sdk/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /opt/s/w/ir/x/w/recipe_cleanup/tmpomvjfgv4/flutter sdk/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=true -Ddart.vm.product=false --compact-async --track-widget-creation --aot --tfa --packages /opt/s/w/ir/x/w/recipe_cleanup/tmp4s3ppzof/openpay/.dart_tool/package_config.json --output-dill /opt/s/w/ir/x/w/recipe_cleanup/tmp4s3ppzof/openpay/.dart_tool/flutter_build/d999e24a7fdecf060aac56889f67b2ff/app.dill --depfile /opt/s/w/ir/x/w/recipe_cleanup/tmp4s3ppzof/openpay/.dart_tool/flutter_build/d999e24a7fdecf060aac56889f67b2ff/kernel_snapshot.d --source file:///opt/s/w/ir/x/w/recipe_cleanup/tmp4s3ppzof/openpay/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///opt/s/w/ir/x/w/recipe_cleanup/tmp4s3ppzof/openpay/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error file:///opt/s/w/ir/x/w/recipe_cleanup/tmp4s3ppzof/openpay/test_driver/scroll_perf.dart
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [+11797 ms] [+12659 ms] grpc/lib/src/client/http2_connection.dart:336:12: Error: The method 'isInsecureConnectionAllowed' isn't defined for the class '_SocketTransportConnector'.
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] [        ]  - '_SocketTransportConnector' is from 'package:grpc/src/client/http2_connection.dart' ('grpc/lib/src/client/http2_connection.dart').
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'isInsecureConnectionAllowed'.
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] [        ]       if (!isInsecureConnectionAllowed(_host)) {
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] [        ]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [+8999 ms] [+9038 ms] Persisting file store
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [ +100 ms] [  +19 ms] Done persisting file store
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [   +5 ms] "flutter assemble" took 22,417ms.
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [   +1 ms] ensureAnalyticsSent: 0ms
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [        ] Running shutdown hooks
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [        ] Shutdown hooks complete
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] [        ] exiting with code 1
[openpay_benchmarks__scroll_perf] [STDOUT] stdout: [        ] Task :app:compileFlutterBuildProfile in app Finished
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ] [   +1 ms] Target kernel_snapshot failed: Exception
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:245:7)
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]            <asynchronous suspension>
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]            <asynchronous suspension>
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[openpay_benchmarks__scroll_perf] [STDOUT] stderr: [        ]            <asynchronous suspension>
```

**Comment by iskakaushik** [comment]
https://dash-internal-review.googlesource.com/c/openpay/+/1140 fixes this error.

**Comment by iskakaushik** [comment]
@keyonghan looks like it's still failing :(. 

1. Is there a way for me to trigger runs using led and enable logs?
2. Can I use a custom revision of `openpay` for the test runs?
3. Could you please disable this test until I can get a successful run?

Thanks.

**Comment by keyonghan** [comment]
> @keyonghan looks like it's still failing :(.
> 
> 1. Is there a way for me to trigger runs using led and enable logs?

Commenting out https://cs.opensource.google/flutter/recipes/+/main:recipes/devicelab/devicelab_drone.py;l=78 will enable the logs.

Then you can run led based on the local changes.

> 2. Can I use a custom revision of `openpay` for the test runs?

You can try replacing `ref`: https://cs.opensource.google/flutter/recipes/+/main:recipes/devicelab/devicelab_drone.py;l=75, with the one from you attempting CL.

> 3. Could you please disable this test until I can get a successful run?

https://github.com/flutter/flutter/pull/108466

**Comment by iskakaushik** [comment]
I finally got around to trying it, I [modified the properties](https://paste.googleplex.com/5841871638102016) of an existing builder and added the relevant bits to checkout openpay. I'm running into errors like so:

```
[E 2022-08-01 09:52:57] original error: googleapi: Error 403: user "kaushikiska@google.com" does not have permission "swarming.tasks.createInRealm"
```

Maybe I need some permissions to launch tasks via CLI in `prod`. I tried changing `prod` to `try` and it still failed.

@keyonghan could you please help me with this?

**Comment by keyonghan** [comment]
Try is expected to work. How about staging? Could you share the command?

**Comment by iskakaushik** [comment]
I used `cat properties.json | led edit-recipe-bundle | led launch`, using https://paste.googleplex.com/5841871638102016 as the `properties.json` file. I changed line 26, from

```
          "bucket": "prod",
```

To


```
          "bucket": "try",
```

**Comment by keyonghan** [comment]
Line 26 is still using `prod`.

You can try:
```
led get-builder "luci.flutter.staging:Linux_android old_gallery__transition_perf" > /tmp/test.json
Update 1) task_name 2) device_type: SM-A025V
cat /tmp/test.json | led edit-recipe-bundle | led launch
```

**Comment by iskakaushik** [comment]
I did change line 26 to try before running it :), still failed.
Will attempt the solution you recommended.

**Comment by iskakaushik** [comment]
https://dash-internal-review.googlesource.com/c/openpay/+/1160 should likely fix this issue, but I found another one while debugging this.

@keyonghan looks like `suppress_logs` means we don't initialize: `initialize_logs_collection`, which in-turn does not set `FLUTTER_TEST_OUTPUTS_DIR`, and the tests currently rely on this env var to be set to find the json files. Would it be OK to call `initialize_logs_collection` but just not upload the logs?

**Comment by keyonghan** [comment]
We should be good on that. Approved https://flutter-review.googlesource.com/c/recipes/+/32340.

**Comment by iskakaushik** [comment]
@keyonghan , this test seems to succeed now, but its still flaky on one of the bots:

https://paste.googleplex.com/5051984135585792

Any reason why the URL in the above mentioned logs wouldn't resolve?

**Comment by keyonghan** [comment]
There is no difference between linux18 and linux27. I would wait for a couple of runs to see if this is a network flake.

**Comment by keyonghan** [comment]
The test is failing consistently again on both linux18 and linux27: https://ci.chromium.org/p/flutter/builders/staging/Linux_samsung_a02%20openpay_benchmarks__scroll_perf

**Comment by jmagman** [comment]
This is still failing every commit, no logs though:
https://ci.chromium.org/p/flutter/builders/staging/Linux_samsung_a02%20openpay_benchmarks__scroll_perf/1800

**Comment by keyonghan** [comment]
@iskakaushik Shall we skip the test from CI before it is ready?

**Comment by iskakaushik** [comment]
@keyonghan yes, that sounds good to me

**Comment by sealesj** [comment]
@iskakaushik created PR to skip the test for now here #111415

**Comment by keyonghan** [comment]
@iskakaushik Do we still need this test?

**Comment by godofredoc** [comment]
Closing as obsolete.
