### ISSUE TITLE
Could not build module 'image_picker_ios'

### ISSUE THREAD

**Issue by GiamBoscaro** [flutter/flutter#108630]
## Steps to Reproduce

Run my application. I do not have any specific step to reproduce since the app is big and has many packages

**Expected results:**

App build correctly

**Actual results:**

Build failed

<details>
<summary>Code sample</summary>

None

</details>

<details>
  <summary>Logs</summary>

```
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'image_picker_ios.Test': '/Users/giammarco/Workspace/imtech/too-quirky/mobile-app/build/ios/Debug-iphonesimulator/firebase_core/firebase_core.framework/Headers/messages.g.h'
/Applications/Flutter/flutter-3/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Test.h:8:8

Semantic Issue (Xcode): Unknown type name 'FLTMaxSize'
/Applications/Flutter/flutter-3/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Test.h:36:39

Semantic Issue (Xcode): Property with 'retain (or strong)' attribute must be of object type
/Applications/Flutter/flutter-3/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Test.h:36:0

Semantic Issue (Xcode): Cannot find protocol declaration for 'FLTImagePickerApi'
/Applications/Flutter/flutter-3/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Test.h:53:36

Parse Issue (Xcode): Could not build module 'image_picker_ios'
/Users/giammarco/Workspace/imtech/too-quirky/mobile-app/ios/Runner/GeneratedPluginRegistrant.m:123:8

Could not build the application for the simulator.
Error launching application on iPhone 13.
```

```
  info • Unused import: '../../commons/components/navigation/main_wrapper.dart' • lib/auth/helpers/auth_helper.dart:15:8 • unused_import
   info • Unused import: '../../commons/ui/welcome_page.dart' • lib/auth/helpers/auth_helper.dart:20:8 • unused_import
   info • The value of the local variable 'status' isn't used • lib/auth/services/apple_auth_service.dart:88:12 • unused_local_variable
   info • The value of the local variable 'status' isn't used • lib/auth/services/facebook_auth_service.dart:82:12 • unused_local_variable
   info • The value of the local variable 'status' isn't used • lib/auth/services/google_auth_service.dart:78:12 • unused_local_variable
   info • The value of the field '_isExpanded' isn't used • lib/chat/components/bottom_drawer/chat_bottom_drawer.dart:41:13 • unused_field
   info • The value of the field '_recorderInitialized' isn't used • lib/chat/components/voice_recorder.dart:33:8 • unused_field
   info • The value of the field '_isPlaybackReady' isn't used • lib/chat/components/voice_recorder.dart:34:8 • unused_field
   info • The value of the local variable 'callback' isn't used • lib/chat/services/chat_manager.dart:48:15 • unused_local_variable
   info • The value of the local variable 'chat' isn't used • lib/chat/services/chat_manager_factory.dart:36:18 • unused_local_variable
   info • 'FirebaseDatabase.FirebaseDatabase' is deprecated and shouldn't be used. Accessing FirebaseDatabase via the constructor is now deprecated. Use `.instanceFor`
          instead. • lib/chat/services/realtime_db_service.dart:22:10 • deprecated_member_use
   info • The value of the local variable 'gradient' isn't used • lib/commons/components/buttons/outline_button.dart:31:10 • unused_local_variable
   info • Unused import: '../../../notifications/ui/notifications_page.dart' • lib/commons/components/navigation/navigator_factory.dart:15:8 • unused_import
   info • Unused import: 'navigation_bar_profile_picture.dart' • lib/commons/components/navigation/navigator_factory.dart:19:8 • unused_import
   info • The value of the field '_isExpanded' isn't used • lib/commons/components/users/bottom_drawer/user_bottom_drawer.dart:39:13 • unused_field
   info • Duplicate import • lib/commons/helpers/api_manager.dart:15:8 • duplicate_import
   info • Duplicate import • lib/commons/helpers/api_manager.dart:16:8 • duplicate_import
   info • The value of the field '_cron' isn't used • lib/commons/helpers/cron_manager.dart:30:9 • unused_field
   info • The value of the field '_schedules' isn't used • lib/commons/helpers/cron_manager.dart:32:36 • unused_field
   info • The value of the field '_timers' isn't used • lib/commons/helpers/cron_manager.dart:34:28 • unused_field
   info • Unused import: 'package:tooquirky/commons/styles/styles.dart' • lib/commons/services/system_service.dart:13:8 • unused_import
   info • Prefer using lowerCamelCase for constant names • lib/commons/styles/styles.dart:80:22 • constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:140:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:148:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:156:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:166:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:176:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:186:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:194:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:202:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:212:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:220:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:228:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:238:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:246:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:256:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:264:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:272:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:280:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:290:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:298:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:306:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:314:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:322:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:330:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:338:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:346:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:354:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:362:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:370:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:380:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:388:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:396:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:404:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:414:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:422:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:430:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:438:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:490:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:500:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:510:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:518:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:526:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:534:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:542:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:550:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:559:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:569:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:577:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commons/styles/styles.dart:585:20 • non_constant_identifier_names
   info • Unused import: 'dart:io' • lib/commons/ui/full_screen_image_page.dart:5:8 • unused_import
   info • Unused import: 'package:tooquirky/auth/services/auth_service.dart' • lib/commons/ui/splash_page.dart:10:8 • unused_import
   info • The value of the local variable 'configLoaded' isn't used • lib/commons/ui/splash_page.dart:70:12 • unused_local_variable
   info • The value of the field '_maxPeople' isn't used • lib/events/components/book_event_button.dart:36:7 • unused_field
   info • The value of the field '_nOutOfRange' isn't used • lib/map/components/filtered_places_double_list.dart:32:12 • unused_field
   info • The value of the field '_isListView' isn't used • lib/map/ui/map_view_page.dart:42:13 • unused_field
   info • The value of the local variable 'settings' isn't used • lib/notifications/services/notifications_service.dart:48:28 • unused_local_variable
   info • The value of the local variable 'responses' isn't used • lib/places/components/around_you_list.dart:111:11 • unused_local_variable
   info • The value of the local variable 'responses' isn't used • lib/profile/components/favourite_users_list.dart:105:11 • unused_local_variable
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale it-IT)
    • Flutter version 3.0.1 at /Applications/Flutter/flutter-3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/giammarco/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 6F00760D-5C95-45C5-9080-DC9E9E132AA2 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64 • macOS 12.4 21F79 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

I am going crazy with this error. I cannot build my app anymore and I don't even know why since I haven't updated any package and in particular not image_picker.

Since I do not work with Swift but only with flutter, these errors for me are like Chinese. I am really struggling at the moment.

I already tried to clean everything. I have done so many times that now I have a script to do it:

```shell
# full_clean.sh

#!/bin/zsh

# shellcheck disable=SC1090
source ~/.zshrc

cd ..
echo "Cleaning flutter cache..."
flutter clean

cd ./ios || exit
echo "Removing Podfile.lock..."
rm -f Podfile.lock

echo "Cleaning pod cache..."
pod cache clean --all

echo "Updating pod repo..."
pod repo update
cd ..

echo "Getting flutter dependencies..."
flutter pub get

cd ./ios || exit
echo "Installing pods..."
pod install
```

**Comment by stuartmorgan** [comment]
This was fixed several months ago in `image_picker_ios` 0.8.5+3; you should `flutter pub upgrade` to get the latest version.

**Comment by GiamBoscaro** [comment]
Unfortunately I do have already the latest version and I had it for months. This issue is still appearing. Well it’s the first time for me, 0.8.5+3 worked good til today

**Comment by GiamBoscaro** [comment]
> This was fixed several months ago in `image_picker_ios` 0.8.5+3; you should `flutter pub upgrade` to get the latest version.

Please at least wait for a reply before closing the issue. I do have the latest version and always had.

**Comment by GiamBoscaro** [comment]
> > I do have the latest version and always had.
> 
> You do not; you have 0.8.5. This is from your error output:
> 
> > > /Applications/Flutter/flutter-3/.pub-cache/hosted/pub.dartlang.org/**image_picker_ios-0.8.5**/ios/Classes/FLTImagePickerPlugin_Test.h:8:8
> 
> You may have the latest version of the app-facing package (`image_picker`), but you need the latest version of the iOS implementation package (`image_picker_ios`, per my earlier comment).

Ohh ok I see. That is weird, I never explicitly added image_picker_ios in my pubspec.yaml, I only have image_picker and it is the latest version. Why is it not installing the latest version if the ios module? 
What should I do? Add the dependency for ios explicitly? 
thank you

**Comment by stuartmorgan** [comment]
> I never explicitly added image_picker_ios in my pubspec.yaml

That is normal; it's a transitive dependency.

> Why is it not installing the latest version if the ios module?

Please see the discussion of `pubspec.lock` at https://docs.flutter.dev/development/tools/pubspec.

> What should I do?

Please see my initial comment.
