### ISSUE TITLE
Canvaskit datepicker skiagold tests are flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110785]
Since the most recent canvaskit roll, these tests are producing new skia diffs on nearly every run. This is closing the framework tree, and blocking rolls.

cc @yjbanov

**Comment by zanderso** [comment]
In particular, at least the following appear to be producing inconsistent results across runs:
```
cupertino.date_picker_test.datetime.initial
cupertino.date_picker_test.time.initial
cupertino.date_picker_test.datetime.drag
```

**Comment by yjbanov** [comment]
Since the CanvasKit roll was reverted, dropping priority to P2.

**Comment by yjbanov** [comment]
Update: still discussing what the right solution is here.

**Comment by Hixie** [comment]
Did the PR above fix this?

**Comment by yjbanov** [comment]
> Did the PR above fix this?

Hard to tell because when we skip goldens we don't send them to Skia Gold any more. I'm working on https://github.com/flutter/flutter/issues/111325 so we can verify flake fixes. Also, will drop the priority of this, since the test is skipped and not causing build breakages.

**Comment by yjbanov** [comment]
Reassigned to @harryterkelsen who's actively overhauling how screenshots are taken in CanvasKit mode.

**Comment by harryterkelsen** [comment]
Should be fixed by https://github.com/flutter/flutter/pull/135249

Using `Scene.toImage` should be more stable than browser screenshot APIs

**Comment by harryterkelsen** [comment]
There is a bug in CanvasKit which causes items in the wheel scroll widget to disappear. This needs to be fixed before we can re-enable the tests on CanvasKit.

**Comment by mdebbar** [comment]
[INFO] This is still broken in Skwasm. I tried to unskip it in https://github.com/flutter/flutter/pull/162038 but it produced incorrect goldens: https://flutter-gold.skia.org/search?issue=162038&crs=github&patchsets=2&corpus=flutter
