### ISSUE TITLE
Error: Locations: No module for http://localhost:xxxx/dart_sdk.js

### ISSUE THREAD

**Issue by sahilmahi** [flutter/flutter#111136]
On flutter 3.3.1 web i'm having this problem: 

`Locations: No module for http://localhost:8199/dart_sdk.js`

![Immagine 2022-09-07 230854](https://user-images.githubusercontent.com/87030675/188982814-a27acc21-15be-4baf-b6ad-cc1a265f3fb7.png)

I can't understand the problem.
Any help?

Flutter 3.3.1 • channel stable 
Framework • revision 4f9d92fbbd (20 hours ago) • 2022-09-06 17:54:53 -0700
Engine • revision 3efdf03e73
Tools • Dart 2.18.0 • DevTools 2.15.0

**Comment by GeoffGodwin** [comment]
Just got the same thing after flutter upgrading to 3.3.1 about 20 mins ago.

**Comment by Bassslaper** [comment]
After updating Flutter to 3.3.1, the same error occurred. Plus DevTools stopped working in VS Code

**Comment by brewsley** [comment]
same issue after upgrading to 3.3, and it persists at 3.3.1, it doesnt matter if it's vs code or android studio, i get this error when running without debug : 
Error: XMLHttpRequest error.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1378:11                                          callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

**Comment by Nazacheres** [comment]
Hello, I have a similar situation I've updated flutter version through fvm from 3.0.1 to 3.3.1, and now on web I have:
```
Locations: No module for http://localhost:5555/dart_sdk.js
Locations: No module for http://localhost:5555/main_module.bootstrap.js
Locations: No module for http://localhost:5555/main_module.bootstrap.js
Locations: No module for 
Locations: No module for http://localhost:5555/dwds/src/injected/client.js
```

The page itself doesn't respond and stays blank. No errors in the browser console.

**Comment by jcviau** [comment]
I have the same problem with VS Code after updating from flutter 3.0.0 to 3.3.0: Locations: No module for http://localhost:xxxx/dart_sdk.js

Probably related but it seems to cause issue when debugging. The execution stop at breakpoints (callstack displayed) but it's impossible to debug since the source code file isnt shown. Opening the source code file manually doesnt work either. Mapping between the breakpoint and source code file doesnt work.

**vs code version** : 1.71.0

**flutter doctor -v**
[✓] Flutter (Channel stable, 3.3.0, on Debian GNU/Linux 11 (bullseye) 5.10.102.1-microsoft-standard-WSL2, locale en_US.UTF-8)
    • Flutter version 3.3.0 on channel stable at /home/dev/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (10 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Debian GNU/Linux 11 (bullseye) 5.10.102.1-microsoft-standard-WSL2

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by sahilmahi** [comment]
I switched to master channel and the error doesn't  appear.

Flutter 3.4.0-19.0.pre.138 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1ed2312493 (33 minutes ago) • 2022-09-08 12:36:07 +0100
Engine • revision 4096e133ef
Tools • Dart 2.19.0 (build 2.19.0-177.0.dev) • DevTools 2.17.0

**Comment by jcviau** [comment]
> I switched to master channel and the error doesn't appear.
> 
> Flutter 3.4.0-19.0.pre.138 • channel master • https://github.com/flutter/flutter.git Framework • revision [1ed2312](https://github.com/flutter/flutter/commit/1ed2312493ac35c17a01cf5ef8e5c9f2a0bcbf59) (33 minutes ago) • 2022-09-08 12:36:07 +0100 Engine • revision 4096e133ef Tools • Dart 2.19.0 (build 2.19.0-177.0.dev) • DevTools 2.17.0

+1

It worked for me also, switching to master.

**Comment by huycozy** [comment]
> I switched to master channel and the error doesn't appear.
> 
> Flutter 3.4.0-19.0.pre.138 • channel master • https://github.com/flutter/flutter.git Framework • revision [1ed2312](https://github.com/flutter/flutter/commit/1ed2312493ac35c17a01cf5ef8e5c9f2a0bcbf59) (33 minutes ago) • 2022-09-08 12:36:07 +0100 Engine • revision 4096e133ef Tools • Dart 2.19.0 (build 2.19.0-177.0.dev) • DevTools 2.17.0

By the confirmation by @sahilmahi and @jcviau, the issue has been fixed on `master` channel. So, for anyone facing with this issue on `stable`, please try upgrading to `master` channel and retry:

```
flutter channel master
flutter upgrade
```

Closing as fixed on the master channel. The fix should land on the stable channel in future releases. 
In case the issue still persists on `master`, please leave a comment and I will reopen the issue right away. Thanks!

**Comment by realitymolder** [comment]
Tried to use flutter-3.4-candidate.19 as suggested here, also the master branch.
Still getting: 


> > I switched to master channel and the error doesn't appear.
> > Flutter 3.4.0-19.0.pre.138 • channel master • https://github.com/flutter/flutter.git Framework • revision [1ed2312](https://github.com/flutter/flutter/commit/1ed2312493ac35c17a01cf5ef8e5c9f2a0bcbf59) (33 minutes ago) • 2022-09-08 12:36:07 +0100 Engine • revision 4096e133ef Tools • Dart 2.19.0 (build 2.19.0-177.0.dev) • DevTools 2.17.0
> 
> By the confirmation by @sahilmahi and @jcviau, the issue has been fixed on `master` channel. So, for anyone facing with this issue on `stable`, please try upgrading to `master` channel and retry:
> 
> ```
> flutter channel master
> flutter upgrade
> ```
> 
> Closing as fixed on the master channel. The fix should land on the stable channel in future releases. In case the issue still persists on `master`, please leave a comment and I will reopen the issue right away. Thanks!

Tried to use flutter-3.4-candidate.19 as suggested here, also the master branch.
Still getting: 
`Uncaught (in promise) TypeError: this.parentElement is null
    remove (index):69
    _callMethodUnchecked0 js_util_patch.dart:92
    DomElementExtension$124remove dom.dart:253
    fromFrameworkMessage text_editing.dart:237
    fromFrameworkMessage text_editing.dart:867
    handleTextInput text_editing.dart:2005
    _sendPlatformMessage platform_dispatcher.dart:512
    sendPlatformMessage platform_dispatcher.dart:325
    send binding.dart:364
    _invokeMethod platform_channel.dart:289
    runBody async_patch.dart:84
    _async async_patch.dart:123
    _invokeMethod platform_channel.dart:283
    _invokeMethod text_editing_delta.dart.js:4400
    invokeMethod platform_channel.dart:566
    runBody async_patch.dart:84
    _async async_patch.dart:123
    invokeMethod platform_channel.dart:565
    _attach text_input.dart:1664
    attach text_input.dart:1652
    _openInputConnection editable_text.dart:2596
    _openOrCloseInputConnectionIfNeeded editable_text.dart:2632
    _handleFocusChanged editable_text.dart:3087
    notifyListeners change_notifier.dart:377
    _notify focus_manager.dart:1038
    _applyFocusChange focus_manager.dart:1803
    _microtaskLoop schedule_microtask.dart:40
    _startMicrotaskLoop schedule_microtask.dart:49
    _scheduleImmediateWithPromise async_patch.dart:166
    promise callback*_scheduleImmediateWithPromise async_patch.dart:164
    _scheduleImmediate async_patch.dart:136
    _scheduleAsyncCallback schedule_microtask.dart:69
    _rootScheduleMicrotask zone.dart:1465
    scheduleMicrotask schedule_microtask.dart:134
    _markNeedsUpdate focus_manager.dart:1761
    _markNextFocus focus_manager.dart:1743
    _markNextFocus focus_manager.dart:920
    _doRequestFocus focus_manager.dart:1092
    requestFocus focus_manager.dart:1069
    userUpdateTextEditingValue editable_text.dart:3266
    _setTextEditingValue editable.dart.js:907
    _setSelection editable.dart.js:914
    selectPositionAt editable.dart.js:1823
    selectPosition editable.dart.js:1808
    onTapDown text_selection.dart:1803
    _handleTapDown text_selection.dart:2387
    handleTapDown tap.dart.js:401
    invokeCallback recognizer.dart.js:218
    handleTapDown tap.dart.js:401
    _checkDown tap.dart.js:216
    acceptGesture tap.dart.js:197
    sweep arena.dart.js:229
    handleEvent binding.dart.js:385
    dispatchEvent binding.dart.js:369
    dispatchEvent view.dart.js:686
    _handlePointerEventImmediately binding.dart.js:345
    handlePointerEvent binding.dart.js:315
    _flushPointerEventQueue binding.dart.js:304
    _handlePointerDataPacket binding.dart.js:292
    invoke1 platform_dispatcher.dart:1175
    invokeOnPointerDataPacket platform_dispatcher.dart:243
    _onPointerData pointer_binding.dart:147
    setup pointer_binding.dart:652
    <anonymous> pointer_binding.dart:593
    loggedHandler pointer_binding.dart:288
    jsHandler pointer_binding.dart:179
    _checkAndCall operations.dart:352
    dcall operations.dart:357
    ret dart_sdk.js:61466
[localhost:50766:69:7](http://localhost:50766/)
    _startMicrotaskLoop schedule_microtask.dart:54
    _scheduleImmediateWithPromise async_patch.dart:166
    (Async: promise callback)
    _scheduleImmediateWithPromise async_patch.dart:164
    _scheduleImmediate async_patch.dart:136
    _scheduleAsyncCallback schedule_microtask.dart:69
    _rootScheduleMicrotask zone.dart:1465
    scheduleMicrotask schedule_microtask.dart:134
    _markNeedsUpdate focus_manager.dart:1761
    _markNextFocus focus_manager.dart:1743
    _markNextFocus focus_manager.dart:920
    _doRequestFocus focus_manager.dart:1092
    requestFocus focus_manager.dart:1069
    userUpdateTextEditingValue editable_text.dart:3266
    _setTextEditingValue editable.dart.js:907
    _setSelection editable.dart.js:914
    selectPositionAt editable.dart.js:1823
    selectPosition editable.dart.js:1808
    onTapDown text_selection.dart:1803
    onTapDown self-hosted:1151
    _handleTapDown text_selection.dart:2387
    _handleTapDown self-hosted:1151
    handleTapDown tap.dart.js:401
    invokeCallback recognizer.dart.js:218
    handleTapDown tap.dart.js:401
    _checkDown tap.dart.js:216
    acceptGesture tap.dart.js:197
    sweep arena.dart.js:229
    handleEvent binding.dart.js:385
    dispatchEvent binding.dart.js:369
    dispatchEvent view.dart.js:686
    _handlePointerEventImmediately binding.dart.js:345
    handlePointerEvent binding.dart.js:315
    _flushPointerEventQueue binding.dart.js:304
    _handlePointerDataPacket binding.dart.js:292
    _handlePointerDataPacket self-hosted:1151
    invoke1 platform_dispatcher.dart:1175
    invokeOnPointerDataPacket platform_dispatcher.dart:243
    _onPointerData pointer_binding.dart:147
    _onPointerData self-hosted:1151
    setup pointer_binding.dart:652
    <anonymous> pointer_binding.dart:593
    loggedHandler pointer_binding.dart:288
    jsHandler pointer_binding.dart:179
    _checkAndCall operations.dart:352
    dcall operations.dart:357
    ret dart_sdk.js:61466`

**Comment by huycozy** [comment]
@realitymolder 
Your flutter version `flutter-3.4-candidate.19` is different than `3.4.0-19.0.pre.138` as we confirmed above. And the error log is also different from the one originally reported. Try upgrading to master channel and retry:

```
flutter channel master
flutter upgrade
```

**Comment by realitymolder** [comment]
OK, I've checked again, last time it was with: 3.4.0-19.0.pre.192 and had an issue. But you are right, I tried it with the current master version, and It doesn't have the same issue, it's a different one. 
Will open another bug report.

Currently, on 3.0.5 without issues like that, only for RTL support.

**Comment by iamar1k92** [comment]
Is this issue fixed on 3.3.2?

As currently i am facing it on 3.3.1 on stable.

**Comment by iamar1k92** [comment]
Locations: No module for http://localhost:51962/dart_sdk.js
2
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js
3
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js
Locations: No module for http://localhost:51962/dart_sdk.js




sultan@Sultans-MacPro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale
    en-PK)
    • Flutter version 3.3.2 on channel stable at
      /Users/sultan/Developments/softwares/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (4 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sultan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/sultan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by bobosette** [comment]
stable 3.3.2 error still appers

**Comment by RandyKdev** [comment]
Same here, Error showing on stable 3.3.2

**Comment by fleetimee** [comment]
error still persist on stable version

**Comment by huycozy** [comment]
For anyone facing this issue on `stable`, this issue has been fixed on `master` as above confirmation. The fix should land on the stable channel in future releases. Please see https://github.com/flutter/flutter/issues/111136#issuecomment-1241494761.

**Comment by sakib-shaikh-github** [comment]
Switch to stable version 3.3.0 worked for me, not the latest one or not even on master branch worked

**Comment by iamar1k92** [comment]
3.3.0 stable isn't yet release

**Comment by CalebKatwigye** [comment]
I have switched channel to master and upgraded but I am still getting the error.

**Comment by CalebKatwigye** [comment]
![image](https://user-images.githubusercontent.com/110837740/191488121-6dc982ea-95d7-4ca0-8072-71146dcdf8b2.png)
but they keep taking me to this function. Could that be where the problem is?

**Comment by iamar1k92** [comment]
[✓] Flutter (Channel master, 3.4.0-19.0.pre.333, on macOS 12.6 21G115
    darwin-arm64, locale en-PK)
    
   I am using the temporary fix to resolve this issue as stated above on this specific branch.

**Comment by Jordan-Nelson** [comment]
> For anyone facing this issue on `stable`, this issue has been fixed on `master` as above confirmation. The fix should land on the stable channel in future releases. Please see [#111136 (comment)](https://github.com/flutter/flutter/issues/111136#issuecomment-1241494761).

Any idea when the fix will land in stable? Will there be a cherry pick for this?

**Comment by huycozy** [comment]
>Any idea when the fix will land in stable? Will there be a cherry pick for this?

@Jordan-Nelson 
It takes a couple of months to land stable fixes to release channels. You can read more about the build release channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.

**Comment by Jordan-Nelson** [comment]
> Depending on the severity of the issue, it is possible. Refer to the cherrypick process for details.

Given the number of people impacted, this seems like it may qualify for a cherry-pick.

**Comment by Marty** [comment]
I am on flutter 3.3.0 and everything was working fine on this version for a few weeks until today I started getting the same error ...

**Comment by shiveshpanesar** [comment]
flutter channel stable 

This worked for me

**Comment by NicTanghe** [comment]
i dident have this problem on the example dart.
then i made an other project when i now try to run the default flutter demo home page i get the error.
I`m on 3.3.2 on fedora 36

**Comment by NicTanghe** [comment]
I started having this error after running 2 diferent projects at the same time now even a reboot doesn`t fix it.

(when running the default app)

**Comment by aleripe** [comment]
At every Flutter upgrade my web app breaks... good job!

**Comment by ivostoykov** [comment]
Hi there,

Same problem here. Neither master nor stable change the result:

Instance of 'Response'

Locations: No module for http://localhost:35475/dart_sdk.js
Locations: No module for http://localhost:35475/dart_sdk.js
....

flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale en_GB.UTF-8)
    • Flutter version 3.3.2 on channel stable at /home/ivo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (13 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/ivo/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
> Same here. In my case, error happens in IntelliJ Community Edition with Flutter stable 3.3.2, but **only in debug mode**.

Which Intellij IDEA version are you using? I tested with `IntelliJ IDEA 2022.1.1 (Community Edition)` but can not replicate this issue. 

------
For anyone else facing this issue on latest stable `3.3.2` and master `3.4.0-33.0.pre.32`, please provide `Steps to reproduce` and the output of `flutter doctor -v` so that we can investigate this. Thank you!

**Comment by huycozy** [comment]
> Same here. In my case, error happens in IntelliJ Community Edition with Flutter stable 3.3.2, but **only in debug mode**.

@KnucklesEQ Which Intellij IDEA version are you using? I tested with `IntelliJ IDEA 2022.1.1 (Community Edition)` but can not replicate this issue. 

------
For anyone else facing this issue on latest stable `3.3.2` and master `3.4.0-33.0.pre.32`, please provide `Steps to reproduce` and the output of `flutter doctor -v` so that we can investigate this. Thank you!

**Comment by KnucklesEQ** [comment]
Hi @huycozy ! 

I'm using IntelliJ IDEA 2022.2.2 Community Edition, with Flutter (stable channel) 3.3.2 on Debian GNU/Linux 11 (bullseye - stable). Testing my apps with Google Chrome version 106.0.5249.61 (my actual project is a Web App with Flutter).

I can replicate the problem just creating a new Web project of any kind (for example, the classic Flutter Demo with the counter), run it in debug mode and add a breakpoint (for example in `_counter++;` inside the `setState`). When you press the add button and the application reaches the code line with the breakpoint, the app stops with the "Locations: No module for http://localhost:37341/dart_sdk.js" error.

> Launching lib/main.dart on Chrome in debug mode...
> Waiting for connection from debug service on Chrome...
> This app is linked to the debug service: ws://127.0.0.1:36299/HDs5qcIDIQU=/ws
> Debug service listening on ws://127.0.0.1:36299/HDs5qcIDIQU=/ws
> 
> 💪 Running with sound null safety 💪
> Debug service listening on ws://127.0.0.1:36299/HDs5qcIDIQU=/ws
> Flutter Web Bootstrap: Programmatic
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js
> Locations: No module for http://localhost:37341/dart_sdk.js

My `flutter doctor -v`

> [✓] Flutter (Channel stable, 3.3.2, on Debian GNU/Linux 11 (bullseye) 5.10.0-18-amd64, locale es_ES.UTF-8)
>     • Flutter version 3.3.2 on channel stable at /home/nevian/Aplicaciones/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e3c29ec00c (hace 2 semanas), 2022-09-14 08:46:55 -0500
>     • Engine revision a4ff2c53d8
>     • Dart version 2.18.1
>     • DevTools version 2.15.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /home/nevian/Android/Sdk
>     • Platform android-33, build-tools 30.0.3
>     • Java binary at: /usr/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • Debian clang version 11.0.1-2
>     • cmake version 3.18.4
>     • ninja version 1.10.1
>     • pkg-config version 0.29.2
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
> 
> [✓] IntelliJ IDEA Community Edition (version 2022.2)
>     • IntelliJ at /home/nevian/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/222.4167.29
>     • Flutter plugin version 70.0.5
>     • Dart plugin version 222.4167.21
> 
> [✓] Connected device (2 available)
>     • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.10.0-18-amd64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.61
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 1 category.
>

**Comment by huycozy** [comment]
@KnucklesEQ thanks for providing `Steps to reproduce`, I can reproduce the issue now on both `IntelliJ IDEA` and `Android Studio`. But it's only reproducible on stable `3.3.2`. I test with master `3.4.0-33.0.pre.32` and see that it no longer happens. Please retry on the latest master channel and confirm the same behavior. Thanks!

**Comment by KnucklesEQ** [comment]
You are welcome @huycozy !

I tried it with the latest version of Flutter on the master channel and I can confirm it doesn't happen anymore. 

The problem is that at the moment it's impossible to debug on stable channel (obviously we always go to production on stable), so I'm crossing my fingers that the fix from master to stable will arrive soon :sweat_smile:

Many thanks!

**Comment by fagnerlc** [comment]
Teve atualização do Flutter ontem para Flutter 3.3.3 • channel stable • 
Será que corrigiram o problema?

**Comment by fagnerlc** [comment]
yesterday there was Flutter update to Flutter 3.3.3 • channel stable •
Did they fix the problem?

**Comment by Jayasubin** [comment]
I faced this issue during runtime (on chrome, debug mode).

While stepping through exceptions, I found that the app had tried to use a plugin that was not supported on web (Path_provider)

```
Locations: No module for http://localhost:65455/dart_sdk.js
Error: Unsupported operation: Platform._operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49     throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                  _operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform_impl.dart 56:40                                         get operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 64:45                                              get _operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 109:40                                             get operatingSystem
packages/platform/src/interface/local_platform.dart 21:45                                                                     get operatingSystem
packages/platform/src/interface/platform.dart 104:41                                                                          get isAndroid
packages/path_provider_platform_interface/src/method_channel_path_provider.dart 56:20                                         getExternalStoragePath
packages/path_provider/path_provider.dart 132:40                                                                              getExternalStorageDirectory
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54               runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5               _async
packages/path_provider/path_provider.dart 131:47                                                                              getExternalStorageDirectory
packages/org_admin/features/common/repository/filesystem_service.dart 44:31                                                   getRootDir
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50               <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                             runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                       handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                       handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                       _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                        [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                        callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                 _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                  _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15              <fn>
```

Windows, flutter version 3.3.3

**Comment by KnucklesEQ** [comment]
> 
> Also, @fagnerlc, It seems they have solved the problem in version 3.3.3

Hi @Jayasubin . I'm still experiencing the same error with Flutter 3.3.3.

**Comment by keitakun** [comment]
This seems to be caused by an exception thrown inside the `main()`.
You can get the same error by creating an empty flutter project and adding a `throw Exception('')` just before `runApp()` in `main.dart`

Just a quick workaround, create a Widget (doesn't matter either Stateless / Stateful) and wrap your initial Widget in `runApp(MyApp())` into it and you'll see the proper errors thrown instead of `No module for...`

```
...
Future<void> main() async {
  ...
  runApp(MyApp());
}
...
```

to

```
Future<void> main() async {
  ...
  runApp(MyApp());
}

class AppWrapper extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return MyApp();
  }
}
`

And try to avoid initialiser calls in the `main()` method.

**Comment by annagrin** [comment]
@christopherfujino we missed this issue, looks like it was closed due the fix available in master. I can repro this stable version Given the number of people affected, would it be possible to cherry-pick the change from https://github.com/flutter/flutter/commit/3b6e3a693836cf0675355eb009a0455d1e237e1c?

**Comment by annagrin** [comment]
@KnucklesEQ 

> The problem is that at the moment it's impossible to debug on stable channel (obviously we always go to production on stable), so I'm crossing my fingers that the fix from master to stable will arrive soon 😅

Could you please let us know what is blocking the debugging in that case - is it too many messages, or does it affect functionality in some way and prevents the users from performing some actions?

**Comment by christopherfujino** [comment]
I am closing this as it is fixed on master (the fix is also present on beta). Fixing this on stable is being tracked in https://github.com/flutter/flutter/issues/112886

**Comment by longfit** [comment]
> 

Same case caused but Not yet how to solve.

**Comment by AKA-LinCoder** [comment]
same case in stable 3.3.4

**Comment by AKA-LinCoder** [comment]
even in master 3.5.0-10.0 pre.98 have case 
Error: Expected a value of type 'DefaultHttpClientAdapter', but got one of type 'BrowserHttpClientAdapter'

**Comment by zhoudajun-ola** [comment]
i update to master channel, still not solve.

**Comment by AKA-LinCoder** [comment]
nfg

**Comment by Pablodev21** [comment]
Today i update to master channel and still not solve

**Comment by PHTremor** [comment]
I'm also facing the same Error on flutter 3.3.8
It's not happening every time I run the code on Chrome, but sometimes. I have a TabBar and TabBarView wrapped inside a NestedScrollView. The Error sometimes appears when I navigate to another page, return to this TabBar - page, and jump from one TabBarView to Another.

**Comment by KanikaRaheja** [comment]
> ![image](https://user-images.githubusercontent.com/110837740/191488121-6dc982ea-95d7-4ca0-8072-71146dcdf8b2.png) but they keep taking me to this function. Could that be where the problem is?

you got any solution to this!?...I have the same error
