### ISSUE TITLE
FAILED BINDER TRANSACTION

### ISSUE THREAD

**Issue by AnukirtiYadav** [flutter/flutter#113427]
## Steps to Reproduce

1. Execute `flutter run --flavor development --target lib/main_development.dart`

**Expected results:** 
App should run.

**Actual results:** 
```
E/JavaBinder(15182): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 340)
W/GmsClient(15182): IGmsServiceBroker.getService failed
W/GmsClient(15182): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
W/GmsClient(15182): 	at android.os.BinderProxy.transactNative(Native Method)
W/GmsClient(15182): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
W/GmsClient(15182): 	at WE.b(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:288)
W/GmsClient(15182): 	at com.google.android.gms.common.internal.BaseGmsClient.p(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:53)
W/GmsClient(15182): 	at BB.run(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:1849)
W/GmsClient(15182): 	at android.os.Handler.handleCallback(Handler.java:942)
W/GmsClient(15182): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/GmsClient(15182): 	at Sp0.dispatchMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:223)
W/GmsClient(15182): 	at android.os.Looper.loopOnce(Looper.java:201)
W/GmsClient(15182): 	at android.os.Looper.loop(Looper.java:288)
W/GmsClient(15182): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @AnukirtiYadav, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by naveenkmavoor** [comment]
Hi, I've faced this issue before. It's mainly causing on my mac m1 by the android emulator. Can be resolved by quitting the emulator and run again.

**Comment by neri4488** [comment]
> 

I have the same on m1 but tried this option and nothing has changed, how do you quit the emulator.
I just clicked the 'x' and that emulator tab closed but the issue persisted.

**Comment by mihaita-tinta** [comment]
after 

> > 
> 
> I have the same on m1 but tried this option and nothing has changed, how do you quit the emulator. I just clicked the 'x' and that emulator tab closed but the issue persisted.

Try to use `Cold Boot Now` to start the emulator again.

**Comment by Sebastian1808** [comment]
I get the same error on a MacBook Pro but with intel, is it a mac error? 

I tried restarting the emulator, closing it and reopening it but the error remains.

**Comment by binaryjc** [comment]
I get the same error. i'm trying to add google ad banner on my app. currently just using the test AdMob app and ad units. ad is not showing.

**Comment by mihaita-tinta** [comment]
> I get the same error on a MacBook Pro but with intel, is it a mac error?
> 
> I tried restarting the emulator, closing it and reopening it but the error remains.

In my case, I reverted to Pixel 2 API 30 emulator on my mac and it works fine compared to latest version (33)

**Comment by ramoenariel** [comment]
I've the same problem in the emulator, BUT not in physical phone.

**Comment by MelihHakanPektas** [comment]
I've the same problem in the google play api 33 emulator.

**Comment by Wegi** [comment]
I encounter the same error, when trying to use the Google One Tap button with Jetpack Compose. Restarting the Emulator seems to help most of the time.

Emulator:
Pixel 5 API 33

**Comment by dmitry-kotorov** [comment]
I've the same issue on Pixel XL API 33 emulator

**Comment by huycozy** [comment]
Hi everyone facing this issue, I tried running the default Flutter project (counter app) on Pixel 4 API 33 emulator but can not reproduce this issue. It would be nice if you can provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this, and along with the output of `flutter doctor -v` as well. Thanks!

**Comment by dhvanit-v-simformsolutions** [comment]
In my case, after wiping data of emulator works.

**Comment by rai-h** [comment]
It's the issue with emulators on m1. For now the only way out from this issue is cold booting your emulator.

**Comment by Cotspheer** [comment]
I had the same issue with a Nexus 5X API 33 Google Play x86_64 emulated device. I did multiple things at once so I'm not sure which one did the trick but I'm leaving my steps here in case it will help someone out:

- Updated build.gradle to use ext.kotlin_version = '1.7.10'
- Added `<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`
- Updated google_maps_flutter 2.2.1 as I got the exception @AnukirtiYadav mentioned but only recognized after I saw that the google-maps-widget was not working
- Wipe Data of Emulator as @dhvanit-v-simformsolutions has mentioned and then did a cold boot

But I still get this log error:
```
E/SurfaceSyncer( 8886): Failed to find sync for id=0
W/Parcel  ( 8886): Expecting binder but got null!
```
which makes me concerned if it is "stable" to use. I'm currently testing android api 33 and I'm on the master channel of flutter as it has a critical not released fix regarding tree-shaking which caused non related issues on iOS devices.

flutter doctor -v
```
[√] Flutter (Channel master, 3.6.0-3.0.pre.32, on Microsoft Windows [Version 10.0.19043.2075], locale de-DE)
    • Flutter version 3.6.0-3.0.pre.32 on channel master at D:\Flutter       
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a298d0b95 (16 hours ago), 2022-11-15 11:26:21 -0500
    • Engine revision eead7b0d86
    • Dart version 2.19.0 (build 2.19.0-401.0.dev)
    • DevTools version 2.19.0

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 33.0.0-rc3
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.0)       
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community      
    • Visual Studio Community 2022 version 17.4.33103.184
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Nighty\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.2075]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

APP: build.gradle
[app_build.gradle.txt](https://github.com/flutter/flutter/files/10019731/app_build.gradle.txt)

Android: build.gradle
[build.gradle.txt](https://github.com/flutter/flutter/files/10019744/build.gradle.txt)

**Comment by champcbg** [comment]
> Hi @AnukirtiYadav, I've faced this issue before. It's mainly causing on my mac m1 by the android emulator. Can be resolved by quitting the emulator and run again.

this also worked on my windows machine

**Comment by Adam-Langley** [comment]
FYI
I also started receiving this error today, Nexus 10 API 33
My environment is VS Code on 16'' MacBook Pro (Intel).

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-x64, locale
    en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!
```

Simulator reboot made no difference.
Issue was resolved by simulator cold boot.

**Comment by YudhiPrasetyo** [comment]
> 

anyone know how to cool boot on intellij since my emulator doesn't show and i have tried cool boot from android studio still cannot since the emulator still running

**Comment by TDuffinNTU** [comment]
Noticed this during a navigation transition while testing on a Windows Android Emulator earlier today. Didn't cause any noticeable issues but though it's worth adding that it wasn't just M1 Macs for me.
