### ISSUE TITLE
[Material3] Add an option in `NavigationBar` items to disable ripple effects.

### ISSUE THREAD

**Issue by mavyfaby** [flutter/flutter#113870]
## Use case

I need to use `NavigationBar` in my app without ripples, but somehow I didn't find any documentation to disable the ripple.

Just like Google Playstore's bottom nav bar.

## Proposal

As the title suggest.

**Comment by huycozy** [comment]
@mavyfaby Thanks for filing the issue. Labeling the issue for further insights.
By the way, I found there is a [workaround](https://github.com/flutter/flutter/pull/83047#issuecomment-916953357) for this. You may want to try applying `splashColor: Colors.transparent` in ThemeData.

**Comment by HansMuller** [comment]
@huycozy - that's a reasonable workaround. One could also create a noop [InkSplashFactory](https://api.flutter.dev/flutter/material/ThemeData/splashFactory.html)

**Comment by rydmike** [comment]
@HansMuller I cannot really find any references in the Material 3 design spec that show the `NavigationBar` with the big tap ink effect it currently has in Flutter's implementation.

I can however in its behavior examples see that it does **not** have it:

https://m3.material.io/components/navigation-bar/guidelines#bd6c5e81-4699-4652-9e3a-b03aa97b8b4b

Just like Google Playstore app does not have it either, or other native apps using this navigator.

Should the extra classic M2 ink ripple effect on the `NavigationBar` perhaps be considered a design bug in its current M3 implementation?

I think adding an option to turn it off, that defaults to off when `useMaterial` is true, sounds like the correct action.

The animated selection indicator design is clearly intended to be a replacement for the tractional ink in this M3 style navigator.

The animated selection with ink splash is clearly not how it should look (below). Turning it off in M3 mode to comply with the spec would make it look better and as designed. Maybe keep it on in M2 mode if you feel that is right for when it is used there, but I would turn it off there too, since this design does not have an M2 spec, there is really no reason to keep it on there either.

![themed_navbar](https://user-images.githubusercontent.com/39990307/202187974-67f0ce9b-4530-477b-9f2a-545a6628eb7b.gif)

**Comment by HansMuller** [comment]
@rydmike - I agree with you, I think we've got this wrong. #114618 is trying to resolve it.

**Comment by mavyfaby** [comment]
Any updates?

**Comment by HansMuller** [comment]
@mavyfaby - #115449 has landed and should resolve this problem.

**Comment by enseitankad0** [comment]
Did you guys get rid of this issue? I'm using this version of flutter and ripple effect is still wrong

[✓] Flutter (Channel stable, 3.3.4, on macOS 13.0.1 22A400 darwin-arm, locale pl-PL)
    • Flutter version 3.3.4 on channel stable at /Users/kamil/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
