### ISSUE TITLE
Google testing being scheduled but never completes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#114858]
Because of internal [b/257101178](http://b/257101178) pre-submit Google testing was manually turned off. However, because of [b/258071287](http://b/258071287), the github check is still created as yellow, even though it will never complete.

**Comment by christopherfujino** [comment]
IDK if related, but https://github.com/flutter/flutter/pull/114112 has a green google testing check, even though testing *actually* failed cl/484101226

**Comment by XilaiZhang** [comment]
right I posted a quick thought in b/258071287. While the bug is being worked on, once the current roll land we can re-enable pre merge tests.

**Comment by XilaiZhang** [comment]
> IDK if related, but #114112 has a green google testing check, even though testing _actually_ failed cl/484101226

right that one comes from we told Jenn to use the 'set github status' button in frob to override the google testing check.

**Comment by XilaiZhang** [comment]
I tentatively created [cl/486817133](https://critique.corp.google.com/cl/486817133) for long term fix.

**Comment by CaseyHillers** [comment]
As a mitigation, I've gone ahead and re-enabled testing. The backlog of PRs should start to show green checks (over the next few hours).

For context, we had the internal test team file an issue that we were testing too much. Our team applied a mitigation to disable the Google Testing on GitHub to preserve quota. It was later detected that this issue was unrelated to us.

It surfaced that:

  (1) Our Flutter Google testing doesn't have the monitoring needed to verify the amount of tests being run
  (2) The production configs don't correctly disable Google Testing
     (A) It is correctly not running tests, but it is still creating a status (which @XilaiZhang linked a proposed fix for)

**Comment by Hixie** [comment]
Reducing to P3 since the team-blocking issue has been resolved.

**Comment by CaseyHillers** [comment]
Closing as the issue has been resolved. If anyone is still seeing this, feel free to reach out.

**Comment by ricardoamador** [comment]
This is still happening on some current pull requests i have open.

**Comment by ricardoamador** [comment]
cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I synced with @ricardoamador and it seems expectations weren't aligned.

1. User error with clicking "Test all", which requires a PST overnight run

I'll monitor again to see if there's any stuck PRs, and will close out if I don't see anything tonight.
