### ISSUE TITLE
Running macOS tests with flutter drive (or integration_test) fails in a CI environment, on Intel based Mac machines

### ISSUE THREAD

**Issue by desistefanova** [flutter/flutter#118469]
Hi team!
We have a problem running `flutter drive`  on the latest MacOS image of GitHub CI. It works on a local Mac machine. And the CI is running on all the other environments successfully. We don't have this issue using Flutter stable version.
Is `flutter drive` being deprecated in favor of `flutter test`?

## Steps to Reproduce

1. Run a GitHub CI action on `macos-latest` image.
2. Install Flutter from beta channel - Flutter 3.7.0-1.3.pre / Dart 2.19.0-444.3.beta
4. Run `flutter drive -d macos --target=test_driver/app.dart --suppress-analytics --dart-entrypoint-args=""` It is also tried with `--debug`. It doesn't matter whether we set `--no-dds` or not.
5. This command hangs and never starts the test application after "Building macOS application". The CI times outs and the operation is automatically canceled.

## Logs

A detailed verbose log could be found here: https://github.com/realm/realm-dart/actions/runs/3901917475/jobs/6664375172
When running `flutter drive` without `verbose` the log is: https://github.com/realm/realm-dart/actions/runs/3902047674/jobs/6664647585.
<details>
<summary>Logs</summary>

```
flutter drive -d macos --target=test_driver/app.dart --suppress-analytics --dart-entrypoint-args="" --debug --no-dds
Running "flutter pub get" in tests...
Resolving dependencies...
+ _fe_analyzer_shared 52.0.0
+ analyzer 5.4.0
+ archive 3.3.2 (3.3.5 available)
+ args 2.3.1
+ async 2.10.0
+ boolean_selector 2.1.1
+ build 2.3.1
+ build_cli_annotations 2.1.0
+ build_config 1.1.1
+ build_daemon 3.1.0
+ build_resolvers 2.1.0
+ build_runner 2.3.3
+ build_runner_core 7.2.7
+ built_collection 5.1.1
+ built_value 8.4.3
+ cancellation_token 1.5.0
+ characters 1.2.1
+ checked_yaml 2.0.2
+ clock 1.1.1
+ code_builder 4.4.0
+ collection 1.[17](https://github.com/realm/realm-dart/actions/runs/3902047674/jobs/6664647585#step:11:18).0
+ convert 3.1.1
+ coverage 1.6.1
+ crypto 3.0.2
+ dart_style 2.2.4
+ fake_async 1.3.1
+ ffi 2.0.1
+ file 6.1.4
+ fixnum 1.0.1
+ flutter 0.0.0 from sdk flutter
+ flutter_driver 0.0.0 from sdk flutter
+ flutter_lints 2.0.1
+ flutter_test 0.0.0 from sdk flutter
+ frontend_server_client 3.2.0
+ fuchsia_remote_debug_protocol 0.0.0 from sdk flutter
+ glob 2.1.1
+ graphs 2.2.0
+ http 0.13.5
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.3
+ js 0.6.5 (0.6.6 available)
+ json_annotation 4.7.0
+ lints 2.0.1
+ logging 1.1.0
+ matcher 0.12.13 (0.12.14 available)
+ material_color_utilities 0.2.0
+ meta 1.8.0
+ mime 1.0.4
+ node_preamble 2.0.1
+ objectid 2.1.0
+ package_config 2.1.0
+ path 1.8.2 (1.8.3 available)
+ platform 3.1.0
+ pool 1.5.1
+ process 4.2.4
+ pub_semver 2.1.3
+ pubspec_parse 1.2.1
+ realm 0.8.0+rc from path ..
+ realm_common 0.8.0+rc from path ../../../common
+ realm_generator 0.8.0+rc from path ../../../generator
+ sane_uuid 1.0.0-alpha.4
+ shelf 1.4.0
+ shelf_packages_handler 3.0.1
+ shelf_static 1.1.1
+ shelf_web_socket 1.0.3
+ sky_engine 0.0.99 from sdk flutter
+ source_gen 1.2.6
+ source_map_stack_trace 2.1.1
+ source_maps 0.10.11
+ source_span 1.9.1
+ stack_trace 1.11.0
+ stream_channel 2.1.1
+ stream_transform 2.1.0
+ string_scanner 1.2.0
+ sync_http 0.3.1
+ tar 0.5.6
+ term_glyph 1.2.1
+ test 1.22.2
! test_api 0.4.17 (overridden) (0.4.[18](https://github.com/realm/realm-dart/actions/runs/3902047674/jobs/6664647585#step:11:19) available)
+ test_core 0.4.[22](https://github.com/realm/realm-dart/actions/runs/3902047674/jobs/6664647585#step:11:23)
+ timezone 0.9.1
+ timing 1.0.0
+ typed_data 1.3.1
+ vector_math 2.1.4
+ vm_service 9.4.0 (10.0.0 available)
+ watcher 1.0.2
+ web_socket_channel 2.3.0
+ webdriver 3.0.1
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.1
Warning: You are using these overridden dependencies:
! test_api 0.4.17 (0.4.18 available)
Changed [91](https://github.com/realm/realm-dart/actions/runs/3902047674/jobs/6664647585#step:11:92) dependencies!
Updating minimum macOS deployment target to 10.14.
Upgrading project.pbxproj
Upgrading Podfile
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Removing script build phase dependency analysis.
Running pod install...                                              3.0s
Building macOS application...                                   
warning: Run script build phase '[CP-User] Download Realm Flutter iOS Binaries' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'realm' from project 'Pods')
warning: Run script build phase '[CP-User] Report Metrics' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'realm' from project 'Pods')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Error: The operation was canceled.
```

```
```

</details>

## Update 2023-04-25: Workaround for GitHub Actions

The `macos-13` image for GitHub actions appears to now include Metal support. See details in comment https://github.com/flutter/flutter/issues/118469#issuecomment-1521594859.

**Comment by exaby73** [comment]
Hello @desistefanova. Thanks for raising this issue. Could you provide an isolated example that reproduces this issue? Preferably, a public Github repository, that includes all the CI files, that I can fork and test with little to no changes.

Along with that, also provide how you're configuring and running the CI builds on Github. Whether it requires any paid machines or can be done with the free tier? 

Try to provide as much information so that it becomes trivial to reproduce and makes the issue much more actionable. Thank you

**Comment by desistefanova** [comment]
Hi @exaby73,
I created an empty Flutter application with one test that even doesn't test widgets. The test timeout on the same way because the app can not be started. The repo that you can fork is https://github.com/desistefanova/fl-apps.
You can compare the jobs in the last CI run: https://github.com/desistefanova/fl-apps/actions/runs/3937156112/jobs/6734354598

- MacOS with Flutter stable - works fine and fast.
- MacOS with Flutter beta - timeouts on starting the app.
- Windows with Flutter beta - works fine but slow.

I hope this will help you to investigate the issue.
Thank you for the support!

**Comment by huycozy** [comment]
@desistefanova Do you see this issue when running it locally? I pulled your sample code and ran it on my mac, on Flutter beta `3.7.0-1.4.pre`, but it executed normally. Below is the log:

```
Building macOS application...                                           
Current PID 88984
00:00 +0: Realm tests (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:51366/8n4XKGCjbvM=/
VMServiceFlutterDriver: Isolate found with number: 3341886432736363
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
00:00 +0: Realm tests run all

00:00 +1: Realm tests (tearDownAll)

00:00 +1: All tests passed!
``` 

<details>
<summary>flutter doctor -v (beta)</summary>

```bash
[!] Flutter (Channel beta, 3.7.0-1.4.pre, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-1.4.pre on channel beta at /Users/huynq/Documents/GitHub/flutter_beta
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 686fe913dc (27 hours ago), 2023-01-10 16:14:01 -0800
    • Engine revision ac5c83dd5f
    • Dart version 2.19.0 (build 2.19.0-444.4.beta)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by desistefanova** [comment]
Hi @huycozy !
It works locally.
The problem is only in GitHub CI.

**Comment by huycozy** [comment]
Hi @desistefanova 
As the issue can not reproduce locally but only on your GitHub CI. We are unfortunately not sure how to resolve this issue. I recommend you ask for support directly from the service provider.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thank you!

**Comment by vegaro** [comment]
I am getting this on CircleCI too. The tests hang after building macOS application and never get to show the `[+1099 ms] Observatory URL on device: http://127.0.0.1:49505/....` log.

I downgraded to 3.3.10 in my CI machines and the tests work fine

**Comment by exaby73** [comment]
@vegaro Are you able to get the details of the machine your tests are running on? If it's an Intel based mac or M1 based? Also, do these tests fail on the latest stable (3.7.0)?

**Comment by desistefanova** [comment]
Yes, it happens with the flutter stable channel also. Our MacOS CI tests stopped working since the Flutter 3.7.0 was released yesterday. 
We use the image[ macos-latest provided by GitHub](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230117.3).
I migrated flutter driver to integrated_tests and the result was the same. It just stops right after running the app.
![image](https://user-images.githubusercontent.com/95419820/214793410-393420d1-0365-4cdf-a799-57876b39ab8c.png)
It points me to this code https://github.com/dart-lang/sdk/blob/a1f6688e16f73f9e13c5dde53430db318847fe98/sdk/lib/_internal/vm/lib/isolate_patch.dart#L189
It is waiting here and timeouts.

**Comment by exaby73** [comment]
Could you provide a sample workflow file along with a sample app (public github repo that can be forked is ideal) that I can test on?

**Comment by desistefanova** [comment]
Sure,
I have already provided a sample in a comment above. Here is the [repo ](https://github.com/desistefanova/fl-apps).
You can check also the PR.

**Comment by vegaro** [comment]
Our repo is also public. We noticed it in this PR https://github.com/RevenueCat/purchases-flutter/pull/592 which was still open when 3.7.0 got released and we had to pin the version to 3.3.10 for the tests to stop failing.

The architecture is also x64. Running on a macOS 12.3.1. Flutter doctor outputs the following:

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.3.1 21E258 darwin-x64, locale en)
```

. I tried upgrading to 12.6, but that didn't help. It also works locally on my M1 machine.

Let me know if you need any more information, or you want us to try something

**Comment by iapicca** [comment]
@vegaro 

it seems to me that you are having an issue with [circle ci](https://github.com/RevenueCat/purchases-flutter/blob/main/.circleci/config.yml) not with github actions (the only [workflow](https://github.com/RevenueCat/purchases-flutter/tree/main/.github/workflows) is "lock")

while one could somewhat try to [run github actions locally](https://github.com/nektos/act), I don't see how anyone could investigate an issue on circle ci except circle ci themselves

**Comment by exaby73** [comment]
@iapicca I am able to reproduce the issue with the repo provided by @desistefanova in https://github.com/flutter/flutter/issues/118469#issuecomment-1405631838 with Gitbub CI. I am right now testing this on another Ci (Codemagic) with M1 and x64, with different versions to try to get more information on it. Will update on my findings in a bit

**Comment by exaby73** [comment]
There looks to be an issue with x64 machines running drive tests on CI environments. Testing on Codemgic M1 machines, it took 58 seconds, while Mac Pros (x64 Intel machines), is at 14 minutes and counting. But running a MacOS build (not the drive test) works without an issue. 

So in conclusion, I see an issue with the `flutter drive` and `integration_test` tests on an x64 (Intel) based mac in specifically CI environments. I have confirmed that the issue reproduces in Codemagic, and Github Actions while @vegaro has confirmed it reproduces on CircleCI as well.

Here's some more detailed information:

This issue seems to only be reproducible in CI environments, when running on an Intel based macs. The OS's I have tested on were all MacOS 12.x with Xcode 14.2.

OP ran `integration_test`, and it seemed to timeout on the test (https://github.com/flutter/flutter/issues/118469#issuecomment-1404705288). The default `TimeoutException` being thrown after 12 minutes.

With my testing, on Github Actions as well as Codemagic using `flutter drive` ([Repo I used](https://github.com/exaby73/issue_118469) (fork of OP's one)):

- M1 works as expected
- Intel based macs, hang on the build phase of `flutter drive -d macos` (Just after printing the plist file in verbose logs). This causes the CI environment to trigger a timeout, which in the case of Github, I had it running for almost 3 hours before having to manually cancel the workflow

I can also confirm that this is a regression and does not occur on 3.3.10, which makes be believe that this is indeed an issue with `flutter drive` and `flutter test integration_test` rather than the CI environments.

Github Actions logs: https://github.com/exaby73/issue_118469/actions/runs/4025223776/jobs/6918176200
<details>
<summary>Codemagic tail logs</summary>

```console
/Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/builder/clone/beta_test_drive/macos
[        ]     Signing Identity:     "-"
[        ]     /usr/bin/codesign --force --sign - --entitlements /Users/builder/clone/beta_test_drive/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/beta_test_drive.app.xcent --timestamp\=none --generate-entitlement-der /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app
[  +40 ms] RegisterExecutionPolicyException /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/builder/clone/beta_test_drive/macos
[        ]     builtin-RegisterExecutionPolicyException /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app
[  +16 ms] Validate /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/builder/clone/beta_test_drive/macos
[        ]     builtin-validationUtility /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app -no-validate-extension
[   +1 ms] Touch /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/builder/clone/beta_test_drive/macos
[        ]     /usr/bin/touch -c /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app
[   +2 ms] RegisterWithLaunchServices /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/builder/clone/beta_test_drive/macos
[        ]     /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -f -R -trusted /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app
[ +386 ms] ** BUILD SUCCEEDED **
[  +37 ms] Building macOS application... (completed in 35.5s)
[   +4 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app/Contents/Info.plist
[  +13 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/builder/clone/beta_test_drive/build/macos/Build/Products/Debug/beta_test_drive.app/Contents/Info.plist
[        ] 
           
           <plist version="1.0">
           <dict>
           	<key>BuildMachineOSBuild</key>
           	<string>21G217</string>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>en</string>
           	<key>CFBundleExecutable</key>
           	<string>beta_test_drive</string>
           	<key>CFBundleIconFile</key>
           	<string>AppIcon</string>
           	<key>CFBundleIconName</key>
           	<string>AppIcon</string>
           	<key>CFBundleIdentifier</key>
           	<string>com.example.betaTestDrive</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>beta_test_drive</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
           	<string>1.0.0</string>
           	<key>CFBundleSupportedPlatforms</key>
           	<array>
           		<string>MacOSX</string>
           	</array>
           	<key>CFBundleVersion</key>
           	<string>1</string>
           	<key>DTCompiler</key>
           	<string>com.apple.compilers.llvm.clang.1_0</string>
           	<key>DTPlatformBuild</key>
           	<string>14C18</string>
           	<key>DTPlatformName</key>
           	<string>macosx</string>
           	<key>DTPlatformVersion</key>
           	<string>13.1</string>
           	<key>DTSDKBuild</key>
           	<string>22C55</string>
           	<key>DTSDKName</key>
           	<string>macosx13.1</string>
           	<key>DTXcode</key>
           	<string>1420</string>
           	<key>DTXcodeBuild</key>
           	<string>14C18</string>
           	<key>LSMinimumSystemVersion</key>
           	<string>10.14</string>
           	<key>NSHumanReadableCopyright</key>
           	<string>Copyright © 2023 com.example. All rights reserved.</string>
           	<key>NSMainNibFile</key>
           	<string>MainMenu</string>
           	<key>NSPrincipalClass</key>
           	<string>NSApplication</string>
           </dict>
           </plist>
```

</details>

All tests were conducted on Flutter 3.7.0, on MacOS 12 (@vegaro please confirm if CircleCI was using a different version), running Xcode 14.2 (@vegaro again, confirm if CircleCI is the same). On the Codemagic machines, the exact MacOS version is 12.6.1. I am not sure of Github and CircleCI

**Comment by vegaro** [comment]
> while one could somewhat try to [run github actions locally](https://github.com/nektos/act),
I don't see how anyone could investigate an issue on circle ci except circle ci themselves

yes @iapicca, thankfully it looks like it's the same issue as GH Actions, so hopefully we find the answer there. Happy to test anything that would be helpful.


> All tests were conducted on Flutter 3.7.0, on MacOS 12 (@vegaro please confirm if CircleCI was using a different version), running Xcode 14.2 (@vegaro again, confirm if CircleCI is the same)

@exaby73 running 3.7.0, on macOS 12.3.1, Xcode 13.4. I tried with macOS 12.6 and Xcode 14.2 and had the same issues.

**Comment by desistefanova** [comment]
Thank you for the research!
We have a workaround for now. We configured our Mac CI to run with Flutter 3.3.10. It will be great if you can find some solution. I will be happy to help, if some more information is needed. 
BTW, It works fine on my local Intel based MacBook Air with MacOs 11.7.2.

**Comment by Gustl22** [comment]
I think the problem is that since Flutter 3.7.0 OpenGL support is removed, and therefore only CI with GPU support can handle the tests:
See also:
https://github.com/actions/runner-images/issues/1779#issuecomment-707071183
https://github.com/flutter/flutter/issues/108304
https://github.com/flutter/engine/pull/37733
https://github.com/actions/runner-images/issues/183

**Comment by GregoryConrad** [comment]
Coming here from #119246. I also got the GitHub Actions timeout after 12 minutes, but I also got the following logs (on some runs) that I haven't seen mentioned anywhere in this thread yet:

```
2023-01-25T23:17:07.3878710Z error: the following command failed with exit code 0 but produced no further output
2023-01-25T23:17:07.3885280Z Ld /Users/runner/work/mimir/mimir/packages/flutter_mimir/example/build/macos/Build/Products/Debug/flutter_mimir/flutter_mimir.framework/Versions/A/flutter_mimir normal (in target 'flutter_mimir' from project 'Pods')
```

This might be a different issue with 3.7 than everyone else here is experiencing, but figured it was noteworthy nonetheless. Not reproducible locally on my M1 MBP.

**Comment by exaby73** [comment]
@GregoryConrad Do you get anything different by adding the `-v` flag?

**Comment by GregoryConrad** [comment]
@exaby73 I do, see [here](https://github.com/GregoryConrad/mimir/actions/runs/4054620082/jobs/6976670808).

<details>
<summary>CI logs</summary>

```
2023-01-31T14:17:21.9318270Z [        ] ** BUILD SUCCEEDED **
2023-01-31T14:17:21.9484490Z [  +16 ms] Building macOS application... (completed in 125.5s)
2023-01-31T14:17:21.9546350Z [   +6 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/runner/work/mimir/mimir/packages/flutter_mimir/example/build/macos/Build/Products/Debug/flutter_example.app/Contents/Info.plist
2023-01-31T14:17:21.9759170Z [  +20 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/runner/work/mimir/mimir/packages/flutter_mimir/example/build/macos/Build/Products/Debug/flutter_example.app/Contents/Info.plist
2023-01-31T14:17:21.9771070Z [        ] <?xml version="1.0" encoding="UTF-8"?>
2023-01-31T14:17:21.9772220Z            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
2023-01-31T14:17:21.9773160Z            <plist version="1.0">
2023-01-31T14:17:21.9773640Z            <dict>
2023-01-31T14:17:21.9776360Z            	<key>BuildMachineOSBuild</key>
2023-01-31T14:17:21.9778880Z            	<string>21G320</string>
2023-01-31T14:17:21.9779610Z            	<key>CFBundleDevelopmentRegion</key>
2023-01-31T14:17:21.9780100Z            	<string>en</string>
2023-01-31T14:17:21.9781190Z            	<key>CFBundleExecutable</key>
2023-01-31T14:17:21.9781670Z            	<string>flutter_example</string>
2023-01-31T14:17:21.9782120Z            	<key>CFBundleIconFile</key>
2023-01-31T14:17:21.9782590Z            	<string>AppIcon</string>
2023-01-31T14:17:21.9783090Z            	<key>CFBundleIconName</key>
2023-01-31T14:17:21.9783900Z            	<string>AppIcon</string>
2023-01-31T14:17:21.9785350Z            	<key>CFBundleIdentifier</key>
2023-01-31T14:17:21.9787810Z            	<string>com.example.flutterExample</string>
2023-01-31T14:17:21.9788920Z            	<key>CFBundleInfoDictionaryVersion</key>
2023-01-31T14:17:21.9796650Z            	<string>6.0</string>
2023-01-31T14:17:21.9797680Z            	<key>CFBundleName</key>
2023-01-31T14:17:21.9801540Z            	<string>flutter_example</string>
2023-01-31T14:17:21.9805330Z            	<key>CFBundlePackageType</key>
2023-01-31T14:17:21.9816100Z            	<string>APPL</string>
2023-01-31T14:17:21.9816770Z            	<key>CFBundleShortVersionString</key>
2023-01-31T14:17:21.9817270Z            	<string>1.0.0</string>
2023-01-31T14:17:21.9817750Z            	<key>CFBundleSupportedPlatforms</key>
2023-01-31T14:17:21.9818200Z            	<array>
2023-01-31T14:17:21.9818620Z            		<string>MacOSX</string>
2023-01-31T14:17:21.9819420Z            	</array>
2023-01-31T14:17:21.9819940Z            	<key>CFBundleVersion</key>
2023-01-31T14:17:21.9820390Z            	<string>1</string>
2023-01-31T14:17:21.9820830Z            	<key>DTCompiler</key>
2023-01-31T14:17:21.9821330Z            	<string>com.apple.compilers.llvm.clang.1_0</string>
2023-01-31T14:17:21.9821820Z            	<key>DTPlatformBuild</key>
2023-01-31T14:17:21.9822270Z            	<string>14C18</string>
2023-01-31T14:17:21.9822710Z            	<key>DTPlatformName</key>
2023-01-31T14:17:21.9823150Z            	<string>macosx</string>
2023-01-31T14:17:21.9823610Z            	<key>DTPlatformVersion</key>
2023-01-31T14:17:21.9824050Z            	<string>13.1</string>
2023-01-31T14:17:21.9824500Z            	<key>DTSDKBuild</key>
2023-01-31T14:17:21.9824920Z            	<string>22C55</string>
2023-01-31T14:17:21.9825350Z            	<key>DTSDKName</key>
2023-01-31T14:17:21.9825790Z            	<string>macosx13.1</string>
2023-01-31T14:17:21.9826220Z            	<key>DTXcode</key>
2023-01-31T14:17:21.9826640Z            	<string>1420</string>
2023-01-31T14:17:21.9827080Z            	<key>DTXcodeBuild</key>
2023-01-31T14:17:21.9827520Z            	<string>14C18</string>
2023-01-31T14:17:21.9827960Z            	<key>LSMinimumSystemVersion</key>
2023-01-31T14:17:21.9828420Z            	<string>10.14</string>
2023-01-31T14:17:21.9828890Z            	<key>NSHumanReadableCopyright</key>
2023-01-31T14:17:21.9829730Z            	<string>Copyright © 2023 com.example. All rights reserved.</string>
2023-01-31T14:17:21.9830270Z            	<key>NSMainNibFile</key>
2023-01-31T14:17:21.9830730Z            	<string>MainMenu</string>
2023-01-31T14:17:21.9831180Z            	<key>NSPrincipalClass</key>
2023-01-31T14:17:21.9831660Z            	<string>NSApplication</string>
2023-01-31T14:17:21.9832090Z            </dict>
2023-01-31T14:17:21.9832510Z            </plist>
2023-01-31T14:26:29.2758040Z ##[group]❌ loading /Users/runner/work/mimir/mimir/packages/flutter_mimir/example/integration_test/movies_test.dart (failed)
2023-01-31T14:26:29.2775410Z TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
2023-01-31T14:26:29.3489100Z package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
2023-01-31T14:26:29.3490380Z dart:async/zone.dart 1390:47                      _rootRun
2023-01-31T14:26:29.3491190Z dart:async/zone.dart 1300:19                      _CustomZone.run
2023-01-31T14:26:29.3491840Z package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
2023-01-31T14:26:29.3519450Z package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
2023-01-31T14:26:29.3523480Z dart:async/zone.dart 1398:13                      _rootRun
2023-01-31T14:26:29.3568720Z dart:async/zone.dart 1300:19                      _CustomZone.run
2023-01-31T14:26:29.3572670Z package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
2023-01-31T14:26:29.3575560Z dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
2023-01-31T14:26:29.3576600Z dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
2023-01-31T14:26:29.3577980Z dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
2023-01-31T14:26:29.3579570Z dart:isolate-patch/isolate_patch.dart 192:26      _RawReceivePort._handleMessage
2023-01-31T14:26:29.3581270Z ##[endgroup]
```

</details>

Actually looks like it is the same issue as reported above.

**Comment by exaby73** [comment]
Hey everyone. Please do upvote the original comment (https://github.com/flutter/flutter/issues/118469#issue-1532806344) with a thumbs up as this allows the team to further prioritize issues. Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#thumbs-up-reactions for more information about how the team uses this information :)

**Comment by stuartmorgan** [comment]
@cbracken FYI: it appears that dropping OpenGL support has impacted a number of CI systems. Do we support software rendering mode with `flutter drive`?

**Comment by cbracken** [comment]
> Do we support software rendering mode with flutter drive?

I'll take a look into this. That seems reasonable, though I suspect there'll be some limitations when it comes to things like PlatformViews and using external Metal textures.

**Comment by Lyokone** [comment]
I think it was fixed in the latest macos-13 runners for GitHub action.

**Comment by Gustl22** [comment]
@Lyokone indeed, the tests now also run with recent versions of flutter with `macos-13` image on GitHub Actions. On the `macos-12` image it still fails.

I wrote a little test to validate, but it did not return any Metal device, so I suspect it is magically handled via the CPU (?).

```yaml
  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: swift test-metal.swift
```

```swift
// test-metal.swift
import Metal
import Darwin

let device = MTLCreateSystemDefaultDevice()
if device == nil {
    print("This device does not support Metal")
    exit(1)
}

print("This device is supporting Metal")
dump(device)
```

**Comment by desistefanova** [comment]
We don't have this issue anymore. It can be closed. 
Thanks about the support!

**Comment by exaby73** [comment]
@huycozy Can you please confirm this? I was able to reproduce this issue based on https://github.com/flutter/flutter/issues/118469#issuecomment-1406604477

**Comment by huycozy** [comment]
@exaby73 The issue still persists on CircleCI as @vegaro's comment above.

**Comment by cbracken** [comment]
@vegaro does CircleCI offer a macOS image that has GPU passthrough enabled? That's what was required to fix this on GitHub Actions, which is a requirement for Metal-specific apps.

**Comment by vegaro** [comment]
@cbracken I talked to CircleCI and this was their answer

> After speaking with our engineering team, there is no GPU access with the Intel Machines and you will need to utilize the M1 medium or large resource class to have access. 

I have confirmed that using an M1 machine in CircleCI fixes the issue 🤷‍♂️ I don't think there's an alternative

**Comment by cbracken** [comment]
@Skycoder42 can you provide the error messages in your logs that confirm weather is the same issue as before (`Unable to create FlutterView; no MTLDevice or MTLCommandQueue available`)? If not, this could well be an unrelated issue, in which case, once you've got a minimal repro that shows it's Flutter-related, please file a new issue with details.

**Comment by cbracken** [comment]
I think it's unlikely that we'll be able to resolve this issue satisfactorily with a change in Flutter. We aren't going to be resurrecting the OpenGL backend for the reasons [mentioned here](https://github.com/flutter/flutter/issues/120154#issuecomment-1500945622), and the underlying issue isn't specifically a Flutter issue but rather that some VM images on some CI providers don't enable GPU passthrough, which also impacts many non-Flutter apps. 

The best path forward is likely to file an issue with the CI provider demonstrating the bug. The [code sample](https://github.com/flutter/flutter/issues/118469#issuecomment-1521594859) provided by @Gustl22 above is sufficient to demonstrate the issue.

One potential path forward would be for us to add a software backend for the macOS embedder. This won't work for all apps (e.g. we won't be able to support PlatformViews with the software backend), and is likely to require non-trivial engineering investment.

I'll leave this issue open for the time being, but as we aren't likely to be working actively on this issue in the near term, I'll remove the assignment.

**Comment by Gustl22** [comment]
I wonder, if its possible to run a Flutter app on OpenGL via the `--enable-impeller` flag.
https://support.apple.com/en-us/101525
It seems that it is also enabled for macos: https://github.com/flutter/engine/blob/2a48302f6f4e3564030f071a7d9fce392aac12d7/impeller/tools/args.gni#L16

But still getting the [error](https://github.com/flutter/engine/blob/2a48302f6f4e3564030f071a7d9fce392aac12d7/shell/platform/darwin/macos/framework/Source/FlutterViewController.mm#L413):
```
Could not acquire Metal device.
Unable to create FlutterView; no MTLDevice or MTLCommandQueue available.
```

**Comment by cbracken** [comment]
Since this issue was related to GPU passthrough being disabled on CI providers and the requirement of GPU support was intentional in Flutter, I am going to close this issue.
