### ISSUE TITLE
Crash on iOS at GrGLGpu

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#11862]
## Steps to Reproduce

Crash was recorded on user's iOS device.
iOS version is 10.3.3.

## Logs

```
Crashed: io_thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001
0  libGPUSupportMercury.dylib     0x19e805fac gpus_ReturnNotPermittedKillClient + 12
1  AGXGLDriver                    0x1a33dce00 gldUpdateDispatch + 7156
2  libGPUSupportMercury.dylib     0x19e806f88 gpusSubmitDataBuffers + 176
3  AGXGLDriver                    0x1a33de30c gldUpdateDispatch + 12544
4  Flutter                        0x100d9af14 GrGLGpu::prepareTextureForCrossContextUsage(GrTexture*) + 128
5  Flutter                        0x100db8d18 SkImage::MakeCrossContextFromEncoded(GrContext*, sk_sp<SkData>, bool, SkColorSpace*) + 560
6  Flutter                        0x100b12488 std::__1::__function::__func<ftl::internal::CopyableLambda<blink::(anonymous namespace)::DecodeImageFromList(_Dart_NativeArguments*)::$_1>, std::__1::allocator<ftl::internal::CopyableLambda<blink::(anonymous namespace)::DecodeImageFromList(_Dart_NativeArguments*)::$_1> >, void ()>::operator()() + 200
7  Flutter                        0x100b07f48 fml::MessageLoopImpl::RunExpiredTasks() + 872
8  Flutter                        0x100b0a84c fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
9  CoreFoundation                 0x18e799aa4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
10 CoreFoundation                 0x18e7997a8 __CFRunLoopDoTimer + 856
11 CoreFoundation                 0x18e799068 __CFRunLoopDoTimers + 244
12 CoreFoundation                 0x18e796c8c __CFRunLoopRun + 1484
13 CoreFoundation                 0x18e6c6da4 CFRunLoopRunSpecific + 424
14 Flutter                        0x100b0a970 fml::MessageLoopDarwin::Run() + 88
15 Flutter                        0x100b08074 fml::MessageLoopImpl::DoRun() + 56
16 Flutter                        0x100b0a49c std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*) + 220
17 libsystem_pthread.dylib        0x18d8ad68c _pthread_body + 240
18 libsystem_pthread.dylib        0x18d8ad59c _pthread_body + 282
19 libsystem_pthread.dylib        0x18d8aacb4 thread_start + 4
```

Crashlytics shows "OpenGL rendering while app in background state".

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Users/foo/Develop/flutter
    • Framework revision 8c2c502257 (7 days ago), 2017-08-23 17:07:59 -0700
    • Engine revision 51775c77a9
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/foo/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.5)
    • Flutter plugin version 16.0
    • Dart plugin version 171.4694.29
```

**Comment by eseidelGoogle** [comment]
I believe @cbracken recently fixed this?

**Comment by chinmaygarde** [comment]
This was fixed in https://github.com/flutter/engine/pull/4002

**Comment by najeira** [comment]
Revision 8c2c502257 includes that fix.
After the fix, the error decreased. However, some crash still occurs.

**Comment by cbracken** [comment]
> Revision 8c2c502 includes that fix. After the fix, crashes decreased. However, some crashes still occurs.

Will take a look, but just to double-check, @najeira this is occurring on the version of the app that's incorporated the above fix -- i.e. that it's not coming from users who haven't yet upgraded to the fixed version?

**Comment by najeira** [comment]
@cbracken This is occurring both before and after the fix.

**Comment by collinjackson** [comment]
Posse is seeing this crash in their latest 1.3 release. It is their top crasher.

Perhaps significantly, it only seems to appear on iPhone 6 and below. I'm seeing it on both iOS10 and iOS11.

**Comment by najeira** [comment]
@collinjackson If it helps you, I'd like to share links of crash reports in our Crashlytics.

**Comment by collinjackson** [comment]
That would be helpful, thank you.

**Comment by collinjackson** [comment]
Here's Hamilton's stack trace

<img width="832" alt="screen shot 2017-10-12 at 10 28 27 am" src="https://user-images.githubusercontent.com/394889/31509973-247f6594-af38-11e7-9361-d02010c3f34d.png">

**Comment by Hixie** [comment]
@cbracken says this is on his radar but no ETA at this time.

**Comment by xster** [comment]
For record, this bug is unrelated to GPU instructions in background issue. Comments #2-#6 are referring to a different issue (#11639) that's unrelated to this issue.

**Comment by xster** [comment]
I think the most likely path is

Main thread
------------
image_provider.dart -> ImageProvider.load() -> decodeImage()
image_decoder.dart -> decodeImageFromList()
image_decoding.cc -> DecodeImageFromList()

IO thread
---------
image_decoding.cc -> DecodeImageAndInvokeImageCallback() -> DecodeImage
third_party/skia/src/image/SkImage_Gpu.cpp -> SkImage::MakeCrossContextFromEncoded()
third_party/skia/src/gpu/gl/GrGLGpu.cc -> prepareTextureForCrossContextUsage()

Interesting part of the stack
```
Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: SEGV_NOOP at 0x0000000000000001
Crashed Thread: 7

Application Specific Information:
Attempted to dereference garbage pointer 0x1.

Thread 7 Crashed:
0   libGPUSupportMercury.dylib      0x32808ffac         gpus_ReturnNotPermittedKillClient
1   AGXGLDriver                     0x3315ebe00         gldUpdateDispatch
2   libGPUSupportMercury.dylib      0x328090f88         gpusSubmitDataBuffers
3   AGXGLDriver                     0x3315ed30c         gldUpdateDispatch
4   Flutter                         0x100812a84         GrGLGpu::prepareTextureForCrossContextUsage(GrTexture*)
5   Flutter                         0x1005aced8         std::__1::__function::__func<fxl::internal::CopyableLambda<blink::(anonymous namespace)::DecodeImageFromList(_Dart_NativeArguments*)::$_1>, std::__1::allocator<fxl::internal::CopyableLambda<blink::(anonymous namespace)::DecodeImageFromList(_Dart_NativeA...
```

Given that it's device specific (exactly iOS devices with A7, A8 chips), there's a part of the SkImage_Gpu code that checks for the GrContext's cross context texture support. Perhaps that toggle can make it safe.

**Comment by bsalomon** [comment]
@brianosman

**Comment by xster** [comment]
Test idea, scroll down a big list of images which schedules a bunch of decodes, then background the app. See if the calls to stop the rasterizer from issuing GPU instructions doesn't block the decoders from issuing GPU instructions.

**Comment by xster** [comment]
@amirh found a way to repro 
https://paste.googleplex.com/5064629906571264

**Comment by xster** [comment]
The callstack does indeed point to background GL operations being the cause https://developer.apple.com/library/content/qa/qa1766/_index.html

**Comment by brianosman** [comment]
Yes (as does the repro case). Seems like any IO thread work (calls to
MakeCrossContextFromEncoded, specifically) needs to be finished/stopped
when being backgrounded.

**Comment by xster** [comment]
So we were chatting about this offline. We can add some control logic around the SkImage logic but we noticed there's a whole bunch of semaphores inside Skia too. Are there any public-ish APIs that we can reuse to suspend certain classes operations?

**Comment by xster** [comment]
Caveat: like the live reports indicate, it also seems like this is only enforced on older iDevices with A7/A8 chips. 

The decoding continues in the background for later devices.

**Comment by xster** [comment]
More stack:

![screen shot 2017-11-20 at 7 01 07 pm](https://user-images.githubusercontent.com/156888/33052751-309b92b0-ce25-11e7-9784-21ddc2676a34.png)

It's the call to glFlush that crashes. 

Not familiar with the code path that doesn't use crossContextTextureSupport but it actually continues to run in the background on A7/A8 devices.

**Comment by xster** [comment]
In fact, if I don't flush here https://github.com/google/skia/blob/ef59d87ae8cd998eede62e7dfd46882cdfcc1817/src/gpu/gl/GrGLGpu.cpp#L4582
everything works ok. 

@brianosman, is there mode or public API we can use to reduce the scope of this fix or do you still think we should do it at a higher level? 

To wrap this, we essentially would try to detect the device type and then prevent any usage of the GrContext which is a bit more invasive.

**Comment by brianosman** [comment]
Some explanation:
The semaphores referenced in that code path are GPU semaphores - the CPU never blocks. Those are simply inserted in the GL command stream to synchronize access to the texture between the two GL contexts (IO vs GL threads). The model is that the IO thread issues some commands to generate and populate the texture, then issues a command that signals a (GPU) semaphore, and then flushes*. Later, when the image is first used by the GPU thread, we insert a command that waits on the same semaphore. This guarantees that the GPU doesn't reorder reads of the texture before all writes have finished.

The flush is necessary in this case. Without it, the commands to populate the texture and (more importantly) signal the semaphore may never be sent to the GPU -- they can be buffered in the driver. In that case, the GPU itself could simply hang the first time that it tries to access that image.

The code path that doesn't use crossContextTextureSupport will always work, but skips doing any GL work on the IO thread. Instead, it defers that work to the GPU thread - the decoding and uploading happens the first time the image is drawn. This isn't ideal, as it sacrifices all the parallelism of the IO thread.

So, there isn't currently a way to block within the API. I do think a higher level approach is necessary - Skia doesn't have any knowledge of app lifecycle, and the correct solution (I think) is to synchronize the IO thread's usage of the GrContext with entering and leaving background state. I think just having a mutex that's locked while calling any of the MakeCrossContext factories, and also from applicationDidEnterBackground (then released in whatever the mirror to that is)?

**Comment by xster** [comment]
Ah cool, thanks. That was exactly the kind of context I was looking for.

**Comment by xster** [comment]
Thanks for your help @brianosman!

**Comment by najeira** [comment]
The number has decreased, but we still have it in our app with Flutter v0.2.1.

```
Crashed: io_thread
0  libGPUSupportMercury.dylib     0x1a1380ee8 gpus_ReturnNotPermittedKillClient + 12
1  AGXGLDriver                    0x1a559d228 gldUpdateDispatch + 7296
2  libGPUSupportMercury.dylib     0x1a1381ecc gpusSubmitDataBuffers + 176
3  AGXGLDriver                    0x1a559e724 gldUpdateDispatch + 12668
4  Flutter                        0x101a2b724 GrGLGpu::prepareTextureForCrossContextUsage(GrTexture*) + 148
5  Flutter                        0x101a57048 SkImage::MakeCrossContextFromEncoded(GrContext*, sk_sp<SkData>, bool, SkColorSpace*) + 580
6  Flutter                        0x1017baf88 std::__1::__function::__func<fxl::internal::CopyableLambda<blink::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1>, std::__1::allocator<fxl::internal::CopyableLambda<blink::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1> >, void ()>::operator()() + 632
7  Flutter                        0x1017b3afc fml::MessageLoopImpl::RunExpiredTasks() + 2428
8  Flutter                        0x1017b4914 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
9  CoreFoundation                 0x185f86fc0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
10 CoreFoundation                 0x185f86ce4 __CFRunLoopDoTimer + 864
11 CoreFoundation                 0x185f864e4 __CFRunLoopDoTimers + 248
12 CoreFoundation                 0x185f840cc __CFRunLoopRun + 1928
13 CoreFoundation                 0x185ea3e58 CFRunLoopRunSpecific + 436
14 Flutter                        0x1017b47a0 fml::MessageLoopDarwin::Run() + 88
15 Flutter                        0x1017b41bc std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*) + 272
16 libsystem_pthread.dylib        0x185c042b4 _pthread_body + 308
17 libsystem_pthread.dylib        0x185c04180 _pthread_body + 310
18 libsystem_pthread.dylib        0x185c02b74 thread_start + 4
```

```
[✓] Flutter (Channel unknown, v0.2.1, on Mac OS X 10.12.6 16G1314, locale ja-JP)
    • Flutter version 0.2.1 at /Applications/flutter
    • Framework revision 6f5bcb97a4 (8 weeks ago), 2018-03-08 15:01:37 -0800
    • Engine revision 24cf8ebd86
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.23.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1
```
