### ISSUE TITLE
Impeller, Emojis Became Black

### ISSUE THREAD

**Issue by jostney** [flutter/flutter#118866]
I saw this issue [107413](https://github.com/flutter/flutter/issues/107413). I'am still having it (Emojis are black) Why this issue is closed ?

It's running on real device (Iphone 12)

Info.plist

```
<key>FLTEnableImpeller</key>
<true/>
```

And flutter doctor
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.4 21F79 darwin-x64, locale en-TR)
    • Flutter version 3.3.10 on channel stable at /Users/myuser/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/myuser/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/myuser/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Users/myuser/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • MI 6 (mobile)             • 66eafcf3                  • android-arm64 • Android 9 (API 28)
    • XYZs IPhone (mobile) • 00008101-0006014A2278001E • ios           • iOS 15.6.1 19G82
    • macOS (desktop)           • macos                     • darwin-x64    • macOS 12.4 21F79 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by jonahwilliams** [comment]
The issue was closed because it was fixed. However, we're not cherry picking impeller fixes to the previous stable, since Impeller itself has been under heavy development since then. If you're interested in trying out impeller please use the latest betas, or wait for a future stable release.

**Comment by litang0908** [comment]
This problem still exists on latest master channel. 
But it's occasionally, if switch pages and come back, it is normal again.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/44760239/220268086-a71c21e6-75c9-4d92-84ee-9f55dcb3bf78.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/44760239/220268042-41732e2b-fa3b-4675-98f9-45b860eabd48.png">


Here is the flutter doctor -v 
```
Flutter (Channel master, 3.8.0-13.0.pre.98, on macOS 12.0.1 21A559 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.8.0-13.0.pre.98 on channel master at /Users/tangyc/Documents/softs2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4245389900 (2 days ago), 2023-02-18 21:53:13 -0500
    • Engine revision 1b71ea81a0
    • Dart version 3.0.0 (build 3.0.0-257.0.dev)
    • DevTools version 2.21.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/tangyc/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/tangyc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A1030d
    • CocoaPods version 1.11.3

```
