### ISSUE TITLE
Flutter 3.7 breaks TextField widgets that wrap MaterialApp.router

### ISSUE THREAD

**Issue by percula** [flutter/flutter#119849]
## Steps to Reproduce

After updating to Flutter 3.7, when a TextField gains focus, the keyboard appears but then immediately is dismissed. This issue was originally reported [here](https://github.com/wiredashio/wiredash-sdk/issues/262). I have confirmed that this issue does not occur in Flutter v3.3. This bug only occurs when a Router is used and only seems to occur for TextFields that are outside the `MaterialApp` in the widget tree. It is _not_ specific to the [wiredash](https://pub.dev/packages/wiredash) package. I've tested it with [flappy](https://pub.dev/packages/flappy) and the same thing happens.

1. Download the [Wiredash sample repo](https://github.com/percula/wiredash_test)
2. Run the sample on an iOS or Android device. There is no need to provide the Wiredash `projectId` or `secret`.
3. Tap the FAB to bring up the Wiredash interface
4. Try to type in the `TextField`

**Expected results:** 
The keyboard will appear and remain.

**Actual results:** 
The keyboard appears and immediately dismisses.

![216086169-621711f4-49f7-4e1e-a127-5a971b4c53a6](https://user-images.githubusercontent.com/16809252/216428514-4a868de7-04fb-4d38-bf0b-5a532cef3ae8.gif)

<details>
<summary>Code sample</summary>

See the [sample project](https://github.com/percula/wiredash_test).

</details>

<details>
  <summary>Logs</summary>

```
[+9897 ms] D/InputMethodManager(18732): showSoftInput() view=io.flutter.embedding.android.FlutterView{71fcbaf VFED..... .F....ID 0,0-1080,2337 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[  +35 ms] W/OnBackInvokedCallback(18732): OnBackInvokedCallback is not enabled for the application.
[        ] W/OnBackInvokedCallback(18732): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[  +17 ms] D/InsetsController(18732): show(ime(), fromIme=true)
```

```
+9897 ms] D/InputMethodManager(18732): showSoftInput() view=io.flutter.embedding.android.FlutterView{71fcbaf VFED..... .F....ID 0,0-1080,2337 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[  +35 ms] W/OnBackInvokedCallback(18732): OnBackInvokedCallback is not enabled for the application.
[        ] W/OnBackInvokedCallback(18732): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[  +17 ms] D/InsetsController(18732): show(ime(), fromIme=true)
```

```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
[!] Flutter (Channel stable, 3.7.1, on macOS 12.6 21G115 darwin-arm64, locale en-US)
    • Flutter version 3.7.1 on channel stable at /Users/peter/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.16.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/peter/development/flutter. Consider adding
      /Users/peter/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (26 hours ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/peter/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.6+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • adb-28281FBH2003ZL-0vnWNw._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos                                            • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)     • chrome                                           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @percula 
I do see the same behavior on latest stable (3.7.1) running on iOS device, but the behavior seem to be working as expected on latest master.


https://user-images.githubusercontent.com/67046386/216567176-922f5622-6c66-4462-8b57-b667cf9fa55c.MP4



> This bug only occurs when a Router is used and only seems to occur for TextFields that are outside the `MaterialApp` in the widget tree

I tried to come up with a code sample for this scenario, but using it, I was unable to replicate the same behavior on latest stable.  I used `go_router` example and had a `TextField` upon navigating to another screen and then tapping on it, as below:

<details>
<summary> code sample </summary>

```

// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () => context.go('/details'),
              child: const Text('Go to the Details screen'),
            ),
          ],
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(),
            ElevatedButton(
              onPressed: () => context.go('/'),
              child: const Text('Go back to the Home screen'),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

If you could narrow it down to only framework's navigator implementation without using wiredash, it'll be helpful to analyze what could be causing this behavior in latest stable. Also check by switching to latest master at your end since the issue doesn't persist on it per above verification.

**Comment by percula** [comment]
@passsy Would you be able to create a super-simple sample that replicates what Wiredash is doing? I tried, but apparently it's not as simple as wrapping the app in a column with a `TextField` above it 😉.

**Comment by percula** [comment]
@darshankawar I can confirm that the issue no longer exists on the latest master. I'm looking through the commits on `Navigator` to see if anything looks like it might have fixed it. If we can identify the fix, any chance this could go into a hotfix on the stable channel?

**Comment by passsy** [comment]
Awesome, that's very good news!

You should be able to identify the commit with `git bisect`. Once we know the commit I can ask it to be cherry-picked. Since it is a regression and the release was last week we have good chances to get it approved.

**Comment by percula** [comment]
The commit that fixes this issue is `a45727d81360b278cc51c5a9ae429529038cf069`.

**Comment by passsy** [comment]
Makes sense, because Wiredash wraps the app with `MediaQuery`. Removing the WidgetsApps dependency on `MediaQuery`, prevents it from rebuilding and requesting focus.

**Comment by passsy** [comment]
I was able to create a repro example, that shows that the Navigator requests focus when wrapped with any widget even when it is not focused.



<table>
<tr>
	<td>With Flutter 3.3</td>
	<td>With Flutter 3.7</td>
    <td>on master Flutter 3.8.0-4.0.pre.21</td>
<tr>
<td>

https://user-images.githubusercontent.com/1096485/216831853-c4d38615-28d9-40c2-8ff7-d7694882b7a4.mp4

</td>
<td>

https://user-images.githubusercontent.com/1096485/216831667-22a3a94c-46ec-467e-9a96-c7652c338eca.mp4
</td>
<td>

https://user-images.githubusercontent.com/1096485/216831722-66ced2f8-2ac4-400c-bd06-a7f6b07c5522.mp4

</td>
</table>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const Issue119849());
}

class Issue119849 extends StatefulWidget {
  const Issue119849({Key? key}) : super(key: key);

  @override
  State<Issue119849> createState() => _Issue119849State();
}

class _Issue119849State extends State<Issue119849> {
  final appKey = GlobalKey(debugLabel: 'app');
  final _focusNode = FocusNode();
  bool _focused = false;

  @override
  void initState() {
    super.initState();
    _focusNode.addListener(() {
      print('focusNode.hasFocus: ${_focusNode.hasFocus}');
      setState(() {
        _focused = _focusNode.hasFocus;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return NotAWidgetsApp(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          ColoredBox(
            color: _focused ? Colors.red : const Color(0xFF333333),
            child: SizedBox(
              height: 400,
              child: Localizations(
                delegates: const [
                  DefaultMaterialLocalizations.delegate,
                  DefaultWidgetsLocalizations.delegate,
                  DefaultCupertinoLocalizations.delegate,
                ],
                locale: const Locale('en', 'US'),
                child: MaterialSupportLayer(
                  child: SafeArea(
                    child: Padding(
                      padding: const EdgeInsets.all(32),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Padding(
                            padding: EdgeInsets.only(bottom: 16),
                            child: Text(
                                "WidgetsApp (below) requests when wrapped in widget in Flutter 3.7.\n\n"
                                "Tap the TextField to open the keyboard which changes MediaQuery insets."),
                          ),
                          TextField(
                            decoration: const InputDecoration(
                              border: OutlineInputBorder(),
                              labelText: "Tap me",
                            ),
                            focusNode: _focusNode,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 20),
          Expanded(
            child: ColoredBox(
              color: const Color(0xFFddeedd),
              child: Builder(builder: (context) {
                // This widget is wrapped in a KeyedSubtree to prevent keep the state
                // but it will be moved (wrapped)
                final app = KeyedSubtree(
                  key: appKey,
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: App(),
                  ),
                );

                if (_focused) {
                  // Changing the position of WidgetsApp in the widget tree
                  // causes it to request focus
                  return ColoredBox(
                    color: const Color(0xFF333333),
                    // Wrapping with any widget causes the issue
                    child: SizedBox(
                      child: app,
                    ),
                  );
                } else {
                  return ColoredBox(
                    // No SizedBox!
                    color: Colors.red,
                    child: app,
                  );
                }
              }),
            ),
          ),
        ],
      ),
    );
  }
}

class App extends StatefulWidget {
  App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const HomePage(),
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    // The issue does not happen with Navigator on any Flutter version
    // return const MaterialApp(
    //   color: Colors.white,
    //   home: HomePage(),
    // );

    // Issue happens only with Router
    // Works with Flutter 3.3
    // Broken with Flutter 3.7.1
    // Broken with Flutter 3.8.0-4.0.pre.21 revision 61f6a0bcd4
    return MaterialApp.router(
      color: Colors.white,
      routerConfig: router,
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color(0xFF0000FF),
        title: const Text('WidgetsApp'),
      ),
      backgroundColor: Colors.white,
      body: const Center(
        child: Padding(
          padding: EdgeInsets.all(32),
          child: TextField(),
        ),
      ),
    );
  }
}

/// Wrapper with default that most widgets required that are now wrapped by a
/// [WidgetsApp]
class NotAWidgetsApp extends StatefulWidget {
  const NotAWidgetsApp({
    required this.child,
    this.textDirection,
    Key? key,
  }) : super(key: key);

  final Widget child;

  final TextDirection? textDirection;

  @override
  State<NotAWidgetsApp> createState() => _NotAWidgetsAppState();
}

class _NotAWidgetsAppState extends State<NotAWidgetsApp> {
  final GlobalKey _childKey = GlobalKey(debugLabel: 'WidgetsApp child');

  @override
  Widget build(BuildContext context) {
    Widget child = KeyedSubtree(
      key: _childKey,
      child: widget.child,
    );

    // Any Text requires a directionality
    child = Directionality(
      textDirection: widget.textDirection ?? TextDirection.ltr,
      child: child,
    );

    final parentMq = MediaQuery.maybeOf(context);
    if (parentMq == null) {
      // Inject a MediaQuery with information from the app window
      child = MediaQuery.fromWindow(
        child: child,
      );
    }

    return child;
  }
}

/// Provides parent Widgets that are required by material widgets that are
/// not wrapped into an [MaterialApp]
class MaterialSupportLayer extends StatefulWidget {
  const MaterialSupportLayer({
    Key? key,
    required this.child,
  }) : super(key: key);

  final Widget child;

  @override
  State<MaterialSupportLayer> createState() => _MaterialSupportLayerState();
}

class _MaterialSupportLayerState extends State<MaterialSupportLayer> {
  OverlayEntry? _entry;

  @override
  void didUpdateWidget(covariant MaterialSupportLayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Rebuild wrapped widget tree when something changes
    // This fixes Hot-Reload
    _entry?.markNeedsBuild();
  }

  @override
  Widget build(BuildContext context) {
    //Overlay is required for text edit functions such as copy/paste on mobile
    _entry = OverlayEntry(
      builder: (context) {
        // use a stateful widget as direct child or hot reload will not
        // work for that widget
        return widget.child;
      },
    );

    Widget child = Overlay(initialEntries: [_entry!]);

    child = Theme(
      data: ThemeData.dark(),
      child: child,
    );

    // Make Wiredash a Material widget to support TextFields, etc.
    child = Material(
      textStyle: DefaultTextStyle.of(context).style,
      color: Colors.transparent,
      child: child,
    );

    // allow text editing (i.e. select all, delete on macos)
    child = DefaultTextEditingShortcuts(
      child: child,
    );

    return child;
  }
}
```

This is code is working fine in Flutter 3.3, but not in 3.7 and also not on master.

I did not exactly find the root cause. But the major difference I discovered is that when the `TextField` is tapped the Navigator now runs through this code branch (`hasFocus == true`), whereas it was running through the other branch (`hasFocus == false`) with Flutter `3.3`.


<img width="1104" alt="Screen-Shot-2023-02-05-17-18-15 65" src="https://user-images.githubusercontent.com/1096485/216831252-4d2446a1-b405-4603-8918-22b95b696ec9.png">

https://github.com/flutter/flutter/blob/b8f5394a5ca6d2bce062d9d0a20aaffb4289fb4c/packages/flutter/lib/src/widgets/focus_manager.dart#L1299-L1311

`setFirstFocus` is called by the router 

https://github.com/flutter/flutter/blob/b8f5394a5ca6d2bce062d9d0a20aaffb4289fb4c/packages/flutter/lib/src/widgets/routes.dart#L888-L893

**Comment by percula** [comment]
@passsy This is interesting, when I'm on `master` (or add the lines from the [gist](https://gist.github.com/percula/53931260f13d2d34512e30ee37e8d835) I created) in my sample project with Wiredash, the issue does not occur, even after updating the sample to use a `StatefulWidget` as you mentioned in the Wiredash issue. However, when I use your simplified code above, I get the same result as you.

**Comment by darshankawar** [comment]
Thanks for providing the updated and a minimal reproducible code sample. Using it, I was able to verify that the functionality is not working on latest stable and master, but works as expected on previous stable (3.3.10).

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (28 hours ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-4.0.pre, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.8.0-4.0.pre on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f5394a5c (22 hours ago), 2023-02-04 23:06:19 -0800
    • Engine revision 2a104cdfcd
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Labeling this as a regression

**Comment by darshankawar** [comment]
Maybe related: https://github.com/flutter/flutter/issues/119798

**Comment by kirill-21** [comment]
Does anybody have the problem that after Flutter 3.7.0 nothing happens when you input anything to the TextField? On your recording there is some problem with un-focusing, but for me focus works all right, the issue is with input

```
return SizedBox(
      width: scale(widget.width),
      child: TextField(
        controller: widget.controller,
      ),
    );
```

Issue appears only on MacOS(windows/android are good). 

![image](https://user-images.githubusercontent.com/63228361/217579929-59b41a4a-0a6e-482f-ab12-ab829a66be6d.png)

May it be related?

**Comment by passsy** [comment]
@kirill-21 Please open a separate issue

**Comment by kirill-21** [comment]
> @kirill-21 Please open a separate issue

https://github.com/flutter/flutter/issues/120680

**Comment by Doflatango** [comment]
Is this issue will get fixed in the future hot releases?

**Comment by ylruiz** [comment]
Is there any update regarding this issue?

**Comment by gspencergoog** [comment]
I've been doing some bisecting (which was complicated by dependency on a package and the release branches having a very old common ancestor), and it appears that the change that broke go_router is flutter/flutter#109702 which removes the embedded focus scope in the Navigator because it had a history of causing issues with nested navigators.

To fix your problem, wrap the app with a FocusScope.

Here's your reproduction case, modified with a focus scope:
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const Issue119849());
}

class Issue119849 extends StatefulWidget {
  const Issue119849({Key? key}) : super(key: key);

  @override
  State<Issue119849> createState() => _Issue119849State();
}

class _Issue119849State extends State<Issue119849> {
  final appKey = GlobalKey(debugLabel: 'app');
  final _focusNode = FocusNode();
  bool _focused = false;

  @override
  void initState() {
    super.initState();
    _focusNode.addListener(() {
      debugPrint('focusNode.hasFocus: ${_focusNode.hasFocus}');
      setState(() {
        _focused = _focusNode.hasFocus;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return NotAWidgetsApp(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          ColoredBox(
            color: _focused ? Colors.red : const Color(0xFF333333),
            child: SizedBox(
              height: 400,
              child: Localizations(
                delegates: const [
                  DefaultMaterialLocalizations.delegate,
                  DefaultWidgetsLocalizations.delegate,
                  DefaultCupertinoLocalizations.delegate,
                ],
                locale: const Locale('en', 'US'),
                child: MaterialSupportLayer(
                  child: SafeArea(
                    child: Padding(
                      padding: const EdgeInsets.all(32),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Padding(
                            padding: EdgeInsets.only(bottom: 16),
                            child: Text(
                                "WidgetsApp (below) requests when wrapped in widget in Flutter 3.7.\n\n"
                                "Tap the TextField to open the keyboard which changes MediaQuery insets."),
                          ),
                          TextField(
                            decoration: const InputDecoration(
                              border: OutlineInputBorder(),
                              labelText: "Tap me",
                            ),
                            focusNode: _focusNode,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 20),
          Expanded(
            child: ColoredBox(
              color: const Color(0xFFddeedd),
              child: Builder(builder: (context) {
                // This widget is wrapped in a KeyedSubtree to prevent keep the state
                // but it will be moved (wrapped)
                final app = KeyedSubtree(
                  key: appKey,
                  child: Padding(
                    padding: const EdgeInsets.all(32),
                    child: App(),
                  ),
                );

                if (_focused) {
                  // Changing the position of WidgetsApp in the widget tree
                  // causes it to request focus
                  return ColoredBox(
                    color: const Color(0xFF333333),
                    // Wrapping with any widget causes the issue
                    child: SizedBox(
                      child: app,
                    ),
                  );
                } else {
                  return ColoredBox(
                    // No SizedBox!
                    color: Colors.red,
                    child: app,
                  );
                }
              }),
            ),
          ),
        ],
      ),
    );
  }
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const HomePage(),
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    // The issue does not happen with Navigator on any Flutter version
    // return const MaterialApp(
    //   color: Colors.white,
    //   home: HomePage(),
    // );

    // Issue happens only with Router
    // Works with Flutter 3.3
    // Broken with Flutter 3.7.1
    // Broken with Flutter 3.8.0-4.0.pre.21 revision 61f6a0bcd4
    return FocusScope(
      child: MaterialApp.router(
        color: Colors.white,
        routerConfig: router,
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color(0xFF0000FF),
        title: const Text('WidgetsApp'),
      ),
      backgroundColor: Colors.white,
      body: const Center(
        child: Padding(
          padding: EdgeInsets.all(32),
          child: TextField(),
        ),
      ),
    );
  }
}

/// Wrapper with default that most widgets required that are now wrapped by a
/// [WidgetsApp]
class NotAWidgetsApp extends StatefulWidget {
  const NotAWidgetsApp({
    required this.child,
    this.textDirection,
    Key? key,
  }) : super(key: key);

  final Widget child;

  final TextDirection? textDirection;

  @override
  State<NotAWidgetsApp> createState() => _NotAWidgetsAppState();
}

class _NotAWidgetsAppState extends State<NotAWidgetsApp> {
  final GlobalKey _childKey = GlobalKey(debugLabel: 'WidgetsApp child');

  @override
  Widget build(BuildContext context) {
    Widget child = KeyedSubtree(
      key: _childKey,
      child: widget.child,
    );

    // Any Text requires a directionality
    child = Directionality(
      textDirection: widget.textDirection ?? TextDirection.ltr,
      child: child,
    );

    final parentMq = MediaQuery.maybeOf(context);
    if (parentMq == null) {
      // Inject a MediaQuery with information from the app window
      child = MediaQuery.fromWindow(
        child: child,
      );
    }

    return child;
  }
}

/// Provides parent Widgets that are required by material widgets that are
/// not wrapped into an [MaterialApp]
class MaterialSupportLayer extends StatefulWidget {
  const MaterialSupportLayer({
    Key? key,
    required this.child,
  }) : super(key: key);

  final Widget child;

  @override
  State<MaterialSupportLayer> createState() => _MaterialSupportLayerState();
}

class _MaterialSupportLayerState extends State<MaterialSupportLayer> {
  OverlayEntry? _entry;

  @override
  void didUpdateWidget(covariant MaterialSupportLayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Rebuild wrapped widget tree when something changes
    // This fixes Hot-Reload
    _entry?.markNeedsBuild();
  }

  @override
  Widget build(BuildContext context) {
    //Overlay is required for text edit functions such as copy/paste on mobile
    _entry = OverlayEntry(
      builder: (context) {
        // use a stateful widget as direct child or hot reload will not
        // work for that widget
        return widget.child;
      },
    );

    Widget child = Overlay(initialEntries: [_entry!]);

    child = Theme(
      data: ThemeData.dark(),
      child: child,
    );

    // Make Wiredash a Material widget to support TextFields, etc.
    child = Material(
      textStyle: DefaultTextStyle.of(context).style,
      color: Colors.transparent,
      child: child,
    );

    // allow text editing (i.e. select all, delete on macos)
    child = DefaultTextEditingShortcuts(
      child: child,
    );

    return child;
  }
}
```

**Comment by passsy** [comment]
Thanks @gspencergoog, that works! I was able to work around the issue for now.

But there's still some exploration left, figuring out what kind of side-effects the `FocusScope` introduces. I was not able to only wrap the app in a `FocusScope` while Wiredash is open, because removing the `FocusScope` throws: 

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Focused child does not have the same idea of its enclosing scope as the scope does.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 1236 pos 12: '_focusedChildren.isEmpty ||
_focusedChildren.last.enclosingScope == this'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      FocusScopeNode.focusedChild (package:flutter/src/widgets/focus_manager.dart:1236:12)
#3      FocusScopeNode._doRequestFocus (package:flutter/src/widgets/focus_manager.dart:1323:17)
#4      FocusNode.unfocus (package:flutter/src/widgets/focus_manager.dart:884:15)
#5      FocusAttachment.detach (package:flutter/src/widgets/focus_manager.dart:176:15)
#6      _FocusState.dispose (package:flutter/src/widgets/focus_scope.dart:570:23)
#7      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5179:11)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1960:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#25     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#31     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#43     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#55     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#61     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#64     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#67     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#73     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#85     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#91     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#97     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#103    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#106    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#115    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#118    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#127    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#130    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#154    _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:67:14)
#155    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#156    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#157    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#158    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#159    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#160    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#161    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#162    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#164    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#165    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#166    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#167    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#168    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#169    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#170    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#171    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#172    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#173    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#174    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#175    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#176    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#177    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#178    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#179    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#180    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#181    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#182    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#183    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#184    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#185    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#186    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#187    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#188    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#189    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#190    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#191    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#192    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#193    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#194    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#195    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#196    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#197    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#198    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#199    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#200    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#201    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1958:7)
#202    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#203    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1956:13)
#204    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#205    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1969:25)
#206    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2601:15)
#207    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3023:7)
#208    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1356:19)
#209    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#210    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#211    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#212    AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1282:5)
#213    runApp (package:flutter/src/widgets/binding.dart:1019:7)
#214    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:942:7)
```

Wiredash now always wraps the app in a `FocusScope`, as `WidgetsApp` did before. Does that mean that Wiredash users will run into similar issues with Nested Routing?

**Comment by gspencergoog** [comment]
Okay, can you file a new issue for that?  I don't think I'll be able to tell exactly what the issue is until I know the details of how you're using it.

As for the nested navigator issue, it mainly comes up when there are two panels, each with their own navigator: before I removed the `FocusScope` from `Navigator`, it was impossible to use tab traversal between the two panels because you'd get trapped in one scope.  I think as long as you don't wrap more than one app, it'll probably be fine for your customers: the problem arose because there were two `FocusScope`s in that scenario, and you should only ever have one.

**Comment by callmhejerry** [comment]
Please I still have the same issue, I’m using flutter 3.10

**Comment by Doflatango** [comment]
> Please I still have the same issue, I’m using flutter 3.10

I'm still using Flutter 3.3 due to this bug 😅

**Comment by callmhejerry** [comment]
Omg It should have been resolved by now , do you know how I can downgrade to v3.3

**Comment by Doflatango** [comment]
> Omg It should have been resolved by now , do you know how I can downgrade to v3.3

@callmhejerry
You just download the Flutter 3.3.x from https://docs.flutter.dev/release/archive?tab=windows , then replace the Flutter SDK directory where you installed before, and then run `flutter clean` and `flutter pub get` under your project.

**Comment by andr3i4o** [comment]
Hi, is there going to be a solution soon on this, it still doesn't work for the last few major updates.

**Comment by masdeval** [comment]
Any news about this?

**Comment by gspencergoog** [comment]
@puspharaj-teachspot I understand you are frustrated, but please re-read our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md?rgh-link-date=2023-11-16T12%3A26%3A42Z) in regard to respectful and welcoming communication.

**Comment by Metin137** [comment]
I add global navigatorKey for GoRouter and this solve issue for me.

**Comment by divan** [comment]
Spent two days hunting a bug with Maestro testing of Flutter web build of the app. Reached the same conlcusions and workaround almost word-by-word. It's literally a stopper for our testing pipeline.

Is there a way bump up this in priority? 3 years without fixing seems like a bit of a stretch.
