### ISSUE TITLE
[CP] Serious problem bug with SystemChrome.setPreferredOrientations when use it with an iPad with iOS 16

### ISSUE THREAD

**Issue by csacchetti** [flutter/flutter#121107]
### issue_link

#121007

### Commit Hash

6ea01e6

### Target

stable

### pr_link

https://github.com/flutter/flutter/blob/stable/bin/internal/release-candidate-branch.version

### Impacted Users

The orientation does not function correctly and this creates serious problems

### Impact Description

The orientations do not function correctly and this creates serious problems because once the landscape mode is set for one page, when you return to the others with all the available orientations it remains in landscape

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by Eimji** [comment]
This bug is really a serious regression, especially for applications playing videos only in landscape.

Please merge the fix into the next stable update.

**Comment by itsjustkevin** [comment]
@csacchetti please open a cherry pick pull request to the branch you pointed to in the PR Link section. 

Once that is updated and the correct link to the Cherry pick is provided, we will review.

**Comment by csacchetti** [comment]
This is my first time requesting a cherry pick and I am not very familiar with it. The commit hash is correct but I don't know how to find the pr_link. I would ask for this commit to be added to the next release of flutter 3.7.6. But I don't know what to do now.

**Comment by itsjustkevin** [comment]
@csacchetti it is okay if you are not familiar with the process, let me walk you through it. 

1.  `git checkout master` // fetch and pull the latest changes from master.
2.  `git checkout flutter-3.7-candidate.1` // This is the same branch you posted in the pr_link section.
3.  `git checkout -b <your local branch name for cherry-picking`
4.  `git cherry-pick 6ea01e6` // cherry pick this into your local branch.
5.  Push it up to github as a PR.
6. Grab that link from your PR and post it in the pr_link section of this form. 

Thanks again for providing this cherry-pick request!

**Comment by Moncader** [comment]
Is there any word on a timeline for when this can get approved to be cherry pick released?
According to https://github.com/flutter/flutter/wiki/Triage this is a P0 or a P1 issue affecting all users from core functionality.

**Comment by jmagman** [comment]
I was asked about hotfixing this in the issue https://github.com/flutter/flutter/issues/111587#issuecomment-1307840441, fixed in PR https://github.com/flutter/engine/pull/37302:

> > Any plans for pulling this change into 3.3.x line?
> 
> We generally reserve hot fixes for very high priority fixes, like that the app won't compile, or it crashes for a high percentage of users.
> 
> > Stability of the release will be the overarching goal, so only high impactful and critical cherrypicks will be allowed across Dart and Flutter.
> 
> https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

I don't think this is worth cherrypicking to stable.  It is available on 3.6.0-0.0.pre which is currently in the beta channel.

**Comment by itsjustkevin** [comment]
Thank you for pointing this out @jmagman!  Wth that, I am closing this cherry-pick request.

**Comment by johannesvuorinen** [comment]
This commit seems to be already merged to 3.7 (checked myself with local engine) and the issue unfortunately seems to persist at least on iOS 16

**Comment by Moncader** [comment]
@itsjustkevin @jmagman 
The author of this issue incorrectly pointed to the wrong engine fix.
https://github.com/flutter/engine/pull/38230
This is the one we need to solve this issue.
It's merged in to beta but is not in stable.

**Comment by jmagman** [comment]
@Moncader Please open a new cherry-pick request for https://github.com/flutter/flutter/issues/116711 then, this request is all over the place and it's too confusing.

**Comment by Moncader** [comment]
@jmagman 
We found a workaround that doesn't require a custom engine build and runs on 3.7.7 and are using that now. So we don't require this cherry pick anymore.
If someone else wants to make it, this _is_ the PR to do it with.

Here's the code to work around this for anyone that wants it.

https://gist.github.com/Moncader/be7d7830e4bf64848e89b85f9dbc25a6
It's just a class (in swift) that extends FlutterViewController and overrides (via objc selector shenanigans) the default FlutterViewControllers orientation code with the updated code from https://github.com/flutter/engine/pull/38230

Set your storyboard to use this ViewController instead and the issue will be gone.

**Comment by itsjustkevin** [comment]
@Moncader a hot fix will release soon with this Cherry-pick.

**Comment by itsjustkevin** [comment]
It is!  https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel. 

This cherry-pick is available in Flutter 3.7.8.

**Comment by itsjustkevin** [comment]
@GabrielAraujo and @Moncader no fix landed for this one today as there is no new cherry-pick request.  If someone has a cherry-pick solution they are willing provide, I can get it in the next release!

**Comment by jmagman** [comment]
@burghoffdavid  I fixed that issue in https://github.com/flutter/engine/pull/38230, available in Flutter repo at https://github.com/flutter/flutter/pull/117005 and available in Flutter 3.7.0-7.0.pre in the beta channel. I don't know what would be referencing the packages repo.

That fix seems to be the one the subsequent commenters want cherry-picked.  Instead of commenting on this closed cherry-pick request for a different issue, please file a new cherry pick issue and fill out the template with what you actually want hotfixed.

> Please open a new cherry-pick request for #116711 then, this request is all over the place and it's too confusing.

See @itsjustkevin comment here as well https://github.com/flutter/flutter/issues/121107#issuecomment-1452074093

**Comment by alexda12** [comment]
Just tried 3.7.8 and the issue is still present (On Stable). 

Note - on Android there is no issue - its only on iOS.
