### ISSUE TITLE
Hero animation bug in Flutter 3.7 - widget is rendered both in flight and at target (duplicated)

### ISSUE THREAD

**Issue by mikeesouth** [flutter/flutter#121325]
## Steps to Reproduce

This problem occurred when upgrading from flutter stable 3.3.10 to 3.7.0 and it still persists in flutter 3.7.5. This is reproducible on iOS, Android and Windows, not sure about Mac, Linux and Impeller. This bug does not seem to happen in flutter web - not with html and not with canvaskit.

There may be more cases where this bug exists but I can reproduce it when navigating between two screens and the second screen has a FutureBuilder. When this FutureBuilder renders some kind of loading / waiting state, then the Hero chain is broken so we will not see a hero transition - that's fine. But when we're popping the route and returning to the first screen, the hero animation can be displayed and so it does - except that the widget is rendered both in flight and already at the target position so the hero widget is seen twice. This did not happen in flutter 3.3.10 and it looks weird.

https://user-images.githubusercontent.com/18122438/220886789-446e3605-1c65-4f38-9977-990089eb8bb2.mp4

I have also added a button called `Future Builder (completed)` and this shows a FutureBuilder where the Future already has a value when rendering the first time. The future builder still starts with "snapshot.hasData = false" so it displays the loading animation for 1 frame and this breaks the hero chain. It would be nice if the FutureBuilder would directly get it's data if the future is completed - that would make future builders more viable so that we can use them in cases where we sometimes need to wait for futures but if the future is already completed, it would just render the child without triggering the loading state of the future builder. Maybe that's a separate feature request but I still wanted to mention it here :)
 
1. Execute `flutter run` on the [code sample](https://github.com/mikeesouth/flutter_hero_future_builder)

**Expected results:** That the Hero animation transitions back when popping the screen from Future Builder screens.

**Actual results:** That the Hero widget is displayed both at the target position AND also rendering as a transition towards the target position. The same widget is duplicated during the hero transition.

<details>
<summary>Code sample</summary>

[flutter_hero_future_builder](https://github.com/mikeesouth/flutter_hero_future_builder)

</details>

<details>
  <summary>Logs</summary>

Flutter logs not attached, no relevant information in them.

Flutter analyze:
```
Analyzing flutter_hero_future_builder...
No issues found! (ran in 1.4s)
```

Flutter doctor:
```
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22000.1574], locale en-SE)
    • Flutter version 3.7.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (11 hours ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\micke\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.4.33403.182
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.75.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1574]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.177
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.49

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @mikeesouth, this issue seems to have been fixed on the latest master channel as I cannot reproduce it there. See the demo below.

<details>
<summary>Demo (Android)</summary>


https://user-images.githubusercontent.com/104349824/220912809-b1b52107-78e4-44fc-8a84-7014ff6807ef.mp4


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.7.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (5 hours ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.8.0-15.0.pre.18, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.8.0-15.0.pre.18 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1ba617a59c (32 minutes ago), 2023-02-22 23:33:22 -0500
    • Engine revision c4577135b5
    • Dart version 3.0.0 (build 3.0.0-266.0.dev)
    • DevTools version 2.22.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I'll be closing this issue since it has already been fixed on the latest master channel. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Comment by huycozy** [comment]
Hi @mikeesouth, thanks for confirming again.
I re-check this on my Samsung device and also can see the issue on the master channel now. 

<details>
<summary>Demo (Samsung Galaxy Tab A7 Lite, Android 13)</summary>


https://user-images.githubusercontent.com/104349824/221211287-bc9622ba-8bc7-4977-a450-efe115a5c9a1.mov


</details>

But the issue also doesn't happen on Web and MacOS apps. Can you please help to confirm this again on the Windows app (Flutter master channel) as well?

**Comment by mikeesouth** [comment]
> Hi @mikeesouth, thanks for confirming again. I re-check this on my Samsung device and also can see the issue on the master channel now.
> 
> Demo (Samsung Galaxy Tab A7 Lite, Android 13)
> But the issue also doesn't happen on Web and MacOS apps. Can you please help to confirm this again on the Windows app (Flutter master channel) as well?

Thanks for re-checking and reopening. I can confirm that this still occurs for me on Windows app with the master channel.

**Comment by jason-simmons** [comment]
This is happening because `_ZoomPageTransition` is animating a snapshot of the route by default (see https://api.flutter.dev/flutter/widgets/PageRoute/allowSnapshotting.html)

You can work around this by providing a `PageTransitionsTheme` that uses `ZoomPageTransitionsBuilder(allowEnterRouteSnapshotting: false)`

@jonahwilliams

**Comment by TahaTesser** [comment]
related to https://github.com/flutter/flutter/issues/119897 where Ink also reproduces similarly with `allowEnterRouteSnapshotting`.

**Comment by bleroux** [comment]
FYI, I bisected this to https://github.com/flutter/flutter/pull/109327. This PR enabled the work done in https://github.com/flutter/flutter/pull/106621.

https://github.com/flutter/flutter/pull/106621 was a significant performance improvement.
As shown in the repro the Hero widget animation is affected by this flag, but, what was not expected is that the snapshotting make the final position of the Hero visible before the end of the animation.

A flag was introduced to opt-out and use the previous behavior.
See https://master-api.flutter.dev/flutter/widgets/PageRoute/allowSnapshotting.html

On master one solution is to use the solution proposed in https://github.com/flutter/flutter/issues/121325#issuecomment-1447344393. I filed a PR to add an example on how to set PageTransitionsTheme, see https://github.com/flutter/flutter/pull/121701.

On stable, the workaroud is to rely on https://master-api.flutter.dev/flutter/widgets/PageRoute/allowSnapshotting.html. I will post an example tomorrow.

@jonahwilliams Do you think there is a way to fix this or is the recommended solution is to rely on PageRoute.allowSnapshotting when there is an Hero animation?

**Comment by bleroux** [comment]
On stable, the workaround  is to disable snapshotting on routes where the issue is visible.
In the given sample code, the problem is visible when popping back to FirstPage, so the following workaround rely on `MaterialApp.onGeneratedRoute` (there are probably other options):

<details>
<summary>Updated code sample with workaround for stable</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

const heroTag = 'hero321';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hero animations with FutureBuilder',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      onGenerateRoute: (RouteSettings settings) {
        if (settings.name == '/') {
          return MaterialPageRoute(
            builder: (_) => const FirstPage(),
            allowSnapshotting: false,
          );
        }
      },
    );
  }
}

class FirstPage extends StatelessWidget {
  const FirstPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Center(
            child: Hero(
              tag: heroTag,
              child: FlutterLogo(size: 300),
            ),
          ),
          Wrap(
            spacing: 20.0,
            runSpacing: 20.0,
            children: [
              _buildButton(
                context,
                'No Future Builder',
                const PageWithoutFuture(),
              ),
              _buildButton(
                context,
                'Future Builder (completed)',
                const PageWithFuture(futureCompleted: true),
              ),
              _buildButton(
                context,
                'Future Builder (delay)',
                const PageWithFuture(futureCompleted: false),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildButton(BuildContext ctx, String buttonText, Widget secondPage) {
    return MaterialButton(
      color: Colors.blue,
      textColor: Colors.white,
      padding: const EdgeInsets.all(20.0),
      onPressed: () => Navigator.of(ctx)
          .push(MaterialPageRoute(builder: (ctx) => secondPage)),
      child: Text(buttonText),
    );
  }
}

class PageWithoutFuture extends StatelessWidget {
  const PageWithoutFuture({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Hero(
        tag: heroTag,
        child: FlutterLogo(size: 300),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.of(context).pop(),
        child: const Icon(Icons.chevron_left),
      ),
    );
  }
}

class PageWithFuture extends StatefulWidget {
  final bool futureCompleted;

  const PageWithFuture({super.key, required this.futureCompleted});

  @override
  State<PageWithFuture> createState() => _PageWithFutureState();
}

class _PageWithFutureState extends State<PageWithFuture> {
  late Future _initFuture;

  @override
  void initState() {
    super.initState();

    if (widget.futureCompleted) {
      _initFuture = Future.value(true);
    } else {
      _initFuture = Future.delayed(const Duration(seconds: 1), () => true);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder(
        future: _initFuture,
        builder: (context, snapshot) {
          if (snapshot.hasError || !snapshot.hasData) {
            return const Text('Waiting!', style: TextStyle(fontSize: 20));
          }

          return const Hero(
            tag: heroTag,
            child: FlutterLogo(size: 300),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.of(context).pop(),
        child: const Icon(Icons.chevron_left),
      ),
    );
  }
}

```
</details>

**Comment by mikeesouth** [comment]
Thanks for the replies here, I'm not sure what the new labels mean and I understand the snapshotting feature and how to disable it. Thanks for the quick fix @jason-simmons and thanks for the example @bleroux. I saw the related issue from @TahaTesser and I have found more cases where this is an issue, e.g. when changing translations from one language to another in a settings screen. When popping back, the snapshotted route is still in the old language so it animates in with the old language and then flips back to the new language when the screen is loaded. Or when changing theme from light to dark in a settings screen. I guess these are also related to snapshotting.

It's great with the performance increase and for most users I think it's the right choice so it should be default. But it would be really sweet to have some kind of easier/automatic detection when snapshotting won't work. E.g. when I change language, can I burn all snapshots so that Navigator.pop() won't use the outdated snapshot?

In my case I will probably disable route snapshotting altogether since it's kind of complex to see in which specific cases where I can't use it and disable it for these specific routes.

But in the end, I can see the issue as resolved and answered. I will close this issue but I'm not sure if it's actually supposed to be kept open based on the team-design and retriage labels. Feel free to reopen it if that's the case.

**Comment by gnprice** [comment]
The new labels are for identifying which team is responsible for triaging the issue:
https://github.com/flutter/flutter/wiki/Triage#triage-process-for-teams
The bot assigned them heuristically based on existing labels; it included a label saying it was unsure, and I think in fact the heuristic was wrong here, so will fix the labels.

There is a workaround, but it'd be great to find a way to do better by default, so it's helpful to leave the issue open to track that. Even if the issue stays open a long time (though hopefully it gets fixed instead), that's helpful because it means that other people running into this can gather on the same issue, which is better than having a series of separate issues that are all closed.
