### ISSUE TITLE
Unable to build docker image for flutter web application

### ISSUE THREAD

**Issue by bkoryon** [flutter/flutter#121339]
## Steps to Reproduce

1. Execute: docker build -t flutter-web-test3:latest  to build a docker image
3. Here's a sample of my dockerfile: 

<-------------------------------------------------------------------------> 
```
FROM instrumentisto/flutter:latest as build-env

# Add the following two lines
ARG API_URL
ENV API_URL=$API_URL

# Clone the flutter repo
#RUN  git clone https://github.com/flutter/flutter.git -b stable /usr/local/flutter

# Set flutter path
#ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

# # Enable flutter web
#RUN  flutter channel stable
#RUN  flutter upgrade
# RUN  flutter config --enable-web

# RUN rm -rf /usr/local/flutter/bin/cache

RUN flutter config --enable-web

# Run flutter doctor
RUN  flutter doctor -v

# Copy the app files to the container
COPY . /usr/local/bin/app

# Set the working directory to the app files within the container
WORKDIR /usr/local/bin/app

# Get App Dependencies
RUN  flutter clean

# Get App Dependencies
RUN  flutter pub get

# Build the app for the web
RUN  flutter build web --dart-define API_URL=${API_URL:-}

# Document the exposed port
EXPOSE 5000

# Set the server startup script as executable
RUN  ["chmod", "+x", "/usr/local/bin/app/server/server.sh"]

# Start the web server
ENTRYPOINT [ "/usr/local/bin/app/server/server.sh" ]

```

<-------------------------------------------------------------------------------> 

**Expected results: Docker image for web application builds successfully

**Actual results:
```
💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.

#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             84.2s
Exception: Failed to compile application for the Web.
The command '/bin/sh -c flutter build web --dart-define API_URL=${API_URL:-}' returned a non-zero code: 1
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
Step 11/14 : RUN  flutter build web --dart-define API_URL=${API_URL:-} -v
 ---> Running in f7618cf44692
[  +88 ms] executing: uname -m
[  +56 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/usr/local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c07f7888888435fd9df505aa2efc38d3cf65681b
[        ] executing: [/usr/local/flutter/] git tag --points-at c07f7888888435fd9df505aa2efc38d3cf65681b
[  +12 ms] Exit code 0 from: git tag --points-at c07f7888888435fd9df505aa2efc38d3cf65681b
[        ] 3.7.5
[  +18 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +25 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +75 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +102 ms] Skipping pub get: version match.
[   +5 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/usr/local/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] Found plugin audio_session at /usr/local/flutter/.pub-cache/hosted/pub.dev/audio_session-0.1.13/
[  +12 ms] Found plugin camera at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera-0.10.3/
[   +3 ms] Found plugin camera_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_android-0.10.4/
[   +3 ms] Found plugin camera_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_avfoundation-0.9.11/
[   +4 ms] Found plugin camera_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_web-0.3.1+1/
[   +9 ms] Found plugin device_info_plus at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus-3.2.4/
[   +2 ms] Found plugin device_info_plus_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_linux-2.1.1/
[   +6 ms] Found plugin device_info_plus_macos at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_macos-2.2.3/
[   +3 ms] Found plugin device_info_plus_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_web-2.1.0/
[   +2 ms] Found plugin device_info_plus_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_windows-2.1.1/
[  +15 ms] Found plugin flutter_plugin_android_lifecycle at /usr/local/flutter/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[  +14 ms] Found plugin just_audio at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio-0.9.31/
[   +3 ms] Found plugin just_audio_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio_web-0.4.7/
[  +18 ms] Found plugin path_provider at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[   +8 ms] Found plugin path_provider_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[   +2 ms] Found plugin path_provider_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[   +2 ms] Found plugin path_provider_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[   +5 ms] Found plugin path_provider_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_windows-2.0.7/
[  +17 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences-2.0.17/
[   +3 ms] Found plugin shared_preferences_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.15/
[   +1 ms] Found plugin shared_preferences_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.3/
[   +1 ms] Found plugin shared_preferences_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.3/
[   +7 ms] Found plugin shared_preferences_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.4/
[   +3 ms] Found plugin shared_preferences_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.3/
[  +29 ms] Found plugin video_player at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player-2.5.1/
[   +3 ms] Found plugin video_player_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_android-2.3.10/
[   +2 ms] Found plugin video_player_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.3.8/
[   +4 ms] Found plugin video_player_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_web-2.0.13/
[  +19 ms] Found plugin integration_test at /usr/local/flutter/packages/integration_test/
[  +44 ms] Found plugin audio_session at /usr/local/flutter/.pub-cache/hosted/pub.dev/audio_session-0.1.13/
[   +2 ms] Found plugin camera at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera-0.10.3/
[        ] Found plugin camera_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_android-0.10.4/
[   +1 ms] Found plugin camera_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_avfoundation-0.9.11/
[   +4 ms] Found plugin camera_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_web-0.3.1+1/
[   +7 ms] Found plugin device_info_plus at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus-3.2.4/
[        ] Found plugin device_info_plus_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_linux-2.1.1/
[   +2 ms] Found plugin device_info_plus_macos at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_macos-2.2.3/
[   +2 ms] Found plugin device_info_plus_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_web-2.1.0/
[   +1 ms] Found plugin device_info_plus_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_windows-2.1.1/
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at /usr/local/flutter/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +4 ms] Found plugin just_audio at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio-0.9.31/
[   +1 ms] Found plugin just_audio_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio_web-0.4.7/
[   +6 ms] Found plugin path_provider at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[   +1 ms] Found plugin path_provider_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[        ] Found plugin path_provider_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[   +1 ms] Found plugin path_provider_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[   +3 ms] Found plugin path_provider_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_windows-2.0.7/
[   +6 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences-2.0.17/
[   +1 ms] Found plugin shared_preferences_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.15/
[        ] Found plugin shared_preferences_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.3/
[   +1 ms] Found plugin shared_preferences_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.3/
[   +1 ms] Found plugin shared_preferences_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.4/
[   +1 ms] Found plugin shared_preferences_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.3/
[   +9 ms] Found plugin video_player at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player-2.5.1/
[        ] Found plugin video_player_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_android-2.3.10/
[        ] Found plugin video_player_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.3.8/
[   +1 ms] Found plugin video_player_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_web-2.0.13/
[  +10 ms] Found plugin integration_test at /usr/local/flutter/packages/integration_test/
[  +64 ms] Found plugin audio_session at /usr/local/flutter/.pub-cache/hosted/pub.dev/audio_session-0.1.13/
[   +1 ms] Found plugin camera at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera-0.10.3/
[        ] Found plugin camera_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_android-0.10.4/
[        ] Found plugin camera_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_avfoundation-0.9.11/
[   +1 ms] Found plugin camera_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_web-0.3.1+1/
[   +3 ms] Found plugin device_info_plus at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus-3.2.4/
[        ] Found plugin device_info_plus_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_linux-2.1.1/
[        ] Found plugin device_info_plus_macos at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_macos-2.2.3/
[   +1 ms] Found plugin device_info_plus_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_web-2.1.0/
[        ] Found plugin device_info_plus_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_windows-2.1.1/
[   +6 ms] Found plugin flutter_plugin_android_lifecycle at /usr/local/flutter/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +5 ms] Found plugin just_audio at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio-0.9.31/
[   +2 ms] Found plugin just_audio_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio_web-0.4.7/
[   +6 ms] Found plugin path_provider at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[   +1 ms] Found plugin path_provider_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[        ] Found plugin path_provider_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[   +1 ms] Found plugin path_provider_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_windows-2.0.7/
[   +4 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences-2.0.17/
[        ] Found plugin shared_preferences_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.15/
[   +1 ms] Found plugin shared_preferences_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.3/
[   +2 ms] Found plugin shared_preferences_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.3/
[   +1 ms] Found plugin shared_preferences_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.4/
[        ] Found plugin shared_preferences_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.3/
[   +7 ms] Found plugin video_player at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player-2.5.1/
[        ] Found plugin video_player_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_android-2.3.10/
[   +1 ms] Found plugin video_player_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.3.8/
[   +1 ms] Found plugin video_player_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_web-2.0.13/
[   +9 ms] Found plugin integration_test at /usr/local/flutter/packages/integration_test/
[ +106 ms] Generating /usr/local/bin/app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +120 ms] 💪 Building with sound null safety 💪
[  +16 ms] Found plugin audio_session at /usr/local/flutter/.pub-cache/hosted/pub.dev/audio_session-0.1.13/
[   +2 ms] Found plugin camera at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera-0.10.3/
[        ] Found plugin camera_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_android-0.10.4/
[   +3 ms] Found plugin camera_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_avfoundation-0.9.11/
[   +4 ms] Found plugin camera_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_web-0.3.1+1/
[   +4 ms] Found plugin device_info_plus at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus-3.2.4/
[   +1 ms] Found plugin device_info_plus_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_linux-2.1.1/
[   +1 ms] Found plugin device_info_plus_macos at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_macos-2.2.3/
[   +1 ms] Found plugin device_info_plus_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_web-2.1.0/
[   +3 ms] Found plugin device_info_plus_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_windows-2.1.1/
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at /usr/local/flutter/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +3 ms] Found plugin just_audio at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio-0.9.31/
[   +1 ms] Found plugin just_audio_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio_web-0.4.7/
[   +5 ms] Found plugin path_provider at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[   +1 ms] Found plugin path_provider_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[   +1 ms] Found plugin path_provider_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[   +1 ms] Found plugin path_provider_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_windows-2.0.7/
[   +4 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences-2.0.17/
[        ] Found plugin shared_preferences_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.15/
[        ] Found plugin shared_preferences_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.3/
[   +1 ms] Found plugin shared_preferences_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.3/
[   +1 ms] Found plugin shared_preferences_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.4/
[        ] Found plugin shared_preferences_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.3/
[   +7 ms] Found plugin video_player at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player-2.5.1/
[        ] Found plugin video_player_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_android-2.3.10/
[   +4 ms] Found plugin video_player_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.3.8/
[   +2 ms] Found plugin video_player_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_web-2.0.13/
[   +9 ms] Found plugin integration_test at /usr/local/flutter/packages/integration_test/
[   +2 ms] generated_plugin_registrant.dart not found. Skipping.
[   +2 ms] Compiling lib/main.dart for the Web...
[  +11 ms] Initializing file store
[  +52 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /usr/local/flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart}
[   +2 ms] Skipping target: gen_localizations
[   +3 ms] web_static_assets: Starting due to {}
[ +162 ms] web_static_assets: Complete
[  +11 ms] Found plugin audio_session at /usr/local/flutter/.pub-cache/hosted/pub.dev/audio_session-0.1.13/
[   +2 ms] Found plugin camera at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera-0.10.3/
[   +3 ms] Found plugin camera_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_android-0.10.4/
[   +2 ms] Found plugin camera_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_avfoundation-0.9.11/
[   +2 ms] Found plugin camera_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/camera_web-0.3.1+1/
[   +3 ms] Found plugin device_info_plus at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus-3.2.4/
[        ] Found plugin device_info_plus_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_linux-2.1.1/
[   +1 ms] Found plugin device_info_plus_macos at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_macos-2.2.3/
[   +1 ms] Found plugin device_info_plus_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_web-2.1.0/
[        ] Found plugin device_info_plus_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/device_info_plus_windows-2.1.1/
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at /usr/local/flutter/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +4 ms] Found plugin just_audio at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio-0.9.31/
[   +2 ms] Found plugin just_audio_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/just_audio_web-0.4.7/
[   +3 ms] Found plugin path_provider at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[        ] Found plugin path_provider_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[   +1 ms] Found plugin path_provider_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[   +1 ms] Found plugin path_provider_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/path_provider_windows-2.0.7/
[   +4 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences-2.0.17/
[        ] Found plugin shared_preferences_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.15/
[        ] Found plugin shared_preferences_foundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.3/
[        ] Found plugin shared_preferences_linux at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.3/
[   +1 ms] Found plugin shared_preferences_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.4/
[   +3 ms] Found plugin shared_preferences_windows at /usr/local/flutter/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.3/
[  +10 ms] Found plugin video_player at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player-2.5.1/
[        ] Found plugin video_player_android at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_android-2.3.10/
[   +1 ms] Found plugin video_player_avfoundation at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.3.8/
[   +2 ms] Found plugin video_player_web at /usr/local/flutter/.pub-cache/hosted/pub.dev/video_player_web-2.0.13/
[   +5 ms] Found plugin integration_test at /usr/local/flutter/packages/integration_test/
[   +2 ms] web_entrypoint: Complete
[   +2 ms] dart2js: Starting due to {}
[   +8 ms] compiling dart code to kernel with command "/usr/local/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /usr/local/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --libraries-spec=/usr/local/flutter/bin/cache/flutter_web_sdk/libraries.json --native-null-assertions -Ddart.vm.product=true -DAPI_URL= -DFLUTTER_WEB_AUTO_DETECT=true --no-source-maps -o /usr/local/bin/app/.dart_tool/flutter_build/bb9a11f2f75b098586b898a875cd41fd/app.dill --packages=.dart_tool/package_config.json --cfe-only /usr/local/bin/app/.dart_tool/flutter_build/bb9a11f2f75b098586b898a875cd41fd/main.dart"
[+85200 ms] Persisting file store
[   +5 ms] Done persisting file store
[   +8 ms] Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.

           #0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
           <asynchronous suspension>
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
           <asynchronous suspension>
           #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
           <asynchronous suspension>
           #7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
           <asynchronous suspension>
           #8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
           <asynchronous suspension>
           #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[  +31 ms] Compiling lib/main.dart for the Web... (completed in 85.6s)
[   +4 ms] "flutter web" took 86,669ms.
[   +5 ms] Exception: Failed to compile application for the Web.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:101:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +6 ms] ensureAnalyticsSent: 2ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
The command '/bin/sh -c flutter build web --dart-define API_URL=${API_URL:-} -v' returned a non-zero code: 1

```

```
flutter analyze
Analyzing ai_studio_mobile_app...                                       
No issues found! (ran in 2.7s)
```

```
Step 5/14 : RUN  flutter doctor -v
 ---> Running in 4dc5d25e4a31
[✓] Flutter (Channel stable, 3.7.5, on Ubuntu 22.04.2 LTS 5.15.78-0-virt, locale en_US.UTF-8)
    • Flutter version 3.7.5 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (16 hours ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.2 LTS 5.15.78-0-virt

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment]
@bkoryon Can you retry on the latest beta or master channel to check if it works?

**Comment by bkoryon** [comment]
I get the same error with the beta or mater branch. When I build with version 2.10.0 it works but the flutter.js file is not generated.

**Comment by SergiMartinezNunez** [comment]
Hi, 
I'm having the same issue building a web docker image after I executed a flutter upgrade (now I have flutter 3.7.5 and dart 2.19.2). I've tried different things like:

```# # Install Operating system and dependencies
# FROM ubuntu:20.04
#
# RUN apt-get update
# RUN DEBIAN_FRONTEND=noninteractive TZ=Europe/Madrid apt-get -y install tzdata
# RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 ninja-build pkg-config libgtk-3-dev cmake clang
# RUN apt-get clean
#
# # download Flutter SDK from Flutter Github repo
# RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
#
# # Set flutter environment path
# ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"
#
# # Run flutter doctor
# RUN flutter doctor -v
#
# # Enable flutter web
# RUN flutter channel master
# RUN flutter upgrade
# RUN flutter config --enable-web
#
# # Copy files to container and build
# RUN mkdir /app/
# COPY . /app/
# WORKDIR /app/
# RUN flutter clean
# RUN flutter pub get
# RUN flutter build web
#
# # Record the exposed port
# EXPOSE 5000
#
# # make server startup script executable and start the web server
# RUN ["chmod", "+x", "/app/server/server.sh"]
#
# ENTRYPOINT [ "/app/server/server.sh"]

# ----------------------------------------------------
# # Install Operating system and dependencies
# FROM ubuntu:20.04
#
# RUN apt-get update
# RUN DEBIAN_FRONTEND=noninteractive TZ=Europe/Madrid apt-get -y install tzdata
# RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 ninja-build pkg-config libgtk-3-dev cmake
# RUN apt-get clean
#
# # download Flutter SDK from Flutter Github repo
# RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
#
# # Set flutter environment path
# ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"
#
# # Run flutter doctor
# # RUN flutter doctor
#
# # Enable flutter web
# RUN flutter channel master
# RUN flutter upgrade
# RUN flutter config --enable-web
#
# # Add dependencies for dart compile js
# RUN apt-get install -y build-essential
# RUN apt-get install -y zlib1g-dev
#
# # Copy files to container and build
# RUN mkdir /app/
# COPY . /app/
# WORKDIR /app/
# RUN flutter clean
# RUN flutter pub get
# # RUN dart compile js -m -o web/main.dart.js web/main.dart
# RUN flutter build web
# # Record the exposed port
# EXPOSE 5000
#
# # make server startup script executable and start the web server
# RUN ["chmod", "+x", "/app/server/server.sh"]
#
# ENTRYPOINT [ "/app/server/server.sh"]

# -----------------------------------------------------------------

FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Europe/Madrid apt-get -y install tzdata && \
    apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 ninja-build pkg-config libgtk-3-dev cmake clang && \
    apt-get clean

# Download Flutter SDK from Flutter Github repo
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter

# Set flutter environment path
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

# Run flutter doctor
RUN flutter doctor

# Enable flutter web
RUN flutter channel master && \
    flutter upgrade && \
    flutter config --enable-web

# Add dependencies for dart compile js
RUN apt-get install -y build-essential && \
    apt-get install -y zlib1g-dev

# Copy files to container and build
RUN mkdir /app/
COPY . /app/
WORKDIR /app/
RUN flutter pub get && \
    flutter build web

# Record the exposed port
EXPOSE 5000

# Make server startup script executable and start the web server
RUN ["chmod", "+x", "/app/server/server.sh"]
ENTRYPOINT [ "/app/server/server.sh"]```

And the build ends with this error message: 


```#15 30.14 Error: Compilation failed.
#15 30.14
#15 30.14 #0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:235:7)
#15 30.14 <asynchronous suspension>
#15 30.14 #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
#15 30.14 <asynchronous suspension>
#15 30.14 #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
#15 30.14 <asynchronous suspension>
#15 30.14 #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
#15 30.14 <asynchronous suspension>
#15 30.14 #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
#15 30.14 <asynchronous suspension>
#15 30.14 #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
#15 30.14 <asynchronous suspension>
#15 30.14 #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
#15 30.14 <asynchronous suspension>
#15 30.14 #7      buildWeb (package:flutter_tools/src/web/compile.dart:54:32)
#15 30.14 <asynchronous suspension>
#15 30.14 #8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:140:5)
#15 30.14 <asynchronous suspension>
#15 30.14 #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1287:27)
#15 30.14 <asynchronous suspension>
#15 30.14 #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
#15 30.14 <asynchronous suspension>
#15 30.14 #11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
#15 30.14 <asynchronous suspension>
#15 30.14 #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
#15 30.14 <asynchronous suspension>
#15 30.14 #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
#15 30.14 <asynchronous suspension>
#15 30.14 #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:226:5)
#15 30.14 <asynchronous suspension>
#15 30.14 #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
#15 30.14 <asynchronous suspension>
#15 30.14 #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
#15 30.14 <asynchronous suspension>
#15 30.14 #17     main (package:flutter_tools/executable.dart:91:3)
#15 30.14 <asynchronous suspension>
#15 30.14
#15 30.14 Compiling lib/main.dart for the Web...                              8.7s
#15 30.14 Exception: Failed to compile application for the Web.
------
executor failed running [/bin/sh -c flutter pub get &&     flutter build web]: exit code: 1```

Any idea? Thanks in advance!

**Comment by huycozy** [comment]
Can you confirm if the project can run/build normally (run/build directly from your machine)? Also, can you check if the issue is also happening on a new empty Flutter project (counter app)?

**Comment by bkoryon** [comment]
The project builds fine with no issues on my machine but when I try building a docker image I get errors. It is also happening on an empty flutter project.

**Comment by SergiMartinezNunez** [comment]
> Can you confirm if the project can run/build normally (run/build directly from your machine)? Also, can you check if the issue is also happening on a new empty Flutter project (counter app)?

I've created a new project and worked fine with a counter app. Then tried to remove all the dependencies from my project and didn't work, here's my pubspec.yaml.
```
name: seleccio_esportiva_375
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # flutter_svg: ^2.0.1
  # carousel_slider: ^4.2.1
  # smooth_page_indicator: ^1.0.1
  # flutter_launcher_icons: ^0.12.0
  # flutter_native_splash: ^2.0.1+1
  # auto_size_text: ^3.0.0
  # email_validator: ^2.1.17

#flutter_native_splash:
#  image: "assets/png/logo.png"
#  color: "#FFFFFF"
#  web: false

# flutter_icons:
#  image_path: "assets/png/logo.png"
#  android: true
#  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/logo.png
    - assets/png/app_background.png
```

**Comment by akmaljalilov** [comment]
I have this issue, too.

**Comment by firdavs97-cloud** [comment]
Same issue. Is there any good news?

**Comment by huycozy** [comment]
@bkoryon I tried your Dockerfile but it lead to another error:

<details>
<summary>Logs (@bkoryon Dockerfile)</summary>

```bash
 => ERROR [6/9] RUN  flutter clean                                                                                                                                     0.7s
------
 > [6/9] RUN  flutter clean:
#10 0.250    Woah! You appear to be trying to run flutter as root.
#10 0.250    We strongly recommend running the flutter tool without superuser privileges.
#10 0.250   /
#10 0.250 📎
#10 0.625 Error: No pubspec.yaml file found.
#10 0.625 This command should be run from the root of your Flutter project.
------
executor failed running [/bin/sh -c flutter clean]: exit code: 1

```
</details>

But when I tried this sample: https://github.com/edwardinubuntu/flutter-web-dockerfile, it ran well:

<details>
<summary>Logs (only snippet logs of docker build output)</summary>

```bash
...
 => [build-env  2/13] RUN apt-get update                                                                                                                               5.3s
 => [build-env  3/13] RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3                   56.0s
 => [build-env  4/13] RUN apt-get clean                                                                                                                                0.4s
 => [build-env  5/13] RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter                                                                         61.7s
 => [build-env  6/13] RUN flutter doctor -v                                                                                                                          104.7s
 => [build-env  7/13] RUN flutter channel master                                                                                                                       2.4s
 => [build-env  8/13] RUN flutter upgrade                                                                                                                              1.8s
 => [build-env  9/13] RUN flutter config --enable-web                                                                                                                  1.5s
 => [build-env 10/13] RUN mkdir /app/                                                                                                                                  0.3s
 => [build-env 11/13] COPY . /app/                                                                                                                                     0.4s
 => [build-env 12/13] WORKDIR /app/                                                                                                                                    0.0s
 => [build-env 13/13] RUN flutter build web                                                                                                                           63.9s
 => [stage-1 2/2] COPY --from=build-env /app/build/web /usr/share/nginx/html                                                                                           0.1s
 => exporting to image                                                                                                                                                 0.2s
 => => exporting layers                                                                                                                                                0.2s
 => => writing image sha256:692d96d239f41a402098f6051c2658fe0fa6fab9649667886e36bbc60392ed38                                                                           0.0s
 => => naming to docker.io/library/myanimate-web      
```
</details>

<img width="907" alt="Screenshot 2023-02-28 at 12 14 47" src="https://user-images.githubusercontent.com/104349824/221824359-767ec50a-4dd1-4399-b238-fe6d79e29d63.png">

For anyone facing this issue, please try following that guideline and confirm if it works for you.

**Comment by Ashkan-Sarlak** [comment]
@huycozy Hi,
I was using cirrusci/flutter image and tried many versions of it, but I get exactly this error.
Then I changed my Dockerfile according to the one you mentioned (installing Flutter on a Debian) but the error persists.
--verbose doesn't show anything more, and the source of error is unclear.
I can build on my machine without any problem.
I should note that this seems to be relevant to the recent version of flutter (3.7.x). The app was building just fine with flutter 3.3.x and prior to that 2.10.x.

**Comment by SergiMartinezNunez** [comment]
Hi, 
I've fixed the imports in some files of my project (ex: "../**V**iews/.." -> "../**v**iews/..") and now builds the docker image. 
(It works for me on v3.7.5)
Sorry because it was my fault, thanks u all!

**Comment by bkoryon** [comment]
Changing of imports still didn't work for me. I'm still unable to build with version 3.7.7 (stable) even after generating a new project with docker build

**Comment by huycozy** [comment]
@bkoryon Have you tried the sample at https://github.com/flutter/flutter/issues/121339#issuecomment-1447917203? Does it build successfully? Or do you only have this issue with the Dockerfile at the OP?
