### ISSUE TITLE
GitHub issue locker bot should run more frequently

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#121880]
My inbox just got hammered by 70+ emails from the github issue locker bot. Can these be spread out over time, please?

**Comment by godofredoc** [comment]
This was a one off issue, the github action was failing for a long time and it was fixed yesterday night. The expectation is that after finishing locking all the pending issues it will get back to normal.

**Comment by zanderso** [comment]
It looks like this is still happening. 105 new emails after the weekend. Could the bot have a max batch size per time period, and stop even though is not yet caught up?

**Comment by godofredoc** [comment]
Unfortunately the action does not provide configurations to customize the batch size:

https://github.com/dessant/lock-threads



The good news is that the action has already locked all the pending issues. No new issues have been locked in the last few hours.

https://github.com/flutter/flutter/actions/workflows/lock.yaml

**Comment by godofredoc** [comment]
The number of lock emails has gotten back to normal.

**Comment by zanderso** [comment]
Can we use this issue to track rate-limiting the emails when there are bugs in the future?

**Comment by godofredoc** [comment]
Rate limiting the number of emails is probably a per github account configuration and not related with the action. The emails we have been receiving for issue locking are sent by github(`notifications@github.com`) based on comments to the bug. The action itself is not sending emails but going through a list of bugs adding comments and locking them.

Potential paths of action:

* a) Remove issue locker if it is not adding value and only causing noise.
* b) Run issue locker action on a different schedule e.g. once per day but not sure it will actually make a difference in the overall number of emails.
* c) Adjusting rate limiting of emails sent by github in the github UI (per github account setting if it exists)

Please let me know if you would like us to proceed with a) or b) which are the only ones infra can control.

**Comment by zanderso** [comment]
(b) sounds promising, but I'm curious what the current schedule is.

**Comment by matanlurey** [comment]
I am guessing this is not a top concern (I personally haven't seen it happen).
