### ISSUE TITLE
Flutter web rendering occasionally becomes blurry when page is expanded

### ISSUE THREAD

**Issue by elliette** [flutter/flutter#122541]
When I expand a Flutter web app, it occasionally becomes slightly blurry. I'm able to reproduce this with just the Flutter Gallery demo app by expanding it a little: https://gallery.flutter.dev/#/

A few things I've noticed:

- This doesn't always happen when expanding the app (perhaps it's dependent on certain height / width ratios)
- This doesn't seem to happen when minimizing the app
- If I IFRAME the app, then this happens every time (see CSS for the IFRAME below)

```
iframe {
    border: 0pt none;
    height: 100%;
    left: 0px;
    position: relative;
    top: 0px;
    width: 100%;
  }
```

### Demo of expanding app and having it become blurry:

![blurry expanding](https://user-images.githubusercontent.com/21270878/224781458-abf5a2b6-3f81-49b9-88e1-9ad85a86edfd.gif)

### Screenshot of blurriness once expanded:

![Screenshot 2023-03-13 at 10 32 07 AM](https://user-images.githubusercontent.com/21270878/224782997-0eb8ba35-607c-4cd5-a674-b55c374ae57d.png)

### Screenshot of same widget once I've refreshed the page (no longer blurry):

![Screenshot 2023-03-13 at 10 32 18 AM](https://user-images.githubusercontent.com/21270878/224783066-46e08636-bf1e-4468-8d6d-b2037fc2127f.png)

**Comment by elliette** [comment]
This happens pretty consistently if the page is resized horizontally (but not vertically)

**Comment by yjbanov** [comment]
Thanks for filing. I can reproduce this on recently deployed apps. Looks like a new regression.

**Comment by yjbanov** [comment]
This is not noticeable on high DPI screens. I can only see it on displays with device-pixel ratio of 1.

**Comment by talski** [comment]
I'm facing this issue too, as workaround I use this css:

```css
@media (-webkit-max-device-pixel-ratio: 1) {
	* {
		image-rendering: pixelated;
	}
}
```

**Comment by davidsomekh** [comment]
> I'm facing this issue too, as workaround I use this css:
> 
> ```css
> @media (-webkit-max-device-pixel-ratio: 1) {
> 	* {
> 		image-rendering: pixelated;
> 	}
> }
> ```

I tried - not a good solution. It makes the text in other cases blurry

**Comment by Juliotati** [comment]
> I tried - not a good solution. It makes the text in other cases blurry

@davidsomekh  try increasing the value from `1` to `2`. This worked for me, but on screens with lower resolution, it might look "weird" but doesn't change when you resize the window.

**Comment by arualana** [comment]
Is this going to be fixed soon or do I revert back to a lesser Flutter version? can I have an estimate so I can make this decision?

**Comment by rdesimone** [comment]
Easily reproducible with a MacBook Pro M1 and external 27" 1440p monitor.

**Comment by chipnetics** [comment]
My experiences: In Edge it also becomes blurry if you launch `https://gallery.flutter.dev/#/` in anything less than maximized, and then maximize.  As OP stated, it appears starting maximized and then shrinking the window is not an issue.  

I've also observed the same behavior in google-chrome-stable in Debian when developing.

I'm not convinced this is a regression however, and believe this has existed for some time.  I have a corporate web application I deployed October '22 and noticed this behavior very early on (as it also happens when debugging); I've held off until now (shamefully) to peruse github to see if others have had the same issue.

**Comment by Dall127** [comment]
Also experiencing the same with Flutter web on my MacBook Pro M1 and a 1440p external monitor. I notice that switching tabs will also do it, or dragging it from one screen (with differing resolutions) to another will also make it blurry.

**Comment by Merceran** [comment]
Still exists with Flutter 3.13.0

**Comment by aliaktas-tr** [comment]
+1

**Comment by Dinjooh** [comment]
Chiming in with the others and saying this is a pretty big setback for our web app since our focus partly is on being visually appealing. A blurry web app doesn't quite do that. 

Any update to whether this will get fixed or looked even at some point would be greatly appreciated.

**Comment by chipnetics** [comment]
I am eager for this to be solved, so I used 'fvm' to build the Counter app against old releases.  Things went blurry at the switch-over from `3.7.0-1.5.pre` to `3.8.0-10.1.pre` (Dart 3 release). Unfortunately there is 925 commits between those two releases,  so it would be too hard to build every commit to narrow it down, but maybe this helps someone else who knows where to look in the source.

**Comment by chipnetics** [comment]
I believe I tracked down the specific commit that is causing the blur.

`55e3894a8c Roll Flutter Engine from ae9e181e30c2 to 53bd4bbf9646 (3 revisions) (#118289)`

The commits prior do not cause a blur (tested immediate previous 3 and 8 random others from prior).  Starting 55e3894a8c forth the blur starts and remains.

**Comment by jdbenito-atco** [comment]
Bump. This bug is really leading to a crapy experience.

**Comment by czw299** [comment]
same

**Comment by chipnetics** [comment]
@jonahwilliams @yjbanov can we get any sort of indication when this will be looked at (re my posts above of the culrpit commit)? This has been an issue for 8 months now. I know there's a lot of flutter engine bugs being worked on, but this really seems like it should be critical. Blurry web applications since January isn't a good look for flutter web which already takes a lot of heat from other stacks! Thanks in advance. ❤️

**Comment by AMZGstudio** [comment]
Same problem here...

**Comment by TheoBodmer1** [comment]
this bug renders our flutter web site unusable! I had to downgrade to flutter 3.7.9

**Comment by aliaktas-tr** [comment]
There are many reviewers who have been waiting for months for this issue to be resolved. I don't understand how flutter developers ignore this problem. many version updates have been done and this problem still persists.

**Comment by xanana** [comment]
+1 please help

**Comment by ku4nc4** [comment]
+1 please help

**Comment by leewrigh7** [comment]
+1 agree, a major issue, not even assigned yet :( @jonahwilliams @yjbanov @harryterkelsen

**Comment by mempler** [comment]
There are so many people having this bug, it must be pushed to the highest priority possible which it already is.

Maybe add a "needs a fix asap" tag, so that's even higher priority than most critical CVEs.

**Comment by desmond206x** [comment]
This should be fixed already.. Please help us

**Comment by ravi-upadhyay-pi** [comment]
I was willing to give flutter a try. But this issue demotivated me. Back to react I guess.

**Comment by jdbenito-atco** [comment]
Just FYI for the folks having this problem. 

Building with HTML-rendering does not exhibit this problem (and at least also offers a better initial load time).

**Comment by mempler** [comment]
> Just FYI for the folks having this problem.
> 
> Building with HTML-rendering does not exhibit this problem (and at least also offers a better initial load time).

That's just an effective workaround, not an fix.

**Comment by Johannes5000** [comment]
This workaround may not be suitable for our application, because we rely on performance. 😕
I hope this issue will be resolved as soon as possible.

**Comment by chipnetics** [comment]
Honestly this bug shouldn't have even sat for more than a day. I literally point right to the commit causing it (see above), but that wasn't enough to get it fixed either apparently. 🤷‍♂️

**Comment by desmond206x** [comment]
This should be one of the most highly priotized bug

**Comment by Merceran** [comment]
Still valid for Flutter 3.16

**Comment by yjbanov** [comment]
Is anyone able to reproduce on latest `master` channel? I can no longer reproduce using the Flutter Gallery on my 1 DPR monitor. This might have been fixed by https://github.com/flutter/engine/pull/47241.

**Comment by chipnetics** [comment]
> Is anyone able to reproduce on latest `master` channel? I can no longer reproduce using the Flutter Gallery on my 1 DPR monitor. This might have been fixed by https://github.com/flutter/engine/pull/47241.

I tried the Flutter Gallery this morning, and it's still doing it on a 1920x1080 24".  Blur kicks in when starting at less than maximized and resizing the window larger. It seems to be fine when resizing smaller.

**Comment by Johannes5000** [comment]
Same here: everything appears blurry after I move and resize the window.

**Comment by yjbanov** [comment]
Thanks for confirming. We'll have to investigate again. Surprising that it's gone for me, after reproducing consistently.

**Comment by asapbox** [comment]
This case is happening in the external monitor on zooming in and out. 
I use: --web-renderer canvaskit

**Comment by mempler** [comment]
I can also confirm, it is indeed fixed on master through CanvasKit. tested on the flutter gallery, or at least i cannot reproduce it within Google Chrome.

Safari works also fine.

Firefox aswell.

So, from my standpoint: this issue has been fixed.

**Comment by chipnetics** [comment]
Definitely a gremlin. Just tested flutter gallery online on Windows 11, in Edge on 1080p 24"... and still seeing it when page is loaded less than maximized and then resized using the window border - especially when resized vertically. It's more evident the bigger the resize.

**Comment by Johannes5000** [comment]
Yep, issue is still present

**Comment by Merceran** [comment]
> Yes, the issue persists. Is any further action needed, considering the label "waiting for customer response" is still set?

Seems this Tag is wrong. No customer resoponse should be needed here. Error is explained and reproduced by a lot of people. Also @chipnetics even pointed out the commit that introduced this issue.

This is a major bug, even labeled P1 "High-priority issues at the top of the work list".
Why is nothing done here, for over half a year now?

**Comment by jpiabrantes** [comment]
For some reason the original reporter is the one that needs to post a reply 🤷🏽‍♂️

**Comment by adar2378** [comment]
We are still facing this issue! Please fix this asap, terrible experience on the web.

**Comment by benthillerkus** [comment]
> For some reason the original reporter is the one that needs to post a reply 🤷🏽‍♂️

@elliette can you try posting a reply here?

**Comment by harryterkelsen** [comment]
I have been unable to reproduce the bug on several setups. Things I've tried:

- Macbook with built-in display
- Macbook with 1440p external monitor
- Windows PC with 1440p monitor

In each setup above I've also tried setting the zoom level to 110%, 125%, and 150% and resizing and have still been unable to reproduce the blurriness. Can someone who is able to reproduce the issue please post their setup along with the output of `flutter doctor`? I will try to reproduce on my Linux workstation tomorrow.

**Comment by harryterkelsen** [comment]
Ah, I am able to reproduce the bug with the Flutter gallery that is hosted at https://gallery.flutter.dev/ but not when building and running the gallery locally with the latest engine. I can consistently get the hosted gallery to be blurry by resizing:

![Screenshot 2023-12-27 at 3 52 48 PM](https://github.com/flutter/flutter/assets/1961493/d09c3617-24da-46be-b653-725f7a5ec838)

I noticed that when the app is blurry, the canvas size and the CSS size are off by one:

![Screenshot 2023-12-27 at 3 53 13 PM](https://github.com/flutter/flutter/assets/1961493/25f8e9a9-32fd-4ead-9e7a-d20cbbdfe95b)

I also noticed that the version Flutter engine that the gallery was built with is from June 2 (hash [54293721816abeb0c8fe9ed629d9897a7527fc13](https://github.com/flutter/engine/commit/54293721816abeb0c8fe9ed629d9897a7527fc13))

This can probably be fixed by re-uploading the gallery to use the latest Flutter master branch.

**Comment by czw299** [comment]
I tried the Master branch on my computer with 1080P monitor and it worked fine, stable branch 3.16.5 still had problem

**Comment by harryterkelsen** [comment]
I will try to repro the bug on stable and see if a hotfix is needed.

**Comment by harryterkelsen** [comment]
Filed a cherry-pick request for stable branch to include the fix that is already on `beta` and `master` channels.

**Comment by chipnetics** [comment]
> Filed a cherry-pick request for stable branch to include the fix that is already on `beta` and `master` channels.

Amazing... simply amazing 👏 hopefully we don't have to wait a year for it to be merged now 🙃

**Comment by Reprevise** [comment]
Given that the cherry-pick request was denied due to performance issues in Firefox and Safari (which AFAIK have been fixed in main), are we going to have to wait another month till the next big stable release of Flutter for this fix?

**Comment by chipnetics** [comment]
Yeah, good question. It now makes a full year this has been an issue, and flutter web has been blurry. 

Flutter should be very grateful that the mainstream programming language 'war' community hasn't picked up on this bug... language haters would have a field day with this one.
