### ISSUE TITLE
iOS Simulator hot reload doesn't work with iOS 11 and XCode 9

### ISSUE THREAD

**Issue by themnd** [flutter/flutter#12281]
Opening a copy of #11945 since it does not seems to be fixed:

```
flutter upgrade
From https://github.com/flutter/flutter
   3433f42b0..63d7b9338  master     -> origin/master
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 701d534ba9 (2 weeks ago) • 2017-09-12 14:01:51 -0700
Engine • revision 31d03de019
Tools • Dart 1.25.0-dev.11.0

Running "flutter packages upgrade" in myapp...        7.8s

Running flutter doctor...
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-IT, channel alpha)
    • Flutter at /Users/mnova/dev/tests/flutter/flutter
    • Framework revision 701d534ba9 (2 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[-] Android Studio
    • Android Studio at /Applications/dev/Android Studio.app/Contents
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[-] IntelliJ IDEA Community Edition (version 2016.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.3)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • None
```

and then:

```
flutter  run
Launching lib/main.dart on iPhone 7 in debug mode...
Running Xcode build...                               10.2s
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.ServerDocuments.ServerFileProvider): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.ServerDocuments.ServerFileProvider): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.videosubscriptionsd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AssetCacheLocatorService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AssetCacheLocatorService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:14 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.WebKit.Networking): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.WebKit.Networking): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.intents.intents-image-service): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.intents.intents-image-service): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.WebKit.Databases): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.WebKit.Databases): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.DictionaryServiceHelper): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.DictionaryServiceHelper): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AnnotationKit.MigratorService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AnnotationKit.MigratorService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.WebKit.WebContent): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.WebKit.WebContent): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AssetCacheLocatorService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AssetCacheLocatorService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Photos.CPLDiagnose): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Photos.CPLDiagnose): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Safari.ImageDecoder): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Safari.ImageDecoder): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Safari.History): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Safari.History): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.CloudDocs.MobileDocumentsFileProvider): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.CloudDocs.MobileDocumentsFileProvider): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.CloudDocsDaemon.container-metadata-extractor): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.CloudDocsDaemon.container-metadata-extractor): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.mobileslideshow.PhotosFileProvider): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.mobileslideshow.PhotosFileProvider): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.intents.intents-image-service): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.intents.intents-image-service): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.DictionaryServiceHelper): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.DictionaryServiceHelper): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AssetCacheLocatorService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.AssetCacheLocatorService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Photos.CPLDiagnose): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.Photos.CPLDiagnose): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnablePressuredExit
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.FileProvider.LocalStorage): Unknown key for Boolean: EnableTransactions
Sep 27 15:52:15 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (com.apple.FileProvider.LocalStorage): Unknown key for Boolean: EnablePressuredExit
```

**Comment by themnd** [comment]
Hi @cbracken, if I look at https://github.com/flutter/flutter/pull/12079 I can see that you expect some info from RUNNER, however in the device system log, if I filter for RUNNER I can only see:

```
Sep 27 16:21:29 mymac Runner[72309]: assertion failed: 16G29 15A372: libxpc.dylib + 69578 [D870A237-D3A7-31F5-AAD4-CE880C0C8E7B]: 0x7d
```

which is also confirmed by flutter -v run:

```
[  +18 ms] tail -n 0 -F /Users/myuser/Library/Logs/CoreSimulator/EE6B4E55-E5EC-4B24-9BD5-5444F120F82B/system.log
[   +2 ms] Building Runner.app for EE6B4E55-E5EC-4B24-9BD5-5444F120F82B.
[   +3 ms] Building build/app.flx
[  +43 ms] tail -n 0 -F /private/var/log/system.log
[ +220 ms] which zip
[   +5 ms] Encoding zip file to build/app.flx
[  +10 ms] [build/flx/] zip -q /Users/myuser/dev/tests/flutter/myapp/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE
[  +33 ms] Built build/app.flx.
[   +1 ms] /usr/bin/xcrun simctl get_app_container EE6B4E55-E5EC-4B24-9BD5-5444F120F82B com.yourcompany.myapp
[        ] /usr/bin/killall Runner
[  +56 ms] [DEVICE LOG] Sep 27 16:21:29 mymac com.apple.CoreSimulator.SimDevice.EE6B4E55-E5EC-4B24-9BD5-5444F120F82B[66813] (UIKitApplication:com.yourcompany.myapp[0x6bf4][66839][67117]): Service exited due to signal: Terminated: 15 sent by killall[72307]
[   +3 ms] [DEVICE LOG] Sep 27 16:21:29 mymac syslogd[66815]: ASL Sender Statistics
[  +63 ms] /usr/bin/xcrun simctl launch EE6B4E55-E5EC-4B24-9BD5-5444F120F82B com.yourcompany.myapp --enable-dart-profiling --flx=/Users/myuser/dev/tests/flutter/myapp/build/app.flx --dart-main=/Users/myuser/dev/tests/flutter/myapp/lib/main.dart --packages=/Users/myuser/dev/tests/flutter/myapp/.packages --enable-checked-mode --observatory-port=8100 --diagnostic-port=8101
[  +46 ms] [DEVICE LOG] Sep 27 16:21:29 mymac launchd_sim[66813]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
[ +115 ms] com.yourcompany.myapp: 72309
[        ] Waiting for observatory port to be available...
[ +472 ms] [DEVICE LOG] Sep 27 16:21:29 mymac Runner[72309]: assertion failed: 16G29 15A372: libxpc.dylib + 69578 [D870A237-D3A7-31F5-AAD4-CE880C0C8E7B]: 0x7d
```

**Comment by themnd** [comment]
this issue is present in the alpha branch but on master has been fixed!
Switching to master (flutter channel master) solved this problem!

**Comment by lukaskirner** [comment]
I still have an Problem 

`Oct  2 19:12:32 Lukass-MacBook-Pro com.apple.CoreSimulator.SimDevice.8EADD4B6-5B22-
 4172-8A40-C8EE4D533825[1698] (com.apple.videosubscriptionsd): Service only ran for 0 
 seconds. Pushing respawn out by 10 seconds.
`

anyone how to solve it?
