### ISSUE TITLE
framework canvaskit cache is not being cleared with engine rolls

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#123737]
Sayith @eyebrowsoffire "So the `WebBuiltInAssets` target always assumes that these are static and can be cached forever. But it now copies canvaskit over from the web sdk, which is not static forever."

**Comment by kevmoo** [comment]
@eyebrowsoffire – reports that this is NOT fixed - https://github.com/flutter/flutter/issues/123794#issuecomment-1492666502

**Comment by eyebrowsoffire** [comment]
Re-opening due to further issues here. https://github.com/flutter/flutter/pull/123915 should fix it though.

**Comment by darshankawar** [comment]
Hello @kevmoo and @eyebrowsoffire 

I tried running a sample app on web `flutter run -d chrome` using latest master and main channels but still seeing below error:

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             20.0s
This app is linked to the debug service: ws://127.0.0.1:49414/M2WfAhbvFAY=/ws
Debug service listening on ws://127.0.0.1:49414/M2WfAhbvFAY=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:49414/M2WfAhbvFAY=
Rejecting promise with error: Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'
_js_helper.TypeErrorImpl.new


```

master version: `Channel master, 3.9.0-22.0.pre.56, on macOS 12.2.1 21D62`

main version: `Channel main, 3.9.0-22.0.pre.56, on macOS 12.2.1 21D62`

**Comment by eyebrowsoffire** [comment]
@darshankawar I haven't been able to reproduce this on my end. Does this still reproduce after you clear the browser cache?

**Comment by darshankawar** [comment]
@eyebrowsoffire
No. After following https://github.com/flutter/flutter/issues/123794#issuecomment-1493372787, I didn't get the said error, although earlier I thought that it was more of a workaround until this original issue gets fixed, so thought to report it here for your reference.

**Comment by eyebrowsoffire** [comment]
After some digging, I was able to get my setup into a state that reproduced this problem, and I have put out a fix: https://github.com/flutter/flutter/pull/124641

**Comment by mit-mit** [comment]
OK, the fairly short window to trigger the issue lowers the priority a bit, and its nice that there is a workaround. BUT when it fails, it fails in a way that is very hard to understand (I got JS interop issues), so I still think we should pick the fix if we think it's relatively low risk of causing regressions.
