### ISSUE TITLE
I cant build my application for flutter after new macOS and Xcode update

### ISSUE THREAD

**Issue by Philnue** [flutter/flutter#123962]
Yesterday, I updated to MacOs 13.3 and Xcode 14.3. Running the latest flutter update.

I tried everything increase the iOS deployment and changing, updating the pod file.

Error (Xcode): File not found:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/u
sr/lib/arc/libarclite_iphoneos.a

![image](https://user-images.githubusercontent.com/65328894/229349360-770e8546-0035-4fd9-8f1b-c7f205d4d7f2.png)

**Comment by sylfreee** [comment]
I made changes to the `ios/Podfile`, setting the iPhoneOS deployment target to 13.0 for all projects and targets, and it worked for me. Here's the updated code:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
  end
end
```

**Comment by Philnue** [comment]
> I made changes to the `ios/Podfile`, setting the iPhoneOS deployment target to 13.0 for all projects and targets, and it worked for me. Here's the updated code:
> 
> ```ruby
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
>   installer.generated_projects.each do |project|
>     project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
>         end
>     end
>   end
> end
> ```

Yeah I did it to, but then I got a lot of undefined symbol error messages and I wasn't able to resolve them

**Comment by CoMatu** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/30466272/229353585-2e13dd66-ebbe-44b7-9a9e-c290eed8b508.png">
It work for me

**Comment by Philnue** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/65328894/229353707-93242c52-7738-42e9-becb-88b5df9cd3b1.png">

I got this error after updating my pod file to yours

**Comment by sylfreee** [comment]
This [link](https://stackoverflow.com/questions/74149640/launch-the-swift-screen-from-flutter-error-xcode-undefined-symbol-s19fire) might help resolve the issue.

**Comment by Philnue** [comment]
I deleted pod FireStore the pre download. The problem now it takes likes 3-5 mins to build

**Comment by oakstair** [comment]
I cant build either after upgrading to xcode 14.3. Yesterday I created this issue 
https://stackoverflow.com/questions/75912776/fail-to-start-my-flutter-app-after-upgrading-to-xcode-14-3

**Comment by cerberodev** [comment]
this works for me

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    end
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                '$(inherited)',
              # dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
              'PERMISSION_LOCATION=1',
              # dart: PermissionGroup.notification
              'PERMISSION_NOTIFICATIONS=1',
              # dart: PermissionGroup.appTrackingTransparency
              'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
              # dart: PermissionGroup.contacts
              'PERMISSION_CONTACTS=1',
              ]
            end
           end
      end
end
end`

**Comment by darshankawar** [comment]
@Philnue 
Similar / related issue https://github.com/flutter/flutter/issues/123903
Check if [this](https://github.com/flutter/flutter/issues/123903#issuecomment-1492791097) comment helps to resolve the issue: 

Also, see [this](https://github.com/flutter/flutter/issues/123903#issuecomment-1493165002) for your reference if you are using Xcode 14.3

**Comment by geisterfurz007** [comment]
Related (possibly): https://github.com/CocoaPods/CocoaPods/pull/11828

**Comment by darshankawar** [comment]
This has been fixed at part of https://github.com/flutter/flutter/issues/123890 at Flutter end and merged into master, so, everyone facing this issue in this thread, please switch to latest master to see it working. The fix will also be cherry-picked to stable https://github.com/flutter/flutter/issues/124081.

Closing, as this is already fixed on master. If anyone disagrees, write in comments and I'll reopen it.

**Comment by ivanarellano** [comment]
My `flutter --version`:
```
Flutter 3.7.10 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 4b12645012 (2 days ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

I still see the issue even after removing Podfile.lock, running `flutter clean`, running `pod install`, and running `flutter pub get`. What did fix the issue for me is to set the `IPHONEOS_DEPLOYMENT_TARGET` to `12.5` for all projects as mentioned above in this thread.

**Comment by keybow007** [comment]
Doesn't seem to have improved with Flutter 3.7.10 in my environment either.

![スクリーンショット 2023-04-06 10 51 09](https://user-images.githubusercontent.com/12907755/230252515-35a8124f-7a7a-425d-9677-da944b728af1.png)

**Comment by leononly** [comment]
> Doesn't seem to have improved with Flutter 3.7.10 in my environment either. It works fine with XCode 14.2. I redid the "flutter clean", delete Podfile.lock and "pod update" just to be sure.
> 
> ![スクリーンショット 2023-04-06 10 51 09](https://user-images.githubusercontent.com/12907755/230252515-35a8124f-7a7a-425d-9677-da944b728af1.png)

same here, i just upgrade to 3.7.10, flutter clean-ed, issue still persists. Must this workaround code in podfile to solve the issue:
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
  end
end`

**Comment by BrutalCoding** [comment]
If anyone is still running into this issue, try the following:

# Fastlane (MacOS)
Assuming you're using [`Fastlane` with `bundler`](https://docs.fastlane.tools/getting-started/ios/setup/), follow these steps:

Let's verify your broken [CocoaPods](https://rubygems.org/gems/cocoapods/versions) version first.
1. Open up your terminal
2. Navigate to your iOS folder
```zsh
> cd your_flutter_app/ios
 ```
3. Output the path to the installed version of your CocoaPods installation
```zsh
> bundle show cocoapods 
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0
```
4. Notice from the path that you're using the production release of cocoapods 1.12.0, which contains the bug. Lets fix that.
5. **(Optional)** Double check if you're using the default cocoapods installation, which is not a git directory:
```zsh
> cd /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0 # Use the path from step 3
> git log -1
> fatal: not a git repository (or any of the parent directories): .git # This is good, it means you're indeed using the stable version, 1.12.0 in this example.
```

## Time to fix it:
1. Open up your terminal
2. Execute `cd your_flutter_app/ios`
3. Execute `rm Podfile.lock`
4. Execute `open Gemfile` (VSCode users: `code Gemfile`)
5. Copy and paste my Gemfile, or simply add the gem CocoaPods line:
```Ruby
source "https://rubygems.org"

# BrutalCoding's note:
# Cocoapods is hardcoded to a specific commit, for the following reason:
# Cocoapods 1.12.0 is not able to use the latest stable version to archive iOS and Mac apps
# Please continue to watch for Xcode updates and update this file accordingly
#
# You can try uncommenting one of the following lines to see if it works for you.
# gem 'cocoapods', '~> 1.12.0' # Specific version
# gem 'cocoapods' # Latest stable version
gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :ref => '3ac99beed81d11a830bdce2fac761a49bae47e83' # The commit SHA of the commit that fixes the -f bug.
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```
6. Execute `bundle install` (in your ios folder)
```zsh
> bundle install
... bunch of files will show up ...
Bundle complete! 11 Gemfile dependencies, 125 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
7. Execute `bundle update`  (in your ios folder)
```zsh
> bundle update
... bunch of files will show up ...
Bundle updated!
```

**Done! Try publishing your app again.**


# Without Fastlane
Will update this post later as I ran out of time. 
But the steps I mentioned above basically comes down to making sure that your installed cocoapods version is using this commit:
https://github.com/CocoaPods/CocoaPods/commit/3ac99beed81d11a830bdce2fac761a49bae47e83

**Comment by jmagman** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/124340 caused by a change of behavior in Xcode 14.3.  Please upgrade to Flutter 3.7.11 and remove any changes you made to your Podfile to work around the issue.

If you are still seeing issues, please file a new GitHub issue and completely fill out the template.
