### ISSUE TITLE
Changing a MaterialApp's initialRoute does not rebuild the widget.

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#12454]
## Steps to Reproduce

Run this demo app:

https://github.com/gavindoughtie/flutter_nav_bug

The key code is:
```dart
class _MyAppState extends State<MyApp> {
  String nextRoute = homeRoute;

  void _nextRoute() {
    String route = secondRoute;
    if (nextRoute == secondRoute) route = homeRoute;
    setState(() {
      print('setting route to $route');
      nextRoute = route;
    });
  }

  @override
  Widget build(BuildContext context) {
    final routes = {
      homeRoute: (BuildContext context) => new MyHomePage(nextRoute: _nextRoute),
      secondRoute: (BuildContext context) => new _MySecondRoute(_nextRoute),
    };
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      routes: routes,
      initialRoute: nextRoute,
    );
  }
}
```
Triggering the _nextRoute() function prints the new initialRoute, but the application is not rebuilt with the new route.

## Logs
```
Launching lib/main.dart on iPhone 7 Plus in debug mode...
Running Xcode build...
	    CFBundleIdentifier = "com.yourcompany.flutterNavBug";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/doughtie/Library/Developer/CoreSimulator/Devices/CD05F0E8-3440-4AB4-941B-E0D3544A87C0/data";
	}
	state->old_bundle: /Users/doughtie/Library/Developer/CoreSimulator/Devices/CD05F0E8-3440-4AB4-941B-E0D3544A87C0/data/Containers/Bundle/Application/6CB1077B-A23F-497C-9AE1-B150D05BC5B7/Runner.app
	state->new_bundle: /Users/doughtie/flutter_nav_bug/build/ios/iphonesimulator/Runner.app
	state->dst_bundle: /Users/doughtie/Library/Developer/CoreSimulator/Devices/CD05F0E8-3440-4AB4-941B-E0D3544A87C0/data/Library/Caches/com.apple.mobile.installd.staging/temp.0Xk96l/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/doughtie/Library/Developer/CoreSimulator/Devices/CD05F0E8-3440-4AB4-941B-E0D3544A87C0/data/Library/Caches/com.apple.mobile.installd.staging/temp.0Xk96l/extracted
Oct  8 00:05:50 doughtie-macbookpro2 com.apple.CoreSimulator.SimDevice.CD05F0E8-3440-4AB4-941B-E0D3544A87C0.launchd_sim[16956] (com.apple.videosubscriptionsd[25547]): Service exited with abnormal code: 1
	    arguments =     (
	        "--enable-dart-profiling",
	        "--flx=/Users/doughtie/flutter_nav_bug/build/app.flx",
	        "--dart-main=/Users/doughtie/flutter_nav_bug/lib/main.dart",
	        "--packages=/Users/doughtie/flutter_nav_bug/.packages",
	        "--enable-checked-mode",
	        "--start-paused",
	        "--observatory-port=8100",
	        "--diagnostic-port=8101"
	    );
	    environment =     {
	    };
	}
		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
	Simulator booted at: 2017-10-07 03:13:02 +0000
	Current time: 2017-10-08 07:05:55 +0000
	Within boot leeway: NO
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
Syncing files to device iPhone 7 Plus...
setting route to route_two
```
Run `flutter analyze` and attach any output of that command also.
```
% flutter analyze
Analyzing /Users/doughtie/flutter_nav_bug...
No issues found!
Ran in 4.8s
```
## Flutter Doctor
```
% flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/doughtie/flutter
    • Framework revision 6420c75f26 (12 days ago), 2017-09-25 13:59:05 -0700
    • Engine revision 005212683c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/doughtie/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.4155.35
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • iPhone 7 Plus • CD05F0E8-3440-4AB4-941B-E0D3544A87C0 • ios • iOS 10.3 (simulator)
```

**Comment by gavindoughtie** [comment]
Note that the Flutter plugin *is* installed and working in IntelliJ, but flutter doctor doesn't seem to notice.

**Comment by Hixie** [comment]
This is working as expected. The `initialRoute` specifies the _initial_ route. Setting it to a new value will have no effect.

**Comment by Hixie** [comment]
We should document that more clearly in `initialRoute`'s API docs, though.

**Comment by Hixie** [comment]
Specifically, we should say that changing this won't have any effect and should point to the `Navigator` API.

**Comment by gavindoughtie** [comment]
What mechanism does one use to reset the "bottom" route of a MaterialApp's navigation stack, then?

**Comment by Hixie** [comment]
https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/NavigatorState/replace.html

**Comment by gavindoughtie** [comment]
Sorry to be thick -- but if you're calling "new MaterialApp(... initialRoute: something)" it's making a new Widget with a *new* initial route, right? Or is this a leaky abstraction for performance and the "app" widget is somehow special?

**Comment by Hixie** [comment]
It's making a new Widget, but the underlying State survives, that's what it means to be a StatefulWidget.

**Comment by gavindoughtie** [comment]
AHA! My conceptual framework has expanded!

**Comment by guitcastro** [comment]
What if app is a stateless widget? My application is and is not working.

**Comment by xyzira** [comment]
I just run into this. I agree with gavindoughtie. From how it's been used, it looks like it can be configured every time the app widget is built. It's confusing, I wanted to do something conditionally with it. 

I didn't find any explanation in the doc: https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html 
The doc should at least indicate the behavior.

**Comment by chunhtai** [comment]
Does change the navigatorKey work?

This should eventually be fixed by https://github.com/flutter/flutter/issues/45938

**Comment by pedromassangocode** [comment]
I'm considering this as a valid issue since the documentation of `initialRoute` does not state that changes to it will take no effect.

@chunhtai since https://github.com/flutter/flutter/pull/50362 has landed (and fixed https://github.com/flutter/flutter/issues/45938) can you confirm if this should still remains open? I recall that the `initialRoute` will eventual be deprecated in favour of the [Navigator 2.0](https://github.com/flutter/flutter/issues/45938).

**Comment by exaby73** [comment]
This is still an issue on the latest Master 3.5.0-12.0.pre.47. Updating labels to reflect the same.
