### ISSUE TITLE
Auto detect missing runtime and do a fresh xcode install

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125273]
When a new xcode version is added to the CI via a pull request, it is very likely that people push new commits to the PR. This will cause existing builds canceled.

If a build is running xcode installation, this cancellation will cause incomplete xcode (like missing runtime) remaining in the cache and cause test failures.

We should have an automatic way to detect missing runtime and do a cleanup and fresh xcode re-installation if detected.

**Comment by jmagman** [comment]
> this cancellation will cause incomplete xcode (like missing runtime) remaining in the cache and cause test failures.

Instead can we avoid writing to the cache until the installation succeeds?

**Comment by keyonghan** [comment]
This somehow will not solve the problem. Copying over xcode/runtime (if we install somewhere else we need to copy them to cache) is also expensive, and canceling a build when copying will also hit same issue.

I would not expect we hit this issue much. This logic might only needed when we bump an xcode version.

**Comment by keyonghan** [comment]
Some context for CIPD install.

CIPD caches installation state, which means it assumes that anything it installed is still installed. We need to handle the incomplete installations on our side (for now). One way is to delete `.cipd` to force a reinstall. (related bug: https://crbug.com/1176408)

**Comment by keyonghan** [comment]
Dig further, we may want an upstream fix from mac_toolchain. They have some shortcuts to skip re-install xcode, and unluckily we hit some corner cases. 
Filed https://crbug.com/1435582 to track.
/cc @godofredoc

**Comment by jmagman** [comment]
> Filed https://crbug.com/1435582 to track.

From that issue it was suggested to do:

```
maybeInstall:
  if !exists sentinel:
    -- previous install is OK
    if version files on disk == desired version:
      return  -- current install is OK and the right version
  doInstall

doInstall:
  write sentinel
  cipd ensure ....
  delete sentinel


but IMO I would just do

maybeInstall:
  cipd ensure ...

This will already skip expensive file operations if the state on the disk matches what the ensure file requested, and is the way that cipd is intended to be used.
```

**Comment by jmagman** [comment]
cc @vashworth @cyanglaz

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/42900 landed to clean up polluted xcode. If no regression (didn't expect to happen), I will close this bug.

**Comment by jmagman** [comment]
Thanks @keyonghan!

**Comment by keyonghan** [comment]
Reopen as this is still happening: https://github.com/flutter/flutter/issues/126092

We hit the case where: xcode exists, the default runtime path exists as well under Copy runtime to `XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime`, but `xcrun simctl list` doesn't show the runtime.

Likely this is due to incomplete copy of the runtime.

**Comment by keyonghan** [comment]
This affects devicelab xcode as well: https://github.com/flutter/flutter/issues/126025.

Use this bug to track xcode cache cleanup for both devicelab and host only. (as we are consolidating osx_sdk and devicelab_osx_sdk modules, it makes sense to use a shared cleanup logic)

**Comment by keyonghan** [comment]
Instead of checking xcode and runtime paths (which misses the case where both paths exist but there are still missing files that are not copied over, resulting `xcrun simctl list` no runtime output), we can check the output of `xcrun simctl list runtimes` directly. If no runtime, then we are sure the xcode is not in a complete state.

**Comment by keyonghan** [comment]
The issue should be resolved in https://flutter-review.googlesource.com/c/recipes/+/44761. Closing.
@vashworth @cyanglaz please let me know if you hit this again when bumping the next xcode version. Hopefully not:-)

**Comment by matanlurey** [comment]
Despite this update, I'm still seeing this occur on CI as-of 2023-08-15:

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/331151/overview

**Comment by vashworth** [comment]
I just uploaded a new Xcode version in CIPD yesterday, maybe that triggered it

**Comment by matanlurey** [comment]
Why does uploading a new version cause CI workers to fail, shouldn't those two bits be isolated?

**Comment by keyonghan** [comment]
> Despite this update, I'm still seeing this occur on CI as-of 2023-08-15:
> 
> https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/331151/overview

Runtime does show up: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8772653137004135969/+/u/list_simulators/stdout

**Comment by vashworth** [comment]
@keyonghan That [link](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8772653137004135969/+/u/list_simulators/stdout) also shows iOS 16.4 runtime as missing

```
Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-16-4 --
```

**Comment by keyonghan** [comment]
The existing logic just makes sure there is some runtime installed, but doesn't enforce a check on every runtime, which misses this corner case.
https://flutter-review.googlesource.com/c/recipes/+/49482 to fix.

**Comment by matanlurey** [comment]
Thanks @keyonghan!

**Comment by keyonghan** [comment]
Recipes CL landed, and the issue should be resolved now. Please reopen you you still see the issue.
