### ISSUE TITLE
Pressing and releasing a key before the framework has started throws

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#125975]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Launch the code sample (tried on Linux and on Android).
2. Do a hot restart and very quickly focused the Flutter app, press and release a key (this might need several tries, because the key has to be pressed and released in the short time where the engine is ready to listen to platform keyboard events and the framework is not fully initialized).

### Expected results

No error

### Actual results

Error thrown: `flutter: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed.`

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs
flutter: in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure
flutter: that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the
flutter: event: KeyUpEvent#17c68(physicalKey: PhysicalKeyboardKey#a8a55(usbHidUsage: "0x00070014", debugName:
flutter: "Key Q"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key
flutter: A"), character: null, timeStamp: 5:07:41.188000)
flutter: 'package:flutter/src/services/hardware_keyboard.dart':
flutter: Failed assertion: line 471 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:471:16)
flutter: #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
flutter: #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:601:5)
flutter: #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1021:37)
flutter: #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
flutter: #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:481:35)
flutter: #8      _invoke2 (dart:ui/hooks.dart:174:13)
flutter: #9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
flutter: #10     _Channel._drainStep (dart:ui/channel_buffers.dart:223:31)
flutter: (elided 4 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════```

</details>


### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.10.0-3.0.pre.403, on Ubuntu 22.10
    5.19.0-41-generic, locale fr_FR.UTF-8)
    • Flutter version 3.10.0-3.0.pre.403 on channel master at
      /home/bruno/Nevercode/flutter
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 110fe75b5d (il y a 7 heures), 2023-05-03 02:11:35 -0400
    • Engine revision 0407a16a9b
    • Dart version 3.1.0 (build 3.1.0-66.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/bruno/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/bruno/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/bruno/Produits/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.10 5.19.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bleroux** [comment]
#87391 Is a generic issue for keyboard assertions thrown after a hot restart.

One of the possible reasons is that the engine sends key events using 2 channel buffers which have a default buffer size of 1. Once the engine starts listening to platform keyboard events and before the framework has registered any handlers, if a key is pressed and released, the key up event is buffered and the framework side will receive it which leads to the following assertion `flutter: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed`.

One solution would be to fix this on the engine side by setting the keyboard channel buffers buffer size to 0.  

A second solution would be to fix this on the framework side. #122885 is not enough to fix this particular case. But it can help because we can decide to not throw for the first event we received if it is not coherent with the initial keyboard state we got.

@dkwingsmt I’m very interested to get your feedback on this, especially the second solution which will be easier to implement as it requires only one PR on the framework side.

**Comment by dkwingsmt** [comment]
Why do the engine need a channel buffer of size 2? Isn't the key event processing synchronous?

**Comment by bleroux** [comment]
@dkwingsmt My point is the engine probably need a channel buffer size of 0. Because the buffered event is usualy obsolete. For instance when pressing and quickly relasing the key (before the framework handlers are set up), the UP event is buffered and will be delivered to the framework and leads to the assertion failure.
Another way to avoid this is to update the framework side to not assert on the first key event because it might be obsolete.

**Comment by loic-sharma** [comment]
@bleroux Would it make sense for the engine to not notify the framework of key events until the framework subscribes to the keyboard channels?

The reason I ask is because for app lifecycle we have a somewhat related issue: you get error logs if the embedder sends app lifecycle messages before the framework is ready to accept them. We're considering a solution where the embedder API notifies the embedder when a channel's listener changes. The embedder can enable/disable app lifecycle messages if the framework subscribes/unsubscribes to the lifecycle channel.

Would a similar approach solve this problem for the keyboard?

**Comment by bleroux** [comment]
@loic-sharma 
Did you consider removing the error by setting the lifecycle channel 'overflow' behavior?

Based my experimentations and from https://github.com/flutter/engine/blob/93e8901490e78c7ba7e319cce4470d9c6478c6dc/lib/ui/channel_buffers.dart#L236-L309, I would say that it is not the responsability of the channel produder to take care of not sending messages until a consumer is registered. 
From channel_buffers.dart code, it is expected that some channels send messages before a handler is set and channel_buffer.dart takes responsability to manage those messages (buffering, showing error logs, etc).

I have two working implementations (Android and Linux) where I tried to set the 'overflow' property for the keyboard channels and it properly hide the similar error log you get.

To fix this particular keyboard issue I also have to set the buffer channel size to 0. It seems to work nicely and I will file PRs for each platforms.

Before doing so I would like to file PRs to add helper functions to easily call the 'resize' and 'overflow' commands. See https://github.com/flutter/flutter/issues/132386.
My motivation for splitting this is to avoid that a keyboard related breakage leads to a revert and also because those helper functions might be needed elsewhere, maybe it will be helpful for the lifecycle channel?

**Comment by loic-sharma** [comment]
@bleroux Hm that's interesting, I wasn't aware of that channel size `0` behavior. I'll follow up on that, thanks!

**Comment by dannyglover** [comment]
Any updates on this?
Thank you.

**Comment by bleroux** [comment]
Status of my work on this issue:

- I started with a PR, https://github.com/flutter/flutter/pull/131258, implementing the second solution I proposed in https://github.com/flutter/flutter/issues/125975#issuecomment-1533015394.
After getting some feedback (see https://github.com/flutter/flutter/pull/131258#issuecomment-1654065201), I canceled this PR and switched to the first solution I proposed (setting channel buffer size to 0).

- In order to implement this solution, I needed a way to set the channel buffer size to 0 and filed https://github.com/flutter/flutter/issues/132386.
This work required a PR for each platform:
-> Android: https://github.com/flutter/engine/pull/44434.
-> iOS/masOS: https://github.com/flutter/engine/pull/44848.
-> Linux: https://github.com/flutter/engine/pull/45056.
-> Windows: https://github.com/flutter/engine/pull/47158. (This Windows PR was way more complex than expected, itmight be merged in the coming weeks).

- Unfortunately, it turned out that this solution (setting channel buffer to 0) is not applicable to very core channels such as lifecycle and keyboard because those channels are created very early on the engine side (before the Dart side has started and this is a blocker because the channel resizing logic is done on the Dart side). 
When experimenting with it, I reached the same issue that Greg described in https://github.com/flutter/flutter/issues/131452#issuecomment-1677962781.

- For the lifecycle channel, the solution which was implemented on Windows is to not send messages until a listener is registered, see https://github.com/flutter/flutter/issues/131616 and https://github.com/flutter/engine/pull/44827.

So the status here is to evaluate if the solution implemented for the lifecycle channel is applicable to the keyboard channel. If yes, the solution would need platform specific implementations similar to the Windows one (https://github.com/flutter/engine/pull/44827).

**Comment by bleroux** [comment]
Status update. I experimented with the solution mentionned in my previous [comment](https://github.com/flutter/flutter/issues/125975#issuecomment-1835822981) (not sending key events from the engine side, until channel listeners are registered on the framework side). I tried this on Windows only because https://github.com/flutter/engine/pull/44827 laid the fundation for it.

Unfortunately it does not seem to be a proper solution.
I filed a WIP PR, https://github.com/flutter/engine/pull/50761, to make this work available and I explained on the PR description why I think it is not a proper solution.

**Comment by bleroux** [comment]
Unassigning myself.
https://github.com/flutter/flutter/pull/149790 would be a good candidate if  the second part of https://github.com/flutter/flutter/pull/149790#issuecomment-2266172602 could be addressed.

**Comment by ChristianKleineidam** [comment]
Given that the keypress timing has to be right, reliably reproducing it isn't easy, but I think the same issue appears to me when building the app for Windows. This logging appeared multiple times and I think in each one I did use the keyboard during the build process. I get the log:

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in HardwareKeyboard. This was the event: KeyDownEvent#f0eac(physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 9:27:21.222196)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 516 pos 11: '!_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:516:11)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:536:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:660:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1184:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:261:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:653:35)
#8      _invoke2 (dart:ui/hooks.dart:363:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:136:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:344:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:802:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:277:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

**Comment by richard457** [comment]
Created PR that can fix this: https://github.com/flutter/flutter/pull/172154#issuecomment-3072677371

**Comment by justinmc** [comment]
Partial fix in https://github.com/flutter/flutter/pull/172154, in case anyone wants to pick this up and get it landed.

**Comment by bleroux** [comment]
Marked as solved by https://github.com/flutter/flutter/pull/181894

@dkwingsmt Thanks a lot for the PR which improves the development experience. 🙏 
Maybe once we get synchronous calls between framework and engine, or a way to share state between them (https://github.com/flutter/flutter/issues/181561), we could completely fix these keyboard issues.

**Comment by dkwingsmt** [comment]
Let's leave this PR open since it's still reproducible if `debugPrintKeyboardEvents` is set.

A more consistent way to reproduce:

Steps:
* Run a Flutter app with `-d macos` on mac.
* Keep keyboard focus on the terminal while make the Flutter app window nearby.
* Press Shift and hold
* Tap key R, then immediately use mouse to click the Flutter window
* Wait a bit before releasing Shift.
* Terminal shows error. 

Video:

https://github.com/user-attachments/assets/bd9a353a-5b20-4b54-a742-e34b595ab846
