### ISSUE TITLE
Expand-to-fit sliver for cases where a viewport isn't full

### ISSUE THREAD

**Issue by mzgreen** [flutter/flutter#12650]
Right now `Flex` widgets can't be used inside a scrollable containers like `ScrollView`. Maybe it's not super common use case but I have one that makes sense.

Let's say that I want to have a vertical layout (a `Column`) consisting of some Widgets. I would like to add a margin at the top and at the bottom of that `Column` that meets these requirements:
- top margin is expanding if it has room and it's shrinking if there is not enough room but it never shrinks under some `minHeight` value like `16.0`.
- bottom margin behaves the same like top margin but it's height is twice as big as top margin, so it shrinks down to `32.0`

Now if screen is big enough I'll see a layout with a margin of height `x` at the top, where `x>=16.0` and a margin at the bottom which height is `y=2x` and `y>=32.0`. I've created layouts with such dynamic spacings on Android using `ConstraintLayout` and on iOS using `AutoLayout`.
I was able to do something that almost works in Flutter, but when I put it inside `ScrollView` then it crashes because widgets that use `flex` can't scroll.

Expected: allow to scroll flexible widgets or add some other way to create such layouts in Flutter.

Actually maybe it's possible to just add an `fillViewport` option to the ScrollView like:
https://developer.android.com/reference/android/widget/ScrollView.html#attr_android:fillViewport
Similar thing exists on iOS and setting it allows to create behavior described above. If it's not set then ScrollView don't know how big it wants to actually be.

**Comment by Hixie** [comment]
You can probably do what you want using CustomMultiChildLayout and SingleChildScrollView.

**Comment by Hixie** [comment]
...actually that won't work because you can't size yourself based on your child's size in that widget. Hmm.

**Comment by Hixie** [comment]
This probably needs some dedicated machinery.

**Comment by Hixie** [comment]
I implemented this the other day. It turns out it's easy. :-)

Wrap a SingleChildScrollView in a LayoutBuilder, then inside the SingleChildScrollView put a ConstrainedBox whose `minHeight` is the `maxHeight` constraint LayoutBuilder saw, and as a child of the ConstrainedBox put your Column with the flexible contents, with its `mainAxisSize` set to `MainAxisSize.min`.

**Comment by Hixie** [comment]
(If your list view might have many children, then that's not efficient (since it doesn't use slivers); for that case we still need the feature described in this report.)

**Comment by 98732** [comment]
Still can't render Expanded inside a SingleChildScrollView.
```
RenderFlex children have non-zero flex but incoming height constraints are unbounded.
```
Even when doing what @Hixie said. 

Using the tree as it follows: 

```Dart
new Scaffold(
         body: new LayoutBuilder(
           builder: (BuildContext context, BoxConstraints constraintss) {
             return SingleChildScrollView(
               child: new ConstrainedBox(
                    constraints: new BoxConstraints(minHeight: constraintss.maxHeight),
                    child:  new Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            new Expanded(
                              flex: 2
                              child: ...
                            ),
                            new Column (...)
                          ]
```

If there is any other way of putting a variable size element in Scroller please let me know.

**Comment by Hixie** [comment]
use a flexible instead of an expanded

**Comment by 98732** [comment]
I would like that my element fill the remaining space, trying that with a Flexible didn't work out.
It renders like it's containing itself instead of stretching to the rest of the available space of it's parent. 
Fit is set to loose and flex factor is higher than it's sibling.

**Comment by Hixie** [comment]
Hmm. Flexible should work, because we force there to be available space with the minHeight constraint... Can you paste your complete main.dart here?

**Comment by 98732** [comment]
```Dart 
main:

void main() {
  isAuthenticated().then((authenticate) {
 // isAuthenticated is always returning false for development purposes
    if(authenticate){
      runApp(new MyApp());
    } else {
      runApp(
         new MaterialApp(
          title: 'tst',
          home:  new AddPhoneWidget(),
        )
      );
    }
  });
  


```AddPhone

import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';


Icon cellphoneIcon = new Icon(Icons.phone_iphone, size: 128.0);
TextStyle poppinsRegular = new TextStyle(fontFamily: 'Poppins', fontSize: 19.0);
TextStyle poppinsMedium = new TextStyle(fontFamily: 'Poppins Medium', fontSize: 30.0);

class AddPhoneWidget extends StatefulWidget{
  @override
  AddPhoneState createState() => new AddPhoneState();
}

class AddPhoneState extends State<AddPhoneWidget> {
  final TextEditingController _controller = new TextEditingController();

  @override
  Widget build(BuildContext context) {
      return new Scaffold(
         body: new LayoutBuilder(
           builder: (BuildContext context, BoxConstraints constraintss) {
             return SingleChildScrollView(
               child: 
                   new ConstrainedBox(
                    constraints: new BoxConstraints(minHeight: constraintss.maxHeight),
                    child:  new Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            new Flexible(
                              flex: 0,
                              child: new Column( 
                                 children: [
                                  cellphoneIcon,
                                  new Padding(
                                    padding: new EdgeInsets.fromLTRB(0.0, 30.0, 0.0, 5.0),
                                    child: new Text("Qual o seu celular ?" , style: poppinsMedium),
                                  ),
                                  new Text("Digite o número abaixo", style: poppinsRegular),

                                  new Container(
                                    padding: new EdgeInsets.only(top: 50.0),
                                    width: 320.0,
                                    child:
                                      new TextField(
                                        controller: _controller,
                                        keyboardType: TextInputType.phone,
                                        textAlign: TextAlign.center ,
                                        decoration: new InputDecoration(
                                          hintText: '55 (00) 00000-0000',
                                        ),
                                      ) 
                                  ),
                                ],
                              )
                            ),
                            new Flexible(
                            flex: 3,
                            fit: FlexFit.loose,
                            child:
                                new FlatButton(
                                  child: new Text('The test button', style: poppinsMedium),
                                  onPressed: () => debugPrint("JOOOJ")
                                )
                            )
                          ]
                        ) 
                    )
             );
           }
         )
      );   

  }
}

**Comment by Hixie** [comment]
Ok, I poked at this a little. I realize the difference between what you're doing and what I was doing when I "solved" it. You are trying to make a button take up all the remaining space, if it's more than its own minimum size. What I was doing was trying to center (actually, space out) a bunch of children, but if they ran out of room have them scroll.

To do what you want, use the following sequence of widgets:
- A LayoutBuilder, to get the size of the general area
  - The SingleChildScrollView so that the contents can scroll
    - A ConstrainedBox that sets a minimum constraint of the maxHeight from the LayoutBuilder's constraints
      - An IntrinsicHeight widget that forces the constraints to be bounded, in theory tightly to the Column's contents' height, but forced by the ConstrainedBox to be at least as high as the viewport.
        - A Column with the children, one or more of which is Expanded.

**Comment by Hixie** [comment]
Ok the behaviour in that first screenshot is crazy. What is going on there. Can you attach the code that made that happen?

**Comment by 98732** [comment]
Not the exact same code, but it produces a similar result.  

```Dart
main:

void main() {
  isAuthenticated().then((authenticate) {
 // isAuthenticated is always returning false for development purposes
    if(authenticate){
      runApp(new MyApp());
    } else {
      runApp(
         new MaterialApp(
          title: 'tst',
          home:  new AddPhoneWidget(),
        )
      );
    }
  });
  


```AddPhone

import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';


Icon cellphoneIcon = new Icon(Icons.phone_iphone, size: 128.0);
TextStyle poppinsRegular = new TextStyle(fontFamily: 'Poppins', fontSize: 19.0);
TextStyle poppinsMedium = new TextStyle(fontFamily: 'Poppins Medium', fontSize: 30.0);

class AddPhoneWidget extends StatefulWidget{
  @override
  AddPhoneState createState() => new AddPhoneState();
}

class AddPhoneState extends State<AddPhoneWidget> {
  final TextEditingController _controller = new TextEditingController();

  @override
  Widget build(BuildContext context) {
      return new Scaffold(
         body: new LayoutBuilder(
           builder: (BuildContext context, BoxConstraints constraintss) {
             return SingleChildScrollView(
               reverse: true,
               child: 
                   new ConstrainedBox(
                    constraints: new BoxConstraints(minHeight: constraintss.maxHeight),
                    child: new IntrinsicHeight(
                      child:
                        new Center( 
                        child: new Padding(
                          padding: const EdgeInsets.only(top: 40.0),
                          child: new Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              new Flexible(
                                flex: 0,
                                child: new Column( 
                                   children: [
                                    cellphoneIcon,
                                    new Padding(
                                      padding: new EdgeInsets.fromLTRB(0.0, 30.0, 0.0, 5.0),
                                      child: new Text("What's your phone number ?" , style: poppinsMedium),
                                    ),
                                    new Text("Type your number below", style: poppinsRegular),
                                        new TextField(
                                          maxLength: 13,
                                          controller: _controller,
                                          keyboardType: TextInputType.phone,
                                          textAlign: TextAlign.center ,
                                          decoration: new InputDecoration(
                                            hintText: '55 (00) 00000-0000',
                                          ),
                                    ),
                                  ],
                                )
                              ),
                              new Expanded(
                              child:
                                  new Column(
                                    mainAxisAlignment: MainAxisAlignment.end,
                                    children: <Widget>[
                                      new Padding(
                                        padding: const EdgeInsets.only(bottom: 25.0),
                                        child: new FlatButton(
                                          child: new Text('Next step', style: poppinsMedium),
                                          onPressed: () => debugPrint("JOOOJ")
                                        ),
                                      )
                                    ],
                                  )
                              )
                            ]
                          ),
                        ) 
                    )
                    )  
                   )
             );
           }
         )
      );   

  }
```

**Comment by 98732** [comment]
This is an experimental project to evaluate whether Flutter is ready for production or not. It was frozen because I was working on projects with higher priority using the web platform.

My big mistake **was running an out of date build** of flutter, **0.2.6**. Today i **switched to beta 0.4.4, and it's working fine.**

Sorry for worring you for nothing Hixie.
Again, thanks for the support 
:)

**Comment by Hixie** [comment]
There's now a `SliverFillRemaining` widget which I think does what everyone here wants. Please let me know if that's not sufficient.

**Comment by Hixie** [comment]
cc @brianegan if you want some patterns to document on the site, my comments on this bug have three patterns which may be of particular interest.

**Comment by brianegan** [comment]
@Hixie Thanks for the heads up! I was dealing with this exact case a couple weeks back as well, and this new Sliver is perfect for my use-case. I'll add it to my list of recipes!

**Comment by MisterJimson** [comment]
SliverFillRemaining does work but causes a Renderflex overflow if any of the content in the SliverFillRemaining goes past the end of the screen.

My use case for this is a widget I have that I want to fill remaining space on large devices that wouldn't need to scroll, but on smaller devices none of the SliverFillRemaining content would be visible until you scroll down.

Any solution?

**Comment by MisterJimson** [comment]
I've tried SingleChildScrollView. But the problem is I need the last item (so second item in my Column in the SingleChildScrollView case) to expand to fill the viewport on larger devices.

If you try to Expand or Flexible the last item it will error as it tries to expand to infinite height.

**Comment by rmtmckenzie** [comment]
@MisterJimson I believe @Hixie was talking about the detailed instructions on how to solve issues like the one you're seeing in the documentation of SingleChildScrollView - look under the [Expanding Content to Fit the Viewport](https://docs.flutter.io/flutter/widgets/SingleChildScrollView-class.html#expanding-content-to-fit-the-viewport) header.

I've run into the issue previously when doing something with slivers though, so I made it into a plugin. I ran into the issue when I wanted to display buttons at the bottom of a list of items, where the buttons would remain at the bottom of the screen once the list items were removed. 

i.e.

```

               ---------------------       ---------------------
              |    some content     |     |   there is now      |
              |    but not much     |     |    a huge           |
              | ------------------- |     |   amount            |
              |                     |     |           of        |
              |     it fills all    |     |   content here      |
              |        of this      |     |    so               |
              |          space      |     |   the buttons will  |
              |                     |     |  need to go slightly|
              |  --------  -------  |     |  off the screen     |
              | | cancel || okay  | |     |  --------  -------  |
              |  --------  -------  |     | | cancel || okay  | |
               ---------------------        --------------------- 

There's one unfortunate bit in the code - it has to pass the viewport's scroll controller into the renderer or else it isn't able to figure out whether it's in the first page of the viewport or not.  It was possible to make it work without that so long as items were never added or removed, but if they were removed it created weird issues in that the 'fill remaining' would fill the place of the last item that was removed even though the list was scrolled.

Here's the plugin though: https://pub.dartlang.org/packages/sliver_fill_remaining_box_adapter, but I'd guess that the sample code Hixie mentioned is probably enough for you.

**Comment by PiN73** [comment]
`SliverFillRemaining` widget didn't work for me, but @Hixie's solution made it.
```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('AppBar'),
        ),
        body: LayoutBuilder(builder: (context, constraints) {
          return SingleChildScrollView(
              child: ConstrainedBox(
                  constraints: BoxConstraints(minHeight: constraints.maxHeight),
                  child: IntrinsicHeight(
                    child: Column(
                        mainAxisSize: MainAxisSize.max,
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          Text('header'),
                          Expanded(
                            child: Container(
                              color: Colors.green,
                              child: Text('body'),
                            ),
                          ),
                          Text('footer'),
                        ]
                    ),
                  )
              )
          );
        })
    );
  }
}
```
Here green container fills all space between footer and header. If the things doesn't fit, they can be scrolled.

**Comment by Vinoth1094** [comment]
> I did this in an app I wrote the other day. It turns out it's easy. :-)
> 
> Wrap a SingleChildScrollView in a LayoutBuilder, then inside the SingleChildScrollView put a ConstrainedBox whose `minHeight` is the `maxHeight` constraint LayoutBuilder saw, and as a child of the ConstrainedBox put your Column with the flexible contents, with its `mainAxisSize` set to `MainAxisSize.min`.

Great answer for an issue which I thought it's impossible. It will be helpful if these things are added in the documentation so that we can know how combination of widgets can be used to make complex UI

**Comment by Skquark** [comment]
Nice, that's the solution I was looking for.. Works great but looks ugly, so made a Widget out of it so I can replace the old SingleChildScrollView containers in the TabBarView with less mess.
```
class SliverScrollView extends StatelessWidget {
  const SliverScrollView({Key key, @required this.child, this.header, this.footer}) : super(key: key);
  final Widget child;
  final Widget header;
  final Widget footer;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(builder: (context, constraints) {
      return SingleChildScrollView(
          child: ConstrainedBox(
              constraints: BoxConstraints(minHeight: constraints.maxHeight),
              child: IntrinsicHeight(
                child: Column(mainAxisSize: MainAxisSize.max, crossAxisAlignment: CrossAxisAlignment.stretch, children: [
                  header ?? Container(),
                  Expanded(child: child),
                  footer ?? Container(),
                ]),
              )));
    });
  }
}
```

**Comment by tedhenry100** [comment]
All I want to do is create a header and footer in a page with a middle item. If there is excess vertical space in the page then center the middle item and have the footer at the bottom. If there is more content than vertical space then have vertically scrollable content. That's not asking for much! The solutions here are complex and I cannot get them to work in my case. Come on!!
