### ISSUE TITLE
Unable to load assets in flutter web: `Flutter Web engine failed to fetch "assets/AssetManifest.smcbin"`

### ISSUE THREAD

**Issue by Yoda-Man** [flutter/flutter#128230]
Assets not loading on flutter web after deploying to server after flutter build web.

**Comment by AhmedHanySaber** [comment]
there are some reasons for your problem 
Check the console: Open the developer console in your browser and look for any error messages that might provide a clue as to what's causing the issue.

Ensure that you have included all necessary files: Make sure that all the files required for your app to run are included in your deployment. Check that you have included the index.html, main.dart.js, and the assets directory.

Check the file paths: Ensure that the file paths in your code are correct. For example, if you have images or other assets in your app, make sure that the file paths in your code match the file paths on the server.

Check the server configuration: Ensure that the server is configured correctly to serve the files required for your app to run. Check that the server is configured to serve the index.html file as the default file and that it is configured to serve the correct MIME types.

Check the caching settings: If you're using caching in your app, ensure that the caching settings are configured correctly. Check that the caching settings on the server are not causing the issue.

Try a different browser: Sometimes, the issue might be browser-specific. Try running your app on a different browser to see if the issue persists.

Run flutter clean and rebuild the app: Try running flutter clean to clear the build cache and rebuild your app. This can sometimes resolve issues with deployment.

**Comment by danagbemava-nc** [comment]
Hi @Yoda-Man,
When opening an issue, please try to provide all or some of the information indicated in the template.

<details>
  <summary>Issue Template</summary>

```
If you are looking for support, please check out our documentation
or consider asking a question on Stack Overflow:
- https://flutter.dev/
- https://api.flutter.dev/
- https://stackoverflow.com/questions/tagged/flutter?sort=frequent

If you have found a bug or if our documentation doesn't have an answer
to what you're looking for, then fill our the template below. Please read
our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

Please attach a small application (ideally just one main.dart file) that
reproduces the problem. You could use https://gist.github.com/ for this.

If the problem is with your application's rendering, then please attach
a screenshot and explain what the problem is.

1. ...
2. ...
3. ...


Please tell us which target platform(s) the problem occurs (Android / iOS / Web / macOS / Linux / Windows)
Which target OS version, for Web, browser, is the test system running?
Does the problem occur on emulator/simulator as well as on physical devices?

Target Platform:
Target OS version/browser:
Devices:

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Finally, paste the output of running `flutter doctor -v` here.
```
</details>

Closing this issue, since no information has been provided.
Thank you.

**Comment by Yoda-Man** [comment]
> there are some reasons for your problem Check the console: Open the developer console in your browser and look for any error messages that might provide a clue as to what's causing the issue.
> 
> Ensure that you have included all necessary files: Make sure that all the files required for your app to run are included in your deployment. Check that you have included the index.html, main.dart.js, and the assets directory.
> 
> Check the file paths: Ensure that the file paths in your code are correct. For example, if you have images or other assets in your app, make sure that the file paths in your code match the file paths on the server.
> 
> Check the server configuration: Ensure that the server is configured correctly to serve the files required for your app to run. Check that the server is configured to serve the index.html file as the default file and that it is configured to serve the correct MIME types.
> 
> Check the caching settings: If you're using caching in your app, ensure that the caching settings are configured correctly. Check that the caching settings on the server are not causing the issue.
> 
> Try a different browser: Sometimes, the issue might be browser-specific. Try running your app on a different browser to see if the issue persists.
> 
> Run flutter clean and rebuild the app: Try running flutter clean to clear the build cache and rebuild your app. This can sometimes resolve issues with deployment.

I know its a bug in flutter because all I did was upgrade build like I used to and noticed the problem. I can see all the assets in the build folder. 

the error in my chrome Console is "Error while trying to load an asset: Flutter Web engine failed to fetch "assets/AssetManifest.smcbin". HTTP request succeeded, but the server responded with HTTP status 404."

**Comment by zhushuihua** [comment]
Yes also encountered the same issue.

below is the demo code..

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Colors.white,
      child: Center(
        child: Image.asset('assets/images/demo.jpg'),
      ),
    );
  }
}

**Comment by zhushuihua** [comment]
I worked in the debug and local release mode, once it is release to the web server, we are seeing the error as below:
Failed to load resource: the server responded with a status of 404 ()

**Comment by Yoda-Man** [comment]
> Hi @Yoda-Man, When opening an issue, please try to provide all or some of the information indicated in the template.
> 
> Issue Template
> Closing this issue, since no information has been provided. Thank you.

Please re-open and look into it. Its a valid bug.
It works perfect on local machine. works fine in debug. Problem occurs after fluttter build web and you deploy.
I can see all the assets in the build folder everything looks good but it just doesn't work.

**Comment by zhushuihua** [comment]
Please note when I downgrade to flutter 3.10.0, the problem disappears and the image will show without any problems.

**Comment by Yoda-Man** [comment]
> Please note when I downgrade to flutter 3.10.0, the problem disappears and the image will show without any problems.

thanks I shall downgrade immediately

**Comment by danagbemava-nc** [comment]
Hi @Yoda-Man, I just deployed the flutter counter app to firebase hosting, and the asset I added to the app loads just fine. 
See the screenshot below. I tested on Safari/Chrome/Firefox/Arc, all browsers display the asset just fine. 

<img width="1181" alt="Screenshot 2023-06-06 at 13 00 09" src="https://github.com/flutter/flutter/assets/88313112/986a45e7-8eee-4c42-b5b9-a52d68b1fb88">

- What version of flutter did you upgrade from? 
- What server is your app hosted on? 
- Do you have this issue with an app created on the latest version of flutter?
- What renderer are you using to deploy your app? 
- Is this on mobile browsers or desktop browsers?

Please also add any additional information that you think might be relevant. 

In the future, when filing an issue, please provide as much information about the issue as you can to make the issues actionable. 

Thank you

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image.asset('assets/images/Dash.png'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.10.3 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (5 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • adb-28291FDH2001SA-5Lv71w._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)   • 00008020-001875E83A38002E                        • ios            • iOS 16.5 20F66
    • macOS (desktop)  • macos                                            • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)     • chrome                                           • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by Yoda-Man** [comment]
> Hi @Yoda-Man, I just deployed the flutter counter app to firebase hosting, and the asset I added to the app loads just fine. See the screenshot below. I tested on Safari/Chrome/Firefox/Arc, all browsers display the asset just fine.
> 
> <img alt="Screenshot 2023-06-06 at 13 00 09" width="400" src="https://user-images.githubusercontent.com/88313112/243702909-986a45e7-8eee-4c42-b5b9-a52d68b1fb88.png">
> * What version of flutter did you upgrade from?
> * What server is your app hosted on?
> * Do you have this issue with an app created on the latest version of flutter?
> * What renderer are you using to deploy your app?
> * Is this on mobile browsers or desktop browsers?
> 
> Please also add any additional information that you think might be relevant.
> 
> In the future, when filing an issue, please provide as much information about the issue as you can to make the issues actionable.
> 
> Thank you
> 
> code sample
> flutter doctor -v

To see the error you can view https://www.soundcentral.africa/
I upgraded from 3.7 to 3.10.2 
The App works fine on Android I can see the Assets 
Problem is only on web on all browsers PC and Mobile
when I run flutter doctor -v  my output is as follows

PS C:\Mobile\sc> flutter doctor -v                              
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.1702], locale en-ZA)
    • Flutter version 3.10.2 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (13 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\trust\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\trust\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\trust\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.37

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by danagbemava-nc** [comment]
Do any of you guys have idm installed on your systems by any chance? 

Can you also try running `flutter clean` & `flutter pub get` before building the web app to see if you have this issue?

**Comment by Yoda-Man** [comment]
> 

I just upgraded again from 3.10.2 to 3.10.3 same problem i will downgrade just now.

**Comment by Yoda-Man** [comment]
> Do any of you guys have idm installed on your systems by any chance?
> 
> Can you also try running `flutter clean` & `flutter pub get` before building the web app to see if you have this issue?

I have tried this 100 times it does not work its a bug only solution is to downgrade flutter version

**Comment by zhushuihua** [comment]
I have deployed two versions to my own website http://abacus.sg

http://abacus.sg/index.html (compiled with flutter 3.10.3), nothing shows up

http://abacus.sg/0/index.html (compiled with flutter 3.10.0), it is working properly.

**Comment by zhushuihua** [comment]
import 'package:flutter/material.dart';

void main() {
  runApp(ColoredBox(
    color: Colors.white,
    child: Center(
      child: Image.asset('assets/math.jpg'),
    ),
  ));
}

**Comment by smelcher** [comment]
I can confirm that I am also having this issue. I tried "flutter clean" + "flutter pub get" but it did not work for me.
I also downgraded to 3.10.0 and it also strangely did not seem to work (I could possibly be doing something wrong there)

**Comment by smelcher** [comment]
Actually, after digging further, I realized that I never successfully downgraded to 3.0.0.  When I try to downgrade to 3.0.0 I get an error:
There is no previously recorded version for channel "stable".
Channel "master" was previously on: 3.0.0-0.0.pre-1198-g0cdb3bf582
.
Channel "beta" was previously on: 2.2.0-10.1.pre

**Comment by darshankawar** [comment]
@Yoda-Man and everyone else in this thread facing the issue, this is likely to be same as https://github.com/flutter/flutter/issues/127297 and probably causing due to https://github.com/flutter/flutter/pull/126837, https://github.com/flutter/flutter/issues/127297#issuecomment-1557708234

I suggest you to follow-up in that issue for further updates. Closing this as a duplicate. If anyone disagrees, write in comments and I'll reopen it.

**Comment by andrewkolos** [comment]
@zhushuihua @Yoda-Man, if assets load correctly when running the app locally, but not after deploying to a web server, it's possible that the web server configuration is preventing the file from being served. There has already been one reported case of this.

For example, in IIS, it's possible to (implicitly or explicitly) deny files with unrecognized extensions from being served. In this case the browser would get a 404 response when requesting any asset. See [File Name Extensions &lt;fileExtensions&gt;](https://learn.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/fileextensions/).

**Comment by andrewkolos** [comment]
@darshankawar Reopening this as https://github.com/flutter/flutter/issues/127297 is now focused on a specific issue encountered only in widget tests.

**Comment by andrewkolos** [comment]
Note for contributors: here is another example of an issue that was caused by flutter changing the file extension of `AssetManifest` file: https://github.com/flutter/flutter/issues/127038#issuecomment-1553497619

**Comment by zhushuihua** [comment]
Yes, this seems to be the case. I added .smcbin as a text/assets MIME type, now it is working.

**Comment by zhushuihua** [comment]
> Note for contributors: here is another example of an issue that was caused by flutter changing the file extension of `AssetManifest` file: [#127038 (comment)](https://github.com/flutter/flutter/issues/127038#issuecomment-1553497619)
Yes, this is the case, I added .smcbin as text/assets MIME type, now it is showing.

**Comment by OllyZA** [comment]
I had this problem hosting the project on IIS . I fixed it by adding this to the web.config file 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <staticContent>
             <mimeMap fileExtension=".smcbin" mimeType="text/xml" />
         </staticContent>
    </system.webServer>
</configuration>
```

**Comment by darshankawar** [comment]
Thanks @andrewkolos for your input. @Yoda-Man Check above solutions and see if they work in your case or not.

**Comment by smelcher** [comment]
Per the above the comment, adding .smcbin to my web.config worked for me

**Comment by andrewkolos** [comment]
> Yes, this seems to be the case. I added .smcbin as a text/assets MIME type, now it is working.

@zhushuihua @OllyZA I'm glad you got this working 🙂. I am not sure it matters, but [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream) is probably the most suitable MIME type for this. You can think of `AssetManifest.smcbin` as a JSON-like object that is encoded in a more efficient binary format.

Note for contributors/archeologists: I've filed https://github.com/flutter/flutter/issues/128456 to document and discuss the root cause of this

**Comment by Yoda-Man** [comment]
Ahh added the Mime type and now the issue is resolved.

**Comment by andrewkolos** [comment]
With https://github.com/flutter/flutter/pull/128621 landing, this issue should stop appearing in an upcoming patch. This change the file extension of `AssetManifest.smcbin` back to `.bin`, which should be recognized by Microsoft IIS by default.

**Comment by rehmnabdul** [comment]
> 

I'm having the same issue. Any solution to that problem?

**Comment by zhushuihua** [comment]
Upgrade flutter to latest version


Sent from Yahoo Mail for iPhone


On Saturday, June 17, 2023, 12:24 PM, Abdur Rahman ***@***.***> wrote:






I'm having the same issue. Any solution to that problem?

**Comment by rehmnabdul** [comment]
> Currently running

Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (2 weeks ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

**Comment by zhushuihua** [comment]
I think 3.10.4 is out already


Sent from Yahoo Mail for iPhone


On Saturday, June 17, 2023, 12:27 PM, Abdur Rahman ***@***.***> wrote:





Currently running


Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f441 (2 weeks ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

**Comment by rehmnabdul** [comment]
Yes, Upgrading it now. Hopefully, It'll fix it. But I have not much hope :)

**Comment by andrewkolos** [comment]
This issue should have been fixed with 3.10.5, which was released a few days ago. Try running `flutter upgrade`. If that alone doesn't work, you can also try `flutter clean` in your projects.

**Comment by mhussnainshabbir** [comment]
its working with the latest:
Flutter (Channel stable, 3.10.5)

**Comment by tim-coder** [comment]
I upgraded to 3.10.5 on MacOS and still get the same error.

`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.6 21G646 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
`

**Comment by zhushuihua** [comment]
Run flutter clean and rebuild


Sent from Yahoo Mail for iPhone


On Saturday, June 24, 2023, 11:24 PM, tim-coder ***@***.***> wrote:




I upgraded to 3.10.5 on MacOS and still get the same error.

`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.6 21G646 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
`

**Comment by tim-coder** [comment]
I did all that to no avail.

I downgraded to 3.10.0 and the problem persists. I think the problem is browser related. The only other change is that my Firefox was upgraded to 114.0.2 (64-bit). 

I'll try an older version of Firefox when I get a minute.

**Comment by zhushuihua** [comment]
Flutter 3.10.5 no longer produces smcbin file, it reverted to bin file instead. So probably you should remove cache from your web browser


Sent from Yahoo Mail for iPhone


On Sunday, June 25, 2023, 12:27 AM, tim-coder ***@***.***> wrote:




I did all that to no avail.

I downgraded to 3.10.0 and the problem persists. I think the problem is browser related. The only other change is that my Firefox was upgraded to 114.0.2 (64-bit).

I'll try an older version of Firefox when I get a minute.

**Comment by Yoda-Man** [comment]
3.10.5 resolved the issue. It could be a chaching issue

**Comment by tim-coder** [comment]
I think Yoda-Man is right - a caching issue.

I loaded my app in a the previous version of Firefox (114.0.1) and it worked. I then tried it in the latest version of Firefox (114.0.2) and it worked! (Using the same profile).

There are no issues that I can find with 3.10.5

Thanks all for your input.
