### ISSUE TITLE
Flutter does not contain all registered ThemeExtension objects in tree.

### ISSUE THREAD

**Issue by lazarvgd** [flutter/flutter#128871]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am trying to abstract ThemeExtension in order to cover different variants of widgets(see the code). I have created a few extensions (MyPrimaryLightButtonColor,MyPrimaryDarkButtonColor, MySuccessButtonColor) that should contain different colors, so they can be used in my custom button widget. 

During debugging, tree `Theme.of(context).extensions` contains only one object, instead of two, but I cannot get any from the tree whatsoever. 

### Expected results

Registered object should be accessible during the runtime.
It should be possible to access 

### Actual results

Theme.of(context).extension<type>() returns null instead of desired object.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          background: Color(0xFFf5f7fa),
          primary: Color(0xFF0091F7),
          secondary: Color(0xFF002766),
          surface: Color(0xFF002766),
          error: Color(0xFFf30303),
          onBackground: Color(0xFF002766),
          onError: Color(0xFFFFFFFF),
          onPrimary: Color(0xFFFFFFFF),
          onSecondary: Color(0xFFFFFFFF),
          onSurface: Color(0xFF002766),
        ),
        extensions: <ThemeExtension<dynamic>>[
          MyPrimaryLightButtonColor(),
          MySuccessButtonColor()

        ],
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          background: Color(0xFFf5f7fa),
          primary: Color(0xFF0091F7),
          secondary: Color(0xFF002766),
          surface: Color(0xFF002766),
          error: Color(0xFFf30303),
          onBackground: Color(0xFF002766),
          onError: Color(0xFFFFFFFF),
          onPrimary: Color(0xFFFFFFFF),
          onSecondary: Color(0xFFFFFFFF),
          onSurface: Color(0xFF002766),
        ),
        extensions: <ThemeExtension<dynamic>>[
          MyPrimaryDarkButtonColor(),
          MySuccessButtonColor()
        ],
      ),
      themeMode: ThemeMode.system,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

abstract class MyButtonColorExtension
    extends ThemeExtension<MyButtonColorExtension> {
  final Color? primaryDefaultColor;
  final Color? primaryHoverColor;
  final Color? primaryActiveColor;
  final Color? primaryFocusColor;
  final Color? primaryDisabledColor;
  final Color? textColor;
  final Color? textDisabledColor;

  MyButtonColorExtension({
    this.primaryDefaultColor,
    this.primaryHoverColor,
    this.primaryActiveColor,
    this.primaryFocusColor,
    this.primaryDisabledColor,
    this.textColor,
    this.textDisabledColor,
  });
}

class MyPrimaryLightButtonColor extends MyButtonColorExtension {
  MyPrimaryLightButtonColor({
    super.primaryDefaultColor = const Color(0xFF002766),
    super.primaryHoverColor = const Color(0xFF001433),
    super.primaryActiveColor = const Color(0xFF000205),
    super.primaryFocusColor = const Color(0xFF002766),
    super.primaryDisabledColor = const Color(0xFF002766),
    super.textColor = const Color(0xFFFFFFFF),
    super.textDisabledColor = const Color(0xFF1F65D7),
  });

  @override
  ThemeExtension<MyButtonColorExtension> lerp(
      covariant ThemeExtension<MyButtonColorExtension>? other, double t) {
    if (other is! MyPrimaryLightButtonColor) {
      return this;
    }
    return MyPrimaryLightButtonColor(
      primaryDefaultColor: Color.lerp(
        primaryDefaultColor,
        other.primaryDefaultColor,
        t,
      )!,
      primaryHoverColor: Color.lerp(
        primaryHoverColor,
        other.primaryHoverColor,
        t,
      )!,
      primaryActiveColor: Color.lerp(
        primaryActiveColor,
        other.primaryActiveColor,
        t,
      )!,
      primaryFocusColor: Color.lerp(
        primaryFocusColor,
        other.primaryFocusColor,
        t,
      )!,
      primaryDisabledColor: Color.lerp(
        primaryDisabledColor,
        other.primaryDisabledColor,
        t,
      )!,
      textColor: Color.lerp(
        textColor,
        other.textColor,
        t,
      )!,
      textDisabledColor: Color.lerp(
        textDisabledColor,
        other.textDisabledColor,
        t,
      )!,
    );
  }

  @override
  ThemeExtension<MyButtonColorExtension> copyWith({
    Color? primaryDefault,
    Color? primaryHover,
    Color? primaryActive,
    Color? primaryFocus,
    Color? primaryDisable,
    Color? textColor,
    Color? textDisableColor,
  }) {
    return MyPrimaryLightButtonColor(
      primaryDefaultColor: primaryDefault,
      primaryHoverColor: primaryHover,
      primaryActiveColor: primaryActive,
      primaryFocusColor: primaryFocus,
      primaryDisabledColor: primaryDisable,
      textColor: textColor,
      textDisabledColor: textDisableColor,
    );
  }
}

class MyPrimaryDarkButtonColor extends MyButtonColorExtension {
  MyPrimaryDarkButtonColor({
    super.primaryDefaultColor = const Color(0xFFD5E2F6),
    super.primaryHoverColor = const Color(0xFFA8C4F0),
    super.primaryActiveColor = const Color(0xFF79A5EC),
    super.primaryFocusColor = const Color(0xFFD5E2F6),
    super.primaryDisabledColor = const Color(0xFFD5E2F6),
    super.textColor = const Color(0xFF293642),
    super.textDisabledColor = const Color(0xFF4786EB),
  });

  @override
  ThemeExtension<MyButtonColorExtension> copyWith({
    Color? primaryDefault,
    Color? primaryHover,
    Color? primaryActive,
    Color? primaryFocus,
    Color? primaryDisable,
    Color? textColor,
    Color? textDisableColor,
  }) {
    return MyPrimaryDarkButtonColor(
      primaryDefaultColor: primaryDefault,
      primaryHoverColor: primaryHover,
      primaryActiveColor: primaryActive,
      primaryFocusColor: primaryFocus,
      primaryDisabledColor: primaryDisable,
      textColor: textColor,
      textDisabledColor: textDisableColor,
    );
  }

  @override
  ThemeExtension<MyButtonColorExtension> lerp(
      covariant ThemeExtension<MyButtonColorExtension>? other, double t) {
    if (other is! MyPrimaryDarkButtonColor) {
      return this;
    }
    return MyPrimaryDarkButtonColor(
      primaryDefaultColor: Color.lerp(
        primaryDefaultColor,
        other.primaryDefaultColor,
        t,
      )!,
      primaryHoverColor: Color.lerp(
        primaryHoverColor,
        other.primaryHoverColor,
        t,
      )!,
      primaryActiveColor: Color.lerp(
        primaryActiveColor,
        other.primaryActiveColor,
        t,
      )!,
      primaryFocusColor: Color.lerp(
        primaryFocusColor,
        other.primaryFocusColor,
        t,
      )!,
      primaryDisabledColor: Color.lerp(
        primaryDisabledColor,
        other.primaryDisabledColor,
        t,
      )!,
      textColor: Color.lerp(
        textColor,
        other.textColor,
        t,
      )!,
      textDisabledColor: Color.lerp(
        textDisabledColor,
        other.textDisabledColor,
        t,
      )!,
    );
  }
}

class MySuccessButtonColor extends MyButtonColorExtension {
  MySuccessButtonColor({
    super.primaryDefaultColor = const Color(0xFF00DD31),
    super.primaryHoverColor = const Color(0xFF00C92C),
    super.primaryActiveColor = const Color(0xFF00AA25),
    super.primaryFocusColor = const Color(0xFF00DD31),
    super.primaryDisabledColor = const Color(0xFF00DD31),
    super.textColor = const Color(0xFF002766),
    super.textDisabledColor = const Color(0xFF00851D),
  });

  @override
  ThemeExtension<MyButtonColorExtension> copyWith({
    Color? primaryDefault,
    Color? primaryHover,
    Color? primaryActive,
    Color? primaryFocus,
    Color? primaryDisable,
    Color? textColor,
    Color? textDisableColor,
  }) {
    return MySuccessButtonColor(
      primaryDefaultColor: primaryDefault,
      primaryHoverColor: primaryHover,
      primaryActiveColor: primaryActive,
      primaryFocusColor: primaryFocus,
      primaryDisabledColor: primaryDisable,
      textColor: textColor,
      textDisabledColor: textDisableColor,
    );
  }

  @override
  ThemeExtension<MyButtonColorExtension> lerp(
      covariant ThemeExtension<MyButtonColorExtension>? other, double t) {
    if (other is! MySuccessButtonColor) {
      return this;
    }
    return MySuccessButtonColor(
      primaryDefaultColor: Color.lerp(
        primaryDefaultColor,
        other.primaryDefaultColor,
        t,
      )!,
      primaryHoverColor: Color.lerp(
        primaryHoverColor,
        other.primaryHoverColor,
        t,
      )!,
      primaryActiveColor: Color.lerp(
        primaryActiveColor,
        other.primaryActiveColor,
        t,
      )!,
      primaryFocusColor: Color.lerp(
        primaryFocusColor,
        other.primaryFocusColor,
        t,
      )!,
      primaryDisabledColor: Color.lerp(
        primaryDisabledColor,
        other.primaryDisabledColor,
        t,
      )!,
      textColor: Color.lerp(
        textColor,
        other.textColor,
        t,
      )!,
      textDisabledColor: Color.lerp(
        textDisabledColor,
        other.textDisabledColor,
        t,
      )!,
    );
  }
}


class MyCard extends StatelessWidget {
  const MyCard({super.key});

  @override
  Widget build(BuildContext context) {
    var theme = Theme.of(context);
    return Card(
      child: Container(
        width: 300,
        height: 300,
        color: theme.brightness == Brightness.light
            ? Colors.white
            : const Color(0xFF293642),
        child: const Center(
          child: Text('MyCard'),
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  late FocusNode focusNode = FocusNode()
    ..addListener(() {
      setState(() {});
    });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const MyCard(),
            ElevatedButton(
              onPressed: () {},
              child: const Text('my button'),
            ),
            const ListTile(
              leading: Icon(Icons.ac_unit),
              title: Text('my title'),
              subtitle: Text('my subtitle'),
              trailing: Icon(Icons.ac_unit),
            ),
            TextButton(onPressed: () {}, child: const Text('my button')),
            const Text(
              'You have pushed the button this many times:',
            ),
            TextField(
                focusNode: focusNode,
                // enabled: false,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Enter your username',
                  focusColor: Colors.red,
                  focusedBorder: OutlineInputBorder(
                    borderSide: BorderSide(
                      color: Colors.red,
                    ),
                  ),
                )),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const DummyMyButton(
              variant: ButtonVariant.success,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


enum ButtonVariant {
  primary,
  secondary,
  highlight,
  ghost,
  danger,
  success,
  confirmation,
}

class DummyMyButton extends StatelessWidget {
  final ButtonVariant variant;

  const DummyMyButton({super.key, this.variant = ButtonVariant.primary});

  @override
  Widget build(BuildContext context) {
    final MyButtonColorExtension? ext = _getColorVariant(context);
    return TextButton(
      style: ButtonStyle(
        backgroundColor: MaterialStatePropertyAll(ext?.primaryActiveColor),
        foregroundColor: MaterialStatePropertyAll(ext?.textColor),
      ),
      onPressed: () {},
      child: const Text('Dummy Button'),
    );
  }

  MyButtonColorExtension? _getColorVariant(
      BuildContext context,
      ) {
    final _brightness = Theme.of(context).brightness;
    var extensions = Theme.of(context).extensions;
    switch (variant) {
      case ButtonVariant.success:
        print('this is null? : ${Theme.of(context).extension<MySuccessButtonColor>() == null}}');
        return Theme.of(context).extension<MySuccessButtonColor>();
      case ButtonVariant.primary:
        if (_brightness == Brightness.light) {
          return Theme.of(context).extension<MyPrimaryLightButtonColor>();
        } else {
          return Theme.of(context).extension<MyPrimaryDarkButtonColor>();
        }
      default:
        return Theme.of(context).extension<MyPrimaryLightButtonColor>();
    }
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.10.4 on channel stable at /Users/<name>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (9 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/<name>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 8ABAE57A-C377-41E2-A9E2-45422CC4270A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by lazarvgd** [comment]
@dam-ease thanks for quick response, I have a few questions regarding the topic.

- am I using the feature in the way it was never meant to be used?
- is this a bug?
- if this is a bug, how long will it take to fix this issue?I am highly rely on this approach since design is not Material friendly and this is the best solution that I found, other than hardcoding style of every widget.

thanks

**Comment by dam-ease** [comment]
Hi @lazarvgd. Tried figuring out if you were using it in the right way as well. Here is a simple example that works fine on my end but only with one object assigned to the extension. Can you check if it fits into your use case as well?

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {

  ThemeMode _themeMode = ThemeMode.light;

  setThemeMode() {
    setState(() {
      if(_themeMode == ThemeMode.light) {
        _themeMode = ThemeMode.dark;
      } else {
        _themeMode = ThemeMode.light;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      themeMode: _themeMode,
      theme: ThemeData(
        brightness: Brightness.light,
        extensions: {
          const MyTheme(
            heading47: TextStyle(
              color: Colors.red,
            ),
          ),
        },
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
      ),
      home: Home(onFabPressed: setThemeMode),
    );
  }
}

class Home extends StatelessWidget {

  final VoidCallback onFabPressed;

  const Home({required this.onFabPressed, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Center(
        child: Text(
          'Heading47',
          style: MyTheme.maybeOf(context)?.heading47,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: onFabPressed,
        child: const Icon(Icons.brightness_high),
      ),
    );
  }
}

@immutable
class MyTheme extends ThemeExtension<MyTheme> {
  const MyTheme({
    required this.heading47,
  });

  final TextStyle heading47;

  @override
  ThemeExtension<MyTheme> copyWith({
    TextStyle? heading47,
  }) {
    return MyTheme(heading47: heading47 ?? this.heading47);
  }

  @override
  ThemeExtension<MyTheme> lerp(
    ThemeExtension<MyTheme>? other,
    double t,
  ) {
    if (other is! MyTheme) return this;

    return MyTheme(
      heading47: TextStyle.lerp(heading47, other.heading47, t)!,
    );
  }

  @override
  bool operator ==(Object other) {
    if (other is! MyTheme) return false;

    return other.heading47 == heading47;
  }

  @override
  int get hashCode => Object.hashAll([heading47]);

  static MyTheme? maybeOf(BuildContext context) {
    return Theme.of(context).extension<MyTheme>();
  }

  static MyTheme of(BuildContext context) {
    return Theme.of(context).extension<MyTheme>()!;
  }
}

``` 

</p>
</details>

**Comment by lazarvgd** [comment]
hi @dam-ease I am asking for assistance because this is not expected behaviour of the feature (if it is then docs need to be updated), I don't see why I cannot use abstraction as long as I implement required methods and follow required rules by compiler. I didn't ask to tech me, fix a bug for me, but why Flutter does not register both objects as extensions. 

There is no documentation on how it should not be used or how it should be used. [The documentation](https://api.flutter.dev/flutter/material/ThemeExtension-class.html) contains api info and basic use case with the video, but other than that it is poorly described. 

FYI r/FlutterHelp is set to private due to protests regarding Reddit's pricing policy...
Stack Overflow cannot fix it, in case it is a bug, so I reached here in case that this is bug and kindly asked if this is a bug.
I know this is public repo and all is based on good will and volunteering, but if you are not in a mood, please leave it, maybe somebody else is willing to help and determine the problem. Either documentation should be updated or the bug should be fixed or it is PEBCAK, so I would like know which one of this is :) 

thanks

**Comment by dam-ease** [comment]
Hi @lazarvgd. I guess I misunderstood your last comment, it seemed the original issue which was Flutter doesn't contain registered ThemeExtension object was solved and you needed help with abstraction. Reading through the edits, can you share the updated code sample??

**Comment by lazarvgd** [comment]
Hi @dam-ease, no the problem is not solved, if you run the code snippet and debug you will observed that objects are missing from the extensions map. For some reason, flutter does not allow inherited classes to be registered in the right order.

Code that does not work: https://pastebin.com/TjD7yvmv
Code that works: https://pastebin.com/Uaiz1RK4

In the first code snippet you will find, during the debug time, that only one object is present and even though it is present it cannot be fetched.

In the second code snippet, everything works fine, because I omitted abstraction of common schemes. 

Please, run the first code snippet and observe the extensions map.

Thanks

**Comment by lazarvgd** [comment]
@dam-ease thank you!

Can you tell me what would be the next steps? Can we consider this as a bug?

thanks

**Comment by lazarvgd** [comment]
Hello @dam-ease, do you have any update on this one? 

thanks

**Comment by HansMuller** [comment]
CC @guidezpl

**Comment by guidezpl** [comment]
This is WAI based on https://github.com/flutter/flutter/blob/main/packages/flutter/lib/src/material/theme_data.dart#L1022-L1023. The same thing would happen if you passed multiple theme extensions of the same type to `extensions`. 

This is beyond the scope of this issue, but it seems counterproductive to create separate extensions containing the same properties. Why not just use the same extension? The example in https://api.flutter.dev/flutter/material/ThemeExtension-class.html uses the same extension twice (light & dark), but there's no upper limit on reusing the extension to define additional sets of colors.

**Comment by lazarvgd** [comment]
Hi @guidezpl, thanks for the answer. 

The idea was to have different colors and text styles, exactly 12 of them (6 for light, 6 for dark mode), based on the button purpose and theme, since the buttons layout is the same.
So, abstracting common fields and assigning the concrete values to in child classes was a solution, rather than piling up  the code in the extension array. 

Anyways, thanks for the response, I will close this issue. :)
