### ISSUE TITLE
[Impeller] Improve scaling of very large images

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#128885]
Steps:

- Find a very high resolution image that exceeds the max limits of a texture size, for example https://github.com/zesage/panorama/blob/master/example/assets/panorama.jpg
- Try to load that image (with or without actually rendering it) on an Impeller enabled app.

> [VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (20266, 10134) exceeds maximum supported size of (16384, 16384)
> [VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.

One option would be to _always_ downscale to at least the max texture size, even if the user did not request downscaling of the image.

It may be worth creating some kind of package that automatically breaks up super large images into tiles for users who really want/need to render very high resolution images at scale.

**Comment by dnfield** [comment]
Here's a base64 encoded 17000x2 PNG image generated from pngpixel.com that shows this problem.

```
iVBORw0KGgoAAAANSUhEUgAAQmgAAAACCAYAAAA6VzmzAAAAo0lEQVR42u3QMQEAAAgDoJnc6LOGB0Rg2mwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBXps1qAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAXw57hgT9XO8leQAAAABJRU5ErkJggg==
```

The panorama image linked above is actually not big enough to cause this problem by itself.

**Comment by dnfield** [comment]
Ok I was wrong again.

I missed this:

```
  target_size.set(std::min(static_cast<int32_t>(max_texture_size.width),
                           target_size.width()),
                  std::min(static_cast<int32_t>(max_texture_size.height),
                           target_size.height()));
```

This has other problems though - we may not be correctly scaling the image if it's only too big on one dimension.

**Comment by bdero** [comment]
@chinmaygarde Mentioned that Skia scales down SkImages that are too large to store as a backend Texture, and recommended tracking scale values as part of the `Texture` itself if we wind up going with this approach for Impeller. Then, we can perform the UV correction when drawing.

**Comment by calcitem** [comment]
I also encountered a similar problem. This problem did not occur in earlier versions, but occurred after updating Flutter to 3.22. It still occurred after upgrading to 3.22.1.

```txt
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (6000000000, 6000000000) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
```

**Comment by spartaman** [comment]
I also encountered a similar problem. This problem did not occur in earlier versions, but occurred after updating Flutter to 3.22. It still occurred after upgrading to 3.22.1. No problem on Android.

[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (4000000000, 4000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.

**Comment by calcitem** [comment]
After verification, I found that this problem does not exist in Flutter v3.19.6, but it appears after upgrading to the latest version.

**Comment by Abion47** [comment]
I'm also getting this error after updating to 3.22.2.

```
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
```

The weird part is that the image I'm trying to load and display isn't anywhere near the 8192 x 8192 max resolution it reports, and certainly not the 2 billion x 2 billion texture size it's apparently trying to create.

**Comment by Abion47** [comment]
After looking into it, I think I am running into the same problem as #149165. Furthermore, I think that ticket was closed prematurely since it's referring to a problematic behavior of an unbounded widget that isn't necessarily related to drawing a static images (in its case, the `BackdropFilter` with the blur effect), whereas this ticket seems to be more concerned with the behavior of drawing static images that really are just that big.

**Comment by test0terter0n** [comment]
Any updates? For us this topic is a showstopper for the update to flutter 3.22

**Comment by ramaarf** [comment]
Is there any workaround? 
I'm also encountered this issue

**Comment by redDwarf03** [comment]
Not resolved with 3.22.3 despite
```https://github.com/flutter/flutter/issues/149700 - [Impeller] Fixes rendering corruption when running on Intel mac simulators.
https://github.com/flutter/flutter/issues/149701 - [Impeller] Fixes an issue on iOS that causese paths to render incorrectly.
https://github.com/flutter/flutter/issues/149702 - [Impeller] Corrects and issue on iOs where coverage computation results in distored pixels in Impeller targets.
https://github.com/flutter/flutter/issues/149704 - [Impeller] Fixes and issue on iOS where flickering may be occur when translating a blurred rounded rectangle.
https://github.com/flutter/flutter/issues/149745 - [Impeller] Fixes a segfault on iOS when tessellating empty convex polygons.
https://github.com/flutter/flutter/issues/149771 - [Impeller] Fixes a rendering error on iOS when advanced blend is double scaled.```

**Comment by Deecency** [comment]
Are there any solutions? I'm also facing this same issue caused by using  BackdropFilter with the blur effect


**Code**

```
Builder(
      builder: (context) {
        return Stack(
          children: [
            Positioned.fill(
              child: GestureDetector(
                onTap: () => Navigator.pop(context),
                child: BackdropFilter(
                  filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.blueAccent.withOpacity(0.55),
                    ),
                  ),
                ),
              ),
            ),
            Dialog(
              backgroundColor: Colors.white,
              elevation: 1,
              clipBehavior: Clip.hardEdge,
              insetPadding: REdgeInsets.symmetric(horizontal: 16),
              alignment: Alignment.center,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
              child: Container(
                width: 100.width,
                padding: padding ?? REdgeInsets.symmetric(horizontal: 16, vertical: 24),
                child: child,
              ),
            ),
          ],
        );
      },
    ),
```



 **Logs**

```
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.


```

Flutter Doctor

> Doctor summary (to see all details, run flutter doctor -v):
> [!] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-NG)
>     ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.6/libexec/bin/dart, which is not inside your current Flutter SDK
>       checkout at /Users/decencyanukam/fvm/versions/3.22.1. Consider adding /Users/decencyanukam/fvm/versions/3.22.1/bin to the front of your path.
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2024.1)
> [✓] VS Code (version 1.91.1)
> [✓] Connected device (5 available)
> [✓] Network resources
> 
> ! Doctor found issues in 1 category.

**Comment by b-nugent** [comment]
@chaeMil I think you may be onto something here. After upgrading to Flutter 3.22.2 my team discovered this issue regarding a widget using a BackdropFilter but so far only on an iPhone 13 mini. We're in the process of attempting to reproduce on other iPhone devices.

This is also a showstopper for us and we'll likely need to downgrade to 3.19 if there is no reliable fix.

**Comment by chinmaygarde** [comment]
This issue has fallen through the cracks a bit and needs re-triage.

### Additional Context for Triagers

Dans original ask was that we do something more elegant that just resize the texture to the max GPU supported texture size when the original image was too big. This leads to loss of fidelity. To be clear, very early on, we didn't do this with Impeller but that was [fixed as of this patch](https://github.com/flutter/engine/commit/af294fbae0b). Impeller matches Skia behavior in that regard. And so, this was a feature-request for better fidelity for such images using perhaps something like auto-tiling. And it was prioritized as such.

But @calcitem s comment on June 01 indicates that there might have been a regression with 3.22. The regression is not with the allocation of textures for framework provided images, but for textures needed for subpasses. I haven't seen any of the reporters mention framework provided images doing this and @Deecency s [reduced test case is instructive](https://github.com/flutter/flutter/issues/128885#issuecomment-2246328143) in that it doesn't use any such images. 

Recommend re-triaging this as a regression in ~3.22 using the new reduced test case and perhaps creating a separate issue for Dans feature-request. The presence of "Requested texture size `<foo>` exceeds maximum supported size of `<bar>`." in the original comment likely makes this a search engine magnet and I originally was extremely confused by the comment chain.

cc @jonahwilliams @bdero @gaaclarke who may have additional context of if recent patches that tinkered with subpass texture sizes.

**Comment by jonahwilliams** [comment]
I don't think this issue is related to resizing textures, it looks like the problem is actually fixed with https://github.com/flutter/engine/pull/54032 . Maybe we should consider a cherry pick into 3.24

**Comment by chinmaygarde** [comment]
Sounds good. I tossed this on the agenda for the sync as a CP candidate. Will also check Jims patch did the trick.

**Comment by flar** [comment]
> I don't think this issue is related to resizing textures, it looks like the problem is actually fixed with [flutter/engine#54032](https://github.com/flutter/engine/pull/54032) . Maybe we should consider a cherry pick into 3.24

https://github.com/flutter/engine/pull/54032 wasn't actually plumbed into anything and was just an "accuracy" improvement on the previous code. For this code to have fixed anything then the actual fix would have been either:

- https://github.com/flutter/engine/pull/54013 which introduced the concept of "intervene if the save layer is unbounded"
- https://github.com/flutter/engine/pull/54085 which uses the PR above to refine the detection of "unbounded"

**Comment by jonahwilliams** [comment]
Right, like @flar mentioned we can't just CP the patch I linked - we'd either have to do both of them or my work around patch I landed earlier.

**Comment by flar** [comment]
54013 can be cherry-picked on its own.

CP of 54085 would require also CP of 54032  and  54013...

**Comment by calcitem** [comment]
I found that the latest version of Flutter 3.24.0 seems to solve this problem.

**Comment by b-nugent** [comment]
Many issues are being redirected to this one (like #153221), making it difficult to understand what aspect of this might have been fixed.

As of 3.24.0, I'm still seeing a defect related to Impeller and the logs that @dnfield posted. In my case, the entire screen goes blank as a widget using BackdropFilter attempts to load.

**Comment by Peetee06** [comment]
I get this issue with this widget:
```dart
ImageFiltered(
  imageFilter: ImageFilter.blur(
    sigmaX: 10,
    sigmaY: 10,
    tileMode: TileMode.mirror,
  ),
  child: Opacity(
    opacity: 0.6,
    child: Container(
      height: 10000,
      color: AppColors.lightBlue,
      child: Column(
        children: <Widget>[
          Image.asset(
            model.backgroundImage,
            alignment: Alignment.topCenter,
            width: MediaQuery.of(context).size.width,
            fit: BoxFit.fitWidth,
          ),
          Image.asset(
            'assets/images/background-to-color-transition.png',
            width: double.infinity,
            fit: BoxFit.fitWidth,
          ),
        ],
      ),
    ),
  ),
)
```

Any combination containing any of `ImageFiltered` or `Opacity` with opacity != 1.0 cause it. I need to remove both for the widget to be rendered. In debug builds the screen this widget is on does not respond to touches on buttons etc. Did not yet test production build

**Comment by bewaternow** [comment]
same here, 3.24.0

**Comment by ziqq** [comment]
> same here, 3.24.0

Yes.

**Comment by Abion47** [comment]
I'm going to vote again for reopening #149165. The specific issue of large images appears to be fixed, but the related issue of widgets like `BackdropFilter` is very much not.

**Comment by alarkirikal** [comment]
Started seeing the same thing happening on 3.24.3

**Comment by lucas-goldner** [comment]
I upgraded my app today and saw this as well on 3.24.3

**Comment by LukeMoody01** [comment]
+1

**Comment by jonahwilliams** [comment]
From discussion in the weekly, we think that we've narrowed down the number of cases this can occur:

* Matrix ImageFilters with large scaling parameters
* Snapshot computation

For both cases, we're going to cap scaling by the max texture size.

**Comment by admincode1** [comment]
Any updates on this ?
I had to use <key>FLTEnableImpeller</key> <false/> key. All errors and previous issues disappeared, but is it recommended?
Currently on Flutter 3.24.3.

**Comment by shahmirzali49** [comment]
any progress on this issue?

**Comment by goj1** [comment]
Guys, this commands work for me:

flutter upgrade
flutter pub upgrade

I hope it help you!

**Comment by jonahwilliams** [comment]
We believe this is fully fixed in 3.27 and 3.29

**Comment by Constans** [comment]
Still getting this error on 3.29.2:
```
[ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(203)] Break on 'ImpellerValidationBreak' to inspect point of failure: Invalid texture descriptor.
```
After disabling the Impeller renderer in the manifest file the issue goes away.
```
        <meta-data
                android:name="io.flutter.embedding.android.EnableImpeller"
                android:value="false" />
```

**Comment by jonahwilliams** [comment]
Its likely that you're experiencing a different issue that is not related to this bug, except in terms of error messages. Continuing to comment on this on instead of file a bug with a repro is not going to lead to a fix for you.
