### ISSUE TITLE
GoogleMap widget causes crash on TabBarView

### ISSUE THREAD

**Issue by berkeenesakt** [flutter/flutter#130873]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the app.
2. Put GoogleMap as TabBarView's children.
3. Wait for the GoogleMap to load.
4. Skip to the next tab.
The app crashes without a helpful log.

### Expected results

The app should not crash.

### Actual results

The app crashes without a helpful log when skipping to the next tab.

### Code sample

<details><summary>Code sample</summary>

```dart
Expanded(
              child: DefaultTabController(
                length: 5,
                child: TabBarView(
                    physics: NeverScrollableScrollPhysics(),
                    controller: tabController,
                    children: [
                      Placeholder(),
                      GoogleMap(),
                      Placeholder(),
                      Placeholder(),
                      Placeholder()
                    ]),
              ),
            ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

iOS Crash Report: 
[ios_report.txt](https://github.com/flutter/flutter/files/12094178/ios_report.txt)
Console Log: 
[console_logs.txt](https://github.com/flutter/flutter/files/12094181/console_logs.txt)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-TR)
    • Flutter version 3.10.5 on channel stable at /Users/berkeenesaktumen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/berkeenesaktumen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 4329F2CF-CDE2-4290-9531-8D1E9B7C3186 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @berkeenesakt. Thanks for filing this issue. I'm currently unable to reproduce this issue on the latest flutter versions. Can you provide more information on how this issue occurs.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State createState() => _HomePageState();
}

class _HomePageState extends State with TickerProviderStateMixin {
  TabController? tabController;
  final LatLng _center = const LatLng(45.521563, -122.677433);
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    tabController = TabController(length: 5, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 5,
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blueGrey.shade500,
          title: const Text('TabBar Widget'),
          bottom: const TabBar(
            indicatorColor: Colors.lime,
            indicatorWeight: 5.0,
            labelColor: Colors.white,
            labelPadding: EdgeInsets.only(top: 10.0),
            unselectedLabelColor: Colors.grey,
            tabs: [
              Tab(
                text: 'Cake',
                icon: Icon(
                  Icons.cake,
                  color: Colors.white,
                ),
                iconMargin: EdgeInsets.only(bottom: 10.0),
              ),
              Tab(
                text: 'Radio',
                icon: Icon(
                  Icons.radio,
                  color: Colors.white,
                ),
                iconMargin: EdgeInsets.only(bottom: 10.0),
              ),
              Tab(
                text: 'Radio',
                icon: Icon(
                  Icons.radio,
                  color: Colors.white,
                ),
                iconMargin: EdgeInsets.only(bottom: 10.0),
              ),
              Tab(
                text: 'Radio',
                icon: Icon(
                  Icons.radio,
                  color: Colors.white,
                ),
                iconMargin: EdgeInsets.only(bottom: 10.0),
              ),
              Tab(
                text: 'Gift',
                icon: Icon(
                  Icons.card_giftcard,
                  color: Colors.white,
                ),
                iconMargin: EdgeInsets.only(bottom: 10.0),
              ),
            ],
          ),
        ),
        body: TabBarView(
            physics: const NeverScrollableScrollPhysics(),
            controller: tabController,
            children: [
              GoogleMap(
                initialCameraPosition: CameraPosition(
                  target: _center,
                  zoom: 10.0,
                ),
              ),
              const Placeholder(),
              const Placeholder(),
              const Placeholder(),
              const Placeholder()
            ]),
      ),
    );
  }
}

``` 

</p>
</details>

<details><summary>Screenshot</summary>
<p>

![simulator_screenshot_E53CDEED-C012-40AF-86C0-5C865CB7AE67](https://github.com/flutter/flutter/assets/53122008/db177f12-4583-4682-beb4-9ce9268241fe)


</p>
</details>  

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
```
[✓] Flutter (Channel master, 3.13.0-6.0.pre.34, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.13.0-6.0.pre.34 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 37ed50ac34 (2 hours ago), 2023-07-19 05:54:05 -0400
    • Engine revision 09389b16d6
    • Dart version 3.1.0 (build 3.1.0-325.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```  

</p>
</details>

**Comment by berkeenesakt** [comment]
It occurs after using app for like 30 mins. You can try to hot reload and hot restart to reproduce the issue, maybe this causes the problem. I am facing it while developing the app. I'm attaching a video. I also faced this problem in my other apps.  

https://github.com/flutter/flutter/assets/81863556/4fb69b63-378e-4b60-8a68-27e12564138a

**Comment by dam-ease** [comment]
Hi @berkeenesakt. Can you try with the code sample in the https://github.com/flutter/flutter/issues/130873#issuecomment-1641962544 to confirm the issue persists?? If it doesn't, kindly provide output of your `flutter run -v`.

**Comment by berkeenesakt** [comment]
In your code sample you are controlling tabs from app bar. In my code there is a next button and I skip to next page with this code: ```dart
tabController.animateTo(index)
```

Can you try to reproduce the issue with this code? I think that is the reason of you can't reproduce the issue.

**Comment by dam-ease** [comment]
Hi @berkeenesakt. For this issue to be workable, we'd need you to kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code instead of code snippets. Thank you!

**Comment by berkeenesakt** [comment]
In my app I use GoogleMap widget on post page and home page. So when I opened the app a GoogleMap widget is building then opening post page is also builds a GoogleMap widget. Maybe building it for 2 times causes the problem. And I saw a post on Stackoverflow, Is it same with my problem?  https://stackoverflow.com/questions/55713603/googlemap-in-pageview

Here is a sample:

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MaterialApp(
    home: GoogleMapTabView(),
  ));
}

class GoogleMapTabView extends StatefulWidget {
  const GoogleMapTabView({super.key});

  @override
  State<GoogleMapTabView> createState() => _GoogleMapTabViewState();
}

class _GoogleMapTabViewState extends State<GoogleMapTabView>
    with SingleTickerProviderStateMixin {
  TabController? _tabController;
  @override
  void initState() {
    _tabController = TabController(length: 3, vsync: this);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Google Map'),
      ),
      body: Column(
        children: [
          Expanded(
            child: DefaultTabController(
                length: 3,
                child: TabBarView(
                  controller: _tabController,
                  children: const [
                    Center(
                      child: Text("First Tab"),
                    ),
                    GoogleMap(
                      initialCameraPosition: CameraPosition(
                        target: LatLng(
                          0,
                          0,
                        ),
                      ),
                    ),
                    Center(
                      child: Text("Third Tab"),
                    ),
                  ],
                )),
          ),
          Padding(
            padding: const EdgeInsets.all(10),
            child: ElevatedButton(
                onPressed: () {
                  if (_tabController!.index < 3) {
                    _tabController!.animateTo((_tabController!.index + 1));
                  }
                },
                child: const Text("Next")),
          ),
        ],
      ),
    );
  }
}

```

**Comment by dam-ease** [comment]
Hi @berkeenesakt. Thanks for the detailed code sample. I am able to reproduce this issue after the second build and after using the app for a while. Using VSCode, I can see a TimeOutException in the logs running `flutter run -v`: 

```
[ +872 ms] The Flutter DevTools debugger and profiler on iPhone 14 Pro is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:51765/POoPlf_sgeA=/
[+12695 ms] Google Maps SDK for iOS version: 5.2.0.0
[        ] New version of Google Maps SDK for iOS available: 8.0.0.0
[+7052 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///Users/dammya/Library/Developer/CoreSimulator/Devices/DCF2031A-7EA9-42FF-8CD4-D4584F3E7
A6D/data/Containers/Data/Application/5BD585D2-E2DE-4C09-A80D-153EF02C9081/tmp/anotherIjqdwL/ano
ther/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future
not completed

[   +2 ms] "flutter run" took 50,260ms.
[ +257 ms] ensureAnalyticsSent: 251ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
``` 

On XCode I can reproduce on first run with the following logs:

```
2023-07-31 08:57:06.984952+0100 Runner[19280:122263] [quic] quic_crypto_session_state_serialize [C4.1.1.1:2] [-fd09b0b196e95390] TLS ticket does not fit (6914 > 6144)
2023-07-31 08:57:19.589680+0100 Runner[19280:119034] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d39478b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010c631b73 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d41c806 _CFThrowFormattedException + 200
	3   CoreFoundation                      0x000000010d41992b -[__NSArrayM insertObject:atIndex:].cold.2 + 0
	4   CoreFoundation                      0x000000010d27d8e4 -[__NSArrayM insertObject:atIndex:] + 951
	5   Flutter                             0x000000011323758b _ZN7flutter30FlutterPlatformViewsController19BringLayersIntoViewENSt21_LIBCPP_ABI_NAMESPACE3mapIxNS1_6vectorINS1_10shared_ptrINS_24FlutterPlatformViewLayerEEENS1_9allocatorIS6_EEEENS1_4lessIxEENS7_INS1_4pairIKxS9_EEEEEE + 309
	6   Flutter                             0x0000000113236da0 _ZN7flutter30FlutterPlatformViewsController11SubmitFrameEP15GrDirectContextRKNSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_10IOSContextEEENS3_10unique_ptrINS_12SurfaceFrameENS3_14default_deleteISA_EEEE + 1058
	7   Flutter                             0x00000001132578b3 _ZN7flutter23IOSExternalViewEmbedder11SubmitFrameEP15GrDirectContextNSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_12SurfaceFrameENS3_14default_deleteIS5_EEEE + 143
	8   Flutter                             0x00000001139d4c0f _ZN7flutter10Rasterizer19DrawToSurfaceUnsafeERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 1281
	9   Flutter                             0x00000001139d6c64 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer13DrawToSurfaceERNS2_20FrameTimingsRecorderERNS2_9LayerTreeEE3$_1NS_9allocatorIS8_EEFvvEEclEv + 26
	10  Flutter                             0x00000001136a291e _ZNK3fml10SyncSwitch7ExecuteERKNS0_8HandlersE + 56
	11  Flutter                             0x00000001139d31bf _ZN7flutter10Rasterizer13DrawToSurfaceERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 357
	12  Flutter                             0x00000001139d3f71 _ZN7flutter10Rasterizer6DoDrawENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_20FrameTimingsRecorderENS1_14default_deleteIS3_EEEENS1_10shared_ptrINS_9LayerTreeEEE + 121
	13  Flutter                             0x00000001139d5775 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS2_8PipelineINS2_13LayerTreeItemEEEEENS_8functionIFbRNS2_9LayerTreeEEEEE3$_1NS_9allocatorISG_EEFvNS_10unique_ptrIS6_NS_14default_deleteIS6_EEEEEEclEOSM_ + 193
	14  Flutter                             0x00000001139d3a1d _ZN7flutter8PipelineINS_13LayerTreeItemEE7ConsumeERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFvNS3_10unique_ptrIS1_NS3_14default_deleteIS1_EEEEEEE + 193
	15  Flutter                             0x00000001139d3378 _ZN7flutter10Rasterizer4DrawERKNSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_8PipelineINS_13LayerTreeItemEEEEENS1_8functionIFbRNS_9LayerTreeEEEE + 150
	16  Flutter                             0x00000001139d5aa4 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS5_8PipelineINS5_13LayerTreeItemEEEEENS_8functionIFbRNS5_9LayerTreeEEEEE3$_0EENS_9allocatorISK_EEFvvEEclEv + 128
	17  Flutter                             0x000000011369f315 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 163
	18  Flutter                             0x00000001136a5d78 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	19  CoreFoundation                      0x000000010d2f3353 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	20  CoreFoundation                      0x000000010d2f2eb0 __CFRunLoopDoTimer + 799
	21  CoreFoundation                      0x000000010d2f2637 __CFRunLoopDoTimers + 243
	22  CoreFoundation                      0x000000010d2ecec8 __CFRunLoopRun + 2183
	23  CoreFoundation                      0x000000010d2ec264 CFRunLoopRunSpecific + 560
	24  GraphicsServices                    0x000000011736524e GSEventRunModal + 139
	25  UIKitCore                           0x000000011fb537bf -[UIApplication _run] + 994
	26  UIKitCore                           0x000000011fb585de UIApplicationMain + 123
	27  Runner                              0x000000010095a74f main + 63
	28  dyld                                0x000000010a176384 start_sim + 10
	29  ???                                 0x0000000201f4141f 0x0 + 8622707743
)
libc++abi: terminating due to uncaught exception of type NSException
Message from debugger: Terminated due to signal 6

``` 

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by dam-ease** [comment]
Hi @berkeenesakt. Trying multiple times on the current `master` channel, this issue seems to not be reproducible, Can you switch to the latest `master` channel: `3.13.0-12.0.pre.40` to confirm this issue still persists on your end as well?

**Comment by berkeenesakt** [comment]
@dam-ease I also cannot reproduce the error in the master channel.

**Comment by dam-ease** [comment]
Thanks for confirming this. I'd be closing this as it seems to have been fixed in latest versions.

**Comment by Fudal** [comment]
@dam-ease A lot of time (more than a month) has passed between reporting this bug the first time and today. In the meantime, a new version 3.10.6 has been released, in which the problem still exists. Since this bug was first reported, it can't be mapped to the master, so just because the bug doesn't exist on the master branch doesn't mean it will be fixed in the next version of the SDK, since the version update has already been out and doesn't include this fix.

**Comment by martin-braun** [comment]
I have the same problem with disposing the Google Maps widget very early. I'd like to quote myself from #131472:

> ### Steps to reproduce
> 
> When popping a `MaterialPageRoute` early that contains a `GoogleMap` widget (either through `Navigator.pop` or through the `AppBar`), the iOS will severely crash.
> 
> It's hard to reproduce for cashed maps, because the map is done loading so fast. It's consistently reproducable if the widget has to load more stuff, such as markers, locations, etc. Try to pop early on initial load to succeed on this reproduction using the code example below.
> 
> The crash appears in production builds as well. The crash also appears sometimes when moving the map around and popping the view immediately after.
> 
> My current guess is that the widget tries to render map tiles when part of the widget does not exist anymore, in particular an array that gets nulled on dispose, but the rendering still tries to access it. This sounds pretty familiar to #105965, although that issue can be bypassed with the new renderer, iOS has no different renderer to play with.
> 
> ### Expected results
> 
> No crash at all.
> 
> ### Actual results
> 
> Severe crash on iOS due to the exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'.
> 
> ### Code sample
> 
> <details><summary>Code sample</summary>
> 
> ```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Google Map iOS Maps Crash Demo',
      themeMode: ThemeMode.light,
      home: HomePage(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("iOS Maps Crash"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: Text("Load Map"),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) {
                        return Scaffold(
                            appBar: AppBar(),
                            body: GoogleMap(
                              zoomGesturesEnabled: false,
                              zoomControlsEnabled: false,
                              myLocationButtonEnabled: false,
                              compassEnabled: false,
                              mapToolbarEnabled: false,
                              initialCameraPosition: CameraPosition(
                                  target: LatLng(-33.8567844, 151.213108),
                                  zoom: 15),
                              mapType: MapType.normal,
                              myLocationEnabled: false,
                            ));
                      },
                    ),
                  );
                },
              ),
            ],
          ),
        ));
  }
}
```
> 
> </details>
> 
> 
> > Note: For a real life example that can consistently be crashed using early back clicks, see https://github.com/martin-braun-net/google_maps_place_picker_mb/tree/master/example as it loads more things and thus keeping the map from finishing loading for a longer period of time.
> 
> ### Screenshots or Video
> 
> <details>
> <summary>Screenshots / Video demonstration</summary>
> 
> ![Flutter iOS Google Maps Crash demonstration](https://github.com/flutter/flutter/assets/24259245/54572c7e-10c8-4457-a842-8b60339e50dd)
> 
> </details>
> 
> 
> ### Logs
> 
> <details><summary>Logs</summary>
> 
> iOS device logs (Xcode):
> 
> ```console
2023-07-28 12:01:17.616885+0200 Runner[78098:23124168] Metal GPU Frame Capture Enabled
2023-07-28 12:01:17.617212+0200 Runner[78098:23124168] Metal API Validation Enabled
2023-07-28 12:01:17.682307+0200 Runner[78098:23124168] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
2023-07-28 12:01:17.794295+0200 Runner[78098:23126211] flutter: The Dart VM service is listening on http://127.0.0.1:52063/uUY7jhAuRog=/
2023-07-28 12:01:26.074418+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.074647+0200 Runner[78098:23124168] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075211+0200 Runner[78098:23124168] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075253+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075786+0200 Runner[78098:23124168] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075834+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.079059+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.079232+0200 Runner[78098:23126138] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:28.721885+0200 Runner[78098:23124168] Google Maps SDK for iOS version: 5.2.0.0
2023-07-28 12:01:28.722059+0200 Runner[78098:23124168] New version of Google Maps SDK for iOS available: 8.0.0.0
2023-07-28 12:01:59.141517+0200 Runner[78098:23124168] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80045478b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004db73 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004dc806 _CFThrowFormattedException + 200
	3   CoreFoundation                      0x00007ff8004d992b -[__NSArrayM insertObject:atIndex:].cold.2 + 0
	4   CoreFoundation                      0x00007ff80033d8e4 -[__NSArrayM insertObject:atIndex:] + 951
	5   Flutter                             0x0000000109df158b _ZN7flutter30FlutterPlatformViewsController19BringLayersIntoViewENSt21_LIBCPP_ABI_NAMESPACE3mapIxNS1_6vectorINS1_10shared_ptrINS_24FlutterPlatformViewLayerEEENS1_9allocatorIS6_EEEENS1_4lessIxEENS7_INS1_4pairIKxS9_EEEEEE + 309
	6   Flutter                             0x0000000109df0da0 _ZN7flutter30FlutterPlatformViewsController11SubmitFrameEP15GrDirectContextRKNSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_10IOSContextEEENS3_10unique_ptrINS_12SurfaceFrameENS3_14default_deleteISA_EEEE + 1058
	7   Flutter                             0x0000000109e118b3 _ZN7flutter23IOSExternalViewEmbedder11SubmitFrameEP15GrDirectContextNSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_12SurfaceFrameENS3_14default_deleteIS5_EEEE + 143
	8   Flutter                             0x000000010a58ec0f _ZN7flutter10Rasterizer19DrawToSurfaceUnsafeERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 1281
	9   Flutter                             0x000000010a590c64 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer13DrawToSurfaceERNS2_20FrameTimingsRecorderERNS2_9LayerTreeEE3$_1NS_9allocatorIS8_EEFvvEEclEv + 26
	10  Flutter                             0x000000010a25c91e _ZNK3fml10SyncSwitch7ExecuteERKNS0_8HandlersE + 56
	11  Flutter                             0x000000010a58d1bf _ZN7flutter10Rasterizer13DrawToSurfaceERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 357
	12  Flutter                             0x000000010a58df71 _ZN7flutter10Rasterizer6DoDrawENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_20FrameTimingsRecorderENS1_14default_deleteIS3_EEEENS1_10shared_ptrINS_9LayerTreeEEE + 121
	13  Flutter                             0x000000010a58f775 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS2_8PipelineINS2_13LayerTreeItemEEEEENS_8functionIFbRNS2_9LayerTreeEEEEE3$_1NS_9allocatorISG_EEFvNS_10unique_ptrIS6_NS_14default_deleteIS6_EEEEEEclEOSM_ + 193
	14  Flutter                             0x000000010a58da1d _ZN7flutter8PipelineINS_13LayerTreeItemEE7ConsumeERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFvNS3_10unique_ptrIS1_NS3_14default_deleteIS1_EEEEEEE + 193
	15  Flutter                             0x000000010a58d378 _ZN7flutter10Rasterizer4DrawERKNSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_8PipelineINS_13LayerTreeItemEEEEENS1_8functionIFbRNS_9LayerTreeEEEE + 150
	16  Flutter                             0x000000010a58faa4 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS5_8PipelineINS5_13LayerTreeItemEEEEENS_8functionIFbRNS5_9LayerTreeEEEEE3$_0EENS_9allocatorISK_EEFvvEEclEv + 128
	17  Flutter                             0x000000010a259315 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 163
	18  Flutter                             0x000000010a25fd78 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	19  CoreFoundation                      0x00007ff8003b3353 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	20  CoreFoundation                      0x00007ff8003b2eb0 __CFRunLoopDoTimer + 799
	21  CoreFoundation                      0x00007ff8003b2637 __CFRunLoopDoTimers + 243
	22  CoreFoundation                      0x00007ff8003acec8 __CFRunLoopRun + 2183
	23  CoreFoundation                      0x00007ff8003ac264 CFRunLoopRunSpecific + 560
	24  GraphicsServices                    0x00007ff809b4024e GSEventRunModal + 139
	25  UIKitCore                           0x000000010da627bf -[UIApplication _run] + 994
	26  UIKitCore                           0x000000010da675de UIApplicationMain + 123
	27  Runner                              0x000000010514b5bf main + 63
	28  dyld                                0x00000001064d2384 start_sim + 10
	29  ???                                 0x000000011163441f 0x0 + 4586685471
)
libc++abi: terminating due to uncaught exception of type NSException
(lldb) 
```
> 
> Debug Console logs (VSCode):
> 
> ```console
Launching lib/main.dart on iPhone Xs Max in debug mode...
main.dart:1
Xcode build done.                                           12.5s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:56388/mWm95VyWBuk=/ws
Google Maps SDK for iOS version: 5.2.0.0
New version of Google Maps SDK for iOS available: 8.0.0.0
Lost connection to device.
Exited
```
> 
> </details>
> 
> 
> ### Flutter Doctor output
> 
> <details><summary>Doctor output</summary>
> 
> ```console
> fvm flutter doctor -v       [crash-fixes] 
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/marty/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/marty/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/marty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Arc.app/Contents/MacOS/Arc

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • iPhone 8 Plus (mobile) • 2F109AE8-CAE0-4948-9E4E-47B422CC576B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone Xs Max (mobile) • 2BBDAB13-5584-4DA1-8FDC-C40A742B7E93 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
> 
> </details>
> 
> > Note: The issue was also existing on Flutter 3.10.5, but I don't know if this is a regression or not.

I also [tested this on the master branch](https://github.com/flutter/flutter/issues/131472).
