### ISSUE TITLE
ExpansionPanelList can't expand. Throw an error on flutter version 3.13.0-7.0.pre.45

### ISSUE THREAD

**Issue by 396501293** [flutter/flutter#131038]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

ExpansionPanelList can't expand on flutter version 3.13.0-7.0.pre.45 while works fine on stable version 3.10.

### Expected results

ExpansionPanelList can expand.

### Actual results

```
I/flutter ( 3830): The following assertion was thrown:
I/flutter ( 3830): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
I/flutter ( 3830): 'elapsedInSeconds >= 0.0': is not true.
I/flutter ( 3830): 
I/flutter ( 3830): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3830): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3830): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3830):   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
I/flutter ( 3830): 
I/flutter ( 3830): When the exception was thrown, this was the stack:
I/flutter ( 3830): #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
I/flutter ( 3830): #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
I/flutter ( 3830): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1301:15)
I/flutter ( 3830): #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1153:11)
I/flutter ( 3830): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
I/flutter ( 3830): #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1151:17)
I/flutter ( 3830): #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1068:5)
I/flutter ( 3830): #12     _invoke1 (dart:ui/hooks.dart:188:10)
I/flutter ( 3830): #13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:388:5)
I/flutter ( 3830): #14     _beginFrame (dart:ui/hooks.dart:129:31)
I/flutter ( 3830): (elided 5 frames from class _AssertionError and dart:async)
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:cyner_app/components/app_bar_with_company_name/app_bar_with_company_name.dart';
import 'package:cyner_app/components/date_display/date_display.dart';
import 'package:cyner_app/components/scanner_page.dart/scanner_page.dart';
import 'package:cyner_app/models/storage.m.dart';
import 'package:cyner_app/services/storage_service.dart';
import 'package:cyner_app/utils/tool/tips_util.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:intl/intl.dart';

DateTime now = DateTime.now();
// 获取两天前的日期
DateTime twoDaysAgo = now.subtract(const Duration(days: 2));

class OutboundListPage extends StatefulWidget {
  const OutboundListPage({Key? key, this.params}) : super(key: key);
  final dynamic params;

  @override
  State<OutboundListPage> createState() => _OutboundListPageState();
}

class _OutboundListPageState extends State<OutboundListPage> {
  final TextEditingController _keywordController = TextEditingController();
  final TextEditingController _dateRangeController = TextEditingController();

  DateTimeRange? _selectedDate;

  List<OutboundRegistration> outboundRegistrationList = [];

  /// 展开状态
  Set<String> expandedSns = {};

  /// 子项过滤状态
  Set<OutboundListSegmentedButtonStatus> filterStatusList = {};

  @override
  void initState() {
    super.initState();

    setState(() {
      DateTimeRange(start: twoDaysAgo, end: now);
      getRegOutboundList();
    });
  }

  void _showDatePicker() async {
    final DateTimeRange? date = await showDateRangePicker(
      initialDateRange: _selectedDate,
      context: context,
      firstDate: DateTime(2020),
      lastDate: DateTime(2100),
    );

    if (date != null) {
      setState(() {
        _selectedDate = date;
        _dateRangeController.text = _selectedDate == null
            ? '请选择日期'
            : '${DateFormat('yyyy/MM/dd').format(_selectedDate!.start)}~${DateFormat('yyyy/MM/dd').format(_selectedDate!.end)}';
      });
    }
  }

  getRegOutboundList() {
    getRegOutboundListApi(
      DateFormat('yyyy-MM-dd').format(_selectedDate?.start ?? twoDaysAgo),
      DateFormat('yyyy-MM-dd').format(
        _selectedDate?.end ?? now,
      ),
      _keywordController.text,
    ).then((value) {
      if (value != null) {
        setState(() {
          outboundRegistrationList = value;
        });
      }
    });
  }

  Widget _buildProductItemCard({String? label, dynamic value}) {
    return Row(
      children: [
        SizedBox(
          width: 100.w, // 固定宽度
          child: Text(
            label ?? '',
            style: TextStyle(fontSize: 14, color: Colors.grey[600]),
          ),
        ),
        value is String?
            ? Text(
                value ?? '',
                style: const TextStyle(fontSize: 14),
              )
            : value,
      ],
    );
  }

  Widget? _statusWidget(status) {
    if (status == 0) {
      return const Text(
        '未出库',
        style: TextStyle(
          color: Colors.grey,
          // fontSize: 24.sp,
        ),
      );
    } else if (status == 1) {
      return const Text(
        '已出库',
        style: TextStyle(
          color: Colors.green,
          // fontSize: 24.sp,
        ),
      );
    } else if (status == 2) {
      return const Text(
        '已取消',
        style: TextStyle(
          color: Colors.orange,
          // fontSize: 24.sp,
        ),
      );
    }
    return null;
  }

  _getfilterdOutboundCount(OutboundRegistration item) {
    final target = filterStatusList
        .lookup(OutboundListSegmentedButtonStatus(key: item.outboundSn));
    final status = target == null ? 0 : target.value;

    return item.prodList.where((element) => element.status == status).length;
  }

  @override
  Widget build(BuildContext context) {
    final primaryColor = Theme.of(context).primaryColor;
    return Scaffold(
      appBar: AppBar(
        title: const AppBarWithCompanyName(title: '出库清单'),
      ),
      body: SafeArea(
        top: true,
        bottom: true,
        child: Column(
          children: [
            Container(
              // color: Colors.white,
              padding: const EdgeInsets.only(left: 16, bottom: 10),
              child: Row(
                children: [
                  Expanded(
                    child: TextField(
                      style: TextStyle(fontSize: 20.sp),
                      controller: _keywordController,
                      decoration: const InputDecoration(
                        labelText: '产品名称',
                        hintText: '请输入产品名称',
                        // prefixIcon: Icon(Icons.search),
                        border: OutlineInputBorder(),
                      ),
                    ),
                  ),
                  SizedBox(width: 10.w),
                  Expanded(
                    child: TextField(
                      style: TextStyle(fontSize: 20.sp),
                      onTap: _showDatePicker,
                      readOnly: true,
                      decoration: const InputDecoration(
                        labelText: '日期',
                        border: OutlineInputBorder(),
                      ),
                      controller: _dateRangeController,
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.search),
                    onPressed: () {
                      getRegOutboundList();
                    },
                  )
                ],
              ),
            ),
            SizedBox(
              height: 10.h,
            ),
            Expanded(
              child: ListView(
                children: [
                  ExpansionPanelList(
                    elevation: 0,
                    expansionCallback: (int index, bool isExpanded) {
                      print('expansionCallback$isExpanded$index');
                      setState(() {
                        if (!isExpanded) {
                          expandedSns
                              .add(outboundRegistrationList[index].outboundSn);
                        } else {
                          expandedSns.remove(
                              outboundRegistrationList[index].outboundSn);
                        }
                      });
                    },
                    children: outboundRegistrationList
                        .map<ExpansionPanel>((OutboundRegistration item) {
                      int notOutboundProdLength = item.prodList
                          .where((element) => element.status == 0)
                          .length;
                      int outboundProdLength = item.prodList
                          .where((element) => element.status == 1)
                          .length;
                      int cancelOutboundProdLength = item.prodList
                          .where((element) => element.status == 2)
                          .length;
                      int totalProdLength = item.prodList.length;

                      return ExpansionPanel(
                        headerBuilder: (BuildContext context, bool isExpanded) {
                          return ListTile(
                            leading: DateDisplayComponent(
                                dateString: item.registerDatetime),
                            title: Text(item.productName),
                            subtitle: Text(item.outboundSn),
                            trailing: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text(
                                  '出库数量',
                                  style: TextStyle(fontSize: 16.sp),
                                ),
                                RichText(
                                  text: TextSpan(
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 24.sp,
                                    ),
                                    children: <TextSpan>[
                                      TextSpan(
                                        text: outboundProdLength.toString(),
                                        style: TextStyle(
                                          color: outboundProdLength ==
                                                  totalProdLength
                                              ? primaryColor
                                              : Colors.grey,
                                        ),
                                      ),
                                      TextSpan(
                                        text: '/$totalProdLength',
                                        style: TextStyle(color: primaryColor),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          );
                        },
                        body: Column(
                          children: [
                            SizedBox(
                              height: 30,
                              // width: 100,
                              child: SegmentedButton(
                                showSelectedIcon: false,
                                style: OutlinedButton.styleFrom(
                                  side: BorderSide(color: primaryColor),
                                  // fixedSize: Size(10, 20),
                                ),
                                segments: [
                                  ButtonSegment(
                                    value: 0,
                                    label: Padding(
                                      padding:
                                          const EdgeInsets.only(bottom: 25),
                                      child: Text(
                                        '未出库($notOutboundProdLength)',
                                        style: const TextStyle(fontSize: 12),
                                      ),
                                    ),
                                  ),
                                  ButtonSegment(
                                    value: 1,
                                    label: Padding(
                                      padding:
                                          const EdgeInsets.only(bottom: 25),
                                      child: Text(
                                        '已出库($outboundProdLength)',
                                        style: const TextStyle(fontSize: 12),
                                      ),
                                    ),
                                  ),
                                  ButtonSegment(
                                    value: 2,
                                    label: Padding(
                                      padding:
                                          const EdgeInsets.only(bottom: 25),
                                      child: Text(
                                        '已取消($cancelOutboundProdLength)',
                                        style: const TextStyle(fontSize: 12),
                                      ),
                                    ),
                                  ),
                                ],
                                selected: {
                                  filterStatusList
                                          .lookup(
                                              OutboundListSegmentedButtonStatus(
                                                  key: item.outboundSn))
                                          ?.value ??
                                      0
                                },
                                onSelectionChanged: (newSelection) {
                                  setState(() {
                                    // By default there is only a single segment that can be
                                    // selected at one time, so its value is always the first
                                    // item in the selected set.

                                    final target = filterStatusList.lookup(
                                        OutboundListSegmentedButtonStatus(
                                            key: item.outboundSn));
                                    if (target == null) {
                                      filterStatusList.add(
                                          OutboundListSegmentedButtonStatus(
                                              key: item.outboundSn,
                                              value: newSelection.first));
                                    } else {
                                      target.value = newSelection.first;
                                    }
                                  });
                                },
                              ),
                            ),
                            _getfilterdOutboundCount(item) == 0
                                ? const SizedBox(
                                    height: 116,
                                    child: Center(
                                      child: Text(
                                        '暂无数据',
                                        style: TextStyle(color: Colors.grey),
                                      ),
                                    ),
                                  )
                                : ListView.builder(
                                    shrinkWrap: true,
                                    itemCount: _getfilterdOutboundCount(item),
                                    itemBuilder:
                                        (BuildContext context, int index) {
                                      final target = filterStatusList.lookup(
                                          OutboundListSegmentedButtonStatus(
                                              key: item.outboundSn));
                                      final status =
                                          target == null ? 0 : target.value;

                                      OutboundProdInfo productItem = item
                                          .prodList
                                          .where((element) =>
                                              element.status == status)
                                          .toList()[index];
                                      return Padding(
                                        padding: EdgeInsets.all(16.w),
                                        child: Row(
                                          children: [
                                            Expanded(
                                              child: Column(
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  _buildProductItemCard(
                                                    label: '批号:',
                                                    value: productItem.batchNo,
                                                  ),
                                                  _buildProductItemCard(
                                                    label: '产品名称:',
                                                    value:
                                                        productItem.productName,
                                                  ),
                                                  _buildProductItemCard(
                                                    label: '货架名称:',
                                                    value: productItem
                                                        .locationName,
                                                  ),
                                                  _buildProductItemCard(
                                                    label: '状态:',
                                                    value: _statusWidget(
                                                        productItem.status),
                                                  ),
                                                  _buildProductItemCard(
                                                    label: '数量:',
                                                    value: productItem.quantity
                                                        .toString(),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            SizedBox(
                                              width: 100,
                                              child: Wrap(
                                                direction: Axis.vertical,
                                                spacing: 10,
                                                children: [
                                                  if (productItem.status == 0)
                                                    SizedBox(
                                                      width: 90,
                                                      height: 30,
                                                      child: ElevatedButton(
                                                        onPressed: () async {
                                                          String? result =
                                                              await Navigator.of(
                                                                      context)
                                                                  .push(
                                                            MaterialPageRoute(
                                                              builder: (context) =>
                                                                  const ScannerPage(),
                                                            ),
                                                          );
                                                          if (result != null) {
                                                            setProdOutboundApi(
                                                                    productItem
                                                                        .regProdOutBoundId,
                                                                    result)
                                                                .then((res) {
                                                              if (res == true) {
                                                                Tips.success(
                                                                    '出库成功');
                                                                getRegOutboundList();
                                                              }
                                                            });
                                                          }
                                                        },
                                                        child:
                                                            const Text('扫码出库'),
                                                      ),
                                                    ),
                                                  if (productItem.status == 0)
                                                    SizedBox(
                                                      width: 90,
                                                      height: 30,
                                                      child: OutlinedButton(
                                                        onPressed: () {
                                                          cancelProdOutboundApi(
                                                                  productItem
                                                                      .regProdOutBoundId)
                                                              .then((value) {
                                                            if (value == true) {
                                                              Tips.success(
                                                                  '取消出库成功');
                                                              getRegOutboundList();
                                                            }
                                                          });
                                                        },
                                                        child:
                                                            const Text('取消出库'),
                                                      ),
                                                    ),
                                                ],
                                              ),
                                            )
                                          ],
                                        ),
                                      );
                                    },
                                  ),
                          ],
                        ),
                        isExpanded: expandedSns.contains(item.outboundSn),
                      );
                    }).toList(),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.13.0-7.0.pre.45, on macOS 13.0.1 22A400 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.0-7.0.pre.45 on channel master at /Users/chenji/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0ed17dd5a2 (15 hours ago), 2023-07-20 09:34:46 -0700
    • Engine revision 6d7842d25f
    • Dart version 3.1.0 (build 3.1.0-331.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/chenji/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • SM S9180 (mobile) • R5CW22P7ZNT • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.198

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": Operation timed out

! Doctor found issues in 1 category.
```

</details>

**Comment by 396501293** [comment]
![image](https://github.com/flutter/flutter/assets/16433331/9332c3c1-fcff-49f2-8fb7-34b7df3924a6)
This is the screenshot of my app which ExpansionPanelLIst works fine with flutter stable version

**Comment by TahaTesser** [comment]
Hi @396501293 
Can you please provide a minimal `ExpansionPanelList` code sample? Similar to the official [sample](https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html#material.ExpansionPanelList.1)

**Comment by 396501293** [comment]
@TahaTesser 
```dart
import 'package:flutter/material.dart';

class DateDisplayComponent extends StatelessWidget {
  final String dateString;

  const DateDisplayComponent({super.key, required this.dateString});

  @override
  Widget build(BuildContext context) {
    final DateTime dateTime = DateTime.parse(dateString);
    final int month = dateTime.month;
    final int day = dateTime.day;
    final int hour = dateTime.hour;

    return Container(
      width: 40,
      // height: 50,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8),
        color: Theme.of(context).colorScheme.primary,
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            '$month月',
            style: const TextStyle(
              fontSize: 8,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          Text(
            '$day日',
            style: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          Text(
            '$hour时',
            style: const TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );
  }
}

class OutboundListSegmentedButtonStatus {
  String key;
  int? value;

  OutboundListSegmentedButtonStatus({
    required this.key,
    this.value,
  });

  @override
  int get hashCode => key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutboundListSegmentedButtonStatus &&
          runtimeType == other.runtimeType &&
          key == other.key;
}

/// Flutter code sample for [showDateRangePicker].
class OutboundRegistration {
  String outboundSn;
  List<OutboundProdInfo> prodList;
  String productName;
  String registerUser;
  int quantity;
  String registerDatetime;
  String owner;

  OutboundRegistration({
    required this.outboundSn,
    required this.prodList,
    required this.productName,
    required this.registerUser,
    required this.quantity,
    required this.registerDatetime,
    required this.owner,
  });

  factory OutboundRegistration.fromJson(Map<String, dynamic> json) {
    return OutboundRegistration(
      outboundSn: json['outboundSn'] ?? '',
      prodList: (json['prodList'] as List<dynamic>?)
              ?.map((item) => OutboundProdInfo.fromJson(item))
              .toList() ??
          [],
      productName: json['productName'] ?? '',
      registerUser: json['registerUser'] ?? '',
      quantity: json['quantity'] ?? 0,
      registerDatetime: json['registerDatetime'] ?? '',
      owner: json['owner'] ?? '',
    );
  }
}

class OutboundProdInfo {
  String productName;
  String locationName;
  int quantity;
  int regProdOutBoundId;
  int status;
  String batchNo;

  OutboundProdInfo({
    required this.productName,
    required this.locationName,
    required this.quantity,
    required this.regProdOutBoundId,
    required this.status,
    required this.batchNo,
  });

  factory OutboundProdInfo.fromJson(Map<String, dynamic> json) {
    return OutboundProdInfo(
      productName: json['productName'] ?? '',
      locationName: json['locationName'] ?? '',
      quantity: json['quantity'] ?? 0,
      regProdOutBoundId: json['regProdOutBoundId'] ?? 0,
      status: json['status'] ?? 0,
      batchNo: json['batchNo'] ?? '',
    );
  }
}

final jsonData = [
  {
    "outboundSn": "20230720021628487728DC",
    "prodList": [
      {
        "productName": "亮膜",
        "locationName": null,
        "regProdOutBoundId": 2,
        "quantity": 110,
        "status": 1,
        "batchNo": "20230720014652927083QF_1"
      },
      {
        "productName": "亮膜",
        "locationName": "仓库3-1层-1排",
        "regProdOutBoundId": 1,
        "quantity": 110,
        "status": 2,
        "batchNo": "20230720014547132880YK_1"
      }
    ],
    "registerDatetime": "2023-07-19 18:16:28",
    "productName": "亮膜",
    "registerUser": "蒋彬彬",
    "owner": "义乌物与喷印-SP0579100",
    "quantity": 220
  }
];

void main() => runApp(const ExpansionListSample());

class ExpansionListSample extends StatelessWidget {
  const ExpansionListSample({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      restorationScopeId: 'app',
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

/// RestorationProperty objects can be used because of RestorationMixin.
class _HomeState extends State<Home> {
  List<OutboundRegistration> outboundRegistrationList = [];

  /// 展开状态
  Set<String> expandedSns = {};

  /// 子项过滤状态
  Set<OutboundListSegmentedButtonStatus> filterStatusList = {};

  @override
  initState() {
    super.initState();

    setState(() {
      outboundRegistrationList = jsonData
          .map<OutboundRegistration>((outboundRegistration) =>
              OutboundRegistration.fromJson(outboundRegistration))
          .toList();
    });
  }

  _getfilterdOutboundCount(OutboundRegistration item) {
    final target = filterStatusList
        .lookup(OutboundListSegmentedButtonStatus(key: item.outboundSn));
    final status = target == null ? 0 : target.value;

    return item.prodList.where((element) => element.status == status).length;
  }

  Widget _buildProductItemCard({String? label, dynamic value}) {
    return Row(
      children: [
        SizedBox(
          width: 100, // 固定宽度
          child: Text(
            label ?? '',
            style: TextStyle(fontSize: 14, color: Colors.grey[600]),
          ),
        ),
        value is String?
            ? Text(
                value ?? '',
                style: const TextStyle(fontSize: 14),
              )
            : value,
      ],
    );
  }

  Widget? _statusWidget(status) {
    if (status == 0) {
      return const Text(
        '未出库',
        style: TextStyle(
          color: Colors.grey,
          // fontSize: 24.sp,
        ),
      );
    } else if (status == 1) {
      return const Text(
        '已出库',
        style: TextStyle(
          color: Colors.green,
          // fontSize: 24.sp,
        ),
      );
    } else if (status == 2) {
      return const Text(
        '已取消',
        style: TextStyle(
          color: Colors.orange,
          // fontSize: 24.sp,
        ),
      );
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final primaryColor = Theme.of(context).primaryColor;
    return MaterialApp(
      theme: Theme.of(context).copyWith(useMaterial3: true),
      home: Scaffold(
        appBar: AppBar(title: const Text('ExpansionPanelList Sample')),
        body: ListView(
          children: [
            ExpansionPanelList(
              elevation: 0,
              expansionCallback: (int index, bool isExpanded) {
                setState(() {
                  if (!isExpanded) {
                    expandedSns.add(outboundRegistrationList[index].outboundSn);
                  } else {
                    expandedSns
                        .remove(outboundRegistrationList[index].outboundSn);
                  }
                });
              },
              children: outboundRegistrationList
                  .map<ExpansionPanel>((OutboundRegistration item) {
                int notOutboundProdLength = item.prodList
                    .where((element) => element.status == 0)
                    .length;
                int outboundProdLength = item.prodList
                    .where((element) => element.status == 1)
                    .length;
                int cancelOutboundProdLength = item.prodList
                    .where((element) => element.status == 2)
                    .length;
                int totalProdLength = item.prodList.length;

                return ExpansionPanel(
                  headerBuilder: (BuildContext context, bool isExpanded) {
                    return ListTile(
                      leading: DateDisplayComponent(
                          dateString: item.registerDatetime),
                      title: Text(item.productName),
                      subtitle: Text(item.outboundSn),
                      trailing: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text(
                            '出库数量',
                            style: TextStyle(fontSize: 16),
                          ),
                          RichText(
                            text: TextSpan(
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 24,
                              ),
                              children: <TextSpan>[
                                TextSpan(
                                  text: outboundProdLength.toString(),
                                  style: TextStyle(
                                    color: outboundProdLength == totalProdLength
                                        ? primaryColor
                                        : Colors.grey,
                                  ),
                                ),
                                TextSpan(
                                  text: '/$totalProdLength',
                                  style: TextStyle(color: primaryColor),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                  body: Column(
                    children: [
                      SizedBox(
                        height: 30,
                        // width: 100,
                        child: SegmentedButton(
                          showSelectedIcon: false,
                          style: OutlinedButton.styleFrom(
                            side: BorderSide(color: primaryColor),
                            // fixedSize: Size(10, 20),
                          ),
                          segments: [
                            ButtonSegment(
                              value: 0,
                              label: Padding(
                                padding: const EdgeInsets.only(bottom: 25),
                                child: Text(
                                  '未出库($notOutboundProdLength)',
                                  style: const TextStyle(fontSize: 12),
                                ),
                              ),
                            ),
                            ButtonSegment(
                              value: 1,
                              label: Padding(
                                padding: const EdgeInsets.only(bottom: 25),
                                child: Text(
                                  '已出库($outboundProdLength)',
                                  style: const TextStyle(fontSize: 12),
                                ),
                              ),
                            ),
                            ButtonSegment(
                              value: 2,
                              label: Padding(
                                padding: const EdgeInsets.only(bottom: 25),
                                child: Text(
                                  '已取消($cancelOutboundProdLength)',
                                  style: const TextStyle(fontSize: 12),
                                ),
                              ),
                            ),
                          ],
                          selected: {
                            filterStatusList
                                    .lookup(OutboundListSegmentedButtonStatus(
                                        key: item.outboundSn))
                                    ?.value ??
                                0
                          },
                          onSelectionChanged: (newSelection) {
                            setState(() {
                              // By default there is only a single segment that can be
                              // selected at one time, so its value is always the first
                              // item in the selected set.

                              final target = filterStatusList.lookup(
                                  OutboundListSegmentedButtonStatus(
                                      key: item.outboundSn));
                              if (target == null) {
                                filterStatusList.add(
                                    OutboundListSegmentedButtonStatus(
                                        key: item.outboundSn,
                                        value: newSelection.first));
                              } else {
                                target.value = newSelection.first;
                              }
                            });
                          },
                        ),
                      ),
                      _getfilterdOutboundCount(item) == 0
                          ? const SizedBox(
                              height: 116,
                              child: Center(
                                child: Text(
                                  '暂无数据',
                                  style: TextStyle(color: Colors.grey),
                                ),
                              ),
                            )
                          : ListView.builder(
                              shrinkWrap: true,
                              itemCount: _getfilterdOutboundCount(item),
                              itemBuilder: (BuildContext context, int index) {
                                final target = filterStatusList.lookup(
                                    OutboundListSegmentedButtonStatus(
                                        key: item.outboundSn));
                                final status =
                                    target == null ? 0 : target.value;

                                OutboundProdInfo productItem = item.prodList
                                    .where(
                                        (element) => element.status == status)
                                    .toList()[index];
                                return Padding(
                                  padding: EdgeInsets.all(16),
                                  child: Row(
                                    children: [
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            _buildProductItemCard(
                                              label: '批号:',
                                              value: productItem.batchNo,
                                            ),
                                            _buildProductItemCard(
                                              label: '产品名称:',
                                              value: productItem.productName,
                                            ),
                                            _buildProductItemCard(
                                              label: '货架名称:',
                                              value: productItem.locationName,
                                            ),
                                            _buildProductItemCard(
                                              label: '状态:',
                                              value: _statusWidget(
                                                  productItem.status),
                                            ),
                                            _buildProductItemCard(
                                              label: '数量:',
                                              value: productItem.quantity
                                                  .toString(),
                                            ),
                                          ],
                                        ),
                                      ),
                                      SizedBox(
                                        width: 100,
                                        child: Wrap(
                                          direction: Axis.vertical,
                                          spacing: 10,
                                          children: [
                                            if (productItem.status == 0)
                                              SizedBox(
                                                width: 90,
                                                height: 30,
                                                child: ElevatedButton(
                                                  onPressed: () async {},
                                                  child: const Text('扫码出库'),
                                                ),
                                              ),
                                            if (productItem.status == 0)
                                              SizedBox(
                                                width: 90,
                                                height: 30,
                                                child: OutlinedButton(
                                                  onPressed: () {},
                                                  child: const Text('取消出库'),
                                                ),
                                              ),
                                          ],
                                        ),
                                      )
                                    ],
                                  ),
                                );
                              },
                            ),
                    ],
                  ),
                  isExpanded: expandedSns.contains(item.outboundSn),
                );
              }).toList(),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment]
Hi @396501293 
The example is long and contains a lot of unrelated code to `ExpansionPanelList` and it also throws an error when trying to run. 

Please remove the unrelated code and use hard-coded or dummy text for the `ExpansionPanelList` content.

or

Try running this minimal code sample. If you can't reproduce the issue, please modify below code sample to make it reproduce the issue. 
### Code sample

<details> 
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [ExpansionPanelList].

void main() => runApp(const ExpansionPanelListExampleApp());

class ExpansionPanelListExampleApp extends StatelessWidget {
  const ExpansionPanelListExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ExpansionPanelList Sample')),
        body: const ExpansionPanelListExample(),
      ),
    );
  }
}

// stores ExpansionPanel state information
class Item {
  Item({
    required this.expandedValue,
    required this.headerValue,
    this.isExpanded = false,
  });

  String expandedValue;
  String headerValue;
  bool isExpanded;
}

List<Item> generateItems(int numberOfItems) {
  return List<Item>.generate(numberOfItems, (int index) {
    return Item(
      headerValue: 'Panel $index',
      expandedValue: 'This is item number $index',
    );
  });
}

class ExpansionPanelListExample extends StatefulWidget {
  const ExpansionPanelListExample({super.key});

  @override
  State<ExpansionPanelListExample> createState() =>
      _ExpansionPanelListExampleState();
}

class _ExpansionPanelListExampleState extends State<ExpansionPanelListExample> {
  final List<Item> _data = generateItems(8);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        child: _buildPanel(),
      ),
    );
  }

  Widget _buildPanel() {
    return ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = !isExpanded;
        });
      },
      children: _data.map<ExpansionPanel>((Item item) {
        return ExpansionPanel(
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
              subtitle:
                  const Text('To delete this panel, tap the trash can icon'),
              trailing: const Icon(Icons.delete),
              onTap: () {
                setState(() {
                  _data.removeWhere((Item currentItem) => item == currentItem);
                });
              }),
          isExpanded: item.isExpanded,
        );
      }).toList(),
    );
  }
}

``` 
	
</details>

**Comment by 396501293** [comment]
Hi @TahaTesser.
I found the reason. The source code of expansionCallback changed. The `isExpanded` is opposite compare with previous version of flutter.
<img width="1352" alt="image" src="https://github.com/flutter/flutter/assets/16433331/5e2a1dc5-e02d-48c6-849e-4edd8630f06c">

**Comment by 396501293** [comment]
Is this just a bug or the API changes @TahaTesser

**Comment by TahaTesser** [comment]
@396501293 
That's a good find, However, we will still have a minimal producible code to address the issue. 
Please see https://github.com/flutter/flutter/issues/131038#issuecomment-1647362397

**Comment by 396501293** [comment]
hi @TahaTesser 
ExpansionPanelList can expand after I reverse the `isExpanded` state.  But it's not 100% to reproduce the issue. The sample code you provided is also producible . It can have probability reproduce the issue by just tap the expansion panel.

<img width="1740" alt="image" src="https://github.com/flutter/flutter/assets/16433331/b5235dd4-9ad5-4d06-9040-43d4910b80c1">

**Comment by TahaTesser** [comment]
@396501293 
I have tried to reproduce the several times, following the steps. I can't get any error. 
Can you please screen-record the steps you took and the error thrown?  Appreciate it

**Comment by 396501293** [comment]
hi @TahaTesser 
I can't reproduce in the simulator. So I record a video.
[video](https://youtu.be/s7Tc5W9Q1EI)

**Comment by dam-ease** [comment]
Hi @396501293. Thanks for your response. I am unable to reproduce the error logged on the latest master channel following the reproduction steps provided both on physical devices and emulator/simulator. This might be device-specific.
Thank you.

**Comment by mashegoindustries** [comment]
@HansMuller I am experimenting the same issue.

I have noticed that the official sample documentation, the expansion panel stopped working there aswel


[official sample](https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html#material.ExpansionPanelList.1)

**Comment by MiguelSOliveira** [comment]
Also having this issue. It was working before update to 3.13.

**Comment by TahaTesser** [comment]
The example is fixed in https://github.com/flutter/flutter/pull/132837

**Comment by TahaTesser** [comment]
@mashegoindustries @MiguelSOliveira 
This isn't a bug. 

https://github.com/flutter/flutter/pull/128082 fixed the expansionCallback to return the correct expanded state and also updated the ExpansionPanel sample in the Flutter gallery but not the API example.  https://github.com/flutter/flutter/pull/132837 fixes example


This issue isn't related to the example issue.

**Comment by iUngerTime** [comment]
This is still broken. Use the official site API documentation and it doesn't work. [API Docs for Expansion Panel](https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html)

**Comment by TahaTesser** [comment]
> This is still broken. Use the official site API documentation and it doesn't work. [API Docs for Expansion Panel](https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html)

The example PR merged just this week, it's only the [master API docs. ](https://master-api.flutter.dev/flutter/material/ExpansionPanelList-class.html)

**Comment by TahaTesser** [comment]
You can use the example on the stable channel too., Just edit the 

Make sure it assigns  `isExpanded`, (not `!isExpanded`)
```dart
          _data[index].isExpanded = !isExpanded;
```

**Comment by mashegoindustries** [comment]
@TahaTesser Based on your suggestion, I just reversed the isExpanded then everything works again.

My question is, 
What is the correct way of using this?

When a new flutter version comes out, with all the fixes 
Will I need to go back and revert all the isExpanded changes that I have just made?

I only use stable channel.

**Comment by PrimeTimeTran** [comment]
@TahaTesser could you please suggest and a reason/solution/action-item why the expansion panel list would work on local development but not release production?

In this example I copy pasted directly from my project it works perfect in local/development but not release/production/Netlify.

<details>
  <summary>Minimum Example</summary>

  ### Heading
```dart
import 'package:flutter/material.dart';

List<Item> generateItems(int numberOfItems) {
  return List<Item>.generate(numberOfItems, (int index) {
    return Item(
      headerValue: 'Panel $index',
      expandedValue: 'This is item number $index',
    );
  });
}

class ExpansionPanelListExample extends StatefulWidget {
  const ExpansionPanelListExample({super.key});

  @override
  State<ExpansionPanelListExample> createState() =>
      _ExpansionPanelListExampleState();
}

class Item {
  String expandedValue;

  String headerValue;
  bool isExpanded;
  Item({
    required this.expandedValue,
    required this.headerValue,
    this.isExpanded = false,
  });
}

class TestScreen extends StatefulWidget {
  const TestScreen({super.key});

  @override
  State<TestScreen> createState() => _TestScreenState();
}

class _ExpansionPanelListExampleState extends State<ExpansionPanelListExample> {
  final List<Item> _data = generateItems(8);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        child: _buildPanel(),
      ),
    );
  }

  Widget _buildPanel() {
    return ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = !isExpanded;
        });
      },
      children: _data.map<ExpansionPanel>((Item item) {
        return ExpansionPanel(
          canTapOnHeader: true,
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
              subtitle:
                  const Text('To delete this panel, tap the trash can icon'),
              trailing: const Icon(Icons.delete),
              onTap: () {
                setState(() {
                  _data.removeWhere((Item currentItem) => item == currentItem);
                });
              }),
          isExpanded: item.isExpanded,
        );
      }).toList(),
    );
  }
}

class _TestScreenState extends State<TestScreen> {
  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(horizontal: 50.0),
      child: Center(child: ExpansionPanelListExample()),
    );
  }
}
```
</details>

Not sure if it's a build config but he's my build command.
if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --web-renderer html --no-tree-shake-icons --dart-define=FLUTTER_WEB_ENTRY=lib/main_production.dart && sed -i 's#<base href="/">#<base href="https://app.1long.vn">#g' build/web/index.html

Thanks in advance~!

**Comment by M97Chahboun** [comment]
Me too I have same issue, I downgrade flutter version waiting fix this bug

**Comment by AndryHTC** [comment]
I understand the current implementation, but I'm having a hard time wrapping my head around it. You can tell me that it's the correct way of assigning the state, but it doesn't seem intuitive to me. Why would setting the attribute to the same value trigger the action of the opposite value? This approach doesn't make sense in my mind.

This non-explained and non-documented change has caused a big problem for developers like us who rely on the consistency and clarity of the Flutter documentation and API updates.

**Comment by tksoh** [comment]
> Hi @396501293 Can you please provide a minimal `ExpansionPanelList` code sample? Similar to the official [sample](https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html#material.ExpansionPanelList.1)

I tried using this example with Flutter 3.13.4, and the panels wouldn't expand. Not errors though.

No issue with Flutter 3.10.5. Verified on Windows 11 & Android 11.

**Comment by blueeyestw** [comment]
> The example PR merged just this week, it's only on the [master API docs. ](https://master-api.flutter.dev/flutter/material/ExpansionPanelList-class.html) for now.

Anyone know when the fix will be available on stable channel?

**Comment by ewilliams-zoot** [comment]
Also awaiting an ETA on this, as we found the same issue in our app on 3.13.9.

This should have been documented as a breaking change, if the functionality of setting the expanded state in the callback changed.

**Comment by ewilliams-zoot** [comment]
> @mashegoindustries @MiguelSOliveira This isn't a bug.
> 
> #128082 fixed the expansionCallback to return the correct expanded state and also updated the ExpansionPanel sample in the Flutter gallery but not the API example. #132837 fixes example
> 
> This current issue isn't related to the example issue.

So #128082 "fixed" the callback, which judging by the code simply flipped the flag. This broke the way developers were using it, so why was this not reported as a breaking change?

The fact that you had to _change the example_ should have clued you in to the fact that developers would have to do the same @TahaTesser . I don't think anyone here is saying it's a bug, but we are definitely saying that the behavior changed.

**Comment by TahaTesser** [comment]
@ewilliams-zoot 
The updated example should be in the stable documentation in the next stable release. Developers can reference it to update their codebase. 

Just to remind everyone, this particular issue being commented on is unrelated since it is about `elapsedInSeconds`. This is device-specific bug that the team couldn't reproduce  https://github.com/flutter/flutter/issues/131038#issuecomment-1651733056

@396501293 

> I/flutter ( 3830): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
> I/flutter ( 3830): 'elapsedInSeconds >= 0.0': is not true.

Are you still running into this issue on your device on the latest beta or master channels?

**Comment by ewilliams-zoot** [comment]
@TahaTesser Gotcha, we can limit this conversation to the `elapsedInSeconds` issue then - but is there anything being done about developers having to change their code? That is the definition of a breaking change, and it was never reported as such. Is there some place we can go to report that?
