### ISSUE TITLE
Many ipad user crash because of SEGV_ACCERR 

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#131161]
Approximately 16 in 10,000 users have these crash, The stack information is as follows because it's an online crash, I don't know how to reproduce it
There are two crashes 
1. 
<img width="594" alt="image" src="https://github.com/flutter/flutter/assets/9412601/3b279a30-3d56-4feb-8c2c-2cde630282d9">

![image](https://github.com/flutter/flutter/assets/9412601/62f8aa3f-5ce0-43cc-aff1-fd3e4cc3ff48)
</br></br>

2. 
<img width="839" alt="image" src="https://github.com/flutter/flutter/assets/9412601/a48f33f4-3068-4781-965d-ee877384d816">

![image](https://github.com/flutter/flutter/assets/9412601/6bfe8d41-74e9-4793-8266-7aedf6fbc3a3)

Device Info of these crash 
<img width="1454" alt="image" src="https://github.com/flutter/flutter/assets/9412601/134e53a9-4760-4fda-86f7-f115e3ae36a2">

The most device is ipad and iphone is very rare
Flutter Info:
<img width="838" alt="image" src="https://github.com/flutter/flutter/assets/9412601/87152b4d-87f4-4219-a2d9-321081592a78">

**Comment by darshankawar** [comment]
@cj3479 
Can you provide the crash log in properly formatted text instead of in screenshots ?

**Comment by cj3479** [comment]
> @cj3479 Can you provide the crash log in properly formatted text instead of in screenshots ?

Please view the log
[crash_log_2.txt](https://github.com/flutter/flutter/files/12146677/crash_log_2.txt)
[crash_log_1.txt](https://github.com/flutter/flutter/files/12146678/crash_log_1.txt)

**Comment by darshankawar** [comment]
@cj3479 
Based on the logs, it seems to be similar / related to https://github.com/flutter/flutter/issues/122957 which was fixed.
Since you are on 3.7.10, the likely fix was also identified on same version and should be available on later versions of 3.7.x, so I suggest you to upgrade to latest stable and run your scenario again to see if you still get the same crash or not.

**Comment by cj3479** [comment]
> @cj3479 Based on the logs, it seems to be similar / related to #122957 which was fixed. Since you are on 3.7.10, the likely fix was also identified on same version and should be available on later versions of 3.7.x, so I suggest you to upgrade to latest stable and run your scenario again to see if you still get the same crash or not.

I compare the fix https://dart.googlesource.com/sdk/+/e3e355e16a8b67ba6a1d7a83f837e8e69cf71534. The  3.7.10 has contain the commit. So The crash still exist

**Comment by cj3479** [comment]
@darshankawar is there more solution？

**Comment by darshankawar** [comment]
```

1 Flutter 0x0000000110cb6640 tonic::DartWeakPersistentValue::Get() (../../third_party/libcxx/src/include/atomic_support.h:74)
2 Flutter 0x0000000110cb6e68 tonic::DartWrappable::ClearDartWrapper() (../../flutter/third_party/tonic/dart_wrappable.cc:69)
3 Flutter 0x0000000110cb6e68 tonic::DartWrappable::ClearDartWrapper() (../../flutter/third_party/tonic/dart_wrappable.cc:69)
4 App 0x000000010f90a158 kDartVmSnapshotInstructions + 4440
5 App 0x000000010f95f028 kDartIsolateSnapshotInstructions + 329896
6 App 0x000000010f9e53d8 kDartIsolateSnapshotInstructions + 879704
7 App 0x000000010f9ef560 kDartIsolateSnapshotInstructions + 921056
8 App 0x000000011016f960 kDartIsolateSnapshotInstructions + 8786400
9 App 0x000000010f9c6fe4 kDartIsolateSnapshotInstructions + 755812
10 App 0x000000010f9cc404 kDartIsolateSnapshotInstructions + 777348
11 App 0x000000010f9f73cc kDartIsolateSnapshotInstructions + 953420
12 App 0x000000010f9df670 kDartIsolateSnapshotInstructions + 855792
13 App 0x000000010fcf812c kDartIsolateSnapshotInstructions + 4102572
14 App 0x000000010fcf801c kDartIsolateSnapshotInstructions + 4102300
15 App 0x000000010fcfbd90 kDartIsolateSnapshotInstructions + 4118032
16 App 0x000000010fcfbd58 kDartIsolateSnapshotInstructions + 4117976
17 App 0x000000010f9c64b8 kDartIsolateSnapshotInstructions + 752952
18 App 0x000000010f9c63fc kDartIsolateSnapshotInstructions + 752764
19 App 0x000000010f9c603c kDartIsolateSnapshotInstructions + 751804
20 App 0x000000010f9c5f04 kDartIsolateSnapshotInstructions + 751492
21 App 0x000000010f91dffc kDartIsolateSnapshotInstructions + 63612
22 App 0x000000010f91e0f8 kDartIsolateSnapshotInstructions + 63864
23 App 0x00000001102d1a20 kDartIsolateSnapshotInstructions + 10236576
24 App 0x00000001102d2a84 kDartIsolateSnapshotInstructions + 10240772
25 App 0x000000010f964d60 kDartIsolateSnapshotInstructions + 353760
26 App 0x000000010f972780 kDartIsolateSnapshotInstructions + 409600
27 App 0x000000010fd05178 kDartIsolateSnapshotInstructions + 4155896
28 App 0x000000010fd051b0 kDartIsolateSnapshotInstructions + 4155952
29 App 0x000000010f90bebc kDartVmSnapshotInstructions + 11964
30 Flutter 0x0000000110e9e14c dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) 
(../../third_party/dart/runtime/vm/dart_entry.cc:0)

31 Flutter 0x0000000110f9c1e4 Dart_InvokeClosure (../../third_party/dart/runtime/vm/dart_api_impl.cc:4778)

32 Flutter 0x0000000110ca32fc flutter::Shell::OnAnimatorBeginFrame(fml::TimePoint, unsigned long long) 
(../../flutter/third_party/tonic/logging/dart_invoke.cc:30)

33 Flutter 0x0000000110c8a3e8 std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::Animator::AwaitVSync()::$_3, 
std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::Animator::AwaitVSync()::$_3>, 
void (std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::FrameTimingsRecorder, 
std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::FrameTimingsRecorder> >)>::operator()(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::FrameTimingsRecorder, 
std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::FrameTimingsRecorder> >&&) (../../flutter/shell/common/animator.cc:106)

34 Flutter 0x0000000110cb3114 std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, boolean)::$_0, 
std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, boolean)::$_0>, void ()>::operator()() 
(../../third_party/libcxx/include/__memory/unique_ptr.h:302)

35 Flutter 0x0000000110b9fcf0 fml::MessageLoopImpl::FlushTasks(fml::FlushType) (../../flutter/fml/message_loop_impl.cc:128)
36 Flutter 0x0000000110ba2e94 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (../../flutter/fml/platform/darwin/message_loop_darwin.mm:86)

CoreFoundation
0x00000001c1d1633c
0x00000001c1c48000 + 844604
38
CoreFoundation
0x00000001c1cd29b8
0x00000001c1c48000 + 567736
39
CoreFoundation
0x00000001c1c76558
0x00000001c1c48000 + 189784
40
CoreFoundation
0x00000001c1cc3fb0
0x00000001c1c48000 + 507824
41
CoreFoundation
0x00000001c1cc8ec0
CFRunLoopRunSpecific + 612
42
Flutter
0x0000000110ba2f80
fml::MessageLoopDarwin::Run() (../../flutter/fml/platform/darwin/message_loop_darwin.mm:52)
43
Flutter
0x0000000110ba2a70
__thread_proxy<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct> >, (lambda at ../../flutter/fml/thread.cc:79:7)> > (../../flutter/fml/message_loop_impl.cc:0)
44
libsystem_pthread.dylib
0x000000020f3666cc
```



```
1 Flutter 0x0000000111154fa0 SkData::PrivateNewWithCopy(void const*, unsigned long) (../../third_party/libcxx/include/atomic:910)
2 Flutter 0x0000000111154f98 SkData::PrivateNewWithCopy(void const*, unsigned long) (../../third_party/libcxx/src/new.cpp:67)
3 Flutter 0x00000001111c33b4 MakeRasterCopyPriv (../../third_party/skia/src/core/SkData.cpp:111)
4 Flutter 0x000000011131f78c SkImage::MakeCrossContextFromPixmap(GrDirectContext*, SkPixmap const&, bool, bool) (../../third_party/skia/src/image/SkImage_Raster.cpp:314)
5 Flutter 0x0000000111574980 std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::UploadRasterImage(sk_sp<SkImage>, fml::WeakPtr<flutter::IOManager> const&, 
fml::tracing::TraceFlow const&)::$_3, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::UploadRasterImage(sk_sp<SkImage>, fml::WeakPtr<flutter::IOManager> const&, 
fml::tracing::TraceFlow const&)::$_3>, void ()>::operator()() (../../flutter/lib/ui/painting/image_decoder_skia.cc:204)

6 Flutter 0x00000001113a1534 fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const (../../flutter/fml/synchronization/shared_mutex.h:29)
7 Flutter 0x00000001115743d4 std::_LIBCPP_ABI_NAMESPACE::__function::__func<fml::internal::CopyableLambda<flutter::ImageDecoderSkia::Decode(fml::RefPtr<flutter::ImageDescriptor>, 
unsigned int, unsigned int, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DlImage>)> const&)::$_1::operator()()::'lambda'()>, 
std::_LIBCPP_ABI_NAMESPACE::allocator<fml::internal::CopyableLambda<flutter::ImageDecoderSkia::Decode(fml::RefPtr<flutter::ImageDescriptor>, 
unsigned int, unsigned int, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DlImage>)> const&)::$_1::operator()()::'lambda'()>>, void ()>::operator()() 
(../../third_party/libcxx/include/__functional/function.h:470)

8 Flutter 0x000000011139fcf0 fml::MessageLoopImpl::FlushTasks(fml::FlushType) (../../flutter/fml/message_loop_impl.cc:128)
9 Flutter 0x00000001113a2e94 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (../../flutter/fml/platform/darwin/message_loop_darwin.mm:86)
10 CoreFoundation 0x00000001d6f76624 0x00000001d6eab000 + 833060
11 CoreFoundation 0x00000001d6f33f4c 0x00000001d6eab000 + 560972
12 CoreFoundation 0x00000001d6ed971c 0x00000001d6eab000 + 190236
13 CoreFoundation 0x00000001d6f254d4 0x00000001d6eab000 + 500948
14 CoreFoundation 0x00000001d6f2a3ec CFRunLoopRunSpecific + 612
15 Flutter 0x00000001113a2f80 fml::MessageLoopDarwin::Run() (../../flutter/fml/platform/darwin/message_loop_darwin.mm:52)
16 Flutter 0x00000001113a2a70 __thread_proxy<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, 
std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct> >, (lambda at ../../flutter/fml/thread.cc:79:7)> > (../../flutter/fml/message_loop_impl.cc:0)

17 libsystem_pthread.dylib 0x00000002361b76b8 _pthread_start + 148

```

**Comment by darshankawar** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/131161#issuecomment-1651007513 flutter#v3.7.10 force ios release arm64

**Comment by darshankawar** [comment]
It most likely is similar to https://github.com/flutter/flutter/issues/115253, so please follow-up in that issue for further updates.
Closing this as a duplicate.
