### ISSUE TITLE
no static method initializeMessages in intl package

### ISSUE THREAD

**Issue by Fandekasp** [flutter/flutter#13121]
## Steps to Reproduce

Added localization to my project following  [the example](https://github.com/flutter/website/tree/master/_includes/code/internationalization/intl)  (linked from [the tutorial](https://flutter.io/tutorials/internationalization/))

Related PR: https://github.com/flutter/flutter/pull/11497
Apparently the initializeMessages() function is provided by the intl package, but running flutter will raise a `no static method declared` error.

dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: 0.1.1
  google_sign_in: 0.3.1
  firebase_analytics: 0.0.4
  firebase_auth: 0.2.0
  firebase_database: 0.0.12
  firebase_storage: 0.0.5
  intl: 0.15.1
  intl_translation: 0.15.0
```
Note that I  installed intl 0.15.1 instead of the [latest version 0.15.2](https://pub.dartlang.org/packages/intl#pub-pkg-tab-changelog) because `flutter packages get` would otherwise fail due to locked dependency from flutter_localizations. 
```
SLVR: | | | | | | | inconsistent constraints on intl:                                                                   
    | | | | | | | |   flutter_localizations 0.0.1-dev from sdk -> intl 0.15.1 from hosted (intl)  
```
It's also [the version used in the example](https://github.com/flutter/website/blob/master/_includes/code/internationalization/intl/main.dart#L19).

## Logs

```
$ flutter run 
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (24.8MB).
Installing build/app/outputs/apk/app.apk...
D/gralloc_ranchu( 3685): Emulator without host-side GPU emulation detected.
Loading gralloc.default.so from /vendor/lib/hw/gralloc.default.so...
I/flutter ( 3685): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86...
I/flutter ( 3685): The following NoSuchMethodError was thrown building
MediaQuery(MediaQueryData(size: Size(360.0,
I/flutter ( 3685): 592.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, padding:
EdgeInsets(0.0, 24.0, 0.0, 0.0))):
I/flutter ( 3685): No static method 'initializeMessages' declared in class
'AppLocalizations'.
I/flutter ( 3685): Receiver: AppLocalizations
I/flutter ( 3685): Tried calling: initializeMessages("en_US")
I/flutter ( 3685):
I/flutter ( 3685): When the exception was thrown, this was the stack:
I/flutter ( 3685): #0      NoSuchMethodError._throwNew
(dart:core-patch/dart:core/errors_patch.dart:192)
I/flutter ( 3685): #1      AppLocalizations.load
(package:grablunch/localization.dart:12)
I/flutter ( 3685): #2      AppLocalizationsDelegate.load
(package:grablunch/localization.dart:38)
I/flutter ( 3685): #3      _loadAll
(package:flutter/src/widgets/localizations.dart:56)
I/flutter ( 3685): #4      _LocalizationsState.load
(package:flutter/src/widgets/localizations.dart:492)
I/flutter ( 3685): #5      _LocalizationsState.initState
(package:flutter/src/widgets/localizations.dart:457)
I/flutter ( 3685): #6      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:3661)
I/flutter ( 3685): #7      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #8      Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #9      Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #10     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #11     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #12     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #13     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #14     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #15     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #16     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #17     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #18     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #19     StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 3685): #20     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #21     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #22     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #23     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #24     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #25     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #26     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #27     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #28     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #29     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #30     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #31     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #32     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #33     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #34     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #35     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #36     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #37     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #38     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #39     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #40     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #41     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #42     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #43     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #44     StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 3685): #45     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #46     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #47     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #48     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #49     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #50     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #51     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #52     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #53     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #54     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #55     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #56     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #57     StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 3685): #58     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #59     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #60     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #61     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 3685): #62     Element.rebuild
(package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 3685): #63     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 3685): #64     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 3685): #65     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 3685): #66     Element.updateChild
(package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 3685): #67     RenderObjectToWidgetElement._rebuild
(package:flutter/src/widgets/binding.dart:809)
I/flutter ( 3685): #68     RenderObjectToWidgetElement.mount
(package:flutter/src/widgets/binding.dart:780)
I/flutter ( 3685): #69
RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:726)
I/flutter ( 3685): #70     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2231)
I/flutter ( 3685): #71     RenderObjectToWidgetAdapter.attachToRenderTree
(package:flutter/src/widgets/binding.dart:725)
I/flutter ( 3685): #72
BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget
(package:flutter/src/widgets/binding.dart:616)
I/flutter ( 3685): #73     runApp (package:flutter/src/widgets/binding.dart:658)
I/flutter ( 3685): #74     main
(file:///home/dori/Projects/personal/flutter/grablunch/lib/main.dart:17)
I/flutter ( 3685): #75     _startIsolate.<anonymous closure>
(dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
I/flutter ( 3685): #76     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter ( 3685):
════════════════════════════════════════════════════════════════════════════════════════════════════

🔥  To hot reload your app on the fly, press "r". To restart the app entirely,
press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available
at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```

## Flutter Doctor
```
 flutter doctor                                 [0f12a7e; 17:41:01]
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/dori/Projects/personal/flutter/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /opt/android-sdk
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by alan-knight** [comment]
It's in generated code, which would normally be in a <prefix>messages_all.dart file. You need to generate that, (see intl_translation) and import it.

**Comment by Fandekasp** [comment]
Thanks @alan-knight I had indeed forgotten to `import 'package:grablunch/l10n/messages_all.dart' show initializeMessages; `

This issue is solved, but I'm having a couple linting issues left:
```
Analyzing /home/dori/Projects/personal/flutter/grablunch...

   info • Don't import implementation files from another package. • lib/l10n/messages_all.dart:9:8
   info • Method doesn't override an inherited method. • lib/localization.dart:53:8
2 issues found • analyzed 3 files, 0.40 seconds
```

The first warning is shown next to `  static Future<AppLocalizations> load(Locale locale) {` ([l.47 of the example](https://github.com/flutter/website/blob/master/_includes/code/internationalization/intl/main.dart#L47)) , and refers to the line `import 'package:intl/src/intl_helpers.dart';` in the messages_all.dart file.

The second one comes from 
```
  @override
  bool isSupported(Locale locale) => ['en', 'ja'].contains(locale.languageCode);
```
([l.74 of the example](https://github.com/flutter/website/blob/master/_includes/code/internationalization/intl/main.dart#L74))

Removing the `@override` suppress the warning, and the app still behaves correctly. Not sure what to do regarding the first warning  though.  I'd like to keep `flutter analyze` free of issues if possible.

**Comment by alan-knight** [comment]
I can't speak to the one in localization.dart. 

Generally, it's not a good idea to lint generated code, and depending what messages you have, you might get a lot more lint messages than that. See https://github.com/dart-lang/intl/issues/151

At the moment, I guess the answer is to exclude that file, and any generated localization files, from linting. I need to publish a new Intl version which will fix some of them, but there's no real way to fix them all, especially as different groups may have different, possibly contradictory, lints.

**Comment by zoechi** [comment]
@alan-knight you could add ignore comments for the common issues
AFAIK excludes still don't work for the analyzer
https://github.com/google/built_value.dart/blob/2a60ebe3e0700577be1a9a60f2868723a64694a1/chat_example/lib/data_model/serializers.g.dart#L9
Allowing custom file headers could help as well, similar to https://github.com/dart-lang/source_gen/issues/275

**Comment by Fandekasp** [comment]
Indeed, adding `// ignore_for_file: implementation_imports` in `lib/l10n/messages_all.dart` removes the error.
Since this isn't related to flutter anymore, I'm closing the issue, thanks for your help!

**Comment by bikcrum** [comment]
I think Flutter is still premature. No concise official documentation and small flutter community. Spend hours on this but still couldn't figure this out.

```
The method 'initializeMessages' isn't defined for the type 'AppLocalizations'.  Try correcting the name to the name of an existing method, or defining a method named 'initializeMessages'.
```
