### ISSUE TITLE
[google_maps_flutter] iOS App crashes with NSInvalidArgumentException insertObject:atIndex: object cannot be nil while popping a screen early with a GoogleMaps widget

### ISSUE THREAD

**Issue by martin-braun** [flutter/flutter#131472]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When popping a `MaterialPageRoute` early that contains a `GoogleMap` widget (either through `Navigator.pop` or through the `AppBar`), the iOS will severely crash.

It's hard to reproduce for cashed maps, because the map is done loading so fast. It's consistently reproducable if the widget has to load more stuff, such as markers, locations, etc. Try to pop early on initial load to succeed on this reproduction using the code example below.

The crash appears in production builds as well. The crash also appears sometimes when moving the map around and popping the view immediately after.

My current guess is that the widget tries to render map tiles when part of the widget does not exist anymore, in particular an array that gets nulled on dispose, but the rendering still tries to access it. This sounds pretty familiar to #105965, although that issue can be bypassed with the new renderer, iOS has no different renderer to play with.

### Expected results

No crash at all.

### Actual results

Severe crash on iOS due to the exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Google Map iOS Maps Crash Demo',
      themeMode: ThemeMode.light,
      home: HomePage(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("iOS Maps Crash"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: Text("Load Map"),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) {
                        return Scaffold(
                            appBar: AppBar(),
                            body: GoogleMap(
                              zoomGesturesEnabled: false,
                              zoomControlsEnabled: false,
                              myLocationButtonEnabled: false,
                              compassEnabled: false,
                              mapToolbarEnabled: false,
                              initialCameraPosition: CameraPosition(
                                  target: LatLng(-33.8567844, 151.213108),
                                  zoom: 15),
                              mapType: MapType.normal,
                              myLocationEnabled: false,
                            ));
                      },
                    ),
                  );
                },
              ),
            ],
          ),
        ));
  }
}
```

</details>

> Note: For a real life example that can consistently be crashed using early back clicks, see https://github.com/martin-braun-net/google_maps_place_picker_mb/tree/master/example as it loads more things and thus keeping the map from finishing loading for a longer period of time.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Flutter iOS Google Maps Crash demonstration](https://github.com/flutter/flutter/assets/24259245/54572c7e-10c8-4457-a842-8b60339e50dd)

</details>

### Logs

<details><summary>Logs</summary>

iOS device logs (Xcode):

```console
2023-07-28 12:01:17.616885+0200 Runner[78098:23124168] Metal GPU Frame Capture Enabled
2023-07-28 12:01:17.617212+0200 Runner[78098:23124168] Metal API Validation Enabled
2023-07-28 12:01:17.682307+0200 Runner[78098:23124168] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
2023-07-28 12:01:17.794295+0200 Runner[78098:23126211] flutter: The Dart VM service is listening on http://127.0.0.1:52063/uUY7jhAuRog=/
2023-07-28 12:01:26.074418+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.074647+0200 Runner[78098:23124168] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075211+0200 Runner[78098:23124168] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075253+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075786+0200 Runner[78098:23124168] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.075834+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.079059+0200 Runner[78098:23126138] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:26.079232+0200 Runner[78098:23126138] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2023-07-28 12:01:28.721885+0200 Runner[78098:23124168] Google Maps SDK for iOS version: 5.2.0.0
2023-07-28 12:01:28.722059+0200 Runner[78098:23124168] New version of Google Maps SDK for iOS available: 8.0.0.0
2023-07-28 12:01:59.141517+0200 Runner[78098:23124168] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80045478b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004db73 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004dc806 _CFThrowFormattedException + 200
	3   CoreFoundation                      0x00007ff8004d992b -[__NSArrayM insertObject:atIndex:].cold.2 + 0
	4   CoreFoundation                      0x00007ff80033d8e4 -[__NSArrayM insertObject:atIndex:] + 951
	5   Flutter                             0x0000000109df158b _ZN7flutter30FlutterPlatformViewsController19BringLayersIntoViewENSt21_LIBCPP_ABI_NAMESPACE3mapIxNS1_6vectorINS1_10shared_ptrINS_24FlutterPlatformViewLayerEEENS1_9allocatorIS6_EEEENS1_4lessIxEENS7_INS1_4pairIKxS9_EEEEEE + 309
	6   Flutter                             0x0000000109df0da0 _ZN7flutter30FlutterPlatformViewsController11SubmitFrameEP15GrDirectContextRKNSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_10IOSContextEEENS3_10unique_ptrINS_12SurfaceFrameENS3_14default_deleteISA_EEEE + 1058
	7   Flutter                             0x0000000109e118b3 _ZN7flutter23IOSExternalViewEmbedder11SubmitFrameEP15GrDirectContextNSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_12SurfaceFrameENS3_14default_deleteIS5_EEEE + 143
	8   Flutter                             0x000000010a58ec0f _ZN7flutter10Rasterizer19DrawToSurfaceUnsafeERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 1281
	9   Flutter                             0x000000010a590c64 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer13DrawToSurfaceERNS2_20FrameTimingsRecorderERNS2_9LayerTreeEE3$_1NS_9allocatorIS8_EEFvvEEclEv + 26
	10  Flutter                             0x000000010a25c91e _ZNK3fml10SyncSwitch7ExecuteERKNS0_8HandlersE + 56
	11  Flutter                             0x000000010a58d1bf _ZN7flutter10Rasterizer13DrawToSurfaceERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 357
	12  Flutter                             0x000000010a58df71 _ZN7flutter10Rasterizer6DoDrawENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_20FrameTimingsRecorderENS1_14default_deleteIS3_EEEENS1_10shared_ptrINS_9LayerTreeEEE + 121
	13  Flutter                             0x000000010a58f775 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS2_8PipelineINS2_13LayerTreeItemEEEEENS_8functionIFbRNS2_9LayerTreeEEEEE3$_1NS_9allocatorISG_EEFvNS_10unique_ptrIS6_NS_14default_deleteIS6_EEEEEEclEOSM_ + 193
	14  Flutter                             0x000000010a58da1d _ZN7flutter8PipelineINS_13LayerTreeItemEE7ConsumeERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFvNS3_10unique_ptrIS1_NS3_14default_deleteIS1_EEEEEEE + 193
	15  Flutter                             0x000000010a58d378 _ZN7flutter10Rasterizer4DrawERKNSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_8PipelineINS_13LayerTreeItemEEEEENS1_8functionIFbRNS_9LayerTreeEEEE + 150
	16  Flutter                             0x000000010a58faa4 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS5_8PipelineINS5_13LayerTreeItemEEEEENS_8functionIFbRNS5_9LayerTreeEEEEE3$_0EENS_9allocatorISK_EEFvvEEclEv + 128
	17  Flutter                             0x000000010a259315 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 163
	18  Flutter                             0x000000010a25fd78 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	19  CoreFoundation                      0x00007ff8003b3353 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	20  CoreFoundation                      0x00007ff8003b2eb0 __CFRunLoopDoTimer + 799
	21  CoreFoundation                      0x00007ff8003b2637 __CFRunLoopDoTimers + 243
	22  CoreFoundation                      0x00007ff8003acec8 __CFRunLoopRun + 2183
	23  CoreFoundation                      0x00007ff8003ac264 CFRunLoopRunSpecific + 560
	24  GraphicsServices                    0x00007ff809b4024e GSEventRunModal + 139
	25  UIKitCore                           0x000000010da627bf -[UIApplication _run] + 994
	26  UIKitCore                           0x000000010da675de UIApplicationMain + 123
	27  Runner                              0x000000010514b5bf main + 63
	28  dyld                                0x00000001064d2384 start_sim + 10
	29  ???                                 0x000000011163441f 0x0 + 4586685471
)
libc++abi: terminating due to uncaught exception of type NSException
(lldb) 
```

Debug Console logs (VSCode):

```console
Launching lib/main.dart on iPhone Xs Max in debug mode...
main.dart:1
Xcode build done.                                           12.5s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:56388/mWm95VyWBuk=/ws
Google Maps SDK for iOS version: 5.2.0.0
New version of Google Maps SDK for iOS available: 8.0.0.0
Lost connection to device.
Exited
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
> fvm flutter doctor -v       [crash-fixes] 
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/marty/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/marty/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/marty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Arc.app/Contents/MacOS/Arc

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • iPhone 8 Plus (mobile) • 2F109AE8-CAE0-4948-9E4E-47B422CC576B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone Xs Max (mobile) • 2BBDAB13-5584-4DA1-8FDC-C40A742B7E93 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

> Note: The issue was also existing on Flutter 3.10.5, but I don't know if this is a regression or not.

**Comment by dam-ease** [comment]
Hi @martin-braun. Thanks for filing this issue. This issue seems to have been fixed on the latest `master` channel. Kindly switch to the latest `master` to confirm this.

**Comment by martin-braun** [comment]
@dam-ease My Flutter Doctor now:

```
[✓] Flutter (Channel master, 3.13.0-11.0.pre.24, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
    • Flutter version 3.13.0-11.0.pre.24 on channel master at /Users/marty/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0ff68b8c61 (3 hours ago), 2023-07-28 04:09:52 -0400
    • Engine revision cfa5427dc4
    • Dart version 3.2.0 (build 3.2.0-11.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/marty/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/marty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Arc.app/Contents/MacOS/Arc

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • iPhone 8 Plus (mobile) • 2F109AE8-CAE0-4948-9E4E-47B422CC576B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone Xs Max (mobile) • 2BBDAB13-5584-4DA1-8FDC-C40A742B7E93 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.4.1
      22F770820d darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

The issue still appears and is reproducable using the above example.

**Comment by martin-braun** [comment]
@dam-ease I think on a real device the map is ready too fast, but I am not sure. I reproduced the issue on a real device, but not on the minimal example, although the error message is the same.

I maintain https://github.com/martin-braun-net/google_maps_place_picker_mb/, experienced the crash, so I went ahead and stripped the example down until it's not using the package anymore. You can find it here: https://github.com/martin-braun/google_maps_place_picker_mb/tree/ios-crash-case/example

This example project out-commented everything that relates to my package. This is what I did, because I originally thought the issue must be on my side, I'm not so sure, anymore.

Could you please clone the above `ios-crash-cash` and launch it within the iPhone Xs Max simulator. You should then have easier times to reproduce it. 

To confirm that it's happening on real devices as well, I suggest to clone the upstream that does more stuff in the initialization process of the maps widget, thus you are more likely to get the same crash with the same error message.

In all cases, please launch from Xcode so you can catch the unhandled exception and receive its logs. Thank you.

**Comment by dam-ease** [comment]
Hi @martin-braun. Thanks for this. From your logs, this seems to be similar/related to https://github.com/flutter/flutter/issues/130873 which seems to not be reproduced at first run sometimes. Closing this in favour of the already open issue. Kindly comment, upvote and follow up on that issue for updates, if you disagree, please comment and I'd reopen this.
Thank you!

**Comment by martin-braun** [comment]
@dam-ease I kindly ask you to re-open at least one of both then. I do confirm that the logs share the same critical exception with the same stacktrace.
