### ISSUE TITLE
Console prints dart:ui_web warnings in a new Flutter project

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#133069]
Running a brand new Flutter web app shows these warnings:

```
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

I am also seeing this warning in a separate project, even though the app is using the correct (non-deprecated) API:

```
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
```

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter project
2. Run the app in Chrome
3. Observe warnigns

### Expected results

Warnings should not be printed.

### Actual results

Warnings are printed

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Logs

<details><summary>Logs</summary>

```console
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v         
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale
    en)
    • Flutter version 3.13.0 on channel stable at
      /Users/ryjohn/code/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/ryjohn/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.1012163
      9/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/ryjohn/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.1012163
      9/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/ryjohn/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/ryjohn/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/ryjohn/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/ryjohn/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by johnpryan** [comment]
Thanks for checking, I can confirm that the first two warnings no longer show up on the main channel, but I still see a warning when I import `dart:ui_web`:

```dart
import 'dart:ui_web' as ui;
import 'dart:html';
import 'package:flutter/material.dart';

void main() {
  ui.platformViewRegistry
      .registerViewFactory('example', (_) => DivElement()..innerText = 'Hello, HTML!');

  runApp(
    MaterialApp(
      title: 'Example',
      theme: ThemeData(colorSchemeSeed: const Color(0xff000000)),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Example'),
        ),
        body: const Column(
          children: [
            Text('Hello, Flutter!'),
            SizedBox(width: 512, height: 512, child: HtmlElementView(viewType: 'example'))
          ],
        ),
      ),
    ),
  );
}
```

```
flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             11.5s
This app is linked to the debug service: ws://127.0.0.1:51886/1CngtyeULrM=/ws
Debug service listening on ws://127.0.0.1:51886/1CngtyeULrM=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:51886/1CngtyeULrM=
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from
`dart:ui_web` instead.
````

**Comment by huycozy** [comment]
Thanks for your confirmation. Keeping the issue open until the fix's landed.

**Comment by Quantentunnel** [comment]
I updated to Flutter 3.13.1 today and get this when I start my project:

The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
The webOnlySetPluginHandler API is deprecated and will be removed in a future release. Please use `setPluginHandler` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.

I just want to emphasize that my project is not new! If I can help you in any way, write briefly.

**Comment by mhmzdev** [comment]
Facing same issue as above. `flutter 3.13`

**Comment by dipinsonwani** [comment]
Facing the same issue

**Comment by NeonX** [comment]
Facing the same issue. flutter 3.13.0

**Comment by raynerhsg** [comment]
Facing same issue, flutter 3.13.1

**Comment by sprabhdeep** [comment]
Adding more on this issue. In addition to above warnings, I'm receiving below as well on flutter web project.
(Flutter 3.13.1 • channel stable)

The webOnlyAssetManager getter is deprecated and will be removed in a future release. Please use `assetManager` from `dart:ui_web` instead.

**Comment by uri-ravzin** [comment]
same issues, on 3.13.1

```
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
The webOnlySetPluginHandler API is deprecated and will be removed in a future release. Please use `setPluginHandler` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

**Comment by DouglasCarterBor** [comment]
same problems here, in 3.13.1

`The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
The webOnlyAssetManager getter is deprecated and will be removed in a future release. Please use `assetManager` from `dart:ui_web` instead.
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
The webOnlySetPluginHandler API is deprecated and will be removed in a future release. Please use `setPluginHandler` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.`

**Comment by johnpryan** [comment]
cc: @yjbanov we might want to land a patch to the stable channel

**Comment by ditman** [comment]
I suspect we could cherry-pick this commit:

* https://github.com/flutter/flutter/commit/87d5214da61c7537742c00f9f1799af4cd7e672e

And most of the issues would go away. I'm trying this right now.

The `platformViewRegistry` one might need updates to plugins / definition of platform views on the web.

**Comment by ditman** [comment]
I have requested a cherry-pick, here:

* https://github.com/flutter/flutter/issues/133892

**Comment by ditman** [comment]
Looking at the `platformViewRegistry` now :/

**Comment by jerehupanen** [comment]
Just updated my version and I'm also getting these errors in the debug console when launching the Chrome build (they're repeated 3 times when I start the app).

```
The webOnlyAssetManager getter is deprecated and will be removed in a future release. Please use `assetManager` from `dart:ui_web` instead.
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
```

This is my version:
```
flutter --version
Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (12 days ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
```

Did anyone figure out a fix? Is this something I should try to actively fix myself?

**Comment by kevan-mtl** [comment]
same issue as @jerehupanen ! 
```
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The webOnlySetPluginHandler API is deprecated and will be removed in a future release. Please use `setPluginHandler` from `dart:ui_web` instead.
```

Flutter doctor:

```
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64,
    locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.81.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by ditman** [comment]
> Is this something I should try to actively fix myself?

@jerehupanen depends on your code, of course.

The first two warnings should be taken care of by the cherry-pick I linked above. For the other two that show up several times:

* Are you creating HTMLElementViews yourself? (That would trigger the `platformViewRegistry` getter warning)
* Are you accessing the asset manager? (That would trigger the `webOnlyAssetManager` warning).

If not, the warning probably comes from a plugin/package that you're using. 1P plugins were updated in this PR:

* https://github.com/flutter/packages/pull/4168

So you might want to ensure that all the plugins you use are updated to the latest versions. If the plugin is a 3P, you probably should ask them to update the code like we did in the PR above.

**Comment by datnttg** [comment]
Facing Same issue. Flutter version 3.13.2 on channel stable

```
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The webOnlySetPluginHandler API is deprecated and will be removed in a future release. Please use `setPluginHandler` from `dart:ui_web` instead.
```

**Comment by jerehupanen** [comment]
@ditman Thanks for the help!

Turns out the `platformViewRegistry` and `webOnlyAssetManager` errors were caused by the [video_player](https://pub.dev/packages/video_player) package, which automatically includes the unlisted [video_player_web](https://pub.dev/packages/video_player_web) package. The errors disappeared after I manually added the newest version of the video_player_web package into my pubspec.

As for the fixes you just committed, will they become available through the stable branch soon (aka I just need to run `flutter upgrade`), or do I need to do something else?

**Comment by mhmzdev** [comment]
@jerehupanen I don't have any `video_player` package in my project. Yet it's showing the same logs/warnings. Any work around?

**Comment by MohamedAymon** [comment]
same in  3.13.2

**Comment by RoyalCoder88** [comment]
the same problems 3.13.2

**Comment by ditman** [comment]
> As for the fixes you just committed, will they become available through the stable branch soon (aka I just need to run flutter upgrade), or do I need to do something else?

@jerehupanen Yes, the cherry-pick has been approved and [merged](https://github.com/flutter/flutter/pull/133891), and should be available in an upcoming `stable` hotfix release (I guess 3.13.3).

**Comment by jstdk** [comment]
> @ditman Thanks for the help!
> 
> Turns out the `platformViewRegistry` and `webOnlyAssetManager` errors were caused by the [video_player](https://pub.dev/packages/video_player) package, which automatically includes the unlisted [video_player_web](https://pub.dev/packages/video_player_web) package. The errors disappeared after I manually added the newest version of the video_player_web package into my pubspec.
> 
> As for the fixes you just committed, will they become available through the stable branch soon (aka I just need to run `flutter upgrade`), or do I need to do something else?

This solved it for me. Thanks

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/flutter/pull/133891

**Comment by WorikQCI** [comment]
Not fixed.

I got a note this morning that there was a flutter upgrade.

```
 % flutter upgrade
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.
```

I am too busy to look ,ore right now, but the saga continues!

**Comment by kfranic1** [comment]
> Not fixed.
> 
> I got a note this morning that there was a flutter upgrade.
> 
> ```
>  % flutter upgrade
> Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.
> ```
> 
> I am too busy to look ,ore right now, but the saga continues!

It's because of unstashed changes on your git. Flutter won't upgrade if you have new changes on your current branch

**Comment by WorikQCI** [comment]
<blockquote>
@WorikQCI
Use flutter upgrade --force
</blockquote>

No.  I am not forcing anything.

Running `flutter upgrade` from the directory where flutter is installed works.

As I said:  This is not fixed.

**Comment by ditman** [comment]
@WorikQCI the cherry-pick seems to have been released in Flutter stable 3.13.3 ([contents](https://github.com/flutter/flutter/commits/3.13.3)).

> As I said: This is not fixed.

Can you be more specific with the Flutter version that you're using, the errors that you're seeing and a sample of your code reproducing the issue?

Otherwise, it's very hard to help you.

**Comment by WorikQCI** [comment]
Working now.  Awesome work!

**Comment by jstdk** [comment]
@ditman, this one is still there 

![image](https://github.com/flutter/flutter/assets/115603308/a1447a26-58cb-435a-9c34-21682159185f)

**Comment by jstdk** [comment]
@ditman, this one is left, all the others are gone

![image](https://github.com/flutter/flutter/assets/115603308/7e605758-676b-4c9e-b175-becbc0d741bb)

![image](https://github.com/flutter/flutter/assets/115603308/c134f615-acda-41f3-8d97-f346ad90a216)

**Comment by ditman** [comment]
@jstdk can you please check that your plugins are updated or if you're using your own platform views? All 1P plugins (flutter/packages) should be already corrected, but others (or your own code) might not.

**Comment by Quantentunnel** [comment]
Brief update from me: Now I upgraded to Flutter 3.13.4 and get still the message.

**Comment by inaamflutterdev** [comment]
facing the Same issue.
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.

**Comment by ditman** [comment]
@Quantentunnel please check [this comment](https://github.com/flutter/flutter/issues/133069#issuecomment-1720133150).

@inaamflutterdev please check [this comment](https://github.com/flutter/flutter/issues/133069#issuecomment-1718244662).

**Comment by naty-car0n** [comment]
Olá @ditman, estou enfrentando o mesmo problema. 

The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.

Flutter version 3.13.5 on channel stable at C:\flutter
Dart version 3.1.2
DevTools version 2.25.0 

environment:
  sdk: ">=2.15.0 <3.7.0"

flutter_osm_plugin: 0.60.4

**Comment by ditman** [comment]
> flutter_osm_plugin: 0.60.4

@naty-car0n I think your problem may come from here:

* https://github.com/liodali/osm_flutter/blob/master/flutter_osm_web/lib/src/controller/web_osm_controller.dart#L32

As described [here](https://github.com/flutter/flutter/issues/133069#issuecomment-1707455542), this needs a small refactor.

**Comment by longtimedeveloper** [comment]
I am now getting this same warning in debug console:  

**The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.**

This seems like a dart / flutter issue as I am not using this in my code.

>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.19045.3448], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)  
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by mpalmer-sps** [comment]
Hello,
I'm seeing this issue in the console:
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.

I believe that it may be after installing quill_html_editor: ^2.2.6 but I'm not certain of that.
[✓] Flutter (Channel stable, 3.13.4, on macOS 14.0 23A344 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by ditman** [comment]
> I believe that it may be after installing quill_html_editor: ^2.2.6 but I'm not certain of that.

@mpalmer-sps certainly: https://github.com/the-airbender/quill_html_editor/blob/8464768dcecac81a629cf9e7780ad3ead7cc0ecd/lib/src/widgets/webviewx/src/view/impl/web.dart#L185

**Comment by inaamflutterdev** [comment]
No i import darl.html mistakenly that why the error was coming. I remove
that import and the problem get solved.

**Comment by inaamflutterdev** [comment]
Glad to hear it!
