### ISSUE TITLE
Doing a hot restart while the debugger is paused hangs.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13396]
Doing a hot restart while the debugger is paused hangs, which, because of https://github.com/flutter/flutter/issues/13395, then turns into a crash.

To reproduce, do `flutter run`, pause the debugger in the observatory, then hit `R` at the `flutter` terminal.

Marking m3 because this will affect users early in their development with Flutter.

**Comment by mit-mit** [comment]
@Hixie this seems exotic enough that we could consider punting to M4?

**Comment by sroddy** [comment]
This also happens if the app is paused because of a breakpoint.

**Comment by Hixie** [comment]
Do we not think people will use the debugger?

It's extremely common as soon as you use the debugger, because the typical workflow is:
1. set a breakpoint
2. step through the code until you see the bug
3. fix the bug
4. restart
5. crash

**Comment by mit-mit** [comment]
From the original description I thought this was limited to reloads while paused at breakpoints in the *Observatory* debugger, and that is what I based the 'exotic' comment on. Does it apply to breakpoints in all our tools (e.g. in IntelliJ og vsCode)?

**Comment by DanTup** [comment]
This does affect IDEs too. The user hits restart and it seems to hang with "Performing hot reload" in the status bar and they just remain at the breakpoint. Hitting continue does nothing (sends a resume to observatory, but it's unresponsive and eventually you get timeout errors).

I had a report at https://github.com/Dart-Code/Dart-Code/issues/756

**Comment by DanTup** [comment]
@mjohnsullivan told me he'd had some issues restarting lately; I suspect it could be this.

**Comment by csga5000** [comment]
It's especially annoying in IDE's that have auto-reload on save (and you don't disable it).  It can be convenient, and some  user's may wish for it.

But if you had a breakpoint, you modify that file after figuring out a fix, but forget to hit "continue" before saving then you will have to stop the app and re-run it.  For me, when testing on iOS (android is faster), even for a somewhat small app that takes about 30 seconds (and you have to manually catch up to your previous state) which is really annoying when you're accustomed to the convenience of flutter reloading. (and does add up over time)

**Comment by csga5000** [comment]
I suppose I should note, it seems to be a problem for me with reloads OR restarts.

**Comment by mit-mit** [comment]
@devoncarew I think we need to take a look a this one. Who's a good candidate for that?

**Comment by aam** [comment]
@Hixie wrote:
>set a breakpoint
> step through the code until you see the bug
> fix the bug
> restart
> crash

  Are you still seeing this? I tried reproducing this, but couldn't: run Flutter Gallery with `flutter run`, set a breakpoint in Observatory in drawer.dart onTap handler, hit breakpoint, edit drawer.dart code/add print statements into onTap handler, hit 'R' on `flutter run` session, app restarts as expected.

**Comment by devoncarew** [comment]
I can't repro the exact issue, but I do see a timeout if trying to repro this on the first reload:

On the latest flutter from master:

- run an app
- hit a breakpoint
- trigger a hot reload
- after perhaps ~30 seconds, I see the stack trace below

This does not repo if you do a hot reload first - when not at a breakpoint - then break. After the first successful hot reload, you can then reload when paused at a breakpoint.

```
Initializing hot reload...
Hot reload failed: TimeoutException: Request to Dart VM Service timed out: _flutter.setAssetBundlePath({viewId: _flutterView/0x6040003e0020, assetDirectory: /Users/devoncarew/Library/Developer/CoreSimulator/Devices/B8126176-E1DD-4BFB-87E2-66DEE028DD28/data/Containers/Data/Application/63D61189-4B0C-4D16-9C78-C2B5DF0EF080/tmp/conference_app9ZgB21/conference_app/build/flutter_assets})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:750)
<asynchronous suspension>
#1      VM.invokeRpc (package:flutter_tools/src/vmservice.dart:767)
<asynchronous suspension>
#2      FlutterView.setAssetDirectory (package:flutter_tools/src/vmservice.dart:1351)
<asynchronous suspension>
#3      FlutterDevice.resetAssetDirectory.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:161)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#6      Future.wait (dart:async/future.dart:385)
#7      FlutterDevice.resetAssetDirectory (package:flutter_tools/src/resident_runner.dart:160)
<asynchronous suspension>
#8      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:527)
<asynchronous suspension>
#9      HotRunner.restart (package:flutter_tools/src/run_hot.dart:461)
<asynchronous suspension>
#10     AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:804)
#11     AppDomain.restart.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:475)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
```

**Comment by devoncarew** [comment]
I have not dug into the timing of the call to `_flutter.setAssetBundlePath()` in flutter tools, but we should probably move the timing of when we call that to after the initial app start - out of the first hot reload.

**Comment by aam** [comment]
thanks @devoncarew , I'm able to reproduce TimeoutException on hot reload request while paused on breakpoint. I think the reason for that is that engine's `SetAssetBundlePathInPlatformView` posts appropriate task on ui thread, but if the app is paused on breakpoint, ui event loop is not running, so the task won't be picked up for processing.

`setAssetBundlePath` is done at the time of first hot reload so that hot-reloaded flutter app picks up latests assets copied from the host to the device.

**Comment by devoncarew** [comment]
I did confirm that in - `run_hot.dart` - moving the call to `device.resetAssetDirectory()` to earlier in the connection lifecycle - like into the `attach()` method - does fix the issue.

**Comment by aam** [comment]
I see, but perhaps switching flutter app to new asset directory before we know we need it as part of hot reload is really unnecessary.
I think forcing setAssetBundlePath to run on ui thread is not really needed as only thing that request does is it sets asset store based on new host-provided path.

**Comment by devoncarew** [comment]
👍 sounds great - I wasn't really advocating for the resetAssetDirectory lifecycle change as the best solution, just pointing it out as one possibility.

**Comment by DanTup** [comment]
@aam was this possible fixed by your fix for the timeout issue (comments suggest so)?

https://github.com/flutter/flutter/issues/17434#issuecomment-390264682

**Comment by aam** [comment]
Similarly to https://github.com/flutter/flutter/issues/17434, this is fixed by the same patch that landed in https://github.com/flutter/flutter/commit/89cb5d268d2fc939f180dcee29df7a729fd051ef.

**Comment by ThinkDigitalRepair** [comment]
This issue hasn't been fixed for me. I'm still receiving it today.

> Flutter 1.3.8 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision e5b1ed7a7f (2 weeks ago) • 2019-03-06 14:23:37 -0800
> Engine • revision f4951df193
> Tools • Dart 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

**Comment by DanTup** [comment]
@ThinkDigitalRepair are you hitting this from an editor or command line? If an editor, does it happen from the command line? And can you repro it on a newly-created `flutter create` project?

**Comment by ThinkDigitalRepair** [comment]
Editor. From Intellij. I get a lot less issues with command line

**Comment by DanTup** [comment]
I don't know about getting lots from IntelliJ, but if you're able to reproduce it from the command line running with the `-v` flag (or in VS Code using the **Dart: Capture Logs** command), could you open a new issue and include the logs?

**Comment by maks** [comment]
@DanTup I'm seeing this consistently with VSCode. To reproduce: set breakpoint in your code, once debugger is paused at breakpoint, click hot-restart in the debugging "mini floating toolbar" in VSC, VSC dispalys in boittom right hand corner the usual floating dialog "Syncing files to device XXXXX" and its just stays there forwever, progress indicator of dialog keeps going, hot-restart never actually completes.

**Comment by DanTup** [comment]
@maks I don't seem to be able to reproduce - can you test this on a new clean project (eg. with **Flutter: New Project** or `examples/flutter_gallery` from the SDK) and give exact instructions on what you're doing (when and where you add the breakpoint, and exactly what steps you take) so I can try here?

**Comment by maks** [comment]
My apologies I can't reproduce this on a new project either. 

So far, the place in my app I'm seeing this happening consistently (hence my first comment) is where I was spending a lot of time debugging recently: in code that is in a MethodCallHandler for a MethodChannel (for Android). 

My current app where I am seeing this is quite large so bit hard to figure out exactly the cause in order to create a simplified reproducable case, but I'll have a go in next few days.

**Comment by DanTup** [comment]
@maks if you manage to repro - please open a new issue and ping me. I don't know if it's related, but it reminded me of these issues:

https://github.com/dart-lang/sdk/issues/37312
https://github.com/Dart-Code/Dart-Code/issues/1714

The first is believed to be fixed in the dev channel (maybe beta channel by now, but not stable), though the second may still be happening. When it seems to stop responding, clicking Pause then Resume seems to get it going again. If that seems to happen here, then it might be related (in which case @bkonyi may be interested in your repro).

**Comment by nickmeinhold** [comment]
I was seeing what I thought was similar behaviour and a search got me here. Although in my case it was when the debugger was breaking on exceptions, then hitting hot-restart that gave me the behaviour maks described.

I was able to repro my problem in a new clean project but only in a specific situation - throwing before runApp and having the debugger set to break on "All Exceptions", then hitting hot-restart.  In hindsight that was where I was seeing the problem so it's pretty specific and probably not the same problem but posting in case it's helpful.

**Comment by DanTup** [comment]
@nickmeinhold if you have a small repro, please do open a new issue with it for someone to take a look.

**Comment by nickmeinhold** [comment]
Sure thing, thanks Dan, would you suggest in DartCode or Flutter?

**Comment by DanTup** [comment]
Here is probably best, as if it's like the issues above, it may be a VM fix - but CC me on it and I can try to repro and check the logs in case there's anything obvious going wrong in Dart-Code.

**Comment by escamoteur** [comment]
I have the same behaviour with an almost new project @DanTup .
See https://www.screencast.com/t/ovrKFMCKfJpD

I did the same again and captured this time an observatory log. Sorry I should have made both together. 
I this doesn't help I can make another screencast

[Dart-Code-Log-2019-08-05 15-57-58.txt](https://github.com/flutter/flutter/files/3610352/Dart-Code-Log-2019-08-05.15-57-58.txt)

**Comment by DanTup** [comment]
@escamoteur thanks for the video and log - that one looks like a VS Code bug. When you click the Restart button in VS Code, we restart the app but never tell VS Code that we've unpaused (I thought it would be implied, but apparently not). This means VS Code thinks we're still paused somewhere when we're not, and shows the wrong button state (eg. continue buttons and no pause button).

I've opened https://github.com/Dart-Code/Dart-Code/issues/1994 for this.

**Comment by DanTup** [comment]
FWIW I don't think that's the same issue Hixie was seeing when he opened this - it may be the same issue @nickmeinhold was seeing though. I'll close this one, and I'll put a dev build on https://github.com/Dart-Code/Dart-Code/issues/1994 once I've checked the fix isn't breaking any existing tests so you can try it out.
