### ISSUE TITLE
[Impeller] ColorFiltered on top of ImageFiltered Widget with Blur causes UI glitches.

### ISSUE THREAD

**Issue by b-ray** [flutter/flutter#135212]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample code provided - with a Stack containing a Blurred Container below a ColorFiltered Widget and an Animated Element on top (in this case a animating CupertinoActivityIndicator)

_____________________

This is a follow-up on https://github.com/flutter/flutter/issues/135013

I was able to reproduce this on:

3.14.0-14.0.pre.358 with Impeller
3.13.4 with Impeller (where the glitch looks different)
The issue does not occur when using Skia.

(I am able to work around the glitches using BackdropFilter, but I am not sure if this is proper fix - I am worried about performance issues)

### Expected results

The animation and surrounding box should be drawn properly.

### Actual results

The surrounding box of the animation has glitches. Please see screenshot.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          ImageFiltered(
            imageFilter: ImageFilter.blur(sigmaX: 40, sigmaY: 40),
            child: ColorFiltered(
              colorFilter: ColorFilter.mode(
                  Colors.black.withOpacity(0.2), BlendMode.srcOver),
              child: Container(
                decoration: const BoxDecoration(
                  gradient: RadialGradient(
                    radius: 0.3,
                    colors: [Colors.pink, Colors.green],
                  ),
                ),
              ),
            ),
          ),
          const Center(
            child: CupertinoActivityIndicator(
              radius: 30,
              animating: true,
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Skia (Expected Result):
![Simulator Screenshot - iPhone 11 Pro - 2023-09-19 at 17 52 33](https://github.com/flutter/flutter/assets/1121929/3d5a2647-d284-44a2-96c3-dc024f179133)

Impeller (Actual Result):
![Impeller](https://github.com/flutter/flutter/assets/1121929/6db38592-858d-4455-ab67-2792925adf11)

</details>

### Logs

<details><summary>No Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.358, on macOS 13.5.2 22G91 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.82.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mahdiramazani** [comment]
very very good

**Comment by darshankawar** [comment]
Thanks for the detailed report. Seeing the same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (32 hours ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.14.0-14.0.pre.408, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.408 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b90a13f3a1 (29 minutes ago), 2023-09-21 00:44:25 -0400
    • Engine revision 88aad10567
    • Dart version 3.2.0 (build 3.2.0-185.0.dev)
    • DevTools version 2.28.0-dev.12
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by jason-simmons** [comment]
This has been fixed on the Flutter master branch (see https://github.com/flutter/engine/commit/c39eb69f)

**Comment by b-ray** [comment]
Thanks for the update @jason-simmons.
I just tried the latest master as of now `3.15.0-6.0.pre.26`, and I am unfortunately still seeing the reported glitches.

Would you be able to help me with my setup? Am I using the wrong state, or do I have to wait for this fix in the engine to be integrated in the Flutter master branch?

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel master, 3.15.0-6.0.pre.26, on macOS 13.5.2 22G91 darwin-arm64, locale en-AT)
    • Flutter version 3.15.0-6.0.pre.26 on channel master at /Users/stpu/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85e52d4363 (2 hours ago), 2023-09-21 23:34:27 -0400
    • Engine revision e0fb071ead
    • Dart version 3.2.0 (build 3.2.0-188.0.dev)
    • DevTools version 2.28.0-dev.12

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/stpu/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/stpu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.82.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • 8502B9A2-1553-4219-93B0-21E155C971E7 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64 • macOS 13.5.2 22G91 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by jason-simmons** [comment]
Sorry - I misunderstood which output was the correct rendering for this app.

On iOS, this issue regressed with https://github.com/flutter/engine/commit/c39eb69f

@bdero

**Comment by jason-simmons** [comment]
This also seems to be related to partial repaint.

The white rectangle behind the progress indicator started with https://github.com/flutter/engine/commit/c39eb69f.  But before that commit the output had an opaque red rectangle around the indicator.

If I patch `CompositorContext::ScopedFrame::Raster` to disable partial repaint then the app renders as intended on iOS.

@jonahwilliams

**Comment by jonahwilliams** [comment]
Generally speaking, unless the repaint rect is wrong (and Skia has the bug too) the only thing partial repaint does is shift bounds and change how pictures are offset. If that causes incorrect rendering the problem is actually a bug in entity pass coverage computation/culling and could be triggered with a playground that emulates a partial repaint like scene by drawing something similar with with a negative offset.

**Comment by jonahwilliams** [comment]
Spent some time investigating this. 

Without partial repaint, the coverage and coverage hint for the blend filter is ((0, 0), (1179, 2556)). With Partial repaint the coverage hint is ((499, 1188), (181, 180)) (which seems correct?)

If I remove the blur filter, the rendering is correct and the coverage hint becomes (0, 0, 181, 180). If I remove the color filter the rendering is also correct. If I stack up two color filters then everything works as expected.

So my guess is that the blur filter -> color filter combo is dropping coverage information on the floor somehow in the presence of partial repaint. I also suspect that this is unique to the blur filter.

**Comment by flar** [comment]
Could this be due to this typo?

https://github.com/flutter/engine/pull/45778#discussion_r1341846040
