### ISSUE TITLE
Xcode 15 launch failure with iOS 17 "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data."

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#135442]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This doesn't happen to me consistently, but there are various reports of this issue:
https://github.com/flutter/flutter/issues/134667#issuecomment-1730978188
https://github.com/flutter/flutter/issues/134667#issuecomment-1732321539
https://github.com/flutter/flutter/issues/135208#issuecomment-1729735614

 The only way I've been able to relatively consistently recreate is

1. Create a flutter project
2. Do `flutter run`
3. Do `flutter clean`
4. Do `flutter run --profile` on an iOS 17 device

### Actual results

Xcode has this error: Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.

![Screenshot 2023-09-25 at 11 47 46 AM](https://github.com/flutter/flutter/assets/15619084/a02de510-85ef-4dbb-b6f3-70dd557dfe77)

<details>
<summary>Show Details</summary>

```
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-09-25 16:47:36 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///xxx/Library/Developer/Xcode/DerivedData/Runner-cvrsbfztnjtwapghkyzoauztkppf/Build/Products/Debug-iphoneos/Runner.app";
}
--
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPad14,3";
    "device_osBuild" = "17.0 (21A329)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 5;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.5.2 (Build 22G91)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-09-25T11:47:36-05:00
```
</details>

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by komaxx** [comment]
Same issue since XCode 15 + iOS 17 update.

Interesting: I *can* launch the app on iOS when I use the XCode UI but I get the described error when attempting to launch from Android Studio.

**Comment by lanrehnics** [comment]
UP

**Comment by RealYoungk** [comment]
Surprisingly, I was experiencing the same problem and I don't know if it's related, but I solved it in the following way.

1. My computer had three android studios
2. Deleted two unused Android studios.
3. And I built it and succeeded.

**Comment by sxm5220** [comment]
first close the Xcode，then flutter run with VSCode or android studio.This method solved my problem.（Run the project without opening Xcode）

**Comment by sxm5220** [comment]
> > first close the Xcode，then flutter run with VSCode or android studio.This method solved my problem.（Run the project without opening Xcode）
> 
> In my case it opens up closed XCode... so frustrating.

May be a new feature of Xcode15 for Futter. In the future  I think  new versions of Futter will solve this problem.

**Comment by sxm5220** [comment]
> > first close the Xcode，then flutter run with VSCode or android studio.This method solved my problem.（Run the project without opening Xcode）
> 
> In my case it opens up closed XCode... so frustrating.

May be a new feature of Xcode15 for Flutter. In the future I think new versions of Flutter will solve this problem.

**Comment by vashworth** [comment]
A fix is out on master. If anyone who was having this problem consistently could try out the fix and report back, that'd be much appreciated.

**Comment by RobertBrunhage** [comment]
@vashworth I am runing stable channel and cherry-picked this in locally, and worked for me!

**Comment by dodatw** [comment]
@vashworth It work!. Can it cherry picked to 3.13 ?

**Comment by vashworth** [comment]
Awesome! Thanks for trying it out! I'll get it hotfixed into stable soon

**Comment by heshesh2010** [comment]
same error but on vs code and flutter v stable  3.13.5 and latest Xcode 15

**Comment by ElDuderini** [comment]
Will this fix get included in the stable release in version 3.13.7? Just downloaded version 3.13.6 and noticed it wasn't included in that round of hotfixes.

**Comment by stuartmorgan** [comment]
You can follow https://github.com/flutter/flutter/issues/135610 for updates on a 3.13 release.

**Comment by ElDuderini** [comment]
> You can follow #135610 for updates on a 3.13 release.

Thank you!

**Comment by nagringapp** [comment]
Hi All, I have been having the same issue, however with the latest fluter update and also the latest Ventura OS and the latest iOS 17 on the device:

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64, locale en-AU)
    • Flutter version 3.13.6 on channel stable at /Users/caco/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (3 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/caco/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/caco/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (5 available)
    • SM A217F (mobile) • RF8R51DXW4L                              • android-arm64  • Android 12 (API 31)
    • iPhoneX (mobile)  • 26c572951929f1725c51ca6a99108845355576d3 • ios            • iOS 16.6.1 20G81
    • iPhone11 (mobile) • 00008030-00016CC60C90802E                • ios            • iOS 17.0.1 21A340
    • macOS (desktop)   • macos                                    • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.
```

<img width="272" alt="image" src="https://github.com/flutter/flutter/assets/87851268/5983c72e-860a-4c32-bc48-a00e1d5cce0a">

Error: 
```
Launching lib/main.dart on iPhone11 in debug mode...
main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: 37CJ28CDPY
Xcode build done.                                           135.4s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Unexpected debug results: 
  Status: succeeded
  Completed: true
  Error Message: null

Could not run build/ios/iphoneos/Runner.app on 00008030-00016CC60C90802E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone11.
Exited
```

```
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data
```

**Comment by serhatopcu** [comment]
I'm experiencing a similar issue, but there's an interesting situation. I get this error when I have Apple Pay added, but when I remove Apple Pay, I don't encounter this problem.
<img width="795" alt="image" src="https://github.com/flutter/flutter/assets/91589497/f71a87f7-5c4a-4bec-b88c-f60275220b85">


LOG
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-09-30 07:59:34 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///Users/developer/Library/Developer/Xcode/DerivedData/Runner-gxwddfrhveriopgnikziofkghvbn/Build/Products/Debug-iphoneos/Runner.app";
}
--
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone13,4";
    "device_osBuild" = "17.0 (21A329)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 4;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-09-30T10:59:34+03:00

**Comment by nagringapp** [comment]
Note: Sometimes I get it running, I'm trying to map what makes it working

**Comment by nagringapp** [comment]
The issue on my project is launching it from VS Code, as I could launch it from XCode as mentioned above (after cleaning up the build folder).

On that angle, I created an ATTACH command on my vscode to attach flutter to the instance running:

command
```
flutter attach --app-id "BUNDLE_ID" --device-vmservice-port PORT_NUMBER -d DEVICE_ID
```

vscode
```
 {
            "name": "iPhone 14 (Dev) | ATTACH",
            "request": "attach",
            "type": "dart",
            "args": [
                "--app-id",
                "BUNDLE_ID",
                "--device-vmservice-port",
                "PORT_NUMBER",
                "-d",
                "DEVICE_ID"
            ]
        },
```

I hope it helps you guys while the fix is not stable

**Comment by nagringapp** [comment]
Another discovery about this issue: it's only happening on my updated iOS 17 device. The other device I haven't updated runs as usual.

Additional note: when launching the iOS17 device on VSCode it opens the XCode, while when I launch the iOS16 device it runs without opening the VSCode

**Comment by nagringapp** [comment]
@vashworth is there any other thread for this item? As the error is still happening, maybe it should be reopened?

**Comment by stuartmorgan** [comment]
@nagringapp According to your comment above you are running Flutter `stable`. This fix hasn't reached `stable` yet (see my comment above) so it's expected that you would still have the issue. Issues are closed when they are fixed on `master`.

**Comment by nagringapp** [comment]
Thanks mate!

**Comment by gyetaroe** [comment]
> first close the Xcode，then flutter run with VSCode or android studio.This method solved my problem.（Run the project without opening Xcode）

并没有解决

**Comment by sxm5220** [comment]
> > first close the Xcode，then flutter run with VSCode or android studio.This method solved my problem.（Run the project without opening Xcode）
> 
> 并没有解决

有什么输出提示吗？可以贴出来看看。或描述一下失败的现象。

**Comment by NM4ik** [comment]
> @nagringapp According to your comment above you are running Flutter `stable`. This fix hasn't reached `stable` yet (see my comment above) so it's expected that you would still have the issue. Issues are closed when they are fixed on `master`.

stable, master, beta not working, everywhere catch this error. I can not compile app in debug for ios physical device

**Comment by stuartmorgan** [comment]
@NM4ik Please file a new issue with details about what you see on master and steps to reproduce it so we can investigate further.

**Comment by NM4ik** [comment]
> stuartmorgan
@stuartmorgan
u can follow #136197

**Comment by likwifi** [comment]
Upgraded to Flutter 3.15.0-15.2.pre issue still persists.

**Comment by likwifi** [comment]
Upgraded to Flutter 3.15.0-15.2.pre issue still persists.

**Comment by lanrehnics** [comment]
Cherry pick the fix into flutter stable on your local.

**Comment by rgbinnovation** [comment]
> Cherry pick the fix into flutter stable on your local.

How would one do this?

**Comment by bensibjarna** [comment]
I fixed all my Xcode 15 issues with flutter by going into [System Settings -> General -> Storage -> Developer -> & Delete the XCode Cache]

**Comment by DevLSerrano** [comment]
I still have an error here.

On VsCode:
```
Xcode build done.                                           59.1s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
Error starting debug session in Xcode: Failed to get CONFIGURATION_BUILD_DIR: Error: Can't get object.
Could not run build/ios/iphoneos/Runner.app

```

**Flutter doctor:**
```
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale
    en-US)
    • Flutter version 3.13.7 on channel stable at /Users/lsworkstation/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (3 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lsworkstation/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/lsworkstation/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] VS Code (version 1.82.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone de Leonardo (mobile) • 00008030-000564542141802E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 118.0.5993.70
    ! Error: Apple Watch de Leonardo needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and
      the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.
   ```

**Comment by bensioz** [comment]
> I still have an error here.
> 
> On VsCode:
> 
> ```
> Xcode build done.                                           59.1s
> You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
> Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
> Error starting debug session in Xcode: Failed to get CONFIGURATION_BUILD_DIR: Error: Can't get object.
> Could not run build/ios/iphoneos/Runner.app
> ```
> 
> **Flutter doctor:**
> 
> ```
> [✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale
>     en-US)
>     • Flutter version 3.13.7 on channel stable at /Users/lsworkstation/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 2f708eb839 (3 days ago), 2023-10-09 09:58:08 -0500
>     • Engine revision a794cf2681
>     • Dart version 3.1.3
>     • DevTools version 2.25.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/lsworkstation/Library/Android/sdk
>     • Platform android-33, build-tools 31.0.0
>     • ANDROID_HOME = /Users/lsworkstation/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 15.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 15A240d
>     • CocoaPods version 1.13.0
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2022.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
> 
> [✓] IntelliJ IDEA Community Edition (version 2023.2.2)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 75.1.4
>     • Dart plugin version 232.9559.10
> 
> [✓] VS Code (version 1.83.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.48.0
> 
> [✓] VS Code (version 1.82.0-insider)
>     • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
>     • Flutter extension version 3.64.0
> 
> [✓] Connected device (3 available)
>     • iPhone de Leonardo (mobile) • 00008030-000564542141802E • ios            • iOS 17.0.3 21A360
>     • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
>     • Chrome (web)                • chrome                    • web-javascript • Google Chrome 118.0.5993.70
>     ! Error: Apple Watch de Leonardo needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and
>       the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
> 
> [✓] Network resources
>     • All expected network resources are available.
> ```

I believe this is another issue, you can find info #134667

**Comment by vanyasem** [comment]
While not a proper solution, a possible workaround is to:
1) Launch the app from Xcode (it will build & install without issue)
2) Open Terminal (or cmd/powershell) - either as a standalone app, or within your IDE
3) Run `flutter attach`
4) Flutter will attach to the currently running app, and will provide you with **Hot Reload, Hot Restart, and DevTools** functionality

<img width="400" alt="Screenshot 2023-10-13 at 15 51 44" src="https://github.com/flutter/flutter/assets/13350458/f7f677d0-3751-4f06-b486-53baad92ebf6">

**Comment by vashworth** [comment]
@DevLSerrano Please file a new issue and include a verbose log (e.g. `flutter run -v`) and steps to recreate

**Comment by kangchong978** [comment]
Go to the Xcode for that project, Runner -> edit schema-> change the build configuration -> Debug -> run again

**Comment by GeekAbdelouahed** [comment]
running `flutter upgrade` fixed my issue in stable channel
