### ISSUE TITLE
flutter/packages `Mac_x64 check_podspecs` fails with Xcode 15

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136737]
```
Running "pod lib lint /Volumes/Work/s/w/ir/x/w/packages/packages/file_selector/file_selector_macos/macos/file_selector_macos.podspec --configuration=Debug --skip-tests --allow-warnings --use-modular-headers"

 -> file_selector_macos
 -> file_selector_macos (0.0.1)
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | [OSX] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [OSX] xcodebuild:  note: Target dependency graph (4 targets)
    - NOTE  | [OSX] xcodebuild:  error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Pods-App' from project 'Pods')
    - NOTE  | [OSX] xcodebuild:  error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'App' from project 'App')

[!] file_selector_macos did not pass validation, due to 1 error.
```

https://ci.chromium.org/ui/p/flutter/builders/try/Mac_x64%20check_podspecs/7355/overview

This issue is the same as https://github.com/flutter/flutter/issues/132980 and can probably be solved similarly: https://github.com/flutter/flutter/pull/133588

**Comment by godofredoc** [comment]
@vashworth @stuartmorgan can you please confirm this is fixed?

**Comment by stuartmorgan** [comment]
@vashworth If merging main into https://github.com/flutter/packages/pull/5018 doesn't fix this let me know and I can investigate again.

**Comment by vashworth** [comment]
Issue is fixed https://ci.chromium.org/ui/p/flutter/builders/try/Mac_x64%20check_podspecs/8873/overview
