### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'toString')     at SingleEntryBrowserHistory.onPopState$1 

### ISSUE THREAD

**Issue by jehuamanna** [flutter/flutter#136873]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using single-spa and embedded the Flutter application. On the initial load, it throws the error message. After closing the error the application works normally.

### Expected results

The page should load normally without errors.

### Actual results

The page loaded with an error message from main.dart.js.

### Code sample

<details><summary>Code sample</summary>

```dart


function loader({entrypointUrl}) {
    // Embed flutter into div#flutter_target
    let target = document.querySelector("#flutter_target");
    _flutter.loader.loadEntrypoint({
        entrypointUrl,
      onEntrypointLoaded: async function (engineInitializer) {
        let appRunner = await engineInitializer.initializeEngine({
          hostElement: target,
          assetBase: "http://localhost:9999/"
        });
        await appRunner.runApp();
      },
    });
  }



  var app = {
    // Optional
    async bootstrap(props) {
      console.log("App is initializing!", props);
    },
    // Required
    async mount(props) {
      console.log("App is mounting", props);
      loader({entrypointUrl: "http://localhost:9999/main.dart.js"})
    //   window.entrypointUrl =  "http://localhost:9999/main.dart.js";
    },
    // Required
    async unmount(props) {
      console.log("App is unmounting", props);
      const flutterElement = document.querySelector("#flutter_target")
      flutterElement.innerHTML= ""
    },
  };

  window.app = app;
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/946070/a78c2561-16ab-40be-9643-f7a58c75ce9c)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.3 LTS 6.2.0-34-generic,
    locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jehuamanna** [comment]
The build was done with compiler optimization. flutter build web --dart2js-optimization O1

**Comment by dam-ease** [comment]
Hi @jehuamanna. Thanks for filing this. Can you please provide more information on this? 

- Does this error message cause a crash? 
- Also, can you share the full logs you are getting on first run?

Moreover, please could you also provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), usually a single `main.dart` file but you could share a sample repo in this case.
- Reproduction steps

Thank you!

**Comment by jehuamanna** [comment]
The app does and does not crash. I don't know when it depends. But after clicking the close button, it continues functioning.
In this example, the app does not crash. 


Sample app : [Sample App](https://github.com/jehuamanna/github_triage_microfrontend.git)

**Comment by dam-ease** [comment]
Hi @jehuamanna. Thanks for your response. I cloned the repo you shared and ran the sample code on my end but I can't seem to reproduce this on my end even on the first run. On the first run, I have this:

<img width="500" alt="Screenshot 2023-10-20 at 08 38 07" src="https://github.com/flutter/flutter/assets/53122008/196e0be0-54c2-46a7-b7a1-a4f4b67b779d">

Are there any steps I might be missing out on?

**Comment by jehuamanna** [comment]
When the app is embedded in another application, the error occurs. This is a micro frontend PoC using a [single-SPA](https://single-spa.js.org/)

I have written steps on how to run the Microfrontend in  [README](https://github.com/jehuamanna/github_triage_microfrontend/blob/master/README.md)

**Comment by dam-ease** [comment]
Hi @jehuamanna. Thanks for filing this, could you try this with a newly created flutter project? Also, I see a similar issue solved by https://github.com/flutter/flutter/issues/94553#issuecomment-985978074, could you try this out to see if it works in your case?

**Comment by jehuamanna** [comment]
@dam-ease I created a new Flutter project application. The issue still remains the same. This is the (updated project)[git@github.com:jehuamanna/github_triage_microfrontend.git]

I am not loading main.dart.js as script from index.html. Infact the index.html looks like (this).[https://github.com/jehuamanna/github_triage_microfrontend/blob/master/es5/index.html]

**Comment by mdebbar** [comment]
This is most likely due to 2 competing apps (the host app and the embedded flutter app) modifying the browser history.

When the flutter app is embedded, we should NOT touch the browser history by default. There's already a Github issue for doing this: https://github.com/flutter/flutter/issues/118219.

@jehuamanna if you are feeling adventurous, you could try copying our [`TestUrlStrategy`](https://github.com/flutter/engine/blob/4f0cdcd0beba315176c01a38dbf7b1ed46fdbd55/lib/web_ui/lib/src/engine/test_embedding.dart#L57) which is basically an in-memory history that doesn't mess with the browser history. Then you can use it like this:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';

void main() {
  setUrlStrategy(TestUrlStrategy());
  runApp(MyApp());
}
```

For now, I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/118219
