### ISSUE TITLE
[Impeller] Stroke text from official documentation not rendering properly on iOS with Impeller

### ISSUE THREAD

**Issue by motucraft** [flutter/flutter#136960]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter app.
2. Execute following code with Impeller.

### Expected results

https://api.flutter.dev/flutter/painting/TextStyle-class.html#painting.TextStyle.6

Text should have a clear and distinct border (or stroke) as depicted in the official Flutter documentation. Specifically, when using PaintingStyle.stroke with a specified strokeWidth and color, the text should be outlined with the given width and color. The outcome should be a text with a colored stroke surrounding the glyphs, matching the behavior shown in the official Flutter documentation's example.

### Actual results

When running the application on iOS with Impeller enabled, the text does not display the expected stroke effect. Instead, either no stroke is visible at all, or it appears extremely faint and barely noticeable, despite the provided strokeWidth and color. This behavior contrasts with the result depicted in the official Flutter documentation and the expected outcome when running without Impeller (e.g., using flutter run --no-enable-impeller).

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Stack(
            children: <Widget>[
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  foreground: Paint()
                    ..style = PaintingStyle.stroke
                    ..strokeWidth = 6
                    ..color = Colors.blue[700]!,
                ),
              ),
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  color: Colors.grey[300],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots (Impeller)</summary>

![image](https://github.com/flutter/flutter/assets/35750184/c3c2de11-6071-4d9f-adc5-9767b0169b59)

</details>

<details>
<summary>Screenshots (Without Impeller)</summary>

Execute without Impeller (either by using the flutter run --no-enable-impeller command or by updating the plist file.

![image](https://github.com/flutter/flutter/assets/35750184/e0ccf860-dab4-4338-b6f5-7bdf548f86ba)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale ja-JP)
    • Flutter version 3.13.8 on channel stable at /Users/osaki/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (2 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/osaki/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/osaki/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/osaki/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Users/osaki/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 34AAA87A-1E84-4717-A688-316247843A52 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 118.0.5993.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I believe you are hitting https://github.com/flutter/flutter/issues/136688 so please follow-up in it for further updates. Closing this as a duplicate.

**Comment by andre-arsenault** [comment]
I am seeing this issue as well. Text strokes are not working at all on iOS with Impeller enabled, as shown in the original posts's screenshots. @darshankawar this is different than #136688.

**Comment by darshankawar** [comment]
@andre-arsenault 
If you are talking about borders not showing up or not being crisp, then it isn't expected to work in 3.13, see https://github.com/flutter/flutter/issues/133157

**Comment by enricoi** [comment]
Same issue for me too. Text strokes are not working at all on iOS with Impeller enabled

**Comment by andre-arsenault** [comment]
> @andre-arsenault
> If you are talking about borders not showing up or not being crisp, then it isn't expected to work in 3.13, see #133157

No this isn't an issue with the stroke being offset or not crisp, this is complete non-functionality on iOS with Impeller enabled. As far as I can tell, it has never worked on iOS with Impeller. There have been many issues related to this in the past but they have all been closed without the issue being resolved.

We need at least one issue to remain open until the text stroke feature works on iOS with Impeller as it does on other platforms.

**Comment by darshankawar** [comment]
Thanks for the feedback @andre-arsenault 
If your issue is different from the one described here originally, please file a new issue with relevant details so that we can properly address it. If it isn't please elaborate on the issue you are describing and how is it different from the one mentioned earlier.

**Comment by andre-arsenault** [comment]
Please read the original bug report in this thread. That is the exact issue we are all experiencing.

**Text stroke does not work at all on iOS with Impeller enabled.** Please look at the screenshots in the original report. That is the problem.

**Comment by darshankawar** [comment]
@andre-arsenault 
I believe you are talking about https://github.com/flutter/flutter/issues/137134 for which the response from engine team is: https://github.com/flutter/flutter/issues/137134#issuecomment-1777677709
See if it answers your question or not.

**Comment by andre-arsenault** [comment]
@darshankawar Alright I think what you're trying to say without actually saying it is that this issue has been fixed internally and will be present in the 3.14.0 release?

That fix was implemented two months ago (August 27). When can we expect to see it in a stable release?

**Comment by darshankawar** [comment]
> Alright I think what you're trying to say without actually saying it is that this issue has been fixed internally

It is fixed and available on master version for everyone to try on. 

> will be present in the 3.14.0 release?

most probably.

**Comment by andre-arsenault** [comment]
We obviously won't be shipping our apps from the master branch though, so until the next release this issue is still essentially not fixed yet. Any ETA on the next release? I have been tracking this particular problem since May and we have been unable to use Impeller on iOS because of it.

**Comment by darshankawar** [comment]
You may read about releases [here](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#flutters-channels).

**Comment by andre-arsenault** [comment]
Wow that really wasn't helpful. I guess we just have a wait a few more months.
