### ISSUE TITLE
[Impeller] Janky scrolling with backdrop filter blur on 3.16.

### ISSUE THREAD

**Issue by ArAmM7** [flutter/flutter#138615]
### Steps to reproduce

1. create a scrollable widget with some text and image item
2. add a BackdropFilter with blur on bottomNavigationBar

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'Scrolling jank 3.16.0'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    super.key,
    required this.title,
  });

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: ListView.separated(
        itemCount: 1000,
        itemBuilder: (_, i) => Container(
          clipBehavior: Clip.antiAlias,
          margin: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            color: Colors.amberAccent,
            borderRadius: BorderRadius.circular(16),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const SizedBox(height: 4),
              for (int x = 0; x < 2; x++)
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    for (int x = 0; x < 10; x++) ...[
                      const FlutterLogo(),
                      Text('$x'),
                    ],
                  ],
                ),
              Image.network(
                'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
                height: 200,
                fit: BoxFit.cover,
              ),
              const SizedBox(height: 4),
              Text('Some  text for $i'),
              const SizedBox(height: 4),
            ],
          ),
        ),
        separatorBuilder: (_, __) => const SizedBox(height: 8),
      ),
      bottomNavigationBar: Material(
        color: Colors.transparent,
        child: BottomAppBar(
          color: const Color(0x22131313),
          shape: const CircularNotchedRectangle(),
          clipBehavior: Clip.antiAlias,
          shadowColor: Colors.transparent,
          surfaceTintColor: Colors.transparent,
          elevation: 0,
          notchMargin: 0,
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaY: 25, sigmaX: 25),
            child: const ColoredBox(
              color: Colors.transparent,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

<details><summary>Timeline Traces JSON</summary>

```json

{
    "devToolsSnapshot": true,
    "devToolsVersion": "2.28.2",
    "connectedApp": {
        "isFlutterApp": true,
        "isProfileBuild": true,
        "isDartWebApp": false,
        "isRunningOnDartVM": true,
        "operatingSystem": "ios",
        "flutterVersion": "3.16.0"
    },
    "activeScreenId": "performance",
    "performance": {
        "selectedFrameId": null,
        "flutterFrames": [
            {
                "number": 25,
                "startTime": 121472945745,
                "elapsed": 18869,
                "build": 2232,
                "raster": 14233,
                "vsyncOverhead": 469
            },
            {
                "number": 27,
                "startTime": 121472983926,
                "elapsed": 13950,
                "build": 649,
                "raster": 11978,
                "vsyncOverhead": 711
            },
            {
                "number": 29,
                "startTime": 121473012248,
                "elapsed": 23086,
                "build": 1072,
                "raster": 20894,
                "vsyncOverhead": 272
            },
            {
                "number": 31,
                "startTime": 121473028955,
                "elapsed": 21718,
                "build": 1265,
                "raster": 15170,
                "vsyncOverhead": 305
            },
            {
                "number": 33,
                "startTime": 121473045825,
                "elapsed": 24699,
                "build": 475,
                "raster": 19500,
                "vsyncOverhead": 501
            },
            {
                "number": 35,
                "startTime": 121473062305,
                "elapsed": 23037,
                "build": 1025,
                "raster": 14903,
                "vsyncOverhead": 305
            },
            {
                "number": 37,
                "startTime": 121473078911,
                "elapsed": 21710,
                "build": 3383,
                "raster": 14875,
                "vsyncOverhead": 236
            },
            {
                "number": 39,
                "startTime": 121473095554,
                "elapsed": 41899,
                "build": 3569,
                "raster": 36443,
                "vsyncOverhead": 204
            },
            {
                "number": 41,
                "startTime": 121473112350,
                "elapsed": 40190,
                "build": 847,
                "raster": 14699,
                "vsyncOverhead": 324
            },
            {
                "number": 45,
                "startTime": 121473145579,
                "elapsed": 41630,
                "build": 1155,
                "raster": 34668,
                "vsyncOverhead": 204
            },
            {
                "number": 47,
                "startTime": 121473162921,
                "elapsed": 39842,
                "build": 562,
                "raster": 14597,
                "vsyncOverhead": 871
            },
            {
                "number": 51,
                "startTime": 121473196108,
                "elapsed": 41840,
                "build": 415,
                "raster": 35233,
                "vsyncOverhead": 708
            },
            {
                "number": 53,
                "startTime": 121473212381,
                "elapsed": 38883,
                "build": 1371,
                "raster": 13297,
                "vsyncOverhead": 305
            },
            {
                "number": 57,
                "startTime": 121473245547,
                "elapsed": 40265,
                "build": 3984,
                "raster": 34260,
                "vsyncOverhead": 121
            },
            {
                "number": 59,
                "startTime": 121473262539,
                "elapsed": 38668,
                "build": 742,
                "raster": 14440,
                "vsyncOverhead": 436
            },
            {
                "number": 63,
                "startTime": 121473295610,
                "elapsed": 39776,
                "build": 457,
                "raster": 34347,
                "vsyncOverhead": 159
            },
            {
                "number": 65,
                "startTime": 121473313118,
                "elapsed": 40207,
                "build": 4782,
                "raster": 16923,
                "vsyncOverhead": 992
            },
            {
                "number": 69,
                "startTime": 121473346411,
                "elapsed": 43410,
                "build": 1049,
                "raster": 36403,
                "vsyncOverhead": 935
            },
            {
                "number": 71,
                "startTime": 121473362531,
                "elapsed": 40299,
                "build": 1337,
                "raster": 13415,
                "vsyncOverhead": 379
            },
            {
                "number": 75,
                "startTime": 121473395673,
                "elapsed": 42968,
                "build": 470,
                "raster": 35857,
                "vsyncOverhead": 171
            },
            {
                "number": 77,
                "startTime": 121473412352,
                "elapsed": 40751,
                "build": 901,
                "raster": 14305,
                "vsyncOverhead": 175
            },
            {
                "number": 81,
                "startTime": 121473445759,
                "elapsed": 42790,
                "build": 646,
                "raster": 34754,
                "vsyncOverhead": 232
            },
            {
                "number": 83,
                "startTime": 121473463053,
                "elapsed": 41712,
                "build": 460,
                "raster": 15443,
                "vsyncOverhead": 851
            },
            {
                "number": 87,
                "startTime": 121473495724,
                "elapsed": 24402,
                "build": 1585,
                "raster": 15800,
                "vsyncOverhead": 171
            },
            {
                "number": 89,
                "startTime": 121473512418,
                "elapsed": 42143,
                "build": 379,
                "raster": 34192,
                "vsyncOverhead": 191
            },
            {
                "number": 91,
                "startTime": 121473529183,
                "elapsed": 40598,
                "build": 528,
                "raster": 14911,
                "vsyncOverhead": 279
            },
            {
                "number": 95,
                "startTime": 121473562425,
                "elapsed": 40409,
                "build": 592,
                "raster": 33015,
                "vsyncOverhead": 173
            },
            {
                "number": 97,
                "startTime": 121473579535,
                "elapsed": 39190,
                "build": 4310,
                "raster": 15169,
                "vsyncOverhead": 607
            },
            {
                "number": 101,
                "startTime": 121473612515,
                "elapsed": 38163,
                "build": 1057,
                "raster": 31919,
                "vsyncOverhead": 238
            },
            {
                "number": 103,
                "startTime": 121473636313,
                "elapsed": 38252,
                "build": 1127,
                "raster": 16670,
                "vsyncOverhead": 7359
            },
            {
                "number": 107,
                "startTime": 121473662860,
                "elapsed": 39605,
                "build": 702,
                "raster": 34582,
                "vsyncOverhead": 557
            },
            {
                "number": 109,
                "startTime": 121473679212,
                "elapsed": 38718,
                "build": 1078,
                "raster": 15624,
                "vsyncOverhead": 233
            },
            {
                "number": 113,
                "startTime": 121473712659,
                "elapsed": 40935,
                "build": 800,
                "raster": 35454,
                "vsyncOverhead": 331
            },
            {
                "number": 115,
                "startTime": 121473729323,
                "elapsed": 37827,
                "build": 709,
                "raster": 13375,
                "vsyncOverhead": 319
            },
            {
                "number": 119,
                "startTime": 121473762743,
                "elapsed": 41326,
                "build": 2495,
                "raster": 36220,
                "vsyncOverhead": 390
            },
            {
                "number": 121,
                "startTime": 121473779988,
                "elapsed": 41078,
                "build": 498,
                "raster": 16207,
                "vsyncOverhead": 959
            },
            {
                "number": 125,
                "startTime": 121473812660,
                "elapsed": 41612,
                "build": 1201,
                "raster": 33546,
                "vsyncOverhead": 281
            },
            {
                "number": 127,
                "startTime": 121473829219,
                "elapsed": 40200,
                "build": 1177,
                "raster": 15101,
                "vsyncOverhead": 165
            },
            {
                "number": 131,
                "startTime": 121473862698,
                "elapsed": 22457,
                "build": 568,
                "raster": 15402,
                "vsyncOverhead": 294
            },
            {
                "number": 133,
                "startTime": 121473879298,
                "elapsed": 40881,
                "build": 497,
                "raster": 34982,
                "vsyncOverhead": 219
            },
            {
                "number": 135,
                "startTime": 121473895967,
                "elapsed": 40835,
                "build": 1144,
                "raster": 16378,
                "vsyncOverhead": 213
            },
            {
                "number": 139,
                "startTime": 121473929385,
                "elapsed": 42691,
                "build": 1154,
                "raster": 34563,
                "vsyncOverhead": 281
            },
            {
                "number": 141,
                "startTime": 121473946014,
                "elapsed": 41061,
                "build": 633,
                "raster": 14757,
                "vsyncOverhead": 235
            },
            {
                "number": 145,
                "startTime": 121473979342,
                "elapsed": 44131,
                "build": 504,
                "raster": 36177,
                "vsyncOverhead": 212
            },
            {
                "number": 147,
                "startTime": 121473996063,
                "elapsed": 40824,
                "build": 595,
                "raster": 13149,
                "vsyncOverhead": 258
            },
            {
                "number": 151,
                "startTime": 121474029309,
                "elapsed": 43921,
                "build": 501,
                "raster": 36321,
                "vsyncOverhead": 154
            },
            {
                "number": 153,
                "startTime": 121474046104,
                "elapsed": 40952,
                "build": 1498,
                "raster": 13549,
                "vsyncOverhead": 273
            },
            {
                "number": 157,
                "startTime": 121474079425,
                "elapsed": 40919,
                "build": 1592,
                "raster": 33158,
                "vsyncOverhead": 245
            },
            {
                "number": 159,
                "startTime": 121474096091,
                "elapsed": 40216,
                "build": 863,
                "raster": 15128,
                "vsyncOverhead": 236
            },
            {
                "number": 163,
                "startTime": 121474129460,
                "elapsed": 40737,
                "build": 599,
                "raster": 33710,
                "vsyncOverhead": 255
            },
            {
                "number": 165,
                "startTime": 121474146054,
                "elapsed": 40874,
                "build": 560,
                "raster": 16625,
                "vsyncOverhead": 174
            },
            {
                "number": 169,
                "startTime": 121474180170,
                "elapsed": 22995,
                "build": 999,
                "raster": 15345,
                "vsyncOverhead": 940
            },
            {
                "number": 171,
                "startTime": 121474196028,
                "elapsed": 40383,
                "build": 999,
                "raster": 33948,
                "vsyncOverhead": 123
            },
            {
                "number": 173,
                "startTime": 121474212958,
                "elapsed": 40653,
                "build": 822,
                "raster": 16823,
                "vsyncOverhead": 377
            },
            {
                "number": 177,
                "startTime": 121474246224,
                "elapsed": 40657,
                "build": 522,
                "raster": 33205,
                "vsyncOverhead": 293
            },
            {
                "number": 179,
                "startTime": 121474263584,
                "elapsed": 40016,
                "build": 689,
                "raster": 15272,
                "vsyncOverhead": 978
            },
            {
                "number": 183,
                "startTime": 121474296946,
                "elapsed": 40945,
                "build": 412,
                "raster": 33789,
                "vsyncOverhead": 990
            },
            {
                "number": 185,
                "startTime": 121474312963,
                "elapsed": 41617,
                "build": 1198,
                "raster": 17165,
                "vsyncOverhead": 330
            },
            {
                "number": 189,
                "startTime": 121474346314,
                "elapsed": 41574,
                "build": 1778,
                "raster": 33160,
                "vsyncOverhead": 333
            },
            {
                "number": 191,
                "startTime": 121474362908,
                "elapsed": 40142,
                "build": 563,
                "raster": 14937,
                "vsyncOverhead": 251
            },
            {
                "number": 195,
                "startTime": 121474396329,
                "elapsed": 42331,
                "build": 541,
                "raster": 35421,
                "vsyncOverhead": 322
            },
            {
                "number": 197,
                "startTime": 121474412954,
                "elapsed": 39098,
                "build": 690,
                "raster": 13247,
                "vsyncOverhead": 272
            },
            {
                "number": 201,
                "startTime": 121474446379,
                "elapsed": 39817,
                "build": 494,
                "raster": 33540,
                "vsyncOverhead": 347
            },
            {
                "number": 203,
                "startTime": 121474462974,
                "elapsed": 42470,
                "build": 1008,
                "raster": 18739,
                "vsyncOverhead": 267
            },
            {
                "number": 207,
                "startTime": 121474496208,
                "elapsed": 43135,
                "build": 994,
                "raster": 33897,
                "vsyncOverhead": 119
            },
            {
                "number": 209,
                "startTime": 121474513056,
                "elapsed": 41098,
                "build": 486,
                "raster": 14439,
                "vsyncOverhead": 323
            },
            {
                "number": 213,
                "startTime": 121474546331,
                "elapsed": 23506,
                "build": 514,
                "raster": 15580,
                "vsyncOverhead": 249
            },
            {
                "number": 215,
                "startTime": 121474563599,
                "elapsed": 41225,
                "build": 439,
                "raster": 34293,
                "vsyncOverhead": 808
            },
            {
                "number": 217,
                "startTime": 121474579681,
                "elapsed": 40682,
                "build": 1195,
                "raster": 15913,
                "vsyncOverhead": 249
            },
            {
                "number": 221,
                "startTime": 121474613030,
                "elapsed": 44137,
                "build": 1094,
                "raster": 36292,
                "vsyncOverhead": 247
            },
            {
                "number": 223,
                "startTime": 121474629655,
                "elapsed": 40319,
                "build": 683,
                "raster": 12199,
                "vsyncOverhead": 197
            },
            {
                "number": 227,
                "startTime": 121474663077,
                "elapsed": 41828,
                "build": 498,
                "raster": 34712,
                "vsyncOverhead": 269
            },
            {
                "number": 229,
                "startTime": 121474680378,
                "elapsed": 39635,
                "build": 1029,
                "raster": 14180,
                "vsyncOverhead": 895
            },
            {
                "number": 233,
                "startTime": 121474713089,
                "elapsed": 40232,
                "build": 1390,
                "raster": 33845,
                "vsyncOverhead": 256
            },
            {
                "number": 235,
                "startTime": 121474729681,
                "elapsed": 40279,
                "build": 634,
                "raster": 16544,
                "vsyncOverhead": 173
            },
            {
                "number": 239,
                "startTime": 121474763196,
                "elapsed": 41473,
                "build": 499,
                "raster": 34369,
                "vsyncOverhead": 337
            },
            {
                "number": 241,
                "startTime": 121474779786,
                "elapsed": 40401,
                "build": 621,
                "raster": 14856,
                "vsyncOverhead": 252
            },
            {
                "number": 245,
                "startTime": 121474813264,
                "elapsed": 42015,
                "build": 511,
                "raster": 34316,
                "vsyncOverhead": 380
            },
            {
                "number": 247,
                "startTime": 121474829889,
                "elapsed": 41725,
                "build": 1320,
                "raster": 16192,
                "vsyncOverhead": 330
            },
            {
                "number": 251,
                "startTime": 121474863169,
                "elapsed": 53051,
                "build": 1648,
                "raster": 44494,
                "vsyncOverhead": 260
            },
            {
                "number": 253,
                "startTime": 121474879859,
                "elapsed": 38804,
                "build": 490,
                "raster": 2337,
                "vsyncOverhead": 275
            },
            {
                "number": 257,
                "startTime": 121474929843,
                "elapsed": 24427,
                "build": 246,
                "raster": 23793,
                "vsyncOverhead": 234
            },
            {
                "number": 259,
                "startTime": 121474947376,
                "elapsed": 22250,
                "build": 782,
                "raster": 14420,
                "vsyncOverhead": 1089
            },
            {
                "number": 261,
                "startTime": 121474963276,
                "elapsed": 22000,
                "build": 848,
                "raster": 16321,
                "vsyncOverhead": 315
            },
            {
                "number": 263,
                "startTime": 121474979869,
                "elapsed": 40363,
                "build": 367,
                "raster": 34920,
                "vsyncOverhead": 235
            },
            {
                "number": 265,
                "startTime": 121474997341,
                "elapsed": 40113,
                "build": 857,
                "raster": 15674,
                "vsyncOverhead": 1031
            },
            {
                "number": 269,
                "startTime": 121475030576,
                "elapsed": 40786,
                "build": 396,
                "raster": 33914,
                "vsyncOverhead": 916
            },
            {
                "number": 271,
                "startTime": 121475046639,
                "elapsed": 41948,
                "build": 1501,
                "raster": 17664,
                "vsyncOverhead": 304
            },
            {
                "number": 275,
                "startTime": 121475079948,
                "elapsed": 42433,
                "build": 1912,
                "raster": 33602,
                "vsyncOverhead": 263
            },
            {
                "number": 277,
                "startTime": 121475096656,
                "elapsed": 40723,
                "build": 798,
                "raster": 14758,
                "vsyncOverhead": 295
            },
            {
                "number": 281,
                "startTime": 121475129972,
                "elapsed": 41433,
                "build": 523,
                "raster": 33901,
                "vsyncOverhead": 262
            },
            {
                "number": 283,
                "startTime": 121475146801,
                "elapsed": 41348,
                "build": 1424,
                "raster": 16373,
                "vsyncOverhead": 414
            },
            {
                "number": 287,
                "startTime": 121475180022,
                "elapsed": 41107,
                "build": 1258,
                "raster": 32403,
                "vsyncOverhead": 286
            },
            {
                "number": 289,
                "startTime": 121475196691,
                "elapsed": 41498,
                "build": 581,
                "raster": 16880,
                "vsyncOverhead": 280
            },
            {
                "number": 293,
                "startTime": 121475230231,
                "elapsed": 43731,
                "build": 409,
                "raster": 35310,
                "vsyncOverhead": 470
            },
            {
                "number": 295,
                "startTime": 121475246656,
                "elapsed": 40809,
                "build": 592,
                "raster": 13591,
                "vsyncOverhead": 220
            },
            {
                "number": 299,
                "startTime": 121475279994,
                "elapsed": 24790,
                "build": 522,
                "raster": 17148,
                "vsyncOverhead": 208
            },
            {
                "number": 301,
                "startTime": 121475296674,
                "elapsed": 40742,
                "build": 1202,
                "raster": 32476,
                "vsyncOverhead": 213
            },
            {
                "number": 303,
                "startTime": 121475313468,
                "elapsed": 40893,
                "build": 669,
                "raster": 16632,
                "vsyncOverhead": 332
            },
            {
                "number": 307,
                "startTime": 121475346681,
                "elapsed": 40353,
                "build": 413,
                "raster": 32220,
                "vsyncOverhead": 195
            },
            {
                "number": 309,
                "startTime": 121475363546,
                "elapsed": 41462,
                "build": 754,
                "raster": 17608,
                "vsyncOverhead": 383
            },
            {
                "number": 313,
                "startTime": 121475397593,
                "elapsed": 44080,
                "build": 408,
                "raster": 35713,
                "vsyncOverhead": 1081
            },
            {
                "number": 315,
                "startTime": 121475413451,
                "elapsed": 41219,
                "build": 1532,
                "raster": 13510,
                "vsyncOverhead": 264
            },
            {
                "number": 319,
                "startTime": 121475446831,
                "elapsed": 42247,
                "build": 1212,
                "raster": 34260,
                "vsyncOverhead": 294
            },
            {
                "number": 321,
                "startTime": 121475463449,
                "elapsed": 39514,
                "build": 566,
                "raster": 13757,
                "vsyncOverhead": 237
            },
            {
                "number": 325,
                "startTime": 121475496684,
                "elapsed": 41219,
                "build": 444,
                "raster": 34931,
                "vsyncOverhead": 122
            },
            {
                "number": 327,
                "startTime": 121475513966,
                "elapsed": 41057,
                "build": 730,
                "raster": 15689,
                "vsyncOverhead": 729
            },
            {
                "number": 331,
                "startTime": 121475546985,
                "elapsed": 39919,
                "build": 1163,
                "raster": 31729,
                "vsyncOverhead": 397
            },
            {
                "number": 333,
                "startTime": 121475563564,
                "elapsed": 40822,
                "build": 1209,
                "raster": 17330,
                "vsyncOverhead": 301
            },
            {
                "number": 337,
                "startTime": 121475596823,
                "elapsed": 44233,
                "build": 740,
                "raster": 36618,
                "vsyncOverhead": 210
            },
            {
                "number": 339,
                "startTime": 121475613687,
                "elapsed": 40529,
                "build": 894,
                "raster": 12815,
                "vsyncOverhead": 398
            },
            {
                "number": 343,
                "startTime": 121475646980,
                "elapsed": 40703,
                "build": 517,
                "raster": 33402,
                "vsyncOverhead": 342
            },
            {
                "number": 345,
                "startTime": 121475663556,
                "elapsed": 41208,
                "build": 1269,
                "raster": 16969,
                "vsyncOverhead": 242
            },
            {
                "number": 349,
                "startTime": 121475697038,
                "elapsed": 41333,
                "build": 1230,
                "raster": 32771,
                "vsyncOverhead": 375
            },
            {
                "number": 351,
                "startTime": 121475713747,
                "elapsed": 39948,
                "build": 639,
                "raster": 14585,
                "vsyncOverhead": 400
            },
            {
                "number": 355,
                "startTime": 121475747005,
                "elapsed": 23378,
                "build": 566,
                "raster": 16651,
                "vsyncOverhead": 316
            },
            {
                "number": 357,
                "startTime": 121475763589,
                "elapsed": 40347,
                "build": 942,
                "raster": 33526,
                "vsyncOverhead": 226
            },
            {
                "number": 359,
                "startTime": 121475780338,
                "elapsed": 39980,
                "build": 1610,
                "raster": 16178,
                "vsyncOverhead": 299
            }
        ],
        "displayRefreshRate": 60,
        "selectedEvent": {},
        "cpuProfile": {},
        "rasterStats": {},
        "rebuildCountModel": null
    },
    "traceEvents": []
}

```

</details>

### Video demonstration

<details>
<summary>Video demonstration</summary>

https://github.com/flutter/flutter/assets/29163975/01ce7b60-8df7-4272-b856-9698294b668b

</details>

### What target platforms are you seeing this bug on?

iOS

### OS/Browser name and version | Device information

iOS 16.7.2 on iPhone X

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

Yes

### Logs

<details><summary>Logs</summary>

```console

http://127.0.0.1:51701/XD9QZDxuJgo=/
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
The Flutter DevTools debugger and profiler on iPhone X (Narek) is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:51701/XD9QZDxuJgo=/

Launching Flutter DevTools for iPhone X (Narek) at
http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A51701%2FXD9QZDxuJgo%3D%2F


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale
    en-AM)
    • Flutter version 3.16.0 on channel stable at
      /Users/aram/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/aram/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • iPhone X (Narek) (mobile) • cb14d4938d2ea5a1bea218dddf44a7a99b8e5636 • ios
      • iOS 16.7.2 20H115
    • iPhone 15 Pro (mobile)    • 5CC0F196-5C29-4E85-B516-F723CB9953B5     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)           • macos                                    •
      darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ArAmM7** [comment]
issue is also reproducible on iPhone 13 Pro, but is not reproducible on iPhone 8 and iPhone 11

**Comment by mark8044** [comment]
Agreed, jank has made my app unusable in 3.16.0.  I blame impeller personally

**Comment by mark8044** [comment]
> This was likely fixed in [flutter/engine#47808](https://github.com/flutter/engine/pull/47808) . I will file a cherry pick request to see if we can get this into 3.16

@jonahwilliams 
The fix (by using master channel) makes the app very very smooth again.

However, when scrolling a view with a lot of images (or videos) the screen will weirdly just freeze (or rapidly move up and down by a few pixels) and spit out alot of these errors:
```
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
```

I won't be able to file an issue because my code is far to massive to create a test case out of.  But this an FYI-- that if this new problem is at all related to the fix, it wouldn't be production ready.  Hopefully its something else.  But this problem is only occurring on master branch, and not with 3.16.

But it is FAST

**Comment by jonahwilliams** [comment]
Unfortunately we don't have any other reports of the issue, nor do any of our benchmarks or test apps show that problem. So I would really appreciate a minimal reproduction if you're able to find it.

If it consistently reproduces with your test app, you might want to look more closely at the logs. Usually the message you have posted only occurs after the real error message has been printed out once. That would tell me what the problem actually is.

**Comment by mark8044** [comment]
@jonahwilliams 

Its very consistent.  
Its occurring when there are ALOT of Network images (>30).  If there are only say 10-20 images then things are OK.
Only happening on master branch and not 3.16.0

I don't get any errors per se before those lines spit out, but I do get this:
```
[Security] This method should not be called on the main thread as it may lead to UI unresponsiveness.
```

Im displaying the images in a listview translated by https://pub.dev/packages/flutter_widget_from_html_core.  The images themselves are presented by CachedNetworkImage

**Comment by jonahwilliams** [comment]
That warning message doesn't have anything to do with the GPU error.

**Comment by mark8044** [comment]
> That warning message doesn't have anything to do with the GPU error.

@jonahwilliams 
Well I certainly love the return of the speed (3.16 is just atrocious).  I guess cherry pick is a good idea and then see if the problem is related, unrelated or if anyone else is having the problem and go from there

**Comment by jonahwilliams** [comment]
No, we definitely can't cherrypick a change if its causing GPU performance issues

**Comment by jonahwilliams** [comment]
Its possible that this is related to this bug here: https://github.com/flutter/flutter/issues/138373

I have a fix pending https://github.com/flutter/engine/pull/48190 , I can post here when it is rolled into the framework and you could try again. In the meantime, a minimal repro would be super helpful

**Comment by jonahwilliams** [comment]
@mark8044 try adding the following line to your Info.plist (on 3.16):

```
<key>FLTEnableWideGamut</key>
<false/>
```

**Comment by mark8044** [comment]
> @mark8044 try adding the following line to your Info.plist (on 3.16):
> 
> ```
> <key>FLTEnableWideGamut</key>
> <false/>
> ```

Ok doing it now, this is to tackle the speed or the GPU crashes?

In regards to GPU issue:
FYI, I moved up to .48 (from .45) just now and the problem is still there.  It only happens on the real device.  iOS simulator is ok

**Comment by jonahwilliams** [comment]
This is a change for stable channel that may improve performance without fixes from master channel.

**Comment by mark8044** [comment]
> This is a change for stable channel that may improve performance without fixes from master channel.

Ok can confirm the app is back to regular FAST speed using the wide gamut.   And NO crashes.

Also, came across some weird image blurring happening only on certain images (the same exact images that causing the GPU crash on master).  Going to research to see what if any link there is.   Going to also try downgrading (if that's even a thing) through the master branch and see if the change can be isolated

Going to

**Comment by jonahwilliams** [comment]
The change I linked _turns off_ wide gamut FWIW. Please let me know what you find.

**Comment by mark8044** [comment]
> The change I linked _turns off_ wide gamut FWIW. Please let me know what you find.

Got it.   

I'm about 15 minutes into straight testing without any crash or jank.  Its VERY FAST (faster then 3.13 I believe).  IMO this fix should get pushed out quicker, because 3.16.0 is kind of embarrassing in terms of jank.    Thanks for the fix!

Now moving onto the idea of stepping backwards through master channel and see if anything can be discovered.  Will let you know.

**Comment by jonahwilliams** [comment]
@mark8044 does your app have platform views in the part that is janky with the blurs?

**Comment by mark8044** [comment]
@jonahwilliams 

The whole app was very janky, everywhere.  However, it is especially so where there was a YouTube video (I think it might  use platform views, but not sure:  youtube_player_iframe 2.2.2)

On a brighter note, here's what Ive come up with in regards to the GPU crash issue:
OK [3.17.0-4.0.pre](https://github.com/flutter/flutter/releases/tag/3.17.0-4.0.pre)
CRASH --> [3.17.0-8.0.pre](https://github.com/flutter/flutter/releases/tag/3.17.0-8.0.pre)

So the problem is somewhere in between there....  Hope that narrows it down somewhat.Sorry I could drill into more specific builds then those versions, I only know how to downgrade between those tag versions by doing git checkout

**Comment by jonahwilliams** [comment]
@mark8044 can you link the commit hashes instead of the versions?

**Comment by jonahwilliams** [comment]
if you do `flutter doctor -v` that will give you the actual commits

**Comment by mark8044** [comment]
Is this what you are looking for?


GOOD
```
Flutter 3.17.0-4.0.pre • channel [user-branch] • unknown source
Framework • revision ca384b84e5 (10 days ago) • 2023-11-08 06:14:09 +0100
Engine • revision 3e3be5e33b
```

BAD
```
Flutter 3.17.0-8.0.pre • channel [user-branch] • unknown source
Framework • revision 6e9d4ccc25 (4 days ago) • 2023-11-13 21:46:14 -0500
Engine • revision d100e8912e
```

**Comment by jonahwilliams** [comment]
Perfect, thanks!

**Comment by mark8044** [comment]
BTW, If you know a way I can downgrade to specific builds then I'm happy to do it and walk through them, the only way I could find was to do a git checkout which only allows me to do it for the tagged version named such as `3.17.0-8.0.pre` not `3.17.0-8.0.pre.XX`

**Comment by jonahwilliams** [comment]
You can plug the commit into this URL to get a listing of commits that happened before it: https://github.com/flutter/flutter/commits/master?after=6e9d4ccc250dd56ad967de221258d2b8eeffe8e3+69&branch=master&qualified_name=refs%2Fheads%2Fmaster

Then use `git checkout` with the commit hash

**Comment by mark8044** [comment]
> You can plug the commit into this URL to get a listing of commits that happened before it: https://github.com/flutter/flutter/commits/master?after=6e9d4ccc250dd56ad967de221258d2b8eeffe8e3+69&branch=master&qualified_name=refs%2Fheads%2Fmaster
> 
> Then use `git checkout` with the commit hash

Ok going to try this now, Im starting off from the link you posted up.  Just to be more efficient, I should be jumping between the hashes for `[Roll Flutter Engine]` right?  that's where the change would likely be?

**Comment by jonahwilliams** [comment]
Yes that is the most likely candidate

**Comment by mark8044** [comment]
> Yes that is the most likely candidate

Really wish my computer was faster right about now LOL.  I will get back to you if I can get to a specific hash causing a problem

**Comment by jonahwilliams** [comment]
I'm willing to bet that it is actually https://github.com/flutter/engine/pull/47808 causing the issue, and we need an additional fix to make that safe to cherry pick

**Comment by mark8044** [comment]
> I'm willing to bet that it is actually [flutter/engine#47808](https://github.com/flutter/engine/pull/47808) causing the issue, and we need an additional fix to make that safe to cherry pick

Ok CONFIRMED.  You are right, build `8b2e5b30a7a1b20b634716bfbf471eb5cddfd66b` is the problem

**Comment by jointhejourney** [comment]
I can confirm the same problem on my iPhone 14 Pro, in addition to our app making the phone overheat quite a bit.

Upgrading to `master` does solve the problem, and the overheating has improved as well (although I'm not 100% sure it has to do with this issue specifically). I'll run a few more tests on master to confirm.

We do use a lot of platform views, though.

**Comment by mark8044** [comment]
@jonahwilliams 
Ok just a small update, and I think you already know this as you alluded to it:  the GPU error/crash is happening anytime I have even a single web view (used to display a YouTube video) on screen.  The web view is  https://pub.dev/packages/webview_flutter which I believe is using a platform view (WkWebview).   So platform views are the actual conflict point.

**Comment by jonahwilliams** [comment]
The fix for the crash is https://github.com/flutter/engine/pull/48190  or opting out of wide gamut.

**Comment by mark8044** [comment]
> The fix for the crash is [flutter/engine#48190](https://github.com/flutter/engine/pull/48190) or opting out of wide gamut.

Much appreciated, looking forward to it making into master 👍

**Comment by jonahwilliams** [comment]
Its possible that https://github.com/flutter/flutter/issues/138656 is the cause of the Jank. Still need to investigate when this regressed.

**Comment by mark8044** [comment]
@jonahwilliams 
That makes sense as the jank I'm seeing is primarily when there is a platform view sitting in a listview with a backdrop filter overlaid or closely adjacent.

Personally I think its a combination of the now fixed issue we talked about as well as something along the lines of https://github.com/flutter/flutter/issues/138656

**Comment by ArAmM7** [comment]
I tested on master, 97ab92ee353e2b8bc60834a2e0756cba69922c38 seems to be fine, stable 60 fps.

The beta 3.19.0 on b7e7d46a046ba8a22897a514bf2311a0f81ab198 still has the issue.

**Comment by jonahwilliams** [comment]
Beta 3.20 includes the new blur implemented by @gaaclarke which should be much faster. Please try it out and let us know if it works for you.

**Comment by RicoLiu** [comment]
Same issue, any updates?

**Comment by ArAmM7** [comment]
> Beta 3.20 includes the new blur implemented by @gaaclarke which should be much faster. Please try it out and let us know if it works for you.

I can confirm that the current beta has good performance, but I see some kind of weird visuals on the blur when scrolling.


https://github.com/flutter/flutter/assets/29163975/451ed55c-7e2e-44a9-b0a2-808da48a040a

**Comment by gaaclarke** [comment]
@ArAmM7 can you try on the main channel?  That should have been resolved now.  If you are still noticing a problem can you please provide reproduction code in a new issue and tag me?  The new blur has some numbers that we can tweak to eliminate these kinds of artifacts.  I hope they are eliminated on the main channel.

**Comment by ArAmM7** [comment]
I tried on master b48ae31487 still seeing it. Created a [new issue](https://github.com/flutter/flutter/issues/143947) for it specifically.

**Comment by jonahwilliams** [comment]
We think this has been fixed with the new blur implementation, which will be available in the next stable release. Closing!
