### ISSUE TITLE
[Impeller] Visual glitches on iOS simulator when using Impeller rendering engine.

### ISSUE THREAD

**Issue by ksokolovskyi** [flutter/flutter#140877]
I encountered visual glitches while developing a prototype using Flutter.

The glitches appear on the iOS simulator when using the Impeller rendering engine.

It seems like the cause of those glitches is the usage of the `BackdropFilter` widgets in the `Stack`.

### Expected results

No visual glitches.

### Actual results

There are visual glitches.

### Code sample

The source code to reproduce the issue can be found in this repository: https://github.com/ksokolovskyi/dirty_button

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

When running with the Impeller rendering engine:

https://github.com/flutter/flutter/assets/30288967/71445257-909f-442b-9497-b2e022b2ab10

When running with `--no-enable-impller` there are no glitches:

https://github.com/flutter/flutter/assets/30288967/96fa924b-558b-4238-adb6-afd1497394aa

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1 23B2073 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this on latest master and stable:


https://github.com/flutter/flutter/assets/67046386/9cbda0db-b0f3-4c6e-8ccc-5798e6aa56f8


Probably this is similar / related to  https://github.com/flutter/flutter/issues/140193 but in the linked issue, the blur seems to be occuring while scrolling. Will keep this issue open for team's input or whether we can close this in favor of the linked one.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (13 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.18.0-18.0.pre.101, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.18.0-18.0.pre.101 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 451d3c8d18 (29 minutes ago), 2024-01-03 23:43:22 -0500
    • Engine revision 1ff3cb8858
    • Dart version 3.3.0 (build 3.3.0-276.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by ksokolovskyi** [comment]
@darshankawar thanks!

**Comment by jason-simmons** [comment]
This started with the change to using coverage hints based on the clip stack (https://github.com/flutter/engine/commit/75c60e6983071af07a980260a90ce33a4d78f45e)

The app is rendering a list of images with a backdrop filter and an advanced blend.  This is then wrapped in a clip and a scale transform.

As an experiment I could get this to render correctly by adding an `->Expand(200)` to the output of `current_clip_coverage->Intersection(coverage.value())` when computing the new clip in `ClipContents::GetClipCoverage`.

Possibly some transform or other adjustment needs to be applied in the clip coverage stack?

@bdero

**Comment by jonahwilliams** [comment]
@bdero unassigning since I don't think you are working on this right now.

**Comment by jonahwilliams** [comment]
I cannot reproduce this problem at ToT. Its possible that we already fixed this when we fixed the other partial repaint issues

**Comment by ksokolovskyi** [comment]
@jonahwilliams thanks for checking this issue!
I tried again on the latest master and it is still reproducible, see the attached video.

https://github.com/flutter/flutter/assets/30288967/ea03869b-4f44-477e-9e38-24ecf8a54a66

**Comment by jonahwilliams** [comment]
Hmm, you're right that I can still reproduce this on Simulators - but its not happening on a physical iOS device. Confusing!

**Comment by ksokolovskyi** [comment]
@jonahwilliams, I tried on the physical iOS device and confirm there are no such visual artifacts  🤔

**Comment by jonahwilliams** [comment]
Is the button designed to behave differently on Simulator vs real device?

**Comment by ksokolovskyi** [comment]
@jonahwilliams, nope, the difference is not an expected behavior

**Comment by chinmaygarde** [comment]
This is on the slimpeller blockers list for issues on-device. The issue title makes it seem like this happens on the simulators only. But, as I understand, this should occur on device as well. Is that right? Can we clarify the title?

**Comment by jonahwilliams** [comment]
This is already fixed. The cherry pick is still waiting though.

**Comment by gaaclarke** [comment]
I think we can close this out, it's fixed.  There is no linked cherry pick and any talk of cherry-picking in June is probably outdated for the end of Sept.  Feel free to reopen if I'm mistaken.

**Comment by jonahwilliams** [comment]
This one actually isn't fixed on Simulators, it is fixed on devices though. I've looked at this a few times and haven't been able to figure it out.

**Comment by jonahwilliams** [comment]
I should have added a comment to that effect the last time I tried it.
