### ISSUE TITLE
Web app with multiple platform views overlayed with Flutter widgets failing on Firefox

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#140981]
### Steps to reproduce

1. Clone and access https://github.com/dart-lang/dart-pad/tree/main/pkgs/sketch_pad
2. Run on Firefox with CanvasKit with a recent build on `main` (3.18.0-19.0.pre.64).
3. Some of the site loads, but other portions fail, and will continue to do so on interacting with menu elements.

### Expected results

Site renders fine without errors.

### Actual results

Failures during canvas kit initialization on production deployment with:

```
Uncaught : RuntimeError: indirect call signature mismatch
    CanvasKitInit https://www.gstatic.com/flutter-canvaskit/9e03a57cde8ae8d1811492653a4ca930986f53e3/canvaskit.js:115
    concat https://www.gstatic.com/flutter-canvaskit/9e03a57cde8ae8d1811492653a4ca930986f53e3/canvaskit.js:44
    a3 https://preview.dartpad.dev/main.dart.js:29371
    fT https://preview.dartpad.dev/main.dart.js:29215
```

and

```
Uncaught : Bad state: PictureRecorder is not recording
    c https://preview.dartpad.dev/main.dart.js:5022
    pX https://preview.dartpad.dev/main.dart.js:29601
    vU https://preview.dartpad.dev/main.dart.js:28617
    s https://preview.dartpad.dev/main.dart.js:6374
    $2 https://preview.dartpad.dev/main.dart.js:41380
    Q https://preview.dartpad.dev/main.dart.js:6360
```

During development:

```
Uncaught (in promise) Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/canvaskit/embedded_views.dart:574:12
_overlays.length == viewsNeedingOverlays.length
is not true
    DartError dart_sdk.js:14006
    throw_ errors.dart:297
    assertFailed errors.dart:38
    _updateOverlays embedded_views.dart:574
    submitFrame embedded_views.dart:356
    runBody async_patch.dart:84
    _async async_patch.dart:127
    submitFrame embedded_views.dart:351
```

### Code sample

Code is at https://github.com/dart-lang/dart-pad/tree/main/pkgs/sketch_pad or you can access a live deployed version at:

https://preview.dartpad.dev/

### Flutter version

```console
Flutter 3.18.0-19.0.pre.64 • channel main • https://github.com/flutter/flutter
Framework • revision 49edbc7491 (3 hours ago) • 2024-01-04 10:26:48 -0800
Engine • revision b81023eb71
Tools • Dart 3.3.0 (build 3.3.0-279.0.dev) • DevTools 2.31.0
```

**Comment by parlough** [comment]
\cc @harryterkelsen The issue DartPad is hitting on recent main builds for reference.

Might not be relevant if you're reverting to the old rendering method, but if there's a goal to switch back eventually, some handling might need to be adjusted?

**Comment by yjbanov** [comment]
Under the assumption that this is what also caused https://bugzilla.mozilla.org/show_bug.cgi?id=1875238, I'm making it a P0. @harryterkelsen is looking into it.

**Comment by harryterkelsen** [comment]
I'm unable to repro the issue with a current engine build. Let me see if I can repro with the old build mentioned in the OP to confirm that it was fixed with the Firefox reverting to multisurface PR

**Comment by parlough** [comment]
It's still occurring on the deployed version of SkethPad, but I'm not sure what build of the engine that's built with.

I'll try with the latest engine locally.

**Comment by harryterkelsen** [comment]
I am able to consistently repro the crash with the old build

**Comment by parlough** [comment]
Yeah it seems like your change fixed it then, thank you!

I just tried on https://github.com/flutter/engine/commit/f2b441a264 (staged at https://parlough-dart-dev.web.app) and it seems to be working without error! Just a few WebGL warnings and deprecations.

Perhaps there still is an issue to fix though? Assuming you want to ever return Firefox to the new strategy. I'm not sure if that's with Flutter or Firefox though.

**Comment by harryterkelsen** [comment]
It's an issue with Firefox. Their implementation of `transferToImageBitmap`/`createImageBitmap` is slow (and apparently can also cause strange crashes?). Mozilla is aware of the issue and is working on it. We should be able to get all browsers back to single-GL-context rendering once the issue is fixed on the browser side.

**Comment by yjbanov** [comment]
Downgrading to P1 as a workaround has been implemented. It's still a P1 to make sure we actively track the fix on the Firefox side, so we can remove the workaround.

**Comment by yjbanov** [comment]
The Mozilla issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1788206
