### ISSUE TITLE
Flutter on iOS always chooses English for localization, even if the system's preferred language is not english

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#14128]
## Steps to Reproduce

I have two languages set up on iOS and Android:
* German
* English

German is the preferred language of the system, meaning the OS and most apps appear in German.

I created an app that has translations for both English and German:
```
    return new MaterialApp(
      localizationsDelegates: <LocalizationsDelegate<dynamic>>[
        new _MyLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('de', 'DE'), // German
        const Locale('en', 'US'), // English
      ],
      title: "MyApp",
      home: new Home(),
    );
```
```
class _MyLocalizationsDelegate extends LocalizationsDelegate<MyStrings> {
  @override
  Future<MyStrings> load(Locale locale) => MyStrings.load(locale);

  @override
  bool shouldReload(_MyLocalizationsDelegate old) => false;
  @override
  bool isSupported(Locale locale) =>
      locale.languageCode == 'en' ||
      locale.languageCode == 'de';
}
```

On Android, this app appears in German. On iOS, it appears in English.
The only way to force the app to appear in German is to remove English as a secondary language of the system.

Is this a bug? Am I missing something?

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel alpha-chq)
    • Flutter at /Users/philipp/code/flutter
    • Framework revision 0bd83f8c34 (12 days ago), 2018-01-04 18:01:44 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Android NDK at /Users/philipp/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0.beta.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.4
    • Dart plugin version 172.4343.25

**Comment by realcarlos** [comment]
Yes ,same problem! Localization in Flutter is so unuseful now.

**Comment by MarkOSullivan94** [comment]
@realcarlos have you tested with any other languages apart from German and English?

**Comment by jerzykiler** [comment]
This is probably because of this:

> [NSLocale currentLocale] is based on the device's Region Format settings, not the language. If the region is set to United States you will get en_US regardless of which language you're using.

from
https://stackoverflow.com/questions/1522210/nslocale-currentlocale-always-returns-en-us-not-users-current-language

Any advices on how to get the preferred language ?

**Comment by pakivika** [comment]
👍

**Comment by reni99** [comment]
(Y)

**Comment by reni99** [comment]
👍

**Comment by pakivika** [comment]
I have four translations available in my app but Flutter always picks English regardless of device language.

**Comment by reni99** [comment]
I guess this is fixed. I am using Flutter 0.1.1, channel dev

**Comment by rcpassos** [comment]
Yes, I have this problem too, but only doesn't work on iOS, on android is working ok.

**Comment by bartwaggoner** [comment]
We have this problem, too. We are using Platform.localeName and it works for android, but always returns "en_US" for iOS.  This issue could hold up the release of our product!

**Comment by bartwaggoner** [comment]
Note we also tried Localizations.localeOf(context) and it also returned "en_US" for iOS.

**Comment by pakivika** [comment]
How could we get this one prioritised? This is the only bug in addition to https://github.com/flutter/flutter/issues/11648 that blocks me from releasing my app.

**Comment by chinmaygarde** [comment]
cc @cbracken

**Comment by bartwaggoner** [comment]
pakivika - we considered adding a language option to the app's settings dialog: perhaps that is something you could do short term in order to release?

**Comment by zanderso** [comment]
It looks like the view controller's `onLocaleUpdated` ([here](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L773)) is correctly wired up to set Window._locale (via [the engine](https://github.com/flutter/engine/blob/master/shell/common/engine.cc#L309) -> [the runtime controller](https://github.com/flutter/engine/blob/master/runtime/runtime_controller.cc#L115) -> [the window](https://github.com/flutter/engine/blob/master/lib/ui/window/window.cc#L157) -> [dart:ui](https://github.com/flutter/engine/blob/master/lib/ui/hooks.dart#L48)). Wiring up `Window._locale` to `Platform.localeName` is the same code as on Android so that probably works. This could be failing on iOS if the `onLocaleUpdated` callback isn't getting called for some reason, and then the default is 'en_US'.

**Comment by alan-knight** [comment]
Removing the flutter-specific locale code in the VM and letting it fall back to the VM version seems to produce correct results for me on iOS. It gives me a language based on my iOS language preference, and a country based on my region. Which can lead to not very helpful locales like 'fr-US', but given what I told the OS that seems reasonable.

**Comment by cbracken** [comment]
@alan-knight if you were able to repro this, can I get detailed repro instructions? Specifically:
1. Was this a physical device, simulator, or both?
2. In Settings > General > Language & Region, what are your values for:
    a. iPhone Language
    b. Preferred Language Order
    c. Region
3. In Xcode, select the Runner project, then click on the left-hand-side of the dropdown to the right of the Run/Stop buttons (on 'Runner'), select Edit Scheme..., select 'Run' in the left column, and select the 'Options' tab. Can you verify that 'Application Language' and 'Application Region' set to 'System Language' and 'System Region'?

I've seen a few reports relating to the 3rd item above, so worth verifying there's no override in your project config.

**Comment by alan-knight** [comment]
1. Simulator

2 a. Francais
   b. Francais
       Espanol
   c. France

3. Yes, they are set to System Language and System Region.

**Comment by miguelpruivo** [comment]
Same problem here. I have PT and EN and it picks EN on iOS despite the device being in PT. On Android works fine tho.

**Comment by gustav77** [comment]
Same problem here. Does not work neither on the real device nor in the simulator.

**Comment by gerryhigh** [comment]
See also [#17933](https://github.com/flutter/flutter/issues/17933)

**Comment by Sonius94** [comment]
Solution:
You can just add Localizations if you have a mac and XCode installed. You have to open the flutter iOS part in xcode. Click on your project in the file list. There you habe to click on the Info tab. One Section will be "Localizations". There you have to add the languages you want to have in your project as well so that the iOS part can return the expected language as well.

**Comment by Hixie** [comment]
We should definitely update the API docs and the Web site to mention this.

**Comment by tvolkert** [comment]
If I'm reading this correctly, it sounds like the bundled app metadata needs to export the list of locales that it supports in order for iOS to know which locale to request of the app -- and currently, Flutter apps only know which locales they support by virtue of the code in the app itself (not any app metadata in the `pubspec.yaml`or such).

@cbracken (current assignee): (a) are you working on this? (b) does that assessment sound right?

**Comment by cbracken** [comment]
@tvolkert yes, we just updated this at yesterday's triage. The plan is just to document for the time being.

**Comment by tvolkert** [comment]
Thanks @cbracken

@robertoscaramuzzi within a Bazel environment, I initially thought this may be specified in the [`ios_application`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application) rule, but it looks like you may just need to update your `Info.plist` and specify the appropriate `CFBundleLocalizations` values:

```xml
  <key>CFBundleLocalizations</key>
  <array>
    <string>en</string>
  </array>
```

**Comment by tiagosito** [comment]
I followed in the steps of @Sonius94 and @tvolkert and worked wonderfully... but I skipped a few steps and did not even have to open xCode

**See how simple it is**

just open the Info.plist file that should be on this path:  ```_your_project/ios/Runner/Info.plist_```
edit the file, putting this as an example, in your case put the languages you want to support
**and be happy**
```
  <key>CFBundleLocalizations</key>
  <array>
    <string>English</string>
    <string>pt</string>
    <string>es</string>
    <string>ja</string>
  </array>
```

**The file should look pretty much like this**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleLocalizations</key>
  <array>
    <string>English</string>
    <string>pt</string>
    <string>es</string>
    <string>ja</string>
  </array>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
.
.
.
other lines
```

**Comment by tiagosito** [comment]
Should this problem be closed? @Hixie

**Comment by miguelpruivo** [comment]
@Sonius94 solution worked for me. However I believe that the docs should include a reference for this.

**Comment by tiagosito** [comment]
@miguelpruivo ops ... this really should be done urgently, thanks for reminding me of that point

**Comment by gerryhigh** [comment]
FYI - this is still not documented on the flutter website (e.g. https://flutter.io/tutorials/internationalization/ ). My developer was testing on iOS today and I had to google to find the answer here. /cc @eseidelGoogle

**Comment by cbracken** [comment]
@gerryhigh this is on our radar and scheduled for our next release cycle. We keep an eye on thumbs-ups as one of several metrics we use to prioritise, so I’d definitely encourage you to upvote issues that affect you.

**Comment by aubykhan** [comment]
@Sonius94 you saved the day for many! Thanks!!!

**Comment by opensourcegps** [comment]
To add to the docs, in case you want your languages listed in iTunes (Store Information), you need to add Base Localization languages in Project info, Localizations section.

![untitled](https://user-images.githubusercontent.com/7678445/44081910-343aa250-9fb0-11e8-9a14-324bf5b86ef8.png)

**Comment by cbracken** [comment]
Fixed by flutter/website#1247.

**Comment by danielaRiesgo** [comment]
I have the Localizations in the Info.plist and the Scheme set to System Language and Region. But, running in the simulator, I still get en_US in flutter code when the Language is es_AR. It even works inside iOS, because I got the app name localized in the InfoPlist.strings and it's taking the correct spanish name.
Can anyone help me?

**Comment by XYliang** [comment]
you should setting in xcode. select path : Runner - info- localizations . then add your support language in  form list.

**Comment by psyanite** [comment]
I had to do 3 things.
1. Set new language as phone language, remove English from preferred language order list
2. Update Info.plist accordingly
3. Update Runner -> Localizations

**Comment by danielaRiesgo** [comment]
I already did that, but it's not working for me. I did use Base internalization, may that be relevant?

**Comment by eseidelGoogle** [comment]
Unclear if we need to re-open this issue?  (@xster might know.)

**Comment by xster** [comment]
@danielaRiesgo could you open a [new bug](https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md) with the steps you tried to follow?

It could help us figure out if our documentation at https://flutter.dev/docs/development/accessibility-and-localization/internationalization needs to be extended.

**Comment by danielaRiesgo** [comment]
Hi all ! I found the problem, it was our Flutter code.
At the `LangLocalizationsDelegate` class, `localeResolutionCallback` function, we did:

**Comment by Wojak27** [comment]
> To add to the docs, in case you want your languages listed in iTunes (Store Information), you need to add Base Localization languages in Project info, Localizations section.
> 
> ![untitled](https://user-images.githubusercontent.com/7678445/44081910-343aa250-9fb0-11e8-9a14-324bf5b86ef8.png)

You've saved my project mate

**Comment by Xgamefactory** [comment]
that gives build error

Runner/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

**Comment by joaowd** [comment]
To fix this open Runner.xcworkspace, select Runner Project and in the Info tab add the Localizations that you want to support.

**Comment by franskjv** [comment]
Hi, I made all the steps from editing info.plist to info in Xcode, but still not working in iOS. I'm using the package flutter_i18n and it works fine on Android. Any help?

info:
<img width="856" alt="Screen Shot 2019-12-29 at 11 02 13" src="https://user-images.githubusercontent.com/4266955/71557875-f4117800-2a2a-11ea-9bc6-e1bc9aff9e23.png">

info.plist:
<img width="875" alt="Screen Shot 2019-12-29 at 11 02 24" src="https://user-images.githubusercontent.com/4266955/71557879-08ee0b80-2a2b-11ea-8653-c77e5855ecd1.png">

Doctor:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-BR)
    • Flutter version 1.12.13+hotfix.5 at /Users/franklin/Development/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/franklin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone do Franklin • 8ca28e9db21289c970d810c3625aa017... • ios • iOS 13.3
    • iPhone 11 Pro Max  • 29823942-BC97-4196-B74D-A03C680F1...     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

Thanks.

**Comment by ale-getman** [comment]
Hi, the package easy_localization also always has the result in English.
On the device I changed languages and regions. He left only one language, without English, still nothing helps.

**Comment by Jbz797** [comment]
Same here

**Comment by HartP97** [comment]
Is there an official way to fix the issue? I'm using version `intl_translation 0.17.9` and here in this thread, I was only able to find workarounds so far, nothing official or with documentation on how to fix it.

**Comment by HartP97** [comment]
I found the official fix in the flutter docs: https://flutter.dev/docs/development/accessibility-and-localization/internationalization
In the very bottom under the topic **Appendix: Updating the iOS app bundle**
(**Hint**: When you open it up in Xcode, by default in the left menu "Target", the Runner file with Flutter Logo is selected, you have to select the Runner file with Xcode Logo above it with the menu heading "Project" to add a new language)

**Comment by Edeph** [comment]
> To fix this open Runner.xcworkspace, select Runner Project and in the Info tab add the Localizations that you want to support.

This seems to be very important step that I barely see mentioned. It made the app work for me both in the simulator and the phone with english still available in the settings as one of the languages.

**Comment by kadenchoi** [comment]
Finally find the solution!!!
Two things need to be added in plist.info
1. Localizations ( add your included languages )
2. Localized resources can be mixed - YES

**Comment by Overman775** [comment]
Work fine, just add locale and set Yes in project(upper message)... but new bug

```
[log] easy localization: Device locale ru_US ---Bug---Country Code 
[log] easy localization: Set locale ru
[MyApp# locale] ru
[MyApp# Intl.defaultLocale] ru
[_MyHomePageState#32c97] Привет!
```
