### ISSUE TITLE
[iOS] App is crashing in production `flutter::ImageDecoderImpeller::UploadTextureToStorage`

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#141554]
### Steps to reproduce

no idea, found in Sentry

### Expected results

no crash

### Actual results

crash
![grafik](https://github.com/flutter/flutter/assets/16635729/bb88df50-da15-4aae-856c-cca1fff49714)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3930], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @escamoteur 
Please provide the stack trace in text format instead of a screenshot for better readability and investigation. 

Also, please provide the list of affected device info (OS, model) along with the percentage occurrence of the crash. Thanks!

**Comment by escamoteur** [comment]
I can add it as text additionally but the screenshot contains more information from sentry
Am 15. Jan. 2024, 12:56 +0100 schrieb huycozy ***@***.***>:

**Comment by huycozy** [comment]
Please also share it in text format, it will be easier to copy and search for information.

**Comment by escamoteur** [comment]
´´´console
Crashed in non-app
AGXMetalG16P_B0
+0x475a10
AGX::Texture<T>::processCompressedRegion2D<T>
Flutter
+0x563da0
impeller::TextureMTL::OnSetContents (texture_mtl.mm:84)
In App
Flutter
+0x35abe4
impeller::Texture::SetContents (texture.cc:41)
In App
Flutter
+0x59bd10
flutter::ImageDecoderImpeller::UploadTextureToStorage (image_decoder_impeller.cc:428)
In App
Flutter
+0x59b3e4
const::lambda::operator() (image_decoder_impeller.cc:532)
In App
Called from
Flutter
+0x59b3e4
std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<T> (invoke.h:403)
Flutter
+0x2e5d64
fml::MessageLoopImpl::FlushTasks (message_loop_impl.cc:126)
In App
Flutter
+0x2e94f8
fml::MessageLoopImpl::RunExpiredTasksNow (message_loop_impl.cc:139)
In App
Flutter
+0x2e94f8
fml::MessageLoopDarwin::OnTimerFire (message_loop_darwin.mm:85)
In App
Called from
CoreFoundation
+0x0ad3e8
__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Flutter
+0x2e95e4
fml::MessageLoopDarwin::Run (message_loop_darwin.mm:51)
In App
Flutter
+0x2e8c58
fml::MessageLoopImpl::DoRun (message_loop_impl.cc:94)
In App
Flutter
+0x2e8c58
fml::MessageLoop::Run (message_loop.cc:49)
In App
Flutter
+0x2e8c58
fml::Thread::Thread::lambda::operator() (thread.cc:85)
In App
Called from
Flutter
+0x2e8c58
std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<T> (invoke.h:403)
Flutter
+0x2e8c58
std::_LIBCPP_ABI_NAMESPACE::__thread_execute[abi:v15000]<T> (thread:284)
Flutter
+0x2e8c58
std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<T> (thread:295)
libsystem_pthread
+0x0024d0
_pthread_start 
´´´´

**Comment by escamoteur** [comment]
![grafik](https://github.com/flutter/flutter/assets/16635729/7ef476ec-b964-435d-b57b-9bc09d06acb1)

**Comment by huycozy** [comment]
Thanks for the update. Based on the stack trace, it is somewhat similar to https://github.com/flutter/flutter/issues/135524 which is fixed on master channel, but I'm not quite sure. Labeling this for the insights from engine team.

**Comment by jonahwilliams** [comment]
Potentially one of the device buffer or data ptrs is nullptr and we're failing to check this before setting the texture contents.

**Comment by yoferzhang** [comment]
#135524 didn't fix this issue; I can still reproduce it in the Flutter 3.19.5 version.

**Comment by yoferzhang** [comment]
> #135524 didn't fix this issue; I can still reproduce it in the Flutter 3.19.5 version.

25% of devices have experienced this problem in the past 7 days

**Comment by escamoteur** [comment]
We just got a new one on 3.22

**Comment by jonahwilliams** [comment]
As of https://github.com/flutter/engine/pull/54606/files#diff-e549e3a4f8d4dd189a09680c69ca8434bb8ae8031926c47b5e248dd080ae9f9d , we no longer use [UploadTextureToStorage](https://github.com/flutter/flutter/issues/141554#top). Previously this would run while Flutter had no GPU context which we believed to be crashy.

Since we had no good way to repro, we can't confirm if this is fixed or not.
