### ISSUE TITLE
Flutter Dashboard has visual glitches on latest Firefox

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#141625]
### Type of Request

bug

### Infrastructure Environment

Flutter Dashboard (https://flutter-dashboard.appspot.com)

### What is happening?

I experience various visual glitches, from minor stuttering and jank when scrolling...

https://github.com/flutter/flutter/assets/40357511/23aaf84d-0494-4ef9-a3ce-4a529ef90f40

https://github.com/flutter/flutter/assets/40357511/d6deb205-e507-4d09-8e0a-7db21515cf58

to this...

https://github.com/flutter/flutter/assets/40357511/3e7425d4-3875-4255-8cee-b3b7844793c2

### Steps to reproduce

I experience these glitches on M1 MacBook Air, latest macOS Sonoma (14.2.1), Firefox 121.0.1)

1. Install latest Firefox Stable (`brew install firefox` works fine)
2. Open Flutter Dashboard
3. Scroll around (vertically, horizontally), see glitches

### Expected results

No visual glitches are present.

**Comment by harryterkelsen** [comment]
Should be addressed by https://github.com/flutter/engine/pull/49572

**Comment by bartekpacia** [comment]
Does flutter-dashboard use latest master? I still see the glitches.

**Comment by bartekpacia** [comment]
This no longer occurs, so the engine fix apparently rolled into the dashboard. Thanks!
