### ISSUE TITLE
TextInputType.number missing decimal seperator

### ISSUE THREAD

**Issue by procedurallygenerated** [flutter/flutter#14554]
## Steps to Reproduce

Hey,

I have a `TextField` with `keyboardType: TextInputType.number`. I tested this on a galaxy s8 running android 7.0 and it works fine.

On a galaxy note 4 running android 6.0.1, the keyboard only has numbers, there are no decimal separators or the negative symbol.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en, channel master)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] Connected devices

• No issues found!

**Comment by mikelward** [comment]
Looks like "number" is used verbatim as the inputType

https://github.com/flutter/flutter/blob/c02b6a8bcf174e5220259f839705afeace151e92/packages/flutter/lib/src/widgets/editable_text.dart#L444

To match the documented behavior, it should probably pass "numberDecimal".
https://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType

**Comment by procedurallygenerated** [comment]
So I should add a new TextInputType?

**Comment by sbaranov** [comment]
Fixed by #14916.

**Comment by NTMS2017** [comment]
On Samsung J7 and J9 the keyboardType: TextInputType.numberWithOptions(decimal: true, signed: true), doesn't show decimal separator.

**Flutter doctor -v**

[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-CY)
    • Flutter version 1.9.1+hotfix.5 at /Users/niyazitoros/flutter
    • Framework revision 1aedbb1835 (2 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

**Comment by mirkancal** [comment]
This issue still exists on Samsung phones. Also there's a related issue on Xamarin Forms.

https://github.com/xamarin/Xamarin.Forms/issues/1898

My question on SO: https://stackoverflow.com/questions/58802772/textinputtype-numberwithoptions-doesnt-show-comma-or-dot?noredirect=1#comment103911981_58802772
