### ISSUE TITLE
Flutter 3.22 different behavior between debug and release mode

### ISSUE THREAD

**Issue by alr2413** [flutter/flutter#148401]
### Steps to reproduce

After upgrading to latest stable version of flutter (i.e. 3.22), found out that the application is not working properly in release mode. but everything works fine in debug mode. I also checked with fresh installation with no luck. So, I downgraded flutter to the previous stable version (i.e., 3.19.6) and both release and debug mode worked fine. 

### Expected results

Both release and debug mode should have the same behavior.

### Actual results

Released version has a different behavior compare to debug version in both windows/mac, the web version works fine.

### Code sample

<details open><summary>Developed application is a bit complicated to share a part of code here.</summary>

</details>

### Logs

There is no output log by running in release mode

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4291], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
[√] Android Studio (version 2023.3)
[√] VS Code, 64-bit edition (version 1.62.3)
[√] Connected device (3 available)
[√] Network resources

**Comment by moffatman** [comment]
No information about what changed. and no code. please help!

**Comment by danagbemava-nc** [comment]
Hi @alr2413, as noted above, we will more information than is currently available if we're to be able to provide some assistance. 

What platform is this issue on? 
Are you seeing any errors in your app (do you have crash monitoring/logging setup)? 

Please provide additional information and if possible a minimal reproducible code sample so that this can be properly investigated. 

Thank you

**Comment by synstin** [comment]
Same for me.
Although in the simulator, i.e. debug mode, everything is fine,
When I deploy the app to the testflight and run it, the app crashes.
I don't see any error logs in either debug mode or release mode.

It works fine on previous stable versions.
Here's my device info
iPhone15, iOS 17.5

**Comment by danagbemava-nc** [comment]
Hi @synstin, testflight should be keeping track of crashes, can you share the crash log? If you run it locally in release mode, does it also crash? Is this specific to iOS or are other platforms affected as well?

**Comment by synstin** [comment]
@danagbemava-nc 

I tested this locally by connecting a real device.
When testing locally, no logs appear and the screen freezes.

I'm attaching the error log as shown in Xcode.

I haven't tested Android because I don't have a device.

```
io.flutter.1.ui (9)
#0	0x00000001082aed54 in flutter::DisplayListBuilder::Restore() ()
0x1082aed54 <+284>:  ldrsb  w8, [x24] io.flutter.1.ui (9): EXC_BAD_ACCESS (code=1, address=0x117467fa8)
```

**Comment by synstin** [comment]
I found the cause.
The error occurs when setting Lottie's renderCache option to raster.

```
Lottie.asset('test.json', renderCache: RenderCache.raster);
```

**Comment by Anders3byg** [comment]
I experience a similar issue where Go_router context.replace says it can't find the route, it only happens in release mode. Works perfect in debug.
It only happens in 3.22, not 3.19, so i assume it must be a flutter core issue.

**Comment by danagbemava-nc** [comment]
Hi @Anders3byg, kindly file a new issue and provide detailed steps required to reproduce the issue as yours may be unrelated to this bug.

**Comment by siddharthadevops** [comment]
I am also experiencing different behavior in release than in debug. I think this issue is related to #148983 because in my case, it happens in parts of the code where I use UniqueKey()

**Comment by ravindran-a** [comment]
+1

**Comment by RoyGuanyu** [comment]
+1, no error in debug, but ui rendering not working in release

**Comment by alr2413** [comment]
> I am also experiencing different behavior in release than in debug. I think this issue is related to #148983 because in my case, it happens in parts of the code where I use UniqueKey()

Yea, I checked my code as well, that was the source of my problem :(

**Comment by darshankawar** [comment]
> related to #148983

This has been fixed and is available in latest master. If anyone can use latest master version and re-run their scenario to confirm would be helpful for everyone in this thread.

**Comment by alr2413** [comment]
@darshankawar 
Seems that my issue has been fixed in latest master. but since it's not stable, I'll switch back to Flutter 3.19 for now. Thanks for all the support :)

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/flutter/flutter/issues/148401#issuecomment-2172720783. 

For anyone else facing a similar issue, please file a new issue and provide detailed information as to how we can reproduce this so it can be properly investigated. 

Thank you

**Comment by say-when** [comment]
I was experiencing issues with our app having a number of different UI problems in release mode after upgrading to 3.22.0 (issue persists in 3.22.1 and 3.22.2) but it worked fine in debug mode. 

I switched to the master channel with 3.23.0, and the app works fine again in release mode. I downgraded back to 3.19.6 for the time being.
