### ISSUE TITLE
Flutter iOS Impeller "Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)"

### ISSUE THREAD

**Issue by droplet-js** [flutter/flutter#149165]
### Steps to reproduce

iOS Simulator iPhone 15 Pro iOS 17.2

``` dart
Scaffold(
  appBar: AppBar(
    title: Text('Demo'),
  ),
  body: Stack(
    children: <Widget>[
      Positioned.fill(
        child: BackdropFilter(
          filter: ui.ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
          child: ColoredBox(
            color: Colors.black.withOpacity(0.7),
          ),
        ),
      ),
    ],
  ),
)
```

### Actual results

black screen

### Logs

<details open>
<summary>Logs</summary>

```console
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (2000000000, 2000000000) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 13.6.5 22G621 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@droplet-js 
We verified the code sample on various iOS versions and simulators but were unable to see the reported error, using latest stable version. We get below with no logs as you reported.

<img width="354" alt="Screenshot 2024-05-28 at 4 23 36 PM" src="https://github.com/flutter/flutter/assets/67046386/f4da3180-206e-4d76-812b-69de3d5c1287">

We also checked on  iOS 17.2 and iPhone 7, iOS 15.8 and iPhone 15 Pro, iOS 17.4 (emulator). Can you try it on other simulator to check if it persists still  along with latest master version as well ?

**Comment by darshankawar** [comment]
Thanks for the update. I think you are hitting https://github.com/flutter/flutter/issues/128885 so please follow-up in it for further updates.
Closing this as duplicate.

**Comment by jonahwilliams** [comment]
Going to reopen this one as its different enough from the previous issues.

**Comment by darshankawar** [comment]
Revisited this issue by trying on various simulators as mentioned in [this](https://github.com/flutter/flutter/issues/149165#issuecomment-2134924863) comment, but we couldn't still get the logs reported. We see a blank screen with no mentioned logs.

@droplet-js Can you try your scenario with latest master and stable versions to check if reported behavior still persists or not ?

**Comment by OliverNarramore** [comment]
This is still an issue for me on 3.24.3 and is a blocker for our app

**Comment by devnoaman** [comment]
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.

**Comment by devnoaman** [comment]
```
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
```

**Comment by Gilianp** [comment]
Same problem here. We use several textures, colorfilters, and savelayers operations, but in version 3.24.2 this problem does not occur

**Comment by vdvpie22** [comment]
I have same issue.
```
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (1290, 16530) exceeds maximum supported size of (16384, 16384)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
```

Flutter 3.24 & 3.22

**Comment by dpedrinha** [comment]
I'm having a similar issue:
Black screen but with a slight different error - Break on 'ImpellerValidationBreak' to inspect point of failure: **Could not create AHB texture source.**

I'm doing some tests and logging everything here #155973

**Comment by YeLwinOo-Steve** [comment]
Any update on this coz I'm having these issues on ios emulator?
```
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
24
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
```

**Comment by jonahwilliams** [comment]
As far as we know, this issue was fixed on the latest stable. If not please comment and Ill reopen.

**Comment by Small-World** [comment]
The problem still exists on 3.24.5. Which version will fix the problem?
