### ISSUE TITLE
Blank/empty UI on second run of app in Android emulator.

### ISSUE THREAD

**Issue by jlewallen** [flutter/flutter#149328]
### Steps to reproduce

Hello, this is an issue I'm seeing with a brand new flutter project on a local Android emulator.

```
flutter emulators --launch Pixel_7_API_VanillaIceCream
flutter create helpme
cd helpme
flutter run -d emulator-5554
```

At this point the application launches correctly, everything seems fine. I then close the application and rerun from inside the emulator and the application starts but everything is blank (white, nothing rendered). I believe the application is running fine, but there seems to be an issue with painting/rendering the UI.

Every time you run the application using `flutter run` it will correctly start.

A significant clue: If I clear the app cache, I'm able to run the application again. This is very reproducible. Effectively, to run the application, clearing the cache is necessary.

Forgive me if I'm leaving out anything critical in this bug report, it's my first time filing one with this project. 

Thanks so much.

### Expected results

There to be no difference when running a brand new app the second time and that to run a second time clearing the cache is not necessary.

### Actual results

Running the app a second time w/o clearing the app cache results in a blank window with no UI rendered.

### Code sample

I am able to reproduce this by creating a new project using:

```
flutter create helpme
```

### Logs

<details open><summary>Logs</summary>

I'm happy to provide these, but due to the nature of the issue the logs seem fine to me, and in order to reproduce the device connection must be lost. Happy to provide `adb` logs, though if those will help.

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
~/helpme main*​​​ 3s
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.5, on Linux Mint 21 5.15.0-107-generic, locale en_US.UTF-8)
    • Flutter version 3.19.5 on channel stable at /home/jlewallen/tools/flutter-3.19.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (9 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/jlewallen/tools/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/jlewallen/tools/android-sdk
    • Java binary at: /home/jlewallen/tools/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/jlewallen/tools/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (4 available)
    • SM J701M (mobile)            • 5200ae734a8895df • android-arm    • Android 9 (API 28)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux            • linux-x64      • Linux Mint 21 5.15.0-107-generic
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 125.0.6422.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @jlewallen 
Can you try [this](https://github.com/flutter/flutter/issues/146890#issuecomment-2123136901) and see if it helps in your case or not ?

**Comment by jlewallen** [comment]
On my machine there is no ANGLE D3D11 renderer. I tried "SwiftRenderer" and the emulator didn't appear functional. I tried Desktop Native and that seemed to fix the issue. Thanks :)

Incidentally, my app was recently rejected because of a "clearing cache issue" and was hoping this was something related that would explain the problem, as I'm unable to reproduce the issue the reviewer saw. Was clearing the app cache a red herring in this case, do you think?

At any rate, things for getting my emulator working.

**Comment by jlewallen** [comment]
Actually, a correction. The example from the template works, but my app still exhibits the same behavior. Fortunately, my app is open source:

https://gitlab.com/fieldkit/patina/

I will start looking into how to make a smaller repro.

**Comment by jlewallen** [comment]
I was trying to reproduce with a narrower and narrower version of my app and ended up back where I started: the problem is happening again with the `flutter create` template. I've tried starting with a new emulator from scratch.

Apologies for the deluge of messages. I'll go silent until I have more useful information, just wanted to update with the knowledge that this is coming and going with a mind of its own and at first did seemed tied to rendering settings, but is not behaving consistently.

**Comment by mohsen-mohamed** [comment]
> Thanks for the report @jlewallen Can you try [this](https://github.com/flutter/flutter/issues/146890#issuecomment-2123136901) and see if it helps in your case or not ?

thank you for the reply it helped me a lot
I've been searching for a solution and finally found it in the link
simply changing that setting fixed it 
and there is another solution in the same post by changing the emulator's config.ini
hw.gpu.enabled=yes
hw.gpu.mode=host
 both solutions worked for me

**Comment by darshankawar** [comment]
> the problem is happening again with the `flutter create` template. I've tried starting with a new emulator from scratch.
> 
> Apologies for the deluge of messages. I'll go silent until I have more useful information, just wanted to update with the knowledge that this is coming and going with a mind of its own and at first did seemed tied to rendering settings, but is not behaving consistently.

@jlewallen Is there a pattern that you can find that consistently replicates the behavior ? Try with different range of android emulators and check which one exhibits it, that'll help us to verify this further.

**Comment by jlewallen** [comment]
Right now it's 100% consistent for me, I'm very confused as to why it worked once and then reverted back to the original behavior. To help with reproducibility, I'm using this script to create and run the emulator:

```
#!/bin/bash

avdmanager delete avd -n p5 || true

avdmanager create avd -n p5 --package "system-images;android-33;google_apis;x86_64" --abi google_apis/x86_64  --device pixel_5 --force

sed -i -e '/hw\.gpu\.enabled/ s/=.*/=yes/' ~/.android/avd/p5.avd/config.ini
sed -i -e '/hw\.gpu\.mode/ s/=.*/=host/' ~/.android/avd/p5.avd/config.ini

pushd ~/tools/android-sdk/emulator
emulator -avd p5 -gpu host
popd
```

I've also upgraded to Flutter 3.22.1 and am creating my example using the same approach as before.

I narrowed down those "Advanced" settings to `~/.config/Android Open Source Project/Emulator.conf` which has:

```
[set]
autoFindAdb=true
clipboardSharing=true
crashReportPreference=2
disableMouseWheel=false
disablePinchToZoom=false
glesApiLevelPreference=1
glesBackendPreference=4
```

Corresponding to Desktop native OpenGL and Renderer maximum.

**Comment by jlewallen** [comment]
Some new behavior, when I re-run the app using `flutter run` I get OpenGL errors:

```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                           2,595ms
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Syncing files to device sdk gphone64 x86 64...                      63ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:41899/4mPGQ6Diqd4=/
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
E/emuglGLESv2_enc( 5100): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:41899/4mPGQ6Diqd4=/
```

This also happens if I select the "Compatibility" OpenGL API level.

**Comment by melihhakanpektas** [comment]
Same here...

**Comment by melihhakanpektas** [comment]
```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk
Connecting to VM Service at ws://127.0.0.1:50901/O0AILUsGstQ=/ws
D/CompatibilityChangeReporter( 8857): Compat change id reported: 183155436; UID 10175; state: ENABLED
I/FirebaseApp( 8857): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
D/CompatibilityChangeReporter( 8857): Compat change id reported: 3400644; UID 10175; state: ENABLED
I/flutter ( 8857): !!BLOC!! StateChangedToUnauthenticatedEvent
I/flutter ( 8857): !!BLOC!! From AuthLoadingState to UnauthenticatedState
17
E/emuglGLESv2_enc( 8857): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2206 GL error 0x502
```

**Comment by darshankawar** [comment]
Thanks for the update. I am unable to replicate this using latest stable and by creating a new Android emulator Pixel 5 for example in which the app builds and compiles all UI elements properly.

@jlewallen The emulator you create, does it have play store feature ?

<img width="351" alt="Screenshot 2024-06-04 at 11 26 46 AM" src="https://github.com/flutter/flutter/assets/67046386/6f2b5129-395a-4348-8680-94c397e45808">

And this behavior is only occuring on emulators and not on physical devices ?

**Comment by jlewallen** [comment]
Hey there @darshankawar ,

Yes, I tried creating a new emulator with play store enabled and the problem persists, regardless of the OpenGL settings. Here are the AVDs I'm trying with:

```
 avdmanager list avd
Available Android Virtual Devices:
    Name: p4
  Device: pixel_4 (Google)
    Path: /home/jlewallen/.android/avd/p4.avd
  Target: Google Play (Google Inc.)
          Based on: Android VanillaIceCream Preview Tag/ABI: google_apis_playstore/x86_64
    Skin: pixel_4
  Sdcard: 512M
---------
    Name: p5
  Device: pixel_5 (Google)
    Path: /home/jlewallen/.android/avd/p5.avd
  Target: Google Play (Google Inc.)
          Based on: Android VanillaIceCream Preview Tag/ABI: google_apis_playstore/x86_64
  Sdcard: 512 MB
```

As far as if I'm seeing it on physical devices, that's harder for me to answer. My Pixel 5 doesn't reproduce the issue nor does an older Android device I have. I've had 1 user report a similar issue on a Pixel 7, in that they had to clear the "app data" in order to get the app to launch, but it doesn't seem like the problem "came back" on successive launches as it does with the emulator. I also had my app rejected because the reviewer received the Android dialog about the app "having a bug" and suggesting the cache be cleared. I can't be positive that these two instances are the same issue, nor do I even know if app store reviews use physical devices.

Right now, other apps work fine in the emulator and assuming that this is the emulator's fault and not something specific to the framework feels risky, giving my experience with the app store.

I would love to have more background/understanding on the details of the issue if you have the time and know more? For example, do you know what's actually in the app's cache that could be affecting this? I've looked for programmatic ways to clear this particular cache, but couldn't find anything. I'm happy to dig deeper into the problem, I'm just not sure where Flutter ends and the emulator begins in the context of this issue.

Thanks!

**Comment by darshankawar** [comment]
Thanks for the update. I am not sure if Linux could be factor. Keeping the issue open and labeling for team's attention.

**Comment by aFrogThatExists** [comment]
The same problem appeared for me too.

I'm also on Linux.

**Comment by aFrogThatExists** [comment]
I solved it by downgrading the android emulator to version 34.1.20 (Stable) with the instructions at https://developer.android.com/studio/emulator_archive

**Comment by gmackall** [comment]
Trying to recreate this at the moment.

Looks like there is also an issue on the public Android bug tracker https://b.corp.google.com/issues/345674553, which contains a [potential workaround in comment 11](https://b.corp.google.com/issues/345674553#comment11):
> For users:
>
> As a workaround, you may try to launch the emulator with the flag -guest-angle, the full command would be:
> 
> `/path/to/emulator -avd your_avd_name -guest-angle`
> Note that it only works with API level 34 or higher, and quickboot will be disabled in -guest-angle mode.

**Comment by Vedant0-0** [comment]
Howw to fix this issue??
My apps runs once but then it doesnt.
see the video link of the issue please help me
https://jmp.sh/3SngybCP

see this video of the issue please tell me the fix

**Comment by abishekmuthian** [comment]
Google closed the [issue](https://issuetracker.google.com/issues/345674553) telling that its fixed in the latest canary, but the neither the canary or the latest beta even open in Linux. 

Folks , if you're on Linux please  (35.2.4) Canary and  (35.1.8) Beta and report in the  issue tracker.

related to #146890 .

**Comment by Vedant0-0** [comment]
> Trying to recreate this at the moment.
> 
> Looks like there is also an issue on the public Android bug tracker https://b.corp.google.com/issues/345674553, which contains a [potential workaround in comment 11](https://b.corp.google.com/issues/345674553#comment11):
> 
> > For users:
> > As a workaround, you may try to launch the emulator with the flag -guest-angle, the full command would be:
> > `/path/to/emulator -avd your_avd_name -guest-angle`
> > Note that it only works with API level 34 or higher, and quickboot will be disabled in -guest-angle mode.

@gmackall What if my API is less than 34?

**Comment by gmackall** [comment]
I was able to reproduce this today on a Windows desktop (didn't ever get it to repro on Mac). 

This is marked as fixed in https://issuetracker.google.com/issues/345674553, and I was able to verify the fix locally by following the instructions at https://developer.android.com/studio/emulator_archive to download emulator version `35.1.18`. 

At the time of writing this comment, the fixed versions weren't available to me in Android Studio's sdkmanager tool, so I'd recommend that people follow those steps to get a fixed emulator version (until that version makes it to Android Studio's sdkmanager tool).

I'm also going to close this issue because the issue isn't a Flutter issue, but an Android emulator issue (and a fixed one at that).

**Comment by nav9** [comment]
The issue is still not solved. Android Studio Jellyfish | 2023.3.1 Patch 1. Flutter 3.22.1. Dart 3.4.1. DevTools 2.34.3.  To solve it I tried searching for the [option](https://github.com/flutter/flutter/issues/146890#issuecomment-2123136901) that @darshankawar pointed to, but couldn't find the corresponding menu containing the option. This bug is so annoying, and is such a fundamental flaw, that I decided not to use Flutter for professional app development. It's especially annoying because after running `flutter clean`, the build process requires a fresh download of some dependencies that consumes another 200 or 300MB of download. When on a metered connection, it consumes too much of the daily download bandwidth. And why the heck does it have to keep downloading stuff that it had already downloaded? I even set `org.gradle.caching=true`, but the downloads still happen after running `flutter clean`. Even having to remember the plethora of the syntax and the single-line-split-into-multiple-lines indenting gets irritating.   
![blankBackground](https://github.com/user-attachments/assets/ee917725-d397-45b7-978f-1aeaa70c6c4c)

**Comment by gmackall** [comment]
@nav9 The issue is specifically fixed on the emulator versions mentioned in https://issuetracker.google.com/issues/345674553#comment26 (35.1.18 or 35.2.4 or higher).

Follow instructions at https://developer.android.com/studio/emulator_archive to upgrade your emulator version.

> This bug is so annoying, and is such a fundamental flaw, that I decided not to use Flutter for professional app development.

I'm sorry that you feel this way. This isn't a Flutter bug, though - it is a bug with the Android emulator. So there is no further action we can take.
