### ISSUE TITLE
Android crash on hot-reload using dart 2 preview using Android Studio or VS Code

### ISSUE THREAD

**Issue by rfuhrer** [flutter/flutter#14945]
## Steps to Reproduce
1. `flutter create fl_test`
2. open project in Android Studio or VsCode with the Dart-Code extension
3. setup the IDE to run in --preview-dart-2 mode
4. open a android simulator
5. debug the project
6. press hot-reload (or make a change and save)
7. app crashes and all you get for an output is `Lost connection to device.`

This issue only happens with the flutter plugin, using the flutter command line works perfectly (pressing 'r' doesn't crash), so it seems to be something with however the plugins interact with the flutter run time that is different from the command line

## Logs
```
Analyzing C:\git\flut_test...
No issues found!
Ran in 6.1s
```
## Flutter Doctor
```
[√] Flutter (Channel dev, v0.1.7, on Microsoft Windows [Version 10.0.17025.1000], locale en-US)
    • Flutter version 0.1.7 at C:\git\flutter
    • Framework revision 3b84503403 (24 hours ago), 2018-02-26 20:11:11 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\Rory\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by DanTup** [comment]
Possibly related?

https://github.com/flutter/flutter-intellij/issues/1809
https://github.com/flutter/flutter/issues/14847

**Comment by jacob314** [comment]
I expect this has probably been fixed by https://github.com/flutter/flutter/pull/14994
but I'm not positive. Based on my change I'm surprised things were sometimes working in the IDE mode but perhaps things can actually sometimes work with a mixture of dart1 and dart2 compilation paths as long as dart 1 and dart2 aren't causing conflicting behavior.

**Comment by grindvoll** [comment]
@jacob314 , I just did a quick test with the commit from #14994 with VSCode on Windows, and it still fails like described. Doing a hot reload by e.g. saving the file results in a disconnect. Pressing `r` in the flutter console works fine.

```
Flutter 0.1.8-pre.22 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7dbe9e7bcd (46 minutes ago) • 2018-03-01 07:19:21 -0800
Engine • revision 6607231638
Tools • Dart 2.0.0-dev.31.0.flutter-1aaebedd70
```

**Comment by jacob314** [comment]
After syncing in just a change to flutter_tools you will need to make sure flutter_tools has rebuilt by deleting the flutter_tools.stamp file. 
What I do on linux is 
rm -f ~/git/flutter/bin/cache/flutter_tools.stamp

**Comment by grindvoll** [comment]
Thanks for the tip. I tried again after rebuilding the tools, but the result is still the same. Saving the file in VSCode results in a disconnect message as shown below.

```

Built build\app\outputs\apk\debug\app-debug.apk (29.9MB).
I/FlutterActivityDelegate(18930): onResume setting current activity to this
D/        (18930): HostConnection::get() New Host Connection established 0xde19e040, tid 18951
Lost connection to device.
```

**Comment by jacob314** [comment]
Another fix just landed that may be related to your issue. Can you sync flutter to the latest and try again?
https://github.com/flutter/engine/pull/4733
Just in case, I would also make sure you manually delete your build directory to ensure you do not have stale files causing the issue.

**Comment by rfuhrer** [comment]
Thanks for picking this up @grindvoll, I'm still about 6 hours away from heading home for the day so I can't test anything until then.

**Comment by rfuhrer** [comment]
@jacob314 Here's what I did:
1. went to my flutter folder, killed the `flutter_tools.stamp`
2. pulled latest from git for flutter, reset master to origin/master which was a commit from 1 hour ago
3. ran `flutter channel master` which kicked off a bunch of sdk downloads and stuff
4. went to my project, ran `flutter clean` to kill the build folder
5. Opened the project in VS Code, hit F5, got to my app's home screen
6. Changed a label, hit save. 🔥 crash

Same message as before, same result in Android Studio.  Same thing where it works fine in the flutter CLI

**Comment by grindvoll** [comment]
I can conform that it still doesn't work. Testing with tools rebuilt from the latest commit (73a1a) and a cleaned build folder, the device is still disconnected when saving the file in VSCode.

**Comment by ics042** [comment]
I've updated to the latest version in master branch, but it's still crashed when the hot reload clicked.

`flutter --version`
![image](https://user-images.githubusercontent.com/22568528/36894152-761398d6-1e45-11e8-9243-f0bb3db7ed5c.png)

`Error output from Android Studio Console`
![image](https://user-images.githubusercontent.com/22568528/36894232-a4ff45a0-1e45-11e8-9bb8-9d06feaabf63.png)

**Comment by jornvandebeek** [comment]
I also have this issue on channel master, and another issue that might be related. When I run tests on the sample project inside android studio, it crashes:

```
D:\flutter\bin\flutter.bat --no-color test --machine --preview-dart-2 test
Testing started at 16:29 ...
Finished compilation of C:\Users\Pd\AppData\Local\Temp\dart_test_listenercff469fb-1fc0-11e8-891d-d050998436e7/listener.dart into C:\Users\Pd\AppData\Local\Temp\dart_test_listenercff469fb-1fc0-11e8-891d-d050998436e7/listener.dart.dill
Shell: e:\b\build\slave\windows_engine\build\src\third_party\dart\runtime\vm\kernel_binary.cc: 42: error: Invalid kernel binary: Indicated size is invalid.
Shell: Stack dump aborted because no current Dart thread.
Failed to load "D:\AndroidStudioProjects\flutperp\test\widget_test.dart":
Shell subprocess crashed with unexpected exit code -1073740791 before connecting to test harness.
Test: D:\AndroidStudioProjects\flutperp\test\widget_test.dart
Shell: D:\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester


dart:async/stream_controller.dart 594                      _StreamController.addError
dart:async/stream_controller.dart 862                      _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 140      _GuaranteeSink._addError
```
Running tests on the command line with `flutter test` works fine. 

I am mentioning it here since Jacob mentioned it might have something to do with old compiled code sticking around. The error message makes it sound like a wrong (old?) kernel binary being used. It seems windows related, given that I and two others here with the issue are all on windows. I have cleared my flutter cache, and I think that makes it download the windows vm binaries again but the problem persists.

I wonder if the others who have seen the original issue here also have the same issue I see running tests.

**Comment by grindvoll** [comment]
Today I tried to spot the differences between doing a hot reload from the command line vs. doing a reload from VSCode. After some attempts I found that crash is affected by Windows file path handling (backslash \ vs slash /).

It seems that the `updateDevFS` method is more sensitive to path formats when running in preview-dart-2 mode.  Ref. parameters `mainPath` and `target` to the method: When running from command line, there is a forward slash in the path before `main.dart`, while when running from VSCode, it's all backslashes. E.g. the value of `mainPath` is:

```
Commmand line:    C:\dev\flutter\app\lib/main.dart
VSCode:           C:\dev\flutter\app\lib\main.dart
```

At line 275 in file `run_hot.dart`:  By replacing all backslashes with slashes in the `mainPath` and `target` parameters to the `updateDevFS` method, hot reloading in VSCode works fine. (Perhaps only one of the mods is needed; I haven't tested that yet):

```dart
    for (FlutterDevice device in flutterDevices) {
      final bool result = await device.updateDevFS(
        mainPath: mainPath.replaceAll('\\', '/'),
        target: target.replaceAll('\\', '/'),
        bundle: assetBundle,
        firstBuildTime: firstBuildTime,
        bundleFirstUpload: isFirstUpload,
        bundleDirty: isFirstUpload == false && rebuildBundle,
        fileFilter: _dartDependencies,
        fullRestart: fullRestart
      );
      if (!result)
        return false;
    }
```

I assume that this is not the right place to introduce this fix - I guess it should be handled in the external general file/path handling library.

**Comment by grindvoll** [comment]
Further checks reveal that it is the `target` property that causes the crash. If this value contains a backslash, the `URI.parse` method in the `DevFS.update` does not give the expected result.

The invocation occurs at line `508` in file `devfs.dart` (at current master branch):

```dart
      if (compiledBinary != null && compiledBinary.isNotEmpty)
        dirtyEntries.putIfAbsent(
          Uri.parse(target + '.dill'),
          () => new DevFSFileContent(fs.file(compiledBinary))
        );
```

By replacing `URI.parse(target + `.dill`)` with `fs.path.toUri(target + '.dill')`, hot reloading works as expected in VSCode. The `fs.path.toUri` call handles platform-dependent path separators.

@jacob314, perhaps can you have a look at this and consider pushing it as a fix? Note that I have only tested the change in a Windows environment.

The resulting code becomes:

```dart
      if (compiledBinary != null && compiledBinary.isNotEmpty)
        dirtyEntries.putIfAbsent(
          fs.path.toUri(target + '.dill'),
          () => new DevFSFileContent(fs.file(compiledBinary))
        );
```

**Comment by aam** [comment]
Thanks for the investigation @grindvoll and proposed fix!
I believe you also should be able to reproduce the crash from command line if you specify `--target` option like so: `flutter run --preview-dart-2 -v --target=lib\main.dart`.
