### ISSUE TITLE
Getting unhelpful error while installing if flutter.io is blocked or if certificate is not recognized

### ISSUE THREAD

**Issue by kdpuvvadi** [flutter/flutter#15014]
## Steps to Reproduce
Trying to install Flutter in Windows 10 Machine. Clone the repo and added path and 
run `flutter doctor  ` it downloaded sdk and getting error. deleted the cache folder in bin and retried but same error.

## Logs

same as `flutter doctor -V`

## Flutter Doctor

```
Updating flutter tool....
CreateProcessW failed 193
CreateProcessW failed 193
CreateProcessW failed 193
%1 is not a valid Win32 application.

  Command: C:\Users\KD\Desktop\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ...
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by cbracken** [comment]
@kdpuvvadi thanks for reporting!

/cc @goderbauer who may be able to provide more insight

**Comment by goderbauer** [comment]
Does `C:\Users\KD\Desktop\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe` Exist? When you execute that in a command prompt, what do you get?

**Comment by goderbauer** [comment]
Is the path to 7za.exe shown in your log the actual path? Or does the real path contain spaces by any chance? On pub’s GitHub there is this report https://github.com/dart-lang/pub/issues/1591, where users saw the same error when they either had spaces in the path or their internet access was blocked by a firewall.

**Comment by goderbauer** [comment]
@nex3 @munificent Any idea why pub is failing to extract the package on Windows with the 7zip that comes bundled with pub?

**Comment by nex3** [comment]
I'm not sure... I suppose it's possible that the executable is binary-incompatible with their version of Windows for some reason.

**Comment by kdpuvvadi** [comment]
@goderbauer that is the real path, no spaces or character in there. and OS is Windows 10 Pro, Version 1709 and build 16299.248. I've checked the with firewall off and also directly connected without hardware firewall

**Comment by mornes** [comment]
IIm having the same issue. Its seem to me like that version is not compatible with Windows 10

**Comment by mornes** [comment]
I had the same issue but got mine sorted. The directory to which my flutter was cloned to had a space. "C:\Users\Mornes Dev\flutter". I changed it to "C:\Dev\flutter" and now everything is working 100% HTH

**Comment by cbracken** [comment]
Interesting! Thanks for the additional information @mornes.

Our integration tests for Linux, macOS, and Windows all run in a directory that includes a space (specifically we use "flutter SDK" as the directory). Verified that the code for testing this on Appveyor is [still there](https://github.com/flutter/flutter/blob/master/appveyor.yml#L3-L4).

To list the differences between the reported case and our bot tests:
* Space appears in the last path segment on the bots (vs above the flutter SDK dir in the report)
* We initially clone into a directory with no spaces on the bots, then add a space to the SDK directory. We don't *run* any flutter commands until after we've added the space though.
* The first commands we run are `bin\flutter.bat config --no-analytics` and `bin\flutter.bat update-packages` vs `flutter doctor` (I'd have thought this shouldn't make a real difference to the downlods + pub failure though).

Thanks again for the additional info. This gives us a bit to go off.

**Comment by Hixie** [comment]
@kdpuvvadi What happens when you run `C:\Users\KD\Desktop\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe` directly in a command prompt?

**Comment by zoechi** [comment]
Some similar errors with workarounds I found

- space in path of flutter install directory
- using BOSH shell #15230
  - #15165 custom bash installation (missing libreadline.6.dylib)
- behind a firewall https://github.com/flutter/flutter/wiki/Using-Flutter-in-China #13349
- switching to `dev` channel #15076
  - #12666 `set DART_VM_OPTIONS=--idle_timeout_micros=200000000` (should be fixed)
- download Dart SDK interrupted #15552

**Comment by kdpuvvadi** [comment]
Problem was flutter.io was blocked in our network and after it was removed from blocklist it's now working.

**Comment by amangautam1** [comment]
same issue....any solution??

**Comment by zoechi** [comment]
@amangautam1 did you check the links in my above comment?

**Comment by tabinnorway** [comment]
Still open. Still no solution. Tried all the recommendations in Zoechi's post.

> Updating flutter tool...
> Got TLS error trying to find package archive at https://pub.dartlang.org.
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> timeout: invalid time interval '/t'
> Try 'timeout --help' for more information.

Tip: I am suspecting the inclusion of a self-signed certificate in our tool chain. This is what trips up npm, ionic and all of this other stuff. The difference between flutter and npm/ionic and all the other stuff is that for these there is a very, very easy work-around.

What's the work-around for flutter?

**Comment by tabinnorway** [comment]
Here is some relevant output from wget

> E:\bin\flutter>wget https://pub.dartlang.org
> --2018-03-23 12:38:05--  https://pub.dartlang.org/
> Resolving pub.dartlang.org (pub.dartlang.org)... 172.217.20.51, 2a00:1450:400f:806::2013
> Connecting to pub.dartlang.org (pub.dartlang.org)|172.217.20.51|:443... connected.
> ERROR: The certificate of 'pub.dartlang.org' is not trusted.
> ERROR: The certificate of 'pub.dartlang.org' hasn't got a known issuer.

**Comment by zoechi** [comment]
Did you check https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?
Sounds related to me even when you're not in China.

**Comment by tabinnorway** [comment]
Nope, it's not related. This is a problem with the way flutter/dart retrieves packages. Again, no problems with npm/ionic and the many many tools out there that does this. Only dart and flutter. I am unsure how npm (for example) does this, but the environment variable you need to set seemingly tells npm to ignore the problem of self -signed certificates. I'd be surprised if this is not the problem Dart is having.

What is needed is an ability for dart/pub/flutter/whateveritis to fetch over https even when there are self-signed certificates in the chain. Probably. Should be possible to find out what npm does when the environment variable NODE_TLS_REJECT_UNAUTHORIZED=0

Please note the **TLS** part of that environment variable and take a look at what the error from flutter/dart/pub says. I would recommend taking a quick look at the source code for npm to figure out what they do when they find the NODE_TLS_REJECT_UNAUTHORIZED=0 environment variable. Just copy those steps.

> $ git clone -b dev https://github.com/flutter/flutter.git
> Cloning into 'flutter'...
> remote: Counting objects: 117247, done.
> remote: Compressing objects: 100% (83/83), done.
> remote: Total 117247 (delta 47), reused 52 (delta 31), pack-reused 117133
> Receiving objects: 100% (117247/117247), 35.48 MiB | 2.42 MiB/s, done.
> Resolving deltas: 100% (87808/87808), done.
> Checking out files: 100% (2444/2444), done.
> 
> $ cd ./flutter
> 
> $ flutter doctor
> Checking Dart SDK version...
> Downloading Dart SDK from Flutter engine 6280adbfb1f9f63cdc6179b9b78634add1e4f2e3...
> Unzipping Dart SDK...
> Updating flutter tool...
> Got TLS error trying to find package archive at https://pub.flutter-io.cn.
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> timeout: invalid time interval '/t'
> Try 'timeout --help' for more information.

**Comment by cbracken** [comment]
@tabinnorway not sure if it helps but looking at the chain of trust for the cert for pub.dartlang.org, it was issued by [Google Internet Authority G2](https://pki.google.com/) which is signed by GeoTrust Global CA. 

Looking at your error message, it looks like you're running against pub.flutter-io.cn, which has a different cert chain, issued by COMODO RSA Certification Authority.

**Comment by tabinnorway** [comment]
@cbracken - the reason I am using pub.flutter-io.cn is that I am attempting the solution suggested by @zoechi above:
> Did you check https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?
> Sounds related to me even when you're not in China.

I am pretty sure that this is caused by the fact that my company (where I am an external consultant) use self-signed certificates in our chain. This is a very common situation in many enterprises, and it is solved by making dart/flutter/pub ignore the fact that there are self signed certificates in the chain. Again, see my comments above with npm/ionic and the others.

The reason I suspect this is because if I try to install any npm package, for example, I need to remind npm to ignore self-signed certificates in the chain. If I do not tell npm (node really) to ignore self-signed certificates in the chain, node/npm will not work, and they will complain about TLS (Transport Level Security) certificates. As you can see from the errors I get from flutter/pub, TLS is where the problem appears to be.

So, my suggestion is that the dart/flutter/pub team check out the node source code (it's right here on Git Hub) to see what node does when the environment variable mentioned is set to 0.

**Comment by Hixie** [comment]
We don't support ignoring invalid certificates. That's a huge security risk. It would allow anyone between you and pub to substitute arbitrary code for the code you are downloading, allowing them to run arbitrary code on your computer.

**Comment by tabinnorway** [comment]
@Hixie 
Most people who would ask questions in what amounts to a programmers forum or similar are probably reasonably familiar with risks involving, for example, self-signed (which is not the same as invalid) certificates. For example, temporarily allowing a self-signed certificate in a communication chain has an extremely low probability of being abused.

Now, one can deal with this in a rational way, which is what you see for example, the node development team do, when they **temporarily** allow the competent developer to suspend the check for self-signed certificates. Alternatively one can get on ones  high horse and exclaim to the world that one is the person who knows best what others should and should not accept of risks to them selves. Huff and puff a little in exasperation of what the ignorant little people in the world asks for and be annoyed that they do not remember to call Ian Hickson "your highness".

Seriously, are you saying that node is a terrible piece of software that should never be foisted on the public because they allow the competent developer to self-evaluate risks to him self?

My customer asked me to evaluate Flutter for their needs, your response will elicit a report that reads more or less as such
> **Tool**: Flutter
> **Suitability**: Not
> **Reason**: A development team that thinks everybody else are morons

**Comment by NathanaelA** [comment]
@Hixie 

> We don't support ignoring invalid certificates. That's a huge security risk. It would allow anyone between you and pub to substitute arbitrary code for the code you are downloading, allowing them to run arbitrary code on your computer.

This is actually a false statement in this case, Ian, a huge number of medium and enterprise companies use a self signed certificate chain so they can snoop on all traffic.  For the uniformed, Ian, the firewall itself will check the cert chain properly from itself to the site; so the the perceived risk is not real risk.
Unfortunately this is very much a standard practice in larger companies and MANY government facilities.    The risk of the data being changed from the firewall to the machine is approximately 0% -- So having a switch that allowed someone to ignore the certificate chain when they are in that situation would open it up to those people.    

Where right now you are basically saying you have no interest in allowing all these larger companies and governmental sites to use Flutter, because there is no way firewall politics is going to change their policy because a set of developers can't get access to these tools.    

 You make it literally impossible for the devs to get the tools; and they will use something else.

**Comment by Hixie** [comment]
> so the the perceived risk is not real risk

It's absolutely real risk. For example, it means the employer in question (or whoever is running the firewall) could be changing the data. It also means anyone on the "inside" could be doing a man-in-the-middle attack and you would be completely unaware.

> So having a switch that allowed someone to ignore the certificate chain when they are in that situation would open it up to those people.

Unfortunately it would also cause people who are experiencing man-in-the-middle attacks to flip the switch "because it fixes my problem".

> Where right now you are basically saying you have no interest in allowing all these larger companies and governmental sites to use Flutter, because there is no way firewall politics is going to change their policy because a set of developers can't get access to these tools.

We are working on some alternative ways to deploy Flutter which will handle these situations (where people will just be able to download pre-built archives of the Flutter repo, for instance).

**Comment by NathanaelA** [comment]
> so the the perceived risk is not real risk
>>It's absolutely real risk. 

You know I've looked into you and I know you are highly intelligent; -- but I assume you just dismissed this without apparently thinking through the ramifications to your statements and the proposed security issues that are already present    You are absolutely 100% wrong, here, Ian!  And hopefully after my long spiel you will have the graciousness to admit it. :grin:     

Your locking the windows after ALL the animals have escaped through the wide open barn door.   :grinning: 

---

If the corporation is large enough to be MTM the traffic, don't you think they have FULL remote admin rights to every machine they allow on their network.  They would just INSTALL what they wanted on the computer; not waste time MTM's the flutter stuff.    The risk you state is 100% non-existent in this first case, which is the overwhelming vast majority of NORMAL cases that need this flag!  (It is good you are looking at alternative methods for install; kudo's for that!)

As for the next case; if a "bad actor" is already remotely inside the network and able to MTM the traffic -- they for sure **DO NOT** need to MTM the flutter engine stuff to get their stuff on device.    If I have access to MTM the traffic inside the network; then I have the ability to use all sorts of ways to get my code on a machine.  I can think of dozens of ways to compromise a network if I have MTM access to the traffic.   But for arguments sake ( and to point out how the fallacy :grin: ) lets say I do want to compromise a specific developer machine with Flutter -- it would be FAR simpler to just subvert the github.com traffic and make a new cloned flutter repo on my server with a new "flutter" scripts that was an "upgrade" to the existing version.   :grinning:   **Oops!!!**    You so nicely have locked the windows; but I just subverted flutter via the **front door**.   So, in this case, again your actual **REAL** risk is nil from this avenue of attack by adding the proposed flag.   By the time the user has ran the compromised flutter command it is WAY too late for YOU to choose to lock the windows.  :grinning:  

The third scenario; is a "bad actor" that works for the company; this actually does present the most likely actual risk for most companies -- however; again in this case s/he probably already being inside the network has access to a lot more ways to get stuff on a machine if s/he has physical access to the boxes.   If you give me physical access to a machine, then you are toast in almost all cases.   You don't want me to have physical access to your machines if you value them.  :grinning:      Also, same MTM issues above, apply, but physical access is normally tremendously easier and safer.

So, in summary; where you didn't think the ramifications through is that if the network connection is already subverted not having a flag does not ADD ANY REAL ADDITIONAL security, and having a flag does not REMOVE ANY ADDITIONAL security -- its already too late!    And specifically, looking at Flutter, you already made the worst mistake possible you (Ian) have people run Shell Scripts, command Scripts, and Powershell scripts from the git repo directly.   Since you can't control the security of the repo -- you just gave any MTM attacker the easiest way in; long before your "window" security is even applied.   :grinning:     If you really care about security; maybe executable flutter commands shouldn't be distributed via a repo...  :grinning:      Once you actually lock the door; you can convince me that locking the windows makes some sense...   :grinning:    

So, despite this issue not actually effecting me in my current position -- I think adding a flag is a worth while item.   It allows the corporate users easier access; but does not truly reduce any security *beyond* what is already present.  :grinning:

**Comment by Hixie** [comment]
> As for the next case; if a "bad actor" is already remotely inside the network and able to MTM the traffic -- they for sure DO NOT need to MTM the flutter engine stuff to get their stuff on device.

Maybe not, but that's only because lots of other things are broken. That's not an excuse for breaking Flutter as well.

> I can think of dozens of ways to compromise a network if I have MTM access to the traffic.

I hope you report all the them so they can be stopped.

>  it would be FAR simpler to just subvert the github.com traffic

If git ignores certificate errors, that's a problem with git, which we should look into and resolve. (I seem to recall checking this and finding it worked correctly, but I could be wrong or maybe it regressed.) In any case, git having a security flaw is not an argument for adding a security flaw to Flutter.

> where you didn't think the ramifications through is that if the network connection is already subverted not having a flag does not ADD ANY REAL ADDITIONAL security, and having a flag does not REMOVE ANY ADDITIONAL security

Where you're already insecure, this flag wouldn't make it less secure. Correct. However, that's not the case I'm primarily concerned about when it comes to a flag. What I'm worried about is people whose network has been compromised but where everything else is still secure. If they don't know what is going on, they may search online for this error message, find a page intended for people working in enterprises with the security practices you describe, turn on the flag, and then have no idea that they just compromised their machine.

This happens _all the time_. This is why browser vendors, for instance, have been making it increasingly hard to ignore certificate errors.


Certificate errors are real errors with serious consequences. Ignoring them is _never_ the right solution. Anyone setting up a network infrastructure that requires users to ignore certificate errors has made a serious and fundamental error in their network infrastructure configuration. We should not be encouraging such behaviour.


We should definitely make the error messages clearer in these cases though.

**Comment by NathanaelA** [comment]
On the MTM, if I have MTM access to the traffic; their is nothing to report -- its too late; as I can change all traffic going through my box.   From injecting bad PDF's to Javascript, or even attack with POC's that are a few months old.  if I have full access to rewrite the traffic; you are screwed, it is trivial to inject anything into the stream that looks official and will be clicked, ran, or otherwise harm the user.  :grinning: 

Like I said; in this case the simplest way to MTM flutter; is just MTM github and give them a modified flutter.bat/.sh file; they pull it -- your doc's say to run it.  Bam, compromised...  :grinning:

---

I do understand your final use case; in that case this does add some security...   And there is nothing stopping you from adding to the flags; a followup question/statement.   Where they have to not only add the flag; but the flag causes them to have to manually type; "I am aware this can compromised my machine" before you let it through.  :grinning: 

---

>Certificate errors are real errors with serious consequences. Ignoring them is never the right solution. Anyone setting up a network infrastructure that requires users to ignore certificate errors has made a serious and fundamental error in their network infrastructure configuration. We should not be encouraging such behaviour.

I don't totally disagree; but I think there are exceptions.   Unfortunately we don't live in a perfect world; and currently the only way for large companies to monitor all traffic is the MTM it.  

Despite their stupidity (yes, I agree MTM'ing their own traffic is stupid).   However, I feel like you are deliberately keeping it unusable and broken for the many gov and larger clients.     These are very important clients; they tend to adopt and even sometimes help fund the development of projects...

Just a small correction; `git` by default does NOT ignore cert errors.  But just like almost every other piece of software that connects to a https connections; like wget, curl, git, npm, openssl, and yes even `Google Chrome` -- they all have a ignore cert errors flag because of big business/government.     Are you telling me that your fellow devs on the Chrome team are not aware of the security implications?   :grinning:

**Comment by Hixie** [comment]
> if I have full access to rewrite the traffic; you are screwed

Not if you correctly implement certificate checking. That's actually the exact thing that certificates prevent.

> the flag causes them to have to manually type; "I am aware this can compromised my machine" before you let it through

People have tried this kind of approach (some browsers have tried this for getting past self-signed certs, for example). It doesn't work. People just copy and paste the text from sites that say it's safe and ignore the dire warnings.

> Are you telling me that your fellow devs on the Chrome team are not aware of the security implications?

I used to work on the HTML standard and worked closely with both the Chrome team and other browser vendors. We're well aware of the security implications, that's why Flutter doesn't have a way to ignore it.

> However, I feel like you are deliberately keeping it unusable and broken for the many gov and larger clients.

As I noted above, we are working on alternatives for these environments that don't require Flutter to ignore certificate errors.

**Comment by NathanaelA** [comment]
>  if I have full access to rewrite the traffic; you are screwed
>>Not if you correctly implement certificate checking. That's actually the exact thing that certificates prevent.

I think you missed what I was saying; if I can successfully rewrite the traffic (i.e. the only way to rewrite the traffic is either ignored certs, no certs, or the ability to act like the main MTM device); then you are screwed.   Yes I fully agree certs are their in part to protect against this attack surface.   And this is where companies MTM'ng themselves do set themselves up for failure; because people at these companies can be very used to clicking through the warnings.  :grinning:      

---

>As I noted above, we are working on alternatives for these environments that don't require Flutter to ignore certificate errors.

Yes, but the question is really when?   You have a lot of things that are "planned", I've looked through the milestones, and I saw how many things even got blown off for the beta release?  :grinning:      Your team has a full plate; and then some.         At this point by not doing either -- you are saying you don't want to cater to these people who through no fault of their own are beholden to a large companies idiotic policies...   

All I'm trying to stress is that at this moment. 
1. Adding the flag does not materially drop the security in almost all of the cases.    Yes, their is one case it does; but the majority effected by this change it won't change their security profile materially and might improve the security profile in the long run by getting more people that want to work on the core.  :grinning:

2. It does allow people with gov/corp MTM'd networks to be able to use Flutter now

3. When you do add alternatives; then you disable the flag; as then you will then have a more secure way of doing it.  

If adding an alternative method to download was something you were going to release say in the next month or so -- then I would agree; there is no need to add a flag; you would have the issue solved a better way.   But anything too much longer and you are choosing to eliminate good people that might want to try and materially commit to flutter.   And right now you are trying to build the flutter community; you don't want artificial barriers stopping them...

**Comment by tabinnorway** [comment]
@Hixie 

> It's absolutely real risk. For example, it means the employer in question (or whoever is
> running the firewall) could be changing the data. It also means anyone on the "inside"
> could be doing a man-in-the-middle attack and you would be completely unaware.

Yes, and anyone using Flutter is probably relatively computer savvy and therefore has the ability to assess this risk and deal with it. You're not going to be able to make these Enterprise companies change this behavior, at least not in the near term.

Another use case for self-signed certificates inside the firewall is anti-virus and such types of software. Basically, by using self-signed certificates the software can analyze the incoming data "on the wire" (yeah, I know). May enterprise solutions use this.

> Unfortunately it would also cause people who are experiencing man-in-the-middle attacks
> to flip the switch "because it fixes my problem".

There you go assuming non-Hixie people are morons again. We are talking about developers. Most developers are quite aware that you do not "flip the switch" permanently. Why is it that so far the only development team in the world making such assumptions are yours?

As for the danger of a MTM inside a corporate firewall, it's mostly a non-issue. If I set up a network MTM, it is a lot easier to discover than if I walk into someone's office, plug in a USB key-logger and get all I want from that. Even better, most enterprises use a third-party cleaners service. I'll just pay someone who is working less than minimum wage a bunch of money to do this. Easy.

You are fighting an extremely unlikely (to the point of being zero in the real world) threat situation. It's kinda like a premature optimization. Ask Knuth about those.

**Comment by Hixie** [comment]
@NathanaelA 

> If adding an alternative method to download was something you were going to release say in the next month or so -- then I would agree; there is no need to add a flag

We hope to have downloadable archives ready sooner than that. It is an active area of development.


@tabinnorway 

> anyone using Flutter is probably relatively computer savvy and therefore has the ability to assess this risk and deal with it

Flutter is intended to be usable by a broad community including developers who are not cryptography experts.

> Most developers are quite aware that you do not "flip the switch" permanently. 

In other words, some are not. That's the problem.

> As for the danger of a MTM inside a corporate firewall, it's mostly a non-issue. 

I refer you to https://www.us-cert.gov/ncas/alerts/TA18-074A -- it's a very real active ongoing issue. Remote actors are infiltrating corporate and enterprise networks. You should not consider the "inside" of a firewall to be "safe", because that means that as soon as anyone breaches the firewall, the entire network is compromised. You may also find https://research.google.com/pubs/pub43231.html of interest.

**Comment by NathanaelA** [comment]
@hixie - Ian, that is awesome news.    I apologize for wasting your time on this issue; I would 100% agree having an alternative (secure) method to download the entire code base is the best solution.

**Comment by Hixie** [comment]
The bug is that the message is misleading; as far as I am aware that is still the case.

**Comment by PStoner3** [comment]
The last message in this conversation is from Aug 24, 2018. Today, I downloaded flutter_windows_v1.5.4-hotfix.2-stable.zip from https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.5.4-hotfix.2-stable.zip.

I am trying to evaluate the product for a new Android application that has been proposed by my company. 

I've tried to create a new project in the latest edition of VS Code (v1.34.0) and received this same message:

Running "flutter packages get" in myfirstflutterapp...          
Got TLS error trying to find package cupertino_icons at https://pub.dartlang.org.

Also tried the same in Android Studio (Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 9, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0). I had to kill instance of Android Studio (AS). I am assuming AS is having the same issue.

Are there any other updates for this issue?

**Comment by thiennhank9** [comment]
I ran cmd below then it worked: 
`set NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by blasten** [comment]
This is fixed on master.

**Comment by boyfox** [comment]
Bug appears on latest stable version on the macOS Catalina

**Comment by Paul74** [comment]
Have this issue, I'm browsing pretty much the whole Internet and still can't work it out. My pc is running behind a corporate proxy (credentials required).

Error is in android studio when launching whatever pub get/upgrade thing:
Got TLS error trying to find packagewhatever at https://pub.flutter-io.cn.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

**Comment by erperejildo** [comment]
> @amangautam1 did you check the links in my above comment?

I did and also have the issue

**Comment by erperejildo** [comment]
> Have this issue, I'm browsing pretty much the whole Internet and still can't work it out. My pc is running behind a corporate proxy (credentials required).
> 
> Error is in android studio when launching whatever pub get/upgrade thing:
> Got TLS error trying to find packagewhatever at https://pub.flutter-io.cn.
> pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

exactly same thing. I use the company laptop for which I have Bitdefender installed and cannot even stop it.

Did you fix it?

**Comment by erperejildo** [comment]
> This is fixed on master.

I' already on master but even if try to change branches it fails:

<img width="893" alt="Screenshot 2021-03-13 at 17 29 11" src="https://user-images.githubusercontent.com/5629919/111036856-b1ff0700-8421-11eb-952f-96f5e91cb5b1.png">
