### ISSUE TITLE
[Web] Autofill is filling the form immediately instead of opening the password manager

### ISSUE THREAD

**Issue by geronimol** [flutter/flutter#152879]
### Steps to reproduce

1. Run the app for web, complete the form and save your credentials in your password manager.
2. Refresh the page and click any form field.

Related issue: #114620  

### Expected results

Should give the option to pick your credentials from password manager(actually working on double click).

### Actual results

It fills the form with your credentials on the first click. Also throws error in the console:

```
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1388:3                              _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1366:3                              _generalAsCheckImplementation
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 81:5                      getProperty
lib/_engine/engine/dom.dart 2241:24                                               DomKeyboardEventExtension.get$35shiftKey
lib/_engine/engine/platform_dispatcher/view_focus_binding.dart 60:15              <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
```

### Code sample

<details open><summary>Code sample</summary>

```dart
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final formKey = GlobalKey<FormState>();
  final controllerEmail = TextEditingController();
  final controllerPassword = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        key: formKey,
        child: Column(
          children: [
            AutofillGroup(
              child: Column(
                children: [
                  TextFormField(
                    controller: controllerEmail,
                    autofillHints: const [AutofillHints.email],
                    keyboardType: TextInputType.text,
                    textInputAction: TextInputAction.next,
                    decoration: const InputDecoration(
                      label: Text('Email'),
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 15),
                  TextFormField(
                    obscureText: true,
                    controller: controllerPassword,
                    autofillHints: const [AutofillHints.password],
                    textInputAction: TextInputAction.done,
                    keyboardType: TextInputType.text,
                    decoration: const InputDecoration(
                      label: Text('Password'),
                      border: OutlineInputBorder(),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/32d99298-0f6f-4bf4-9965-309e7071ead8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 13.6.4 22G513 darwin-x64, locale es-419)
    • Flutter version 3.22.3 on channel stable at /usr/local/Caskroom/flutter/3.19.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gero/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Volumes/Latest/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.4 22G513 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @geronimol,
The error above seems to be similar to one at https://github.com/flutter/flutter/issues/149968 and it's fixed by https://github.com/flutter/engine/pull/53830. But the fix is on master channel only, so please switch to master channel and confirm this:

```
flutter channel master
flutter upgrade
```

**Comment by geronimol** [comment]
@huycozy The console errors are gone, but the autofill issue persists

**Comment by huycozy** [comment]
I checked this on my end but couldn't see that issue. I faced https://github.com/flutter/flutter/issues/66356 instead. Can you share your demo?

<details>
<summary>Demo</summary>


https://github.com/user-attachments/assets/3e856b66-edb4-4d58-97a3-d6d6c100fac0


</details>

My Flutter versions:

```console
Channel stable, 3.24.0
Channel master, 3.24.0-1.0.pre.486
```

**Comment by geronimol** [comment]
Demo:
https://github.com/user-attachments/assets/32d99298-0f6f-4bf4-9965-309e7071ead8

I can see errors in the console again, on the second attempt:

```
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1388:3                              _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1366:3                              _generalAsCheckImplementation
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 81:5                      getProperty
lib/_engine/engine/dom.dart 2241:24                                               DomKeyboardEventExtension.get$35shiftKey
lib/_engine/engine/platform_dispatcher/view_focus_binding.dart 60:15              <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
```

Flutter version: 

```
Flutter 3.24.0-1.0.pre.487 • channel master •
```

**Comment by geronimol** [comment]
Demo:
https://github.com/user-attachments/assets/32d99298-0f6f-4bf4-9965-309e7071ead8

Flutter version: 
```
Flutter 3.24.0-1.0.pre.487 • channel master •
```

**Comment by huycozy** [comment]
I am using Chrome as well. Can you share your Chrome settings on `chrome://password-manager/settings` (screenshot) like this?

<details>
<summary>password-manager/settings</summary>

![Screenshot 2024-08-08 at 11 21 46](https://github.com/user-attachments/assets/0e62990e-1a14-487f-88c9-444a2574e11e)
</details>

**Comment by geronimol** [comment]
![Captura de pantalla 2024-08-08 a la(s) 12 34 28](https://github.com/user-attachments/assets/4095aea3-4509-4b02-87d7-14b3199f1302)

Sorry it is in spanish

**Comment by huycozy** [comment]
Thanks. I still can't reproduce the issue. Labeling this to see other's input.

**Comment by yjbanov** [comment]
I don't yet know what Flutter does to cause it to fill in the form differently (I thought this was purely based on browser configuration), but will keep this open for further investigation.

**Comment by akashgk** [comment]
Can you guys try with the code i have provided on issue https://github.com/flutter/flutter/issues/160114

**Comment by akashgk** [comment]
> Thanks. I still can't reproduce the issue. Labeling this to see other's input.

Can you try from the code on this bug. I have also attached a screeen recording for the same as to how I reproduced it

https://github.com/flutter/flutter/issues/160114

**Comment by bastigerner** [comment]
Hello, we are having the same Issue. We're building a web base login and it is pretty annoying that once you click and of the fields it immediately fills the login fields with the top most Password Managers value.

Furthermore does the manager only show if you would delete your whole value or click the text field twice. So there seems to be two bugs.

Additionally we have noticed that the immediate autofill is delayed buy like 1s after you click one of the given auto fill fields.

Could we please investigate into this a little more than just leaving it open for 5 months since this is a really unuserfriendly behaviour.

![image](https://github.com/user-attachments/assets/c453c678-c1af-4891-b480-4255a60fe124)

**Comment by Ssiswent** [comment]
The same, autofill with just one click without selecting.
https://github.com/user-attachments/assets/dd46fbd6-e79f-44f9-ad95-39b8f316dd90

**Comment by bastigerner** [comment]
How come this issue still exists?
Anyone knows a workaround or maybe knows where in the code this is triggered so I could fork it?

**Comment by KevMorelli** [comment]
The issue persists to this day. I tried several possible workarounds but none of them work.
No news on a fix for this?

**Comment by DanilKarasev** [comment]
Same here. Really annoying

**Comment by FairyWorld** [comment]
I also encountered the same problem, using flutter 3.35.6

**Comment by CGSiemensEnergy** [comment]
We noticed this issue as well and identified 2 different behaviours on latest stable version. (3.35.7)

Common Step:
1. Fill out the Form with the credentials
2. Save Password in Password-Manager

Flutter Web in Debug-Mode:
- Fields are filled in automatically after they have been selected.

Flutter Web in Release-Mode:
- Here I get a window and can select the user.
- When I select it the Password Manager window disappears and reappears directly.
- I can't select the user properly because the clicks aren't recognized. I would say it only works if I click directly on the user name in the center, but even that isn't reliable. Only then are the fields filled in.
