### ISSUE TITLE
`Unexpected null value` error appears when running multiView on Flutter Web

### ISSUE THREAD

**Issue by CKunhardt** [flutter/flutter#153198]
### Steps to reproduce

Create new Flutter project on "stable" branch
Add flutter_bootstrap.js to web folder
Configure the engineInitializer to use multiViewEnabled: true
Run "flutter build web"
Run "flutter run -d chrome"

### Expected results

Example code completes without error, allows Flutter app to be loaded in a <div> with a subsequent runApp() call.

### Actual results

App experiences an uncaught exception when trying to call <app>.runApp() and crashes

### Code sample

<details open><summary>Code sample</summary>

```javascript
// flutter_bootstrap.js
{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load({
  onEntrypointLoaded: async function(engineInitializer) {
    const appRunner = await engineInitializer.initializeEngine({
      multiViewEnabled: true,
    });

    await appRunner.runApp();
  }
});
```

No changes to main.dart from initial project generation.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs
```console
When running in the Chrome Debugger:
This app is linked to the debug service: ws://127.0.0.1:49590/JGZRNP2PoDM=/ws
dom.dart:178 Rejecting promise with error: Unexpected null value.
DomConsoleExtension$124warn @ dom.dart:178
(anonymous) @ dom.dart:178
(anonymous) @ js_promise.dart:29
runUnary @ zone.dart:1661
handleError @ future_impl.dart:181
handleError @ future_impl.dart:873
_propagateToListeners @ future_impl.dart:894
[_completeError] @ future_impl.dart:674
completeError @ async_patch.dart:496
_asyncRethrow @ async_patch.dart:562
(anonymous) @ app_bootstrap.dart:56
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
(anonymous) @ async_patch.dart:578
runBinary @ zone.dart:1666
handleError @ future_impl.dart:178
handleError @ future_impl.dart:873
_propagateToListeners @ future_impl.dart:894
[_completeError] @ future_impl.dart:674
completeError @ async_patch.dart:496
_asyncRethrow @ async_patch.dart:562
(anonymous) @ initialization.dart:35
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
(anonymous) @ async_patch.dart:574
runUnary @ zone.dart:1661
handleValue @ future_impl.dart:163
handleValueCallback @ future_impl.dart:861
_propagateToListeners @ future_impl.dart:890
[_completeWithValue] @ future_impl.dart:666
(anonymous) @ future_impl.dart:736
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:179
Promise.then
_scheduleImmediateWithPromise @ async_patch.dart:178
_scheduleImmediate @ async_patch.dart:153
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1466
scheduleMicrotask @ zone.dart:1681
[_asyncCompleteWithValue] @ future_impl.dart:735
[_asyncComplete] @ future_impl.dart:695
complete @ async_patch.dart:484
_asyncReturn @ async_patch.dart:551
(anonymous) @ initialization.dart:234
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
initializeEngineUi @ initialization.dart:208
(anonymous) @ initialization.dart:39
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
(anonymous) @ initialization.dart:41
(anonymous) @ app_bootstrap.dart:57
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
(anonymous) @ app_bootstrap.dart:58
(anonymous) @ js_loader.dart:74
_callDartFunctionFast1 @ js_allow_interop_patch.dart:216
ret @ js_allow_interop_patch.dart:81
onEntrypointLoaded @ flutter_bootstrap.js:17
await in onEntrypointLoaded
didCreateEngineInitializer @ flutter_bootstrap.js:1
(anonymous) @ initialization.dart:52
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
bootstrapEngine @ initialization.dart:27
(anonymous) @ web_entrypoint.dart:19
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:9894
(anonymous) @ client.js:26180
(anonymous) @ client.js:4009
call$2 @ client.js:12381
_asyncStartSync @ client.js:3973
$call$body$main__closure @ client.js:26196
call$1 @ client.js:26109
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_add$1 @ client.js:13600
_handleData$2 @ client.js:13663
_handleData$1 @ client.js:13626
(anonymous) @ client.js:1772
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
(anonymous) @ client.js:1827
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
add$1 @ client.js:25284
call$1 @ client.js:25731
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
perform$1 @ client.js:13502
call$0 @ client.js:13561
_rootRun @ client.js:4378
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_rootRun @ client.js:4382
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_microtaskLoop @ client.js:4241
_startMicrotaskLoop @ client.js:4247
call$1 @ client.js:12258
childList
call$1 @ client.js:12268
_scheduleAsyncCallback @ client.js:4261
_rootScheduleMicrotask @ client.js:4448
scheduleMicrotask$1 @ client.js:13826
scheduleMicrotask @ client.js:4302
schedule$1 @ client.js:13533
_addPending$1 @ client.js:13312
_sendData$1 @ client.js:13125
add$1 @ client.js:12990
call$1 @ client.js:25632
call$1 @ client.js:25548
_rootRunUnary @ client.js:4401
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
call$1 @ client.js:13916
_callDartFunctionFast1 @ client.js:8307
(anonymous) @ client.js:8298
flutter_bootstrap.js:19 Uncaught (in promise) null
onEntrypointLoaded @ flutter_bootstrap.js:19
await in onEntrypointLoaded
didCreateEngineInitializer @ flutter_bootstrap.js:1
(anonymous) @ initialization.dart:52
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
bootstrapEngine @ initialization.dart:27
(anonymous) @ web_entrypoint.dart:19
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:9894
(anonymous) @ client.js:26180
(anonymous) @ client.js:4009
call$2 @ client.js:12381
_asyncStartSync @ client.js:3973
$call$body$main__closure @ client.js:26196
call$1 @ client.js:26109
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_add$1 @ client.js:13600
_handleData$2 @ client.js:13663
_handleData$1 @ client.js:13626
(anonymous) @ client.js:1772
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
(anonymous) @ client.js:1827
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
add$1 @ client.js:25284
call$1 @ client.js:25731
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
perform$1 @ client.js:13502
call$0 @ client.js:13561
_rootRun @ client.js:4378
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_rootRun @ client.js:4382
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_microtaskLoop @ client.js:4241
_startMicrotaskLoop @ client.js:4247
call$1 @ client.js:12258
childList
call$1 @ client.js:12268
_scheduleAsyncCallback @ client.js:4261
_rootScheduleMicrotask @ client.js:4448
scheduleMicrotask$1 @ client.js:13826
scheduleMicrotask @ client.js:4302
schedule$1 @ client.js:13533
_addPending$1 @ client.js:13312
_sendData$1 @ client.js:13125
add$1 @ client.js:12990
call$1 @ client.js:25632
call$1 @ client.js:25548
_rootRunUnary @ client.js:4401
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
call$1 @ client.js:13916
_callDartFunctionFast1 @ client.js:8307
(anonymous) @ client.js:8298

When running in a Dockerized container:
TypeError: Cannot read properties of null (reading 'toString')
    at Object.ajT (http://localhost:8080/main.dart.js:16971:3)
    at a04.$0 (http://localhost:8080/main.dart.js:51494:15)
    at http://localhost:8080/main.dart.js:28553:12
    at a_x.a (http://localhost:8080/main.dart.js:4181:63)
    at a_x.$2 (http://localhost:8080/main.dart.js:25737:14)
    at ZS.$1 (http://localhost:8080/main.dart.js:25731:21)
    at YH.VP (http://localhost:8080/main.dart.js:26317:33)
    at YH.vE (http://localhost:8080/main.dart.js:26320:13)
    at Xb.$0 (http://localhost:8080/main.dart.js:26077:11)
    at Object.mK (http://localhost:8080/main.dart.js:4276:39)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22621.3880], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\repos\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (10 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\244618\AppData\Local\Android\sdk
    • Platform android-34-ext10, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code, 64-bit edition (version 1.91.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.100
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by spydon** [comment]
Should be fixed by https://github.com/flutter/flutter/issues/152953
I tried with main and the issue is indeed solved there!

**Comment by huycozy** [comment]
Thanks for your report, @CKunhardt!
I checked this on master channel `3.24.0-1.0.pre.545` but didn't see the issue anymore. I think this issue has the same cause as https://github.com/flutter/flutter/issues/145410 so I will mark this as a duplicate of that issue. 

Please follow the CP request at https://github.com/flutter/flutter/issues/152953 as shared above. Once the stable hotfix release but the issue persists with `multiViewEnabled` flag enabled, please write in the comments and I will reopen this for further investigation. Thanks!

**Comment by CKunhardt** [comment]
Hi @spydon @huycozy, thanks for the replies! I just upgraded to Flutter 3.24.0-1.0.pre.547, regenerated the project and made the same changes as specified above. I'm still receiving the same error, actually. Looks like that CP has been merged into `main`, so maybe this is different?

**Comment by spydon** [comment]
> Hi @spydon @huycozy, thanks for the replies! I just upgraded to Flutter 3.24.0-1.0.pre.547, regenerated the project and made the same changes as specified above. I'm still receiving the same error, actually. Looks like that CP has been merged into `main`, so maybe this is different?
> 
> I should mention for clarity that the same behavior is occurring when I just run `flutter run -d chrome` -- just to rule out my little docker container.

Oh interesting, I only tried on main and just assumed it was in the CP. We'll have to find out which PR it is that fixes it then so that it also can be CP:ed.

**Comment by CKunhardt** [comment]
Just for clarification, I didn't CP anything myself. Just `flutter channel main` and `flutter upgrade`. You're saying it worked for you on main?

**Comment by spydon** [comment]
> Just for clarification, I didn't CP anything myself. Just `flutter channel main` and `flutter upgrade`. You're saying it worked for you on main?

Yeah, it did indeed. I thought you checked out the CP and tried from that one.

**Comment by huycozy** [comment]
@CKunhardt Perhaps we misunderstood the steps and code sample. I re-open this to verify the issue again. 

This is steps I tried:
1. Create new Flutter project
2. Update `web/index.html` file content as below:

    <details>
    <summary>index.html</summary>
    
    ```html
    <!DOCTYPE html>
    <html>
    <head>
      <!--
        If you are serving your web app in a path other than the root, change the
        href value below to reflect the base path you are serving from.
    
        The path provided below has to start and end with a slash "/" in order for
        it to work correctly.
    
        For more details:
        * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
    
        This is a placeholder for base href that will be replaced by the value of
        the `--base-href` argument provided to `flutter build`.
      -->
      <base href="$FLUTTER_BASE_HREF">
    
      <meta charset="UTF-8">
      <meta content="IE=Edge" http-equiv="X-UA-Compatible">
      <meta name="description" content="A new Flutter project.">
    
      <!-- iOS meta tags & icons -->
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="apple-mobile-web-app-status-bar-style" content="black">
      <meta name="apple-mobile-web-app-title" content="repro_stable">
      <link rel="apple-touch-icon" href="icons/Icon-192.png">
    
      <!-- Favicon -->
      <link rel="icon" type="image/png" href="favicon.png"/>
    
      <title>repro_stable</title>
      <link rel="manifest" href="manifest.json">
    </head>
    <body>
      <script src="flutter_bootstrap.js" async></script>
    
      {{flutter_js}}
      {{flutter_build_config}}
    
      _flutter.loader.load({
        onEntrypointLoaded: async function(engineInitializer) {
          const appRunner = await engineInitializer.initializeEngine({
            multiViewEnabled: true,
          });
    
          await appRunner.runApp();
        }
      });
    </body>
    </html>
    
    ```
    </details>

3. Run app with web target: `flutter run -d chrome` (remember to switch to master channel before executing command, or using your Flutter version management like alias/fvm)

### Result
- Stable 3.24.0: the error `Cannot read properties of null` appears
- Master 3.24.0-1.0.pre.547: the error doesn't appear

Can you confirm these steps? If there is any difference, please clarify. Thanks!

**Comment by CKunhardt** [comment]
@huycozy Almost exactly, although I split `flutter_bootstrap.js` into its own file under `web/`. Not sure if that's what you were implying through your code or not.

I took a screen cap video of me walking through it slowly to show I'm really not doing any extraneous steps, I even copied the code sample right from the Flutter docs! Hope it shows up OK.


https://github.com/user-attachments/assets/105a5cf2-89c6-4efa-8c04-91db3fee4194

**Comment by huycozy** [comment]
Thanks for your video that explains the steps to set up this. I can reproduce the same now. However the error is not similar to the original one, so I will paste it here and update the issue title as well.

<details>
<summary>Output log from browser console</summary>

```console
 This app is linked to the debug service: ws://127.0.0.1:49590/JGZRNP2PoDM=/ws
dom.dart:178 Rejecting promise with error: Unexpected null value.
DomConsoleExtension$124warn @ dom.dart:178
(anonymous) @ dom.dart:178
(anonymous) @ js_promise.dart:29
runUnary @ zone.dart:1661
handleError @ future_impl.dart:181
handleError @ future_impl.dart:873
_propagateToListeners @ future_impl.dart:894
[_completeError] @ future_impl.dart:674
completeError @ async_patch.dart:496
_asyncRethrow @ async_patch.dart:562
(anonymous) @ app_bootstrap.dart:56
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
(anonymous) @ async_patch.dart:578
runBinary @ zone.dart:1666
handleError @ future_impl.dart:178
handleError @ future_impl.dart:873
_propagateToListeners @ future_impl.dart:894
[_completeError] @ future_impl.dart:674
completeError @ async_patch.dart:496
_asyncRethrow @ async_patch.dart:562
(anonymous) @ initialization.dart:35
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
(anonymous) @ async_patch.dart:574
runUnary @ zone.dart:1661
handleValue @ future_impl.dart:163
handleValueCallback @ future_impl.dart:861
_propagateToListeners @ future_impl.dart:890
[_completeWithValue] @ future_impl.dart:666
(anonymous) @ future_impl.dart:736
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:179
Promise.then
_scheduleImmediateWithPromise @ async_patch.dart:178
_scheduleImmediate @ async_patch.dart:153
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1466
scheduleMicrotask @ zone.dart:1681
[_asyncCompleteWithValue] @ future_impl.dart:735
[_asyncComplete] @ future_impl.dart:695
complete @ async_patch.dart:484
_asyncReturn @ async_patch.dart:551
(anonymous) @ initialization.dart:234
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
initializeEngineUi @ initialization.dart:208
(anonymous) @ initialization.dart:39
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
(anonymous) @ initialization.dart:41
(anonymous) @ app_bootstrap.dart:57
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
(anonymous) @ app_bootstrap.dart:58
(anonymous) @ js_loader.dart:74
_callDartFunctionFast1 @ js_allow_interop_patch.dart:216
ret @ js_allow_interop_patch.dart:81
onEntrypointLoaded @ flutter_bootstrap.js:17
await in onEntrypointLoaded
didCreateEngineInitializer @ flutter_bootstrap.js:1
(anonymous) @ initialization.dart:52
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
bootstrapEngine @ initialization.dart:27
(anonymous) @ web_entrypoint.dart:19
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:9894
(anonymous) @ client.js:26180
(anonymous) @ client.js:4009
call$2 @ client.js:12381
_asyncStartSync @ client.js:3973
$call$body$main__closure @ client.js:26196
call$1 @ client.js:26109
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_add$1 @ client.js:13600
_handleData$2 @ client.js:13663
_handleData$1 @ client.js:13626
(anonymous) @ client.js:1772
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
(anonymous) @ client.js:1827
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
add$1 @ client.js:25284
call$1 @ client.js:25731
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
perform$1 @ client.js:13502
call$0 @ client.js:13561
_rootRun @ client.js:4378
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_rootRun @ client.js:4382
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_microtaskLoop @ client.js:4241
_startMicrotaskLoop @ client.js:4247
call$1 @ client.js:12258
childList
call$1 @ client.js:12268
_scheduleAsyncCallback @ client.js:4261
_rootScheduleMicrotask @ client.js:4448
scheduleMicrotask$1 @ client.js:13826
scheduleMicrotask @ client.js:4302
schedule$1 @ client.js:13533
_addPending$1 @ client.js:13312
_sendData$1 @ client.js:13125
add$1 @ client.js:12990
call$1 @ client.js:25632
call$1 @ client.js:25548
_rootRunUnary @ client.js:4401
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
call$1 @ client.js:13916
_callDartFunctionFast1 @ client.js:8307
(anonymous) @ client.js:8298
flutter_bootstrap.js:19 Uncaught (in promise) null
onEntrypointLoaded @ flutter_bootstrap.js:19
await in onEntrypointLoaded
didCreateEngineInitializer @ flutter_bootstrap.js:1
(anonymous) @ initialization.dart:52
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
bootstrapEngine @ initialization.dart:27
(anonymous) @ web_entrypoint.dart:19
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:9894
(anonymous) @ client.js:26180
(anonymous) @ client.js:4009
call$2 @ client.js:12381
_asyncStartSync @ client.js:3973
$call$body$main__closure @ client.js:26196
call$1 @ client.js:26109
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_add$1 @ client.js:13600
_handleData$2 @ client.js:13663
_handleData$1 @ client.js:13626
(anonymous) @ client.js:1772
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
(anonymous) @ client.js:1827
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
add$1 @ client.js:25284
call$1 @ client.js:25731
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
perform$1 @ client.js:13502
call$0 @ client.js:13561
_rootRun @ client.js:4378
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_rootRun @ client.js:4382
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_microtaskLoop @ client.js:4241
_startMicrotaskLoop @ client.js:4247
call$1 @ client.js:12258
childList
call$1 @ client.js:12268
_scheduleAsyncCallback @ client.js:4261
_rootScheduleMicrotask @ client.js:4448
scheduleMicrotask$1 @ client.js:13826
scheduleMicrotask @ client.js:4302
schedule$1 @ client.js:13533
_addPending$1 @ client.js:13312
_sendData$1 @ client.js:13125
add$1 @ client.js:12990
call$1 @ client.js:25632
call$1 @ client.js:25548
_rootRunUnary @ client.js:4401
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
call$1 @ client.js:13916
_callDartFunctionFast1 @ client.js:8307
(anonymous) @ client.js:8298
```
</details>

This is the sample project: [repro.zip](https://github.com/user-attachments/files/16598317/repro_stable.zip)

Reproduced this on `Channel master, 3.24.0-1.0.pre.559`.

**Comment by CKunhardt** [comment]
Thanks for the additional details @huycozy ! I was originally testing in a Dockerized container, so the initial defect reflected the Javascript console output. I wasn't sure how to pull the Dart debugger output, since the whole Chrome debugger locks out input when you enable breakpoints on unhandled exceptions, so I appreciate you filling in the details there. I've updated the initial description with all these details.

**Comment by gabrielginter** [comment]
I just tested on 3.24.1 and I experience the same issue, `embedded mode` or `mutiview mode` doesn't seem to be working:

here is the error logs in debug mode, (NOTE: same error but with less details happen on release mode):

```console
Debug service listening on ws://127.0.0.1:63107/kkeRtwtWIy4=/ws
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 606:18  nullCheck
packages/flutter/src/widgets/binding.dart 1219:44                                 wrapWithDefaultView
packages/flutter/src/widgets/binding.dart 1399:21                                 runApp
packages/message_center/main.dart 16:3                                            main$
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/my_epic_app/main.dart 11:10                                           main$
web_entrypoint.dart 24:31                                                         <fn>
lib/ui_web/ui_web/initialization.dart 41:9                                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

here is my setup:

flutter_bootstrap.js file:

```javascript
{{flutter_js}}
{{flutter_build_config}}

const workerVersion = {{flutter_service_worker_version}};

_flutter.loader.load({
  onEntrypointLoaded: async function(engineInitializer) {
    // App initialize
    const appRunner = await engineInitializer.initializeEngine({
      multiViewEnabled: true
    });

    let fcmApp = await appRunner.runApp();
    await fcmApp.addView({
      hostElement: document.getElementById('flutter-wrapper')
    });
  }
});
```

`flutter-wrapper` is a div in `body` in `index.html`.

I tried many things, and I was unable to make it work, this feels like a high priority issue as it stops the development of embedded flutter web widgets/apps.

Thanks

**Comment by ditman** [comment]
We very recently encountered this issue when going through this feature in a customer user journey. I'll add the `runWidget` documentation to the steps.

The root cause of the issue is that:

* When setting `multiViewEnabled: true` on the web,
* We don't create a `platformDispatcher.implicitView`,
* The code `platformDispatcher.implicitView!` in `wrapWithDefaultView` crashes (Unexpected null)
* The error is cryptic at this point.

I'll update the documentation, but also attempt to add an `assert` to `runApp` or `wrapWithDefaultView` so the error message while developing is more clear, and points people to the correct spot in the docs.

**Comment by ditman** [comment]
I am going to reopen this, because I'm still working to add an assertion to `runApp` to notify users when the implicitView is missing.

**Comment by ditman** [comment]
Added a more descriptive message so this use-case is mmmmaybe a little easier to debug by end users. Thanks all for testing the new multi-view embedding for the web, let us know what stuff you build with it!! 🙏
