### ISSUE TITLE
[WEB] RuntimeError: Aborted()

### ISSUE THREAD

**Issue by glaceon2000** [flutter/flutter#153333]
### Steps to reproduce

When I leave a flutter web application running untouched for a while, the app will freeze and throw this error in the console. Refreshing the tab will solve the issue. There's no animation, just a static page.

### Expected results

App running normally

### Actual results

App freezes after leaving running for a while.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="343" alt="image" src="https://github.com/user-attachments/assets/4f886093-9e42-4e56-867c-2f132427a430">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 13.6.8 22G820 darwin-arm64, locale en-VN)
    • Flutter version 3.22.0 on channel stable at /Users/mht/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (3 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mht/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Volumes/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.92.0)
    • VS Code at /Volumes/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 13.6.8 22G820 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 13.6.8 22G820 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @glaceon2000, does this happen with the counter app? If not, can you provide a complete minimal reproducible code sample so that we can properly investigate this issue? 

Also, does this occur in release mode or debug mode? How long do you typically leave the application running before you encounter this issue?

**Comment by glaceon2000** [comment]
> Hi @glaceon2000, does this happen with the counter app? If not, can you provide a complete minimal reproducible code sample so that we can properly investigate this issue?
> 
> Also, does this occur in release mode or debug mode? How long do you typically leave the application running before you encounter this issue?

Tricky thing is that it's only happening on production aka release. I haven't encountered this in debug, therefore I cannot give an example code snippet

**Comment by danagbemava-nc** [comment]
Hi @glaceon2000, can you upgrade to the latest stable version and redeploy your application to see if you still experience this issue?

**Comment by glaceon2000** [comment]
I'll try and see if it still happens. In the meantime, please don't close this

**Comment by glaceon2000** [comment]
Unfortunately it still happens :'(

**Comment by danagbemava-nc** [comment]
Hi @glaceon2000, does this happen with the counter app? And how long do you usually leave the app before this issue occurs?

**Comment by glaceon2000** [comment]
That I cannot check as it only happens in production :(

**Comment by danagbemava-nc** [comment]
Hi @glaceon2000, can you try to build your app with `flutter build web --release --source-maps` and redeploy to see if you're able to get a clearer stack trace so we can properly investigate this?

**Comment by glaceon2000** [comment]
I will apply this and report the bug next time it happens

**Comment by majdkurdi** [comment]
Are there any new updates regarding the same issue? @glaceon2000

**Comment by fatduckling** [comment]
Hi team, I'm having the exact same issue.
This is how I built my app:
```
flutter build web --release --source-maps --no-tree-shake-icons --output ../core/src/main/resources/static
```

Here is the stack trace of error:
[error.txt](https://github.com/user-attachments/files/17116286/error.txt)

You can use my live environment to reproduce the issue: https://ravageousgame.com

**Steps to reproduce:**
# Open website https://ravageousgame.com in Firefox
# Enable console logs (F12 shortcut)
# Wait 1-2 mins and the error is observed.

I waited ~5 minutes in Chrome but the error is not observed. I'll do more testing on Chrome later this week.

Please let me know if you need anything else.

**Comment by danagbemava-nc** [comment]
Hi @fatduckling, what version of flutter was used to deploy your website?

**Comment by fatduckling** [comment]
Hi, I'll check tonight when I get home. But it is the latest version if I recall correctly.

**Comment by fatduckling** [comment]
@danagbemava-nc 

This is the Flutter version I'm using to deploy my app:
```
saleem@ryzen-destroyer:~/CLionProjects/ravageous/landing-page$ flutter doctor -v
[✓] Flutter (Channel stable, 3.24.3, on LMDE 6 (faye) 6.1.0-25-amd64, locale en_AU.UTF-8)
    • Flutter version 3.24.3 on channel stable at /home/saleem/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/saleem/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/saleem/software/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/saleem/software/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /home/saleem/software/idea-IU-241.18034.62
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • LMDE 6 (faye) 6.1.0-25-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

I'll try producing a minimum reproducible project this week to help with investigation. Thanks

**Comment by fatduckling** [comment]
Hi @danagbemava-nc 
I couldn't make a very small project to reproduce the issue, so instead, I will send you my project with most of the content removed and simplified. I'm able to reproduce the issue with this issue.

Can you please check this?

[runtime_error_aborted.zip](https://github.com/user-attachments/files/17151312/runtime_error_aborted.zip)

I did the following to reproduce the issue with Apache (httpd) web server on Debian:

```
$ unzip runtime_error_aborted.zip
$ cd runtime_error_aborted/
$ flutter build web
$ mv build/web/ /var/www/html/bug
$ firefox http://localhost/bug
```

Then I opened up the console log on Firefox and waited 1 minute for the error to come up.
![image](https://github.com/user-attachments/assets/32ca3ffe-2e07-470f-a2c5-6e0c71918eb0)

Can you please check if you can reproduce as well?

**Comment by danagbemava-nc** [comment]
Hi @fatduckling, I could reproduce this on stable but either it's fixed on master or it's just taking longer to reproduce on master, can you check to see if you reproduce this on master as well?

**Comment by fatduckling** [comment]
Hi @danagbemava-nc 
The issue is still present even in master, but it takes a bit longer (~4 minutes). Also on master, we are getting different error:

```
Uncaught : Error: WebGL2RenderingContext.texSubImage2D: Argument 9 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
```

Here is the full stacktrace
[error_master.txt](https://github.com/user-attachments/files/17165028/error_master.txt)

It can be reproducible with the sample project I provided with you yesterday.
```
saleem@ryzen-destroyer:~/CLionProjects/ravageous/landing-page$ flutter doctor -v
[✓] Flutter (Channel master, 3.26.0-1.0.pre.248, on LMDE 6 (faye)
    6.1.0-25-amd64, locale en_AU.UTF-8)
    • Flutter version 3.26.0-1.0.pre.248 on channel master at
      /home/saleem/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9be22b58c4 (5 hours ago), 2024-09-27 04:22:24 -0400
    • Engine revision 7c603de2dc
    • Dart version 3.6.0 (build 3.6.0-279.0.dev)
    • DevTools version 2.40.0-dev.1
```

**Comment by grahamsmith** [comment]
I just had a spike in these issues, I wondered if it was anything to do with the canvaskit download on web?

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample in https://github.com/flutter/flutter/issues/153333#issuecomment-2377296499. It is not minimal but it doesn't seem like this happens with a minimal code sample. This happens with both wasm and canvas kit. It is easier to reproduce in Firefox but this not specific to Firefox (initial report was from chrome) 

Labeling for further investigation 

```
Uncaught : Error: WebGL2RenderingContext.texSubImage2D: Argument 9 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    Na https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:189
    CanvasKitInit https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:116
    drawPicture https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:49
    Yc http://localhost:9006/main.dart.js:19561
    aht http://localhost:9006/main.dart.js:3349
    Z http://localhost:9006/main.dart.js:26389
    o5 http://localhost:9006/main.dart.js:20414
    oJ http://localhost:9006/main.dart.js:19746
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    KR http://localhost:9006/main.dart.js:19763
    oJ http://localhost:9006/main.dart.js:19728
    qx http://localhost:9006/main.dart.js:20661
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    Y9 http://localhost:9006/main.dart.js:20663
    qx http://localhost:9006/main.dart.js:20644
    pB http://localhost:9006/main.dart.js:20831
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    Up http://localhost:9006/main.dart.js:20835
    pB http://localhost:9006/main.dart.js:20824
    mD http://localhost:9006/main.dart.js:20801
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    SM http://localhost:9006/main.dart.js:20823
    mD http://localhost:9006/main.dart.js:20792
    yO http://localhost:9006/main.dart.js:20786
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    a1_ http://localhost:9006/main.dart.js:20791
    yO http://localhost:9006/main.dart.js:20772
    rJ http://localhost:9006/main.dart.js:22774
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    a0Y http://localhost:9006/main.dart.js:22776
    rJ http://localhost:9006/main.dart.js:22766
    Xf http://localhost:9006/main.dart.js:43549
    wX http://localhost:9006/main.dart.js:39429
    wX http://localhost:9006/main.dart.js:47019
    RH http://localhost:9006/main.dart.js:39419
    aht http://localhost:9006/main.dart.js:3349
    CQ http://localhost:9006/main.dart.js:43977
    CP http://localhost:9006/main.dart.js:43981
    Hv http://localhost:9006/main.dart.js:43967
    Ro http://localhost:9006/main.dart.js:43943
    aht http://localhost:9006/main.dart.js:3348
    iq http://localhost:9006/main.dart.js:1073
    $1 http://localhost:9006/main.dart.js:22141
    anu http://localhost:9006/main.dart.js:6332
    s http://localhost:9006/main.dart.js:6323
    $0 http://localhost:9006/main.dart.js:22127
    hg http://localhost:9006/main.dart.js:22765
    hg http://localhost:9006/main.dart.js:43922
    oz http://localhost:9006/main.dart.js:43897
    oy http://localhost:9006/main.dart.js:43901
    DY http://localhost:9006/main.dart.js:38492
    $0 http://localhost:9006/main.dart.js:38509
    $0 http://localhost:9006/main.dart.js:27739
    setTimeout handler*O6 http://localhost:9006/main.dart.js:27727
    amY http://localhost:9006/main.dart.js:4485
    a6W http://localhost:9006/main.dart.js:4483
    c_ http://localhost:9006/main.dart.js:4680
    QV http://localhost:9006/main.dart.js:38457
    aht http://localhost:9006/main.dart.js:3349
    CQ http://localhost:9006/main.dart.js:43977
    $2 http://localhost:9006/main.dart.js:44018
    Z http://localhost:9006/main.dart.js:27321
    a5j http://localhost:9006/main.dart.js:182
    Ht http://localhost:9006/main.dart.js:43953
    R0 http://localhost:9006/main.dart.js:43939
    aht http://localhost:9006/main.dart.js:3349
    ir http://localhost:9006/main.dart.js:1076
    $1 http://localhost:9006/main.dart.js:22138
    anu http://localhost:9006/main.dart.js:6332
    s http://localhost:9006/main.dart.js:6323
    $0 http://localhost:9006/main.dart.js:22127
    hg http://localhost:9006/main.dart.js:22765
    hg http://localhost:9006/main.dart.js:43922
    oz http://localhost:9006/main.dart.js:43897
    oy http://localhost:9006/main.dart.js:43901
    DY http://localhost:9006/main.dart.js:38492
    kA http://localhost:9006/main.dart.js:38486
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    $1 http://localhost:9006/main.dart.js:27752
    a1b http://localhost:9006/main.dart.js:28353
    yR http://localhost:9006/main.dart.js:28356
    $0 http://localhost:9006/main.dart.js:28106
    o8 http://localhost:9006/main.dart.js:4606
    mq http://localhost:9006/main.dart.js:28039
    eM http://localhost:9006/main.dart.js:27747
    O http://localhost:9006/main.dart.js:4492
    d4 http://localhost:9006/main.dart.js:22049
main.dart.js:3196:19
```

```
Uncaught : RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    Ea https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:93
    h https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:169
    CanvasKitInit https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:116
    F https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:156
    PictureRecorder https://www.gstatic.com/flutter-canvaskit/569abc4044b84d8bab78f4ec67abfc3c9a825ce5/canvaskit.js:105
    q3 http://localhost:9006/main.dart.js:20615
    qx http://localhost:9006/main.dart.js:20656
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    Y9 http://localhost:9006/main.dart.js:20663
    qx http://localhost:9006/main.dart.js:20644
    pB http://localhost:9006/main.dart.js:20831
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    Up http://localhost:9006/main.dart.js:20835
    pB http://localhost:9006/main.dart.js:20824
    mD http://localhost:9006/main.dart.js:20801
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    SM http://localhost:9006/main.dart.js:20823
    mD http://localhost:9006/main.dart.js:20792
    yO http://localhost:9006/main.dart.js:20786
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    a1_ http://localhost:9006/main.dart.js:20791
    yO http://localhost:9006/main.dart.js:20772
    rJ http://localhost:9006/main.dart.js:22774
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    P http://localhost:9006/main.dart.js:4488
    a0Y http://localhost:9006/main.dart.js:22776
    rJ http://localhost:9006/main.dart.js:22766
    Xf http://localhost:9006/main.dart.js:43549
    wX http://localhost:9006/main.dart.js:39429
    wX http://localhost:9006/main.dart.js:47019
    RH http://localhost:9006/main.dart.js:39419
    aht http://localhost:9006/main.dart.js:3349
    CQ http://localhost:9006/main.dart.js:43977
    CP http://localhost:9006/main.dart.js:43981
    Hv http://localhost:9006/main.dart.js:43967
    Ro http://localhost:9006/main.dart.js:43943
    aht http://localhost:9006/main.dart.js:3348
    iq http://localhost:9006/main.dart.js:1073
    $1 http://localhost:9006/main.dart.js:22141
    anu http://localhost:9006/main.dart.js:6332
    s http://localhost:9006/main.dart.js:6323
    $0 http://localhost:9006/main.dart.js:22127
    hg http://localhost:9006/main.dart.js:22765
    hg http://localhost:9006/main.dart.js:43922
    oz http://localhost:9006/main.dart.js:43897
    oy http://localhost:9006/main.dart.js:43901
    DY http://localhost:9006/main.dart.js:38492
    kA http://localhost:9006/main.dart.js:38486
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    $1 http://localhost:9006/main.dart.js:27752
    a1b http://localhost:9006/main.dart.js:28353
    yR http://localhost:9006/main.dart.js:28356
    $0 http://localhost:9006/main.dart.js:28106
    o8 http://localhost:9006/main.dart.js:4606
    mq http://localhost:9006/main.dart.js:28039
    eM http://localhost:9006/main.dart.js:27747
    O http://localhost:9006/main.dart.js:4492
    d4 http://localhost:9006/main.dart.js:22049
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    $1 http://localhost:9006/main.dart.js:27752
    a1b http://localhost:9006/main.dart.js:28353
    yR http://localhost:9006/main.dart.js:28356
    $0 http://localhost:9006/main.dart.js:28106
    o8 http://localhost:9006/main.dart.js:4606
    mq http://localhost:9006/main.dart.js:28039
    $0 http://localhost:9006/main.dart.js:28075
    aon http://localhost:9006/main.dart.js:4638
    aoy http://localhost:9006/main.dart.js:4640
    $1 http://localhost:9006/main.dart.js:27711
    $0 http://localhost:9006/main.dart.js:22127
    hg http://localhost:9006/main.dart.js:22765
    hg http://localhost:9006/main.dart.js:43922
    oz http://localhost:9006/main.dart.js:43897
    oy http://localhost:9006/main.dart.js:43901
    DY http://localhost:9006/main.dart.js:38492
    kA http://localhost:9006/main.dart.js:38486
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    $1 http://localhost:9006/main.dart.js:27752
    a1b http://localhost:9006/main.dart.js:28353
    yR http://localhost:9006/main.dart.js:28356
    $0 http://localhost:9006/main.dart.js:28106
    o8 http://localhost:9006/main.dart.js:4606
    mq http://localhost:9006/main.dart.js:28039
    eM http://localhost:9006/main.dart.js:27747
    O http://localhost:9006/main.dart.js:4492
    d4 http://localhost:9006/main.dart.js:22049
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    $1 http://localhost:9006/main.dart.js:27752
    a1b http://localhost:9006/main.dart.js:28353
    yR http://localhost:9006/main.dart.js:28356
    $0 http://localhost:9006/main.dart.js:28106
    o8 http://localhost:9006/main.dart.js:4606
    mq http://localhost:9006/main.dart.js:28039
    $0 http://localhost:9006/main.dart.js:28075
    aon http://localhost:9006/main.dart.js:4638
    aoy http://localhost:9006/main.dart.js:4640
    $1 http://localhost:9006/main.dart.js:27711
    $0 http://localhost:9006/main.dart.js:22127
    hg http://localhost:9006/main.dart.js:22765
    hg http://localhost:9006/main.dart.js:43922
    oz http://localhost:9006/main.dart.js:43897
    oy http://localhost:9006/main.dart.js:43901
    DY http://localhost:9006/main.dart.js:38492
    kA http://localhost:9006/main.dart.js:38486
    s http://localhost:9006/main.dart.js:4502
    $2 http://localhost:9006/main.dart.js:27758
    $1 http://localhost:9006/main.dart.js:27752
    a1b http://localhost:9006/main.dart.js:28353
    yR http://localhost:9006/main.dart.js:28356
    $0 http://localhost:9006/main.dart.js:28106
    o8 http://localhost:9006/main.dart.js:4606
    mq http://localhost:9006/main.dart.js:28039
main.dart.js:3196:19
```
<details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
```

```
[!] Flutter (Channel master, 3.26.0-1.0.pre.263, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.26.0-1.0.pre.263 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4fdfbd4dde (26 hours ago), 2024-09-29 02:21:39 -0400
    • Engine revision 569abc4044
    • Dart version 3.6.0 (build 3.6.0-279.0.dev)
    • DevTools version 2.40.0-dev.1

```
</details>

**Comment by MaxVang** [comment]
![image](https://github.com/user-attachments/assets/91a0d740-754f-4ac2-b561-c2f61cb958e1)

Similar issue, web app freezing after a short while... seems linked to animations in our case with it freezing faster when on pages with more (constant)animations. From the error message im getting it looks like a memory leak.

**Comment by glaceon2000** [comment]
Another weird error similar to this. This is thrown when first load the web app, but when I clear cache it works fine. However, if I open it again in another tab I'll have to clear cache and reload. Because of these reasons it's impossible to reproduce:

- This error only triggers on Chrome.
- It happens to random people, but if it happens to someone then it sticks
- It only happens in production

<img width="582" alt="image" src="https://github.com/user-attachments/assets/955d1240-555e-4e5e-908a-61fa3d9452fd">
```
Uncaught Error: TypeError: null: type 'minified:Tw' is not a subtype of type 'String'
    at Object.e (main.dart.js?version=1.30.21:3475:19)
    at Object.h (main.dart.js?version=1.30.21:4265:9)
    at aBM.d7W (main.dart.js?version=1.30.21:34836:25)
    at cu7.byY (main.dart.js?version=1.30.21:63147:34)
    at cu7.Lj (main.dart.js?version=1.30.21:63150:13)
    at cie.$0 (main.dart.js?version=1.30.21:62553:11)
    at Object.a1o (main.dart.js?version=1.30.21:4955:40)
    at aS.Gw (main.dart.js?version=1.30.21:62488:3)
    at aKq.f5 (main.dart.js?version=1.30.21:62129:8)
    at Object.y (main.dart.js?version=1.30.21:4836:10)
```

**Comment by 8971-certainc** [comment]
> Another weird error similar to this. This is thrown when first load the web app, but when I clear cache it works fine. However, if I open it again in another tab I'll have to clear cache and reload. Because of these reasons it's impossible to reproduce:
> 
> * This error only triggers on Chrome.
> * It happens to random people, but if it happens to someone then it sticks
> * It only happens in production
> 
> <img alt="image" width="582" src="https://private-user-images.githubusercontent.com/51567674/393093718-955d1240-555e-4e5e-908a-61fa3d9452fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTU5NjEsIm5iZiI6MTczMzcxNTY2MSwicGF0aCI6Ii81MTU2NzY3NC8zOTMwOTM3MTgtOTU1ZDEyNDAtNTU1ZS00ZTVlLTkwOGEtNjFmYTNkOTQ1MmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAzNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOTg1MmM0ODU3NjRmOGEzOWMzZTYzNzEzN2EwNmJmYmFlMzk0YTFlMGYzNjAwNDdjMDg2MjVhNGViNjI1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lQIhPI6Sc2DWgtxCUIpKXag2LLUCmvr4ld6GwlqvIsY"> ``` Uncaught Error: TypeError: null: type 'minified:Tw' is not a subtype of type 'String' at Object.e (main.dart.js?version=1.30.21:3475:19) at Object.h (main.dart.js?version=1.30.21:4265:9) at aBM.d7W (main.dart.js?version=1.30.21:34836:25) at cu7.byY (main.dart.js?version=1.30.21:63147:34) at cu7.Lj (main.dart.js?version=1.30.21:63150:13) at cie.$0 (main.dart.js?version=1.30.21:62553:11) at Object.a1o (main.dart.js?version=1.30.21:4955:40) at aS.Gw (main.dart.js?version=1.30.21:62488:3) at aKq.f5 (main.dart.js?version=1.30.21:62129:8) at Object.y (main.dart.js?version=1.30.21:4836:10) ```

This looks unrelated to the error here.

**Comment by johsoe** [comment]
We are seeing this happening ~150 times a day on our production environment with around 1600k unique visitors :(

**Comment by fatduckling** [comment]
Hi,
I think this is fixed now.
I uploaded a reproducible project last year here: https://github.com/flutter/flutter/issues/153333#issuecomment-2377296499

In Firefox 138.0.1 and Chrome 136.0.7103.92, I can no longer see the exception being thrown in the console logs - I had the website running in the background for over an hour.

**Comment by stx** [comment]
Still happens for us.

Easily reproducible by hot restarting a big project many times in debug mode.

**Comment by mitjawd** [comment]
We are not able to reproduce the error after downgrading back to 3.38.7, which our previous working release used. We only get a behaviorally similar crash/freeze once in a while but without the Aborted() errors. After we released an update to the web app with 3.38.7 on Wednesday, the user error events have gone down as well.
