### ISSUE TITLE
[tool_crash] SocketException: Connection refused, OS Error: Connection refused, errno = 111

### ISSUE THREAD

**Issue by catalunha** [flutter/flutter#153709]
## Command
```sh
flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target /home/catalunha/heetoo/biblingo_mobile/lib/main.dart -d chrome --web-port 8080
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Connection refused, OS Error: Connection refused, errno = 111
```console
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
#4      Socket.startConnect (dart:io/socket.dart:825:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
<asynchronous suspension>
#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:30)
<asynchronous suspension>
#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:5)
<asynchronous suspension>
#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:5)
<asynchronous suspension>
#16     ResidentWebRunner.cleanupAtFinish (package:flutter_tools/src/isolated/resident_web_runner.dart:191:5)
<asynchronous suspension>
#17     ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1482:5)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:788:26)
```
```console
[✓] Flutter (Channel stable, 3.24.0, on Pop!_OS 22.04 LTS 6.9.3-76060903-generic, locale en_US.UTF-8)
    • Flutter version 3.24.0 on channel stable at /home/catalunha/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/catalunha/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/catalunha/Android/Sdk
    • Java binary at: /home/catalunha/development/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/catalunha/development/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.92.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Pop!_OS 22.04 LTS 6.9.3-76060903-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.5.2+90
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
audio_session-0.1.21
audioplayers-6.0.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.0
audioplayers_windows-4.0.0
cached_video_player_plus-3.0.3
chargebee_flutter-0.4.5
firebase_analytics-11.2.1
firebase_analytics_web-0.5.9+1
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_messaging-15.0.4
firebase_messaging_web-3.8.12
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_secure_storage-8.1.0
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-2.1.1
flutter_sound-9.6.0
flutter_sound_web-9.6.0
intercom_flutter-8.1.3
intercom_flutter_web-1.1.1
package_info_plus-8.0.1
path_provider-2.1.4
path_provider_android-2.2.9
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.8
permission_handler_apple-9.4.5
permission_handler_html-0.1.2
permission_handler_windows-0.2.1
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.8
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.9.1
video_player_android-2.6.0
video_player_avfoundation-2.6.1
video_player_web-2.3.2
wakelock_plus-1.2.7

**Comment by huycozy** [comment]
Hi @catalunha 
There was an issue at https://github.com/flutter/flutter/issues/153064 that had a similar crash stack trace but the exception message is not the same. It has been fixed on Flutter master channel so you can try switching to master channel and retry.

**Comment by andrewkolos** [comment]
This may be still happening on 3.24.1.

@catalunha could you tell us what you are doing/seeing when this crash happens? Is it when quitting out of flutter run (or stopping debugging through VSCode)?
