### ISSUE TITLE
Set up 10 new Linux hosts in the try pool and connect mokey devices to them

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#154014]
The version of Linux should be the same as on the other Linux hosts in the lab.

**Comment by zanderso** [comment]
Hey @kentnguyen99, it looks like the corp dns ticket was resolved. Please let me know if there's anything else I need to do to move this along.

**Comment by kentnguyen99** [comment]
@zanderso, We still have another issue that all machines in the Device lab could not connecting to Salt master after network changed last week. There is a ticket opened and being working on by Network teams. https://gutsv3.corp.google.com/#ticket/228663253

**Comment by kentnguyen99** [comment]
@zanderso All new 10 Linux Bots are online and ready for production. 

Hostname:
flutter-devicelab-linux-64.mtv.corp.google.com
flutter-devicelab-linux-65.mtv.corp.google.com
flutter-devicelab-linux-66.mtv.corp.google.com
flutter-devicelab-linux-67.mtv.corp.google.com
flutter-devicelab-linux-68.mtv.corp.google.com
flutter-devicelab-linux-69.mtv.corp.google.com
flutter-devicelab-linux-70.mtv.corp.google.com
flutter-devicelab-linux-71.mtv.corp.google.com
flutter-devicelab-linux-72.mtv.corp.google.com
flutter-devicelab-linux-73.mtv.corp.google.com

**Comment by zanderso** [comment]
Thanks!

**Comment by kentnguyen99** [comment]
All ten new Linux Bots are online and have been rolled out production, ticket completed and closed.
