### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRDependency while building app with Flutter News Toolkit

### ISSUE THREAD

**Issue by daachet** [flutter/flutter#154291]
### Steps to reproduce

1. Make a fresh install of Flutter News Toolkit
2. Run app in development mode

### Expected results

Succesfull Build

### Actual results

```
Launching lib/main/main_development.dart on iPhone 15 in debug mode...
Xcode build done.                                           15,4s
Failed to build iOS app
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FIRDependency

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15.

Exited (1).
```

### Code sample

<details open><summary>Code sample</summary>

```dart
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'FirebaseFirestore/WithLeveldb', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.3.0'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |build_configuration|
      # GoogleSignIn does not support arm64 simulators.
      # https://github.com/flutter/flutter/issues/85713
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'

      # You can enable the permissions needed here. For example to enable camera
      # permission, just remove the `#` character in front so it looks like this:
      #
      # ## dart: PermissionGroup.camera
      # 'PERMISSION_CAMERA=1'
      #
      #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=1',
       
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=1',   
        
        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        # 'PERMISSION_CRITICAL_ALERTS=1'
      ]
    end
  end
end

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  news_momsapp flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale ru-RU)
    • Flutter version 3.24.1 on channel stable at /opt/homebrew/Caskroom/flutter/3.16.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (8 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dc/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • iPhone (D) (mobile)             • 00008110-000620DC3CD9401E            • ios            • iOS 17.5.1 21F90
    • iPhone 15 (mobile)              • FFA35DC2-C52E-460D-917D-0C96D54CE786 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.85
    ! Error: Browsing on the local area network for Apple Watch — D. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @daachet, I built [flutter_news_example](https://github.com/flutter/news_toolkit/tree/main/flutter_news_example) and saw it succeed. Can you also try and confirm? If the issue persists, can you provide the output of `flutter run -v`? Thanks!

**Comment by daachet** [comment]
Hi @huycozy, with [flutter_news_example](https://github.com/flutter/news_toolkit/tree/main/flutter_news_example) build also failed but another error appears:

`Launching lib/main/main_development.dart on iPhone 15 Pro Max in debug mode...
Updating minimum iOS deployment target to 12.0.
Upgrading project.pbxproj
Upgrading AppFrameworkInfo.plist
Upgrading Podfile
Updating project for Xcode compatibility.
Upgrading project.pbxproj
ios/Runner/AppDelegate.swift uses the deprecated @UIApplicationMain attribute, updating.
Xcode build done.                                           25,7s
Failed to build iOS app
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/win32-5.0.9/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

Exited (1).`

**Comment by darshankawar** [comment]
@daachet 
It looks to me dependency conflict issue at your end. Some of your project's dependency probably depends on older version of win32 package. Can you try running `flutter pub upgrade` and check if it helps ?

**Comment by daachet** [comment]
@darshankawar thank you for your suggestions
I have MacOS Sonoma with M2 chip so win32 packages is not relevant in my case.
Also `flutter pub upgrade` didn't help.

**Comment by daachet** [comment]
Also while compiling for Android I see the list of errors regarding Android SDK version.

build.gradle declares

```
android {
    compileSdkVersion 33
```

but:
```
Your project is configured to compile against Android SDK 33, but the following plugin(s) require to be compiled against a higher Android SDK version:
- android_intent_plus compiles against Android SDK 34
- firebase_analytics compiles against Android SDK 34
- firebase_auth compiles against Android SDK 34
- firebase_core compiles against Android SDK 34
- firebase_crashlytics compiles against Android SDK 34
- firebase_dynamic_links compiles against Android SDK 34
- firebase_messaging compiles against Android SDK 34
- flutter_secure_storage compiles against Android SDK 34
- google_sign_in_android compiles against Android SDK 34
- in_app_purchase_android compiles against Android SDK 34
- path_provider_android compiles against Android SDK 34
- permission_handler_android compiles against Android SDK 34
- share_plus compiles against Android SDK 34
- shared_preferences_android compiles against Android SDK 34
- sign_in_with_apple compiles against Android SDK 34
- sqflite compiles against Android SDK 34
- url_launcher_android compiles against Android SDK 34
- video_player_android compiles against Android SDK 34
- webview_flutter_android compiles against Android SDK 34

```

**Comment by darshankawar** [comment]
> but:
> 
> ```
> Your project is configured to compile against Android SDK 33, but the following plugin(s) require to be compiled a
> ```

This suggests why you are seeing the log. 



> Failed to build iOS app
> [   +2 ms] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FIRDependency

This could be also due to the xcode version and this symbol have a dependency on a particular xcode version. Since you are on Xcode 15.4 which is latest.

**Comment by daachet** [comment]
@darshankawar Xcode 15 is the only version supported with Sonoma, so there is no option to use another one in my case. 
Also I tried a trick with 
```
dependency_overrides:
  win32: ^5.5.4
```
Throws the same error.

**Comment by huycozy** [comment]
@daachet Can you please provide the error output after upgrading `win32` package? I also faced that `win32` dependency error but it was solved after I did upgrade the package. On my end, I added these:

```
dependencies:
  # other packages 
  archive: ^3.6.1
  win32: ^5.5.4
```

**Comment by daachet** [comment]
@huycozy still the same, please see attached screenshot
<img width="640" alt="news_error" src="https://github.com/user-attachments/assets/96d5da65-7b92-4764-a320-f84a1c00fdff">

**Comment by huycozy** [comment]
>Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FIRDependency

**Comment by huycozy** [comment]
>Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FIRDependency

This is most likely an issue with FirebaseCore Pod. Can you confirm that you have configured Firebase as mentioned at https://flutter.github.io/news_toolkit/#configure-firebase?

**Comment by daachet** [comment]
Sure, I have configured Firebase exactly as it was described in the documentation
![Uploading Снимок экрана 2024-09-05 в 21.44.08.png…]()

**Comment by huycozy** [comment]
Thanks for the update. I will label this issue to consult insight from others.

**Comment by matiasleyba** [comment]
Hi @daachet 👋🏻 
The problems you are seeing are due to the version of flutter you are using, I suggest you try flutter 3.22.2.
Anyway we are working on updating the toolkit to support the latest version of flutter, this should be done soon, probably next week.

**Comment by GP4cK** [comment]
I have the same issue with XCode 16 and flutter 3.24.3

**Comment by matiasleyba** [comment]
Could you try it with the latest version of the toolkit [1.0.14](https://brickhub.dev/bricks/flutter_news_template)? 

@daachet  @GP4cK

**Comment by GP4cK** [comment]
I wasn't using the toolkit but by studying the diff, I saw that we also had this line in our `ios/Podfile`:
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.10.0'

After upgrading to v11, it fixed the issue.

**Comment by matiasleyba** [comment]
Closing the issue as it should be resolved using the latest version of the template, feel free to reopen the issue if the problem persists.
