### ISSUE TITLE
local_auth header not found when deploying to iOS Device

### ISSUE THREAD

**Issue by AppleEducate** [flutter/flutter#15532]
## Steps to Reproduce

1. In Visual Studio Code add the plugin "local_auth: "^0.2.0"" to pod spec.

<img width="307" alt="screen shot 2018-03-14 at 3 52 45 pm" src="https://user-images.githubusercontent.com/31253215/37427426-d07fd876-279f-11e8-9b60-03b7d3a8f2f6.png">

2. Get Flutter Packages
3. Select iOS Device as Target
4. Press Run in Visual Studio Code / Debug Screen
<img width="1123" alt="screen shot 2018-03-14 at 3 54 29 pm" src="https://user-images.githubusercontent.com/31253215/37427503-06ce8f3a-27a0-11e8-9723-e7b4a960cfb3.png">

5. Open Workspace in Xcode and Build and Run

<p align="center">
<img width="524" alt="screen shot 2018-03-14 at 3 49 33 pm" src="https://user-images.githubusercontent.com/31253215/37427360-9536b212-279f-11e8-9bfa-07a0aca7c195.png">
<img width="829" alt="screen shot 2018-03-14 at 3 39 41 pm" src="https://user-images.githubusercontent.com/31253215/37427361-95444a76-279f-11e8-9542-506f2155f422.png">
</p>

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.21.0)
[✓] Connected devices (3 available)

• No issues found!
exit code 0

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by AppleEducate** [comment]
I believe the issue #15168 is released.

@abogdanovich1 May have the answer:

"@theEpicality I found a workaround if you are still having issues.
The problem is that the .h files are missing from the "headers" directory in the iOS files. I looked up the missing .h files from the github repo and manually added all the missing ones. Built and it ran just fine! here's a screenshot of where I put mine
screen shot 2018-03-07 at 5 16 35 pm

In the screenshot provided, the project previously only had the "google_sign_in-umbrella.h" file in it. I simply added "GoogleSignInPlugin.h" from github, as well as the .h files for auth, database, storage, core, and analytics into their respective directories.

Hope that helps!"

Not sure but I believe it is the way Flutter is generating the headers for the iOS Target.

**Comment by theEpicality** [comment]
Pretty sure this has been fixed in the Master channel. Are you on it?

**Comment by AppleEducate** [comment]
Thats the channel I have been using, I have upgraded flutter and continued to test. It works when I target Android but on IOS any package I add it does not find the Header when I go to build.

**Comment by theEpicality** [comment]
Could [this](https://stackoverflow.com/questions/49163614/flutter-xcode-build-failure-after-adding-1st-party-dependency/49274856#49274856) be of any help?

**Comment by AppleEducate** [comment]
I think it will. Looks like I created the project prior to the fix. Thanks for the help!

**Comment by theEpicality** [comment]
Awesome! I'm glad you were able to fix it!

**Comment by AppleEducate** [comment]
For Future Reference: 

I think this is a known issue https://github.com/flutter/flutter/issues/15099#issuecomment-372375566

To apply the fix in #15437 to a Swift-based Flutter project created before the fix landed, add [these lines] to ios/Podfile.
Which I think means https://github.com/mravn-google/flutter/blob/e0c73220a6f69d341ce436244212277d83bc189b/packages/flutter_tools/templates/cocoapods/Podfile-swift#L70-L73

 # workaround for https://github.com/CocoaPods/CocoaPods/issues/7463
 target.headers_build_phase.files.each do |file|
   file.settings = { 'ATTRIBUTES' => ['Public'] }
 end

This goes at the end of the Pod file under enable BitCode: https://stackoverflow.com/a/49274856/7303311

**Comment by itchyfingertips** [comment]
No, that does not fix it for me! 

What i have been noticed is that if i create flutter project objc for iOS everything works fine, but if i create project with swift on iOS (flutter create -i swift myapp) then it breaks and I get this error. 

You can easily try this by creating new project:
1) _flutter create -i swift myapp_
add this package: 
2) _flutter_facebook_login: 1.1.0_

Add this to podfile:
3)_target.headers_build_phase.files.each do |file|
file.settings = { 'ATTRIBUTES' => ['Public'] }
end_

and run this command
4) _flutter build ios_

it will crash saying:

 /Users/zigmarsdzerve/code/light_tale/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:24:9: fatal error: 'BridgeAPI/FBSDKBridgeAPIProtocol.h' file not found
