### ISSUE TITLE
[Impeller] libImpeller: Crash in FreeType during release of a typography context.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#157208]
Reported when creating and releasing a single typographer context:

```
#1  0x00007ffff7ce42b1 in SkTypeface_FreeTypeStream::~SkTypeface_FreeTypeStream() () from libimpeller.so
#2  0x00007ffff7ce42e9 in SkTypeface_FreeTypeStream::~SkTypeface_FreeTypeStream() () from libimpeller.so
#3  0x00007ffff7d4b58d in skia::textlayout::TypefaceFontStyleSet::~TypefaceFontStyleSet() () from libimpeller.so
#4  0x00007ffff7d4b436 in skia::textlayout::TypefaceFontProvider::~TypefaceFontProvider() () from libimpeller.so
#5  0x00007ffff7e8b086 in txt::FontCollection::~FontCollection() ()
   from libimpeller.so
#6  0x00007ffff7a8dbd9 in impeller::interop::TypographyContext::~TypographyContext() () from libimpeller.so
```

cc @lyceel

[This test should be creating a collecting a context](https://github.com/flutter/engine/blob/08170c44b0f8932cadf8c7e01f139781c571530c/impeller/toolkit/interop/impeller_unittests.cc#L248) so it is unclear what is going on here. Debugging.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/56411

**Comment by lyceel** [comment]
Still seeing this issue in our code:

Thread 1 "har-rendering-p" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7abd8e9 in fml::NonOwnedMapping::~NonOwnedMapping() ()
   from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#2  0x00007ffff7c2a4a7 in SkMemoryStream::~SkMemoryStream() ()
   from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#3  0x00007ffff7cedff1 in SkTypeface_FreeTypeStream::~SkTypeface_FreeTypeStream() () from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#4  0x00007ffff7cee029 in SkTypeface_FreeTypeStream::~SkTypeface_FreeTypeStream() () from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#5  0x00007ffff7d5537d in skia::textlayout::TypefaceFontStyleSet::~TypefaceFontStyleSet() () from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#6  0x00007ffff7d55226 in skia::textlayout::TypefaceFontProvider::~TypefaceFontProvider() () from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#7  0x00007ffff7e99ec6 in txt::FontCollection::~FontCollection() ()
   from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#8  0x00007ffff7a964b9 in impeller::interop::TypographyContext::~TypographyContext() () from /mnt/build/flutter/src/out/host_debug/libimpeller.so
#9  0x0000555555f0060e in impeller::typography_context::{impl#2}::drop (
    self=0x7fffffffb4b0)
    at crates/framework/graphics/impeller/src/typography_context.rs:62
#10 0x0000555555ebbafb in core::ptr::drop_in_place<impeller::typography_context::TypographyContext> ()
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ptr/mod.rs:498

**Comment by lyceel** [comment]
Note this occurs with static data (e.g.: passing NULL) as the release callback.
