### ISSUE TITLE
Safe area with keyboard showing has excess padding above the keyboard on iPhone X

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#15947]
On phones that have a "Safe Area" at the bottom, such as the iPhone X, the safe area seems to still be respected even when the keyboard shows.  

This behavior can be seen with the following build method:
```dart
@override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Safe Area Test"),
      ),
      body: new Builder(
        builder: (BuildContext context) {
          return new SafeArea(
            child: new Stack(
              children: <Widget>[
                new Positioned(
                  left: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  height: 60.0,
                  child: new Container(
                    padding: const EdgeInsets.symmetric(
                        vertical: 10.0, horizontal: 5.0),
                    color: Colors.yellow,
                    child: new Center(
                      child: new Container(
                        decoration: new BoxDecoration(
                          color: Colors.white,
                          borderRadius: new BorderRadius.circular(20.0),
                        ),
                        padding: const EdgeInsets.only(left: 10.0, right: 0.0),
                        height: 50.0,
                        child: new Row(
                          children: <Widget>[
                            new Expanded(
                              child: new TextField(
                                decoration: new InputDecoration(
                                  border: InputBorder.none,
                                ),
                              ),
                            ),
                            new Container(
                              width: 40.0,
                              height: 40.0,
                              child: new Material(
                                borderRadius: new BorderRadius.circular(20.0),
                                type: MaterialType.transparency,
                                child: new IconButton(
                                  onPressed: () {
                                  },
                                  icon: new Icon(Icons.arrow_upward),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
```

And an image of the described issue:
<img width="410" alt="screen shot 2018-03-26 at 3 34 12 pm" src="https://user-images.githubusercontent.com/9346834/37928813-1cc1b4dc-310c-11e8-94a8-3e518d85e755.png">

## Steps to Reproduce
- Build a screen with a safe area and a text field aligned to the bottom, the sample code above has it.
- Click into the textfield so the keyboard appears
- See described issue

### flutter run

```
Launching lib/main.dart on iPhone X in debug mode...
Syncing files to device iPhone X...                          2.1s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```

### flutter analyze
```
Analyzing /Users/KG/Developer/Mine/testing_safe_to_delete_all_contents/keyboard_safe_area_test...
No issues found!
Ran in 6.2s
```

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.2.5-pre.41, on Mac OS X 10.12.6 16G1212, locale en-US)
    • Flutter version 0.2.5-pre.41 at /Users/KG/Developer/Flutter/flutter
    • Framework revision 2171fcb882 (2 days ago), 2018-03-25 00:04:24 -0700
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0
```

**Comment by xster** [comment]
cc @cbracken

**Comment by bhlvoong** [comment]
Also experiencing this, it'd be nice to also incorporate some form of keyboardDismissMode with a ListView.  The input area should also follow the dragging motion similar to an inputAccessoryView.

**Comment by zoechi** [comment]
Sorry for the late response. There were some related changes.
Is this still an issue in recent Flutter versions?

**Comment by nick-harris** [comment]
Yes this is still an issue with the project I am working on.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.25.0)
[✓] Connected devices (1 available)

**Comment by KevinTheGray** [comment]
also confirming that it is still an issue for me as well

```
[✓] Flutter (Channel master, v0.5.8-pre.61, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.8-pre.61 at /Users/KG/Developer/Flutter/flutter
    • Framework revision b8b6d4166c (16 hours ago), 2018-07-17 18:07:54 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25
```

**Comment by markmooibroek** [comment]
I also experience this on the master and beta channels

**Comment by zoechi** [comment]
#18562 looks related that was merged 4 days ago but that should be included in v0.5.8-pre.115
You could try setting a different `scrollPadding` value.

**Comment by markmooibroek** [comment]
Don't think scrollPadding has anything to do with this issue. In my specific case i have a button outside the ListView and sticked to the bottom and when the keyboard appears it looks funky ><

<img width="395" alt="screen shot 2018-07-24 at 08 15 28" src="https://user-images.githubusercontent.com/1412238/43120246-d4b8358c-8f19-11e8-83e1-9a061860ddf4.png">

<img width="408" alt="screen shot 2018-07-24 at 08 15 34" src="https://user-images.githubusercontent.com/1412238/43120247-d4d296ac-8f19-11e8-8ce9-40ecd5fa9707.png">

**Comment by xster** [comment]
@cbracken I think we need another condition at https://github.com/flutter/flutter/blob/da0e898da9c329192cd1ef4f8fe6e7d03a952adc/packages/flutter/lib/src/material/scaffold.dart#L1443 for if `widget.resizeToAvoidBottomPadding` is true and `mediaQuery.viewInsets.bottom > 0` (though ideally subtract mediaQuery.viewInsets from mediaQuery.padding). Does that sound right?

**Comment by markmooibroek** [comment]
If I move my buttons into the Scaffold.persistentFooterButtons the bottom padding will go away when the keyboard shows, but im left with a divider I don't want :-) So adding something to the `removeBottomPadding ` as @xster suggest seems the way to go

<img width="378" alt="screen shot 2018-07-27 at 15 41 30" src="https://user-images.githubusercontent.com/1412238/43324108-9c4af936-91b3-11e8-84f8-6e26a04a583a.png">

**Comment by wwwdata** [comment]
A super easy fix would also be to manually apply the required safe area padding and check whether the keyboard is currently open with `MediaQuery`.

You can find out the current keyboard height with `MediaQuery.of(context).viewInsets.bottom > 0.0`

If that is the case you just don't apply the safe area, which you can get with `MediaQuery.of(context).padding.bottom`

You could even create a custom widget that does this for you. But in my opinion I would add an option the the `SafeArea` widget that allows to remove the `bottom` safe area when the keyboard is open

I inserted my check into the `didChangeDependnecies` method.

**Comment by markmooibroek** [comment]
Thanks @wwwdata, that worked like magic :-)

**Comment by ma-rp** [comment]
@wwwdata can you please provide an example of your proposal?

**Comment by wwwdata** [comment]
@ma-rp it is very easy. You can either make a custom `SafeArea` Widget that takes in a `child` Widget. Or if you just need it once, use a stateful component and then do it like this:

```dart
double _safeAreaHeight;

@override
void initState() {
  super.initState();
  _safeAreaHeight = MediaQuery.of(context).padding.bottom;
}

@override
void didChangeDependencies() {
  super.didChangeDependencies();
  final bool isKeyboardVisible = MediaQuery.of(context).viewInsets.bottom > 0.0;
  if (isKeyboardVisible && _safeAreaHeight > 0.0)) {
    setState(() {
      _safeAreaHeight = 0.0;
    });
  } else if (!isKeyboardVisible && _safeAreaHeight == 0.0) {
    setState(() {
      _safeAreaHeight = MediaQuery.of(context).padding.bottom;
    });
  }
}
```

and then in your build method, use that `_safeAreaHeight` variable as padding manually. 

But if you need this behaviour more often, just do a small custom stateful component that does this check for you and renders a `child` Widget with a surrounding `Padding` Widget. That's it.

**Comment by SteveAlexander** [comment]
@zoechi If it's correct that https://github.com/flutter/flutter/pull/18562 caused this problem, what is the right thing to do? Would you revert that PR until it has been improved to not cause this problem?

I'll try backing out the PR on my local branch, and see if it is the cause.

**Comment by SteveAlexander** [comment]
@goderbauer I wonder if you'd mind taking a look at this issue? It's possible it's related to your PR https://github.com/flutter/flutter/pull/18562

**Comment by SteveAlexander** [comment]
@Norbert515 / @goderbauer I just tried reproducing the problem with and without the changes in PR https://github.com/flutter/flutter/pull/18562/ and the problem this issue is about is still there without the changes.

@zoechi After an empirical test, I'm pretty sure this isn't to do with that PR

**Comment by cbracken** [comment]
@xster missed your [last comment](https://github.com/flutter/flutter/issues/15947#issuecomment-407608275) while I was out in Japan. Your proposal sounds right to me; that looks like an oversight on my part from back when this was added.

**Comment by cbracken** [comment]
Sent out a fix for this in flutter/engine#6297.

**Comment by cbracken** [comment]
The fix has landed. When the engine rolls to the framework, this will be available on `master`.

**Comment by GaryQian** [comment]
Fixed by: https://github.com/flutter/engine/pull/6297

**Comment by arlindiDev** [comment]
@cbracken I am still facing this issue.
I am on flutter version  `1.19.0-4.1.pre`
