### ISSUE TITLE
After upgrade to 3.27 android app become to much slow mostly unresponsive

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#160153]
### Steps to reproduce

After upgrading to version 3.27, the build does not work properly.

### Expected results

the should not hang or crash 

### Actual results

app very slow and crashing

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by hasanbasribayat** [comment]
Same here!

It's because [the Impeller engine comes enabled by default in 3.27](https://medium.com/flutter/whats-new-in-flutter-3-27-28341129570c#74c8). Disabling Impeller fixes the bug.

But, isn't it supposed to be stable enough to use?

**Comment by darshankawar** [comment]
@alihassan143 
Can you provide some details, information of slowness or app hanging ? What device does this occur on ? Can you also provide us reproducible code sample that shows the behavior ? Per above comment, is it related to impeller at your end too ? ie, with and without it, you get different behavior ?

**Comment by alihassan143** [comment]
when building app with and releasing app on playstore 
the totally stuck on the screen no dilaog navigation everything not working correctly you can test this behaviour or vivo y21 device 
cannot provide code due to some project but this issue happening once updated to latest version 
after downgrading to old version everything become normal

**Comment by hasanbasribayat** [comment]
@darshankawar  Even the simplest code is janky right now.

### Code
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text('Home')),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.of(context).push(
          MaterialPageRoute(builder: (context) => DetailsPage()),
        ),
      ),
    );
  }
}

class DetailsPage extends StatelessWidget {
  const DetailsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      backgroundColor: Colors.amber,
      body: Center(child: Text('Details')),
    );
  }
}
```

### Emulator
- Pixel 8 Pro API 35 (android-arm64-v8a emulator) - 2GB RAM - 12GB Storage

### Output

#### With Impeller
https://github.com/user-attachments/assets/b4da542c-14a6-4dd2-a3ae-8e4196cd18ee

#### Without Impeller
https://github.com/user-attachments/assets/84d2c642-96fc-4d9a-8745-c73976b1e617

**Comment by publio-bejao** [comment]
We are also experiencing performance drops and visual glitches in some cases (blurs and shadows, especially with scrolls), but only on certain devices. By disabling Impeller through the metadata in the manifest, everything seems to be resolved and back to normal. 

Tested on a POCO X3 with an Adreno 618 GPU.

**Comment by t01t** [comment]
I ended up disabling the Impeller engine, for now

placing the following in your AndroidManifest.xml file

`<meta-data android:name="io.flutter.embedding.android.EnableImpeller" android:value="false"/>`

**Comment by t01t** [comment]
Samsung A20 GPU:Mali-G71
https://github.com/user-attachments/assets/bf07a269-4b53-47be-b097-675b7c9d2126

**Comment by NikhilKukreja26** [comment]
I am also facing this issue.

**Comment by jonahwilliams** [comment]
@publio-bejao  for that device, we are cherry picking a change to disable impeller.

For emulator bugs, also please report the emulator binary version. Vulkan on emulators has been ... challenging. If the emulator is just slow for you, while I would still like bug reports (so I can forward them to Android folks) there isn't much we can do there. For now I would recommend disabling Impeller if its a problem.

**Comment by krll-kov** [comment]
The problem is that even after disabling impeller on Flutter 3.27.0 app feels laggy. Both impeller and Skia are bad with new Flutter version.

i downgraded to Flutter 3.24.5 and app became super fast and responsive , i don't think this is related to Impeller, there's something wrong with Flutter itself.

With 3.24.5 i tested both engines and they are both perfect, super fast and optimized (Except for green glitches on Samsung with that old Impeller) 
```
flutter run --enable-impeller
flutter run --no-enable-impeller
```

Devices: Pixel 7a and Samsung A12

**Comment by krll-kov** [comment]
> Same here. I think impeller not ready for now, it seems to not tested enough.

Maybe it's not the impeller, try switching to Flutter 3.24.5 and running your app with flutter **run --enable-impeller --release**, for me even debug builds work as snappy as release ones with old SDK with Impeller and Skia

**Comment by krll-kov** [comment]
> @krll-kov I think you'll need to file a new bug.

But what do i describe there? What data do i need collect for flutter team for this?

**Comment by jonahwilliams** [comment]
please try reading the issue template

**Comment by darshankawar** [comment]
> Even the simplest code is janky right now.

I tried this code sample on stable 3.24.5 and on 3.27.0 with and without impeller running on Pixel XL api 35 emulator, but I didn't see the janky behavior.


https://github.com/user-attachments/assets/52d71ffa-95cd-42f8-80ae-e889a443a45e

We also tried on Pixel 7 api 35 physical device with which we didn't get the reported behavior. Looks more specific to the devices mentioned in the comments, so I'll keep the issue open for team's tracking.

**Comment by krll-kov** [comment]
> > Even the simplest code is janky right now.
> 
> I tried this code sample on stable 3.24.5 and on 3.27.0 with and without impeller running on Pixel XL api 35 emulator, but I didn't see the janky behavior.
> 
>  160153.mov 
> We also tried on Pixel 7 api 35 physical device with which we didn't get the reported behavior. Looks more specific to the devices mentioned in the comments, so I'll keep the issue open for team's tracking.

https://github.com/flutter/flutter/issues/160153

Can you try more complex code sample? Both with impeller and skia

**Comment by Xelorium** [comment]
Having the same issue here.

**Comment by IliaKhuzhakhmetov** [comment]
After upgrading to version 3.27.0 from version 3.24.3 I got similar behavior on the emulator as the author, it becomes very inconvenient to test in Debug mode, and also profile mode does not help, noticeable FPS drop still occurs. I'm back on the version 3.24.3 - flying normally

**Comment by jonahwilliams** [comment]
Update: we think this issue will be fixed by [#57213 ](https://github.com/flutter/engine/pull/57213)

**Comment by ekuleshov** [comment]
@jonahwilliams was there some specific Vulkan feature that need to be present on device?

I'm getting the UI slowness reports from users running app on Samsung TM-220 devices, but not sure what to check for.

**Comment by jonahwilliams** [comment]
@ekuleshov this bug seems to mostly down to emulator performance, which we believe will be fixed by the cherry pick above (not released yet). You could try the following change to the android manifest to disable Android SurfaceControl:

```
<meta-data
    android:name="io.flutter.embedding.android.DisableSurfaceControl"
    android:value="true" />
```

However the issue you are encountering may be unrelated, and we'd need a full issue report to work though it.

**Comment by ekuleshov** [comment]
> You could try the following change to the android manifest to disable Android SurfaceControl

I'm adding that too based on other's reports that matched with my own ANRs stack traces.
Though some description what does that switch do would be good to...

> However the issue you are encountering may be unrelated, and we'd need a full issue report to work though it.

I don't have any details for it. The UI interactions, including button pressed and screen transitions are taking 10..15 seconds to complete according to users, but that's may not be long enough to trigger Android's ANR in Crashlytics, so no details.

**Comment by jonahwilliams** [comment]
We think this issue is fixed by the latest hotfix release. however, as we don't have a repro we'll need to rely on the original reporters to try their applications.

**Comment by erdemtas-et** [comment]
I can confirm that from 3.27.0 to 3.24.5 definitely increased the performance and smoothness in our app even in debug mode. Probably impeller issue.

**Comment by alihassan143** [comment]
lagging issue is resolved ut now animation are very slow for drop down hai bottom sheet

**Comment by jonahwilliams** [comment]
Hi folks. We think the original issue filled has been fixed. You may be experiencing similar symptoms but we need new bug reports with specific devices / versions and ideally sample code.

**Comment by krll-kov** [comment]
> Member

https://github.com/flutter/flutter/issues/160207 for me issue is still not gone

**Comment by jwelmac** [comment]
I am having this issue also. But it seems to only occur when I build with `appbundle`, APKs seem to work fine.

**Comment by jwelmac** [comment]
And its not fixed in the latest patch
