### ISSUE TITLE
flutter 3.27 Black Screen crash after upgrade from 3.24.5 to 3.27.0

### ISSUE THREAD

**Issue by kwsoftnet7** [flutter/flutter#160228]
### Steps to reproduce

1- created new counter app with flutter 3.27.0
2- run counter app with flutter 3.27.0

### Expected results

The app should launch correctly with no problems.

using flutter 3.24.5 the app correctly launches.

### Actual results

results in some real android devices crashing, the app is unable to launch and the screen is black.

Some real devices experiencing the problem:
android 12; Samsung Galaxy M31

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[flutter error ImpellerValidationBreak.webm](https://github.com/user-attachments/assets/e85d92ce-2574-42a4-bf54-77800c30412c)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
[CXX1101] NDK at C:\Android_SDK\ndk\26.1.10909125 did not have a source.properties file
√ Built build\app\outputs\flutter-apk\app-debug.apk
I/flutter ( 5497): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2154)
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2154)
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2154)
Connecting to VM Service at ws://127.0.0.1:51520/_KpdHFsucsQ=/ws
Connected to the VM Service.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(110)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 5497): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(110)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 5497): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(110)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 5497): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2154)
E/flutter ( 5497): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(110)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 5497): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
D/ProfileInstaller( 5497): Installing profile for com.example.flutter_test_project
Application finished.

Exited (-1).

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS C:\Users\ASHRAF\Desktop\2023 Files\flutter_test_project> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.19045.5247], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2019 16.11.15)
[√] Android Studio (version 2023.2)
[√] Android Studio (version 2024.1)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.96.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by shpy2001** [comment]
Same issue here. 
For Android:
Some devices get black splash screen and delay ~10s to continue. Some devices show normal splash screen but stuck there. And other devices get whole black screen.
Tested on 2 apps. Everythings are ok on Flutter 3.24.5.

**Comment by cachapa** [comment]
I'm not experiencing problems myself (Pixel 8), but am getting reports from users that mirror what is described in this ticket - not yet sure what devices those users are on.

This happened after updating my app with Flutter 3.27.0 last night.

**Comment by Hung6129** [comment]
same issue after updated from 3.24
some time its show a black screen sometime its quit the simulator(android studio lady bug)

**Comment by darshankawar** [comment]
I tried on S10+ device (Android 12) with latest stable and also on Pixel XL api 35 emulator on which I didn't get the reported behavior.

Could be similar to https://github.com/flutter/flutter/issues/160201.  @kwsoftnet7 and everyone in this thread seeing the black screen, can you try as mentioned in [this](https://github.com/flutter/flutter/issues/160201#issuecomment-2540222923) comment to see if it helps in your case or not ?

For emulator specific issue showing black screen, maybe it could be similar / related to https://github.com/flutter/flutter/issues/160168

**Comment by taniksha-mfy** [comment]
I am getting the same issue after upgrading to 3.27. Getting black screen on android Samsung Galaxy note 10 lite.
 Had to install app using flutter run --no-enable-impellerthen it worked. But when restarting the app after killing it then again same issue, everytime need to install like this on my device.

**Comment by richanshah** [comment]
same issue in ios, working when I run from Xcode but when I make ipa it gives error. let me know if anyone found any solution .

**Comment by rubenlop88** [comment]
I do not get a blank screen but my app is stuck in the  splash screen.

**Comment by eijiotieno-official** [comment]
I had the same issue because of impeller rendering engine, disable it completely or use the following when debugging `flutter run --no-enable-impeller`

**Comment by eijiotieno-official** [comment]
> I had the same issue because of impeller rendering engine, disable it completely or use the following when debugging `flutter run --no-enable-impeller`

I added the following inside user settings.json in vscode so that I don't have to use `flutter run --no-enable-impeller` when I don't want to launch app from the terminal, it also works across all projects when you set it inside user's settings.json `"dart.flutterRunAdditionalArgs": [
    "--no-enable-impeller"
  ],`

**Comment by nagendiran89** [comment]
Same issue after updated from 3.24.5 to 3.27.0. It works fine on my device vivo T3 Ultra android 14. Many users facing these issues on my app. They rated my app to 1 star for this issue.
![Screenshot 2024-12-16 102056](https://github.com/user-attachments/assets/f4476a62-d4f0-46c2-84f3-48e3b83d2fbd)
![Screenshot 2024-12-16 102142](https://github.com/user-attachments/assets/7b6d4192-d3a4-46c9-8fb6-7b3bcb210917)

Screen shots on user device:
![Screenshot_20241215-051212_Find Friends](https://github.com/user-attachments/assets/d6e6cbb5-0ecc-4c5b-8f15-0904a8d9c01c)
![2](https://github.com/user-attachments/assets/19e534ed-2089-4bd0-b5bc-0a0c2f1f3f75)

**Comment by kwsoftnet7** [comment]
> I do not get a blank screen but my app is stuck in the splash screen. Only in the emulator.

same issue and i solved it by using `flutter run --no-enable-impeller` as mentioned from [eijiotieno-official](https://github.com/eijiotieno-official)

and i used this method temporary :


> > I had the same issue because of impeller rendering engine, disable it completely or use the following when debugging `flutter run --no-enable-impeller`
> 
> I added the following inside user settings.json in vscode so that I don't have to use `flutter run --no-enable-impeller` when I don't want to launch app from the terminal, it also works across all projects when you set it inside user's settings.json `"dart.flutterRunAdditionalArgs": [ "--no-enable-impeller" ],`

thanks for all and i wait flutter team to solve this issue.

**Comment by richanshah** [comment]
if we use fvm flutter run --target lib/flavor/main_prod.dart --release --no-enable-impeller

  <meta-data
            android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="false" />
 still, it does not work. 

we need proper solution for this issue. otherwise we can not release the app with 3.27.

**Comment by peterweb2005** [comment]
seems related to this issue:
https://github.com/flutter/flutter/issues/158425

**Comment by amitind49** [comment]
`
flutter run --flavor dev --no-enable-impeller --target lib/main_dev.dart`

This change works for me, Thanks @eijiotieno-official

**Comment by jonahwilliams** [comment]
Hi folks. We're working on a chery pick for this issue, but it gets hard to keep track of things with so many off topic comments. Please refrain from commenting unless you have more information to provide.

**Comment by cachapa** [comment]
@jonahwilliams I'm not sure this is related, but some of my users have also reported bad z-order drawing:

![1000014514](https://github.com/user-attachments/assets/dd9ecd9c-ea06-4344-b1cd-2d33d99e236b)

This is a normal BottomSheet overlaid on top of a custom chart widget. The widget is drawing a bunch of lines and text, but weirdly only the dots break the Z order.

The dots are drawn using `canvas.drawPoints`:

``` dart
      canvas.drawPoints(PointMode.points, offsets, _outerPaint);
      canvas.drawPoints(PointMode.points, offsets, _centerPaint);
```

Disabling impeller on Android solved the issue.

**Comment by jonahwilliams** [comment]
@cachapa That doesn't look related at all, please file a new bug.

**Comment by julianryorex** [comment]
I am also experiencing this when running my app on Mac (15.1.1). It does not occur when running on a real ipad (12.9 in 5th gen) or the simulator (both on iOS 18.1).

On hot restart, the app crashes and does not reload. I currently need to quit and restart the build. No crash logs appear on my side, and `--no-enable-impeller` does not seem to have an effect.

**Comment by jonahwilliams** [comment]
@julianryorex that has nothing to do with this bug which is about physical android devices.

**Comment by darshankawar** [comment]
@kwsoftnet7 Please try with latest hotfix version (3.27.1) and confirm the behavior.

**Comment by kwsoftnet7** [comment]
> @kwsoftnet7 Please try with latest hotfix version (3.27.1) and confirm the behavior.

thanks @darshankawar now after install hotfix version (3.27.1) the issue is solved and now the app working on vm and real devices very good without problems.

**Comment by richanshah** [comment]
I have tried with 3.27.1, but my app still stuck on launch screen and getting below logs.

I/flutter ( 9626): [INFO:flutter/shell/platform/android/android_context_vk_impeller.cc(64)] Known bad Vulkan driver encountered, falling back to OpenGLES. then no responds.

**Comment by darshankawar** [comment]
> thanks @darshankawar now after install hotfix version (3.27.1) the issue is solved and now the app working on vm and real devices very good without problems.

Based on this, I will close this as fixed. If anyone still facing same issues, please file new issue and we would need device details and binary version so that we can properly address it.

**Comment by amoghkb** [comment]
I am facing issues with Android Studio. Before the update, it was working fine, but after updating to the latest version, I can no longer run my application. The app installs successfully, but it gets stuck on the default splash screen and doesn't proceed further. I have tried troubleshooting the issue, but nothing seems to work.

**Comment by amoghkb** [comment]
I am facing issues with Android Studio. Before the update, it was working fine, but after updating to the latest version, I can no longer run my application. The app installs successfully, but it gets stuck on the default splash screen and doesn't proceed further. I have tried troubleshooting the issue, but nothing seems to work.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4602], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Community Edition (version 2024.2)
[√] VS Code (version 1.93.1)
[√] Connected device (4 available)
[√] Network resources

![Screenshot 2024-12-20 182909](https://github.com/user-attachments/assets/3e1efeff-cbb8-4da3-a13e-ec02f233962b)
this the device i am using and i also tried with other as well but same issue.

**Comment by rubenlop88** [comment]
@amon Checkout this issue #160439. I had the same problem after I upgraded to 3.27. I created another emulator with the API 35 image instead of the VanillaIceCream one and I was able to run my app again. Hope this helps.

**Comment by neel-vaghani** [comment]
> Please try with latest hotfix version (3.27.1) and confirm the behavior

I am using **flutter 3.27.1** and i got same issue 

![WhatsApp Image 2024-12-25 at 5 33 30 PM](https://github.com/user-attachments/assets/9d79c23f-8ca0-4780-8c76-16ca4ae7b324)

**Device Name** : OPPO F19 Pro
**Android version** : 13

**Comment by shalabycr7** [comment]
I also have the same issue on my phone but the app works fine on the emulator.. strange 

Device Name : OPPO A94
Android version : 13

**Comment by JavohirYakubov** [comment]
I added the following line and the problem was solved:

`    
<application
        android:name="${applicationName}"
        android:icon="@mipmap/launcher_icon"
        android:label="App"
        android:allowBackup="false"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true">

        <meta-data android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="false" />

</application>
`

**Comment by z85510** [comment]
When I add `<meta-data android:name="io.flutter.embedding.android.EnableImpeller" android:value="false" />` to the AndroidManifest file, the app still gets stuck on the splash screen. However, if I bring the app to the foreground, it resumes working. Interestingly, running the app with the --no-enable-impeller flag `(e.g., flutter run --release --no-enable-impeller) `resolves the issue.

I've confirmed that the <meta-data> tag is placed correctly under the <application> tag in the AndroidManifest, but it seems like Impeller isn't being disabled as expected. What could be causing this, and how can I fix it?

`<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>

    <application android:label="CanSell" android:name=".Application" android:icon="@mipmap/launcher_icon" android:usesCleartextTraffic="true">
        <meta-data android:name="io.flutter.embedding.android.EnableImpeller" android:value="false" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />
        <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize" android:enableOnBackInvokedCallback="true">

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="cansell.info" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="cansell" android:host="verify" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

        </activity>

        <activity android:name="com.yalantis.ucrop.UCropActivity" android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>

        <meta-data android:name="flutterEmbedding" android:value="2" />

        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorPrimary" />
    </application>
</manifest>
`
