### ISSUE TITLE
Nested generic function inside factory constructor crashes flutter run (web) compiler

### ISSUE THREAD

**Issue by NicolaVerbeeck** [flutter/flutter#160338]
### Steps to reproduce

1. Update to flutter 3.27.0
2. `flutter run -d chrome`

### Expected results

Chrome opens with the flutter application running

### Actual results

Dart compiler crashes. Note that this does not happen for other non-web runs (eg windows). This also does not happen when compiling a js bundle from it

### Code sample

<details open><summary>Code sample</summary>

Due to the confidential nature and the lack of any indication in which file the bug is triggered, we cannot provide a code sample to reproduce this. If we somehow can get even more verbose logs that point us to which function is being compiled that crashes the compiler, we may be able to extract a code sample.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib\main.dart on Chrome in debug mode...
Unhandled exception:
Exception: RtiTypeEnvironments should not receive extended type parameters.
#0      RtiTypeEnvironment.extend (package:dev_compiler/src/kernel/type_environment.dart:137)
#1      ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3590)
#2      ProgramCompiler.visitFunctionDeclaration (package:dev_compiler/src/kernel/compiler.dart:4882)
#3      FunctionDeclaration.accept (package:kernel/src/ast/statements.dart:1747)
#4      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3971)
#5      MappedIterable.elementAt (dart:_internal/iterable.dart:395)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:364)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     SetBase.toList (dart:collection/set.dart:119)
#11     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4160)
#12     Block.accept (package:kernel/src/ast/statements.dart:103)
#13     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3971)
#14     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4004)
#15     ProgramCompiler._emitFactoryConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2460)
#16     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2749)
#17     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3749)
#18     ProgramCompiler._emitFactoryConstructor (package:dev_compiler/src/kernel/compiler.dart:2458)
#19     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2230)
#20     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:1041)
#21     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:973)
#22     List.forEach (dart:core-patch/growable_array.dart:417)
#23     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:912)
#24     List.forEach (dart:core-patch/growable_array.dart:417)
#25     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:620)
#26     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:231)
#27     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:874)
<asynchronous suspension>
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:690)
<asynchronous suspension>
#29     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1392)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...             14.7s
Failed to compile application.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22631.4602], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2024.3)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @NicolaVerbeeck, can you provide your pubspec.yaml along with the full output of `flutter run -d chrome -v`? Also, did this start after a flutter upgrade or a dependency change or something similar?

**Comment by NicolaVerbeeck** [comment]
Sure, here is a redacted version. It happens in a small 'reproducible' scenario where we add one (specific) one of our local libraries (monorepo style) even in a bare-bones new flutter application (with > 0.5m lines of code).

It started when we upgraded from 3.22.3 to 3.27.0 (we skipped previous major release for other reasons, but that one compiled just fine)


Pubspec:
```yaml
name: <redacted>
description: <redacted>
publish_to: "none"
version: 1.0.0

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Stream library
  rxdart: ^0.28.0

  # Utility functions and classes
  collection: ^1.19.0

  # Dependency injection
  flutter_riverpod: ^2.6.1

  # Model definitions
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Platform specific utilities
  url_strategy: ^0.2.0

  # Cross-platform utilities
  universal_html: ^2.2.4

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  # code generation
  super_annotations: ^0.8.2

  # Semantic Versioning Library
  pub_semver: ^2.1.5
  pubspec_parse: ^1.3.0

  # Load .svg files
  flutter_svg: ^2.0.16

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../<redacted>

  <redacted>:
    path: ../../<redacted>/<redacted>

  math_parser: ^1.5.1

  # EventManager
  dart_mediator: ^0.3.2

  js: any
  vector_math: any
  meta: any
  intl: ^0.19.0
dev_dependencies:
  # Code generation
  build_runner: 2.4.9
  json_serializable: ^6.9.0
  freezed: ^2.5.7

  # Tests
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  test_assets:
    path: ../../<redacted>/<redacted>

  http: any
  path: any

dependency_overrides:
  collection: 1.19.0
  barcode:
    git:
      url: https://github.com/NicolaVerbeeck/dart_barcode.git
      path: barcode
      ref: ed06e3fa57fbc0202acc55f93723ad81af7d6335

flutter:
  assets:
    - assets/icons/
    - assets/dev/
```

Logs
```console
flutter run -d chrome -v
[ +182 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] Skipping pub get: version match.
[ +102 ms] Found plugin flutter_qjs at <redacted>\packages\flutter_qjs\
[  +12 ms] Found plugin integration_test at D:\Dev\fvm\versions\3.27.0\packages\integration_test\
[  +82 ms] Found plugin flutter_qjs at <redacted>\packages\flutter_qjs\
[   +7 ms] Found plugin integration_test at D:\Dev\fvm\versions\3.27.0\packages\integration_test\
[  +64 ms] Found plugin flutter_qjs at <redacted>\packages\flutter_qjs\
[   +6 ms] Found plugin integration_test at D:\Dev\fvm\versions\3.27.0\packages\integration_test\
[ +101 ms] Launching lib\main.dart on Chrome in debug mode...
[  +73 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Updating assets
[ +330 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +6 ms] Waiting for connection from debug service on Chrome...
[  +91 ms] Found plugin flutter_qjs at <redacted>\packages\flutter_qjs\
[  +10 ms] Found plugin integration_test at D:\Dev\fvm\versions\3.27.0\packages\integration_test\
[  +51 ms] shaderc command: [D:\Dev\fvm\versions\3.27.0\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --iplr, --json, --sl=build\flutter_assets\shaders/ink_sparkle.frag, --spirv=build\flutter_assets\shaders/ink_sparkle.frag.spirv,
--input=D:\Dev\fvm\versions\3.27.0\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=D:\Dev\fvm\versions\3.27.0\packages\flutter\lib\src\material\shaders, --include=D:\Dev\fvm\versions\3.27.0\bin\cache\artifacts\engine\windows-x64\shader_lib]
[ +178 ms] Warning: In index.html:24: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead. See https://docs.flutter.dev/platform-integration/web/initialization for more details.
[   +1 ms] <- reset
[   +2 ms] D:\Dev\fvm\versions\3.27.0\bin\cache\dart-sdk\bin\dartaotruntime.exe D:\Dev\fvm\versions\3.27.0\bin\cache\dart-sdk\bin\snapshots\frontend_server_aot.dart.snapshot --sdk-root D:\Dev\fvm\versions\3.27.0\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --experimental-emit-debug-metadata--output-dill <redacted>\flutter_tools.eee61111\flutter_tool.3d089445\app.dill --packages <redacted>\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
<redacted>\AppData\Local\Temp\flutter_tools.eee61111\flutter_tools.519b4a38 --filesystem-scheme org-dartlang-app --initialize-from-dill build\80b1a4cf4e7b90e1ab5f72022a0bc624.cache.dill.track.dill --platform file:///D:/Dev/fvm/versions/3.27.0/bin/cache/flutter_web_sdk/kernel/ddc_outline_sound.dill   
--verbosity=error --sound-null-safety
[   +6 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+18592 ms] Unhandled exception:
[        ] Exception: RtiTypeEnvironments should not receive extended type parameters.
[        ] #0      RtiTypeEnvironment.extend (package:dev_compiler/src/kernel/type_environment.dart:137)
[        ] #1      ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3590)
[        ] #2      ProgramCompiler.visitFunctionDeclaration (package:dev_compiler/src/kernel/compiler.dart:4882)
[        ] #3      FunctionDeclaration.accept (package:kernel/src/ast/statements.dart:1747)
[        ] #4      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3971)
[        ] #5      MappedIterable.elementAt (dart:_internal/iterable.dart:395)
[        ] #6      ListIterator.moveNext (dart:_internal/iterable.dart:364)
[        ] #7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
[        ] #8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
[        ] #9      new List.of (dart:core-patch/array_patch.dart:39)
[        ] #10     SetBase.toList (dart:collection/set.dart:119)
[        ] #11     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4160)
[        ] #12     Block.accept (package:kernel/src/ast/statements.dart:103)
[        ] #13     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3971)
[        ] #14     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4004)
[        ] #15     ProgramCompiler._emitFactoryConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2460)
[        ] #16     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2749)
[        ] #17     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3749)
[        ] #18     ProgramCompiler._emitFactoryConstructor (package:dev_compiler/src/kernel/compiler.dart:2458)
[        ] #19     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2230)
[        ] #20     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:1041)
[        ] #21     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:973)
[        ] #22     List.forEach (dart:core-patch/growable_array.dart:417)
[        ] #23     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:912)
[        ] #24     List.forEach (dart:core-patch/growable_array.dart:417)
[        ] #25     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:620)
[        ] #26     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:231)
[        ] #27     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:874)
[        ] <asynchronous suspension>
[        ] #28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:690)
[        ] <asynchronous suspension>
[        ] #29     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1392)
[        ] <asynchronous suspension>
[  +54 ms] "flutter run" took 19,904ms.
[  +25 ms] the Dart compiler exited unexpectedly.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:882:13)
           #2      _rootRun (dart:async/zone.dart:1406:47)
           #3      _CustomZone.run (dart:async/zone.dart:1317:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:419:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:429:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:318:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1406:47)
           #14     _CustomZone.run (dart:async/zone.dart:1317:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:419:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:429:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:318:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1406:47)
           #26     _CustomZone.run (dart:async/zone.dart:1317:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:419:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:429:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:318:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:785:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:640:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:633:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2462:21)
           #35     _rootRunUnary (dart:async/zone.dart:1430:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1324:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:651:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:606:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1949:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1378:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[   +1 ms] Waiting for connection from debug service on Chrome... (completed in 19.0s)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[ +104 ms] ensureAnalyticsSent: 103ms
[        ] Running 2 shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by danagbemava-nc** [comment]
Hi @NicolaVerbeeck, would it be possible for us a get a minimal reproducible code sample so that we can properly investigate this?

**Comment by NicolaVerbeeck** [comment]
I can't figure out which code is the culprit. It is somewhere in 0.5m lines of dart code but the compiler gives me no way (that I can find) to tell which file/function triggers the issue

**Comment by NicolaVerbeeck** [comment]
Building the dart sdk with some helpful information lead me to find the bug.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyBug {
  MyBug._();

  factory MyBug.iAmABug() {
    /// =============================== This cause a compiler crash
    T? getIt<T>(String arg) {
      return arg as T;
    }

    getIt<String?>('I am a bug');

    return MyBug._();
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

**Comment by andyshephard** [comment]
I can compile successfully to web if I run in release mode, but encountering the same issue in debug mode.

pubspec.yaml:
```
name: nift_mobile_apps
description: A new Flutter project.

publish_to: "none"
version: 1.0.41+999999999

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.27.1

dependencies:
  adaptive_action_sheet: ^2.0.2
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6
  animated_flip_counter: ^0.3.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  collection: ^1.1.0
  cupertino_icons: ^1.0.6
  datadog_flutter_plugin: ^2.2.0
  datadog_tracking_http_client: ^2.1.0
  device_info_plus: ^11.2.0
  dio: ^5.4.0
  easy_localization: ^3.0.4
  envied: ^1.0.0
  equatable: ^2.0.5
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1
  flutter_bloc: ^8.1.3
  flutter_branch_sdk: ^8.0.0
  flutter_foreground_task: ^8.10.4
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.4
  flutter_native_splash: ^2.4.1
  flutter_polyline_points: ^2.0.0
  flutter_screen_lock: ^9.0.2
  flutter_secure_storage: ^9.0.0
  flutter_stripe: ^11.0.0
  flutter_stripe_web: ^6.0.0
  geocoding: ^3.0.0
  get_it: ^8.0.2
  go_router: ^14.6.2
  google_maps: ^8.0.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  hover_menu: ^1.1.1
  http: ^1.2.1
  in_app_review: ^2.0.9
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  live_activities: ^2.0.0+2
  logger: ^2.1.0
  meilisearch: ^0.16.0
  meta_seo: ^3.0.9
  navigation_history_observer: ^1.1.0
  package_info_plus: ^8.1.2
  page_transition: ^2.1.0
  photo_view: ^0.15.0
  responsive_sizer: ^3.3.1
  retrofit: ^4.0.3
  seo: ^0.0.7
  share_plus: ^10.1.2
  shared_preferences: ^2.2.2
  shorebird_code_push: ^2.0.2
  sign_in_with_apple: ^6.1.1
  text_scroll: ^0.2.0
  url_launcher: ^6.2.3
  uuid: ^4.3.3
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  web: ^1.1.0
  webview_flutter: ^4.4.4

dev_dependencies:
  build_runner: any
  envied_generator: ^1.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: any

flutter:
  uses-material-design: true

  assets:
    - lib/assets/translations/
    - lib/assets/images/
    - lib/assets/images/payment_icons/
    - shorebird.yaml

  fonts:
    - family: Bicyclette
      fonts:
        - asset: lib/assets/fonts/Bicyclette-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Bicyclette-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Bicyclette-Black.ttf
          weight: 900

flutter_native_splash:
  image: lib/assets/images/app_icons/NIFT-Production.png
  color: "#000000"
  ios: true
  android: true
  android_12:
    image: lib/assets/images/app_icons/NIFT-Production.png
    color: "#000000"
  web: true

scripts: derry.yaml
```

compile log error (debug):
```
Launching lib/config/web/main_production.dart on Chrome in debug mode...
Unhandled exception:
Exception: RtiTypeEnvironments should not receive extended type parameters.
#0      RtiTypeEnvironment.extend (package:dev_compiler/src/kernel/type_environment.dart:137)
#1      ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3590)
#2      ProgramCompiler.visitFunctionDeclaration (package:dev_compiler/src/kernel/compiler.dart:4882)
#3      FunctionDeclaration.accept (package:kernel/src/ast/statements.dart:1747)
#4      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3971)
#5      MappedIterable.elementAt (dart:_internal/iterable.dart:395)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:364)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     SetBase.toList (dart:collection/set.dart:119)
#11     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4160)
#12     Block.accept (package:kernel/src/ast/statements.dart:103)
#13     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3971)
#14     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4004)
#15     ProgramCompiler._emitFactoryConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2460)
#16     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2749)
#17     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3749)
#18     ProgramCompiler._emitFactoryConstructor (package:dev_compiler/src/kernel/compiler.dart:2458)
#19     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2230)
#20     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:1041)
#21     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:973)
#22     List.forEach (dart:core-patch/growable_array.dart:417)
#23     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:912)
#24     List.forEach (dart:core-patch/growable_array.dart:417)
#25     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:620)
#26     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:231)
#27     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:874)
<asynchronous suspension>
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:690)
<asynchronous suspension>
#29     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1392)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Failed to compile application.

Exited (1).
```

**Comment by 00017102** [comment]
Any fix for this at the moment?

**Comment by NicolaVerbeeck** [comment]
> Any fix for this at the moment?
Convert the factory to a static method

**Comment by mraleph** [comment]
cc @biggs0125

**Comment by PiotrRogulski** [comment]
Hi, any updates on this issue? 😅 This prevents our team from upgrading to the newest Flutter

**Comment by mraleph** [comment]
cc @a-siva

**Comment by mraleph** [comment]
@biggs0125 Nate, could somebody look at this?

**Comment by biggs0125** [comment]
A small repro can be found here:
```
class A {
  A();
  
  factory A.foo() {
    void func<T>(T i) {
      print(i);
    }
    func(3);

    return A();
  }
}

void main() {
  A.foo();
}
```

Defining a generic function within a factory constructor seems to elicit this error. A workaround is to either (1) pull the local function out into a static:
```
class A {
  A();

  static void func<T>(T i) {
    print(i);
  }
  
  factory A.foo() {
    func(3);

    return A();
  }
}

void main() {
  A.foo();
}
```

Or (2) make the function not be generic.

I'll work on putting together a fix for this in the SDK.

**Comment by AmoonPod** [comment]
Hi. Any ETA on this? Thank you.

**Comment by biggs0125** [comment]
This issue is fixed in the Dart SDK. Don't think this fix warrants a cherrypick given there are some workarounds (though not necessarily the prettiest ones).

So I think this is safe to close out.

**Comment by ChuckPG** [comment]
> This issue is fixed in the Dart SDK. Don't think this fix warrants a cherrypick given there are some workarounds (though not necessarily the prettiest ones).
> 
> So I think this is safe to close out.

Would really appreciate a cherrypick or to get this into releases ASAP because it's difficult to work around since the thrown exception doesn't give you the location of the issue to fix it.

I have ~300 factory constructors in the codebase I'm working on and it will be fairly time consuming to go through each one to work around this.

Thanks for considering

**Comment by ahmednfwela** [comment]
flutter 3.29.0 is out and this issue still persists, I don't understand how this does not warrant a cherry pick when it's a p1 regression bug

![Image](https://github.com/user-attachments/assets/5ea3232a-482f-476d-a237-bd717d797d75)

**Comment by biggs0125** [comment]
Thanks everyone for weighing in. Since the workaround is impractical for some, I've started the cherrypick process to the stable channel for this fix.

**Comment by AndryHTC** [comment]
Guys, how is this 3 months old? Crazy

**Comment by mraleph** [comment]
I have confirmed that this will be part of 3.29.2 which is going to be released relatively soon.

So I am going to close this as fixed.
