### ISSUE TITLE
Impeller on Android renders apps black on Samsung A51

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#160316]
### Steps to reproduce

I have at least two users complaining about the app being all black on the same device: samsung a51 (Galaxy A51)

Running tests on Firebase Labs don't show any issue, but, real devices are rendering a black app.

There are no error messages, AFAIK.

### Expected results

To render correctly

### Actual results

App is all black

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1 24B83 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.96.0)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @JCKodel, can you try https://github.com/flutter/flutter/issues/160201#issuecomment-2540222923 to see if it resolves your issue?

**Comment by JCKodel** [comment]
@danagbemava-nc, I cannot test that in production. My ANR threshold spiked to the roof with Impeller on, so I had to turn it off. We're a company that depends on this to get our wages in the end of the month.

<img width="1558" alt="image" src="https://github.com/user-attachments/assets/2a95f145-b3f3-471f-8d1e-d4bffa765940" />

**Comment by ekuleshov** [comment]
> Hi @JCKodel, can you try [#160201 (comment)](https://github.com/flutter/flutter/issues/160201#issuecomment-2540222923) to see if it resolves your issue?

Is the 3.27.1 hotfix resolves this issue or we still need to add `io.flutter.embedding.android.DisableSurfaceControl` ?

**Comment by danagbemava-nc** [comment]
Hi @ekuleshov, I don't think it should be necessary to add that with hotfix 3.27.1. I don't have a similar device so I can't confirm this. 

@JCKodel, can you check with the latest hot fix to see if this resolves the issue? 

PS: Please file issues for the ANRs with detailed information so that they can be properly addressed

Thank you

**Comment by jonahwilliams** [comment]
We believe this was fixed by the .1 hotix. Closing until I hear otherwise.

**Comment by mauriziopinotti** [comment]
Problem is still happening with 3.27.1 on some devices, e.g. Oppo Reno2 Z with ColorOS 11 (GPU PowerVR GM9446):

App compiled with Flutter 3.27.1:

![image](https://github.com/user-attachments/assets/701680b5-d244-46a5-af52-8793b548d476)

Here I get this output in the logcat:

```logcat
12-20 18:01:20.300 27897 27897 I flutter : [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
12-20 18:01:21.487 27897 27897 I flutter : [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
```

App compiled with Flutter 3.27.1 and Impeller disabled (`io.flutter.embedding.android.EnableImpeller` set to `false` in `AndroidManifest.xml`):

![image](https://github.com/user-attachments/assets/7c1778af-e8c4-4ad3-86ed-21fd86020370)

**Comment by JCKodel** [comment]
Some comments:

It's not just black screens, ANR spiked as well with Flutter 3.27 (I had to revert them back, and I didn't tested on 3.27.1, but, it's not just black screens). I really can't make a test with 300k users with such an impact =\

I don't know if this is a brazilian thing (Samsung often offers cheaper products in BRICS than the USA (for example: USA models uses Snapdragon, we have to bear with Exynos)) or if it is how Firebase Test lab works, but A51 from test labs works just fine (at least I have screenshots and videos showing the app running and working properly on an A51 and Flutter 3.27), but users reports of black screen are all for the same A51.

I would gladly do an open test run with Flutter 3.27.1 (about 12k users), but people often don't give proper feedback (they just write a useless review like "trash" or "no working", etc.), so it would be useless =\
