### ISSUE TITLE
I have flicker with Flutter App On Android and sometimes on iOS

### ISSUE THREAD

**Issue by astudilloalex** [flutter/flutter#160824]
### Steps to reproduce

1. I have a page on scroll or speed movement i have flicker

### Expected results

The scroll does not working correctly 

### Actual results

I have flicker

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:austro_digital/app/login/_children/register_austrotoken_login/presenter/blocs/camera_access_bloc/camera_access_bloc.dart';
import 'package:austro_digital/app/login/_children/register_austrotoken_login/presenter/screens/screens.dart';
import 'package:austro_digital/apps/ley_proteccion/models/args_for_law_terms_model.dart';
import 'package:austro_digital/core/widgets/inputs/terms_checkbox.dart';
import 'package:austro_digital/global_var.dart';
import 'package:ba_app_widgets/ba_components.dart';
import 'package:ba_mobile_core/ba_mobile_core.dart';
import 'package:ba_mobile_design_system/ba_mobile_design_system.dart';
import 'package:ba_mobile_utils/image_utils.dart';
import 'package:firebase_analytics_tracker/firebase_analytics_tracker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:shimmer/shimmer.dart';
import 'package:sizer/sizer.dart';

List<Map<String, String>> items = [
  {
    'imagePath': ImageUtils.focoImage,
    'text': 'Tener buena iluminación.',
  },
  {
    'imagePath': ImageUtils.eyeglasses,
    'text': 'No uses lentes o accesorios.',
  },
  {
    'imagePath': ImageUtils.focusFace,
    'text': 'Enfoca tu cédula y rostro completo. Evita que esté borroso.',
  },
];

class CameraAccessPage extends StatefulWidget {
  static const String routeName = '/camera-access';

  const CameraAccessPage({super.key});

  @override
  State<CameraAccessPage> createState() => _CameraAccessPageState();
}

class _CameraAccessPageState extends State<CameraAccessPage>
    with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    GlobalVars().timeLastSession = DateTime.now();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    switch (state) {
      case AppLifecycleState.resumed:
        BlocProvider.of<CameraAccessBloc>(context).add(
          RequestCameraAccessEvent(),
        );
        break;
      case AppLifecycleState.paused:
        break;
      case AppLifecycleState.inactive:
        break;
      case AppLifecycleState.detached:
      default:
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: BlocProvider.of<CameraAccessBloc>(context),
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Comprobar identidad'),
          centerTitle: false,
          bottom: const PreferredSize(
            preferredSize: Size.fromHeight(2.5),
            child: LinearProgressIndicator(
              color: BaColor.secondary,
              backgroundColor: Colors.transparent,
              value: 2 / 5,
            ),
          ),
        ),
        backgroundColor: BaColor.skyMist,
        body: BlocListener<CameraAccessBloc, CameraAccessState>(
          listener: (context, state) async {
            if (state is CameraAccessGrantedState) {
              // await Navigator.of(context).pushNamed(
              //   InfoScreen.routeName,
              //   arguments: InfoScreenArgs(
              //     appBarText: 'Comprobar identidad',
              //     title: 'Validación lista',
              //     messages: ['Hemos comprobado tu identidad exitosamente'],
              //     buttonText: 'Continuar',
              //     onPressed: () {
              //       Navigator.of(context).pushNamedAndRemoveUntil(
              //         CreateAustroTokenPinScreen.routeName,
              //         (route) => false,
              //       );
              //     },
              //     imagePath: imgCheckGlobal.path,
              //     imageColor: const Color(0xFF319E48),
              //   ),
              // );

              if (RemoteConfigService.instance
                  .getBool(RemoteConfigEnum.skipLifeTest)) {
                Navigator.of(context).pushNamed(
                  CreateAustroTokenPinScreen.routeName,
                );
              } else {
                Navigator.of(context).pushNamed(
                  //CreateAustroTokenPinScreen.routeName,
                  //AustroTokenActivatedScreen.routeName,
                  ProofOfLifeScreen.routeName,
                );
              }
            }
            if (state is CameraAccessDeniedState) {
              Navigator.pushNamed(
                context,
                InfoScreen.routeName,
                arguments: InfoScreenArgs(
                  appBarText: 'Comprobar identidad',
                  title: 'Acceso pendiente',
                  messages: [
                    'Es necesario los permisos de la cámara del dispositivo para continuar con el proceso de creación de cuenta.',
                  ],
                  buttonText: 'Permitir',
                  onPressed: () {
                    BlocProvider.of<CameraAccessBloc>(context).add(
                      RequestCameraAccessEvent(),
                    );
                    Navigator.of(context).pop();
                  },
                  imagePath: ImageUtils.notCamera,
                ),
              );
            }
            if (state is CameraAccessPermanentlyDeniedState) {
              Navigator.pushNamed(
                context,
                InfoScreen.routeName,
                arguments: InfoScreenArgs(
                  appBarText: 'Comprobar identidad',
                  title: 'Acceso pendiente',
                  messages: [
                    'Es necesario los permisos de la cámara del dispositivo para continuar con el proceso de creación de cuenta.',
                    'Puedes dar este permiso desde la configuración del sistema.',
                  ],
                  buttonText: 'Configuración',
                  onPressed: () {
                    context.read<CameraAccessBloc>().logEvent(
                          AnalyticsEvent.loginCameraAccessOnOpenConfiguration,
                        );
                    openAppSettings();

                    Navigator.of(context).pop();
                  },
                  imagePath: ImageUtils.notCamera,
                ),
              );
            }
          },
          child: const _Body(),
        ),
      ),
    );
    // return BlocProvider.value(
    //   value: BlocProvider.of<CameraAccessBloc>(context),
    //   child: BaScreenBase(
    //     hasGoBack: true,
    //     hasPadding: false,
    //     customBackgroundColor: BaColor.skyMist,
    //     appBarText: 'Comprobar identidad',
    //     child: BlocListener<CameraAccessBloc, CameraAccessState>(
    //       listener: (context, state) {

    //       },
    //       child: const _Body(),
    //     ),
    //   ),
    // );
  }
}

class _Body extends StatefulWidget {
  const _Body();

  @override
  State<_Body> createState() => _BodyState();
}

class _BodyState extends State<_Body> {
  bool _isChecked = true;
  bool _showTermsAndConditionsCheck = true;
  bool _isLoading = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _checkTermsAndConditions();
  }

  Future<void> _checkTermsAndConditions() async {
    if (context.read<CameraAccessBloc>().title ==
        'Recupera tu pin con identificación de tu rostro') {
      return;
    }
    bool accepted = false;
    if (!mounted) return;
    setState(() {
      _isLoading = true;
    });
    try {
      final CameraAccessBloc bloc = context.read<CameraAccessBloc>();
      accepted = await bloc.acceptedTermsAndConditions;
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _showTermsAndConditionsCheck = !accepted;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: ListView(
            children: [
              const SizedBox(height: 34.0),
              Image.asset(
                ImageUtils.cameraRounded,
                height: 190.0,
              ),
              const SizedBox(height: 50.0),
              H3(
                text: context.read<CameraAccessBloc>().title,
                color: BaColor.secondary,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20.0),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const H6(
                      text: 'Recuerda:',
                      color: BaColor.secondary,
                      textAlign: TextAlign.start,
                      fontWeight: FontWeight.w700,
                    ),
                    ...items
                        .map(
                          (item) => CustomRowWidget(
                            imagePath: item['imagePath']!,
                            text: item['text']!,
                          ),
                        )
                        .toList(),
                  ],
                ),
              ),
              GeneralVerticalSpace(
                customSpace: 2.h,
              ),
              GeneralVerticalSpace(
                customSpace: 12.h,
              ),
            ],
          ),
        ),
        if (_isLoading &&
            context.read<CameraAccessBloc>().title ==
                'Pediremos permiso para acceder a tu cámara')
          Shimmer.fromColors(
            baseColor: Colors.grey[300]!,
            highlightColor: Colors.grey[100]!,
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              child: TermsCheckBox(
                checked: _isChecked,
                text: Text(
                  'He leído y acepto la Política de Privacidad y Protección de Datos Personales.',
                  style: TextStyle(
                    fontSize: 11.sp,
                    decoration: TextDecoration.underline,
                    fontWeight: FontWeight.w400,
                  ),
                ),
                onChange: (value) {},
              ),
            ),
          ),
        if (_showTermsAndConditionsCheck &&
            !_isLoading &&
            context.read<CameraAccessBloc>().title ==
                'Pediremos permiso para acceder a tu cámara')
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            child: TermsCheckBox(
              checked: _isChecked,
              text: Text(
                'He leído y acepto la Política de Privacidad y Protección de Datos Personales.',
                style: TextStyle(
                  fontSize: 11.sp,
                  decoration: TextDecoration.underline,
                  fontWeight: FontWeight.w400,
                ),
              ),
              onChange: (value) {
                setState(() {
                  _isChecked = value ?? false;
                });
              },
              openTerms: () async {
                final bool? acepto = await Navigator.pushNamed<bool?>(
                  context,
                  TermsPdfPage.routeName,
                  arguments: ArgsForLawTermsModel(
                    pdfUrl: url,
                  ),
                );
                //final CameraAccessBloc bloc = context.read<CameraAccessBloc>();
                if (acepto != null && acepto) {
                  setState(() {
                    _isChecked = true;
                  });
                }
                //await _checkTermsAndConditions();
                if (!mounted) return;
                //setState(() => _isChecked = acepto ?? false);
              },
            ),
          ),
        const SizedBox(height: 16.0),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: BaButton(
            text: 'Continuar',
            onPressed: (_isLoading || !_isChecked) &&
                    context.read<CameraAccessBloc>().title !=
                        'Recupera tu pin con identificación de tu rostro'
                ? null
                : () async {
                    if (context.read<CameraAccessBloc>().title ==
                        'Recupera tu pin con identificación de tu rostro') {
                      BlocProvider.of<CameraAccessBloc>(context).add(
                        RequestCameraAccessEvent(),
                      );
                      return;
                    }
                    setState(() {
                      _isLoading = true;
                    });
                    final CameraAccessBloc bloc =
                        context.read<CameraAccessBloc>();
                    await bloc.acceptDataProtection();
                    setState(() {
                      _isLoading = false;
                    });
                    BlocProvider.of<CameraAccessBloc>(context).add(
                      RequestCameraAccessEvent(),
                    );
                  },
            backgroundColor: BaColor.primary,
          ),
        ),
        const SizedBox(height: 25.0),
      ],
    );
  }
}

class CustomRowWidget extends StatelessWidget {
  final String imagePath;
  final String text;

  const CustomRowWidget({
    Key? key,
    required this.imagePath,
    required this.text,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListTile(
      leading: Image.asset(
        imagePath,
      ),
      title: M3(
        text,
        color: BaColor.black,
        fontWeight: FontWeight.w400,
      ),
    );
  }
}

const url = 'https://www.bancodelaustro.com/politica-de-proteccion-de-datos';
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Redmi Note 8 Pro (One time on Iphone 13, but anymore)

https://github.com/user-attachments/assets/ab7a1e36-d4ff-480f-95d7-8d00603c662e

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale en-EC)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.6)
[✓] VS Code (version 1.92.2)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone de William. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Comment by oshanrasanjana** [comment]
it is because of the latest flutter version 3.27.0 uses impeller as default rendering engine and it does not work properly with heavy widgets like "Backdrop filters"  in stacks. [https://docs.flutter.dev/perf/impeller#:~:text=Flutter%20enables%20Impeller%20by%20default%20on%20Android.,to%20the%20flutter%20run%20command.](url) follow this links.
You can disable impeller on debug mode by passing a flag "flutter run --no-enable-impeller" 

Here is the issue i'm also facing that by adding 

"<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="false" />"
    
 this in android manifest the release apks should also disable impeller but it does not. I really hope flutter team will see this and fix this issue really quick as our apps completely jerking off because of impeller . Specially in release mode because in debug mode the flag is working.
 
 Please reply if this work for you in release mode "build apk or appbundle in android"

**Comment by leaf-node** [comment]
In the older version, 3.27.0, I haven't noticed this flickering behavior, even when Impeller is enabled, but I do see this flickering behavior in version 3.27.1. Adding the [following](https://docs.flutter.dev/perf/impeller#android) seems to resolve the bug on 3.27.1:

```
<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="false" />
```

In my case, the flickering can be hard to catch / reproduce (on version 3.27.1). I noticed it mostly while tapping in and out of menus, by pressing navigation buttons lined up on two screens. That way the screen is showing constant motion. I've also seen this while quickly scrolling columns of color-coded widgets. In both of these cases, there is a high contrast from one frame to another, so it's easier to spot when it happens.

The flickering usually lasts for about one or a half second or so, quickly repeating two frames tens of times. And then the app returns to normal, but then it can happen again a second or so later, repeating the flickering behavior several times in quick succession. And then the behavior tends to go away completely for a while, and then may come back later.

**Comment by oshanrasanjana** [comment]
Try with a older flutter version like 3.24 or use the flag while debugging
cause impeller pre compile all graphical shaders whivh makes the app faster
and smooth but can cause some animations to flicker. My case was brutal as
after upgrafing to 3.27.1 my app started to flicker so fast that i cant
even see the widget (I had heavy animations on a stack with backdrop filter
-- In a one page) so i used the flag and it worked -- It also worked when i
remove backdrop filter widget from stack - It wasnt idle cause i wanted it
and there were other pages that caused the same issue. anyway when i used
build command to build an apk the manifest declaration doesnt worked as
expected --as the flag. I think i have to go back to flutter 3.24 till the
team fix this issue  when going into production.
Note the flag is also not permanent as its a runtime flag if you close the
app after run command and then open it from the icon on home screen it does
not work you have to rebuild all the time for it to work.

**Comment by astudilloalex** [comment]
The solution is not to disable Impeller. We need Impeller to be stable now.

**Comment by oshanrasanjana** [comment]
yeah that's the obvious answer but it's still like a child that hardly walk so we can't expect it to sprint. I believe flutter team or we should come up with a solution to disable impeller on android and ios for production releases then we can improve impeller and learn how to handle complex hierarchies with it. So do you found a solution for production builds ,does the flag worked for you and how can we get flutter teams attention or make a pull request with appropriate actions

**Comment by oshanrasanjana** [comment]
I'm devastated as i have to go back to a previous version of the app if i switch back to 3.24 cause I update my codebases to be up to date with framework . So in case anyone found a solution for production builds like getting priority to that metadata in manifest for android please share with me.I checked the merged manifest and it looks fine as it has the metadata for disable impeller included.

**Comment by astudilloalex** [comment]
For the moment on the version 3.27.1 using this code works correctly for the moment

![image](https://github.com/user-attachments/assets/6590a9b1-544e-42d1-8c09-bf64d76c79d5)

inside android/app/src/main/AndroidManifest.xml

**Comment by oshanrasanjana** [comment]
Sure i'll try , thanks

**Comment by astudilloalex** [comment]
The test was done again on the device in the video shown here and the flickering seemed to have disappeared.

**Comment by astudilloalex** [comment]
> Sure i'll try , thanks

The test was done again on the device in the video shown here and the flickering seemed to have disappeared.

**Comment by oshanrasanjana** [comment]
I had this 
"  ```
<meta-data
            android:name="io.flutter.embedding.android.DisableImpeller"
            android:value="true" />
```
"
and i changed it to new code and it worked
"```
<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="false" />
```
"
I copied the code from official website but somehow it has changed. thanks for the help cause i spend hours trying to fix it and was devastated to launch the app as only the debug flag worked.

**Comment by maheshj01** [comment]
Hi @astudilloalex, the code sample shared has lot of third party libraries and widgets. Please share a minimal code sample that reproduces the flicker. And is the flicker with or without impeller?

**Comment by fareesh** [comment]
Running into the same type of graphical issue when I scroll. Coincidentally I also happen to be using the `shimmer` package. Makes me wonder if the two are related. I will try disabling `shimmer` and see if that fixes it.

**Comment by leaf-node** [comment]
I was running into this issue while using Impeller. Turning off Impeller or downgrading Flutter were both workarounds for me.

I'm not sure, but upgrading Gradle may have resolved the problem for me? I tried making a code sample that reproduces the issue, but had to upgrade the build system on that fresh project to get it to build. I also went ahead and upgraded Gradle on my main project, knowing that it was possible.

Since then, after a few minutes of testing, I haven't run into the problem. Here's the patch that seems to be working for me:

```patch
diff --git a/android/gradle/wrapper/gradle-wrapper.properties b/android/gradle/wrapper/gradle-wrapper.properties
index 7bb2df6..348c409 100644
--- a/android/gradle/wrapper/gradle-wrapper.properties
+++ b/android/gradle/wrapper/gradle-wrapper.properties
@@ -2,4 +2,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
diff --git a/android/settings.gradle b/android/settings.gradle
index b9e43bd..ebe6f9c 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -18,7 +18,7 @@ pluginManagement {
 
 plugins {
     id "dev.flutter.flutter-plugin-loader" version "1.0.0"
-    id "com.android.application" version "8.1.0" apply false
+    id "com.android.application" version '8.7.3' apply false
     id "org.jetbrains.kotlin.android" version "1.8.22" apply false
 }
 
```

And here is the demo I created that wasn't working for me (no flicker found on Android this way). The issue was originally noticeable when frequently popping in and out of different menus for about a minute or so, and occasionally when scrolling, so it's possible that merely switching between background colors isn't enough to reproduce the bug. Perhaps someone else can use this as a starting point for popping in and out of menus, or infinite scrolling.

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(const MyApp());
}

class AppCubit extends Cubit<ThemeMode> {
  AppCubit() : super(ThemeMode.light) {
    Timer.periodic(Duration(milliseconds: 500), (_) {
      if (state == ThemeMode.light) {
        emit(ThemeMode.dark);
      } else {
        emit(ThemeMode.light);
      }
    });
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => AppCubit(),
        child: BlocBuilder<AppCubit, ThemeMode>(
            builder: (context, state) => MaterialApp(
                  title: 'Flutter Demo',
                  theme: ThemeData(
                    colorScheme:
                        ColorScheme.fromSeed(seedColor: Colors.deepPurple),
                    useMaterial3: true,
                  ),
                  darkTheme: ThemeData(
                      colorScheme: const ColorScheme.dark(
                          primary: Color(0xFF224488),
                          onSurface: Color(0xFFBBBBBB))),
                  themeMode: state,
                  home: const MyHomePage(
                      title: 'Flutter flicker demo (for Android)'),
                )));
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'This screen will switch between light\n'
              'mode and dark mode every 500 ms. Keep\n'
              'an eye out for any major flickering\n'
              'during a transition on Android.',
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by leaf-node** [comment]
> I'm not sure, but upgrading Gradle may have resolved the problem for me? I tried making a code sample that reproduces the issue, but had to upgrade the build system on that fresh project to get it to build. I also went ahead and upgraded Gradle on my main project, knowing that it was possible.

I take that back. I did notice some flickering a few times on my main app. It's happening less than it was when I first commented on this issue, so it hasn't been as easy to catch.

**Comment by leaf-node** [comment]
Update: Not only have I seen flickering with Impeller, but I just reproduced this behavior with Skia. It may be harder to get the flickering visuals with the latter started though.

On my GrapheneOS Pixel 8 phone, with my (not so basic) Android app set to render with Skia, I was tapping back and forth through menus for a few minutes, without any luck. Then I decided to use my app's internal settings to switch from dark mode to light mode. That started a flicker, and one occurred pretty much every time I selected another menu screen until I switched back to dark mode, and eventually it stopped.

I've seen this behavior on the x86 Android emulators before too, but I haven't recently tried reproducing there.

**Comment by leaf-node** [comment]
I updated the demo code to push and pop two different screens, but so far I haven't seen the issue come up yet. The latest code lives here: <https://github.com/leaf-node/flicker_demo>.

**Comment by fareesh** [comment]
I can confirm that there is "flickering" with both skia and impeller since the update. None of the solutions in the thread are leading to a resolution so far. Our test users on "Internal Test" updating the app from the play store beta are seeing it even with impeller disabled.

**Comment by leaf-node** [comment]
I just noticed flicker on the older 3.27.0 version, with Skia enabled.

**Comment by leaf-node** [comment]
I did some testing, and am able to reproduce the bug with my current app on Flutter version `3.24.0`, which was released on July 30th 2024. I wasn't seeing this behavior in my app back then, so something other than the Flutter engine itself must have changed in order to introduce this behavior. Could this be triggered by a Flutter plugin update, an OS library on the host system compiling the app, or by some (perhaps theoretically valid) change in my code?

If someone else could check that they see this behavior even on old versions of Flutter, that would help to confirm we're running into the same bug.

**Comment by leaf-node** [comment]
I added some logging to see if it's actually an issue with my navigation controller switching between screens very rapidly.

However, I'm currently unable to reproduce the bug using Flutter 2.27.2 and the latest OS upgrade of Graphene OS on my Pixel 8, with both Skia and Impeller. While it could be that I'm failing to produce the bug right now, it's also possible that my phone's graphics driver was patched.

**Comment by oshanrasanjana** [comment]
Guys the issue is with impeller - how impeller handels shaders which mean it pre renders the graphics instead of runtime which causes advanced widget trees to lost some frames which obviously cause flickering.In Flutter 3.27.1 the issue was fixed by introducing 
`<meta-data
           android:name="io.flutter.embedding.android.EnableImpeller"
           android:value="false" />
`
instead of 
`
<meta-data
           android:name="io.flutter.embedding.android.DisableImpeller"
           android:value="true" />
`
for android production builds. For debug builds 
`
flutter run -no-enable-impeller
`
worked since 3.27 base version. Yet there is another issue with Vs Code and that is When you run your Application in Debug Version with ▶it just run " flutter run " ,the default debug command for flutter framework.it doesn't matter if you change the vs code debug Configurations it still uses the default debug command.

To  fix it simply run using CLI or configure custom debug command and run it through debug panel in left panel of Vs Code.
`{
           "name": "App name - Debug",
            "request": "launch",
            "type": "dart",
            "toolArgs": [
            "--no-enable-impeller",
            ]
        },
`
And always refer to flutter official documentation at [here](https://docs.flutter.dev/perf/impeller#android).

**How to reproduce:**
1)Create a new flutter project with flutter version 2.7 base onwards
2)add a stack
3)add a fullscreen image in stack
4) add a backdrop blur filter 
5) add a heavy widget -- like a builder / animation on top of it 
6) run on android debug / release mode -- sometimes it works fine on debug and appear on release mode.

Impeller is great for performance but it's like a baby for heavy widgets.
Use Skia and use pre rendered " sksl " bundle for performance.
It Works Like Magic 

Happy coding.

**Comment by leaf-node** [comment]
> Guys the issue is with impeller - how impeller handels shaders which mean it pre renders the graphics instead of runtime which causes advanced widget trees to lost some frames which obviously cause flickering.In Flutter 3.27.1 the issue was fixed by introducing
> 
> ```
> <meta-data
>            android:name="io.flutter.embedding.android.EnableImpeller"
>            android:value="false" />
> ```

That doesn't resolve the problem for me, so we might be facing different bugs with similar behavior. 🫤

**Comment by umutarpat** [comment]
The "Flick" happens to our app only on Android. It happens on >=3.27.0

Adding this to info.plist (as described here: [Impeller](https://docs.flutter.dev/perf/impeller))

```
  <key>FLTEnableImpeller</key>
  <false />
```

and this to AndroidManifest.xml

```
<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="false" />
```

helped fixing the issue by using Skia, but there is more important question here, why did Flutter team make Impeller default if it doesn't work or tested correctly ?

**Comment by wantroba** [comment]
> The "Flick" happens to our app only on Android. It happens on >=3.27.0
> 
> Adding this to info.plist (as described here: [Impeller](https://docs.flutter.dev/perf/impeller))
> 
> ```
>   <key>FLTEnableImpeller</key>
>   <false />
> ```
> 
> and this to AndroidManifest.xml
> 
> ```
> <meta-data
>     android:name="io.flutter.embedding.android.EnableImpeller"
>     android:value="false" />
> ```
> 
> helped fixing the issue by using Skia, but there is more important question here, why did Flutter team make Impeller default if it doesn't work or tested correctly ?

That's exactly what I think. A serious problem that happens with several phones and the developer may not even know it's happening if users don't report the problem. I was having this problem in three different apps and I only detected it because I tested it on a specific phone.

**Comment by stan-at-work** [comment]
Same problem here. When I apply an `ImageFiltered(ImageFilter.blur(sigmaX: 4, sigmaY: 4))` over an `Image.asset`, I get flickering.

**Comment by leaf-node** [comment]
I built my app using an Ubuntu 24.04 build environment and ran into the same issue as before. I was previously building it on OpenSUSE Tumbleweed, which is a rolling release, so this suggests that the bug (at least the one I'm seeing) is not dependent upon super recent dependencies on Linux. Also, others have reported the same or related issues with other build host OSes.

**Comment by leaf-node** [comment]
What happens if you set your phone's display refresh rate to a higher value? When I set mine to 120 Hz, the flickering was still there, but it was less noticeable, and didn't last as long. See for more details:

https://discuss.grapheneos.org/d/13577-strange-flicker-when-toggling-tiles

**Comment by stan-at-work** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now.
> If you find this problem please file a new issue with the same description, what happens, logs and the output of 'flutter doctor -v'. All system setups can be slightly different so it's always better to open new issues and reference the related ones.
> Thanks for your contribution.

What additional info there are 43 comment describing possible solutions. What more information do you need?

**Comment by stan-at-work** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now.
> If you find this problem please file a new issue with the same description, what happens, logs and the output of 'flutter doctor -v'. All system setups can be slightly different so it's always better to open new issues and reference the related ones.
> Thanks for your contribution.

What additional info there are 43 comment describing possible solutions. What more information do you need?
