### ISSUE TITLE
Flutter 3.27.x Platform Views freezes or crashes on Android 10

### ISSUE THREAD

**Issue by lhlhlh111000** [flutter/flutter#160854]
### Steps to reproduce

It works fine on the Android 10 emulator, but there are bugs on two physical Android 10 devices (Mi 8). I tried disabling Impeller, but the problem still exists.

When I rolled back to version 3.24.5, everything worked fine again.

1. The app starts normally.
2. Open the WebView page within the app.
3. Navigate to another page within the WebView, and then return to the WebView page; the page becomes unresponsive or crashes.

### Expected results

The WebView page can interact and display normally.

### Actual results

The WebView page freezes or crashes when returning.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

import 'second_page.dart';

class WebPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _WebPageState();
}

class _WebPageState extends State<WebPage> {
  final controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..loadRequest(Uri.parse('https://github.com/'));

  @override
  void initState() {
    super.initState();

    controller.platform.setOnScrollPositionChange((position) {
      print('AAAAAA${position.x}_${position.y}');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('WebPage'),
      ),
      body: WebViewWidget(controller: controller),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (context) => const SecondPage()));
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

[Reproduce the demo](https://github.com/lhlhlh111000/flutter_widget)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/lhlhlh111000/flutter_widget/blob/main/Screenrecorder-2024-12-26-10-46-01-638.mp4

</details>

### Logs

<details open><summary>Logs</summary>

```console
OpenGLRenderer          com.example.widget_test              W  dequeueBuffer failed, error = -110; switching to fallback
2024-12-25 13:37:52.617 18237-18237 Choreographer           com.example.widget_test              I  Skipped 61 frames!  The application may be doing too much work on its main thread.
2024-12-25 13:37:52.625 18237-18273 OpenGLRenderer          com.example.widget_test              W  reserveNext failed, error = -2147483648 (Unknown error -2147483648)
2024-12-25 13:37:52.628 18237-18273 OpenGLRenderer          com.example.widget_test              I  Davey! duration=1028ms; Flags=0, IntendedVsync=122796470637814, Vsync=122797487304440,
```
```console2
W/OpenGLRenderer (14239): dequeueBuffer failed, error = -110; switching to fallback
I/OpenGLRenderer (14239): Davey! duration=4517ms; Flags=2, IntendedVsync=183046658448444, Vsync=183046658448444, OldestInputEvent=0, NewestInputEvent=0, HandleInputStart=183046658448444, AnimationStart=
183046658448444,
PerformTraversalsStart=183046658448444, DrawStart=183046658448444, SyncQueued=183046674544441, SyncStart=183046674547410, IssueDrawCommandsStart=183046674593295, SwapBuffers=1830511746
11262,
FrameCompleted=183051175909075, DequeueBufferDuration=0, QueueBufferDuration=0,
F/crash_dump64(15521): crash_dump.cpp:465] failed to attach to thread 561: Permission denied
w/OpenGLRenderer (14239): dequeueBuffer failed, error = -110; switching to fallback
E/AN_LOG (14239): >>> msg's executing time is too long
E/ ANR_LOG
(14239): Blocked msg = { when=-16516ms what=0 target=android.view.Choreographer$FrameHandler callback=android.view.Choreographer$FrameDisplayEventReceiver }, cost = 8460 ms
E/ANR_LOG
(14239): >>>Current msg List is:
E/ANR_LOG
(14239) :
Current msg <1>
= { when=-16514ms what=0 target=com-google.android.gms.internal.tasks.zza callback=com.google.android.gms.tasks-zzi }
E/ANR LOG
(14239) :
Current msg <2>
= { when=-16s509ms
what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
E/AN_LOG
(14239) :
Current msg
<3>
= { when=-16508ms
what=0 targeteandroid. 05. Handler callback-10.Flutter. embedding-engine. dart.DartMessengerSSExternalSyntheticLambdal
E/ANR_LOG
(14239): Current
msg
<4>
= { when=-16s508ms what=0 target=com.google.android.gms.internal.tasks.zza callback=com.google.android.gms.tasks.zzi }
E/ANR_LOG
(14239): Current
msg
<5>
= { when=-16s25ms what=0 target=android.os.Handler callback=cn.thinkingdata.analytics.utils.p$c )
E/ANR LOG
(14239):
Current
msg
<6>
{ when=-13525ms what=0 target-android.os.Handler callback=lo.flutter-plugins-webviewflutter.AndroidWebkitLibraryPigeonInstanceManager$$ExternalSyntheticLambda3 }
E/ANR LOG
(14239):
Current
msg <7>
& when=-13525ms what=0 target=android.os.Handler callback=lo.flutter.plugins.webviewflutter.AndroidWebkitLibraryPigeonInstanceManager$SExternalSyntheticLambda3 ›
E/ANR_LOG
(14239):
Current msg
<8>
{ when=-12s489ms what=2 target=android.app.job.JobServiceEngineSJobHandler obj=android.app.job.JobParameters@848c708 }
E/ANR_LOG
(14239):
Current
msg <9>
= { when=-12119ms what=0 target=android.os.Handler callback=com.android.billingclient.api.zzn }
E/ANR_LOG
(14239): Current
msg
<10>
= { when=-12116ms what=0 target=android.os.Handler callback=com.android.billingclient.api.zzn /
E/ANR_LOG
(14239): >>>CURRENT MSG DUMP OVER<<<
I/OpenGLRenderer (14239): Davey! duration=12509ms; Flags=0, IntendedVsync=183038674868385, Vsync=183046724868063, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1830467309152
23, AnimationStart=183046730946681,
PerformTraversalsStart=183046733234650, DrawStart=183046733312931, SyncQueued=183051178193762, SyncStart=183055190609073, IssueDraw/CommandsStart=183055190819230, Swa
pBuffers=183055193145063, FrameCompleted=183055196825688,
DequeueBufferDuration=796000, QueueBufferDuration=1686000,
I/Choreographer (14239): Skipped 509 frames!
The application may be doing too much work on its main thread.
W/OpenGLRenderer (14239): dequeueBuffer failed, error = -110; switching to fallback
I/OpenGLRenderer (14239): Davey! duration=4009ms; Flags=2, IntendedVsync=183055192375637, Vsync=183055192375637, OldestInputEvent=0, NewestInputEvent=0, HandleInputStart=183055192375637, AnimationStart= 183055192375637, PerformTraversalsStart=183055192375637, DrawStart=183055192375637, SyncQueued=183055197555271, SyncStart=183055197558657, IssueDrawCommandsStart=183055197602407, SwapBuffers=1830592010
72822,
FrameCompleted=183059201600478, DequeueBufferDuration=0, QueueBufferDuration=0,
Lost connection to
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.27.1, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.27.1 on channel stable at /Users/a1/fvm/versions/3.27.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (9 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/a1/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • MI 8 (mobile)                   • 39f98a6e              • android-arm64  • Android 10 (API 29)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @lhlhlh111000, can you check on the beta or master channels to see if you still reproduce this on those channels? I don't have the devices in question and this appears to work as expected on my Nokia 6 with android 9

**Comment by MickaelTitecaTAO** [comment]
Hi @danagbemava-nc,

I have downloaded [the repo](https://github.com/lhlhlh111000/flutter_widget) shared by @lhlhlh111000 in order to test it.
Here my results for the Flutter versions below :
- 3.24.3 : no issues
- 3.27.2 : crash
- beta : crash
- master : crash

<details>
  <summary>master channel version</summary>

```
Flutter 3.28.0-2.0.pre.38763 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5517cc9b3b (17 hours ago) • 2025-01-15 22:17:29 +0100
Engine • revision 5517cc9b3b
Tools • Dart 3.7.0 (build 3.7.0-323.0.dev) • DevTools 2.42.0
```

</details>

I can't upgrade my main project because of this crash on an Android 10 device.
I'm available if your need more info.

**Comment by danagbemava-nc** [comment]
Hi @MickaelTitecaTAO, does this work as expected if you disable impeller?

**Comment by MickaelTitecaTAO** [comment]
As @lhlhlh111000 said, I tried disabling Impeller too, but the problem still exists.

**Comment by danagbemava-nc** [comment]
Thanks for info

@MickaelTitecaTAO, can you test with the google maps plugin to see if this issue occurs as well? I want to know if this is a general issue with platform views or if it is specific to the webview plugin

**Comment by MickaelTitecaTAO** [comment]
I've downloaded Google Maps example project [here](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example).

<details>
  <summary>Flutter 3.24.5 : no issues</summary>

https://github.com/user-attachments/assets/1e77104f-9d25-4273-a29d-0eafaea1b21a

</details>

<details>
  <summary>Flutter 3.27.2 : crash</summary>

https://github.com/user-attachments/assets/5f39440a-cce7-4b53-9a96-28d1348b148d

</details>

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

Labeling this for further investigation as I do not a device running a similar version of the OS. 

### Summary
- This appears to be a platform-view issue rather than specific to the webview plugin
- So far, this seems to be reproducing only on android 10 devices (as I tested an android 9 device but I couldn't reproduce it)
- It doesn't appear related to impeller as disabling it doesn't seem to have any effect
- It also seems to persist on the master channel.

**Comment by MickaelTitecaTAO** [comment]
I don't know if the issue is the same than [this one](https://github.com/flutter/flutter/issues/162147) because I don't have an Android 11 device. If someone can test with Android 11, it can be useful.

**Comment by fsilvafactoriabiz** [comment]
Hi, I have tried with Android 11 and the same problem still occurs but using Android 12 you don't have the problem anymore.

Any update to solve this problem?

**Comment by fsilvafactoriabiz** [comment]
Hi, I have tried with Android 11 and the same problem still occurs but using Android 12 you don't have the problem anymore.

The problem occurs because Flutter has set by default the use of Impeller Ingine in version 3.27.

-------

**Solution that worked for me in my case**:

**ANDROID**

Add in the AndroidManifest the following property:

![Image](https://github.com/user-attachments/assets/36410c51-3fb9-45dc-815a-a8ece0b4563f)

**IOS**

Add the following line in the Info.plist file.

![Image](https://github.com/user-attachments/assets/563219fc-14b7-4df3-818b-5610b9fd64ea)

**Flutter RUN**

Another alternative would be to add a flag when starting flutter run:

`flutter run --no-enable-impeller`

**Comment by camsim99** [comment]
@jonahwilliams Note from Android triage: What can the Android team do to help you here?

**Comment by jonahwilliams** [comment]
If disabling Impeller doesn't fix the crash then its likely not an Impeller issue, and probably more related to SurfaceProducer bugs. I'll un-assign for now.

I think you'd need to acquire the device in question and test it.

**Comment by jonahwilliams** [comment]
I can reproduce this on a Galaxy Note10 Lite

**Comment by tentenponce** [comment]
Same issue on my end and same error log, but it is happening on Google maps. It is happening on my Xiaomi Pocophone F1 (Adreno 630)

I uploaded a minimum replicable flutter project as well: https://github.com/tentenponce/flutter_google_map_issue

## 3.27.x - has issue

<img src="https://github.com/tentenponce/flutter_google_map_issue/blob/master/demo/3.27.x.gif" width="200" alt="3.27.x demo">

## 3.24.x - no issue

<img src="https://github.com/tentenponce/flutter_google_map_issue/blob/master/demo/3.24.x.gif" width="200" alt="3.24.x demo">

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/163265

**Comment by tentenponce** [comment]
hi @jonahwilliams , is it already included on 3.29.0? I tried it and the issue is still happening and its worse, as it is stuck even if we don't navigate to a different screen. Here's the minimum replicable project as well: https://github.com/tentenponce/flutter_google_map_issue

Also, the fix seems to only affect samsung devices, and the issue can be replicated on non-samsung devices, as mentioned by the author (Mi 8) and the one that I'm using: Xiaomi Pocophone F1.

The issue is a bit critical on our end since we have a total of 86k users, and around 4% of them (3.5k) have android 10 devices. Although we do have a workaround (refresh map when the issue is encountered) and can proceed with the 3.27.x update, we're still a little bit hesitant because the risk is quite high (app will be unusable if map is stuck).

I'm thinking of opening a new issue, but that would seem to be redundant as the issue specified here is exactly what I'm encountering as well.

Let me know if we can assist even if we need to provide a device to replicate the issue, or whatever information you need.

**Comment by jonahwilliams** [comment]
The cherry pick release has not gone out yet. If you have the devices you can test on master channel.

>  and around 4% of them (3.5k) have android 10 devices.

This is not an Android 10 bug. This is bug that is specific to certain devices.

**Comment by tentenponce** [comment]
> This is not an Android 10 bug. This is bug that is specific to certain devices.

Agree that the issue is specific to certain devices, and as of now the issue can only be replicated on specific Android 10 versions.

I tested it on master channel and the issue is still there, it is similar to 3.29.0, map freezes even just by interacting to it, while on 3.27.x requires to navigate on a different screen after a fling on the map to replicate the issue. I don't have Samsung device that can replicate the issue to test the PR though, but the problem still exists on the device that we're using (Xiaomi Pocophone F1).

Just to add, issue is replicable as well on Huawei P30 (EMUI 12.0.0, which is based on Android 10).

Given this information, is this enough to re-open this issue?

**Comment by jonahwilliams** [comment]
@tentenponce I've landed some more changes on master that changes how 29 devices choose between ImageReader platform views or SurfaceTexture platform views. If you have some time I'd appreciate it if you could test them out on any impacted devices you have.

**Comment by tentenponce** [comment]
@jonahwilliams It's now working on the Xiaomi Pocophone F1 (Android 10) 🎉. I tried the same replication steps where I was able to replicate the issue, and the issue no longer occurs.

I'll test it on other devices where we previously replicated the issue later, and update this comment if it works there as well. Thanks!

**Comment by jonahwilliams** [comment]
@tentenponce the changes are currently only in master channel. They're not in an release branches or versioned releases at this point.

**Comment by matheusbristot** [comment]
@jonahwilliams Impeller alert appears with meta-data enabled, and UI freezes when disabled

Using master (3.30.0-1.0.pre.562)

When I enable Impeller by setting the following meta-data in my AndroidManifest.xml:
`<meta-data android:name="io.flutter.embedding.android.EnableImpeller" android:value="true"/>`

I see this log message:
`I/flutter (32631): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).`

However, even when I change the meta-data value to "false", some freezes still occur and UI interactions do not happen.

Physical device: Samsung Galaxy A20s (SM-A207M/DS) with GPU Qualcomm Adreno 506 (600MHz)
![Image](https://github.com/user-attachments/assets/6788f161-a7de-4c63-9e53-87e60152b55e)


<details open><summary>Doctor output</summary>
```console
[✓] Flutter (Channel master, 3.30.0-1.0.pre.562, on macOS 15.3.1 24D70 darwin-arm64, locale pt-BR) [3,7s]
    • Flutter version 3.30.0-1.0.pre.562 on channel master at /Users/matheusbristot/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 234b50aa53 (3 hours ago), 2025-03-12 11:51:35 +0200
    • Engine revision 234b50aa53
    • Dart version 3.8.0 (build 3.8.0-177.0.dev)
    • DevTools version 2.44.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [3,5s]
    • Android SDK at /Users/matheusbristot/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/matheusbristot/Library/Android/sdk
    • Java binary at: /Users/matheusbristot/.sdkman/candidates/java/current/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Corretto-17.0.13.11.1 (build 17.0.13+11-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0) [2,8s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [11ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.3) [10ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.98.0) [9ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (4 available) [7,6s]
    • SM A207M (mobile)           • R9QN501JZXP                          • android-arm64 • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5556                        • android-arm64 • Android 15 (API 35) (emulator)
    • iPhone 15 Pro (mobile)      • AFA8A3E3-C938-4706-B096-899278B5D5D6 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64  • macOS 15.3.1 24D70 darwin-arm64
    ! Error: Browsing on the local area network for iBristot. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [332ms]
    • All expected network resources are available.
```

</details>

**Comment by jonahwilliams** [comment]
Unfortunately if disabling impeller does not fix the problem then it seems unlikely that it is related to impeller, no?

**Comment by matheusbristot** [comment]
Sorry. I updated the comment.

It is the opposite, when disable fix the freezing.

**Comment by jonahwilliams** [comment]
Are you using the same sample code as this original issue filler had or is this a different bug that needs a new issue?

**Comment by jonahwilliams** [comment]
Fixed in 3.29.2

**Comment by JDongKhan** [comment]
How to solve on 3.27.4？ @jonahwilliams  

We cannot upgrade to 3.29 in the short term.
