### ISSUE TITLE
[Impeller] App launches with a black screen on some devices 

### ISSUE THREAD

**Issue by korama9320** [flutter/flutter#160866]

**Comment by Gershon17** [comment]
@korama9320 facing the same issue but for Android 10. Found any fix?

**Comment by korama9320** [comment]
@Gershon17 I uploaded new version with. flutter 3.24.5 for now

**Comment by Mashi-91** [comment]
Still Showing Black Screen on Samsung s21fe android 14. After Updating the app. Fixed the issue by clearing the data of app.

[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.26100.2605], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)

Got this Black Screen Error After Updating the app. Unless you do clear data.
So Anyone know how to fix it.

**Comment by Mashi-91** [comment]
@korama9320 does this fixed the issue?

**Comment by Mashi-91** [comment]
After Updating Latest Version Fixed the issue.
Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale en-US)

**Comment by danagbemava-nc** [comment]
Hi @korama9320, can you share the devices that are experiencing this issue? Please also share screenshots/recordings of the issue in question. Do you get any errors on startup?

**Comment by korama9320** [comment]
![WhatsApp Image 2025-01-02 at 11 35 40](https://github.com/user-attachments/assets/89c416ec-788a-4ab1-9f73-a68661d3b2d0)
![WhatsApp Image 2025-01-02 at 11 36 04](https://github.com/user-attachments/assets/4f6e18b8-0207-4a90-a794-910a3c9eda79)
![WhatsApp Image 2025-01-02 at 11 36 36](https://github.com/user-attachments/assets/5a37c3d5-088f-49cf-ac23-e9c315d35dc4)

https://github.com/user-attachments/assets/da65f413-4b47-4282-a88c-f70d96987ae3

![WhatsApp Image 2025-01-02 at 11 35 40 (1)](https://github.com/user-attachments/assets/ed7128db-dfeb-4467-94bc-3d5930d12503)

I don't have device names but i will try to get them @danagbemava-nc 
ه

**Comment by korama9320** [comment]
it didn't happen to me every thing was going very well when i tested the app .these were users complaint when they updated the app.

**Comment by korama9320** [comment]
I managed to get a device name oppo CPH2121

**Comment by Mashi-91** [comment]
@korama9320 Maybe try to update to latest version. And update gradle also.
Let me know if thts help.

**Comment by kjm0202** [comment]
Related to https://github.com/flutter/flutter/issues/160866
Adding a block for not using Impeller doesn't seem to work properly either.
I think the only solution for now is downgrading Flutter SDK into 3.24.5 or below.

**Comment by danagbemava-nc** [comment]
Hi @korama9320, what versions of android were they running? Also, if you disable impeller, does this work as expected?

**Comment by korama9320** [comment]
@Mashi-91 flutter 3.7.1 is the latest

**Comment by danagbemava-nc** [comment]
Hi @korama9320, just to confirm, at present, the only devices experiencing this issue with stable 3.27.1 are the oppo devices, is that correct?

**Comment by korama9320** [comment]
@danagbemava-nc  realme 6 users also experience screen glitches while displaying animation

**Comment by danagbemava-nc** [comment]
Hi @korama9320, is this with impeller enabled or disabled?

**Comment by danagbemava-nc** [comment]
#### Summary

oppo CPH2121 - PowerVR GM9446
realme 6 - Mali-G76 MC4

The devices this issue are appearing on are stated above. They have different gpus (according to data from gsmarena) and there are some screenshots of the glitches in https://github.com/flutter/flutter/issues/160866#issuecomment-2567497044

This seems to be limited to impeller. 

Labeling for further investigation

**Comment by korama9320** [comment]
@yasmineLalabouali  you could try to run it with impeller disabled flutter run --no-enable-impeller
but i went back to flutter 3.24.5 .

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/161841

**Comment by korama9320** [comment]
@jonahwilliams I tried to update to 3.27.3 and the problem still there. 

https://github.com/user-attachments/assets/a6be0988-2b8b-4c28-b5ab-ff86f6610664

@yasmineLalabouali  this worked for me thanks.

**Comment by jonahwilliams** [comment]
This change will be in 3.29
