### ISSUE TITLE
Flutter commands no longer work if a branch is cloned with `--single-branch`

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#162251]
### Steps to reproduce

I have a GitHub action for cloning Flutter to run tests. The test run on various different branches but to save time/space only the branch being tested is cloned (the other branches run in different jobs) using `--single-branch`.

This used to work fine, but recently has stopped working because Flutter assumes it can access `origin/master`.

To repro:

1. Run `git clone --single-branch --branch beta https://github.com/flutter/flutter` to clone the beta branch without all others
2. Run `./flutter_beta/bin/flutter doctor`

### Expected results

`flutter doctor` should run successfully.

### Actual results

```
PS D:\Temp> ./flutter_beta/bin/flutter doctor
fatal: Not a valid object name origin/master
Error: Unable to determine engine version...
```

### Code sample

N/A

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Image](https://github.com/user-attachments/assets/3db2ea7f-5a48-42b5-80f6-455a1f2dbfd3)

</details>

### Logs

<details open><summary>Logs</summary>

Unable to get any verbose logs:

```console
PS D:\Temp> ./flutter_beta/bin/flutter doctor -v
fatal: Not a valid object name origin/master
Error: Unable to determine engine version...
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Unable to run:

```console
PS D:\Temp> ./flutter_beta/bin/flutter doctor -v
fatal: Not a valid object name origin/master
Error: Unable to determine engine version...
```

</details>

**Comment by DanTup** [comment]
I found https://github.com/flutter/flutter/issues/160626#issuecomment-2555975455 from @christopherfujino that says:

> Shallow clones of flutter/flutter was never officially supported. I'm not sure if that's related to this failure, though...

But it's also stuck out, so I don't know if this is actually just by design or not. If so, happy to close this and stop using `--single-branch`.

**Comment by christopherfujino** [comment]
FYI @jtmcdole

**Comment by jtmcdole** [comment]
> Further fetches into the resulting repository will only update the remote-tracking branch for the branch this option was used for the initial cloning.

Darn. The following seems slow as well and still checks out ~137MB of `.git`

```shell
git clone --depth=1 --no-single-branch --branch beta https://github.com/flutter/flutter
```

**Comment by jtmcdole** [comment]
Ah: `engine.version` should get checked into the `beta` branch. We are not using the origin/master to find the sha: 

https://github.com/flutter/flutter/blob/flutter-3.29-candidate.0/bin/internal/update_engine_version.sh#L39

**Comment by DanTup** [comment]
@jtmcdole it was a minor optimisation for me so I just removed `--single-branch` earlier. Mostly I wasn't sure if it was deliberate/known or not (and not sure if it might affect many others).

I could change the command, although my next question would be, are those supported if the original command is not?

**Comment by christopherfujino** [comment]
> Ah: `engine.version` should get checked into the `beta` branch. We are not using the origin/master to find the sha:
> 
> https://github.com/flutter/flutter/blob/flutter-3.29-candidate.0/bin/internal/update_engine_version.sh#L39

Ahh yeah, I just fixed this earlier today: https://github.com/flutter/flutter/commit/45459707c029b168a61dcde1f1c1d64df9d529af

We'll need another publish build to update the beta branch

**Comment by christopherfujino** [comment]
@DanTup can you try again? I *think* we fixed this.

**Comment by DanTup** [comment]
@christopherfujino unfortunately it's still the same:

![Image](https://github.com/user-attachments/assets/623245f9-bfc9-4af6-84c1-0ea204bef43a)

```
PS D:\Temp> git clone --single-branch --branch beta https://github.com/flutter/flutter
Cloning into 'flutter'...
remote: Enumerating objects: 957590, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 957590 (delta 1), reused 0 (delta 0), pack-reused 957586 (from 2)
Receiving objects: 100% (957590/957590), 238.15 MiB | 21.43 MiB/s, done.
Resolving deltas: 100% (675978/675978), done.
Updating files: 100% (14688/14688), done.
PS D:\Temp> ./flutter/bin/flutter doctor
fatal: Not a valid object name origin/master
Error: Unable to determine engine version...
```

**Comment by filiph** [comment]
FWIW, I just started seeing this error after a regular `flutter upgrade`. I have my flutter installation managed by FVM, but otherwise it's nothing special.

```shell
$ which flutter
/Users/filiph/fvm/default/bin/flutter
$ flutter --version
fatal: Not a valid object name origin/master
$ cd ~/fvm/default/
$ git fetch --all
$ git remote -v
origin	https://github.com/flutter/flutter.git (fetch)
origin	https://github.com/flutter/flutter.git (push)
$ git status
On branch stable
Your branch is up to date with 'origin/stable'.

nothing to commit, working tree clean
$ bin/dart --version
fatal: Not a valid object name origin/master
```

I don't know what I botched and it's possible this is unrelated — thought I'd report just in case.

**Comment by mi-laf** [comment]
In our pipelines we fetch flutter via 
`git clone --depth 1 https://github.com/flutter/flutter.git -b [version]`

If this is not officially supported, we will just change this, obviously. But I just wanted to say that this worked for quite some time now and it reduced the initialization overhead of our pipelines quite a bit. Therefore, unless the change is necessary, would be nice to get this back.

**Comment by jtmcdole** [comment]
We're investigating something similar to this for shallow copies.

**Comment by jtmcdole** [comment]
#163672 should fix this.

**Comment by DanTup** [comment]
> https://github.com/flutter/flutter/pull/163672 should fix this for any "release" version of flutter (stable, beta, 3.29.0, etc) in which engine.version is tracked.

I presume this will only work for the branches/tags that include this change (eg. the next beta, stable, tagged versions etc.)?

**Comment by jtmcdole** [comment]
I'm working on a cherry pick, but yes.

**Comment by DanTup** [comment]
Great, thanks! (it wasn't a request for such, I just wanted to be sure I understood so I didn't test and claim it wasn't fixed 😄)

**Comment by Rexios80** [comment]
This is affecting the example post clone script for Xcode Cloud here: https://docs.flutter.dev/deployment/cd#post-clone-script

**Comment by matanlurey** [comment]
This should be fixed now at HEAD.
