### ISSUE TITLE
Bug: Black Screen Issue in Flutter SDK 3.27.0+ on Oppo Devices

### ISSUE THREAD

**Issue by JagaranMaharjan** [flutter/flutter#162303]
### Steps to reproduce

The black screen issue arises when running Flutter apps on the following device specifications:
**Device Model:** Oppo F19 Pro
**Model Name:** CPH2285
**Processor:** Octa-core
**Operating System:** Android 13

**Steps to reproduce black screen issue:**
Step 1: Install or upgrade your Flutter SDK to version 3.27.0 or above.
Step 2: Create new flutter project or clone project from: https://github.com/JagaranMaharjan/flutter_black_screen_issue
Step 3: Navigate to the project directory and run the app
Step 4: Observe that the app runs but only displays a black screen.

### Expected results

When running a Flutter app on the Oppo F19 Pro (Model: CPH2285, Android 13) with Flutter SDK 3.27.0+, the app should:

Display the home screen or initial user interface immediately after launching.
Transition smoothly from the splash screen (if implemented) to the main app without any delays or issues.

### Actual results

Instead of showing the expected UI:

The app launches but remains stuck on a black screen.
No UI elements are rendered, and there’s no feedback or error displayed to indicate the problem.

### Code sample

Project Repository: https://github.com/JagaranMaharjan/flutter_black_screen_issue

### Screenshots or Video

<details open>
<summary>
The black screen issue arises when running Flutter apps on the following device specifications:
**Device Model:** Oppo F19 Pro
**Model Name:** CPH2285
**Processor:** Octa-core
**Operating System:** Android 13
</summary>

</details>

### Logs

<details open><summary>Logs</summary>

**Console Log File:**
[+2368 ms] W/libc    ( 9629): Access denied finding property "persist.vendor.debug.gpud.enable"
[   +1 ms] D/BLASTBufferQueue( 9629): [SurfaceView[com.jagaran.testing_apk/com.jagaran.testing_apk.MainActivity]#1](f:0,a:1) acquireNextBufferLocked size=1080x2268 mFrameNumber=1 applyTransaction=true mTimestamp=287720379107992(auto) mPendingTransactions.size=0 graphicBufferId=41356240093192 transform=0
[   +1 ms] D/VRI[MainActivity]( 9629): registerCallbacksForSync syncBuffer=false
[  +29 ms] D/BLASTBufferQueue( 9629): [VRI[MainActivity][com.jagaran.testing_apk/com.jagaran.testing_apk.MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=287720418143761(auto) mPendingTransactions.size=0 graphicBufferId=41356240093197 transform=0
[  +10 ms] D/VRI[MainActivity]( 9629): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
[        ] W/Parcel  ( 9629): Expecting binder but got null!
[        ] D/VRI[MainActivity]( 9629):  debugCancelDraw  cancelDraw=false,count = 228,android.view.ViewRootImpl@afb9d00
[        ] D/VRI[MainActivity]( 9629): draw finished.
[  +51 ms] D/VRI[MainActivity]( 9629): onFocusEvent true
[   +3 ms] I/Quality ( 9629): TaskTrackInfo {"Pkg":com.jagaran.testing_apk,"Window":com.jagaran.testing_apk.MainActivity,"Type":1,"Action":10,"Cost":4980,"FV":16,"JC":16-90-0-0-0-0-0-1-20-1-0-0-0-0-0-0-0-0-1-0-4950-3964-287720389-1538,"SF":no-need,"UITid":9629,"RTid":16886} TTI:cannot access task track path
[+1330 ms] D/ProfileInstaller( 9629): Installing profile for com.jagaran.testing_apk
[+2425 ms] V/AutofillManager( 9629): requestHideFillUi(null): anchor = null
[   +4 ms] D/OplusSystemUINavigationGestureExtImpl( 9629): regionString = null
[  +56 ms] D/OplusInputMethodManagerInternal( 9629): get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@bbf9b53
[  +80 ms] V/AutofillManager( 9629): requestHideFillUi(null): anchor = null
[+1901 ms] V/AutofillManager( 9629): requestHideFillUi(null): anchor = null
[ +113 ms] I/ran.testing_apk( 9629): Background concurrent copying GC freed 14MB AllocSpace bytes, 6(120KB) LOS objects, 68% free, 2785KB/8929KB, paused 76us,26us total 113.494ms
[   +1 ms] W/FinalizerDaemon( 9629): type=1400 audit(0.0:33400): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c136,c257,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=com.jagaran.testing_apk

[log.txt](https://github.com/user-attachments/files/18570491/log.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

jagaran@Jagarans-MacBook-Pro testing_apk % flutter doctor -v
[✓] Flutter (Channel stable, 3.27.3, on macOS 15.2 24C101 darwin-arm64 (Rosetta), locale en-NP)
    • Flutter version 3.27.3 on channel stable at /Users/jagaran/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (7 days ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/jagaran/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Users/jagaran/Downloads/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.96.4)
    • VS Code at /Users/jagaran/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • CPH2285 (mobile)                • 89CAHYS4EYBQ85R8      • android-arm64  • Android 13 (API 33)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.2 24C101 darwin-arm64 (Rosetta)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.2 24C101 darwin-arm64 (Rosetta)
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 132.0.6834.111
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Ambition Guru’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Santosh’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
jagaran@Jagarans-MacBook-Pro testing_apk % 

</details>

**Comment by bcihanc** [comment]
+1

I can say that this problem also exists in the Oppo Reno series.

**Comment by darshankawar** [comment]
@JagaranMaharjan 
Looking at the details of the device you mentioned, it uses PowerVR GPU and the black screen issue seems to be related to this hardware you are using and this is fixed by https://github.com/flutter/flutter/pull/161841, so I suggest you to switch to latest master / main branch and re-run your scenario to check if it works or not.


https://www.gsmarena.com/oppo_f19_pro-10761.php

**Comment by JagaranMaharjan** [comment]
@darshankawar , I've already switched to the latest master or main branch and tried, but the same issue still persists in my case

**Comment by darshankawar** [comment]
@JagaranMaharjan Does it work if you running without Impeller ?

**Comment by JagaranMaharjan** [comment]
@darshankawar without impeller, it works well

**Comment by jonahwilliams** [comment]
Can you share the flutter doctor from the master channel version you used? All of these devices should be disabled post https://github.com/flutter/flutter/pull/161841 .

**Comment by theamorn** [comment]
Our app, built with Flutter 3.27.2 and EnableImpeller set to false, is still experiencing issues on Oppo devices.

So far, we have identified issues with the Oppo A93 and A94. We have already rolled back to Flutter 3.19.4, which was our last version on the Play Store so I want to confirm that 

It's not working without Impeller

**Comment by jonahwilliams** [comment]
@theamorn I suspect you did not correctly disable Impeller. Please double check https://docs.flutter.dev/perf/impeller#android

On this issue: we narrowed the cause of a large number of these blackscreen/rendering problems to issues we're having with PowerVR GPUs. These devices are now prevented from using Vulkan and instead will use OpenGLES. This change is available on master channel and will be in 3.29

**Comment by theamorn** [comment]
At first, I had the same thought, so I checked our production app by pulling files and looking at our AndroidManifest.xml.

I carefully checked every character and letter to make sure it was 100% correct. I can confirm it matches the Flutter documentation for disabling Impeller perfectly.

I looked into the Flutter repository and checked the code from 
commit **c21336e2277f34cdfd2a06ef1a59b7ba241129dc**, 
but it didn't fix the Oppo issues.

After looking around more, I found a commit that reverts Skia, which I think is the cause of my issue: 
commit **683096002da9baa282bd213c9e1e9aa7698baf78**

After going back to this commit, everything works fine - my Oppo A94 no longer shows a black screen. for turning off Impeller

Would you mind checking this again? I think even version 3.29 might not fix this issue, and it might move to a later version.

I'm ready to help with my device if you need any additional testing!
If could point out which commit will be the release in 3.29, I will go to test it

**Comment by theamorn** [comment]
I can confirm that:

When using Master commit: 4d08217f8dca7b0564decc82f22fcb2becf7b5e6

The Oppo A94 works perfectly with both Impeller settings (on and off). While I believe it's off behind the scenes, I explicitly set it to off in AndroidManifest.xml.

**Comment by GhoulBoii** [comment]
Hi,

Not a flutter dev, but I use a handful of flutter apps on [my Oppo A15](https://www.gsmarena.com/oppo_a15-10497.php). I have observed this issue for a couple of weeks now, where I enter a flutter app and the UI is glitched. The only temporary solution I found was to reinstall/update the app and the issue would be fixed for the first couple app launches. I hope this issue can be fixed as soon as possible so I could use these apps on my phone again.

Broken flutter apps:
- [Obtainium](https://github.com/ImranR98/Obtainium)
- [Ente Auth](https://github.com/ente-io/ente)
- [Flexify](https://github.com/brandonp2412/Flexify)

**Comment by fanyqe** [comment]
Hello, this problem needs to be solved urgently and should come to the stable version. Because Google Play rejects our apps. This is a big problem.

**Comment by edward-reynara** [comment]
its work for me https://stackoverflow.com/a/79373487

**Comment by mh-sarkar** [comment]
@jonahwilliams This is not fixed for all oppo devices. I face this issue on Oppo android version 9 for this 3.29.0 version.

**Comment by mh-sarkar** [comment]
If Oppo Android version 9 for Flutter 3.29.0 version issue occurs, then add this:
`<meta-data
        android:name="io.flutter.embedding.android.EnableImpeller"
        android:value="false" />`

**Comment by PhanVanLinh** [comment]
@jonahwilliams in the future, will this fix be included in version 3.27.x, or will we have to upgrade to 3.29.x?
