### ISSUE TITLE
Debug mode and hot reload fail on iOS 18.4 due to JIT restriction `error: mprotect failed: 13 (Permission denied)`

### ISSUE THREAD

**Issue by passsionforprogramming** [flutter/flutter#163984]
### Workarounds

> [!IMPORTANT]  
> iOS 18.4 beta 1 breaks Flutter's debug mode on physical devices. If you have upgraded your device to iOS 18.4 beta 1, please upgrade to iOS 18.4 beta 2 or higher.

### Steps to reproduce

1. Run flutter ios in debug mode with ios 18.4
2. Notice the error ../../../flutter/third_party/dart/runtime/vm/virtual_memory_posix.cc: 428: error: mprotect failed: 13 (Permission denied)
3. The build will fail. === Crash occurred when compiling unknown function in unoptimized JIT mode in unknown pass

### Expected results

Fluter build should not fail when in debug mode.

### Actual results

Flutter build fails on ios in debug mode with version 18.4

### Code sample

This is related to the build and not the code.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
../../../flutter/third_party/dart/runtime/vm/virtual_memory_posix.cc: 428: error: mprotect failed: 13 (Permission denied)
version=3.7.0 (stable) (Wed Feb 5 04:53:58 2025 -0800) on "ios_arm64"
pid=726, thread=259, isolate_group=vm-isolate(0x11ea52800), isolate=vm-isolate(0x11ebe5800)
os=ios, arch=arm64, comp=no, sim=no
isolate_instructions=10f8ab5a0, vm_instructions=10f8ab5a0
fp=16eee4f50, sp=16eee4f30, pc=110302e84
  pc 0x0000000110302e84 fp 0x000000016eee4f50 Dart_DumpNativeStackTrace+0x18
  pc 0x000000010feb1428 fp 0x000000016eee4f70 dart::Assert::Fail(char const*, ...) const+0x30
  pc 0x000000010ffac33c fp 0x000000016eee5420 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x82c
  pc 0x0000000110039cb0 fp 0x000000016eee5a30 dart::StubCode::Init()+0x320
  pc 0x000000010fefc4f4 fp 0x000000016eee64e0 dart::Dart::DartInit(Dart_InitializeParams const*)+0x2b18
  pc 0x00000001102e9754 fp 0x000000016eee6960 Dart_Initialize+0x60
  pc 0x000000010fe71e24 fp 0x000000016eee6f30 flutter::DartVM::Create(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>, std::_fl::shared_ptr<flutter::IsolateNameServer>)+0x1d64
  pc 0x000000010fdcdf9c fp 0x000000016eee7690 flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners const&, flutter::Settings, std::_fl::function<std::_fl::unique_ptr<flutter::PlatformView, std::_fl::default_delete<flutter::PlatformView>> (flutter::Shell&)> const&, std::_fl::function<std::_fl::unique_ptr<flutter::Rasterizer, std::_fl::default_delete<flutter::Rasterizer>> (flutter::Shell&)> const&, bool)+0x310
  pc 0x000000010f8ba564 fp 0x000000016eee8420 -[FlutterEngine createShell:libraryURI:initialRoute:]+0xa8c
  pc 0x000000010f8ece64 fp 0x000000016eee8480 -[FlutterViewController sharedSetupWithProject:initialRoute:]+0x198
  pc 0x000000010f8ecca4 fp 0x000000016eee84b0 -[FlutterViewController awakeFromNib]+0x6c
  pc 0x000000018a580450 fp 0x000000016eee8980 <redacted>+0x6dc
  pc 0x000000018a5ef55c fp 0x000000016eee89f0 <redacted>+0xec
  pc 0x000000018a5ef368 fp 0x000000016eee8a20 <redacted>+0x50
  pc 0x000000018a5eee68 fp 0x000000016eee8a80 <redacted>+0x8c
  pc 0x000000018a48d180 fp 0x000000016eee8ac0 <redacted>+0xa8
  pc 0x000000018a48d980 fp 0x000000016eee8cd0 <redacted>+0x338
  pc 0x000000018a4cebd8 fp 0x000000016eee8d10 <redacted>+0x84
  pc 0x000000018a3e11e4 fp 0x000000016eee8d60 _UIScenePerformActionsWithLifecycleActionMask+0x70
  pc 0x000000018a3e32c0 fp 0x000000016eee8e20 <redacted>+0xfc
  pc 0x000000018a3e2fb4 fp 0x000000016eee8e90 <redacted>+0xd4
  pc 0x000000018a3e1cc8 fp 0x000000016eee8fa0 <redacted>+0x260
  pc 0x000000018a3e19e8 fp 0x000000016eee9010 <redacted>+0xf4
  pc 0x000000018a3e1594 fp 0x000000016eee9050 <redacted>+0x94
  pc 0x000000018a28cc38 fp 0x000000016eee9150 <redacted>+0x2e0
  pc 0x000000018a28c260 fp 0x000000016eee91c0 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion+0xe0
  pc 0x000000018a3361d8 fp 0x000000016eee92c0 <redacted>+0x13c
  pc 0x000000018a335f64 fp 0x000000016eee9410 <redacted>+0x268
  pc 0x000000018a3358b0 fp 0x000000016eee9580 <redacted>+0xd0
  pc 0x000000018a2e13ac fp 0x000000016eee9640 <redacted>+0xf4
  pc 0x000000018a2e0ed4 fp 0x000000016eee9720 <redacted>+0x2fc
  pc 0x000000018a2e0b6c fp 0x000000016eee97b0 <redacted>+0x120
  pc 0x00000001a279330c fp 0x000000016eee98f0 <redacted>+0x120
  pc 0x00000001a277f2d8 fp 0x000000016eee9920 <redacted>+0x44
  pc 0x00000001a27998b8 fp 0x000000016eee99f0 <redacted>+0x1b4
  pc 0x00000001a2798f2c fp 0x000000016eee9ab0 <redacted>+0x120
  pc 0x00000001a2798c58 fp 0x000000016eee9af0 <redacted>+0xa8
  pc 0x00000001a279913c fp 0x000000016eee9c40 <redacted>+0x1d8
  pc 0x00000001051c5f80 fp 0x000000016eee9c50 _dispatch_client_callout+0x10
  pc 0x00000001051b07fc fp 0x000000016eee9ca0 _dispatch_block_invoke_direct+0x128
  pc 0x00000001a2795658 fp 0x000000016eee9cd0 <redacted>+0x34
  pc 0x00000001a27955d8 fp 0x000000016eee9d60 <redacted>+0xf0
  pc 0x00000001a27954b0 fp 0x000000016eee9d80 <redacted>+0x1c
  pc 0x0000000187884dc8 fp 0x000000016eee9d90 <redacted>+0x1c
  pc 0x0000000187884d5c fp 0x000000016eee9dc0 <redacted>+0xac
  pc 0x0000000187883ae0 fp 0x000000016eee9e20 <redacted>+0xe8
  pc 0x0000000187882d20 fp 0x000000016eeeab90 <redacted>+0x348
  pc 0x00000001878a77f0 fp 0x000000016eeeac10 CFRunLoopRunSpecific+0x23c
  pc 0x00000001d4afa190 fp 0x000000016eeeac70 GSEventRunModal+0xa8
  pc 0x000000018a4ce158 fp 0x000000016eeeacf0 <redacted>+0x330
  pc 0x000000018a4cc388 fp 0x000000016eeead80 UIApplicationMain+0x150
  pc 0x000000018a927eb4 fp 0x000000016eeeadc0 <redacted>+0x265c
  pc 0x0000000102b0d26c fp 0x000000016eeeae10 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ+0x78
  pc 0x0000000102b0d1e4 fp 0x000000016eeeae40 $s6Runner11AppDelegateC5$mainyyFZ+0x2c
  pc 0x0000000102b0d2e8 fp 0x000000016eeeae60 __debug_main_executable_dylib_entry_point+0x1c
  pc 0x00000001aee53a58 fp 0x000000016eeeb4c0 <redacted>+0x174c
-- End of DumpStackTrace
=== Crash occurred when compiling unknown function in unoptimized JIT mode in unknown pass
=== Flow Graph not available```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.97.2)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Nick’s iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by seokyongKim** [comment]
Likewise, I'm not doing a debug build on my actual iOS 18.4 beta because of that issue.
When you build relase, it works fine.
I think it's a JIT question.

**Comment by seokyongKim** [comment]
```
../../../flutter/third_party/dart/runtime/vm/virtual_memory_posix.cc: 428: error: mprotect failed: 13 (Permission denied)
version=3.6.0 (stable) (Thu Dec 5 07:46:24 2024 -0800) on "ios_arm64"
pid=3252, thread=259, isolate_group=vm-isolate(0x107205400), isolate=vm-isolate(0x107369000)
os=ios, arch=arm64, comp=no, sim=no
isolate_instructions=108e375a0, vm_instructions=108e375a0
fp=16bb19560, sp=16bb19540, pc=109889864
  pc 0x0000000109889864 fp 0x000000016bb19560 Dart_DumpNativeStackTrace+0x18
  pc 0x000000010943aeb8 fp 0x000000016bb19580 dart::Assert::Fail(char const*, ...) const+0x30
  pc 0x0000000109536100 fp 0x000000016bb19a30 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x82c
  pc 0x00000001095f51c8 fp 0x000000016bb1a040 dart::StubCode::Init()+0x31c
  pc 0x0000000109485c30 fp 0x000000016bb1ab00 dart::Dart::DartInit(Dart_InitializeParams const*)+0x2a9c
  pc 0x0000000109870310 fp 0x000000016bb1ab20 Dart_Initialize+0x3c
  pc 0x0000000108f1aaf4 fp 0x000000016bb1b0f0 flutter::DartVM::Create(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>, std::_fl::shared_ptr<flutter::IsolateNameServer>)+0x1d60
  pc 0x00000001093f17dc fp 0x000000016bb1b850 flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners const&, flutter::Settings, std::_fl::function<std::_fl::unique_ptr<flutter::PlatformView, std::_fl::default_delete<flutter::PlatformView>> (flutter::Shell&)> const&, std::_fl::function<std::_fl::unique_ptr<flutter::Rasterizer, std::_fl::default_delete<flutter::Rasterizer>> (flutter::Shell&)> const&, bool)+0x310
  pc 0x0000000108e3b060 fp 0x000000016bb1c5c0 -[FlutterEngine createShell:libraryURI:initialRoute:]+0x934
  pc 0x0000000108e42c4c fp 0x000000016bb1c630 -[FlutterViewController sharedSetupWithProject:initialRoute:]+0x1cc
  pc 0x0000000108e42a58 fp 0x000000016bb1c660 -[FlutterViewController awakeFromNib]+0x58
  pc 0x00000001876c0450 fp 0x000000016bb1cb30 <redacted>+0x6dc
  pc 0x000000018772f55c fp 0x000000016bb1cba0 <redacted>+0xec
  pc 0x000000018772f368 fp 0x000000016bb1cbd0 <redacted>+0x50
  pc 0x000000018772ee68 fp 0x000000016bb1cc30 <redacted>+0x8c
  pc 0x00000001875cd180 fp 0x000000016bb1cc70 <redacted>+0xa8
  pc 0x00000001875cd980 fp 0x000000016bb1ce80 <redacted>+0x338
  pc 0x000000018760ebd8 fp 0x000000016bb1cec0 <redacted>+0x84
  pc 0x00000001875211e4 fp 0x000000016bb1cf10 _UIScenePerformActionsWithLifecycleActionMask+0x70
  pc 0x00000001875232c0 fp 0x000000016bb1cfd0 <redacted>+0xfc
  pc 0x0000000187522fb4 fp 0x000000016bb1d040 <redacted>+0xd4
  pc 0x0000000187521cc8 fp 0x000000016bb1d150 <redacted>+0x260
  pc 0x00000001875219e8 fp 0x000000016bb1d1c0 <redacted>+0xf4
  pc 0x0000000187521594 fp 0x000000016bb1d200 <redacted>+0x94
  pc 0x00000001873ccc38 fp 0x000000016bb1d300 <redacted>+0x2e0
  pc 0x00000001873cc260 fp 0x000000016bb1d370 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion+0xe0
  pc 0x00000001874761d8 fp 0x000000016bb1d470 <redacted>+0x13c
  pc 0x0000000187475f64 fp 0x000000016bb1d5c0 <redacted>+0x268
  pc 0x00000001874758b0 fp 0x000000016bb1d730 <redacted>+0xd0
  pc 0x00000001874213ac fp 0x000000016bb1d7f0 <redacted>+0xf4
  pc 0x0000000187420ed4 fp 0x000000016bb1d8d0 <redacted>+0x2fc
  pc 0x0000000187420b6c fp 0x000000016bb1d960 <redacted>+0x120
  pc 0x000000019f8d330c fp 0x000000016bb1daa0 <redacted>+0x120
  pc 0x000000019f8bf2d8 fp 0x000000016bb1dad0 <redacted>+0x44
  pc 0x000000019f8d98b8 fp 0x000000016bb1dba0 <redacted>+0x1b4
  pc 0x000000019f8d8f2c fp 0x000000016bb1dc60 <redacted>+0x120
  pc 0x000000019f8d8c58 fp 0x000000016bb1dca0 <redacted>+0xa8
  pc 0x000000019f8d913c fp 0x000000016bb1ddf0 <redacted>+0x1d8
  pc 0x0000000105e25f80 fp 0x000000016bb1de00 _dispatch_client_callout+0x10
  pc 0x0000000105e107fc fp 0x000000016bb1de50 _dispatch_block_invoke_direct+0x128
  pc 0x000000019f8d5658 fp 0x000000016bb1de80 <redacted>+0x34
  pc 0x000000019f8d55d8 fp 0x000000016bb1df10 <redacted>+0xf0
  pc 0x000000019f8d54b0 fp 0x000000016bb1df30 <redacted>+0x1c
  pc 0x00000001849c4dc8 fp 0x000000016bb1df40 <redacted>+0x1c
  pc 0x00000001849c4d5c fp 0x000000016bb1df70 <redacted>+0xac
  pc 0x00000001849c3b44 fp 0x000000016bb1dfd0 <redacted>+0x14c
  pc 0x00000001849c2d20 fp 0x000000016bb1ed40 <redacted>+0x348
  pc 0x00000001849e77f0 fp 0x000000016bb1edc0 CFRunLoopRunSpecific+0x23c
  pc 0x00000001d1c3a190 fp 0x000000016bb1ee20 GSEventRunModal+0xa8
  pc 0x000000018760e158 fp 0x000000016bb1eea0 <redacted>+0x330
  pc 0x000000018760c388 fp 0x000000016bb1ef30 UIApplicationMain+0x150
  pc 0x0000000187a67eb4 fp 0x000000016bb1ef70 <redacted>+0x265c
  pc 0x00000001051341a4 fp 0x000000016bb1efc0 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ+0x78
  pc 0x000000010513411c fp 0x000000016bb1eff0 $s6Runner11AppDelegateC5$mainyyFZ+0x2c
  pc 0x0000000105134268 fp 0x000000016bb1f010 __debug_main_executable_dylib_entry_point+0x1c
  pc 0x00000001abf93a58 fp 0x000000016bb1f670 <redacted>+0x174c
-- End of DumpStackTrace
=== Crash occurred when compiling unknown function in unoptimized JIT mode in unknown pass
=== Flow Graph not available
```

**Comment by emreerkaslan** [comment]
I am having the same trouble after updating to ios 18.4.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

version=3.5.4 (stable) (Wed Oct 16 16:18:51 2024 +0000) on "ios_arm64"
pid=1200, thread=259, isolate_group=vm-isolate(0x144b48a00), isolate=vm-isolate(0x144c8e800)
os=ios, arch=arm64, comp=no, sim=no
isolate_instructions=1173575e0, vm_instructions=1173575e0
fp=16cec96d0, sp=16cec96b0, pc=117d781a0
  pc 0x0000000117d781a0 fp 0x000000016cec96d0 Dart_DumpNativeStackTrace+0x18
  pc 0x000000011794a0e8 fp 0x000000016cec96f0 dart::Assert::Fail(char const*, ...) const+0x30
  pc 0x0000000117a4560c fp 0x000000016cec9ba0 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x874
  pc 0x0000000117b02268 fp 0x000000016cec9ed0 dart::StubCode::Init()+0x310
  pc 0x0000000117992a78 fp 0x000000016ceca990 dart::Dart::DartInit(Dart_InitializeParams const*)+0x2b6c
  pc 0x0000000117d61900 fp 0x000000016ceca9b0 Dart_Initialize+0x3c
  pc 0x0000000117433160 fp 0x000000016cecaf80 flutter::DartVM::Create(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>, std::_fl::shared_ptr<flutter::IsolateNameServer>)+0x1d60
  pc 0x0000000117900a54 fp 0x000000016cecb6e0 flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners const&, flutter::Settings, std::_fl::function<std::_fl::unique_ptr<flutter::PlatformView, std::_fl::default_delete<flutter::PlatformView>> (flutter::Shell&)> const&, std::_fl::function<std::_fl::unique_ptr<flutter::Rasterizer, std::_fl::default_delete<flutter::Rasterizer>> (flutter::Shell&)> const&, bool)+0x310
  pc 0x000000011735bad0 fp 0x000000016cecc420 -[FlutterEngine createShell:libraryURI:initialRoute:]+0x538
  pc 0x0000000117364a18 fp 0x000000016cecc490 -[FlutterViewController sharedSetupWithProject:initialRoute:]+0x1cc
  pc 0x0000000117364824 fp 0x000000016cecc4c0 -[FlutterViewController awakeFromNib]+0x58
  pc 0x000000019644c450 fp 0x000000016cecc990 <redacted>+0x6dc
  pc 0x00000001964bb55c fp 0x000000016cecca00 <redacted>+0xec
  pc 0x00000001964bb368 fp 0x000000016cecca30 <redacted>+0x50
  pc 0x00000001964bae68 fp 0x000000016cecca90 <redacted>+0x8c
  pc 0x0000000196359180 fp 0x000000016ceccad0 <redacted>+0xa8
  pc 0x0000000196359980 fp 0x000000016ceccce0 <redacted>+0x338
  pc 0x000000019639abd8 fp 0x000000016ceccd20 <redacted>+0x84
  pc 0x00000001962ad1e4 fp 0x000000016ceccd70 _UIScenePerformActionsWithLifecycleActionMask+0x70
  pc 0x00000001962af2c0 fp 0x000000016cecce30 <redacted>+0xfc
  pc 0x00000001962aefb4 fp 0x000000016ceccea0 <redacted>+0xd4
  pc 0x00000001962adcc8 fp 0x000000016ceccfb0 <redacted>+0x260
  pc 0x00000001962ad9e8 fp 0x000000016cecd020 <redacted>+0xf4
  pc 0x00000001962ad594 fp 0x000000016cecd060 <redacted>+0x94
  pc 0x0000000196158c38 fp 0x000000016cecd160 <redacted>+0x2e0
  pc 0x0000000196158260 fp 0x000000016cecd1d0 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion+0xe0
  pc 0x00000001962021d8 fp 0x000000016cecd2d0 <redacted>+0x13c
  pc 0x0000000196201f64 fp 0x000000016cecd420 <redacted>+0x268
  pc 0x00000001962018b0 fp 0x000000016cecd590 <redacted>+0xd0
  pc 0x00000001961ad3ac fp 0x000000016cecd650 <redacted>+0xf4
  pc 0x00000001961aced4 fp 0x000000016cecd730 <redacted>+0x2fc
  pc 0x00000001961acb6c fp 0x000000016cecd7c0 <redacted>+0x120
  pc 0x00000001ae65f30c fp 0x000000016cecd900 <redacted>+0x120
  pc 0x00000001ae64b2d8 fp 0x000000016cecd930 <redacted>+0x44
  pc 0x00000001ae6658b8 fp 0x000000016cecda00 <redacted>+0x1b4
  pc 0x00000001ae664f2c fp 0x000000016cecdac0 <redacted>+0x120
  pc 0x00000001ae664c58 fp 0x000000016cecdb00 <redacted>+0xa8
  pc 0x00000001ae66513c fp 0x000000016cecdc50 <redacted>+0x1d8
  pc 0x0000000106039f80 fp 0x000000016cecdc60 _dispatch_client_callout+0x10
  pc 0x00000001060247fc fp 0x000000016cecdcb0 _dispatch_block_invoke_direct+0x128
  pc 0x00000001ae661658 fp 0x000000016cecdce0 <redacted>+0x34
  pc 0x00000001ae6615d8 fp 0x000000016cecdd70 <redacted>+0xf0
  pc 0x00000001ae6614b0 fp 0x000000016cecdd90 <redacted>+0x1c
  pc 0x0000000193750dc8 fp 0x000000016cecdda0 <redacted>+0x1c
  pc 0x0000000193750d5c fp 0x000000016cecddd0 <redacted>+0xac
  pc 0x000000019374fb44 fp 0x000000016cecde30 <redacted>+0x14c
  pc 0x000000019374ed20 fp 0x000000016ceceba0 <redacted>+0x348
  pc 0x00000001937737f0 fp 0x000000016cecec20 CFRunLoopRunSpecific+0x23c
  pc 0x00000001e09c6190 fp 0x000000016cecec80 GSEventRunModal+0xa8
  pc 0x000000019639a158 fp 0x000000016ceced00 <redacted>+0x330
  pc 0x0000000196398388 fp 0x000000016ceced90 UIApplicationMain+0x150
  pc 0x00000001967f3eb4 fp 0x000000016cecedd0 <redacted>+0x265c
  pc 0x000000010ac30168 fp 0x000000016cecee20 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ+0x78
  pc 0x000000010ac300e0 fp 0x000000016cecee50 $s6Runner11AppDelegateC5$mainyyFZ+0x2c
  pc 0x000000010ac301e4 fp 0x000000016cecee70 __debug_main_executable_dylib_entry_point+0x1c
  pc 0x00000001bad1fa58 fp 0x000000016cecf4d0 <redacted>+0x174c
-- End of DumpStackTrace
=== Crash occurred when compiling unknown function in unoptimized JIT mode in unknown pass
=== Flow Graph not available

**Comment by mraleph** [comment]
It seems that iOS 18.4 Beta has finally closed a long existing loophole with `get-task-allow` allowing to bypass code signing restrictions. The app itself can no longer write into its own executable memory and flip permission RX->RW and back. The is a special path built into kernel to allow `debugserver` do these things (based on private entitlement). Some preliminary analysis of kernel changes available [here](https://gist.github.com/osy/8940e5ae5f24646b808f58d197883ca5).

What this means for us: 

- we need to go back and fallback to interpretation for development builds like we did in the early days of Flutter. That's fairly straightforward - but we would need to tackle performance implications to the extent we _can_. (Another thing is `dart:ffi` - we would need to write generic stubs for ABI marshalling which do not rely on JIT code generation.) cc @a-siva @alexmarkov @mkustermann @dcharkes 
- In the interim we need to warn people that they would not be able to develop on iOS 18.4 (release and profile builds are fine though) - so they should not update their phones if they want to use hot reload and stuff. cc @jmagman @zanderso @jtmcdole @johnmccutchan for visibility.

**Comment by a-siva** [comment]
I have created https://github.com/dart-lang/sdk/issues/60202 on the Dart side for this issue, please discuss all issues related to interpreting over there.

**Comment by israeloriente** [comment]
Same problem

**Comment by knopp** [comment]
Please read the issue description before replying.

**Comment by MrAzimzadeh** [comment]
Thank you for your response. I have read the previous comments and the issue description, but I still couldn’t find a solution. If I missed any details or if you have any other suggestions, I would appreciate your help. 😊

**Comment by knopp** [comment]
The issue description literally says that until there is a hotfix available, the only solution is to not upgrade, run release mode or use simulator. There is no other solution right now.

**Comment by MrAzimzadeh** [comment]
Thank you for the clarification! I understand now. I will use the simulator or release mode for now and wait for a hotfix. I appreciate your help! 😊

**Comment by gnprice** [comment]
@mraleph or others: Might there be a possibility of going through LLDB to make the same writes that the app itself currently makes? So instead of the Flutter tool telling the Dart VM to edit its executable memory using the now-closed `get-task-allow` loophole, the Flutter tool would tell LLDB to tell `debugserver` to make the same edits.

If that works, it might be quite stable in continuing to work: unlike the `get-task-allow` loophole, it's not something that a sideloaded app could use to get a JIT, and so Apple wouldn't necessarily have any motivation to break it.

(But I'm certainly no expert on this — maybe LLDB doesn't offer the operations that are needed, or maybe it'd be difficult to coordinate all the other steps involved in hot reload with making those writes via LLDB.)

**Comment by jkcoxson** [comment]
Just an FYI for everyone here, dev beta 2 has undone these changes.

**Comment by SternXD** [comment]
> Just an FYI for everyone here, dev beta 2 has undone these changes.

Yup I also just tested on my own and found this out too

**Comment by noone4224** [comment]
Thanks @jkcoxson, I was starting to believe it was a new feature I added yesterday but my phone updated to beta 1 in the night so that was the problem haha

**Comment by MrAzimzadeh** [comment]
@jkcoxson 
Thanks for the good news

**Comment by Vofchuk** [comment]
Hello, any update? how do Im unable to run my app. this is critical

**Comment by MrAzimzadeh** [comment]
@Vofchuk 
Update ios beta version

**Comment by vadim-a-yegorov** [comment]
> Just an FYI for everyone here, dev beta 2 has undone these changes.

So we still got JIT in iOS 18.4+?

**Comment by JJTech0130** [comment]
For the record: Duy Tran is @khanhduytran0

Thanks,
James Gill

**Comment by vadim-a-yegorov** [comment]
> For the record: Duy Tran is [@khanhduytran0](https://github.com/khanhduytran0)
> 
> Thanks, James Gill

Sorry, James! I assume he’s been referencing your code, or is he the author?

**Comment by vadim-a-yegorov** [comment]
Did anyone check 18.4RC?

**Comment by loic-sharma** [comment]
@jmagman Can we close this issue now that Flutter hot reload is confirmed to work on iOS 18.4?

**Comment by jmagman** [comment]
Reopening this, `does_rx_rw_rx_flip_work` is false on iOS 26 beta 1.  https://github.com/flutter/flutter/issues/170312
https://dart-review.googlesource.com/c/sdk/+/412281

```
../../../flutter/third_party/dart/runtime/vm/virtual_memory_posix.cc: 254: error: Unable to flip between RX and RW memory protection on pages
version=3.9.0-211.0.dev (dev) (Fri Jun 6 17:03:13 2025 -0700) on "ios_arm64"
pid=698, thread=259, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
os=ios, arch=arm64, comp=no, sim=no
isolate_instructions=0, vm_instructions=0
fp=16daa2370, sp=16daa2350, pc=10609ce88
  pc 0x000000010609ce88 fp 0x000000016daa2370 Dart_DumpNativeStackTrace+0x18
  pc 0x0000000105c373cc fp 0x000000016daa2390 dart::Assert::Fail(char const*, ...) const+0x30
  pc 0x0000000105c86980 fp 0x000000016daa2e50 dart::Dart::DartInit(Dart_InitializeParams const*)+0x5b24
  pc 0x000000010607f7d8 fp 0x000000016daa32d0 Dart_Initialize+0x60
  pc 0x0000000105bfdb60 fp 0x000000016daa3880 flutter::DartVM::Create(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>, std::_fl::shared_ptr<flutter::IsolateNameServer>)+0x1b38
  pc 0x0000000105b5bd20 fp 0x000000016daa3fe0 flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners const&, flutter::Settings, std::_fl::function<std::_fl::unique_ptr<flutter::PlatformView, std::_fl::default_delete<flutter::PlatformView>> (flutter::Shell&)> const&, std::_fl::function<std::_fl::unique_ptr<flutter::Rasterizer, std::_fl::default_delete<flutter::Rasterizer>> (flutter::Shell&)> const&, bool)+0x2fc
  pc 0x0000000105755260 fp 0x000000016daa4d10 -[FlutterEngine createShell:libraryURI:initialRoute:]+0x9bc
  pc 0x00000001057871fc fp 0x000000016daa4d90 -[FlutterViewController sharedSetupWithProject:initialRoute:]+0x274
  pc 0x0000000105786f60 fp 0x000000016daa4dc0 -[FlutterViewController awakeFromNib]+0x6c
  pc 0x0000000194a156b4 fp 0x000000016daa5290 <redacted>+0x6dc
  pc 0x0000000194ff7144 fp 0x000000016daa5300 <redacted>+0xec
  pc 0x0000000194ff701c fp 0x000000016daa5330 <redacted>+0x50
  pc 0x00000001950e7fe8 fp 0x000000016daa5390 <redacted>+0x50
  pc 0x0000000193bf6e6c fp 0x000000016daa53d0 <redacted>+0x6c
  pc 0x00000001942a2dfc fp 0x000000016daa55e0 <redacted>+0x37c
  pc 0x0000000194e2b91c fp 0x000000016daa56f0 <redacted>+0x348
  pc 0x0000000194e2bdb8 fp 0x000000016daa57b0 <redacted>+0x134
  pc 0x00000001948f5eb0 fp 0x000000016daa5840 <redacted>+0x120
  pc 0x00000001ad6c0d5c fp 0x000000016daa59f0 <redacted>+0x16c
  pc 0x00000001ad6c1214 fp 0x000000016daa5a30 <redacted>+0x80
  pc 0x00000001ad6c0b74 fp 0x000000016daa5b00 <redacted>+0x1b4
  pc 0x00000001ad72f414 fp 0x000000016daa5bc0 <redacted>+0x120
  pc 0x00000001ad6cee08 fp 0x000000016daa5c00 <redacted>+0xa8
  pc 0x00000001ad6ebd34 fp 0x000000016daa5d50 <redacted>+0x1e0
  pc 0x00000001ad6ed698 fp 0x000000016daa5de0 <redacted>+0x10c
  pc 0x00000001ad6cee08 fp 0x000000016daa5e20 <redacted>+0xa8
  pc 0x0000000102f5a2b0 fp 0x000000016daa5e30 _dispatch_client_callout+0x10
  pc 0x0000000102f44978 fp 0x000000016daa5e80 _dispatch_block_invoke_direct+0x128
  pc 0x00000001ad7b8514 fp 0x000000016daa5eb0 <redacted>+0x34
  pc 0x00000001ad7b74d4 fp 0x000000016daa5f30 <redacted>+0xe0
  pc 0x0000000190eae960 fp 0x000000016daa5f40 <redacted>+0x1c
  pc 0x0000000190eae778 fp 0x000000016daa5f70 <redacted>+0xac
  pc 0x0000000190eae638 fp 0x000000016daa5fd0 <redacted>+0x14c
  pc 0x0000000190eaef54 fp 0x000000016daa6d40 <redacted>+0x348
  pc 0x0000000190fa8234 fp 0x000000016daa6dd0 <redacted>+0x234
  pc 0x00000001e1f16424 fp 0x000000016daa6e20 GSEventRunModal+0x78
  pc 0x0000000193bb89a0 fp 0x000000016daa6ea0 <redacted>+0x318
  pc 0x0000000193ba6358 fp 0x000000016daa6f30 UIApplicationMain+0x150
  pc 0x0000000193bf53f4 fp 0x000000016daa6f70 <redacted>+0x174
  pc 0x00000001025a8584 fp 0x000000016daa6fc0 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ+0x80
  pc 0x00000001025a84f4 fp 0x000000016daa6ff0 $s6Runner11AppDelegateC5$mainyyFZ+0x2c
  pc 0x00000001025a8600 fp 0x000000016daa7010 __debug_main_executable_dylib_entry_point+0x1c
  pc 0x000000018e14ba5c fp 0x000000016daa7680 <redacted>+0x182c
-- End of DumpStackTrace
```

**Comment by techouse** [comment]
As mentioned in the Dart issue https://github.com/dart-lang/sdk/issues/60202, [Apple confirmed that this was planned](https://github.com/dart-lang/sdk/issues/60202#issuecomment-2867319559).

**Comment by golh30** [comment]
![Image](https://github.com/user-attachments/assets/434b047a-4bc7-418c-902c-c79fc14b53cd)

Ios 26 build failure

**Comment by zanderso** [comment]
Hi folks, in alignment with our issue tracker policies, please do not comment on this issue with "me too" type comments. Thanks!

**Comment by devberkay** [comment]
Profile mode succeeds to run but on the first hot restart trial, it crashes. (iOS 26, Flutter V3.32.2, macOS V15.5)

**Comment by mraleph** [comment]
Can somebody test with the latest master? We have placed a temporary workaround while a long term solution is being developed.

**Comment by leonalonso** [comment]
@mraleph I tried the last master but nothing, the application does not start, it remains in a loop on Installing and launching... and it gives an error on Xcode

<img width="1837" alt="Image" src="https://github.com/user-attachments/assets/4fd3135b-60f4-413c-bae3-e99f2e9935bd" />
<img width="1857" alt="Image" src="https://github.com/user-attachments/assets/33179077-bf6c-4985-9fb7-1da3c32a8aa6" />

**Comment by jplekkerkerker** [comment]
On `Flutter (Channel master, 3.33.0-1.0.pre.518, on macOS 15.5 24F74 darwin-arm64, locale en-NL)` I'm getting a EXC_BAD_ACCESS

<img width="1174" alt="Image" src="https://github.com/user-attachments/assets/89f451b3-6911-4560-935d-032f12d75444" />

**Comment by mraleph** [comment]
@leonalonso @jplekkerkerker thanks. well, that's unfortunate. So it seems the workaround does not work on newer iOS devices. I have previously tested on an older generation iPhone - where it works. I will need to get access to a newer generation device then.

**Comment by mraleph** [comment]
@leonalonso @jplekkerkerker could you try master again? I think it _should_ work now. I have tested on iPhone 16e + iOS 26 (make sure to run `flutter clean` before running - there seems to be some lingering issue with ephemeral LLDB init file)

**Comment by jplekkerkerker** [comment]
@mraleph Tested it with `[✓] Flutter (Channel master, 3.33.0-1.0.pre.584, on macOS 15.5 24F74 darwin-arm64, locale en-NL)`on an iPhone 16 Pro Max with iOS 26(`23A5260u`) the debug mode works.

**Comment by ravirasadiya** [comment]
Tested and working initially application loads, but issue reappears after a few minutes of activity. @mraleph 

[✓] Flutter (Channel master, 3.33.0-1.0.pre.585, on macOS 26.0 25A5279m darwin-arm64, locale en-IN)

**Comment by mraleph** [comment]
@ravirasadiya could you add some information from the moment of the crash? e.g. what were you doing, how the crash looks (e.g. type `bt` into lldb console after the crash and include the output)

**Comment by leonalonso** [comment]
@mraleph I confirm that the application now starts correctly. However, after launching, the communication with the device is interrupted — this can happen after just one second or even after a minute. 

<img width="1840" alt="Image" src="https://github.com/user-attachments/assets/38f9905b-b6de-4a30-afdd-fc49c41f4084" />
<img width="2240" alt="Image" src="https://github.com/user-attachments/assets/01788ca8-926c-4e8b-abea-3ee2faa507ee" />

**Comment by mraleph** [comment]
@leonalonso thanks for the stack trace, based on it I have found one place which I have overlooked when implementing dual mapping. I think that's where it crashes. I will make a fix for that!

**Comment by ravirasadiya** [comment]
Yes, I have the same console output as @leonalonso . Let me know if you need any additional information to help with further debugging! @mraleph

**Comment by mraleph** [comment]
Thanks @leonalonso @ravirasadiya. I have managed to reproduce it and I have made a fix [here](https://dart-review.googlesource.com/c/sdk/+/435860). I will ping you again once we it lands and rolls into master.

**Comment by mraleph** [comment]
> Thanks [@leonalonso](https://github.com/leonalonso) [@ravirasadiya](https://github.com/ravirasadiya). I have managed to reproduce it and I have made a fix [here](https://dart-review.googlesource.com/c/sdk/+/435860). I will ping you again once we it lands and rolls into master.

The fix has rolled into Flutter master. Everybody is welcome to try again.

**Comment by leonalonso** [comment]
@mraleph Awesome, it seems to be working! The connection is stable, and the application starts up without any more errors. Thank you so much!  🎉

**Comment by ManasMalla** [comment]
@mraleph The fix works on the master. But we have a quick issue here.

App is being debugged, do not track this hang
Hang detected: 12.59s (debugger attached, not reporting)

App gets too laggy actually we have a 10-12s gap between every render, or a new page route explored.

**Comment by mraleph** [comment]
@ManasMalla do you continuously experience 10s gap between renders? does it go away after some time e.g. you navigate to some route, there is a stall then you navigate to the same route - is there a stall again? How is your device connected (e.g. USB or WiFi?).

There is a possibility that this is related to necessity to roundtrip to the debugger in certain situations - which is considerably slower when phone is connected over WiFi, but I would not have expected it to happen repeatedly.

**Comment by LouisRaverdy** [comment]
I experienced the same issue, 
Yes, I see that ~10 s gap on every render attempt.
No, it doesn’t clear up after the first stall—navigating back to the same route immediately reproduces the delay.
I’ve tested both USB and Wi-Fi connections.
I’m using the standard VS Code debugger.

**Comment by mraleph** [comment]
@LouisRaverdy does it reproduce if you run outside of VSCode? (e.g. using `flutter run` from CLI?). Does it reproduce on some smaller apps?

**Comment by mraleph** [comment]
We still don't have enough data to try and reproduce long (10s) stalls. So if you are experiencing these could you try to reduce them to some code you can share? Flutter stable branch cut is coming and it would be great if we could repro and address these issues before we hit the cut.

**Comment by pedroduarte-dev** [comment]
Is this fix already at this point ?

**Comment by JinUltimate1995** [comment]
Hello. Is this fixed yet? Shall i upgrade to MacOS 26 and iOS 26 beta?

**Comment by mraleph** [comment]
To the best of my knowledge you can use Flutter master with iOS 26 without any issues. 

Some users reported UI stalls, which we are unable to reproduce.

**Comment by LouisRaverdy** [comment]
> [@LouisRaverdy](https://github.com/LouisRaverdy) does it reproduce if you run outside of VSCode? (e.g. using `flutter run` from CLI?). Does it reproduce on some smaller apps?

Hi, sorry for late reply, same issue outside VSCode with `flutter run` outside of VSCode, and it even happens on a fresh Flutter blank project. The app takes a very long time to launch and to perform hot reload, load anything etc...
My question now is: where is this slowdown coming from, and how can I debug it?

**Comment by sahilasopa** [comment]
@mraleph I tried to run the app on iOS 26 using flutter master, same issue

**Comment by LouisRaverdy** [comment]
@mraleph any update on this issue ?

**Comment by mraleph** [comment]
You can try the following: after you have tried running the application once, stop it and edit `./ios/Flutter/ephemeral/flutter_lldb_helper.py` replacing its contents with https://gist.github.com/mraleph/54be87e550f77aab1638163469ac852b. Then run the application again. In XCode debugger window you should see output like this:

```
handle_new_rx_page took 60.154 ms
Dart execution mode: JIT
handle_new_rx_page took 1098.008 ms
handle_new_rx_page took 524.566 ms
handle_new_rx_page took 519.135 ms
```

Check if some of printed durations are awfully long. 

Also you should at some point stop seeing new `handle_new_rx_page` lines. If you continously see new - that would be concerning.

**Comment by LouisRaverdy** [comment]
@mraleph I got some news ! Tried my app with the edited script and here is the result : 
iOS 18.5 (Simulator) : 
```
-- LLDB integration loaded --
`UIScene` lifecycle will soon be required. Failure to adopt will result in an assert in the future.
FlutterView implements focusItemsInRect: - caching for linear focus movement is limited as long as this view is on screen.
handle_new_rx_page took 23.35 ms
Dart execution mode: JIT
handle_new_rx_page took 280.918 ms
handle_new_rx_page took 264.034 ms
flutter: The Dart VM service is listening on http://0.0.0.0:62412/UrW0bHsJStE=/
handle_new_rx_page took 288.989 ms
handle_new_rx_page took 263.133 ms
handle_new_rx_page took 255.669 ms
handle_new_rx_page took 301.926 ms
handle_new_rx_page took 244.897 ms
handle_new_rx_page took 266.992 ms
handle_new_rx_page took 231.349 ms
handle_new_rx_page took 246.681 ms
handle_new_rx_page took 229.98 ms
handle_new_rx_page took 267.712 ms
handle_new_rx_page took 260.519 ms
handle_new_rx_page took 273.669 ms
handle_new_rx_page took 267.356 ms
handle_new_rx_page took 270.306 ms
handle_new_rx_page took 261.604 ms
handle_new_rx_page took 269.562 ms
```

iOS 26 Beta 4 (Real Device) : 
```
-- LLDB integration loaded --
`UIScene` lifecycle will soon be required. Failure to adopt will result in an assert in the future.
FlutterView implements focusItemsInRect: - caching for linear focus movement is limited as long as this view is on screen.
handle_new_rx_page took 45.733 ms
Dart execution mode: JIT
handle_new_rx_page took 300.332 ms
handle_new_rx_page took 289.065 ms
flutter: The Dart VM service is listening on http://127.0.0.1:49551/9OS9uMpYz6M=/
handle_new_rx_page took 286.404 ms
handle_new_rx_page took 284.027 ms
handle_new_rx_page took 259.327 ms
handle_new_rx_page took 915.003 ms
handle_new_rx_page took 260.523 ms
handle_new_rx_page took 258.734 ms
handle_new_rx_page took 272.598 ms
handle_new_rx_page took 250.249 ms
handle_new_rx_page took 257.993 ms
handle_new_rx_page took 268.505 ms
handle_new_rx_page took 267.425 ms
handle_new_rx_page took 275.579 ms
handle_new_rx_page took 260.969 ms
handle_new_rx_page took 263.839 ms
```

Seems the problem doesn't come from here. Did you have any other ideas ?

**Comment by mraleph** [comment]
@LouisRaverdy well, that's both good and bad. Good because the obvious culprit does not seem to be the cause of your issue, bad - because I am not sure where else to look. Could you try doing `flutter run -v --debug`, do a couple of hot reloads and see if there is anything obviously slow there? e.g. DevFS sync. 

Does your app have large native dependencies? (e.g. Firebase?)

**Comment by LouisRaverdy** [comment]
I'll try this evening or tomorrow with the basic flutter project cause my app have a lot of dependencies. Thanks for your help and I'll keep you in touch as soon as I can.

**Comment by LouisRaverdy** [comment]
@mraleph Here is the debug on my iPhone 16 Pro (iOS 26 beta 5) with the example flutter app : 
```
[   +3 ms] Checking for authentication code for com.monsite.demoApp._dartVmService._tcp.local
[   +3 ms] Installing and launching... (completed in 232.8s)
[  +10 ms] Caching compiled dill
[  +85 ms] Connecting to service protocol: http://172.20.10.1:49524/r8kDq061Go4=/
[+7534 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://172.20.10.1:49524/r8kDq061Go4=/.
[+4383 ms] Successfully connected to service protocol: http://172.20.10.1:49524/r8kDq061Go4=/
[  +30 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/9618B618-8B81-4871-B417-CD94F24B4950/tmp/demo_appnqinYc/demo_app/)
[   +3 ms] Updating assets
[  +95 ms] Syncing files to device Louis’s iPhone (wireless)...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:demo_app/main.dart 5c78ec8c-29b8-4f60-8e10-006193c682a3
[        ] <- 5c78ec8c-29b8-4f60-8e10-006193c682a3
[        ] Bundle processing done.
[  +42 ms] Updating files.
[        ] Pending asset builds completed. Writing dirty entries.
[        ] DevFS: Sync finished
[        ] Syncing files to device Louis’s iPhone (wireless)... (completed in 44ms)
[        ] Synced 0.0MB.
[        ] <- accept
[+1253 ms] Connected to _flutterView/0x156245420.
[   +4 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on Louis’s iPhone (wireless) is available at: http://127.0.0.1:49793/2Hc0bEgMjzU=/
[  +10 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 26.0
[        ] executing: sw_vers -buildVersion
[  +10 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 25A5316i
[        ] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] arm64
[+8191 ms] The Flutter DevTools debugger and profiler on Louis’s iPhone (wireless) is available at:
                    http://127.0.0.1:9102?uri=http://127.0.0.1:49793/2Hc0bEgMjzU=/
[+20302 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: gen_localizations
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[  +16 ms] Scanned through 660 files in 7ms
[        ] Syncing files to device Louis’s iPhone (wireless)...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:demo_app/main.dart 7ee6f234-6731-438c-8da3-fcaaed5607fb
[        ] <- 7ee6f234-6731-438c-8da3-fcaaed5607fb
[        ] Bundle processing done.
[   +5 ms] Updating files.
[        ] Pending asset builds completed. Writing dirty entries.
[  +61 ms] DevFS: Sync finished
[        ] Syncing files to device Louis’s iPhone (wireless)... (completed in 68ms)
[        ] Synced 0.0MB.
[   +7 ms] Reassembling application
[+1892 ms] Hot reload performed in 1,973ms.
[   +1 ms] Performing hot reload... (completed in 1,985ms)
```

There is a `[+20302 ms] Skipping target: gen_dart_plugin_registrant` that is very suspicious. The app is very slow to start (freezing ~20s on launch screen, and freeze again ~40-60s on app at launch).

**Comment by mraleph** [comment]
@LouisRaverdy
 
I think at this point we should probably file a separate issue - because I don't think iOS 26 JIT related workarounds are related to the performance issue we are seeing here, this must be something else.

When you say "example flutter app" do you mean just an empty one created with `flutter create`?

Do you see similar slowness if you connect your physical phone using USB connection?

**Comment by walt-etermax** [comment]
Hello. I just wanted to ask if this fix has been released in any Flutter version or if it’s only on master. Thanks.

**Comment by Guziq** [comment]
> Hello. I just wanted to ask if this fix has been released in any Flutter version or if it’s only on master. Thanks.

Unfortunately, I’ve tested both the beta and master channels, and the issue still persists.

**Comment by sudo-ping-pong** [comment]
I can confirm that my flutter app runs perfectly fine in debug mode on the latest master build. No stutters. No hangs . Currently on iOS 26 Beta 6.

[✓] Flutter (Channel master, 3.33.0-1.0.pre-1375, on macOS 26.0 25A5338b
    darwin-arm64, locale en-US) [4.9s]
    • Flutter version 3.33.0-1.0.pre-1375 on channel master at
      /Users/soocher/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f93f3053c8 (30 hours ago), 2025-08-12 22:04:23 -0400
    • Engine revision f93f3053c8
    • Dart version 3.10.0 (build 3.10.0-88.0.dev)
    • DevTools version 2.49.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop,
      enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [5.5s]
    • Android SDK at /Users/soocher/Library/Android/sdk
    • Emulator version 35.6.11.0 (build_id 13610412) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [6.3s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [15ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [11.2s]
    • Syed’s iPhone (mobile) • 00008140-0012254A210B001C • ios            • iOS
      26.0 23A5318c
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 26.0 25A5338b darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 139.0.7258.68

[✓] Network resources [1,205ms]
    • All expected network resources are available.

• No issues found!
