### ISSUE TITLE
Unable to Upgrade intl Package Due to Flutter Localization Dependency on intl 0.19.0

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [flutter/flutter#164688]
### Steps to reproduce

We are unable to upgrade the intl package in our Flutter project because Flutter’s localization depends on intl 0.19.0. This restriction prevents us from using newer versions of intl, which may include important bug fixes and enhancements.

### Expected results

Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because klp depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because klp depends on intl ^0.20.2, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.19.0
Failed to update packages.

### Actual results

Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because klp depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because klp depends on intl ^0.20.2, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.19.0
Failed to update packages.

### Code sample

-

### Screenshots or Video

-

### Logs

-

### Flutter Doctor output

-

**Comment by darshankawar** [comment]
@emanuelzallikodelabs 
This seems to have been resolved already as part of https://github.com/flutter/flutter/issues/162525

**Comment by emanuelzallikodelabs** [comment]
I still get the same error when I try to update the intl library from 0.19.0 to 0.20.2

This is the error:

Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because klp depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because klp depends on intl ^0.20.2, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.19.0
Failed to update packages.

-----------------------------------------------------------------------------------------------------------

This is the flutter version:
Flutter 3.29.2 • channel stable
Tools • Dart 3.7.2 • DevTools 2.42.3

**Comment by darshankawar** [comment]
> Because klp depends

@emanuelzallikodelabs this is third party package which probably needs to be updated to use latest intl package, so the changes need to be done in that package itself to be compatible with intl. The tool correctly identifies it and shows what needs to be done.
Closing, as this isn't flutter tool issue.
