### ISSUE TITLE
Firebase plugins: type 'Future<dynamic>' is not a subtype of type 'Future<Null>

### ISSUE THREAD

**Issue by acrozes** [flutter/flutter#16463]
## Steps to Reproduce

After the Flutter beta 2 (and Dart 2)  this type of error appear with firebase plugins ...
This case is on my training app "Friendly Chat" 

## Logs

```
E/flutter (27762): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27762): type 'Future<dynamic>' is not a subtype of type 'Future<Null>' where
E/flutter (27762):   Future is from dart:async
E/flutter (27762):   Future is from dart:async
E/flutter (27762):   Null is from dart:core
E/flutter (27762): 
E/flutter (27762): #0      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart)
E/flutter (27762): <asynchronous suspension>
E/flutter (27762): #1      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196:28)
E/flutter (27762): #2      _RootZone.run (dart:async/zone.dart:1376:54)
E/flutter (27762): #3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
E/flutter (27762): #4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603:39)
E/flutter (27762): #5      Future._propagateToListeners (dart:async/future_impl.dart:659:37)
E/flutter (27762): #6      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342:9)
E/flutter (27762): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (27762): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): Failed to handle method call
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): java.lang.IllegalStateException: Concurrent operations detected: init, init
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.checkAndSetPendingOperation(GoogleSignInPlugin.java:146)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.init(GoogleSignInPlugin.java:159)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin.onMethodCall(GoogleSignInPlugin.java:75)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at android.os.Looper.loop(Looper.java:130)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/MethodChannel#plugins.flutter.io/google_sign_in(27762): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
W/DynamiteModule(27762): Local module descriptor class for com.google.firebase.auth not found.
W/IInputConnectionWrapper(27762): showStatusIcon on inactive InputConnection
V/ActivityThread(27762): updateVisibility : ActivityRecord{264a1d49 token=android.os.BinderProxy@3df31543 {com.yourcompany.myfriendlychat/com.yourcompany.myfriendlychat.MainActivity}} show : false
Lost connection to device.

```

## Flutter Doctor

C:\flutter\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [version 6.3.9600], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by saifeiLee** [comment]
I also have this problem.Any help please?

**Comment by mtuxo** [comment]
disable dart 2 mode in setting->flutter->Run applications in Dart 2.0 mode.

**Comment by acrozes** [comment]
So Firebase packages are not yet compatible with dart 2 ?
In the firebase_auth changelog, some dart 2 problems have been fixed in version 0.5.2 ...
How to know which package is compatible with dart 2 or not ?

```
0.5.4
Simplified podspec for Cocoapods 1.5.0, avoiding link issues in app archives.
0.5.3
Secure fetchProvidersForEmail (no providers)
0.5.2
Fixed Dart 2 type error in fetchProvidersForEmail.
```

**Comment by kalehv** [comment]
I am not using Firebase but having same problem for Google Sign In package 
https://pub.dartlang.org/packages/google_sign_in#-installing-tab-

**Comment by viju85** [comment]
I am having the same problem as well. Any help?

**Comment by ch-muhammad-adil** [comment]
facing same problem ..

**Comment by ch-muhammad-adil** [comment]
I have managed to fix this issue by disabling dart 2 

Open Preferences/Settings, and select 'Flutter' under 'Languages & Frameworks'
Set the 'Run applications in Dart 2.0:' option to 'Disable Dart 2'

Dart 2 is highly recommended but just because of it is creating issue because of two different modules I had to perform this action. 
https://github.com/flutter/flutter/wiki/Opting-out-of-Dart-2-with-Flutter-beta-2

**Comment by kalehv** [comment]
I managed to get rid of this problem by creating a new project and copying over my actual code files to new project. Obviously means that some configuration needed an upgrade. I haven't gotten time to look what new change actually fixed it but the problem is gone for me now.

**Comment by yagitatsu** [comment]
In my case,  this problem is resolved by editing pubsupec.yaml as follows: 

before: 
> google_sign_in: 0.3.1

after:
> google_sign_in: 3.0.2

**Comment by jldork** [comment]
Updating google_sign_in didn't solve my issue :(.

@acrozes were you able to figure this out? 

my terminal output below
![image](https://user-images.githubusercontent.com/1771806/39263590-a6ea042a-4890-11e8-9280-2931017a83ca.png)

**Comment by jldork** [comment]
@acrozes try ```flutter packages get && flutter packages upgrade  && flutter clean```

This solved my problem. The key here must've been the flutter clean - that would corroborate @kalehv 's fix.

thanks to @slightfoot on gitter!
![image](https://user-images.githubusercontent.com/1771806/39264369-b4c01dd0-4892-11e8-83a9-7cd369d0b35a.png)

**Comment by slightfoot** [comment]
@jldork your welcome 😄

**Comment by alisonchilds** [comment]
^^^ This worked for me too. Thanks everyone!

**Comment by felideon** [comment]
So, to clarify and sum it all up, here's what seems to work:

1. Quit the `flutter run` (terminal) or debug session (IDE).
2. In pubspec.yaml, make sure the google_sign_in dependency constraint is set thusly: `google_sign_in: ^3.0.0`
3. In the terminal, do `flutter packages upgrade && flutter clean`

Now you can re-run the application and try again.

**Comment by allexradu** [comment]
I had the same problem with the fallowing code:

```
Future<Null> fetchProducts() {
    _isLoading = true;
    notifyListeners();
    return http
        .get('https://blabla.firebaseio.com/products.json')
        .then((http.Response response) {
      final List<Product> fetchedProductList = [];
      final Map<String, dynamic> productListData = json.decode(response.body);
      if (productListData == null) {
        _isLoading = false;
        notifyListeners();
        return;
      }
      productListData.forEach((String productId, dynamic productData) {
        final Product product = Product(
            id: productId,
            title: productData['title'],
            description: productData['description'],
            image: productData['image'],
            price: productData['price'],
            userEmail: productData['userEmail'],
            userId: productData['userId']);
        fetchedProductList.add(product);
      });
      _products = fetchedProductList;
      _isLoading = false;
      notifyListeners();
      _selProductId = null;
    }).catchError((error) {
      _isLoading = false;
      notifyListeners();
      return;
    });
  }
```

I've solved the problem by specifying the return type of the .then block:.

` .then<Null>((http.Response response) {
`

**Comment by zoechi** [comment]
@allexradu `<void>` is preferred since Dart 2 over `<Null>` and should work as well.
