### ISSUE TITLE
[Mac-15][iOS Simulator] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.

### ISSUE THREAD

**Issue by alex-medinsh** [flutter/flutter#166333]
### Steps to reproduce

1. `flutter create bug`
2. `flutter run` on an iOS 18.4 Simulator

### Expected results

Does not print an error when the app starts.

### Actual results

Prints error on app start

[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
alex@Alexs-MacBook-Pro test_bug % flutter run
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        10.0s
Xcode build done.                                           28.9s
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
Syncing files to device iPhone 16 Pro...                           361ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 16 Pro is available at: http://127.0.0.1:54413/3lvtheyskW0=/
The Flutter DevTools debugger and profiler on iPhone 16 Pro is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54413/3lvtheyskW0=/
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.4 24E248 darwin-arm64, locale en-GB) [2.3s]
    • Flutter version 3.29.2 on channel stable at /Users/alex/workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [2.3s]
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/alex/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.3) [2.1s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    ! CocoaPods 1.13.0 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [12ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2) [12ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.98.2) [10ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (3 available) [6.4s]
    • iPhone 16 Pro (mobile)          • 523BE6AB-F2BA-4984-ABE2-5C61B84D3556 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-18-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 15.4 24E248 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 15.4 24E248 darwin-arm64
    ! Error: Browsing on the local area network for Alex’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1,901ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshj01** [comment]
Hey @RepliedSage11, Thanks for filing the issue, Do you have any steps to reproduce the isssue?

**Comment by RepliedSage11** [comment]
@maheshj01 I created a fresh iOS 18.4 Simulator and tried running the app. Maybe it needs to be a fresh simulator for it to reproduce?

**Comment by st1llsane** [comment]
same

**Comment by checkmatesuga** [comment]
same here

**Comment by RepliedSage11** [comment]
@zhujiageng @st1llsane @checkmatesuga 
There is no need to leave "same" comments. Just add a 👍 to the OP. There is no need to spam others with notifications that provide no value.

> Do not add "me too" or "same" or "is there an update" comments to issues or PRs
> 
> The Flutter team prioritizes issues in part based on the number of +1 (thumbs up) reactions on the top level comment of the bug. Adding comments like "me too" or "same here" is generally distracting and makes it harder to find other more meaningful content in the bug. If you have no new details to add, consider just thumbs up-ing the issue. If you wish to subscribe to the issue, click the "subscribe" button in the right hand column of the GitHub UI.

**Comment by maheshj01** [comment]
Thanks for the details I was able to reproduce it on stable and the master channel
 
```
Could not load custom device from config index 0: Expected enabled to be a boolean.
Launching lib/main.dart on iPhone 16 Plus in debug mode...
Xcode build done.                                           61.6s
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
Connecting to VM Service at ws://127.0.0.1:55076/RQNmrB5BzC0=/ws
Connected to the VM Service.
```

<details>
<summary>flutter doctor -v</summary>

**master**
```console
[!] Flutter (Channel master, 3.31.0-1.0.pre.345, on macOS 15.4 24E248 darwin-arm64, locale en-US) [4.7s]
    • Flutter version 3.31.0-1.0.pre.345 on channel master at /Users/mahesh/Development/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/mahesh/Development/flutter/bin/flutter, which is not inside your
      current Flutter SDK checkout at /Users/mahesh/Development/flutter_master. Consider adding
      /Users/mahesh/Development/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/mahesh/Development/flutter/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/mahesh/Development/flutter_master. Consider adding
      /Users/mahesh/Development/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ce60b743d (2 days ago), 2025-03-31 23:50:27 +0300
    • Engine revision 9ce60b743d
    • Dart version 3.8.0 (build 3.8.0-245.0.dev)
    • DevTools version 2.45.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.2s]
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,605ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [143ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [142ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1) [141ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.96.2) [20ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available) [6.7s]
    • iPhone 16 Pro (mobile)  • 34497AEA-B6B0-4F79-99A3-6E40007745A3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • iPhone 16 Plus (mobile) • 55311E15-05E9-46F1-BA53-8EDD8B382A85 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 15.4 24E248 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 131.0.6778.265

[✓] Network resources [482ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**stable**
```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.4 24E248 darwin-arm64, locale en-US) [3.8s]
    • Flutter version 3.29.2 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [4.4s]
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [3.7s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [133ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [133ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1) [130ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.96.2) [18ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available) [6.5s]
    • iPhone 16 Pro (mobile)          • 34497AEA-B6B0-4F79-99A3-6E40007745A3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • iPhone 16 Plus (mobile)         • 55311E15-05E9-46F1-BA53-8EDD8B382A85 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.4 24E248
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.4 24E248
      darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.265

[✓] Network resources [640ms]
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by KlausJokisuo** [comment]
Same for iOS 16.2 simulator.

```
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           24.5s
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
Debug service listening on ws://127.0.0.1:51395/sz4y0GUzVR4=/ws
Syncing files to device iPhone 16 Pro...
```


```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.31.0-0.1.pre, on macOS 15.4 24E248 darwin-arm64, locale en-FI)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.5)
[✓] VS Code (version 1.81.0)
⣷^C%                                                                                               ➜  ~ flutter doctor --verbose
[✓] Flutter (Channel beta, 3.31.0-0.1.pre, on macOS 15.4 24E248 darwin-arm64, locale en-FI) [533ms]
    • Flutter version 3.31.0-0.1.pre on channel beta at /Users/max/fvm/versions/beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fce807530a (2 weeks ago), 2025-03-17 16:47:17 +0000
    • Engine revision 50f226569f
    • Dart version 3.8.0 (build 3.8.0-171.0.dev)
    • DevTools version 2.44.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) [1,562ms]
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/max/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [970ms]
    • Xcode at /Applications/Xcode-16.2.0.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [98ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [98ms]
    • Android Studio at /Users/max/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.5) [96ms]
    • IntelliJ at /Users/max/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.26053.17

[✓] VS Code (version 1.81.0) [12ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available) [6.3s]
    • max’s iPhone (wireless) (mobile) • 00008130-00061D022EF8001C            • ios            •
      iOS 18.4 22E240
    • iPhone 16 Pro (mobile)             • 99A29CF2-EE8E-468D-BFEC-B8646A23C3B9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    • macOS (desktop)                    • macos                                • darwin-arm64   •
      macOS 15.4 24E248 darwin-arm64
    • Chrome (web)                       • chrome                               • web-javascript •
      Google Chrome 134.0.6998.89

[✓] Network resources [258ms]
    • All expected network resources are available.

• No issues found!
```

**Comment by RGPaul** [comment]
I have the same Issue. It started to arise since I updated to macOS 15.4.
Another App asked for permissions, but within macOS. The App that is installed in the iOS Simulator is now listed in the network permissions from macos.

**Comment by arlucio** [comment]
Haven't used flutter a while did a new installation and completely stuck on this.

How can I workaround this? Is it of a version of simulator, an IOS version? What can I change so I can make this work?

**Comment by vashworth** [comment]
I haven't investigated yet, but seems like this may be isolated to macOS 15.4.

Until this is fixed, as a workaround you can create a Debug-only Info.plist and add Local Network permissions to it. See instructions here: https://docs.flutter.dev/add-to-app/ios/project-setup#set-local-network-privacy-permissions

**Comment by vashworth** [comment]
Update: This seems to only impact Simulators on macOS 15.4. Also, this does not appear to cause hot reload or the app to stop working. The error message indicates something is wrong with publishing the DartVM as an mDNS service, but most things should still work actually. No workaround is needed. The error can be ignored for now.

**Comment by luckygogreen** [comment]
I have serious OCD, and this error is really affecting my mood.

**Comment by Weny-murat** [comment]
> Update: This seems to only impact Simulators on macOS 15.4. Due to this error, `flutter attach` on iOS simulators will not work. Only workaround is to use a physical device instead of a simulator.
> 
> The error message indicates something is wrong with publishing the DartVM as an mDNS service, but most things should still work actually (unless you're using `flutter attach`). This does cause hot reload or the app to stop working. If you're not doing `flutter attach` on an iOS simulator, you can ignore the error for now.

same behavior physical device (ios 18.4) permission granted that mentioned about local network

**Comment by vashworth** [comment]
Workaround for `flutter attach` workflow:

If you're using `flutter attach` on an iOS simulator, you can copy the Dart VM Service url from Xcode and pass it to `flutter attach --debug-url`. See example below:

![Image](https://github.com/user-attachments/assets/e85395b9-4d10-4e58-b810-d547a03ac5d9)

```
flutter attach --debug-url http://127.0.0.1:58083/_gNGsw7S3rY=/
```

**Comment by vashworth** [comment]
> same behavior physical device (ios 18.4) permission granted that mentioned about local network

@Weny-murat Are you getting an error for a physical device?

**Comment by Mohamed-Abdulla** [comment]
Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Xcode build done.                                           18.4s
2
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.

**Comment by Mohamed-Abdulla** [comment]
> Launching lib/main.dart on iPhone 16 Pro Max in debug mode... Xcode build done. 18.4s 2 [ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
> 
> It's happened i updated xcode to latest and updated my emulator to 18.4,



Fix:

I fixed the issue by allowing http services in my emulator

Step 1: open settings in emulator
Step 2: click developer option and enable "Allow HTTP services" under wallet testing.

**This works for me !**

**Comment by benokan** [comment]
> > Launching lib/main.dart on iPhone 16 Pro Max in debug mode... Xcode build done. 18.4s 2 [ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
> > It's happened i updated xcode to latest and updated my emulator to 18.4,
> 
> Fix:
> 
> I fixed the issue by allowing http services in my emulator
> 
> Step 1: open settings in emulator Step 2: click developer option and enable "Allow HTTP services" under wallet testing.
> 
> **This works for me !**

What is your macos version?

**Comment by behnamsattar** [comment]
> > Launching lib/main.dart on iPhone 16 Pro Max in debug mode... Xcode build done. 18.4s 2 [ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
> > It's happened i updated xcode to latest and updated my emulator to 18.4,
> 
> Fix:
> 
> I fixed the issue by allowing http services in my emulator
> 
> Step 1: open settings in emulator Step 2: click developer option and enable "Allow HTTP services" under wallet testing.
> 
> **This works for me !**

I tried this and although I still see the error message regarding the FlutterDartVMServicePublisher, my issue with connecting to my local backend instance is resolved. For now I can continue with my dev activities. Thanks!

**Comment by Weny-murat** [comment]
> > same behavior physical device (ios 18.4) permission granted that mentioned about local network
> 
> [@Weny-murat](https://github.com/Weny-murat) Are you getting an error for a physical device?

[Mohamed-Abdulla](https://github.com/Mohamed-Abdulla) solution didn't work for me!

Yes and popup has shown and accepted on physical device. App is on the list and allowed on local network permission list 

and finally yes it was fine before the xcode update so there is a high possibility that this is related to this update

**Comment by vashworth** [comment]
> Yes and popup has shown and accepted on physical device. App is on the list and allowed on local network permission list
> 
> and finally yes it was fine before the xcode update so there is a high possibility that this is related to this update

@Weny-murat Can you file a new issue with steps to reproduce your issue? Sounds like it's different than this issue

**Comment by Weny-murat** [comment]
> > Yes and popup has shown and accepted on physical device. App is on the list and allowed on local network permission list
> > and finally yes it was fine before the xcode update so there is a high possibility that this is related to this update
> 
> [@Weny-murat](https://github.com/Weny-murat) Can you file a new issue with steps to reproduce your issue? Sounds like it's different than this issue

Actually getting this error in a big project and preventing login function in app. Investigating atm if I find a clue I will report it.

**Comment by luckygogreen** [comment]
I'm using a brand new MacBook Pro with all the software updated to the latest version. When I run the project, the same error still appears. So it seems likely that this is an issue on Xcode's side. Hopefully, Apple will fix it soon.

**Comment by luckygogreen** [comment]
I think I may have found a possible cause, but I can't confirm it yet because I haven't been able to consistently reproduce the error.

When running my Flutter app on the iOS simulator, a prompt appears asking whether to allow scanning for local devices.

On MacBook 1 (running the latest version of macOS and the iOS simulator), I chose "Allow", and the error disappeared.

On MacBook 2 (also with the latest macOS and simulator), I chose "Don't Allow", and the error occurred.

What confuses me is that regardless of whether you choose "Allow" or "Don't Allow", there should be an option somewhere in Settings to change this permission later. Unfortunately, I went through all the settings on both the MacBook and the simulator—including the Privacy section—but couldn’t find anything related to this permission.

I'm still trying to locate where this setting can be changed. If I find it, I'll share the solution right away.

**Comment by victorfaria** [comment]
It started to happen with me after updating xcode to the latest version and ios to 18.4. I was able to workaround after installing and using the iOS 18.3 version. Even showing the permission denied on terminal, apparently the app is running smoothly now.

**Comment by leandrormartins** [comment]
I've had the same problem since I updated to Xcode 16 (yesterday), and I tested simulators in versions 18, 18.3, and 18.4.

I created a Flutter project from SCRATCH, and it gives me the same error.

The message is from Impeller and FlutterDartVMServicePublisher.

I tried to put the tags in the ifo.plist but I also had no success.

Now I can no longer support my application, and I can't release a new version.

If anyone has a way to get around the problem, I'd appreciate your help.

**Comment by leandrormartins** [comment]
> > I've had the same problem since I updated to Xcode 16 (yesterday), and I tested simulators in versions 18, 18.3, and 18.4.
> > I created a Flutter project from SCRATCH, and it gives me the same error.
> > The message is from Impeller and FlutterDartVMServicePublisher.
> > I tried to put the tags in the ifo.plist but I also had no success.
> > Now I can no longer support my application, and I can't release a new version.
> > If anyone has a way to get around the problem, I'd appreciate your help.
> 
> [@leandrormartins](https://github.com/leandrormartins) This issue should not be preventing you from running your application. If you're unable to run your application, please file a new issue with reproduction steps and information about the error you are receiving.

After the error ([ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] ), the application does not load, the screen remains black.

Even in a new flutter project.

**Comment by vashworth** [comment]
A [fix](https://github.com/flutter/flutter/pull/166782) was made on master that should hide the error for simulators (will still show with verbose engine logs).

Again, if you're getting this error and it's preventing you from developing your app or is happened on a physical device, please file a new issue.

**Comment by rubenbae** [comment]
in your ios/Runner/Info.plist you can add this lines just before </dict> tag
`
<key>NSLocalNetworkUsageDescription</key>
<string>This app runnig in IOS Simulator need networks permitions. RB</string>

<key>NSBonjourServices</key>
<array>
    <string>_dartobservatory._tcp</string>
</array>
`
save the file .plist

after you need close your app and clean your workspace
in your terminal
`
flutter clean
flutter pub get
flutter run
`

**Comment by ksmohamed** [comment]
same here

**Comment by behnamsattar** [comment]
I’m experiencing a similar issue with Flutter where I’m unable to connect to my locally running backend instance on macOS from within the iOS simulator. It’s not just the warning messages.

I’ve come across this [related issue on Expo GitHub](https://github.com/expo/expo/issues/35642), which seems to describe a similar network connectivity problem. The issue appears to have been resolved in [this PR](https://github.com/expo/expo/pull/36060). It might be worth looking into this as it could offer some insight into resolving the problems folks are having, beyond just the warning messages.

**Comment by fatih-yilmaz-mytech** [comment]
I get the same error I am in xcode version 16.3. My macos version is 15.4.1. Google sign in is not working because of this error.

**Comment by davidianstyle** [comment]
Running into the same on my machine when attempting to connect to local Firebase Emulator. Completely prevents me from authenticating in my app and continue development.

MacOS: Sequoia 15.4.1
iOS Simulator: 18.4

![Image](https://github.com/user-attachments/assets/296aaf65-9525-487c-ad5c-3df0627a98d1)

I see no option in my System Settings > Privacy & Security > Local Network to enable access for my Flutter app.

![Image](https://github.com/user-attachments/assets/27aa3df3-5b97-4345-99be-15f8d8d79b08)

I tried toggling off then on the following with no luck:
- Xcode
- iTerm
- IPNExtension
- Visual Studio Code

**Comment by justin-dele0n** [comment]
I've been running into the same issue as @davidianstyle. At this point, what's worked for me is resorting to an older version of iOS for the simulator. I tested my auth, and it worked properly when on iOS 18.2 for the simulator. 

Note that although the authentication process worked on my end, after the launch of the application (flutter run -> and selecting device), it still gives the error that FlutterDartVMServicePublisher doesn't have the correct permissions, similar to when the auth had issues on iOS 18.4.

**Comment by otabekinha** [comment]
I'm getting similar issues after updating xcode and still could not find any solution for this. This problem is also stopping me to google sign in. If you guys have any solution, let us know it would help a lot

**Comment by zuno90** [comment]
> I'm getting similar issues after updating xcode and still could not find any solution for this. This problem is also stopping me to google sign in. If you guys have any solution, let us know it would help a lot

same here, can not use GGsignin by using firebase. Need a help!

**Comment by anshyyy** [comment]
` <key>NSLocalNetworkUsageDescription</key>
    <string>This app needs access to network service discovery to debug the app</string>
    <key>NSBonjourServices</key>
    <array>
        <string>_dartobservatory._tcp</string>
    </array>`

add this into the info.plist it has worked for me

**Comment by zuno90** [comment]
> ` <key>NSLocalNetworkUsageDescription</key> <string>This app needs access to network service discovery to debug the app</string> <key>NSBonjourServices</key> <array> <string>_dartobservatory._tcp</string> </array>`
> 
> add this into the info.plist it has worked for me

bro,  it was not worked on 18.4!

**Comment by anshyyy** [comment]
@zuno90 i have tried it on 18.1, and it worked there

**Comment by pweibert** [comment]
> [@zuno90](https://github.com/zuno90) i have tried it on 18.1, and it worked there
Just tried it 

Didn't work for me on Iphone 16 Pro Simulator, (ios 18.0) build XCode 16.0,  also tried `flutter clean` and `flutter run` again. No luck

**Comment by zuno90** [comment]
> I'm getting similar issues after updating xcode and still could not find any solution for this. This problem is also stopping me to google sign in. If you guys have any solution, let us know it would help a lot

I move to Android emulator to dev with Social login instead. I think that bug belongs to Flutter, not IOS although i changed other IOS devices.

**Comment by Developed-by-Mo** [comment]
I have the same issue, testing on a real device instead of a simulator seems to work fine though so I'm guessing it's just a simulator issue perhaps.

**Comment by vashworth** [comment]
Again, this is a bug with macOS 15.4+ and the simulator. It is not a bug with Flutter. There is no known workaround other than to use a physical device. Apple has acknowledged it as a bug: https://developer.apple.com/forums/thread/780655?answerId=835257022#835257022. As the [forum](https://developer.apple.com/forums/thread/780655?answerId=835257022#835257022) mentions, you can create a Feedback Assistant bug report to help get this issue fixed.

**Comment by rlebuy** [comment]
I have the same issue , when i got my new M4 , the 129 Error, i try to create an emulator with with ios 17.0 and the same issue , the behavior is when the emulator opens , it try to find for a privilege , and ends on the setting screen , is not a ios issue is something that flutter has to update

**Comment by IbrahimHasan93** [comment]
for me i added app_tracking_transparency package in my flutter projet, but i forget to add NSUserTrackingUsageDescription permission inside the info.plist, after i added it was solved

**Comment by Louayelaroui** [comment]
im trying to use flutter-map with strit map and location .. 
but he still show me this errors ?
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.

even that i give it all permission more than  he need  :
   <key>NSLocalNetworkUsageDescription</key>
    <string>Cette app a besoin d'accéder au réseau local pour les fonctionnalités de débogage et de communication locale.</string>
	<key>NSBonjourServices</key>
    <array>
       <string>_dartobservatory._tcp</string>
    </array>
    <key>NSLocationWhenInUseUsageDescription</key>
	<key>NSLocationAlwaysUsageDescription</key>
	<key>NSUserTrackingUsageDescription</key>
    <string>This app requires location access to provide mapping functionality.</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>This app needs background location access for navigation.</string>
    <key>UIBackgroundModes</key>
    <array>
        <string>location</string>
    </array>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>

did samone know how to solve this problem and  know ho to solve it please ?
when i open the map he dont show the map because i dont have this permission :")

**Comment by brunos0** [comment]
Hello guys, just to share the information...

Until Apple fix the issue, my friend found a way to attach on iOS:

open the terminal on Vscode or terminal in flutter project folder and put this command:

flutter attach --target lib/main.dart --app-id br.com.mark.app --device-vmservice-port 8888 --host-vmservice-port 8888 -v --debug-url=http://127.0.0.1:50721/cNJTSof37nQ=/ --device-id D100D12A-9843-48B5-B1A7-93EB82DF4A0D

Note that you must change the app-id to that your app use. 

You will need change the debug-url. This information appears on Xcode when you launch app. Just go to the debug console and type flutter and you will get something like this:  flutter: The Dart VM service is listening on http://127.0.0.1:50721/cNJTSof37nQ=/

And finally you will need inform your device id. You can get this information typing flutter device on terminal .

You can omit the "-v" to short logs

type r in terminal for hot reload, R for hot restart and Q to quit the attach.

Hope this information helps somebody.

**Comment by hanzayarsoe** [comment]
I have the same issue when I run my flutter app it show
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(129)] Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
So I add to the info.plist file
<key>NSLocalNetworkUsageDescription</key>
<string>This app uses the local network for debugging and development tools.</string>
It still don't work. Does anyone know how to fix this problem?

**Comment by chunkhai96** [comment]
Same here, after I updated to Sequoia 15.5

**Comment by chunkhai96** [comment]
Same here, after I updated to Sequoia 15.5. But I managed to fix it, when I rerun
```sh
flutter attach
```

**Comment by janlektonen** [comment]
> Try using iOS Simulator **18.2**, instead of the latest 18.4. It worked for me, even though the error still shows. Im using macOS 15.5.

I have just tried that on Mac OS 15.5 with iphone 13 simulator and iOS 18.2. Still no network connection and cannot test any apps. I've also tried iOS 18.4 on iPhone 16 plus emulator. Same problem. Only physical iPhone device is working with Flutter version 3.32.0

**Comment by firstlogo** [comment]
same here

**Comment by akshoyduya** [comment]
I am also facing the same issue. please help. is it going to affect the production build?

**Comment by madushans** [comment]
No AFAIK release builds are fine. So are deploys to physical devices. It’s just that flutter debugger can’t connect to the simulator. 

Android emulator is unaffected, so I switched to using that until this is sorted.

**Comment by YuyeQingshan** [comment]
ENV: macOS 15.5 + Xcode16.2, iOS 18.2 SDK, iOS 18.3 simulator; Flutter SDK 3.13.9

Flutter Module, can not use `flutter attach` to the simulator.

**Comment by madushans** [comment]
## I can confirm this is fixed on macOS 15.5 with iOS 18.5 SDK. 🎉 

Mine got (violently) auto-updated. (that was fun), but I think the steps are:

- update to macOS 15.5 (not sure if you need this, but it's my current version)
- quit any Simulators
- Update your xcode to 16.4
- open xcode, go to XCode Menu > Settings
- Select Components
- under platform support, click Get on 'iOS 18.5' (downloads 8.8 gigs)
- if you had vscode open, might need to restart that, plus restart XCode for good measure 
- open Simulator
- open vscode (or whatever else you use) and make sure your iOS simulator is selected 
- run your app

--- 

I'm gonna disable all kinds of MacOS updates execept for Security Responses and system files option going forward so I can prepare myself mentally before I update any of these.

**Comment by alangautham** [comment]
Still getting the same error. Updated Xcode and now running 18.5 simulator on 15.5 macOS.

**Comment by Klim-Karma** [comment]
> Still getting the same error. Updated Xcode and now running 18.5 simulator on 15.5 macOS.

Hi @alangautham, are you able to build and debug app? Am I right that issue is in console log only?
Asking just to understand if I can update the environment and still be able to debug app on my laptop.

**Comment by YuyeQingshan** [comment]
THX @madushans 

**[macOS 15.5 + Xcode 16.4 + iOS 18.5 Simulator + Flutter SDK 3.13.9]** works for me in Flutter Module. 

![Image](https://github.com/user-attachments/assets/dba94c11-531f-4029-ad38-f817481169cd)

And in the project I also set this in info.plist

![Image](https://github.com/user-attachments/assets/5b67b12e-266e-482a-b380-d5c11bbebba6)

After I upgraded Xcode, my first attempt to attach the app failed. But after a system reboot and retest, it worked. However, subsequent attempts weren't always successful, and I'll keep an eye on the potential reasons for failure.

**Comment by JokerXUE18** [comment]
macos15.5 + xcode16.4 + ios18.5 + flutter3.32.2  Still wrong！！！

**Comment by eEQK** [comment]
TL;DR verify the key in `Project Settings > Cloud Messaging > Apple app configuration`

_First of all, make sure you have `flutterfire configure` set up_

I had a similar issue, in the meantime we've moved the app to a different org and suddenly the notifications stopped working. The annoying part is that everything seemed to work, there were no errors whatsoever but notifications didn't go through on iOS.

Turns out apple removes the keys during org transfer so I had to set up that part again. 

Basically just go through this part: [1. Registering a key](https://firebase.flutter.dev/docs/messaging/apple-integration/#1-registering-a-key)

**Comment by mapp24dev** [comment]
The solution is actually hinted at in the warning itself:

> Check your ‘Local Network’ permissions for this app in the Privacy section of the system Settings.

What’s a bit confusing, though, is where you’re supposed to change that setting. I first tried to adjust it from within the simulator, but it turns out you need to do it in your Mac’s System Settings, not inside the simulator.

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/3c243317-6604-4d89-9eaa-3692fce7a17b" />

**Comment by MurbX** [comment]
> The solution is actually hinted at in the warning itself:
> 
> > Check your ‘Local Network’ permissions for this app in the Privacy section of the system Settings.
> 
> What’s a bit confusing, though, is where you’re supposed to change that setting. I first tried to adjust it from within the simulator, but it turns out you need to do it in your Mac’s System Settings, not inside the simulator.
> 
> <img alt="Image" width="716" src="https://private-user-images.githubusercontent.com/188555836/455158034-3c243317-6604-4d89-9eaa-3692fce7a17b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAwMTI3NjIsIm5iZiI6MTc1MDAxMjQ2MiwicGF0aCI6Ii8xODg1NTU4MzYvNDU1MTU4MDM0LTNjMjQzMzE3LTY2MDQtNGQ4OS05ZWFhLTM2OTJmY2U3YTE3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxNVQxODM0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2FhNGM2Y2IyOGMwNDcxNDgxYzg5NzJjYTdkYjVkNDU0YzFkZTIyMDczOTliYjQwN2RlM2Y4MDhhMDY1MWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.puwo8eSMkCWpj1SkruOMtMPmN5NjuJ4jcVt0s6xNvUY">

The issue on my end is that the it's not listed on the "Local Network" section and hence I can't grant it the permissions.

**Comment by DivyanshuKhattarTest** [comment]
Hey @MurbX I checked my mac's system settings. It doesn't show my app's name, It is only showing Chrome and Andriod Studio. Well I am running mobile app in IOS. I am getting this error:
`Could not register as server for FlutterDartVMServicePublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.`

**Comment by dustinatfwd** [comment]
Getting the same issue. Checked mac's settings but no related items in Local network

**Comment by akshatjain-beam** [comment]
getting same issue

**Comment by RubengilDribba** [comment]
Same issue here

**Comment by nickolasdeluca** [comment]
> THX [@madushans](https://github.com/madushans)
> 
> **[macOS 15.5 + Xcode 16.4 + iOS 18.5 Simulator + Flutter SDK 3.13.9]** works for me in Flutter Module.
> 
> ![Image](https://github.com/user-attachments/assets/dba94c11-531f-4029-ad38-f817481169cd)
> 
> And in the project I also set this in info.plist
> 
> ![Image](https://github.com/user-attachments/assets/5b67b12e-266e-482a-b380-d5c11bbebba6)
> 
> After I upgraded Xcode, my first attempt to attach the app failed. But after a system reboot and retest, it worked. However, subsequent attempts weren't always successful, and I'll keep an eye on the potential reasons for failure.

I added these entries to the info.plist and yet the warning persists. I manage to debug just fine, but I noticed that every time I start a debugging session, the app starts like an exception has happened, if I press continue, the app runs just fine and debugs correctly.

**Comment by glauberlima** [comment]
Same issue here.

Is there a workaround? Or can we downgrade the Flutter version?

**Comment by RubengilDribba** [comment]
Hello!

I finally solved this problem by running the app on a physical device first, and then running it on the simulator. When I ran the app on the physical device, Xcode prompted me for the necessary permissions (I believe that's what happened).

Is this a true workaround? No, not really a proper one. Will it work for you? I hope so. These seem like random solutions for random errors, but it's worth a try!

**Comment by madushans** [comment]
Seems to work without the warning now.

Launched my app now and it asked on Mac if <app name> should be allowed to access local network. I accepted and the warning is gone, and debugging works.

```
...  % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.5 24F74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 16.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.100.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

Debug Console on launch
```
Launching lib/main.dart on iPhone 16 in debug mode...
Xcode build done.                                           13.1s
Connecting to VM Service at ws://127.0.0.1:59631/EIG6Dw548E8=/ws
Connected to the VM Service.
```

**Comment by RubengilDribba** [comment]
¿It could be a problem with the M4 architecture?

**Comment by gb-matias-navarro** [comment]
> Hello!
> 
> I finally solved this problem by running the app on a physical device first, and then running it on the simulator. When I ran the app on the physical device, Xcode prompted me for the necessary permissions (I believe that's what happened).
> 
> Is this a true workaround? No, not really a proper one. Will it work for you? I hope so. These seem like random solutions for random errors, but it's worth a try!

This doesn't work for me

**Comment by JCKodel** [comment]
> ¿It could be a problem with the M4 architecture?

Nop. Using a Hackintosh (i7-13700K, 128Gb RAM) and the same error message.

**Comment by Dms98Br** [comment]
✅ Solved: Local Network Permission Error in iOS Flutter Debugging

Hey everyone! 👋

I was facing this error when running my Flutter app on iOS:

```
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(130)] 
Could not register as server for FlutterDartVMServicePublisher, permission denied. 
```
Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
Even though I had the proper keys in my Info.plist:


```
<key>NSLocalNetworkUsageDescription</key>
<string>This app needs local network access for debugging and communication.</string>
<key>NSBonjourServices</key>
<array>
  <string>_dartobservatory._tcp</string>
</array>
```
The app wasn’t showing up in Settings > Privacy > Local Network, and the error persisted.

💡 What worked for me
I just created a new Flutter file with a simple HTTP GET request to localhost:3000 and ran it.

Interestingly, the permission prompt never showed up, and the app still did not appear in the Local Network settings list.

However, after running this simple test, when I went back to my original app and ran it again, the error disappeared and everything started working fine.

If you’re stuck with this issue, try running a simple test app or file that accesses your local network (even if it’s just localhost), even if no permission prompt appears and the app doesn’t show in the Local Network list. It might “trigger” iOS to recognize the network usage properly.

Hope this helps others facing the same problem!

Here’s the code that solved it for me:

```
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Test Local Network')),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              try {
                final res = await http.get(Uri.parse('http://192.168.0.101:3000'));
                print('Success: ${res.statusCode}');
              } catch (e) {
                print('Error: $e');
              }
            },
            child: const Text('Call Localhost API'),
          ),
        ),
      ),
    );
  }
}
```

**Comment by brunos0** [comment]
> ✅ Solved: Local Network Permission Error in iOS Flutter Debugging
> 
> Hey everyone! 👋
> 
> I was facing this error when running my Flutter app on iOS:
> 
> ```
> [ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(130)] 
> Could not register as server for FlutterDartVMServicePublisher, permission denied. 
> ```
> 
> Check your 'Local Network' permissions for this app in the Privacy section of the system Settings. Even though I had the proper keys in my Info.plist:
> 
> ```
> <key>NSLocalNetworkUsageDescription</key>
> <string>This app needs local network access for debugging and communication.</string>
> <key>NSBonjourServices</key>
> <array>
>   <string>_dartobservatory._tcp</string>
> </array>
> ```
> 
> The app wasn’t showing up in Settings > Privacy > Local Network, and the error persisted.
> 
> 💡 What worked for me I just created a new Flutter file with a simple HTTP GET request to localhost:3000 and ran it.
> 
> Interestingly, the permission prompt never showed up, and the app still did not appear in the Local Network settings list.
> 
> However, after running this simple test, when I went back to my original app and ran it again, the error disappeared and everything started working fine.
> 
> If you’re stuck with this issue, try running a simple test app or file that accesses your local network (even if it’s just localhost), even if no permission prompt appears and the app doesn’t show in the Local Network list. It might “trigger” iOS to recognize the network usage properly.
> 
> Hope this helps others facing the same problem!
> 
> Here’s the code that solved it for me:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:http/http.dart' as http;
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         appBar: AppBar(title: const Text('Test Local Network')),
>         body: Center(
>           child: ElevatedButton(
>             onPressed: () async {
>               try {
>                 final res = await http.get(Uri.parse('http://192.168.0.101:3000'));
>                 print('Success: ${res.statusCode}');
>               } catch (e) {
>                 print('Error: $e');
>               }
>             },
>             child: const Text('Call Localhost API'),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

I can confirm that this way o was able to attach successfully!

I create a new project width "test" name, than i opened até vsCode and searched for test and then o replace com.example.test to same package name that i really wanna attach. When i rum It, appears a box asking for local permission. Then i go to real app and then error on console disappears and i could attach to app normally.

I think that is not a definitive way to fix It but now i can debug the application more easly.

Thx Mr Dms98Br

**Comment by njamal816** [comment]
> > ✅ Solved: Local Network Permission Error in iOS Flutter Debugging
> > Hey everyone! 👋
> > I was facing this error when running my Flutter app on iOS:
> > ```
> > [ERROR:flutter/shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm(130)] 
> > Could not register as server for FlutterDartVMServicePublisher, permission denied. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Check your 'Local Network' permissions for this app in the Privacy section of the system Settings. Even though I had the proper keys in my Info.plist:
> > ```
> > <key>NSLocalNetworkUsageDescription</key>
> > <string>This app needs local network access for debugging and communication.</string>
> > <key>NSBonjourServices</key>
> > <array>
> >   <string>_dartobservatory._tcp</string>
> > </array>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The app wasn’t showing up in Settings > Privacy > Local Network, and the error persisted.
> > 💡 What worked for me I just created a new Flutter file with a simple HTTP GET request to localhost:3000 and ran it.
> > Interestingly, the permission prompt never showed up, and the app still did not appear in the Local Network settings list.
> > However, after running this simple test, when I went back to my original app and ran it again, the error disappeared and everything started working fine.
> > If you’re stuck with this issue, try running a simple test app or file that accesses your local network (even if it’s just localhost), even if no permission prompt appears and the app doesn’t show in the Local Network list. It might “trigger” iOS to recognize the network usage properly.
> > Hope this helps others facing the same problem!
> > Here’s the code that solved it for me:
> > ```
> > import 'package:flutter/material.dart';
> > import 'package:http/http.dart' as http;
> > 
> > void main() => runApp(const MyApp());
> > 
> > class MyApp extends StatelessWidget {
> >   const MyApp({super.key});
> >   @override
> >   Widget build(BuildContext context) {
> >     return MaterialApp(
> >       home: Scaffold(
> >         appBar: AppBar(title: const Text('Test Local Network')),
> >         body: Center(
> >           child: ElevatedButton(
> >             onPressed: () async {
> >               try {
> >                 final res = await http.get(Uri.parse('http://192.168.0.101:3000'));
> >                 print('Success: ${res.statusCode}');
> >               } catch (e) {
> >                 print('Error: $e');
> >               }
> >             },
> >             child: const Text('Call Localhost API'),
> >           ),
> >         ),
> >       ),
> >     );
> >   }
> > }
> > ```
> 
> I can confirm that this way o was able to attach successfully!
> 
> I create a new project width "test" name, than i opened até vsCode and searched for test and then o replace com.example.test to same package name that i really wanna attach. When i rum It, appears a box asking for local permission. Then i go to real app and then error on console disappears and i could attach to app normally.
> 
> I think that is not a definitive way to fix It but now i can debug the application more easly.
> 
> Thx Mr Dms98Br

Didn't work for me. Does anyone got any solution for this?

**Comment by brunos0** [comment]
Apple developer told to test this scenario in macos 15.6 beta version. Hope this version fiz this issue.

**Comment by ajxbit** [comment]
Just try Erasing the device as it fixed for me.

<img width="356" height="86" alt="Image" src="https://github.com/user-attachments/assets/e5f5b53c-1697-4738-9a3c-3bc7b4eb39c2" />

**Comment by Turburlar** [comment]
Thumbs up for flutter developer experience!

**Comment by erikkubica** [comment]
I have managed to solve this by simply updating xcode through appstore.

**Comment by Rodrigolmti** [comment]
I tried all the suggestions and no luck with my project, sharing my context. Our project was a bit outdated in terms of dependencies and Flutter version, now Google play store has a policy that requires all apps to adhere to Android SDK 35, in order to get everything working on Android I had to use the latest Flutter version 3.32 .

Android build is working just fine, but my iOS build now does not work, if I try to build using vscode or xcode, and physical device or simulator. While exploring different solutions I was able to get a different error at some point, that hints to some miss configuration with Flutter SDK:

Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: <90FCEF77-12EA-3F25-ABF6-CF4318D0F460> /private/var/containers/Bundle/Application/8328AC31-7804-4254-AE48-4D81E6C34D63/Runner.app/Runner.debug.dylib
  Reason: tried: /usr/lib/swift/Flutter.framework/Flutter (no such file, not in dyld cache), 

This bug is a bit frustrating since i have to comply with Google play store policies by the end of the next month, and if I can't build the iOS project, I have a big problem.

Update:

I managed to find this [issue](https://github.com/flutter/flutter/issues/158090) which explains about the thin binary build step, for some reason my project did not had that phase anymore. Adding it back, solved the no such file error and i also don't get the error for the Could not register as server for FlutterDartVMServicePublisher.

I'm not sure what is the actual relationship between both issues, but just wanted to share what solved my issue.

This only solves the build straight from Xcode, I still get the following error while trying to build with vscode / cursor:

```txt
Error: Flutter could not connect to the Dart VM service.

Please ensure your IDE or terminal app has permission to access devices on the local network. This allows Flutter to connect to the Dart VM.

You can grant this permission in System Settings > Privacy & Security > Local Network.
SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
```

**Comment by glauberlima** [comment]
I believe the ultimate solution should come from Flutter team.

Everything mentioned in the thread are workaround solutions.

Em qua., 16 de jul. de 2025 às 12:43, Rodrigo Lopes <
***@***.***> escreveu:

**Comment by evanwangace** [comment]
God, this matter has been causing me significant concern. I would appreciate a prompt resolution.😣

**Comment by janlektonen** [comment]
Just updated to xCode 16.4 and created new simulator with iOS 18.5. I'm on latest macOS Sequoia 15.5.

I also tried this in info.plist:

<key>NSLocalNetworkUsageDescription</key>
<string>Allow the debugger to connect over your local network.</string>
<key>NSBonjourServices</key>
<array>
        <string>_dartVmService._tcp</string>
        <string>_dartobservatory._tcp</string>
</array>

I also looked for accepting internet access in macos and app under privacy & anonymi. Also The iOS simulator can browse internet fine in Safari but the app does not have access therefore the error we all talk about :-)

If it is a macOS problem I guess we will have to wait, but would be nice to have Flutter SDK working on iOS simulators again.

**Comment by PierrevdMerwe** [comment]
> Just updated to xCode 16.4 and created new simulator with iOS 18.5. I'm on latest macOS Sequoia 15.5.
> 
> I also tried this in info.plist:
> 
> NSLocalNetworkUsageDescription Allow the debugger to connect over your local network. NSBonjourServices _dartVmService._tcp _dartobservatory._tcp
> 
> I also looked for accepting internet access in macos and app under privacy & anonymi. Also The iOS simulator can browse internet fine in Safari but the app does not have access therefore the error we all talk about :-)
> 
> If it is a macOS problem I guess we will have to wait, but would be nice to have Flutter SDK working on iOS simulators again.

@janlektonen I have the exact same configuration and tried the same workarounds. Commenting here to stay in the loop for when there is a fix. I even tried older simulators but it didn't work.

**Comment by PierrevdMerwe** [comment]
## Update:
Fixed in macOS public beta 15.6 can confirm👍🏼

## Old:

I did some digging and it seems that this has been fixed in a new beta macOS version. See [HERE](https://developer.apple.com/forums/thread/780655?answerId=846540022#846540022) on apple forum.

I did ask to specify if this is the Public or Developer Beta version, still waiting on a response.

Hope this fixes our issues 🙏🏼

**Comment by toxaq** [comment]
So after I got this error and read this thread, in a second terminal I simply ran `dart devtools`. This opened a window in Chrome, I copied in the debugger profile url from the first terminal into that and boom, I got my app in the simluator. HTH.

**Comment by behnamsattar** [comment]
So I just downloaded macOS 15.6 which was released a couple of hours ago and it fixed the issue. We should be able to close this one.

**Comment by vashworth** [comment]
This issue is fixed with macOS 15.6. Closing.
