### ISSUE TITLE
Flutter web: 'CompilationError' while debugging makes debugging any `async` function virtually impossible

### ISSUE THREAD

**Issue by andynewman10** [flutter/flutter#168641]
### Steps to reproduce

Very often, it is not possible to inspect variable values by hovering over variable names while in a Flutter web debug session. The actual variable value is not displayed as it would be expected. Instead, a tooltip displaying the type of the variable is displayed, just as if the debugger wasn't running.

1. Create a Flutter web application using flutter create, then add an `async` function somewhere. Call it from, eg., the `incrementCounter()` implementation. Just print something out in this async function.
2. Place a breakpoint on the `print` line and start debugging
3. When you reach your breakpoint, try hovering a member variable name in the source code.

### Expected results

The variable value should be displayed.

### Actual results

The value of the variable is not displayed.

When the problem occurs, if you type the variable name in the debug console, you will see:

```
> image
CompilationError: The getter 'image' isn't defined for the class 'XXXPageState'.
 - 'XXXPageState' is from 'package:com_example_application/xxx_page.dart' ('lib/xxx_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'image'.
image
^^^^^
```

The debug console (itself) seems to work overall though:

```
> print(1234)
1234
> this
XXXPageState (XXXPageState#e5b8d)
  ... (correct output here)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
More details/discussion here: https://github.com/Dart-Code/Dart-Code/issues/5414
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots</summary>

In the screenshot below, the value of the variable should be displayed inside the tooltip window while in a debug session:

![Image](https://github.com/user-attachments/assets/e2bb20e5-79e0-4c5b-8e78-3ef8bde68272)

In the code above, note that image does have a value - and that value should be displayed - as the line of code above the yellow indicator has (successfully) been executed.

Also, the image variable is effectively used in the code further below (not shown), and even print'ed. It is not expected to be tree-shaken.

Occasionnally, the VS console log shows:

```
ChromeProxyService: Failed to evaluate expression '': InvalidInputError: .
```
</details>

### Logs

<details open><summary>Logs</summary>

```console
Nothing to show here
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.29.2, on Microsoft Windows [version 10.0.26100.3775], locale fr-FR) [762ms]
    ! Flutter version 3.29.2 on channel [user-branch] at C:\Users\andy\Documents\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision c236373904 (8 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (11 Professionnel 64-bit, 24H2, 2009) [3,0s]

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [5,7s]
    • Android SDK at C:\Users\andy\AppData\Local\Android\sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web [198ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.13.2) [196ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.13.35825.156
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3) [32ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.100.0) [30ms]
    • VS Code at C:\Users\andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.110.0

[√] Connected device (3 available) [349ms]
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.26100.3775]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 136.0.7103.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 136.0.3240.64

[√] Network resources [367ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by pamafe1976** [comment]
This happens not only when hovering over the variable, but also for the variable watcher in vscode, and when trying to print in the debug console. In both cases, the CompilationError is shown.

In my case it happens for most variables I try to inspect in **async** functions, even those variables declared locally.
Non async functions are not affected.

**This makes developing for web in flutter very difficult and slow.**

The getters seem to not be affected. Their values show correctly.

**Comment by AbdeMohlbi** [comment]
CC @FMorschel is this expected ?

**Comment by FMorschel** [comment]
The hover detecting an empty string seems like a VS Code bug (CC @DanTup any ideas?)

The values not showing even on watch seems like a VM bug if the variable is not treeshaken and has already been given a value (CC @derekxu16 )

**Comment by DanTup** [comment]
I think the main issue here is what @biggs0125 mentioned at https://github.com/Dart-Code/Dart-Code/issues/5414

> I suspect the fact that this is an async function is the issue here. Async Dart functions get translated as a complex state machine to allow for async gaps. In this representation, most variable declarations get hoisted out of the function body changing the way we have to refer to these variables. It's possible the expression evaluation code is generating incorrect references to these variables.

From my comment at https://github.com/Dart-Code/Dart-Code/issues/5414#issuecomment-2732605479 the compiled code uses `asyncScope.test` but I presume the expression evaluation is not correctly mapping to that.

I don't know if here, the Dart SDK, or the webdev repo is the right place for this issue though - perhaps @biggs0125 can advise.


> The hover detecting an empty string seems like a VS Code bug (CC @DanTup any ideas?)

It's hard to say without more info - steps to repro (or a log captured with **Dart: Capture Debugging Logs**) may be useful. It's possible the empty string doesn't originate in VS Code but happens somewhere along the way. I would suggest filing an issue at https://github.com/Dart-Code/Dart-Code about this with steps to repro / a log and we can inspect the raw DAP + VM Service traffic to try to understand where it's going wrong.

**Comment by darshankawar** [comment]
I tried following the details and steps to replicate in the linked issue but was unable to replicate it. I'll try few more times to see if I can get the reported error or not, but meantime, based on the report and discussion, I'll keep the issue open for team's tracking.

**Comment by a-siva** [comment]
//cc @nshahan

**Comment by andynewman10** [comment]
@biggs0125 any news on this? This problem causes serious headaches when debugging. In VS Code, the Variables section of the debugging pane sometimes contains 'Locals' and 'Globals' subsections, with variables values, as it should, I noticed, however sometimes it does not contain anything at all. In that case, inspecting variable values is impossible (since hovering over a variable name to get its value is already impossible, and typing something in the Debug Console does not work either).

Resolving this issue would give an extremely substantial benefit to developers.

**Comment by biggs0125** [comment]
The fix for this landed back in May but wasn't included in stable until Dart 3.9/Flutter 3.35 which were released 1.5 weeks ago. 

Closing this out since the issue should be fixed everywhere but please reopen if any more occurrences of you find new occurrences of this.

**Comment by andynewman10** [comment]
> The fix for this landed back in May but wasn't included in stable until Dart 3.9/Flutter 3.35 which were released 1.5 weeks ago.
> 
> Closing this out since the issue should be fixed everywhere but please reopen if any more occurrences of you find new occurrences of this.

@biggs0125 @darshankawar The problem still persists with Dart 3.9 and Flutter 3.35. Tested on Flutter 3.35.1 with a Flutter web project using latest VS Code and Dart-Code. I cannot test with Flutter 3.35.2, released yesterday, as there seems to be issues with Flutter web debugging with this version (console output flooded with `DebugService: Error serving requestsError: Unsupported operation: Cannot send Null` errors)

**Comment by andynewman10** [comment]
I cannot reopen the issue because the `Reopen issue` button is now greyed out.

**Comment by andynewman10** [comment]
Shall I open a new issue (I suspect I have to)?

**Comment by FMorschel** [comment]
@biggs0125 can you answer above please? Thanks!

Today is a holiday in the US, so maybe wait a bit more (tomorrow they may answer) @andynewman10.

**Comment by DanTup** [comment]
@andynewman10 sorry for the slow responses. I just tried this on on both Flutter 3.35.2 and also on latest `master` but the repro I had at https://github.com/Dart-Code/Dart-Code/issues/5414#issuecomment-2732605479 does seem to work now (although there are some other spurious errors that probably need debugging):

3.352:

<img width="857" height="412" alt="Image" src="https://github.com/user-attachments/assets/c489f3ba-618f-4b35-8808-72b926fce9f1" />

master:

<img width="735" height="467" alt="Image" src="https://github.com/user-attachments/assets/a579457d-db2c-4f93-ae5f-d3eaf21643df" />

Could you try `clean`ing the project to verify it's nothing stale and if it still repros, are you able to share a complete sample file and instructions that trigger it for you?

Thanks!

**Comment by andynewman10** [comment]
Sorry it took me so long to try again after problems I had this week.
Many thanks @DanTup. I believe the problem indeed came from my project requiring a `flutter clean`. I can no longer repro today using both Flutter 3.35.1 and 3.35.3.
My apology for the false alarm @biggs0125.

**Comment by DanTup** [comment]
@andynewman10 great, thanks for confirming!
