### ISSUE TITLE
Release app bundle failed to strip debug symbols from native libraries

### ISSUE THREAD

**Issue by yourengineerbro** [flutter/flutter#169443]
### Type of Request

infra task

### Infrastructure Environment

Command ran: flutter build appbundle

Error:
**Release app bundle failed to strip debug symbols from native libraries.** 
Attached image:
![Image](https://github.com/user-attachments/assets/2b1720a9-3c56-4f7d-9c8a-e2c73363804b)

flutter doctor:
**No issues found**
Attached image:

![Image](https://github.com/user-attachments/assets/7b3872fe-4f54-47b9-a9cc-8a6640ad2064)

Project directory: C:\myweb

Android/app/build.gradle.kts:
`
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val f = "C:/upload-keystore.jks"

android {
    namespace = "com.yourengineerbro.myweb"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.yourengineerbro.myweb"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        create("release") {
            keyAlias = "uploadkey"
            keyPassword = "password"
            storeFile = f?.let { file(it) }
            storePassword = "password"
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

flutter {
    source = "../.."
}`

### What is happening?
Release build is not getting generated.

### Steps to reproduce

Step 1: Install the latest Flutter SDK (as of time of creating this issue) and create a sample-template project.
Step 2: Add the signing code in Android/App/build.gradle.kts
Step 3: Run flutter build appbundle in release mode.

Operating system: Windows 10 home

### Expected results

I expect to get the app bundle (.aab) file generated at the execution of flutter build appbundle.

**Comment by ShuvamJaswal** [comment]
@Crdzbird I found the solution to my problem. Remove 
`    ndk {
                    debugSymbolLevel 'FULL'
                }`

from your buid.gradle and try again. Apparently they are not required anymore https://github.com/flutter/flutter/issues/60240#issuecomment-2625681148

**Comment by yourengineerbro** [comment]
Could not find `ndk { debugSymbolLevel 'FULL' }` anywhere in build.gradle.

I am on Windows OS, building for android.
Anyone who have solved, please suggest workaround.

**Comment by IvanGast** [comment]
Also experiencing same issue and can't release the application. Any fix would be very appreciated.

**Comment by Crdzbird** [comment]
For anyone experiencing the issue, the issue maybe linked to something related with gradle version, in my case the AAB has the following configuration and till today I can confirm the build actually works.

<img width="455" alt="Image" src="https://github.com/user-attachments/assets/d901c437-1fa5-49e8-8e3b-8da8962f69fb" />


This is my current setup, hope this helps anyone.

> settings.gradle


```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version '8.10.0' apply false
    // START: FlutterFire Configuration
    id "com.google.gms.google-services" version "4.3.15" apply false
    // END: FlutterFire Configuration
    id "org.jetbrains.kotlin.android" version "2.1.20" apply false
}
```

> cradle-wrapper.properties

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-all.zip`

> app/build.gradle

```
plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    // END: FlutterFire Configuration
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace "ni.devotion.powerbill"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion "29.0.13113456"

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "ni.devotion.powerbill"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 23
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutter.versionCode
        versionName flutter.versionName
    }

    signingConfigs {
        if (System.getenv("ANDROID_KEYSTORE_PATH")) {
            release {
                storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
                keyAlias System.getenv("ANDROID_KEYSTORE_ALIAS")
                keyPassword System.getenv("ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD")
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            }
        } else {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    flavorDimensions "default"
    productFlavors {
        production {
            dimension "default"
            applicationIdSuffix ""
            manifestPlaceholders = [appName: "Power Bill"]
        }
        staging {
            dimension "default"
            applicationIdSuffix ".stg"
            manifestPlaceholders = [appName: "[STG] Power Bill"]
        }
        development {
            dimension "default"
            applicationIdSuffix ".dev"
            manifestPlaceholders = [appName: "[DEV] Power Bill"]
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.20"
    implementation "com.onesignal:OneSignal:5.1.29"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}

```

**Comment by yourengineerbro** [comment]
@Crdzbird Have you used downgraded versions for it to work. It should be working fine with latest stable one.

In your code, what modules exactly have you downgraded?

**Comment by essare** [comment]
Everything was working fine, until I upgraded Flutter to `v3.32.0`, then the build stopped working
```BASH
flutter build appbundle \
    --flavor="$ENV" \
    --release \
    --dart-define=ENV="$ENV" \
    --obfuscate \
    --split-debug-info="$OUTPUT_DIR/debug-info-android"
```
The build fails with the following error:

`Running Gradle task 'bundleProdRelease'...   196.7s`
> Release app bundle failed to strip debug symbols from native libraries. Please run flutter doctor and ensure that the Android toolchain does not report any issues.

After downgrading to `v3.29.3`everything is working again.

**Comment by lembos-hauser** [comment]
Had the same issue. After rearranging multiple code sections I just decided to **go back to flutter 3.29.3** - which solved the problem!

**Comment by MichalDanielDobrzanski** [comment]
This is crazy. Where can we expect to have it fixed?

**Comment by MichalDanielDobrzanski** [comment]
This is crazy. When can we expect to have it fixed?

**Comment by docaohuynhcse** [comment]
I got same error when upgrade to [3.32.1]. Build apk success but  build appbundle failure

**Comment by docaohuynhcse** [comment]
> [@Crdzbird](https://github.com/Crdzbird) I found the solution to my problem. Remove
> 
> ` ndk { debugSymbolLevel 'FULL' }`
> 
> from your buid.gradle and try again. Apparently they are not required anymore [#60240 (comment)](https://github.com/flutter/flutter/issues/60240#issuecomment-2625681148)

After commend this line it works. Thanks

```
 buildTypes {
      release {
          signingConfig signingConfigs.release
          // ndk {
          //     debugSymbolLevel 'FULL'
          // }
      }
  }
```

**Comment by MostafaAlyy** [comment]
I have the build Gradle file in Kotlin it does not contain  debugSymbolLevel  to remove, and this problem still happens

**Comment by gmackall** [comment]
Anyone including 
```
                ndk {
                    debugSymbolLevel 'FULL'
                }
```
in their `buildTypes` block as an attempted fix for https://github.com/flutter/flutter/issues/60240 should remove it.

For those who are intentionally adding this configuration, it's inclusion should be fixed by https://github.com/flutter/flutter/pull/169864, which I'll work on getting cherry picked to stable as well.

For those of you who aren't including that block but are still encountering this - does it reproduce on a simple counter app?

**Comment by hajini** [comment]
On app/build/gradle 

you may change the code from

ndk {
   debugSymbolLevel 'FULL'
}

to 

ndk {
   debugSymbolLevel 'symbol_table'
}

**Comment by gvozditskiy** [comment]
Still have this issue.
I don't have debugSymbolLevel in gradle file. 

Running Gradle task 'bundleProductionRelease'...                  433.0s
**_Release app bundle failed to strip debug symbols from native libraries_**. Please run flutter doctor and ensure that the Android toolchain does not report any issues.

Otherwise, file an issue at https://github.com/flutter/flutter/issues.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.32.4, on macOS 15.5 24F74 darwin-arm64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.4)
    ! CocoaPods 1.15.0 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2024.2.2)
[✓] IntelliJ IDEA Community Edition (version 2024.2.3)
[✓] VS Code (version 1.100.3)
[✓] Connected device (3 available)            
[✓] Network resources

**Comment by gvozditskiy** [comment]
Still have this issue.
I don't have debugSymbolLevel in gradle file.

Running Gradle task 'bundleProductionRelease'... 433.0s
Release app bundle failed to strip debug symbols from native libraries. Please run flutter doctor and ensure that the Android toolchain does not report any issues.

Otherwise, file an issue at https://github.com/flutter/flutter/issues.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.32.4, on macOS 15.5 24F74 darwin-arm64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.4)
! CocoaPods 1.15.0 out of date (1.16.2 is recommended).
CocoaPods is a package manager for iOS or macOS platform code.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/to/platform-plugins
To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2024.2.2)
[✓] IntelliJ IDEA Community Edition (version 2024.2.3)
[✓] VS Code (version 1.100.3)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by gmackall** [comment]
> Still have this issue. I don't have debugSymbolLevel in gradle file.
> 
> Running Gradle task 'bundleProductionRelease'... 433.0s Release app bundle failed to strip debug symbols from native libraries. Please run flutter doctor and ensure that the Android toolchain does not report any issues.
> 
> Otherwise, file an issue at https://github.com/flutter/flutter/issues.
> 
> Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.32.4, on macOS 15.5 24F74 darwin-arm64, locale en-RU) [✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [!] Xcode - develop for iOS and macOS (Xcode 16.4) ! CocoaPods 1.15.0 out of date (1.16.2 is recommended). CocoaPods is a package manager for iOS or macOS platform code. Without CocoaPods, plugins will not work on iOS or macOS. For more info, see https://flutter.dev/to/platform-plugins To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods [✓] Chrome - develop for the web [✓] Android Studio (version 2024.3) [✓] Android Studio (version 2024.1) [✓] Android Studio (version 2024.2.2) [✓] IntelliJ IDEA Community Edition (version 2024.2.3) [✓] VS Code (version 1.100.3) [✓] Connected device (3 available) [✓] Network resources

Can you post the verbose logs from your build? (`flutter build appbundle --verbose`, plus your normal arguments)

**Comment by lembos-hauser** [comment]
As far as I know for now the fix is to downgrade from your Flutter:
Flutter (Channel stable, 3.32.4)
I fixed it by going back to 3.29.3.

**Comment by gvozditskiy** [comment]
@lembos-hauser I wouldn't really call this a "fix"

@gmackall 
` flutter build appbundle --flavor production --target lib/main_production.dart --obfuscate  --split-debug-info=symbols --verbose`
```
[  +47 ms] Release app bundle failed to strip debug symbols from native libraries. Please run flutter doctor and ensure that the Android toolchain does not report any issues.
           
           Otherwise, file an issue at https://github.com/flutter/flutter/issues.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:597:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:263:5)
           <asynchronous suspension>
           #3      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:168:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1563:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:494:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:102:3)
           <asynchronous suspension>
           
           
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[  +90 ms] exiting with code 1
```

**Comment by gmackall** [comment]
> [@lembos-hauser](https://github.com/lembos-hauser) I wouldn't really call this a "fix"
> 
> [@gmackall[<img alt="" width="15" height="15" src="chrome-extension://dlebflppeeemcdpidccbiblndppbmjmh/ospo-chrome-ext-logo.png">](https://teams.googleplex.com/mackall@google.com)](https://github.com/gmackall) ` flutter build appbundle --flavor production --target lib/main_production.dart --obfuscate --split-debug-info=symbols --verbose`
> 
> ```
> [  +47 ms] Release app bundle failed to strip debug symbols from native libraries. Please run flutter doctor and ensure that the Android toolchain does not report any issues.
>            
>            Otherwise, file an issue at https://github.com/flutter/flutter/issues.
> [        ] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
>            #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:597:9)
>            <asynchronous suspension>
>            #2      AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:263:5)
>            <asynchronous suspension>
>            #3      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:168:5)
>            <asynchronous suspension>
>            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1563:27)
>            <asynchronous suspension>
>            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
>            <asynchronous suspension>
>            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:494:9)
>            <asynchronous suspension>
>            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
>            <asynchronous suspension>
>            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
>            <asynchronous suspension>
>            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
>            <asynchronous suspension>
>            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
>            <asynchronous suspension>
>            #12     main (package:flutter_tools/executable.dart:102:3)
>            <asynchronous suspension>
>            
>            
> [        ] Running 1 shutdown hook
> [   +1 ms] Shutdown hooks complete
> [  +90 ms] exiting with code 1
> ```

I assume this is not the full output, is it? I'm looking for earlier logs from the Android gradle plugin which would indicate why symbols were not stripped.

**Comment by gvozditskiy** [comment]
Full log: [android_build.txt](https://github.com/user-attachments/files/20796162/android_build.txt)

**Comment by Tienisto** [comment]
In my case, I needed to install `Android SDK Command-line Tools`. Using SDK Manager in Android Studio is an easy way to do it.

The line `ndk { debugSymbolLevel 'FULL' }` has no effect on my side.

**Comment by mu7mmd** [comment]
@Tienisto Thanks it works directly

**Comment by gvozditskiy** [comment]
Flutter 3.32.5. The error still persists

**Comment by gvozditskiy** [comment]
removing `doNotStrip '**/*.so'` fixed the problem

**Comment by zkrige** [comment]
im on macOS and my android sdk path has no spaces.

If I use `ndk { debugSymbolLevel 'NONE'}` then I get the error
If I use `ndk { debugSymbolLevel 'SYMBOL_TABLE'}` then I the error goes away

**Comment by AyeshaIftikhar** [comment]
> removing `doNotStrip '**/*.so'` fixed the problem

This seems to work but my generated app bundle has size of 418 mbs. Could you suggest some workarounds to reduce size?

**Comment by joshmalin1** [comment]
> Had the same issue. After rearranging multiple code sections I just decided to **go back to flutter 3.29.3** - which solved the problem!

This was the solution for me as well.

**Comment by Rakibul25** [comment]
We encountered this issue only when trying to generate an app bundle.

It was happening on my **colleague’s Windows laptop**, while the same project worked perfectly on my macOS machine, with no errors during build.

Everything was ok, Flutter SDK and Android SDK were set up. Environment variables (ANDROID_HOME) were correct, flutter doctor showed no issues.

But still, the app bundle build failed to strip debug symbols from native libraries

After a lot of findings and solutions, we discovered a solution on the internet. The problem was related to the Android SDK path containing spaces.

In my colleague’s system, the SDK was located at-

`C:\Users\MD. Muied Hossain\AppData\Local\Android\sdk`

That space in the username folder (MD. Muied Hossain) was causing the bundle build to fail — likely due to how certain native or Gradle tasks handle paths with spaces.

**✅ Solution:**

We moved the SDK to a path without spaces, like:

`C:\src\Android\sdk`

Then we updated the SDK path in Android Studio, updated the ANDROID_HOME environment variable to the new location. After that, flutter build appbundle worked without any issues.
