### ISSUE TITLE
ListView inside a NestedScrollView skipping items while scrolling up 

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#17096]
## Steps to Reproduce
1. scroll down to the bottom
2. scroll up
 -> the ListView will only finish the animation after skipping some items

Could this be a bug or is my usage of a ListView inside a NestedScrollView not correct?

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new MaterialApp(
            home: new DefaultTabController(
                length: 1,
                child: new Scaffold(
                    body: new NestedScrollView(
                        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                            return <Widget>[
                                new SliverAppBar(
                                    pinned: true,
                                    expandedHeight: 256.0,
                                    floating: true,
                                    bottom: new PreferredSize(
                                        preferredSize: new Size.fromHeight(30.0),
                                        child: new Container(
                                            height: 30.0,
                                            child: new TabBar(
                                                tabs: [ new Tab(child: new Text("First"))],
                                            ),
                                        ),
                                    ),
                                ),
                            ];
                        },
                        body: new TabBarView(
                            children: [
                                new ListView.builder(
                                    itemCount: 20,
                                    itemBuilder: (BuildContext context, int index) {
                                        return new ListTile(title: new Text("Item $index"));
                                    },
                                ),
                            ]
                        ),
                    ),
                ),
            )
        );
    }
}
```

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.3.6-pre.53, on Mac OS X 10.13.4 17E199, locale de-DE)
    • Flutter version 0.3.6-pre.53 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision cdbb2385f1 (50 minutes ago), 2018-04-29 10:47:34 -0700
    • Engine revision 613aae032f
    • Dart version 2.0.0-dev.50.0.flutter-cd0c4e4fe1

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/valauskasmodestas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-ea-b05)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.3317.48

[✓] Connected devices (2 available)
    • MViPhone • 423196df51b51b49d7d58cab29ea34e19f94fbe8 • ios • iOS 11.3
    • iPhone X • A1223CE9-152A-48EA-8C14-94C467CBF812     • ios • iOS 11.3 (simulator)
```

**Comment by zoechi** [comment]
I don't seem to be able with your example code (thanks for that) with 

[✓] Flutter (Channel master, v0.7.1-pre.28, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.7.1-pre.28 at /Users/zoechi/flutter/flutter
    • Framework revision 546449238a (8 hours ago), 2018-08-26 19:50:02 -0400
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by modulovalue** [comment]
I've recreated the bug with the official gallery demo ([tabs_demo.dart](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/tabs_demo.dart/))

here's a video on how to trigger it
[video](https://www.youtube.com/watch?v=wGxvNQI6KGQ&feature=youtu.be)
(The height of the SliverAppBar was changed to 350.0)

**Comment by miguelpruivo** [comment]
I have what it looks like a similar issue.
In my app I have a `NestedScrollView` with a sliver header. Somehow, in iOS, when the scroll is made "quickly" to the top, there's a slightly jump back from the header to its initial position. However, if you scroll slowly, it's fine.

**Comment by wwwdata** [comment]
You can also trigger the bug by scrolling down very fast and tapping right before it would do the overscroll on iOS. Then the Scrollview will reliably jump up a lot

**Comment by lifenautjoe** [comment]
Same problem here. And a note to everyone else, please remember to upvote the original top issue, that's the one that drives priority for what I've read on other issues.

**Comment by TheJulianJES** [comment]
For me it seems to help to remove the following lines: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_physics.dart#L314-L315
Then it kind of works, but that isn't a fix as it's probably intended for something else.
I can also get it to continuously "glitch", if you scroll up like in the video posted ([here](https://www.youtube.com/watch?v=wGxvNQI6KGQ)), then immediately stop with the scrolling and then let go of the mouse button / lifting the finger. Then it'll "glitch" every time.

**Comment by matthiasbruns** [comment]
Any updates on this? Facing the same issues

**Comment by kamilpowalowski** [comment]
Was this fixed?

**Comment by anandnaikb** [comment]
Having the same issue when using `NestedScrollView` with `ListView.seperated()` as the `body`. It's quite choppy when you try to scroll up immediately after you scroll down (Similar to  when you pull to refresh). 

![ezgif-3-209d15f2f639](https://user-images.githubusercontent.com/7621183/83909596-ab10dd00-a79b-11ea-99e2-445eedbe8170.gif)

**Comment by themobilecoder** [comment]
Still has not been fixed since at Flutter v.1.17.3 Stable branch

**Comment by anandnaikb** [comment]
Fix available on master branch.

**Comment by DanielSmith1239** [comment]
I'm experiencing the same issue, and updating to the master branch didn't fix the issue for me.

**Comment by DanielSmith1239** [comment]
Any updates on this?

**Comment by sulaiman-mlbd** [comment]
Any update on this? Still facing issue in flutter 1.22.6
