### ISSUE TITLE
Bug in class object.dart for RenderObject and more precisely LayoutBuilder

### ISSUE THREAD

**Issue by Nicroms** [flutter/flutter#171429]
### Steps to reproduce

In the void layout(Constraints constraints, {bool parentUsesSize = false}) { method there is a crash on line     final RenderObject relayoutBoundary = isRelayoutBoundary ? this : parent!._relayoutBoundary!;

with Null check operator used on a null value parent!._relayoutBoundary! here precisely, the _relayoutBoundary is null and so create a crash on it
 

### Expected results

No error 

### Actual results

The following _TypeError was thrown during performLayout():
Null check operator used on a null value

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:marquee/marquee.dart';

class TeleportingMarquee extends StatefulWidget {
  final String text;
  final TextStyle style;
  final Duration scrollDuration;
  final Duration pauseDuration;
  final bool shouldCenter;

  const TeleportingMarquee({
    Key? key,
    required this.text,
    required this.style,
    this.shouldCenter = false,
    this.scrollDuration = const Duration(seconds: 5),
    this.pauseDuration = const Duration(seconds: 2),
  }) : super(key: key);

  @override
  State<TeleportingMarquee> createState() => _TeleportingMarqueeState();
}

class _TeleportingMarqueeState extends State<TeleportingMarquee> {
  String _text = '';
  Timer? _timer;
  bool _needsScrolling = false;

  @override
  void initState() {
    super.initState();
    _text = widget.text;
  }

  @override
  void didUpdateWidget(covariant TeleportingMarquee oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.text != widget.text) {
      _text = widget.text;
    }
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final textSpan = TextSpan(text: widget.text, style: widget.style);
        final textPainter = TextPainter(
          text: textSpan,
          textDirection: TextDirection.ltr,
          maxLines: 1,
        )..layout();

        final needsScroll = textPainter.width > constraints.maxWidth - 10;

        return SizedBox(
            height: textPainter.height, // Use actual text height
            child: needsScroll
                ? _buildMarquee(textPainter)
                : widget.shouldCenter ? _buildCenterStaticText() : _buildStaticText(),
        );
      },
    );
  }

  Widget _buildMarquee(TextPainter textPainter) {
    return Center( // Added Center wrapper
      child: Marquee(
        text: _text,
        style: widget.style,
        pauseAfterRound: widget.pauseDuration,
        scrollAxis: Axis.horizontal,
        crossAxisAlignment: widget.shouldCenter ? CrossAxisAlignment.center : CrossAxisAlignment.start, // Changed to center
        velocity: 85,
        blankSpace: 20.0,
        startPadding: 0.0,
        fadingEdgeStartFraction: 0.0,
        fadingEdgeEndFraction: 0.0,
        showFadingOnlyWhenScrolling: true,
      ),
    );
  }

  Widget _buildStaticText() {
    return  Text(
        _text,
        style: widget.style,
        overflow: TextOverflow.visible,
    );
  }

  Widget _buildCenterStaticText() {
    return Center( // Added Center wrapper
      child: Text(
        _text,
        textAlign: TextAlign.center,
        style: widget.style,
        overflow: TextOverflow.visible,
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

======== Exception caught by rendering library =====================================================
The following _TypeError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was: 
  LayoutBuilder LayoutBuilder:file:///Users/axel/m1nno/mobile-multiplateform/m1nno_flutter/lib/widgets/teleporting_marquee.dart:52:12
When the exception was thrown, this was the stack: 
#0      RenderObject.layout (package:flutter/src/rendering/object.dart:2744:96)
#1      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:451:14)
#2      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2655:7)
#3      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1160:18)
#4      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1173:15)
#5      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:629:23)
#6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1242:13)
#7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
#9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
#10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1204:5)
#11     _invoke (dart:ui/hooks.dart:331:13)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444:5)
#13     _drawFrame (dart:ui/hooks.dart:303:31)
The following RenderObject was being processed when the exception was fired: _RenderLayoutBuilder#622dc NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=259.4, 0.0<=h<=Infinity)
...  size: Size(259.4, 19.0)
RenderObject: _RenderLayoutBuilder#622dc NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=259.4, 0.0<=h<=Infinity)
  size: Size(259.4, 19.0)
...  child: RenderConstrainedBox#a935b NEEDS-PAINT
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=259.4, 0.0<=h<=Infinity)
...    size: Size(259.4, 19.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=19.0)
...    child: RenderPositionedBox#75acc NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=259.4, h=19.0)
...      size: Size(259.4, 19.0)
...      alignment: Alignment.center
...      textDirection: ltr
...      widthFactor: expand
...      heightFactor: expand
...      child: RenderShaderMask#9a40b relayoutBoundary=up1 NEEDS-PAINT
...        needs compositing
...        parentData: offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=259.4, 0.0<=h<=19.0)
...        layer: ShaderMaskLayer#b7a7b DETACHED
...          engine layer: ShaderMaskEngineLayer#e5324
...          handles: 2
...          shader: Instance of 'Gradient'
...          maskRect: Rect.fromLTRB(35.0, 172.0, 294.4, 191.0)
...          blendMode: dstIn
...        size: Size(259.4, 19.0)
...        child: RenderClipRect#6557d relayoutBoundary=up2
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=259.4, 0.0<=h<=19.0)
...          size: Size(259.4, 19.0)
====================================================================================================```

</details>

**Comment by pamafe1976** [comment]
Hi @Nicroms.
I could not reproduce the issue with the code you provided.
Could this be related to #170478 
Did you try with the master channel?

Regards

**Comment by darshankawar** [comment]
@Nicroms  Based on the logs, it seems similar to https://github.com/flutter/flutter/issues/170478 which has been fixed in master, so I suggest you to switch to latest master and re-run your scenario to confirm that it works. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by Nicroms** [comment]
Yes this is the same problem, as i develop on stable for production I was still having this problem but I manage to redo part of my functionality in another way which is working well now. Thanks for the fast response !

**Comment by ashwinashok98** [comment]
@Nicroms  Could you please share how you were able to resolve the issue or what exactly you redid? I'm facing a similar problem and any details would be really helpful. Thanks in advance!

**Comment by Nicroms** [comment]
I removed the usage of layout builder and calculated the need to scroll like that :
```
 // Calculate text dimensions
    final textSpan = TextSpan(text: widget.text, style: widget.style);
    final textPainter = TextPainter(
      text: textSpan,
      textDirection: TextDirection.ltr,
      maxLines: 1,
    )..layout();

    // Determine if scrolling is needed
    bool needsScroll = false;

    if (_isWidgetMounted && _availableWidth != null) {
      needsScroll = textPainter.width > _availableWidth! - 10;
    } else {
      // If not yet measured, try to measure now
      WidgetsBinding.instance.addPostFrameCallback((_) {
        _measureWidth();
      });
      // For now, assume no scrolling needed until we have measurements
      needsScroll = false;
    }
```

with : 

```
 void _measureWidth() {
    if (!mounted) return;

    try {
      final renderBox = context.findRenderObject() as RenderBox?;
      if (renderBox != null && renderBox.hasSize) {
        final newWidth = renderBox.size.width;
        if (_availableWidth != newWidth) {
          setState(() {
            _availableWidth = newWidth;
            _isWidgetMounted = true;
          });
        }
      } else {
        // If RenderBox is not ready, try again in the next frame
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (mounted) {
            _measureWidth();
          }
        });
      }
    } catch (e) {
      // Handle any exceptions gracefully
      print('Error measuring width: $e');
      // Set a reasonable fallback if measurement fails
      if (_availableWidth == null && mounted) {
        setState(() {
          _availableWidth = 300.0; // Reasonable fallback
          _isWidgetMounted = true;
        });
      }
    }
  }
```
