### ISSUE TITLE
SIGSEGV crashes on Android with Flutter 3.32.4

### ISSUE THREAD

**Issue by nottmey** [flutter/flutter#171691]
### Steps to reproduce

(caused in user device, not yet reproducible)

### Expected results

no crash

### Actual results

0.5% of our android user sessions crashing

Android 11 to 16L

affected devices: (no 100% error rate)
- samsung a55x (Samsung Galaxy A55 5G)
- samsung a52sxq (Samsung Galaxy A52s 5G)
- samsung r8q (Samsung Galaxy S20 FE 5G)
- samsung o1s (Samsung Galaxy S21)
- samsung dm3q (Samsung Galaxy S23 Ultra)
- google lynx (Google Pixel 7a)
- (and some more)

### Code sample

(not yet reproducible)

### Logs

<details open><summary>Logs</summary>

```console
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 25277 >>> io.onecommafive.my.production.app <<<

backtrace:
  #00  pc 0x000000000006c3b8  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+12)
  #01  pc 0x00000000004cb08c  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::mutex::lock()+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #02  pc 0x00000000007fbac0  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (impeller::CommandQueueVK::Submit(std::_fl::vector<std::_fl::shared_ptr<impeller::CommandBuffer>, std::_fl::allocator<std::_fl::shared_ptr<impeller::CommandBuffer>>> const&, std::_fl::function<void (impeller::CommandBuffer::Status)> const&)+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #03  pc 0x000000000085be4c  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::UnsafeUploadTextureToPrivate(std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::optional<SkImageInfo> const&)+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #04  pc 0x000000000085c124  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::__function::__func<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0, std::_fl::allocator<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0>, void ()>::operator()()+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #05  pc 0x00000000004d0678  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #06  pc 0x000000000085b448  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #07  pc 0x000000000085b1b8  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const::'lambda'()::operator()() const+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #08  pc 0x000000000085b06c  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1, std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1>, void ()>::operator()()+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #09  pc 0x00000000004cce54  /data/app/~~Vc-i1HztTpVkEv8ofiNdDw==/io.onecommafive.my.production.app-rllEM0C10cDwHCwQPZw5dA==/split_config.arm64_v8a.apk!libflutter.so (void* std::_fl::__thread_proxy[abi:nn210000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>>(void*)+20135936) (BuildId: a3968a9125362955f61c5475b7b5b499c7c46589)
  #10  pc 0x000000000006b1f0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+196)
  #11  pc 0x000000000005e1b4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

</details>

### Flutter Doctor output

(not yet reproducible)

**Comment by Ginder-Singh** [comment]
MacBook-Pro:app gindersingh$ flutter doctor -v
[✓] Flutter (Channel beta, 3.34.0-0.1.pre, on macOS 15.4 24E248 darwin-arm64, locale en-CA) [823ms]
    • Flutter version 3.34.0-0.1.pre on channel beta at /Users/gindersingh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb3ca25171 (3 weeks ago), 2025-06-17 14:19:52 -0700
    • Engine revision 8ed9edbd7a
    • Dart version 3.9.0 (build 3.9.0-196.1.beta)
    • DevTools version 2.47.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [4.3s]
    • Android SDK at /Users/gindersingh/Library/Android/sdk
    • Emulator version 35.6.11.0 (build_id 13610412) (CL:N/A)
    • Platform android-36, build-tools 35.0.1
    • ANDROID_HOME = /Users/gindersingh/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/gindersingh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [2.1s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [12ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [12ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.100.1) [10ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available) [7.5s]
    • SM A356W (mobile)                     • RFCX508G1AR   • android-arm64  • Android 15 (API 35)
    • sdk google atv64 amati arm64 (mobile) • emulator-5554 • android-arm64  • Android 16 (API 36) (emulator)
    • macOS (desktop)                       • macos         • darwin-arm64   • macOS 15.4 24E248 darwin-arm64
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 137.0.7151.120
    ! Error: Browsing on the local area network for Ginder’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [459ms]
    • All expected network resources are available.

• No issues found!

```

Installing build/app/outputs/flutter-apk/app-debug.apk...
D/FlutterJNI( 9539): Beginning load of flutter...
D/FlutterJNI( 9539): flutter (null) was loaded normally!
I/flutter ( 9539): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(62)] Using the Impeller rendering backend (Vulkan).
Debug service listening on ws://127.0.0.1:58725/eRXLchyIaFs=/ws
Syncing files to device sdk google atv64 amati arm64...
F/libc    ( 9539): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x799ce20100 in tid 9581 (1.raster), pid 9539 (ld.setuputility)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_google_atv64_amati_arm64/emu64a:16/BT2A.250323.001.A4/13388323:user/dev-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2025-07-07 02:36:27.402777554-0400
Process uptime: 4s
Cmdline: com.controld.setuputility
pid: 9539, tid: 9581, name: 1.raster  >>> com.controld.setuputility <<<
uid: 10096
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x000000799ce20100
    x0  000000799ce20100  x1  b400007993047000  x2  0000000000400000  x3  000000799ce20100
    x4  b400007993447000  x5  000000799d220100  x6  00000079b309411c  x7  0000000000000000
    x8  b400007b2ac376e0  x9  0000000000400000  x10 00000000e6d9df31  x11 0200007b2ac376e0
    x12 0000000000000000  x13 d9ec383e7dd4900a  x14 0000000000000000  x15 b400007c5ac27240
    x16 00000079b635f660  x17 0000007d6aed3300  x18 00000079b2c84000  x19 0000000000400000
    x20 0000000000000000  x21 000000799ce20100  x22 b400007beac4ddc8  x23 0000000000000000
    x24 b400007993047000  x25 0000000000000000  x26 00000000000025c8  x27 00000079b3094660
    x28 b400007c9ac419f0  x29 00000000000005d0
    lr  00000079b5e908d8  sp  00000079b3094300  pc  0000007d6aed3400  pst 0000000020001000
37 total frames
backtrace:
      #00 pc 000000000006a400  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy_aarch64_simd+256) (BuildId: a5abe11d81f309ffe9415d00efc3f46c)
      #01 pc 0000000001df28d4  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #02 pc 0000000001c6578c  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #03 pc 0000000001c65654  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #04 pc 0000000001cfcb68  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #05 pc 0000000001c68344  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #06 pc 0000000001db7d98  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #07 pc 0000000001dbc05c  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #08 pc 0000000001d79e04  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #09 pc 0000000001d7d048  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #10 pc 0000000001a27cac  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #11 pc 0000000001d81ae4  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #12 pc 0000000001a2841c  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #13 pc 0000000001a27740  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #14 pc 0000000001d82e84  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #15 pc 0000000001e955f8  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #16 pc 0000000001cf4f0c  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #17 pc 0000000001cf4dec  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #18 pc 0000000001cf4e74  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #19 pc 0000000001e1e2a0  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #20 pc 0000000001e1dd54  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #21 pc 0000000001e1cbe8  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #22 pc 0000000001e1d5c4  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #23 pc 0000000001e1f1fc  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #24 pc 0000000001e1d058  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #25 pc 0000000001e1cdf0  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #26 pc 0000000001e2bdec  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #27 pc 00000000019c161c  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #28 pc 00000000019c7114  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #29 pc 0000000000018eec  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+1224) (BuildId: 73be4fd1c6333950b8c8ec712bad69c1)
      #30 pc 0000000000025480  /system/lib64/libandroid.so (ALooper_pollOnce+100) (BuildId: 3470d50c3d3b89f9a63a1aa3538c5075)
      #31 pc 00000000019c709c  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #32 pc 00000000019c1568  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #33 pc 00000000019c53e0  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #34 pc 00000000019c5278  /data/app/~~onXV5V448fpKXu5BANoCfA==/com.controld.setuputility-UiuPF-WD_dwt8Q8792KFRw==/lib/arm64/libflutter.so (BuildId: 00a8bf97df45bbb849d72826174c3e6466a548b8)
      #35 pc 0000000000080df8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+232) (BuildId: a5abe11d81f309ffe9415d00efc3f46c)
      #36 pc 0000000000073dd8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a5abe11d81f309ffe9415d00efc3f46c)
Lost connection to device.
The Dart compiler exited unexpectedly.
```

**Comment by darshankawar** [comment]
@Ginder-Singh The stacktrace you shared doesn't seem to be similar / related to original issue, so first please try to get symbolicated logs using https://github.com/flutter/flutter/blob/master/engine/src/flutter/docs/Crashes.md#android and file a new issue.

**Comment by darshankawar** [comment]
Based on impeller logs from original issue description, it looks related to https://github.com/flutter/flutter/issues/164794, but this doesn't have the metal related entries, so could be different from the fixed one above.
Keeping the issue open for team's tracking / attention.

**Comment by nottmey** [comment]
@darshankawar thank you for classifying this, from #164794 I can see that it's fix first appeared in 3.31.0, so if it would be the same thing, it wouldn't appear in 3.32.4, right?

Which leads me to think this is something different.

**Comment by Neelansh-ns** [comment]
Getting a similar crash:

Logs:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 12082 >>> io.invideo.ai <<<

backtrace:
  #00  pc 0x00000000000f4fcc  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+8)
  #01  pc 0x00000000004cb08c  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::mutex::lock()+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #02  pc 0x00000000007fb8d4  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (impeller::CommandQueueVK::Submit(std::_fl::vector<std::_fl::shared_ptr<impeller::CommandBuffer>, std::_fl::allocator<std::_fl::shared_ptr<impeller::CommandBuffer>>> const&, std::_fl::function<void (impeller::CommandBuffer::Status)> const&)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #03  pc 0x000000000085b95c  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::UnsafeUploadTextureToPrivate(std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::optional<SkImageInfo> const&)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #04  pc 0x000000000085bc34  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::__function::__func<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0, std::_fl::allocator<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0>, void ()>::operator()()+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #05  pc 0x00000000004d0678  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #06  pc 0x000000000085af58  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #07  pc 0x000000000085acc8  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const::'lambda'()::operator()() const+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #08  pc 0x000000000085ab7c  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1, std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1>, void ()>::operator()()+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #09  pc 0x00000000004cce54  /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (void* std::_fl::__thread_proxy[abi:nn210000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>>(void*)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
  #10  pc 0x00000000000f4510  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #11  pc 0x000000000008ef34  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

<img width="1139" height="719" alt="Image" src="https://github.com/user-attachments/assets/a20d6aaa-0d7b-4260-ae18-54af5ee7bc47" />

**Comment by tirth-patel-nc** [comment]
@Neelansh-ns could you please try symbolising it? https://github.com/flutter/flutter/blob/master/engine/src/flutter/docs/Crashes.md

**Comment by Neelansh-ns** [comment]
> [@Neelansh-ns](https://github.com/Neelansh-ns) could you please try symbolising it? https://github.com/flutter/flutter/blob/master/engine/src/flutter/docs/Crashes.md

Flutter Version: `3.32.2`

Symbolicated Report:

```
********** Crash dump: **********
#00 0x00000000000f4fcc /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+8)
#01 0x00000000004cb08c /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::mutex::lock()+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             std::_fl::__libcpp_mutex_lock[abi:nn210000](pthread_mutex_t*)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__thread/support/pthread.h:95:10
                                                                                                                                             std::_fl::mutex::lock()
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/src/mutex.cpp:29:12
#02 0x00000000007fb8d4 /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (impeller::CommandQueueVK::Submit(std::_fl::vector<std::_fl::shared_ptr<impeller::CommandBuffer>, std::_fl::allocator<std::_fl::shared_ptr<impeller::CommandBuffer>>> const&, std::_fl::function<void (impeller::CommandBuffer::Status)> const&)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             impeller::FenceWaiterVK::AddFence(impeller::vk::UniqueHandle<impeller::vk::Fence, impeller::vk::detail::DispatchLoaderDynamic>, std::_fl::function<void ()> const&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/impeller/renderer/backend/vulkan/fence_waiter_vk.cc:0:14
                                                                                                                                             impeller::CommandQueueVK::Submit(std::_fl::vector<std::_fl::shared_ptr<impeller::CommandBuffer>, std::_fl::allocator<std::_fl::shared_ptr<impeller::CommandBuffer>>> const&, std::_fl::function<void (impeller::CommandBuffer::Status)> const&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc:72:49
#03 0x000000000085b95c /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::UnsafeUploadTextureToPrivate(std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::optional<SkImageInfo> const&)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             flutter::ImageDecoderImpeller::UnsafeUploadTextureToPrivate(std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::optional<SkImageInfo> const&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/lib/ui/painting/image_decoder_impeller.cc:394:36
#04 0x000000000085bc34 /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::__function::__func<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0, std::_fl::allocator<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0>, void ()>::operator()()+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0::operator()() const
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/lib/ui/painting/image_decoder_impeller.cc:439:17
                                                                                                                                             decltype(std::declval<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&>()()) std::_fl::__invoke[abi:nn210000]<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&>(flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:179:25
                                                                                                                                             void std::_fl::__invoke_void_return_wrapper<void, true>::__call[abi:nn210000]<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&>(flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:251:5
                                                                                                                                             void std::_fl::__invoke_r[abi:nn210000]<void, flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&>(flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:273:10
                                                                                                                                             std::_fl::__function::__alloc_func<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0, std::_fl::allocator<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0>, void ()>::operator()[abi:nn210000]()
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__functional/function.h:167:12
                                                                                                                                             std::_fl::__function::__func<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0, std::_fl::allocator<flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)::$_0>, void ()>::operator()()
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__functional/function.h:319:10
#05 0x00000000004d0678 /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             std::_fl::function<void ()>::operator()() const
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__functional/function.h:995:10
                                                                                                                                             fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/fml/synchronization/sync_switch.cc:0:0
#06 0x000000000085af58 /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             flutter::ImageDecoderImpeller::UploadTextureToPrivate(std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)>, std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<impeller::DeviceBuffer> const&, SkImageInfo const&, std::_fl::shared_ptr<SkBitmap> const&, std::_fl::optional<SkImageInfo> const&, std::_fl::shared_ptr<fml::SyncSwitch const> const&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/lib/ui/painting/image_decoder_impeller.cc:433:24
#07 0x000000000085acc8 /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const::'lambda'()::operator()() const+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const::'lambda'()::operator()() const
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/lib/ui/painting/image_decoder_impeller.cc:571:11
#08 0x000000000085ab7c /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (std::_fl::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1, std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1>, void ()>::operator()()+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/lib/ui/painting/image_decoder_impeller.cc:584:11
                                                                                                                                             decltype(std::declval<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&>()()) std::_fl::__invoke[abi:nn210000]<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&>(flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:179:25
                                                                                                                                             void std::_fl::__invoke_void_return_wrapper<void, true>::__call[abi:nn210000]<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&>(flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:251:5
                                                                                                                                             void std::_fl::__invoke_r[abi:nn210000]<void, flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&>(flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:273:10
                                                                                                                                             std::_fl::__function::__alloc_func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1, std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1>, void ()>::operator()[abi:nn210000]()
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__functional/function.h:167:12
                                                                                                                                             std::_fl::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1, std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1>, void ()>::operator()()
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__functional/function.h:319:10
#09 0x00000000004cce54 /data/app/~~j_BaO3AUJWtRqguH9Uir4Q==/io.invideo.ai-zfElDgPhstAGEmSY4MXn0A==/split_config.arm64_v8a.apk!libflutter.so (void* std::_fl::__thread_proxy[abi:nn210000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>>(void*)+48807936) (BuildId: ca2f3afc99b842cc15c38420405f8254e71901d6)
                                                                                                                                             fml::ConcurrentMessageLoop::WorkerMain()
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/fml/concurrent_message_loop.cc:0:7
                                                                                                                                             fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0::operator()() const
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/fml/concurrent_message_loop.cc:20:7
                                                                                                                                             decltype(std::declval<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>()()) std::_fl::__invoke[abi:nn210000]<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0&&)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__type_traits/invoke.h:179:25
                                                                                                                                             void std::_fl::__thread_execute[abi:nn210000]<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>&, std::_fl::__tuple_indices<...>)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__thread/thread.h:200:3
                                                                                                                                             void* std::_fl::__thread_proxy[abi:nn210000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>>(void*)
                                                                                                                                             out/ci/android_release_arm64/../../../flutter/third_party/libcxx/include/__thread/thread.h:209:3
#10 0x00000000000f4510 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
#11 0x000000000008ef34 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

```

**Comment by arlakay** [comment]
i have similiar issue, because of third party library.
my go to step is, check dependencies that use native libs (example in my cases webrtc, mlkit, opencv)
remove 1 by 1 alternately, and try to run using --release mode.
I hope this helps

**Comment by jason-simmons** [comment]
This should be fixed by https://github.com/flutter/flutter/commit/2831e61a9dfd9d7845e1c45480ed0bc9e134 

The issue fixed by that commit matches the stack traces seen above.

**Comment by iampawan** [comment]
Also receiving a similar crash from a long time. I have also disabled Impeller though. Tried Flutter version 3.27.4, 3.29.2 and now 3.32.8

```********** Crash dump: **********
#00 0x00000000004b2bfc /data/app/~~YLRxm8rfS8-ShOn0H_WpQw==/com.radio.pocketfm--5R_olxR9CMsdTXFyLr8iQ==/split_config.arm64_v8a.apk!libflutter.so (flutter::AttachJNI(_JNIEnv*, _jclass*, _jobject*)+474) (BuildId: fe6a2478b3359b3e92f9c4f6ebb12f6dc34712c2)
#01 0x0000000000d5893c /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+124)
#02 0x000000000068a4a0 /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #03  pc 0x0000000000351830  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#03 0x0000000000351830 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#04 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #05  pc 0x000000000035197a  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#05 0x000000000035197a /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#06 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #07  pc 0x0000000000351256  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#07 0x0000000000351256 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#08 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #09  pc 0x00000000003510e4  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#09 0x00000000003510e4 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#10 0x000000000068ab48 /apex/com.android.art/lib64/libart.so (nterp_helper+5720)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #11  pc 0x00000000003509de  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#11 0x00000000003509de /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#12 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #13  pc 0x0000000000350956  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#13 0x0000000000350956 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#14 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #15  pc 0x0000000000342e10  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#15 0x0000000000342e10 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#16 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #17  pc 0x00000000003424ee  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#17 0x00000000003424ee /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#18 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #19  pc 0x0000000000343968  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#19 0x0000000000343968 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#20 0x000000000068a444 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
WARNING:ndkstack:Frame has no file name or container offset, cannot find symbols:   #21  pc 0x0000000000336808  /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#21 0x0000000000336808 /data/app/~~EAsAWjTusb1cSX4BkMTngA==/com.radio.pocketfm-iO-3I2YvM_VQODyoUPzdAA==/base.apk
#22 0x000000000086299c /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Activity.performCreate+892)
#23 0x00000000005dda00 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Instrumentation.callActivityOnCreate+80)
#24 0x00000000006bc5bc /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.performLaunchActivity+5484)
#25 0x00000000006c4fd8 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleLaunchActivity+1048)
#26 0x000000000087053c /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.LaunchActivityItem.execute+364)
#27 0x0000000000610ca0 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.executeCallbacks+1312)
#28 0x000000000061057c /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.execute+1164)
#29 0x00000000006a2284 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+1524)
#30 0x00000000008d2518 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+152)
#31 0x00000000008d59a8 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+1048)
#32 0x00000000008d54f4 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+916)
#33 0x00000000006ba43c /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+3228)
#34 0x0000000000328460 /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
#35 0x00000000003224a0 /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+544)
#36 0x00000000005c5af8 /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32)
#37 0x0000000000d598f4 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
#38 0x0000000000b99ae8 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+120)
#39 0x0000000000ba36f8 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3160)
#40 0x0000000000328460 /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
#41 0x0000000000327098 /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+800)
#42 0x000000000064a850 /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156)
#43 0x00000000000becd8 /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+104)
#44 0x00000000000cabd8 /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+840)
#45 0x0000000000002560 /system/bin/app_process64 (main+1280)
#46 0x0000000000084dc0 /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96)```

**Comment by tirth-patel-nc** [comment]
According to [this comment](https://github.com/flutter/flutter/issues/171691#issuecomment-3161563122), the issue should now be resolved. Please try this if you're able.

**Comment by littleGnAl** [comment]
We’re also seeing this crash in production; could this fix (https://github.com/flutter/flutter/commit/2831e61a9dfd9d7845e1c45480ed0bc9e134) be cherry-picked into the 3.32.x stable branch?

**Comment by gaaclarke** [comment]
I'm closing this issue since it is fixed on `main`.  I'll pose the question to @jtmcdole if we'd like to cherry-pick this.  The commit has a test and seems good to me.  Any PR dealing with threading comes with an inherent risk though.

**Comment by nottmey** [comment]
Yes, cherry-picking this into 3.35.x would help immensely @jtmcdole, thank you!

We have 3.35.1 in production, and this issue is still our main crash event type. (first row)

<img width="1637" height="366" alt="Image" src="https://github.com/user-attachments/assets/60141ddb-4e17-4184-a776-1c2a962f6fd9" />

**Comment by jtmcdole** [comment]
Looking at cherry picking.
