### ISSUE TITLE
Suggestions are including example directory whenever doing dry run before publishing package

### ISSUE THREAD

**Issue by MarkOSullivan94** [flutter/flutter#17168]
I think the suggestions provided after doing a dry run should probably ignore the example directory. I don't think the suggestions in my case are necessary as I believe a good example would be to have a basic app to allow users to quickly test out the functionality of updating the launcher icons.

## Steps to Reproduce

Added an example directory for my Flutter package, went to do a dry run and it's now providing suggestions based on the example directory.

`flutter packages pub publish --dry-run`

## Logs

This is the suggestions provided

```
Suggestions:
* line 7, column 1 of example/test/widget_test.dart: This package doesn't depend on flutter.
  import 'package:flutter/material.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 8, column 1 of example/test/widget_test.dart: This package doesn't depend on flutter_test.
  import 'package:flutter_test/flutter_test.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 10, column 1 of example/test/widget_test.dart: This package doesn't depend on example.
  import 'package:example/main.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 1, column 1 of example/lib/main.dart: This package doesn't depend on flutter.
  import 'package:flutter/material.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by MarkOSullivan94** [comment]
Can be found here: https://github.com/franzsilva/flutter_launcher_icons

**Comment by goderbauer** [comment]
I believe the problem here is that the analyzer as used by pub doesn't deal properly with the nested packages `example` inside of another package (here: `flutter_launcher_icons`). I filed a bug for this over on Dart's github, but I cannot find it now :(

/cc @devoncarew

**Comment by devoncarew** [comment]
I believe these errors are coming directly from pub (/cc @nex3, @munificent) and not necessarily the analyzer. It seems like pub is validating that the import's in your code don't step outside what you define in your pubspec, but is not expecting that there's a nested sample that defines it's own pubspec.

**Comment by devoncarew** [comment]
If that's the case, perhaps it could stop traversing looking for import issues when it finds a sub dir that contains a pubspec file.

**Comment by zoechi** [comment]
Looks similar to #10015 which was closed in May.
#100001 looks like a dup.

**Comment by shyandsy** [comment]
i got same issue for my plugin test code

example/test/widget_test.dart

https://github.com/shyandsy/cipher2/blob/master/example/test/widget_test.dart

**Comment by zoechi** [comment]
I think this should be reported in https://github.com/dart-lang/pub/issues instead to get more attention

**Comment by diegoperini** [comment]
This complicates scripting CI stuff due to bad status code (65 instead of 0) after `flutter packages pub publish --dry-run`.

**Comment by GAM3RG33K** [comment]
Mine is stuck at suggestions for hours. All I can do is terminate.
I used two commnds to test the plugin's publishing with dry-run flag.

Here is the output on console (only suggestion part is presented here) :
1) issue: Does not stop execution
command: `flutter pub publish -dry-run`
log file: 
[command_logcat_1.txt](https://github.com/flutter/flutter/files/3317634/command_logcat_1.txt)

2) issue: Completes execution with exit code 65 as described by @diegoperini 
command: ` flutter packages pub publish --dry-run`
log file: 
[command_logcat_2.txt](https://github.com/flutter/flutter/files/3317633/command_logcat_2.txt)

**Comment by mit-mit** [comment]
I cannot repro this. @MarkOSullivan94 @alextekartik @diegoperini are you still seeing this?

@GAM3RG33K that sounds like a very different issue. If you are still seeing that, please file a new bug.

**Comment by wuxj** [comment]
i got same issue for my plugin test code

[https://github.com/wuxj/flutter_plugin_xgpush/blob/master/example/test/widget_test.dart](url)

**Comment by mit-mit** [comment]
@wuxj I cannot seem to repro that:

```
$ cd flutter_plugin_xgpush-master/
| ~/tmp/flutter_plugin_xgpush-master @ mit-macbookpro3 (mit)
$ flutter pub pub publish --dry-run
Publishing flutter_plugin 0.0.1 to https://pub.dartlang.org:
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- android
|   |-- build.gradle
...
|-- example
|   |-- README.md
|   |-- android
|   |   |-- app
...
|-- pubspec.yaml
'-- test
    '-- flutter_plugin_test.dart

Package has 0 warnings.
| ~/tmp/flutter_plugin_xgpush-master @ mit-macbookpro3 (mit)
```

**Comment by diegoperini** [comment]
@mit-mit Me neither, I don't remember how many times I updated my flutter installation after my last comment.

**Comment by mit-mit** [comment]
OK, I believe this is resolved by now, so I'll close this issue. If anyone gets a repro, ping us and we can re-open it.

**Comment by MarkOSullivan94** [comment]
@mit-mit still seeing this

```
me@my-machine:flutter_launcher_icons master 0m ➜ pub publish --dry-run                      
Publishing flutter_launcher_icons 0.7.3 to https://pub.dartlang.org:
|-- .gitignore
|-- .travis.yml
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- bin
|   '-- main.dart
|-- example
|   |-- .DS_Store
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       '-- main
|   |   |           |-- AndroidManifest.xml
|   |   |           |-- java
|   |   |           |   |-- com
|   |   |           |   |   '-- example
|   |   |           |   |       '-- example
|   |   |           |   |           '-- MainActivity.java
|   |   |           |   '-- io
|   |   |           |       '-- flutter
|   |   |           |           '-- plugins
|   |   |           |               '-- GeneratedPluginRegistrant.java
|   |   |           '-- res
|   |   |               |-- drawable
|   |   |               |   '-- launch_background.xml
|   |   |               |-- mipmap-hdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-mdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xxhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xxxhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               '-- values
|   |   |                   '-- styles.xml
|   |   |-- build.gradle
|   |   |-- gradle
|   |   |   '-- wrapper
|   |   |       |-- gradle-wrapper.jar
|   |   |       '-- gradle-wrapper.properties
|   |   |-- gradle.properties
|   |   |-- gradlew
|   |   |-- gradlew.bat
|   |   |-- local.properties
|   |   '-- settings.gradle
|   |-- assets
|   |   |-- .DS_Store
|   |   '-- images
|   |       |-- background-test.png
|   |       |-- christmas-background.png
|   |       |-- ic_launcher.png
|   |       |-- icon-1024x1024.png
|   |       |-- icon-128x128.png
|   |       |-- icon-710x599-android.png
|   |       |-- icon-710x599-ios.png
|   |       |-- icon-710x599.png
|   |       '-- icon-foreground-432x432.png
|   |-- example.iml
|   |-- example_android.iml
|   |-- ios
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- AppFrameworkInfo.plist
|   |   |   |-- Debug.xcconfig
|   |   |   |-- Generated.xcconfig
|   |   |   |-- Release.xcconfig
|   |   |   '-- flutter_export_environment.sh
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   |-- AppIcon.appiconset
|   |   |   |   |   |-- Contents.json
|   |   |   |   |   |-- Icon-App-1024x1024@1x.png
|   |   |   |   |   |-- Icon-App-20x20@1x.png
|   |   |   |   |   | (10 more...)
|   |   |   |   |   |-- Icon-App-76x76@1x.png
|   |   |   |   |   |-- Icon-App-76x76@2x.png
|   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
|   |   |   |   '-- LaunchImage.imageset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- LaunchImage.png
|   |   |   |       |-- LaunchImage@2x.png
|   |   |   |       |-- LaunchImage@3x.png
|   |   |   |       '-- README.md
|   |   |   |-- Base.lproj
|   |   |   |   |-- LaunchScreen.storyboard
|   |   |   |   '-- Main.storyboard
|   |   |   |-- GeneratedPluginRegistrant.h
|   |   |   |-- GeneratedPluginRegistrant.m
|   |   |   |-- Info.plist
|   |   |   '-- Runner-Bridging-Header.h
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   '-- contents.xcworkspacedata
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       '-- contents.xcworkspacedata
|   |-- lib
|   |   '-- main.dart
|   '-- pubspec.yaml
|-- lib
|   |-- android.dart
|   |-- constants.dart
|   |-- custom_exceptions.dart
|   |-- ios.dart
|   |-- main.dart
|   '-- xml_templates.dart
|-- pubspec.yaml
'-- test
    |-- android_test.dart
    |-- config
    |   '-- test_pubspec.yaml
    '-- main_test.dart
Suggestions:
* line 1, column 1 of example/lib/main.dart: This package doesn't depend on flutter.
    ╷
  1 │ import 'package:flutter/material.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
* line 5, column 1 of test/main_test.dart: This package doesn't depend on path.
    ╷
  5 │ import 'package:path/path.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵

Package has 2 warnings.
```

Updated my Flutter version before trying

```
Flutter 1.9.7 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 4984d1a33d (6 days ago) • 2019-08-28 17:04:07 -0700
Engine • revision f52c0b9270
Tools • Dart 2.5.0
```

**Comment by mit-mit** [comment]
@MarkOSullivan94 and your code in `/example` does or doesn't depend on those imports? What happens if you remove them?
