### ISSUE TITLE
SVG radialGradient with negative cx and gradientTransform matrix fails to render correctly after Flutter upgrade

### ISSUE THREAD

**Issue by guoxz** [flutter/flutter#171854]
### Steps to reproduce

1. Create a Flutter project with the [`flutter_svg`](https://pub.dev/packages/flutter_svg) package.
2. Add an SVG asset that includes a <radialGradient> with:
    a negative cx value.
    a gradientTransform="matrix(...)".

Run on Flutter 3.29.1 or later.

### Expected results

The rectangle is filled with a radial gradient, rendered correctly regardless of the negative cx.

### Actual results

The gradient is not rendered incorrectly  but it was ok with flutter 3.27.0

### Code sample

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(body: Center(child: GradientExample())),
    );
  }
}

class GradientExample extends StatefulWidget {
  const GradientExample({super.key});

  @override
  State<GradientExample> createState() => _GradientExampleState();
}

class _GradientExampleState extends State<GradientExample> {
  @override
  Widget build(BuildContext context) {
    final svgString = '''
 <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
     <defs>
       <radialGradient id="myGradient"
         cx="-50"
         cy="100"
         r="80"
         gradientTransform="matrix(0,1,2.0,0,40,300)">
         <stop offset="0%" stop-color="red" />
         <stop offset="100%" stop-color="blue" />
       </radialGradient>
     </defs>
     <rect x="0" y="0" width="400" height="400" fill="url(#myGradient)" />
   </svg>

''';

    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        SvgPicture.string(
          svgString,
          height: 240,
          width: 240,
          allowDrawingOutsideViewBox: true,
        ),
        const SizedBox(height: 20),
      ],
    );
  }
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.29.1, on macOS 15.4.1 24E263 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 16.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.100.2)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by darshankawar** [comment]
@guoxz 
Running on latest stable (3.32.5) and passing cx value as -10, it shows me as below:

<img width="930" height="455" alt="Image" src="https://github.com/user-attachments/assets/76e9a13c-33f3-41bd-9c12-b2072430c61e" />

If I have it as-is (ie, -50), then it does show but not fully, but at the edge of the border. If you are passing negative x axis value, then it will bound to go beyond the border. 

How was it in earlier versions ?

**Comment by guoxz** [comment]
Sure, thanks for checking!

To avoid rendering inconsistencies across Flutter versions, we are now using the following simplified SVG:

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 340 255" opacity="0.6">
  <defs>
    <radialGradient id="boxGradient" cx="-520" cy="35" r="70"
      gradientTransform="matrix(0, 1, 2.9, 0, 55, 570)" gradientUnits="userSpaceOnUse">
      <stop offset="0.15" stop-color="#8B98C7"/>
      <stop offset="0.85" stop-color="#8B98C7" stop-opacity="0.02"/>
    </radialGradient>
  </defs>
  <path d="M40,60 L300,50 L290,190 L50,200 Z" fill="url(#boxGradient)"/>
</svg>
```

This version still uses a negative `cx` and matrix transform, but applies a simplified, abstract shape. We found this renders more consistently across recent Flutter versions.

### 📷 Comparison

Here are screenshots for reference:

* **Flutter 3.22.3**


![Image](https://github.com/user-attachments/assets/3f64f144-67d2-487c-bd98-d7360b5c4b16)

* **Flutter 3.29.3**

![Image](https://github.com/user-attachments/assets/487a0aea-7004-4f83-9c76-ce29e05ee1c0)


If you look closely at the Flutter 3.29.3 screenshot, the shape is rendered — it's just extremely faint due to the gradient rendering behavior. That’s another reason we decided to simplify the design for more reliable results.
---

**Comment by darshankawar** [comment]
> To avoid rendering inconsistencies across Flutter versions, we are now using the following simplified SVG:

Does this mean the issue is resolved and can be closed ?

**Comment by guoxz** [comment]
Thank you for the follow-up.

The issue is not resolved yet. It’s now quite clear that newer versions of Flutter have trouble properly rendering SVGs that use a negative cx value along with a matrix in gradientTransform.

The correct rendering—when viewed in a browser or using Flutter 3.22.3—should look like the screenshot from version 3.22.3. However, in the latest versions, the display is noticeably incorrect.

**Comment by darshankawar** [comment]
Thanks for the update. With the updated svg and running with latest stable and master versions, seeing the same behavior as reported.

```
stable : 3.32.5
master : 3.33.0-1.0.pre.905
```

**Comment by jason-simmons** [comment]
This is a side effect of how https://github.com/flutter/engine/commit/62cb2c9ee7e88163344d38dd8e5ad3a260658d9f changed the handling of matrices passed to the engine's Dart gradient construction APIs.

The Dart API expects a 4x4 matrix represented as a list of 16 values.  Previously this list was passed to `ToSkMatrix`, which would construct a 3x3 `SkMatrix` from a subset of the input.  Later, when the 3x3 `SkMatrix` is converted to a 4x4 `DlMatrix` the 10th element representing the z-axis scale is set to 1.0.

With https://github.com/flutter/engine/commit/62cb2c9ee7e88163344d38dd8e5ad3a260658d9f the input list is directly converted into a 4x4 matrix.  The list provided by the SVG parser sets the 10th element to zero, resulting in different output.

This could be fixed by changing the SVG parser to pass 1.0 as the `m4_10` value when constructing the `AffineMatrix`
(https://github.com/flutter/packages/blob/main/packages/vector_graphics_compiler/lib/src/svg/parsers.dart#L96)

@flar

**Comment by flar** [comment]
@jason-simmons is correct in that the matrices maintained by the SVG library were not valid 4x4 matrices despite being converted to 4x4 when interacting with some of the Flutter/Dart APIs. I think this could also be handled inside the AffineMatrix class itself which maintains that `m4_10` value as a work-around for dealing with abbreviated matrix storage. It's not clear the handling is always accurate (for instance, when scaling by x,y scale factors, it [applies the X scale to that value](https://github.com/flutter/packages/blob/09533b7d5d66b66b75b43ec89c116312838f94a7/packages/vector_graphics_compiler/lib/src/geometry/matrix.dart#L109) which is representing a Z scale and it isn't clear what that is trying to accomplish?).

Perhaps the AffineMatrix 6-valued constructor should default the m4_10 value to 1 instead of the `a` value (I think it is trying to set the Z scale to the same as the X scale which is usually stored in the `a` value, but it won't be represented there if there is any rotation present at all - and even if it was scaled, "Z scale == A scale" isn't a very valid default).

**Comment by flar** [comment]
It looks like the `m4_10` default value was initially 1.0 as I suggest above and was changed to be equal to the upper-left matrix value (the X scale value) in this commit: https://github.com/flutter/packages/commit/542f437a32cadf21e7edec869b676698ab86258b (the first change in that diff).

**Comment by flar** [comment]
@jason-simmons patched the vector_graphics_compiler package to fix this issue, upgrading it to v1.1.18 in doing so.

If the developers reporting this issue could upgrade to this version of the package and verify that it solves your particular test case, we should be able to retire this issue - thanks in advance!
