### ISSUE TITLE
Light status bar with dark icons

### ISSUE THREAD

**Issue by kalehv** [flutter/flutter#17231]
This is not really an issue but a question about how to do it in flutter.
I asked this question on SO but didn't get any answers.
https://stackoverflow.com/questions/49179175/how-to-make-android-status-bar-light-in-flutter

I want to change the status bar to light on Android which automatically turns icons dark. This was introduced in Android v23 with `<item name="android:windowLightStatusBar">true</item>`.

Please note that my question is NOT about changing status bar color or about removing translucency. I know how to do all that. I just want to change the color of icons which in Android is possible with `windowLightStatusBar` property. 

Check image below for reference.

![xnvg8](https://user-images.githubusercontent.com/588703/39557171-81144378-4e3a-11e8-9922-004d722fbcfe.png)

**Comment by jonahwilliams** [comment]
Hi @kalehv, right now flutter doesn't expose the necessary API to configure the status bar or other parts of the system chrome for Android.  I'm working on a PR to add the low level functionality in the engine here: https://github.com/flutter/flutter/pull/17171 - this should be done fairly soon!

After that I'll also need to update the framework and make a breaking change to the AppBar so that the low level API is useable - this will take a bit longer.

**Comment by zoechi** [comment]
I assume this was fixed by #17171

**Comment by miikaeru** [comment]
During launch in splash screen the status and navigation bar still can't be set to the light mode. Changing the appearance after the splash screen is not desirable and interrupts the user experience. Why is it not possible to change the mode with `<item name="android:windowLightStatusBar">true</item>` in the main activtiy?

**Comment by Mhamza007** [comment]
For making status bar transparent. In main.dart add

`Future<void> main() async {
  SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
    ),
  );
  ...
}
`


Then in appbar add this
`return AppBar(
  brightness: Brightness.light,
  ...
)`

Hope it helps
