### ISSUE TITLE
[Xcode 26 beta 4] Xcode reports `Could not extract value, error: No value at that key path or invalid key path` for some keys when running on iOS

### ISSUE THREAD

**Issue by danagbemava-nc** [flutter/flutter#172627]
### Steps to reproduce

1. Use Xcode 26 beta 4
2. Create a new flutter app on either stable, beta or master
3. Run the app on iOS

### Expected results

Xcode doesn't report missing keys in the logs

### Actual results

Xcode reports missing keys in the logs. The app still launches, however, sometimes I cannot debug the app. After the application launches, the app just closes with this message. 

```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:64581/WJVUsMFhG58=/
HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:64581/WJVUsMFhG58=/ws
```

I tested on iOS 18.6 and iOS 26 and on both devices, I see the message in the logs section below. (Error added below for brevity). 

The error goes away when I add the respective entitlements. I tested with this by adding the  `NSLocalNetworkUsageDescription` key and the error went away. I didn't test `NSBonjourServices` (this I believe is an array, and I wasn't sure which options would apply in our case). However, I believe when we add the right options for the `NSBonjourServices`, the error should go away . This does not happen with Xcode 26 beta 3. 

When running on the stable channel, the error is not surfaced in `flutter run`. It is surfaced when you run `flutter run -v`. 

```
error: /Users/deanli/projects/QA-Manual/creation/beta4/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could
not extract value, error: No value at that key path or invalid key path: NSBonjourServices
error: /Users/deanli/projects/QA-Manual/creation/beta4/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could
not extract value, error: No value at that key path or invalid key path: NSLocalNetworkUsageDescription
```

### Code sample

The counter app should suffice for this (added below)

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

N/A

### Logs

[ios26.log](https://github.com/user-attachments/files/21384437/ios26.log)

[ios18_6.log](https://github.com/user-attachments/files/21384440/ios18_6.log)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.7, on macOS 26.0 25A5316i darwin-arm64, locale en-US) [824ms]
    • Flutter version 3.32.7 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7b523b356 (7 days ago), 2025-07-15 17:03:46 -0700
    • Engine revision 39d6d6e699
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.5s]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [1,523ms]
    • Xcode at /Applications/Xcode-26.0.0-Beta.4.app/Contents/Developer
    • Build 17A5285i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [13ms]
    • Android Studio at /Users/deanli/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.102.1) [11ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (4 available) [12.6s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5297i
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.5 22F76
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5316i darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 138.0.7204.159
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [2.2s]
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.33.0-1.0.pre-1078, on macOS 26.0 25A5316i darwin-arm64, locale en-US) [3.3s]
    • Flutter version 3.33.0-1.0.pre-1078 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision afba7d75b3 (7 hours ago), 2025-07-23 14:04:50 +1200
    • Engine revision afba7d75b3
    • Dart version 3.10.0 (build 3.10.0-15.0.dev)
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [1,462ms]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Emulator version 36.1.8.0 (build_id 13784423) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [980ms]
    • Xcode at /Applications/Xcode-26.0.0-Beta.4.app/Contents/Developer
    • Build 17A5285i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [5ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6.2s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5297i
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.5 22F76
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5316i darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 138.0.7204.159
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [831ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by vashworth** [comment]
I'm not able to recreate this. @danagbemava-nc Did it happen consistently for you or only sometimes? I wonder if it's a race condition

**Comment by MMALI3287** [comment]
My app runs but this errors are shown in the Xcode:

/Users/musaddique/Library/Developer/Xcode/DerivedData/Runner-dynupcibvywghwelpatdeebpbcww/Build/Products/Debug-iphoneos/Runner.app/Info.plist: Could not extract value, error: No value at that key path or invalid key path: NSBonjourServices

/Users/musaddique/Library/Developer/Xcode/DerivedData/Runner-dynupcibvywghwelpatdeebpbcww/Build/Products/Debug-iphoneos/Runner.app/Info.plist: Could not extract value, error: No value at that key path or invalid key path: NSLocalNetworkUsageDescription

Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

**Comment by danagbemava-nc** [comment]
> I'm not able to recreate this. @danagbemava-nc Did it happen consistently for you or only sometimes? I wonder if it's a race condition

Hi @vashworth, it happens consistently for me. It may not be visible in the console unless you run with the verbose flag in some cases. I just tested with master `3.33.0-1.0.pre-1099` to confirm and I see it with a new application I created there as well. I was able to reproduce this when running on the iOS simulator. 

PS: The app still runs as expected

**Comment by hellohuanlin** [comment]
CC @hellohuanlin to repro on Xcode beta 4

**Comment by hellohuanlin** [comment]
I just tried Xcode beta 4 with a beta 1 device, and I couldn't repro. let me update my device to beta 4 as well.

**Comment by hellohuanlin** [comment]
Update: I just updated my device to beta 4, and still not able to reproduce it. Labeling as "need repro info" for more detailed repro setups and steps @danagbemava-nc @vashworth

**Comment by danagbemava-nc** [comment]
Hi @hellohuanlin, I took another look at this and I realized there's one piece missing. It appears you need to be on the `macOS 26 beta` as well. I have another Mac running the beta 4 of Xcode but I can't reproduce this on that Mac. 
On my other Mac which is running macOS 26 beta 4 (at the time of writing), that is where I see the issue. 

Attaching logs from my Mac running macOS 15 and my Mac running macOS 26. 

[macOS 15](https://github.com/user-attachments/files/21462506/warn.log)

[macOS 26](https://github.com/user-attachments/files/21462577/bom.log)

**Comment by hellohuanlin** [comment]
> The error goes away when I add the respective entitlements. I tested on with NSLocalNetworkUsageDescription but I believe the same will apply when the NSBonjourServices key is added. 

Hi, @danagbemava-nc in the issue description, could you elaborate more? i am not sure if i follow (e.g. what is "the same will apply"? does the error still happen after adding `NSLocalNetworkUsageDescription`

**Comment by hellohuanlin** [comment]
> It appears you need to be on the macOS 26 beta as well. 

@vashworth also pointed out I needed macOS 26, so I tried it and was able to repro it. Sorry for the late update.

**Comment by vashworth** [comment]
@hellohuanlin 

Here's the place we extract / insert into the Info.plist

https://github.com/flutter/flutter/blob/7063ea19c41bd5419477d164ea1a1a3f5166cef5/packages/flutter_tools/bin/xcode_backend.dart#L389-L468

Here's where we add stderr to the to errorOutput, which we stream to the flutter tool:

https://github.com/flutter/flutter/blob/7063ea19c41bd5419477d164ea1a1a3f5166cef5/packages/flutter_tools/bin/xcode_backend.dart#L123-L140

**Comment by danagbemava-nc** [comment]
> i am not sure if i follow (e.g. what is "the same will apply"? does the error still happen after adding NSLocalNetworkUsageDescription

Hi @hellohuanlin, the description has been updated. TLDR,  the error goes away when I add `NSLocalNetworkUsageDescription`. The "same will apply" was to mean that the error would go away if we added the key and options for `NSBonjourServices`

**Comment by danagbemava-nc** [comment]
Hi @hellohuanlin, this doesn't appear to be fixed. I just tested on master `3.33.0-1.0.pre-1343` with the latest version of macOS 26beta, Xcode26beta and I still see it being reported. 


```console
deanli@Deans-MacBook-Pro master % fm run -d "iPhone 16 Pro Max"
Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
X8NNQ9CYL2
/Users/deanli/projects/master/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could not extract value,
error: No value at that key path or invalid key path: NSBonjourServices
/Users/deanli/projects/master/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could not extract value,
error: No value at that key path or invalid key path: NSLocalNetworkUsageDescription
Running Xcode build...                                                  
Xcode build done.                                           19.1s
Installing and launching...                                        14.8s
Syncing files to device iPhone 16 Pro Max...                       424ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 16 Pro Max is available at: http://127.0.0.1:54648/w0eNA17E3u0=/
The Flutter DevTools debugger and profiler on iPhone 16 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54648/w0eNA17E3u0=/


Application finished.
```

<details>
<summary>flutter doctor -v</summary>

```console
[!] Flutter (Channel master, 3.33.0-1.0.pre-1343, on macOS 26.0 25A5327h darwin-arm64, locale en-US)
    [4.6s]
    • Flutter version 3.33.0-1.0.pre-1343 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not
      inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding
      /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding
      /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1590543f67 (2 days ago), 2025-08-08 23:18:19 -0400
    • Engine revision d77a9629f2
    • Dart version 3.10.0 (build 3.10.0-81.0.dev)
    • DevTools version 2.49.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop,
      enable-android, enable-ios, cli-animations, enable-native-assets, enable-lldb-debugging
    • If those were intentional, you can disregard the above warnings; however it is recommended to use
      "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [4.4s]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Emulator version 36.1.8.0 (build_id 13784423) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [3.5s]
    • Xcode at /Applications/Xcode-26.0.0-beta.5.app/Contents/Developer
    • Build 17A5295f
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (5 available) [6.6s]
    • iPhone 16 Pro Max (mobile)      • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5308g
    • Nexus (wireless) (mobile)       • 00008020-001875E83A38002E • ios            • iOS 18.6 22G86
    • Dean’s iPad (wireless) (mobile) • 00008103-000825C811E3401E • ios            • iOS 26.0 23A5287g
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 26.0
      25A5327h darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome
      138.0.7204.185
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached
      with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1,331ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by hellohuanlin** [comment]
I just tried it out, Xcode doesn't fail the compilation anymore, since the error message doesn't start with "error: ". However, having seeing this message in the terminal is indeed confusing (for both stderr and stdout). I think we should just hide this message completely, since to our bonjour logic, not having the key is one of the expected state, which shouldn't be an error.

**Comment by hellohuanlin** [comment]
@danagbemava-nc Hi, this should be fixed. could you double check? Thank you!

**Comment by danagbemava-nc** [comment]
Hi @hellohuanlin, I still see it logged in the console without the verbose flag 

I tested with master `3.33.0-1.0.pre-1429` in a freshly created project

```console
Launching lib/main.dart on Dean’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
/Users/deanli/projects/stable/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could not extract value, error: No value at that key path or invalid
key path: NSBonjourServices
/Users/deanli/projects/stable/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could not extract value, error: No value at that key path or invalid
key path: NSLocalNetworkUsageDescription
Running Xcode build...
Xcode build done.                                           19.2s
Installing and launching...                                        16.8s
Syncing files to device Dean’s iPad...                             224ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Dean’s iPad is available at: http://127.0.0.1:55766/pAg8Lnd5cTk=/
The Flutter DevTools debugger and profiler on Dean’s iPad is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:55766/pAg8Lnd5cTk=/
```

```console
[!] Flutter (Channel master, 3.33.0-1.0.pre-1429, on macOS 26.0 25A5338b darwin-arm64, locale en-US) [3.4s]
    • Flutter version 3.33.0-1.0.pre-1429 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e076dd4e02 (78 minutes ago), 2025-08-15 01:25:44 -0400
    • Engine revision e076dd4e02
    • Dart version 3.10.0 (build 3.10.0-101.0.dev)
    • DevTools version 2.49.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.9s]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.7+-13880790-b1038.58)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [1,699ms]
    • Xcode at /Applications/Xcode-26.0.0-beta.5.app/Contents/Developer
    • Build 17A5295f
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [6ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (5 available) [11.1s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5318c
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.6 22G86
    • Dean’s iPad (mobile)                  • 00008103-000825C811E3401E • ios            • iOS 26.0 23A5318c
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5338b darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 139.0.7258.128
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1,213ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by hellohuanlin** [comment]
Hi @danagbemava-nc, could you please try out this patch? https://github.com/flutter/flutter/pull/174001 

Thank you!

**Comment by danagbemava-nc** [comment]
Hi @hellohuanlin, it looks like we're good to go. I tested on master `3.33.0-1.0.pre-1468` with and without the patch. The results are shared below 

<details>
<summary>without the patch</summary>

```console
fm run -d "iPhone 16 Pro Max"
Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
X8NNQ9CYL2
/Users/deanli/projects/stable/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could not extract value,
error: No value at that key path or invalid key path: NSBonjourServices
/Users/deanli/projects/stable/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could not extract value,
error: No value at that key path or invalid key path: NSLocalNetworkUsageDescription
Running Xcode build...                                                  
Xcode build done.                                           139.3s
Installing and launching...                                        17.9s
Syncing files to device iPhone 16 Pro Max...                       156ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 16 Pro Max is available at: http://127.0.0.1:64555/war4QCA611s=/
The Flutter DevTools debugger and profiler on iPhone 16 Pro Max is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:64555/war4QCA611s=/

Application finished.
```
</details>

<details>
<summary>with the patch</summary>

```console
fm run -d "iPhone 16 Pro Max"
Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
X8NNQ9CYL2
Running Xcode build...                                                  
Xcode build done.                                            7.0s
Installing and launching...                                        16.2s
Syncing files to device iPhone 16 Pro Max...                       187ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 16 Pro Max is available at: http://127.0.0.1:49172/1HnPNE4WrQc=/
The Flutter DevTools debugger and profiler on iPhone 16 Pro Max is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:49172/1HnPNE4WrQc=/

Application finished.
```
</details>
