### ISSUE TITLE
Flutter Engine build broken with latest Visual Studio components

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#172824]
It appears the latest MSVC C++ libraries v17.44 require Clang >= 19.0.0, while the clang toolchain the engine build comes bundled with is currently version 18.

**Reproduction**
1. Install latest MSVC C++ libraries & buildtools in Visual Studio Installer (`14.44-17.14`)
2. ```cmd
    git clone --depth 1 https://github.com/flutter/flutter.git flutter-build-issue-repro
    cd flutter-build-issue-repro
    copy flutter-build-issue-repro\engine\scripts\standard.gclient .gclient
    gclient sync --no-history --shallow
    engine\src\flutter\tool\gn
    ninja -C engine\src\out\host_debug
    ```

**Output**
```
. . .
[79/6682] CXX obj/flutter/shell/platform/common/client_wrapper/client_wrapper.core_implementations.obj
FAILED: obj/flutter/shell/platform/common/client_wrapper/client_wrapper.core_implementations.obj
../../flutter/buildtools/windows-x64/clang/bin/clang-cl.exe /c ../../flutter/shell/platform/common/client_wrapper/core_implementations.cc /Foobj/flutter/shell/platform/common/client_wrapper/client_wrapper.core_implementations.obj  /nologo /showIncludes:user "-imsvc../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include" "-imsvc../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/ATLMFC/include" "-imsvc../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/VS/include" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/um" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/shared" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/winrt" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/cppwinrt" -DUSE_OPENSSL=1 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DNTDDI_VERSION=0x06030000 -DPSAPI_VERSION=1 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -D_UNICODE -DUNICODE -D_WIN32_WINNT=0x0603 -DWINVER=0x0603 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DFLUTTER_DESKTOP_LIBRARY -I../.. -Igen -I../../flutter/shell/platform/common/public /GS /FS /guard:cf -m64 -fcolor-diagnostics /wd4091 /wd4722 /wd4312 /wd4838 /wd4172 /wd4005 /wd4311 /wd4477 -Wno-ignored-pragma-optimize -Wno-unqualified-std-cast-call -Wno-deprecated-literal-operator /MT -Wstring-conversion -Wnewline-eof /O1 /Ob2 /Oy- /Gw /Oi /Zi /std:c++17 /GR- /Fd"obj/flutter/shell/platform/common/client_wrapper/client_wrapper_cc.pdb"
In file included from ../../flutter/shell/platform/common/client_wrapper/core_implementations.cc:16:
In file included from ../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include\cassert:7:
../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include\yvals_core.h(908,1): error: static assertion failed: error STL1000: Unexpected compiler version, expected Clang 19.0.0 or newer.
  908 | _EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 19.0.0 or newer.");
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include\yvals_core.h(534,58): note: expanded from macro '_EMIT_STL_ERROR'
  534 | #define _EMIT_STL_ERROR(NUMBER, MESSAGE)   static_assert(false, "error " #NUMBER ": " MESSAGE)
      |                                                          ^~~~~
1 error generated.
[80/6682] CXX obj/flutter/shell/platform/common/client_wrapper/client_wrapper.standard_codec.obj
FAILED: obj/flutter/shell/platform/common/client_wrapper/client_wrapper.standard_codec.obj
../../flutter/buildtools/windows-x64/clang/bin/clang-cl.exe /c ../../flutter/shell/platform/common/client_wrapper/standard_codec.cc /Foobj/flutter/shell/platform/common/client_wrapper/client_wrapper.standard_codec.obj  /nologo /showIncludes:user "-imsvc../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include" "-imsvc../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/ATLMFC/include" "-imsvc../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/VS/include" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/um" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/shared" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/winrt" "-imsvc../../../../../../../../Program Files (x86)/Windows Kits/10/include/10.0.22621.0/cppwinrt" -DUSE_OPENSSL=1 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DNTDDI_VERSION=0x06030000 -DPSAPI_VERSION=1 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -D_UNICODE -DUNICODE -D_WIN32_WINNT=0x0603 -DWINVER=0x0603 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DFLUTTER_DESKTOP_LIBRARY -I../.. -Igen -I../../flutter/shell/platform/common/public /GS /FS /guard:cf -m64 -fcolor-diagnostics /wd4091 /wd4722 /wd4312 /wd4838 /wd4172 /wd4005 /wd4311 /wd4477 -Wno-ignored-pragma-optimize -Wno-unqualified-std-cast-call -Wno-deprecated-literal-operator /MT -Wstring-conversion -Wnewline-eof /O1 /Ob2 /Oy- /Gw /Oi /Zi /std:c++17 /GR- /Fd"obj/flutter/shell/platform/common/client_wrapper/client_wrapper_cc.pdb"
In file included from ../../flutter/shell/platform/common/client_wrapper/standard_codec.cc:10:
In file included from ../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include\cassert:7:
../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include\yvals_core.h(908,1): error: static assertion failed: error STL1000: Unexpected compiler version, expected Clang 19.0.0 or newer.
  908 | _EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 19.0.0 or newer.");
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include\yvals_core.h(534,58): note: expanded from macro '_EMIT_STL_ERROR'
  534 | #define _EMIT_STL_ERROR(NUMBER, MESSAGE)   static_assert(false, "error " #NUMBER ": " MESSAGE)
      |                                                          ^~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by darshankawar** [comment]
The error is also stated in [this](https://github.com/flutter/flutter/issues/172335#issuecomment-3090291698) issue comment with a possible root-cause and a potential solution.

**Comment by ardera** [comment]
> The error is also stated in [this](https://github.com/flutter/flutter/issues/172335#issuecomment-3090291698) issue comment with a possible root-cause and a potential solution.

Ahh good!

FWIW, after spending some time unsuccessfully trying to downgrade MSVC, I'm currently working around using this patch:
[0010-Windows-Allow-configuring-VC-compiler-toolset-versio.patch](https://github.com/user-attachments/files/21468630/0010-Windows-Allow-configuring-VC-compiler-toolset-versio.patch)
And then manually specifying `--gn-args=vc_version="14.42"` in the `gn` invocation. (`14.44` is the non-working version, which is auto-selected by default) I suspect it's incomplete, but at least it makes the build go through for now.

**Comment by chinmaygarde** [comment]
@jason-simmons is in the middle of doing a clang roll.

**Comment by gaaclarke** [comment]
This was fixed in https://github.com/flutter/flutter/pull/173429, thanks jason.

**Comment by Stumblinbear** [comment]
I'm still receiving the same error on `3.35.3`. I'm uncertain if any additional changes need to be made on my end other than a pull, sync, and build. Checking `engine/src/flutter/buildtools/windows-x64/clang/bin/clang.exe` seems to still be `18.0.0`. Has it not yet been included in a release?
