### ISSUE TITLE
Cocoon device_doctor build is failing

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#173240]
### Help us understand the severity of this issue

- [x] breakage; unable to contribute or trigger builds will no workarounds
- [ ] inconvenient workarounds exist, but significant effort required
- [ ] needed for a Flutter team-wide priority (already agreed upon)
- [ ] nice-to-have; none of the above

### What do you need help with

```
[P79540 11:28:02.323 client.go:2190 I] All changes applied.
/Volumes/Work/s/w/ir/x/w/cocoon/cipd_packages/device_doctor /Volumes/Work/s/w/ir/x/w/cocoon/cipd_packages/device_doctor
/Volumes/Work/s/w/ir/x/w/cocoon/cipd_packages/device_doctor
LICENSE
README
bin
build.bat
build.sh
dartdoc_options.yaml
ensure_file
ensure_file_windows
include
infra-dialog
lib
revision
sdk_packages.yaml
version
/Volumes/Work/s/w/ir/x/w/cocoon/cipd_packages/device_doctor/tool/build.sh: line 38: 79552 Killed: 9               tool/bin/dart pub get
```

https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20device_doctor/173/overview

It appears that [cocoon use's the `dev` build](https://github.com/flutter/cocoon/blob/ec38a33c59573202849e8d08323a0bd38a58804f/cipd_packages/device_doctor/tool/ensure_file#L3) of the Dart SDK. The dev build is currently broken: https://github.com/dart-lang/sdk/issues/61235. I believe this is what is causing the build to fail.

**Comment by jtmcdole** [comment]
Thanks for spotting.  I thought there were two device_doctors installed, one staging and one presumably not.

**Comment by aam** [comment]
Two recipe changes landed towards fixing this issue:
- https://dart-review.googlesource.com/c/recipes/+/443480
- https://dart-review.googlesource.com/c/recipes/+/444140

We should confirm that the issue is resolved now with those recipe changes.

**Comment by vashworth** [comment]
> Two recipe changes landed towards fixing this issue:
> 
> * https://dart-review.googlesource.com/c/recipes/+/443480
> * https://dart-review.googlesource.com/c/recipes/+/444140
> 
> We should confirm that the issue is resolved now with those recipe changes.

I don't think this will be fixed until a new release is made to the `dev` channel.

I verified the device_doctor build is still failing.

**Comment by aam** [comment]
Deduping this to https://github.com/dart-lang/sdk/issues/61235

**Comment by aam** [comment]
Reopening until new release actually happens.
