### ISSUE TITLE
[Web] Drag events broken on Chrome - Linux

### ISSUE THREAD

**Issue by MichealReed** [flutter/flutter#174049]
### Steps to reproduce

Run the example code on chrome with a linux build.

### Expected results

Drag events should work as they do on other browsers, and even Windows Chrome.

### Actual results

Drag events are broken, no updates are provided and end does not output accurate coordinates.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: DragGestureDemo(),
      ),
    );
  }
}

class DragGestureDemo extends StatefulWidget {
  const DragGestureDemo({super.key});

  @override
  State<DragGestureDemo> createState() => _DragGestureDemoState();
}

class _DragGestureDemoState extends State<DragGestureDemo> {
  Offset _offset = const Offset(120, 150);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned.fill(
          child: IgnorePointer(
            ignoring: true,
            child: CustomPaint(
              painter: _CrosshairPainter(),
            ),
          ),
        ),
        Positioned(
          left: _offset.dx,
          top: _offset.dy,
          child: GestureDetector(
            onPanStart: (details) {
              print(
                  'PanStart: global=${details.globalPosition}, local=${details.localPosition}');
            },
            onPanUpdate: (details) {
              setState(() {
                _offset += details.delta;
              });
              print(
                  'PanUpdate: delta=${details.delta}, global=${details.globalPosition}, local=${details.localPosition} -> newOffset=$_offset');
            },
            onPanEnd: (details) {
              print(
                  'PanEnd: velocity=${details.velocity.pixelsPerSecond}, magnitude=${details.velocity.pixelsPerSecond.distance}');
            },
            onPanCancel: () {
              print('PanCancel');
            },
            child: MouseRegion(
              cursor: SystemMouseCursors.move,
              child: Container(
                width: 200,
                height: 100,
                decoration: BoxDecoration(
                  color: Colors.cyan,
                  borderRadius: BorderRadius.circular(8),
                  boxShadow: const [
                    BoxShadow(
                      color: Colors.black26,
                      blurRadius: 8,
                      offset: Offset(2, 4),
                    )
                  ],
                ),
                alignment: Alignment.center,
                child: const Text(
                  'Gesture Drag\n(Watch console)',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class _CrosshairPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.grey.shade300
      ..strokeWidth = 1;
    canvas.drawLine(Offset(size.width / 2, 0),
        Offset(size.width / 2, size.height), paint);
    canvas.drawLine(Offset(0, size.height / 2),
        Offset(size.width, size.height / 2), paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) =>
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
PanStart: global=Offset(226.0, 221.0), local=Offset(106.0, 71.0)
PanEnd: velocity=Offset(0.0, 0.0), magnitude=0
PanStart: global=Offset(243.0, 180.0), local=Offset(123.0, 30.0)
PanEnd: velocity=Offset(0.0, 0.0), magnitude=0
PanStart: global=Offset(262.0, 169.0), local=Offset(142.0, 19.0)
PanEnd: velocity=Offset(0.0, 0.0), magnitude=0
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.1, on Ubuntu 25.04 6.14.0-28-generic, locale en_US.UTF-8) [42ms]
    • Flutter version 3.35.1 on channel stable at /home/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 20f8274939 (5 days ago), 2025-08-14 10:53:09 -0700
    • Engine revision 1e9a811bf8
    • Dart version 3.9.0
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios,
      cli-animations, enable-lldb-debugging

[✗] Android toolchain - develop for Android devices [22ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web [11ms]
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop [25ms]
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from
      https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/

[!] Android Studio (not installed) [9ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] VS Code (version 1.103.1) [8ms]
    • VS Code at /usr/share/code
    • Flutter extension version 3.116.0

[✓] Connected device (2 available) [64ms]
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 25.04 6.14.0-28-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 139.0.7258.127

[✓] Network resources [560ms]
    • All expected network resources are available.
```

</details>

**Comment by MichealReed** [comment]
JS reproduction works, flutter does not.

```js
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Drag Gesture Demo (JS)</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>
  html,body {
    margin:0;
    height:100%;
    font-family: system-ui, Arial, sans-serif;
    background:#fff;
  }
  .stage {
    position:relative;
    width:100%;
    height:100%;
    overflow:hidden;
    user-select:none;
    -webkit-user-select:none;
    cursor:default;
  }
  /* Crosshair (center lines only) */
  .stage::before,
  .stage::after {
    content:"";
    position:absolute;
    left:0; top:0;
    width:100%; height:100%;
    pointer-events:none;
  }
  .stage::before {
    border-left:1px solid #d0d0d0;
    left:50%;
  }
  .stage::after {
    border-top:1px solid #d0d0d0;
    top:50%;
  }
  .card {
    position:absolute;
    width:200px;
    height:100px;
    background:#00bcd4;
    color:#033;
    border-radius:8px;
    box-shadow:2px 4px 8px rgba(0,0,0,0.26);
    display:flex;
    align-items:center;
    justify-content:center;
    font-weight:600;
    text-align:center;
    cursor:move;
    touch-action:none; /* allow pointer events without browser panning */
  }
  .coords {
    position:fixed;
    left:8px;
    bottom:8px;
    background:#0007;
    color:#fff;
    font:12px/1.4 monospace;
    padding:6px 8px;
    border-radius:4px;
    pointer-events:none;
  }
</style>
</head>
<body>
  <div class="stage" id="stage">
    <div class="card" id="card">
      Gesture Drag<br/>(Watch console)
    </div>
    <div class="coords" id="coords"></div>
  </div>

<script>
(function() {
  const card = document.getElementById('card');
  const coordsBox = document.getElementById('coords');
  const stage = document.getElementById('stage');

  // Initial offset similar to Flutter example
  let offsetX = 120;
  let offsetY = 150;

  // Pointer drag state
  let dragging = false;
  let dragStartPointerOffsetX = 0;
  let dragStartPointerOffsetY = 0;

  function applyPosition() {
    card.style.transform = `translate(${offsetX}px, ${offsetY}px)`;
    coordsBox.textContent = `offset=(${offsetX.toFixed(1)}, ${offsetY.toFixed(1)})`;
  }

  applyPosition();

  card.addEventListener('pointerdown', (e) => {
    e.preventDefault();
    card.setPointerCapture(e.pointerId);
    dragging = true;

    // Pointer's position relative to card top-left
    const cardRect = card.getBoundingClientRect();
    dragStartPointerOffsetX = e.clientX - cardRect.left;
    dragStartPointerOffsetY = e.clientY - cardRect.top;

    console.log(
      `PanStart: global=(${e.clientX}, ${e.clientY}), local=(${dragStartPointerOffsetX.toFixed(1)}, ${dragStartPointerOffsetY.toFixed(1)})`
    );
  });

  card.addEventListener('pointermove', (e) => {
    if (!dragging) return;
    // Compute new top-left so the pointer keeps same relative position
    const newLeft = e.clientX - dragStartPointerOffsetX;
    const newTop  = e.clientY - dragStartPointerOffsetY;

    const deltaX = newLeft - offsetX;
    const deltaY = newTop - offsetY;

    offsetX = newLeft;
    offsetY = newTop;
    applyPosition();

    console.log(
      `PanUpdate: delta=(${deltaX.toFixed(1)}, ${deltaY.toFixed(1)}), global=(${e.clientX}, ${e.clientY}), local=(${dragStartPointerOffsetX.toFixed(1)}, ${dragStartPointerOffsetY.toFixed(1)}) -> newOffset=(${offsetX.toFixed(1)}, ${offsetY.toFixed(1)})`
    );
  });

  function endDrag(e, cancelled=false) {
    if (!dragging) return;
    dragging = false;
    try { card.releasePointerCapture(e.pointerId); } catch(_) {}
    if (cancelled) {
      console.log('PanCancel');
    } else {
      // Approximate velocity using pointer movement (not integrated over time)
      // Here we just log 0; for real velocity, store timestamps & last positions.
      const velocity = { x: 0, y: 0 };
      const magnitude = 0;
      console.log(`PanEnd: velocity=(${velocity.x.toFixed(1)}, ${velocity.y.toFixed(1)}), magnitude=${magnitude.toFixed(1)}`);
    }
  }

  card.addEventListener('pointerup', (e) => endDrag(e,false));
  card.addEventListener('pointercancel', (e) => endDrag(e,true));
  window.addEventListener('pointerleave', (e) => {
    // If pointer leaves window while dragging, treat as cancel
    if (dragging) endDrag(e,true);
  });

  // Optional: arrow keys to nudge (helps testing)
  window.addEventListener('keydown', (e) => {
    const step = e.shiftKey ? 10 : 1;
    if (e.key === 'ArrowLeft') offsetX -= step;
    else if (e.key === 'ArrowRight') offsetX += step;
    else if (e.key === 'ArrowUp') offsetY -= step;
    else if (e.key === 'ArrowDown') offsetY += step;
    else return;
    applyPosition();
  });

})();
</script>
</body>
</html>
```

**Comment by MichealReed** [comment]
JS reproduction works, flutter does not.

```js
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Drag Gesture Demo (JS)</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>
  html,body {
    margin:0;
    height:100%;
    font-family: system-ui, Arial, sans-serif;
    background:#fff;
  }
  .stage {
    position:relative;
    width:100%;
    height:100%;
    overflow:hidden;
    user-select:none;
    -webkit-user-select:none;
    cursor:default;
  }
  /* Crosshair (center lines only) */
  .stage::before,
  .stage::after {
    content:"";
    position:absolute;
    left:0; top:0;
    width:100%; height:100%;
    pointer-events:none;
  }
  .stage::before {
    border-left:1px solid #d0d0d0;
    left:50%;
  }
  .stage::after {
    border-top:1px solid #d0d0d0;
    top:50%;
  }
  .card {
    position:absolute;
    width:200px;
    height:100px;
    background:#00bcd4;
    color:#033;
    border-radius:8px;
    box-shadow:2px 4px 8px rgba(0,0,0,0.26);
    display:flex;
    align-items:center;
    justify-content:center;
    font-weight:600;
    text-align:center;
    cursor:move;
    touch-action:none; /* allow pointer events without browser panning */
  }
  .coords {
    position:fixed;
    left:8px;
    bottom:8px;
    background:#0007;
    color:#fff;
    font:12px/1.4 monospace;
    padding:6px 8px;
    border-radius:4px;
    pointer-events:none;
  }
</style>
</head>
<body>
  <div class="stage" id="stage">
    <div class="card" id="card">
      Gesture Drag<br/>(Watch console)
    </div>
    <div class="coords" id="coords"></div>
  </div>

<script>
(function() {
  const card = document.getElementById('card');
  const coordsBox = document.getElementById('coords');
  const stage = document.getElementById('stage');

  // Initial offset similar to Flutter example
  let offsetX = 120;
  let offsetY = 150;

  // Pointer drag state
  let dragging = false;
  let dragStartPointerOffsetX = 0;
  let dragStartPointerOffsetY = 0;

  function applyPosition() {
    card.style.transform = `translate(${offsetX}px, ${offsetY}px)`;
    coordsBox.textContent = `offset=(${offsetX.toFixed(1)}, ${offsetY.toFixed(1)})`;
  }

  applyPosition();

  card.addEventListener('pointerdown', (e) => {
    e.preventDefault();
    card.setPointerCapture(e.pointerId);
    dragging = true;

    // Pointer's position relative to card top-left
    const cardRect = card.getBoundingClientRect();
    dragStartPointerOffsetX = e.clientX - cardRect.left;
    dragStartPointerOffsetY = e.clientY - cardRect.top;

    console.log(
      `PanStart: global=(${e.clientX}, ${e.clientY}), local=(${dragStartPointerOffsetX.toFixed(1)}, ${dragStartPointerOffsetY.toFixed(1)})`
    );
  });

  card.addEventListener('pointermove', (e) => {
    if (!dragging) return;
    // Compute new top-left so the pointer keeps same relative position
    const newLeft = e.clientX - dragStartPointerOffsetX;
    const newTop  = e.clientY - dragStartPointerOffsetY;

    const deltaX = newLeft - offsetX;
    const deltaY = newTop - offsetY;

    offsetX = newLeft;
    offsetY = newTop;
    applyPosition();

    console.log(
      `PanUpdate: delta=(${deltaX.toFixed(1)}, ${deltaY.toFixed(1)}), global=(${e.clientX}, ${e.clientY}), local=(${dragStartPointerOffsetX.toFixed(1)}, ${dragStartPointerOffsetY.toFixed(1)}) -> newOffset=(${offsetX.toFixed(1)}, ${offsetY.toFixed(1)})`
    );
  });

  function endDrag(e, cancelled=false) {
    if (!dragging) return;
    dragging = false;
    try { card.releasePointerCapture(e.pointerId); } catch(_) {}
    if (cancelled) {
      console.log('PanCancel');
    } else {
      // Approximate velocity using pointer movement (not integrated over time)
      // Here we just log 0; for real velocity, store timestamps & last positions.
      const velocity = { x: 0, y: 0 };
      const magnitude = 0;
      console.log(`PanEnd: velocity=(${velocity.x.toFixed(1)}, ${velocity.y.toFixed(1)}), magnitude=${magnitude.toFixed(1)}`);
    }
  }

  card.addEventListener('pointerup', (e) => endDrag(e,false));
  card.addEventListener('pointercancel', (e) => endDrag(e,true));
  window.addEventListener('pointerleave', (e) => {
    // If pointer leaves window while dragging, treat as cancel
    if (dragging) endDrag(e,true);
  });

  window.addEventListener('keydown', (e) => {
    const step = e.shiftKey ? 10 : 1;
    if (e.key === 'ArrowLeft') offsetX -= step;
    else if (e.key === 'ArrowRight') offsetX += step;
    else if (e.key === 'ArrowUp') offsetY -= step;
    else if (e.key === 'ArrowDown') offsetY += step;
    else return;
    applyPosition();
  });

})();
</script>
</body>
</html>
```

**Comment by darshankawar** [comment]
@MichealReed Thanks for the report. 

> bool shouldRepaint(covariant CustomPainter oldDelegate) =>

I fixed this by returning false. 

I did observe `OnPanUpdate` getting triggered on macOS chrome and desktop platforms respectively, but do see `onPanEnd` as mentioned in the description:

```
flutter: PanUpdate: delta=Offset(-0.0, 0.0), global=Offset(279.4, 417.7), local=Offset(-213.0, 55.8) -> newOffset=Offset(163.3, 357.5)
flutter: PanEnd: velocity=Offset(0.0, 0.0), magnitude=0.0
```
Did `OnPanUpdate` work properly in previous stable if you can check ? Trying to know if this is a regression or not.

**Comment by MichealReed** [comment]
@darshankawar apologies on the paste error with the example. Just tried with [✓] Flutter (Channel stable, 3.10.0, on Ubuntu 25.04 6.14.0-28-generic, locale en_US.UTF-8), still does not drag.

**Comment by darshankawar** [comment]
> Channel stable, 3.10.0,

@MichealReed It is an old version. Can you please verify with latest stable 3.35.1 ?

**Comment by MichealReed** [comment]
My original submission was on 3.35.1, it's been broken for a long time and still is on latest.

**Comment by darshankawar** [comment]
Thanks for the update. Sorry I misread your earlier post. Based on original findings and per my verifications, I'll keep the issue open for team's tracking.
