### ISSUE TITLE
GridView can't in Column?

### ISSUE THREAD

**Issue by ikakaxi** [flutter/flutter#17558]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.3 17D47, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.

*********code:
```
import 'package:flutter/material.dart';

const TEXT_NORMAL = 160.0;

void main() {
  runApp(MaterialApp(
    home: Scaffold(
        appBar: AppBar(
          title: Text("gridview in column issue"),
        ),
        body: GameLocationPage()
    ),
  ));
}

class GameLocationPage extends StatefulWidget {

  @override
  GameLocationState createState() {
    return new GameLocationState();
  }
}

class GameLocationState extends State<GameLocationPage> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    //has problem
//    return Column(
//      crossAxisAlignment: CrossAxisAlignment.start,
//      children: <Widget>[
//        Container(
//            padding: EdgeInsets.all(10.0),
//            child: Text("you selected", style: TextStyle(fontSize: TEXT_NORMAL),)
//        ),
//        Container(
//            width: 100.0,
//            margin: EdgeInsets.all(10.0),
//            padding: EdgeInsets.all(10.0),
//            color: Colors.white,
//            child: Row(
//              mainAxisSize: MainAxisSize.min,
//              children: <Widget>[
//                Icon(Icons.location_on, color: Theme
//                    .of(context)
//                    .primaryColor),
//                Text("all")
//              ],
//            )
//        ),
//        Container(
//            padding: EdgeInsets.all(10.0),
//            child: Text("second", style: TextStyle(fontSize: TEXT_NORMAL),)
//        ),
//        GridView.extent(
//            maxCrossAxisExtent: 150.0,
//            children: <String>[
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//              'http://www.for-example.org/img/main/forexamplelogo.png',
//            ].map((String url) {
//              return new GridTile(
//                  child: new Image.network(url, fit: BoxFit.cover));
//            }).toList()),
//      ],
//    );

    // no problem
    return GridView.extent(
        maxCrossAxisExtent: 150.0,
        children: <String>[
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
          'http://www.for-example.org/img/main/forexamplelogo.png',
        ].map((String url) {
          return new GridTile(
              child: new Image.network(url, fit: BoxFit.cover));
        }).toList());
  }
}
```

**Comment by ikakaxi** [comment]
Resolved, ListView or GridView using shrinkWrap: true

**Comment by patelkrunal78** [comment]
body: new Column(
children: <Widget>[
new Expanded(
child: GridView.count(
// Create a grid with 2 columns. If you change the scrollDirection to
// horizontal, this would produce 2 rows.
crossAxisCount: 2,
// Generate 100 Widgets that display their index in the List
children: List.generate(10, (index) {
return _buildCard(index);
}),
),
),
new Text("text")
],
),

Find Your Solution [Here](https://icetutor.com/question/flutter-gridview-in-column)

**Comment by firatcetiner** [comment]
Still an issue. I can't believe there exist a such an issue, it has been more than 6 months... 

It's just a simple layout: Card -> Column -> [Text, GridView]. Unbeliavable..

**Comment by gewure** [comment]
i also face issues using Gridview in Column. i am currently testing to get a clearer picture on it.

**Comment by arulmani33** [comment]
Im also facing issue with gridview inside column, its not scrolling even i cant use singlescrollview

**Working**
`SafeArea(
      child: _buildSearchResult(), // gridview
)`
**Not Working**
`SafeArea(
      // child: _buildSearchResult(),
      child: Column(
        children: [
          Text("sss"),
          SingleChildScrollView(child: _buildSearchResult())
        ],
  ));`

**Comment by arulmani33** [comment]
> Still an issue. I can't believe there exist a such an issue, it has been more than 6 months...
> 
> The problem is when you have an ancestor of ListView. For example using GridView in a Column works just fine, wrapping the Column with ListView is causing the issue.
> 
> Edit: Maybe this is unrelevant but I don't want to open a new issue.

Can you share how you use GridView inside column
