### ISSUE TITLE
blink::DartSnapshot::GetData() crashing during desktop embedding.

### ISSUE THREAD

**Issue by awdavies** [flutter/flutter#17884]
Linux precompiled engine version: `86d96fd0ce8d58d2dfcd4398eb97aa66873d3bf7`
Flutter version: `70772ea5a00a9518bea3e611c5008181df3423fe`

When calling `RunFlutterEngine`, the engine crashes with the following GDB backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2af71f0 in blink::DartSnapshot::GetData() const ()
   from /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
(gdb) bt
#0  0x00007ffff2af71f0 in blink::DartSnapshot::GetData() const ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#1  0x00007ffff2af7cf7 in blink::DartVM::DartVM(blink::Settings const&, fxl::RefPtr<blink::DartSnapshot>, fxl::RefPtr<blink::DartSnapshot>) () at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#2  0x00007ffff2af8926 in fxl::RefPtr<blink::DartVM> fxl::internal::MakeRefCountedHelper<blink::DartVM>::MakeRefCounted<blink::Settings&, fxl::RefPtr<blink::DartSnapshot>, fxl::RefPtr<blink::DartSnapshot> >(blink::Settings&, fxl::RefPtr<blink::DartSnapshot>&&, fxl::RefPtr<blink::DartSnapshot>&&) ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#3  0x00007ffff2af8769 in void std::__1::__call_once_proxy<std::__1::tuple<blink::DartVM::ForProcess(blink::Settings, fxl::RefPtr<blink::DartSnapshot>, fxl::RefPtr<blink::DartSnapshot>)::$_0&&> >(void*) ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#4  0x00007ffff2fc55e8 in std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) (flag=@0x7ffff305eb48: 1, arg=0x7fffffffbc00, func=0x7ffff2af8720 <void std::__1::__call_once_proxy<std::__1::tuple<blink::DartVM::ForProcess(blink::Settings, fxl::RefPtr<blink::DartSnapshot>, fxl::RefPtr<blink::DartSnapshot>)::$_0&&> >(void*)>)
    at /b/s/w/ir/kitchen-workdir/llvm-project/libcxx/src/mutex.cpp:236
#5  0x00007ffff2af76f7 in blink::DartVM::ForProcess(blink::Settings, fxl::RefPtr<blink::DartSnapshot>, fxl::RefPtr<blink::DartSnapshot>) () at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#6  0x00007ffff2af762f in blink::DartVM::ForProcess(blink::Settings) ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#7  0x00007ffff2582490 in shell::Shell::Create(blink::TaskRunners, blink::Settings, std::__1::function<std::__1::unique_ptr<shell::PlatformView, std::__1::default_delete<shell::PlatformView> > (shell::Shell&)>, std::__1::function<std::__1::unique_ptr<shell::Rasterizer, std::__1::default_delete<shell::Rasterizer> > (shell::Shell&)>) ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#8  0x00007ffff2519665 in shell::EmbedderEngine::EmbedderEngine(shell::ThreadHost, blink::TaskRunners, blink::Settings, std::__1::function<std::__1::unique_ptr<shell::PlatformView, std::__1::default_delete<shell::PlatformView> > (shell::Shell&)>, std::__1::function<std::__1::unique_ptr<shell::Rasterizer, std::__1::default_delete<shell::Rasterizer> > (shell::Shell&)>) ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#9  0x00007ffff24fdc99 in FlutterEngineRun ()
    at /redacted/flutter-desktop-embedding/linux/library/libflutter_engine.so
#10 0x00007ffff77785a5 in RunFlutterEngine(GLFWwindow*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) ()
    at /redacted/flutter-desktop-embedding/linux/example/../library/libflutter_embedder.so
#11 0x00007ffff777886f in flutter_desktop_embedding::CreateFlutterWindow(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) ()
    at /redacted/flutter-desktop-embedding/linux/example/../library/libflutter_embedder.so
#12 0x0000555555555082 in main ()
```

**Comment by stuartmorgan** [comment]
Locally built engine did the same thing for me. I get "VM snapshot must be valid" logging to the console before it crashes, but using source mode didn't help.

**Comment by awdavies** [comment]
From Chinmay: should be fixed when https://github.com/flutter/engine/pull/5368 lands

**Comment by chinmaygarde** [comment]
Fix has landed. Thanks!

**Comment by bdytx5** [comment]
I'm getting this error when I run the app in release mode on iOS. It crashes on startup. Not really sure why this is happening...

[VERBOSE-2:dart_vm.cc(256)] VM snapshot must be valid. 
[VERBOSE-3:shell.cc(216)] Check failed: vm. Must be able to initialize the VM.

Here is my flutter doctor 

• No issues found!
mwc-034148:flutterThumbsOut brett$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.72, on Mac OS X 10.13 17A405, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (3 available)

• No issues found!

**Comment by nashfive** [comment]
@bdytx5 I get the exact same issue. Did you find a way to fix this ?

**Comment by manondidi** [comment]
same problem

**Comment by stuartmorgan** [comment]
This bug was about a specific regression for desktop embedding that was fixed. Anyone seeing a crash in this function when building for supported Flutter platforms (iOS, Android) should file a different bug.

**Comment by AteqEjaz** [comment]
Still getting same ERROR

2019-09-30 22:59:37.791687+0500 Runner[810:141577] [VERBOSE-2:dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
2019-09-30 22:59:37.793008+0500 Runner[810:141577] [VERBOSE-2:dart_vm.cc(245)] Could not setup VM data to bootstrap the VM from.
2019-09-30 22:59:37.793537+0500 Runner[810:141577] [VERBOSE-2:dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
2019-09-30 22:59:37.795949+0500 Runner[810:141577] [VERBOSE-3:shell.cc(212)] Check failed: vm. Must be able to initialize the VM.
(lldb)

**Comment by stuartmorgan** [comment]
@AteqEjaz Please see my last comment above.
