### ISSUE TITLE
NestedScrollView cannot scroll inner list view

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter#18099]
I have a `NestedScrollView` with a `SliverAppBar` with an `expandedHeight` and a `SliverFixedExtentList` inside. Basically [this example](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html).

Now I want to `jumpTo` `position` `5000.0` in the list.

So I add a `ScrollController` to the `NestedScrollView`. But the `range` that I can `jumpTo` seems to be limited to the height of the header.

I am not able to programatically scroll the `SliverFixedExtentList` to any position.

I believe this is because the `NestedScrollView` doesn't allow access to the `innerController`, but that is just a guess.

Is there a way to achieve this any other way?

Why, because I try to have a `TabBar` and each tab scrolls the `ListView` underneath to a specific section - basically like in the UeberEats app's menu page.

**Comment by chinmaygarde** [comment]
cc @Hixie @Han

**Comment by Hixie** [comment]
Yeah there's some weird stuff going on in that code.

**Comment by knewter** [comment]
We're also trying to figure this out right now, same situation (and actually using that ubereats screen as inspiration too!). I was assuming I was meant to do something to explicitly get the inner scroll view controller, but now it seems like the expected behaviour would be to just use the scrollcontroller from the nestedscrollview itself - it just doesn't work.

**Comment by jaggerwang** [comment]
@knewter I also have a similar problem #26409 . There is no notification of inner scroll view's position after load new data for once, so I can not load data anymore.

**Comment by uiboy** [comment]
Whats the latest on this @Hixie / @han ? Same problem here too.

**Comment by rhalff** [comment]
I've found a way to still get a hold of the `innerController` by looking up an ancester widget of the type ` PrimaryScrollController`, which is created when the body is being build.

```dart
NestedScrollView(
  body: Builder(
    builder: (BuildContext context) {
      final innerScrollController =
        (context.ancestorWidgetOfExactType(PrimaryScrollController)
          as PrimaryScrollController).controller;

// Use the innerScrollController to listen to the scrolling (and dispose again)

    }
  ),
);
```

The exact code rendering the `PrimaryScrollController` can be found here:
https://github.com/flutter/flutter/blob/1946fc4da0f80c522d7e3ae7d4f7309908ed86f2/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L274-L284

Performance-wise it should be ok I think as the `PrimaryController` is a direct parent.

 It's still a hack though and not a final solution.

**Comment by rhalff** [comment]
Perhaps adding a `bodySliverBuilder` option to `NestedScrollView` would be sufficient?
It could receive the `innerController` and the `bodyIsScrolled` value.

**Comment by ayush221b** [comment]
Hey, I am facing the same issue, and I need this now. Is there any update @Hixie ? Thanks.

**Comment by IkhwanSI13** [comment]
> I've found a way to still get a hold of the `innerController` by looking up an ancester widget of the type ` PrimaryScrollController`, which is created when the body is being build.
> 
> ```dart
> NestedScrollView(
>   body: Builder(
>     builder: (BuildContext context) {
>       final innerScrollController = PrimaryScrollController.of(context);
> 
> // Use the innerScrollController to listen to the scrolling (and dispose again)
> 
>     }
>   ),
> );
> ```
> 
> The exact code rendering the `PrimaryScrollController` can be found here:
> https://github.com/flutter/flutter/blob/1946fc4da0f80c522d7e3ae7d4f7309908ed86f2/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L274-L284
> 
> Performance-wise it should be ok I think as the `PrimaryController` is a direct parent.
> 
> It's still a hack though and not a final solution.
> 
> update: changed example to use the `PrimaryScrollController.of` method.

I faced the same problem, and I tried this but found another error, when I took the scroll position.

**Comment by rhalff** [comment]
@IkhwanSI13 this issue is about getting access to the `innerScrollController` which the code above solves.

Perhaps you could provide an example of what's not working and then ask for help at: https://gitter.im/flutter/flutter

Unless you've found that the `innerScrollController` itself is somehow not usable.

**Comment by IkhwanSI13** [comment]
Solved with SingleChildScrollView.

https://gist.github.com/IkhwanSI13/eb09a588096db4c88f96ad9f2faf91d1

**Comment by csells** [comment]
@BerndWessels does the use of SingleChildScrollView as per @IkhwanSI13 solve your problem?

**Comment by Piinks** [comment]
This might also be fixed by #49004
Feedback is welcome on the proposed change. :)

**Comment by debasmitasarkar** [comment]
> Solved with SingleChildScrollView.
> 
> https://gist.github.com/IkhwanSI13/eb09a588096db4c88f96ad9f2faf91d1

Does not solve the problem. It does not trigger NestedScrollView

**Comment by debasmitabounce** [comment]
> I've found a way to still get a hold of the `innerController` by looking up an ancester widget of the type ` PrimaryScrollController`, which is created when the body is being build.
> 
> ```dart
> NestedScrollView(
>   body: Builder(
>     builder: (BuildContext context) {
>       final innerScrollController = PrimaryScrollController.of(context);
> 
> // Use the innerScrollController to listen to the scrolling (and dispose again)
> 
>     }
>   ),
> );
> ```
> 
> The exact code rendering the `PrimaryScrollController` can be found here:
> https://github.com/flutter/flutter/blob/1946fc4da0f80c522d7e3ae7d4f7309908ed86f2/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L274-L284
> 
> Performance-wise it should be ok I think as the `PrimaryController` is a direct parent.
> 
> It's still a hack though and not a final solution.
> 
> update: changed example to use the `PrimaryScrollController.of` method.

This is really helpful. Saved my day

**Comment by deepakrajv** [comment]
> I've found a way to still get a hold of the `innerController` by looking up an ancester widget of the type ` PrimaryScrollController`, which is created when the body is being build.
> 
> ```dart
> NestedScrollView(
>   body: Builder(
>     builder: (BuildContext context) {
>       final innerScrollController = PrimaryScrollController.of(context);
> 
> // Use the innerScrollController to listen to the scrolling (and dispose again)
> 
>     }
>   ),
> );
> ```
> 
> The exact code rendering the `PrimaryScrollController` can be found here:
> https://github.com/flutter/flutter/blob/1946fc4da0f80c522d7e3ae7d4f7309908ed86f2/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L274-L284
> 
> Performance-wise it should be ok I think as the `PrimaryController` is a direct parent.
> 
> It's still a hack though and not a final solution.
> 
> update: changed example to use the `PrimaryScrollController.of` method.

Work like a charm.
