### ISSUE TITLE
SafeArea on Android does not change when hiding UIOverlays

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#18671]
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setEnabledSystemUIOverlays([]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Container(color: Colors.blueGrey,),
      ),
    );
  }
}
```
### Android
![screenshot_1529576276](https://user-images.githubusercontent.com/814785/41715383-8b274f50-7553-11e8-9503-0f44177701e1.png)

### iOS
![simulator screen shot - iphone 7 - 2018-06-21 at 12 54 19](https://user-images.githubusercontent.com/814785/41715382-8b09a2f2-7553-11e8-915e-7042b55b953d.png)

**Comment by zoechi** [comment]
@Hixie

**Comment by Hixie** [comment]
cc @cbracken @jason-simmons

**Comment by cbenhagen** [comment]
Any news on this? Or any workarounds?

**Comment by granoeste** [comment]
Is it still solved? Is there any workarounds?

**Comment by granoeste** [comment]
I think that there is a same bug without using SafeArea on Channel beta, v0.7.3.

I tried with the following code.
```
void main() {
  // Full screen UI
  SystemChrome.setEnabledSystemUIOverlays([]);
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Portrate Full Screen'),
      ),
      body: new Container(
        color: Colors.amber,
        alignment: FractionalOffset.center,
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'Portrate full screen, Bottom navigation area bug?',
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```

At portrait, the content are not displayed in hidden bottom navigation bar.

![screenshot_1537237186](https://user-images.githubusercontent.com/291993/45660739-50ea6700-bb35-11e8-8195-6cce928424c6.png)

At landscape, No problems, the content was displayed in  hidden side navigation bar but there is a problem in the position of the FAB.

![screenshot_1537238006](https://user-images.githubusercontent.com/291993/45661042-bd199a80-bb36-11e8-9dc8-cc4a7dd0dc6b.png)

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale ja-JP)
    • Flutter version 0.7.3 at /Users/granoeste/Library/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282
```

I'm hoping for an early fix!

**Comment by GaryQian** [comment]
This issue's direct problems should now be fixed when the engine rolls into Flutter. The bottom inset spacing is moved into a separate bug linked above.

**Comment by guccisekspir** [comment]
This error still continue.....

**Comment by 0ne0rZer0** [comment]
@GaryQian Hey the issue still persists, is there a possible fix upcoming?
I've tried rebuilding, hot restart also, there is still a black bar instead of app going full screen when the status bar is disabled.
Thanks for yourtime!

**Comment by jaddison06** [comment]
Any progress on this?
