### ISSUE TITLE
flutter bash completion

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#18988]
It would be really nice to have a bash completion package so we don't always have to type the full commands in flutter

**Comment by DanTup** [comment]
@kevmoo I came across https://github.com/kevmoo/completion.dart - but the readme is a little bare. Would it help here? `flutter_tools` uses the `args` package - seems like it should be easy to script bash completion (we already have a human-readable list via `--help`)?

**Comment by kevmoo** [comment]
@DanTup – I believe it would! The issue is startup time. There has been some discussion about creating a serialization format for the various flags/options that could parsed without a startup hit – or we could look into snapshots....

**Comment by DanTup** [comment]
I'm not familiar with how this works; what's slow? As I understand it, all of the commands and their args are registered on every invocation of `flutter` and running `flutter --help` is fast; isn't this just an alternative output from that?

(I read https://iridakos.com/tutorials/2018/03/01/bash-programmable-completion-tutorial.html and have been assuming we'd just make a big flat file of the args; but now I wonder if your package is doing more than just that?)

**Comment by kevmoo** [comment]
If `flutter --help` is "fast", then completion is fast.

**Comment by kevmoo** [comment]
I just published `0.2.0` of completion to support the latest pkg:args – also include Dart2 fixes

**Comment by DanTup** [comment]
@kevmoo It's not clear to me how to use/test it - I've tried reading through the example dart file and shell scripts but I'm still not exactly sure how to add it to a project. Are there any notes on it (or a PR on another project that added it)?

**Comment by DanTup** [comment]
Oh, nm - looks like @gspencergoog picked this up 👍
