### ISSUE TITLE
Can't run basic app on iOS

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1910]
Ok, I've installed every dependency and jumped through every hoop, and I still can't get to space:
```
ianh-macbookpro:dev ianh$ git clone https://github.com/flutter/flutter.git -b master
Cloning into 'flutter'...
remote: Counting objects: 35730, done.
remote: Compressing objects: 100% (1023/1023), done.
remote: Total 35730 (delta 654), reused 0 (delta 0), pack-reused 34699
Receiving objects: 100% (35730/35730), 12.71 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (23588/23588), done.
Checking connectivity... done.
ianh-macbookpro:dev ianh$ flutter create -o story
Downloading Dart SDK 1.14.1...
######################################################################## 100.0%
Building flutter tool...
Creating story...
  story/.analysis_options
  story/.gitignore
  story/README.md
  story/android/AndroidManifest.xml
  story/android/res/.empty
  story/flutter.yaml
  story/ios/Assets.xcassets/AppIcon.appiconset/Contents.json
  story/ios/Info.plist
  story/ios/LaunchScreen.storyboard
  story/lib/main.dart
  story/pubspec.yaml

Running 'pub get' in 'story'...

All done! To run your application:

  $ cd story
  $ flutter run

ianh-macbookpro:dev ianh$ cd story
ianh-macbookpro:story ianh$ flutter run
Downloading darwin-x64 artifacts from the cloud, one moment please...
Downloading https://storage.googleapis.com/mojo_infra/flutter/9e1e1fba5474b458458b65f1aa1d0d730af2705b/darwin-x64/artifacts.zip.
Starting lib/main.dart on iPod touch...
Path "/Users/ianh/dev/story/ios/.generated" does not exist.
Did you run `flutter ios --init`?
Could not build the precompiled application for the device
Error starting application on iPod touch.
Unable to run application.
ianh-macbookpro:story ianh$ flutter ios --init
Fetching the Xcode project archive from the cloud...
Downloading https://storage.googleapis.com/flutter_infra/flutter/9e1e1fba5474b458458b65f1aa1d0d730af2705b/ios/FlutterXcode.zip...
Unzipping Xcode project to local directory...
Xcode project created at /Users/ianh/dev/story/ios/.generated/.
User editable settings are in /Users/ianh/dev/story/ios/.
ianh-macbookpro:story ianh$ flutter run
Starting lib/main.dart on iPod touch...
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Could not build the precompiled application for the device
Error starting application on iPod touch.
Unable to run application.
ianh-macbookpro:story ianh$ 
```

**Comment by chinmaygarde** [comment]
May I have the results of `flutter run --verbose` please? Though I am pretty sure this is because the engine was rolled over the weekend without landing a patch to the tooling (currently in review)

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/pull/1917 may have helped with this?

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/flutter/pull/1835

**Comment by Hixie** [comment]
I still get this. Filed a new bug with more details at https://github.com/flutter/flutter/issues/1949.
