### ISSUE TITLE
Form fields loose data when scrolled out of view

### ISSUE THREAD

**Issue by momsenmeister** [flutter/flutter#19148]
I had a form using a data object and a formState key.
The form was working fine until I added some more TextFormFields that made it neccessary to scroll the form to see the submit button.

Now I experience a strange behavior:
The text entered in the first TextFormField is lost when I scroll until the end of the form and then back.
Also the validator of the first TextFormField is not working anymore.

I already found a similar issue:
https://stackoverflow.com/questions/45240734/flutter-form-data-disappears-when-i-scroll
But in  my opinion this behaviour should not occur at all and the proposed solution is just a workaround.

I would suggest that all children of a Form widget should behave consistent and should not be removed from the widget tree at any time or when scrolled out of view.

**Comment by miyoyo** [comment]
How about a form controller?

**Comment by jonahwilliams** [comment]
@momsenmeister does the solution in that stack overflow question not work?  Without a controller you will see a similar effect from anything that causes the widget to be rebuilt, such as an animation or opacity effect on a parent widget.  Flutter may call build up to 60 times a second, anything less is just an optimization.

**Comment by momsenmeister** [comment]
Do I need to add a controller to every field or is it possible to just use one for the whole form?
Could you direct me to an example?
Thanks!

**Comment by jonahwilliams** [comment]
you can use a controller for each field to hold the state of the form so that it can be persisted from frame to frame.  I think putting a global key on each form field widget will persist it if it goes offscreen.

For an example I would checkout either the form field demo in the [gallery](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart) or maybe [building a form with validation](https://flutter.io/cookbook/forms/validation/).

**Comment by momsenmeister** [comment]
Neither of your examples use a controller, so they are not really helpful ;-)

My implementation is like in the [gallery](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart) which doesn't work as soon as you scroll out of view.

**Comment by jonahwilliams** [comment]
@momsenmeister those were both fixed by adding the global key

**Comment by momsenmeister** [comment]
@jonahwilliams 
I already am using a global FormState key.

`class CreatePageState extends State<CreatePage> {
  final _formKey = new GlobalKey<FormState>();
.....`

and set is as the key for my form:
`@override
  Widget build(BuildContext context) {
    final Size screenSize = MediaQuery.of(context).size;

    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Neues Event erstellen'),
      ),
      body: new Container(
          padding: new EdgeInsets.all(20.0),
          child: new Form(
            key: this._formKey,
            child: new ListView(
              children: <Widget>[
                new TextFormField(
                    keyboardType: TextInputType.text,
                    maxLength: 30,
                    decoration: new InputDecoration(
                        hintText: '',
                        labelText: 'Wie soll das Event heißen?',
                    ),
                    validator: this._validateTitle,
                    style: new TextStyle(fontSize: 14.0, color: Colors.black87),
                    onSaved: (String value) {
                      this._data.title = value;
                    }
                ),
....` 

I'm sure there might be some workarounds, but this really seems just like a bug?

**Comment by momsenmeister** [comment]
I'm going for this workaround for now, which works:
`
 body: new Container(
          padding: new EdgeInsets.all(20.0),
          child: new Form(
            key: this._formKey,
            child: SingleChildScrollView(
              child: new Column(
              children: <Widget>[
                new TextFormField(
                  ........
`
Uaing this instead of the ListView works fine.

**Comment by jonahwilliams** [comment]
thanks, @momsenmeister I'll take a look at the code you provided and see If I can't figure out what's been happening.

**Comment by DanielSmith1239** [comment]
Any updates on this? Still having this issue.

**Comment by mohamedHassanKa** [comment]
any updates guys i still have this issue

**Comment by miyoyo** [comment]
Wasn't this solved by creating a controller inside of the state object, instead of using the default one in the list (which is garbage collected when it scrolls out of sight)?

**Comment by Livinglist** [comment]
> Wasn't this solved by creating a controller inside of the state object, instead of using the default one in the list (which is garbage collected when it scrolls out of sight)?

Could you please articulate?

**Comment by zacwolfe** [comment]
Is there a timeline for this to be fixed? I'm still seeing the issue

**Comment by narciero** [comment]
i see this issue as well when i have my form fields (`FormField<T>` and `TextFormField`) inside a `ListView` which is inside a `PageView` and i scroll between pages

**Comment by Asim-kudo** [comment]
I have the same issue but what about the stepped form?  Or any solution?

**Comment by Allan-Nava** [comment]
> ```dart
> TextFormField
> ```

I have this bug with
```
 SingleChildScrollView(
          child: new Column(
```
![device-2019-05-07-175314](https://user-images.githubusercontent.com/22498435/57314003-15ff6880-70f1-11e9-9447-29614f85b114.png)

**Comment by chunhtai** [comment]
For those who experience this issue, one thing to try is wrapping the textfield in a keep alive client
```dart
class WidgetExample extends StatefulWidget {
  const WidgetExample({
    Key key
  }) : super(key: key);

  @override
  WidgetExampleState createState() => WidgetExampleState();
}

class WidgetExampleState extends State<WidgetExample> with AutomaticKeepAliveClientMixin{

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return TextFormField();
  }

  @override
  bool get wantKeepAlive => true;
}
```

If you are not sure how to do that, feel free to post an runnable example.

**Comment by iapicca** [comment]
Hi @momsenmeister 
I'm closing this issue for inactivity.
If you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by vivchar** [comment]
I have the same issue, looks like when we use ListView and TextFormField as a child of ListView,
onSave didn't call if TextFormField is outside of display area (it is removed from ListView)

**Comment by chunhtai** [comment]
It seems like we _unregister the formfield from form when the element deactivate and register it when we build. This behavior seems weird to me. I think do it in initstate and dispose make more sense. What do you think @justinmc ?

**Comment by justinmc** [comment]
That makes sense to me at a high level but I'm not very familiar with how forms work.  Maybe @HansMuller could say?

It sounds like something that might have been done for performance reasons?

**Comment by endrelovas** [comment]
I think this has nothing to do with Forms. Correct me if I am wrong: when you use ListView, the elements are dynamically created/disposed as when they scroll in and out of the screen. This is the behaviour of ListView to save resources when there are hundreds or thousands of listItems should be display inside them.

So if you wrap your textfield inside a listItem it will get disposed when it moves out of the screen.

In my understanding this is how it works. Too bad that the examples of Form use ListView.

My solution for the problem was this:

`	Widget build( BuildContext context ) {
		_buildFields( );
		return Form(
			key: _formKey,
			child: SingleChildScrollView(
				child: Padding(
					padding: const EdgeInsets.all( 8.0 ),
					child: Column(
						children: _fields,
					),
				),
			),
		);
	}
`

**Comment by tinashehondo** [comment]
I tried the SingleChildScrollView but still it didnt work, i ended up using TextEditingController defined globally since the default one garbage collects when TextFormField is not visible.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
