### ISSUE TITLE
Application crash at launch when system language set to id_ID.

### ISSUE THREAD

**Issue by wychi** [flutter/flutter#19155]
## Steps to Reproduce

Application crash at launch when system language set to id_ID.

Here is the sample code.
I found another crash while creating this sample.
You can find it in the comment.

```
import 'dart:async';

import 'package:coin_master/utils/env.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';
import 'package:intl/intl_standalone.dart';

class SampleApp extends StatelessWidget {
  // Note: uncomment this, the crash goes away.
  // final DateFormat dateFormat = new DateFormat('MM/dd HH:mm');

  @override
  Widget build(BuildContext context) {
    // https://github.com/flutter/flutter/issues/14128
    Future<String> future;
    if (isiOS()) {
      future = Future.value("in_ID");
    } else {
      future = findSystemLocale();
    }

    return FutureBuilder(
      future: future,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Container();
        }
        var currentLocale = snapshot.data;
        // NOTE: override for demo
        currentLocale = new Locale("id", "ID");
        return new MaterialApp(
          locale: currentLocale,
          title: 'Flutter Demo',
          theme: new ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: ClockWidget(),
// Note: crash2
//          home: Container(
//            child: Text(
//                "Date ${new DateFormat().add_Hms().format(new DateTime.now())}"),
//          ),
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
          ],
        );
      },
    );
  }
}

class ClockWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final DateFormat dateFormat = new DateFormat('MM/dd HH:mm');

    return Container(
      child: Text("Date ${dateFormat.format(new DateTime.now())}"),
    );
  }
}

void main() {
  runApp(new SampleApp());
}


```
## Logs

```
E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    Invalid argument(s): Invalid locale 'id_ID'
    #0      Intl._throwLocaleError (package:intl/intl.dart:240:5)
    #1      Intl.verifiedLocale (package:intl/intl.dart:234:21)
    #2      Intl.verifiedLocale (package:intl/intl.dart:219:14)
    #3      new DateFormat (file:///Users/wychi/.pub-cache/hosted/pub.dartlang.org/intl-0.15.6/lib/src/intl/date_format.dart:246:20)
```

## Version
```
Flutter 0.5.6-pre.61 • channel unknown • unknown source
Framework • revision 2e559584e2 (9 days ago) • 2018-06-22 16:32:32 -0700
Engine • revision 549c855e89
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
```

**Comment by HansMuller** [comment]
The source of the problem appears to be that `packages/flutter_localizations/lib/src/l10n/date_localizations.dart` hasn't been updated in a while and does not include the Indonesian locale. 

Updating it now.

**Comment by HansMuller** [comment]
@wychi  https://github.com/flutter/flutter/pull/19174 should fix this bug

Can you check your app against the "tip of tree"?

**Comment by wychi** [comment]
@HansMuller 
yes, the first crash goes away.

The other crash still exist.
```
I/flutter (10918): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10918): The following LocaleDataException was thrown building FutureBuilder<String>(dirty, state:
I/flutter (10918): _FutureBuilderState<String>#fa4ad):
I/flutter (10918): Locale data has not been initialized, call initializeDateFormatting(<locale>).
I/flutter (10918): 
I/flutter (10918): When the exception was thrown, this was the stack:
I/flutter (10918): #0      UninitializedLocaleData._throwException (package:intl/src/intl_helpers.dart:71:5)
I/flutter (10918): #1      UninitializedLocaleData.containsKey (package:intl/src/intl_helpers.dart:68:61)
I/flutter (10918): #2      DateFormat.localeExists (file:///Users/wychi/.pub-cache/hosted/pub.dartlang.org/intl-0.15.6/lib/src/intl/date_format.dart:753:28)
I/flutter (10918): #3      Intl.verifiedLocale (package:intl/intl.dart:222:21)
I/flutter (10918): #4      Intl.verifiedLocale (package:intl/intl.dart:219:14)
I/flutter (10918): #5      new DateFormat (file:///Users/wychi/.pub-cache/hosted/pub.dartlang.org/intl-0.15.6/lib/src/intl/date_format.dart:246:20)
I/flutter (10918): #6      SampleApp.build.<anonymous closure> (file:///Users/wychi/repositories/coinmaster/lib/sample/sample_app.dart:42:29)
I/flutter (10918): #7      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter (10918): #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (10918): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (10918): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (10918): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (10918): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (10918): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (10918): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (10918): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (10918): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (10918): #18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (10918): #19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (10918): #20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (10918): (elided one frame from package dart:async)
I/flutter (10918): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by HansMuller** [comment]
The error message indicates that you haven't called `initializeDateFormatting()` from the intl package.

**Comment by wychi** [comment]
@HansMuller 
thanks you for the explanation.

**Comment by HansMuller** [comment]
You're welcome. I'm going to close this issue, since I think we've addressed the original issue.

**Comment by anztrax** [comment]
thanks @HansMuller  :+1:
