### ISSUE TITLE
Flutter crashes in debug builds (but not release) on the Hisense C11 Chromebook

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#19524]
I purchased a cheap Hisense Chromebook to test out how Unreal Engine performs on it (and the results are quite surprising!)

Anyways, running a release mode app on the Chromebook runs fine, very smooth, great performance, etc.

Running a debug mode app is... actually quite entertaining. Seems to be a VM bug.

Fun error snippet:

```
E/flutter (19652): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (19652): 'package:flutter/src/foundation/binding.dart': Failed assertion: line 79 pos 12: '!_debugInitialized': is not true.
E/flutter (19652): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
E/flutter (19652): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
E/flutter (19652): #2      BindingBase.initInstances (package:flutter/src/foundation/binding.dart)
E/flutter (19652): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding.initInstances (package:flutter/src/gestures/binding.dart:26:11)
E/flutter (19652): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding.initInstances (package:flutter/src/services/binding.dart:26:11)
E/flutter (19652): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:196:11)
E/flutter (19652): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:22:11)
E/flutter (19652): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:31:11)
E/flutter (19652): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #9      new BindingBase (package:flutter/src/foundation/binding.dart:53:5)
E/flutter (19652): #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #15     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #16     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter (19652): #17     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:911:11)
E/flutter (19652): #18     runApp (package:flutter/src/widgets/binding.dart:703:25)
E/flutter (19652): #19     main (file:///C:/Users/ds841/Realism/naga/lib/main.dart:11:3)
E/flutter (19652): #20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter (19652): #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (19652): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (19652): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (19652): The getter '_v4storage' was called on null.
I/flutter (19652): Receiver: null
I/flutter (19652): Tried calling: _v4storage
I/flutter (19652): 
I/flutter (19652): When the exception was thrown, this was the stack:
I/flutter (19652): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
I/flutter (19652): #1      new Vector4 (file:///C:/Users/ds841/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/vector_math-2.0.6/lib/src/vector_math_64/vector4.dart)
I/flutter (19652): #2      TransformLayer.find (package:flutter/src/rendering/layer.dart:787:32)
I/flutter (19652): #3      RenderView._updateSystemChrome (package:flutter/src/rendering/view.dart:215:58)
I/flutter (19652): #4      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:198:9)
I/flutter (19652): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:273:16)
I/flutter (19652): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (19652): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (19652): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (19652): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (19652): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (19652): #11     _invoke (dart:ui/hooks.dart:125:13)
I/flutter (19652): #12     _drawFrame (dart:ui/hooks.dart:114:3)
I/flutter (19652): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Other ones are just crashes in JIT'd code (the stack traces are _very_ short), or aborts in unrelated pieces of code like this one:

[tombstone_00.txt](https://github.com/flutter/flutter/files/2206784/tombstone_00.txt)

This one seems to be a crash in the JIT:

[tombstone_04.txt](https://github.com/flutter/flutter/files/2206796/tombstone_04.txt)

ChromeOS isn't writing the tombstones for some of the crashes, which is kinda disappointing.

/proc/cpuinfo:

```
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc0d
CPU revision    : 1

processor       : 1
model name      : ARMv7 Processor rev 1 (v7l)
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc0d
CPU revision    : 1

processor       : 2
model name      : ARMv7 Processor rev 1 (v7l)
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc0d
CPU revision    : 1

processor       : 3
model name      : ARMv7 Processor rev 1 (v7l)
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc0d
CPU revision    : 1

Hardware        : Rockchip (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

Flutter Doctor:

```
[√] Connected devices (1 available)
    • Rockchip RK3288 Chromebook • <omitted>:5555 • android-arm • Android 7.1.1 (API 25)
```

**Comment by ds84182** [comment]
Another one (breaks some fields in _FloatingActionButtonTransition and then crashes):

```
I/flutter (21312): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21312): The following assertion was thrown building _FloatingActionButtonTransition(dirty, state:
I/flutter (21312): _FloatingActionButtonTransitionState#8332b(tickers: tracking 2 tickers)):
I/flutter (21312): 'package:flutter/src/widgets/transitions.dart': Failed assertion: line 43 pos 15: 'listenable !=
I/flutter (21312): null': is not true.
I/flutter (21312): 
I/flutter (21312): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21312): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21312): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21312):   https://github.com/flutter/flutter/issues/new
I/flutter (21312): 
I/flutter (21312): When the exception was thrown, this was the stack:
I/flutter (21312): #2      new AnimatedWidget (package:flutter/src/widgets/transitions.dart)
I/flutter (21312): #3      new RotationTransition (package:flutter/src/widgets/transitions.dart:222:8)
I/flutter (21312): #4      _FloatingActionButtonTransitionState.build (package:flutter/src/material/scaffold.dart:633:20)
I/flutter (21312): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (21312): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (21312): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #23     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3968:11)
I/flutter (21312): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4772:32)
I/flutter (21312): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #70     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #100    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #109    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #112    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (21312): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #131    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (21312): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (21312): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (21312): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (21312): #136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (21312): #137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (21312): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (21312): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
Syncing files to device Rockchip RK3288 Chromebook...
F/libc    (21312): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x8531f2b0 in tid 21328 (1.ui)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/jerry/jerry_cheets:7.1.1/R69-10866.1.0/4884711:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 21312, tid: 21328, name: 1.ui  >>> io.realism.naga <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x8531f2b0
    r0 8dd020c1  r1 8ccbb000  r2 854386a0  r3 00000001
    r4 8dd019d1  r5 87338e49  r6 87338a39  r7 85325541
    r8 8531c0b1  r9 87338a39  sl 8ccbb000  fp a0bef490
    ip 00002328  sp a0bef478  lr 8543871c  pc 8531f2b0  cpsr a00b0030
backtrace:
    #00 pc 0001f2b0  <anonymous:85300000>
    #01 pc 00038718  <anonymous:85400000>
```

**Comment by zoechi** [comment]
Similar 
```
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.007/4586646:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 20892, tid: 20923, name: Thread-3  >>> com.lookatyou.lookatmybaby <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x755c4f83
    eax 7bdface3  ebx 94edeb8c  ecx ab6bd000  edx 06835d5c
    esi f97ca2a0  edi 93bfd9dc
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip 947610ca  ebp 93bfca08  esp 93bfc9c0  flags 00010286
backtrace:
    #00 pc 009140ca  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #01 pc 009142be  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #02 pc 00914e43  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #03 pc 0091cbec  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #04 pc 0071c08c  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #05 pc 008ef46a  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #06 pc 009051f5  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #07 pc 00934842  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #08 pc 00937e1a  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #09 pc 00939487  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #10 pc 00938c1b  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #11 pc 00934dd6  /data/app/com.lookatyou.lookatmybaby-kpiWlPPbQVIQrnJg93ob3w==/lib/x86/libflutter.so
    #12 pc 000005cb  <anonymous:92600000>
    #13 pc 0000061c  <anonymous:92600000>
    #14 pc 0001d1bc  <anonymous:8a2c0000>
    #15 pc 0001cf74  <anonymous:8a2c0000>
    #16 pc 0001b793  <anonymous:8a2c0000>
    #17 pc 0001a74e  <anonymous:8a2c0000>
    #18 pc 000729ce  <anonymous:8a6c0000>
    #19 pc 00070d23  <anonymous:8a6c0000>
    #20 pc 000194ec  <anonymous:8a2c0000>
    #21 pc 000729ce  <anonymous:8a6c0000>
    #22 pc 00070d23  <anonymous:8a6c0000>
    #23 pc 00004ed7  <anonymous:8a2c0000>
    #24 pc 000729ce  <anonymous:8a6c0000>
    #25 pc 00070d23  <anonymous:8a6c0000>
    #26 pc 00000792  <anonymous:8a2c0000>
    #27 pc 0007255a  <anonymous:8a6c0000>
    #28 pc 00070d23  <anonymous:8a6c0000>
    #29 pc 0007fd3f  <anonymous:8a6c0000>
    #30 pc 0004aec1  <anonymous:8a6c0000>
    #31 pc 0002ae5a  <anonymous:84580000>
    #32 pc 00008121  <anonymous:8e880000>
    #33 pc 0000af74  <anonymous:84580000>
    #34 pc 0003da3c  <anonymous:8ea40000>
    #35 pc 0003d889  <anonymous:8ea40000>
    #36 pc 0003d2dd  <anonymous:8ea40000>
    #37 pc 0003d0ee  <anonymous:8ea40000>
    #38 pc 00007d91  <anonymous:8e880000>
    #39 pc 00007a75  <anonymous:8e880000>
    #40 pc 0002c645  <anonymous:8c380000>
    #41 pc 00002f76  <anonymous:8e880000>
    #42 pc 0000461b  <anonymous:8e880000>
    #43 pc 000041f3  <anonymous:8e880000>
    #44 pc 0003afdc  <anonymous:8ea40000>
    #45 pc 0003ac6c  <anonymous:8ea40000>
    #46 pc 0004c4ac  <anonymous:8a6c0000>
    #47 pc 0002ae5a  <anonymous:84580000>
    #48 pc 00008121  <anonymous:8e880000>
    #49 pc 0000af74  <anonymous:84580000>
    #50 pc 0003da3c  <anonymous:8ea40000>
    #51 pc 0003d889  <anonymous:8ea40000>
    #52 pc 0003d2dd  <anonymous:8ea40000>
    #53 pc 0003d0ee  <anonymous:8ea40000>
    #54 pc 00007d91  <anonymous:8e880000>
    #55 pc 00007a75  <anonymous:8e880000>
    #56 pc 0002c645  <anonymous:8c380000>
    #57 pc 00002f76  <anonymous:8e880000>
    #58 pc 0000461b  <anonymous:8e880000>
    #59 pc 000041f3  <anonymous:8e880000>
    #60 pc 0003afdc  <anonymous:8ea40000>
    #61 pc 0003ac6c  <anonymous:8ea40000>
    #62 pc 0004d41e  <anonymous:8a6c0000>
    #63 pc 0002ae5a  <anonymous:84580000>
Lost connection to device.
```
```
[✓] Flutter (Channel master, v0.5.8-pre.215, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.215 at /Users/zoechi/flutter/flutter
    • Framework revision eda03e2586 (2 hours ago), 2018-08-02 12:02:32 +0200
    • Engine revision a76054f4b6
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Looks like #19379 and should be fixed though.

**Comment by ds84182** [comment]
Still happening on the latest version of Flutter. I can work around it by reopening the app after it crashes if `flutter run` is still waiting for it to launch. Hot reload and debugging work fine after that.

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by ds84182** [comment]
I don't have access to the Chromebook that this was occurring on right now,
so I can't test again. I do know I was still getting the bug back in
November/early December.

**Comment by zoechi** [comment]
@ds84182 Thanks for the update!
