### ISSUE TITLE
Random crash on all my apps

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#20255]
I'm having a lot of brutal crashes under IntelliJ no error is thrown previously on this stack.
Sometimes it crash instantly at startup sometimes after some mins.
Crash on all my apps, even the simple Flutter default template.

```
../../third_party/dart/runtime/vm/compiler/backend/flow_graph_compiler.cc: 1975: error: expected: !range.IsIllegalRange()
Dumping native stack trace for thread a503
[0x000000010fd48214] dart::Profiler::DumpStackTrace(void*)
[0x000000010fd48214] dart::Profiler::DumpStackTrace(void*)
[0x000000010ffca392] dart::Assert::Fail(char const*, ...)
[0x000000010fe209d2] dart::FlowGraphCompiler::GenerateCidRangesCheck(dart::Assembler*, dart::Register, dart::MallocGrowableArray<dart::CidRange> const&, dart::Label*, dart::Label*, bool)
[0x000000010fdebec9] dart::TypeTestingStubGenerator::BuildOptimizedSubtypeRangeCheck(dart::Assembler*, dart::MallocGrowableArray<dart::CidRange> const&, dart::Register, dart::Register, bool)
[0x000000010fdebcf4] dart::TypeTestingStubGenerator::BuildOptimizedTypeTestStubFastCases(dart::Assembler*, dart::HierarchyInfo*, dart::Type const&, dart::Class const&, dart::Register, dart::Register)
[0x000000010fdd7d17] dart::TypeTestingStubGenerator::BuildOptimizedTypeTestStub(dart::Assembler*, dart::HierarchyInfo*, dart::Type const&, dart::Class const&)
[0x000000010fdeab73] dart::TypeTestingStubGenerator::BuildCodeForType(dart::Type const&)
[0x000000010fdea872] dart::TypeTestingStubGenerator::OptimizedCodeForType(dart::AbstractType const&)
[0x000000010fdea71e] dart::TypeTestingStubGenerator::SpecializeStubFor(dart::Thread*, dart::AbstractType const&)
[0x000000010fd99817] dart::DRT_TypeCheck(dart::NativeArguments)
[0x0000000123a8091b] [Stub] CallToRuntime
[0x0000000123a82d8c] [Stub] LazySpecializeTypeTest
[0x0000000123f174ed] *_GrowableList.add
[0x0000000123f1bbdf] BuildOwner.scheduleBuildFor
[0x0000000128529268] Element.markNeedsBuild
[0x0000000128527c97] State.setState
[0x0000000123f1b26d] _WidgetsAppState.didChangeMetrics
[0x0000000123f18d49] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.handleMetricsChanged
[0x0000000123f18b5c] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.handleMetricsChanged
[0x00000001254004f2] _Closure.call
[0x0000000125405b7f] _invoke
[0x0000000125402f18] _updateWindowMetrics
[0x0000000123a80da3] [Stub] InvokeDartCode
[0x000000010fc0c7b5] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
[0x000000010ff5951d] Dart_Invoke
[0x000000010faba1a4] tonic::DartInvokeField(_Dart_Handle*, char const*, std::initializer_list<_Dart_Handle*>)
[0x000000010f742530] blink::Window::UpdateWindowMetrics(blink::ViewportMetrics const&)
[0x000000010f74beb9] blink::RuntimeController::SetViewportMetrics(blink::ViewportMetrics const&)
[0x000000010f7538aa] shell::Engine::SetViewportMetrics(blink::ViewportMetrics const&)
[0x000000010f72553c] fml::MessageLoopImpl::RunExpiredTasks()
[0x000000010f72840e] fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
[0x0000000111d59174] __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
[0x0000000111d58e32] __CFRunLoopDoTimer
[0x0000000111d589ea] __CFRunLoopDoTimers
[0x0000000111d50404] __CFRunLoopRun
[0x0000000111d4f889] CFRunLoopRunSpecific
[0x000000010f72855f] fml::MessageLoopDarwin::Run()
[0x000000010f725673] fml::MessageLoopImpl::DoRun()
[0x000000010f727f00] std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*)
[0x0000000117342661] _pthread_body
[0x000000011734250d] _pthread_body
[0x0000000117341bf9] thread_start
-- End of DumpStackTrace
```

```
No issues found
```

```
[✓] Flutter (Channel master, v0.5.8-pre.230, on Mac OS X 10.13.5 17F77, locale en-FR)
    • Flutter version 0.5.8-pre.230 at /Users/user/Install/flutter
    • Framework revision 8dd06a1190 (3 days ago), 2018-08-03 17:10:17 +0200
    • Engine revision 4893b0760d
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/robbie/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.0.3
    • Dart plugin version 182.3569.4

[✓] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 62001927-580B-49AC-8098-15C557E75D95 • ios • iOS 11.2 (simulator)

• No issues found!

```

**Comment by mraleph** [comment]
Marking with TODAY until we know the reason for sure.

**Comment by mraleph** [comment]
@Solido do you have any more information to share. Do I understand correctly that it crashes like that when you try to run a Flutter application on iOS simulator from InteliJ? Do you have any breakpoints active? 

> even the simple Flutter default template.

Is it result of running `flutter create`?

**Comment by Solido** [comment]
Projects where created with IntelliJ.
Crash started about 1 week ago but I was working on a complex app so I was thinking I've made error in my code.
It crashed so often and randomly I suspected smth else so I created a new basic project from intellij and after 10 secs I got the message.

Lots of problems appeared in my workflow recently. 
- When launching a app it freeze after `Xcode build done.` and need to stop and relaunch. 
All restarts using Debug will crash the app, Running the App will not.
Let me know if I can add some to log more.

Breakpoints could be a suspect.

**Comment by Solido** [comment]
Really looks like linked to debug. After some normal Run I blocked the app in Debug mode for sometimes, releasing the Breakpoint triggered the error message.

**Comment by mraleph** [comment]
We think we found it - it is indeed related to breakpoints (more specifically to expression evaluation used by the debugger). It seems that `EvaluateCompiledExpressionHelper` is introducing classes into the class table with id equal to 0 - which is not something that other parts of the code expect to ever happen. 

We are working on a fix.

**Comment by Solido** [comment]
Thanks for handling the case so quickly ! I was desperate ;)

**Comment by mkustermann** [comment]
The fix for this particular issue is up for review: https://dart-review.googlesource.com/c/sdk/+/68681

**Comment by mraleph** [comment]
We are only going close this bug once we roll into Flutter.

**Comment by mkustermann** [comment]
This issue should be fixed and was included in the flutter roll flutter/engine@d90223fadfd219af23d4a4c260a78fb21be3fe99 .

**Comment by Solido** [comment]
Just flutter upgrade and still the same error.
Maybe the patch is not in my package ?

`
Flutter 0.5.9-pre.24 • channel master • https://github.com/flutter/flutter.git
Framework • revision e69b434602 (11 hours ago) • 2018-08-13 20:36:44 +0200
Engine • revision e54bc4ea18
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c
`

```
../../third_party/dart/runtime/vm/compiler/backend/flow_graph_compiler.cc: 1965: error: expected: !range.IsIllegalRange()
Dumping native stack trace for thread 5703
[0x0000000107d93ec4] dart::Profiler::DumpStackTrace(void*)
[0x0000000107d93ec4] dart::Profiler::DumpStackTrace(void*)
[0x0000000108016a82] dart::Assert::Fail(char const*, ...)
[0x0000000107e6c622] dart::FlowGraphCompiler::GenerateCidRangesCheck(dart::Assembler*, dart::Register, dart::MallocGrowableArray<dart::CidRange> const&, dart::Label*, dart::Label*, bool)
[0x0000000107e38229] dart::TypeTestingStubGenerator::BuildOptimizedTypeArgumentValueCheck(dart::Assembler*, dart::HierarchyInfo*, dart::AbstractType const&, long, dart::Register, dart::Register, dart::Register, dart::Register, dart::Register, dart::Label*)
[0x0000000107e23b8f] dart::TypeTestingStubGenerator::BuildOptimizedTypeArgumentValueCheck(dart::Assembler*, dart::HierarchyInfo*, dart::AbstractType const&, long, dart::Label*)
[0x0000000107e37f9c] dart::TypeTestingStubGenerator::BuildOptimizedSubclassRangeCheckWithTypeArguments(dart::Assembler*, dart::HierarchyInfo*, dart::Class const&, dart::TypeArguments const&, dart::TypeArguments const&, dart::Register, dart::Register, dart::Register)
[0x0000000107e23b63] dart::TypeTestingStubGenerator::BuildOptimizedSubclassRangeCheckWithTypeArguments(dart::Assembler*, dart::HierarchyInfo*, dart::Class const&, dart::TypeArguments const&, dart::TypeArguments const&)
[0x0000000107e37bcc] dart::TypeTestingStubGenerator::BuildOptimizedTypeTestStubFastCases(dart::Assembler*, dart::HierarchyInfo*, dart::Type const&, dart::Class const&, dart::Register, dart::Register)
[0x0000000107e23ae7] dart::TypeTestingStubGenerator::BuildOptimizedTypeTestStub(dart::Assembler*, dart::HierarchyInfo*, dart::Type const&, dart::Class const&)
[0x0000000107e36993] dart::TypeTestingStubGenerator::BuildCodeForType(dart::Type const&)
[0x0000000107e36692] dart::TypeTestingStubGenerator::OptimizedCodeForType(dart::AbstractType const&)
[0x0000000107e3653e] dart::TypeTestingStubGenerator::SpecializeStubFor(dart::Thread*, dart::AbstractType const&)
[0x0000000107de54e5] dart::DRT_TypeCheck(dart::NativeArguments)
[0x000000011e50091b] [Stub] CallToRuntime
[0x000000011e502e0c] [Stub] LazySpecializeTypeTest
[0x000000012395d56a] *_List.[]=
[0x0000000123ded163] _HashSet._addEntry
[0x0000000123decbc7] _HashSet.add
[0x000000012332b466] Element.inheritFromWidgetOfExactType
[0x00000001245e606a] DefaultTextStyle.of
[0x00000001245e53d1] Text.build
[0x0000000122f71e14] StatelessElement.build
[0x0000000122f7118e] ComponentElement.performRebuild
[0x0000000122f7033a] Element.rebuild
[0x0000000122f6fcf9] ComponentElement._firstBuild
[0x0000000122f6f5dc] ComponentElement.mount
[0x0000000122f6e45a] Element.inflateWidget
[0x0000000122f6d80a] Element.updateChild
[0x000000012344cf94] SingleChildRenderObjectElement.mount
[0x0000000122f6e45a] Element.inflateWidget
[0x0000000122f6d80a] Element.updateChild
[0x0000000122f714d6] ComponentElement.performRebuild
[0x0000000122f7033a] Element.rebuild
[0x0000000122f6fcf9] ComponentElement._firstBuild
[0x0000000122f6f5dc] ComponentElement.mount
[0x0000000122f6e45a] Element.inflateWidget
[0x0000000122f6d80a] Element.updateChild
[0x0000000127601d95] RenderObjectElement.updateChildren
[0x0000000124ebebe1] MultiChildRenderObjectElement.update
[0x0000000122f6d499] Element.updateChild
[0x0000000122f714d6] ComponentElement.performRebuild
[0x0000000122f7033a] Element.rebuild
[0x0000000124eb1f4d] StatefulElement.update
[0x0000000122f6d499] Element.updateChild
[0x0000000124eb35ca] SingleChildRenderObjectElement.update
[0x0000000122f6d499] Element.updateChild
[0x0000000122f714d6] ComponentElement.performRebuild
[0x0000000122f7033a] Element.rebuild
[0x0000000124e87dfc] StatelessElement.update
[0x0000000122f6d499] Element.updateChild
[0x0000000122f714d6] ComponentElement.performRebuild
[0x0000000122f7033a] Element.rebuild
[0x0000000122f6525e] BuildOwner.buildScope
[0x0000000124a38c0b] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame
[0x0000000124a38879] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback
[0x0000000124a38750] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback
[0x000000011ffa3235] _Closure.call
[0x0000000124a37f5b] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
[0x0000000124a37228] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
[0x0000000124e8746f] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
[0x0000000124e8729c] _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
[0x0000000123949a3a] *_Closure.call
[0x000000011ff8590d] _invoke
[0x000000011ff8ee54] _drawFrame
[0x000000011e500da3] [Stub] InvokeDartCode
[0x0000000107c574d5] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
[0x0000000107fa5c0d] Dart_Invoke
[0x0000000107b04e8c] tonic::DartInvokeField(_Dart_Handle*, char const*, std::initializer_list<_Dart_Handle*>)
[0x000000010778ec8b] blink::Window::BeginFrame(fml::TimePoint)
[0x0000000107797a98] blink::RuntimeController::BeginFrame(fml::TimePoint)
[0x000000010779e959] shell::Engine::BeginFrame(fml::TimePoint)
[0x000000010779c6b4] shell::Animator::BeginFrame(fml::TimePoint, fml::TimePoint)
[0x00000001077610ff] std::__1::function<void (fml::TimePoint, fml::TimePoint)>::operator()(fml::TimePoint, fml::TimePoint) const
[0x00000001077b0386] std::__1::__function::__func<shell::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0, std::__1::allocator<shell::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0>, void ()>::operator()()
[0x000000010776e346] fml::MessageLoopImpl::RunExpiredTasks()
[0x0000000107771218] fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
[0x0000000109e03174] __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
[0x0000000109e02e32] __CFRunLoopDoTimer
[0x0000000109e029ea] __CFRunLoopDoTimers
[0x0000000109dfa404] __CFRunLoopRun
[0x0000000109df9889] CFRunLoopRunSpecific
[0x0000000107771369] fml::MessageLoopDarwin::Run()
[0x000000010776e47d] fml::MessageLoopImpl::DoRun()
[0x0000000107770d0a] std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*)
[0x000000010ff31661] _pthread_body
[0x000000010ff3150d] _pthread_body
[0x000000010ff30bf9] thread_start
```

**Comment by jonahwilliams** [comment]
@Solido the engine roll is pending here: https://github.com/flutter/flutter/pull/20533

**Comment by mkustermann** [comment]
@Solido My apologies for this. I was under the impression the previous dart -> flutter/engine roll (which contains the fix) was also rolled from flutter/engine -> flutter/flutter. Turns out that roll wasn't completed yet.

My roll in https://github.com/flutter/flutter/pull/20427 will then have these changes in. Hopefully we can land this soon.

**Comment by Solido** [comment]
@mkustermann Oh I see huge release 2.1 dev ! 
frustrating but I understand. Thank you !

**Comment by Solido** [comment]
It's getting worse, not starting & no trace.
I'll go back to a previous release and wait.
`
flutter run --debug
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Starting Xcode build...
 ├─Assembling Flutter resources...                    4.4s

 └─Compiling, linking and signing...                 11.6s

Xcode build done.                                           19.7s
Lost connection to device.
`

**Comment by mkustermann** [comment]
The roll got reverted and I'm working on relanding it.
