### ISSUE TITLE
firebase_messaging: onMessage/onLaunch/onResume only give access to the data message payload. There is no way to get the notification object, the priority, sender, sentTime...

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#21043]
On Android (and probably iOS as well), `FirebaseMessagingService` receives a [`RemoteMessage`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage) object when a notification or data message is received.

This object contains many useful properties, like the displayed notification text, key, message type, date...

Yet there is no way to receive this information in dart code. Only the data payload is sent to `onMessage`/`onLaunch`/`onResume`.

**Comment by zoechi** [comment]
https://github.com/flutter/plugins/pull/672 might fix that

**Comment by sir-boformer** [comment]
Yep, although it seems like that PR will not be merged soon. There are also more fields which are still missing in that PR.

**Comment by zoechi** [comment]
You could add a comment to the PR to help improve it.

**Comment by ffeu** [comment]
just mentioning the PR was merged, maybe the issue is fixed.

**Comment by sir-boformer** [comment]
Looks like the issue is partially fixed.

Notification title and body are included in a `notification` item, other properties are still missing.

**Comment by kroikie** [comment]
@sir-boformer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/689. Any further collaboration will be done there.
