### ISSUE TITLE
Three things to make TabView work without crashing in my app

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#21630]
I'm working on flutter app that uses a TabView where each view contains a widget with a GlobalKey.

With the latest master channel, the app crashes on switching between the tabs.

However, if I do the following three things, it appears to be very stable.

1. merge in this PR: https://github.com/flutter/flutter/pull/21350

The rationale for the PR is in the PR and its linked issue https://github.com/flutter/flutter/issues/11895

2. remove the following `assert` in `scroll_position.dart`, as per issue https://github.com/flutter/flutter/issues/18756.

As per my comment in that issue https://github.com/flutter/flutter/issues/18756#issuecomment-415387519, it is unclear to me why it is important that `pixels != null` at this point in the code. I'd love if this assert would read `assert(pixels != null, "And here's why it's important...")`. Removing it appears to be harmless.

```
--- a/packages/flutter/lib/src/widgets/scroll_position.dart
+++ b/packages/flutter/lib/src/widgets/scroll_position.dart
@@ -658,7 +658,7 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {

   @override
   void dispose() {
-    assert(pixels != null);
+    // assert(pixels != null);
     activity?.dispose(); // it will be null if it got absorbed by another ScrollPosition
     _activity = null;
     super.dispose();
```

3. In `Element.updateChild`, change the position of checking that a GlobalKey is not being reused by a different widget so that it occurs after the old child widget has had a chance to be deactivated, thus freeing the GlobalKey to be used in the new widget.

See https://stackoverflow.com/questions/49862572/multiple-widgets-used-the-same-globalkey?rq=1 for some more background on this, and an example.

```
--- a/packages/flutter/lib/src/widgets/framework.dart
+++ b/packages/flutter/lib/src/widgets/framework.dart
@@ -2705,18 +2705,12 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
   /// |  **child != null**  |  Old child is removed, returns null. | Old child updated if possible, returns child or new [Element]. |
   @protected
   Element updateChild(Element child, Widget newWidget, dynamic newSlot) {
-    assert(() {
-      if (newWidget != null && newWidget.key is GlobalKey) {
-        final GlobalKey key = newWidget.key;
-        key._debugReserveFor(this);
-      }
-      return true;
-    }());
     if (newWidget == null) {
       if (child != null)
         deactivateChild(child);
       return null;
     }
+
     if (child != null) {
       if (child.widget == newWidget) {
         if (child.slot != newSlot)
@@ -2737,6 +2731,13 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
       deactivateChild(child);
       assert(child._parent == null);
     }
+    assert(() {
+      if (newWidget.key is GlobalKey) {
+        final GlobalKey key = newWidget.key;
+        key._debugReserveFor(this);
+      }
+      return true;
+    }());
     return inflateWidget(newWidget, newSlot);
   }
```

It's okay to move the assert to the end, because it cannot possibly trigger on the other code paths.
Either `newWidget == null`, so it can't have a `GlobalKey` anyway. Or `child.widget == newWidget` so the `GlobalKey` is already being used by the child. Or (see code below), `Widget.canUpdate(child.widget, newWidget)` is true, which means that `child.widget.key == newWidget.key`, according to the rules of being allowed to replace a widget.

```
      if (Widget.canUpdate(child.widget, newWidget)) {
        if (child.slot != newSlot)
          updateSlotForChild(child, newSlot);
        child.update(newWidget);
        assert(child.widget == newWidget);
        assert(() {
          child.owner._debugElementWasRebuilt(child);
          return true;
        }());
        return child;
      }

```

Therefore, the only place that needs to have the assert to check we're not using a `GlobalKey` more than once, is near the end of this method.

I imagine that (1) will land on Master shortly (thanks @dnfield)

I think we need some clarity about why `assert(pixels != null)` is or isn't important to proceed with (2).

While (3) fixes my problem, and I think I have pretty robust reasoning what bug it fixes and why this is an appropriate fix, I have no idea how to move this forward into a PR. I'd like some advice, or for someone from the core team to take a look.

Thanks

**Comment by dnfield** [comment]
Is there a copy/paste error for your third point?  Maybe I'm misreading it, but it looks like content from my patch related to the first point.

For the second item, I'm not sure why that assert is in the dispose but it doesn't seem quite right to me either.

**Comment by SteveAlexander** [comment]
@dnfield yep — I copy-pasted the wrong diff! d'oh!

It's updated now with the right one. Thanks for taking a look.

**Comment by dnfield** [comment]
So I'd suggest you do two things:

1. Open a PR for your second issue.  Explain your findings, and it will get some attention and potentially move forward.
2. Open a PR for your third issue, with similar explanation.

If you're not sure how to create a PR, check the [docs](https://help.github.com/articles/creating-a-pull-request/).  Basically, you should:

1. fork this repository so you have a copy on your own GitHub account.  
2. Create a new branch from `master` for each PR you plan to open; e.g. "scroll_position_assert" and "update_child_global_key".  
3. __Write a test that fails before your change__. 
4. Apply your respective changes.  
5. __Verify your test passes and that all other tests pass__.
6. Then open a new pull request for each and the patch/reasoning can be discussed there.

(Sorry if this is explaining things you already know, but feel free to ask questions if any of it isn't clear too).

**Comment by SteveAlexander** [comment]
thanks!

Also, for reference as it might help understand why `ScrollController.dispose()` has `assert(pixels != null)` — I think this was carried over a couple of refactors from `ScrollPositionWithSingleContext.dispose()` in this commit:

https://github.com/flutter/flutter/commit/c288c7064f9e2a9f9e3f4188fcccf1ad103ef61b?diff=split

There's a doc / comment in the commit that explains:

```
  /// The `initialPixels` argument can be null, but in that case it is
  /// imperative that the value be set, using [correctPixels], as soon as
  /// [applyNewDimensions] is invoked, before calling the inherited
  /// implementation of that method.
```

This comment is missing in the code on master now.

So, I believe the semantics of `pixels` have changed since this code was written, and it is now okay for `pixels` to be `null`, although it needs setting (via `correctPixels`) before certain methods are called.

If an app has a `PageStorage` as an `InheritedWidget` then `pixels` will be set properly. From today's code:

```
  /// The default implementation reads the value from the nearest [PageStorage]
  /// found from the [context]'s [ScrollContext.storageContext] property, and
  /// sets it using [correctPixels], if [pixels] is still null.
  ///
  /// This method is called from the constructor, so layout has not yet
  /// occurred, and the viewport dimensions aren't yet known when it is called.
  @protected
  void restoreScrollOffset() {
    if (pixels == null) {
      final double value = PageStorage.of(context.storageContext)?.readState(context.storageContext);
      if (value != null)
        correctPixels(value);
    }
  }
```

So another approach to fixing this is to keep `assert(pixels != null)` in `dispose()`, but ensure that all users of `ScrollPosition` that aren't using `PageStorage` in their context always explicitly call `correctPixels` after creating the `ScrollPosition`.

The fix would be tracking down all times a ScrollPosition or subclass is created, determining if it will exclusively be used in a `PageStorage` context, and if not calling `correctPixels(0.0);` before it is used.

Now this approach sounds fragile — the only time a developer will see that they didn't set `correctPixels` as needed is later on, when the `ScrollPosition` is disposed. And it's hard to see a cause-effect relationship there. This is different than other methods on `ScrollPosition` that require a non-null `pixels` value, as there you can see a direct causal relationship when the code fails.

It also introduces a kind of extra coupling between `ScrollPosition` and the app it is to be used in.

Therefore, I think the right thing to do here is to allow `pixels` to be `null` on `ScrollController.dispose()`.

**Comment by SteveAlexander** [comment]
for anyone who is following along, I believe I've got to the bottom of how things work around my changes in points 2 and 3. I've edited the explanations above.

**Comment by pulyaevskiy** [comment]
Just added a PageView and it started failing on me with the same error. :(

Wondering if there is a way to workaround this without a need to modify Flutter SDK?

**Comment by SteveAlexander** [comment]
@pulyaevskiy the first PR has been merged into the main line of development. I don't know which flutter channel is has reached yet, but it's certainly on Master. So first of all, run flutter on the master channel.

The other two issues are caused by `assert`s being in the wrong place.

So, you can avoid those by running in release mode rather than debug mode.

But maybe you don't want to do that while developing... to avoid the third issue, you can ensure there is a `PageStorage` inherited widget near the base of your widget tree. This will ensure that the `pixels` is initialized, and so you won't get the third issue.

I don't know a workaround for the second issue that doesn't involve changing the SDK.

**Comment by pulyaevskiy** [comment]
> to avoid the third issue, you can ensure there is a PageStorage inherited widget near the base of your widget tree

This doesn't seem to help in my case. Thanks for the information though! I'll see if I can find any other clues.

**Comment by dnfield** [comment]
@SteveAlexander any reason you haven't submitted your patches as PRs?

**Comment by SteveAlexander** [comment]
@dnfield thanks for asking!

I've been super busy with a work project that isn't to do with flutter this past week, and haven't had the hour or two of focused time I think I'd need to figure out how Flutter automated tests work.

Seems I can dash off a quick reply on a tea break, but getting into the coding zone takes me a bit longer.

**Comment by dnfield** [comment]
Got it!  For your second point, I'm not sure any (new) tests would be needed.  Someone else might think so, but it'd be best to just open a PR and get it on the review queue.

For your third, you might do well just having a test based on your failing app - but I understand paring that down takes some time and effort.

**Comment by SteveAlexander** [comment]
@dnfield I've submitted an issue and PR for the third issue, although with a worked example rather than a test.

As this is changing the position of an `assert` rather than actual framework logic, I wonder about the value of testing this specifically.

If the example app isn't enough for this, I'll look at providing a test.

Thanks again for your help on these things.

**Comment by dnfield** [comment]
Tests are best so that we don't accidentally regress this later

**Comment by SteveAlexander** [comment]
I can see the point of that. I'm also concerned that implementation specific tests make the test cases brittle, and raise the level of complexity that contributors need to apprehend before making significant contributions. Do you know whether the flutter project has a set of principles around testing that speak to this trade-off?

**Comment by racknoris** [comment]
@SteveAlexander @dnfield If I understand correctly, this bug manifests itself only in debug mode?
Can it affect release mode in some way?

I have `TabBarView` with 3 tabs, one of which contains `PageView`

**Comment by wdjwxh** [comment]
any news?

**Comment by SteveAlexander** [comment]
I'm not developing in Flutter at the moment, but I think all three issues are now fixed

**Comment by wdjwxh** [comment]
> I'm not developing in Flutter at the moment, but I think all three issues are now fixed

Tks, but It's still wrong when i use sdk 1.12 .  I changed the code follow your suggest, bug a new error occur..  

```
═══════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<RemindPageListState>#9aad8 _reply]
This was determined by noticing that after the widget with the above global key was moved out of its respective previous parents, those previous parents never updated during this frame, meaning that they either did not update at all or updated before the widget was moved, in either case implying that they still think that they should have a child with that global key.
The specific parents that did not update after having one or more children forcibly removed due to GlobalKey reparenting are:
- Padding(padding: EdgeInsets(16.0, 0.0, 16.0, 0.0), dependencies: [Directionality], renderObject: RenderPadding#721e2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
  Padding(padding: EdgeInsets(16.0, 0.0, 16.0, 0.0), dependencies: [Directionality], renderObject: RenderPadding#96cf1 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
  RepaintBoundary(renderObject: RenderRepaintBoundary#cd79f)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
#0      BuildOwner.finalizeTree.<anonymous closure> 
package:flutter/…/widgets/framework.dart:2578
#1      BuildOwner.finalizeTree 
package:flutter/…/widgets/framework.dart:2603
#2      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:775
#3      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:283
#4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1102
...
════════════════════════════════════════════════════════════════════════════════
```

**Comment by wdjwxh** [comment]
> I'm not developing in Flutter at the moment, but I think all three issues are now fixed

Sorry! I just found that the reason is my custom tab code was old.  It's works find when i use your #24821

**Comment by darshankawar** [comment]
Hi @SteveAlexander, considering your [last](https://github.com/flutter/flutter/issues/21630#issuecomment-585649888) comment, do you feel this ticket can be closed ?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
