### ISSUE TITLE
image_picker: Android app CRASH when capturing image using camera

### ISSUE THREAD

**Issue by apgapg** [flutter/flutter#21871]
## Steps to Reproduce
After successfully capturing an image using camera, when i click OK, the app crashes saying 'Unfortunately ** Stopped'. This issue is coming only on Samsung Galaxy J5, J7 devices.   
image_picker: 0.4.10

## Logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
```

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {***.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {***}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4221)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

```
[✓] Flutter (Channel dev, v0.7.5, on Linux, locale en_IN)
    • Flutter version 0.7.5 at /home/master/flutter
    • Framework revision eab5cd9853 (2 weeks ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/master/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /home/master/android-studio-ide-182.4968538-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.3)
    • Android Studio at /home/master/android-studio-ide-182.4968538-linux/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.27.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

```

**Comment by monu0751** [comment]
I am also facing same issue while taking image from image_picker source: camera.
It crashed my app if i used frequently.

Here is the scenario,
I clicked image and save it and image saved.
but if i do same for 2-3 times than my app crashed.

Here, is my code
  Future<bool> saveTimeInOut(MarkTime mk) async {
  try{
    File imagei = null;
    imagei = await ImagePicker.pickImage(source: ImageSource.camera);
    if(imagei!=null) {      
    final tempDir = await getTemporaryDirectory();
    
    String path = tempDir.path;
    int rand = new Math.Random().nextInt(10000);
    
    im.Image image1 = im.decodeImage(imagei.readAsBytesSync());
    imagei.deleteSync();
   
    im.Image smallerImage = im.copyResize(image1, 500); // choose the size here, it will maintain aspect ratio
   
    
    File compressedImage = new File('$path/img_$rand.jpg')..writeAsBytesSync(im.encodeJpg(smallerImage, quality: 50));
    

    
    Dio dio = new Dio();
    FormData formData = new FormData.from({
    "uid": mk.uid,
    "location": mk.location,
    "aid": mk.aid,
    "act": mk.act,
    "shiftid": mk.shiftid,
    "refid": mk.refid,
    "latit": mk.latit,
    "longi": mk.longi,
    "file": new UploadFileInfo(compressedImage, "image.png"),
    });
    print("5");
    Response<String> response1=await dio.post("https://sandbox.ubiattendance.com/index.php/services/saveImage",data:formData);
    //Response<String> response1=await dio.post("http://192.168.0.200/ubiattendance/index.php/services/saveImage",data:formData);
    //Response<String> response1 = await dio.post("https://ubitech.ubihrm.com/services/saveImage", data: formData);
    
    compressedImage.deleteSync();

    Map MarkAttMap = json.decode(response1.data);
    print(MarkAttMap["status"].toString());
    if (MarkAttMap["status"] == 1 || MarkAttMap["status"] == 2)
      return true;
    else
      return false;
    }else{
      print("6");
      return false;
    }
  } catch (e) {
    print(e.toString());
    return false;
  }
}

**Comment by zoechi** [comment]
Where do the forward slashes in below command come from?
It's quite some time I used Windows and don't know how it deals with slashes in paths.

```
flutter build bundle --suppress-analytics --target C:\Users\UBIAPP\AndroidStudioProjects\NewAttFlutter\lib\main.dart --target-platform android-arm64 --depfile C:\Users\UBIAPP\AndroidStudioProjects\NewAttFlutter\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir C:\Users\UBIAPP\AndroidStudioProjects\NewAttFlutter\build\app\intermediates\flutter\debug/flutter_assets --debug
```

**Comment by zoechi** [comment]
> NewAttFlutter\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: Access is denied.
, errno = 5)

probably caused by some antivirus tools or other task that kept the file open and prevented the directory to be deleted and recreated.

Try excluding the directory in Antivirus and if it doesn't help restart your computer.

**Comment by Errichamonda** [comment]
I have the same problem, when I open the camera after 2 seconds the application crashes without any warning or error, not logging anything.

**Comment by zoechi** [comment]
Looks similar to #17950

**Comment by cameronalicia** [comment]
@Errichamonda I'm facing the same issue, my app crashes immediately without warning or any error. Did you ever find a solution?

**Comment by Errichamonda** [comment]
> @Errichamonda I'm facing the same issue, my app crashes immediately without warning or any error. Did you ever find a solution?

No sorry, it started working but sometimes it keeps coming back

**Comment by miduch** [comment]
+1

**Comment by kangwang1988** [comment]
@cameronalicia 
Can you make a minimal demo project which can help reproduce your issue?

**Comment by cameronalicia** [comment]
I figured out that it was a result of a previous package I had used at some point, and when I removed the code required for that package from my AndroidManifest.xml, everything works fine again. So it was not a problem related to this package after all, I apologize.

**Comment by Errichamonda** [comment]
This also happend in iOS. Same code, same plugin version, the permission are set.

**Comment by apgapg** [comment]
Still this is giving crash while clicking image. I am using the latest version of image_picker 0.4.12 and flutter 1.0.0. Mostly this issue is occuring on Samsung devices especially Samsung galaxy j7 (india)

**Comment by Blaypeg** [comment]
I get this on both Android and iOS versions of my app, when taking a picture at the point of confirming the app crashes.
The app closes immediately, no crash report is generated via Crashlytics. When connected to a phone via USB the debug window says connection lost. No stack trace or hint about reason for crash.

**Comment by zoechi** [comment]
Looks like #21102

**Comment by iNima** [comment]
Is there any update on this issue. I have the same problem on iOS.

**Comment by Sayegh7** [comment]
I have recently ran into this same issue. I was able to fix it by clearing some storage space on my device. Just leaving it here as it might help someone else.

**Comment by cyanglaz** [comment]
The crashes should be fixed by https://github.com/flutter/plugins/pull/1509.
However, because the crash is due to the main activity is restarted on Android, the data is lost. I have included a new API in  https://github.com/flutter/plugins/pull/1512 with version 0.5.4 to retrieve the data if you want to. 
If you think your crash is not because of the MainActivity restarting, and the new version of image picker doesn't fix the crash, please fire another issue with details.

**Comment by rahi0** [comment]
Launching lib\main.dart on Redmi Note 5A in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
V/BoostFramework(13877): BoostFramework() : mPerf = com.qualcomm.qti.Performance@fb677be
I/Timeline(13877): Timeline: Activity_launch_request time:46644022 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
I/Timeline(13877): Timeline: Activity_launch_request time:46646451 intent:Intent { act=android.intent.action.GET_CONTENT typ=image/* }
I/art     (13877): Rejecting re-init on previously-failed class java.lang.Class<com.yalantis.ucrop.UCropActivity>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
I/art     (13877):   at android.content.Intent com.yalantis.ucrop.UCrop.getIntent(android.content.Context) (UCrop.java:186)
I/art     (13877):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity, int) (UCrop.java:138)
I/art     (13877):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity) (UCrop.java:128)
I/art     (13877):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:91)
I/art     (13877):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:36)
I/art     (13877):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/art     (13877):   at void io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(java.lang.String, byte[], int) (FlutterNativeView.java:188)
I/art     (13877):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/art     (13877):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/art     (13877):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:323)
I/art     (13877):   at void android.os.Looper.loop() (Looper.java:142)
I/art     (13877):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6393)
I/art     (13877):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (13877):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:933)
I/art     (13877):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:823)
I/art     (13877): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.uoload_image-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.uoload_image-1/lib/arm64, /data/app/com.example.uoload_image-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
I/art     (13877):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     (13877):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     (13877):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     (13877):   at android.content.Intent com.yalantis.ucrop.UCrop.getIntent(android.content.Context) (UCrop.java:186)
I/art     (13877):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity, int) (UCrop.java:138)
I/art     (13877):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity) (UCrop.java:128)
I/art     (13877):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:91)
I/art     (13877):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:36)
I/art     (13877):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/art     (13877):   at void io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(java.lang.String, byte[], int) (FlutterNativeView.java:188)
I/art     (13877):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/art     (13877):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/art     (13877):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:323)
I/art     (13877):   at void android.os.Looper.loop() (Looper.java:142)
I/art     (13877):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6393)
I/art     (13877):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (13877):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:933)
I/art     (13877):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:823)
I/art     (13877): 
E/flutter (13877): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yalantis/ucrop/UCropActivity;
E/flutter (13877): 	at com.yalantis.ucrop.UCrop.getIntent(UCrop.java:186)
E/flutter (13877): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:138)
E/flutter (13877): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:128)
E/flutter (13877): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(ImageCropperDelegate.java:91)
E/flutter (13877): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(ImageCropperPlugin.java:36)
E/flutter (13877): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter (13877): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/flutter (13877): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/flutter (13877): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (13877): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (13877): 	at android.os.Looper.loop(Looper.java:142)
E/flutter (13877): 	at android.app.ActivityThread.main(ActivityThread.java:6393)
E/flutter (13877): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13877): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/flutter (13877): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/flutter (13877): Caused by: java.lang.ClassNotFoundException: com.yalantis.ucrop.UCropActivity
E/flutter (13877): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/flutter (13877): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
E/flutter (13877): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
E/flutter (13877): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (13877): 	... 15 more
E/flutter (13877): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
E/flutter (13877): 	... 15 more
E/flutter (13877): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.uoload_image-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.uoload_image-1/lib/arm64, /data/app/com.example.uoload_image-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/flutter (13877): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/flutter (13877): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/flutter (13877): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (13877): 	... 15 more
E/flutter (13877): 
F/flutter (13877): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (13877): Fatal signal 6 (SIGABRT), code -6 in tid 13877 (le.uoload_image)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/ugg/ugg:7.1.2/N2G47H/V10.2.1.0.NDKMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 13877, tid: 13877, name: le.uoload_image  >>> com.example.uoload_image <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
'
    x0   0000000000000000  x1   0000000000003635  x2   0000000000000006  x3   0000000000000008
    x4   000000000000001d  x5   0000008000000000  x6   0000007f92943000  x7   0000000000000000
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  00000000ffffffff  x14  000000000001ddf0  x15  0030c1e11c03f6a4
    x16  0000007f9203aec8  x17  0000007f91fe8550  x18  000000007141a98c  x19  0000007f929f7b48
    x20  0000000000000006  x21  0000007f929f7aa0  x22  000000000000000b  x23  0000000000200025
    x24  0000007f6fac8d00  x25  0000000000000050  x26  0000007f6ea339e0  x27  0000007f83fe0e40
    x28  0000000000000002  x29  0000007fe3bd7b10  x30  0000007f91fe59e0
    sp   0000007fe3bd7af0  pc   0000007f91fe8558  pstate 0000000060000000
backtrace:
    #00 pc 000000000006b558  /system/lib64/libc.so (tgkill+8)
    #01 pc 00000000000689dc  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023f28  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c9ac  /system/lib64/libc.so (abort+52)
    #04 pc 00000000006b7e48  /data/app/com.example.uoload_image-1/lib/arm64/libflutter.so (offset 0x690000)
    #05 pc 00000000006aca1c  /data/app/com.example.uoload_image-1/lib/arm64/libflutter.so (offset 0x690000)
    #06 pc 00000000006abc74  /data/app/com.example.uoload_image-1/lib/arm64/libflutter.so (offset 0x690000)
    #07 pc 00000000006e5018  /data/app/com.example.uoload_image-1/lib/arm64/libflutter.so (offset 0x690000)
    #08 pc 00000000006b9368  /data/app/com.example.uoload_image-1/lib/arm64/libflutter.so (offset 0x690000)
    #09 pc 00000000006baf58  /data/app/com.example.uoload_image-1/lib/arm64/libflutter.so (offset 0x690000)
    #10 pc 00000000000182c4  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+852)
    #11 pc 0000000000017ec0  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
    #12 pc 00000000000f2508  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
    #13 pc 00000000022b09c0  /system/framework/arm64/boot-framework.oat (offset 0x19d7000) (android.os.MessageQueue.nativePollOnce+140)
    #14 pc 00000000022b25e0  /system/framework/arm64/boot-framework.oat (offset 0x19d7000) (android.os.MessageQueue.next+236)
    #15 pc 00000000022ac188  /system/framework/arm64/boot-framework.oat (offset 0x19d7000) (android.os.Looper.loop+340)
    #16 pc 0000000001a99414  /system/framework/arm64/boot-framework.oat (offset 0x19d7000) (android.app.ActivityThread.main+592)
    #17 pc 00000000000d2a68  /system/lib64/libart.so (art_quick_invoke_static_stub+600)
    #18 pc 00000000000df4b0  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
    #19 pc 000000000042c2c0  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
    #20 pc 000000000042de30  /system/lib64/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_m+1188)
    #21 pc 00000000003a4d94  /system/lib64/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+56)
    #22 pc 000000000061ab48  /system/framework/arm64/boot.oat (offset 0x54e000) (java.lang.reflect.Method.invoke+180)
    #23 pc 0000000002998d00  /system/framework/arm64/boot-framework.oat (offset 0x19d7000) (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+124)
    #24 pc 000000000299a0b0  /system/framework/arm64/boot-framework.oat (offset 0x19d7000) (com.android.internal.os.ZygoteInit.main+1484)
    #25 pc 00000000000d2a68  /system/lib64/libart.so (art_quick_invoke_static_stub+600)
    #26 pc 00000000000df4b0  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
    #27 pc 000000000042c2c0  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
    #28 pc 000000000042bf18  /system/lib64/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+380)
    #29 pc 00000000003467f0  /system/lib64/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+604)
    #30 pc 00000000000a04f0  /system/lib64/libandroid_runtime.so
    #31 pc 00000000000a2b48  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+704)
    #32 pc 000000000000226c  /system/bin/app_process64
    #33 pc 000000000001a7d4  /system/lib64/libc.so (__libc_init+88)
    #34 pc 0000000000001ccc  /system/bin/app_process64
Lost connection to device.
Exited (sigterm)

this is what I got for my android project

**Comment by AresVampire** [comment]
I am still facing this problem when I try to capture an image with the camera and tap on ok, then it crashes the app.

```
static Future<File> pickImageFromCamera() {
    return ImagePicker.pickImage(source: ImageSource.camera);
  }
```

My phone is Galaxy S10e, android version 10. I found that it only crashes on the phone without external storage like SD card.

**Comment by karmazinkd** [comment]
Why this issue is closed? Lot's of people including me experiencing this bug.

> I get this on both Android and iOS versions of my app, when taking a picture at the point of confirming the app crashes.
The app closes immediately, no crash report is generated via Crashlytics. When connected to a phone via USB the debug window says connection lost. No stack trace or hint about reason for crash.

No stack traces, no errors, just `Lost connection to device.` in console.

In my case it works fine for the first time after app starts, then when during the same app session I try to use the camera again I got this crash.

my code:
` await ImagePicker?.pickImage(source: ImageSource.camera)`

flutter `1.17.1`
image_picker `0.6.6+1`

**Comment by Tapaswi846580** [comment]
Upgrading **image_picker** package version to **0.6.6+4** worked for me

**Comment by GENL** [comment]
Same with me. I am using Samsung Galaxi S5. ImagePicker's version is 0.6.7, it did the same with 0.6.6 + 4.
The application hangs and restarts only when I choose an image with the rear camera, when I take selfi (front camera), everything works fine.

**Comment by Tapaswi846580** [comment]
I am also facing this issue sometimes so, I think there will be some problem in the package itself and @flutter needs to fix this. If anyone find the solution of this problem please post it here.

**Comment by PSSubramanya** [comment]
I am facing the same issue as well, it worked fine when I tried first time, but the app is crashing when I confirm the captured image after that, kindly someone help with it

**Comment by MATTYGILO** [comment]
Has anyone found a solution to this

**Comment by houdayec** [comment]
Facing the same issue. Working well, then on picture confirmation, app crashes and debug connection is lost so now way to get logs.

  image_picker: 0.6.7+1


Flutter doctor:

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/houdayec/Development/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/houdayec/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Mi A2 Lite • 08ea1b6c0705 • android-arm64 • Android 10 (API 29)

**Comment by MATTYGILO** [comment]
> Facing the same issue. Working well, then on picture confirmation, app crashes and debug connection is lost so now way to get logs.
> 
> image_picker: 0.6.7+1
> 
> Flutter doctor:
> 
> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
> • Flutter version 1.17.5 at /Users/houdayec/Development/flutter
> • Framework revision [8af6b2f](https://github.com/flutter/flutter/commit/8af6b2f038c1172e61d418869363a28dffec3cb4) (5 weeks ago), 2020-06-30 12:53:55 -0700
> • Engine revision ee76268252
> • Dart version 2.8.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at /Users/houdayec/Library/Android/sdk
> • Platform android-30, build-tools 29.0.2
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 11.4, Build version 11E146
> • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.6)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.47.3)
> • VS Code at /Applications/Visual Studio Code.app/Contents
> • Flutter extension version 3.12.2
> 
> [✓] Connected device (1 available)
> • Mi A2 Lite • 08ea1b6c0705 • android-arm64 • Android 10 (API 29)

I am having the same issue

**Comment by PaccoreIT** [comment]
> Facing the same issue. Working well, then on picture confirmation, app crashes and debug connection is lost so now way to get logs.
> 
> image_picker: 0.6.7+1
> 
> Flutter doctor:
> 
> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
> • Flutter version 1.17.5 at /Users/houdayec/Development/flutter
> • Framework revision [8af6b2f](https://github.com/flutter/flutter/commit/8af6b2f038c1172e61d418869363a28dffec3cb4) (5 weeks ago), 2020-06-30 12:53:55 -0700
> • Engine revision ee76268252
> • Dart version 2.8.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at /Users/houdayec/Library/Android/sdk
> • Platform android-30, build-tools 29.0.2
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 11.4, Build version 11E146
> • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.6)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.47.3)
> • VS Code at /Applications/Visual Studio Code.app/Contents
> • Flutter extension version 3.12.2
> 
> [✓] Connected device (1 available)
> • Mi A2 Lite • 08ea1b6c0705 • android-arm64 • Android 10 (API 29)

+1

**Comment by gigiosilva** [comment]
+1

> Facing the same issue. Working well, then on picture confirmation, app crashes and debug connection is lost so now way to get logs.
> 
> image_picker: 0.6.7+1
> 
> Flutter doctor:
> 
> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
> • Flutter version 1.17.5 at /Users/houdayec/Development/flutter
> • Framework revision [8af6b2f](https://github.com/flutter/flutter/commit/8af6b2f038c1172e61d418869363a28dffec3cb4) (5 weeks ago), 2020-06-30 12:53:55 -0700
> • Engine revision ee76268252
> • Dart version 2.8.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at /Users/houdayec/Library/Android/sdk
> • Platform android-30, build-tools 29.0.2
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 11.4, Build version 11E146
> • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.6)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.47.3)
> • VS Code at /Applications/Visual Studio Code.app/Contents
> • Flutter extension version 3.12.2
> 
> [✓] Connected device (1 available)
> • Mi A2 Lite • 08ea1b6c0705 • android-arm64 • Android 10 (API 29)

+1

**Comment by Alexddsilva** [comment]
> Facing the same issue. Working well, then on picture confirmation, app crashes and debug connection is lost so now way to get logs.
> 
> image_picker: 0.6.7+1
> 
> Flutter doctor:
> 
> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
> • Flutter version 1.17.5 at /Users/houdayec/Development/flutter
> • Framework revision [8af6b2f](https://github.com/flutter/flutter/commit/8af6b2f038c1172e61d418869363a28dffec3cb4) (5 weeks ago), 2020-06-30 12:53:55 -0700
> • Engine revision ee76268252
> • Dart version 2.8.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at /Users/houdayec/Library/Android/sdk
> • Platform android-30, build-tools 29.0.2
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 11.4, Build version 11E146
> • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.6)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.47.3)
> • VS Code at /Applications/Visual Studio Code.app/Contents
> • Flutter extension version 3.12.2
> 
> [✓] Connected device (1 available)
> • Mi A2 Lite • 08ea1b6c0705 • android-arm64 • Android 10 (API 29)

+1

**Comment by AsjadSiddiqui** [comment]
Anyone found a Solution ?
The App just closes and restarts.
Happens on Multi Image Picker package too.

**Comment by pumuckelo** [comment]
For me the app crashes if I try to access image picker to times in a row.
For Example if I cancel on the first time it will crash on the second time

**Comment by AsjadSiddiqui** [comment]
> For me the app crashes if I try to access image picker to times in a row.
> For Example if I cancel on the first time it will crash on the second time

Same here, works sometimes, but crashes most of the times.

**Comment by pumuckelo** [comment]
it was working some versions ago though :/

**Comment by AsjadSiddiqui** [comment]
@pumuckelo have you tried downgrading the version in the pubspec.yaml file ?
Does it work ?

**Comment by pumuckelo** [comment]
no, not yet

**Comment by cafererensimsek** [comment]
Same issue, was working fine yesterday, today crashes after okaying the image

**Comment by pumuckelo** [comment]
> Same issue, was working fine yesterday, today crashes after okaying the image

@AsjadSiddiqui @cafererensimsek @Alexddsilva @PaccoreIT @MATTYGILO  this problem only seem exist if you have the app in debug mode.

**Solution:**
If you build the apk and run it on your phone it does not crash anymore. 

Hope this also works for you

**Comment by AsjadSiddiqui** [comment]
@pumuckelo Nope, it still crashes.
I have tried, with many different versions of flutter, even tried running in profile mode and release mode, it still crashes everytime.

**Comment by pumuckelo** [comment]
@AsjadSiddiqui Did You build the apk file and installed it on your android device? 

I didn't test it on ios though but it was crashing on Android too if I run it via console or VS code but after releasing the apk and installing it on my phone manually it didn't crash anymore

**Comment by AsjadSiddiqui** [comment]
@pumuckelo I tried everything, from releasing the app to play store using app bundle to building release build and installing manually.
Still crashes.

**Comment by cafererensimsek** [comment]
> > Same issue, was working fine yesterday, today crashes after okaying the image
> 
> @AsjadSiddiqui @cafererensimsek @Alexddsilva @PaccoreIT @MATTYGILO  this problem only seem exist if you have the app in debug mode.
> 
> **Solution:**
> If you build the apk and run it on your phone it does not crash anymore. 
> 
> Hope this also works for you 

My solution was to delete image_picker_save from my dependencies. Appareantly they can't exist at the same time. I've read that if the required permissions are taken manually before launching the camera, that also works.

**Comment by pumuckelo** [comment]
@AsjadSiddiqui damn that sucks.

What did you try so far? Is it possible that you somehow try to call the pickImage function while there is still one open? Or accidentally call it twice? 
Did you try deleting image_picker_save if youre using it?

**Comment by pumuckelo** [comment]
You should also check the RAM usage with the dev tools, maybe the ram does not get cleared after closing the image picker and then if you try to open it the second time it exceeds its maximum

**Comment by zfc0812** [comment]
> > Facing the same issue. Working well, then on picture confirmation, app crashes and debug connection is lost so now way to get logs.
> > image_picker: 0.6.7+1
> > Flutter doctor:
> > [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
> > • Flutter version 1.17.5 at /Users/houdayec/Development/flutter
> > • Framework revision [8af6b2f](https://github.com/flutter/flutter/commit/8af6b2f038c1172e61d418869363a28dffec3cb4) (5 weeks ago), 2020-06-30 12:53:55 -0700
> > • Engine revision ee76268252
> > • Dart version 2.8.4
> > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> > • Android SDK at /Users/houdayec/Library/Android/sdk
> > • Platform android-30, build-tools 29.0.2
> > • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> > • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> > • All Android licenses accepted.
> > [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> > • Xcode at /Applications/Xcode.app/Contents/Developer
> > • Xcode 11.4, Build version 11E146
> > • CocoaPods version 1.9.1
> > [✓] Android Studio (version 3.6)
> > • Android Studio at /Applications/Android Studio.app/Contents
> > • Flutter plugin version 45.1.1
> > • Dart plugin version 192.7761
> > • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> > [✓] VS Code (version 1.47.3)
> > • VS Code at /Applications/Visual Studio Code.app/Contents
> > • Flutter extension version 3.12.2
> > [✓] Connected device (1 available)
> > • Mi A2 Lite • 08ea1b6c0705 • android-arm64 • Android 10 (API 29)
> 
> +1

I am facing the some issue as well. Also on Mi A2 Lite. It's production app, not debug.

**Comment by juampiq6** [comment]
Having same issue here, only in production, but not whit my phone, must be some kind of RAM issue. App restarts every time the user picks and image and confirms it.
