### ISSUE TITLE
Android Studio flutter and dart plugins not recognized by flutter doctor , but plugins are installed

### ISSUE THREAD

**Issue by ZayniddinMamarasulov** [flutter/flutter#21881]
Hello everybody , I am trying to install flutter on ubuntu , android studio flutter and dart plugins have been installed , but `flutter doctor` said that they are not installed. At the beginning flutter doctor didn't find my android studio and sdk even if they are installed, then fixed this problems by configuring custom directories for android studio and sdk with this commands : 
```
flutter config --android-studio-dir=/my/local/path/for/android/studio
flutter config --android-sdk=/my/local/path/for/sdk
``` 
but couldn't find any solution how to show android studio installed plugins directory for flutter doctor
```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_US.UTF-8)
    • Flutter version 0.7.3 at /home/zayniddin/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/zayniddin/Documents/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /home/zayniddin/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio
    • Android Studio at /home/zayniddin/Documents/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/zayniddin/Documents/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /snap/intellij-idea-community/77
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```
any solutions ?, please help me

**Comment by evelyne24** [comment]
Hey, I'm on Mac but I had to _manually_ install the Flutter and Dart plugin in Android Studio, by going to `Preferences > Plugins > Browse Repositories > find the plugins, install and restart`.  Have you tried that?

<img width="1023" alt="screen shot 2018-09-14 at 23 54 02" src="https://user-images.githubusercontent.com/239384/45574733-a4c92780-b879-11e8-8077-7c808fd34605.png">

**Comment by ZayniddinMamarasulov** [comment]
> Hey, I'm on Mac but I had to install the Flutter and Dart plugin in Android Studio, by going to `Preferences > Plugins > Browse Repositories > find the plugins, install and restart`. Have you tried that?
> 
> <img alt="screen shot 2018-09-14 at 23 54 02" width="1023" src="https://user-images.githubusercontent.com/239384/45574733-a4c92780-b879-11e8-8077-7c808fd34605.png">

yes I installed plugins , but flutter doctor didn't recognize

**Comment by zoechi** [comment]
`flutter doctor -v` also doesn't show your Android Studio version

```
[✓] Android Studio (version 3.1)
```

What Android Studio version do you have installed?

**Comment by febs** [comment]
I got that very same behavior on Android Studio 3.2 RC3:

`[✓] Android Studio (version 3.2)
    • Android Studio at /home/fabio/DevTools/beta/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)`

**Comment by zoechi** [comment]
Try with `master` channel. I think to remember there was a fix recently to make the plugins compatible with Android Studio 3.2.

**Comment by febs** [comment]
That partially solved the issue. Now both my copies of Android Studio (3.1 and 3.2beta) are recognized and they plug-ins also are.
But :-D the flutter doctor now also identifies a non-existent third Android Studio installation (with no version attached according to it) and the missing plugins.

Here's the output:

```
 [✓] Android Studio (version 3.1)
    • Android Studio at /home/fabio/android-studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
[✓] Android Studio (version 3.2)
    • Android Studio at /home/fabio/DevTools/beta/android-studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[✓] Android Studio
    • Android Studio at /home/fabio/DevTools/beta/android-studio/
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/fabio/DevTools/beta/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2620](https://github.com/flutter/flutter-intellij/issues/2620) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zoechi** [comment]
reopening according to the comment to https://github.com/flutter/flutter-intellij/issues/2620

**Comment by SPSpisoft** [comment]
This is also the problem for me :(
In addition, when the new project is launched in Android Studio, it will not work after the final stage (Finish) And to get out of this situation is forced to end task..
Look at the picture ..

![flutter_issue](https://user-images.githubusercontent.com/11540724/45926785-03d01180-bef6-11e8-85d1-16d043b95d00.png)

I look forward to fixing this problem impatiently
Thanks

**Comment by SPSpisoft** [comment]
Hi everyone
This problem has been solved fortunately for me. But unfortunately I can not exactly say how it was solved!
Because I did some things at once. Anyway I write what I did, I hope your problem will be solved.

- I updated SDK
- Then I updated JDK
and change JAVA_HOME in Environment Variable
- in Flutter console run `flutter doctor --android-licenses`
And in answer to the questions: `y <Enter>`
- in Flutter console run `flutter create <TEST_APP>`

Now, After running `flutter doctor -v` the problem is solved !

The only remaining problem is that it's not possible to build a new project through Android Studio
But the project that was made through the flutter console can be opened and edit in Android Studio

Good luck to all friends and flutter team :+1:

**Comment by vinceyoumans** [comment]
> I got that very same behavior on Android Studio 3.2 RC3:
> 
> `[✓] Android Studio (version 3.2)`
> `• Android Studio at /home/fabio/DevTools/beta/android-studio`
> `✗ Flutter plugin not installed; this adds Flutter specific functionality.`
> `✗ Dart plugin not installed; this adds Dart specific functionality.`
> `• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)`

I have the same problem...  have always had it.  did you ever resolve this?

**Comment by GhostLee** [comment]
> That partially solved the issue. Now both my copies of Android Studio (3.1 and 3.2beta) are recognized and they plug-ins also are.
> But :-D the flutter doctor now also identifies a non-existent third Android Studio installation (with no version attached according to it) and the missing plugins.
> 
> Here's the output:
> 
> ```
>  [✓] Android Studio (version 3.1)
>     • Android Studio at /home/fabio/android-studio
>     • Flutter plugin version 28.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> [✓] Android Studio (version 3.2)
>     • Android Studio at /home/fabio/DevTools/beta/android-studio
>     • Flutter plugin version 28.0.2
>     • Dart plugin version 181.5616
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> [✓] Android Studio
>     • Android Studio at /home/fabio/DevTools/beta/android-studio/
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • android-studio-dir = /home/fabio/DevTools/beta/android-studio/
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> ```

So have u ever tried to move the configuration files of Android Studio?I just move these files and my flutter cannot recognized those plugins.

**Comment by zoechi** [comment]
Are you using Android Studio Canary 3.4?
This is not yet supported.

**Comment by VEWapps** [comment]
I was having the exact same issue, using IntelliJ IDEA Community version on Linux Mint.
I opened Android Studio to make sure that I had installed the dart and flutter plug-ins (which I had already done), I changed nothing, and closed Android Studio.
Then, when I ran flutter doctor again, the problem was solved. Additionally, the version of Android Studio appeared (before it had just said "Android Studio").
So, problem solved, I guess? But I have no idea how or why.

**Comment by zoechi** [comment]
Please check if you can still reproduce in latest master. 
Tentatively closing as duplicate of #26928.
Please add a comment to have it reopened in case you can still reproduce.

**Comment by nvintz22** [comment]
What I did is I checkout to master branch after installing the Flutter and Dart plugins. Then run flutter doctor. 
Then it works.

**Comment by ZackPashkin** [comment]
Solved on fresh Ubuntu 18.04 by apt-get install git

**Comment by ZackPashkin** [comment]
Solved by settings --> plugins--> search in repositories --> flutter 
then restart android studio

**Comment by iverc** [comment]
Happened to me on Android Studio 3.3. To solve the issue:
- Run `flutter doctor --android-licenses` and accept all licenses.
- Run `flutter doctor` again, it should be able to recognize plugins at this point.

**Comment by poos** [comment]
When you install plugins finished, android studio remind you restart it. Maybe you should **Manually restart**. Then, run flutter doctor again. It will be ok.

**Comment by giobio941** [comment]
for MY issue for it to be solved. I have intelliJ AND Android Studio. I had to install Flutter and Dart on the IntelliJ Application. Once installed, I ran flutter doctor in Android Studio and all issues were resolved.

**Comment by xurshidt90** [comment]
У меня тоже была такая проблема. Я удалил _IntelliJ_ и занова запустил комманда (`flutter doctor`) и все работал

**Comment by patelkrunal78** [comment]
Very Similar To [Flutter plugin not installed error;. When running flutter doctor](https://icetutor.com/question/flutter-plugin-not-installed-error-when-running-flutter-doctor)

**Comment by milanpatel18** [comment]
Already Solved At #11940

**Comment by TheArslan** [comment]
> That partially solved the issue. Now both my copies of Android Studio (3.1 and 3.2beta) are recognized and they plug-ins also are.
> But :-D the flutter doctor now also identifies a non-existent third Android Studio installation (with no version attached according to it) and the missing plugins.
> 
> Here's the output:
> 
> ```
>  [✓] Android Studio (version 3.1)
>     • Android Studio at /home/fabio/android-studio
>     • Flutter plugin version 28.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> [✓] Android Studio (version 3.2)
>     • Android Studio at /home/fabio/DevTools/beta/android-studio
>     • Flutter plugin version 28.0.2
>     • Dart plugin version 181.5616
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> [✓] Android Studio
>     • Android Studio at /home/fabio/DevTools/beta/android-studio/
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • android-studio-dir = /home/fabio/DevTools/beta/android-studio/
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> ```

Did you find the solution of this? Can you please explain me

**Comment by hiep294** [comment]
Here is my found solution in my linux laptop, first is to set permission for flutter
`chown -R YOUR_USERNAME YOUR_FLUTTER_DIRECTORY`
for instanse:
`chown -R hiep294 /opt/flutter`
luckily, everything worked!

**Comment by mkbond777** [comment]
> Hey, I'm on Mac but I had to install the Flutter and Dart plugin in Android Studio, by going to `Preferences > Plugins > Browse Repositories > find the plugins, install and restart`. Have you tried that?
> 
> <img alt="screen shot 2018-09-14 at 23 54 02" width="1023" src="https://user-images.githubusercontent.com/239384/45574733-a4c92780-b879-11e8-8077-7c808fd34605.png">

In my case I updated my plugin and it worked. Thanks anyways.

**Comment by bryanpei** [comment]
> Here is my found solution in my linux laptop, first is to set permission for flutter
> `chown -R YOUR_USERNAME YOUR_FLUTTER_DIRECTORY`
> for instanse:
> `chown -R hiep294 /opt/flutter`
> luckily, everything worked!

Thanks! This fixed my issue. I ran `sudo chown -R YOUR_USERNAME YOUR_FLUTTER_DIRECTORY` then the problem is fixed.

**Comment by srinivasugt** [comment]
I had the same issue (Flutter plugin not installed; this adds Flutter specific functionality.). So I followed this steps which got resolved:

Under Tools>SDK Manager
On the left side panel, click on Plugins & after selecting Plugins link, on right side you search for Flutter & on the search result Flutter will be displayed, just click "Install" button which automatically installs the Dart as well & post installation. It will ask to restart IDE. Click on Restart IDE. And check for flutter doctor.. your problem will be resolved...

Happy learning...

**Comment by srinivasugt** [comment]
Similarly, I fixed for Visual Studio Code:

Flutter extension not installed; install from                                                                           https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

Steps followed to install flutter & dart in VS Code:

File > Preferences > Extensions 
Search for Flutter & click on "install" link & same for Dart also, search for Dart & click on "install" link.. Restart VS Code.. Problem is solved..

Happy learning...

**Comment by srinivasugt** [comment]
Problem on IntelliJ IDE :
Flutter plugin not installed; this adds Flutter specific functionality.                                               X Dart plugin not installed; this adds Dart specific functionality. 

Fixed by doing:

File > Settings > Plugins (found on left side). Search for Flutter & click on Install, it will also install Dart along with Flutter... We need to click on "Accept" button during installation process..

Happy learning...

**Comment by SeasonLeee** [comment]
I know this has been closed, but I still have the exact same issue where `flutter doctor`
printing the plugin of my Android Studio is not installed.
Help!!! Please...

And here's my flutter doctor output:
![image](https://user-images.githubusercontent.com/13610283/73851990-6450bc00-4869-11ea-8691-83450752bdcd.png)

And I have just upgraded my Android Studio to latest, I think.
![image](https://user-images.githubusercontent.com/13610283/73852097-94985a80-4869-11ea-8a22-072e932659d7.png)

**Comment by giobio941** [comment]
Try to install the same plugins on your intelliJ. Verify they have been installed and try to run flutter doctor on android studio.

**Comment by SeasonLeee** [comment]
@giobio941 Thanks for the reply, but I have the plugin installed already...

And this is the screenshot of my plugin setting of Flutter, which shows installed
![image](https://user-images.githubusercontent.com/13610283/73855573-353d4900-486f-11ea-8cdc-eea4e2e13b5a.png)

And I have also tried uninstall it and reinstalled it, but no, nothing works...

**Comment by giobio941** [comment]
This is the issue I've had before. I had intelliJ installed first, then i downloaded android studio. For some odd reason, android studio didn't recognize the plugins. After running the flutter doctor many times, i tried to install the flutter plugins on Intellij. Once i installed it on IntelliJ, I went back to android studio and it recognized the plugins. If you've tried that, Imm sorry if it didn't help.

**Comment by SeasonLeee** [comment]
@giobio941 Thanks for your advice, and I should notice that you said intellij! 

And oh my god, I do have a intellij installed!!! What a moron was I!!!

It works now!
![image](https://user-images.githubusercontent.com/13610283/73861599-37f06c00-4878-11ea-931f-48b25d936d12.png)


So basically, the fact that I didn't realize the fluter doctor was reporting the intellij not Android Studio... my stupid eyes... sorry, again, and super thank you for your awesome help!!!!

Thanks!!! hahaha

**Comment by whyte624** [comment]
I see that issue is closed, however I tried a lot of things from this issue, and did not solve the problem.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266,
    locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available
```

I have tried:

- updated flutter
- updated android SDK
- installed plugins both for Android Studio and Intellij Idea
- disable and enable back plugins
- cleared flutter bin/cache
- restarted everything multiple times 😀

Is there any permanent solution for this issue?

**Comment by SeasonLeee** [comment]
@whyte624 Hi! You need to navigate to your IntelliJ IDEA to install flutter related plugin on that IDE as well, even you won't use it to develop Flutter App.

**Comment by iribeirodev** [comment]
It worked for me after running flutter doctor --android-licenses:
$ flutter doctor --android-licenses
Warning: File /home/myuser/.android/repositories.cfg could not be loaded.       
All SDK package licenses accepted.======] 100% Computing updates..

$flutter doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.43.2)

Then I started Android Studio and ran flutter doctor again
$flutter doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.43.2)
[!] Connected device
    ! No devices available
