### ISSUE TITLE
iOS - swift - Replace splash screen in native to flutter transition

### ISSUE THREAD

**Issue by nishant-thite** [flutter/flutter#21949]
Splash screen is appearing whenever flutter view is rendered inside swift app.
I want to show an activity indicator instead of default splash screen of project, while the flutter view setup is going on. *But I am not able to find a call back* when to stop my activity indicator.
Specifically which methods tackle these view transitions. Are there any delegates, I can use?
I have created a sample project for a quick run.
https://github.com/nishant-thite/Flutter_Swift

Please see below gif for a quick view

![flutter_swift_spalsh](https://user-images.githubusercontent.com/35624316/45641549-6dee4e00-bad3-11e8-8783-539121034677.gif)

**Comment by nishant-thite** [comment]
Hi @cbracken @HansMuller @Hixie ,
Any thoughts 😀 We want to use Flutter as mainstream platform, but this is a blocker.. Any help / pointer will be great!

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by nishant-thite** [comment]
Hi @zoechi 
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.8.2 at /Users/nishantt/Documents/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/nishantt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/nishantt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 5EA7C391-57E5-4022-84B7-9F08FA6A3DD5 • ios • iOS 11.4 (simulator)

• No issues found!

```

**Comment by nishant-thite** [comment]
Please refer to https://github.com/nishant-thite/Flutter_Swift to see my usage of flutter in swift project

**Comment by cbracken** [comment]
@nishant-thite I'm not 100% clear on the issue you're trying to handle, but would it be fixed by [this PR](https://github.com/flutter/engine/pull/6135)?

**Comment by nishant-thite** [comment]
@cbracken , yes this is exactly what I was looking for! Thanks a lot!

**Comment by Coder-XI** [comment]
I still have this problem, how to remove splash screen in native to flutter transition?
