### ISSUE TITLE
android_alarm_manager should detect when you haven't called AlarmService.setPluginRegistrant and throw an exception explaining things

### ISSUE THREAD

**Issue by Seedorf161** [flutter/flutter#21969]
I've been trying to integrate the `android_alarm_manager` plugin but got this error after integration.

```
I/AlarmService(20006): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at android.os.Looper.loop(Looper.java:148)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(20006): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
E/flutter (20006): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (20006): PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference, null)
E/flutter (20006): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter (20006): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (20006): <asynchronous suspension>
E/flutter (20006): #2      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:70:10)
E/flutter (20006): <asynchronous suspension>
E/flutter (20006): #3      main (file:///C:/Users/Saheed%20Olalekan/course_alert/lib/main.dart:75:29)
E/flutter (20006): <asynchronous suspension>
E/flutter (20006): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (20006): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Error -32601 received from application: Method not found
E/flutter (20006): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (20006): MissingPluginException(No implementation found for method AlarmService.initialized on channel plugins.flutter.io/android_alarm_manager_background)
E/flutter (20006): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter (20006): <asynchronous suspension>
E/flutter (20006): #1      _alarmManagerCallbackDispatcher (package:android_alarm_manager/android_alarm_manager.dart:46:12)
E/flutter (20006): #2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (20006): #3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
```

**flutter doctor -v**

```
[√] Flutter (Channel master, v0.7.4-pre.21, on Microsoft Windows [Version 10.0.16299.125], locale en-NG)
    • Flutter version 0.7.4-pre.21 at C:\Users\Saheed Olalekan\Documents\flutter
    • Framework revision 7cebaac985 (3 weeks ago), 2018-08-29 21:53:39 -0700
    • Engine revision 252da48082
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Saheed Olalekan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.12.2

[√] Connected devices (1 available)
    • Infinix NOTE 3 • 0179710711403422 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/20697#issuecomment-413837702 is about the same error message

**Comment by kashlo** [comment]
same problem

```
E/flutter (25501): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (25501): PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference, null)
```

**Comment by MartinHlavna** [comment]
Affects me as well. Plugin was working great for a while, then on Monday it started throwing this error. AFAIK nothing related to AlarmManager was changed lately. Crash happens after calling 

`await AndroidAlarmManager.initialize()` 

But it happens just after first call. If I call it again all works as expected.

`/AlarmService(22848): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22848): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22848): java.lang.IllegalStateException: registrar.activity() must not be null`

Application class exists, is referenced in AndroidManifest.xml, i is being called correctly and contains

`AlarmService.setPluginRegistrant(this);`

**Comment by MartinHlavna** [comment]
I have found the problem.

Since AlarmManager uses separate isolate, any plugin that is used in scheduled code needs to be initialized for AlarmManager separately. I was using 

`GeneratedPluginRegistrant.registerWith(registry);`

as stated [here](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager). After adding geocoder plugin error mentioned in this thread started to rise. 

Workaround is to only intiailize plugins needed in scheduled code e.g.

`SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
`

In addition to thrown error this could also result in some plugins not initialized for Alarm manager. It was just a coincidence that second time everything worked.

**Comment by rupert2133** [comment]
@MartinHlavna Cool! Where should we put the `SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));` example? What if I initialized AlarmManager only?

**Comment by MartinHlavna** [comment]
@rupert2133 This was the problem in my case. Your case might be different. The example I have provided belongs to application class instead of `GeneratedPluginRegistrant` (although better solution would be to find out why `GeneratedPluginRegistrant` fails in this case). Consult [this example](https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/plugins/androidalarmmanagerexample/Application.java) for Application class example.

**Comment by alexandranb** [comment]
This plugin is driving me insane. Can somebody tell mw where do I put the AlarmService class?

Thanks in advance

**Comment by alexandranb** [comment]
So, I found out why I couldn't use exactly the example from the plugin because I don't use Java, I use kotlin, so at least I found out where I needed too add it. It only took me 18 hours :) now I still need to deal with the error the first person mentioned.

Thanks

**Comment by MartinHlavna** [comment]
@alexandranb 

You can try workaround I have used. Most likely, one of the other plugins you are using (which is initialized with GeneratedPluginRegistrant) is throwing this error. If I remember correctly, in my case it was Geocoder plugin or one of its dependencies which was trying to access FlutterActivity during initialization, that is null in this context.

**Comment by alexandranb** [comment]
Hi @MartinHlavna ,

I managed to set it up to use Java files instead of kotlin, and still the same error. I will try to comment one at the time, the plugin that might give this error and try to fix it.

Thank you

**Comment by alexandranb** [comment]
Hello back,

@MartinHlavna I managed to isolate the plugin that gives me the error. Is the location plugin. Do you have any idea how to still use it and initialize manually somehow somewhere?

Thanks

**Comment by MartinHlavna** [comment]
You can initialize only plugins that are neccessary for your scheduled code by extracting lines from GeneratedPluginRegistrant (and imports of course). Still, it is just a workaround.

**Comment by alexandranb** [comment]
I don't need the location plugin in my scheduled tasks, however, I still can't remove it from pubspeck, as I need it in some other pages. However, the app still throws error.

**Comment by MartinHlavna** [comment]
1. Copy GeneratedPluginRegistrant to AndroidAlarmManagerPluginRegistrant
2. Remove unneccessary plugin initializations from AndroidAlarmManagerPluginRegistrant 
3. Use AndroidAlarmManagerPluginRegistrant in [Application](https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/plugins/androidalarmmanagerexample/Application.java) class instead of GeneratedPluginRegistrant

This way your main app code will run using GeneratedPluginRegistrant and will initialize ALL plugins. Hovewer scheduled code (which runs in separate dart isolate and does not share heap memory with rest of the app) will use AndroidAlarmManagerPluginRegistrant and thus will have access only to the subset of plugins initialized in AndroidAlarmManagerPluginRegistrant.

**Comment by alexandranb** [comment]
Hello all,

Happy new year to everybody! I kind of did something like that before your response @MartinHlavna  and it worked only for one plugin out of the 2. It worked only for the Geolocator plugin and not for Location plugin. However this is sufficient for me for now, as I managed to switch the Location plugin with the Geolocator plugin and made my app work. Thank you so much for your response. If you have any programming blog or youtube channel, I would very much like to follow your apps ad progress.

Thank you

**Comment by Hixie** [comment]
In addition to fixing the docs, the code should probably throw a more useful exception when it notices it's about to call a method on null, e.g. pointing to the documentation.

**Comment by JaiSachdeva** [comment]
> I have found the problem.
> 
> Since AlarmManager uses separate isolate, any plugin that is used in scheduled code needs to be initialized for AlarmManager separately. I was using
> 
> `GeneratedPluginRegistrant.registerWith(registry);`
> 
> as stated [here](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager). After adding geocoder plugin error mentioned in this thread started to rise.
> 
> Workaround is to only intiailize plugins needed in scheduled code e.g.
> 
> `SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")); `
> 
> In addition to thrown error this could also result in some plugins not initialized for Alarm manager. It was just a coincidence that second time everything worked.

Registering only AlarmManagerPlugin worked for me -
`class Application : FlutterApplication(), PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        AlarmService.setPluginRegistrant(this)
    }

    override fun registerWith(pluginRegistry: PluginRegistry?) {
        //GeneratedPluginRegistrant.registerWith(pluginRegistry);
        AndroidAlarmManagerPlugin.registerWith(pluginRegistry!!.registrarFor("io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin"))
    }

}`

**Comment by sathishRA91** [comment]
Flutter alarm manager not working in my code please help to fix it
Application class and manifest file created as per plugin
//Application Class
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.androidalarmmanager.AlarmService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        AlarmService.setPluginRegistrant(this);
    }
// manifest File

<application
        android:name=".Application"
        android:label="alaram_manager_test"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <service
            android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
            android:exported="false"/>


    </application>

//Main class

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}


Future<void> initAlaram()async
{
await AndroidAlarmManager.initialize();

 await AndroidAlarmManager.periodic(
     const Duration(seconds: 5), helloAlarmID, printHello);
}

void printHello() {

print(" Hello, world!");


setState(() {
  _counter++;
});

**Comment by Hixie** [comment]
I have updates to the README on a branch somewhere, and I'll submit those, but as noted above this bug is really about better detection at runtime.

**Comment by Manpreet-Kaur14** [comment]
> I have found the problem.
> Since AlarmManager uses separate isolate, any plugin that is used in scheduled code needs to be initialized for AlarmManager separately. I was using
> GeneratedPluginRegistrant.registerWith(registry);
> as stated here. After adding geocoder plugin error mentioned in this thread started to rise.
> Workaround is to only intiailize plugins needed in scheduled code e.g.
> SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")); 
> In addition to thrown error this could also result in some plugins not initialized for Alarm manager. It was just a coincidence that second time everything worked.
> 
> Registering only AlarmManagerPlugin worked for me -
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         AlarmService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(pluginRegistry: PluginRegistry?) {
>         //GeneratedPluginRegistrant.registerWith(pluginRegistry);
>         AndroidAlarmManagerPlugin.registerWith(pluginRegistry!!.registrarFor("io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin"))
>     }
> 
> }

Still this code is not working in Flutter. Can you Please provide proper code.

**Comment by martinory** [comment]
> > I have found the problem.
> > Since AlarmManager uses separate isolate, any plugin that is used in scheduled code needs to be initialized for AlarmManager separately. I was using
> > `GeneratedPluginRegistrant.registerWith(registry);`
> > as stated [here](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager). After adding geocoder plugin error mentioned in this thread started to rise.
> > Workaround is to only intiailize plugins needed in scheduled code e.g.
> > `SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")); `
> > In addition to thrown error this could also result in some plugins not initialized for Alarm manager. It was just a coincidence that second time everything worked.
> 
> Registering only AlarmManagerPlugin worked for me -
> 
> ```kotlin
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         AlarmService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(pluginRegistry: PluginRegistry?) {
>         //GeneratedPluginRegistrant.registerWith(pluginRegistry);
>         AndroidAlarmManagerPlugin.registerWith(pluginRegistry!!.registrarFor("io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin"))
>     }
> 
> }
> ```

The android_alarm_manager works well when not having AndroidX-compatibility added. When migrating to AndroidX, it doesn't work. The solution looks more like a workaround to me. This solves the **PlatformException (PlatformException(error, registrar.activity() must not be null, null))**-issue, but then I get exceptions about that other plugins are not registered in the main thread.

**Comment by Manpreet-Kaur14** [comment]
Thanks a lot for this. But I want to know that how *android alarm manager*
works on *IOS*. I did all the possible changes that I know but it doesn't
work.
My app is crash when I ran:

                 *AndroidAlarmManager.initialize();*

If you know that how this works. Then please guide me how I Execute this.

*Thanks & Regards*
Manpreet Kaur

**Comment by bkonyi** [comment]
@martinory this issue has been closed as the problem described has been resolved. If you have other problems, please file a new issue.

@Manpreet-Kaur14 the `android_alarm_manager` plugin only has support for Android, which is likely why you're seeing a crash on iOS.

**Comment by ahmadalibaloch** [comment]
Tried all above solutions, still getting this:

`I/AndroidAlarmManagerPlugin(28873): onAttachedToEngine
W/FlutterEnginePluginRegistry(28873): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@ecaeeb1) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f07bf96).
I/AndroidAlarmManagerPlugin(28873): onAttachedToEngine
E/MethodChannel#(28873): Parameter messenger must not be null.
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onAttachedToEngine(AndroidAlarmManagerPlugin.java:90)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.registerWith(AndroidAlarmManagerPlugin.java:61)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at com.xoredge.sehrireminder.Application.registerWith(Application.kt:18)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:179)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugins.androidalarmmanager.AlarmService.startBackgroundIsolate(AlarmService.java:64)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:119)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(28873): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (28873): /data/user/0/com.xoredge.sehrireminder/app_flutter
I/AlarmService(28873): AlarmService started!
E/flutter (28873): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference, null)
E/flutter (28873): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter (28873): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (28873): <asynchronous suspension>
E/flutter (28873): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28873): #3      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:96:35)
E/flutter (28873): #4      _MyHomePageState.initState (package:sehrireminder/main.dart:45:25)
E/flutter (28873): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (28873): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (28873): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (28873): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (28873): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (28873): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (28873): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (28873): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (28873): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (28873): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (28873): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (28873): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (28873): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (28873): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (28873): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (28873): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (28873): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (28873): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28873): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28873): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (28873): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (28873): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (28873): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (28873): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framewo`
