### ISSUE TITLE
Snackbar position incorrect when used with bottomNavigationBar and centerDocked floatingActionButton

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#21976]
## Steps to Reproduce

Implement a `bottomNavigationBar` with a `floatingActionButton` (eg. position `centerDocked`) in your application.

```dart
return MaterialApp(
  title: 'Test app',
  home: Scaffold(
    body: Home(),
    floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
    floatingActionButton: FloatingActionButton(
      child: Text('Test'),
      onPressed: () {},
    ),
    bottomNavigationBar: BottomNavigationBar(
      currentIndex: 0,
      items: [
        BottomNavigationBarItem(
          icon: new Icon(Icons.home),
          title: new Text('Home'),
        ),
        BottomNavigationBarItem(
          icon: new Icon(Icons.mail),
          title: new Text('Messages'),
        ),
        BottomNavigationBarItem(
            icon: Icon(Icons.person), 
            title: Text('Profile')),
      ],
    ),
  ),
);
```

According to the [material design (section > snackbars)](https://material.io/design/components/app-bars-bottom.html#behavior), the snackbar should be displayed above the button and navigation. 

The behaviour in Flutter is a bit different: the action button will be pushed away.
So the order with the displayed snackbar is the following: 
1. bottomNavigation
2. snackbar
3. actionButton (pushed away).

Without snackbar:
![image](https://user-images.githubusercontent.com/40127061/45671678-5c826180-bb26-11e8-883b-cd90aa7b9f9b.png)

With snackbar:
![image](https://user-images.githubusercontent.com/40127061/45671687-60ae7f00-bb26-11e8-9b62-60ba8efef92d.png)

Should look something like that:
![image](https://user-images.githubusercontent.com/40127061/45671831-d4e92280-bb26-11e8-863d-7dcb1f7c89ab.png)

**Comment by flddr** [comment]
@YAPPDEF Maybe this helps: #21484

**Comment by Zazo032** [comment]
I think this is solved right now by setting `SnackBar`'s `behavior` parameter to `SnackBarBehavior.floating`.

**Comment by domske** [comment]
@Zazo032 No unf. not. Following [this](https://material.io/components/snackbars/#usage) and the changes here https://github.com/flutter/flutter/pull/21484 , the Snackbar now dodges the bottom bar and fab buttons. 

> Snackbars are placed in the most suitable area of the UI.

![snackbar](https://user-images.githubusercontent.com/28209992/73602262-1db14800-4571-11ea-812a-a7b04d73758c.png)

Also if the `behavior` is set to `floating`. If the behavior is set to `fixed` the fab button will move above the snackbar. Both behaviors dodges the bottom bar. 

I can understand the behavior, but there must be an option to just overlay all without respecting the bottom bar or fab buttons.

**Comment by TahaTesser** [comment]
This issue still 

<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: FABbutton(),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: 0,
        items: [
          BottomNavigationBarItem(
            icon: new Icon(Icons.home),
            title: new Text('Home'),
          ),
          BottomNavigationBarItem(
            icon: new Icon(Icons.mail),
            title: new Text('Messages'),
          ),
          BottomNavigationBarItem(
              icon: Icon(Icons.person), title: Text('Profile')),
        ],
      ),
    );
  }
}

class FABbutton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
      child: Text('Test'),
      onPressed: () {
        final snackBar = SnackBar(content: Text('Yay! A SnackBar!'));

// Find the Scaffold in the widget tree and use it to show a SnackBar.
        Scaffold.of(context).showSnackBar(snackBar);
      },
    );
  }
}

```

</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (9 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>
