### ISSUE TITLE
DropdownButton bad behaviour when tapped and keyboard is showing

### ISSUE THREAD

**Issue by NotThatBowser** [flutter/flutter#22075]
Have view with a TextField and a DropdownButton.  If the user has the TextField active (keyboard is showing) and they tap the DropdownButton the behaviour is not as expected.

The DropdownButton will open for 1 frame and immediately close again making the user see a box flash up then disappear.  The keyboard closes as you would expect.

The user would expect either:
* The keyboard closes with no visual flash from the DropdownButton and the DropdownButton doesn't open.
* The keyboard closes and the DropdownButton opens.

This only happens when the keyboard is showing; if the TextField has a cursor but the keyboard is hidden then clicking on the DropdownButton will open it normally as expected.  To speculate, it suggests that when the keyboard is showing the tap on the DropdownButton is allowing it to open normally but is then immediately closed by the closing of the keyboard meaning its contents box shows for 1-frame.

```
Doctor:
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.285], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 32-bit edition (version 1.26.1)
[√] Connected devices (1 available)
```

**Comment by davidmartos96** [comment]
Here is some code showing this issue.
I am not experiencing the flash @NotThatBowser says, although 2 taps are needed to display the dropdown options when the keyboard is opened, which is not the expected behaviour, at least in Android.

Debugging the DropdownButton source code, it doesn't seem like a problem with its GestureDetector because the _handleTap fuction is triggered. Looks like it is an issue with the _DropdownRoute inside this function.
```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Sample",
      home: Scaffold(
        appBar: AppBar(
          title: Text("Focus"),
        ),
        body: Column(
          children: <Widget>[
            TextField(
              decoration: InputDecoration(
                hintText: "TextField",
              ),
            ),
            DropdownButton(
              onChanged: (val) {},
              items: [
                DropdownMenuItem(
                  child: Text("Dropdown"),
                ),
              ],
            ),
            GestureDetector(
              onTap: () {
                print("Tapped blue");
              },
              child: Container(
                width: 80,
                height: 80,
                color: Colors.blue,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by Simpler1** [comment]
This problem can even be seen in the flutter gallery for pickers:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/date_and_time_picker_demo.dart

If you start typing a name for the Event and then click the Activity dropdown at the bottom.
Problem 1: The first click just dismisses the keyboard when it should actually open the dropdown
The second click opens the dropdown.
The third click selects an entry in the dropdown.
Problem 2: The cursor is shown as blinking in the Event field at the top, but focus should not have returned to the Event field.
Problem 3: The keyboard is missing even though the cursor is blinking.

This makes the user experience very bad.

The same problem occurs on this same page if one of the date or time fields is selected (instead of the dropdown) when entering a name in the Event field.

Is there a workaround to keep the focus from returning to a previously focused field?

**Comment by toby3000** [comment]
I have the same problem. :-( No Solution yet?

**Comment by dnv190** [comment]
I have the same problem. :-( No Solution yet?

**Comment by rmarau** [comment]
@NotThatBowser Allow me to add my experience with this issue.

I believe this is not related to the soft keyboard being up or down. I'm experiencing the same problem in an emulator with soft keyboard disabled.

1- Tap the TextField. The TextField is focused and becomes editable (via hard-keyboard or soft-keyboard if enabled)
2- Tap DropdownButton.  The TextField loses focus > The DropdownButton won't display > TextField regains focus. The TextField gets into this weird state where it's focused (with cursor blinking) but it's not in an editable state - Hard keyboard will not type and soft keyboard (if enabled) will not pop out.

3- (fork)
3- a) Re-tap DropdownButton. Now it pops-up. Possibly because TextField was not really editable despite being focused (speculation).

3- b) (instead of 3-a) Re-tap TextField. TextField keeps in the focused state but now it's editable. (it responds to keys and the Soft-keyboard shows if enabled). And are back to state 1.

It appears to be a problem in DropdownButton when opening with some TextField on focus and editable. It won't happen with a PopupMenuButton.

WRT the weird state where TextField gets into (focused, blinking but not editable), Im not sure this is the intended behavior or a new separate issue. This behavior is identical to dismissing/selecting an item in either PopupMenuButton and PopupMenuButton.

I've tested with flutter dev v1.5.8 and the current master 549b412656bb4db80920de56a09912e079fdd2a2

My test code:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  final values = <String>["1","2","3","4"];
  FocusNode _focus = new FocusNode();

  @override
  void initState() {
    _focus.addListener(_onFocusChange);
    super.initState();
  }

  _onFocusChange(){
    debugPrint("TextField Focus: ${_focus.hasFocus}");
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
          body: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[

              DropdownButton<String>(
                  value: values[0],
                  items: values.map<DropdownMenuItem<String>>(
                          (value) => DropdownMenuItem<String>( value: value, child: Text("DropdownMenuItem option:"+value) )
                  ).toList(),
                  onChanged: (_){},
              ),

              PopupMenuButton<String>(
                itemBuilder: (BuildContext context) {
                  return values.map<PopupMenuEntry<String>>(
                          (value)=>PopupMenuItem<String>( value: value, child: Text("PopupMenuItem option:"+value) )
                  ).toList();
                },
              ),

              TextField(
                focusNode: _focus,
              ),

            ],
          ),
        )
    );
  }
}
```

**Comment by rmarau** [comment]
Some context: When the DropdownButton is opened it lists the options and upon a change to the screen size (orientation) it dismisses the list. The user will have to tap it again to open. I believe this would be the normal usage pattern.

To achieve this, DropdownButton internally subscribes to an observer that triggers this code below.
https://github.com/flutter/flutter/blob/64749826498123e795c77f9bec8cea804a40a051/packages/flutter/lib/src/material/dropdown.dart#L728-L733

It removes the route responsible for presenting the list of options.

Back to the case-study:
For some reason (that I don't know) when the TextField is focused and "editable", tapping on the DropdownButton triggers a didChangeMetrics and so the route is immediately removed, as if the user rotated the screen.

I don't know much about the connection between focus changing and the didChangeMetrics call. 
A quick one line patch to workaround would be to ignore didChangeMetrics
```dart
void didChangeMetrics() {
    //print(WidgetsBinding.instance.focusManager.toString());
    //_removeDropdownRoute();
  }
```
But this disrupts DropdownButton's normal behavior with orientation.

Anyone knows how to test the event that triggers `didChangeMetrics`?

There's this [code](https://github.com/flutter/flutter/blob/829bdeb42653c38f4d3c64b7e81f54a2642a140b/packages/flutter/lib/src/widgets/editable_text.dart#L1198-L1206) in EditableText to detect the presence of a soft-keyboard. This test would be fine in a scenario with a soft-keyboard. But as I mentioned in my previous comment the DropdownButton also fails in a device without soft-keyboard.

**Comment by jrnelson333** [comment]
The behavior in a native Android app seems to be that opening a dropdown does not dismiss the keyboard, and therefore the application's dimensions would not change (didChangeMetrics would not be called). This can be observed in Contacts App on a Google Pixel (see screenshot). Would the correct solution be to keep the keyboard open when opening a dropdown?

![Screenshot_2019-06-09_132714](https://user-images.githubusercontent.com/20613561/59162179-9d5a4600-8aba-11e9-9500-83f4af601cf1.jpg)

**Comment by faustinoribeiro** [comment]
Is there some news on that? It is an irritating issue, specially in forms that mix multiple text fields and dropdowns.

**Comment by njovy** [comment]
Is there any workaround for this issue?

**Comment by Rhymond** [comment]
Any news?

**Comment by cdsaenz** [comment]
Having the same trouble here..

**Comment by cdsaenz** [comment]
> ```dart
> void didChangeMetrics() {
>     //print(WidgetsBinding.instance.focusManager.toString());
>     //_removeDropdownRoute();
>   }
> ```
> 
> But this disrupts DropdownButton's normal behavior with orientation.

So far this seems the only workaround for me, I didn't find so far any disruption but had to do a better test.

**Comment by thedumbtechguy** [comment]
@cdsaenz did you fork the dropdown for the solution above?

**Comment by thedumbtechguy** [comment]
I forked the Dropdown button and removed the `didChangeMetrics` code. I noticed some awkward behavior when the keyboard disappears.

Expected behavior
![WhatsApp Image 2019-08-03 at 12 17 08 (2)](https://user-images.githubusercontent.com/923493/62411846-f50fbc00-b5e8-11e9-9e10-2bc830b2e0aa.jpeg)
![WhatsApp Image 2019-08-03 at 12 17 08 (3)](https://user-images.githubusercontent.com/923493/62411847-f50fbc00-b5e8-11e9-8fe4-458924a64140.jpeg)

Observed behavior
![WhatsApp Image 2019-08-03 at 12 17 08 (1)](https://user-images.githubusercontent.com/923493/62411850-0b1d7c80-b5e9-11e9-96e5-3aa8fd282f17.jpeg)
![WhatsApp Image 2019-08-03 at 12 17 08](https://user-images.githubusercontent.com/923493/62411851-0b1d7c80-b5e9-11e9-990f-ce2b97a60be9.jpeg)


I think the soft keyboard affects the layout and when it disappears, causes this to happen. I am sure I can fix with my layout, but this is what I observed.

**Comment by besserwisser** [comment]
Honestly I am shocked that Google has not addressed this issue after a whole year...

**Comment by analogic** [comment]
I am afraid its some kind of flutter issue with keyboard. I have same problem with dropdowns and even problem with text input where keyboard instantiation change cursor position to begin. 

![CanineBlindApisdorsatalaboriosa-size_restricted](https://user-images.githubusercontent.com/934254/64327001-41c12b00-cfcb-11e9-8297-212d368c0bca.gif)
(just clicking textfield and dropdown back and forth)

**Comment by duzenko** [comment]
1.9.1 has 1,548 Pull Requests merged but nothing actually useful, like this one or #22075

**Comment by alyyasser** [comment]
after reading @rmarau analysis and do some experiments myself, i think the main issue is caused by the triggered `didChangeMetrics` method, which then trigger `_removeDropdownRoute`.

because it's actual implementation using `Navigator.push()`, so it'll remove the _route_ `_removeDropdownRoute` triggered.

the other thing i noticed is, `didChangeMetrics` (which trigger `_removeDropdownRoute`) triggered not only when the device orientation changed (or rotated). based on the documentation,

> Called when the **application's dimensions change**. For example, when a phone is rotated.
> This method exposes notifications from [Window.onMetricsChanged].

and when soft-keyboard up or down, it actually did change the application's dimensions, which then trigger `didChangeMetrics`. but i can't confirm if it's triggered when a TextField gain focus with soft-keyboard disabled (like in emulator).

IMO, the `_removeDropdownRoute` should only executed when orientation changed (rotated), so the implementation should be changed a bit to detect the _real_ orientation changed based on that `Window.onMetricsChanged` notifications (when `didChangeMetrics` triggered).

**Comment by alyyasser** [comment]
> IMO, the `_removeDropdownRoute` should only executed when orientation changed (rotated), so the implementation should be changed a bit to detect the _real_ orientation change based on that `Window.onMetricsChanged` notifications (when `didChangeMetrics` triggered).

i've done the change myself here: https://github.com/alyyasser/flutter/commit/c5470efc34672a1d81d923bfa2c62e3b93aad5e0
it seems good enough for me, feel free to check it out.

but, it doesn't fix the issue mentioned by @NotThatBowser 

here is some test i've done, using test code from @rmarau 
![2019-09-14002319](https://user-images.githubusercontent.com/16476111/64882120-a85ade80-d686-11e9-85e3-d4ede6a91984.gif)

after the change i did in the commit above, it behave like `PopupMenuButton` now, but i doesn't feel quite right though.

the last idea i have is, to apply some kind of delay mechanism in `_handleTap` method if it triggered when soft-keyboard is open, wait until the soft-keyboard's closing animation to be done before executing the code to push the `dropdownRoute`.

**Comment by stomachflu** [comment]
Disabling `_removeDropdownRoute` works for me. I hope it wont affect other part of my UI. Thanks

**Comment by alyyasser** [comment]
> Disabling `_removeDropdownRoute` works for me. I hope it wont affect other part of my UI. Thanks

it'll. you can try rotate your screen, and compare the behaviour between `_removeDropdownRoute` disabled and enabled.

**Comment by billy124** [comment]
Wow, over a year and still no solution or work around  👎

**Comment by toby3000** [comment]
> Wow, over a year and still no solution or work around 👎

very sad :-(

**Comment by agozie** [comment]
Just encountered this... spent 10 hours troubleshooting before finding this issue. Any concrete fix yet please?

**Comment by ThinkDigitalSoftware** [comment]
> I am afraid its some kind of flutter issue with keyboard. I have same problem with dropdowns and even problem with text input where keyboard instantiation change cursor position to begin.
> 
> ![CanineBlindApisdorsatalaboriosa-size_restricted](https://user-images.githubusercontent.com/934254/64327001-41c12b00-cfcb-11e9-8297-212d368c0bca.gif)
> (just clicking textfield and dropdown back and forth)

Your issue may be resolved by making sure your textEditingController is created outside of your build method and inside the initState so that it's not rebuilt  whenever the widget is. I've seen and fixed something like this before

**Comment by ThinkDigitalSoftware** [comment]
Another issue that's related is that the focus returns to the previously used TextField even if the keyboard was dismissed.
![ezgif-4-408d89423126](https://user-images.githubusercontent.com/23037821/65995274-04c14a80-e44a-11e9-9310-4dde6d061304.gif)

**Comment by EricPreventa** [comment]
Somehow, my code changed and now this is becoming an issue for me. Can't believe this is a problem. Do we have any preferred fix for this?

**Comment by Purus** [comment]
> Disabling `_removeDropdownRoute` works for me. I hope it wont affect other part of my UI. Thanks

@stomachflu Can you guide how to do this?

**Comment by dalewking** [comment]
@Purus What I did was copy in [the source file](https://github.com/flutter/flutter/blob/a95a84ebfb5f477d3ac06a04032fc65a08348b97/packages/flutter/lib/src/material/dropdown.dart) to my project. Then comment out the body of the didChangeMetrics method ([line 928](https://github.com/flutter/flutter/blob/a95a84ebfb5f477d3ac06a04032fc65a08348b97/packages/flutter/lib/src/material/dropdown.dart#L928)).

You then have to import that file using a [library prefix](https://dart.dev/guides/language/language-tour#using-libraries) to differentiate it from the one in material library.

That works for our app because we are portrait only so no screen rotations. If you support screen rotations this could do weird things if you had the drop down open and rotated the screen.

**Comment by liteux** [comment]
Here is what worked for me.
It seems it happens only when there are text and dropdown fields together on one form and when I have a text field focused and I try to open a dropdown. Add following lines in your code and see if it works for me, it worked for me:
For all text fields, take a focus node each:
```
FocusNode textField = FocusNode();
FormBuilderTextField(
        focusNode: textField,
        onEditingComplete: textField.unfocus,
```

Now when you will open the dropdown, it will force it to unfocus the text field. I am using flutter_form_builder but it should work the same way for normal TextFormField.

**Comment by dalewking** [comment]
@liteux's suggestion does not fix the underlying problem that the dropdown that is starting to display gets dismissed because the layout metrics are changing due to the keyboard being dismissed. It does let you actually open the drop down menu (which did not happen before for me), but it requires you to tap the drop down twice.

**Comment by gilvangobbato** [comment]
I'm with the same problem!
For now, I will to use an popup, but it's necessary to solve this problem.

**Comment by dalewking** [comment]
Good news is that 3 days ago there was a PR merged that supposedly fixes this issue: https://github.com/flutter/flutter/pull/42482

**Comment by Tokenyet** [comment]
I just upgrade to `master` and the problem sloved, but I noticed that checkbox's text is changed to unexpected Alignment. However, the main problem sloved.

**Comment by gspencergoog** [comment]
Yes,  #42482 fixes this issue.  @Tokenyet, that sounds like a different problem.  Can you file a separate issue for that?

**Comment by andersonmendesdev** [comment]
Strange I am in flutter version v1.9.1+hotfix.6  and still have this problem.

**Comment by gspencergoog** [comment]
@andersonmendesdev that's because it hasn't landed in stable yet. When dee75839087fb9cdfab342dd26587caa51b31eaf is in stable, you will have the fix, or you can switch to the `master` channel until then.

**Comment by andersonmendesdev** [comment]
@gspencergoog  Thanks yes, I will wait for the stable version then.

**Comment by lazylazyllama** [comment]
It's not perfect though..

As you can see:
![photo_2019-11-02_15-29-37](https://user-images.githubusercontent.com/10547444/68072410-bfb07100-fd85-11e9-8edb-648f18d412e9.jpg)

The dropdown stays open, but the position of the popup changes as the keyboard closes... so the position of the dropdown is weird.

**Comment by rserro** [comment]
A workaround if you need the fix ASAP and cannot wait until it goes into a stable release:
```
Listener(
    onPointerDown: (_) => FocusScope.of(context).unfocus(),
    child: DropdownButton<...>(...),
)
```

**Comment by chitgoks** [comment]
@rserro 
people starting out with flutter will find this confusing. i also got to this thread because of this issue. can you please explain where exactly this needs to be added?

**Comment by rserro** [comment]
@chitgoks sure.

If you are using a DropdownButton and facing the problem of this thread, your widget build method will probably look like:
```
@override
Widget build(BuildContext context) {
    ...
    child: DropdownButton<Type>(your args),
    ...
}
```

To "solve" the problem, just encapsulate your DropdownButton<Type>(your args) under the code I wrote like this:
```
@override
Widget build(BuildContext context) {
    ...
    child: Listener(
        onPointerDown: (_) => FocusScope.of(context).unfocus(),
        child: DropdownButton<Type>(your args),
    ),
    ...
}
```

**Comment by chitgoks** [comment]
@rserro  awesome! this works! thank you very much!

**Comment by wisnuwijo** [comment]
> onPointerDown: (_) => FocusScope.of(context).unfocus(),



> A workaround if you need the fix ASAP and cannot wait until it goes into a stable release:
> 
> ```
> Listener(
>     onPointerDown: (_) => FocusScope.of(context).unfocus(),
>     child: DropdownButton<...>(...),
> )
> ```

thanks, it works for me

**Comment by FuturistLabs** [comment]
> Here is what worked for me.
> It seems it happens only when there are text and dropdown fields together on one form and when I have a text field focused and I try to open a dropdown. Add following lines in your code and see if it works for you, it worked for me:
> For all text fields, take a focus node each:
> 
> ```
> FocusNode textField = FocusNode();
> FormBuilderTextField(
>         focusNode: textField,
>         onEditingComplete: textField.unfocus,
> ```
> 
> Now when you will open the dropdown, it will force it to unfocus the text field. I am using flutter_form_builder but it should work the same way for normal TextFormField.

This fix, is correct!

**Comment by FuturistLabs** [comment]
> @chitgoks sure.
> 
> If you are using a DropdownButton and facing the problem of this thread, your widget build method will probably look like:
> 
> ```
> @override
> Widget build(BuildContext context) {
>     ...
>     child: DropdownButton<Type>(your args),
>     ...
> }
> ```
> 
> To "solve" the problem, just encapsulate your DropdownButton(your args) under the code I wrote like this:
> 
> ```
> @override
> Widget build(BuildContext context) {
>     ...
>     child: Listener(
>         onPointerDown: (_) => FocusScope.of(context).unfocus(),
>         child: DropdownButton<Type>(your args),
>     ),
>     ...
> }
> ```

This is also a good solution , but will suggest  :
```  void removeCurrentFocus(BuildContext context) {
      FocusScopeNode currentFocus = FocusScope.of(context);

      if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
      }
  }

**Comment by aungmyooo2k17** [comment]
> A workaround if you need the fix ASAP and cannot wait until it goes into a stable release:
> 
> ```
> Listener(
>     onPointerDown: (_) => FocusScope.of(context).unfocus(),
>     child: DropdownButton<...>(...),
> )
> ```

work for me really well thanks much

**Comment by usherwalce** [comment]
I have had no luck with any of the solutions above. No matter what I try, keyboard closes when I click the dropdown button.

**Comment by devDeejay** [comment]
Was this fixed in stable release cos I still observe very weird dropdown behaviour.

**Comment by liveaffiliates** [comment]
This didn't fix it for me it was still happening I did this instead which stoped the issue:

Listener(
    onPointerDown: (_) => FocusScope.of(context).requestFocus(FocusNode(),
    child: DropdownButton<...>(...),
)
