### ISSUE TITLE
Cancelling Google Sign In on Android throws exception instead of returning null

### ISSUE THREAD

**Issue by buntagonalprism** [flutter/flutter#22113]
According to the comments on the `signIn()` function in `google_sign_in.dart`, if the user cancels the sign in process, then `null` should be returned. 

However, cancelling the sign-in on android currently throws a Platform Exception containing generic error messages that do not indicate the request was cancelled. 

```
I/flutter ( 9795): PlatformException(sign_in_failed, Status{statusCode=ERROR, resolution=null}, null)
```

This makes it hard to differentiate request cancellation from a generic sign in failure, for the purpose of showing a retry snackbar / dialog for example. 

Using google_sign_in `3.0.6`

## Steps to Reproduce
1. Run Google Sign In example app on physical Android device (tested on Galaxy S8) from `plugins/packages/google_sign_in/example` 
2. Press `Sign In` button to launch google sign in account selector dialog
3. Press system back button to dismiss dialog
4. Generic platform exception is thrown 

## Logs

```
[+32164 ms] D/ViewRootImpl@2fdd086[MainActivity]( 9795): ViewPostIme pointer 0
[  +63 ms] D/ViewRootImpl@2fdd086[MainActivity]( 9795): ViewPostIme pointer 1
[ +297 ms] D/ViewRootImpl@2fdd086[MainActivity]( 9795): MSG_WINDOW_FOCUS_CHANGED 0
[  +55 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): setView = DecorView@52da61a[SignInHubActivity] TM=true MM=false
[   +1 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): dispatchAttachedToWindow
[  +15 ms] V/Surface ( 9795): sf_framedrop debug : 0x4f4c, game : false, logging : 0
[   +1 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): Relayout returned: old=[0,0][0,0] new=[0,0][1080,2076] result=0x7 surface={valid=true 493536477184} changed=true
[  +23 ms] D/mali_winsys( 9795): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x2076]-format:1
[        ] D/OpenGLRenderer( 9795): eglCreateWindowSurface = 0x72f0dfb630
[  +25 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2076) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
[        ] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): MSG_WINDOW_FOCUS_CHANGED 1
[   +1 ms] V/InputMethodManager( 9795): Starting input: tba=android.view.inputmethod.EditorInfo@9f4db28 nm : io.flutter.plugins.googlesigninexample ic=null
[        ] I/InputMethodManager( 9795): startInputInner - mService.startInputOrWindowGainedFocus
[  +83 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): MSG_WINDOW_FOCUS_CHANGED 0
[+4342 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): MSG_WINDOW_FOCUS_CHANGED 1
[        ] V/InputMethodManager( 9795): Starting input: tba=android.view.inputmethod.EditorInfo@a1de740 nm : io.flutter.plugins.googlesigninexample ic=null
[        ] I/InputMethodManager( 9795): startInputInner - mService.startInputOrWindowGainedFocus
[  +47 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): MSG_WINDOW_FOCUS_CHANGED 0
[   +2 ms] D/ViewRootImpl@2fdd086[MainActivity]( 9795): MSG_WINDOW_FOCUS_CHANGED 1
[  +13 ms] V/InputMethodManager( 9795): Starting input: tba=android.view.inputmethod.EditorInfo@6b12679 nm : io.flutter.plugins.googlesigninexample ic=null
[        ] I/InputMethodManager( 9795): startInputInner - mService.startInputOrWindowGainedFocus
[   +1 ms] I/flutter ( 9795): PlatformException(sign_in_failed, Status{statusCode=ERROR, resolution=null}, null)
[  +16 ms] D/OpenGLRenderer( 9795): eglDestroySurface = 0x72f0dfb630
[   +6 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): Relayout returned: old=[0,0][1080,2076] new=[0,0][1080,2076] result=0x5 surface={valid=false 0} changed=true
[   +6 ms] D/ViewRootImpl@3be0cc5[SignInHubActivity]( 9795): dispatchDetachedFromWindow
[        ] D/InputEventReceiver( 9795): channel 'd2e145a io.flutter.plugins.googlesigninexample/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (client)' ~ Disposing input event receiver.
[        ] D/InputEventReceiver( 9795): channel 'd2e145a io.flutter.plugins.googlesigninexample/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (client)' ~NativeInputEventReceiver.
```

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.17134.285], locale en-AU)
    • Flutter version 0.6.0 at C:\flutter
    • Framework revision 9299c02cf7 (5 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\t\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • SM G950F • ce03171315f2833503 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

```

**Comment by buntagonalprism** [comment]
Hi @MdMahadiaHossain this issue is reproducible on a physical device (Galaxy S8) with google play services installed and up to date. Being able to sign in is not the issue - sign in with google works just fine, the issue is only if the user manually cancels sign in using the system back button.

**Comment by ayush-12** [comment]
I am also getting the same issue when calling await _googleSignIn.disconnect(); that to on Galaxy S8. The app just freezes.
Below are the logs.
E/flutter (16617): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (16617): PlatformException(status, Failed to disconnect., null)
E/flutter (16617): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (16617): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (16617): 
E/flutter (16617): #2 GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:217:58)
E/flutter (16617): 
E/flutter (16617): #3 GoogleSignIn._addMethodCall. (package:google_sign_in/google_sign_in.dart:269:28)
E/flutter (16617): #4 _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (16617): #5 _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (16617): #6 Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (16617): #7 Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (16617): #8 Future._addListener. (dart:async/future_impl.dart:351:9)
E/flutter (16617): #9 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (16617): #10 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by truongsinh** [comment]
can NO longer reproduce this on `3.2.4`

**Comment by buntagonalprism** [comment]
Confirmed, the issue has been resolved as of version 3.2.4 of google_sign_in. Cancelling google sign in no longer throws a platform exception but instead correctly returns null from `signIn` method

**Comment by pushangupta** [comment]
@buntagonalprism Could you please elaborate what was causing the bug? I have this bug in other places too. Like the file_picker plugin. You cancel choosing a file and the exception throws which is not even being caught inside a try-catch!

**Comment by benjaminhorner** [comment]
@buntagonalprism I am still having the issue on iOS even after updating to 3.2.4.
Steps to reproduce :
- click the cancel button when the popover window shows prompting the user to grant access to google.com to Sign In. 

Also, the exception cannot be caught in a try catch statement.

```
try {
        account = await _googleSignIn.signIn();
      } on PlatformException catch (error) {
        /// This is never caught
        yield LoginState.failure(error.message);
      }
```

**Comment by lohanidamodar** [comment]
I am too having the same problem on android. Yes the signIn method returns null on cancel, but after first throwing platformException and the catch method doesn't work.

**Comment by benjaminhorner** [comment]
@lohanidamodar are you also running the 3.2.4 version of the plugin?

**Comment by lohanidamodar** [comment]
yes I am running the 3.2.4 version

**Comment by benjaminhorner** [comment]
I tested with the demo (https://github.com/flutter/plugins/blob/master/packages/google_sign_in/example/lib/main.dart) and I am also facing the issue.

Double checked I am using 3.2.4.

**Comment by benjaminhorner** [comment]
@zoechi I thought that instead of creating a NEW issue for an unresolved issue, this one should be reopened. But Okay I will create a new one.

**Comment by zoechi** [comment]
@benjaminhorner the original author doesn't see it anymore so it's likely a different issue.

**Comment by maheshmnj** [comment]
has anyone able to solve this issue I still see it on both ios as well as android with latest version 4.1.1 even tried with v3.2.4 but unable to catch the exception it throws ```sigin_cancelled exception```

**Comment by surpriso1997** [comment]
> has anyone able to solve this issue I still see it on both ios as well as android with latest version 4.1.1 even tried with v3.2.4 but unable to catch the exception it throws `sigin_cancelled exception`

I am also having the same issue.

**Comment by maheshmnj** [comment]
The only workaround as of now is to use the release version of the apk and it works smoothly for ios and android and doesn't pause the app on exception,it is probably the ide that pauses on the exception

**Comment by paulkastel** [comment]
Duplicate of: #44431. Valid for version 4.2.0 of google_sign_in. Sign in throws an exception when user cancels:
`PlatformException (PlatformException(sign_in_canceled, com.google.android.gms.common.api.ApiException: 12501: , null))`
