### ISSUE TITLE
Flutter Dart Singletons aren't true singletons. 

### ISSUE THREAD

**Issue by mjaffa-figure** [flutter/flutter#22194]
## Steps to Reproduce

Create a singleton like this:

class LivesCalculator {
  static final LivesCalculator _singleton = new LivesCalculator._internal();
  LivesCalculator._internal() { print('Lives Calculator contructor called'); }
  static LivesCalculator get instance => _singleton;

 int lives;
}

1. Through a bunch of threads set lives on the object, change the amount on a different thread.
2. on another thread in another Widget, like in a timer call back reference that "lives" member, this value is not the same on the other thread.
3. I verified with my print statement the constructor is only called once like a singleton, but the member value is different between threads sometimes. Sometimes it works. 
4. Other programming languages this is a known issue and you have to mark that member variable with a "synchronized" keyword to keep the value the same between threads.

Is something wrong with Flutter/Dart?

flutter doctor -v
[✓] Flutter (Channel master, v0.9.3-pre.20, on Mac OS X 10.13.6 17G2307, locale en-US)
    • Flutter version 0.9.3-pre.20 at /Users/matthewjaffa/flutter
    • Framework revision 6d134e0c86 (15 hours ago), 2018-09-23 00:43:05 -0700
    • Engine revision 57fd394e59
    • Dart version 2.1.0-dev.5.0.flutter-654c4babc8

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/matthewjaffa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L232m
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Matthew’s iPhone • e5167fb6705be49ae5fe64392a7db61e6fc0e53e • ios • iOS 12.0
    • iPhone 8         • D8EA316C-2CB0-43D2-A00B-91822B264C81     • ios • iOS 12.0 (simulator)

**Comment by zoechi** [comment]
Dart doesn't share values between threads. All widgets are in the same thread (the UI thread).
Async execution is not related to threads, async code only runs concurrently on the same thread unless you start a new isolate explicitely.

I assume you're running into https://github.com/dart-lang/sdk/issues/33076

To fix, replace all relative imports to `package:...` imports in `lib/main.dart` and don't import `lib/main.dart` from another file.

**Comment by zoechi** [comment]
@datvtwkm what Flutter version are you using?
Does your `lib/main.dart` contain relative imports (see my comment above)?
Try `flutter clean` in a terminal window in the project directory (where `pubspec.yaml` is).

**Comment by asimbahwe** [comment]
@zoechi , you are right, using absolute imports make singletons work very well.

**Comment by zoechi** [comment]
@asimbahwe that was a Dart issue that was fixed since. This shouldn't cause issues and you can mix absolute and relative imports. There might still be some weirdnesses if you are using uppercase letters in file names on windows.

**Comment by asimbahwe** [comment]
using flutter, until now that issue still exists. I don't know why

**Comment by zoechi** [comment]
@asimbahwe are you on the latest Flutter version? (`>= 1.0.0`)

**Comment by asimbahwe** [comment]
I think yes, I just downloaded it two weeks ago

**Comment by zoechi** [comment]
@asimbahwe I think it's better discussed here https://stackoverflow.com/questions/53776124/flutter-dart-relative-imports-vs-absolute-imports anyway.
That looks like an issue with your code, not with Dart or Flutter.

**Comment by asimbahwe** [comment]
So I could appreciate for sure to know exactly where I made mistakes in the code. I'm still new using both flutter and dart

**Comment by zoechi** [comment]
Sorry, it was my mistake. I misinterpreted your code.

**Comment by asimbahwe** [comment]
Anh okay, no problem. are you the one suggested to post the full code?

**Comment by asimbahwe** [comment]
You are right. I created a new project in which tried with both relative imports then absolute imports and it worked fine in both cases. Thank you
