### ISSUE TITLE
Warnings from the cloud_firestore plugin on Android: FirebaseCorePlugin.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#22438]
## Steps to Reproduce

1. Create a new project
2. Add dependency for `cloud_firestore: ^0.8.0`
3. `flutter run`

## Logs

```
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
```

And also

```
Note: /Users/filiph/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.0/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/filiph/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

(And also this, but it's covered by https://github.com/flutter/flutter/issues/18159)

```
W/Firestore( 5687): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore( 5687): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore( 5687): 
W/Firestore( 5687): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore( 5687): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore( 5687):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore( 5687):     .build();
W/Firestore( 5687): firestore.setFirestoreSettings(settings);
W/Firestore( 5687): 
W/Firestore( 5687): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore( 5687): 
W/Firestore( 5687): // Old:
W/Firestore( 5687): java.util.Date date = snapshot.getDate("created_at");
W/Firestore( 5687): // New:
W/Firestore( 5687): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore( 5687): java.util.Date date = timestamp.toDate();
W/Firestore( 5687): 
W/Firestore( 5687): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.

```

cc @kroikie @bparrishMines

**Comment by filiph** [comment]
Another warning:

```
Note: /Users/filiph/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/filiph/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.0/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

This might be just the Firebase plugin itself. Adding here for completeness.

**Comment by kroikie** [comment]
The Firestore warning has been resolved. See [example](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/lib/main.dart#L22).

**Comment by zoechi** [comment]
I assume this issue is solved.

**Comment by rajeshjeshar** [comment]
@zoechi The Warning still exists:

Launching lib\main.dart on SM J500F in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Note: G:\ANDROID\FLUTTER\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.


Built build\app\outputs\apk\debug\app-debug.apk.
D/FirebaseApp(27171): com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/ResourcesManager(27171): For user 0 new overlays fetched Null
V/NativeCrypto(27171): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
I/art     (27171): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java7ExtendedSSLSession>
I/art     (27171): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java7ExtendedSSLSession>
I/art     (27171): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession>
I/art     (27171): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession>
I/ProviderInstaller(27171): Installed default security provider GmsCore_OpenSSL
D/libGLESv2(27171): DTS_GLAPI : DTS is not allowed for Package : app.dailyme
D/libGLESv1(27171): DTS_GLAPI : DTS is not allowed for Package : app.dailyme


**FLUTTER DOCTOR:**

D:\CURRENT\dailyme>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.30.2)
[√] Connected device (1 available)

• No issues found!

**Plugins used:**
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.8.2+3
  firebase_core: ^0.2.5+1





application code:
Used the [Example Code given in the Clodufirestore Plugin](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/lib/main.dart#L22) with my Project's parameters like appid project id etc..

**Comment by epiphanatic** [comment]
@zoechi followed the workaround but still getting the same warnings

**Comment by jeffdiederiks** [comment]
Getting the same error with `firebase-core:16.0.9`:

**Comment by Katekko** [comment]
Same here jeffdie!

> Getting the same error with `firebase-core:16.0.9`:
> 
> ```
> Launching lib/main.dart on Pixel in debug mode...
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Note: /home/jeff/Programs/flutter/v1.2.1/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
> 
> Note: Recompile with -Xlint:unchecked for details.
> error processing /home/jeff/Dev/track-app/build/app/intermediates/javac/debug/compileDebugJavaWithJavac/classes
> java.lang.ArrayIndexOutOfBoundsException: 4202
> 	at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
> ```

**Comment by c0h1b4** [comment]
Same error here.
firebase_core: ^0.4.0+1

**Comment by c0h1b4** [comment]
Initializing gradle...                                              0.8s
Resolving dependencies...                                           1.3s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/mauro/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      38.1s
Built build/app/outputs/apk/release/app-release.apk (9.3MB).

**Comment by gabrielnemeth** [comment]
Same here:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.116], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (1 available)

• No issues found!

```

Packages:
```
firebase_core: ^0.4.0+1
firebase_auth: ^0.11.1+1
google_sign_in: ^4.0.1+3
flutter_facebook_login: ^2.0.1
cloud_firestore: ^0.12.0
```

```
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by bradmuzza** [comment]
having the same issue

**Comment by AndroidNils** [comment]
Same!

**Comment by raulluiz** [comment]
Follow the instructions!

https://firebase.google.com/docs/flutter/setup?hl=pt-br

**Comment by hemangjoshi37a** [comment]
Any update??

**Comment by xTMxTM** [comment]
Note: Warning only shows up for me when building the app after doing a 'flutter clean' or upgrading flutter version.

**Comment by kroikie** [comment]
@filiph

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/640. Any further collaboration will be done there.

**Comment by sunaarun** [comment]
> Note: Warning only shows up for me when building the app after doing a 'flutter clean' or upgrading flutter version.

The same thing to me

**Comment by GabrielModog** [comment]
You can fix this by using multidex.

See it how setting up: https://developer.android.com/studio/build/multidex

**Comment by shaadakhan** [comment]
I have same issue.

**Comment by Renkon117** [comment]
I have the same issue right after i added "cloud_firestore: ^0.13.4+2" plugin

**Comment by Renkon117** [comment]
i added following code in /app/build.gradle and it works fine now
`release {
            signingConfig signingConfigs.debug
            minifyEnabled true
        }
        debug {
            minifyEnabled true
        }`
