### ISSUE TITLE
Alignment Issue when labelText and prefixIcon used in TextField

### ISSUE THREAD

**Issue by figengungor** [flutter/flutter#22471]
## Steps to Reproduce
Here is the gist to reproduce the issue:
https://gist.github.com/figengungor/53c53cee0128a0ab9056946cca9cb2c3

![hinttextissue](https://user-images.githubusercontent.com/3411015/46247654-50947a80-c417-11e8-9b18-615f5db48156.png)

## Logs

```
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.8.2 at C:\flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\LOOP\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\LOOP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio3.0\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio3.0
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by HansMuller** [comment]
The `prefixIcon` is centered vertically within the InputDecorator, the `prefix` widget is aligned with the input/hint's baseline.  I'm guessing that you're looking for the latter?

**Comment by figengungor** [comment]
Hi @HansMuller. When I change the prefixIcon with prefix, the result I'm getting is as following:

![passive_prefix](https://user-images.githubusercontent.com/3411015/49697645-1ee42080-fbcb-11e8-8660-aceea87ab404.png)

It only shows up when it is active:

![active_prefix](https://user-images.githubusercontent.com/3411015/49697657-2e636980-fbcb-11e8-91ab-32163876d793.png)

The prefixIcon is working fine with labelText but when I want to use hintText, The position of prefixIcon is fine vertically centered but it's the hintText that is being positioned wrong as I see. 

prefixIcon with labelText:
![labeltext](https://user-images.githubusercontent.com/3411015/49697690-a2057680-fbcb-11e8-810c-8d30d012e73d.png)

prefixIcon with hintText:
![hinttext](https://user-images.githubusercontent.com/3411015/49697708-c6f9e980-fbcb-11e8-9b3b-d974f2cf7400.png)

**Comment by cbk2604** [comment]
It's fixed by adding as
labelText: ''

**Comment by stpch** [comment]
It can also be fixed by changing the hint text style height, e.g. `hintStyle: TextStyle(height: 1.4)`.

**Comment by w4-wonjerry** [comment]
I think this problem is fixed in flutter 1.12.13+hotfix.8

**Comment by figengungor** [comment]
Nope. I still get the same output in the screenshot  with flutter 1.12.13+hotfix.8

**Comment by ngocdb** [comment]
Use TextField's "textAlignVertical: TextAlignVertical.center" then hintText will align nicely with prefixIcon

**Comment by darshankawar** [comment]
Issue replicable on latest dev channel.

**Comment by mikeRozen** [comment]
May it be possible to consider the issue with _hintText_ not aligned correctly when _prefixText_ is used (as mentioned by @figengungor [third comment](https://github.com/flutter/flutter/issues/22471#issuecomment-445540053)) as the same issue
