### ISSUE TITLE
Missing Email-Link Sign-In in firebase_auth plugin.

### ISSUE THREAD

**Issue by kkrauthaeuser** [flutter/flutter#22958]
It seems like there is currently no option to use the email-only authentication with the firebase_auth plugin.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Have you tried `FirebaseAuth.instance.signInWithEmailAndPassword(...)`?

**Comment by kkrauthaeuser** [comment]
That's the method I'm using right now. But I'd like to use the Firebase-Auth Feature described for Android development [here](https://firebase.google.com/docs/auth/android/email-link-auth) in Flutter. As far as I know, this is currently not possible using the firebase_auth plugin.

**Comment by lukepighetti** [comment]
Confirmed that it is not possible. It is different than `signInwithEmailAndPassword()`. it is a password-less email auth method (like Medium.com)

**Comment by zoechi** [comment]
@lukepighetti thanks for the update and clarification. I saw your reference links in #22960

**Comment by yhua537** [comment]
Password-less is much better than weak passwords that user is likely going to use, +1 support on this feature

**Comment by bizz84** [comment]
I have implemented partially working solution for this, and open-sourced a sample app here:

https://github.com/bizz84/passwordless_sign_in_firebase_flutter

My fork of the plugins repo is here:

https://github.com/bizz84/plugins/tree/enable-passwordless-sign-in

Adding the required functionality wasn't straightforward. Could someone look at my plugin code and sample app and help out?

**Comment by rasmuschristensen** [comment]
I'm currently onboarding users with the anonymous option.  That way I'm able to let users into the app very easy and still have api endpoints with a trusted authority from firebase. On specific needs the user is asked to create a profile with a purpose. There I let the use enter email/password I was considering SMS instead. But what I do is adding credentials on the current anonymous profile I have in firebase.

**Comment by lukepighetti** [comment]
@rasmuschristensen unrelated?

**Comment by rasmuschristensen** [comment]
@lukepighetti Yeah I guess your're right. I read it as something else. I'll remove it.

**Comment by bizz84** [comment]
I have added a PR to Firebase plugins here:

https://github.com/flutter/plugins/pull/1159

This still needs a bit of work. It would be amazing if someone from the Flutter/Firebase team could help out.

**Comment by bizz84** [comment]
This can be closed. FirebaseAuth now supports this.

**Comment by kroikie** [comment]
@kkrauthaeuser

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/613. Any further collaboration will be done there.
