### ISSUE TITLE
io.Platform.localeName is '_' on iOS simulator

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#23241]
`io.Platform.localeName` returns '_' on an iOS simulator.

I found this because it is causing https://github.com/Dana-Ferguson/time_machine to not initialize, as it expects a proper locale string.

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.1-pre.77, on Mac OS X 10.13.6 17G2307, locale
    en-GB)
    • Flutter version 0.10.1-pre.77 at /Users/steve/code/flutter
    • Framework revision 5193affb27 (2 hours ago), 2018-10-18 04:15:02 -0400
    • Engine revision cc2ec365b7
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected device (1 available)
    • iPhone X • EF563F7A-675E-4CF8-AFFF-E518AF44A1F2 • ios • iOS 12.0
      (simulator)

• No issues found!
```

**Comment by yjbanov** [comment]
I'm able to reproduce this. @a-siva who is available to help with debug this? This issue is also blocking an internal release.

**Comment by tvolkert** [comment]
See also: https://github.com/flutter/flutter/issues/13748 (reported almost a year ago)

**Comment by tvolkert** [comment]
https://github.com/flutter/engine/pull/6557 looks relevant.

/cc @GaryQian

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/commit/02d659e82ae88fbe7439c9679a5094795afbae04 should resolve this.

**Comment by SteveAlexander** [comment]
On today's master, I'm seeing `io.Platform.localeName` is `"null"` — that is, the string "null" including the quotes.

Time machine is still broken with this, as it (reasonably, I think) expects it to be a valid locale string `xx_YY` or an actual `null`.

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.2-pre.53, on Mac OS X 10.13.6 17G2307, locale en-GB)
    • Flutter version 0.10.2-pre.53 at /Users/steve/code/flutter
    • Framework revision 549e8e07c6 (15 hours ago), 2018-10-24 14:41:16 -0700
    • Engine revision 2586e94122
    • Dart version 2.1.0-dev.7.1.flutter-45f9462398

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected device (1 available)
    • iPhone X • EF563F7A-675E-4CF8-AFFF-E518AF44A1F2 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by SteveAlexander** [comment]
Can we re-open this please? I don't believe it was properly resolved.

On today's master, I'm seeing io.Platform.localeName is null — that is, the string "null" excluding the quotes.

Time machine is still broken with this, as it (reasonably, I think) expects it to be a valid locale string xx_YY or an actual null.

```
flutter doctor -v
[✓] Flutter (Channel master, v0.11.10-pre.3, on Mac OS X 10.13.6 17G3025, locale en-GB)
    • Flutter version 0.11.10-pre.3 at /Users/steve/code/flutter
    • Framework revision 06e4ccc9a9 (32 hours ago), 2018-11-25 04:55:23 -0500
    • Engine revision 99e73d8c64
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone XR • 1EE1625B-61BB-421E-B104-CB3C8A5B6076 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by SteveAlexander** [comment]
ok, filed a new bug https://github.com/flutter/flutter/issues/24747
