### ISSUE TITLE
video_player image distortion problem after last flutter update 0.11.3

### ISSUE THREAD

**Issue by lgArlequin** [flutter/flutter#24402]
After the last update of flutter I have begun to have problems in some android devices with the video plugin.
It would seem like a codec problem.
To rule out a problem in my project, create a new one with the base example of the video plugin.
I attach a screenshot.
![screenshot_20181115-171559](https://user-images.githubusercontent.com/41754758/48579807-43b2e400-e8fc-11e8-9cda-f02f8c9e0d2e.png)
The device I use testing is a one plus one with android 8, I could also try an apk on a Samsung Galaxy S8 and an iphone s6 without problems.

Flutter doctor:
```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G3025, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.0)
[✓] Connected device (2 available)

• No issues found!
exit code 0
```
Debug Console:
```
Launching lib/main.dart on A0001 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/ExoPlayerImpl(14246): Init 676cb13 [ExoPlayerLib/2.8.0] [bacon, A0001, OnePlus, 27]
I/ExoPlayerImpl(14246): Init 8c4cf49 [ExoPlayerLib/2.8.0] [bacon, A0001, OnePlus, 27]
D/NetworkSecurityConfig(14246): No Network Security Config specified, using platform default
W/VideoCapabilities(14246): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(14246): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(14246): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities(14246): Unsupported profile 4 for video/mp4v-es
D/SurfaceUtils(14246): connecting to surface 0x8edda008, reason connectToSurface
I/MediaCodec(14246): [OMX.qcom.video.decoder.avc] setting surface generation to 14587905
D/SurfaceUtils(14246): disconnecting from surface 0x8edda008, reason connectToSurface(reconnect)
D/SurfaceUtils(14246): connecting to surface 0x8edda008, reason connectToSurface(reconnect)
D/SurfaceUtils(14246): set up nativeWindow 0x8edda008 for 560x320, color 0x7fa30c04, rotation 0, usage 0x42002900
D/vndksupport(14246): Loading /vendor/lib/hw/android.hardware.graphics.allocator@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport(14246): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
W/GrallocMapperPassthrough(14246): buffer descriptor with invalid usage bits 0x2002000
I/chatty  (14246): uid=10092(com.example.videotest) CodecLooper identical 4 lines
W/GrallocMapperPassthrough(14246): buffer descriptor with invalid usage bits 0x2002000
I/ACodec  (14246): codec does not support config priority (err -2147483648)
D/SurfaceUtils(14246): set up nativeWindow 0x8edda008 for 560x320, color 0x7fa30c04, rotation 0, usage 0x42002900
D/AudioTrack(14246): Client defaulted notificationFrames to 2362 for frameCount 7088
D/vndksupport(14246): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
D/vndksupport(14246): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
I/zygote  (14246): Do partial code cache collection, code=29KB, data=29KB
I/zygote  (14246): After code cache collection, code=29KB, data=29KB
I/zygote  (14246): Increasing code cache capacity to 128KB
D/vndksupport(14246): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
I/chatty  (14246): uid=10092(com.example.videotest) Thread-2 identical 2 lines
D/vndksupport(14246): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
W/OkHttpClient(14246): A connection to http://www.sample-videos.com/ was leaked. Did you forget to close a response body?
I/zygote  (14246): Do partial code cache collection, code=61KB, data=53KB
I/zygote  (14246): After code cache collection, code=61KB, data=53KB
I/zygote  (14246): Increasing code cache capacity to 256KB
W/OkHttpClient(14246): A connection to https://www.sample-videos.com/ was leaked. Did you forget to close a response body?
W/OkHttpClient(14246): A connection to http://www.sample-videos.com/ was leaked. Did you forget to close a response body?
W/OkHttpClient(14246): A connection to http://www.sample-videos.com/ was leaked. Did you forget to close a response body?
I/zygote  (14246): Do full code cache collection, code=123KB, data=88KB
I/zygote  (14246): After code cache collection, code=114KB, data=70KB
E/ExoPlayerImplInternal(14246): Source error.
E/ExoPlayerImplInternal(14246): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal(14246): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
E/ExoPlayerImplInternal(14246): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
E/ExoPlayerImplInternal(14246): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
E/ExoPlayerImplInternal(14246): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal(14246): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal(14246): 	at java.lang.Thread.run(Thread.java:764)
I/flutter (14246): Video player had error com.google.android.exoplayer2.ExoPlaybackException
W/OkHttpClient(14246): A connection to https://www.sample-videos.com/ was leaked. Did you forget to close a response body?
W/OkHttpClient(14246): A connection to http://www.sample-videos.com/ was leaked. Did you forget to close a response body?
W/OkHttpClient(14246): A connection to https://www.sample-videos.com/ was leaked. Did you forget to close a response body?
I/zygote  (14246): Do partial code cache collection, code=125KB, data=82KB
I/zygote  (14246): After code cache collection, code=125KB, data=82KB
I/zygote  (14246): Increasing code cache capacity to 512KB
I/zygote  (14246): Background concurrent copying GC freed 11255(4MB) AllocSpace objects, 7(476KB) LOS objects, 60% free, 3MB/9MB, paused 5.033ms total 71.098ms
```

**Comment by jason-simmons** [comment]
I reproduced this on a Samsung Galaxy S5.

This was introduced by https://github.com/google/skia/commit/dc82994e3a76141cc037c92a644b7a6c54c87ad7

That commit has some special cases for specific platforms and GPUs.  Possibly more devices need to be treated specially?

@bsalomon

**Comment by lishuhao** [comment]
I have the same problem，my device is one plus x Android 6.0，flutter 0.11.3

**Comment by recastrodiaz** [comment]
I can confirm I get the exact same issue on an LG G2 (D802) running kik kat 4.4.2. However, I don't see this problem on an Android Galaxy S6.

Some other issues I believe are actually the same: https://github.com/flutter/flutter/issues/24289#issuecomment-438998391 and  https://github.com/flutter/flutter/issues/23930#issuecomment-439273322

**Comment by tvolkert** [comment]
Fixed by https://skia.googlesource.com/skia/+/a6dddeaac902114677b21cb39f423db0f5557b10 (as soon as that rolls into Flutter)

**Comment by lgArlequin** [comment]
Thanks! I will wait for the update

**Comment by tvolkert** [comment]
@lgArlequin this should be fixed in the latest release (`v0.11.10`, available on the dev and beta channels).  Can you please run `flutter upgrade` and then verify to see if it's fixed for you?

**Comment by microdog** [comment]
@tvolkert We are still facing image distortion problem with v0.11.10 on Smartisan YQ601.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.11.10, on Mac OS X 10.14.1 18B75, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)

• No issues found!
```

```
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2018-11-19T09:37:19.000000Z
  Duration: 00:00:11.05, start: 0.000000, bitrate: 1789 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 750x1334, 1739 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2018-11-19T09:37:19.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 45 kb/s (default)
    Metadata:
      creation_time   : 2018-11-19T09:37:19.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
```

![image](https://user-images.githubusercontent.com/4081579/49064353-96be5c80-f255-11e8-88bb-a259a66c7618.png)


![image](https://user-images.githubusercontent.com/4081579/49064232-34655c00-f255-11e8-8b3e-f3007588d3f1.png)

**Comment by lgArlequin** [comment]
> @lgArlequin this should be fixed in the latest release (`v0.11.10`, available on the dev and beta channels). Can you please run `flutter upgrade` and then verify to see if it's fixed for you?

@tvolkert, no, unfortunately the problem continues.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.13.6 17G3025, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)
```

**Comment by tvolkert** [comment]
Ok, second take... can you please try `v0.11.11` (on the latest `dev` and `beta` channels - available via `flutter upgrade`)?  Thanks!

**Comment by fbatschi** [comment]
same for Nexus 5, Android 5. still affected.

[✓] Flutter (Channel beta, v0.11.11, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

**Comment by hyz1992** [comment]
I have upgrade to dev 0.10.12，and I tried with  Le X620（Android 6.0），MHA-AL00（Android 8.0）,
in this two phone model. But in Che1-CL20（Android4.4.4），the problem still exists。
![The screen shot](https://github.com/hyz1992/gif_ani/blob/master/gif/screenshot.gif)

**Comment by tvolkert** [comment]
@hyz1992 thanks for your patience!  We continue to look into this, and I'm about to release 0.11.13, with another shot at fixing this.

**Comment by jamiegau** [comment]
Great BUT.  I have seen this bug too, but I would assume the #24565 bug is FAR more important than this one as using newer Android devices, this issue is not a problem..  The fact #24565 means video player in next to useless even if this is fixed is the key issue here.   I hope your addressing #24565 too.

**Comment by tvolkert** [comment]
@jamiegau thanks for the heads up on #24565.  We know the exact commit that introduced this bug, which is why we're trying to fix this while it's still fresh in our minds.

**Comment by jamiegau** [comment]
Great, once I see a commit on this I will do some testing from my side.  Reliability is key on these features.  I'll set up a emulator and android device and run it 24/7 in my office and keep an eye on it while I work.  flutter having this feature with a solid and reliable capability is a key feature for many.

**Comment by tvolkert** [comment]
Ok, `v0.11.13` is live on the `dev` and `beta` channels, with the latest attempt at fixing this.

**Comment by microdog** [comment]
@tvolkert Thanks for the fix, I can confirm that the green badge issue has been fixed in `v0.11.13` on Smartisan YQ601, but the image rendering quality does not seem good. Is there anything I can do to improve the quality?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.11.13, on Mac OS X 10.14.1 18B75, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
[✓] VS Code (version 1.29.1)
[✓] Connected device (3 available)

• No issues found!
```

![image](https://user-images.githubusercontent.com/4081579/49271508-f52f4900-f4a8-11e8-8e95-1e30d51c1848.png)

**Comment by hyz1992** [comment]
Yes, it has been fixed in  Che1-CL20（Android4.4.4）,Thank you very much!

**Comment by tvolkert** [comment]
Thanks @microdog.  Would you mind filing a separate issue for that so that this issue doesn't get overloaded?

I'll close this one out - thanks everyone!

**Comment by lishuhao** [comment]
It is working now. Thanks @tvolkert

**Comment by lgArlequin** [comment]
Thanks @tvolkert , I also confirm the fix!

**Comment by RUPESHJHA06** [comment]
I am getting the issue still in the latest android devices(Android 10).
