### ISSUE TITLE
Image rendering issues on Adreno 3xx devices after upgrade from 0.9.4 to 0.10.2

### ISSUE THREAD

**Issue by d0bry** [flutter/flutter#24517]
After upgrade from 0.9.4 to 0.10.2 some images are corrupted or not displayed at all.

I have observed the issue on my friends Samsung Galaxy S4 and the following devices from the Google/Firebase Test Lab:
- Moto G Play (4th Gen) XT1607
- LG K3 LG
- Samsung Galaxy Note 3 Duos Samsung
- Nexus 7 (2013)

All of these have **Adreno 3xx** and I believe the problem is related to that.

There is nothing special in the log output (compared to the proper behavior).
It works OK on:
- all devices/simulator after downgrading to 0.9.4,
- other devices/simulator on 0.10.2 and above.

Unfortunately all of my devices are unaffected (none of them has Adreno 3xx) and it's hard for me to prepare a reduced test case. The affected images are displayed using RawImage widget or directly painted with Canvas.drawImage / Canvas.drawImageRect.

Below is an output extracted from the Firebase Test Lab video. These are 30 sample images:

Galaxy Note 3 Duos, flutter 0.9.4 (proper output):
![v0-9-4](https://user-images.githubusercontent.com/6552566/48697742-9edb2400-ebe5-11e8-8219-7fd4f65dd63e.png)

Galaxy Note 3 Duos, flutter 0.10.2 (corrupted images):
![v0-10-2](https://user-images.githubusercontent.com/6552566/48697749-a39fd800-ebe5-11e8-949b-bd97bb795541.png)

The images are either not displayed at all or contain pixel data from other images (displayed distorted if image width is different).

The root cause may be related to #24402 and #24289.

**Comment by d0bry** [comment]
The issue still occurs on the latest master (v0.11.10-pre.2).

**Comment by d0bry** [comment]
...and on the latest beta (v0.11.9).

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by d0bry** [comment]
No issue on:
```
[√] Flutter (Channel unknown, v0.9.4, on Microsoft Windows [Version 10.0.17134.407], locale pl-PL)
    • Flutter version 0.9.4 at C:\sdk\flutter
    • Framework revision f37c235c32 (8 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\dobry\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by tvolkert** [comment]
Fixed by https://skia.googlesource.com/skia/+/a6dddeaac902114677b21cb39f423db0f5557b10 (as soon as that rolls into Flutter)

**Comment by tvolkert** [comment]
@d0bry this should be fixed in the latest release (`v0.11.10`, available on the dev and beta channels).  Can you please run `flutter upgrade` and then verify to see if it's fixed for you?

**Comment by d0bry** [comment]
The issue still persists on both beta (v0.11.10) and master (0.11.11-pre.2).

**Comment by tvolkert** [comment]
Ok, second take... can you please try `v0.11.11` (on the latest `dev` and `beta` channels - available via `flutter upgrade`)?  Thanks!

**Comment by d0bry** [comment]
Not fixed. Tried beta (v0.11.11) and master (v0.11.12-pre.2).

**Comment by tvolkert** [comment]
Ok, `v0.11.13` is live on the `dev` and `beta` channels, with the latest attempt at fixing this.

**Comment by d0bry** [comment]
Still not fixed unfortunately. Thanks for all your efforts.

I've seen the latest fix (v0.11.13) helped in #24402, so the root cause must have been different.

I'll try to get an affected device and possibly prepare a reduced test case (my current scenario is quite complex and the issue seems to occur only after some initial image drawing operations).

Clearly the issue started between v0.9.4 and v0.10.2. Is there any way I can help in investigating this (like trying specific versions of skia in between these Flutter versions)?

**Comment by tvolkert** [comment]
Thanks for your patience, @d0bry.  Yes, if you could come up with a reduced test case, that'd help a bunch!

**Comment by d0bry** [comment]
I'll see what I can do. In the meantime I've run a few more tests to narrow it down.

Everything is still fine on:
v0.10.2-pre.56 (checkout 4452bd0a6bf3fb3590072926797e31c9d17024b0) - **still good**

The issue was introduced in:
v0.10.2-pre.57 (checkout b715cf142d32c5511d0a22bcc0fdb76ddd879625) - **this issue occurs**

(in case you don't already know)

**Comment by tvolkert** [comment]
The corresponding Skia commit range where this was introduced is https://skia.googlesource.com/skia.git/+log/b46c4d0925ad..dfca8f6adb6b

/cc @bsalomon since that commit range includes https://skia.googlesource.com/skia.git/+/dc82994, which is known to have triggered similar issues #24402, #24289, #24391, and #23900

@d0bry if you're [set up to build the engine](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment), you could try bisecting the Skia commits in that range and then running Flutter with the `--local-engine` flag to see which commit triggered this.

**Comment by d0bry** [comment]
Thanks, @tvolkert. I've never built the engine, so I'll skip that for now.

I finally got an affected device and was able to create a relatively simple test case.
The code with images is here: [imagebug.zip](https://github.com/flutter/flutter/files/2637383/imagebug.zip) - unzip into a newly created Flutter app project.

```
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'image bug investigation',
      home: ImageFolder(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class ImageFolder extends StatefulWidget {
  ImageFolder({Key key}) : super(key: key);

  @override
  _ImageFolderState createState() => _ImageFolderState();
}

class _ImageFolderState extends State<ImageFolder> {
  bool _loading = true;
  List<ui.Image> _images;

  Future<Null> initRes() async {
    _images = [];

    List<String> imageNames = [
      "image0",
      "image1",
      "image2",
      "image3",
      "image4"
    ];

    for (String name in imageNames) {
      ByteData pngData = await rootBundle.load('assets/$name.png');

      ui.Codec codec =
          await ui.instantiateImageCodec(pngData.buffer.asUint8List());
      ui.Image image = (await codec.getNextFrame()).image;
      _images.add(image);
    }

    setState(() {
      _loading = false;
    });
  }

  @override
  void initState() {
    super.initState();
    initRes();
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) return Container();

    return Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      Container(
        width: 100.0,
        height: 100.0,
        child: CustomPaint(
          painter: TestImagePainter(_images),
        ),
      ),
      Image.asset("assets/image2.png", width: 100.0, height: 100.0),
      RawImage(image: _images[2], width: 100.0, height: 100.0),
      Image.network(
          "https://raw.githubusercontent.com/flutter/flutter/master/examples/flutter_gallery/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
          width: 100.0,
          height: 100.0),
    ]);
  }
}

class TestImagePainter extends CustomPainter {
  List<ui.Image> _images;

  TestImagePainter(this._images);

  @override
  void paint(Canvas canvas, Size size) {
    canvas
      ..save()
      ..scale(0.2);

    for (ui.Image image in _images)
      canvas.drawImage(
          image, Offset.zero, Paint()..filterQuality = FilterQuality.high);

    canvas.restore();
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}
```

Result on Moto G4 Plus (as expected):
![g4plus](https://user-images.githubusercontent.com/6552566/49344522-c23baf80-f678-11e8-925f-08f2dbaaeed6.png)

and on Moto G4 Play (Image.asset, RawImage and Image.network not displayed):
![g4play](https://user-images.githubusercontent.com/6552566/49344524-c8ca2700-f678-11e8-8cbf-e9c10d95c11e.png)

Both on the latest beta (v0.11.13).

**Comment by d0bry** [comment]
Ok, good news. It looks the issue **doesn't occur when the _filterQuality_ of all images is _low_ or _none_.** These are usually the defaults (at least for image widgets and _Paint_).

Interestingly, setting _filterQuality_ to _medium/high_ for some images may affect other images (not necessarily the ones with this setting, as in the code above). May be somehow related to mipmapping used in _medium/high_...

Anyway, non-default _filterQuality_ + Adreno 3xx makes it more of a corner case. I'll stick to _filterQuality.low_ for now, which seems good enough for most use cases.

Still happy to help with the investigation if needed.

**Comment by cbracken** [comment]
/cc @brianosman for input from the Skia side.

@d0bry I assume you're still seeing this issue when filterQuality is set to medium/high?

**Comment by d0bry** [comment]
@cbracken Yes, just checked the attached sample ([imagebug.zip](https://github.com/flutter/flutter/files/2637383/imagebug.zip)) on the current master (v1.2.1-pre.72) with Moto G3. The result is a bit different - none of the images is displayed. After changing FilterQuality.high to low all is good.

**Comment by diglesia-google** [comment]
Hi, I'm seeing the same behavior.  Also on an Adreno GPU, and similarly, the problem only shows up on filterQuality being set.

I'm using Image.memory() on png data, with filterQuality=high. The image displays only when it is shown at the full size of the image data; when shown at any other size (by setting parameters on Image.memory()), it does not display. When the size is set by a surrounding container, instead of by the Image object itself, it works fine. (These distinctions were reflected in the sample code four posts up, just confirming).

To clarify:
This works (surrounding container custom size):
Container(width:<custom with>, size: <custom size>, child:Image.memory(pngData, filterQuality:high));

So does this (Image size is the same as underlying image size, i.e. is displayed at 100% scale)
Image.memory(pngData, width:<actual image width> height:<actual image height> filterQuality:high));

But this shows nothing:
Image.memory(pngData, width:<arbitrary width> height:<arbitrary height> filterQuality:high);

Note that this happened for most of my app's pngs (all of the same format: single-channel grayscale, without an alpha), but for _some_ other images (e.g. a color png with an alpha channel) it showed the image, but with incorrect color (as if it was mis-reading the color channels), and in other cases (jpg images) showed the image correctly at all times.

**Comment by brianosman** [comment]
Update: I have reproduced this in Flutter using the attached sample (thank you!). I've done some poking, and have found some overly broad changes to get it working, but they're not something I want to land. I've tried to reproduce the issue in Skia, without success. I'm going to continue investigating...

**Comment by brianosman** [comment]
I'm almost certain this is a driver bug, and I've been unable to replicate it outside of Flutter. I did simplify the reproduction case, which helped to eliminate a few possible causes. At this point, I can't even come up with a good workaround, other than:

1) Force Adreno 3xx GPUs to build mips for all textures on the IO thread (at upload time). Currently, images are uploaded without mips, and copies are made on the GPU thread if it's later decided that mips are needed.

2) Blacklist Adreno 3xx GPUs from using mips entirely.

Either of these is straightforward to implement. The second option could actually hurt performance (and visual quality), but will cause all of these devices to use strictly less memory than they do now.

The first option adds mip-chain memory overhead (~30%) to all images, but might be a wash (or net win), depending on how many images are currently being drawn at reduced scale with medium or high filtering. We can't currently mipmap a cross-context image in-place after it's been created, so the GPU thread ends up creating a whole new image, with a copy of the base level. If we pre-mip on the IO thread, then we avoid all of that. For what it's worth, I think it could even make sense to do this on all GPUs - the images that are most affected are large, and those are also the ones most likely to be drawn at reduced scale.
