### ISSUE TITLE
Problem with google maps in IOS, after minimizing and maximizing the app, all the widgets are frozen.

### ISSUE THREAD

**Issue by aldobm** [flutter/flutter#24900]
Steps to Reproduce

1. ... Run the example .pub-cache/git/plugins-821f854f1119abfa43e21be9f5fc11ee9359a447/packages/google_maps_flutter/example/ios
2. ... Open the app in Iphone 6, IOS 12.1 (16B92)
3. ... Check the widgets animation ( Buttons ), all Ok, Map Works OK.
4. ... Press home button. (The app minimize).
5. ... touch the app icon. (The app Maximize).
6. ... Check the widgets,  the animation of the widgets buttons frozen, but the code run. Another Widgets (Drawer, Animated box) all frozen.

Logs in XCODE
```
2018-12-01 11:43:57.955655-0500 Runner[939:138948] [DYMTLInitPlatform] platform initialization successful
W1201 11:43:58.056840       1 commandlineflags.cc:1503] Ignoring RegisterValidateFunction() for flag pointer 0x1016d3e90: no flag found at that address
2018-12-01 11:43:58.561318-0500 Runner[939:138779] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2018-12-01 11:43:58.561411-0500 Runner[939:138779] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2018-12-01 11:43:58.859680-0500 Runner[939:138982] flutter: Observatory listening on http://127.0.0.1:64228/
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/BD499C4A-877C-437B-9507-55562C1619F0/Runner.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/BD499C4A-877C-437B-9507-55562C1619F0/Runner.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/BD499C4A-877C-437B-9507-55562C1619F0/Runner.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
2018-12-01 11:44:17.559173-0500 Runner[939:139029] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x103e46ea0] get output frames failed, state 8196
2018-12-01 11:44:17.560382-0500 Runner[939:139029] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x103e46ea0] get output frames failed, state 8196
2018-12-01 11:44:17.565106-0500 Runner[939:139029] TIC Read Status [2:0x0]: 1:57
2018-12-01 11:44:17.565868-0500 Runner[939:139029] TIC Read Status [2:0x0]: 1:57
```

```
[✓] Flutter (Channel master, v0.11.14-pre.2, on Mac OS X 10.13.6 17G65, locale
    en-EC)
    • Flutter version 0.11.14-pre.2 at /Users/aldo/flutter
    • Framework revision a226c0f0d9 (16 hours ago), 2018-11-30 16:18:18 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/aldo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 64 • emulator-5554                            •
      android-x64 • Android 8.0.0 (API 26) (emulator)
    • iPhone de aldo               • 34c051847f3a5fcb2cf5ae0de8b95fb328b525bd •
      ios         • iOS 12.1
```

**Comment by profjared** [comment]
Was so pumped after Flutter Live, but this is a showstopper for us - map is critical to our app. Hoping for a quick fix from you all. Thank you!

**Comment by guruprasath-b** [comment]
is there any temporary work around for this?

**Comment by timtraversy** [comment]
@guruprasath-b I noticed that in the Testflight build of my app, this issue doesn't occur, so it seems to have something to do with release/debug differences.

**Comment by timtraversy** [comment]
This is probably known, but this is an issue with `FlutterPlatformView` on iOS. In both the webview and maps plugin example iOS apps, the UI freezes if the app is minimized. Doesn't seem to happen on Android.

**Comment by csjames** [comment]
This problem isn't unique to the google maps plugin. I was developing a similar integration using MapBox native UI views and the same issue occurs, indicator some form of gesture recognition issue?

**Comment by timtraversy** [comment]
Yeah. @zoechi do you think this issue is somewhere in the engine? I'd be happy to work on fixing it but I'm not really familiar with that end of things. This UI freeze means the whole google map plugin can't be used in production.

**Comment by IhorKlimov** [comment]
I come from the referenced issue, mine seems somewhat close. 

The current solution I came up with is to have a base state for every page, which overrides WidgetBindingObserver#didChangeAppLifecycleState, check if platform is iOS and state is resumed, then push replacement of your root page (basically reloading the app)

Ugly, but works

**Comment by amirh** [comment]
I can't reproduce this, can you elaborate what do you mean by "widget button freezes"? Does this happen on both physical devices and simulators?

**Comment by amirh** [comment]
Thanks, I can see this on a physical device.

**Comment by timtraversy** [comment]
https://drive.google.com/open?id=16VJ_-PttPBOhlB19E3f5HKJyByT2hIf8
Same issue with the WebView plugin, so seems like a UiKitView problem, not google map specific.

**Comment by aldobm** [comment]
Excelent, now works fine, update flutter channel master

`[✓] Flutter (Channel master, v1.1.5-pre.36, on Mac OS X 10.13.6 17G65, locale
    en-EC)
    • Flutter version 1.1.5-pre.36 at /Users/aldo/flutter
    • Framework revision ff9f7236e6 (4 hours ago), 2018-12-28 15:34:15 -0800
    • Engine revision 1bd9d41f89
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 88e6fe0f67)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aldo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone de aldo • 34c051847f3a5fcb2cf5ae0de8b95fb328b525bd • ios • iOS 12.1

`

**Comment by awazgyawali** [comment]
I am facing similar issue on my OnePlus 6 while running google maps. Is anybody  facing the same?

**Comment by bogdannedelcu** [comment]
I tested with master channel and the map control. After hiding/repoen the app the behavior seems to have been improved, but still sometimes I swipe on the map and nothing happens. On the second swipe it works ok. Seems the map does not get the touch events, They get routed in my case to the corner button showing the Drawer of the app which keeps showing the Drawer.

**Comment by Nazacheres** [comment]
Still facing this issue with latest stable flutter and latest google maps library. 100% chance to reproduce on iPhone X: lock the screen, wait for a bit. Open it again -> widgets got frozen.

**Comment by timtraversy** [comment]
The fix was pushed to the `master` branch, I don't think it's made it to `stable` yet

**Comment by csjames** [comment]
Be warned that master is basically the Fury Road in terms of using in
production

**Comment by Menelphor** [comment]
Im still facing this bug, also on the flutter master channel

**Comment by qypengzai** [comment]
@timtraversy hello, only one platform view works well, but when I have two or more platform view in the page, the problem reproduce again.

**Comment by qypengzai** [comment]
@timtraversy  Another Interesting case, when I have two platform view in the page, turning the app back into background and coming back to the foreground, the APP's UI frozen with no doubt.But when I delete one of the platform view, the UI became normal!

**Comment by timtraversy** [comment]
What version of flutter are you using?

**Comment by RyanRamchandar** [comment]
@timtraversy I ran into the same issue @qypengzai did and I documented it in #40050

cc @amirh seems like a regression?
