### ISSUE TITLE
Obfuscating dart code causing incompatibility in most of the devices.

### ISSUE THREAD

**Issue by ctrleffive** [flutter/flutter#25072]
I've experienced this issue in two different apps. When building release apk in first app, the app builds successfully. But as soon as the app opens, it crashed. I removed below line i added before in **android/gradle.properties** and rebuild.

`extra-gen-snapshot-options=--obfuscate`

App worked without problem later.

Yesterday i faced the same issue with a new app. Now the app is running in some of the devices i have. I published the app to play store. The app is incompatible with almost all phones except mine. I disabled obfuscation and uploaded patched version. Now it is working fine.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by cujslive** [comment]
```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_IN)
    • Flutter version 1.0.0 at /home/chandu/Flutter
    • Framework revision 5391447fae (7 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/chandu/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Redmi Note 4 • 192.168.0.101:5555 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by goderbauer** [comment]
@liamappelbe Do you know when exactly https://github.com/dart-lang/sdk/issues/34311 was fixed? Did that make the cut for Flutter's 1.0.0? If yes it looks like there are still issues with obfuscation (see comments above)...

**Comment by mraleph** [comment]
I think some classes in the framework (and potentially `dart:ui`) are still missing proper `@pragma('vm:entry-point')` annotations - see for example https://github.com/flutter/flutter/issues/24329, obfuscated apps would break in bizarre ways if functionality from those classes is touched. 

/cc @sjindel-google

**Comment by goderbauer** [comment]
@mraleph How can we identify the complete set of classes that needs the annotation? Any way to write an automated test to ensure that all classes that need it have it?

**Comment by mraleph** [comment]
@goderbauer I think the only reliable way is to go through all your C++ code and look at every single use of Dart VM C API and each time it reaches into Dart by name (e.g. accesses a field by name, invokes method by name etc) you need to check that  target of the invocation is marked with the pragma. 

@sjindel-google has added an assertion into Dart VM that does not allow you to access classes that are not marked with pragma. I think we need to expand that assertion further to cover methods and fields. 

I think we had temporarily softened the assertion, but we should actually tighten it back up. I have filed a bug for this: https://github.com/dart-lang/sdk/issues/35369

**Comment by modulovalue** [comment]
Was this ever investigated further? I have an app on the play store that also is incompatible with a ton of devices that should be compatible. 

Should `flutter run -d "S" --release extra-gen-snapshot-options=--obfuscate` run without any problems? because it also crashes on me with

```dart
E/flutter ( 7202): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'Lac' was called on null.
E/flutter ( 7202): Receiver: null
E/flutter ( 7202): Tried calling: Lac
E/flutter ( 7202): #0      kE.wbc (gmd:90)
E/flutter ( 7202): <asynchronous suspension>
E/flutter ( 7202): #1      lE.wbc (gmd:429)
E/flutter ( 7202): <asynchronous suspension>
E/flutter ( 7202): #2      DE.bcc (rmd:228)
E/flutter ( 7202): <asynchronous suspension>
E/flutter ( 7202): #3      main (Imd:14)
E/flutter ( 7202): <asynchronous suspension>
E/flutter ( 7202): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dpd:229)
E/flutter ( 7202): #5      _aZ (upd:1124)
E/flutter ( 7202): #6      _Wb.Sla (upd:1021)
E/flutter ( 7202): #7      _zZ (upd:1516)
E/flutter ( 7202): #8      vZ (upd:1500)
E/flutter ( 7202): #9      _runMainZoned.<anonymous closure> (dpd:221)
E/flutter ( 7202): #10     _startIsolate.<anonymous closure> (hsd:305)
E/flutter ( 7202): #11     _RawReceivePortImpl._handleMessage (hsd:172)
E/flutter ( 7202): 

```

**Comment by sjindel-google** [comment]
@modulovalue This looks like a separate issue which is unrelated to the Flutter engine.

Are you using noSuchMethod or any other reflective features of Dart?

**Comment by mraleph** [comment]
@modulovalue could you deobfuscate the stack trace to see where exactly it crashes?

**Comment by modulovalue** [comment]
@sjindel-google @mraleph sorry for the false alarm around the stacktrace. It was my mistake and totally unrelated to this issue.

However, the issue around incompatible devices still remains. I'll try to publish my app with no obfuscation to see if that changes anything.

**Comment by modulovalue** [comment]
@sjindel-google The error that I mentioned before was indeed not caused by obfuscation.
What I'm trying to find out is why my App is being shown as incompatible with devices that fall into the SDK range of supported devices. 

cujslive said
>  I published the app to play store. The app is incompatible with almost all phones except mine. I disabled obfuscation and uploaded patched version. Now it is working fine.

I'm experiencing something similar and I hope that disabling obfuscation will also have the same effect.

**Comment by zanderso** [comment]
I hid several comments that appeared off-topic. In particular @emattu your issue appears related to your app's dependencies @blasten.

@mraleph @goderbauer @sjindel-google can this issue be closed?

**Comment by emattu** [comment]
@zanderso I was only able to release the app because I skipped the obfuscate process. Apologies for posting in the wrong thread and thanks for looking at my issue and providing a solution.

**Comment by mraleph** [comment]
To the best of my knowledge `--obfuscate` works, so I am going to close this issue.
