### ISSUE TITLE
ElevatedButton and  PhysicalModel has a problem

### ISSUE THREAD

**Issue by ShowMeThe** [flutter/flutter#25130]
```dart
  @override
  Widget build(BuildContext context) {
    return PhysicalModel(
        color: Colors.blue,
        elevation: calculateElevation(),
        borderRadius: BorderRadius.circular(25.0),
        child: Container(
          key: _globalKey,
          height: 48.0,
          width: _width,
          child: RaisedButton(
            padding: EdgeInsets.all(12.0),
            color: _state == 2 ? Colors.green : Colors.blue,
            child: buildButtonChild(),
            onPressed: () {},
            onHighlightChanged: (isPressed) {
              setState(() {
                _isPressed = isPressed;
                if (_state == 0) {
                  animateButton();
                }
              });
            },
          ),
        ));
  }
```

But I see this，but I want the RaisedButton corner is circular？
![default](https://user-images.githubusercontent.com/30461332/49696169-f7984e00-fbe0-11e8-9531-a74f8f2a9734.PNG)

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by ShowMeThe** [comment]
import 'package:flutter/material.dart';
import 'dart:async';

class ProgressButton extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => _ProgressButtonState();
}

class _ProgressButtonState extends State<ProgressButton>
    with TickerProviderStateMixin {
  bool _isPressed = false, _animatingReveal = false;
  int _state = 0;
  double _width = 300;
  Animation _animation;
  GlobalKey _globalKey = GlobalKey();
  AnimationController _controller;

  @override
  void deactivate() {
    reset();
    super.deactivate();
  }

  @override
  dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return PhysicalModel(
        color: Colors.blue,
        elevation: calculateElevation(),
        borderRadius: BorderRadius.circular(25.0),
        child: Container(
          key: _globalKey,
          height: 48.0,
          width: _width,
          child: RaisedButton(
            padding: EdgeInsets.all(0.0),
            color: _state == 2 ? Colors.green : Colors.blue,
            child: buildButtonChild(),
            onPressed: () {},
            onHighlightChanged: (isPressed) {
              setState(() {
                _isPressed = isPressed;
                if (_state == 0) {
                  animateButton();
                }
              });
            },
          ),
        ));
  }

  void animateButton() {
    double initialWidth = _globalKey.currentContext.size.width;

    _controller =
        AnimationController(duration: Duration(milliseconds: 300), vsync: this);
    _animation = Tween(begin: 0.0, end: 1.0).animate(_controller)
      ..addListener(() {
        setState(() {
          _width = initialWidth - ((initialWidth - 48.0) * _animation.value);
        });
      });
    _controller.forward();

    setState(() {
      _state = 1;
    });

    Timer(Duration(milliseconds: 3300), () {
      setState(() {
        _state = 2;
      });
    });

    Timer(Duration(milliseconds: 3600), () {
      _animatingReveal = true;
    });
  }

  Widget buildButtonChild() {
    if (_state == 0) {
      return Text(
        'Login',
        style: TextStyle(color: Colors.white, fontSize: 16.0),
      );
    } else if (_state == 1) {
      return SizedBox(
        height: 36.0,
        width: 36.0,
        child: CircularProgressIndicator(
          value: null,
          valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
        ),
      );
    } else {
      return Icon(Icons.check, color: Colors.white);
    }
  }

  double calculateElevation() {
    if (_animatingReveal) {
      return 0.0;
    } else {
      return _isPressed ? 6.0 : 4.0;
    }
  }

  void reset() {
    _width = 300;
    _animatingReveal = false;
    _state = 0;
  }
}



[√] Flutter (Channel master, v1.0.1-pre.2, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
    • Flutter version 1.0.1-pre.2 at D:\Android\flutter
    • Framework revision 27c8ffa06c (4 days ago), 2018-12-05 14:50:59 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\cuvsu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

**Comment by ShowMeThe** [comment]
import 'package:flutter/material.dart';

void main() => runApp(MyApp());
class MyApp extends StatelessWidget{
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData.light(),
        home: Scaffold(
          body: Center(
            child:PhysicalModel(
                color: Colors.blue,
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  child: RaisedButton(   //MaterialButton 
                    child: Text("123"),
                    onPressed: () {},
                  ),
                )),
          ),
        ));
  }
}

if I change RaisedButton into MaterialButton is ok
RaisedButton ：
![9da0d562073fabb2753c37b38b6f0e1](https://user-images.githubusercontent.com/30461332/49699561-98046780-fc0d-11e8-8373-236ba23b4b4a.jpg)


MaterialButton ：
![f5b7adc9ff3f31fa46116848ff02593](https://user-images.githubusercontent.com/30461332/49699592-08ab8400-fc0e-11e8-83d5-e03d288443df.jpg)

**Comment by TahaTesser** [comment]
Issue still exist

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (5 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129
• No issues found!
```

</details>

**Comment by ShowMeThe** [comment]
![capture](https://user-images.githubusercontent.com/30461332/80683704-350fbb00-8af7-11ea-8717-d2b7766aaa8c.png)

The bug has been fixed, I run the following code in web
```
 Center(
          child: PhysicalModel(
            color: Colors.blue,
            borderRadius: BorderRadius.circular(20),
            child: Container(
              child: FlatButton(onPressed: (){

              }, child: Text("123")),
            ),
          ),
      )
```

[√] Flutter (Channel master, v1.16.4-pre.69, on Microsoft Windows [Version 10.0.17763.1158], locale zh-CN)
    • Flutter version 1.16.4-pre.69 at D:\Android\flutter
    • Framework revision 19e7db585d (4 weeks ago), 2020-04-01 11:16:01 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129
    • Web Server • web-server • web-javascript • Flutter Tools

**Comment by TahaTesser** [comment]
Hi @ShowMeThe 
This issue still exist on mobile 

`PhysicalModel` with `RaisedButton` on mobile 
![flutter_03](https://user-images.githubusercontent.com/48603081/80698870-b1ef6480-8af8-11ea-8c8e-1b1dae162701.png)
![flutter_04](https://user-images.githubusercontent.com/48603081/80698872-b3209180-8af8-11ea-8bf5-db1ae854c207.png)


`PhysicalModel` with `FlatButton` on mobile  

![flutter_02](https://user-images.githubusercontent.com/48603081/80698910-c3d10780-8af8-11ea-9e91-1e2366695829.png)
![flutter_01](https://user-images.githubusercontent.com/48603081/80698913-c5023480-8af8-11ea-8ffd-878c15f8ad0a.png)


`PhysicalModel` with `FlatButton` on web 

<img width="163" alt="Screenshot 2020-04-30 at 3 37 13 PM" src="https://user-images.githubusercontent.com/48603081/80698926-cc294280-8af8-11ea-92a9-dc05e68e9329.png">

**Comment by ShowMeThe** [comment]
Hi  @TahaTesser 
I was too careless. I just tested it on web! Instead of using  PhysicalModel and FlatButton/RaisedButton , I prefer to use the PhysicalModel  and  MaterialButton. By the way , I 'm a little surprised , this bug still here.

**Comment by darshankawar** [comment]
Since `RaisedButton` is deprecated for `ElevatedButton` (https://api.flutter.dev/flutter/material/RaisedButton-class.html), but the issue still persist on stable and master.

<img width="314" alt="Screenshot 2021-01-13 at 5 18 11 PM" src="https://user-images.githubusercontent.com/67046386/104449660-f5c1c580-55c4-11eb-8b17-8922bcacdf4e.png">

<details>
<summary>stable and master flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 1.26.0-2.0.pre.312, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.312 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7c75c01fc3 (9 hours ago), 2021-01-12 19:01:18 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```

</details>

**Comment by ShowMeThe** [comment]
This bug still exist </br>
<img src = "https://user-images.githubusercontent.com/30461332/129871165-410e8e55-e35b-48c0-a0eb-f3ca34669ed4.jpg" width = 400 />

```
class Example extends StatelessWidget {
  const Example({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: PhysicalModel(
        elevation: 12.0,
        color: Colors.deepOrange,
        borderRadius: BorderRadius.circular(25.0),
        child: ElevatedButton(
          onPressed: () {},
          child: const Text("1231"),
        ),
      ),
    );
  }
}

```

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.131, on Microsoft Windows [Version 10.0.19042.1110], locale zh-CN)
    • Flutter version 2.5.0-7.0.pre.131 at D:\Android\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 061dff8ca7 (54 minutes ago), 2021-08-18 04:07:02 -0400
    • Engine revision 99df75c44e
    • Dart version 2.15.0 (build 2.15.0-25.0.dev)
    • Pub download mirror https://pub.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2)
    • Android Studio at D:\Android-Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

```

**Comment by darshankawar** [comment]
@ShowMeThe 
Using the code sample provided below, I got the output as:

<img width="116" alt="Screenshot 2023-03-08 at 5 53 18 PM" src="https://user-images.githubusercontent.com/67046386/223712886-1644f7bd-46f9-4a20-835b-a0d20789b137.png">

<details>
<summary> updated code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Example(),
    ),
  );
}

class Example extends StatelessWidget {
  const Example({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: PhysicalModel(
      //  elevation: 12.0,
        color: Colors.deepOrange,
        borderRadius: BorderRadius.circular(25.0),
        child: ElevatedButton(
          onPressed: () {},
          child: const Text("1231"),
          style: ButtonStyle(
            shape: MaterialStateProperty.all<RoundedRectangleBorder>(
          RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(25),
          //  side: BorderSide(color: Colors.red)
        )
          )),
        ),
      ),
    );
  }
}

```

</details>

See if above solution works for your case.

**Comment by ShowMeThe** [comment]
@darshankawar Thanks for this reply. Setting MaterialStateProperty in ButtonStyle is a solution for my case.
