### ISSUE TITLE
video_player: Could not find com.google.android.exoplayer:exoplayer-core:2.8.0

### ISSUE THREAD

**Issue by westy92** [flutter/flutter#25145]
## Steps to Reproduce

1. attempt to run the `flutter_gallery`: `flutter run --release`

## Logs

```
westy92@westy92-VirtualBox:~/Source/flutter/examples/flutter_gallery$ flutter run --release
Initializing gradle...                                       1.4s
Resolving dependencies...                                   18.5s
Launching lib/main.dart on Pixel in release mode...
Gradle task 'assembleRelease'...                                 

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find com.google.android.exoplayer:exoplayer-core:2.8.0.
  Searched in the following locations:
    - file:/home/westy92/Android/Sdk/extras/m2repository/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.pom
    - file:/home/westy92/Android/Sdk/extras/m2repository/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.jar
    - file:/home/westy92/Android/Sdk/extras/google/m2repository/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.pom
    - file:/home/westy92/Android/Sdk/extras/google/m2repository/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.jar
    - file:/home/westy92/Android/Sdk/extras/android/m2repository/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.pom
    - file:/home/westy92/Android/Sdk/extras/android/m2repository/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.jar
    - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.pom
    - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.jar
    - https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.pom
    - https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-core/2.8.0/exoplayer-core-2.8.0.jar
  Required by:
      project :app > com.google.android.exoplayer:exoplayer:2.8.0
      project :app > com.google.android.exoplayer:exoplayer:2.8.0 > com.google.android.exoplayer:exoplayer-hls:2.8.0
      project :app > com.google.android.exoplayer:exoplayer:2.8.0 > com.google.android.exoplayer:exoplayer-smoothstreaming:2.8.0
      project :app > com.google.android.exoplayer:exoplayer:2.8.0 > com.google.android.exoplayer:exoplayer-ui:2.8.0
> Could not find com.google.android.exoplayer:exoplayer-dash:2.8.0.
  Searched in the following locations:
    - file:/home/westy92/Android/Sdk/extras/m2repository/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.pom
    - file:/home/westy92/Android/Sdk/extras/m2repository/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.jar
    - file:/home/westy92/Android/Sdk/extras/google/m2repository/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.pom
    - file:/home/westy92/Android/Sdk/extras/google/m2repository/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.jar
    - file:/home/westy92/Android/Sdk/extras/android/m2repository/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.pom
    - file:/home/westy92/Android/Sdk/extras/android/m2repository/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.jar
    - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.pom
    - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.jar
    - https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.pom
    - https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-dash/2.8.0/exoplayer-dash-2.8.0.jar
  Required by:
      project :app > com.google.android.exoplayer:exoplayer:2.8.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
 
Gradle task 'assembleRelease'... Done                        7.4s
Gradle task assembleRelease failed with exit code 1
```

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/westy92/Source/flutter
    • Framework revision 5391447fae (10 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/westy92/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/westy92/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/westy92/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Pixel • FA69H0305733 • android-arm64 • Android 9 (API 28)

• No issues found!
```

I could only get this to work by adding a custom repository in `android/build.gradle`:
```
        maven {
            url 'http://repo.spring.io/plugins-release/'
        }
```

I'm guessing you will need to release an update to the `video_player` plugin and then update `flutter_gallery` to use it.

**Comment by XingdongYu** [comment]
the same issue : (

**Comment by zoechi** [comment]
The latest video_player plugin uses 2.9.1. Perhaps you need to upgrade.

**Comment by pupali** [comment]
same issue here, did u find a solution for it??

**Comment by ayush221b** [comment]
Same issue. @zoechi Could you please elaborate?

**Comment by XingdongYu** [comment]
hi @zoechi, here is the video-player version in .packages file:
`video_player:file:///Users/yuxingdong/.pub-cache/hosted/pub.flutter-io.cn/video_player-0.7.2/lib/`
it seems the latest version. If I remove this and the codes about the video_player, the project can be run successfully. Can you give some advice about it?

**Comment by westy92** [comment]
@zoechi the latest `video_player` version is `0.7.2`, which I (and `flutter_gallery`) are using. (https://pub.dartlang.org/packages/video_player)

`video_player` has _unreleased_ changes that seem to be staged as `0.8.0`: https://github.com/flutter/plugins/blob/master/packages/video_player/CHANGELOG.md

**Comment by zoechi** [comment]
@westy92 seems you're right. 
A Git dependency might work for your as workaround
```
dependencies:
  video_player: 
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/video_player
```

**Comment by zoechi** [comment]
changing the order of `google` and `jcenter` in `android/build.gradle` might also work 
```
allprojects {
    repositories {
        google()
        jcenter()
```

**Comment by zxl777** [comment]
How to fix it?

**Comment by zxl777** [comment]
```
dependencies:
  video_player: 
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/video_player

allprojects {
    repositories {
        google()
        jcenter()
```

I have modified two files and " flutter clean;flutter run" still can't work.

```
...
> Could not find com.google.android.exoplayer:exoplayer-smoothstreaming:2.9.1.
  Searched in the following locations:
...
```

**Comment by pupali** [comment]
> ```
> dependencies:
>   video_player: 
>     git:
>       url: https://github.com/flutter/plugins.git
>       path: packages/video_player
> 
> allprojects {
>     repositories {
>         google()
>         jcenter()
> ```
> I have modified two files and " flutter clean;flutter run" still can't work.
> 
> ```
> ...
> > Could not find com.google.android.exoplayer:exoplayer-smoothstreaming:2.9.1.
>   Searched in the following locations:
> ...
> ```

same here .. so is it an exoplayer issue, i tried to create a native project in android studio and added 
exoplayer as dependency 
and same problem occured!!

**Comment by ened** [comment]
https://github.com/google/ExoPlayer/issues/5225

 => should be resolving itself in a few hours

**Comment by xster** [comment]
The temporary fix for the upstream problem (https://b.corp.google.com/issues/120759347) is on master head now. If you're facing this issue, flutter upgrading should resolve it.

**Comment by xster** [comment]
Apologies. Pasted the wrong link. Edited. 

Can you copy paste your whole error output (into a gist or some such)? Further errors are unexpected.

**Comment by Cretezy** [comment]
Just confirming that I'm still getting a missing package on my side too (Canada East).

Seems like @pupali's fix does work:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }
}
```

**Comment by ThinkDigitalRepair** [comment]
No problem. I edited mine too.
Here's a link to the gist. https://gist.github.com/ThinkDigitalRepair/17a30d6e20e535eaecf99197a45f309c

**Comment by ThinkDigitalRepair** [comment]
Unfortunately, with that configuration, I'm still not able to build.
I have:
```gradle
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
    }
}
```

**Comment by ThinkDigitalRepair** [comment]
I moved it afterwards to all projects and it may have fixed that error, but then another one was thrown. :/

**Comment by pupali** [comment]
so its working for me at home.
but in my work it doesn't, it's not able to find smoothstreaming module 
i checked the jcenter here [](https://jcenter.bintray.com/com/google/android/exoplayer/)
all the modules seems to be there except smoothstreaming

**Comment by aBuder** [comment]
@pupali I have the same problem. Is there an workaround available?

**Comment by zxl777** [comment]
> UPDATE (temporary solution) : so it is a jcenter issue
> i tried @westy92 solution (url) it didn't work for me for some reason.
> But adding:
> 
> ```
> maven {
>             url 'https://google.bintray.com/exoplayer/'
>         }
> ```
> to project `build.gradle` (located at the root of the android folder of your project)
> so it becomes:
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         maven {
>             url 'https://google.bintray.com/exoplayer/'
>         }
>     }
> }
> ```
> works for me
> and hopfully it get solved from jcenter.

Thank you, Worked!

**Comment by xster** [comment]
Ah, yes, the originally filed bug was for building the gallery. If you're seeing this issue in your own `flutter create`d projects, adding 

```
maven {
    url 'https://google.bintray.com/exoplayer/'
}
```

such as 

```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }
}
```

will work until https://issuetracker.google.com/issues/120759347 is solved
