### ISSUE TITLE
License script failing

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#25462]
The license script in Skia->Flutter/Engine autoroller started failing for what appears to not be a Skia issue.

skia@autoroll-be-skia-flutter-autoroll-0:/data/engine/src/flutter/tools/licenses$ /data/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart lib/main.dart --release --src ../../.. --out /data/engine/src/out/licenses

(attempting to post only the relevant error logs below)
```       775 of 10477 ░░░░░░░░░░ 7% (1 missing licenses)  .../third_party/boringssl/src/crypto/asn1/a_bitstr.c    error searching for copyright in: ../../../third_party/boringssl/src/crypto/asn1/a_bool.c

      1363 of 10477 █░░░░░░░░░ 13% (226 missing licenses)  .../../third_party/boringssl/src/ssl/tls_method.ccerror searching for copyright in: ../../../third_party/boringssl/src/ssl/tls_record.cc
unmatched potential copyright and license statements; first twenty lines:
----8<----
/* Copyright (C) 1995-1998 Eric Young (eay@cryptsoft.com)
 * All rights reserved.
 *
 * This package is an SSL implementation written
 * by Eric Young (eay@cryptsoft.com).
 * The implementation was written so as to conform with Netscapes SSL.
 *
 * This library is free for commercial and non-commercial use as long as
 * the following conditions are aheared to.  The following conditions
 * apply to all code found in this distribution, be it the RC4, RSA,
 * lhash, DES, etc., code; not just the SSL code.  The SSL documentation
 * included with this distribution is covered by the same copyright terms
 * except that the holder is Tim Hudson (tjh@cryptsoft.com).
 *
 * Copyright remains Eric Young's, and as such any Copyright notices in
 * the code are not to be removed.
 * If this package is used in a product, Eric Young should be given attribution
 * as the author of the parts of the library used.
 * This can be in the form of a textual message at program startup or
 * in documentation (online or textual) provided with the package.
```

I get the same error when running locally.

**Comment by rmistry** [comment]
@liyuqian

**Comment by rmistry** [comment]
Actually I see an error before running the above script:
```
$ ../../../third_party/dart/tools/sdks/dart-sdk/bin/dart lib/main.dart --src ../../.. --out ../../../src/out/licenses --golden ../../ci/licenses_golden/

lib/main.dart:1: Warning: Interpreting this as package URI, 'package:licenses/main.dart'.
Finding files...
Collecting licenses for _gclient_flutter_cqE_Vs
    Failed to read signature file, scanning directory.
failure: Invalid argument(s): Progress.max must be > 0 but was: 0
#0      new _Progress (package:licenses/main.dart:2111:7)
#1      main (package:licenses/main.dart:2251:34)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

aborted.
```

**Comment by cbracken** [comment]
As a quick workaround for this issue, the 'fix' appears to be to blow away your flutter third_party directory and do a clean build. 

I grabbed a copy of one of the failing files before and after doing this, and they appear to be identical. I'm still entirely unsure of what's causing this particular licence regex to not match in this case, but I'd suggest running a clobber build to get the auto-roller going again.

**Comment by rmistry** [comment]
I deleted engine/src/third_party, did gclient sync and ran license script again, failed with the same error.

**Comment by cbracken** [comment]
I suspect I've found it. Should be fixed momentarily.

**Comment by cbracken** [comment]
Fix is out in flutter/engine#7242.

**Comment by rmistry** [comment]
I am still getting the error mentioned in https://github.com/flutter/flutter/issues/25462#issuecomment-447897407
Not sure what I am doing wrong. I blew away third_party several times while testing.
Any recommendations on what I should look for in third_party that is causing that error?

**Comment by cbracken** [comment]
The issue was a bug in the licence script itself, not in any of the source files. If the auto-roller has synced to engine commit 5c63303 or later, things should just work.

> Also, would be great if one day we could tell the license script that we only care about licenses_skia and third_party/skia so that we are not impacted by changes in other directories.

The script is designed to skip checking licences so long as it detects no changes in the fileset for a given component vs what's in the golden file. In such cases, normally you'd see: 

```
Finding files...
Collecting licenses for flutter
       678 of 678 ██████████ 100% (0 missing licenses)  Done.
Collecting licenses for third_party
    Skipping this component - no change in signature
Collecting licenses for skia
       100 of 3619 ░░░░░░░░░░ 3% (0 missing licenses)  .../third_party/skia/bench/PicturePlaybackBench.cpp^C
```

I'll catch up with you over chat to see if we can figure out what's going on with the bot.
