### ISSUE TITLE
Title of pinned, floating SliverAppBar not fading out with "bottom"

### ISSUE THREAD

**Issue by TheJulianJES** [flutter/flutter#25993]
## Steps to Reproduce

The "issue"/(unexpected behavior) that can be seen is that the title of the `SliverAppBar` no longer fades out when it's pinned and floating when the "bottom" has a widget.

Previously (current beta/stable) the title slowly faded out when the `NestedScrollView` is scrolled and the bottom "overlaps" the title which was almost invisible by the time the bottom was at the top.

Now the title no longer fades out when the `NestedScrollView` is scrolled and the "bottom" basically overlaps the title with no transition.

(See videos // screenshots)

This is probably related to: #25051 @goderbauer 

Code to reproduce (try on current dev channel and on current beta/stable => Flutter 1.0.0):
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage();

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
          headerSliverBuilder: (context, innerBoxScrolled) => [
                SliverAppBar(
                  title: Text("Sliver App Bar"),
                  floating: true,
                  pinned: true,
                  bottom: PreferredSize(
                    preferredSize: Size.fromHeight(35.0),
                    child: Padding(
                      padding: EdgeInsets.fromLTRB(8.0, 0.0, 8.0, 8.0),
                      child: Container(
                        width: 144.0,
                        child: TextField(
                          maxLines: 1,
                          textAlign: TextAlign.center,
                          decoration: InputDecoration(
                            hintText: 'Text Field',
                            focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.white)),
                            border: UnderlineInputBorder(borderSide: BorderSide(color: Colors.white)),
                            contentPadding: EdgeInsets.all(2.0),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
          body: ListView.builder(itemBuilder: (context, index) {
            return Text('Sample Text: $index');
          })),
    );
  }
}
```
## Logs

```
```

`flutter analyze`:
```
Analyzing testing_app...                                         
No issues found! (ran in 1.2s)
```

`flutter doctor -v` (current beta // stable channel which doesn't have the issue):
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale de-DE)
    • Flutter version 1.0.0 at /Users/USERNAME/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/USERNAME/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

`flutter doctor -v` (current dev channel which has the issue):
```
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.14.2 18C54, locale de-DE)
    • Flutter version 1.1.4 at /Users/USERNAME/flutter
    • Framework revision 7a88fbc5fd (13 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)
...
```

Screenshots (in fade / overlap):

Previously (title fading out when NestedScrollView is scrolled):
<img width="452" alt="bildschirmfoto 2019-01-03 um 02 27 49" src="https://user-images.githubusercontent.com/6409465/50620779-d38b0c80-0f01-11e9-9c9d-6e63a44b769f.png">
Video: https://youtu.be/ozBWfNvpIz8

Now (title not fading out when NestedScrollView is scrolled):
<img width="448" alt="bildschirmfoto 2019-01-03 um 02 24 52" src="https://user-images.githubusercontent.com/6409465/50620788-e00f6500-0f01-11e9-81ab-fa3e6d27bb0d.png">
Video: https://youtu.be/YMG1SZmA8Bw

**Comment by goderbauer** [comment]
I posted PR https://github.com/flutter/flutter/pull/26021 for review, which should fix the issue.

**Comment by KorbinianMossandl** [comment]
@goderbauer 
I am still seeing the issue on the latest release Flutter 1.7.8+hotfix.4

**Comment by goderbauer** [comment]
I cannot reproduce the issue described in the first post on master. That one is still fixed. If you are seeing any issues, it may be a new one. Please open a new bug with code that reproduces your issue.
