### ISSUE TITLE
Android Camera Preview Dark (Samsung Galaxy Tab A)

### ISSUE THREAD

**Issue by NickCullen** [flutter/flutter#26079]
Hi,

The camera preview on the Samsung Galaxy Tab A is very dark. 

I've wrote an in app camera for my app using Xamarin a few months back and had the same issue. To fix it I had to reduce the camera previews FPS range (I basically picked the first off of the list camera characteristics for the FPS ranges for the camera device). The reason being is that the FPS was too high for the exposure and it couldn't keep up so it basically 'gives up'.

[This is the link](https://stackoverflow.com/questions/38493000/camera2basic-app-has-very-dark-preview-in-android-6-0-lgg3) to the stack overflow issue that helped me fix my issue.

I don't have access to my code currently, but is this something you guys can look into? Or maybe I can help out?

**Comment by NickCullen** [comment]
Thanks I’ll have a look as soon as I can. 

I’m not 100% sure the other issue you referenced is related as such. They’re on about the resulting image being dark and not the camera preview but I will have a look at that also :)

**Comment by NickCullen** [comment]
FWIW: I have now fixed this, just battling with Windows to install the flutter_plugin_tools (it appears to hang for me... yay!) 

Will create a pull request as soon as.

**Comment by jatinmadaan8** [comment]
Hey @NickCullen  I'm still getting this problem. Can you please share some sample code.Thanks

**Comment by NickCullen** [comment]
@jatinmadaan8 Hey, I created a pull request but it is on hold at the moment as they're favouring quality over features.

The issue is that the camera preview FPS is too high / fast for the exposure to work correctly. To fix it, you can query an array of available FPS ranges for the device's camera - my fix attempted to pick the one with the largest range in FPS so that it would use the slower FPS if the exposure is struggling or use a high FPS if the device is more able. 

This then turned into a feature request because it may not be an ideal choice for certain applications - i.e. some apps may want this high FPS (why I don't know as the camera preview is too dark, but I understand the concern). Therefore, there should be an option when opening up the camera via your dart code to favour this low FPS over picture quality or not. I just don't have the time to implement this change at the moment.

You can view my change here if you want to branch the plugin and use it internally for now, if this is what you desire: 
https://github.com/flutter/plugins/pull/1035

**Comment by jatinmadaan8** [comment]
@NickCullen Thank you so much i just tried your solution and it's working very well. Thank you again.

**Comment by EmmanuelMess** [comment]
This seems that is replicable on LG K11alpha also.

**Comment by Abhishek01039** [comment]
Hello @TahaTesser 
This issue might be solved by mvanbeusekom here https://github.com/flutter/plugins/pull/3383
can you please take a look?
Thanks

**Comment by TahaTesser** [comment]
@nichtverstehen 
No worries, Is there any chance you still have this device? Can confirm if the issue persists?

@Abhishek01039 
I don't have access to this device, none of my devices have this issue

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
