### ISSUE TITLE
TextField issue: TextField doesn't get focus in Android

### ISSUE THREAD

**Issue by hnvn** [flutter/flutter#26563]
I've just upgraded Flutter to v1.1.10-pre.58 and `TextField` doensn't get focus in Android anymore. (tap in `TextField` but keyboard doesn't open up)
````
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.1.10-pre.58, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
````

**Comment by taijuan** [comment]
Same as above
However, it happened in xiaomi phones

**Comment by hnvn** [comment]
I have to downgrade to v1.1.9

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by ncb000gt** [comment]
Here is something that reproduces the issue for me:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Demo'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            TextField(
              decoration: InputDecoration(
                hintText: 'test',
                labelText: 'test'
              )
            ),
          ],
        ),
      ),
    );
  }
}
```

Doctor
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.73, on Mac OS X 10.14 18A391, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

I'm running `Android 9`, kernel version `4.4.116-g921edebf2ac5`.

As an aside, I also noticed this when pressing on a text field (sharing in the off chance it is related). I did add some printout to the flutter project and it did seem like some press pressures did go over 1 which is why the assertion triggered. I did a `flutter clean` and they seemed to go away, but that seemed suspicious to me... Also, when I run this in the iOS emulator it doesn't appear to be an issue and the press pressure is NaN, but I'm guessing that's due to it not being an actual device.
```
I/flutter (20454): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20454): The following assertion was thrown while routing a pointer event:
I/flutter (20454): 'package:flutter/src/gestures/force_press.dart': Failed assertion: line 220 pos 14: 'pressure.isNaN
I/flutter (20454): ? true : (pressure <= 1.0 && pressure >= 0.0)': is not true.
I/flutter (20454):
I/flutter (20454): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20454): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20454): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20454):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20454):
I/flutter (20454): When the exception was thrown, this was the stack:
I/flutter (20454): #2      ForcePressGestureRecognizer.handleEvent (package:flutter/src/gestures/force_press.dart:220:14)
I/flutter (20454): #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (20454): #4      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (20454): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter (20454): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (20454): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (20454): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (20454): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (20454): #13     _invoke1 (dart:ui/hooks.dart:189:10)
I/flutter (20454): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:138:5)
I/flutter (20454): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (20454):
I/flutter (20454): Event:
I/flutter (20454):   PointerMoveEvent(Offset(177.1, 106.3))
I/flutter (20454): ════════════════════════════════════════════════════════════════════════════════════════════════════```

**Comment by fhuonder** [comment]
See https://github.com/flutter/flutter/pull/24457#issuecomment-454365729 and https://github.com/flutter/flutter/pull/24457#issuecomment-454372664

**Comment by zoechi** [comment]
I can reproduce with
```
Flutter 1.1.10-pre.76 • channel master • https://github.com/flutter/flutter.git
Framework • revision 684d050791 (32 minutes ago) • 2019-01-16 01:01:51 -0500
Engine • revision fdfb0e72f0
Tools • Dart 2.1.1 (build 2.1.1-dev.1.0 d9944433af)
```

**Comment by zoechi** [comment]
@sdolski #26624 with reference to #26628 might be related

**Comment by zoechi** [comment]
See also #26626

**Comment by xster** [comment]
Very sorry for the breakage all.

I took a quick look. This is on Android and OEM specific. 

Causes:

- #25683 using the force touch / pressure gesture on TextField merged 2 days ago.
- Root cause, a pressure range assertion in https://github.com/flutter/flutter/pull/24554/files#diff-33e497749408edbc5092541c1c602cc8R219 in the force touch recognizer didn't meet expected range.  
- Root cause, in the engine, iOS max pressure is piped but a TODO on the Android side was never resolved https://github.com/flutter/engine/blob/b058920cab5be328295f72d8af66461ade161e7d/shell/platform/android/io/flutter/view/FlutterView.java#L478

Resolution:

- [ ] Revert #25683 to relief the most visible issue. Though the new ForcePressGestureRecognizer will still have issue on some Android devices
- [ ] Report a better max pressure in FlutterView.java
- [ ] Merge in various cleanups from Ian's #26629

**Comment by Hixie** [comment]
One problem that my patch didn't fix but that I think we should also fix is that the force push recognizer should not do anything is pressureMax == 1.0.

**Comment by xster** [comment]
If I understand correctly, this is the issue you pointed out at https://github.com/flutter/flutter/pull/25683#issuecomment-454671734?

**Comment by Hixie** [comment]
it's the same issue, yes. I hadn't thought through the solution at the time. I think the solution is my comment above.

**Comment by jslavitz** [comment]
Ok, this is fixed now everyone! Sorry about that!

**Comment by goderbauer** [comment]
@jslavitz if this is fixed, can we close the issue? Or is there more to do?

**Comment by xster** [comment]
We want to follow through with the other root causes. @jslavitz: feel free to move the list of tasks to another bug though.

**Comment by xster** [comment]
For posterity, this specific issue has been fixed. The last clean-up was #26659

**Comment by terryl1900** [comment]
@xster The issue still happens on iOS simulator when trackpad doesn't support force touch. I suspect it also happens to older iPhone where 3D touch is not supported, but I haven't tried it out.

Repro:
Use the app in above thread https://github.com/flutter/flutter/issues/26563#issuecomment-454642091
`iPhone XR simulator, iOS 12.1`
```
flutter: The following assertion was thrown while dispatching a pointer event:
flutter: 'package:flutter/src/gestures/force_press.dart': Failed assertion: line 209 pos 12:
flutter: 'event.pressureMax >= 1.0': is not true.`
```
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.13.6 17G65, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by xster** [comment]
Sorry for the issue. That was a slightly different issue https://github.com/flutter/flutter/issues/28447 and also fixed on master head in https://github.com/flutter/flutter/pull/28478

**Comment by eliezedeck** [comment]
For some reason, I my TextField still doesn't get focus sometimes.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G7024, locale en-MG)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (2 available)

• No issues found!
```

I'm not sure where to start, but sometimes the focus is not happening on Android, sometimes on iOS (iPad). I haven't noticed any correlation yet, and I'll report if I do.

**Comment by eliezedeck** [comment]
Even forcing the `CupertinoTextField` to have focus like below doesn't do anything. When I keep tapping or long-pressing the text field, it just shows the *Paste* action, **no cursor**.

Here is how I'm forcing the focus:

```dart
  FocusNode searchFocus = FocusNode();

  @override
  void initState() {
    super.initState();
    Timer(Duration(milliseconds: 500), () {
      FocusScope.of(context).requestFocus(searchFocus);
      debugPrint("forced focus!");
    });
  }
```

The `forced focus! ` is printed alright, but **no cursor** on the text field.

**Comment by eliezedeck** [comment]
Problem **solved**, after using Flutter v1.6.3 (beta channel).

**Comment by bianxiang** [comment]
> Problem **solved**, after using Flutter v1.6.3 (beta channel).

I use Flutter v1.12.13,how can I fix it?
