### ISSUE TITLE
AAPT: error: resource android:attr/fontVariationSettings not found after Flutter Upgrade

### ISSUE THREAD

**Issue by zanecidan** [flutter/flutter#27226]
My flutter application used to work perfectly until recently I decided to upgrade to Flutter version 1.0.0. After upgrade I'm getting the below errors during compilation in one of my project:

```
AAPT: error: resource android:attr/fontVariationSettings not found.
AAPT: error: resource android:attr/ttcIndex not found.

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDevelopmentDebugResources'.
> Failed to process resources, see aapt output above for details.
```

I've tried many things I can find in Google but none of them works. Appreciates for any help here.

**Comment by zoechi** [comment]
Looks similar to #27106

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zanecidan** [comment]
flutter doctor -v
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\src\flutter\flutter_windows_v0.5.1-beta\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Chin Ying Jie\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

#27106 is about moving to AndroidX, but I'm not planning to move as of now. Still using version 27.1.1.

Strangely my 2 other applications work fine.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/27106#issuecomment-458366675

> If you don't want to migrate your app off of the deprecated support libraries, then for now you can avoid this by staying pinned to the last major version and avoiding this change.

**Comment by zanecidan** [comment]
> [#27106 (comment)](https://github.com/flutter/flutter/issues/27106#issuecomment-458366675)
> 
> > If you don't want to migrate your app off of the deprecated support libraries, then for now you can avoid this by staying pinned to the last major version and avoiding this change.

I did the migration and I can compile now. Thanks @zoechi .

**Comment by MarcinusX** [comment]
Setting `compileSdkVersion 28` in `app/build.gradle` fixed the issue for me.

**Comment by zoechi** [comment]
@zanecidan does this fix it for you as well?

**Comment by mklim** [comment]
It looks like this was fixed for @zanecidan a few posts above.

From [here](https://github.com/flutter/flutter/issues/27106#issuecomment-458366675):

> For anyone else seeing this issue, the root cause of this error message is because we introduced a breaking change to the plugins that migrated them from the deprecated Android support libraries to AndroidX (#23995). Unfortunately this update also requires a manual migration in apps using the plugins in cases where the apps are also relying on the original support libraries and/or aren't compiling to SDK 28 already (the case with the `flutter (stable) create` template).
> 
> 
> If you want to keep using the latest major versions of the plugins, [the official Android migration guide for AndroidX is here](https://developer.android.com/jetpack/androidx/migrate). Android Studio provides an automated migration tool for apps that will probably make migrating easiest (also described on that page). You can import a flutter app into AS by hitting "Open an existing android studio project" on the IDE's opening splash screen and then opening `<my_app_root>/android/build.gradle`.
>
> If you don't want to migrate your app off of the deprecated support libraries, then for now you can avoid this by staying pinned to the last major version and avoiding this change.

**Comment by nkmswot** [comment]
My Compiledsdkversioin is 28 only. But still facing the same issue. 

```
* What went wrong:

Execution failed for task ':url_launcher:verifyReleaseResources'.

> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

  D:\flutter-projects\project1\build\url_launcher\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.

  D:\flutter-projects\project1\build\url_launcher\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
```

**Comment by alexda12** [comment]
I upgraded yesterday to 1.12.13. I now have exactly this issue. More info here  https://github.com/flutter/flutter/issues/46881

**Comment by divyanshub024** [comment]
I'm also facing the same issue when I run `flutter build apk`

```
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':thumbnails:verifyReleaseResources'.                                                    
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
   > Android resource linking failed                                                                               
     /Users/divyanshub024/.gradle/caches/transforms-2/files-2.1/8ef0dd1b827b6b28c1e9211227fa2d4c/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                                                                   
     /Users/divyanshub024/.gradle/caches/transforms-2/files-2.1/8ef0dd1b827b6b28c1e9211227fa2d4c/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                                                                   
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 2m 56s  
```

**Comment by sarinupreti** [comment]
I upgraded yesterday to 1.12.13. I now have exactly this issue.

**Comment by sarinupreti** [comment]
I upgraded yesterday to 1.12.13. I have the same issue as well

**Comment by ChiHwe** [comment]
guys, i facing this issue too, can i know how you guys fix it?

**Comment by miguelcmedeiros** [comment]
I had this issue with a couple of plugins that my project uses:
- devicelocale
- vibrate

The issue was gone once these plugins were updated to use compiledsdkversioin set to 28.

**Comment by adrianvintu** [comment]
my fix here https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-566656630

CC @nkmswot

**Comment by ayham95** [comment]
If anyone has this issue with some package

- In your project folder go to External libraries
- Locate the library that raised the issue
- Open it's build.gradle(app) 
- update the compileSdkVersion to 28

**Comment by bobanminic96** [comment]
> If anyone has this issue with some package
> 
> * In your project folder go to External libraries
> * Locate the library that raised the issue
> * Open it's build.gradle(app)
> * update the compileSdkVersion to 28

Didnt work for me. Didnt find solution already. Any suggestions ?

Plus, android studio throws exception 'Cannot resolve symbol GradleException' at line 11 , but i ignore that one.

**Comment by AleksMx** [comment]
I fixed this error by changing compileSdkVersion from 27 to 28 in one of the dependencies. So check build.gradle file in the repo of every dependency that you use.

**Comment by gopalsgs** [comment]
> If anyone has this issue with some package
> 
> * In your project folder go to External libraries
> * Locate the library that raised the issue
> * Open it's build.gradle(app)
> * update the compileSdkVersion to 28

Thank you. It solved the issue

**Comment by shadyshrif** [comment]
> If anyone has this issue with some package
> 
> * In your project folder go to External libraries
> * Locate the library that raised the issue
> * Open it's build.gradle(app)
> * update the compileSdkVersion to 28

Thanks this worked for me I had this issue in sharedpreferences package! I didn't know why!

For those who couldn't solve the issue 

>  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[your project path]\build\**[the package that has the problem]**\\intermediates\res\merged\release\values\values.xml

to solve the issue

1- open android studio
2- open the android project of your app. (take care not NOT the app itself)
3- on the left make sure that you view in "project" or "android" view
4- You will find all your packages listed, open expand  **[the package that has the problem]**\android\
5- open **[the package that has the problem]** build.gradle
6- make sure that `compileSdkVersion 28` not 27

**Comment by shadyshrif** [comment]
For those who still couldn't solve the issue, first of all find this line in your error log
>  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[your project path]\build\**[the package that has the problem]**\\intermediates\res\merged\release\values\values.xml

To solve the issue

1- open android studio
2- open the android project of your app. (take care not NOT the app itself)
3- on the left make sure that you view in "project" or "android" view
4- You will find all your packages listed, open expand  **[the package that has the problem]**\android\
5- open **[the package that has the problem]** build.gradle
6- make sure that `compileSdkVersion 28` not 27

**Comment by dsmailpuneet** [comment]
> I'm also facing the same issue when I run `flutter build apk`
> 
> ```
> FAILURE: Build failed with an exception.                                                                           
>                                                                                                                    
> * What went wrong:                                                                                                 
> Execution failed for task ':thumbnails:verifyReleaseResources'.                                                    
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
>    > Android resource linking failed                                                                               
>      /Users/divyanshub024/.gradle/caches/transforms-2/files-2.1/8ef0dd1b827b6b28c1e9211227fa2d4c/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
>                                                                                                                    
>      /Users/divyanshub024/.gradle/caches/transforms-2/files-2.1/8ef0dd1b827b6b28c1e9211227fa2d4c/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
>                                                                                                                    
>                                                                                                                    
> * Try:                                                                                                             
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                                                                    
> * Get more help at https://help.gradle.org                                                                         
>                                                                                                                    
> BUILD FAILED in 2m 56s  
> ```

Do you get solution?

**Comment by gmlewis** [comment]
My failure appears to be caused by: https://github.com/rickyazhari/root_checker/blob/master/android/build.gradle#L25

**Comment by hatted** [comment]
I remove all unused plugins from External Libraries folder and pub.yaml to solve the problem.
