### ISSUE TITLE
Flutter Doctor -- "Android Studio (not installed)"

### ISSUE THREAD

**Issue by vnagendra** [flutter/flutter#27283]
When I run flutter doctor, I see the following output.. 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.13.6 17G4015, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
I am not sure if this _should be_ an issue. IntelliJ licensed edition is a _valid_ IDE to develop Flutter in. I am sure so is vscode and a few others that are supported. 

Is there an actual issue or should this message be amended? 

There was one point in the _beta_ channel when this went away. But since Flutter 1.0 this message has come back (on the beta channel). Perhaps a regression?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Seems you mean something like #25719

I was interested in the output of `flutter doctor -v` to possibly get more details  why it thinks it is `not installed`.

**Comment by kangwang1988** [comment]
@vnagendra 
I'm closing this issue.
Feel free to comment below, like 
> I was interested in the output of flutter doctor -v to possibly get more details why it thinks it is not installed.

**Comment by vnagendra** [comment]
Apologies for the delay in response. @zoechi - You are correct. I should've checked the other issue. I tried to find, but clearly didn't do a good job. 

My point originally was 

1. In my specific case that "warning" is _correct_. I do *not* have Android Studio installed. However that warning is also misleading IMO to a new Flutter developer to mean "there is something wrong with my installation". I was referring to maybe changing this or removing it entirely to be something along the lines of 
 - If Android Studio is installed, then check plugins
 - If not, nothing to do. 

2. In theory if I have flutter installed, while not pleasant, I can write code using `vi` :) I see no reason to raise an error/warning relating to IDEs, especially when they are not even installed! (or let's be fair and also complain that I don't have VSCode installed as well).

**Comment by kangwang1988** [comment]
Track this issue under: https://github.com/flutter/flutter/issues/25719

**Comment by IamStupidMan** [comment]
I got the same issue,the output of flutter doctor -v is like below
![image](https://user-images.githubusercontent.com/11649719/81462462-45a1ee80-91e5-11ea-9905-5e31ab44c30d.png)
But,I installed AS actually

**Comment by shivamrsoft** [comment]
Same I just installed flutter and android studio and I got the same response from flutter doctor.

**Comment by shvamabps** [comment]
I also just received thee same issue with the flutter. I had installed android studio. @FlutterIssues

**Comment by shivamrsoft** [comment]
![Screenshot from 2020-10-15 11-35-43](https://user-images.githubusercontent.com/70791712/96083356-a642ff00-0eda-11eb-8945-7ec41a6a79b8.png)

is Android studio suppose to look this way

**Comment by samiq** [comment]
this happened to me as well windows with the current version, I have Android Studio 4.1 installed before I downloaded flutter zip from the website. Ran `flutter doctor` and it didn't recognise Java, Android SDK or Android Studio. I had to add JAVA_HOME to the path (to point to the one in Android Studio), doing it then it found the android sdk. but no Android Studio yet.

![image](https://user-images.githubusercontent.com/220773/96285762-44b48a80-0fd7-11eb-953e-7c0a7e288f48.png)

**Comment by shelendravashishtha2** [comment]
I'm also having same problem and I've also installed android studio. The problem started when I updated my android studio after that I've even reinstalled android studio but this problem still stopping me.
![android](https://user-images.githubusercontent.com/53626635/96302230-0f7b5d00-1016-11eb-9d6d-eee584fea47f.PNG)

**Comment by FRANCKWILFRIEDNGBO** [comment]
![Capture d’écran (33)](https://user-images.githubusercontent.com/62740272/96322639-84ab5a00-1037-11eb-91d1-54489ed4eded.png)
I think we all have the same error so basically it may be due to the recent update of  Android studio that happened so if someone know how to help our common problem .
we look forward to hear from you

**Comment by samiq** [comment]
I think it has something to do with Android Studio 4.1 and the current Flutter setup, I changed channels to the beta channel and upgraded and now `flutter doctor` works.

**Comment by FRANCKWILFRIEDNGBO** [comment]
ok can you tell me the steps of it because i have upgraded to but now it is
saying that flutter and dart plugin not installed
Do you have any idea how to solve it
[image: Capture d’écran (117).png]

Le sam. 17 oct. 2020 à 17:38, Gilbert Corrales <notifications@github.com> a
écrit :

**Comment by shelendravashishtha2** [comment]
@FRANCKWILFRIEDNGBO you can just reinstall the plugin in your android studio and if still problem doesn't  resolve simply  ignore the warning and it would work fine anyway

**Comment by djaBalasbas** [comment]
I have the same issue after updating to Android Studio 4.1

**Comment by shvamabps** [comment]
@samiq  Hey! I tried this changing channel thing. I changed it to dev and still the same situation.
![Screenshot from 2020-10-22 22-37-28](https://user-images.githubusercontent.com/37547983/96906536-8b165780-14b7-11eb-9042-d3fe906b4ffb.png)
![Screenshot from 2020-10-22 22-37-31](https://user-images.githubusercontent.com/37547983/96906543-8ea9de80-14b7-11eb-9b91-76f55ab257bc.png)

**Comment by samiq** [comment]
there is something I did prior to switching branches and it was to set the pointer to the android studio directory using `--android-studio-dir` flag of `flutter config`, now what's interesting is that Android Studio's flutter plugin is doesn't see flutter's sdk's despite of it being in the PATH so looks like there is some funny things happening for sure

**Comment by samiq** [comment]
now for what is worth I just did a fresh install of Android Studio 4.1 and flutter on a Windows 10 machine running October's service pack of Windows and it recognised Android Studio but not the plugins (this is without configuring the studio directory), but same, Android Studio didn't recognize Flutter by default so had to set it up.

**Comment by nickcollie** [comment]
I am no expert. Especially not on Windows.

I had this problem on Ubuntu when I used the snap install, but the problem was resolved when I installed android studio from the repository.

**Comment by jcstange** [comment]
On Ubuntu, if you installed from snap, you should set these two parameters:
```
flutter config --android-sdk="$HOME/Android/Sdk"
flutter config --android-studio-dir="/snap/android-studio/current/android-studio/"
```

**Comment by gamenic-pawanrai** [comment]
> On Ubuntu, if you installed from snap, you should set these two parameters:
> 
> ```
> flutter config --android-sdk="$HOME/Android/Sdk"
> flutter config --android-studio-dir="/snap/android-studio/current/android-studio/"
> ```

Thanks man for the answer

**Comment by shvamabps** [comment]
@jcstange  will that configuration be global or it will be instantial.

**Comment by hoccpan** [comment]
> On Ubuntu, if you installed from snap, you should set these two parameters:
> 
> ```
> flutter config --android-sdk="$HOME/Android/Sdk"
> flutter config --android-studio-dir="/snap/android-studio/current/android-studio/"
> ```

I manually config these two as guided. but the plug-in still doesn't work:
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.

Although I already installed flutter ( and dart) through studio->settings->Plugin->Marketplace.

Seems flutter didn't recognize these plugins.. anything else I can do? (I am using linux)

**Comment by b1414m** [comment]
> I am no expert. Especially not on Windows.
> 
> I had this problem on Ubuntu when I used the snap install, but the problem was resolved when I installed android studio from the repository.

How did you delete the one that you downloaded from snap? And what else did you have to do ?

**Comment by shivamrsoft** [comment]
@b1414m  kindly use this command to remove the flutter from snap
`sudo snap remove flutter`

**Comment by b1414m** [comment]
> @b1414m kindly use this command to remove the flutter from snap
> `sudo snap remove flutter`

Thanks I solved it. 

For those interested:

- Im on Ubuntu installing Flutter 4.1 
- I was getting Android studio not found
- I Locked into android studion > File > Project Structure > Sdk  | there I manually selected the SDK 
- Then I added the following in .bashrc --> flutter config --android-studio-dir="/home/bundu/Documents/dev/android-studio"
At this point flutter doctor was now able to find Android Studio but not Flutter and Dart Plugins so I did the follwoing:

1. Switch Channel: First `flutter channel` to see your current channel (I was on Stable channel) and then `flutter channel Dev` to switch from Stable to Dev
2. upgrade flutter 
3. You might have to go to Android Studio to manually install the plugins or they might have already been installed 
4. restart 
5. close edit and run flutter doctor -v again 

That was it. 

Good Luck

**Comment by shivamrsoft** [comment]
@b1414m  Thanks man for the steps. This thing has been bugging for days. I guess this would finally get solved at Flutter end too in the new update.

**Comment by b1414m** [comment]
> @b1414m Thanks man for the steps. This thing has been bugging for days. I guess this would finally get solved at Flutter end too in the new update.

Hopefully. I was stuck on this for the whole weekend.

**Comment by notandyvee** [comment]
@b1414m great find. Its February, still not in the stable channel. For those not wanting to be on the bleeding edge. Us the master channel. Works there at the moment.

**Comment by Rithika-29** [comment]
@IamStupidMan can u help me how to solve this issue

**Comment by Rithika-29** [comment]
I have installed flutter and dart pluggins , even though am getting an error

**Comment by pureabsolute** [comment]
@Rithika-29 et al -- 
On windows 10:

flutter config --android-studio-dir <path to android studio. Default: "c:\program files\android\android studio">

The configuration seems to stick, and flutter doctor is clean.  This is with default flutter, installing default android studio (4.2) afterwards, setting java_home to the android jdk (not the sdk, but I wouldn't think that would matter).

**Comment by KomalPatel-github** [comment]
> 
> 
> > @b1414m kindly use this command to remove the flutter from snap
> > `sudo snap remove flutter`
> 
> Thanks I solved it.
> 
> For those interested:
> 
>     * Im on Ubuntu installing Flutter 4.1
> 
>     * I was getting Android studio not found
> 
>     * I Logged into android studio > File > Project Structure > Sdk  | there I manually selected the SDK
> 
>     * Then I added the following in .bashrc --> flutter config --android-studio-dir="/home/bundu/Documents/dev/android-studio"
>       At this point flutter doctor was now able to find Android Studio but not Flutter and Dart Plugins so I did the following:
> 
> 
>     1. Switch Channel: First `flutter channel` to see your current channel (I was on Stable channel) and then `flutter channel Dev` to switch from Stable to Dev
> 
>     2. upgrade flutter
> 
>     3. You might have to go to Android Studio to manually install the plugins or they might have already been installed
> 
>     4. restart
> 
>     5. close edit and run flutter doctor -v again
> 
> 
> Note: I did not have to uninstall flutter via snap
> 
> That was it.
> 
> Good Luck

Can anyone find a similar solution for Windows?

**Comment by mattyinjapan** [comment]
@pureabsolute Thank you! Saved a few hours or more!

**Comment by exeptionerror** [comment]
[[Solved][!] Android Studio (not installed), when run flutter doctor while Android Studio installed on machine
](https://fluttercorner.com/android-studio-not-installed-when-run-flutter-doctor-while-android-studio/)

**Comment by FaisalNahian** [comment]
> @Rithika-29 et al --
> On windows 10:
> 
> flutter config --android-studio-dir <path to android studio. Default: "c:\program files\android\android studio">
> 
> The configuration seems to stick, and flutter doctor is clean. This is with default flutter, installing default android studio (4.2) afterwards, setting java_home to the android jdk (not the sdk, but I wouldn't think that would matter).

That solved my problem. Thanks!
