### ISSUE TITLE
PlatformView on iOS  - duplicate touch events causes assertion failure

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#27700]
Splitting this off from #24207

I believe what's going on is that for accepted gestures when the delaying gesture recognizer rejects, the same touch sequence that was passed to Flutter through the forwarding recognizer is passed again directly to FlutterView.

This fails an assertion resulting in the following error (only in debug mode):

```
Dart Error: Unhandled exception:
'package:flutter/src/gestures/converter.dart': Failed assertion: line 143 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:143:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _invoke1 (dart:ui/hooks.dart:165:13)
#7      _dispatchPointerDataPacket (dart:ui/hooks.dart:119:5)
```

**Comment by jesaiasmaia** [comment]
I'm facing this problem, I am using [google maps](https://pub.dartlang.org/packages/google_maps_flutter), when I touch the map and it is not the first focus, occurr the error, if I touch another component and then back to the map, the error occurr again.

**Comment by Faverolles** [comment]
I am also facing this issue. It occurs when using a ScaleGestureRecognizer with [webview_flutter](https://github.com/flutter/plugins/tree/master/packages/webview_flutter)
The error does not occur when using any other gesture recognizers, and only occurs in iOS.
The page will zoom in and out when pinching the screen but will throw this error when navigating away from, or back too, a webview (thus  [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) in iOS) that has had its contents scaled.

**Comment by zoechi** [comment]
Possible duplicate of #11672

**Comment by zoechi** [comment]
@cyanglaz can this issue be closed? #8026 is merged.

**Comment by palancana** [comment]
It seems that the assertion still happens with Flutter 1.2.1 (stable) and package `webview_flutter: ^0.3.3+1`.

The line position for the assertion is different now. The error displays:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand 
package:flutter/…/gestures/converter.dart:155
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:83
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by cyanglaz** [comment]
This issue should be fixed in the latest flutter master branch. Closing the issue now.

**Comment by steve3d** [comment]
may I ask when is this fix are going into the beta channel?

**Comment by faverolles** [comment]
The '!state.down' assertion failure is still happening in the master branch. It is no longer causing the app to crash which is great, but the exception is still being thrown when swiping.   When the user swipes left or right inside a tab view, normally it will "snap" to the next tab.  But, if the exception is thrown other gestures such as pinching to zoom will cease to function.  The tab view's children become "draggable" instead of swiping and snapping.  I have found that if the tab view's children are very simple, such as place holder widgets or just circle progress indicators, the '!state.down' assertion does **not** get thrown. But if the tab view's children are (relatively speaking) expensive the assertion will always be thrown as soon as the frameworks starts to render the next tab's child.  If you very slowly start to drag left or right, as soon as the next tab's child begins to come into view, the assertion will be thrown.

**Comment by cyanglaz** [comment]
> may I ask when is this fix are going into the beta channel?

Unfortunately, I'm not sure about the exact day it will go to beta, but it will probably be in April.
Please refer [here](https://github.com/flutter/flutter/wiki/Release-process) for the release process.

**Comment by cyanglaz** [comment]
> The '!state.down' assertion failure is still happening in the master branch. It is no longer causing the app to crash which is great, but the exception is still being thrown when swiping. When the user swipes left or right inside a tab view, normally it will "snap" to the next tab. But, if the exception is thrown other gestures such as pinching to zoom will cease to function. The tab view's children become "draggable" instead of swiping and snapping. I have found that if the tab view's children are very simple, such as place holder widgets or just circle progress indicators, the '!state.down' assertion does **not** get thrown. But if the tab view's children are (relatively speaking) expensive the assertion will always be thrown as soon as the frameworks starts to render the next tab's child. If you very slowly start to drag left or right, as soon as the next tab's child begins to come into view, the assertion will be thrown.

Is this issue related to a particular plugin platform view(google map or webview)? Or it happens for regular Flutter Widgets.

**Comment by jesaiasmaia** [comment]
> > The '!state.down' assertion failure is still happening in the master branch. It is no longer causing the app to crash which is great, but the exception is still being thrown when swiping. When the user swipes left or right inside a tab view, normally it will "snap" to the next tab. But, if the exception is thrown other gestures such as pinching to zoom will cease to function. The tab view's children become "draggable" instead of swiping and snapping. I have found that if the tab view's children are very simple, such as place holder widgets or just circle progress indicators, the '!state.down' assertion does **not** get thrown. But if the tab view's children are (relatively speaking) expensive the assertion will always be thrown as soon as the frameworks starts to render the next tab's child. If you very slowly start to drag left or right, as soon as the next tab's child begins to come into view, the assertion will be thrown.
> 
> Is this issue related to a particular plugin platform view(google map or webview)? Or it happens for regular Flutter Widgets.

No, it is happening in google maps widget.

**Comment by palancana** [comment]
It was happening to me using webview. Same behavior as mentioned by @jesaiasmaia.

**Comment by cyanglaz** [comment]
@palancana would you mind to share a sample code to reproduce the issue?

**Comment by faverolles** [comment]
@cyanglaz In my case the exception is happening when using a webview inside a tab. If I add a HorizontalDragGestureRecognizer to the webview's gesture recognizer set then the webview claims the horizontal swipes, so the tab view never tries to move to the next tab. In this case the bug will never be thrown. Otherwise (without the HorizontalDragGestureRecognizer) as soon as the tab view claims the horizontal swipe and tries to move to the next tab, the bug will be thrown. My current workaround for iOS is to wrap the webview in a GestureDetector to intercept just the horizontal drags then use the tab view's controller to manually move to the next index. With this set up I do not include HorizontalDragGestureRecognizer in the webview's gesture recognizer set.

**Comment by amirh** [comment]
@faverolles could you share a minimal app that reproduced the failure and your output for `flutter doctor -v` ?

**Comment by faverolles** [comment]
@amirh Yes I would be happy to. I will post both as soon as I can, this afternoon or evening.

**Comment by faverolles** [comment]
Here is a test app to reproduce the '!state.down' bug, as well as the 'unexpected touch phase' issue.
https://github.com/flutter/flutter/issues/27580 https://github.com/flutter/flutter/issues/29427



````dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: BasePage(),
    );
  }
}

class BasePage extends StatefulWidget {
  BasePage({Key key}) : super(key: key);

  @override
  _BasePageState createState() => _BasePageState();
}

class _BasePageState extends State<BasePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Bug App")),
      body: Flex(
        direction: Axis.vertical,
        children: <Widget>[
          Expanded(
            flex: 1,
            child: Center(
              child: Text(
                "Once the !state.down error has been thrown,"
                " navigate back to this page. Pushing a new MaterialPageRoute"
                " will restore the ability to swipe and scale.",
                textAlign: TextAlign.center))),
          Expanded(
            flex: 1,
            child: Center(
              child: RaisedButton(
                textColor: Colors.blue,
                child: Text("Show Bug Page"),
                onPressed: () => Navigator.push(
                  context,
                  new MaterialPageRoute(
                    builder: (context) => BugPage()))))),
        ],
      ),
    );
  }
}

class BugPage extends StatefulWidget {
  BugPage({Key key}) : super(key: key);

  @override
  _BugPageState createState() => _BugPageState();
}

class _BugPageState extends State<BugPage> {

  static final _keys = List<GlobalKey>.generate(3, (_) => GlobalKey());
  List<WebTest> _tabPages = {
    0:"https://www.google.com/",
    1:"https://flutter.dev/",
    2:"https://github.com/flutter"
  }.entries.map((p) =>
      WebTest(path: p.value, webKey: _keys[p.key],)).toList();

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          title: Text("Bug Page"),
          bottom: TabBar(
            tabs: [Tab(text: "Tab 1"), Tab(text: "Tab 2"), Tab(text: "Tab 3")]
          )
        ),
        body: TabBarView(children: this._tabPages),
      ),
    );
  }
}

class WebTest extends StatefulWidget {
  WebTest({Key key, this.path, this.webKey}) : super(key: key);

  final GlobalKey webKey;
  final String path;

  final Set<Factory<OneSequenceGestureRecognizer>> _gSet = Set()..addAll([
    Factory<VerticalDragGestureRecognizer>(
        () => VerticalDragGestureRecognizer()),
    Factory<ScaleGestureRecognizer>(
        () => ScaleGestureRecognizer()),
    Factory<PanGestureRecognizer>(
        () => PanGestureRecognizer()),
    ]);

  @override
  _WebTestState createState() => _WebTestState();
}

class _WebTestState extends State<WebTest>
    with AutomaticKeepAliveClientMixin<WebTest> {

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return WebView(
        key: widget.webKey,
        gestureRecognizers: widget._gSet,
        javascriptMode: JavascriptMode.unrestricted,
        initialUrl: widget.path);
  }
}
````

### flutter doctor -v

```
5D-LK49-BH:bugapp faverolles$ flutter doctor -v
[✓] Flutter (Channel master, v1.3.10-pre.31, on Mac OS X 10.14.3 18D109,
    locale en-US)
    • Flutter version 1.3.10-pre.31 at /flutter
    • Framework revision 275769b89d (2 days ago), 2019-03-13 10:13:51 -0700
    • Engine revision 5ccee95373
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/faverolles/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • faverolles iPad • ---------------- • ios • iOS
      12.1.4

• No issues found!

```

**Comment by cyanglaz** [comment]
Feels like could be the same issue as https://github.com/flutter/flutter/issues/29427

**Comment by BaiKunlun** [comment]
[VERBOSE-2:ui_dart_state.cc(161)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:81:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:249:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:152:5)
2019-03-26 16:19:59.537360+0800 NewsInHouse[893:101775] Flutter Forward end
2019-03-26 16:19:59.540471+0800 NewsInHouse[893:101775] flutter: Flutter 左右滑动 end
2019-03-26 16:19:59.541888+0800 NewsInHouse[893:101775] [VERBOSE-2:ui_dart_state.cc(161)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 262 pos 18: 'state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:262:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:81:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:249:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:152:5)

**Comment by BaiKunlun** [comment]
`[VERBOSE-2:ui_dart_state.cc(161)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:81:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:249:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:152:5)
2019-03-26 16:19:59.537360+0800 NewsInHouse[893:101775] Flutter Forward end
2019-03-26 16:19:59.540471+0800 NewsInHouse[893:101775] flutter: Flutter 左右滑动 end
2019-03-26 16:19:59.541888+0800 NewsInHouse[893:101775] [VERBOSE-2:ui_dart_state.cc(161)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 262 pos 18: 'state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:262:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:81:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:249:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:152:5)`
I don't use the platform View, but simple flutterview in iOS. When I detect a pan gesture, it occurs predictably. @amirh

**Comment by BaiKunlun** [comment]
[VERBOSE-2:ui_dart_state.cc(161)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:81:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:249:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:152:5)

I don't use the platformview but the simple FlutterView. When I pass a pan gesture touches event to the engine, the assert comes. @amirh

**Comment by amirh** [comment]
@BaiKunlun if you're not using platform views this might be a different issue, could you file a separate issue with a minimal code snippet that reproduces the problem?

**Comment by fengqiangboy** [comment]
PanGesture on UIKitView also have this issue
