### ISSUE TITLE
Google Maps and Stack on iOS

### ISSUE THREAD

**Issue by irevans** [flutter/flutter#27837]
This issue relates to the Flutter Google Maps plugin. 

Following a certain user interaction my application needs to display some text over the top of the map. To do this I am using a `Stack`; following the user interaction I am fading a text widget in and after a short delay it fades out again (using an `AnimationController`, `Animation` and `FadeTransition` but I have also tried this with an `AnimatedOpacity` and had the same issue). 

I have come across an issue on iOS. If I minimize the application (i.e. send it to the background) and then bring the application back to the foreground the overlaid text no longer gets displayed. From what I can tell it's as though the text is getting drawn but somehow the map is preventing it from being displayed correctly. I suspect (anecdotally) that the problem is caused by platform views on iOS.

The following will illustrate the problem, after pushing the application to the background and then bringing it back to the foreground you will notice that the text no longer gets displayed:

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapPage extends StatefulWidget {
  MapPage({Key key}) : super(key: key);

  @override
  MapState createState() => MapState();
}

class MapState extends State<MapPage> with TickerProviderStateMixin {
  AnimationController animationController;
  Animation<double> animation;
  GoogleMapController controller;

  void _onMapCreated(GoogleMapController controller) {
    this.controller = controller;
  }

  initState() {
    super.initState();
    animationController = AnimationController(
        duration: const Duration(milliseconds: 500), vsync: this);
    animation = CurvedAnimation(parent: animationController, curve: Curves.easeIn);
  }

  Widget build(BuildContext context) {
    return Column(children: <Widget>[
      Stack(children: <Widget>[
        SizedBox(width: 300, height: 300,
          child: GoogleMap(
              onMapCreated: _onMapCreated,
              initialCameraPosition: const CameraPosition(
                target: LatLng(-33.852, 151.211),
                zoom: 11.0,
              )),
        ),
        FadeTransition(
          opacity: animation,
          child: Container(color: Colors.green, width: 300, height: 50,
            child: Text( 'Some Text',  style: TextStyle(fontSize: 30, color: Colors.red),
            ),
          ),
        ),
      ]),
      Row(mainAxisAlignment: MainAxisAlignment.center, children: <Widget>[
        RaisedButton(
          child: Text('Fade In'),
          onPressed: () => animationController.forward(),
        ),
        RaisedButton(
          child: Text('Fade Out'),
          onPressed: () => animationController.reverse(),
        ),
      ])
    ]);
  }

  @override
  void dispose() {
    super.dispose();
    animationController.dispose();
  }
}
```

Has anybody seen a similar issue? Are there any workarounds?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by irevans** [comment]
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D42, locale en-GB)
    • Flutter version 1.0.0 at /Users/foobar/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/foobar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
That Flutter version is a bit dated already. Could you please try if you can still reproduce with `dev` channel?

**Comment by irevans** [comment]
I was in the process of testing against master. It is fixed on master:

[✓] Flutter (Channel master, v1.2.1-pre.160, on Mac OS X 10.14.3 18D42, locale en-GB)
    • Flutter version 1.2.1-pre.160 at /Users/foobar/flutter
    • Framework revision cb2ac0a125 (4 hours ago), 2019-02-12 17:05:09 +0800
    • Engine revision d48de7a3ec
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 fdfe40ea95)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/foobar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    ! No devices available

! Doctor found issues in 1 category!

**Comment by zoechi** [comment]
> It is fixed on master:

I assume it's ok to close the issue then. Thanks for the update!

**Comment by DennisKragekjaer** [comment]
This is not fixed, still occuring and it is becoming too much with Flutter and bugs
