### ISSUE TITLE
Application crashes on device with google_maps_flutter with Android 9 on Samsung S9

### ISSUE THREAD

**Issue by mrimran** [flutter/flutter#28201]
## Steps to Reproduce

I've tested it with stable channel and beta channel of the flutter but problem remains same. Here is the code that is producing the issue, and if I comment it the application works fine on the S9 device.

```dart
          Center(
          child: SizedBox(
            width: screenWidth * 0.95,
            height: 200.0,
            child: GoogleMap(
              initialCameraPosition:
                  CameraPosition(target: LatLng(0.00, 0.00), zoom: 1.0),
              onMapCreated: _onMapCreated,
            ),
          )
```

## Logs

The map works fine on Emulator but when I tested the application on actual device it crashes when we go to map page. And produces the following error:

```
D/SurfaceView(30577): windowStopped(false) false 2978567 of ViewRootImpl@abaa081[MainActivity]
D/SurfaceView(30577): onWindowVisibilityChanged(0) true 2978567 of ViewRootImpl@abaa081[MainActivity]
D/ViewRootImpl@abaa081[MainActivity](30577): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={valid=true 516966010880} changed=true
D/mali_winsys(30577): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(30577): eglCreateWindowSurface = 0x7853412080, 0x785d935010
D/SurfaceView(30577): show() Surface(name=SurfaceView - com.proappdev.easylist/com.proappdev.easylist.MainActivity@2978567@1[30577])/@0xa7e162d io.flutter.view.FlutterView{2978567 VFE...... ........ 0,0-1080,2076}
D/SurfaceView(30577): surfaceCreated 1 #8 io.flutter.view.FlutterView{2978567 VFE...... ........ 0,0-1080,2076}
D/mali_winsys(30577): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(30577): surfaceChanged (1080,2076) 1 #8 io.flutter.view.FlutterView{2978567 VFE...... ........ 0,0-1080,2076}
D/ViewRootImpl@abaa081[MainActivity](30577): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 72 - 0, 144) vi=Rect(0, 72 - 0, 144) or=1
D/ViewRootImpl@abaa081[MainActivity](30577): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(30577): prepareNavigationBarInfo() DecorView@323d526[MainActivity]
D/InputMethodManager(30577): getNavigationBarColor() -855310
D/InputMethodManager(30577): prepareNavigationBarInfo() DecorView@323d526[MainActivity]
D/InputMethodManager(30577): getNavigationBarColor() -855310
V/InputMethodManager(30577): Starting input: tba=com.proappdev.easylist ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(30577): startInputInner - Id : 0
I/InputMethodManager(30577): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(30577): Input channel constructed: fd=100
D/InputTransport(30577): Input channel destroyed: fd=101
D/ViewRootImpl@abaa081[MainActivity](30577): ViewPostIme pointer 0
D/ViewRootImpl@abaa081[MainActivity](30577): ViewPostIme pointer 1
D/ViewRootImpl@abaa081[MainActivity](30577): ViewPostIme pointer 0
D/ViewRootImpl@abaa081[MainActivity](30577): ViewPostIme pointer 1
I/flutter (30577): ****** null
D/Dialog  (30577): mIsSamsungBasicInteraction = false
D/Dialog  (30577): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/zzbz    (30577): Making Creator dynamically
W/appdev.easylis(30577): Unsupported class loader
W/appdev.easylis(30577): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(30577): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
I/DynamiteModule(30577): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
W/appdev.easylis(30577): Unsupported class loader
W/appdev.easylis(30577): Skipping duplicate class check due to unsupported classloader
I/Google Maps Android API(30577): Google Play services client version: 12451000
I/Google Maps Android API(30577): Google Play services package version: 15090039
W/appdev.easylis(30577): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
D/NetworkSecurityConfig(30577): No Network Security Config specified, using platform default
I/System.out(30577): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(30577): (HTTPLog)-Static: isSBSettingEnabled false
D/InputTransport(30577): Input channel constructed: fd=148
D/ViewRootImpl@f19cdfc[MainActivity](30577): setView = DecorView@7a7ac85[MainActivity] TM=true MM=false
D/SurfaceView(30577): onWindowVisibilityChanged(0) true cd32ada of ViewRootImpl@f19cdfc[MainActivity]
D/ViewRootImpl@f19cdfc[MainActivity](30577): dispatchAttachedToWindow
D/ViewRootImpl@f19cdfc[MainActivity](30577): Relayout returned: old=[0,0][912,600] new=[0,0][912,600] result=0x7 surface={valid=true 516537118720} changed=true
D/mali_winsys(30577): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(30577): eglCreateWindowSurface = 0x7857273b80, 0x784402f010
D/SurfaceView(30577): show() Surface(name=SurfaceView - Sys2037:com.proappdev.easylist/com.proappdev.easylist.MainActivity@cd32ada@0[30577])/@0x83b8c01 com.google.maps.api.android.lib6.gmm6.api.aq{cd32ada VFE...C.. ......ID 0,0-912,600}
D/SurfaceView(30577): surfaceCreated 1 #8 com.google.maps.api.android.lib6.gmm6.api.aq{cd32ada VFE...C.. ......ID 0,0-912,600}
D/SurfaceView(30577): surfaceChanged (912,600) 1 #8 com.google.maps.api.android.lib6.gmm6.api.aq{cd32ada VFE...C.. ......ID 0,0-912,600}
D/mali_winsys(30577): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ViewRootImpl@f19cdfc[MainActivity](30577): Relayout returned: old=[0,0][912,600] new=[0,0][912,600] result=0x3 surface={valid=true 516537118720} changed=false
D/ViewRootImpl@f19cdfc[MainActivity](30577): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 912, 600) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=2
E/AndroidRuntime(30577): FATAL EXCEPTION: Thread-7
E/AndroidRuntime(30577): Process: com.proappdev.easylist, PID: 30577
E/AndroidRuntime(30577): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
E/AndroidRuntime(30577): 	at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15090083@15.0.90 (100408-231259764):3)
E/AndroidRuntime(30577): 	at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15090083@15.0.90 (100408-231259764):3)
E/AndroidRuntime(30577): 	at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15090083@15.0.90 (100408-231259764):15)
E/AndroidRuntime(30577): 	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15090083@15.0.90 (100408-231259764):6)
E/AndroidRuntime(30577): 	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15090083@15.0.90 (100408-231259764):23)
E/AndroidRuntime(30577): 	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15090083@15.0.90 (100408-231259764):8)
E/AndroidRuntime(30577): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000026/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000026/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(30577): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(30577): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(30577): 	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@15090083@15.0.90 (100408-231259764):4)
E/AndroidRuntime(30577): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(30577): 	... 6 more
D/ViewRootImpl@abaa081[MainActivity](30577): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(30577): prepareNavigationBarInfo() DecorView@323d526[MainActivity]
D/InputMethodManager(30577): getNavigationBarColor() -855310
D/SurfaceView(30577): onWindowVisibilityChanged(8) false 2978567 of ViewRootImpl@abaa081[MainActivity]
D/SurfaceView(30577): show() Surface(name=SurfaceView - com.proappdev.easylist/com.proappdev.easylist.MainActivity@2978567@1[30577])/@0xa7e162d io.flutter.view.FlutterView{2978567 VFE...... ........ 0,0-1080,2076}
D/SurfaceView(30577): surfaceDestroyed callback.size 1 #2 io.flutter.view.FlutterView{2978567 VFE...... ........ 0,0-1080,2076}
W/libEGL  (30577): EGLNativeWindowType 0x785d936010 disconnect failed
D/SurfaceView(30577): destroy() Surface(name=SurfaceView - com.proappdev.easylist/com.proappdev.easylist.MainActivity@2978567@1[30577])/@0xa7e162d io.flutter.view.FlutterView{2978567 VFE...... ........ 0,0-1080,2076}
W/libEGL  (30577): EGLNativeWindowType 0x785d935010 disconnect failed
D/OpenGLRenderer(30577): eglDestroySurface = 0x7853412080, 0x785d935000
D/ViewRootImpl@abaa081[MainActivity](30577): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={valid=false 0} changed=true
D/SurfaceView(30577): windowStopped(true) false 2978567 of ViewRootImpl@abaa081[MainActivity]
D/ViewRootImpl@abaa081[MainActivity](30577): Surface release. android.view.WindowManagerGlobal.setStoppedState:669 android.app.Activity.performStop:7646 android.app.ActivityThread.callActivityOnStop:4352 android.app.ActivityThread.performStopActivityInner:4330 android.app.ActivityThread.handleStopActivity:4405 android.app.servertransaction.TransactionExecutor.performLifecycleSequence:192 android.app.servertransaction.TransactionExecutor.cycleToPath:165 android.app.servertransaction.TransactionExecutor.executeLifecycleState:142 
W/libEGL  (30577): EGLNativeWindowType 0x786dca0010 disconnect failed
D/SurfaceView(30577): onWindowVisibilityChanged(8) false cd32ada of ViewRootImpl@f19cdfc[MainActivity]
D/SurfaceView(30577): show() Surface(name=SurfaceView - Sys2037:com.proappdev.easylist/com.proappdev.easylist.MainActivity@cd32ada@0[30577])/@0x83b8c01 com.google.maps.api.android.lib6.gmm6.api.aq{cd32ada VFE...C.. ........ 0,0-912,600}
D/SurfaceView(30577): surfaceDestroyed callback.size 1 #2 com.google.maps.api.android.lib6.gmm6.api.aq{cd32ada VFE...C.. ........ 0,0-912,600}
D/SurfaceView(30577): destroy() Surface(name=SurfaceView - Sys2037:com.proappdev.easylist/com.proappdev.easylist.MainActivity@cd32ada@0[30577])/@0x83b8c01 com.google.maps.api.android.lib6.gmm6.api.aq{cd32ada VFE...C.. ........ 0,0-912,600}
D/ViewRootImpl@abaa081[MainActivity](30577): dispatchDetachedFromWindow
D/ViewRootImpl@abaa081[MainActivity](30577): Surface release. android.view.ViewRootImpl.doDie:7931 android.view.ViewRootImpl.die:7899 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.ActivityThread.handleDestroyActivity:4722 android.app.servertransaction.DestroyActivityItem.execute:39 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145 
D/InputTransport(30577): Input channel destroyed: fd=87
W/libEGL  (30577): EGLNativeWindowType 0x784402f010 disconnect failed
D/OpenGLRenderer(30577): eglDestroySurface = 0x7857273b80, 0x784402f000
D/ViewRootImpl@f19cdfc[MainActivity](30577): dispatchDetachedFromWindow
D/ViewRootImpl@f19cdfc[MainActivity](30577): Surface release. android.view.ViewRootImpl.doDie:7931 android.view.ViewRootImpl.die:7899 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.Dialog.dismissDialog:517 android.app.Dialog.dismiss:500 android.app.Dialog.cancel:1461 
D/InputTransport(30577): Input channel destroyed: fd=148
W/DynamiteModule(30577): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(30577): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule(30577): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/appdev.easylis(30577): Unsupported class loader
W/appdev.easylis(30577): Skipping duplicate class check due to unsupported classloader
W/System  (30577): A resource failed to call release. 
```

```
   info • Unused import: './user.dart' • lib/models/product.dart:3:8 • unused_import
   info • Unused import: 'package:scoped_model/scoped_model.dart' • lib/pages/product.dart:5:8 • unused_import
   info • Unused import: '../scoped_models/main.dart' • lib/pages/product.dart:7:8 • unused_import
   info • The method '_showWarningDialog' isn't used • lib/pages/product.dart:15:3 • unused_element

4 issues found. (ran in 2.7s)
```

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/imran/development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/imran/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/imran/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/imran/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • SM G960F • 21a9ce870c057ece • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by delizondo** [comment]
Same happens to me. On a Nokia 7 Plus, running Android 9. 

pubspec.yaml
```
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+1
  cloud_firestore: ^0.9.0+1
  firebase_auth: ^0.8.1
  firebase_analytics: ^2.0.1
  firebase_core: ^0.3.0+1
  intl: ^0.15.7
  connectivity: ^0.4.2
  latlong: ^0.6.1
  cached_network_image: ^0.6.0-beta+1
  flutter_webview_plugin: ^0.3.0+2
  flutter_duration_picker: ^1.0.4
  flutter_svg: ^0.9.0
  google_maps_flutter: ^0.2.0+4
  geolocator: ^2.1.1
  url_launcher: ^5.0.0
```

Flutter Doctor
```Davids-MacBook-Pro-2:~ david$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.3 18D109, locale en-CR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (2 available)

• No issues found!
```

Crash Error: 
```E/AndroidRuntime(11278): FATAL EXCEPTION: Thread-5
E/AndroidRuntime(11278): Process: com.fixar.fixarbike.dev, PID: 11278
E/AndroidRuntime(11278): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
E/AndroidRuntime(11278): 	at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/AndroidRuntime(11278): 	at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/AndroidRuntime(11278): 	at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):15)
E/AndroidRuntime(11278): 	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):6)
E/AndroidRuntime(11278): 	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):23)
E/AndroidRuntime(11278): 	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):8)
E/AndroidRuntime(11278): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000004f/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000004f/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(11278): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(11278): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(11278): 	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@15090081@15.0.90 (100400-231259764):4)
E/AndroidRuntime(11278): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(11278): 	... 6 more```

**Comment by delizondo** [comment]
The error in the issue [28445](https://github.com/flutter/flutter/issues/28445) is related to this, seems like a duplicate

**Comment by delizondo** [comment]
I can confirm that the solution added [here](https://github.com/flutter/flutter/issues/28445) solves the issue

**Comment by allandaleho** [comment]
For those who needs a quick fix, adding `<uses-library android:name="org.apache.http.legacy" android:required="false"/>` into android manifest fixes the problem for me.

**Comment by sam-toon** [comment]
This seems to be the same as #28630 which has a fix.

**Comment by iskakaushik** [comment]
This should be fixed as of the latest release. Please try that.

**Comment by Elias8** [comment]
Still experiencing the same issue on ```google_maps_flutter: ^0.5.26```. Also, I have tried by adding ```<uses-library android:name="org.apache.http.legacy" android:required="false"/>``` but it doesn't fix the problem.
