### ISSUE TITLE
Tapping on TextField throws an exception

### ISSUE THREAD

**Issue by afnx** [flutter/flutter#28447]
After the last update of Flutter, TextField has started to behave oddly.  When it is tapped, the following error appears:

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching a pointer event:
flutter: 'package:flutter/src/gestures/force_press.dart': Failed assertion: line 209 pos 12:
flutter: 'event.pressureMax >= 1.0': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ForcePressGestureRecognizer.addPointer (package:flutter/src/gestures/force_press.dart:209:12)
flutter: #3      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:731:18)
flutter: #4      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2643:14)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #12     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #13     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Event:
flutter:   PointerDownEvent(Offset(148.3, 711.3))
flutter: Target:
flutter:   RenderPointerListener#a4a39 relayoutBoundary=up15
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Logs

```
[✓] Flutter (Channel master, v1.2.3-pre.31, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.3-pre.31 at /Users/user/Android/flutter
    • Framework revision 3423c831b9 (9 hours ago), 2019-02-24 21:48:50 +0100
    • Engine revision 0546e1e5e9
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • iPhone 6 Plus • 0CBD3FC1-2E7E-4BD2-8728-089A51AD40CA • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
I tentatively added `today` label because I think this was fixed recently. 
Was the fix reverted? Do I mix something up?

**Comment by afnx** [comment]
@zoechi Can you share it, if there is an issue or fix related to this? I use the latest version, I guess.

**Comment by dexcell** [comment]
I can confirm that i had same issue after upgrading flutter just now

**Comment by Tkko** [comment]
Same

**Comment by dexcell** [comment]
After running `flutter doctor` the problem seems gone

**Comment by HansMuller** [comment]
I think this was supposed to have been fixed here: https://github.com/flutter/flutter/issues/26563

**Comment by HansMuller** [comment]
I tried a simple test case on an Android device and the current version of the repo ("Channel master, v1.2.3-pre.33"), seems to work OK.

**Comment by afnx** [comment]
It is fine on Android Emulator. However, I'm still having the same problem on iPhone 6 Plus Simulator although it is `Channel master, v1.2.3-pre.41`.

**Comment by xster** [comment]
This issue is different from #26563 and caused by an addition in #26659. Though it is really surprising that iOS reports a max pressure < 1. 

It shouldn't affect Android since the feature isn't turned on currently for non-iOS devices' text fields.

**Comment by xster** [comment]
I can't repro on physical+simulator iPhone 6s or simulator iPhone 6. @afnx, can you show us a reduced repro program? 

Removing the today tag for now.

**Comment by xster** [comment]
Correction: this does break on physical iPhone 4s (and likely more). Adding today tag back on.
