### ISSUE TITLE
Widget rendering strange since Flutter update

### ISSUE THREAD

**Issue by dsa28s** [flutter/flutter#28484]
Hello.
I using the Flutter beta channel, widgets rendered as shown in the picture below after updating from 1.1.8 to 1.2.1.

**↓ This screenshot flutter version > beta channel v 1.2.1**
<img src="https://user-images.githubusercontent.com/10934461/53383186-07daf080-39ba-11e9-9d86-54988d4ec055.PNG" width="250">

**↓ This screenshot flutter version > beta channel v 1.1.8 (before update)**
<img src="https://user-images.githubusercontent.com/10934461/53383225-35279e80-39ba-11e9-91b9-f24dbd0f3a5b.PNG" width="250">

**Platform** : iOS

**(Current) Here is my flutter information:**

```
$ flutter doctor -v

[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-KR)
    • Flutter version 1.2.1 at /Users/dsa28s/flutter
    • Framework revision 8661d8aecd (11 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dsa28s/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dsa28s/AndroidSDK
    • Java binary at: /Users/dsa28s/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/dsa28s/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Users/dsa28s/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (2 available)
    • Pixel 3 XL • XXXXXXXXX                 • android-arm64 • Android 9 (API 28)
    • 도라도라       • XXXXXXXXX • ios           • iOS 12.1.4

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Can you please provide a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by dsa28s** [comment]
This page using custom font, and image asset. What can I do?

Here is page file `splash-screen.dart`

```dart
// splash-screen.dart

import 'dart:async' show Timer;
import 'dart:io' show Platform;

import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';

import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';

import 'package:google_sign_in/google_sign_in.dart';

import 'package:maat_pick/redux/application-state.dart';
import 'package:maat_pick/redux/auth/auth-middleware.dart';

class SplashPage extends StatefulWidget {
  @override
  SplashPageState createState() => SplashPageState();
}

class SplashPageState extends State<SplashPage> {
  GoogleSignInAccount _googleAccount;

  @override
  void initState() {
    super.initState();

    Timer(new Duration(seconds: 1), () => checkLogin(context));

    if (Platform.isIOS) {
      FlutterStatusbarcolor.setStatusBarWhiteForeground(true);
    } else {
      FlutterStatusbarcolor.setStatusBarColor(Colors.transparent);
      FlutterStatusbarcolor.setStatusBarWhiteForeground(true);
    }
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Container(
            decoration: BoxDecoration(
                gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: [const Color(0xffff3fba), const Color(0xffff971f)],
            )),
            child: Stack(
              children: <Widget>[
                Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Image.asset(
                        'assets/icons/icon_splash.png',
                        width: 160,
                      ),
                      Padding(
                        padding: const EdgeInsets.only(top: 16.0),
                        child: Text(
                          '맛픽',
                          style: TextStyle(
                              fontFamily: 'SongMyung',
                              fontWeight: FontWeight.normal,
                              fontSize: 64,
                              color: Colors.white),
                        ),
                      ),
                      Padding(
                          padding: const EdgeInsets.only(bottom: 40),
                          child: Text(
                            'ma’at pick',
                            style: TextStyle(
                                fontFamily: 'Oswald',
                                fontWeight: FontWeight.normal,
                                fontSize: 36,
                                color: Colors.white),
                          )),
                    ],
                  ),
                ),
                Container(
                  alignment: Alignment.bottomCenter,
                  padding: const EdgeInsets.only(bottom: 50),
                  child: SizedBox(
                      width: 160,
                      height: 3,
                      child: DecoratedBox(
                          decoration: BoxDecoration(
                              borderRadius:
                                  BorderRadius.all(const Radius.circular(8.0))),
                          child: LinearProgressIndicator(
                              backgroundColor: Color(0x4dffffff),
                              valueColor: AlwaysStoppedAnimation<Color>(
                                  Colors.white)))),
                )
              ],
            )),
      );

  void checkLogin(BuildContext context) async {
     // check login logic
  }
}
```

**Comment by zoechi** [comment]
Thanks!
You could publish a reduced project to github or just zip the files and upload into a comment

**Comment by dsa28s** [comment]
![ezgif com-resize](https://user-images.githubusercontent.com/10934461/53406955-688c1c80-39fe-11e9-8e18-1cd8af4257ab.gif)

I separate the screen with the problem and tested it.
However, it didn't happen.

Attached is the video.
The first app is currently being developed, and the second app is a separate screen and compiled.

--

So I did a test.

Remove image widget

```dart
Image.asset(
    'assets/icons/icon_splash.png',
    width: 160,
),
```

It didn't happen!!

And add image widget > happening again.

Attach reduced project file.
[widget_rendering_error.zip](https://github.com/flutter/flutter/files/2905047/widget_rendering_error.zip)

**Comment by zoechi** [comment]
Could you please check if you can reproduce with `master` channel as well?
```
flutter channel master
flutter doctor
```
There was a related fix recently and I don't know if it is included in `beta` already
```
Framework revision 8661d8aecd (11 days ago),
```

**Comment by zoechi** [comment]
I was not able to reproduce
```
[✓] Flutter (Channel master, v1.2.3-pre.47, on Mac OS X 10.14.3 18D42, locale en-AT)
[✓] Connected device (2 available)
    • Pixel XL                  • HT69V0203649  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)
```
but I have not tried iOS

**Comment by dsa28s** [comment]
I change flutter master channel.
Here is my flutter information.

```
[✓] Flutter (Channel master, v1.2.3-pre.50, on Mac OS X 10.14.3 18D109, locale ko-KR)
    • Flutter version 1.2.3-pre.50 at /Users/dsa28s/FlutterSDK
    • Framework revision f460dd60df (3 hours ago), 2019-02-26 08:08:28 -0500
    • Engine revision 9f95ef23aa
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 f7e435ac26)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dsa28s/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dsa28s/AndroidSDK
    • Java binary at: /Users/dsa28s/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/dsa28s/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Users/dsa28s/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • 도라도라 • XXXXXXXX • ios • iOS 12.1.4

! Doctor found issues in 2 categories.
```

Tested on multiple devices.

**iOS 12.1.4 > Strange widget rendering
iOS 11.3 > Strange widget rendering
iOS 10.2 > Strange widget rendering**

Android 9 (Pie) > No problem
Android 8.1 (Oreo) > No Problem
Android 6.0 (Marshmallow) > No Problem

**Comment by tvolkert** [comment]
@dsa28s does this happen in release builds too, or just debug builds (debug builds use software rendering instead of GPU rendering)?

**Comment by jason-simmons** [comment]
What device models did the bug reproduce on?

I tried running this using the Flutter master branch on an iPhone 6, iPhone 6S, and iPhone SE.  The sample app appeared to render correctly on each of these devices.

**Comment by Hixie** [comment]
@dsa28s Is that in the simulator or on a real device or both?

**Comment by dsa28s** [comment]
I just now, updated the Flutter master channel.
Flutter v 1.2.3-pre.50 → Flutter v 1.2.3-pre.65

```
[✓] Flutter (Channel master, v1.2.3-pre.65, on Mac OS X 10.14.3 18D109, locale en-KR)
    • Flutter version 1.2.3-pre.65 at /Users/dsa28s/flutter
    • Framework revision 6daad8d0eb (30 minutes ago), 2019-02-26 17:15:39 -0800
    • Engine revision 113b91fe82
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 0f9a5198bd)
```

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10934461/53459575-bac05280-3a7d-11e9-8d85-8b82b0b0ee3c.gif)

Now, It's not a rendering error, it's just a little weird for a second, and rendered normally.
It's not that much of a concern now, but it appears in the release mode as an attached video.

iPhone Xs (iOS 12.1.4)
iPhone 7 (iOS 11.3)
iPhone 6s (iOS 10.2)

Android > Work perfectly.

Not tested simulator.

**Comment by marcglasberg** [comment]
A question: Do you use the `flutter_svg` package? 

Also, would you say these 3 following issues are the same problem? 
https://github.com/flutter/flutter/issues/28484 
https://github.com/flutter/flutter/issues/22546
https://github.com/flutter/flutter/issues/28786

**Comment by marcglasberg** [comment]
Also these:
https://github.com/flutter/flutter/issues/28227
https://github.com/dnfield/flutter_svg/issues/115

**Comment by dsa28s** [comment]
I used to `flutter_svg` library.
After this happened, I thought it was a `flutter_svg` library problem.
Remove svg library, but it was the same.

**Comment by shakir-betube** [comment]
i also got this issue in release build of iOS.
any update.
![8f62c3e2-a0fb-4e8b-9d8c-c83caa71c660](https://user-images.githubusercontent.com/22122364/54124411-28786100-4424-11e9-8da5-63f887e6a85c.jpeg)

**Comment by tvolkert** [comment]
We should try to reproduce on the following phones, against which this was reported:

iPhone Xs (iOS 12.1.4)
iPhone 7 (iOS 11.3)
iPhone 6s (iOS 10.2)

**Comment by willlarche** [comment]
I'm unable to reproduce on an iPhone XS Max 12.1.4 in release mode with the sample code provided on master commit e1005143d. (Nor on any iOS simulator that matches the models and versions above in debug mode.)

Please upgrade your Flutter on that master channel and retry. If you continue to see the issue, we'll need more specifics on what causes the issue. 

@shakir-betube , please also upgrade and post a link to a small Flutter project with just the code necessary to reproduce if you still see the issue..

**Comment by shakir-fattani** [comment]
Thank you @willlarche. Switching to master channel fixes the issue.

**Comment by tvolkert** [comment]
Thanks @shakir-fattani. I'm going to close this since it's already been fixed in master.

@csells FYI unfortunately, this means that this bug exists in the stable branch.

**Comment by dsa28s** [comment]
Thanks for comment! I using master channel for flutter, I believe this issue was solved.
It doesn't happen anymore. Thank you for flutter team and all participants for this issue!

**Comment by allandaleho** [comment]
Help @tvolkert !
I'm still having this problem after i changed to master channel, before it only happened with release and not with debug but now both compile have this problem. I did a flutter clean a few times and still have no luck.

`$ flutter doctor -v
[✓] Flutter (Channel master, v1.3.10-pre.29, on Mac OS X 10.14 18A391, locale
    en-SG)
    • Flutter version 1.3.10-pre.29 at
      /Users/allandaleho/Documents/Flutter/flutter
    • Framework revision 89a51272d5 (24 hours ago), 2019-03-12 18:32:42 -0700
    • Engine revision 5ccee95373
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/allandaleho/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Lena’s iPhone • b34804a1e2caa10a5619c5b358d9dcbd5d806288 • ios • iOS
      11.1.2

• No issues found!`

**Comment by tvolkert** [comment]
@allandaleho, please post the code for a minimal reproducible case.  We've still been unable to reproduce this.

**Comment by songfei** [comment]
May be same issue on Android Pad   flutter_svg demo 

![screen](https://user-images.githubusercontent.com/1343893/54329841-68229100-464e-11e9-88d4-46e4fc087789.png)

**Comment by tvolkert** [comment]
@all we're unable to reproduce this and thus can't investigate -- if you're able to reliably reproduce this with an updated master channel, please include minimal reproducible code, debug vs release build, & device info (simulator vs physical device, make & model).

**Comment by marcglasberg** [comment]
@tvolkert In any case this issue should be reopened, since it's not fixed in master. As I understand from reading the above, nothing was done to fix this, we were just hoping this would magically be fixed as time passes by? Not gonna happen. I've been seeing glitches like this since Flutter beta. :(

**Comment by tvolkert** [comment]
> We were just hoping this would magically be fixed as time passes by?

Please be respectful if your communication.  https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

It sounded like an inadvertent fix must have landed since the original reporter had reported that they were no longer able to reproduce on master.

I've re-opened the issue.

**Comment by dsa28s** [comment]
I'm currently using the latest commit on the Flutter master channel. However, not reproduced. 
But, It still happens in a stable version.

First of all, I think the problem seems to have been solved because it doesn't happen on the master channel.

**Comment by tvolkert** [comment]
@liyuqian @jason-simmons does this look like a dup of #28227 as well?

**Comment by liyuqian** [comment]
Seems so to me. @csmartdalton86 : has Skia recently disabled CCPR in the master branch which fixes this issue in the Flutter master branch?

**Comment by zazu27** [comment]
I am from #29289
All works fine after deleting Image widget. I use png file.

**Comment by wilburt** [comment]
> Seems so to me. @csmartdalton86 : has Skia recently disabled CCPR in the master branch which fixes this issue in the Flutter master branch?

@liyuqian Just curious, in this context, please what is CCPR in full?

**Comment by liyuqian** [comment]
CCPR = Coverage Counting Path Rendering, a new vector path rasterization algorithm on GPU.

Its main issue (which is shared by many new algorithms) is skbug.com/6886

**Comment by dsa28s** [comment]
The recent upgrade of the Flutter master channel.
Build in release mode, it was reproduced.

Removing the png image, does not reproduced.
But, re-including the png image, reproduced.

I'm looking at the engine code in case it helps, but it's too complicated. Sorry I didn't help a lot.

**Comment by dsa28s** [comment]
@xster What is that mean label `customer: penguin` ? 😃

**Comment by abogdanovich1** [comment]
I am also having this issue with iOS. Got an app rejected from the App Store due to this reason.
I am on the latest Stable build of Flutter (1.2.something I believe). 
I've had this issue during development from time to time, and was hoping it was only specific to dev builds, and wouldn't happen on a release build, but it appears it still happens there.

I unfortunately don't have much more info other than this screenshot, and that it seems to be very much related to everyone else having this same issue, but I can provide as much info as I can if you can point me to the right direction.

![attachment-156757836516287880IMG_0496](https://user-images.githubusercontent.com/21229169/55173602-38d54f00-5139-11e9-8337-3c94ec5bcdf3.PNG)

I am not at my machine at the moment and can't show my flutter doctor/version output, but will update this comment or attach those when I get home. I have not yet tried building with the master branch, but I am also not able to reliably reproduce this. It happens some times, but not others which makes it really hard to see if switching to the master branch actually helped, or I just got lucky on a few runs.

Either way, I would like to help as much as I can to diagnose this issue so if anyone has some tips on how they've reproduced this bug, please let me know and I'll try to do the same on my machine and see what I can find out!

**Comment by tvolkert** [comment]
@abogdanovich1 this issue should be fixed on the master channel - can you see if you can reproduce on that channel?

**Comment by abogdanovich1** [comment]
@tvolkert I will try my best, but as I said in my last comment I'm not even sure how to reliably reproduce it on the Stable channel. I'm gonna attempt to get the issue to pop up at least somewhat reliably in my current build, and switch to master to see if issue goes away.

I'll report back what I find out!

**Comment by michalsuryntequiqo** [comment]
I have the same issue rendering issue as folks above. After experimenting with different Flutter versions, **only** `channel beta v.1.2.1` seems to be working fine.
The bug happens on `master`,  `stable` and `beta` (versions higher than mention above v.1.2.1) channels.

<img width="371" alt="Zrzut ekranu 2019-04-03 o 14 14 24" src="https://user-images.githubusercontent.com/46317368/55478016-dbe70680-561a-11e9-844c-88645251a19b.png">

**Comment by abogdanovich1** [comment]
After switching to the master channel, I was able to get my app through the review process. Unfortunately, I cannot fully confirm that the bug is fixed, as I was still not reliably able to reproduce the issue prior to switching to master.

When I launched the app once, it glitched immediately upon logging in, but following the exact same steps 23 times afterwards did not trigger the glitch.

@michalsuryntequiqo have you found a way to get this to happen every time if you're using one of the problematic flutter builds?

**Comment by michalsuryntequiqo** [comment]
@abogdanovich1 Nope. Using problematic Flutter's versions it works unpredictable and nondeterministic. Sometimes it works fine, sometimes glitches - the same both when debugging app and in the release mode (deployed via TestFlight).
I was also experimenting a lot with widgets hierarchy or switching images used - all with no success.
The only way I found to make it work **stable** is to use `Flutter beta v1.1.8`.

**Comment by andrea689** [comment]
Also my bug is not present in v1.1.8 #30565

**Comment by kevinrodriguez-io** [comment]
This is happening to me too on iOS Production Releases for Flutter 1.2, i will attach screenshots and logs but it's kinda the same issue everyone here is having.

Please note i did crete my project using the -i swift flag (Swift) and i'm using the custom embedded views for Google maps; also i'm using Fontawesome icons and flare.

**Comment by liyuqian** [comment]
Flutter 1.2 still has CCPR enabled. CCPR was disabled in Flutter 1.4.0 so please try to see if the issue is still in 1.4.0 or in the master branch.

If the issue can still be reproduced in 1.4.0 or master, then getting an SKP screenshot by `flutter screenshot --type=skia --observatory-port=<observatory_port_from_flutter_run>` would be helpful for us to diagnose the problem.

**Comment by liyuqian** [comment]
Also, the CCPR's glitch was introduced around 01/07/0219 (https://skia.googlesource.com/skia.git/+/351e80cc28ff6fff947d4272f4792e40615f07ed) so v1.18 (released on 01/08/2019, which probably didn't pick up Skia's change on 01/07 yet) and earlier versions are expected to not have such glitches.

**Comment by metizror** [comment]
Switch to flutter channel "master" resolved my issue. 

Just followed below steps: 
    flutter channel master 
    flutter upgrade

**Comment by chinmaygarde** [comment]
We think this thread described two issues:

* Rendering regressions caused by CCPR.
* Incorrect management of resource context on iOS.

CCPR has been disabled and the iOS [issue fixed](https://github.com/flutter/engine/pull/8387). Closing.

**Comment by zhancheng** [comment]
this bug already fixed , but  another problem come out, the image at first screen loaded slowly then other widget such as text, it is not a good experience.

**Comment by cwwng** [comment]
Can you provide a specific version number of the Flutter that has solved this problem? Thank you.
