### ISSUE TITLE
Flutter Google Maps Crash

### ISSUE THREAD

**Issue by momoDragon** [flutter/flutter#28630]
## Steps to Reproduce
Run the example project given in the repo
## Logs
```
D/ViewRootImpl@24a61fd[MainActivity](27435): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={valid=true 524604243968} changed=true
I/OpenGLRenderer(27435): Initialized EGL, version 1.4
D/OpenGLRenderer(27435): Swap behavior 2
D/SurfaceView(27435): show() Surface(name=SurfaceView - mycompany.com.foodpluslifevendor/mycompany.com.foodpluslifevendor.MainActivity@5e020f9@0[27435])/@0xd4bc2d8 io.flutter.view.FlutterView{5e020f9 VFED..... ......ID 0,0-1080,2094}
D/mali_winsys(27435): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27435): eglCreateWindowSurface = 0x7a2487c280, 0x7a24d98010
D/SurfaceView(27435): surfaceCreated 1 #8 io.flutter.view.FlutterView{5e020f9 VFED..... ......ID 0,0-1080,2094}
D/mali_winsys(27435): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
Syncing files to device SM G965F...
D/SurfaceView(27435): surfaceChanged (1080,2094) 1 #8 io.flutter.view.FlutterView{5e020f9 VFED..... ......ID 0,0-1080,2094}
I/Choreographer(27435): Skipped 39 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@24a61fd[MainActivity](27435): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 524604243968} changed=false
I/OpenGLRenderer(27435): Davey! duration=742ms; Flags=1, IntendedVsync=365380398735194, Vsync=365381048735168, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=365381063032664, AnimationStart=365381063080511, PerformTraversalsStart=365381063144164, DrawStart=365381071989126, SyncQueued=365381077125626, SyncStart=365381077287703, IssueDrawCommandsStart=365381077569934, SwapBuffers=365381139664164, FrameCompleted=365381141374741, DequeueBufferDuration=4250000, QueueBufferDuration=345000, 
D/ViewRootImpl@24a61fd[MainActivity](27435): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(27435): prepareNavigationBarInfo() DecorView@e1a3bc0[MainActivity]
D/InputMethodManager(27435): getNavigationBarColor() -855310
D/InputMethodManager(27435): prepareNavigationBarInfo() DecorView@e1a3bc0[MainActivity]
D/InputMethodManager(27435): getNavigationBarColor() -855310
V/InputMethodManager(27435): Starting input: tba=mycompany.com.foodpluslifevendor ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(27435): startInputInner - Id : 0
I/InputMethodManager(27435): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(27435): Input channel constructed: fd=102
D/ViewRootImpl@24a61fd[MainActivity](27435): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 126) or=1
D/InputMethodManager(27435): prepareNavigationBarInfo() DecorView@e1a3bc0[MainActivity]
D/InputMethodManager(27435): getNavigationBarColor() -855310
V/InputMethodManager(27435): Starting input: tba=mycompany.com.foodpluslifevendor ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(27435): startInputInner - Id : 0
D/ViewRootImpl@24a61fd[MainActivity](27435): ViewPostIme pointer 0
D/ViewRootImpl@24a61fd[MainActivity](27435): ViewPostIme pointer 1
D/Dialog  (27435): mIsSamsungBasicInteraction = false
D/Dialog  (27435): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/zzbz    (27435): Making Creator dynamically
W/dpluslifevendo(27435): Unsupported class loader
W/dpluslifevendo(27435): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(27435): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
I/DynamiteModule(27435): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
V/DynamiteModule(27435): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/dpluslifevendo(27435): Unsupported class loader
I/Google Maps Android API(27435): Google Play services client version: 12451000
I/Google Maps Android API(27435): Google Play services package version: 15090037
W/dpluslifevendo(27435): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
D/NetworkSecurityConfig(27435): No Network Security Config specified, using platform default
I/System.out(27435): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(27435): (HTTPLog)-Static: isSBSettingEnabled false
D/InputTransport(27435): Input channel constructed: fd=154
D/ViewRootImpl@11056c[MainActivity](27435): setView = DecorView@46e6735[MainActivity] TM=true MM=false
E/GoogleMapController(27435): Cannot enable MyLocation layer as location permissions are not granted
D/SurfaceView(27435): onWindowVisibilityChanged(0) true e7247ca of ViewRootImpl@11056c[MainActivity]
D/ViewRootImpl@11056c[MainActivity](27435): dispatchAttachedToWindow
D/ViewRootImpl@11056c[MainActivity](27435): Relayout returned: old=[0,0][788,525] new=[0,0][788,525] result=0x7 surface={valid=true 523734626304} changed=true
D/mali_winsys(27435): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27435): eglCreateWindowSurface = 0x7a2487c300, 0x79f1043010
D/SurfaceView(27435): show() Surface(name=SurfaceView - Sys2037:mycompany.com.foodpluslifevendor/mycompany.com.foodpluslifevendor.MainActivity@e7247ca@0[27435])/@0x716a19c com.google.maps.api.android.lib6.gmm6.api.aq{e7247ca VFE...C.. ......ID 0,0-788,525}
D/SurfaceView(27435): surfaceCreated 1 #8 com.google.maps.api.android.lib6.gmm6.api.aq{e7247ca VFE...C.. ......ID 0,0-788,525}
D/SurfaceView(27435): surfaceChanged (788,525) 1 #8 com.google.maps.api.android.lib6.gmm6.api.aq{e7247ca VFE...C.. ......ID 0,0-788,525}
D/mali_winsys(27435): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ViewRootImpl@11056c[MainActivity](27435): Relayout returned: old=[0,0][788,525] new=[0,0][788,525] result=0x3 surface={valid=true 523734626304} changed=false
D/ViewRootImpl@11056c[MainActivity](27435): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 788, 525) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=2
E/AndroidRuntime(27435): FATAL EXCEPTION: Thread-7
E/AndroidRuntime(27435): Process: mycompany.com.foodpluslifevendor, PID: 27435
E/AndroidRuntime(27435): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
E/AndroidRuntime(27435): 	at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/AndroidRuntime(27435): 	at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/AndroidRuntime(27435): 	at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):15)
E/AndroidRuntime(27435): 	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):6)
E/AndroidRuntime(27435): 	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):23)
E/AndroidRuntime(27435): 	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):8)
E/AndroidRuntime(27435): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000044/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000044/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(27435): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(27435): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(27435): 	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@15090081@15.0.90 (100400-231259764):4)
E/AndroidRuntime(27435): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(27435): 	... 6 more
I/Process (27435): Sending signal. PID: 27435 SIG: 9
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] VS Code, 64-bit edition (version 1.24.1)
[√] Connected device (1 available)

• No issues found!
```

## What worked:
When running the app on my emulator (google pixel 2xl) it worked.
## What did not work: 
When running it on my physical device (samsung s9 plus) it crashed immediately when loading the map

**Comment by momoDragon** [comment]
running version:  google_maps_flutter: ^0.3.0+1

**Comment by sam-toon** [comment]
I have this crash in an emulator.  It seems to crash in Android 9 (Pie), but works in earlier versions of Android. This is for both emulators and physical devices.

**Comment by iskakaushik** [comment]
Will be addressed in https://github.com/flutter/plugins/pull/1294, we need to add `<uses-library android:name="org.apache.http.legacy" android:required="false"/>` to `AndroidManifest.xml`.

**Comment by iskakaushik** [comment]
This is addressed by `0.3.0+2`. Please try that version. Thanks!

**Comment by jsa-nic** [comment]
Still experiencing this on `0.3.0+2`, however adding `<uses-library android:name="org.apache.http.legacy" android:required="false"/>` to the manifest fixed the issue, so perhaps the fix didn't make it out with that build?

**Comment by tommaso1** [comment]
Still on 0.4.0 `<uses-library android:name="org.apache.http.legacy" android:required="false"/>` under `<application>` tag on manifest solve the problem. I have experienced this library bug only on android 9

**Comment by silasrm** [comment]
Hi, 
Google Map continues crash a app. I'm using this config `<uses-library android:name="org.apache.http.legacy" android:required="false"/>`, but continue to crash.

Any idea?

**Comment by AntoineJonard** [comment]
Hi,
Same problem for me and the <uses-library android:name="org.apache.http.legacy" android:required="false"/> change nothing.
I use google_maps_flutter: ^1.0.6.
the emulator : API 27 (Android 8.1)

`Syncing files to device Android SDK built for x86...
D/EGL_emulation( 8302): eglMakeCurrent: 0xb03afde0: ver 2 0 (tinfo 0x963919f0)
I/flutter ( 8302): Ancienne position : LatLng(50.331173, 3.51246900000001)
D/        ( 8302): HostConnection::get() New Host Connection established 0x94846900, tid 8314
I/zzbz    ( 8302): Making Creator dynamically
W/zygote  ( 8302): Unsupported class loader
W/zygote  ( 8302): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule( 8302): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule( 8302): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule( 8302): Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/        ( 8302): HostConnection::get() New Host Connection established 0x94846e80, tid 8316
W/zygote  ( 8302): Unsupported class loader
W/zygote  ( 8302): Skipping duplicate class check due to unsupported classloader
I/Google Maps Android API( 8302): Google Play services client version: 12451000
I/Google Maps Android API( 8302): Google Play services package version: 204516022
I/zygote  ( 8302): Do partial code cache collection, code=28KB, data=28KB
I/zygote  ( 8302): After code cache collection, code=28KB, data=28KB
I/zygote  ( 8302): Increasing code cache capacity to 128KB
W/DynamiteModule( 8302): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 8302): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule( 8302): Selected remote version of com.google.android.gms.googlecertificates, version >= 6`
