### ISSUE TITLE
Cannot execute operation because FlutterJNI is not attached to native.

### ISSUE THREAD

**Issue by pamir72** [flutter/flutter#28651]
App crashes and exception 

```
Cannot execute operation because FlutterJNI is not attached to native.
```
appears if I close application during `await getCurrentPosition` in `geolocator` plugin `^3.0.0`.(Android).

It have started after newest `flutter upgrade`. Not geolocator upgrade !

## Log
```
E/AndroidRuntime( 4949): FATAL EXCEPTION: main
E/AndroidRuntime( 4949): Process: ru.ser.spm, PID: 4949
E/AndroidRuntime( 4949): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime( 4949): at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:523)
E/AndroidRuntime( 4949): at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:486)
E/AndroidRuntime( 4949): at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime( 4949): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime( 4949): at com.baseflow.flutter.plugin.geolocator.data.Result.success(Result.java:22)
E/AndroidRuntime( 4949): at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.reportLocationUpdate(LocationUpdatesUsingLocationServicesTask.java:108)
E/AndroidRuntime( 4949): at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.access$000(LocationUpdatesUsingLocationServicesTask.java:19)
E/AndroidRuntime( 4949): at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask$1.onLocationResult(LocationUpdatesUsingLocationServicesTask.java:40)
E/AndroidRuntime( 4949): at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
E/AndroidRuntime( 4949): at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
E/AndroidRuntime( 4949): at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
E/AndroidRuntime( 4949): at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 4949): at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4949): at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 4949): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4949): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 4949): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Lost connection to device.
```
## Configuration
```yml
geolocator ^3.0.0
```
```
[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.14.3 18D109, locale ru-RU)
• Flutter version 1.2.2 at /Users/pavelmiheev/Flutter
• Framework revision 007a415c2a (5 days ago), 2019-02-21 20:22:47 -0800
• Engine revision f1f19bba8f
• Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/pavelmiheev/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.1, Build version 10B61
• ios-deploy 2.0.0
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 33.3.1
• Dart plugin version 182.5215
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
• SM G930F • ad0b1603812a66dbad • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by pamir72** [comment]
**Additionally. Geolocator had nothing to do.
This happens if you quickly exit the application during launching**

FATAL EXCEPTION: main
E/AndroidRuntime(23688): Process: ru.serp.spm, PID: 23688
E/AndroidRuntime(23688): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(23688): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:514)
E/AndroidRuntime(23688): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:477)
E/AndroidRuntime(23688): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime(23688): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime(23688): 	at com.tekartik.sqflite.SqflitePlugin$BgResult$1.run(SqflitePlugin.java:88)
E/AndroidRuntime(23688): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(23688): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23688): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23688): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(23688): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23688): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(23688): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (23688): Sending signal. PID: 23688 SIG: 9
Lost connection to device.

**Comment by luigi-agosti** [comment]
I'm having similar issues with:
    • Flutter version 1.3.0 at /Users/luigi/dev/app/flutter-alpha-20171102
    • Framework revision 3054a93579 (3 days ago), 2019-02-27 14:49:49 -0800
    • Engine revision 4434a39c7d
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 0f9a5198bd)

**Comment by AresVampire** [comment]
I am facing the same issue without geolocator.
I am using Location
Flutter version 1.3.0

**Comment by pamir72** [comment]
Problem seems to have started after [**Roll engine f7306394e303..1d0615af4ee5**](https://github.com/flutter/flutter/pull/28487)

**Comment by creativecreatorormaybenot** [comment]
Same happens with `5. at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$9.onSuccess (Unknown Source:8)` (previous four functions in the stack are the same) on `Xiaomi Mi A2 (jasmine_sprout), Android 9`.

**Comment by pamir72** [comment]
D/SurfaceView(19441): surfaceDestroyed 1 io.flutter.view.FlutterView{9cd6c0b VFE...... .F....I. 0,0-1080,1920}
D/AndroidRuntime(19441): Shutting down VM
E/AndroidRuntime(19441): FATAL EXCEPTION: main
E/AndroidRuntime(19441): Process: ru.serviopump.spmobile, PID: 19441
E/AndroidRuntime(19441): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(19441): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:514)
E/AndroidRuntime(19441): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:444)
E/AndroidRuntime(19441): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
E/AndroidRuntime(19441): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
E/AndroidRuntime(19441): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(19441): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:71)
E/AndroidRuntime(19441): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel.updateEditingState(TextInputChannel.java:117)
E/AndroidRuntime(19441): 	at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:61)
E/AndroidRuntime(19441): 	at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:86)
E/AndroidRuntime(19441): 	at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:444)
E/AndroidRuntime(19441): 	at android.view.inputmethod.BaseInputConnection.closeConnection(BaseInputConnection.java:163)
E/AndroidRuntime(19441): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
E/AndroidRuntime(19441): 	at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:225)
E/AndroidRuntime(19441): 	at com.android.internal.view.IInputConnectionWrapper.closeConnection(IInputConnectionWrapper.java:211)
E/AndroidRuntime(19441): 	at android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.deactivate(InputMethodManager.java:644)
E/AndroidRuntime(19441): 	at android.view.inputmethod.InputMethodManager.clearConnectionLocked(InputMethodManager.java:1016)
E/AndroidRuntime(19441): 	at android.view.inputmethod.InputMethodManager.finishInputLocked(InputMethodManager.java:1038)
E/AndroidRuntime(19441): 	at android.view.inputmethod.InputMethodManager.windowDismissed(InputMethodManager.java:1838)
E/AndroidRuntime(19441): 	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:494)
E/AndroidRuntime(19441): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:435)
E/AndroidRuntime(19441): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:131)
E/AndroidRuntime(19441): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4645)
E/AndroidRuntime(19441): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime(19441): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
E/AndroidRuntime(19441): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(19441): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(19441): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(19441): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19441): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(19441): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Lost connection to device.

**Comment by MDSADABWASIM** [comment]
App crashes while closing it, I'm not even using geolocator plugin, the error log is same but have some log related to cloud firestore.

**Comment by arteki65** [comment]
I have similar issue when using connectivity plugin https://pub.dartlang.org/packages/connectivity#-readme-tab-
App crashes when I close the app(by pressing back button) and then run it again and turn on/off internet conneciton.

**Comment by dark-chocolate** [comment]
Those of you (@arteki65, @MDSADABWASIM, @AresVampire and others) who are facing this issue but hasn't upvoted it yet, I request you to please do so, so that Flutter team can put this issue on priority. 

Thanks

**Comment by Theunodb** [comment]
Also having this issue

**Comment by dark-chocolate** [comment]
@Theunodb Please read last message of this thread again and upvote this issue.

**Comment by MDSADABWASIM** [comment]
@zoechi Any suggestions.

**Comment by dark-chocolate** [comment]
I'm just not able to push my app on the Play store because of this issue. Hoping to get a quick fix. Thanks @zoechi for putting it in goals.

**Comment by MDSADABWASIM** [comment]
Seems like these two methods get called before crash From 
engine/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java class 

`private void ensureNotAttachedToNative() {
    if (nativePlatformViewId != null) {
      throw new RuntimeException("Cannot execute operation because FlutterJNI is attached to native.");
    }
  }

  private void ensureAttachedToNative() {
    if (nativePlatformViewId == null) {
      throw new RuntimeException("Cannot execute operation because FlutterJNI is not attached to native.");
    }
}`

**Comment by jonahwilliams** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I'll look into this tomorrow.  For now, switching from an exception to a log warning should fix this issue.

@jason-simmons @mklim do you have thoughts on what the appropriate action is in the scenario where a platform message comes through after the FlutterView has been destroyed?  In some cases a no-op might be fine, but in other cases this might signal an important missed message, depending on the plugin in question.

**Comment by matthew-carroll** [comment]
This bug should be fixed here: https://github.com/flutter/engine/pull/8170

**Comment by dark-chocolate** [comment]
I'm on dev channel and changes made are in the master channel (which it how it works) but is there any way to edit this file manually in the dev channel? 

I tried searching for the file but all I get is `FlutterJNI.class` (compiled file), I can't get the source code. So, can I make these changes on my own without having to update flutter.

Thanks to all developers who are striving to fix issues real quick. 💯

**Comment by pamir72** [comment]
I'm on dev channel too. Our fate is hoping for a quick dev release )

**Comment by matthew-carroll** [comment]
@dark-chocolate you could choose to compile with a custom version of the engine.  To do that, you would follow the standard instructions for working on the engine, available in the Wiki.  However, if you're not already setup to do that then you are probably better off just waiting for the downstream roll.

**Comment by pamir72** [comment]
**_Updated to 1.3.11. The problem is not resolved_**

[✓] Flutter (Channel dev, v1.3.11, on Mac OS X 10.14.3 18D109, locale ru-RU)
    • Flutter version 1.3.11 at /Users/pavelmiheev/Flutter
    • Framework revision 73fb457cae (3 days ago), 2019-03-14 23:51:18 -0700
    • Engine revision 403337ebb8
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)


java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(  704): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:532)
E/AndroidRuntime(  704): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:495)
E/AndroidRuntime(  704): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime(  704): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime(  704): 	at com.tekartik.sqflite.SqflitePlugin$BgResult$1.run(SqflitePlugin.java:91)
E/AndroidRuntime(  704): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(  704): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  704): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(  704): 	at android.app.ActivityThread.main(ActivityThread.java:7032)
E/AndroidRuntime(  704): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  704): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(  704): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by matthew-carroll** [comment]
@jonahwilliams I think the issue is resolved, it must just be taking a while to get the roll through.  Notice that the line numbers in the latest callstack don't match FlutterJNI, and notice that the `ensureAttachedToNative` is no longer even called in FlutterJNI from `invokePlatformMessageResponseCallback`:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java

Should this ticket really be re-opened?

**Comment by pamir72** [comment]
**Error while updating to 1.3.13**

error: Your local changes to the following files would be overwritten by merge:
        examples/flutter_gallery/pubspec.yaml
        packages/flutter_tools/pubspec.yaml
Please commit your changes or stash them before you merge.
Aborting

**_What is it ?_**

**Comment by pamir72** [comment]
1.3.13. it seems the issue is solved. Thank you !

**Comment by dark-chocolate** [comment]
@pamir72 @matthew-carroll @zoechi 
I've updated to `1.3.13` but still the issue persist. I am not sure why, there is also something interesting. When I run `flutter doctor`, here is the output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```
And when I run `flutter version` here what it shows

```
...
v1.3.0
v1.3.1
v1.3.10
v1.3.11
v1.3.12
v1.3.13
v1.3.2
v1.3.3
v1.3.4
v1.3.5
v1.3.6
v1.3.7
v1.3.8
v1.3.9
``` 

Am I doing something wrong?

**Comment by matthew-carroll** [comment]
@dark-chocolate can you please post your latest crash stacktrace?

**Comment by dark-chocolate** [comment]
@matthew-carroll Sure, here it is

```
  --------- beginning of crash
E: FATAL EXCEPTION: main
    Process: com.example.app, PID: 14078
    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:553)
        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:477)
        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:149)
        at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:142)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:213)
        at com.baseflow.flutter.plugin.geolocator.data.Result.success(Result.java:26)
        at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.reportLocationUpdate(LocationUpdatesUsingLocationServicesTask.java:129)
        at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.access$000(LocationUpdatesUsingLocationServicesTask.java:21)
        at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask$1.onLocationResult(LocationUpdatesUsingLocationServicesTask.java:49)
        at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
        at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
        at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W:   Force finishing activity com.example.app/.MainActivity
```

**Comment by pamir72** [comment]
Hmm...I use geolocator and I get warning in the log now. Not exception.

**Comment by dark-chocolate** [comment]
@pamir72 I'm also using the same (latest version of both flutter dev and geolocator) but I'm still having the issue. Hope @matthew-carroll comes up with a solution.

**Comment by matthew-carroll** [comment]
@pamir72 that warning is expected.  That will happen until we eventually determine the root cause.

@dark-chocolate somehow you're using a different version.  My guess is its because you're on the "dev" channel instead of the "master" channel.  You may have to wait longer for the update.  @pamir72 you said you were on the "master" channel, right?

**Comment by dark-chocolate** [comment]
@matthew-carroll pamir72 is also on dev channel just like me and his issue got solved in 1.3.13, below are the quotes from @pamir72 

> I'm on dev channel too. Our fate is hoping for a quick dev release )


> 1.3.13. it seems the issue is solved. Thank you !

**Comment by pamir72** [comment]
@matthew-carroll I'm on dev

**Comment by dark-chocolate** [comment]
Other participants who also have upvoted this issue or having this issue and who are also running dev channel, please upgrade your flutter version by using `flutter upgrade` and let us know if that fixes your issue because it worked for pamir72 and failed for me including the fact that we both are using same dev channel, same package (geolocator). 

Thank you :)

**Comment by yy1300326388** [comment]
## 

## flutter doctor -v

```
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.3.13 at /Users/shipuliu/Documents/flutter
    • Framework revision 59ce7d6bff (3 days ago), 2019-03-18 11:20:10 -0700
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shipuliu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio
      2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.
```
## Log

```
03-21 11:27:54.649   998   998 I am_crash: [18017,0,com.tengyue360.student,15253060,java.lang.RuntimeException,Cannot execute operation because FlutterJNI is not attached to native.,FlutterJNI.java,553]
=========================================================================================================
03-21 11:30:20.519 22478 23151 I am_crash: [22930,0,com.tengyue360.student,13155908,java.lang.RuntimeException,Cannot execute operation because FlutterJNI is not attached to native.,FlutterJNI.java,553]
=========================================================================================================
03-21 11:27:54.459 18017 18017 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x417d1898)
=================================================================================================
03-21 11:27:54.649 18017 18017 E AndroidRuntime: FATAL EXCEPTION: main
03-21 11:27:54.649 18017 18017 E AndroidRuntime: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:553)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:477)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:71)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.embedding.engine.systemchannels.TextInputChannel.updateEditingState(TextInputChannel.java:117)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:61)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:86)
03-21 11:27:54.649 18017 18017 E AndroidRuntime: 	at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:272)
=================================================================================================
03-21 11:29:26.459 18017 18017 E AndroidRuntime: android.os.DeadObjectException
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at android.os.BinderProxy.transact(Native Method)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:3708)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:138)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:51)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl$1.uncaughtException(AppCompatDelegateImpl.java:143)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
03-21 11:29:26.459 18017 18017 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
=================================================================================================
03-21 11:30:18.249 22930 22930 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x417ad898)
=================================================================================================
03-21 11:30:20.519 22930 22930 E AndroidRuntime: FATAL EXCEPTION: main
03-21 11:30:20.519 22930 22930 E AndroidRuntime: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:553)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:477)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:71)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.embedding.engine.systemchannels.TextInputChannel.updateEditingState(TextInputChannel.java:117)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:61)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:86)
03-21 11:30:20.519 22930 22930 E AndroidRuntime: 	at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:272)
=================================================================================================

```
This problem is very serious for me, which makes it impossible for me to publish the application. The pass rate is only 53.57%.

**Comment by matthew-carroll** [comment]
@dark-chocolate and @yy1300326388 can each of you try the master channel and see if your problem is solved on master?

**Comment by joshuaferguson** [comment]
I'm still seeing this error:

```
03-21 14:10:30.965 24510-24510/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.worldview.mobile, PID: 24510
    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(Unknown Source)
        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(Unknown Source)
        at io.flutter.embedding.engine.dart.DartMessenger.send(Unknown Source)
        at io.flutter.embedding.engine.dart.DartExecutor.send(Unknown Source)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(Unknown Source)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(Unknown Source)
        at io.flutter.embedding.engine.systemchannels.TextInputChannel.updateEditingState(Unknown Source)
        at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(Unknown Source)
        at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(Unknown Source)
        at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:277)
        at android.view.inputmethod.InputMethodManager.reportFinishInputConnection(InputMethodManager.java:998)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4000)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6967)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
```

```
[✓] Flutter (Channel master, v1.3.14-pre.42, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.14-pre.42 at /Users/jferguson/flutter
    • Framework revision db096cdfd8 (2 hours ago), 2019-03-21 10:32:43 -0700
    • Engine revision d4d4883216
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jferguson/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/jferguson/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5199772/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by matthew-carroll** [comment]
@joshuaferguson are you seeing that error on the master channel?

**Comment by joshuaferguson** [comment]
Yes, this is currently on the master channel.

**Comment by matthew-carroll** [comment]
Ok, now I see where the confusion came from.  We're mixing up 2 different stacktraces in this ticket.  The one I originally fixed is not the one that has been referenced in the last few messages.

Here is a PR that should at least put an end to the crashes you are seeing:
https://github.com/flutter/engine/pull/8246

It is still unclear to me why the app is detaching from Flutter's C++ side and yet the app is still attempting to send platform messages.  I have filed another ticket to investigate the root cause:

https://github.com/flutter/flutter/issues/29757

**Comment by joshuaferguson** [comment]
AHHHH...I apologize for hijacking the thread!

**Comment by matthew-carroll** [comment]
No worries - they are related, and we need to get this fixed for you all.  Unfortunately, we'll need to go through another engine roll to get this fix out.  But I'll try to keep this thread updated.

**Comment by matthew-carroll** [comment]
@joshuaferguson @yy1300326388 @dark-chocolate Would you all mind providing your repro steps to cause this issue?  Was the app in foreground or background?  Were you interacting with it at the time of the issue?  Any other details that can help us repro on our end?

**Comment by matthew-carroll** [comment]
FYI - the latest PR for the bugfix just landed in the engine:
https://github.com/flutter/engine/pull/8246

Next we need to wait for an engine roll to bring this engine change into the Flutter framework on master.

**Comment by dark-chocolate** [comment]
@matthew-carroll I updated it to `master` and seems like the issue is solved (I mean there is no error but only warning), 

```
W/FlutterJNI: Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter.baseflow.com/geolocator/events. Response ID: 0
```

And if I close the app and opens it again, I keep getting this warning every second my app request a location update from geolocator, which I believe is not a good thing as far as performance is considered. I hope for a better fix.

**Comment by matthew-carroll** [comment]
@dark-chocolate when the following commit rolls into master, please try again and see if the problem is resolved.

https://github.com/flutter/engine/commit/68bd4f2c6479c19a4e4af6574db45900fcade346

**Comment by nieben** [comment]
is this bug fixed in beta or dev channel?

**Comment by dark-chocolate** [comment]
@nieben it is not fixed in either of them, I am on dev channel running `v1.5.8`, will have to wait more!

**Comment by nieben** [comment]
> @nieben it is not fixed in either of them, I am on dev channel running `v1.5.8`, will have to wait more!

oh, thanks!

**Comment by jp1017** [comment]
@matthew-carroll Problem still exsits. https://github.com/flutter/flutter/issues/33511 with flutter version 1.10.15

**Comment by amreniouinnovent** [comment]
Still in Flutter 1.12 hotfix 5

**Comment by nailgilaziev** [comment]
I meet this error when trying to destroy pre-warmed engine. [Add2App]
`flutterEngine.destroy();`

* I pre-warm engine;
* open and close flutter activity several times. 
* but when I need to  switch user in my host app, I need to destroy this pre-warmed engine too, because executed content not related to new user. 

`Flutter (Channel master, v1.14.4-pre.17, on Mac OS X 10.15.2 19C57, locale en-RU)`

**Comment by sanekyy** [comment]
Problem still reproduce

```
Flutter 1.14.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (8 days ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

![image](https://user-images.githubusercontent.com/18647037/73830080-1611cd80-4815-11ea-84ce-42d3dd0ee26a.png)

**Comment by TAMILSELVAN943** [comment]
![](https://files.slack.com/files-pri/T15LJA3QV-FTKAW20A1/screenshot_20200205-115123.jpg)

**Comment by TAMILSELVAN943** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/59245291/73842622-ef6a8b80-4842-11ea-8b9b-3c2cd3439cad.png)
Why this error comes

**Comment by TAMILSELVAN943** [comment]
![Screenshot_20200205-115123](https://user-images.githubusercontent.com/59245291/73842717-22148400-4843-11ea-83d3-9e1cfdf5bb33.jpg)
Why this Crash comes

**Comment by mosil** [comment]
Here same problem

![螢幕快照 2020-02-07 下午1 49 36](https://user-images.githubusercontent.com/1974459/74004432-b4866600-49b0-11ea-8489-5b3fbdb55d87.png)

**Comment by mustafabhatkar** [comment]
Yep facing the same issue on Oneplus 5 running Android 9

**Comment by shinayser** [comment]
I jsut started facing this issue now with Android 10. It started to happen because I migrated my project to Android V2 binding, but I have no idea how to workaround that.

Any idea?

**Comment by KrishnaPravin** [comment]
We are using firebase_messaging_plugin.
FlutterJNI is properly attached for the first time when the app is opened or when the app is force stopped and opened.
But FlutterJNI is not attaching to the platform when the app is resumed after
  1. The app is minimized using either back or home button/gesture
  2. The app cleared from the recent apps tray

Background messages are received properly when the app goes to the background for the first time.
Due to this issue when the app goes to the background for the second time onwards background messages are not received.

I guess there is a problem is removing the FlutterJNI and reattaching it to the platform.

**Comment by mustafabhatkar** [comment]
any fix for this?

**Comment by kw2019ltd** [comment]
Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
       at io.flutter.embedding.engine.FlutterJNI.setSemanticsEnabled(FlutterJNI.java:513)
       at io.flutter.embedding.engine.systemchannels.AccessibilityChannel.onAndroidAccessibilityDisabled(AccessibilityChannel.java:110)
       at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:291)
       at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1157)
       at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(:4)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by abdulllrashid** [comment]
I'm also facing this issue while using flutter webview plugin


![Screenshot 2020-03-10 at 12 03 14 PM](https://user-images.githubusercontent.com/28691569/76286163-61f9db80-62c7-11ea-8998-f2f631520197.png)

**Comment by pamir72** [comment]
[android] on "app exit" : Runtime exception at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative #48063

**Comment by PotholeProject** [comment]
I am also facing the same issue and I don't see any solution for the issue. Why is the issue closed?

**Comment by kw2019ltd** [comment]
It should be opened

**Comment by A7medMaher** [comment]
Same issue here  :(
W/FlutterJNI(12708): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/firebase_auth. Response ID: 0

**Comment by mathias22osterhagen22** [comment]
Same issue for me too.
I'm using the package: https://pub.dev/packages/admob_flutter
To press the return button to close the app while an advertising banner is on screen make crash the app with the same log as above.

**Comment by FacuRossi** [comment]
same issue. using the camera plugin.
the devices are samsung and xiaomi. 
![image](https://user-images.githubusercontent.com/21088004/78939777-20f21400-7a8b-11ea-9a5e-f28a5d901bc7.png)

**Comment by zahidshaikh08** [comment]
> Same issue for me too.
> I'm using the package: https://pub.dev/packages/admob_flutter
> To press the return button to close the app while an advertising banner is on screen make crash the app with the same log as above.

same issue brother...

**Comment by DevMattM** [comment]
I am experiencing this problem as well running a Flutter app with Google Maps, Firestore, geolocation, and admob plugins.

    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by trgan96** [comment]
hi @matthew-carroll , I have the same problem. I configured the back button :
              - no history: main activity will finish (call finish() method.).
After that I reopend the app => the app crashed. 

I received a FATAL EXCEPTION:
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7212)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)

**Comment by xster** [comment]
Looks like a collection of different issues going on here. Looking at a couple of the stack traces, they generally look like our engine code not thoroughly cleaning up callbacks when FlutterEngine.destroy -> flutterJNI.detachFromNativeAndReleaseResources is called. When those callbacks come back after the engine is destroyed it crashes. 

@GaryQian would you like to make a comb on our engine code to clean up some of these dangling callbacks? The various stack traces above should offer hints on all the remaining handles.

**Comment by kw2019ltd** [comment]
hi
getting below issue with Flutter (Channel unknown, v1.17.1)


Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
       at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

image

$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
• Flutter version 1.17.1 at /home/cirrus/sdks/flutter
• Framework revision f7a6a79 (3 days ago), 2020-05-12 18:39:00 -0700
• Engine revision 6bc433c6b6
• Dart version 2.8.2
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /opt/android-sdk-linux
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
! No devices available
! Doctor found issues in 3 categories

**Comment by pacifio** [comment]
same issue with the flutter connectivity plugin
```bash
W/FlutterJNI(10176): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/connectivity_status. Response ID: 0
```

**Comment by singun-lxd** [comment]
same issue with v1.17.2

**Comment by StevenKek** [comment]
Same issue with 1.17.3, using [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) and [connectivity](https://pub.dev/packages/connectivity) plugins.

Stack trace:
`E/AndroidRuntime( 2950): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime( 2950): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
E/AndroidRuntime( 2950): 	at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
E/AndroidRuntime( 2950): 	at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
E/AndroidRuntime( 2950): 	at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
E/AndroidRuntime( 2950): 	at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
E/AndroidRuntime( 2950): 	at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:209)
E/AndroidRuntime( 2950): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime( 2950): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime( 2950): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
E/AndroidRuntime( 2950): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2950): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime( 2950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
`

**Comment by PhloxDev** [comment]
I have same problem when using mapbox_gl and flutter version 1.17.4 in debug mode not in release mode.

**Comment by YuriOliveiraAbel** [comment]
same issue with v1.17.4, detected on dashboard in play store

**Comment by prakharb10** [comment]
The same issue in v1.17.4, app crashes on pressing the back button, using similar dependencies, as mentioned in earlier comments.

**Comment by CristianDRM** [comment]
I have the same issue by pressing the back button.

**Comment by zengbo88** [comment]
> Same issue with 1.17.3, using [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview), [firebase_remote_config](https://pub.dev/packages/firebase_remote_config) and [connectivity](https://pub.dev/packages/connectivity) plugins.
> 
> Stack trace:
> `E/AndroidRuntime( 2950): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native. E/AndroidRuntime( 2950): at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141) E/AndroidRuntime( 2950): at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:209) E/AndroidRuntime( 2950): at android.os.Handler.dispatchMessage(Handler.java:108) E/AndroidRuntime( 2950): at android.os.Looper.loop(Looper.java:166) E/AndroidRuntime( 2950): at android.app.ActivityThread.main(ActivityThread.java:7425) E/AndroidRuntime( 2950): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime( 2950): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) E/AndroidRuntime( 2950): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) `

Hello, did you resolve this issue. I met the same issue when using InAppWebView.

**Comment by StepanMynarik** [comment]
> 
> 
> > Same issue with 1.17.3, using [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview), [firebase_remote_config](https://pub.dev/packages/firebase_remote_config) and [connectivity](https://pub.dev/packages/connectivity) plugins.
> > Stack trace:
> > `E/AndroidRuntime( 2950): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native. E/AndroidRuntime( 2950): at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35) E/AndroidRuntime( 2950): at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141) E/AndroidRuntime( 2950): at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:209) E/AndroidRuntime( 2950): at android.os.Handler.dispatchMessage(Handler.java:108) E/AndroidRuntime( 2950): at android.os.Looper.loop(Looper.java:166) E/AndroidRuntime( 2950): at android.app.ActivityThread.main(ActivityThread.java:7425) E/AndroidRuntime( 2950): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime( 2950): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) E/AndroidRuntime( 2950): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) `
> 
> Hello, did you resolve this issue. I met the same issue when using InAppWebView.

Nope, just waiting for the official fix.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/19558 Has landed, those with the `markTextureFrameAvailable` version of this crash, can you please verify the fix? The change is on master channel.

**Comment by GaryQian** [comment]
After a quick read through this issue, there have been 3 different crashes and 3 different fixes. It seems that the `markTextureFrameAsAvailable` one is the last of the remaining crashes, and if confirmed resolved, I think we can (re)close this issue.

**Comment by GaryQian** [comment]
Actually, the fix has not yet rolled into master, the roll seems to be slightly backed up. Will post here when it is available.

**Comment by GaryQian** [comment]
flutter/engine#19558 has rolled into master. Should be ready for trying out now.

**Comment by markfili** [comment]
I'm still experiencing this issue:
```
Flutter 1.20.0-8.0.pre.125 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9c4a5ef1ed (10 hours ago) • 2020-07-15 21:41:27 +0100
Engine • revision 774ae0313d
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-8.0.pre.125, on Mac OS X 10.15.5 19F101, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```
I can sometimes reproduce the "FlutterJNI was detached" message by just pressing back from the screen which triggered communication with the native side, like the `sensors` package, and backing up until the app is sent to the background, then the message would appear.

**Comment by guilhermeagostinelli** [comment]
Thanks @GaryQian ! I'm not getting the RuntimeException anymore, but if I re-open the app and navigate back from a specific page, I get a

`Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/cloud_firestore. Response ID: 0`

$ flutter doctor -v:
```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.125, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-8.0.pre.125 at /home/guilherme/Downloads/flutter
    • Framework revision 9c4a5ef1ed (16 hours ago), 2020-07-15 21:41:27 +0100
    • Engine revision 774ae0313d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/guilherme/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/guilherme/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/guilherme/Downloads/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by GaryQian** [comment]
Is this causing any unexpected behavior? This warning was introduced in flutter/engine#8170 which fixed the platform message version of this bug and should just reflect the detached JNI state.

**Comment by GaryQian** [comment]
@markfili Can you try a `flutter upgrade` before trying again? It looks like your revision was from 10hrs ago from when you posted, which may not include the necessary changes.

**Comment by guilhermeagostinelli** [comment]
> Is this causing any unexpected behavior? This warning was introduced in flutter/engine#8170 which fixed the platform message version of this bug and should just reflect the detached JNI state.

Apparently not ;) Thanks for the clarification!

**Comment by GaryQian** [comment]
It looks like the 3 version of this bug reported here all have appropriate fixes, I will close this bug for now, please feel free to comment with any additional issues anyone sees regarding this and we can re-open.

**Comment by NathanO14** [comment]
When can we expect this to be made available in the stable channel?

**Comment by GaryQian** [comment]
Generally, stable releases are quarterly and beta releases are monthly. I don't have an immediate release date, but you can generally add a few months to the previous stable release. This is probably not hotfix worthy, but if enough people want it as a hot fix, we can consider it.

In the meantime, the change should soon be available on dev and master channels, and we welcome you to try it there.

**Comment by fadrizul** [comment]
@GaryQian What is the process to request a hotfix? Our users are experiencing crashes using our app https://play.google.com/store/apps/details?id=com.grab.merchant&hl=en and it is affected their businesses in terms of revenue generation.

**Comment by GaryQian** [comment]
@edeortuzar you need to try this on master channel. It has not made it to stable yet.

**Comment by GaryQian** [comment]
@fadrizul I will submit this for hotfix consideration

**Comment by MrLittleStrong** [comment]
> @fadrizul I will submit this for hotfix consideration

What version will the next stable be? and when will there be a new stable? I've seen 1.18,1.19.1.20 on beta for a long time. 1.18 for more than 2 months. still not been made to stable. I'm a little confused.

**Comment by BeshoyAdelHemaya** [comment]
@GaryQian any new updates from your side because the issue affected our users

**Comment by BeshoyAdelHemaya** [comment]
This issue happened with me when i displayed an Interstitial Ads and while press back to close the App, the crash happened on background. So i disposed the Ad and this issue didn't happen. I published a new release but still this issue happened so may be something like Interstitial behavior caused the issue. any support ????

**Comment by kw2019ltd** [comment]
still happened also on flutter 1.20

**Comment by lukaszciastko** [comment]
Why is this issue closed? I'm experiencing this bug on Android 10+ with the latest Flutter 1.20.1 (stable).

**Comment by sanekyy** [comment]
Same issue

**Comment by mwolffalonso** [comment]
Same here, but the weird thing is that it is just happening in release build not in debug build.

It looks related to AudioService Plugin after stopping the service

`2020-08-12 15:05:34.072 2494-7425/? D/AudioService: setBluetoothA2dpOn false
2020-08-12 15:05:34.073 2494-3287/? D/AudioSystem-JNI: setForceUse (1,10)
2020-08-12 15:05:34.073 2246-2246/? D/APM_AudioPolicyManager: setForceUse() usage 1, config 10, mPhoneState 0
2020-08-12 15:05:34.085 25992-25992/? W/FlutterJNI: Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 19
2020-08-12 15:05:34.085 25992-25992/? D/AndroidRuntime: Shutting down VM
2020-08-12 15:05:34.086 25992-25992/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mtheorysoft.twitterapitabbed, PID: 25992
    java.lang.NullPointerException: Attempt to invoke virtual method 'void d.a.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
        at c.g.a.a$d.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

**Comment by mwolffalonso** [comment]
Sorry, my issue was related to Audio_Service interaction with Flutter_tts plugins. I solved the problem following the following instructions:

https://github.com/dlutton/flutter_tts/issues/149#issue-674593278

**Comment by indev-aj** [comment]
is this problem fixed? i'm getting `Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/firebase_database` when pressing the back button to exit from the app.

**Comment by yusufnacar** [comment]
I am facing same issue. I am using Google Maps and Location plugins. When I open the screen that get user location, everything is working fine. But when I close the app through pressing back button and start again , I am getting a warning message every second and I think that  it is not a good thing as far as performance and battery drain. 

Here my flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.165, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

• No issues found!
yusufnacar@yusufs-mbp ~ % flutter doctor - v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-8.0.pre.165, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

• No issues found!
```



And it is the message which I am facing every second 


```
W/FlutterJNI( 4383): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: lyokone/locationstream. Response ID: 0

```

**Comment by mwolffalonso** [comment]
Maybe you need to close the reference to the Location or Map API somehow.
Or put a completer to check that the status of the API reference is correct when the back button is pressed and if not await to be complete.

⁣Gracias,
Saludos,
Martin.​

**Comment by yurisasc** [comment]
I'm having the same issue as well, for me it affects the [Quickblox package](https://pub.dev/packages/quickblox_sdk). What's the status of the hotfix?

```
W/FlutterJNI( 9071): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: FlutterQBChatChannel/RECEIVED_NEW_MESSAGE. Response ID: 0
```

**Comment by micodev** [comment]
```W/FlutterJNI( 3517): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 9```
same here using ```pusher_client```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale ar-IQ)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by RashidaBegamShaik** [comment]
https://github.com/flutter/flutter/issues/28651#issuecomment-744396559
am also facing the same issue, when I clear the app from background,  am getting this message and then QuickBlox services has been stopped after this message

**Comment by mikeborodin** [comment]
Same issue here. For me it happens when using just_audio and firebase_auth 
`W/FlutterJNI(20011): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 45`

**Comment by CaoGiaHieu-dev** [comment]
i got same error on package adhara_socket_io

"W/FlutterJNI(20116): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: adhara_socket_io:event_streams#6. Response ID: 0"

**Comment by JunaidHaneef** [comment]
package com.gogappi.consumer

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

**Comment by albrewot** [comment]
Same issue here using "camera" plugin

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [VersiÃ³n 10.0.10586], locale es-VE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] VS Code, 64-bit edition (version 1.55.2)
[√] Proxy Configuration
[√] Connected device (2 available)

• No issues found!

**Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter.io/cameraPlugin/device. Response ID: 0**
