### ISSUE TITLE
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()

### ISSUE THREAD

**Issue by Huyamin150** [flutter/flutter#28713]
## Logs

WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: app

### **### And when i run "-Pandroid.debug.obsoleteApi=true" command, i got logs below:**

WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: /Users/nickhu/Documents/WorkSpace/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle:441
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.
WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: /Users/nickhu/Documents/WorkSpace/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle:441
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: /Users/nickhu/Documents/WorkSpace/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle:441
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.

-------------------------------Flutter doctor -v-------------------------------------------

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/nickhu/Documents/WorkSpace/Flutter/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nickhu/Documents/WorkSpace/AndroidSdk
    • Android NDK at /Users/nickhu/Documents/WorkSpace/AndroidSdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/nickhu/Documents/WorkSpace/AndroidSdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • ONEPLUS A6000 • 49bb105f • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by bradyt** [comment]
```
$ gradle assembleRelease -Pandroid.debug.obsoleteApi=true

> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: /Users/iam/opt/flutter/packages/flutter_tools/gradle/flutter.gradle:424
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: /Users/iam/opt/flutter/packages/flutter_tools/gradle/flutter.gradle:446
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.

> Task :app:lintVitalRelease
Calling mockable JAR artifact transform to create file: /Users/iam/.gradle/caches/transforms-2/files-2.1/b1b48f0b00fdc1af31e32f95985f8201/android.jar with input /Users/iam/Library/Android/sdk/platforms/android-27/android.jar
Calling mockable JAR artifact transform to create file: /Users/iam/.gradle/caches/transforms-2/files-2.1/c8a57a01356eacbf0f602db1177d88a3/android.jar with input /Users/iam/Library/Android/sdk/platforms/android-28/android.jar
/Users/iam/opt/flutter/bin/cache/artifacts/engine/android-arm-release/flutter.jar: D8: Type `android.support.v4.app.FragmentActivity` was not found, it is required for default or static interface methods desugaring of `void io.flutter.app.FlutterFragmentActivity.onCreate(android.os.Bundle)79 actionable tasks: 79 executed
```

**Comment by rmtmckenzie** [comment]
This looks to be a duplicate of #28318. Also, it appears to have previously been fixed then reverted (see #26544).

**Comment by exts** [comment]
To temporarily fix this issue, revert gradle back to 3.2.1, seems like there's some incompatibilities with 3.4 atm

**Comment by iftee939** [comment]
I got this issue with Gradle version 3.4.1

**Comment by GvOscar** [comment]
Lo solucione de la siguiente manera:

1. Migre el proyecto a AndroidX
2. Actualice butterknife a 10.1.0
3 No incluyan  
apply plugin: 'com.android.library' 
apply plugin: 'com.jakewharton.butterknife'
4. Baje la version a 3.2.1
5 Volvi a subir a la version 3.4.1
6 Sincronice el proyecto con archivos de Gradle

**Comment by Iampato** [comment]
> 
> 
> I got this issue with Gradle version 3.4.1
 change to 3.4.0 works like a charm

**Comment by phanirithvij** [comment]
Is this fixed in `1.7.8+hotfix.3` i.e. the current stable release?

**Comment by guzishiwo** [comment]
> Is this fixed in `1.7.8+hotfix.3` i.e. the current stable release?
This problem still exists

**Comment by fauzipadlaw** [comment]
This problem still exists

**Comment by nogicoder** [comment]
Still exists guys. Please take a look!

**Comment by Jayant11** [comment]
Not solved yet

**Comment by Jayant11** [comment]
Stable gradle version-
• Gradle plugin - `3.4.2`
• Gradle version - `https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`

Using version `3.5.0` shows these API warnings for me.
Hope it helps!

**Comment by momoDragon** [comment]
> Stable gradle version-
> • Gradle plugin - `3.4.2`
> • Gradle version - `https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`
> 
> Using version `3.5.0` shows these API warnings for me.
> Hope it helps!

Dosent work for me :/

**Comment by Jayant11** [comment]
> > Stable gradle version-
> > • Gradle plugin - `3.4.2`
> > • Gradle version - `https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`
> > Using version `3.5.0` shows these API warnings for me.
> > Hope it helps!
> 
> Dosent work for me :/

Can you share your Gradle configuration and the error shown?
I can try to reproduce the issue and test

**Comment by momoDragon** [comment]
> > > Stable gradle version-
> > > • Gradle plugin - `3.4.2`
> > > • Gradle version - `https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`
> > > Using version `3.5.0` shows these API warnings for me.
> > > Hope it helps!
> > 
> > 
> > Dosent work for me :/
> 
> Can you share your Gradle configuration and the error shown?
> I can try to reproduce the issue and test
I think the error for me was coming from other packages?
i ran this in terminal to refetch all the plugins:
flutter pub pub cache repair
And after that the errors went away

**Comment by momoDragon** [comment]
> > > Stable gradle version-
> > > • Gradle plugin - `3.4.2`
> > > • Gradle version - `https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`
> > > Using version `3.5.0` shows these API warnings for me.
> > > Hope it helps!
> > 
> > 
> > Dosent work for me :/
> 
> Can you share your Gradle configuration and the error shown?
> I can try to reproduce the issue and test

I think the error for me was coming from other packages?
i ran this in terminal to refetch all the plugins:
flutter pub pub cache repair
And after that the errors went away

**Comment by Huyamin150** [comment]
issue fixed in 1.7.8
Gradle version:4.6

**Comment by nohli** [comment]
I've just updated to the latest Gradle and Plugin version and the issue still persists.
https://developer.android.com/studio/releases/gradle-plugin

Are you suggesting using a Gradle version which is one year old to 'fix' the warnings (which occur with newer versions)?

**Comment by Huyamin150** [comment]
> I've just updated to the latest Gradle and Plugin version and the issue still persists.
> https://developer.android.com/studio/releases/gradle-plugin
> 
> Are you suggesting using a Gradle version which is one year old to 'fix' the warnings (which occur with newer versions)?

nope, but I never try it in the latest Gradle version, so I can't give you a valuable suggestion in your condition. I think maybe not the Gradle's issue, try to upgrade flutter. My Gradle version always 4.6 but it's working now after upgrading my flutter

**Comment by nohli** [comment]
So, when working with a one-year-old gradle, it doesn't say that the API is obsolete (probably wasn't back then)...but when using the latest gradle, it complains about it being obsolete.

It doesn't seem fixed.

My Flutter is always the latest and 'flutter pub pub cache repair' didn't work.
Also, I get two warnings - the one in the title and another obsolete API.

If anyone has a different solution, please tell us :)

**Comment by san7dhl** [comment]
Step 1: Migrate to Android X

Step 2: In Android Studio Go to File->Project Structure
Android Gradle Plugin: 3.2.1
Gradle Version: 4.10.2

This solved the problem for me

**Comment by smourier** [comment]
FWIW, the changes are commited for some weeks now, read here: https://github.com/flutter/flutter/commit/407668f4d51b5ecb4c12a434769954e293fc68dc#diff-d9b052388990c36138e397b5bb529025 but this is labeled 1.10, so it will only be available for flutter 1.10 so you can either switch to flutter **beta** or **dev** channel, or wait for 1.10 to reach **stable** channel : https://flutter.dev/docs/development/tools/sdk/releases (or keep using an old Gradle of course)

**Comment by emadsoliman25** [comment]
change Gradle version to 3.4.0  and replace distributionUrl in  gradle-wrapper.properties file in wrapper directory to 
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
