### ISSUE TITLE
When double clicked on button , from page CupertinoNavigationBar is disappear！

### ISSUE THREAD

**Issue by hbsion** [flutter/flutter#28768]
## Steps to Reproduce

**Forgive me!
My English is very poor, so  I use Chinese description this bug.**

项目是官方给出的"flutter_gallery"
进入项目更目录后运行 

`flutter run`

1. 打开APP进入到Cupertino > Navigation
2. 随便点击一个色块后，用手势返回。
3. 快速再次点击一下色块，就会出来如下logs
4. 如果不出现logs，重复2->3->2->2->3...

猜测原因：手势返回后Router中动画未完成，点击了Navigation.of(context).push(...)导致的。

This is “flutter run —release” on iOS screen
https://youtu.be/jWtQhmK2Hyo

## Logs

```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on MI 5X is available at: http://127.0.0.1:50254/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
I/zygote64(13160): Do partial code cache collection, code=29KB, data=20KB
I/zygote64(13160): After code cache collection, code=29KB, data=20KB
I/zygote64(13160): Increasing code cache capacity to 128KB
I/zygote64(13160): Do partial code cache collection, code=61KB, data=45KB
I/zygote64(13160): After code cache collection, code=61KB, data=45KB
I/zygote64(13160): Increasing code cache capacity to 256KB
I/flutter (13160): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13160): The following assertion was thrown during a scheduler callback:
I/flutter (13160): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 485 pos 14: 'manifest.toHero ==
I/flutter (13160): newManifest.fromHero': is not true.
I/flutter (13160): 
I/flutter (13160): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13160): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13160): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13160):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13160): 
I/flutter (13160): When the exception was thrown, this was the stack:
I/flutter (13160): #2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:485:14)
I/flutter (13160): #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:682:25)
I/flutter (13160): #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:630:11)
I/flutter (13160): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13160): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter (13160): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (13160): #11     _invoke (dart:ui/hooks.dart:189:10)
I/flutter (13160): #12     _drawFrame (dart:ui/hooks.dart:162:3)
I/flutter (13160): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (13160): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (13160): Another exception was thrown: Cannot reuse a CupertinoPageRoute<void> after disposing it.
```

```
➜  flutter_gallery git:(06b979c4d) flutter doctor -v                                      
[✓] Flutter (Channel unknown, v1.2.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.0 at /Users/hbsion/dev/flutter
    • Framework revision 06b979c4d5 (5 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hbsion/Library/Android/sdk
    • Android NDK at /Users/hbsion/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/hbsion/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • MI 5X • becf9bc50504 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by John251314** [comment]
I have the same issues.

**Comment by xster** [comment]
Assigning to @LongCatIsLooong to double check but I suspect we already fixed this

**Comment by LongCatIsLooong** [comment]
@xster tested on [master](9022d9f48) on ios, unfortunately the `toHero != fromHero` issue still persists. Wasn't able to reproduce `Cannot reuse a CupertinoPageRoute<void> after disposing it.` Looking into it.

**Comment by xster** [comment]
Thanks

**Comment by LongCatIsLooong** [comment]
No longer reproducible on master(4ff467191b13da6bdb3e0a9420c1d2b487176ed4), closing. @hbsion @John251314 if you are still having this issue on master, feel free to reopen.
