### ISSUE TITLE
SliverAppBar's flexibleSpace glitch on iOS when NestedScrollView's body is a ScrollView

### ISSUE THREAD

**Issue by hendricgc** [flutter/flutter#29264]
## Steps to Reproduce

Basically, when creating an application with a `SliverAppBar` inside a `NestedScrollView`, a scrolling glitch is performed **only on iOS** if you scroll down and then scroll up before the bouncing animation ends. On Android it does not happen.
Noticed that it happens when the body of the `NestedScrollView` is an implementation of `ScrollView`.

Demo:

![sliverappbarglitch](https://user-images.githubusercontent.com/20709746/54244468-87fd6c00-450b-11e9-9bf2-bb89b47e6bcc.gif)

Example code (simplified code from the demo):

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  TabController _tabController;
  ScrollController _scrollViewController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: 2);
    _scrollViewController = ScrollController(initialScrollOffset: 0.0);
  }

  @override
  void dispose() {
    _tabController.dispose();
    _scrollViewController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        controller: _scrollViewController,
        headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 300.0,
              title: Text('Tab Controller Example'),
              pinned: true,
              floating: true,
              forceElevated: boxIsScrolled,
            )
          ];
        },
        body: PageOne(),
      ),
    );
  }
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemExtent: 250.0,
      itemBuilder: (context, index) => Container(
            padding: EdgeInsets.all(10.0),
            child: Material(
              elevation: 4.0,
              borderRadius: BorderRadius.circular(5.0),
              color: index % 2 == 0 ? Colors.cyan : Colors.deepOrange,
              child: Center(
                child: Text(index.toString()),
              ),
            ),
          ),
    );
  }
}
```

Is there any workaround to make it work properly? Is this a framework bug? I ask that because almost every example code of this functionality is like the example above.

Thank you!

## Logs

Flutter doctor:
```
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.13.6 17G3025, locale pt-BR)
    • Flutter version 1.2.1 at /Users/hendricgc/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hendricgc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone 8                  • 24F06D4E-0628-4529-93A4-D2C16A67C4F6 • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by RusKryzhanovskiy** [comment]
I have the same problem, waiting for a decision. Thank you in advance.

**Comment by yadaniyil** [comment]
You can use `physics: ClampingScrollPhysics()` inside `NestedScrollView` or `CustomScrollView` to change scrolling behavior to android-like. This is not the proper fix but at least this will make slivers usable on iOS.

**Comment by x4080** [comment]
I got this problem too, hopefully there's a fix

**Comment by chloe722** [comment]
I got this problem too

**Comment by kongo2002** [comment]
Yes, same problem here - using `ClampingScrollPhysics()` in the `NestedScrollView` does not help either.

**Comment by nkrietenbrink** [comment]
I have the same problem. ClampingScrollPhysics is also no help for me.

**Comment by p02diada** [comment]
I have the same problem. ClampingScrollPhysics is also no help for me.

**Comment by Kiruel** [comment]
Same problem so I can't use the driver test for iOS because I have this widget.

**Comment by Klabauterman** [comment]
I have the same problem. Setting ClampingScrollPhysics on the CustomScrollView prevents the bug from appearing, but it does not feel right on iOS.

**Comment by FernandoUFS** [comment]
I am facing the same problem here. Using ClampingScrollPhysics on ListView.builder solved to me (on NestedScrollView it not worked). But I agree that is not the proper solution, since I need the iOS physics on the list.

`[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale pt-BR)`

**Comment by sunyatax** [comment]
ClampingScrollPhysics() doesn't work. @Hixie - any help you can provide here? Thanks.

**Comment by Piinks** [comment]
I've distilled the provided reproduction and confirmed on master:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                expandedHeight: 300.0,
                title: Text('Demo'),
              )
            ];
          },
          body: ListView.builder(
            itemExtent: 250.0,
            itemBuilder: (context, index) => Container(
              child: Center(child: Text(index.toString()))
            )
          )
        ),
      ),
    );
  }
}

```

**Comment by x4080** [comment]
@Piinks Is it fixed now ?

**Comment by Piinks** [comment]
No, I have confirmed it is currently reproducing on master.

**Comment by x4080** [comment]
@Piinks Cool, wait for the fix then. Cheers

**Comment by RoryHyman** [comment]
Waiting for the fix. Cheers

**Comment by benzsuankularb** [comment]
I think this happened to every ScrollView. Not only NestedScrollView

If you drag down until and the end of spring when you drag up quickly,

After you release the finger ScrollView will try to animate the scroll position to zero.

I think it's the case to make NestedScrollView be like this.

**Comment by telinx** [comment]
facing the same problem

**Comment by telinx** [comment]
I found a solution that might work：

NestedScrollView add ScrollController1
CustomScrollView add ScrollController2
Bind Listen to ScrollController2
eg:
``` 
// add _scrollController1 _scrollController2
NestedScrollView(
  physics: NeverScrollableScrollPhysics(),
  controller: this._scrollController1,
  headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
    return <Widget>[
       SliverPersistentHeader(
         floating: false,
         pinned: false,
         delegate: SliverAppBarDelegate(
           minHeight: AppConfig.trendHeaderImageHeight,
           maxHeight: AppConfig.trendHeaderImageHeight,
           child: trendingHeader,
         )
       )
    ];
  },
  body: CustomScrollView(
    controller: this._scrollController2
	...
  ),
);


// initState bind listen
WidgetsBinding.instance.addPostFrameCallback((_) {
  this._scrollController2.addListener(() {
    double offset = this. _scrollController2.offset;
    if(offset <= AppConfig.trendHeaderImageHeight){
       _scrollController1.jumpTo(offset);
    }else if(offset > AppConfig.trendHeaderImageHeight && widget.scrollController.offset < AppConfig.trendHeaderImageHeight){
       _scrollController1.jumpTo(AppConfig.trendHeaderImageHeight);
    }
    // ScrollDirection direction = this.listViewController.position.userScrollDirection;
  });
});

```

**Comment by jaddoescad** [comment]
any solutions?

**Comment by filiph** [comment]
@HansMuller Is this really a performance issue? It looks more like a glitch to me. Even if the underlying issue is performance, from the user's perspective, it seems more critical.

**Comment by NicolasCELLA** [comment]
Did you have any solutions to propose? It's a real problem in many of the projects I work with |

**Comment by hasanzia1993** [comment]
Going through the same problem. Hoping a fix is released soon

**Comment by tedhenry100** [comment]
I found success with the same workaround as @FernandoUFS. It is adding `ClampingScrollPhysics` on `ListView.builder` that works. Adding the same to `NestedScrollView` does not help.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool isScrolled) {
            return [
              SliverAppBar(
                pinned: true,
                floating: true,
                expandedHeight: 200,
                title: Text("Tab Bouncing Problem"),
                flexibleSpace: FlexibleSpaceBar(),
                bottom: TabBar(
                  tabs: [
                    Tab(text: "One"),
                    Tab(text: "Two"),
                    Tab(text: "Three"),
                  ],
                ),
              ),
            ];
          },
          body: TabBarView(
            children: [
              MyTabContainer(),
              MyTabContainer(),
              MyTabContainer(),
            ],
          ),
        ),
      ),
    );
  }
}

class MyTabContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      physics: ClampingScrollPhysics(), // *** THIS IS THE FIX ***
      itemBuilder: (BuildContext context, int index) {
        return ListTile(
          title: Text("Item: $index"),
        );
      },
    );
  }
}
```

**Comment by romanlytvyn** [comment]
Does anyone have any clue when this might be addressed? It's been open for almost a year now.
`SliverAppBar` is totally unusable like this.

Meanwhile, is there anything we could try to workaround this issue while retaining the bouncing physics?

**Comment by fullstack-cliffex** [comment]
@hendricgc  Add  `physics: ClampingScrollPhysics()` in ListView.builder of Pageone.

**Comment by telinx** [comment]
use [extended_nested_scroll_view](https://pub.flutter-io.cn/packages/extended_nested_scroll_view), this plugin is okay.

**Comment by Piinks** [comment]
I believe I have a fix for this. See #55069. 
The SliverAppBar in the original reproduction above is a floating app bar. #55069 is intended to fix the overscroll issue. The floating issue is being tracked in #17518, with a fix to follow soon there too. :)
Feedback always welcome.

**Comment by dprodoomoolmori** [comment]
What's the recommended flutter channel for this fix? I know that the recent "master, 1.19.0-2.0.pre.145" has the fix but I don't want to use it for my product since it's not stable.
Please suggest the best practice @Piinks

**Comment by Piinks** [comment]
Hi @dprodoomoolmori,

> 1. Do you know when this fix will be merged to stable channel? I know that the recent "master, 1.19.0-2.0.pre.145" has the fix but I don't want to use it for my product since it's not stable. I did copy/paste nested_scroll_view.dart for now.

I don't know an exact date when it will reach stable, but our wiki provides guidance on [our release process](https://github.com/flutter/flutter/wiki/Release-process#rolling-the-stable-channel).

> 2. In my product, there is still an issue that when scroll on NestedScrollView widget, the SingleChildScrollView inside a TabBarView is also scrolling. I can send the recorded video of it if you need. Can I request for this issue?

I would file a separate issue for this with a minimal code reproduction of the behavior you are experiencing.

**Comment by Piinks** [comment]
Update on the milestone here: As mentioned above, the UI glitch has been fixed, but the floating portion of the reproduction is outstanding (related issue: #17518). There is a PR open to close both issues (#57707), it is still going back and forth in review, anticipated to land soon. I have moved the milestone to June to remove from the overdue heap.

**Comment by peerwaya** [comment]
@Piinks  this issue still happens, noticed it in Flutter Channel master, 1.24.0-4.0.pre.106.

![RPReplay-Final1604012713](https://user-images.githubusercontent.com/14053870/97641868-338e6380-1a44-11eb-88f9-b2e760415bb9.gif)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-4.0.pre.106, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.0)
[✓] Connected device (5 available)

**Comment by habibshaban** [comment]
> Hi @Piinks, Thank you so much for fixing this issue. I'm very happy about it. And I've got two concerns. Please consider those as feedback/request.
> 
> 1. Do you know when this fix will be merged to stable channel? I know that the recent "master, 1.19.0-2.0.pre.145" has the fix but I don't want to use it for my product since it's not stable. I did copy/paste nested_scroll_view.dart for now.
> 2. In my product, there is still an issue that when scroll on NestedScrollView widget, the SingleChildScrollView inside a TabBarView is also scrolling. I can send the recorded video of it if you need. Can I request for this issue?

did you find any solution for this?

**Comment by sulaiman-mlbd** [comment]
Still facing this issue? Any update ? 
`Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
`
