### ISSUE TITLE
Suddenly getting "Default activity not found" when "flutter run"

### ISSUE THREAD

**Issue by marianoarga** [flutter/flutter#29335]
I'm suddenly getting error when running (not any error in building) after upgrading Android Studio, never happened before and I hadn't changed anything in the code.
This happend on my MacOs High Sierra and on my office Ubuntu 14.04.
Tried reinstalling Android Studio and it didn't work.

## Steps to Reproduce

1. Upgraded Android Studio to latest version (3.3.2)
2. Run "flutter run", it fails on any device, physical or emulator, on any flavor (release, debug, profile)
3. Get the error message:
Error running com.gotyalabs.dollar. Default activity not found
Unable to read manifest info from /Users/mariano/development/apps/dolalert/build/app/outputs/apk/app.apk.
No application found for TargetPlatform.android_x86.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.

## Logs

flutter run --verbose
```
[  +25 ms] executing: [/Users/mariano/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/mariano/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Users/mariano/development/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +1 ms] executing: [/Users/mariano/development/flutter/] git log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/Users/mariano/development/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] hace 4 semanas
[        ] executing: [/Users/mariano/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +189 ms] executing: /Users/mariano/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/mariano/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ZY2247GWGL             device usb:346030080X product:potter_n model:Moto_G__5__Plus device:potter_n transport_id:4
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[   +8 ms] executing: idevice_id -h
[  +30 ms] /usr/bin/xcrun simctl list --json devices
[ +242 ms] Found plugin firebase_admob at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.8.0/
[   +2 ms] Found plugin firebase_messaging at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-3.0.0/
[   +3 ms] Found plugin flutter_inapp_purchase at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-0.9.0/
[  +27 ms] Found plugin share at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.5.3/
[   +1 ms] Found plugin shared_preferences at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +29 ms] Found plugin firebase_admob at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.8.0/
[        ] Found plugin firebase_messaging at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-3.0.0/
[   +1 ms] Found plugin flutter_inapp_purchase at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-0.9.0/
[  +17 ms] Found plugin share at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.5.3/
[   +1 ms] Found plugin shared_preferences at /Users/mariano/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +29 ms] /Users/mariano/Library/Android/sdk/platform-tools/adb -s ZY2247GWGL shell getprop
[  +84 ms] ro.hardware = qcom
[ +837 ms] Launching lib/main.dart on Moto G 5 Plus in debug mode...
[  +11 ms] Initializing gradle...
[   +4 ms] Using gradle from /Users/mariano/development/apps/dolalert/android/gradlew.
[   +5 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[  +18 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[        ] {
               CFBundleDevelopmentRegion = English;
               CFBundleDocumentTypes =     (
                           {
                       CFBundleTypeExtensions =             (
                           ipr
                       );
                       CFBundleTypeIconFile = "studio.icns";
                       CFBundleTypeName = "Android Studio Project File";
                       CFBundleTypeRole = Editor;
                   },
                           {
                       CFBundleTypeExtensions =             (
                           "*"
                       );
                       CFBundleTypeName = "All documents";
                       CFBundleTypeOSTypes =             (
                           "****"
                       );
                       CFBundleTypeRole = Editor;
                       LSTypeIsPackage = 0;
                   }
               );
               CFBundleExecutable = studio;
               CFBundleGetInfoString = "Android Studio 3.3, build AI-182.5107.16.33.5314842. Copyright JetBrains s.r.o., (c) 2000-2019";
               CFBundleIconFile = "studio.icns";
               CFBundleIdentifier = "com.google.android.studio";
               CFBundleInfoDictionaryVersion = "6.0";
               CFBundleName = "Android Studio";
               CFBundlePackageType = APPL;
               CFBundleShortVersionString = "3.3";
               CFBundleSignature = "????";
               CFBundleURLTypes =     (
                           {
                       CFBundleTypeRole = Editor;
                       CFBundleURLName = Stacktrace;
                       CFBundleURLSchemes =             (
                           idea
                       );
                   }
               );
               CFBundleVersion = "AI-182.5107.16.33.5314842";
               JVMOptions =     {
                   ClassPath =
                   "$APP_PACKAGE/Contents/lib/bootstrap.jar:$APP_PACKAGE/Contents/lib/extensions.jar:$APP_PACKAGE/Contents/lib/util.jar:$APP_PACKAGE/Contents/lib/jdom.jar:$
                   APP_PACKAGE/Contents/lib/log4j.jar:$APP_PACKAGE/Contents/lib/trove4j.jar:$APP_PACKAGE/Contents/lib/jna.jar";
                   JVMVersion = "1.8*,1.8+";
                   MainClass = "com.intellij.idea.Main";
                   Properties =         {
                       "idea.executable" = studio;
                       "idea.home.path" = "$APP_PACKAGE/Contents";
                       "idea.java.redist" = Bundled;
                       "idea.paths.selector" = "AndroidStudio3.3";
                       "idea.platform.prefix" = AndroidStudio;
                   };
                   WorkingDirectory = "$APP_PACKAGE/Contents/bin";
               };
               LSApplicationCategoryType = "public.app-category.developer-tools";
               LSArchitecturePriority =     (
                   "x86_64"
               );
               LSMinimumSystemVersion = "10.8";
               LSRequiresNativeExecution = YES;
               NSHighResolutionCapable = 1;
               NSSupportsAutomaticGraphicsSwitching = 1;
           }
[   +4 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +21 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.3
[  +62 ms] executing: /Users/mariano/development/apps/dolalert/android/gradlew -v
[ +477 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.13.6 x86_64
[   +8 ms] Initializing gradle... (completed in 0.6s)
[        ] Resolving dependencies...
[        ] executing: [/Users/mariano/development/apps/dolalert/android/] /Users/mariano/development/apps/dolalert/android/gradlew app:properties
[ +583 ms]
                    > Configure project :app
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
                    WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

                    > Task :app:properties

                    ------------------------------------------------------------
                    Project :app
                    ------------------------------------------------------------

                    INTERNAL__CHECKED_MINIMUM_PLUGIN_VERSIONS: true
                    _internalAndroidGradlePluginDependencyCheckerRegistered: true
                    allprojects: [project ':app']
                    android: com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated@3a58f82a
                    android.enableJetifier: true
                    android.useAndroidX: true
                    ant: org.gradle.api.internal.project.DefaultAntBuilder@7e64b922
                    antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@810d80e
                    archivesBaseName: app
                    artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@5cb8194a
                    asDynamicObject: DynamicObject for project ':app'
                    assemble: task ':app:assemble'
                    baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@215c335f
                    buildDir: /Users/mariano/development/apps/dolalert/build/app
                    buildFile: /Users/mariano/development/apps/dolalert/android/app/build.gradle
                    buildOutputs: BaseVariantOutput container
                    buildPath: :
                    buildScriptSource: org.gradle.groovy.scripts.TextResourceScriptSource@7a2a23ff
                    buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@74f4541c
                    childProjects: {}
                    class: class org.gradle.api.internal.project.DefaultProject_Decorated
                    classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@689a6181
                    components: SoftwareComponentInternal set
                    configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@281c6106
                    configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@3028a21
                    configurations: configuration container
                    convention: org.gradle.api.internal.plugins.DefaultConvention@55806ae9
                    copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                    copyFlutterAssetsDynamicProfile: task ':app:copyFlutterAssetsDynamicProfile'
                    copyFlutterAssetsDynamicRelease: task ':app:copyFlutterAssetsDynamicRelease'
                    copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                    copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                    createMockableJar: task ':app:createMockableJar'
                    defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@6ead8fb1
                    defaultTasks: []
                    deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@2572c733
                    dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@3236023e
                    dependencyLocking: org.gradle.internal.locking.DefaultDependencyLockingHandler_Decorated@6437e1b3
                    depth: 1
                    description: null
                    displayName: project ':app'
                    distsDir: /Users/mariano/development/apps/dolalert/build/app/distributions
                    distsDirName: distributions
                    docsDir: /Users/mariano/development/apps/dolalert/build/app/docs
                    docsDirName: docs
                    ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@66e53a83
                    extensions: org.gradle.api.internal.plugins.DefaultConvention@55806ae9
                    fileOperations: org.gradle.api.internal.file.DefaultFileOperations@559d2233
                    fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@57b8fd4c
                    flutter: FlutterExtension_Decorated@c59b471
                    flutterBuildDebug: task ':app:flutterBuildDebug'
                    flutterBuildDynamicProfile: task ':app:flutterBuildDynamicProfile'
                    flutterBuildDynamicRelease: task ':app:flutterBuildDynamicRelease'
                    flutterBuildProfile: task ':app:flutterBuildProfile'
                    flutterBuildRelease: task ':app:flutterBuildRelease'
                    flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                    googleServices: com.google.gms.googleservices.GoogleServicesPlugin$GoogleServicesPluginConfig_Decorated@4327b65b
                    gradle: build 'android'
                    group: android
                    identityPath: :app
                    inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@7f1798b6
                    java: org.gradle.api.plugins.internal.DefaultJavaPluginExtension_Decorated@6fd55885
                    layout: org.gradle.api.internal.file.DefaultProjectLayout@2e6e8332
                    libsDir: /Users/mariano/development/apps/dolalert/build/app/libs
                    libsDirName: libs
                    listenerBuildOperationDecorator: org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator@50056dca
                    logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@572c58c9
                    logging: org.gradle.internal.logging.services.DefaultLoggingManager@13149d54
                    mergeDebugAssets: task ':app:mergeDebugAssets'
                    mergeDynamicProfileAssets: task ':app:mergeDynamicProfileAssets'
                    mergeDynamicReleaseAssets: task ':app:mergeDynamicReleaseAssets'
                    mergeProfileAssets: task ':app:mergeProfileAssets'
                    mergeReleaseAssets: task ':app:mergeReleaseAssets'
                    modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@5640eec3
                    modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@12d533c8
                    module: org.gradle.api.internal.artifacts.ProjectBackedModule@d7a238e
                    name: app
                    normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@ced902a
                    objects: org.gradle.api.internal.model.DefaultObjectFactory@77fdc740
                    org.gradle.jvmargs: -Xmx1536M
                    parent: root project 'android'
                    parentIdentifier: root project 'android'
                    path: :app
                    pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@40340ad6
                    plugins: [org.gradle.api.plugins.HelpTasksPlugin@11d3c2e5, com.android.build.gradle.api.AndroidBasePlugin@71df7c35,
                    org.gradle.language.base.plugins.LifecycleBasePlugin@68816289, org.gradle.api.plugins.BasePlugin@803b7f5,
                    org.gradle.api.plugins.ReportingBasePlugin@7c888fa, org.gradle.api.plugins.JavaBasePlugin@dfc72e2, com.android.build.gradle.AppPlugin@6e0adcfe,
                    FlutterPlugin@7b2362d5, com.google.gms.googleservices.GoogleServicesPlugin@386fba13]
                    processDebugGoogleServices: task ':app:processDebugGoogleServices'
                    processDebugResources: task ':app:processDebugResources'
                    processDynamicProfileGoogleServices: task ':app:processDynamicProfileGoogleServices'
                    processDynamicProfileResources: task ':app:processDynamicProfileResources'
                    processDynamicReleaseGoogleServices: task ':app:processDynamicReleaseGoogleServices'
                    processDynamicReleaseResources: task ':app:processDynamicReleaseResources'
                    processOperations: org.gradle.api.internal.file.DefaultFileOperations@559d2233
                    processProfileGoogleServices: task ':app:processProfileGoogleServices'
                    processProfileResources: task ':app:processProfileResources'
                    processReleaseGoogleServices: task ':app:processReleaseGoogleServices'
                    processReleaseResources: task ':app:processReleaseResources'
                    project: project ':app'
                    projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@566aa49e
                    projectDir: /Users/mariano/development/apps/dolalert/android/app
                    projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                    projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@6e3f7f81
                    projectPath: :app
                    projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@e6a8d59
                    properties: {...}
                    providers: org.gradle.api.internal.provider.DefaultProviderFactory@b58ddb8
                    reporting: org.gradle.api.reporting.ReportingExtension_Decorated@4b1011a5
                    reportsDir: /Users/mariano/development/apps/dolalert/build/app/reports
                    repositories: repository container
                    resourceLoader: org.gradle.internal.resource.transfer.DefaultUriTextResourceLoader@48dd120d
                    resources: org.gradle.api.internal.resources.DefaultResourceHandler@5d8bafe0
                    rootDir: /Users/mariano/development/apps/dolalert/android
                    rootProject: root project 'android'
                    script: false
                    scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@7d1f14d
                    scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@4c07452b
                    serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@6cea6bdc
                    services: ProjectScopeServices
                    sourceCompatibility: 1.8
                    sourceSets: SourceSet container
                    standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@13149d54
                    state: project state 'EXECUTED'
                    status: integration
                    subprojects: []
                    targetCompatibility: 1.8
                    tasks: task set
                    testReportDir: /Users/mariano/development/apps/dolalert/build/app/reports/tests
                    testReportDirName: tests
                    testResultsDir: /Users/mariano/development/apps/dolalert/build/app/test-results
                    testResultsDirName: test-results
                    version: unspecified
                    1 actionable task: 1 executed
[   +2 ms] executing: [/Users/mariano/development/apps/dolalert/android/] /Users/mariano/development/apps/dolalert/android/gradlew app:tasks --all --console=auto
[ +602 ms]
                    > Configure project :app
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
                    WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

                    > Task :app:tasks

                    ------------------------------------------------------------
                    All tasks runnable from project :app
                    ------------------------------------------------------------

                    Android tasks
                    -------------
                    androidDependencies - Displays the Android dependencies of the project.
                    signingReport - Displays the signing info for the base and test modules
                    sourceSets - Prints out all the source sets defined in this project.

                    Build tasks
                    -----------
                    assemble - Assemble main outputs for all the variants.
                    assembleAndroidTest - Assembles all the Test applications.
                    build - Assembles and tests this project.
                    buildDependents - Assembles and tests this project and all projects that depend on it.
                    buildNeeded - Assembles and tests this project and all projects it depends on.
                    bundle - Assemble bundles for all the variants.
                    clean - Deletes the build directory.
                    cleanBuildCache - Deletes the build cache directory.
                    compileDebugAndroidTestSources
                    compileDebugSources
                    compileDebugUnitTestSources
                    compileDynamicProfileSources
                    compileDynamicProfileUnitTestSources
                    compileDynamicReleaseSources
                    compileDynamicReleaseUnitTestSources
                    compileProfileSources
                    compileProfileUnitTestSources
                    compileReleaseSources
                    compileReleaseUnitTestSources

                    Cleanup tasks
                    -------------
                    lintFix - Runs lint on all variants and applies any safe suggestions to the source code.

                    Help tasks
                    ----------
                    buildEnvironment - Displays all buildscript dependencies declared in project ':app'.
                    components - Displays the components produced by project ':app'. [incubating]
                    dependencies - Displays all dependencies declared in project ':app'.
                    dependencyInsight - Displays the insight into a specific dependency in project ':app'.
                    dependentComponents - Displays the dependent components of components in project ':app'. [incubating]
                    help - Displays a help message.
                    model - Displays the configuration model of project ':app'. [incubating]
                    projects - Displays the sub-projects of project ':app'.
                    properties - Displays the properties of project ':app'.
                    tasks - Displays the tasks runnable from project ':app'.

                    Install tasks
                    -------------
                    installDebug - Installs the Debug build.
                    installDebugAndroidTest - Installs the android (on device) tests for the Debug build.
                    installDynamicProfile - Installs the DynamicProfile build.
                    installDynamicRelease - Installs the DynamicRelease build.
                    installProfile - Installs the Profile build.
                    installRelease - Installs the Release build.
                    uninstallAll - Uninstall all applications.
                    uninstallDebug - Uninstalls the Debug build.
                    uninstallDebugAndroidTest - Uninstalls the android (on device) tests for the Debug build.
                    uninstallDynamicProfile - Uninstalls the DynamicProfile build.
                    uninstallDynamicRelease - Uninstalls the DynamicRelease build.
                    uninstallProfile - Uninstalls the Profile build.
                    uninstallRelease - Uninstalls the Release build.

                    Verification tasks
                    ------------------
                    check - Runs all checks.
                    connectedAndroidTest - Installs and runs instrumentation tests for all flavors on connected devices.
                    connectedCheck - Runs all device checks on currently connected devices.
                    connectedDebugAndroidTest - Installs and runs the tests for debug on connected devices.
                    deviceAndroidTest - Installs and runs instrumentation tests using all Device Providers.
                    deviceCheck - Runs all device checks using Device Providers and Test Servers.
                    lint - Runs lint on all variants.
                    lintDebug - Runs lint on the Debug build.
                    lintDynamicProfile - Runs lint on the DynamicProfile build.
                    lintDynamicRelease - Runs lint on the DynamicRelease build.
                    lintProfile - Runs lint on the Profile build.
                    lintRelease - Runs lint on the Release build.
                    lintVitalRelease - Runs lint on just the fatal issues in the release build.
                    test - Run unit tests for all variants.
                    testDebugUnitTest - Run unit tests for the debug build.
                    testDynamicProfileUnitTest - Run unit tests for the dynamicProfile build.
                    testDynamicReleaseUnitTest - Run unit tests for the dynamicRelease build.
                    testProfileUnitTest - Run unit tests for the profile build.
                    testReleaseUnitTest - Run unit tests for the release build.

                    Other tasks
                    -----------
                    assembleDebug - Assembles main output for variant debug
                    assembleDebugAndroidTest - Assembles main output for variant debugAndroidTest
                    assembleDebugUnitTest - Assembles main output for variant debugUnitTest
                    assembleDynamicProfile - Assembles main output for variant dynamicProfile
                    assembleDynamicProfileUnitTest - Assembles main output for variant dynamicProfileUnitTest
                    assembleDynamicRelease - Assembles main output for variant dynamicRelease
                    assembleDynamicReleaseUnitTest - Assembles main output for variant dynamicReleaseUnitTest
                    assembleProfile - Assembles main output for variant profile
                    assembleProfileUnitTest - Assembles main output for variant profileUnitTest
                    assembleRelease - Assembles main output for variant release
                    assembleReleaseUnitTest - Assembles main output for variant releaseUnitTest
                    buildDebugPreBundle
                    buildDynamicProfilePreBundle
                    buildDynamicReleasePreBundle
                    buildProfilePreBundle
                    buildReleasePreBundle
                    bundleDebug - Assembles bundle for variant debug
                    bundleDebugAndroidTestClasses
                    bundleDebugAndroidTestResources
                    bundleDebugClasses
                    bundleDebugResources
                    bundleDebugUnitTestClasses
                    bundleDynamicProfile - Assembles bundle for variant dynamicProfile
                    bundleDynamicProfileClasses
                    bundleDynamicProfileResources
                    bundleDynamicProfileUnitTestClasses
                    bundleDynamicRelease - Assembles bundle for variant dynamicRelease
                    bundleDynamicReleaseClasses
                    bundleDynamicReleaseResources
                    bundleDynamicReleaseUnitTestClasses
                    bundleProfile - Assembles bundle for variant profile
                    bundleProfileClasses
                    bundleProfileResources
                    bundleProfileUnitTestClasses
                    bundleRelease - Assembles bundle for variant release
                    bundleReleaseClasses
                    bundleReleaseResources
                    bundleReleaseUnitTestClasses
                    checkDebugManifest
                    checkDynamicProfileManifest
                    checkDynamicReleaseManifest
                    checkProfileManifest
                    checkReleaseManifest
                    compileDebugAidl
                    compileDebugAndroidTestAidl
                    compileDebugAndroidTestJavaWithJavac
                    compileDebugAndroidTestNdk
                    compileDebugAndroidTestRenderscript
                    compileDebugAndroidTestShaders
                    compileDebugJavaWithJavac
                    compileDebugNdk
                    compileDebugRenderscript
                    compileDebugShaders
                    compileDebugUnitTestJavaWithJavac
                    compileDynamicProfileAidl
                    compileDynamicProfileJavaWithJavac
                    compileDynamicProfileNdk
                    compileDynamicProfileRenderscript
                    compileDynamicProfileShaders
                    compileDynamicProfileUnitTestJavaWithJavac
                    compileDynamicReleaseAidl
                    compileDynamicReleaseJavaWithJavac
                    compileDynamicReleaseNdk
                    compileDynamicReleaseRenderscript
                    compileDynamicReleaseShaders
                    compileDynamicReleaseUnitTestJavaWithJavac
                    compileLint
                    compileProfileAidl
                    compileProfileJavaWithJavac
                    compileProfileNdk
                    compileProfileRenderscript
                    compileProfileShaders
                    compileProfileUnitTestJavaWithJavac
                    compileReleaseAidl
                    compileReleaseJavaWithJavac
                    compileReleaseNdk
                    compileReleaseRenderscript
                    compileReleaseShaders
                    compileReleaseUnitTestJavaWithJavac
                    consumeConfigAttr
                    copyFlutterAssetsDebug
                    copyFlutterAssetsDynamicProfile
                    copyFlutterAssetsDynamicRelease
                    copyFlutterAssetsProfile
                    copyFlutterAssetsRelease
                    createDebugCompatibleScreenManifests
                    createDynamicProfileCompatibleScreenManifests
                    createDynamicReleaseCompatibleScreenManifests
                    createMockableJar
                    createProfileCompatibleScreenManifests
                    createReleaseCompatibleScreenManifests
                    extractApksForDebug
                    extractApksForDynamicProfile
                    extractApksForDynamicRelease
                    extractApksForProfile
                    extractApksForRelease
                    extractProguardFiles
                    flutterBuildDebug
                    flutterBuildDynamicProfile
                    flutterBuildDynamicRelease
                    flutterBuildProfile
                    flutterBuildRelease
                    flutterBuildX86Jar
                    generateDebugAndroidTestAssets
                    generateDebugAndroidTestBuildConfig
                    generateDebugAndroidTestResources
                    generateDebugAndroidTestResValues
                    generateDebugAndroidTestSources
                    generateDebugAssets
                    generateDebugBuildConfig
                    generateDebugFeatureMetadata
                    generateDebugFeatureTransitiveDeps
                    generateDebugResources
                    generateDebugResValues
                    generateDebugSources
                    generateDebugUnitTestAssets
                    generateDebugUnitTestResources
                    generateDebugUnitTestSources
                    generateDynamicProfileAssets
                    generateDynamicProfileBuildConfig
                    generateDynamicProfileFeatureMetadata
                    generateDynamicProfileFeatureTransitiveDeps
                    generateDynamicProfileResources
                    generateDynamicProfileResValues
                    generateDynamicProfileSources
                    generateDynamicProfileUnitTestAssets
                    generateDynamicProfileUnitTestResources
                    generateDynamicProfileUnitTestSources
                    generateDynamicReleaseAssets
                    generateDynamicReleaseBuildConfig
                    generateDynamicReleaseFeatureMetadata
                    generateDynamicReleaseFeatureTransitiveDeps
                    generateDynamicReleaseResources
                    generateDynamicReleaseResValues
                    generateDynamicReleaseSources
                    generateDynamicReleaseUnitTestAssets
                    generateDynamicReleaseUnitTestResources
                    generateDynamicReleaseUnitTestSources
                    generateProfileAssets
                    generateProfileBuildConfig
                    generateProfileFeatureMetadata
                    generateProfileFeatureTransitiveDeps
                    generateProfileResources
                    generateProfileResValues
                    generateProfileSources
                    generateProfileUnitTestAssets
                    generateProfileUnitTestResources
                    generateProfileUnitTestSources
                    generateReleaseAssets
                    generateReleaseBuildConfig
                    generateReleaseFeatureMetadata
                    generateReleaseFeatureTransitiveDeps
                    generateReleaseResources
                    generateReleaseResValues
                    generateReleaseSources
                    generateReleaseUnitTestAssets
                    generateReleaseUnitTestResources
                    generateReleaseUnitTestSources
                    javaPreCompileDebug
                    javaPreCompileDebugAndroidTest
                    javaPreCompileDebugUnitTest
                    javaPreCompileDynamicProfile
                    javaPreCompileDynamicProfileUnitTest
                    javaPreCompileDynamicRelease
                    javaPreCompileDynamicReleaseUnitTest
                    javaPreCompileProfile
                    javaPreCompileProfileUnitTest
                    javaPreCompileRelease
                    javaPreCompileReleaseUnitTest
                    mainApkListPersistenceDebug
                    mainApkListPersistenceDebugAndroidTest
                    mainApkListPersistenceDynamicProfile
                    mainApkListPersistenceDynamicRelease
                    mainApkListPersistenceProfile
                    mainApkListPersistenceRelease
                    makeApkFromBundleForDebug
                    makeApkFromBundleForDynamicProfile
                    makeApkFromBundleForDynamicRelease
                    makeApkFromBundleForProfile
                    makeApkFromBundleForRelease
                    mergeDebugAndroidTestAssets
                    mergeDebugAndroidTestJniLibFolders
                    mergeDebugAndroidTestResources
                    mergeDebugAndroidTestShaders
                    mergeDebugAssets
                    mergeDebugJniLibFolders
                    mergeDebugResources
                    mergeDebugShaders
                    mergeDynamicProfileAssets
                    mergeDynamicProfileJniLibFolders
                    mergeDynamicProfileResources
                    mergeDynamicProfileShaders
                    mergeDynamicReleaseAssets
                    mergeDynamicReleaseJniLibFolders
                    mergeDynamicReleaseResources
                    mergeDynamicReleaseShaders
                    mergeProfileAssets
                    mergeProfileJniLibFolders
                    mergeProfileResources
                    mergeProfileShaders
                    mergeReleaseAssets
                    mergeReleaseJniLibFolders
                    mergeReleaseResources
                    mergeReleaseShaders
                    packageDebug
                    packageDebugAndroidTest
                    packageDebugBundle
                    packageDebugUniversalApk
                    packageDynamicProfile
                    packageDynamicProfileBundle
                    packageDynamicProfileUniversalApk
                    packageDynamicRelease
                    packageDynamicReleaseBundle
                    packageDynamicReleaseUniversalApk
                    packageProfile
                    packageProfileBundle
                    packageProfileUniversalApk
                    packageRelease
                    packageReleaseBundle
                    packageReleaseUniversalApk
                    preBuild
                    preDebugAndroidTestBuild
                    preDebugBuild
                    preDebugUnitTestBuild
                    preDynamicProfileBuild
                    preDynamicProfileUnitTestBuild
                    preDynamicReleaseBuild
                    preDynamicReleaseUnitTestBuild
                    prepareLintJar
                    preProfileBuild
                    preProfileUnitTestBuild
                    preReleaseBuild
                    preReleaseUnitTestBuild
                    processDebugAndroidTestJavaRes
                    processDebugAndroidTestManifest
                    processDebugAndroidTestResources
                    processDebugGoogleServices
                    processDebugJavaRes
                    processDebugManifest
                    processDebugResources
                    processDebugUnitTestJavaRes
                    processDynamicProfileGoogleServices
                    processDynamicProfileJavaRes
                    processDynamicProfileManifest
                    processDynamicProfileResources
                    processDynamicProfileUnitTestJavaRes
                    processDynamicReleaseGoogleServices
                    processDynamicReleaseJavaRes
                    processDynamicReleaseManifest
                    processDynamicReleaseResources
                    processDynamicReleaseUnitTestJavaRes
                    processProfileGoogleServices
                    processProfileJavaRes
                    processProfileManifest
                    processProfileResources
                    processProfileUnitTestJavaRes
                    processReleaseGoogleServices
                    processReleaseJavaRes
                    processReleaseManifest
                    processReleaseResources
                    processReleaseUnitTestJavaRes
                    reportBuildArtifactsDebug
                    reportBuildArtifactsDynamicProfile
                    reportBuildArtifactsDynamicRelease
                    reportBuildArtifactsProfile
                    reportBuildArtifactsRelease
                    reportSourceSetTransformAndroidTest
                    reportSourceSetTransformAndroidTestDebug
                    reportSourceSetTransformDebug
                    reportSourceSetTransformDynamicProfile
                    reportSourceSetTransformDynamicRelease
                    reportSourceSetTransformMain
                    reportSourceSetTransformProfile
                    reportSourceSetTransformRelease
                    reportSourceSetTransformTest
                    reportSourceSetTransformTestDebug
                    reportSourceSetTransformTestDynamicProfile
                    reportSourceSetTransformTestDynamicRelease
                    reportSourceSetTransformTestProfile
                    reportSourceSetTransformTestRelease
                    resolveConfigAttr
                    shrinkReleaseResources
                    signingConfigWriterDebug
                    signingConfigWriterDebugAndroidTest
                    signingConfigWriterDynamicProfile
                    signingConfigWriterDynamicRelease
                    signingConfigWriterProfile
                    signingConfigWriterRelease
                    transformClassesAndDexWithShrinkResForRelease
                    transformClassesAndResourcesWithProguardForRelease
                    transformClassesWithDexBuilderForDebug
                    transformClassesWithDexBuilderForDebugAndroidTest
                    transformClassesWithDexBuilderForDynamicProfile
                    transformClassesWithDexBuilderForDynamicRelease
                    transformClassesWithDexBuilderForProfile
                    transformClassesWithDexBuilderForRelease
                    transformDexArchiveWithDexMergerForDebug
                    transformDexArchiveWithDexMergerForDebugAndroidTest
                    transformDexArchiveWithDexMergerForDynamicProfile
                    transformDexArchiveWithDexMergerForDynamicRelease
                    transformDexArchiveWithDexMergerForProfile
                    transformDexArchiveWithDexMergerForRelease
                    transformDexArchiveWithExternalLibsDexMergerForDebug
                    transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest
                    transformDexArchiveWithExternalLibsDexMergerForDynamicProfile
                    transformDexArchiveWithExternalLibsDexMergerForDynamicRelease
                    transformDexArchiveWithExternalLibsDexMergerForProfile
                    transformNativeLibsWithMergeJniLibsForDebug
                    transformNativeLibsWithMergeJniLibsForDebugAndroidTest
                    transformNativeLibsWithMergeJniLibsForDynamicProfile
                    transformNativeLibsWithMergeJniLibsForDynamicRelease
                    transformNativeLibsWithMergeJniLibsForProfile
                    transformNativeLibsWithMergeJniLibsForRelease
                    transformResourcesWithMergeJavaResForDebug
                    transformResourcesWithMergeJavaResForDebugAndroidTest
                    transformResourcesWithMergeJavaResForDebugUnitTest
                    transformResourcesWithMergeJavaResForDynamicProfile
                    transformResourcesWithMergeJavaResForDynamicProfileUnitTest
                    transformResourcesWithMergeJavaResForDynamicRelease
                    transformResourcesWithMergeJavaResForDynamicReleaseUnitTest
                    transformResourcesWithMergeJavaResForProfile
                    transformResourcesWithMergeJavaResForProfileUnitTest
                    transformResourcesWithMergeJavaResForRelease
                    transformResourcesWithMergeJavaResForReleaseUnitTest
                    validateSigningDebug
                    validateSigningDebugAndroidTest
                    validateSigningDynamicProfile
                    validateSigningDynamicRelease
                    validateSigningProfile
                    validateSigningRelease
                    writeDebugApplicationId
                    writeDebugModuleMetadata
                    writeDynamicProfileApplicationId
                    writeDynamicProfileModuleMetadata
                    writeDynamicReleaseApplicationId
                    writeDynamicReleaseModuleMetadata
                    writeProfileApplicationId
                    writeProfileModuleMetadata
                    writeReleaseApplicationId
                    writeReleaseModuleMetadata

                    Rules
                    -----
                    Pattern: clean<TaskName>: Cleans the output files of a task.
                    Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
                    Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.
                    1 actionable task: 1 executed
[   +5 ms] Resolving dependencies... (completed in 1.2s)
[   +1 ms] executing: /Users/mariano/Library/Android/sdk/build-tools/28.0.3/aapt dump xmltree /Users/mariano/development/apps/dolalert/build/app/outputs/apk/app.apk
AndroidManifest.xml
[   +6 ms] Exit code 0 from: /Users/mariano/Library/Android/sdk/build-tools/28.0.3/aapt dump xmltree /Users/mariano/development/apps/dolalert/build/app/outputs/apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x28a3
               A: android:versionName(0x0101021c)="1.04.03" (Raw: "1.04.03")
               A: android:installLocation(0x010102b7)=(type 0x10)0x0
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.gotyalabs.dollar" (Raw: "com.gotyalabs.dollar")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=8)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="com.android.vending.BILLING" (Raw: "com.android.vending.BILLING")
               E: meta-data (line=20)
                 A: android:name(0x01010003)="com.google.android.gms.ads.APPLICATION_ID" (Raw: "com.google.android.gms.ads.APPLICATION_ID")
                 A: android:value(0x01010024)="[ADMOB_APP_ID]" (Raw: "[ADMOB_APP_ID]")
               E: uses-permission (line=24)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=25)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=26)
                 A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" (Raw:
                 "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
               E: uses-permission (line=27)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw: "com.google.android.c2dm.permission.RECEIVE")
               E: application (line=35)
                 A: android:label(0x01010001)="Dolalert" (Raw: "Dolalert")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: meta-data (line=41)
                   A: android:name(0x01010003)="com.google.android.gms.ads.APPLICATION_ID" (Raw: "com.google.android.gms.ads.APPLICATION_ID")
                   A: android:value(0x01010024)="ca-app-pub-7622677027150498~1471083981" (Raw: "ca-app-pub-7622677027150498~1471083981")
                 E: activity (line=45)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.gotyalabs.dollar.MainActivity" (Raw: "com.gotyalabs.dollar.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=59)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: meta-data (line=62)
                     A: android:name(0x01010003)="com.google.firebase.messaging.default_notification_icon" (Raw: "com.google.firebase.messaging.default_notification_icon")
                     A: android:resource(0x01010025)=@0x7f040016
                   E: intent-filter (line=66)
                     E: action (line=67)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=69)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
                     E: action (line=71)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=73)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: service (line=79)
                   A: android:name(0x01010003)="io.flutter.plugins.firebasemessaging.FlutterFirebaseInstanceIDService" (Raw:
                   "io.flutter.plugins.firebasemessaging.FlutterFirebaseInstanceIDService")
                   E: intent-filter (line=80)
                     E: action (line=81)
                       A: android:name(0x01010003)="com.google.firebase.INSTANCE_ID_EVENT" (Raw: "com.google.firebase.INSTANCE_ID_EVENT")
                 E: service (line=84)
                   A: android:name(0x01010003)="io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService" (Raw:
                   "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService")
                   E: intent-filter (line=85)
                     E: action (line=86)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=93)
                   A: android:name(0x01010003)="com.google.firebase.messaging.FirebaseMessagingService" (Raw: "com.google.firebase.messaging.FirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=96)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=97)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: activity (line=101)
                   A: android:theme(0x01010000)=@0x1030010
                   A: android:name(0x01010003)="com.android.billingclient.api.ProxyBillingActivity" (Raw: "com.android.billingclient.api.ProxyBillingActivity")
                   A: android:configChanges(0x0101001f)=(type 0x11)0x5b0
                 E: service (line=106)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw: "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: meta-data (line=109)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=112)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.iid.Registrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.iid.Registrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                 E: receiver (line=117)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementReceiver" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementReceiver")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=122)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver")
                   A: android:permission(0x01010006)="android.permission.INSTALL_PACKAGES" (Raw: "android.permission.INSTALL_PACKAGES")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=127)
                     E: action (line=128)
                       A: android:name(0x01010003)="com.android.vending.INSTALL_REFERRER" (Raw: "com.android.vending.INSTALL_REFERRER")
                 E: service (line=132)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementService" (Raw: "com.google.android.gms.measurement.AppMeasurementService")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=136)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementJobService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementJobService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw: "android.permission.BIND_JOB_SERVICE")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=142)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdReceiver" (Raw: "com.google.firebase.iid.FirebaseInstanceIdReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw: "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=146)
                     E: action (line=147)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw: "com.google.android.c2dm.intent.RECEIVE")
                 E: service (line=154)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdService" (Raw: "com.google.firebase.iid.FirebaseInstanceIdService")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=157)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=158)
                       A: android:name(0x01010003)="com.google.firebase.INSTANCE_ID_EVENT" (Raw: "com.google.firebase.INSTANCE_ID_EVENT")
                 E: provider (line=162)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw: "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.gotyalabs.dollar.firebaseinitprovider" (Raw: "com.gotyalabs.dollar.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                 E: activity (line=168)
                   A: android:theme(0x01010000)=@0x1030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw: "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: activity (line=172)
                   A: android:theme(0x01010000)=@0x103000f
                   A: android:name(0x01010003)="com.google.android.gms.ads.AdActivity" (Raw: "com.google.android.gms.ads.AdActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:configChanges(0x0101001f)=(type 0x11)0xfb0
                 E: provider (line=178)
                   A: android:name(0x01010003)="com.google.android.gms.ads.MobileAdsInitProvider" (Raw: "com.google.android.gms.ads.MobileAdsInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.gotyalabs.dollar.mobileadsinitprovider" (Raw: "com.gotyalabs.dollar.mobileadsinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                 E: meta-data (line=184)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw: "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f060001
[   +6 ms] Error running com.gotyalabs.dollar. Default activity not found
[   +1 ms] Unable to read manifest info from /Users/mariano/development/apps/dolalert/build/app/outputs/apk/app.apk.
[   +6 ms] No application found for TargetPlatform.android_arm.
           Is your project missing an android/app/src/main/AndroidManifest.xml?
           Consider running "flutter create ." to create one.
[   +4 ms] "flutter run" took 3,307ms.
[        ] "flutter run" took 3,307ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:411:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Users/mariano/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
Analyzing dolalert...

   info • Name types using UpperCamelCase • lib/animations/background.dart:4:7 • camel_case_types
   info • Name types using UpperCamelCase • lib/animations/background.dart:9:7 • camel_case_types
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/animations/background.dart:54:3 • sdk_version_async_exported_from_core
   info • The value of the local variable 'backgrounWidgets' isn't used • lib/animations/background.dart:66:18 • unused_local_variable
   info • Unused import: 'package:dollar/models/message.dart' • lib/bloc/dollar_bloc.dart:4:8 • unused_import
   info • Unused import: 'package:firebase_messaging/firebase_messaging.dart' • lib/bloc/dollar_bloc.dart:5:8 • unused_import
   info • Cancel instances of dart.async.StreamSubscription • lib/bloc/dollar_bloc.dart:9:22 • cancel_subscriptions
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: HomePage._bannerAd •
          lib/main.dart:84:7 • must_be_immutable
   info • 'designedForFamilies' is deprecated and shouldn't be used • lib/main.dart:88:7 • deprecated_member_use
   info • The value of the field '_bannerAd' isn't used • lib/main.dart:97:12 • unused_field
   info • Dead code • lib/main.dart:172:40 • dead_code
   info • Dead code • lib/main.dart:174:31 • dead_code
   info • Dead code • lib/main.dart:178:31 • dead_code
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/main.dart:190:3 •
          sdk_version_async_exported_from_core
   info • This function has a return type of 'Future', but doesn't end with a return statement • lib/main.dart:190:3 • missing_return
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/main.dart:273:1 •
          sdk_version_async_exported_from_core
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          SimpleTimeSeriesChart.animate • lib/modules/charts.dart:8:7 • must_be_immutable
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: WeekChart.series •
          lib/modules/charts.dart:150:7 • must_be_immutable
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: MonthChart.series •
          lib/modules/charts.dart:232:7 • must_be_immutable
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/charts.dart:325:1 • sdk_version_async_exported_from_core
   info • This function has a return type of 'Future<List<TimeSeriesCurrency>>', but doesn't end with a return statement • lib/modules/charts.dart:325:1 • missing_return
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/charts.dart:350:1 • sdk_version_async_exported_from_core
   info • This function has a return type of 'Future<List<TimeSeriesCurrency>>', but doesn't end with a return statement • lib/modules/charts.dart:350:1 • missing_return
   info • The value of the local variable 'isTablet' isn't used • lib/modules/currencyCalculator.dart:45:16 • unused_local_variable
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/currencyCalculator.dart:48:5 • sdk_version_async_exported_from_core
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/currencyCalculator.dart:49:5 • sdk_version_async_exported_from_core
   info • Unused import: 'dart:convert' • lib/modules/notifications.dart:1:8 • unused_import
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:145:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:153:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:159:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:344:27 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:508:31 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:593:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:608:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/modules/notifications.dart:614:3 • sdk_version_async_exported_from_core

35 issues found. (ran in 2.2s)
```

```
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.13.6 17G65, locale en-AR)
    • Flutter version 1.2.1 at /Users/mariano/development/flutter
    • Framework revision 8661d8aecd (hace 4 semanas), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mariano/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Moto G 5 Plus             • ZY2247GWGL    • android-arm • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by marianoarga** [comment]
Tried Downgrading Android Studio an using VSCode, same result.

**Comment by marianoarga** [comment]
Is not failing in new projects, but in all the "old" (1 week) ones.

**Comment by Vivekban** [comment]
@marianoarga I am facing the same issue. Any solution?

**Comment by toanphung** [comment]
Same issue. How do fix it?

**Comment by marianoarga** [comment]
I don't have a fix yet.
Seems related to #21382 as far as I can tell, maybe it fails after some flutter upgrade.

**Comment by marianoarga** [comment]
Changed to dev (1.3.10) channel, but getting the same error.
The error only disappears if I remove
`<action android:name="FLUTTER_NOTIFICATION_CLICK" />`
And
`<category android:name="android.intent.category.DEFAULT" />`
From AndroidManifest.xml, so if you don't need the notification's payload you can avoid using that intent

**Comment by marianoarga** [comment]
This is not happening in Android Studio 3.2.1, tested on older computer. 
I don't have a clue in why the error is the same when usin Android Studio 3.3.2 and switching to VSCode...

**Comment by pratiktimer** [comment]
even me facing the same isssue ...creating new project moving code also not helping..

**Comment by Vivekban** [comment]
It can be resolved by making activity first element inside AndroidManifest.xml. Earlier, I am having meta-data as first element. 

Working Sample

       <application
        android:name=".MyApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="Test">
           <activity>  // should be first element inside application 
           </activity>
           // then other elements like
           <meta- data/>
           <receiver/> 
       </applicatiopn>

**Comment by marianoarga** [comment]
@Vivekban yes, it was a malformed AndroidManifest.xml problem, solved a few days ago, the build breaks now (where older versions of the framework don't), it doesn't seem to understand the malformation.

Solved by correctly placing xml tags.

**Comment by gewoonwoutje** [comment]
I had the same problem after updating, but it did not seem to be related to the AndroidManifest.xml file. I invalidated the Android Studio cache and closed it, and fixed it by deleting all build caches in:
- ~/.gradle/cache
- ~/.AndroidStudio/system/caches
- <project dir>/build
- <project dir>/android/.gradle

**Comment by Aqluse** [comment]
@gewoonwoutje Thanks, it does help, but I had too reboot PC to be able to remove first two chache folders fully

**Comment by SscSPs** [comment]
This is actually a bug, which I think I have fixed, will be submitting a PR soon.
Will add this as reference in the PR.

**Comment by Shashank25071999** [comment]
clean your build folder by command flutter clean then run your app by flutter run it will work

**Comment by marianoarga** [comment]
@Shashank25071999 this issue has already been described as fixed and the problem was related to a malformed AndroidManifest.xml, runngin "flutter clean" does not fix the issue, thank you.
