### ISSUE TITLE
Camera plugin causing memory leak on iOS

### ISSUE THREAD

**Issue by zbarbuto** [flutter/flutter#29586]
This is reproducible in the example project for the [camera plugin](https://github.com/flutter/plugins/tree/master/packages/camera/example).

Unsure whether or not this is directly related to #26007 or not

#20402 and #20943 were both closed without a resolution (I tried `flutter upgrade` as mentioned which did not fix the issue).

## Steps to Reproduce

1. Build the flutter code (`flutter build package`) and run on an iOS device through Xcode
2. Go to the memory profiling section in Xcode:
![image](https://user-images.githubusercontent.com/9100419/54579983-dc49a400-4a55-11e9-8495-dadce71ba369.png)

3. Alternate between the two cameras at the bottom of the screen (front then back then front then back etc)

Result:
The memory usage will slowly climb with each alternation - it will spike for the back camera (likely due to the higher resolution) then drop down for the front camera but in either case the values that each settle on will get higher and higher until the app crashes with an out of memory error:

![image](https://user-images.githubusercontent.com/9100419/54580023-0c914280-4a56-11e9-914d-a80001b30b27.png)

**Comment by andrei-cimpan** [comment]
I don't know if this helps as I wasn't using camera flip, but instead realtime frame processing of the and upgrading to Flutter 1.5.2 solved the memory leak.

**Comment by zbarbuto** [comment]
I just updated to 1.5.4 and it is still an issue for me.

**Comment by rmtmckenzie** [comment]
I've added a +1 but I'd also like to add a bit more insight to this issue. I've been trying to integrate a 3rd party image processing API into my app and therefore needed to write the camera code myself. After thinking I'd done something wrong and spending several days tracing for memory leaks I concluded it wasn't me so it was either the 3rd-party framework or Flutter. 

I ended up making a sample plugin to test things out and look for memory leaks (https://github.com/rmtmckenzie/swiftcameratest) and observed the same issue (I also thought it might be something to do with the swift <--> objc interfacing but that doesn't seem to really be it either). I was able to conclude that it wasn't anything to do with opening & closing the camera itself as that always seems to free any allocated memory if remove the `textureRegistry.register(...)`, `textureRegistry.textureFrameAvailable(...)`, and `textureRegistry.unregisterTexture(...)` calls.

![Screenshot showing no memory leaks without texture registry](https://user-images.githubusercontent.com/3103484/57411318-055afb00-71a2-11e9-8e89-5a1772c8fc0d.png)

Anyways, I did some profiling on the camera plugin's sample app, and was able to reproduce the crash just by switching between cameras (as @zbarbuto found. I only found this issue when I tried submitting my own though =D). It turns out that this is mainly in the form of leaked IOSurface objects. ![Screenshot of profiling table showing IOSurface allocations](https://user-images.githubusercontent.com/3103484/57411603-e7da6100-71a2-11e9-944f-9bb0788b13cd.png), which results in this memory graph:
![Memory graph showing growth over time until crash](https://user-images.githubusercontent.com/3103484/57411622-f58fe680-71a2-11e9-863c-9fa1fc692da9.png)
 
Note that in my app with the 3rd party library which also takes a fair amount of memory, instead of seeing this after switching between cameras multiple times it actually occurs on the second time the camera is opened - and I definitely need to open it at least twice during the runtime of the app. So this has turned into a bit of a blocker for me.

**Comment by kf6gpe** [comment]
@bparrishMines is this something on your or the team's radar to look at at this point, or should we move it to the Stretch Goals milestone?

**Comment by bparrishMines** [comment]
We don't currently have bandwidth for this, so moving it to Stretch Goals is fine with me.

**Comment by kf6gpe** [comment]
@cyanglaz This might be another one for Q4 if the team's got the bandwidth.

**Comment by cyanglaz** [comment]
https://github.com/flutter/flutter/issues/60409#issuecomment-651323149 looks like the memory leak issue on the plugin has been resolved?

**Comment by edocabhi** [comment]
@cyanglaz  No, it is not fixed. Please don't add misleading comments without testing yourself.

**Comment by mvanbeusekom** [comment]
I have been trying to reproduce this issue switching between the front and back camera but the memory now stays constant around 189Mb. This issue seems to be fixed since patch:

>##  0.5.2+2
>
>*  Fix memory leak related to not unregistering stream handler in FlutterEventChannel when disposing camera.

If I rollback this update (simply comment out this [line](https://github.com/flutter/plugins/blob/7d392476ac20569c8afd9ebc5f0328d383fdc7c5/packages/camera/camera/ios/Classes/CameraPlugin.m#L571)) the memory seems to be leaking again. Therefore I suggest we close this issue (@cyanglaz, @bparrishMines).

**Comment by rmtmckenzie** [comment]
I agree - I'm not able to reproduce the issue any more either! Awesome work =).

**Comment by mvanbeusekom** [comment]
Thanks for confirming @rmtmckenzie, I will close the issue now.

**Comment by yurijdvornyk** [comment]
I'm able to reproduce this issue in my app with the same graph.
I have multiple screens with camera, that are switched with Navigator.pushReplacementNamed(...). Camera is disposed on every of them, however, after switching 8-10 times the app leaks. It is reproducible for me with ResolutionPreset.max on iPhone 8 and XS (2 devices that I have near me right now).
