### ISSUE TITLE
Android Studio not found at /Application/Android Studio.app/Contents

### ISSUE THREAD

**Issue by jimStyle88** [flutter/flutter#30149]
![image](https://user-images.githubusercontent.com/20588608/55201905-1a865680-5200-11e9-95a6-ea5414b9022b.png)
[✓] Android Studio (version 3.3)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Application/Android Studio.app/Contents

how can i deal it

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/55202195-64237100-5201-11e9-9b7b-71c0471adafa.png)
[✓] Android Studio (version 3.3)
[!] Android Studio
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.
✗ Android Studio not found at /Application/Android Studio.app/Contents

i have already install  flutter plugin & dart plugin ，

![image](https://user-images.githubusercontent.com/20588608/55202314-ddbb5f00-5201-11e9-85de-0450fb802893.png)
how can i deal it

**Comment by ZanderBA** [comment]
I'm facing the same problem. I have installed Flutter and Android Studio in Windows, and flutter doctor has reported:

<img width="566" alt="doctor" src="https://user-images.githubusercontent.com/10908032/57808740-618dc400-773a-11e9-991b-29d125ff6bc4.PNG">

**Comment by ZanderBA** [comment]
Problem solved removing android-studio-dir setting by running:

      flutter config --android-studio-dir=

as sugested by flutter doctor when executed to show all details

    flutter doctor -v

**Comment by arlucio** [comment]
[maybe this helps](https://stackoverflow.com/a/57468726/10492091)

when you install via JetBrains toolbox the pwd is different

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by MAB-IT** [comment]
✗ Android Studio not found at /Application/Android Studio.app/Contents

I fixed this problem :
By changing the name of the folder from "/android studio" to "/android_studio"

may be the Spaces and symbols not supported.

**Comment by lodipalle** [comment]
I followed this syntax: flutter config --android-studio-dir="C:/Program_Files/Android/Android_Studio" but still getting the same error.
