### ISSUE TITLE
Problem deploying to iOS device

### ISSUE THREAD

**Issue by joaowd** [flutter/flutter#30180]
When I try to debug in a physical iOS device I got this exception:

Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1094/ws
Exited (sigterm)

**Comment by Toubap** [comment]
same here..

**Comment by tomalabaster** [comment]
A couple of things to check, have you disabled `Connect via network` from Xcode, and you're not tethering your machine to your iOS device are you?

**Comment by c0h1b4** [comment]
Same issue here:

https://github.com/flutter/flutter/issues/32651

This is a SEVERE and very old issue that the Flutter team can't solve or don't want to. And it is starting to grow as the flutter developer base increases. It is very frustrating to see that they don't care.

**Comment by follyxing** [comment]
same here.......

**Comment by NTMS2017** [comment]
same here https://github.com/flutter/flutter/issues/38458 I run flutter run -v and found out end of the information there is a dart zone error... Any news from flutter team?

I am using macbook with Intellij and with iPhone 6 on iOS 12.4

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by joaowd** [comment]
Yes keeps happening. Sometimes I also get this error:

Could not update files on device: OS Error: Connection reset by peer, errno = 54

**Comment by escamoteur** [comment]
@joaowd Does this mean this error appears only sometimes or always?

Could you please add the output of your `flutter doctor` and the full log when this error appears?
Thanks

**Comment by joaowd** [comment]
@escamoteur Sometimes I get the first error, sometimes I get this error I just sent.

I'd say when I try to deploy to a physical iOS device I have 40% chances that the deploy is successful.

I have no issues with Android or in the iOS simulator.

flutter doctor -v:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-PT)
    • Flutter version 1.9.1+hotfix.2 at /Users/joaopalma/Development/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/joaopalma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.0

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1
```

**Comment by escamoteur** [comment]
Does it make a difference if you run from the console or from the IDE?

**Comment by escamoteur** [comment]
Also could you please try the beta channel, there is a new hotfix on since yesterday

**Comment by escamoteur** [comment]
All the referenced issues are fixed so I m really curious if it work with the beta

**Comment by joaowd** [comment]
Still failing on (v1.9.1+hotfix.4) btw I'm using visual studio code

**Comment by janmoppel** [comment]
Hello @joaowd !

Can you please also attach the error stack trace, if there is any?

Thank you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
