### ISSUE TITLE
Threading issues with rendering during window resize

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30671]
The desktop shells resize the graphics context on the main thread, while drawing to it happens from a background thread. This can cause crashes (#17579), but even when it doesn't there are often strange rendering behaviors (red flashes, briefly transparent or garbage-filled windows, etc.)

Beyond just fixing the crashes, we need a robust solution to make resizing feel reasonable. Visually, synchronous repaints would probably be ideal, but something that isn't synchronous, but is highly responsive while avoiding shaking and/or tearing would likely feel good enough (c.f. Chromium's async renderer painting).

**Comment by stuartmorgan** [comment]
@chinmaygarde It would be great if you could post the in-progress work you had for this (for macOS, IIRC) somewhere as a starting point for whoever takes this on.

**Comment by rknell** [comment]
Confirming I have this problem and can reliably reproduce it. Not sure I have the engineering ability to resolve, but if you need someone to help test and reproduce I am happy to help out.

**Comment by gspencergoog** [comment]
@chinmaygarde @stuartmorgan What's the status of this with the resize crash being fixed?  @franciscojma86 seems to think this is done.

**Comment by stuartmorgan** [comment]
We should probably retitle it. The actual threading problems are fixed, but the second part of the original description (resize looking incredibly janky) is still a problem.

**Comment by chinmaygarde** [comment]
I am closing this issue as the threading issue [has been fixed](https://github.com/flutter/engine/commit/e3c5f4827d17e82887b66469cf0d13ecc1cd5d3e). Part of what made the resize look really bad was the OpenGL errors during resize causing a frame that was of an undefined color (usually red). Not being susceptible to these errors has made the resizing much more pleasant. We should file and prioritize a separate issue if the experience is still not satisfactory.

**Comment by stuartmorgan** [comment]
Filed #44136. The current situation is definitely still not satisfactory on macOS.
