### ISSUE TITLE
`flutter help attach` should provide better instructions

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#30826]
Currently `flutter help attach` says:

> Attach to a running application.

But based on https://github.com/flutter/flutter/issues/29886#issuecomment-476046878 , this is very misleading since `flutter attach`needs to be run first, and therefore the application can't be "running".

`flutter help attach` should provide more detailed and more accurate instructions. (Or it should work how it claims, although I'm presuming that's much less feasible.)

[✓] Flutter (Channel unknown, v1.4.13-pre.16, on Linux, locale en_US.UTF-8)    
    • Flutter version 1.4.13-pre.16 at /home/jamesdlin/git/flutter/flutter     
    • Framework revision 514aba6e36 (3 hours ago), 2019-04-09 17:40:20 -0400   
    • Engine revision eec74e5c92
    • Dart version 2.2.1 (build 2.2.1-dev.3.1 None)

**Comment by christopherfujino** [comment]
Fixed in [31279](Add flutter attach documentation #31279).

**Comment by jamesderlin** [comment]
Thanks for adding the documentation, but is that markdown document supposed to be shown when I run `flutter help attach`? (I'm not seeing it.) If not, then this isn't fixed. `flutter help attach` is the first place a user should be expected to look.

**Comment by Pragya007** [comment]
To solve this issue I am changing [this ](https://github.com/flutter/flutter/blob/f95f46e91052f23b945671cc918bd523caa4898e/packages/flutter_tools/lib/src/commands/attach.dart#L112)file...but when I did `flutter help attach` in cmd it still showing this old description why the change here in description is not visible. Do I need to change another file also..

**Comment by christopherfujino** [comment]
@Pragya007 did you rebuild the tool? There are instructions here https://github.com/flutter/flutter/wiki/The-flutter-tool#making-changes-to-the-flutter-tool

**Comment by Pragya007** [comment]
> @Pragya007 did you rebuild the tool? There are instructions here https://github.com/flutter/flutter/wiki/The-flutter-tool#making-changes-to-the-flutter-tool

Thanks @christopherfujino

**Comment by JuYeong0413** [comment]
Fixed in https://github.com/flutter/flutter/pull/61569, this issue should be closed.
