### ISSUE TITLE
[v1.4.9-hotfix.1] Test coverage tool crashes while collecting data for the report

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#31196]
Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.13.6 17G5019, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.io/setup/#android-setup for detailed instructions.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

When running tests with coverage enabled (flutter test --coverage), the process fails and reports a failure. Running tests without coverage enabled works perfectly fine

## Steps to Reproduce

1. Run tests with coverage enabled
2. See the crash after ~30 seconds

Stacktrace:

```
NoSuchMethodError: The method 'map' was called on null.
  Receiver: null
  Tried calling: map<List<int>>(Closure: (dynamic) => List<int>)
  dart:core-patch/object_patch.dart 50:5                        Object.noSuchMethod
  package:vm_service_client/src/script.dart 181:14              new VMScript._
  package:vm_service_client/src/script.dart 62:11               VMScriptRef.load
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                             _Completer.completeError
  dart:async-patch/async_patch.dart 40:18                       _AsyncAwaitCompleter.completeError
  package:vm_service_client/src/script.dart                     VMScriptRef.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                       _asyncThenWrapperHelper
  package:vm_service_client/src/script.dart                     VMScriptRef.load
  package:coverage/src/collect.dart 101:30                      _getCoverageJson
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                       _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             _getCoverageJson
  package:coverage/src/collect.dart 67:26                       _getAllCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                       _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             _getAllCoverage
  package:coverage/src/collect.dart 51:18                       collect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                       _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             collect
  package:flutter_tools/src/test/coverage_collector.dart 55:45  CoverageCollector.collectCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart          _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 483:36   _FlutterPlatform.loadChannel
  package:flutter_tools/src/test/flutter_platform.dart 438:46   _FlutterPlatform.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                       _asyncThenWrapperHelper
  package:test_core/src/runner/loader.dart                      Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 98:31            new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>
```

**Comment by jonahwilliams** [comment]
The hot fix is unfortunately from before the coverage change, and it looks like there is an pre-existing bug when the tokenTables are not defined for a Script, which might only happen for newer dart vms

**Comment by ITJammish** [comment]
I am also seeing a similar error when running `flutter test --coverage` and the same reproduction steps:
`NoSuchMethodError: The getter 'iterator' was called on null.` etc

Coverage works fine on Flutter versions up to and including v1.5.3, but v1.5.4 and after 
1) show this message
2) hang indefinitely on various tests (often the last test in a test class) and never complete.

Regular `flutter test` runs fine on all tested Flutter versions. Later Flutter versions also confirmed showing the same message: v1.5.4-hotfix.1, v1.5.4-hotfix.2, v1.6.0

Flutter doctor (lowest failing version found):
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4, on Mac OS X 10.14.5 18F132, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
[!] VS Code (version 1.26.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
Closing as this should have been fixed on the latest stable

**Comment by ovidiu-anghelina** [comment]
I am still getting this on v1.8.2 (stacktrace below).

The strange thing is, if I add the --start-paused flag and indicate the file with the test that would throw this exception, it no longer throws the exception and correctly generates the coverage file as well.

```
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _buildCoverageMap (package:flutter_tools/src/test/coverage_collector.dart:262:52)
#2      _getAllCoverage (package:flutter_tools/src/test/coverage_collector.dart:248:5)
<asynchronous suspension>
#3      collect (package:flutter_tools/src/test/coverage_collector.dart:199:10)
<asynchronous suspension>
#4      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:87:45)
<asynchronous suspension>
#5      CoverageCollector.handleFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:33:11)
<asynchronous suspension>
#6      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:667:30)
<asynchronous suspension>
#7      FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:363:36)
#8      FlutterPlatform.load (package:flutter_tools/src/test/flutter_platform.dart:316:46)
<asynchronous suspension>
#9      Loader.loadFile.<anonymous closure> (package:test_core/src/runner/loader.dart:224:36)
<asynchronous suspension>
#10     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/load_suite.dart:98:31)
<asynchronous suspension>
#11     invoke (package:test_api/src/utils.dart:241:5)
#12     new LoadSuite.<anonymous closure> (package:test_core/src/runner/load_suite.dart:97:7)
#13     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#14     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#16     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#17     _rootRun (dart:async/zone.dart:1120:38)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#22     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
