### ISSUE TITLE
Calling setState() with the value of switch not working

### ISSUE THREAD

**Issue by akshathjain** [flutter/flutter#31290]
I'm calling `setState` on the `value` of the switch when it's changed. In this example, I'm trying to prevent anything from happening. However, if the user manually slides the switch back, `_attemptChange` is still called yet the switch does not go back to the `true` position.

```dart
bool _toggleState = true;

@override
Widget build(BuildContext context){
  return Switch(
    value: _toggleState,
    onChanged: _attemptChange,
  );
}
 
void _attemptChange(bool newState){
  setState(() {
    _toggleState = true;
  });
}
```

**Comment by jonahwilliams** [comment]
The code you've included does not contain enough information to diagnose any errors. Please include a minimal reproducible example of the error and the output of `flutter doctor -v`.

**Comment by ffey** [comment]
Maybe your code must like below
```
void _attemptChange(bool newState){
  setState(() {
    _toggleState = !_toggleState ;
  });
}
```

**Comment by YuzhouZhang** [comment]
```
import 'package:camera/camera.dart';
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';
import 'package:quick_learners_dictionary/main.dart';
import 'package:quick_learners_dictionary/widgets/text_style.dart';

CameraController cameraController;

AnimationController backDropAnimationController;

var cameraPreviewWords = '';

class CameraPage extends StatefulWidget {
  @override
  _CameraPageState createState() {
    return _CameraPageState();
  }
}

class _CameraPageState extends State<CameraPage> with TickerProviderStateMixin, WidgetsBindingObserver {
  final GlobalKey _backdropKey = GlobalKey(debugLabel: 'Backdrop');

  bool _resolutionPreset = prefs.getBool('ResolutionPreset');

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: _displayWordsWithWrap,
    );
  }

  Widget _displayWordsWithWrap(BuildContext context, BoxConstraints constraints) {
    return SafeArea(
      child: Container(
        key: _backdropKey,
        child: Stack(
          children: <Widget>[
            new Column(
              mainAxisAlignment: MainAxisAlignment.start,
              mainAxisSize: MainAxisSize.max,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                Flexible(
                  child: Container(
//                  padding: EdgeInsets.all(10),
                    child: Stack(
                      alignment: AlignmentDirectional.center,
                      children: <Widget>[
                        Stack(
                          alignment: AlignmentDirectional.topEnd,
                          children: <Widget>[
                            Padding(
                              padding: const EdgeInsets.only(top: 1),
                              child: PopupMenuButton(
                                offset: Offset(0, AdSize.banner.height.toDouble()),
                                icon: Icon(
                                  Icons.menu,
                                  color: Colors.white,
                                ),
                                itemBuilder: (BuildContext context) {
                                  return <PopupMenuItem<String>>[
                                    PopupMenuItem<String>(
                                      child: SwitchListTile(
                                        title: Text(
                                          'High Sensitivity',
                                          style: RegularTextStyle(
                                            fontSize: 16,
                                            color: Theme.of(context).primaryColorDark,
                                          ),
                                        ),
                                        value: _resolutionPreset,
                                        onChanged: (value) {
                                          setState(() {
                                            if (value) {
                                              _resolutionPreset = true;
//                                              prefs.setBool('ResolutionPreset', _resolutionPreset);
                                            } else {
                                              _resolutionPreset = false;
//                                              prefs.setBool('ResolutionPreset', _resolutionPreset);
                                            }
                                          });
                                        },
                                      ),
                                      value: 'High Sensitivity',
                                    ),
                                  ];
                                },
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

I can slide the switch button, but when I click the switch button, nothing happens. 

flutter doctor output:

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/zhangyuzhou/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/zhangyuzhou/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/zhangyuzhou/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/zhangyuzhou/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/zhangyuzhou/Downloads/idea-IC-181.4892.42
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Pixel 2 XL • 805KPYR1822994 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by akshathjain** [comment]
Here's a simpler `main.dart` that you can copy in to a fresh project. Notice that if you click on the toggle, nothing happens (which is intended), but the toggle's state changes when you slide it (which shouldn't happen).

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Issue #31290',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Issue #31290 Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget build(BuildContext context){
    return Scaffold(
      appBar: AppBar(title: Text(widget.title),),
      body: Center(
        child: Switch(
          value: false,
          onChanged: (bool b){},
        ),
      ),
    );
  }
}
```

Also, here's the output of `flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale
    en-US)
    • Flutter version 1.2.1 at /Users/akshath/Library/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53
      -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/akshath/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.0

[✓] Connected device (1 available)
    • iPhone Xs • 03FF088A-3DB4-425D-8B15-827534D700F8 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment]
is there any update on this I am facing a similar issue ?

**Comment by adecentrai** [comment]
Any update on this issue facing the same issue. Looks like Switch is not properly. Please Help

**Comment by kleeb** [comment]
same for me

**Comment by kleeb** [comment]
ok, no idea why but it starts working when you move the setState invocation outside of the build method

**Comment by VadPinchuk** [comment]
same situation. still facing this issue.
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-UA) 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

**Comment by bsutton** [comment]
I can confirm this behaviour. I even tried moving the call to setState out to a delayed future with the same results:
```
 void update() {
    Future.delayed(
        Duration(microseconds: 0), () => setState(() => activated = true));
  }
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_AU.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by Sathyananth** [comment]
> I'm calling `setState` on the `value` of the switch when it's changed. In this example, I'm trying to prevent anything from happening. However, if the user manually slides the switch back, `_attemptChange` is still called yet the switch does not go back to the `true` position.
> 
> ```dart
> bool _toggleState = true;
> 
> @override
> Widget build(BuildContext context){
>   return Switch(
>     value: _toggleState,
>     onChanged: _attemptChange,
>   );
> }
>  
> void _attemptChange(bool newState){
>   setState(() {
>     _toggleState = true;
>   });
> }
> ```

From my understanding the bool value assigned during the creation of switch is considered to be final.

In your case, during the creation of switch, the _toggleState=true. If the switch is toggled manually to false, the _toggleState is mismatch with the current state of the switch. This will trigger the "onChanged", which will call your function "_attemptChange".  Here your function pro-grammatically changes your variable _toggleState=true again. This will not create the switch again because it was already built.

Now again you toggle the switch to true, but the _toggleState is already true. So there is no change, which in turn will not trigger the "onChanged".

**Comment by JoshRice1** [comment]
So just a suggestion I got this to work but in a really hoky way.

What I think we really want is a beforeChange callback that lets us designate if the change should be allowed or not.
This would be useful in multiple situations where you want a user to confirm they want to enable a feature or any other validation you might want to do on a form.

What works but sucks for UI resonsivness:
```
bool _toggleState = true;

  @override
  Widget build(BuildContext context) {
    return Switch(
      value: _toggleState,
      onChanged: _attemptChange,
    );
  }

  void _attemptChange(bool newState) {
    setState(() {
      _toggleState = newState;
    });
    compute(sleep, Duration(microseconds: 0)).then((_) {
      setState(() {
        _toggleState = !newState;
      });
    });
  }
```

**Comment by Afsar-Pasha** [comment]
fixed in #51606

**Comment by TahaTesser** [comment]
Hi @akshathjain 
Calling setState is working fine on latest `dev` channel and also works with drag


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Issue #31290',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Issue #31290 Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _toggleState = false;

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Switch(
          value: _toggleState,
          onChanged: _attemptChange,
        ),
      ),
    );
  }

  void _attemptChange(bool newState) {
    setState(() {
      _toggleState = newState;
    });
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details> 


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by CCinnovationsUK** [comment]
Weird, still facing the same issue today. My initial boolean is declared outside of the build widget and I've used the usual `setState(){initialBool = newVal;}` ... Will drop my solution here when I find it

**Comment by danielgchap** [comment]
Flutter Switch elements are constantly a frigging let down. Whoever incorporated the inherent initial value and it's response to params passed in.. is a freaking moron. YEARS this has been going on. Pathetic.
