### ISSUE TITLE
Listview crashes when scrolling all the items out of the screen (listview viewport)

### ISSUE THREAD

**Issue by AndrsDev** [flutter/flutter#32442]
## Steps to Reproduce

1. Write a simple listview.builder:
2. Set `physics: AlwaysScrollableScrollPhysics(),`
3. **Scroll to the top as fast as you can trying to get all the items out of the screen!!**
4.  It crashes and close the app.

A gif that best describes the crash tested on a real device (the same bug occurs if you try the same but scrolling to bottom):

<a href="https://imgflip.com/gif/30nqog"><img src="https://i.imgflip.com/30nqog.gif" title="made at imgflip.com"/></a>

## Logs

**Exception error:**
```
E/flutter (28414): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NullPointerException: Attempt to invoke interface
method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/flutter (28414):      at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1324)
E/flutter (28414):      at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:269)
E/flutter (28414):      at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:162)
E/flutter (28414):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (28414):      at android.os.MessageQueue.next(MessageQueue.java:379)
E/flutter (28414):      at android.os.Looper.loop(Looper.java:144)
E/flutter (28414):      at android.app.ActivityThread.main(ActivityThread.java:7529)
E/flutter (28414):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28414):      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/flutter (28414):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter (28414):
F/flutter (28414): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/ANE-LX3/HWANE:8.0.0/HUAWEIANE-LX3/156(C25):user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 15436, tid: 15436, name: ndrsdev.tutting  >>> com.andrsdev.tutting <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env). 
'
    x0   0000000000000000  x1   0000000000003c4c  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   7f7f7f7f7f7f7f7f
    x8   0000000000000083  x9   0cd54a82b9a256f7  x10  0000000000000001  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000010  x14  ffffffffffffffff  x15  00002243c4ea9436
    x16  0000007c9ae2c2d0  x17  0000007c9adcd800  x18  00000000130611b8  x19  0000000000003c4c
    x20  0000000000003c4c  x21  0000007ffd0d2028  x22  0000007ffd0d2280  x23  0000000000000000
    x24  0000000000000000  x25  00000000ffffffff  x26  000000000000000c  x27  0000000000000018
    x28  0000000000000018  x29  0000007ffd0d2010  x30  0000007c9ad80b54
    sp   0000007ffd0d1fd0  pc   0000007c9adcd808  pstate 0000000060000000
backtrace:
    #00 pc 000000000006a808  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000001db50  /system/lib64/libc.so (abort+88)
    #02 pc 00000000005ff780  /data/app/com.andrsdev.tutting-Cn9B4aX5oQotMkjHUi_ntw==/lib/arm64/libflutter.so (offset 0x5e0000)
    #03 pc 00000000005f2de8  /data/app/com.andrsdev.tutting-Cn9B4aX5oQotMkjHUi_ntw==/lib/arm64/libflutter.so (offset 0x5e0000)
    #04 pc 000000000062d904  /data/app/com.andrsdev.tutting-Cn9B4aX5oQotMkjHUi_ntw==/lib/arm64/libflutter.so (offset 0x5e0000)
    #05 pc 0000000000600c80  /data/app/com.andrsdev.tutting-Cn9B4aX5oQotMkjHUi_ntw==/lib/arm64/libflutter.so (offset 0x5e0000)
    #06 pc 00000000006029f8  /data/app/com.andrsdev.tutting-Cn9B4aX5oQotMkjHUi_ntw==/lib/arm64/libflutter.so (offset 0x5e0000)
    #07 pc 0000000000015f18  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+808)
    #08 pc 0000000000015b68  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+108)
    #09 pc 000000000011b31c  /system/lib64/libandroid_runtime.so (_ZN7androidL38android_os_MessageQueue_nativePollOnceEP7_JNIEnvP8_jobjectli+44)
    #10 pc 000000000082869c  /system/framework/arm64/boot-framework.oat (offset 0x627000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+140)
    #11 pc 0000000000006c40  /dev/ashmem/dalvik-jit-code-cache (deleted)


```

**Flutter analyze:**
```
   info - Unused import: 'countries.dart' - lib\framework\localizations.dart:4:8 - unused_import
   info - The value of the field '_errorMessage' isn't used - lib\screens\new-class.dart:45:10 - unused_field
```

**Flutter doctor:**
```
[√] Flutter (Channel master, v1.5.9-pre.213, on Microsoft Windows [VersiÃ³n 10.0.17134.706], locale es-GT)
    • Flutter version 1.5.9-pre.213 at C:\src\flutter
    • Framework revision 382704ca95 (57 minutes ago), 2019-05-10 13:28:19 -0700
    • Engine revision 3822aeccd9
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Developer\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Developer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.0

[√] Connected device (1 available)
    • ANE LX3 • 6NUDU18605002140 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by AndrsDev** [comment]
It happens in flutter gallery app too. Crashes on every listview scroll when setting the platform mechanics to Mountain view!!!  this is severe

**Comment by jituijiaqiezi** [comment]
just update your flutter version with "flutter upgrade" will solve the problem.

**Comment by justinmc** [comment]
I'm going to close this since it looks like it's been fixed, but let me know if it doesn't fix the problem and I'll reopen this.  Make sure you're using the master channel to pick up this brand new fix.

**Comment by AndrsDev** [comment]
@justinmc I've already updated the flutter version and switched to master channel. The crash still happens. I also updated the issue with a gif for a better understanding and demostration of the crash. Please reopen this issue.

**Comment by justinmc** [comment]
Alright sounds like this is different than https://github.com/flutter/flutter/issues/32047, reopening.

**Comment by AndrsDev** [comment]
This seems to be the bug derived from #32047,

**Comment by jckpn** [comment]
Just noticed this in my app too, using a GridView. Happens on both my Pixel 2 and Razer Phone, in debug and release.

I tried adding code to prevent it by listening for the offset and calling jumpTo(), but the app still freezes and needs to be stopped.

`var _pos = searchScrollController.offset.round();
  
  if (_pos < -screenHeight / 12)
    searchScrollController.jumpTo(-screenHeight / 12);

  if (_pos > searchScrollController.position.maxScrollExtent + screenHeight/12) {
      searchScrollController.jumpTo(searchScrollController.position.maxScrollExtent + screenHeight/12);
  }`

**Comment by RobPFarley** [comment]
I believe i'm having the same issue with one of my apps. Scrolling to the bottom of a ListView then reloading the ListView by filtering the items used to build it results in the same error as above. Here's the code needed to replicate:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var searchTerm = '';
  final _searchTextController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    var items = List<String>();
    for (var i = 0; i < 10; i++) {
      items.add('a');
      items.add('ab');
      items.add('abc');
      items.add('abcd');
      items.add('abcde');
    }

    var filteredItems = items.where((item) => item.contains(searchTerm)).toList();

    return Scaffold(
      appBar: AppBar(
        title: TextField(
          controller: _searchTextController,
          onChanged: (text) => setState(() => searchTerm = text),
          textInputAction: TextInputAction.search,
          decoration: InputDecoration(
            hintText: "Search...",
          ),
          autofocus: true,
        ),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.close),
            onPressed: () => _searchTextController.clear(),
          ),
        ],
      ),
      body: ListView.separated(
        separatorBuilder: (context, index) => Divider(height: 1),
        itemCount: filteredItems.length,
        itemBuilder: (context, index) => ListTile(title: Text(filteredItems[index])),
      ),
    );
  }
}

```

### Steps to reproduce:

1. Run the above code on an Android device
2. Scroll to the bottom of the list
3. Type the letter "e" in the search box
4. The app will now crash with the below error

```Launching lib\main.dart on SM G950F in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
D/ViewRootImpl@ba93e5b[MainActivity](21426): MSG_WINDOW_FOCUS_CHANGED 0
D/ViewRootImpl@ba93e5b[MainActivity](21426): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@ba93e5b[MainActivity](21426): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 479276048384} changed=false
D/libGLESv2(21426): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.list_view_crash_test
V/InputMethodManager(21426): Starting input: tba=android.view.inputmethod.EditorInfo@b13611a nm : com.example.list_view_crash_test ic=io.flutter.plugin.editing.InputConnectionAdaptor@2f2744b
I/InputMethodManager(21426): startInputInner - mService.startInputOrWindowGainedFocus
D/InputMethodManager(21426): SSI - flag : 0 Pid : 21426 view : com.example.list_view_crash_test
D/ViewRootImpl@ba93e5b[MainActivity](21426): MSG_RESIZED: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 72 - 0, 144) vi=Rect(0, 72 - 0, 144) or=1
D/ViewRootImpl@ba93e5b[MainActivity](21426): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 479276048384} changed=false
D/SurfaceView(21426): BG show() Surface(name=Background for - SurfaceView - com.example.list_view_crash_test/com.example.list_view_crash_test.MainActivity@75f67d1@0) io.flutter.view.FlutterView{75f67d1 VFED..... .F....ID 0,0-1080,2076}
D/SurfaceView(21426): surfaceChanged (1080,2076) 1 io.flutter.view.FlutterView{75f67d1 VFED..... .F....ID 0,0-1080,2076}
D/mali_winsys(21426): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x2076]-format:1
D/ViewRootImpl@ba93e5b[MainActivity](21426): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 479276048384} changed=false
I/zygote64(21426): Do partial code cache collection, code=27KB, data=29KB
I/zygote64(21426): After code cache collection, code=27KB, data=29KB
I/zygote64(21426): Increasing code cache capacity to 128KB
D/ViewRootImpl@ba93e5b[MainActivity](21426): ViewPostIme pointer 0
D/ViewRootImpl@ba93e5b[MainActivity](21426): ViewPostIme pointer 1
I/zygote64(21426): Do partial code cache collection, code=59KB, data=54KB
I/zygote64(21426): After code cache collection, code=59KB, data=54KB
I/zygote64(21426): Increasing code cache capacity to 256KB
E/flutter (21426): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/flutter (21426): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1315)
E/flutter (21426): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:268)
E/flutter (21426): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:150)
E/flutter (21426): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21426): 	at android.os.MessageQueue.next(Unknown Source:21)
E/flutter (21426): 	at android.os.Looper.loop(Unknown Source:24)
E/flutter (21426): 	at android.app.ActivityThread.main(Unknown Source:146)
E/flutter (21426): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21426): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
E/flutter (21426): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:198)
E/flutter (21426):
F/flutter (21426): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).
F/libc    (21426): Fatal signal 6 (SIGABRT), code -6 in tid 21426 (view_crash_test)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU4CRL3:user/release-keys'
Revision: 'unknown'
ABI: 'arm64'
pid: 21426, tid: 21426, name: view_crash_test  >>> com.example.list_view_crash_test <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).
'
    x0   0000000000000000  x1   00000000000053b2  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000008000000000
    x8   0000000000000083  x9   ed4a286577fd782d  x10  0000000000000001  x11  0000000000000000
    x12  ffffffffffffffff  x13  0000000000000018  x14  ffffffffffffffff  x15  001311e96d21e2cc
    x16  0000006fb9fae2f8  x17  0000006fb9f4e90c  x18  0000006fbd68e0f0  x19  00000000000053b2
    x20  00000000000053b2  x21  0000007fd5464688  x22  00000000ffffffff  x23  000000000000000c
    x24  0000000000000018  x25  00000000ffffffff  x26  0000006f80f4457c  x27  0000000000000018
    x28  000000000000000f  x29  0000007fd5464670  x30  0000006fb9efb05c
    sp   0000007fd5464630  pc   0000006fb9f4e914  pstate 0000000060000000
backtrace:
    #00 pc 0000000000071914  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000001e058  /system/lib64/libc.so (abort+88)
    #02 pc 0000000000d143b8  /data/app/com.example.list_view_crash_test-3gdID1apCENDVGIg_8s52g==/lib/arm64/libflutter.so (offset 0xd00000)
    #03 pc 0000000000d07568  /data/app/com.example.list_view_crash_test-3gdID1apCENDVGIg_8s52g==/lib/arm64/libflutter.so (offset 0xd00000)
    #04 pc 0000000000d05f18  /data/app/com.example.list_view_crash_test-3gdID1apCENDVGIg_8s52g==/lib/arm64/libflutter.so (offset 0xd00000)
    #05 pc 0000000000d4928c  /data/app/com.example.list_view_crash_test-3gdID1apCENDVGIg_8s52g==/lib/arm64/libflutter.so (offset 0xd00000)
    #06 pc 0000000000d14e78  /data/app/com.example.list_view_crash_test-3gdID1apCENDVGIg_8s52g==/lib/arm64/libflutter.so (offset 0xd00000)
    #07 pc 0000000000d18cc0  /data/app/com.example.list_view_crash_test-3gdID1apCENDVGIg_8s52g==/lib/arm64/libflutter.so (offset 0xd00000)
    #08 pc 0000000000016854  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+836)
    #09 pc 0000000000016484  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+116)
```

I haven't noticed this issue happening on an iOS device, I've only managed to replicate it on Android, but it happens every time there's a ListView that gets rebuilt after scrolling to the bottom. I've tried wrapping the Scaffold inside a try-catch, but the app still crashes fully without entering the catch block.

Flutter doctor:
```
PS C:\Users\Robert\Desktop\list_view_crash_test> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.35.1)
[√] Connected device (1 available)

• No issues found!
```

I've tried this on all flutter channels and the issue persists. I believe this should be very high priority as it makes making pages with dynamic ListViews impossible. I've made a workaround using a SingleChildScrollView and building the list using a column, but this is obviously not a long-term solution.

**Comment by cpboyd** [comment]
Like @RobPFarley, I'm also seeing this issue when attempting to filter while scrolling on Android.

Interestingly, this appears to be a heisenbug because when I tried setting breakpoints, the crash would never happen.

My guess is that when hitting the breakpoint, it pauses all calculations (including any on-going renders) and essentially the renderer is given time to catch up to the actual state of the list.

It's plausible that the renderer is still trying to render an item from the old list.

**Comment by RobPFarley** [comment]
I have actually noticed that myself with adding breakpoints. It took me a while to figure out what the issue was because of adding breakpoints around the code that caused the rebuild

**Comment by cpboyd** [comment]
@RobPFarley FYI, I seem to have found a workaround by utilizing a `ScrollController`:
```dart

class _MyHomePageState extends State<MyHomePage> {
  var searchTerm = '';
  final _searchTextController = TextEditingController();
  final _scrollController = new ScrollController();

  @override
  Widget build(BuildContext context) {
    var items = List<String>();
    for (var i = 0; i < 10; i++) {
      items.add('a');
      items.add('ab');
      items.add('abc');
      items.add('abcd');
      items.add('abcde');
    }

    var filteredItems = items.where((item) => item.contains(searchTerm)).toList();

    return Scaffold(
      appBar: AppBar(
        title: TextField(
          controller: _searchTextController,
          onChanged: (text) {
            _scrollController.jumpTo(0);
            setState(() => searchTerm = text);
          },
          textInputAction: TextInputAction.search,
          decoration: InputDecoration(
            hintText: "Search...",
          ),
          autofocus: true,
        ),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.close),
            onPressed: () => _searchTextController.clear(),
          ),
        ],
      ),
      body: ListView.separated(
        controller: _scrollController,
        separatorBuilder: (context, index) => Divider(height: 1),
        itemCount: filteredItems.length,
        itemBuilder: (context, index) => ListTile(title: Text(filteredItems[index])),
      ),
    );
  }
}
```

**Comment by RobPFarley** [comment]
@cpboyd Thanks for that :) I came up with a workaround myself where I built my own list view using a scroll view and column, but your workaround looks a lot better

**Comment by akari** [comment]
One more simple way to reproduce this bug:

1. Run this code on Android device (can't reproduce on the x86 emulator)
2. Scroll to the end of the list and tap on one of the last items
3. App will crash

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> _items = new List.generate(100, (i) => 'List item $i');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: _items.length,
        itemBuilder: (context, position) {
          return ListTile(
            title: Text(_items[position]),
            onTap: () {
              setState(() {
                _items = ['First item', 'Second item'];
              });
            }
          );
        },
      ),
    );
  }
}
```

Exception:
```
E/flutter (25471): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/flutter (25471): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1329)
E/flutter (25471): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:269)
E/flutter (25471): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:439)
E/flutter (25471): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25471): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (25471): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (25471): 	at android.app.ActivityThread.main(ActivityThread.java:6729)
E/flutter (25471): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (25471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (25471):
F/flutter (25471): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).
F/libc    (25471): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25471 (tterlistviewbug), pid 25471 (tterlistviewbug)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Nokia/Onyx_00WW/B2N_sprout:9/PPR1.180610.011/00WW_3_54E:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 25471, tid: 25471, name: tterlistviewbug  >>> com.example.flutterlistviewbug <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).
'
    x0  0000000000000000  x1  000000000000637f  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000800000
    x8  0000000000000083  x9  9a739b329275dc62  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000028  x14 ffffffffffffffff  x15 0000a62e51544510
    x16 00000074a5c712c8  x17 00000074a5baf0d0  x18 0000000000000001  x19 000000000000637f
    x20 000000000000637f  x21 0000007fda3a9078  x22 00000000ffffffff  x23 000000000000000c
    x24 0000000000000018  x25 00000000ffffffff  x26 00000073ff8f005c  x27 0000000000000018
    x28 000000000000000f  x29 0000007fda3a9060
    sp  0000007fda3a9020  lr  00000074a5ba3bfc  pc  00000074a5ba3c24
backtrace:
    #00 pc 0000000000021c24  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000d34a40  /data/app/com.example.flutterlistviewbug-9GnEoy2v5tBIfWYWZBXWUQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #02 pc 0000000000d27960  /data/app/com.example.flutterlistviewbug-9GnEoy2v5tBIfWYWZBXWUQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #03 pc 0000000000d26318  /data/app/com.example.flutterlistviewbug-9GnEoy2v5tBIfWYWZBXWUQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #04 pc 0000000000d6b958  /data/app/com.example.flutterlistviewbug-9GnEoy2v5tBIfWYWZBXWUQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #05 pc 0000000000d354ec  /data/app/com.example.flutterlistviewbug-9GnEoy2v5tBIfWYWZBXWUQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #06 pc 0000000000d3a1f4  /data/app/com.example.flutterlistviewbug-9GnEoy2v5tBIfWYWZBXWUQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #07 pc 00000000000141c0  /system/lib64/libutils.so (android::Looper::pollInner(int)+856)
    #08 pc 0000000000013dcc  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
    #09 pc 0000000000121ebc  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    #10 pc 00000000003e5fec  /system/framework/arm64/boot-framework.oat (offset 0x3d1000) (android.media.MediaExtractor.seekTo [DEDUPED]+140)
    #11 pc 000000000000551c  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.MessageQueue.next+204)
    #12 pc 0000000000554b88  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #13 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #14 pc 000000000027f2f8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #15 pc 0000000000279300  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #16 pc 000000000052480c  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #17 pc 0000000000547114  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #18 pc 0000000000b193be  /system/framework/boot-framework.vdex (android.os.Looper.loop+130)
    #19 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1006592660+488)
    #20 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #21 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #22 pc 0000000000525d10  /system/lib64/libart.so (MterpInvokeStatic+204)
    #23 pc 0000000000547294  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #24 pc 000000000039717a  /system/framework/boot-framework.vdex (android.app.ActivityThread.main+226)
    #25 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1006592660+488)
    #26 pc 00000000005150a0  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #27 pc 000000000055dcfc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #28 pc 0000000000554e4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #29 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #30 pc 000000000045c934  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #31 pc 000000000045e388  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
    #32 pc 00000000003ee2c8  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
    #33 pc 000000000011e6d4  /system/framework/arm64/boot-core-oj.oat (offset 0x114000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
    #34 pc 0000000000554b88  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #35 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #36 pc 000000000027f2f8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #37 pc 0000000000279300  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #38 pc 000000000052480c  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #39 pc 0000000000547114  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #40 pc 0000000000c3c15a  /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
    #41 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1006592660+488)
    #42 pc 00000000005150a0  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #43 pc 000000000055dcfc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #44 pc 0000000000bfa750  /system/framework/arm64/boot-framework.oat (offset 0x3d1000) (com.android.internal.os.ZygoteInit.main+3088)
    #45 pc 0000000000554e4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #46 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #47 pc 000000000045c934  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #48 pc 000000000045c594  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
    #49 pc 0000000000361ba4  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
    #50 pc 00000000000b403c  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
    #51 pc 00000000000b69c0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+756)
    #52 pc 00000000000022f8  /system/bin/app_process64 (main+1380)
    #53 pc 00000000000aca4c  /system/lib64/libc.so (__libc_init+88)
Lost connection to device.
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G65, locale en-RU)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by AndrsDev** [comment]
I'm no longer having this issue what I did was: 

1. Change to flutter **master channel**
2. Run` flutter clean `on the project
3. Uninstall the application from the phone.
4. Restart the phone.
5. Run the command `flutter run`

**Comment by justinmc** [comment]
Hmm hopefully it's fixed in master now then.  I tried @akari's example above and couldn't get it to crash on master.  If no one else can reproduce this on master then maybe we can close.

**Comment by ManojMM026** [comment]
I am still getting this crash. On Home page I have Nested List and BottomNavigation tab bar, If I scroll through the list (each having 10 items with no image) and switch tab for 2 3 times I can reproduce this easily on my Note 5 pro

**Comment by gladimdim** [comment]
I also encounter this issue.

Workaround layout fix: replace ListView with:

Expanded->SingleScrollView->Column->[listItems]

**Comment by ManojMM026** [comment]
@gladimdim  any example for me?

**Comment by davidmartos96** [comment]
> I also encounter this issue.
> 
> Workaround layout fix: replace ListView with:
> 
> Expanded->SingleScrollView->Column->[listItems]

@gladimdim  An scrollable column is not the same as a ListView. ListView builder, for instance, will only build the widgets as they are needed, whereas a Column will build all of them. If there are a lot, it could cause performance issues.

**Comment by ManojMM026** [comment]
This is a very critical issue, Anyone has a solution on this?

**Comment by justinmc** [comment]
Just to make sure, can you guys confirm that you're seeing this on the master channel? https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by RobPFarley** [comment]
Yes I can confirm that I still have the issue on master

**Comment by justinmc** [comment]
Thanks for confirming.

**Comment by ManojMM026** [comment]
@justinmc Please fix this on priority, It's like I can not deploy the app on xiaomi phones.

**Comment by pushangupta** [comment]
@justinmc I am on stable channel. This issue exists on some phones like Moto G4. 
My steps to reproduce are:
1. Listview with scroll direction horizontal.
2. Click on any item that is outside the width of the device.
3. Navigate to another page
4. Navigate back to the original page.
5. After landing on the original page, call setState on listview and rebuild the listview.

**Comment by pushangupta** [comment]
@justinmc This might be android 8 specific issue?

**Comment by ManojMM026** [comment]
@pushangupta , Mine is on android 9.

**Comment by Lecarvalho** [comment]
This solution worked for me: https://github.com/flutter/flutter/issues/30675#issuecomment-502834518

**Comment by pushangupta** [comment]
@Lecarvalho yes this worked for me too... but can someone please if this is the best solution and is production ready?

**Comment by ManojMM026** [comment]
@Lecarvalho It worked for me too. But as @pushangupta said we need something solid on this.

**Comment by ManojMM026** [comment]
@Lecarvalho release build still crashes with the above solution.

**Comment by fast0490f** [comment]
Hi, i have problem too ( Android 9, Samsung-950)
```
E/flutter ( 7569): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/flutter ( 7569): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1329)
E/flutter ( 7569): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:269)
E/flutter ( 7569): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:439)
E/flutter ( 7569): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 7569): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 7569): 	at android.os.Looper.loop(Looper.java:181)
E/flutter ( 7569): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/flutter ( 7569): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7569): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 7569): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter ( 7569): 

```

**Comment by gladimdim** [comment]
> @gladimdim any example for me?
> What do you think about sliverlist will it work?

Currently I am using this substitution of ListView:

https://gist.github.com/gladimdim/5b419d7178b654f846ea1fb14d25404c

But as other folks mentioned, it works only when you have small number of items to render in the view. For large arrays you have to use ListView.

**Comment by pablo384** [comment]
I have the same issue, just when I have like 60 items on my ListView, scrolldown and when I delete some items jus crash:

`E/flutter (18753): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/flutter (18753): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1329)
E/flutter (18753): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:269)
E/flutter (18753): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:439)
E/flutter (18753): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (18753): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (18753): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (18753): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/flutter (18753): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18753): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/flutter (18753): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (18753):
F/flutter (18753): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).
F/libc    (18753): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18753 (example.lotenet), pid 18753 (example.lotenet)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'OnePlus/OnePlus3/OnePlus3:9/PKQ1.181203.001/1906252002:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 18753, tid: 18753, name: example.lotenet  >>> com.example.lotenet <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(96)] Check failed: CheckException(env).
'
    x0  0000000000000000  x1  0000000000004941  x2  0000000000000006  x3  0000000000000008
    x4  0000000022d17308  x5  0000000022d17308  x6  0000000022d17308  x7  00000000001fffff
    x8  0000000000000083  x9  d30d325bda4d320d  x10 fffffff87ffffbdf  x11 d30d325bda4d320d
    x12 d30d325bda4d320d  x13 fffffff87ffffbdf  x14 0000000000000001  x15 00000077181b88c8
    x16 00000077181ac2b0  x17 00000077180be088  x18 0000007697400080  x19 0000000000004941
    x20 0000000000004941  x21 0000000000000083  x22 00000000ffffffff  x23 000000000000000c
    x24 0000000000000018  x25 00000000ffffffff  x26 000000767c8599bc  x27 0000000000000018
    x28 000000000000000f  x29 0000007ff50bc2b0
    sp  0000007ff50bc270  lr  00000077180af4d0  pc  00000077180af4f0
backtrace:
    #00 pc 00000000000224f0  /system/lib64/libc.so (abort+112)
    #01 pc 0000000000d34a40  /data/app/com.example.lotenet-AGhuqPzr1QUNqZHKpirh1w==/lib/arm64/libflutter.so (offset 0xd20000)
    #02 pc 0000000000d27960  /data/app/com.example.lotenet-AGhuqPzr1QUNqZHKpirh1w==/lib/arm64/libflutter.so (offset 0xd20000)
    #03 pc 0000000000d26318  /data/app/com.example.lotenet-AGhuqPzr1QUNqZHKpirh1w==/lib/arm64/libflutter.so (offset 0xd20000)
    #04 pc 0000000000d6b958  /data/app/com.example.lotenet-AGhuqPzr1QUNqZHKpirh1w==/lib/arm64/libflutter.so (offset 0xd20000)
    #05 pc 0000000000d354ec  /data/app/com.example.lotenet-AGhuqPzr1QUNqZHKpirh1w==/lib/arm64/libflutter.so (offset 0xd20000)
    #06 pc 0000000000d3a1f4  /data/app/com.example.lotenet-AGhuqPzr1QUNqZHKpirh1w==/lib/arm64/libflutter.so (offset 0xd20000)
    #07 pc 00000000000150b8  /system/lib64/libutils.so (android::Looper::pollInner(int)+844)
    #08 pc 0000000000014cd0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
    #09 pc 000000000012922c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    #10 pc 00000000003ebfec  /system/framework/arm64/boot-framework.oat (offset 0x3d7000) (android.media.MediaExtractor.seekTo [DEDUPED]+140)
    #11 pc 00000000000033fc  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.MessageQueue.next+204)
    #12 pc 0000000000561188  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #13 pc 00000000000cf6b8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #14 pc 0000000000282b00  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #15 pc 000000000027cbb0  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+960)
    #16 pc 0000000000530310  /system/lib64/libart.so (MterpInvokeVirtual+576)
    #17 pc 0000000000553894  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #18 pc 0000000000b21a96  /system/framework/boot-framework.vdex (android.os.Looper.loop+130)
    #19 pc 0000000000256d10  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3399805955+488)
    #20 pc 000000000025c8c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #21 pc 000000000027cb94  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+932)
    #22 pc 00000000005317d8  /system/lib64/libart.so (MterpInvokeStatic+200)
    #23 pc 0000000000553a14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #24 pc 00000000003a06ca  /system/framework/boot-framework.vdex (android.app.ActivityThread.main+214)
    #25 pc 0000000000256d10  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3399805955+488)
    #26 pc 0000000000520ad8  /system/lib64/libart.so (artQuickToInterpreterBridge+944)
    #27 pc 000000000056a2fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #28 pc 000000000056144c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #29 pc 00000000000cf6d8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #30 pc 0000000000466690  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #31 pc 00000000004681e4  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
    #32 pc 00000000003f6af0  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
    #33 pc 000000000011f6d4  /system/framework/arm64/boot-core-oj.oat (offset 0x115000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
    #34 pc 0000000000561188  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #35 pc 00000000000cf6b8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #36 pc 0000000000282b00  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #37 pc 000000000027cbb0  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+960)
    #38 pc 0000000000530310  /system/lib64/libart.so (MterpInvokeVirtual+576)
    #39 pc 0000000000553894  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #40 pc 0000000000c473a2  /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
    #41 pc 0000000000256d10  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3399805955+488)
    #42 pc 0000000000520ad8  /system/lib64/libart.so (artQuickToInterpreterBridge+944)
    #43 pc 000000000056a2fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #44 pc 0000000000c0c270  /system/framework/arm64/boot-framework.oat (offset 0x3d7000) (com.android.internal.os.ZygoteInit.main+3088)
    #45 pc 000000000056144c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #46 pc 00000000000cf6d8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #47 pc 0000000000466690  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #48 pc 0000000000466294  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
    #49 pc 0000000000368498  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
    #50 pc 00000000000b2c94  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+128)
    #51 pc 00000000000b5784  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+952)
    #52 pc 000000000000252c  /system/bin/app_process64 (main+2016)
    #53 pc 00000000000d4e58  /system/lib64/libc.so (__libc_init+88)`

**Comment by pushangupta** [comment]
@zoechi I request you to please have a look. We strongly need support on this. Thanks :)

**Comment by pushangupta** [comment]
Its sad to say, it isn't fixed yet. Please can someone provide an alternative as we need to move to production soon.

**Comment by Ethras** [comment]
same issue here on Android P and channel master

**Comment by cpboyd** [comment]
@pushangupta Have you tried what I suggested in https://github.com/flutter/flutter/issues/32442#issuecomment-506985541?

My initial guess is that the underlying Android ListView implementation is still trying to reference the item at the last index that it rendered.

As such, you probably don't have to scroll all the way back to the top, but that's just what I did to be safe (and it seemed to make sense in my case that after users filtered items, they should be at the top of whatever they filtered).

**Comment by pushangupta** [comment]
@cpboyd Yes I tried adding a controller before. But there is a situation in which even adding a controller won't work. 

Imagine you scroll to bottom of your listview. Then suddenly you perform some action where you completely want to switch your view to another listview whose scroll extent way less than the previous one.

Now this becomes a case where are you are scrolling beyond its maxscrollextent and hence fails on some android devices.

I think a simple try catch with JAVA framework should be implemented so that the crashes are avoided.

**Comment by cpboyd** [comment]
@pushangupta I've been successfully switching between different SliverLists of varying sizes (in some instances, the `SliverAppBar` will expand because the list is smaller than the screen).

**Comment by ratinggorilla** [comment]
@justinmc Its really late.. and it isn't fixed yet. Please I request you to keep this in priority. Its a major crash and our entire team is having a setback.

**Comment by justinmc** [comment]
I just tried again with @akari's example code and wasn't able to reproduce the crash on a Xiaomi Pocophone F1 running Android 9.

I'm going to close this issue since it seems like there are a lot of related but different problems in here.  @ratinggorilla or anyone else still having a problem, please open a new issue and link to this one in the description.  Please include the code for a minimal app that reproduces the problem and I'll try to reproduce it on my end!

**Comment by fast0490f** [comment]
@justinmc
Hey. I have this problem only on the Samsung-950. I know exactly how to reproduce the error, but on Xiaomi MI A2 for example it doesn’t work. I think this is an important clarification, you need to try on another device.

**Comment by justinmc** [comment]
@fast0490f Sorry, I closed this issue because it's hard to distinguish all the different different old and new problems in here.

Please open a new issue, including code for a minimal app to reproduce the problem, and the devices you expect it to be reproducible on.  Mention me in the issue and I'll take a look.
