### ISSUE TITLE
Empty app crash on iOS when in background for 3 minutes

### ISSUE THREAD

**Issue by stupidfive** [flutter/flutter#32461]
## Steps to Reproduce

1. Create new flutter app with `flutter create blank_app`
2. Open Xcode and select developer team
3. Build and run app on iPhone with `flutter run`
4. Lock iPhone screen with power button
5. Wait for 3 minutes or more
6. Unlock iPhone screen

Expected: App is still active
Actual: App terminated

## Logs

`flutter run --verbose` log after app in background

```
[+207406 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/F593A89F-8CBD-40F0-B75C-4862EC9F4D8F/tmp/blank_appirGFzG/blank_app/)
[        ] Sending to VM service: _deleteDevFS({fsName: blank_app})
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 228,559ms.
[        ] "flutter run" took 228,559ms.

```

`flutter analyze` output

```
Analyzing blank_app...
No issues found! (ran in 6.9s)
```

`flutter doctor -v` output

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D42, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/georgewu/flutter
    • Framework revision 7a4c33425d (10 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/georgewu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.3569.4
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • George’s iPhone 8x • d4104f2761b9550a888f1488ec17f46f1244ac36 • ios • iOS 11.3.1

! Doctor found issues in 2 categories.
```

**Comment by cbracken** [comment]
Fixed by flutter/engine#8930.

**Comment by MazEbeid** [comment]
Hi .. I am new to all of this and I am having the same problem .. my app crashes once it's in the background for some time. What does it mean when you mark the issue fixed? Do I need to update to a different flutter version where is the fix exactly?
Thanks

**Please see the below log after the app was terminated**
`[+1673 ms] Service protocol connection closed. [ ] Lost connection to device. [ +2 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/A4613311-537B-48FE-930C- EDCD59B696A5/tmp/seesometerStPr8t/seesometer/) [ ] Sending to VM service: _deleteDevFS({fsName: seesometer}) [ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed [ +3 ms] "flutter run" took 228,531ms. [ ] "flutter run" took 228,531ms.`

Flutter doctor output:

`[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[!] VS Code (version 1.36.1)
✗ Flutter extension not installed; install from
https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)`

**Comment by tudor07** [comment]
@cbracken can you please open this issue? It still happens in Flutter `1.7.8+hotfix.4`

**Comment by zhengwu119** [comment]
> @cbracken can you please open this issue? It still happens in Flutter `1.7.8+hotfix.4`

try this:

`override func applicationDidBecomeActive(_ application: UIApplication) {
        signal(SIGPIPE, SIG_IGN);
    }
    
    override func applicationWillEnterForeground(_ application: UIApplication) {
        signal(SIGPIPE, SIG_IGN);
    }`
