### ISSUE TITLE
Calling WidgetsFlutterBinding.ensureInitialized() in main() before runApp() causes launch image to disappear and a black screen to be displayed momentarily

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#32736]
## Use case

Calling `WidgetsFlutterBinding.ensureInitialized()` in `main()` before calling `runApp()` causes the launch image to disappear and a blank (typically black) screen to be displayed momentarily.

Calling this method is useful to get a head-start on app initialization, e.g. calling `InAppPurchaseConnection.instance.queryProductDetails` or installing `WidgetsBindingObserver`s cannot be done safely without doing so.

Practically speaking it may be almost as efficient to perform such initialization later, e.g. in `initState()` for the app's main widget, but I found myself putting these calls in `main()` as the most logical place. This then broke my launch screens, and it took me some time to figure out why I was seeing a black screen for a couple of seconds between launch image and my app's main screen.

This happens on both Android and iOS.

## Proposal

It would be nice to either:
- have a note in the documentation of `ensureInitialized()` warning developers that this is the case,
- or defer dismissal of the launch screen until the first frame is ready to be drawn.

I'm opening this as a feature request since it isn't strictly speaking a bug.

**Comment by matthewlloyd** [comment]
Gist demonstrating the issue: https://gist.github.com/matthewlloyd/be39c707e705e9612c8fc677f2614494

**Comment by daoan1412** [comment]
any update ?

**Comment by liammendes** [comment]
Because of recent changes in the Flutter API, a black screen can now be seen in the production version of Reflectly, an application with hundreds of thousands of users
https://play.google.com/store/apps/details?id=com.reflectlyApp

**Comment by vagners2** [comment]
Hi guys,
is this a bug, or there is an action that you intent to take in the future?

**Comment by liammendes** [comment]
This issue can be closed as the issue seems to be fixed in the closed issue #39494 as a result of #39535

**Comment by liammendes** [comment]
@Hixie

**Comment by goderbauer** [comment]
Closing this as a dup of #39494, which was fixed in #39535.

**Comment by firatcetiner** [comment]
Not fixed. Black screen still appears because of this in channel stable.

**Comment by goderbauer** [comment]
Try the master channel. It should be fixed there.

**Comment by firatcetiner** [comment]
> Try the master channel. It should be fixed there.

Thanks, I guess we can say that this won't be fixed in the next upcoming several stable releases, am I correct?
