### ISSUE TITLE
Offer options that balances embeddable Flutter load time with resource consumption

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32946]
We should identify the right balance point between loading the embedding / vm / isolate / framework / userland element tree / resources in the tree based on each part’s load time vs its memory use.

This involves https://github.com/flutter/flutter/issues/32945 to audit cold init time and also auditing memory consumption.

Our recommended embedding strategy + default behaviors from APIs should be reasonably balanced between fast loading and memory usage. 

Document alterations users can make given those APIs such as prewarming/keeping the vm only, prewarming/keeping the isolate. Flutter side APIs to flush parts of the tree when window is not visible.

**Comment by matthew-carroll** [comment]
This sounds like it might imply new APIs for such control? If so, those APIs probably sit at the basest level of the system and we should resolve these concerns ASAP. I imagine that this could impact bootstrapping behavior for the native system, as well as core APIs for all embeddings...

**Comment by xster** [comment]
I agree, this is the first task I'm looking at. I'm still not sure yet whether this involves just fixing bugs or our existing APIs can't offer the right degree of control for our users.

**Comment by xster** [comment]
In scope is to fix

![Screen Shot 2019-06-06 at 6 07 57 PM](https://user-images.githubusercontent.com/156888/59075581-38b6a580-8886-11e9-896c-3244830b201f.png)

Whether by API changes or fixing bugs

**Comment by xster** [comment]
Part of the issue above is likely #26007

**Comment by goderbauer** [comment]
I am not sure I understand what this issue is asking for. Specifically, what's needed from the framework to fix this (since it has the framework tag).

**Comment by xster** [comment]
The framework side of it will mostly be just https://github.com/flutter/flutter/issues/32871 (in making sure that there's a way to unload things once the window is no longer attached).
