### ISSUE TITLE
Flutter incompatible with Android Gradle Kotlin DSL

### ISSUE THREAD

**Issue by heinrichreimer** [flutter/flutter#33762]
## Steps to Reproduce

1. Create new Flutter Android app.
2. Mitgrate Gradle build scripts to Kotlin scripts (`build.gradle` -> `build.gradle.kts`)
3. Run `flutter run`

## Logs

```
> flutter run
Launching lib/main.dart on Pixel 2 in debug mode...
No application found for TargetPlatform.android_arm64.
Is your project missing an android\AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

```
> flutter analyze
Analyzing sudoku...
No issues found! (ran in 2.2s)
```

```
> flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\kiese\AppData\Local\flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kiese\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\kiese\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\kiese\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\kiese\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7479.19
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] VS Code, 64-bit edition (version 1.34.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • Pixel 2 • FA7A61A10729 • android-arm64 • Android 9 (API 28)

• No issues found!
```

## Possible Causes
When Flutter tries to run the application, it detects, the device is an Android phone.
Then it creates an instance of an [`AndroidProject`](https://github.com/flutter/flutter/blob/d0e45a2369e9b7603c5d8ca33280128fba01de38/packages/flutter_tools/lib/src/project.dart#L442).

In the `AndroidProject` multiple times the assertion is made, that a Gradle project must have a `build.gradle` file. This assertion is wrong, as Gradle projects can also use the Kotlin DSL, hence use a `build.gradle.kts` file.

## Occurrences to be fixed.
https://github.com/flutter/flutter/blob/d0e45a2369e9b7603c5d8ca33280128fba01de38/packages/flutter_tools/lib/src/project.dart#L502-L504
https://github.com/flutter/flutter/blob/d0e45a2369e9b7603c5d8ca33280128fba01de38/packages/flutter_tools/lib/src/project.dart#L506-L509
https://github.com/flutter/flutter/blob/d0e45a2369e9b7603c5d8ca33280128fba01de38/packages/flutter_tools/lib/src/project.dart#L511-L514

Generally the current approach using Regexes to check the Android project properties is very error-prone. We might investigate whether there are better alternatives.

## Workaround

For now you can fix the build by include a `build.gradle` file referencing the `build.gradle.kts` file:

```gradle
apply from: "build.gradle.kts"
```

This will work around the check in [`isUsingGradle`](https://github.com/flutter/flutter/blob/d0e45a2369e9b7603c5d8ca33280128fba01de38/packages/flutter_tools/lib/src/project.dart#L503), but won't fix the other occurences.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by budioktaviyan** [comment]
Hi, this issue still happen on latest stable branch

`[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-ID)
    • Flutter version 1.12.13+hotfix.7 at /Users/budioktaviyan/Library/Google/flutter
    • Framework revision 9f5ff2306b (4 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/budioktaviyan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/budioktaviyan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_202-release"
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version openjdk version "1.8.0_202-release"

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!`

**Comment by onuryarar** [comment]
Hello, 
have you tried to go back to the previous version? 
I have had the same problem after updating the flutter and when I downloaded and installed the previous version (**v1.12.13+hotfix.5**), the problem was solved.
[Flutter SDK Relases](https://flutter.dev/docs/development/tools/sdk/releases)
I hope that will be useful.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Albert221** [comment]
Hi! This issue still happens on the latest stable (1.22.5) and on the master. The [packages/flutter_tools/lib/src/project.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/project.dart) still relies on regexes in `build.gradle` file to perform checks.

This is NOT different on different setups. Flutter tool just doesn't work with the Gradle Kotlin DSL.

In Gradle Kotlin DSL, gradle files may end not with `.gradle` but with `.gradle.kts` and also the syntax can be different, so that the regular expressions won't match.

Please, reopen this issue.

**Comment by iapicca** [comment]
@Albert221 
please follow the indications [above](https://github.com/flutter/flutter/issues/33762#issuecomment-582797932)
