### ISSUE TITLE
Map plugin iOS  example does not build

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34042]
Cloned the repo afresh and here's the error
`/Users/a/Documents/flutterplugins/packages/google_maps_flutter/example/ios/Pods/Headers/Public/GoogleMaps/GoogleMaps/GMSAddress.h:14:9: Module 'GoogleMapsBase' not found`

Seemingly fixed by manually adding this path to framework search paths (target google_maps_flutter):
/Users/a/Documents/flutterplugins/packages/google_maps_flutter/example/ios/Pods/GoogleMaps/Base/Frameworks

But since it does not show up in git it must be an ignored file somewhere.

**Comment by iskakaushik** [comment]
Should be fixed by https://github.com/flutter/plugins/pull/1734

**Comment by duzenko** [comment]
Still fails to build for me in master branch. I'm on pod version 1.5.0.

**Comment by mikhail-tokarev** [comment]
Hi @duzenko 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by duzenko** [comment]
> 
> 
> Hi @duzenko
> are you still experiencing this issue with the latest version of Flutter?
> If so please reply attaching your `flutter doctor -v`

Yes I am: `ld: library not found for -lgoogle_maps_flutter`

```
Antons-Mac:pavement a$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-UA)
    • Flutter version 1.9.1+hotfix.4 at /Applications/flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by iapicca** [comment]
Hi @duzenko 
if you could also post
a self contained app on github
it would help to reproduce the issue,
thank you

**Comment by duzenko** [comment]
> 
> 
> Hi @duzenko
> if you could also post
> a self contained app on github
> it would help to reproduce the issue,
> thank you

https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/example

**Comment by jmagman** [comment]
> https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/example

I deleted my ModuleCache, and I'm not able to reproduce in the example app.  Also not able to reproduce on a new `flutter create`d app.

I'm about to add module support to that plugin, so it may be fixed with that.

**Comment by duzenko** [comment]
> 
> 
> > https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/example
> 
> I deleted my ModuleCache

How do I do that?

**Comment by jmagman** [comment]
> How do I do that?

Quit Xcode and rm DerivedData/ModuleCache.noindex.

**Comment by duzenko** [comment]
> 
> 
> > How do I do that?
> 
> Quit Xcode and rm DerivedData/ModuleCache.noindex.

```
Antons-Mac:takenote a$ rm DerivedData/ModuleCache.noindex
rm: DerivedData/ModuleCache.noindex: No such file or directory
```

**Comment by jmagman** [comment]
> Consider the fact that not everyone knows what DerivedData or ModuleCache are.

I wasn't suggesting that was a fix.  I'm trying to track down the bug, and I thoroughly tried to reproduce and couldn't.  I was documenting my steps to point out that https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/example is not on its own sufficient to reproduce.

**Comment by duzenko** [comment]
XCode - File - Open - iOS/Runner - > Cmd-R

**Comment by jmagman** [comment]
Did you open Runner.xcworkspace and not Runner.xcodeproj?

**Comment by duzenko** [comment]
> 
> 
> Did you open Runner.xcworkspace and not Runner.xcodeproj?

The .xcworkspace in master seems to build for me today

**Comment by jmagman** [comment]
So were you opening the xcodeproj before?

**Comment by duzenko** [comment]
Either that or I was not on HEAD

**Comment by jmagman** [comment]
@duzenko Can we close this?  I'm not sure there's enough actionable information here.
