### ISSUE TITLE
Can't trigger paste toolbar when empty text for TextField

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter#34215]
## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              Text('input 1'),
              TextField(
                autofocus: true,
              ),
              Text('input 2'),
              TextField()
            ],
          ),
        ),
      ),
    );
  }
}

```

#### empty text case
1. run example and make sure you have a copied text
2. long tap on textfield, the paste toolbar doesn't show up. (this is a bug)
3. double tap on textfield, the paste toolbar doesn't show up. (this is a bug)
4. type a word, and do step 2 and 3, you can get it in both steps.

#### switch textfield case

1. run example and make sure you have a copied text
2. assume current focus is on first field.
3. long tap on text field 1, the paste toolbar doesn't show up. (this is a bug)
4. tap on text field to focus on it, long tap on it and the paste toolbar show up.
5. you can't hide the toolbar anymore except close keyboard/type words/change focus. (this is a bug)

already tried on 1.7.0, 1.7.3 and today's master branch. no lucky. : (

## Logs

```
$ flutter analyze
Analyzing flutter...
No issues found! (ran in 13.1s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.7.2-pre.108, on Mac OS X 10.14.5 18F132, locale en-TW)
    • Flutter version 1.7.2-pre.108 at /Users/jerry/Documents/project/flutter
    • Framework revision e9ca112e44 (5 hours ago), 2019-06-10 19:17:55 -0700
    • Engine revision 4c0daaca27
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 7f146e431e)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[✓] Connected device (2 available)
    • iPhone Xs • B14E00B6-35BA-4FBE-8CCB-340589DEAC94 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by jaysson** [comment]
Try removing `autofocus`.

**Comment by jerrywell** [comment]
this workaround works, thanks.
but we can't remove it because the UX is pretty bad : (

**Comment by justinmc** [comment]
Thanks for the clear issue, I can reproduce every bug you pointed out on both Android and iOS.

Good to know that there is a workaround, but that definitely shouldn't be the behavior when autofocus is set, so we should fix this.

**Comment by jerrywell** [comment]
the root cause is at the line: https://github.com/flutter/flutter/blame/master/packages/flutter/lib/src/rendering/editable.dart#L366

```
void _handlePotentialSelectionChange(
  TextSelection nextSelection,
  SelectionChangedCause cause,
) {
  if (nextSelection == selection) {
    return;
  }
  onSelectionChanged(nextSelection, this, cause);
}
```

which is a side effect of the fix: https://github.com/flutter/flutter/commit/6031c56d4ccfc70656d1a7aff93b913b4476e1bc

the workaround is remove the comparison:
```
 if (nextSelection == selection) {
    return;
 }
```

but this will bring the #32911 issue back.

**Comment by justinmc** [comment]
Related: https://github.com/flutter/flutter/issues/33293

**Comment by justinmc** [comment]
All of these cases should be fixed in the next release (1.8.1+) with the PR referenced above.  Make sure you're on the right [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) to get it.

**Comment by vargavince91** [comment]
I think the case where the text field wasn't empty, then the user removed all text is still not covered, in that case, the "Paste" toolbar is not showing up.

See the issue I just opened: https://github.com/flutter/flutter/issues/36758

**Comment by irfantusneem** [comment]
This is still an open issue.

**Comment by justinmc** [comment]
@irfantusneem Does https://github.com/flutter/flutter/issues/48434 cover the problem you're seeing with this?

**Comment by irfantusneem** [comment]
Not exactly.  Long press or double tap do not work in the text field if
there is no text already present.  If I strip the app down to just the text
field or a trivial app then it works as expected.

Irfan

**Comment by AlexVincent525** [comment]
Yes, still not showing paste when textfield is empty.

**Comment by SzuwarJr** [comment]
Maybe it will help:
https://stackoverflow.com/questions/6414540/missing-copy-paste-menu-in-uitextfield-uiwebview/60632410#60632410
