### ISSUE TITLE
Remove PlatformViewsController conditionals in TextInputPlugin once new embedding includes PlatformViewController

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#34286]
Remove PlatformViewsController conditionals in TextInputPlugin once new embedding includes PlatformViewController

**Comment by mtallenca** [comment]
Not sure if this is related - but I'm getting an occasional crash on Android.   Stack trace is always the same.  Happens when I have a flutter app open that has a platform webview on screen.  I swipe up to switch to a different app to take notes - with the keyboard still up - switch back to flutter app.  Flutter app crashes with the following trace.   Looks like flutter is trying to attach keyboard - which is in the process of closing because of the app swap.

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
	at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:195)
	at io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:397)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1290)
	at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1574)
	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2600)
	at android.view.ViewRootImpl.access$900(ViewRootImpl.java:132)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by matthew-carroll** [comment]
I don't think your issue is related to this ticket, but I'll CC @amirh about the issue.

**Comment by amirh** [comment]
Yes, unrelated to this ticket, please file a separate issue. (you might be hitting the issue that's fixed by https://github.com/flutter/engine/pull/9423 but I can't be certain based just on this descripiton)

**Comment by jyp334** [comment]
Excuse me, has this problem been solved?Because I had the same problem, the same error log.My flutter version is 1.7.6

**Comment by jyp334** [comment]
> Not sure if this is related - but I'm getting an occasional crash on Android. Stack trace is always the same. Happens when I have a flutter app open that has a platform webview on screen. I swipe up to switch to a different app to take notes - with the keyboard still up - switch back to flutter app. Flutter app crashes with the following trace. Looks like flutter is trying to attach keyboard - which is in the process of closing because of the app swap.
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
> at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:195)
> at io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:397)
> at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1290)
> at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1574)
> at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2600)
> at android.view.ViewRootImpl.access$900(ViewRootImpl.java:132)
> at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4182)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:193)
> at android.app.ActivityThread.main(ActivityThread.java:6718)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Excuse me, has this problem been solved?Because I had the same problem, the same error log

**Comment by matthew-carroll** [comment]
Hi @jyp334. The problem your describing is unrelated to this issue. Can you please file a new bug with appropriate reproduction steps and your Flutter doctor info?

**Comment by matthew-carroll** [comment]
Done here: https://github.com/flutter/engine/pull/9938

**Comment by luffynas** [comment]
@matthew-carroll this issues still occurs, please read https://github.com/flutter/flutter/issues/38668#issuecomment-522221140

**Comment by matthew-carroll** [comment]
@luffynas this ticket was a work-item rather than a bug fix. I believe the issue that you're interested in is here: https://github.com/flutter/flutter/issues/36453
