### ISSUE TITLE
Crash on iOS when going to google maps, go back and then press some widget.

### ISSUE THREAD

**Issue by Dominic12** [flutter/flutter#34509]
## Steps to Reproduce

Hi Folks,

I have an App which has google maps implemented and some firebase functions.
When i go to google maps and then wait for approximately 5 seconds and then switch back to a selection and click any widget, the app crashes. This does only affect iOS.

## Logs

```

thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x00000001a48bc568 GLEngine`gleRunVertexSubmitARM + 2860
    frame #1: 0x00000001a48b9914 GLEngine`gleSetVertexArrayFunc + 144
    frame #2: 0x00000001a4861438 GLEngine`glDrawElementsInstanced_ACC_ES2Exec + 704
    frame #3: 0x0000000105393650 Flutter`GrGLGpu::sendIndexedInstancedMeshToGpu(GrPrimitiveType, GrBuffer const*, int, int, GrBuffer const*, int, GrBuffer const*, int, int, GrPrimitiveRestart) + 272
    frame #4: 0x00000001053936bc Flutter`non-virtual thunk to GrGLGpu::sendIndexedInstancedMeshToGpu(GrPrimitiveType, GrBuffer const*, int, int, GrBuffer const*, int, GrBuffer const*, int, int, GrPrimitiveRestart) + 36
    frame #5: 0x0000000105393118 Flutter`GrMesh::sendToGpu(GrMesh::SendToGpuImpl*) const + 224
    frame #6: 0x0000000105392fb4 Flutter`GrGLGpu::draw(GrRenderTarget*, GrSurfaceOrigin, GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, GrMesh const*, int) + 544
    frame #7: 0x0000000105396fcc Flutter`GrGLGpuRTCommandBuffer::onDraw(GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, GrMesh const*, int, SkRect const&) + 56
    frame #8: 0x0000000105306cd8 Flutter`GrGpuRTCommandBuffer::draw(GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, GrMesh const*, int, SkRect const&) + 192
    frame #9: 0x0000000105347b2c Flutter`GrFillRRectOp::onExecute(GrOpFlushState*, SkRect const&) + 1484
    frame #10: 0x000000010531ddc4 Flutter`GrOp::execute(GrOpFlushState*, SkRect const&) + 236
    frame #11: 0x000000010531dc58 Flutter`GrRenderTargetOpList::onExecute(GrOpFlushState*) + 452
    frame #12: 0x00000001052ffaa0 Flutter`GrDrawingManager::executeOpLists(int, int, GrOpFlushState*, int*) + 448
    frame #13: 0x00000001052ff704 Flutter`GrDrawingManager::flush(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrPrepareForExternalIORequests const&) + 1436
    frame #14: 0x00000001052ffbe8 Flutter`GrDrawingManager::flushSurfaces(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&) + 124
    frame #15: 0x000000010531b2a4 Flutter`GrRenderTargetContext::flush(SkSurface::BackendSurfaceAccess, GrFlushInfo const&) + 280
    frame #16: 0x00000001053addf4 Flutter`SkGpuDevice::flush() + 36
    frame #17: 0x00000001055152d4 Flutter`flutter::GPUSurfaceGL::PresentSurface(SkCanvas*) + 240
    frame #18: 0x00000001051e2cd0 Flutter`flutter::SurfaceFrame::PerformSubmit() + 88
    frame #19: 0x00000001051e2c68 Flutter`flutter::SurfaceFrame::Submit() + 36
    frame #20: 0x00000001051d469c Flutter`flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) + 268
    frame #21: 0x00000001051d49b4 Flutter`flutter::Rasterizer::DoDraw(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >) + 88
    frame #22: 0x00000001051d566c Flutter`std::__1::__function::__func<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) + 56
    frame #23: 0x00000001051d4af0 Flutter`flutter::Pipeline<flutter::LayerTree>::Consume(std::__1::function<void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>) + 188
    frame #24: 0x00000001051d47ec Flutter`flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) + 144
    frame #25: 0x00000001051e0b54 Flutter`std::__1::__function::__func<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_24, std::__1::allocator<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_24>, void ()>::operator()() + 72
    frame #26: 0x0000000105194618 Flutter`fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) + 836
    frame #27: 0x0000000105197bf8 Flutter`fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
    frame #28: 0x000000018328f650 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
    frame #29: 0x000000018328f380 CoreFoundation`__CFRunLoopDoTimer + 864
    frame #30: 0x000000018328ebb4 CoreFoundation`__CFRunLoopDoTimers + 248
    frame #31: 0x0000000183289b04 CoreFoundation`__CFRunLoopRun + 1844
    frame #32: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #33: 0x000000018548979c GraphicsServices`GSEventRunModal + 104
    frame #34: 0x00000001afc03978 UIKitCore`UIApplicationMain + 212
  * frame #35: 0x0000000102a28ae8 Runner`main(argc=1, argv=0x000000016d3dbb28) at main.m:7:12
    frame #36: 0x0000000182d4e8e0 libdyld.dylib`start + 4
  thread #2, queue = 'com.google.firebase.firestore.rpc'
    frame #0: 0x0000000182e9bfd8 libsystem_kernel.dylib`poll + 8
    frame #1: 0x0000000106f9393c grpc`pollset_work(pollset=0x00000001090181e8, worker_hdl=0x0000000000000000, deadline=9223372036854775807) at ev_poll_posix.cc:1012:11
    frame #2: 0x0000000106f971dc grpc`pollset_work(pollset=0x00000001090181e8, worker=0x0000000000000000, deadline=9223372036854775807) at ev_posix.cc:322:21
    frame #3: 0x000000010700a32c grpc`grpc_pollset_work(pollset=0x00000001090181e8, worker=0x0000000000000000, deadline=9223372036854775807) at pollset.cc:48:10
    frame #4: 0x0000000106f80c14 grpc`cq_next(cq=0x00000001090180e0, deadline=(tv_sec = 9223372036854775807, tv_nsec = 0, clock_type = GPR_CLOCK_REALTIME), reserved=0x0000000000000000) at completion_queue.cc:1030:23
    frame #5: 0x0000000106f80090 grpc`::grpc_completion_queue_next(cq=0x00000001090180e0, deadline=(tv_sec = 9223372036854775807, tv_nsec = 0, clock_type = GPR_CLOCK_REALTIME), reserved=0x0000000000000000) at completion_queue.cc:1106:10
    frame #6: 0x00000001073b0f68 grpcpp`grpc_impl::CompletionQueue::AsyncNextInternal(this=0x0000000282239658, tag=0x000000016d4627e8, ok=0x000000016d4627e7, deadline=(tv_sec = 9223372036854775807, tv_nsec = 0, clock_type = GPR_CLOCK_REALTIME)) at completion_queue_cc.cc:48:15
    frame #7: 0x0000000102ab0224 Runner`grpc_impl::CompletionQueue::Next(this=0x0000000282239658, tag=0x000000016d4627e8, ok=0x000000016d4627e7) at completion_queue_impl.h:179:13
    frame #8: 0x0000000102ab0108 Runner`firebase::firestore::remote::Datastore::PollGrpcQueue(this=0x0000000282239618) at datastore.mm:143:22
    frame #9: 0x0000000102ab7160 Runner`firebase::firestore::remote::Datastore::Start(this=0x0000000281e2a8c8)::$_0::operator()() const at datastore.mm:116:35
    frame #10: 0x0000000102ab7124 Runner`decltype(__f=0x0000000281e2a8c8)::$_0&>(fp)()) std::__1::__invoke<firebase::firestore::remote::Datastore::Start()::$_0&>(firebase::firestore::remote::Datastore::Start()::$_0&) at type_traits:4339:1
    frame #11: 0x0000000102ab70d8 Runner`void std::__1::__invoke_void_return_wrapper<void>::__call<firebase::firestore::remote::Datastore::Start(__args=0x0000000281e2a8c8)::$_0&>(firebase::firestore::remote::Datastore::Start()::$_0&) at __functional_base:349:9
    frame #12: 0x0000000102ab59dc Runner`std::__1::__function::__func<firebase::firestore::remote::Datastore::Start()::$_0, std::__1::allocator<firebase::firestore::remote::Datastore::Start()::$_0>, void ()>::operator(this=0x0000000281e2a8c0)() at functional:1562:12
    frame #13: 0x0000000102be0c90 Runner`std::__1::function<void ()>::operator(this= Lambda in File datastore.mm at Line 116)() const at functional:1913:12
    frame #14: 0x0000000102b00958 Runner`firebase::firestore::util::internal::DispatchAsync(this=0x0000000281e2a8c0, raw_work=0x0000000281e2a8c0)>&&)::$_0::operator()(void*) const at executor_libdispatch.mm:57:5
    frame #15: 0x0000000102b00928 Runner`firebase::firestore::util::internal::DispatchAsync(raw_work=0x0000000281e2a8c0)>&&)::$_0::__invoke(void*) at executor_libdispatch.mm:55:33
    frame #16: 0x0000000182d3d7d4 libdispatch.dylib`_dispatch_client_callout + 16
    frame #17: 0x0000000182d18dec libdispatch.dylib`_dispatch_lane_serial_drain$VARIANT$armv81 + 548
    frame #18: 0x0000000182d1992c libdispatch.dylib`_dispatch_lane_invoke$VARIANT$armv81 + 408
    frame #19: 0x0000000182d21e08 libdispatch.dylib`_dispatch_workloop_worker_thread + 584
    frame #20: 0x0000000182f1d114 libsystem_pthread.dylib`_pthread_wqthread + 304
    frame #21: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #4
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d138 libsystem_pthread.dylib`_pthread_wqthread + 340
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #5, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000183c56fac Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
    frame #6: 0x0000000183c56e3c Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 96
    frame #7: 0x00000001afce9494 UIKitCore`-[UIEventFetcher threadMain] + 136
    frame #8: 0x0000000183d836a4 Foundation`__NSThread__start__ + 984
    frame #9: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #10: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #11: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #6, name = 'io.flutter.1.ui'
    frame #0: 0x0000000105701578 Flutter`dart::Thread::EnterApiScope() + 28
    frame #1: 0x00000001058a48d8 Flutter`Dart_EnterScope + 152
    frame #2: 0x0000000105480600 Flutter`tonic::DartState::Scope::Scope(std::__1::shared_ptr<tonic::DartState>) + 32
    frame #3: 0x00000001051c8434 Flutter`flutter::RuntimeController::NotifyIdle(long long) + 96
    frame #4: 0x00000001051cfcb0 Flutter`flutter::Engine::NotifyIdle(long long) + 120
    frame #5: 0x00000001051cce88 Flutter`flutter::Animator::AwaitVSync() + 172
    frame #6: 0x0000000105194618 Flutter`fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) + 836
    frame #7: 0x0000000105197bf8 Flutter`fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
    frame #8: 0x000000018328f650 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
    frame #9: 0x000000018328f380 CoreFoundation`__CFRunLoopDoTimer + 864
    frame #10: 0x000000018328ebb4 CoreFoundation`__CFRunLoopDoTimers + 248
    frame #11: 0x0000000183289b04 CoreFoundation`__CFRunLoopRun + 1844
    frame #12: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #13: 0x0000000105197d1c Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #14: 0x0000000105194258 Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #15: 0x0000000105197234 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #16: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #17: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #18: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #7, name = 'io.flutter.1.gpu'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000105197d1c Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #6: 0x0000000105194258 Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #7: 0x0000000105197234 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #8, name = 'io.flutter.1.io'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000105197d1c Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #6: 0x0000000105194258 Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #7: 0x0000000105197234 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #9, name = 'dart:io EventHandler'
    frame #0: 0x0000000182e9b8f4 libsystem_kernel.dylib`kevent + 8
    frame #1: 0x0000000105486a70 Flutter`dart::bin::EventHandlerImplementation::EventHandlerEntry(unsigned long) + 232
    frame #2: 0x00000001054a23c0 Flutter`dart::bin::ThreadStart(void*) + 48
    frame #3: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #4: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #5: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #10, name = 'Dart ThreadPool Worker'
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194a4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x000000010567d170 Flutter`dart::Monitor::Wait(long long) + 156
    frame #3: 0x000000010580c6ec Flutter`dart::BackgroundCompiler::Run() + 812
    frame #4: 0x0000000105702868 Flutter`dart::ThreadPool::Worker::Loop() + 200
    frame #5: 0x00000001057026a4 Flutter`dart::ThreadPool::Worker::Main(unsigned long) + 176
    frame #6: 0x000000010567c98c Flutter`dart::ThreadStart(void*) + 76
    frame #7: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #8: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #9: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #11
    frame #0: 0x0000000182f1fcd0 libsystem_pthread.dylib`start_wqthread
  thread #12, name = 'com.apple.CFSocket.private'
    frame #0: 0x0000000182e9a328 libsystem_kernel.dylib`__select + 8
    frame #1: 0x00000001832976f4 CoreFoundation`__CFSocketManager + 620
    frame #2: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #3: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #4: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #13, name = 'io.flutter.plugins.location_background.2.ui'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000105197d1c Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #6: 0x0000000105194258 Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #7: 0x0000000105197234 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #14, name = 'io.flutter.plugins.location_background.2.gpu'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000105197d1c Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #6: 0x0000000105194258 Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #7: 0x0000000105197234 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #15, name = 'io.flutter.plugins.location_background.2.io'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000105197d1c Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #6: 0x0000000105194258 Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #7: 0x0000000105197234 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #16, name = 'com.apple.NSURLConnectionLoader'
    frame #0: 0x0000000182e8f0f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000182e8e5a0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018328ea10 CoreFoundation`__CFRunLoopServiceMachPort + 236
    frame #3: 0x0000000183289920 CoreFoundation`__CFRunLoopRun + 1360
    frame #4: 0x00000001832890b0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x00000001838a274c CFNetwork`-[__CoreSchedulingSetRunnable runForever] + 216
    frame #6: 0x0000000183d836a4 Foundation`__NSThread__start__ + 984
    frame #7: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #8: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #9: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #17
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194a4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x00000001078dfc54 leveldb`leveldb::(anonymous namespace)::PosixEnv::BGThread(this=0x0000000109016a10) at env_posix.cc:640:27
    frame #3: 0x00000001078dfa7c leveldb`leveldb::(anonymous namespace)::PosixEnv::BGThreadWrapper(arg=0x0000000109016a10) at env_posix.cc:555:39
    frame #4: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #5: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #6: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #18
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194a4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x0000000107060bd4 grpc`::gpr_cv_wait(cv=0x0000000109017b20, mu=0x0000000109017ad0, abs_deadline=(tv_sec = 9223372036854775807, tv_nsec = 0, clock_type = GPR_CLOCK_MONOTONIC)) at sync_posix.cc:217:11
    frame #3: 0x0000000106f991a4 grpc`grpc_core::Executor::ThreadMain(arg=0x0000000109017ad0) at executor.cc:245:7
    frame #4: 0x000000010706c2dc grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(this=0x000000028103b4e0, v=2 elements)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const at thd_posix.cc:114:27
    frame #5: 0x000000010706c200 grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(v=2 elements)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) at thd_posix.cc:84:25
    frame #6: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #7: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #8: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #19
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194a4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x0000000107060bd4 grpc`::gpr_cv_wait(cv=0x0000000109017c90, mu=0x0000000109017c40, abs_deadline=(tv_sec = 9223372036854775807, tv_nsec = 0, clock_type = GPR_CLOCK_MONOTONIC)) at sync_posix.cc:217:11
    frame #3: 0x0000000106f991a4 grpc`grpc_core::Executor::ThreadMain(arg=0x0000000109017c40) at executor.cc:245:7
    frame #4: 0x000000010706c2dc grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(this=0x000000028103bae0, v=0x000000028103bae0)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const at thd_posix.cc:114:27
    frame #5: 0x000000010706c200 grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(v=0x000000028103bae0)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) at thd_posix.cc:84:25
    frame #6: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #7: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #8: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #20
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194a4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x0000000107060bd4 grpc`::gpr_cv_wait(cv=0x00000001070ec258, mu=0x00000001070ec218, abs_deadline=(tv_sec = 9223372036854775807, tv_nsec = 0, clock_type = GPR_CLOCK_MONOTONIC)) at sync_posix.cc:217:11
    frame #3: 0x00000001070717cc grpc`wait_until(next=9223372036854775807) at timer_manager.cc:211:5
    frame #4: 0x0000000107071380 grpc`timer_main_loop() at timer_manager.cc:265:14
    frame #5: 0x0000000107071294 grpc`timer_thread(completed_thread_ptr=0x0000000281e2a860) at timer_manager.cc:294:3
    frame #6: 0x000000010706c2dc grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(this=0x000000028103bae0, v=0x000000028103bae0)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const at thd_posix.cc:114:27
    frame #7: 0x000000010706c200 grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(v=0x000000028103bae0)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) at thd_posix.cc:84:25
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #21
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194a4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x0000000107060c2c grpc`::gpr_cv_wait(cv=0x00000001070ec258, mu=0x00000001070ec218, abs_deadline=(tv_sec = 1560538320, tv_nsec = 245596791, clock_type = GPR_CLOCK_REALTIME)) at sync_posix.cc:233:11
    frame #3: 0x00000001070717cc grpc`wait_until(next=26060) at timer_manager.cc:211:5
    frame #4: 0x0000000107071380 grpc`timer_main_loop() at timer_manager.cc:265:14
    frame #5: 0x0000000107071294 grpc`timer_thread(completed_thread_ptr=0x0000000281f5d780) at timer_manager.cc:294:3
    frame #6: 0x000000010706c2dc grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(this=0x000000028106c3c0, v=0x000000028106c3c0)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const at thd_posix.cc:114:27
    frame #7: 0x000000010706c200 grpc`grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(v=0x000000028106c3c0)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) at thd_posix.cc:84:25
    frame #8: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #9: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #10: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #22
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d1f8 libsystem_pthread.dylib`_pthread_wqthread + 532
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #23
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d138 libsystem_pthread.dylib`_pthread_wqthread + 340
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #24
    frame #0: 0x0000000182f1fcd0 libsystem_pthread.dylib`start_wqthread
  thread #25
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d1f8 libsystem_pthread.dylib`_pthread_wqthread + 532
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #26
    frame #0: 0x0000000182f1fcd0 libsystem_pthread.dylib`start_wqthread
  thread #27
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d1f8 libsystem_pthread.dylib`_pthread_wqthread + 532
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #28
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d1f8 libsystem_pthread.dylib`_pthread_wqthread + 532
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #30, name = 'Dart ThreadPool Worker'
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194d8 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 680
    frame #2: 0x000000010567d260 Flutter`dart::Monitor::WaitMicros(long long) + 128
    frame #3: 0x000000010570280c Flutter`dart::ThreadPool::Worker::Loop() + 108
    frame #4: 0x00000001057026a4 Flutter`dart::ThreadPool::Worker::Main(unsigned long) + 176
    frame #5: 0x000000010567c98c Flutter`dart::ThreadStart(void*) + 76
    frame #6: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #7: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #8: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #31, name = 'Dart ThreadPool Worker'
    frame #0: 0x0000000182e99ee4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182f194d8 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 680
    frame #2: 0x000000010567d260 Flutter`dart::Monitor::WaitMicros(long long) + 128
    frame #3: 0x000000010570280c Flutter`dart::ThreadPool::Worker::Loop() + 108
    frame #4: 0x00000001057026a4 Flutter`dart::ThreadPool::Worker::Main(unsigned long) + 176
    frame #5: 0x000000010567c98c Flutter`dart::ThreadStart(void*) + 76
    frame #6: 0x0000000182f1c2c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #7: 0x0000000182f1c220 libsystem_pthread.dylib`_pthread_start + 44
    frame #8: 0x0000000182f1fcdc libsystem_pthread.dylib`thread_start + 4
  thread #32
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d1f8 libsystem_pthread.dylib`_pthread_wqthread + 532
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4
  thread #33
    frame #0: 0x0000000182e9ab74 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000182f1d138 libsystem_pthread.dylib`_pthread_wqthread + 340
    frame #2: 0x0000000182f1fcd4 libsystem_pthread.dylib`start_wqthread + 4

```

```
[✓] Flutter (Channel dev, v1.7.3, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.7.3 at /Users/dominicjarmann/Documents/developement/flutter
    • Framework revision 362b999b90 (7 days ago), 2019-06-07 12:43:27 -0700
    • Engine revision 0602dbb275
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 6e0d978505)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/dominicjarmann/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone • d738cbe523807492ac441d6e98d0f4bf8f0ac0d6 • ios • iOS 12.3.1

```

**Comment by Dominic12** [comment]
Workarround at [PR](https://github.com/flutter/engine/pull/9370)

**Comment by cyanglaz** [comment]
This crash should be fixed with https://github.com/flutter/engine/pull/9377. I'm closing the issue now. If you found any related issue applying the patch please free feel to open another issue with details or reopen this one.

**Comment by darren-f5s** [comment]
As stated in the thread you've linked to, this issue isn't solved

**Comment by cyanglaz** [comment]
@darren-f5s have you tried on master? Could you share the stack trace or any logs if any?

**Comment by pan-ng** [comment]
Ya I keep on getting this error also
```
Crashed: com.apple.main-thread
0  GLEngine                       0x25d370d18 gleRunVertexSubmitARM + 2864
1  (Missing)                      0x69b4825d36e0b8 (Missing)
2  (Missing)                      0x3e7b825d36e038 (Missing)
3  (Missing)                      0x709f825d314f88 (Missing)
4  (Missing)                      0x7ec6823ed4f5d4 (Missing)
5  (Missing)                      0xc20105f655bc (Missing)
6  Flutter                        0x105f65668 (Missing)
7  Flutter                        0x105f6d4c4 (Missing)
8  Flutter                        0x105edf034 (Missing)
9  Flutter                        0x105f1db08 (Missing)
10 Flutter                        0x105ef4744 (Missing)
11 Flutter                        0x105ef45d8 (Missing)
12 Flutter                        0x105ed882c (Missing)
13 Flutter                        0x105ed90e0 (Missing)
14 Flutter                        0x105ef35e0 (Missing)
15 Flutter                        0x105f8403c (Missing)
16 Flutter                        0x1060d77a0 (Missing)
17 Flutter                        0x105dcd82c (Missing)
18 Flutter                        0x105dbdcfc (Missing)
19 Flutter                        0x105dbe17c (Missing)
20 Flutter                        0x105dbe88c (Missing)
21 Flutter                        0x105dbdff0 (Missing)
22 Flutter                        0x105dc367c (Missing)
23 Flutter                        0x105d82b90 (Missing)
24 Flutter                        0x105d84144 (Missing)
25 CoreFoundation                 0x23ba72aa8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
26 (Missing)                      0x11f6023ba727d4 (Missing)
27 (Missing)                      0x15b0823ba71fb8 (Missing)
28 (Missing)                      0x6b3823ba6cc88 (Missing)
29 (Missing)                      0x1072823ba6c254 (Missing)
30 (Missing)                      0x2e97823dcabd8c (Missing)
31 (Missing)                      0x55f48268db44c0 (Missing)
32 (Missing)                      0x78db0104d1b054 (Missing)
33 libdyld.dylib                  0x23b528fd8 start + 4
```

**Comment by cyanglaz** [comment]
@pan-ng The temporary fix was committed on Jun 20th.https://github.com/flutter/engine/pull/9377
Could you try on master to see if it still crashes for you?

**Comment by darren-f5s** [comment]
Still an issue even when on the latest version of flutter: https://github.com/flutter/flutter/issues/40650

**Comment by radvansky-tomas** [comment]
@darren-f5s same here

**Comment by j05u3** [comment]
I believe I have a similar issue, I just posted it here #49093

**Comment by sanekyy** [comment]
Same crash in our production app for iOS with google_maps_flutter plugin.

**Comment by iapicca** [comment]
Hi @Dominic12 
does the workaround in @j05u3 link works for you as well?
thank you

**Comment by sanekyy** [comment]
Hi there. We fixed crash in our project. I described our workaround [here](https://github.com/flutter/flutter/issues/49093#issuecomment-582365851).

**Comment by sanekyy** [comment]
Hi there. We fixed similar crash in our project. I described our workaround [here](https://github.com/flutter/flutter/issues/49093#issuecomment-582365851).

**Comment by sanekyy** [comment]
Got another crash.
![image](https://user-images.githubusercontent.com/18647037/74029669-3f219200-49be-11ea-99b4-bb04f6413ea6.png)

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
