### ISSUE TITLE
Error: The getter 'toolbarIsVisible' was called on null.

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#34571]
## Logs
NoSuchMethodError: The getter 'toolbarIsVisible' was called on null.
Receiver: null
Tried calling: toolbarIsVisible
at EditableTextState.toggleToolbar	(editable_text.dart:1503 )
at _TextFieldState._handleSingleLongTapEnd	(text_field.dart:822 )
at _TextSelectionGestureDetectorState._handleLongPressEnd	(text_selection.dart:1019 )
at LongPressGestureRecognizer._checkLongPressEnd.<anonymous closure>	(long_press.dart:302 )
at GestureRecognizer.invokeCallback	(recognizer.dart:182 )
at LongPressGestureRecognizer._checkLongPressEnd	(long_press.dart:302 )
at LongPressGestureRecognizer.handlePrimaryPointer	(long_press.dart:247 )
at PrimaryPointerGestureRecognizer.handleEvent	(recognizer.dart:455 )
at PointerRouter._dispatch	(pointer_router.dart:75 )
at PointerRouter.route	(pointer_router.dart:102 )
at _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent	(binding.dart:218 )
at _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent	(binding.dart:198 )
at _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent	(binding.dart:156 )
at _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue	(binding.dart:102 )
at _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket	(binding.dart:86 )
at _rootRunUnary	(zone.dart:1136 )
at _CustomZone.runUnary	(zone.dart:1029 )
at _CustomZone.runUnaryGuarded	(zone.dart:931 )
at _invoke1	(hooks.dart:250 )
at _dispatchPointerDataPacket	(hooks.dart:159 )

**Comment by HansMuller** [comment]
cc @justinmc

**Comment by justinmc** [comment]
I believe this was fixed in https://github.com/flutter/flutter/pull/34055, which means that you need version 1.7.4 or above to get it, or use the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).

@cvolzke4 Let me know if you can reproduce this on master.

**Comment by skzwksk** [comment]
not fixed this issue.
i faced this error.
flutter v1.12.13+hotfix.6
android

**Comment by justinmc** [comment]
@sudha-anecure Thanks! I've opened an issue to try to gather more information: https://github.com/flutter/flutter/issues/64471

Hopefully the issue has been fixed in later versions of Flutter, so for now I recommend you upgrade. If it still exists, please post on that issue so we can try to figure out how to reproduce this.  It seems to have to do with tapping on the text selection handles.
