### ISSUE TITLE
[Web] Dartev compile Error http module

### ISSUE THREAD

**Issue by iamsabet** [flutter/flutter#34858]
hi im trying to run an existing flutter app (witch is ok for mobile and desktop) on web , (new way)
i have master version of flutter 

dartdev compile error http module , i tried with dart2js got exact same error
im a little new to this flutter thing , i appreciate a little light here 
flutter run -p web 
throws error
<img width="979" alt="Screen Shot 2019-06-21 at 8 27 42 PM" src="https://user-images.githubusercontent.com/20267993/59936295-e3bd8680-9464-11e9-9a13-bbeccbf0791d.png">

pubspce : 

`name: myapp
version : 0.0.1
environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  equatable: ^0.2.4
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  intl: ^0.15.8
  shared_preferences: 0.5.3+1
  build_runner: any
  build_web_compilers: ^2.1.1
  test: ^1.3.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

`

**Comment by jonahwilliams** [comment]
Hi @iamsabet, can you try removing build_runner, build_web_compilers, and test from your direct dependencies - then run `flutter clean` and `flutter packages get` and try again?

**Comment by iamsabet** [comment]
hey @jonahwilliams thanks for response , i just did what you said , ... its still the same

**Comment by iamsabet** [comment]
1 General question , does flutter web gonna cover all flutter for web completely in the future ? (except for mobile device native modules to access hardware like , camera , sensors ... ) ?
@jonahwilliams

**Comment by jonahwilliams** [comment]
It looks like in this case I've misconfigured the builders, I'll look into this.

> General question , does flutter web gonna cover all flutter for web completely in the future

Flutter only handle supporting the plugin API, and it is up to the plugin implementations to support what the device is capable of. You could imagine implementing the shared_preferences plugins in terms of local storage for the web, for example. That said, not all plugins will work on all platforms.

**Comment by jonahwilliams** [comment]
I'm not able to reproduce this just with your set of dependencies. Can you narrow this down to a particular reproducible case?

**Comment by rostopira** [comment]
I think, this issue should be reopened

**Comment by Solido** [comment]
I'm also using `build_runner: ^1.6.5` 
Going with the `flutter generate` way get the same result.

**Comment by Solido** [comment]
@jonahwilliams This is a test drive I can share the sources if it helps to reproduce.

**Comment by jonahwilliams** [comment]
I have a pending fix in https://github.com/dart-lang/build/pull/2404. Once that lands I'll update the tool and that should resolve it

**Comment by cbenhagen** [comment]
Still getting:
```
[ +314 ms] Dart2Js finished with:

                    packages/http/src/multipart_file.dart:14:8:
                    Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
                    import 'multipart_file_stub.dart'
                           ^
                    packages/http/src/multipart_file.dart:93:7:
                    Error: Method not found: 'multipartFileFromPath'.
                          multipartFileFromPath(field, filePath,
                          ^^^^^^^^^^^^^^^^^^^^^
                    Error: Compilation failed.
```

on latest master when running `flutter build web --release`. I am NOT using the forked `flutter_web`.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.1-pre.85, on Mac OS X 10.14.6 18G87, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

• No issues found!
```

```
  build_runner: ^1.6.6
  build_web_compilers: ^2.2.3
```

**Comment by jonahwilliams** [comment]
I'm no longer able to reproduce with a simple import of `package:http`. Could you post your pubspec.yaml and an example that reproduces the above error for you?

**Comment by Solido** [comment]
I did not used the release command so testing it now I get 

```
Dart2Js finished with:

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading
'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Error compiling dartdevc module:hrpath_forms|test/widget_test.ddc.js

test/widget_test.dart.browser_test.dart:22:43: Error: Getter not found: 'main'.
  internalBootstrapBrowserTest(() => test.main);
                                          ^^^^

```

Dependencies 

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  chopper: ^3.0.0
  validators: ^2.0.0+1
  provider: ^3.0.0+1

  #
  breakpoint: ^1.0.0
  responsive_scaffold: ^1.1.0+3

  mobx: 0.3.5
  flutter_mobx: 0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.5
  mobx_codegen: 0.3.3+1
  chopper_generator: ^3.0.0
```

Thanks !

**Comment by jonahwilliams** [comment]
Ahh yes, this is still happening in release mode. On it

**Comment by jonahwilliams** [comment]
As a temporary workaround, in projects that use package:http you can import the BrowserClient directly.

```
import 'package:http/browser_client.dart';
```

instead of 

```
import 'package:http/http.dart';
```

This isn't useable by the mobile flutter however

**Comment by jonahwilliams** [comment]
Reopening due to temporary revert

**Comment by CaiJingLong** [comment]
Hi, this question has returned.
Create a new demo, introduce the http library 0.12.0+2 version.
`$ flutter build web`  will get log:

```bash
for_web_test flutter build web
Running "flutter pub get" in for_web_test...                        0.5s
Dart2Js finished with:

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Failed after 27.9s
Compiling lib/main.dart for the Web...                             39.1s
```

environment:
```
flutter --version
Flutter 1.10.2-pre.36 • channel master • https://github.com/flutter/flutter
Framework • revision 32c946f31b (5 hours ago) • 2019-09-10 20:49:27 -0700
Engine • revision 7ea9884ab0
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)
```

**Comment by maszhin** [comment]
I received similar issue with dart2js

```
flutter build web --release
Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

Error creating http|lib/http.ddc.dill                                   
Error creating kernel summary for module:http|lib/http.ddc.dill         

Response:--dart-sdk-summary=file:///Users/maverick/Documents/Flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--output=/private/var/folders/l4/0srdkmqs1vggbp9qrl2m6r3h0000gn/T/scratch_spaceJ0yJKT/packages/http/http.ddc.dill --packages-file=file:///var/folders/l4/0srdkmqs1vggbp9qrl2m6r3h0000gn/T/kernel_builder_eWSKK8/.packages
--multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/maverick/Documents/Flutter/bin/cache/flutter_web_sdk/libraries.json
--input-summary=org-dartlang-app:///packages/path/path.ddc.dill --input-summary=org-dartlang-app:///packages/http_parser/http_parser.ddc.dill --input-summary=org-dartlang-app:///packages/async/async.ddc.dill
--input-summary=org-dartlang-app:///packages/pedantic/pedantic.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill
--input-summary=org-dartlang-app:///packages/string_scanner/src/eager_span_scanner.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_data.ddc.dill
--input-summary=org-dartlang-app:///packages/source_span/source_span.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/ascii.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/charcode.ddc.dill
--input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill
--input-summary=org-dartlang-app:///packages/charcode/html_entity.ddc.dill --source=package:http/src/multipart_file_io.dart --source=package:http/src/multipart_file.dart --source=package:http/src/boundary_characters.dart
--source=package:http/src/streamed_request.dart --source=package:http/src/multipart_request.dart --source=package:http/http.dart
org-dartlang-app:///packages/http/src/multipart_file.dart:14:8: Error: Error when reading 'org-dartlang-app:///packages/http/src/multipart_file_stub.dart': File not found
import 'multipart_file_stub.dart'
       ^



                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
BuildStepCompletedException: Attempt to use a BuildStep after is has completed
                                                                        
AssetNotFoundException: http|lib/http.ddc.dill     
```

Flutter doctor:
````
[✓] Flutter (Channel master, v1.10.2-pre.36, on Mac OS X 10.14.6 18G87, locale en-NO)
    • Flutter version 1.10.2-pre.36 at /Users/maverick/Documents/Flutter
    • Framework revision 32c946f31b (5 hours ago), 2019-09-10 20:49:27 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/maverick/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/maverick/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/maverick/Library/Android/sdk
    • Java binary at: /Users/maverick/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/maverick/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Users/maverick/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools
```

**Comment by catalsdevelop** [comment]
same error when run `flutter run -d chrome --release`
my env
```
Flutter 1.10.2-pre.36 • channel master • https://github.com/flutter/flutter.git
Framework • revision 32c946f31b (8 hours ago) • 2019-09-10 20:49:27 -0700
Engine • revision 7ea9884ab0
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)
```

**Comment by ACChe** [comment]
After run `flutter clean` and `flutter run -d chrome -v`, the error came:
`[ +581 ms] 7.7s elapsed, 58/61 actions completed.
[ +213 ms] Error compiling dartdevc module:http|lib/http.ddc.js
                    
                    packages/http/src/multipart_file.dart:14:8: Error: Error when reading 'packages/http/src/multipart_file_stub.dart': File not found
                    import 'multipart_file_stub.dart'
                           ^
                    packages/http/src/multipart_file.dart:93:7: Error: Method not found: 'multipartFileFromPath'.
                          multipartFileFromPath(field, filePath,
                          ^^^^^^^^^^^^^^^^^^^^^
                    
[   +6 ms] Unable to read http|lib/http.ddc.js, check your console or the `.dart_tool/build/generated/http/lib/http.ddc.js.errors` log file.
[   +4 ms] AssetNotFoundException: wh_be|lib/main_web_entrypoint.ddc.js
[        ] #0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:126:34)
           <asynchronous suspension>
           #1      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:248:13)
           <asynchronous suspension>
           #2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)
           <asynchronous suspension>
           #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
           #4      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
           #5      Future.wait (dart:async/future.dart:393:26)
           #6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)
           #7      _rootRun (dart:async/zone.dart:1124:13)
           #8      _CustomZone.run (dart:async/zone.dart:1021:19)
           #9      _runZoned (dart:async/zone.dart:1516:10)
           #10     runZoned (dart:async/zone.dart:1500:12)
           #11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #12     runBuilder (package:build/src/generate/run_builder.dart:51:9)
           <asynchronous suspension>
           #13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:473:19)
           #14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:471:23)
           <asynchronous suspension>
           #16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:430:22)
           #18     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:426:17)
           #20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
           #21     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #22     Future.wait (dart:async/future.dart:393:26)
           #23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
           <asynchronous suspension>
           #24     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
           <asynchronous suspension>
           #25     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #26     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:316:47)
           <asynchronous suspension>
           #27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #28     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:310:32)
           #29     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           <asynchronous suspension>
           #30     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:267:26)
           <asynchronous suspension>
           #31     _rootRun (dart:async/zone.dart:1124:13)
           #32     _CustomZone.run (dart:async/zone.dart:1021:19)
           #33     _runZoned (dart:async/zone.dart:1516:10)
           #34     runZoned (dart:async/zone.dart:1500:12)
           #35     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:262:5)
           #36     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:209:24)
           <asynchronous suspension>
           #37     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:42)
           #38     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:100:35)
           <asynchronous suspension>
           #39     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #40     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #41     Server._build (package:build_daemon/src/server.dart:119:13)
           #42     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #43     _rootRunUnary (dart:async/zone.dart:1132:38)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #49     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #50     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #51     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #52     _rootRunUnary (dart:async/zone.dart:1132:38)
           #53     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #57     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
           #58     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
           #59     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #60     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #61     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
           #62     _rootRunUnary (dart:async/zone.dart:1132:38)
           #63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #68     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #69     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #70     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
           #71     _rootRunUnary (dart:async/zone.dart:1136:13)
           #72     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #76     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #77     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #78     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
           #80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
           #81     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[ +277 ms] Running build completed, took 8.0s

[        ] Caching finalized dependency graph...
[   +6 ms] Caching finalized dependency graph completed, took 219ms

[  +11 ms] Failed after 8.2s`

**Comment by sh0umik** [comment]
Still getting the error. I am not even using the `http` package. But instead my app uses `grpc-web` and `protobuff` . `flutter run -d chrome` works well but `flutter build web` did not.

**Comment by Abhilash-Chandran** [comment]
Likewise I get a similar error when I use `graphql: ^2.0.0` package. This package depends on `http` package internally.

**Comment by sezaru** [comment]
Hello, I'm getting the same issue, it was introduced in commit 8504f3ae13d081ee78409e80777a4c71b04ffff0, if I rollback flutter to a previous commit it works fine.
I hope that helps.

**Comment by AppleEducate** [comment]
@sezaru  what version did you roll back to?

**Comment by sezaru** [comment]
I rollbacked to that one: f098de1fdedec2232aa740a6413f318166762795

It works when running with chrome

But it does not work when running `flutter build web`
```
Dart2Js finished with:                                                  

packages/http/src/multipart_file.dart:14:8:
Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading 'packages/http/src/multipart_file_stub.dart'  (No such file
or directory)
import 'multipart_file_stub.dart'
       ^
packages/http/src/multipart_file.dart:93:7:
Error: Method not found: 'multipartFileFromPath'.
      multipartFileFromPath(field, filePath,
      ^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.


Error compiling dartdevc module:loli_app|test/widget_test.ddc.js        

test/widget_test.dart.browser_test.dart:22:43: Error: Getter not found: 'main'.
  internalBootstrapBrowserTest(() => test.main);
```

**Comment by AppleEducate** [comment]
Same for me:

Flutter doctor..

```
dev-mac-100:example_db rodydavis$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.2-pre.14, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.10.2-pre.14 at /usr/local/Caskroom/flutter/1.2.1/flutter
    • Framework revision 2449928d7c (2 days ago), 2019-09-09 21:12:27 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rodydavis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • macOS  • macOS  • darwin-x64     • Mac OS X 10.14.4 18E226
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132 


• No issues found!
```

Logs..

```
dev-mac-100:example_db rodydavis$ flutter build web -v
[  +31 ms] executing: [/usr/local/Caskroom/flutter/1.2.1/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +42 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2449928d7ca4ae1bde00694627b2099417d6a5e6
[        ] executing: [/usr/local/Caskroom/flutter/1.2.1/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +31 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.1-14-g2449928d7
[   +9 ms] executing: [/usr/local/Caskroom/flutter/1.2.1/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/usr/local/Caskroom/flutter/1.2.1/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/usr/local/Caskroom/flutter/1.2.1/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +87 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +125 ms] Found plugin device_calendar at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-1.0.0+2/
[  +42 ms] Found plugin location at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.3.5/
[  +11 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.3.0/
[   +9 ms] Found plugin screen at /usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/screen-0.0.5/
[   +7 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.6+3/
[  +17 ms] Found plugin url_launcher at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.2/
[   +2 ms] Found plugin video_player at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+1/
[  +86 ms] Found plugin device_calendar at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-1.0.0+2/
[  +26 ms] Found plugin location at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.3.5/
[   +7 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.3.0/
[   +8 ms] Found plugin screen at /usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/screen-0.0.5/
[   +4 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.6+3/
[   +8 ms] Found plugin url_launcher at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.2/
[   +1 ms] Found plugin video_player at
/usr/local/Caskroom/flutter/1.2.1/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+1/
[ +165 ms] Compiling lib/main.dart for the Web...
[+6867 ms] Starting daemon...
[ +262 ms] Initializing inputs
[ +326 ms] Building new asset graph...
[+1728 ms] flutter_tools|lib/src/build_runner/build_script.dart was not found in the asset graph, incremental builds will not
work.
                     This probably means you don't have your dependencies specified fully in your pubspec.yaml.
[  +19 ms] Building new asset graph completed, took 1.7s

[        ] Checking for unexpected pre-existing outputs....
[   +1 ms] Checking for unexpected pre-existing outputs. completed, took 2ms

[  +18 ms] Initializing inputs
[   +3 ms] Building new asset graph...
[        ] Building new asset graph completed, took 1.7s
[        ] Checking for unexpected pre-existing outputs....
[        ] Checking for unexpected pre-existing outputs. completed, took 2ms
[+1387 ms] About to build [web, test]...
[   +5 ms] Running build...
[ +990 ms] 1.0s elapsed, 360/380 actions completed.
[+1086 ms] 2.1s elapsed, 767/779 actions completed.
[+1001 ms] 3.1s elapsed, 1049/1056 actions completed.
[+1060 ms] 4.2s elapsed, 1659/1675 actions completed.
[+1047 ms] 5.2s elapsed, 2326/2335 actions completed.
[+1003 ms] Running dart2js with
--libraries-spec="/usr/local/Caskroom/flutter/1.2.1/flutter/bin/cache/flutter_web_sdk/libraries.json" -O4 -o
packages/example_db/main_web_entrypoint.dart.js --packages=".package-00f456ea7da1641164f6fb1a1d4e1639" -Ddart.vm.product=true
package:example_db/main_web_entrypoint.dart

[+1087 ms] 7.3s elapsed, 2643/2644 actions completed.
[+1001 ms] 8.3s elapsed, 2643/2644 actions completed.
[+1097 ms] 9.4s elapsed, 2643/2644 actions completed.
[+1000 ms] 10.4s elapsed, 2643/2644 actions completed.
[+1004 ms] 11.4s elapsed, 2643/2644 actions completed.
[ +902 ms] Dart2Js finished with:
                    
                    packages/http/src/multipart_file.dart:14:8:
                    Error: Error when reading 'packages/http/src/multipart_file_stub.dart': Error reading
                    'packages/http/src/multipart_file_stub.dart'  (No such file or directory)
                    import 'multipart_file_stub.dart'
                           ^
                    packages/http/src/multipart_file.dart:93:7:
                    Error: Method not found: 'multipartFileFromPath'.
                          multipartFileFromPath(field, filePath,
                          ^^^^^^^^^^^^^^^^^^^^^
                    Error: Compilation failed.
                    
[  +39 ms] building for target test/widget_test.dart.browser_test.dart
[+1056 ms] 13.4s elapsed, 2680/2833 actions completed.
[+1100 ms] 14.5s elapsed, 2691/2841 actions completed.
[+1097 ms] 15.6s elapsed, 2706/2847 actions completed.
[+1009 ms] 16.6s elapsed, 2720/2856 actions completed.
[+1091 ms] 17.7s elapsed, 2744/2860 actions completed.
[+1102 ms] 18.8s elapsed, 2759/2861 actions completed.
[+1099 ms] 19.9s elapsed, 2766/2865 actions completed.
[+1096 ms] 21.0s elapsed, 2772/2867 actions completed.
[+1100 ms] 22.1s elapsed, 2779/2872 actions completed.
[+1099 ms] 23.2s elapsed, 2786/2875 actions completed.
[+1100 ms] 24.3s elapsed, 2796/2880 actions completed.
[+1098 ms] 25.4s elapsed, 2810/2884 actions completed.
[+1101 ms] 26.5s elapsed, 2825/2897 actions completed.
[+1098 ms] 27.6s elapsed, 2835/2900 actions completed.
[+1114 ms] 28.7s elapsed, 2851/2906 actions completed.
[+1086 ms] 29.8s elapsed, 2869/2920 actions completed.
[+1001 ms] 30.8s elapsed, 2882/2929 actions completed.
[+1096 ms] 31.9s elapsed, 2896/2937 actions completed.
[+1002 ms] 32.9s elapsed, 2912/2950 actions completed.
[+1098 ms] 34.0s elapsed, 2927/2962 actions completed.
[+1000 ms] 35.0s elapsed, 2938/2972 actions completed.
[+1101 ms] 36.1s elapsed, 2957/2990 actions completed.
[+1095 ms] 37.2s elapsed, 2975/3008 actions completed.
[+1001 ms] 38.2s elapsed, 2987/3020 actions completed.
[+1002 ms] 39.2s elapsed, 3003/3036 actions completed.
[+1097 ms] 40.3s elapsed, 3018/3051 actions completed.
[+1002 ms] 41.3s elapsed, 3028/3061 actions completed.
[+1099 ms] 42.4s elapsed, 3042/3075 actions completed.
[+1097 ms] 43.5s elapsed, 3058/3091 actions completed.
[+1100 ms] 44.6s elapsed, 3073/3101 actions completed.
[+1001 ms] 45.6s elapsed, 3085/3108 actions completed.
[+1097 ms] 46.7s elapsed, 3096/3115 actions completed.
[+1000 ms] 47.7s elapsed, 3111/3128 actions completed.
[+1005 ms] 48.7s elapsed, 3124/3141 actions completed.
[+1095 ms] 49.8s elapsed, 3140/3144 actions completed.
[+1076 ms] 50.9s elapsed, 3144/3144 actions completed.
[ +416 ms] Running build completed, took 51.1s

[        ] Caching finalized dependency graph...
[  +12 ms] Caching finalized dependency graph completed, took 230ms

[   +8 ms] Failed after 51.3s
[  +11 ms] Compiling lib/main.dart for the Web... (completed in 61.9s)
[   +2 ms] "flutter web" took 62,564ms.
Failed to compile lib/main.dart for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWeb (package:flutter_tools/src/web/compile.dart:61:5)
<asynchronous suspension>
#2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:47:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by AppleEducate** [comment]
@sezaru On the latest version on the master I can run on chrome but I am getting the above error.

I though you were saying the rolled back version would build.

**Comment by sezaru** [comment]
Sorry, I was talking about the chrome, I tried use latest version on master but I would still have the chrome error, I will try again

**Comment by sezaru** [comment]
I just tried it again, I got the latest commit from master e10bd6c83 and run `flutter clean` and then tried to run my project via chrome target  and it did trigger the bug.

Doing the same with commit f098de1fdedec2232aa740a6413f318166762795 works

**Comment by AppleEducate** [comment]
yeah for some reason I have the same, but mine works in chrome.

**Comment by Bujupah** [comment]
Well, if you guys wanna bypass this error temporarily...
Edit **http.dart** and comment the multipart_*.dart files
```
... 

export 'src/byte_stream.dart';
export 'src/client.dart';
export 'src/exception.dart';
//export 'src/multipart_file.dart'; <--- comment this
//export 'src/multipart_request.dart'; <--- and this
export 'src/request.dart';
export 'src/response.dart';

...

```

its works D: but the multipart is no more 😅

**Comment by jonahwilliams** [comment]
If you're on the latest flutter master and still experiencing this issue I would greatly appreciate it if you could share a minimal app to reproduce it.

**Comment by abbasidaniyal** [comment]
Still not working for me. A simple http.MultiPart request still gives an error.

**Comment by jonahwilliams** [comment]
Are you using a mutlipart request object directly? These aren't supported in on the web version of package:http

**Comment by alarmatwork** [comment]
Finally started working with the latest master and only after I've performed `flutter clean`

**Comment by TheJulianJES** [comment]
@Solido I'm not sure if you fixed your issue, but it seems to me that the widget_test.dart in your project can't be fully empty.
At least it needs an empty main method. This fixed my issue (of course you should have tests though ;)

Hopefully this will help somebody else who's having this issue.

**Comment by ACChe** [comment]
`flutter clean` is dangerous operation !
