### ISSUE TITLE
Web: GestureRecognizers in nested TextSpans do not work.

### ISSUE THREAD

**Issue by kwight** [flutter/flutter#34931]
If I have nested `TextSpan`s in a `RichText` widget, adding a `GestureRecognizer` to the top level `TextSpan` will work fine, but adding one to a nested `TextSpan` will not. This is only an issue with Flutter for web, not standard Flutter.

This works:

```dart
RichText(
  text: TextSpan(
    text: 'TOP',
    recognizer: TapGestureRecognizer()..onTap = _incrementCounter,
    children: <TextSpan>[
      TextSpan(
        text: 'CHILD',
        // recognizer: TapGestureRecognizer()..onTap = _incrementCounter,
      ),
    ],
  ),
),
```

This does not:

```dart
RichText(
  text: TextSpan(
    text: 'TOP',
    // recognizer: TapGestureRecognizer()..onTap = _incrementCounter,
    children: <TextSpan>[
      TextSpan(
        text: 'CHILD',
        recognizer: TapGestureRecognizer()..onTap = _incrementCounter,
      ),
    ],
  ),
),
```

If both are present, the parent will win (I assume this is intended behaviour).

My use-case is nested spans to be able to colour separators in a [slide credit](https://github.com/kwight/flutter-for-web-presi/blob/master/lib/widgets/footer.dart#L39), where I need different links. Or maybe I don't understand how best to work with `RichText` and `TextSpan` for something like this?

<img width="317" alt="Screen Shot 2019-06-22 at 1 18 01 PM" src="https://user-images.githubusercontent.com/349751/59968551-31330580-94f0-11e9-8283-6e51b1283fa5.png">

**Comment by dbacinski** [comment]
Found the same issue while porting  flutter_linkify to flutter web.

Here is an example of it:
https://github.com/dbacinski/flutter_linkify/tree/flutter_web/example

Lib is essentially doing the same thing as described above:
```
return TextSpan(
    children: elements.map<TextSpan>(
      (element) {
        if (element is LinkableElement) {
          return TextSpan(
            text: element.text,
            style: linkStyle,
            recognizer: onOpen != null
                ? (TapGestureRecognizer()..onTap = () => onOpen(element))
                : null,
          );
        } else {
          return TextSpan(
            text: element.text,
            style: style,
          );
        }
      },
    ).toList(),
```

**Comment by ferhatb** [comment]
Thank you for sample. We reproduced issue. Working on a fix.

**Comment by vhgn** [comment]
Hi. I am experiencing some issues related to this topic.
I have the code:
```dart
RichText(
            text: TextSpan(
              text: 'Package goes from ',
              style: TextStyle(fontSize: 36, color: Colors.black),
              children: <TextSpan>[
                TextSpan(
                  text: _originValue ?? 'here', // _originValue is a String variable (not initially defined)
                  style: TextStyle(
                      color: Colors.deepPurple,
                      fontWeight: FontWeight.bold,
                      decoration: TextDecoration.underline),
                  recognizer: TapGestureRecognizer()
                    ..onTap = () async {
                      _originValue = await Navigator.push(context,
                          MaterialPageRoute(builder: (context) => Cities()));
                    },
                ),
                TextSpan(
                  text: ' to ',
                ),
                TextSpan(
                  text: _destinationValue ?? 'there', // _destinationValue is a String variable (not initially defined)
                  style: TextStyle(
                    color: Colors.deepPurple,
                    fontWeight: FontWeight.bold,
                    decoration: TextDecoration.underline,
                  ),
                  recognizer: TapGestureRecognizer()
                    ..onTap = () async {
                      _destinationValue = await Navigator.push(context,
                          MaterialPageRoute(builder: (context) => Cities()));
                    },
                ),
              ],
            ),
          )
```
> All of this is in a StatefulWidget (in case it's important)

It works fine on mobile (both iOS and Android). Recently I added web support, but it does not always work on web.

_The steps I used to add web support from beta channel_
```shell
flutter channel beta
flutter upgrade
flutter config --enable-web 
```

After running `flutter run -d chrome` it renders like this:

<img width="556" alt="Screen Shot 2019-12-12 at 23 03 18" src="https://user-images.githubusercontent.com/36004230/70740903-a9f27c00-1d33-11ea-8f5b-23867de981b8.png">

Where only _there_ button works, and the state of it changes.

<img width="630" alt="Screen Shot 2019-12-12 at 23 05 11" src="https://user-images.githubusercontent.com/36004230/70741011-dd350b00-1d33-11ea-9343-e32a02b5d40e.png">

However, the button _here_ doesn't work. And it doesn't matter if I first click on _here_ or _there_ only _there_ button works.

I think I should have the patch of this issue, as I upgraded to beta just a few hours ago. I think it did not cover my problem.

Any further help will be greatly appreciated, thank you.

**Comment by vhgn** [comment]
### PS
The output from my `flutter doctor -v`

<img width="669" alt="Screen Shot 2019-12-12 at 23 13 17" src="https://user-images.githubusercontent.com/36004230/70741772-7e709100-1d35-11ea-9a29-c221b6a7279f.png">

**Comment by wonderful89** [comment]
I find the same problem in mobile devices. I commit it here.
[https://github.com/flutter/flutter/issues/48231](https://github.com/flutter/flutter/issues/48231).

@ferhatb  @yjbanov

**Comment by firatcetiner** [comment]
Same problem here. I can't show the a code snippet in the moment but I can say that it's not working properly. Its stange that it recognizes when I tap the widget fast and strongly.

**Comment by yjbanov** [comment]
We're tracking the issue with gesture recognition in text spans in https://github.com/flutter/flutter/issues/46975

**Comment by krel024** [comment]
I just find out that `TapGestureRecognizer` is not working in proper way when `RichText` has `textAlign` with TextAlign.center at least in `web`. It's like the tap still recognized when align is `TextAlign.left`.

**Comment by jlubeck** [comment]
This is still broken on `Flutter v1.17.0-3.4.pre`  not sure why it is closed...

**Comment by Dennis-Mwea** [comment]
Has been fixed in latest flutter build. Remember to add _textKey to your RichText like so.

**Comment by jlubeck** [comment]
@Dennis-Mwea your example is not using a TextAlign other than TextAlign.left. It is still broken on `Flutter 1.18.0-11.1.pre` now
