### ISSUE TITLE
flutter build is not printing the flavor bundle identifier that it actually uses (correctly)

### ISSUE THREAD

**Issue by rajeshzmoke** [flutter/flutter#35163]
I'm using flavors to build ios for different environments

`flutter build ios --release --flavor qa`
```
Building com.highxxxsw.xxx for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 6HXXXX3K
Running pod install...                                              4.1s
Running Xcode build...                                                  
                                                   
 ├─Building Dart code...                                    56.5s
 ├─Generating dSYM file...                                   0.4s
 ├─Stripping debug symbols...                                0.1s
 ├─Assembling Flutter resources...                           1.7s
 └─Compiling, linking and signing...                        17.5s
Xcode build done.                                           115.7s
```
it shows
>  Building com.highxxxsw.xxx for device (ios-release)

i would expect it show `Building com.highxxxsw.xxx.qa for device (ios-release)` for qa flavor
i would expect it show `Building com.highxxxsw.xxx.dev for device (ios-release)` for dev flavor
and 
i would expect it show `Building com.highxxxsw.xxx for device (ios-release)` for prod flavor

which i have configured in Xcode with different bundle identifier for different flavors

**Comment by rajeshzmoke** [comment]
here is my flutter doctor log

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at /Users/rajeshkumar/Desktop/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshkumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rajeshkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@rajeshzmoke is it the same while using current flutter stable v1.9.1+hotfix.4?

**Comment by edTheGuy00** [comment]
@BondarenkoStas I'm still seeing this on `Beta` channel

**Comment by jmagman** [comment]
@rajeshzmoke or @edTheGuy00
> which i have configured in Xcode with different bundle identifier for different flavors

How did you do that?  Did you set the PRODUCT_BUNDLE_IDENTIFIER build setting?  Did you set the CFBundleIdentifier in the Info.plist?

Hopefully this was fixed with https://github.com/flutter/flutter/pull/47993, which made it into 1.13.7.  Would you mind checking if it's [fixed on the dev channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)?

**Comment by edTheGuy00** [comment]
@jmagman I created separate schemes and defined different bundle identifiers for each as seen below.
<img width="616" alt="Screen Shot 2563-01-23 at 14 41 51" src="https://user-images.githubusercontent.com/16095735/72967389-cfbf7600-3df3-11ea-9803-748eb1725a11.png">

I'm still seeing the issue in latest `dev 1.14.3` However it appears that it may just be a a wrong print statement on the console. The build logs show the wrong Flavor but the app output is the correct app flavor `(DEV)_MyApp.ipa` with all the Dev variables I assigned on Info.plist.
 
I think this issue explains it https://github.com/flutter/flutter/issues/45790

**Comment by rajeshzmoke** [comment]
@BondarenkoStas yes and i've updated flutter and this is still occurring in latest Flutter stable version
flutter doctor -v log
```[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at /Users/rajeshkumar/Desktop/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshkumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/rajeshkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • F0C452B9-4FD7-40EF-B9E9-D4E617B5825E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```
Flutter command line build log
```
flutter build ios --release --flavor dev
Building com.clinicalsoftworks.loop for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXX
Running pod install...                                              7.8s
Running Xcode build...                                                  
                                                   
 ├─Building Dart code...                                    63.2s
 ├─Generating dSYM file...                                   0.3s
 ├─Stripping debug symbols...                                0.1s
 ├─Assembling Flutter resources...                           2.9s
 └─Compiling, linking and signing...                        42.8s
Xcode build done.                                           139.6s
```

**Comment by jmagman** [comment]
> yes and i've updated flutter and this is still occurring in latest Flutter stable version

@rajeshzmoke Current stable is 1.12.13+hotfix.5, but https://github.com/flutter/flutter/pull/47993 is in 1.13.7, which is only in the dev channel.

**Comment by jmagman** [comment]
@edTheGuy00 I just closed https://github.com/flutter/flutter/issues/45790, I think it also should be fixed by https://github.com/flutter/flutter/pull/47993 (the code they referenced is now only called on systems that don't have Xcode tools installed).

Is your Info.plist CFBundleIdentifier $(PRODUCT_BUNDLE_IDENTIFIER)`?

I would have just preferred to straight up grab the `PRODUCT_BUNDLE_IDENTIFIER` because that's the more correct solution, but people have hardcoded different bundle identifiers in their their Info.plist to get around the issue, and I didn't want to break them.

**Comment by jmagman** [comment]
@rajeshzmoke Please confirm this is fixed in [Flutter v1.13.7 or later](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos).

**Comment by edTheGuy00** [comment]
@jmagman I'm currently on Dev channel `v1.15.16` and I'm still seeing this. 

And yes my `Info.plist` has 

```
<key>CFBundleIdentifier</key>
<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```

Everything on my dev environment and CI builds works perfectly fine, this is just a minor confusing console message that can be ignored.

**Comment by rajeshzmoke** [comment]
@jmagman  currently i cannot change the channel and test this but on stable branch command line information still does not show proper flavor used, and we have moved to codemagic for automated builds 

```
Flutter doctor - v

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/rajeshkumar/Desktop/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshkumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/rajeshkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Rajesh Kumar’s iPhone • 76fd22d0d6fe8432a90a895351b60bd1d159e8ef • ios • iOS 13.1.2

• No issues found!
```

**Comment by paulpopiel** [comment]
Seeing the same issue on:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.3-pre.7, on Mac OS X 10.15.3 19D76, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.1)
[✓] Connected device (3 available)

As others have said seems to be an issue with the print statement which leads to confusion.

**Comment by acoutts** [comment]
I'm also experiencing this.

```
Flutter 1.17.0-3.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2a7bc389f2 (2 days ago) • 2020-04-21 20:34:20 -0700
Engine • revision 4c8c31f591
Tools • Dart 2.8.0 (build 2.8.0-dev.20.10)
```

**Comment by shinriyo** [comment]
I'm also experiencing this.

I expect `com.highxxxsw.xxx` expected for production release
but, it shows `com.highxxxsw.xxx.dev`. why???
I actually PROJECT

And I can't resolve.
Why Flutter ignores my setting.

I actually set like this.
<img width="700" alt="Screen Shot 2020-05-08 at 13 11 05" src="https://user-images.githubusercontent.com/396927/81369552-b2f24880-912d-11ea-9175-56c12c4787d3.png">

<img width="653" alt="Screen Shot 2020-05-08 at 13 11 19" src="https://user-images.githubusercontent.com/396927/81369560-b554a280-912d-11ea-9893-c567d257bb9f.png">

**Comment by shinriyo** [comment]
<img width="311" alt="Screen Shot 2020-05-08 at 13 15 06" src="https://user-images.githubusercontent.com/396927/81369721-1d0aed80-912e-11ea-9dbb-2c489bc9b7b4.png">
Sorry, the blue highlight is a secret.
But, I set this actually.

**Comment by shinriyo** [comment]
```
flutter --version
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2
```

suitable is old? Does beta fix it?

**Comment by shinriyo** [comment]
@edTheGuy00
Where is `Info.plist`?

```
 find . -type f -name "Info.plist"
```
SO many..

**Comment by shinriyo** [comment]
```
./ios/Runner/Info.plist
./ios/Flutter/Flutter.framework/Info.plist
./ios/Flutter/App.framework/Info.plist
```

**Comment by shinriyo** [comment]
Ah,  1.13.7 fix it?

**Comment by shinriyo** [comment]
<img width="861" alt="Screen Shot 2020-05-08 at 16 51 49" src="https://user-images.githubusercontent.com/396927/81386420-ed6cdd00-914f-11ea-80fa-859875d37b34.png">
not yet...

**Comment by shinriyo** [comment]
Before build. use it in the project forlder. Is it okey?
```
/usr/bin/plutil -replace CFBundleIdentifier -string com.company.appname   ios/Runner/Info.plist
```

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/56620.  See https://github.com/flutter/flutter/issues/14648#issuecomment-627079766 for more details.

**Comment by shinriyo** [comment]
@jmagman
Thank you for fix.
Is it already available?

**Comment by jmagman** [comment]
@shinriyo https://github.com/flutter/flutter/pull/56620 is currently available on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#master).  It will be in the next [dev release](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), which hasn't happened yet.

**Comment by shinriyo** [comment]
@jmagman Thank you. I'm looking for #56620 release. When is next dev release?

**Comment by jmagman** [comment]
Should be any day now, pending various processes and tests passing.  Don't have an exact date though.
