### ISSUE TITLE
m3u8 wouldn't load on iOS when using live stream

### ISSUE THREAD

**Issue by marianoarga** [flutter/flutter#35402]
Hello, I have tested on all channels but the issue continues, m3u8 video would load just fine only when it is an already finished video, such as the one in plugin's /example:
http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8
But wouldn't even .initialize() on **live stream** m3u8 like:
https://live-edge01.telecentro.net.ar/live/smil:musictop.smil/playlist.m3u8

## Steps to Reproduce

1. Make an app with video_player example and modify the m3u8 by a live streming  m3u8
2. Launch app on iOS physical device
3. Video would not load, neither VideoPlayerController's .initialize() initializes

## Logs

Log from emulator, since not getting any log on physical device, seems to be receiving video chunks but is a log that I cannot comprehend, maybe it helps
```
[C2.1 884DFDC6-EB6E-4EA1-83A2-4DB6B0416053 192.168.0.38:50343<->200.115.193.177:443]
	Connected Path: satisfied (Path is satisfied), interface: en7
	Duration: 9.128s, DNS @0.000s took 0.002s, TCP @0.003s took 0.009s, TLS took 0.042s
	bytes in/out: 4230/1018, packets in/out: 8/3, rtt: 0.008s, retransmitted packets: 0, out-of-order packets: 0
	[C1.1 2F2D2C18-C1E1-41E5-9283-9796C65E4756 192.168.0.38:50339<->200.115.193.177:443]
	Connected Path: satisfied (Path is satisfied), interface: en7
	Duration: 10.890s, DNS @0.002s took 0.011s, TCP @0.015s took 0.013s, TLS took 0.046s
	bytes in/out: 11145698/3642, packets in/out: 7706/10, rtt: 0.006s, retransmitted packets: 1, out-of-order packets: 0
	[C3.1 A1F6DD61-DF46-4725-B10B-3B75639902FA 192.168.0.38:50350<->200.115.193.177:443]
	Connected Path: satisfied (Path is satisfied), interface: en7
	Duration: 9.077s, DNS @0.001s took 0.000s, TCP @0.003s took 0.008s, TLS took 0.040s
	bytes in/out: 4230/1018, packets in/out: 8/3, rtt: 0.007s, retransmitted packets: 0, out-of-order packets: 0
	[C4.1 E0E38830-1BB1-4C9F-B72F-D617370A0814 192.168.0.38:50351<->200.115.193.177:443]
	Connected Path: satisfied (Path is satisfied), interface: en7
	Duration: 10.316s, DNS @0.000s took 0.001s, TCP @0.003s took 0.010s, TLS took 0.039s
```

Not related analyze errors
```
flutter analyze
Analyzing Diario26...

   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: CategoryListing.category • lib/main.dart:59:7 •
          must_be_immutable
   info • This function has a return type of 'Future<List<Post>>', but doesn't end with a return statement • lib/main.dart:385:3 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/models/Post.dart:11:16 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/Post.dart:13:138 • non_constant_identifier_names

4 issues found. (ran in 3.1s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale es-AR)
    • Flutter version 1.6.3 at /Users/juanma/Development/flutter
    • Framework revision bc7bc94083 (6 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/juanma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by hahafather007** [comment]
I used Flutter dev v1.4.5-pre.11 and used video_player's 0.10.1+3 version to play m3u8 in both Android and IOS, which is perfect. But now I switch to master v1.7.12-pre.43, it can only play normally in Android, only the first frame can be loaded on IOS. How can I solve this problem? Switching to the Flutter version is not possible, because Android has modified a lot of code to adapt AndroidX.

**Comment by marianoarga** [comment]
@hahafather007 Did you make sure you test on a physical device for iOS? Since video_player documentation says it doesn't work on emulator, just to clarify that.

**Comment by hahafather007** [comment]
@marianoarga Of course I test on a  physical device, both iphone6 and iphonex

**Comment by nealwon** [comment]
I got the same problem.   Android is ok,but ios(iphone xr) not work.

**Comment by marianoarga** [comment]
@nealwon you should thumbs up the issue, since the Flutter team looks at thoose "votes"

**Comment by marianoarga** [comment]
Using 0.10.0+8 version of video_player works as espected, @ianko 's referenced his merge request and explained the cause.
Looking forward to see it merged.
Thanks.

**Comment by hahafather007** [comment]
This problem also happen with version from 0.10.1 to 0.10.2+1

**Comment by marianoarga** [comment]
@hahafather007 If you read the @ianko PR you should see something like this:
"The 0.10.1 version introduced the condition to have the duration in order to consider the player initialized", we can asume any version greater than 0.10.1 has this issue

**Comment by mikhail-tokarev** [comment]
hi @marianoarga 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of "flutter doctor -v"

**Comment by marianoarga** [comment]
@mikhail-tokarev I don't see @ianko PR merged, can you refference the fix aplied  for this issue in latest stable release?, thank you.
Will test anyway.

**Comment by aletorrado** [comment]
Any update about this?

**Comment by griand** [comment]
I got the same problem with any HLS live streams. Android is fine, iphone X not work. 
flutter video_player plugin version is: ^0.10.5

flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale ru-RU)
    • Flutter version 1.12.13+hotfix.5 at /Users/javau/dev/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/javau/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/javau/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • GT I9300        • 4df17c1f4319af51                         • android-arm • Android 4.3 (API 18)
    • iPhone (A) • 4a00839382bf6e99c1d7aba3c4db793d73f6a5a2 • ios         • iOS 13.3

**Comment by VictorLekweuwa** [comment]
Please, what is the solution to this? Has anyone found a work-around? video_player 0.10.0+8 also not playing m3u8 file on iOS.

**Comment by ianko** [comment]
@VictorLekweuwa I'd recommend you to switch to [better_player](https://pub.dev/packages/better_player).

This issue was solved by some PRs before, [including one of my own](https://github.com/flutter/plugins/pull/1743), but never gets merged . If the community can't contribute, and the core team has no interest in solve it, the best thing to do is not use it.

If for any reason you can't replace the player at the moment, you can override the `video_player` in your pubspec to one of the open PRs forks. (don't use mine, I've added some code to support Mux Analytics integration and it's probably something you don't want).

Example using the flutter/plugins#3360:

pubspec.yaml
```yaml
...
dependencies:
  video_player: ^2.1.6
  
dependency_overrides:
  video_player:
    git:
      url: https://github.com/nathanaelneveux/flutter-plugins.git
      ref: issue-48670
      path: packages/video_player/video_player
```

> **NOTE:** I haven't tested this code and PR/fork.

**Comment by VictorLekweuwa** [comment]
> @VictorLekweuwa I'd recommend you to switch to [better_player](https://pub.dev/packages/better_player).
> 
> This issue was solved by some PRs before, [including one of my own](https://github.com/flutter/plugins/pull/1743), but never gets merged. If the community can't contribute, and the core team has no interest in solve it, the best thing to do is not use it.
> 
> If for any reason you can't replace the player at the moment, you can override the `video_player` in your pubspec to one of the open PRs forks. (don't use mine, I've added some code to support Mux Analytics integration and it's probably something you don't want).
> 
> Example using the [flutter/plugins#3360](https://github.com/flutter/plugins/pull/3360):
> 
> pubspec.yaml
> 
> ```yaml
> ...
> dependencies:
>   video_player: ^2.1.6
>   
> dependency_overrides:
>   video_player:
>     git:
>       url: https://github.com/nathanaelneveux/flutter-plugins.git
>       ref: issue-48670
>       path: packages/video_player/video_player
> ```
> 
> > **NOTE:** I haven't tested this code and PR/fork.

Thanks, I tried betterplayer but it's still not working. I'm getting the error:
Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation could not be completed, null, null)

**Comment by maheshmnj** [comment]
The issue is reproducible on latest stable channel with ```video_player: ^2.1.6```, The video_player is blank on both IOS and Android and there are no logs for IOS.

<details>
<summary>code sample</summary>

```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: VideoPlayerDocs(),
    ),
  );
}

class VideoPlayerDocs extends StatefulWidget {
  @override
  _VideoPlayerDocsState createState() => _VideoPlayerDocsState();
}

class _VideoPlayerDocsState extends State<VideoPlayerDocs> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://live-edge01.telecentro.net.ar/live/smil:musictop.smil/playlist.m3u8')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
        print('initialized');
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: Stack(
                    alignment: Alignment.topCenter,
                    children: <Widget>[
                      VideoPlayer(_controller),
                      VideoProgressIndicator(_controller, allowScrubbing: true),
                    ],
                  ),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```
</details>

<details>
<summary>Android logs</summary>

```
I/TetheringManager(10114): registerTetheringEventCallback:io.flutter.plugins.videoplayerexample
W/eoplayerexampl(10114): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(10114): Init 3b75cd8 [ExoPlayerLib/2.12.1] [emulator_arm64, sdk_gphone_arm64, Google, 30]
E/ExoPlayerImplInternal(10114): Playback error
E/ExoPlayerImplInternal(10114):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(10114):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(10114):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(10114):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10114):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(10114):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10114):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10114):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal(10114):   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/ExoPlayerImplInternal(10114):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:589)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:493)
E/ExoPlayerImplInternal(10114):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)
E/ExoPlayerImplInternal(10114):       ... 8 more
E/ExoPlayerImplInternal(10114):   Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:661)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
E/ExoPlayerImplInternal(10114):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/ExoPlayerImplInternal(10114):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/ExoPlayerImplInternal(10114):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/ExoPlayerImplInternal(10114):       ... 30 more
E/ExoPlayerImplInternal(10114):   Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(10114):       ... 43 more
E/flutter (10114): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (10114):
```
</details>

**Comment by Hwan-seok** [comment]
still happening on latest version 
- flutter: 2.5.1
- video_player: 2.2.5

**Comment by jmagman** [comment]
I believe this has been fixed and m3u8 videos now work.  See https://github.com/flutter/plugins/pull/4727 and friends.

If you are still seeing this, please let us know and we'll reopen and investigate.
