### ISSUE TITLE
text selection toolbar options is not shown on long press CupertinoTextField Widget !!

### ISSUE THREAD

**Issue by MoSala7** [flutter/flutter#35837]
with `enableInteractiveSelection: true,`  cut/copy/paste menu must be showed as mentioned in documentation in :
https://api.flutter.dev/flutter/cupertino/CupertinoTextField/enableInteractiveSelection.html
but i can only find the two default options as showed in picture 
https://ibb.co/j55PhdY

it can only shown in double tap not long press!!!

## Logs

```
`CupertinoTextField(
                                  clearButtonMode: OverlayVisibilityMode.always,
                                  enableInteractiveSelection: true,
                                  expands: true,
                                  controller: _noteController,
                                  style: TextStyle(
                                      color: StyleCustom.txtPrimary,
                                      fontSize: 16.0),
                                  maxLines: null,
                                  minLines: null,
                                  placeholder: 'write your note here',
                                  decoration: BoxDecoration(),
                                  onChanged: (String value) {
                                    debugPrint(value);
                                  },
                                ),`
```

```
`[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
    • Framework revision b712a172f9 (4 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\midos\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7479.14

[√] VS Code, 64-bit edition (version 1.36.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • COR L29 • XTX7N18A31001552 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.`
```

**Comment by LongCatIsLooong** [comment]
I think that's because there were no selected characters so it doesn't make sense to show the copy button. Could you try selecting more than one character and see if copy appears?

**Comment by MoSala7** [comment]
> I think that's because there were no selected characters so it doesn't make sense to show the copy button. Could you try selecting more than one character and see if copy appears?

to select more than one charachter i have to double tap on some word thats only when i can see cut/copy options, but when using TextField Widget i don't have to double tap i can only long press at any word to see cut/copy options!!

**Comment by GuilhermeVendramini** [comment]
After upgrade Flutter I had same problem, before upgrade was working fine.

**Comment by justinmc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/34215?

**Comment by justinmc** [comment]
This should be fixed in the next release (1.8.1+) with the PR referenced above.  Make sure you're on the right [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) to get it.

**Comment by adriancmurray** [comment]
@justinmc I tried the master channel with the 1.8.2-pre.30 and it is still not showing up with either double tap or long press. I've been able to get the toolbar to show up if I do a hot reload right after the point it's supposed to pop up (such as a long press or a double tap). Here's the error : 

```
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1694:18)
flutter: #3      RenderBox.size (package:flutter/src/rendering/box.dart:1700:6)
flutter: #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2425:24)
flutter: #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2167:24)
flutter: #6      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2244:31)
flutter: #7      _ToolbarRenderBox.performLayout (package:flutter/src/cupertino/text_selection.dart:167:35)
flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #15     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #25     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #26     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
flutter: #27     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #37     _invoke (dart:ui/hooks.dart:236:10)
flutter: #38     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: _ToolbarRenderBox#da810 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   creator: CupertinoTextSelectionToolbar ← CompositedTransformFollower ← FadeTransition ←
flutter:     _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#ff4d8] ← Stack ← _Theatre ←
flutter:     Overlay-[LabeledGlobalKey<OverlayState>#78b35] ← _FocusMarker ← Semantics ← FocusScope ←
flutter:     AbsorbPointer ← Listener ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=414.0, h=896.0)
flutter:   size: Size(414.0, 896.0)
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child: RenderDecoratedBox#f67be relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderFlex#e954a relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 1: RenderSemanticsGestureHandler#220b1 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPointerListener#93d8d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderSemanticsAnnotations#6894e relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 2: RenderConstrainedBox#15488 relayoutBoundary=up3 NEEDS-PAINT
flutter:         child 3: RenderSemanticsGestureHandler#fecfc relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPointerListener#281dc relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderSemanticsAnnotations#601c1 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 4: RenderConstrainedBox#edf08 relayoutBoundary=up3 NEEDS-PAINT
flutter:         child 5: RenderSemanticsGestureHandler#ad32d relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPointerListener#c1437 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderSemanticsAnnotations#03654 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
```

**Comment by justinmc** [comment]
@adriancmurray Can you provide some code and instructions for how to reproduce that?  I don't see it if I just make a super simple app and double tap or long press in the empty field.

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      debugShowCheckedModeBanner: false,
      title: 'Text Field Test',
      home: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              CupertinoTextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by adriancmurray** [comment]
I did, but in its own issue : https://github.com/flutter/flutter/issues/36124

**Comment by justinmc** [comment]
Ah thank you, I'll follow up over in that issue.
