### ISSUE TITLE
Nested embedded view does not display in iOS 

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#35840]
## Steps to Reproduce

1. Switch to Flutter master channel
2. Run sample app with `webview_flutter: ^0.3.9+1` and enable Embedded Views preview
3. In iOS, the WebView only renders if either `ClipRRect` **or** `SingleChildScrollView` is removed. Otherwise the WebView will show nothing.
4. Issue not present in Android. Issue also not present in Flutter beta channel in both Android and iOS.

Sample app:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ClipRRect(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(10.0),
            topRight: Radius.circular(10.0),
          ),
          child: SingleChildScrollView(
            child: ConstrainedBox(
              constraints: BoxConstraints(maxHeight: 100.0),
              child: WebView(
                gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{
                  Factory<VerticalDragGestureRecognizer>(
                    () => VerticalDragGestureRecognizer(),
                  ),
                },
                initialUrl: Uri.dataFromString(
                  '<p>Web view sample</p>' * 1000,
                ).toString(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

Pubspec:

```
name: webview_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

## Logs

When scrolling on the blank view:

```
Runner[14188]: (UIKitCore) Created Activity ID: 0x1bfa1, Description: send
gesture actions
```

```
→ flutter analyze
Analyzing webview_test...
No issues found! (ran in 3.0s)
```

```
→ flutter doctor -v
[✓] Flutter (Channel master, v1.8.1-pre.56, on Mac OS X 10.14.5 18F132, locale
    en-US)
    • Flutter version 1.8.1-pre.56 at /Users/droidery/flutter
    • Framework revision 2ad5376a06 (2 hours ago), 2019-07-09 16:00:33 -0700
    • Engine revision 75387dbc14
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)


[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/droidery/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[!] iOS tools - develop for iOS devices
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller
      may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✗] Chrome - develop for the web (Cannot find chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! CHROME_EXECUTABLE not set

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86    • Android 9 (API 28) (emulator)
    • macOS                     • macOS                                •
      darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome                    • chrome                               •
      web-javascript • unknown (unsupported)

! Doctor found issues in 2 categories.
```

May be related to https://github.com/flutter/flutter/issues/35394, another combination of widgets that breaks Flutter Webview on the master channel.

**Comment by droidery** [comment]
This bug is now also in the Flutter beta channel. @amirh Any tips on other workarounds for people using platform views beta?

**Comment by amirh** [comment]
@cyanglaz

**Comment by cyanglaz** [comment]
https://github.com/flutter/engine/pull/9937 should fix the issue.

**Comment by cyanglaz** [comment]
@droidery The fix is merged, could you confirm it is working for you as well on master?

**Comment by droidery** [comment]
@cyanglaz I tried Flutter master but I'm still getting the same issue in the iOS emulator.

This is my version, is this the version with the fix?

```
Flutter 1.8.2-pre.115 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6830edd0be (40 minutes ago) • 2019-07-19 14:54:24 -0700
Engine • revision 5467f6f630
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 63120303a7)
```

**Comment by cyanglaz** [comment]
It seems the engine has not rolled in yet. You can try build with a local engine pointing to master.

**Comment by droidery** [comment]
Thank you @cyanglaz. This fixes the WebView not showing.

**Comment by vitulgoyani** [comment]
I can't wrap webview in ClipRRect, anybody please help me?

**Comment by dhanrajvermaRepo** [comment]
@droidery, how you solved this problem? I am also facing the same issue in iOS.
I am using 
Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at /Users/root-flutter/Documents/development/flutter
    • Framework revision 1aedbb1835 (3 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
