### ISSUE TITLE
Flutter app crashes with firestore

### ISSUE THREAD

**Issue by emrekosen** [flutter/flutter#36189]
I was using old version of firestore plugin 0.8 i remember, transactions was not working, then i get the 0.12.7 and now when i use firestore functions app crashes. Like 1 or 2 month ago app was working correctly. I can't figure out the problem.

```
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): Failed to handle method call result
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.success(CloudFirestorePlugin.java:391)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:199)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:114)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:654)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9595): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

`E/CloudFirestorePlugin( 9595): Timed out waiting for Task
E/CloudFirestorePlugin( 9595): java.util.concurrent.TimeoutException: Timed out waiting for Task
E/CloudFirestorePlugin( 9595): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
E/CloudFirestorePlugin( 9595): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:418)
E/CloudFirestorePlugin( 9595): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:370)
E/CloudFirestorePlugin( 9595): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$1(com.google.firebase:firebase-firestore@@19.0.0:283)
E/CloudFirestorePlugin( 9595): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$3.call(Unknown Source:6)
E/CloudFirestorePlugin( 9595): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin( 9595): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin( 9595): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin( 9595): 	at java.lang.Thread.run(Thread.java:764)`

`D/AndroidRuntime( 9595): Shutting down VM
E/AndroidRuntime( 9595): FATAL EXCEPTION: main
E/AndroidRuntime( 9595): Process: com.acmhacettepe.acmhacettepe, PID: 9595
E/AndroidRuntime( 9595): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 9595): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
E/AndroidRuntime( 9595): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime( 9595): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3.onComplete(CloudFirestorePlugin.java:436)
E/AndroidRuntime( 9595): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
E/AndroidRuntime( 9595): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 9595): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9595): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9595): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 9595): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9595): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9595): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 9595): Sending signal. PID: 9595 SIG: 9
Lost connection to device.
```

**Comment by guit4eva** [comment]
My app is crashing too with transactions, but only on a physical iOS device. I've been trying to figure this out for 5 days now :/

#https://github.com/flutter/flutter/issues/35806

Some things that I've noticed:

1) Sometimes the transaction will fire multiple times
2) If it fires once (as it should), I get the error and crash if I run the transaction 5 times in a row. As far as I know, Firestore attempts a transaction 5 times before failing. 

I'm not sure why the failures result in app crashes though? Or why it sometimes fires multiple times...

**Comment by guit4eva** [comment]
Another error after attempting a transaction:

> [  +19 ms] *** Assertion failure in void firebase::firestore::core::Transaction::Lookup(const std::vector<DocumentKey> &, firebase::firestore::core::Transaction::LookupCallback
> &&)(), /Users/rudeboy/Localis/localis/ios/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/core/transaction.mm:83
> [   +7 ms] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Transactions lookups are invalid after
> writes. (expected mutations_.empty())'
> [        ] 	*** First throw call stack:
> [        ] 	(0x258e391b 0x2507ee17 0x258e37f1 0x260c7583 0x3bda41 0x3bdbc3 0x49a4b5 0x26eadb 0x26edfb 0x5d1105 0x25451823 0x254605e9 0x2545ffcd 0x25615b29 0x25615718)
> [  +28 ms] Service protocol connection closed.
> [        ] Lost connection to device.

**Comment by emrekosen** [comment]
The issue solved with new firestore plugin update.

**Comment by guit4eva** [comment]
> The issue solved with new firestore plugin update.

I'm still getting the same error after updating to 0.12.9+4 ?

**Comment by BondarenkoStas** [comment]
@guit4eva Please provide your flutter doctor -v output.

**Comment by kroikie** [comment]
@emrekosen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1214. Any further collaboration will be done there.
