### ISSUE TITLE
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true

### ISSUE THREAD

**Issue by kecson** [flutter/flutter#36350]
1. 
```
@override
  Widget build(BuildContext context) {
    return Container(
      width: 200,
      height: 100,
    );
}
```
2. then 2 fingers simultaneously click the Container

## Logs

```
I/HiTouch_PressGestureDetector(30551): ACTION_POINTER_DOWN.
I/flutter (30551): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30551): The following assertion was thrown while dispatching a pointer event:
I/flutter (30551): 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons ==
I/flutter (30551): kPrimaryButton': is not true.
I/flutter (30551): 
I/flutter (30551): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30551): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30551): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30551):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (30551): 
I/flutter (30551): When the exception was thrown, this was the stack:
I/flutter (30551): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
I/flutter (30551): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
I/flutter (30551): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (30551): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter (30551): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (30551): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (30551): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (30551): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (30551): #13     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter (30551): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter (30551): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (30551): 
I/flutter (30551): Event:
I/flutter (30551):   PointerUpEvent#e1106(position: Offset(106.9, 368.5), timeStamp: 283:24:16.081000, pointer: 4,
I/flutter (30551):   kind: touch, device: 1, down: false, pressure: 0.2, pressureMin: 0.0)
I/flutter (30551): Target:
I/flutter (30551):   <WidgetsFlutterBinding>
I/flutter (30551): ════════════════════════════════════════════════════════════════════════════════════════════════════
V/AudioManager(30551): playSoundEffect   effectType: 0
V/AudioManager(30551): querySoundEffectsEnabled...
I/ViewRootImpl(30551): jank_removeInvalidNode all the node in jank list is out of time
I/flutter (30551): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.
```

**Comment by LeandroMoura3** [comment]
Same here:

> E/flutter (22777): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons == kPrimaryButton': is not true.
> E/flutter (22777): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
> E/flutter (22777): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (22777): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
> E/flutter (22777): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
> E/flutter (22777): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> E/flutter (22777): #5      GestureArenaManager.release (package:flutter/src/gestures/arena.dart:199:7)
> E/flutter (22777): #6      DoubleTapGestureRecognizer._reset (package:flutter/src/gestures/multitap.dart:260:44)
> E/flutter (22777): #7      _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (22777): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (22777): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (22777): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (22777): #11     _rootRun (dart:async/zone.dart:1124:13)
> E/flutter (22777): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (22777): #13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> E/flutter (22777): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
> E/flutter (22777): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> E/flutter (22777): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> E/flutter (22777): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> E/flutter (22777): 
> I/flutter (22777): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.

Here is the code:
`import 'package:flutter/material.dart';
import 'package:multi_image_picker/multi_image_picker.dart';

class DetailPhotoScreen extends StatefulWidget {
  final _image;

  DetailPhotoScreen(this._image);

  @override
  _DetailPhotoScreenState createState() => _DetailPhotoScreenState(_image);
}

class _DetailPhotoScreenState extends State<DetailPhotoScreen>
    with TickerProviderStateMixin{
  final _image;
  double _scale = 1.0;
  Offset _translate = Offset(0.0, 0.0);
  Animation<double> _scaling;
  AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(duration: Duration(milliseconds: 250), vsync: this);

    _scaling = Tween<double>(begin: 0.0, end: 1.0).animate(_controller);

    _scaling.addListener((){
      setState((){
        _scale = _scaling.value;
      });
    });
  }

  _DetailPhotoScreenState(this._image);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        GestureDetector(
          onDoubleTap: () {
            setState(() {
              _translate = Offset(0.0, 0.0);
              _scale = 1.0;
            });
          },
          child: Center(
            child: Container(
              color: Colors.black,
              child: GestureDetector(
                onPanUpdate: (x) {
                  setState(() {
                    _translate = _translate + x.delta;
                  });
                },
                child: Transform.translate(
                  offset: _translate,
                  child: Transform.scale(
                    scale: _scale,
                    child: AssetThumb(
                      asset: _image,
                      width: _image.originalWidth,
                      height: _image.originalHeight,
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
        Align(
          alignment: AlignmentDirectional.bottomEnd,
          child: Container(
            width: 50.0,
            height: 50.0,
            margin: EdgeInsets.only(right: 80.0, bottom: 15.0),
            child: RaisedButton.icon(
              onPressed: () {
                setState((){
                  if (_scale < 10){
                    _scaling = Tween<double>(begin: _scale, end: _scale*2.0).animate(_controller);
                    _controller.reset();
                    _controller.forward();
                  }
                });
              },
              icon: Icon(Icons.zoom_in, color: Colors.white70),
              label: Text(""),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(25.0))),
              color: Theme.of(context).primaryColor,
            ),
          ),
        ),
        Align(
          alignment: AlignmentDirectional.bottomEnd,
          child: Container(
            width: 50.0,
            height: 50.0,
            margin: EdgeInsets.only(right: 15.0, bottom: 15.0),
            child: RaisedButton.icon(
              onPressed: () {
                setState((){
                  if (_scale > 0.1){
                    _scaling = Tween<double>(begin: _scale, end: _scale*0.5).animate(_controller);
                    _controller.reset();
                    _controller.forward();
                  }
                });
              },
              icon: Icon(Icons.zoom_out, color: Colors.white70),
              label: Text(""),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(25.0))),
              color: Theme.of(context).primaryColor,
            ),
          ),
        ),
      ],
    );
  }
}
`

**Comment by kecson** [comment]
but I don't want to listener onDoubleTap.

**Comment by kecson** [comment]
> Same here:
> 
> > E/flutter (22777): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons == kPrimaryButton': is not true.
> > E/flutter (22777): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
> > E/flutter (22777): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> > E/flutter (22777): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
> > E/flutter (22777): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
> > E/flutter (22777): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> > E/flutter (22777): #5      GestureArenaManager.release (package:flutter/src/gestures/arena.dart:199:7)
> > E/flutter (22777): #6      DoubleTapGestureRecognizer._reset (package:flutter/src/gestures/multitap.dart:260:44)
> > E/flutter (22777): #7      _rootRun (dart:async/zone.dart:1120:38)
> > E/flutter (22777): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
> > E/flutter (22777): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> > E/flutter (22777): #10     _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
> > E/flutter (22777): #11     _rootRun (dart:async/zone.dart:1124:13)
> > E/flutter (22777): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
> > E/flutter (22777): #13     _CustomZone.bindCallback. (dart:async/zone.dart:947:23)
> > E/flutter (22777): #14     Timer._createTimer. (dart:async-patch/timer_patch.dart:21:15)
> > E/flutter (22777): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> > E/flutter (22777): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> > E/flutter (22777): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> > E/flutter (22777):
> > I/flutter (22777): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.
> 
> Here is the code:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:multi_image_picker/multi_image_picker.dart';
> 
> class DetailPhotoScreen extends StatefulWidget {
>   final _image;
> 
>   DetailPhotoScreen(this._image);
> 
>   @override
>   _DetailPhotoScreenState createState() => _DetailPhotoScreenState(_image);
> }
> 
> class _DetailPhotoScreenState extends State<DetailPhotoScreen>
>     with TickerProviderStateMixin{
>   final _image;
>   double _scale = 1.0;
>   Offset _translate = Offset(0.0, 0.0);
>   Animation<double> _scaling;
>   AnimationController _controller;
> 
>   @override
>   void initState() {
>     super.initState();
>     _controller = AnimationController(duration: Duration(milliseconds: 250), vsync: this);
> 
>     _scaling = Tween<double>(begin: 0.0, end: 1.0).animate(_controller);
> 
>     _scaling.addListener((){
>       setState((){
>         _scale = _scaling.value;
>       });
>     });
>   }
> 
>   _DetailPhotoScreenState(this._image);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Stack(
>       children: <Widget>[
>         GestureDetector(
>           onDoubleTap: () {
>             setState(() {
>               _translate = Offset(0.0, 0.0);
>               _scale = 1.0;
>             });
>           },
>           child: Center(
>             child: Container(
>               color: Colors.black,
>               child: GestureDetector(
>                 onPanUpdate: (x) {
>                   setState(() {
>                     _translate = _translate + x.delta;
>                   });
>                 },
>                 child: Transform.translate(
>                   offset: _translate,
>                   child: Transform.scale(
>                     scale: _scale,
>                     child: AssetThumb(
>                       asset: _image,
>                       width: _image.originalWidth,
>                       height: _image.originalHeight,
>                     ),
>                   ),
>                 ),
>               ),
>             ),
>           ),
>         ),
>         Align(
>           alignment: AlignmentDirectional.bottomEnd,
>           child: Container(
>             width: 50.0,
>             height: 50.0,
>             margin: EdgeInsets.only(right: 80.0, bottom: 15.0),
>             child: RaisedButton.icon(
>               onPressed: () {
>                 setState((){
>                   if (_scale < 10){
>                     _scaling = Tween<double>(begin: _scale, end: _scale*2.0).animate(_controller);
>                     _controller.reset();
>                     _controller.forward();
>                   }
>                 });
>               },
>               icon: Icon(Icons.zoom_in, color: Colors.white70),
>               label: Text(""),
>               shape: RoundedRectangleBorder(
>                   borderRadius: BorderRadius.all(Radius.circular(25.0))),
>               color: Theme.of(context).primaryColor,
>             ),
>           ),
>         ),
>         Align(
>           alignment: AlignmentDirectional.bottomEnd,
>           child: Container(
>             width: 50.0,
>             height: 50.0,
>             margin: EdgeInsets.only(right: 15.0, bottom: 15.0),
>             child: RaisedButton.icon(
>               onPressed: () {
>                 setState((){
>                   if (_scale > 0.1){
>                     _scaling = Tween<double>(begin: _scale, end: _scale*0.5).animate(_controller);
>                     _controller.reset();
>                     _controller.forward();
>                   }
>                 });
>               },
>               icon: Icon(Icons.zoom_out, color: Colors.white70),
>               label: Text(""),
>               shape: RoundedRectangleBorder(
>                   borderRadius: BorderRadius.all(Radius.circular(25.0))),
>               color: Theme.of(context).primaryColor,
>             ),
>           ),
>         ),
>       ],
>     );
>   }
> }
> ```

but I don't want to listener onDoubleTap.

**Comment by kecson** [comment]
> > Same here:
> > > E/flutter (22777): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons == kPrimaryButton': is not true.
> > > E/flutter (22777): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
> > > E/flutter (22777): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> > > E/flutter (22777): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
> > > E/flutter (22777): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
> > > E/flutter (22777): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> > > E/flutter (22777): #5      GestureArenaManager.release (package:flutter/src/gestures/arena.dart:199:7)
> > > E/flutter (22777): #6      DoubleTapGestureRecognizer._reset (package:flutter/src/gestures/multitap.dart:260:44)
> > > E/flutter (22777): #7      _rootRun (dart:async/zone.dart:1120:38)
> > > E/flutter (22777): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
> > > E/flutter (22777): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> > > E/flutter (22777): #10     _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
> > > E/flutter (22777): #11     _rootRun (dart:async/zone.dart:1124:13)
> > > E/flutter (22777): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
> > > E/flutter (22777): #13     _CustomZone.bindCallback. (dart:async/zone.dart:947:23)
> > > E/flutter (22777): #14     Timer._createTimer. (dart:async-patch/timer_patch.dart:21:15)
> > > E/flutter (22777): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> > > E/flutter (22777): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> > > E/flutter (22777): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> > > E/flutter (22777):
> > > I/flutter (22777): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.
> > 
> > 
> > Here is the code:
> > ```
> > import 'package:flutter/material.dart';
> > import 'package:multi_image_picker/multi_image_picker.dart';
> > 
> > class DetailPhotoScreen extends StatefulWidget {
> >   final _image;
> > 
> >   DetailPhotoScreen(this._image);
> > 
> >   @override
> >   _DetailPhotoScreenState createState() => _DetailPhotoScreenState(_image);
> > }
> > 
> > class _DetailPhotoScreenState extends State<DetailPhotoScreen>
> >     with TickerProviderStateMixin{
> >   final _image;
> >   double _scale = 1.0;
> >   Offset _translate = Offset(0.0, 0.0);
> >   Animation<double> _scaling;
> >   AnimationController _controller;
> > 
> >   @override
> >   void initState() {
> >     super.initState();
> >     _controller = AnimationController(duration: Duration(milliseconds: 250), vsync: this);
> > 
> >     _scaling = Tween<double>(begin: 0.0, end: 1.0).animate(_controller);
> > 
> >     _scaling.addListener((){
> >       setState((){
> >         _scale = _scaling.value;
> >       });
> >     });
> >   }
> > 
> >   _DetailPhotoScreenState(this._image);
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Stack(
> >       children: <Widget>[
> >         GestureDetector(
> >           onDoubleTap: () {
> >             setState(() {
> >               _translate = Offset(0.0, 0.0);
> >               _scale = 1.0;
> >             });
> >           },
> >           child: Center(
> >             child: Container(
> >               color: Colors.black,
> >               child: GestureDetector(
> >                 onPanUpdate: (x) {
> >                   setState(() {
> >                     _translate = _translate + x.delta;
> >                   });
> >                 },
> >                 child: Transform.translate(
> >                   offset: _translate,
> >                   child: Transform.scale(
> >                     scale: _scale,
> >                     child: AssetThumb(
> >                       asset: _image,
> >                       width: _image.originalWidth,
> >                       height: _image.originalHeight,
> >                     ),
> >                   ),
> >                 ),
> >               ),
> >             ),
> >           ),
> >         ),
> >         Align(
> >           alignment: AlignmentDirectional.bottomEnd,
> >           child: Container(
> >             width: 50.0,
> >             height: 50.0,
> >             margin: EdgeInsets.only(right: 80.0, bottom: 15.0),
> >             child: RaisedButton.icon(
> >               onPressed: () {
> >                 setState((){
> >                   if (_scale < 10){
> >                     _scaling = Tween<double>(begin: _scale, end: _scale*2.0).animate(_controller);
> >                     _controller.reset();
> >                     _controller.forward();
> >                   }
> >                 });
> >               },
> >               icon: Icon(Icons.zoom_in, color: Colors.white70),
> >               label: Text(""),
> >               shape: RoundedRectangleBorder(
> >                   borderRadius: BorderRadius.all(Radius.circular(25.0))),
> >               color: Theme.of(context).primaryColor,
> >             ),
> >           ),
> >         ),
> >         Align(
> >           alignment: AlignmentDirectional.bottomEnd,
> >           child: Container(
> >             width: 50.0,
> >             height: 50.0,
> >             margin: EdgeInsets.only(right: 15.0, bottom: 15.0),
> >             child: RaisedButton.icon(
> >               onPressed: () {
> >                 setState((){
> >                   if (_scale > 0.1){
> >                     _scaling = Tween<double>(begin: _scale, end: _scale*0.5).animate(_controller);
> >                     _controller.reset();
> >                     _controller.forward();
> >                   }
> >                 });
> >               },
> >               icon: Icon(Icons.zoom_out, color: Colors.white70),
> >               label: Text(""),
> >               shape: RoundedRectangleBorder(
> >                   borderRadius: BorderRadius.all(Radius.circular(25.0))),
> >               color: Theme.of(context).primaryColor,
> >             ),
> >           ),
> >         ),
> >       ],
> >     );
> >   }
> > }
> > ```
> 
> but I don't want to listener onDoubleTap.

when I click the empty area, it will throw this error.

**Comment by kecson** [comment]
但我只是想要显示一个文本而已，不需要加GestureDetector手势处理呢。 ，然后2个手指同时点击点击报错了， 难道在APP内每个文本显示的Text都加上GestureDetector去处理这个问题吗





------------------ 原始邮件 ------------------
发件人: "LeandroMoura3"<notifications@github.com>;
发送时间: 2019年7月18日(星期四) 凌晨5:05
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "kecson"<kecson@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [flutter/flutter] 'package:flutter/src/gestures/monodrag.dart':Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is nottrue (#36350)




Same here:
  
E/flutter (22777): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons == kPrimaryButton': is not true.
 E/flutter (22777): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
 E/flutter (22777): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
 E/flutter (22777): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
 E/flutter (22777): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
 E/flutter (22777): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
 E/flutter (22777): #5      GestureArenaManager.release (package:flutter/src/gestures/arena.dart:199:7)
 E/flutter (22777): #6      DoubleTapGestureRecognizer._reset (package:flutter/src/gestures/multitap.dart:260:44)
 E/flutter (22777): #7      _rootRun (dart:async/zone.dart:1120:38)
 E/flutter (22777): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
 E/flutter (22777): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
 E/flutter (22777): #10     _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
 E/flutter (22777): #11     _rootRun (dart:async/zone.dart:1124:13)
 E/flutter (22777): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
 E/flutter (22777): #13     _CustomZone.bindCallback. (dart:async/zone.dart:947:23)
 E/flutter (22777): #14     Timer._createTimer. (dart:async-patch/timer_patch.dart:21:15)
 E/flutter (22777): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
 E/flutter (22777): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
 E/flutter (22777): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
 E/flutter (22777):
 I/flutter (22777): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.
  
Here is the code:
 `import 'package:flutter/material.dart';
 import 'package:multi_image_picker/multi_image_picker.dart';
 
class DetailPhotoScreen extends StatefulWidget {
 final _image;
 
DetailPhotoScreen(this._image);
 
@override
 _DetailPhotoScreenState createState() => _DetailPhotoScreenState(_image);
 }
 
class _DetailPhotoScreenState extends State
 with TickerProviderStateMixin{
 final _image;
 double _scale = 1.0;
 Offset _translate = Offset(0.0, 0.0);
 Animation _scaling;
 AnimationController _controller;
 
@override
 void initState() {
 super.initState();
 _controller = AnimationController(duration: Duration(milliseconds: 250), vsync: this);
 _scaling = Tween<double>(begin: 0.0, end: 1.0).animate(_controller); _scaling.addListener((){   setState((){     _scale = _scaling.value;   }); });  
}
 
_DetailPhotoScreenState(this._image);
 
@override
 Widget build(BuildContext context) {
 return Stack(
 children: [
 GestureDetector(
 onDoubleTap: () {
 setState(() {
 _translate = Offset(0.0, 0.0);
 _scale = 1.0;
 });
 },
 child: Center(
 child: Container(
 color: Colors.black,
 child: GestureDetector(
 onPanUpdate: (x) {
 setState(() {
 _translate = _translate + x.delta;
 });
 },
 child: Transform.translate(
 offset: _translate,
 child: Transform.scale(
 scale: _scale,
 child: AssetThumb(
 asset: _image,
 width: _image.originalWidth,
 height: _image.originalHeight,
 ),
 ),
 ),
 ),
 ),
 ),
 ),
 Align(
 alignment: AlignmentDirectional.bottomEnd,
 child: Container(
 width: 50.0,
 height: 50.0,
 margin: EdgeInsets.only(right: 80.0, bottom: 15.0),
 child: RaisedButton.icon(
 onPressed: () {
 setState((){
 if (_scale < 10){
 _scaling = Tween(begin: _scale, end: _scale2.0).animate(_controller);
 _controller.reset();
 _controller.forward();
 }
 });
 },
 icon: Icon(Icons.zoom_in, color: Colors.white70),
 label: Text(""),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.all(Radius.circular(25.0))),
 color: Theme.of(context).primaryColor,
 ),
 ),
 ),
 Align(
 alignment: AlignmentDirectional.bottomEnd,
 child: Container(
 width: 50.0,
 height: 50.0,
 margin: EdgeInsets.only(right: 15.0, bottom: 15.0),
 child: RaisedButton.icon(
 onPressed: () {
 setState((){
 if (_scale > 0.1){
 _scaling = Tween(begin: _scale, end: _scale0.5).animate(_controller);
 _controller.reset();
 _controller.forward();
 }
 });
 },
 icon: Icon(Icons.zoom_out, color: Colors.white70),
 label: Text(""),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.all(Radius.circular(25.0))),
 color: Theme.of(context).primaryColor,
 ),
 ),
 ),
 ],
 );
 }
 }
 `

**Comment by rockingdice** [comment]
Met the same issue. happened on an iOS device, not sure about Android.
I rapidly tap a GestureDetector with two fingers. This assert will block all later touches. The user cannot continue to use the app after that.

**Comment by kecson** [comment]
> I'm guessing it's the same issue as #37466, which I have a fix that has just been merged. Please check if the current master (or wait until the next release of your channel) fixes this problem.

Thanks, when is it released to a stable channel?

**Comment by danieldai** [comment]
Is there any workaround before the fix released to a stable channel？

**Comment by dkwingsmt** [comment]
@danieldai My suggestion is to switch to dev channel for now, and beta channel once a new beta is out.  My apology for the inconvenience.

**Comment by dkwingsmt** [comment]
Status: Waiting for this to land on stable.

**Comment by DIVINER-onlys** [comment]
I add a long press event to solve

**Comment by phj7777777** [comment]
> Status: Waiting for this to land on stable.

Hii, is this fix been landed on stable version?

**Comment by dkwingsmt** [comment]
@phj7777777 Yes, this will be landed in the upcoming stable that has just been frozen.

**Comment by masashi-sutou** [comment]
I think this issue fixed in stable `1.12.13+hotfix.5`.

Did you forget to colse issue or is there still a problem?

**Comment by kecson** [comment]
this issue fixed in stable 1.12.13+hotfix.5.

**Comment by 33-Elephants** [comment]
The problem still exists - there is no scenario, but screen is getting frozen randomly. When tapping on screen we get the following log: 

ViewRootImpl@131b3b9[FlutterActivity]: ViewPostIme pointer 0
ViewRootImpl@131b3b9[FlutterActivity]: ViewPostIme pointer 1
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 407 pos 12: '_initialButtons == kPrimaryButton': is not true.

flutter doctor:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/artem/Development/flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/artem/Development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/artem/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/artem/Development/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Nexus 5   • 07e3ff7c0de4bdf7 • android-arm   • Android 6.0.1 (API 23)
    • SM N970U1 • R58MA5ZACRT      • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by dkwingsmt** [comment]
@33-Elephants Can you come up with a minimal example and/or reproducible steps?

**Comment by matehat** [comment]
It also happened to me just now, in development, using a iPad testing device, on `v1.12.13+hotfix.5`.

**Comment by akshaybengani** [comment]
The issue still persists and it screen freezes.
`
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (3 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2
(base) SW-LP10342:tribes malav.desai$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.1 at /Users/malav.desai/Project/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/malav.desai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • HD1901 • 917fed4e • android-arm64 • Android 10 (API 29)

• No issues found!
`

**Comment by akshaybengani** [comment]
Container(
                      height: MediaQuery.of(context).size.height * 0.5,
                      child: CarouselSlider(
                        options: CarouselOptions(
                          viewportFraction: 0.75,
                          aspectRatio: 4 / 5,
                          height: MediaQuery.of(context).size.height,
                          enlargeCenterPage: true,
                          autoPlay: false,
                          enableInfiniteScroll: false,
                        ),
                        items: state.user.userTribes
                            .map(
                              (UserTribe userTribe) => Card(
                                shape: RoundedRectangleBorder(
                                    borderRadius: CustomTheme.circular()),
                                child: GestureDetector(
                                  
                                  dragStartBehavior: DragStartBehavior.start,
                                  onTap: () async {
                                    await userRepository.updateUserTribeId(
                                      userTribe.user.id,
                                      userTribe.tribe.id,
                                    );
                                    Navigator.of(context).push(
                                      MaterialPageRoute(
                                        builder: (context) =>
                                            BlocProvider<ConversationBloc>(
                                          create: (context) =>
                                              ConversationBloc()
                                                ..add(
                                                  GetConversation(
                                                    userId: userTribe.user.id,
                                                    tribeId:
                                                        userTribe.tribe.id,
                                                  ),
                                                ),
                                          child: ConversationScreen(),
                                        ),
                                      ),
                                    );
                                  },
                                  child: Stack(
                                    children: <Widget>[
                                      Container(
                                        decoration: BoxDecoration(
                                          borderRadius:
                                              CustomTheme.circular(),
                                          image: DecorationImage(
                                            fit: BoxFit.cover,
                                            image: userTribe.tribe.imageUrl ==
                                                    null
                                                ? AssetImage(
                                                    "assets/images/wallpaper.png")
                                                : NetworkImage(
                                                    userTribe.tribe.imageUrl),
                                          ),
                                        ),
                                      ),
                                      Container(
                                        width: double.infinity,
                                        decoration: BoxDecoration(
                                          borderRadius:
                                              CustomTheme.circular(),
                                          gradient: LinearGradient(
                                              begin: Alignment.topLeft,
                                              end: Alignment.bottomRight,
                                              colors: [
                                                Colors.grey.shade900,
                                                Colors.transparent
                                              ],
                                              stops: [
                                                0.0,
                                                1.0
                                              ]),
                                        ),
                                        child: Padding(
                                          padding: EdgeInsets.all(20),
                                          child: Column(
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: <Widget>[
                                              Text(
                                                userTribe.tribe.name,
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .headline1,
                                              ),
                                              SizedBox(height: 10),
                                              Text(
                                                userTribe.tribe.hintText,
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .bodyText1,
                                              ),
                                              
                                            ],
                                          ),
                                        ),
                                      ),

                                    ],
                                  ),
                                ),
                              ),
                            )
                            .toList(),
                      ),
                    ),

**Comment by akshaybengani** [comment]
`
                    Container(
                      height: MediaQuery.of(context).size.height * 0.5,
                      child: CarouselSlider(
                        options: CarouselOptions(
                          viewportFraction: 0.75,
                          aspectRatio: 4 / 5,
                          height: MediaQuery.of(context).size.height,
                          enlargeCenterPage: true,
                          autoPlay: false,
                          enableInfiniteScroll: false,
                        ),
                        items: state.user.userTribes
                            .map(
                              (UserTribe userTribe) => Card(
                                shape: RoundedRectangleBorder(
                                    borderRadius: CustomTheme.circular()),
                                child: GestureDetector(
                                  
                                  dragStartBehavior: DragStartBehavior.start,
                                  onTap: () async {
                                    await userRepository.updateUserTribeId(
                                      userTribe.user.id,
                                      userTribe.tribe.id,
                                    );
                                    Navigator.of(context).push(
                                      MaterialPageRoute(
                                        builder: (context) =>
                                            BlocProvider<ConversationBloc>(
                                          create: (context) =>
                                              ConversationBloc()
                                                ..add(
                                                  GetConversation(
                                                    userId: userTribe.user.id,
                                                    tribeId:
                                                        userTribe.tribe.id,
                                                  ),
                                                ),
                                          child: ConversationScreen(),
                                        ),
                                      ),
                                    );
                                  },
                                  child: Stack(
                                    children: <Widget>[
                                      Container(
                                        decoration: BoxDecoration(
                                          borderRadius:
                                              CustomTheme.circular(),
                                          image: DecorationImage(
                                            fit: BoxFit.cover,
                                            image: userTribe.tribe.imageUrl ==
                                                    null
                                                ? AssetImage(
                                                    "assets/images/wallpaper.png")
                                                : NetworkImage(
                                                    userTribe.tribe.imageUrl),
                                          ),
                                        ),
                                      ),
                                      Container(
                                        width: double.infinity,
                                        decoration: BoxDecoration(
                                          borderRadius:
                                              CustomTheme.circular(),
                                          gradient: LinearGradient(
                                              begin: Alignment.topLeft,
                                              end: Alignment.bottomRight,
                                              colors: [
                                                Colors.grey.shade900,
                                                Colors.transparent
                                              ],
                                              stops: [
                                                0.0,
                                                1.0
                                              ]),
                                        ),
                                        child: Padding(
                                          padding: EdgeInsets.all(20),
                                          child: Column(
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: <Widget>[
                                              Text(
                                                userTribe.tribe.name,
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .headline1,
                                              ),
                                              SizedBox(height: 10),
                                              Text(
                                                userTribe.tribe.hintText,
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .bodyText1,
                                              ),
                                              
                                            ],
                                          ),
                                        ),
                                      ),

                                    ],
                                  ),
                                ),
                              ),
                            )
                            .toList(),
                      ),
                    ),

`

**Comment by yourshinsuke** [comment]
not yet 1.17

**Comment by ztigunes** [comment]
i have same issue. Are there any bug fix or workaround solution ?


flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 416 pos 12: '_initialButtons ==
flutter: kPrimaryButton': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      DragGestureRecognizer._checkEnd 
package:flutter/…/gestures/monodrag.dart:416
flutter: #3      DragGestureRecognizer.didStopTrackingLastPointer 
package:flutter/…/gestures/monodrag.dart:358
flutter: #4      OneSequenceGestureRecognizer.stopTrackingPointer 
package:flutter/…/gestures/recognizer.dart:343
flutter: #5      DragGestureRecognizer._giveUpPointer 
package:flutter/…/gestures/monodrag.dart:367
flutter: #6      DragGestureRecognizer.handleEvent 
package:flutter/…/gestures/monodrag.dart:256
flutter: #7      PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:78

igunes@igunes ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TR)
    • Flutter version 1.20.3 at /users/igunes/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/igunes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Mustafa’s iPad (mobile) • ec9cc0171e4772f3dbca05f0c732828429310826 • ios •
      iOS 13.5.1

**Comment by flutterfrank** [comment]
I have the same issue too.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while dispatching a pointer event:[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons == kPrimaryButton': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      DragGestureRecognizer._checkStart[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#3      DragGestureRecognizer.acceptGesture[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#4      GestureArenaManager.sweep[39;49m 
 package:flutter/…/gestures/arena.dart
[38;5;244m#5      GestureBinding.handleEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#6      GestureBinding.dispatchEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m...[39;49m
[38;5;244mEvent: PointerUpEvent#d0714(position: Offset(26.0, 242.3))[39;49m
    [38;5;244mposition: Offset(26.0, 242.3)[39;49m
[38;5;244mTarget: <WidgetsFlutterBinding>[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons ==
kPrimaryButton': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
[38;5;244m#2      DragGestureRecognizer._checkStart[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#3      DragGestureRecognizer.acceptGesture[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#4      GestureArenaManager.sweep[39;49m 
 package:flutter/…/gestures/arena.dart
[38;5;244m#5      GestureBinding.handleEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#6      GestureBinding.dispatchEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#7      GestureBinding._handlePointerEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#8      GestureBinding._flushPointerEventQueue[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#9      GestureBinding._handlePointerDataPacket[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#13     _invoke1  (dart:ui/hooks.dart:267:10)[39;49m
[38;5;244m#14     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)[39;49m
(elided 5 frames from class _AssertionError and dart:async)
Event:
  PointerUpEvent#d0714(position: Offset(26.0, 242.3))
Target:
  <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

[38;5;248m════════ Exception caught by gesture library ═══════════════════════════════════[39;49m
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m



Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1082], locale de-DE)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.49.0)
[√] Connected device (1 available)

• No issues found!

**Comment by ztigunes** [comment]
i have same issue. Are there any bug fix or workaround solution ? When i use tabbar like dummy user with two or three finger (gesture) it freeze all tab bar views.

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 416 pos 12: '_initialButtons ==
flutter: kPrimaryButton': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter: https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2 DragGestureRecognizer._checkEnd
package:flutter/…/gestures/monodrag.dart:416
flutter: #3 DragGestureRecognizer.didStopTrackingLastPointer
package:flutter/…/gestures/monodrag.dart:358
flutter: #4 OneSequenceGestureRecognizer.stopTrackingPointer
package:flutter/…/gestures/recognizer.dart:343
flutter: #5 DragGestureRecognizer._giveUpPointer
package:flutter/…/gestures/monodrag.dart:367
flutter: #6 DragGestureRecognizer.handleEvent
package:flutter/…/gestures/monodrag.dart:256
flutter: #7 PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:78

igunes@igunes ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TR)
• Flutter version 1.20.3 at /users/igunes/flutter
• Framework revision 216dee6 (13 days ago), 2020-09-01 12:24:47 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
• Android SDK at /Users/igunes/Library/Android/sdk
• Platform android-30, build-tools 30.0.0
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.7, Build version 11E801a
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 48.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.14.1

[✓] Connected device (1 available)
• Mustafa’s iPad (mobile) • ec9cc0171e4772f3dbca05f0c732828429310826 • ios •
iOS 13.5.1

**Comment by FickleLife** [comment]
I am starting to get this error too. Happens when I scroll the page quickly with the mouse pointer (seeing this on iOS14 Simulator). Error is:
```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons ==
kPrimaryButton': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      DragGestureRecognizer._checkStart 
package:flutter/…/gestures/monodrag.dart:379
#3      DragGestureRecognizer.acceptGesture 
package:flutter/…/gestures/monodrag.dart:310
#4      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:158
#5      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:224
#6      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
#7      GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
#8      GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
#9      GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
#13     _invoke1  (dart:ui/hooks.dart:267:10))
#14     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5))
(elided 5 frames from class _AssertionError and dart:async)
Event:
  PointerUpEvent#73670(position: Offset(0.0, 812.0))
Target:
  <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
```
and flutter doctor:
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.4 at /Applications/flutter
    • Framework revision fba99f6cf9 (4 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alexblack/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 5CFD3069-FA5A-4B04-9E94-E80AFB173593 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

**Comment by furkankurt** [comment]
Same issue here. How to solve it? Help!!

**Comment by LorTos** [comment]
Started having the same issue on **iOS 14 simulator**. For me it happens consistently when using a `CustomScrollView` with a `SliverAppBar`, either by just scrolling or when tapping the back button after having scrolled.

```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons ==
kPrimaryButton': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      DragGestureRecognizer._checkEnd
package:flutter/…/gestures/monodrag.dart
#3      DragGestureRecognizer.didStopTrackingLastPointer
package:flutter/…/gestures/monodrag.dart
#4      OneSequenceGestureRecognizer.stopTrackingPointer
package:flutter/…/gestures/recognizer.dart
#5      DragGestureRecognizer._giveUpPointer
package:flutter/…/gestures/monodrag.dart
#6      DragGestureRecognizer.handleEvent
package:flutter/…/gestures/monodrag.dart
#7      PointerRouter._dispatch[39;49m
package:flutter/…/gestures/pointer_router.dart
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#10     PointerRouter._dispatchEventToRoutes[39;49m
package:flutter/…/gestures/pointer_router.dart
#11     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart
#12     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart
#13     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart
#14     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart
#15     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart
#16     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart
#17     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart
#21     _invoke1 (dart:ui/hooks.dart:265:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
(elided 5 frames from class _AssertionError and dart:async)

router: Instance of 'PointerRouter'
route: Closure: (PointerEvent) => void from Function 'handleEvent':.
event: PointerMoveEvent#c9147(position: Offset(0.0, 812.0))
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by AndrsDev** [comment]
@LorTos This issue is happening to me too!

**Comment by razvangeangu** [comment]
This is happening to me in the simulator as well.

**Comment by lbjlsy** [comment]
This issue is happening to me too!

**Comment by TheFedex87** [comment]
Same here, ios 14 Emulator and I'm getting this error on a SliverAppBar inside a NestedScrollView. I didn' still try on a real device

**Comment by marcellocamara** [comment]
Why this issue is closed if it's not fixed? I face this problem at Flutter (Channel stable, 1.22.4, on Microsoft Windows [versão 10.0.18363.1198], locale pt-BR)

```
════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following _CastError was thrown while dispatching a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321:60)
#1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
#3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
...
Event: PointerUpEvent#8ccd7(position: Offset(190.5, 166.8))
  position: Offset(190.5, 166.8)
Target: <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 0

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 1
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 0

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 1
```

**Comment by diego-lipinski-de-castro** [comment]
Why is this closed? Just got into this problem.

1.22.5 • channel stable

**Comment by mohamadalmoayad** [comment]
problem still exist even after last upgrade to version 1.22.6

**Comment by VictorCamargo** [comment]
I'm facing the same problem on flutter 1.22.4. iOS simulator 14.4 iPhone 12 Pro Max.

**Comment by dkwingsmt** [comment]
I'm aware that many people are still encountering related crashes and this definitely needs fixing. Another ticket has been opened in https://github.com/flutter/flutter/issues/75061 where some people has posted some investigations. For now I myself am too occupied on another project to investigate this issue, but I still encourage everyone to post reproduction and/or investigation into the new issue, if any, and I'll come back as soon as possible. My apology for not being able to drive it right now.

**Comment by niypoo** [comment]
same issue with me

**Comment by dkwingsmt** [comment]
@niypoo Can you check which version you're on with `flutter --version`? This should have landed to 2.0.2 (https://github.com/flutter/flutter/commit/8962f6dc68ec8e2206ac2fa874da4a453856c7d3)

**Comment by S1nPur1ty** [comment]
Yep, same here with the most recent Flutter version..

**Comment by JohnnyRainbow81** [comment]
Same here with Flutter 2.0.3

**Comment by caiphaav** [comment]
Same here with Android emulator
