### ISSUE TITLE
[connectivity] sample project: “Lost connection to device” error after switch network. 

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#36609]
## Steps to Reproduce

1. I using [https://github.com/flutter/plugins/tree/master/packages/connectivity/example](https://github.com/flutter/plugins/tree/master/packages/connectivity/example)
2. Change code sign, and run on my iPhone
3. Switch off/on mobile network.
4. Xcode will show alert 'Lost connection to `my device`'.

So that I can't debug this API([`connectivity 0.4.3+6`](https://pub.dev/packages/connectivity))'s stream feature on device.

## Logs

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-CN)
    • Flutter version 1.7.8+hotfix.3 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision b712a172f9 (11 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0
```

**Comment by jerryzhoujw** [comment]
its's maybe solved by [libusbmuxd 6539b02](https://github.com/flutter/flutter/issues/35102#issuecomment-507393860)

**Comment by jerryzhoujw** [comment]
still have this problem with `usbmuxd HEAD-6539b02_1`

**Comment by BondarenkoStas** [comment]
@jerryzhoujw Is the issue still relevant? Can you please try it with current stable version?

**Comment by jerryzhoujw** [comment]
@BondarenkoStas  waiting https://github.com/flutter/flutter/issues/37699 to solved first, so I can't test it on device.

**Comment by jerryzhoujw** [comment]
@BondarenkoStas  this error not appear again on `v1.9.1+hotfix.3` (Channel `beta`) version now.  I close it now. 
 Also I found a issue `the Wifi IP is show correct address 192.168.X.X at first time, but show error when close wifi and open wifi again.`  I'll create the issue if still exist then it merge into channel stable.
