### ISSUE TITLE
Flutter application black screen in release mode when run only on Samsung J6+  

### ISSUE THREAD

**Issue by leovu** [flutter/flutter#37155]
## Steps to Reproduce

I tried to build an apk in release mode, it work ok on other device , but only on SS J6+ , OS 9.0, when open the app , the app run shows black screen and cannot do anything. 
I downgraded to Flutter v1.7.9 dev , it works perfectly. This bug happens with any apk in release mode run with this device (only happens when Flutter version is higher than v1.7.9) . I cannot show the log because when I tried to debug this bug, the phone run normally without black screen. 
These are the device's info' screenshots: 

![Screenshot_20190729-145630_Settings](https://user-images.githubusercontent.com/44394323/62031280-2bc48b80-b211-11e9-955b-014522f4cad5.jpg)
![Screenshot_20190729-143103_Settings](https://user-images.githubusercontent.com/44394323/62031207-08014580-b211-11e9-85dd-94158bf3bc4b.jpg)

**Comment by diego-develop** [comment]
You could check issue #36130, I'm still testing the fix they suggested there, but it is a very similar problem with a J6+.

**Comment by agueroveraalvaro** [comment]
Yes, that is the solution

> I downgraded to Flutter v1.7.9 dev , it works perfectly.

run `flutter version 1.7.9`

**Comment by BondarenkoStas** [comment]
@leovu Please check the updates at #36130. The fix is landed on master, but not yet included to stable or beta. Could you please check if it's reproducible using `master` channel?

**Comment by bayuramadeza** [comment]
is the new beta updates has included this fix?

**Comment by duduf15** [comment]
Same problem (J4+) for me with my latest release, many bad reviews on Play Store. I will not release my application from the master channel to get other bugs. It's not possible to doing an hotfix ? thx

**Comment by LazyDave76** [comment]
we're seeing this too.  :(

**Comment by BondarenkoStas** [comment]
@LazyDave76 It's available in v1.10.0, which is in Dev since September 6, but not yet on stable/beta. I'm going to close the issue as it should be already fixed. Please try, if you encounter it using any v1.10.0+, comment here and I will re-open it right away.

**Comment by 26shruti** [comment]
@BondarenkoStas Still getting it on v1.10.1

**Comment by catalin260** [comment]
Still getting it on the latest version v1.10.15. Please fix this issue as soon as possible. 
This is happening on many devices

**Comment by rymesaint** [comment]
i have the same problem with their phone who have samsung j4 plus and samsung j6 plus, any progress on this problem?

**Comment by MarcoMihaiCondrache** [comment]
Same issue for me i resolved it using the last version of master.
In stable the problem persist

**Comment by VladimirRychlitskiy** [comment]
Encountered the same issue on Galaxy J4+ (j4primelte)

**Comment by nerder** [comment]
Same problem with Samsung xj6

**Comment by BondarenkoStas** [comment]
I reopened it because @26shruti and @catalin260 encountered it in the after fix versions.

**Comment by akeblom** [comment]
Our customer did see this case of stuck black screen on app start . One iPhone 8 running 10.3.3 and one relatively new Samsung. So the problem seems to occur on both platforms. I cannot reproduce myself though.

**Comment by huergomartin** [comment]
Hi, yesterday I added internal testers with J6+ and J4+ in beta channel 1.10.7 and the black screen still appears. The bad comments on the store keep growing.

**Comment by liyuqian** [comment]
I can run flutter_gallery in release mode on my Galaxy J6+ without any black screens. Here's my version
- Galaxy J6+ Model number: SM-j610G/DS
- One UI version 1.0
- Android version 9
- Flutter version 440753bae8f324b7a9a2dd03516d9a12f1d9c761

Do you have a minimal Flutter app (single-file, hopefully less than 200 lines of code) that can reproduce the black screen in the master branch tip-of-tree Flutter?

Also loop in Skia engineer @brianosman early to see if he has some insights.

**Comment by sroddy** [comment]
this problem is serious: we are getting dozens of bad reviews coming from J4+ and J6+ users (which account for a total 1% of our user base (roughly 1000 installs).

I still didn't understand if the problem is fixed on current master or not, as We don't have access to that devices for testing them

**Comment by sroddy** [comment]
@liyuqian I see that you are not experiencing this issue on your J6+ device running on a commit that is still not released in a dev build. 

Can you please try to run the same on latest stable/beta/dev and check if you are able to reproduce this issue? If this is the case we can assume that a roll of the engine that is subsequent to the latest dev build has actually solved this issue.

Thanks a lot.

**Comment by liyuqian** [comment]
@sroddy : I just tested flutter_gallery on the dev branch 1946fc4da0f80c522d7e3ae7d4f7309908ed86f2 (v1.10.14) and there's no black screen with `flutter run --release`: https://photos.app.goo.gl/5HWDHArutiuiNFxU9

**Comment by sroddy** [comment]
@liyuqian thank you veery much!
what about current stable? If you see the black screen we can assume it's fixed. If you don't see it then there might be some OS-specific (or widget-specific) stuff that is causing it

**Comment by liyuqian** [comment]
@sroddy : I reproduced the black screen on the stable branch 1aedbb1835bd6eb44550293d57d4d124f19901f0 (v1.9.1+hotfix.5). So this seem to be fixed between stable and dev.

**Comment by sroddy** [comment]
Amazing news, thank you again @liyuqian 
I think it would be important to make sure that at least the beta channel (if it's impossible to back port the fix to the current stable channel), has the fix.
@huergomartin said that the issue was still present in beta, so it would be nice to understand which version (or even commit) effectively solved the issue

**Comment by AndersonSantosMedeiros** [comment]
Hey guys, I just found that in version v1.10.7, currently on beta channel, the black screen problem was gone. I've tested it on my J6 plus.

**Comment by huergomartin** [comment]
@liyuqian perfect !!! @AndersonSantosMedeiros that's a surprise, I'm going to retest with users on the beta channel and I will give you feedback. Thanks to everyone.

**Comment by icfilho** [comment]
I used the beta 1.10.17 and still remained the black screen on the Samsung J6. Has anyone got any solution for this? Thanks if you can help.

**Comment by liyuqian** [comment]
@icfilho : I think we were all testing on J6+ so it's possible that there's a different issue for J6. If it turns out that 1.10.7 is Ok for J6+, maybe you can create a new issue just for J6 and we can follow on that.

**Comment by icfilho** [comment]
> @icfilho : I think we were all testing on J6+ so it's possible that there's a different issue for J6. If it turns out that 1.10.7 is Ok for J6+, maybe you can create a new issue just for J6 and we can follow on that.

Excuse me. The device is J6+

**Comment by liyuqian** [comment]
@icfilho : I just tested flutter_gallery on J6+ with v1.10.7 without the black screen. Can you share us more information of how you reproduced the black screen? (What app are you using, can you share a screenshot, etc.)

@dxfrankowicz : I don't think the v1.9.1+hotfix.6 is fixing this issue...

**Comment by Lobosque** [comment]
I still have clients using J4 and J6+ having this issue. Our latest release is under 1.9.1+hotfix.6

**Comment by fillipetardelli** [comment]
Hi guys,

Based on this thread we updated our app to the flutter 1.9.1+hotfix.6 thinking that the problem was solved.
But we still getting negative user reviews facing the black screen problem.

The issue was already fixed? We need this fix ASAP plz.

**Comment by liyuqian** [comment]
@Lobosque @fillipetardelli : I don't think it's fixed in 1.9.1+hotfix.6 (see the [earlier comment](https://github.com/flutter/flutter/issues/37155#issuecomment-546544986)). The earliest version that I tested without showing the black screen is the beta v1.10.7 version.

**Comment by fillipetardelli** [comment]
@liyuqian are you already using this beta version in the production environment?

**Comment by kasonde** [comment]
Hi, I'm currently still experiencing this despite following this thread quietly. Can anyone recommend a flutter version that will at least get this issue out of our hands? We have a live app and it's affecting at least 10% of our users.

**Comment by akeblom** [comment]
> Hi, I'm currently still experiencing this despite following this thread quietly. Can anyone recommend a flutter version that will at least get this issue out of our hands? We have a live app and it's affecting at least 10% of our users.

What version are you running? As I understand the latest version on the beta channel is suppose to work.

**Comment by dxfrankowicz** [comment]
Latest beta version is working fine on J6+. Got feedback from my clients

**Comment by kasonde** [comment]
Okay thanks. I tried it earlier but i wasn’t able to compile it. For some reason only stable channel can compile an app on Android.

**Comment by liyuqian** [comment]
No problem. Glad to hear your clients to confirm the fix on the beta channel! Because of that, I'm going to close this issue. For other problems like the Android app won't compile with beta, maybe open a new issue to track it separately?

**Comment by kasonde** [comment]
@liyuqian I've done just that, it's here [#43895](https://github.com/flutter/flutter/issues/43895)

**Comment by Lobosque** [comment]
@liyuqian so there will be no backporting of the fix for 1.9.x?

**Comment by liyuqian** [comment]
If there were, it would be a hotfix. CC @tvolkert to evaluate if this needs a hot fix.

**Comment by tvolkert** [comment]
We're in the process of revamping our release process for the future, but in the meantime, hot-fixes are very painful for a number of reasons, so we generally avoid them.  @liyuqian what is the PR that fixed this?

**Comment by Lobosque** [comment]
I understand that the process for releasing a hotfix is not easy, but this
issue affects up to 4% of the user base of many apps, ours included.
Unless 1.10 stable is going to be released this week, please take the time
needed to push this hotfix.

**Comment by fillipetardelli** [comment]
@liyuqian why the issue was closed? what's the solution here?

The stable channel has no fix and we are facing erros triyng to compile the beta channel.
Even if the beta channel works, I think that the stable channel can't be named stable if there is a bug on it.

**Comment by rsacacio** [comment]
Hi @liyuqian , I have the same problem in my production app. I am getting bad ratings because of this. Do you have any plans to release the fixed version on the stable channel?

**Comment by liyuqian** [comment]
@tvolkert @Lobosque @rsacacio : I bisected the fix to https://github.com/flutter/flutter/commit/9769754d2, and I'll start our hotfix process.

@fillipetardelli : I closed this issue because it's confirmed to be fixed in our beta channel. But since now we're pushing it as a hotfix into the stable channel, I'm going to reopen it.

**Comment by liyuqian** [comment]
To make it clear, I started the hotfix **evaluation** process. I was told that such process does not always guarantee a hotfix (because there are many other issues that are competing our resources). We're working hard to satisfy everyone as much as possible.

For those who really want a quick fix, please feel free to cherry-pick https://github.com/flutter/flutter/commit/9769754d2 into your local stable Flutter checkout and test it.

**Comment by opensourcegps** [comment]
Please issue a hotfix. Flutter apps stopped working for thousands of devices (J6+ / J4+), thousands of live flutter apps affected. This is a major production problem affecting not only users, but also developers who get constant 1 star reviews because their app stopped working with black screen.

With hotfix5 not fixing any production issues, one would think this production problem would be hotfixed 2 weeks ago:  https://github.com/flutter/flutter/releases

**Comment by JCKodel** [comment]
At least on Samsung J4+ (I had to bought one =\): it works ONLY on beta channel, updated:

`Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale en-GB)`

**Comment by codxse** [comment]
> At least on Samsung J4+ (I had to buy one 😒): it works ONLY on beta channel, upgraded to 1.10.x:
> 
> `Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale en-GB)`

yes, but do successfully compile it? I can't compile it actually.

**Comment by JCKodel** [comment]
@codxse  If it works, it compiles =P Yes. Everything works fine (except the usual Flutter bugs - and there are plenty of them). The problem is that is not stable enough =\ Google Ads, for instance, crashes some devices =\

**Comment by ianrumac** [comment]
I wouldn't close this until it's in the `stable` channel. An issue like this needs a standalone hotfix instead of the solution being `update to beta or dev` which in itself brings another swat of changes we need to apply.

**Comment by Lobosque** [comment]
While I fully understand and accept all the risks that comes with depending on Open Source Software, and despite understanding the positive intent of the core team, I am disapointed that there is so much bureoucracy involved in releasing a fix for such a blocker, no matter how painful the release process is... Its been 3 months since the issue was opened.
@liyuqian is there any ETA on the evaluation process?

**Comment by liyuqian** [comment]
@tvolkert or @Hixie may have a more precise ETA. My ETA is that the fix will  be landed to the stable channel no more than 1.5 months.

**Comment by ianrumac** [comment]
Any idea what would be the blocker behind releasing the hotfix on the stable channel? Is it just review and testing processs or?

**Comment by rsfarias** [comment]
> Thanks for the hotfix, cherry-picked it!

@ianrumac Sorry for the beginner's question, but would you mind telling me the command you used to cherry-pick the fix into the stable channel?

Is it `git cherry-pick -x 9769754d2` from the stable channel?

**Comment by Xgamefactory** [comment]
> 
> 
> While I fully understand and accept all the risks that comes with depending on Open Source Software, and despite understanding the positive intent of the core team, I am disapointed that there is so much bureoucracy involved in releasing a fix for such a blocker, no matter how painful the release process is... Its been 3 months since the issue was opened.
> @liyuqian is there any ETA on the evaluation process?

Totally agree. We have same situation and many users encountered with black screen issue.
Flutter developers became so lazy. instead of working on useless features fixing such bug must be high priority otherwise in a short period flutter will became unreliable and good reason to switch back to facebook react.

**Comment by Hixie** [comment]
We make stable channel releases every 3 or 4 months, and beta channel releases, which are the same level of quality, every month (the only difference is that stable releases are usually released as part of an event). We do not generally intend to cherry pick fixes like this onto previous releases, for several reasons: 1. cherry picks are very risky (we do not have the ability to run all our tests on branches like we do for releases), and we don't want to make things worse; 2. if we did make cherry picks, the number of fixes we would cherry pick would be very high, at which point we might as well just release master as stable every day; and 3. cherry picking is an expensive process and we would rather spend our effort on making the next beta/stable release better.

I would encourage you to use whatever toolkit is best for your needs. While I hope Flutter is the best way for you to develop your apps, your needs may well be such that another SDK, such as React, is better for you, in which case that is what I would encourage you to use.

Calling people lazy in a derogatory sense is unacceptable behavior. Please consider our code of conduct before further posting on Flutter fora. Thanks.

**Comment by Xgamefactory** [comment]
Not everone using flutter for homeworks or simple project.
Instead of urgent hotfix for such big issue you just offer developers to wait for standard monthly stable release que.
@liyuqian expressed it very well
>  is so much bureoucracy involved in releasing a fix for such a blocker

**Comment by shinayser** [comment]
My clients started reporting black screens on both J6+ and J4 also =(

**Comment by Hixie** [comment]
@Xgamefactory you are continuing to not follow our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md), which requires being kind and respectful (your last comment was neither). Please avoid posting here or on other issues for the next few weeks.

**Comment by juumixx** [comment]
@zaralockheart we switched to beta to solve the issue. The released versions seem to be fine for iOS and Android, but since then I have lots of issues with hot reload in debug mode. Your developers might not like that :(

**Comment by raviganwal** [comment]
I come to this thread every day just to if there is any hotfix for this issue. My app is going to be live in a few weeks, but due to this issue, I am scared already.

**Comment by zaralockheart** [comment]
@juumixx Thanks for quick reply. If beta is good to go then I can set our CI to use beta while stay with stable for development. My only concern is if there's problem that stable don't have this issue but beta do and vice versa.

**Comment by ogrenichv** [comment]
We are using beta (1.10.7), no issues mentioned by @juumixx (at least on Android platform). Seems pretty stable for us.
The only thing we have to put up with is https://github.com/flutter/flutter/issues/43853 but I'm not sure that there is no such issue in current stable release.

**Comment by rsfarias** [comment]
@zaralockheart Unfortunately I can not say the same as the other guys. 

I've switched to beta 1.10.7 and started experiencing bugs in the camera plugin and strange behaviors with textfields (keyboard type changing and locking input). Camera and textfields work properly in stable channel, but not in beta channel. I've filed an issue for the [camera bug](https://github.com/flutter/flutter/issues/44436) already, which can be reproduced. I might have done something wrong, but do test your app thoroughly before using the beta channel.

**Comment by luisdiaz14** [comment]
Any news on this matter?
I am facing the same issue.

Thanks in advance.

**Comment by pkkhandsome** [comment]
I rolled back the version to 1.7.8 h4.

**Comment by tvolkert** [comment]
For what it's worth to everyone following this issue: we are aware of the pain inherent in our current release process, and we're currently in the process of designing a better release process -- one of the goals of which is to make it easier to cherrypick important fixes into existing stable releases.  We're not there yet, but we're working on it -- and in the meantime, I apologize for any painful choices you have to make in choosing which Flutter release you use to build your app.

**Comment by campioncino** [comment]
I rolled back to 1.7.8 hofix 4 for Android and 1.9.1 hotfix 6 for iOS

**Comment by campioncino** [comment]
> I rolled back the version to 1.7.8 h4.

I rolled back to 1.7.8 hofix 4 for Android and 1.9.1 hotfix 6 for iOS

**Comment by andreichiritescu** [comment]
same problem has been reported on Nokia 2.1 (E2M) Android 9 OpenGL ES version 3.0. As well as J6+ and J4+.
I have the utmost respect for the developers, but having a bug which affects more then 5% or the devices in a stable build and saying to wait 3-4 months is not acceptable for a stable release. A fix for this should be a blocker and if its not possible it should be specified in the release notes or by other means. Dont let us release in production a version which does not work for 5% of the users.

**Comment by liyuqian** [comment]
@tvolkert : I further bisected the fix downto engine commit https://github.com/flutter/engine/commit/12769335c486ff8cead000df7a8ec92781caebfc and Skia commit https://skia.googlesource.com/skia.git/+/ca8b07cf8a59f74ce959df49135940bec7bdc84e . The root cause of this failure is because the GPU driver of Samsung J4+ and J6+ reports the incorrect GLSL version number. The Skia fix is a workaround of that driver bug by limiting the GLSL version number to be no greater than the GL version.

**Comment by tvolkert** [comment]
@brianosman is there a test on the Skia side that will guard against a regression here?  See the previous comment for context.

**Comment by brianosman** [comment]
Not currently, no. We'd need a test that mocks a broken driver, and we don't have the framework for any tests like that (though it is possible). I've filed a bug about this on our end: https://bugs.chromium.org/p/skia/issues/detail?id=9656.

**Comment by tvolkert** [comment]
Thanks Brian.

Since the fix is on master, I'm going to close this issue.

**Comment by jeffwoooo** [comment]
After closing, can I expect to be noticed from this issue when the fix be merged into stable branch, or do I have to track it on my own?

**Comment by tvolkert** [comment]
The fix will definitely be in the next stable, which will be released within the next month.

**Comment by karatasemre** [comment]
@tvolkert Do we have to wait for the next month for this problem? We receive this error in our live corporate application and this is a big problem for us. What is your suggestion? Thanks.

**Comment by tvolkert** [comment]
The beta release that will become the next stable should be available in ~2 weeks.

**Comment by shinayser** [comment]
> The beta release that will become the next stable should be available in ~2 weeks.

Well, actually this fix is already on beta. I had to turn my brach to beta just because of that fix. I am using beta  `v1.10.7`.

**Comment by kevin4dhd** [comment]
![image](https://user-images.githubusercontent.com/22886367/69602880-fa08d900-0fe6-11ea-94eb-46a3dce59c5a.png)

I have V1.10.7 but the problem persists, someone else if it works well with this version?

**Comment by TheJulianJES** [comment]
I'm not sure if this is related, but I didn't want to create a new issue due to the lack of information.
I've had one person report, that my flutter app, built with the current beta channel, crashed on their "Huawei Y7 Prime 2019 (HWDUB-Q)" at startup.
After a downgrade to a version built from the stable channel, the problem went away.
I have no crashlogs, as it seems like the crashes were only caught by the Google Play Console (which only shows a very brief report and not by Firebase Crashlytics:)
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> de.tjjstudios.glplanflutter <<<

backtrace:
 
  #00  pc 000000000047cc4c  /data/app/de.tjjstudios.glplanflutter-Ed0RLKOLWu88CyFi1p0HaQ==/split_config.arm64_v8a.apk
 
  #01  pc 000000000004e6dc  /data/app/de.tjjstudios.glplanflutter-Ed0RLKOLWu88CyFi1p0HaQ==/split_config.arm64_v8a.apk
```

**Comment by JCKodel** [comment]
What I don't understand is: 1.9 has 6 hotfixes. Why the reluctance in such important fix now? I have an app with 1.6 million downloads, you can imagine the problems in release it with beta technology (I also have 1 star reviews with "won't open")

But is just for the sake of curiosity. I will never use Flutter again. Last update broke a lot of plugins... It's just too unstable for serious using.

**Comment by Lobosque** [comment]
```
What I don't understand is: 1.9 has 6 hotfixes. Why the reluctance in such important fix now?
```
@JCKodel I am having trouble understanding this. I really doubt that these 6 bugs that were fixed are more severe than this one.

I also do not understand the criteria of considering a bug fixed just because code is on master, when you do not have a stable release that includes the fix, or even a release date defined.

**Comment by opensourcegps** [comment]
LG Aristo 3+ (cv1s) is also affected by this problem.

**Comment by rafaelcorbellini-egsys** [comment]
I have the same inssue on` v1.12.15` a regreat to` v1.7.9` and works fine

**Comment by liyuqian** [comment]
@rafaelcorbellini-egsys : if there's still a black screen in `v1.12.15`, there might be another issue. Can you please provide us more details of how to reproduce the black screen? Are you also testing `flutter_gallery` app on a Samsung Galaxy J6+?

**Comment by tvolkert** [comment]
This issue is closed (original problem found and fixed).  Further discussion on this bug is likely to get lost.  @rafaelcorbellini-egsys please file a new issue with reproducible steps to track the new issue you're encountering.

**Comment by Hixie** [comment]
@zaralockheart 
> @Hixie With this, means that channel is good for production use right? We have this problem too at this point. I want to suggest to my development team to change to beta channel but I need your assurance to notify the team :)

FWIW, with the applications I publish on my own time I literally ship from dev. I just pick a dev build that I find works well for my app, then stick with it as I fix the last few bugs before uploading to the store. Then when I do an update later, I switch to a more recent dev.

**Comment by rafaelcorbellini-egsys** [comment]
My bad,for some reason i believe  in  test i was not at `1.12.5`.

I re-tested at `1.12.5`and it worked on Galaxy J6+

**Comment by Gyoko** [comment]
@tvolkert said that a stable release would be up in 2 weeks... 2 weeks ago. When will the black screen get fixed in stable release? I have a lot of dependencies now and rolling back to `1.7.9` is not an option without disabling a quarter of features.

**Comment by tvolkert** [comment]
Actually I said that "the _beta_ release that will become the next stable should be available in ~2 weeks."

The beta release is available as of yesterday.  The current beta release is `v1.12.13+hotfix.2`, which contains this fix.

**Comment by Gyoko** [comment]
_Sigh_, now that "black screen" users are okay, normal users start getting crashes at startup. I hope the new release process you're talking about works out.

**Comment by tvolkert** [comment]
> normal users start getting crashes at startup

@Gyoko if this is due to a bug in Flutter, can you file a new bug with info so we can track it down? Thanks!

**Comment by JCKodel** [comment]
> > normal users start getting crashes at startup
> 
> @Gyoko if this is due to a bug in Flutter, can you file a new bug with info so we can track it down? Thanks!

Why? So you can ignore for 2, 3 months as well?

**Comment by tvolkert** [comment]
@JCKodel such language is not helpful.  Please read and follow our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).  If you're not willing to adhere to it, then please refrain from commenting on issues.

**Comment by santiagorr207** [comment]
Buenos días, me pueden pasar el código completo de la versión donde esta solucionado el problema, gracias

**Comment by JCKodel** [comment]
> _Sigh_, now that "black screen" users are okay, normal users start getting crashes at startup. I hope the new release process you're talking about works out.

Same here.
Use beta for users with Adreno 308 and lose other users or rollback to whatever version is working and lose J4+, J6+, J7 Prime and other Adreno 308 users?

IT IS NOT POSSIBLE TO USE A BETA VERSION FOR PRODUCTION APPS. HOW HARD IS TO UNDERSTAND THAT?

Total regret in using Flutter >.<

**Comment by tvolkert** [comment]
@JCKodel we are trying to fix the bugs that are reported, but as far as I know, there's been no bug filed about the crashing on Adreno 308, so we have no way of investigating.

I ask again: will you (a) please file a bug about the new crash on beta, and (b) please use constructive, helpful language?

**Comment by tvolkert** [comment]
ping @Gyoko have you filed a bug about the crash?

**Comment by Gyoko** [comment]
@tvolkert
At least when on android, **after switching branches (`master `-> `beta`), updating app via GooglePlay results in black screen on start**. Meaning you need to perform a clean install for the app to actually work. I don't know whether this is caused by something in `1.12` or the channels themselves. But it does mean that this solution is nonviable - developer must explain each and every client (that decides to reach out, instead of leaving 1 star and moving on) that they need to reinstall the app. 

At this point I've accepted the fact that I will be moving to `1.7.9`, and somehow will figure out how to avoid disabling any of the features. 

Anyways, I do get why your dev team gets much hate, and I can't really say that it's undeserved. It's not the first time there are problems with flutter running on Samsung phones - you could've already acquired a few platforms for testing to ensure there are no half-baked `master `releases...
But at the same time Flutter has a LOT of potential - Fuchsia, Desktop. Keep up the ~~good~~ work. It will pay off :)

**Comment by JCKodel** [comment]
![image](https://user-images.githubusercontent.com/379339/70399067-e22a4f80-19ff-11ea-9766-a7bd71f510e7.png)

About 50% of my user base use crappy Samsungs and I have to inform them: choose between black screen or the app not opening.

Bugs are ok. Months to apply a fix THAT IS ALREADY READY is unacceptable.

Now a lot of bugs in iOS as well (regression bugs on google_sign_in).

WORST DECISION EVER TO USE FLUTTER!

**Comment by tvolkert** [comment]
@Gyoko it seems like there are multiple distinct issues being discussed, and it gets very confusing to try to discuss them all in one bug.  Also, again, the bug causing this issue has been found and fixed, so this bug is not the right venue to discuss new issues.  Thus, I filed https://github.com/flutter/flutter/issues/46570 to discuss to black screen on Play Store update, and I filed https://github.com/flutter/flutter/issues/46571 to discuss the crash that you reported.  Please add information to those bugs so we can have a look.

@JCKodel you continue to not follow our code of conduct, so unfortunately, I'm going to block you for 10 days.  If you would like to continue to engage pleasantly, we'd be happy to listen and try to address any issues you run into.

**Comment by myriky** [comment]
did you know that SAMSUNG GALAXY S7 (Qualcomm Snapdragon 820 Models) also affected by this problem.

**Comment by ric-cl** [comment]
Hi,
Any update of when the stable update with this fix will be available (pre-christmas gift) please.

**Comment by tvolkert** [comment]
@ric-cl we're going through the final testing of the next stable - it should be any day now (definitely before Christmas 🙂)

**Comment by tvolkert** [comment]
This fix is now available on the stable channel (`v1.12.13+hotfix.5`)

**Comment by davidmartos96** [comment]
@myriky Does the latest stable version fixes the problem you mention with the Samsung Galaxy S7?

**Comment by hermanmaritz** [comment]
> This fix is now available on the stable channel (`v1.12.13+hotfix.5`)

Thank you!

Updated our app last night. Still getting in reports (7 in the last 5 hours) specific to Huawei Y7 Prime 2019 (HWDUB-Q), but this might be different issues - seems to be a crash.
For example:
> ★
> Oh no... The newest version suddenly doesn't work anymore. It just closes on its own as you try open it. I did uninstall and reinstall.

Don't see anything in crash reports (yet). Thanks again!

**Comment by tvolkert** [comment]
Thanks @hermanmaritz!  If you get details on the crash, please mention me on the issue, and I'll have a look.

**Comment by TheJulianJES** [comment]
@hermanmaritz I'm also seeing crashes on the Google Play Console for the "Huawei Y7 Prime 2019 (HWDUB-Q), Android 8.1" (with v1.12.13+hotfix.5 and prior beta versions).
However, I'm unable to file a new issue, as I don't have any crash logs myself. (Firebase Crashlytics has no logs of any of the 32 crashes) and the Google Play Console also doesn't show very much in terms of a crashlog.

The only thing I can say is that after I sent the user an earlier build using Flutter v1.9.1+hotfix.6, it seems to work fine. So a new issue should probably be filled for this.

**Comment by Xgamefactory** [comment]
we will wait for couple weeks  to be sure that this release really stable.

**Comment by n0tc0ding** [comment]
Hello @hermanmaritz @TheJulianJES , any news about the crashes on Huawei?

**Comment by hermanmaritz** [comment]
Unfortunately from 15 App Reviews on the app I can confirm that the "Black screen" us still an issue on `Y7 Prime 2019 (HWDUB-Q)`. If there is something I can do to help debug this let me know? 

```
flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (5 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
```

**Comment by birtanyildiz** [comment]
we are facing this problem with honor 8c and huawei y7 prime 2019 devices.( May be its not the same with samsung j4 / j6 ) on google play console we can only see the error like this. I am trying to find a device may be i can reach more information after that. but its only on theese devices.
![image](https://user-images.githubusercontent.com/810556/70914116-66945800-2028-11ea-937a-fe15f86dc3c1.png)

**Comment by liyuqian** [comment]
@birtanyildiz @hermanmaritz @TheJulianJES : since this issue is Samsung specific, I created a new issue https://github.com/flutter/flutter/issues/47164 for Huawei. Let's redirect our future discussions and fix on the Huawei devices there.

**Comment by abdulmueizrosli** [comment]
Unfortunately the "Black screen" still an issue on VIVO V5 Plus.

E:\Flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale en-MY)
    • Flutter version 1.12.13+hotfix.5 at E:\Flutter\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6

**Comment by premtemp1** [comment]
Any solution... I am seeing this error on LG --OS9

**Comment by tmatrai** [comment]
I have an app in Google Play with some thousand users, and I still have one star reviews related with black screen issues. On 95% of the devices is okkey, but on others it is still an issue. 

My latest app release is built on Flutter 1.12.13+hotfix5 (stable channel).

**Comment by LuizLeite** [comment]
Hi. In my case, i removed the "get_ip" package, and the black screen is gone, the app is back up and running.

**Comment by dumplings** [comment]
![WechatIMG71](https://user-images.githubusercontent.com/16367785/73610087-cb266900-460e-11ea-9dba-b8c305b46c32.jpeg)
the same issues with me.

 ~ flutter --version
Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (6 days ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0

**Comment by campioncino** [comment]
Do you know if the v1.12.13+hotfix.7 solve the Huawei problem?

**Comment by LuizLeite** [comment]
Hi.I am trying to believe that these are packages that have not been upgraded to version 1.12.xx of Flutter. Try to remove them and test. If the problem persists, then it’s up to the folks at Google.

Luiz Leite
 

    Em terça-feira, 4 de fevereiro de 2020 04:59:41 BRT, campioncino <notifications@github.com> escreveu:  
 
 
Do you know if the v1.12.13+hotfix.7 solve the Huawei problem?

**Comment by liyuqian** [comment]
@tmatrai : v1.12.13+hotfix.5 is known to have some blackscreen issues and it's fixed in v1.12.13+hotfix.7. Please see https://github.com/flutter/flutter/issues/47164

@dumplings : what device did you see the blackscreen problem with v1.12.13+hotfix.7 ?

@GaryQian : can you please double check v1.12.13+hotfix.7 with the Huawei devices that we recently purchased, and the Samsung J6+ device (probably in my drawer)? I believe they should be fixed in v1.12.13+hotfix.7.

**Comment by costarf** [comment]
Updated to v1.12.13+hotfix.7 and still get the error on J4 and Huawei.

Any estimate when this will be really fixed?

**Comment by GaryQian** [comment]
@costarf What devices exactly are you testing on? I just verified that this crash is fixed on Huawei Y7Pro/Enjoy9 (DUB AL20) and Huawei Honor8C (BKK AL10) as well as Samsung J6+ (SM-J610G)

Also, is this happening with a minimal app such as the hello world app from `flutter create`?

**Comment by Bernardomrf** [comment]
I had some problems like this, after I migrated my flutter project to AndroidX. On some android devices the app wouldn't pass the splash screen.

**Solution:**
I discovered that I had the _android:hardwareAccelerated_ variable set to false, in AndroidManifest.xml. After I set it to true, I got the app working on those android devices.

I'm using the Stable channel - v1.12.13+hotfix.8.

**Comment by liyuqian** [comment]
@xster : according to https://github.com/flutter/flutter/issues/37155#issuecomment-585177594, we might have issues when android:hardwareAccelerated is set to false. Do we support setting android:hardwareAccelerated to false? If so, there seems to be a bug. If not, maybe we should make it impossible to set it to false.

**Comment by xster** [comment]
@liyuqian this is probably a question for @jason-simmons or @chinmaygarde what our official level of support is for software rendering on Android for debug or in general. 

This is also probably the same question as ramifications to https://github.com/flutter/flutter/issues/47804 and whether it could cause more obscure issues down the line.

**Comment by liyuqian** [comment]
@xster : the software backend should be quite solid as all Google-internal golden tests are running with software rendering. The only downside of using software rendering is the performance hit as far as I know.

Do you suggest to fallback to software if the GPU backend fails to initialize? If so, I think we first have to establish some alerting system so we won't let some GPU issues slip through and cause wide performance regressions without detections.

**Comment by xster** [comment]
Ah, good to know. Let's continue on https://github.com/flutter/flutter/issues/50900. Once we establish signaling like you're saying, we can just fail on benchmarks on software fallbacks.

**Comment by mohamed-eltwahy** [comment]
> Hi. In my case, i removed the "get_ip" package, and the black screen is gone, the app is back up and running.

how i can do this?

**Comment by LuizLeite** [comment]
Hi.

Just remove the package from the pubspec.yaml file.


Luiz Leite
 

    Em quinta-feira, 12 de março de 2020 08:46:41 BRT, mohamed-eltwahy <notifications@github.com> escreveu:  
 
 



Hi. In my case, i removed the "get_ip" package, and the black screen is gone, the app is back up and running.


how i can do this?
