### ISSUE TITLE
image_picker loses exif data when resizing the picture in iOS  (version 0.6.0+17)

### ISSUE THREAD

**Issue by mahdi-ninja** [flutter/flutter#37151]
When the maxHeight or maxWidth parameters are passed to ImagePicker.pickImage, it resizes the captured image BUT on **iOS** it **loses exif data**.

I tested the latest version of the image_picker (v **0.6.0+17**) and seems like this issue only exists in iOS. On Android it is working as expected.

It's really easy to reproduce this bug. Here's my minimal test code which is the official example plus "maxWidth" parameter.

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          var image = await ImagePicker.pickImage(
            source: ImageSource.gallery,
            maxWidth: 1024,
          );
          setState(() {
            _image = image;
          });
        },
        tooltip: 'Pick Image',
        child: Icon(Icons.photo),
      ),
    );
  }
}
```

**Comment by Daniel-BD** [comment]
I just realized this as well. Since rotation info can be in the EXIF data, this means that in some cases the photo will be imported in the correct orientation if `maxHeight` and `maxWidth` isn't used, but will be imported in an incorrect orientation if `maxHeight` or `maxWidth` is used. So this is pretty important I'd say.

**Comment by TrustTheBoy** [comment]
Same

**Comment by Damandroid** [comment]
Struggling with the same issue since I started plying with max height and/or maxwidth.

**Comment by mahdi-ninja** [comment]
This has been fixed in 0.6.1+3 https://github.com/flutter/plugins/commit/2daeaf22cc5b2938762b9ced228e9fa737629ae3

**Comment by thearaks** [comment]
@mahdi-ninja I'm still having this problem with 0.6.7+14 on iPhones with the latest iOS installed, is it possible?
Here is a picture that gets consistently rotated wrongly when scaled (maxWidth is set to 1280):
[Sample image](https://drive.google.com/file/d/1ID7uAMGoqfAlExZnypN8qToPDPZPVPYE/view?usp=sharing)

Should we reopen this issue?
