### ISSUE TITLE
Copy/paste toolbar needs smarter positioning

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#3945]
The copy/paste toolbar is always positioned above the selection. We should position it below the selection if it is too close to the top of the screen.

**Comment by Hixie** [comment]
There's logic in the tooltip code to do something similar, might be able to factor it out into a reusable component.

**Comment by xster** [comment]
From #20692 remember to avoid placing the toolbar above the selected text itself when avoiding the edge. 

From #25632 remember to avoid placing the toolbar into the safe area when avoiding the edge.

**Comment by parsodyl** [comment]
Any update on this?

**Comment by justinmc** [comment]
@parsodyl I hope to work on this soon.  There is a major bug with this where the selection menu is overlapping the cutout, which was pointed out in the duplicate issue above.

![selection menu cutout overlap](https://user-images.githubusercontent.com/15890184/55343647-1ac37200-54de-11e9-8640-f364e9ae9216.png)

**Comment by MichaelPriebe** [comment]
Hope someone could figure out a way to summon the native menu. Flutter applications are very obvious on androids with skins.

**Comment by justinmc** [comment]
That probably won't be doable since Flutter does all of its own text rendering.  It's true that there are too many inconsistencies with the native menu right now though.  I think we can make a few tweaks and get it to match the default menu perfectly, but I'm not sure about skins.  Maybe long term we can detect and show a reproduction of the common skinned menus as well?

**Comment by parsodyl** [comment]
@justinmc thanks for your reply.
Having a text field inside the app bar is a common pattern and sometimes the copy/paste bar is not only "ugly", but also unusable. If the text field widget could have something like a flag (in order to draw the copy/past bar under the widget), that would be a really nice solution in many cases.

**Comment by Hixie** [comment]
We intentionally do not attempt to match skins.

**Comment by justinmc** [comment]
Thanks for the clarification 👍

**Comment by loongliu** [comment]
This problem (selection menu is overlapping the cutout) is a main block for releasing our application. So we have to speed some time to fix it. Is this problem pull request welcome? @justinmc

**Comment by loongliu** [comment]
Generally there are two solutions.
1. change the position smarter. Put some safe space at top of screen, when TextField intersects with safe space, position toolbar below the TextField.
2. Add a property such as overlayPosition to TextField, let developer to decide proper position. When desired position is not safe, use the offsite position.

Android and iOS choose 1st solution. Tooltip widget chooses 2nd solution.
I prefer 2nd solution, which bring more freedom when TextField is in the middle.

**Comment by justinmc** [comment]
@loongliu You'd make a lot of people happy if you submitted a pull request for this!  It's definitely welcome.

I agree that we should try to make this solution follow what Tooltip does.  We should try to reuse as much code as possible between the two.  Take a look at [_TooltipPositionDelegate](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tooltip.dart#L211) and how it uses [positionDependentBox](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/geometry.dart#L41).  `positionDependentBox` seems like something we should reuse for this.  Maybe even create a common widget shared with Tooltip that uses it?

**Comment by justinmc** [comment]
Looks like there is already an outstanding PR that should solve this: https://github.com/flutter/flutter/pull/29809

@loongliu I'm interested in your feedback on that PR if it solves your problem!

**Comment by justinmc** [comment]
This is now fixed with https://github.com/flutter/flutter/pull/29809.

To get the changes, you'll need a Flutter version greater than 1.5.8, or for now you can use the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#master).

**Comment by jlund24** [comment]
I'm a little confused. Should the copy/paste menu now not be displaying under the appbar (or other obstructions) after the PR mentioned above? Because it's still happening for me. Sorry if I'm misunderstanding the fix.
![Screen Shot 2019-06-27 at 3 24 59 PM](https://user-images.githubusercontent.com/22064842/60301939-c74f9d00-98ef-11e9-9d90-d40e05507ce9.png)

**Comment by justinmc** [comment]
@jlund24 In your case the menu should appear on top of the appbar, and this issue's fix shouldn't affect you.  Is anything complicated happening in your main view that could affect the stacking order?  Here is what I see on master:

<img width="200" src="https://user-images.githubusercontent.com/389558/60302201-1abded00-98e8-11e9-90de-80a7546aeff8.png" />

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              TextField(
                autofocus: true,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by jlund24** [comment]
@justinmc possibly, the textfields are in a Reorderable listview. The copy/paste menu also seems to cause an error talking about paint order which I'm guessing is related. Would the list view be forcing some strange stacking behavior?

**Comment by jlund24** [comment]
I can create a separate issue with an example if that would be more appropriate since it sounds like my issue is different than the one this thread is concerned with

**Comment by justinmc** [comment]
That could be it... Yes please open a new issue.  If you can, try to pare down the problem into a minimal app and include it in the issue.

**Comment by jlund24** [comment]
Created a new issue that can be found here: [https://github.com/flutter/flutter/issues/35227#issue-461785818](https://github.com/flutter/flutter/issues/35227#issue-461785818)
