### ISSUE TITLE
TextFormField doesn't show trailing spaces when text is aligned to the right

### ISSUE THREAD

**Issue by cachapa** [flutter/flutter#40088]
## Steps to Reproduce

1. Create a TextFormField with text alignment set to `end`:
``` dart
TextFormField(
    textAlign: TextAlign.end,
),
```
2. Type some text and add trailing spaces
3. The spaces at the end of the text do not move the text or carret.

This seems to be related to #21679 but I tested on the master branch and the problem still exists.

## Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.1-pre.41, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.38.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Issue still exist

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextFormField(
            textAlign: TextAlign.end,
          ),
        ),
      ),
    );
  }
}

```

### flutter doctor -v
```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 14f3a36aba (3 days ago), 2020-04-03 17:06:01 -0700
    • Engine revision 09bc1fc45e
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 e736495eb7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

**Comment by tapizquent** [comment]
Has this been looked at? By the tag `found in release 1.18` means that it has been fixed?

It's really annoying that this is not in stable channel

**Comment by cachapa** [comment]
Just tested on the `master` channel and the issue is still there.

[✓] Flutter (Channel master, 1.18.0-9.0.pre.122, on Linux, locale en_US.UTF-8)

**Comment by Jjagg** [comment]
Looks like a duplicate of #40648.

**Comment by TahaTesser** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/40648
