### ISSUE TITLE
When I specify localizations, cursor of TextField is not aligned properly.

### ISSUE THREAD

**Issue by yohom** [flutter/flutter#40118]
@GaryQian 
## Steps to Reproduce

1. Add `flutter_localizations` dependency in pubspec.yaml.
2. Specify localization in `MaterialApp`.
3. Put a `TextField` in screen with some hint text.
4. Tap the `TextField`, the cursor is not aligned properly.

**Sample Code**:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [const Locale('zh', 'CH'), const Locale('en', 'US')],
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: EdgeInsets.all(32),
        child: Center(
          child: TextField(
            decoration: InputDecoration(hintText: '测试提示'),
          ),
        ),
      ),
    );
  }
}
```
<img width="346" alt="Screen Shot 2019-09-10 at 10 42 22" src="https://user-images.githubusercontent.com/10418364/64580099-b58e7980-d3b7-11e9-8f08-3833f7fcb631.png">

`flutter doctor -v`
```
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale en-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/yohom/Library/Flutter/flutter
    • Framework revision 2d2a1ffec9 (3 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yohom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/yohom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.0.beta.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1
```

**Comment by RemmoYu** [comment]
Have the same issue, mark...

**Comment by GaryQian** [comment]
So the cause is that without any actual text, the field is rendering the caret with the default height, which is of an alphabetic ` ` space character. However, the hint text is showing Chinese, which is taller than the alphabetic space. What we could do here is try to base the caret initially off of the hint text (if any) instead of blindly choosing an alphabetic space.

**Comment by githubhai** [comment]
试试 TextField > style > textBaseline: TextBaseline.alphabetic

**Comment by StarOfLife** [comment]
> 
> 
> 试试 TextField > style > textBaseline: TextBaseline.alphabetic

这个方法可以

**Comment by RemmoYu** [comment]
> 试试 TextField > style > textBaseline: TextBaseline.alphabetic

It seems doesn't work for me.

Target: Android
Version:  Channel stable, v1.9.1+hotfix.2

**Comment by GaryQian** [comment]
So I have looked into this, and it is actually not trivial to just use the hint text as the initial height. Since the TextInputDecoration is not actually passed into the RenderEditable, we do not have direct access to the contents of the hint or label. To do so, we would have to pass the decoration info into the RenderEditable as well, which would go against the way we currently have the decoration rendering and textfield rendering separately. I'll see if I can come up with a compromise to obtain the text information.

**Comment by caoyunxiao** [comment]
Have the same issue

**Comment by dmskys** [comment]
Have the same issue

**Comment by Moosphan** [comment]
Have the same issue too.

**Comment by Jasper-zzq** [comment]
StarOfLife 可行

**Comment by Jasper-zzq** [comment]
@githubhai thanks

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/44029 Should fix this.

**Comment by caoyunxiao** [comment]
I have added TextBaseline. Alphabetic, which cannot completely solve the problem, but will still happen occasionally. Android devices have a high probability

Flutter (Channel v1.9.1-hotfixes, v1.9.1+hotfix.6-pre.1

**Comment by jp1017** [comment]
1.12.13， hotfix6 still has this issue, and TextField > style > textBaseline: TextBaseline.alphabetic can't solve this still. @GaryQian @StarOfLife

**Comment by GaryQian** [comment]
Do you mind posting a screenshot/code of what you are seeing now? The baseline change should have fixed it for many cases, I'd like to know exactly what cases this repros on now.

**Comment by jp1017** [comment]
> Do you mind posting a screenshot/code of what you are seeing now?

I add this code in decoration: 
` contentPadding: const EdgeInsets.symmetric(vertical: 0.0),`

makes it again.

**Comment by mainxml** [comment]
@GaryQian 

![1](https://user-images.githubusercontent.com/25843019/70887208-42c91600-2018-11ea-8b33-be0cf49d9375.png)
![2](https://user-images.githubusercontent.com/25843019/70887215-49578d80-2018-11ea-9be6-97115764e93a.png)

```
D:\Program\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\Program\flutter
    • Framework revision 27321ebbad (5 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by iapicca** [comment]
Hi @yohom 
are you still experiencing the this issue?
https://github.com/flutter/flutter/issues/43482#issuecomment-565149624
thank you

**Comment by yohom** [comment]
I tested in version 1.14.6, it is fixed.

**Comment by Curtis-ly** [comment]
CupertinoTextField has the same problem

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
