### ISSUE TITLE
ERROR: The GPU does not support this version of OpenGL ES, try an older version

### ISSUE THREAD

**Issue by ahmednafea** [flutter/flutter#40150]
when i update flutter to 1.9.1 this error is raised in the run window in android studio
it says : ERROR: The GPU does not support this version of OpenGL ES, try an older version

**Comment by BondarenkoStas** [comment]
@ahmednafea Please provide your ```flutter doctor -v``` output.

**Comment by ahmednafea** [comment]
now i had downloaded the master version instead of stable
in stable version which i faced the problem , flutter doctor was good no need to fix any issue the problem not in the installation but i running the my app and it gave me only black screen and this error which i explained.

**Comment by BondarenkoStas** [comment]
@ahmednafea doctor output is mostly used here to see which exactly version of the framework you use while encountering an issue, to see environment etc:)
Do you face it only on the specific app? Can you come up with some minimal reproducible code example?

**Comment by ahmednafea** [comment]
![image](https://user-images.githubusercontent.com/32443261/64621799-99ee9780-d3e6-11e9-804c-0b7ecd682a3a.png)
![image](https://user-images.githubusercontent.com/32443261/64621883-bc80b080-d3e6-11e9-83d1-c51cfa273f4a.png)
that's the error and doctor screenshots

**Comment by madara134** [comment]
me too

**Comment by blokberg** [comment]
i downgrade flutter version "v1.7.8+hotfix.4" and error is gone.
i think this is the solution for now.

**Comment by ppicas** [comment]
This looks like a duplicated of https://github.com/flutter/flutter/issues/36130.

**Comment by BondarenkoStas** [comment]
@ppicas Thank you, you are right!
@ahmednafea Thank you for reporting! Please, follow the updates on that issue.
Closing it. If you disagree, feel free to comment and I will reopen it.

**Comment by ahmednafea** [comment]
the bug is still alive, i downgraded the version to 1.7.8 hotfix 4 but i want to upgrade to the new version, i'm waiting for a new hotfix of this version.

**Comment by BondarenkoStas** [comment]
Unfortunately, #471c805 (which includes fixes from skia side) is not in v1.9.1+hotfix.2. 
It's unlikely that there will be a hotfix for this issue (which may itself take several weeks). Fortunately, the next beta is just a few weeks away and that should include the fix.

**Comment by HassanDev13** [comment]
the same problem! :(

**Comment by HassanDev13** [comment]
> Unfortunately, [471c805](https://github.com/flutter/flutter/commit/471c8058291327e6832b36e0fe0992211a0397af) (which includes fixes from skia side) is not in v1.9.1+hotfix.2.
> It's unlikely that there will be a hotfix for this issue (which may itself take several weeks). Fortunately, the next beta is just a few weeks away and that should include the fix.

any fix for this problem?

**Comment by Yasirihsan55** [comment]
any fix regarding this issue :/

**Comment by escamoteur** [comment]
This should be fixed now on the beta and master channel.

**Comment by BondarenkoStas** [comment]
#471c805 went to v1.10.0 which is Dev since September 6, so not on the Beta yet.

**Comment by MuhammamdArslanKhan** [comment]
Still facing same issue Flutter 1.9.1+hotfix.4

**Comment by escamoteur** [comment]
Yes, currently you have to use dev or master channel.

**Comment by MuhammamdArslanKhan** [comment]
@escamoteur  Flutter 1.9.1+hotfix.4 master channel is also not working, the same issue

**Comment by BondarenkoStas** [comment]
@MuhammamdArslanKhan 1.9.1+hotfix.4 is the stable, but the fix landed on v1.10.0, which is not in stable or beta yet. to use dev for example you should `flutter channel dev` and `flutter upgrade`.

**Comment by lorenzoporto** [comment]
In emulator I'm not getting this error though in my physical device still having this issue.

**Comment by escamoteur** [comment]
@lorenzoporto Emulators fully support OpenGL. Have you done as we proposed above and switched to master?

**Comment by lorenzoporto** [comment]
@escamoteur  in current channel dev really fixed it!

**Comment by MuhammamdArslanKhan** [comment]
V1.7.8+hotfix.4 having the same issue with Adreno 308.  Any good advice, please..

**Comment by escamoteur** [comment]
Hi, if you look above, the only solution at the moment is to switch to the dev or master channel.

**Comment by MuhammamdArslanKhan** [comment]
Basically when I used "flutter channel" to see the channels. it start upgrading automatically to lates version. we should not use "flutter channel" to remain in required channels just use flutter version v1.7.8+hotfix.4

**Comment by tedhenry100** [comment]
I have Flutter version v1.9.1+hotfix.6 and am still seeing this problem!

**Comment by ahmednafea** [comment]
@tedhenry100  work with 1.10 it's working well with me

**Comment by escamoteur** [comment]
@tedhenry100 Please upgrade to the latest stable release.
