### ISSUE TITLE
[google_maps_flutter] Empty map when resuming from background on Android

### ISSUE THREAD

**Issue by jbxbergdev** [flutter/flutter#40284]
Tested with google_maps_flutter 0.5.21-0.5.21+11 on Emulator and Pixel 3a, Android 10.

**Steps to reproduce:**
- Open app with GoogleMap -> displays ok
- Put app into background, without it being killed by the system.
- Resume the app after a while

**Behaviour:**
* The map content (base map and custom polygon overlay) is visible for a brief moment, then disappears. 
* The Google logo stays visible. 
* The map appears to still be there, but be drawn completely translucently. Widgets behind it become visible. Gesture/movement/tap listeners still react to inputs.
* The map can be made reappear by 'wildly' applying zoom-in gestures.
* No specific log outputs. 

Note that this is an intermittent problem. I couldn't find a pattern yet as to how long the app needs to be in the background or how much load the device needs to be under (I _think_ it is more likely to happen if the app stays in the background for a longer time, however I had it happen when leaving the app for only a couple of seconds).

<img src="https://user-images.githubusercontent.com/12424161/70328180-bb6dec80-1838-11ea-9dd2-1d10cc66aed9.png" height="450" />

**Comment by jbxbergdev** [comment]
@BondarenkoStas you marked this issue as device-specific, but it really isn't. It happens on various devices. I was just stating the hardware I was testing on.

**Comment by jbxbergdev** [comment]
The problem also happens in the following scenario:

- The MapView is contained in an IndexedStack along with some other views.
- Another widget within the IndexedStack comes into the foreroiund (but the MapView stays initialized)
- MapView comes into foreground again.

When the MapView comes into foreground, sometimes the behavior is as described in the initial post.

It would be really great if somebody could look into this issue.

**Comment by jbxbergdev** [comment]
Here is a log output from this issue happening. I'm also using firebase_auth  in my app. Seems like the libraries somehow talk to each other and something goes wrong: 
`2019-12-06 12:51:42.898 22883-22946/de.bolz.dachzeltfestival W/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@d807a44
2019-12-06 12:51:42.905 22883-22911/de.bolz.dachzeltfestival W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
2019-12-06 12:51:42.907 22883-22911/de.bolz.dachzeltfestival I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
2019-12-06 12:51:42.907 22883-22911/de.bolz.dachzeltfestival I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
2019-12-06 12:51:43.758 22883-22903/de.bolz.dachzeltfestival D/FirebaseAuth: Notifying id token listeners about user ( RzgiHyy37MaYtBpb5OG0XBGBfPW2 ).
`

**Comment by jbxbergdev** [comment]
Could somebody please look into this? @BondarenkoStas

**Comment by jbxbergdev** [comment]
Here's a screenshot:
![Screenshot_20191206-145337](https://user-images.githubusercontent.com/12424161/70328120-98433d00-1838-11ea-87ad-0f2d2a9d4e06.png)

**Comment by jbxbergdev** [comment]
I was able to reproduce the problem also with using a GoogleMap as root widget and found that persistent zooming in 'reanimates' the map after a while. See also my Spost on StackOverflow on this issue: https://stackoverflow.com/questions/59374010/flutter-googlemap-is-blank-after-resuming-from-background

I would _really_ appreciate to get at least a word on whether this is being looked at.

**Comment by xapprika** [comment]
same issue here

**Comment by jbxbergdev** [comment]
Workaround here: https://stackoverflow.com/a/59435683/1257326

**Comment by TryLoveCatch** [comment]
same problem，after white screen，swith screen to landscape，platformView will display again 😂

**Comment by emnfelix** [comment]
I am having this problem as well. Has anybody been able to find a solution?

**Comment by abdulrehman4433** [comment]
the same problem, just one-time map work properly at the emulator and when I perform any design changes and again hot restart it will disappear and when I close the android studio and again start it and run the project map works properly. I don't know what is the main problem.

**Comment by Xgamefactory** [comment]
this should be fixed or team should provide a solutions for such case.

**Comment by Xgamefactory** [comment]
> Workaround here by modifying a fork: https://stackoverflow.com/a/59435683/1257326

thanks for this workound 
currently we are using this patch.

**Comment by rahulmanuwas** [comment]
@FlutterIssues team - have you published a patch for this yet?

**Comment by ccamba** [comment]
Same issue with Android 10 API 29

**Comment by nadav-fima** [comment]
Just experienced this on a OnePlus A5000 & Samsung Galaxy A51. Didn't see anything weird in the logs.

**Comment by rafaeltakahashi** [comment]
To me, the app outright crashes in the Android emulator after switching to another app and then switching back. Tested in Android 6 through 10.
```

E/Surface ( 5993): getSlotFromBufferLocked: unknown buffer: 0x200
D/EGL_emulation( 5993): eglMakeCurrent: 0xdd117540: ver 3 0 (tinfo 0xc67780e0)
E/flutter ( 5993): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(71)] Failed to setup Skia Gr context.
D/EGL_emulation( 5993): eglMakeCurrent: 0xe8659b80: ver 3 0 (tinfo 0xdd1c9610)
F/libc    ( 5993): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 6022 (1.raster), pid 5993 ([app id])
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-08-25 17:05:03-0300
pid: 5993, tid: 6022, name: 1.raster  >>> [app id] <<<
uid: 10144
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    eax 00000000  ebx c863ac78  ecx fffffff9  edx 00000000
    edi c69f5978  esi 00000004
    ebp c69f56f8  esp c69f56f8  eip c7f91b85
backtrace:
      #00 pc 0138cb85  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
      #01 pc 0138b55d  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
      #02 pc 0142dd20  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
      #03 pc 015ff502  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
      #04 pc 015ff3d9  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
      #05 pc 015ff8c3  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
      #06 pc 015ff6af  /data/app/[app id]-8G1wZH1E4TI7ZbVnqWpWTw==/lib/x86/libflutter.so (BuildId: 7c10268101450e4033959b201ce27d4c3845c232)
Lost connection to device.

```

On a real Android device (running Android 10), the map becomes blank without any errors in the log, as described by the other comments.

Output of flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

• No issues found!
```

Version of google_maps_flutter is 0.5.28+1.

**Comment by rahulmanuwas** [comment]
@FlutterIssues team please update the repository with a patch.

**Comment by Xgamefactory** [comment]
same issue happens on android 10 api 29 but only on release version of app 
with debug mode it works.

**Comment by MattyBoy4444** [comment]
It would be nice if this was fixed.  I started submitting a PR and then started wondering if there was a better way to do this fix.  Temporarily I added a didChangeAppLifecycleState to my Widget and force the GoogleMap to redraw with a state change.

**Comment by Yaffar** [comment]
I have the same issue, will this be adressed soon or do we have to always use the workaround? :C

**Comment by ahmadkhedr** [comment]
Same issue here..this issue should be fixed as soon as possible

**Comment by tarektaamali** [comment]
I have the same issue with  version Flutter 1.22.2 stable and the last version of the package 1.0.3 of flutter google maps

**Comment by tarektaamali** [comment]
This issue has opened more than a year ago .why didn't find an effective solution till now ?

**Comment by math1man** [comment]
I wonder if the problem is related to state restoration. The Google maps code restores state via `mapView.onCreate(savedInstanceState)`. With the v2 plugin, this method is called twice: once in the implementation of `DefaultLifecycleObserver#onCreate` using a null bundle, and again in the implementation of Flutter's `OnSaveInstanceStateListener#onRestoreInstanceState` using a valid bundle. I wonder if these are occurring in an unexpected order and therefore causing state to restore incorrectly.

**Comment by 2IIZ** [comment]
Same issue here with Samsung Galaxy S9+ (Switching apps, rotation and Stack() Widget)

**Comment by Navil** [comment]
Same Problem here, but only for some of my users. Any updates on this ?

**Comment by Hitsu91** [comment]
Same here, any news?

**Comment by hfranco346** [comment]
Same problem!! give us a solution please, this issue has more than one year open and the problem persist

**Comment by manostheo** [comment]
This bug occurs in official flutter map examples too.  To replicate just try switching apps to force change in lifecycle state. This is really a critical bug and needs to be fixed as soon as possible.

**Comment by rajd90** [comment]
google_maps_flutter: ^1.0.6
flutter: 1.22.5

I'm having the same problem. I've tried to solution using didChangeAppLifecycleState but it didn't seem to make any difference. Is there an update on when this might get resolved?

**Comment by nguyenleanhkhoa** [comment]
im having the same problem , any ideas for this isue ?? TT_TT

**Comment by HasikaDilshani** [comment]
Having same issue..any solutions?

**Comment by vanlooverenkoen** [comment]
This is the workaround we are using right now.

```

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _initMapStyle();
    }
  }

  Future<void> _initMapStyle() async {
    _mapStyle ??= await rootBundle.loadString(ThemeAssets.mapsStyle);
    await _controller?.setMapStyle(_mapStyle);
  }
```

**Comment by HasikaDilshani** [comment]
Thank you very much

**Comment by Pman143** [comment]
Hey @HasikaDilshani @vanlooverenkoen did you extend or implement any class?
It doesn't seem to be working for me, i extended WidgetsBindingObserver,.
It's not even running the didChangeAppLifecycleState method as far as i can tell.

**Comment by vanlooverenkoen** [comment]
This is how you sould use the WidgetBinderObserver
```
class MapsState extends State<Maps> with WidgetsBindingObserver 
```
```
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }
```

```
  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
```

**Comment by jbxbergdev** [comment]
Hi, it's been almost 1.5 years since I reported the bug. @BondarenkoStas @TahaTesser is this issue being worked on? Thanks.

**Comment by AlexoDz** [comment]
same issue

**Comment by iapicca** [comment]
@jbxbergdev @AlexoDz 
did you try the workarounds suggested [here](https://stackoverflow.com/questions/59374010/flutter-googlemap-is-blank-after-resuming-from-background)?

**Comment by jbxbergdev** [comment]
@iapicca yes, I actually posted the question.

**Comment by widarlein** [comment]
I'm running into this issue as well (duh). Would be great if fixed!

**Comment by AlexoDz** [comment]
Yeah! It works fine

**Comment by darshankawar** [comment]
@jbxbergdev Please check @maheshmnj's findings above. Can you check and confirm at your end if this is still replicable using latest plugin version ?

**Comment by jbxbergdev** [comment]
@darshankawar unfortunately, I'm currently not working on the app that had this problem. However, I advise that this is/was an intermittent problem which may require several attempts/possibly longer time in the background to reproduce. Other users replying to this have had the same behavior. Maybe someone else can check?

**Comment by yacineblr** [comment]
> This is the workaround we are using right now.
> 
> ```
> 
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     if (state == AppLifecycleState.resumed) {
>       _initMapStyle();
>     }
>   }
> 
>   Future<void> _initMapStyle() async {
>     _mapStyle ??= await rootBundle.loadString(ThemeAssets.mapsStyle);
>     await _controller?.setMapStyle(_mapStyle);
>   }
> ```

Thanks you @vanlooverenkoen , i'ts work !!!!!! ❤️

**Comment by maheshmnj** [comment]
We tried to replicate this issue by keeping the app in background for ~20 mins and tried few times, but couldn't replicate it. We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by vanlooverenkoen** [comment]
It will never happen if you keep your app open. The issue appears when going to the background and back to the app a couple of times. Look at my example that is how we can fix it in dart. But we actually should override the lifecycle in android

**Comment by maheshmnj** [comment]
Reopening it based on above comment but cannot replicate. Keeping it open for further investigation from team.

**Comment by TahaTesser** [comment]
Hi everyone
First of all, thanks @vanlooverenkoen for commenting on the issue

I can reproduce the issue on the Android device after running the for almost 6 hours.

### Steps to reproduce  
1. Running a minimal code sample  for `flutter_google_maps` in release mode  and push the app  to the background.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}
``` 

</details>

2. Open Play store, Youtube, Weather or any random apps, around 8-10 of the would be good enough and open and these apps to the background as well.
3. Keep the device busy with long Youtube videos running (played white noise videos in my testing) or playing games.
4/ Switch between maps app and other apps few times

After couple of hours, maps started to loading slowly whenever I switch, then after a few more switches, maps apps comes blank.

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/122415853-ed652080-cf90-11eb-9329-2ab686de43a5.gif" height="450" />	|





<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233
[✓] VS Code (version 1.57.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0
[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1055]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.48
! Doctor found issues in 1 category.
```

</details>

**Comment by vanlooverenkoen** [comment]
Damn that is dedication 🎉 

In our tests we had it after switching between apps in a timespan of 30 min. After that the map was always blank. As I already said. the fix in dart worked for us. But should be fixed by handling the android lifecycle

**Comment by ccamba** [comment]
Hi @vanlooverenkoen , which is the import of ThemeAssets.mapsStyle ?

**Comment by vanlooverenkoen** [comment]
That is just a string `assets/map_style/dark.json` But that could be any mapstyle.

**Comment by ajosecueto** [comment]
bug persists in some devices... but fixed used the workaround posted up.

also using  controller.setMapStyle("[]"); in my case.... because map doesnt have any style...

**Comment by zyruva** [comment]
I can confirm that this bug still exists with the latest version of the google maps flutter package on my emulator (Android 7) and on my actual phone running Android 10.
When the app is being used, everything runs smoothly, but as soon as i switch to another app and go back to my app, the Google Maps widget turns blank.

**Comment by Navil** [comment]
I can approve, that this issue still exists even with the newest google maps version.

**Comment by chloe722** [comment]
Same. Tested with Samsung S20 Android 11 the issue still exists.

**Comment by bryanjorgeflores** [comment]
Is there any solution? I can't post my app while this Big persist 😞

**Comment by ajosecueto** [comment]
> Is there any solution? I can't post my app while this Big persist 😞

You can use the workaround posted in this thread.... You can post your app.

**Comment by rativitea** [comment]
> Workaround here by modifying a fork: https://stackoverflow.com/a/59435683/1257326

Hi, I tried using the workaround. 

![Capture2](https://user-images.githubusercontent.com/87474563/126061244-8036a588-a1b3-44e2-9d66-a6f5c6599167.PNG)

Edited the fork and imported it into my project but I got this error. 

![Capture](https://user-images.githubusercontent.com/87474563/126061220-f5266f35-e69a-4748-827a-a38b44552d26.PNG)


My pubscpec.yaml: 
![pubspec yaml](https://user-images.githubusercontent.com/87474563/126061262-6a333a3a-a952-4eb2-8af1-99bc2ea65cd4.PNG)

Wondering if it's just me lol

**Comment by ActuallyGSM** [comment]
Hey, I tried something & it seems to be working!

Step 01,
Implement **WidgetsBindingObserver** for related class's State class as follows,
i.e: `class MainScreenState extends State<MainScreen> with WidgetsBindingObserver {....`

Step 02,
Override **didChangeAppLifecycleState** method
i.e:   
```
@override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    switch (state) {
      case AppLifecycleState.inactive:
        print('appLifeCycleState inactive');
        break;
      case AppLifecycleState.resumed:
        print('appLifeCycleState resumed');
        break;
      case AppLifecycleState.paused:
        print('appLifeCycleState paused');
        break;
      case AppLifecycleState.detached:
        print('appLifeCycleState detached');
        break;
    }
  }
```

Step 03
add this for init state
`WidgetsBinding.instance!.addObserver(this);`

Step 04
Step 4 should be as follows

```
//onMapCreated method
  void onMapCreated(GoogleMapController controller) {
    controller.setMapStyle(Utils.mapStyles);
    _controller.complete(controller);
  }
```

```
// lifecycle
  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    switch (state) {
      case AppLifecycleState.inactive:
        print('appLifeCycleState inactive');
        break;
      case AppLifecycleState.resumed:
        final GoogleMapController controller = await _controller.future;
        onMapCreated(controller);
        print('appLifeCycleState resumed');
        break;
      case AppLifecycleState.paused:
        print('appLifeCycleState paused');
        break;
      case AppLifecycleState.detached:
        print('appLifeCycleState detached');
        break;
    }
  }
```

**Comment by LuisAngelCG** [comment]
> seems to be working!
> 
> Step 01,
> Implement **WidgetsBindingObserver** for related class's State class as follows,
> i.e: `class MainScreenState extends State<MainScreen> with WidgetsBindingObserver {....`
> 
> Step 02,
> Override **didChangeAppLifecycleState** method
> i.e:
> 
> ```
> @override
>   Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
>     super.didChangeAppLifecycleState(state);
>     switch (state) {
>       case AppLifecycleState.inactive:
>         print('appLifeCycleState inactive');
>         break;
>       case AppLifecycleState.resumed:
>         print('appLifeCycleState resumed');
>         break;
>       case AppLifecycleState.paused:
>         print('appLifeCycleState paused');
>         break;
>       case AppLifecycleState.detached:
>         print('appLifeCycleState detached');
>         break;
>     }
>   }
> ```
> 
> Step 03
> add this for init state
> `WidgetsBinding.instance!.addObserver(this);`
> 
> Step 04
> Step 4 should be as follows
> 
> ```
> //onMapCreated method
>   void onMapCreated(GoogleMapController controller) {
>     controller.setMapStyle(Utils.mapStyles);
>     _controller.complete(controller);
>   }
> ```
> 
> ```
> // lifecycle
>   @override
>   Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
>     super.didChangeAppLifecycleState(state);
>     switch (state) {
>       case AppLifecycleState.inactive:
>         print('appLifeCycleState inactive');
>         break;
>       case AppLifecycleState.resumed:
>         final GoogleMapController controller = await _controller.future;
>         onMapCreated(controller);
>         print('appLifeCycleState resumed');
>         break;
>       case AppLifecycleState.paused:
>         print('appLifeCycleState paused');
>         break;
>       case AppLifecycleState.detached:
>         print('appLifeCycleState detached');
>         break;
>     }
>   }
> ```

following your solution I get
"The getter 'future' isn't defined for the type 'GoogleMapController'.
Try importing the library that defines 'future', correcting the name to the name of an existing getter, or defining a getter or field named 'future'."
could indicate what type is '_controller' or how to solve this, if I have errors in the language it is because I am not learning: c

**Comment by lhhuu** [comment]
code nhu lin, chay deo dau

**Comment by wazini-john** [comment]
Has anyone implemented [`this`](https://github.com/flutter/flutter/issues/40284#issuecomment-883899432) using `flutter_hooks` ?

**Comment by VladanRandjelovic** [comment]
> Hey, I tried something & it seems to be working!
> 
> Step 01,
> Implement **WidgetsBindingObserver** for related class's State class as follows,
> i.e: `class MainScreenState extends State<MainScreen> with WidgetsBindingObserver {....`
> 
> Step 02,
> Override **didChangeAppLifecycleState** method
> i.e:
> 
> ```
> @override
>   Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
>     super.didChangeAppLifecycleState(state);
>     switch (state) {
>       case AppLifecycleState.inactive:
>         print('appLifeCycleState inactive');
>         break;
>       case AppLifecycleState.resumed:
>         print('appLifeCycleState resumed');
>         break;
>       case AppLifecycleState.paused:
>         print('appLifeCycleState paused');
>         break;
>       case AppLifecycleState.detached:
>         print('appLifeCycleState detached');
>         break;
>     }
>   }
> ```
> 
> Step 03
> add this for init state
> `WidgetsBinding.instance!.addObserver(this);`
> 
> Step 04
> Step 4 should be as follows
> 
> ```
> //onMapCreated method
>   void onMapCreated(GoogleMapController controller) {
>     controller.setMapStyle(Utils.mapStyles);
>     _controller.complete(controller);
>   }
> ```
> 
> ```
> // lifecycle
>   @override
>   Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
>     super.didChangeAppLifecycleState(state);
>     switch (state) {
>       case AppLifecycleState.inactive:
>         print('appLifeCycleState inactive');
>         break;
>       case AppLifecycleState.resumed:
>         final GoogleMapController controller = await _controller.future;
>         onMapCreated(controller);
>         print('appLifeCycleState resumed');
>         break;
>       case AppLifecycleState.paused:
>         print('appLifeCycleState paused');
>         break;
>       case AppLifecycleState.detached:
>         print('appLifeCycleState detached');
>         break;
>     }
>   }
> ```

after adding this to my code it throws bad state future already completed error when resuming the app, and for some reason my custom marker started to kind of "jump", can anybody help please?

**Comment by ActuallyGSM** [comment]
I updated the code.  Add the following code for the onMapCreated method. 
```
    if (!_controller.isCompleted) {
      _controller.complete(controller);
    }
```

**Comment by laban405** [comment]
> Hey, I tried something & it seems to be working!
> 
> Step 01, Implement **WidgetsBindingObserver** for related class's State class as follows, i.e: `class MainScreenState extends State<MainScreen> with WidgetsBindingObserver {....`
> 
> Step 02, Override **didChangeAppLifecycleState** method i.e:
> 
> ```
> @override
>   Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
>     super.didChangeAppLifecycleState(state);
>     switch (state) {
>       case AppLifecycleState.inactive:
>         print('appLifeCycleState inactive');
>         break;
>       case AppLifecycleState.resumed:
>         print('appLifeCycleState resumed');
>         break;
>       case AppLifecycleState.paused:
>         print('appLifeCycleState paused');
>         break;
>       case AppLifecycleState.detached:
>         print('appLifeCycleState detached');
>         break;
>     }
>   }
> ```
> 
> Step 03 add this for init state `WidgetsBinding.instance!.addObserver(this);`
> 
> Step 04 Step 4 should be as follows
> 
> ```
> //onMapCreated method
>   void onMapCreated(GoogleMapController controller) {
>     controller.setMapStyle(Utils.mapStyles);
>    if (!_controller.isCompleted) {
>       _controller.complete(controller);
>     }
>   }
> ```
> 
> ```
> // lifecycle
>   @override
>   Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
>     super.didChangeAppLifecycleState(state);
>     switch (state) {
>       case AppLifecycleState.inactive:
>         print('appLifeCycleState inactive');
>         break;
>       case AppLifecycleState.resumed:
>         final GoogleMapController controller = await _controller.future;
>         onMapCreated(controller);
>         print('appLifeCycleState resumed');
>         break;
>       case AppLifecycleState.paused:
>         print('appLifeCycleState paused');
>         break;
>       case AppLifecycleState.detached:
>         print('appLifeCycleState detached');
>         break;
>     }
>   }
> ```

working well. i recomment it

**Comment by kamami** [comment]
I also can approve, that this issue still exists with the newest google maps version.

**Comment by marianhlavac** [comment]
It's unbelievable, that this issue is opened since 9/2019, has multiple confirmations of reproducing on many devices with minimal example, there are three different workarounds for this, and yet at the end of 2021 there is still no sign of progress or attention to this major issue, which will happen to almost 100% of the Android users, because each of them will eventually pause and resume the app.

Issue seen on Redmi 7, Android 10 QKQ1, on latest version 2.1.1.
It isn't always reproducible, sometimes when the app is rebuilt it doesn't happen, but that's rare.

**Comment by jbxbergdev** [comment]
@marianhlavac As far as I understand, google_maps_flutter is, at least for the most part, not developed by the Google Maps team, but by the community. I might be wrong on this, but it might explain the slow (or in this case nonexistent) progress.

How serious Google is about driving Flutter adoption, while unwilling to dedicate sufficient resources to such an important plugin like Google Maps, is another story.

**Comment by Daeon97** [comment]
This worked for me though

```
@override
    void didChangeAppLifecycleState(AppLifecycleState state) {
        if (state == AppLifecycleState.resumed) {
            controller.setMapStyle("[]");
        }
    }
```
[https://stackoverflow.com/questions/59374010/flutter-googlemap-is-blank-after-resuming-from-background/59435683#59435683](url)

**Comment by radheshyamsinghpretlist** [comment]
I am also getting white screen some time when app comes in foreground with map on screen. Other widget on same screen are working fine. It is only happening with devices with android 12. None of the above are helpful in my case.

**Comment by timbotimbo** [comment]
I've used the `setMapStyle` workaround reliably for about a year, but I'm getting a blank map again on Android 12 devices.
Anything prior to Android 12 still seems to be alright.
Might be a different bug that causes it but it result in the same blank screen on app resume.

**Comment by neoacevedo** [comment]
I can confirm it with a Samsung Galaxy A10s. 

When the app goes to background and it returns to foreground, the map doesn't load anymore. 

I also got the same in another Samsung Galaxy Note GTN5110 with LineageOS 10.4 (Nougat). Implementing the @Daeon97 code, worked in that tab, so I'm testing now in the Galaxy A10s.

**Comment by kldMohammed** [comment]
It still appears on the Poco phone with android 12.

And all work around above didn't work

**Comment by felix-synorex** [comment]
Thanks to workaround by [Tim-HNK](https://github.com/Tim-HNK) from https://github.com/flutter/flutter/issues/98865#issuecomment-1113204746.

This is a workaround for device that run Android 12 and above (I think this work on Android version below 12 as well). This workaround remove Google Map for the first frame after AppLifecycleState resume.

Here is the full source code:
```
class WidgetWithGoogleMap extends StatefulWidget {
  const WidgetWithGoogleMap({super.key});

  @override
  State<WidgetWithGoogleMap> createState() => _WidgetWithGoogleMapState();
}

class _WidgetWithGoogleMapState extends State<WidgetWithGoogleMap>
    with WidgetsBindingObserver {
  bool _includeMap = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _resetMap();
    }
  }

  void _resetMap() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        setState(() {
          _includeMap = true;
        });
      }
    });
    if (mounted) {
      setState(() {
        _includeMap = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return _includeMap
        ? const GoogleMap(
            mapType: MapType.normal,
            initialCameraPosition: CameraPosition(
              target: LatLng(37.42796133580664, -122.085749655962),
            ),
          )
        : const SizedBox.shrink();
  }
}
```

**Comment by wongcheehong** [comment]
Thanks to workaround by [Tim-HNK](https://github.com/Tim-HNK) from https://github.com/flutter/flutter/issues/98865#issuecomment-1113204746.

This is a workaround for device that run Android 12 and above (I think this work on Android version below 12 as well). This workaround remove Google Map for the first frame after AppLifecycleState resume.

Here is the full source code:
```
class WidgetWithGoogleMap extends StatefulWidget {
  const WidgetWithGoogleMap({super.key});

  @override
  State<WidgetWithGoogleMap> createState() => _WidgetWithGoogleMapState();
}

class _WidgetWithGoogleMapState extends State<WidgetWithGoogleMap>
    with WidgetsBindingObserver {
  bool _includeMap = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _resetMap();
    }
  }

  void _resetMap() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        setState(() {
          _includeMap = true;
        });
      }
    });
    if (mounted) {
      setState(() {
        _includeMap = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return _includeMap
        ? const GoogleMap(
            mapType: MapType.normal,
            initialCameraPosition: CameraPosition(
              target: LatLng(37.42796133580664, -122.085749655962),
            ),
          )
        : const SizedBox.shrink();
  }
}
```

**Comment by johnmccutchan** [comment]
I can't reproduce this issue at flutter head using version 2.5.3 of google_maps_flutter. Tested on a Pixel 7 Pro running Android 14.
