### ISSUE TITLE
Sliders won't move in short distances when competing with other drags

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#40310]
Recording: ![Screen Recording 2019-09-11 at 23 09 28 2019-09-11 23_12_13](https://user-images.githubusercontent.com/351125/64748798-c7703980-d4e9-11e9-90ed-6170f7792e90.gif)

## Steps to Reproduce

1. Get any Slider
2. Touch on the thumb
3. Move slightly to left or right (usually within the ripple area), it won't move.

I tried using the [sample code from Gallery app](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/slider_demo.dart) and it is fully reproducible. It seems, however, that the official Gallery app (which was last updated months ago) doesn't have this issue.

Edit: this is what cause the issue. kTouchSlop should be 0 for this scenario.
 https://github.com/flutter/flutter/blob/cd84ceaf5e3e8eee6a1e803938e176bdeb2efef0/packages/flutter/lib/src/gestures/monodrag.dart#L526

## Logs

```
➜ flutter doctor -v
[✓] Flutter (Channel dev, v1.10.1, on Mac OS X 10.14.6 18G95, locale en-BR)
    • Flutter version 1.10.1 at /usr/local/Cellar/flutter/dev
    • Framework revision ce45c2d3e6 (5 days ago), 2019-09-06 20:11:41 -0400
    • Engine revision b9ce2500d9
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bernardoferrari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/bernardoferrari/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/bernardoferrari/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio 3.5 Preview.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/bernardoferrari/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.5863777/Android
      Studio 3.6 Preview.app/Contents
    • Flutter plugin version 39.0.4
    • Dart plugin version 192.6527
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Users/bernardoferrari/Applications/JetBrains Toolbox/IntelliJ
      IDEA Ultimate.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SM G9600 • 23a1f4ee1a057ece • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Hixie** [comment]
If this used to work, we should first determine why it regressed, and then write a test for it.

Changing the slop shouldn't be necessary. The slop only matters when there's competing gesture detectors.

**Comment by bernaferrari** [comment]
> The slop only matters when there's competing gesture detectors.
I think this is precisely the issue.

In flutter_gallery, the range sliders are inside a Column. There is no scrolling factor, yet this triggers the issue. In my apps most of them are also in a Column.

Additionally, I'm also curious regarding the slop, even in ListView. I've never seen this in other platforms. Shouldn't it be optional?

**Comment by Hixie** [comment]
We need to bisect to find when it regressed. The best way to do that is to create a unit test that exactly reproduces the issue you're concerned with, verify that it worked in the past, and then use `git bisect` to automatically determine what commit broke it.

**Comment by Hixie** [comment]
> Additionally, I'm also curious regarding the slop, even in ListView. I've never seen this in other platforms. Shouldn't it be optional?

When it's working correctly, the touch slop is the distance you have to go for us to distinguish a horizontal drag from a vertical drag when both are possible (and similar things between other kinds of gestures). Android has something similar from what i can tell by dragging sliders inside list views (e.g. the Audio Balance slider in the Accessibility settings on Q).

It should have no impact in the case being discussed here, where there's no other gesture competing.

**Comment by bernaferrari** [comment]
I tested here in Accessibility and you are right - a bit inconsistent, since in other places it doesn't follow this, but you are right. 
On native Android, they added support for the touch slop in the Material Components library this week!! https://github.com/material-components/material-components-android/commit/a7da96fac0f18684898131221c3fa628b38e7f3e

This is possibly the reason why you hardly ever see this in Android. And it is going to break a few apps in the coming months, or years, when this is eventually released. Therefore, we might see both usages for a long time.

According to @clocksmith  in the PR, it isn't a regression because the sample changed but the way it works has always been this way. I guess it makes it a feature request, then? But there is an additional issue:

On iOS (Settings -> Display & Brightness), the slider doesn't have the touch slop but doesn't jump when you slide your finger, only when you tap.
However, CupertinoSlider relies in `HorizontalDragGestureRecognizer` https://github.com/flutter/flutter/blob/fcaf9c4070bc726585a221279b3c94e37f49698d/packages/flutter/lib/src/cupertino/slider.dart#L338 which causes the same issue listed here with `touchSlop`. And, you can't tap on it to scroll.

So I guess we could make `HorizontalDragGestureRecognizer` accept a `touchSlop` (either boolean for default value or int which would make it more scalable) parameter and `CupertinoSlider` make use of it? And **maybe** make it optional on Material, not the default like iOS, but optional?

**Comment by clocksmith** [comment]
Correct this is not a regression. It started surfacing on the old flutter gallery once the demo was put into tabs, and there was competing gesture detection.

**Comment by pedromassangocode** [comment]
I was able to reproduce this on latest stable channel. Tested with the Gallery project!

![gif](https://user-images.githubusercontent.com/67424416/92723368-df7ad300-f360-11ea-8440-f308dd83e910.gif)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5556 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by fzyzcjy** [comment]
Hi this still appear in latest flutter (2021.1.1). Will it be solved? Thanks!

**Comment by SashaFarkas** [comment]
Any updates on this?

**Comment by clocksmith** [comment]
@bernaferrari suggested setting the touchSlop to 0 and making it configurable. I think that could work. @HansMuller does that seem like a good solution?

**Comment by nt4f04uNd** [comment]
Turns out the jump has gone with https://github.com/flutter/flutter/pull/82152

**Comment by bernaferrari** [comment]
How?

**Comment by nt4f04uNd** [comment]
onStart is now called only once per drag, so there's no jump after the slop. The slop is still there though

**Comment by bernaferrari** [comment]
Oh, so the issue is still valid..

**Comment by nt4f04uNd** [comment]
Yes

**Comment by maheshmnj** [comment]
Hello @bernaferrari, I tried running the [gallery app](https://github.com/flutter/gallery/tree/main) on the latest master channel, and it seems to drag the handle fine I believe this issue is fixed.

 
https://user-images.githubusercontent.com/31410839/211722431-a266eced-ae8a-4c50-ba02-79d53ad36d4d.mov


<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.7.0-15.0.pre.16, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-15.0.pre.16 on channel master at /Users/mahesh/Development/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/mahesh/Development/flutter/bin/flutter, which is not
      inside your current Flutter SDK checkout at /Users/mahesh/Development/flutter_master. Consider adding
      /Users/mahesh/Development/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/mahesh/Development/flutter/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/mahesh/Development/flutter_master. Consider adding
      /Users/mahesh/Development/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ddf42eae5 (4 days ago), 2023-01-06 17:44:44 -0500
    • Engine revision 33d7f8a1b3
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 10.0.0.252:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos           • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome          • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details> 


Closing as fixed, Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.

Thank you.

**Comment by bernaferrari** [comment]
They probably just removed the horizontal listview. The issue is still there, just the sample that changed.

**Comment by maheshmnj** [comment]
Thanks for the update  @bernaferrari, I tried the below code sample which wraps Slider in a Horizontal ListView-> GestureDetector, But the slider seems to slide just fine. Let me know if the code sample doesn't represent the actual issue.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _value = 0.0;
  @override
  Widget build(BuildContext context) {
    Widget _slider() => Slider(
          value: _value,
          onChanged: (double newValue) {
            setState(() {
              _value = newValue;
            });
          },
        );

    return Scaffold(
      appBar: AppBar(
        // toolbarHeight: 48,
        title: Text(widget.title),
      ),
      body: Center(
        child: Stack(
          children: [
            Row(
              children: [
                Expanded(
                  child: ListView(
                    scrollDirection: Axis.horizontal,
                    children: <Widget>[
                      GestureDetector(
                        child: _slider(),
                      ),
                    ],
                  ),
                ),
                Expanded(child: _slider())
              ],
            ),
            Align(
                alignment: Alignment.topCenter,
                child: Text(_value.toStringAsPrecision(2)))
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by bernaferrari** [comment]
It seems the logic now is touch only. Shouldn't happen with mouse. I think this is mostly fine.

![image](https://user-images.githubusercontent.com/351125/211968456-05d83716-c06d-4994-aaf0-66522d8017c8.png)
