### ISSUE TITLE
[web] White screen and error in console when running Flutter for Web app

### ISSUE THREAD

**Issue by klavergne** [flutter/flutter#40876]
## Steps to Reproduce

1. Migrate to Flutter master
2. Create new Flutter project using `flutter create`
3. Start app in Chrome using `flutter run -d chrome`
4. Open developer tools and view console

## Console Log
```
Uncaught (in promise) TypeError: Cannot read property 'hash' of undefined
    at HashLocationStrategy.get path [as path] (browser_location.dart:94)
    at _engine.BrowserHistory.new.get currentPath [as currentPath] (history.dart:56)
    at _engine.BrowserHistory.new.[_setupStrategy] (history.dart:164)
    at _engine.BrowserHistory.new.set locationStrategy [as locationStrategy] (history.dart:51)
    at _engine.EngineWindow.new.set locationStrategy [as locationStrategy] (window.dart:81)
    at webOnlyInitializePlatform (initialization.dart:12)
    at webOnlyInitializePlatform.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at Object.webOnlyInitializePlatform (initialization.dart:8)
    at main$ (main_web_entrypoint.dart:7)
    at main$.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at main$ (main_web_entrypoint.dart:5)
    at Function.call$0 (client.js:27433)
    at client.js:26055
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3110)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11704)
    at Object._asyncStartSync (client.js:3075)
    at main__closure3.$call$body$main__closure (client.js:26063)
    at main__closure3.call$1 (client.js:25993)
    at StaticClosure._rootRunUnary [as call$2$5] (client.js:3393)
    at _CustomZone.runUnary$2$2 (client.js:13083)
    at _CustomZone.runUnaryGuarded$1$2 (client.js:13011)
    at _ControllerSubscription._sendData$1 (client.js:12564)
    at _DelayedData.perform$1 (client.js:12771)
    at _StreamImplEvents.handleNext$1 (client.js:12845)
    at _PendingEvents_schedule_closure.call$0 (client.js:12817)
    at Object._microtaskLoop (client.js:3253)
    at StaticClosure._startMicrotaskLoop (client.js:3259)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:11580)
    at invokeClosure (client.js:1206)
    at MutationObserver.<anonymous> (client.js:1225)
    get path | @ | browser_location.dart:94 
  | get currentPath | @ | history.dart:56
  | [_setupStrategy] | @ | history.dart:164
  | set locationStrategy | @ | history.dart:51
  | set locationStrategy | @ | window.dart:81
  | webOnlyInitializePlatform | @ | initialization.dart:12
  | runBody | @ | async_patch.dart:84
  | _async | @ | async_patch.dart:123
  | webOnlyInitializePlatform | @ | initialization.dart:8
  | main$ | @ | main_web_entrypoint.dart:7
  | runBody | @ | async_patch.dart:84
  | _async | @ | async_patch.dart:123
  | main$ | @ | main_web_entrypoint.dart:5
  | Function.call$0 | @ | client.js:27433
  | (anonymous) | @ | client.js:26055
  | (anonymous) | @ | client.js:3110
  | call$2 | @ | client.js:11704
  | _asyncStartSync | @ | client.js:3075
  | $call$body$main__closure | @ | client.js:26063
  | call$1 | @ | client.js:25993
  | _rootRunUnary | @ | client.js:3393
  | runUnary$2$2 | @ | client.js:13083
  | runUnaryGuarded$1$2 | @ | client.js:13011
  | _sendData$1 | @ | client.js:12564
  | perform$1 | @ | client.js:12771
  | handleNext$1 | @ | client.js:12845
  | call$0 | @ | client.js:12817
  | _microtaskLoop | @ | client.js:3253
  | _startMicrotaskLoop | @ | client.js:3259
  | call$1 | @ | client.js:11580
  | childList (async) |   |  
  | call$1 | @ | client.js:11590
  | _scheduleAsyncCallback | @ | client.js:3272
  | _rootScheduleMicrotask | @ | client.js:3437
  | scheduleMicrotask | @ | client.js:3300
  | schedule$1 | @ | client.js:12806
  | _addPending$1 | @ | client.js:12555
  | _sendData$1 | @ | client.js:12365
  | add$1 | @ | client.js:12260
  | _onIncomingMessage$1 | @ | client.js:25615
  | eval | @ | VM72:3
  | invokeClosure | @ | client.js:1206
  | (anonymous) | @ | client.js:1225
  | Show 35 more frames
```

```
flutter doctor -v
[✓] Flutter (Channel master, v1.10.5-pre.24, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.10.5-pre.24 at /Users/klavergne/Documents/dev/flutter
    • Framework revision ea7876ae82 (3 hours ago), 2019-09-19 07:46:50 -0700
    • Engine revision 1cada0a6dc
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 ea969c358e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/klavergne/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • iPhone Xʀ • 8E59914C-6EE3-4892-BEA5-038A2F801AC7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)
    • Chrome    • chrome                               • web-javascript • Google Chrome 77.0.3865.90
    • Server    • web                                  • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jonahwilliams** [comment]
cc @yjbanov @mdebbar

**Comment by wada314** [comment]
Same here, Windows 10. 
I created a similar issue #40879 but I closed it.

**Comment by wada314** [comment]
And some similar bug reports in #40531.

**Comment by timtraversy** [comment]
https://github.com/flutter/flutter/pull/40824 It seems like the regression happens from this commit onwards.

**Comment by MSchmack** [comment]
Same error on the master channel. Error does not appear on the dev channel.

**Comment by ymback** [comment]
Same here, Windows 10.

```
[√] Flutter (Channel master, v1.10.6-pre.19, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.10.6-pre.19 at C:\Temp\Android\flutter
    • Framework revision ec07e039c2 (2 hours ago), 2019-09-19 21:37:41 -0400
    • Engine revision 70f21b0edb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Temp\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\Temp\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.5
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by yangxinliang** [comment]
Create a web application using flutter but with a blank screen

**Comment by yangxinliang** [comment]
Create a web application using flutter but with a blank screen #40876

**Comment by AmjadKhan2k18** [comment]
I was working on web application it was working fine, when i upgrade flutter to Flutter 1.10.6-pre.19 version it's just a blank screen now

**Comment by jinges** [comment]
I have a same bug;

[+1948 ms] Failed to load asset at path:
packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

**Comment by fribeau** [comment]
I have the same bug.
I am running under Linux (Ubuntu 18.04).

`
[✓] Flutter (Channel master, v1.10.6-pre.19, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.10.6-pre.19 at /home/X/X/flutter
    • Framework revision ec07e039c2 (il y a 11 heures), 2019-09-19 21:37:41 -0400
    • Engine revision 70f21b0edb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/X/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.75
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
`

**Comment by timtraversy** [comment]
If you have the same bug, you can just thumbs up this issue 👍🏼

**Comment by escamoteur** [comment]
I had today the same problem after upgrading master to latest version v1.10.6-pre.19

**Comment by jason-simmons** [comment]
Bisected this to a Dart SDK change: https://github.com/dart-lang/sdk/commit/ce6f40bccc5bd570ad516d266306f6c99e9e60f2

@vsmenon

**Comment by vsmenon** [comment]
Reverting the above for now: https://dart-review.googlesource.com/c/sdk/+/118261

**Comment by asmallkite** [comment]
Same error on the master channel. Error does not appear on the dev channel.

**Comment by biij5698** [comment]
The same problem to me

**Comment by vsmenon** [comment]
Note, this should fixed on the next Dart roll.

**Comment by lbaiao** [comment]
Same problem here. Chrome and Windows 10

**Comment by nancy54264** [comment]
Same error , Win 10

**Comment by sutharsha** [comment]
Same error OsX and Chrome

**Comment by 5lineofcode** [comment]
same problem on windows 10,

fixed when i change it to dev channel,
flutter channel dev
flutter upgrade
flutter run -d chrome

Thanks @asmallkite

**Comment by brux88** [comment]
the same problem

**Comment by escamoteur** [comment]
Hey guys we know the problem and a fix is on the way.

**Comment by Lucasoliviersystem** [comment]
same problem here :/

**Comment by debasmitasarkar** [comment]
Same here :/

**Comment by omontoya** [comment]
same here...

**Comment by ptyagicodecamp** [comment]
Web variant works fine for dev channel. You may want to switch flutter channel to `dev`:
```
flutter channel dev
flutter upgrade
flutter run -d chrome
```
However, there are 2 issues in dev channel as well:

1. It throws following exception in console (chrome's):
```
pointer_binding.dart:85 Uncaught TypeError: t129.onPointerDataPacket is not a function
    at _engine.PointerBinding.new.[_onPointerData] (pointer_binding.dart:85)
    at pointer_binding.dart:207
    at HTMLElement.<anonymous> (pointer_binding.dart:143)
```

2. Wouldn't work for native. Check [this issue](https://github.com/flutter/flutter/issues/41049) for details.

**Comment by mdebbar** [comment]
> 1. It throws following exception in console (chrome's):

@ptyagicodecamp this is an unrelated issue that's being fixed [here](https://github.com/flutter/engine/pull/12403).

**Comment by ptyagicodecamp** [comment]
> Web variant works fine for dev channel. You may want to switch flutter channel to `dev`:
> 
> ```
> flutter channel dev
> flutter upgrade
> flutter run -d chrome
> ```
> 
> However, there are 2 issues in dev channel as well:
> 
> 1. It throws following exception in console (chrome's):
> 
> ```
> pointer_binding.dart:85 Uncaught TypeError: t129.onPointerDataPacket is not a function
>     at _engine.PointerBinding.new.[_onPointerData] (pointer_binding.dart:85)
>     at pointer_binding.dart:207
>     at HTMLElement.<anonymous> (pointer_binding.dart:143)
> ```
> 
> 1. Wouldn't work for native. Check [this issue](https://github.com/flutter/flutter/issues/41049) for details.

Two other issues that I mentioned were not related to this particular problem. Switching to `dev` channel fixed the White screen issue for me.

**Comment by ptyagicodecamp** [comment]
> > 1. It throws following exception in console (chrome's):
> 
> @ptyagicodecamp this is an unrelated issue that's being fixed [here](https://github.com/flutter/engine/pull/12403).

Thanks for confirming that.

**Comment by timtraversy** [comment]
This seems to be resolved now on the `master` branch 🚀. I created a fresh project and ran `flutter run -d chrome` and didn't hit any issues.

**Comment by ferhatb** [comment]
Original dart PR was reverted, engine updated and engine rolled into flutter.

**Comment by humazed** [comment]
still having the same issue in the master while dev is working fine.

 Flutter (Channel master, v1.10.6-pre.49, on Microsoft Windows [Version 10.0.18362.356], locale en-US)

**Comment by chunhtai** [comment]
The engine roll that reverted the dartsdk has been reverted due to ios32bit crash.
The fix will be reapply once the ios32 bit dart change is reverted and rerolled into flutter.

**Comment by Hixie** [comment]
Status: We're waiting for a clean engine roll; no work needs to be done specifically here.

**Comment by sajidbarcha** [comment]
I am on channel master, windows 10, I am facing the same problem

Channel master v1.10.6-pre.25

**Comment by Ndivhuwo** [comment]
I too am facing this issue of Flutter 1.10.15-pre.338

**Comment by praharshbhatt** [comment]
Still facing the issue, on **Flutter (Channel master, v1.10.17-pre.70, on Microsoft Windows [Version 10.0.18362.418], locale en-US)**
The blank screen only appears in web build using `flutter build web`, debug works just fine.


![image](https://user-images.githubusercontent.com/30700808/68742899-3fa4c980-0617-11ea-8a29-65e3d2a38758.png)

**Comment by yjbanov** [comment]
@praharshbhatt Your issue does not seem related to the original issue. In your case it seems you are attempting to run the app by opening it from the file system (as shown by the `file:///` URLs), and the CORS policy blocks all XHRs (in fact XHRs cannot possibly succeed without a server). We do not support this mode. You need a local server to serve the app from. For development you can use `flutter run -d chrome`. For deployment any popular HTTP server should work, including static site hosting, such as Firebase.

**Comment by nemoryoliver** [comment]
same here on the latest Flutter Beta channel. No errors just blank white screen.

**Comment by TheJulianJES** [comment]
@nemoryoliver You may want to file a new issue, as it probably has a different cause.

**Comment by mdebbar** [comment]
@nemoryoliver please file a new issue and include some details of what you are seeing (e.g. console output, terminal output, `flutter doctor -v` output, etc).

**Comment by sangron** [comment]
Hey, when I try on the emulator it builds the apk and runs ok.
When I try `flutter run -d chrome` builds the app and runs ok on chrome.
But when I try `flutter run -d chrome --release` then I get a white screen, with this error message in the console.
So I have the same problem with `flutter build web`, is there a way to use dardevc to run flutter build web

```
Uncaught Assertion failed
    at Object.f (http://localhost:51107/main.dart.js:1770:3)
    at Object.K (http://localhost:51107/main.dart.js:1776:23)
    at http://localhost:51107/main.dart.js:14902:3
    at a89.a (http://localhost:51107/main.dart.js:2685:71)
    at a89.$2 (http://localhost:51107/main.dart.js:22942:23)
    at Object.A (http://localhost:51107/main.dart.js:2672:19)
    at Object.DT (http://localhost:51107/main.dart.js:14921:10)
    at http://localhost:51107/main.dart.js:62620:8
    at http://localhost:51107/main.dart.js:62615:55
    at dartProgram (http://localhost:51107/main.dart.js:62618:84)
```

`in js_helper.dart:1342`

then I follow this source and this is the content.
```Could not load content for org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_helper.dart : HTTP status code: 404```

Here is my flutter doctor -v output:
```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [VersiÃ³n 10.0.18362.535], locale es-MX)
    • Flutter version 1.12.13+hotfix.6 at C:\tools\flutter\flutter
    • Framework revision 18cd7a3601 (32 hours ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by qijie07** [comment]
> @nemoryoliver please file a new issue and include some details of what you are seeing (e.g. console output, terminal output, `flutter doctor -v` output, etc).

It's is working fine on my mac, but I got this error when I visiting it on my server.All of content in dartlang-sdk is 404.
![image](https://user-images.githubusercontent.com/12227120/70875970-cec84700-1ff2-11ea-8a9a-dac29158334c.png)
![image](https://user-images.githubusercontent.com/12227120/70876019-fddeb880-1ff2-11ea-8354-8967edc806af.png)
![image](https://user-images.githubusercontent.com/12227120/70876030-046d3000-1ff3-11ea-9bf0-2a1b52defd4c.png)

**Comment by praharshbhatt** [comment]
> > @nemoryoliver please file a new issue and include some details of what you are seeing (e.g. console output, terminal output, `flutter doctor -v` output, etc).
> 
> It's working fine on my mac, but I got this error when I visiting it on my server.All of content in dartlang-sdk is 404.I using the latest Flutter Beta channel.
> ![image](https://user-images.githubusercontent.com/12227120/70875970-cec84700-1ff2-11ea-8a9a-dac29158334c.png)
> ![image](https://user-images.githubusercontent.com/12227120/70876019-fddeb880-1ff2-11ea-8354-8967edc806af.png)
> ![image](https://user-images.githubusercontent.com/12227120/70876030-046d3000-1ff3-11ea-9bf0-2a1b52defd4c.png)

I'm facing the very same error, works fine on debug. The error only occurs while in release mode

**Comment by michalsurynt** [comment]
I'm getting the same issue. Debugging locally works perfectly fine, but then the app is built and run at codemagic's static pages, I can see only the blank screen.
```
== Flutter version ==
Flutter 1.15.3 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 67826bdce5 (2 days ago) • 2020-02-10 14:59:32 -0800
Engine • revision 6158f03ef5
Tools • Dart 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)
```

**Comment by ditman** [comment]
@michalsurynt any errors in your browser's JS console?

**Comment by ianvillamia** [comment]
Same recently tried flutter web and encountered this I've tried changing channels but still doesn't show. Please re-Open

**Comment by QwesysDigitalSolution** [comment]
hi getting the same error.
```
flutter channel dev
flutter upgrade
flutter run -d chrome
```
Work For Me. In master channel it still pending.

**Comment by Arcturus122** [comment]
Hi, getting this error to. even when trying with channel dev, it does not work and I still got a blank page.

**Comment by TinusJ** [comment]
@Arcturus122 Are you using Firebase?

**Comment by Arcturus122** [comment]
> @Arcturus122 Are you using Firebase?

Yes I'm using Firebase.

**Comment by TinusJ** [comment]
@Arcturus122 Add the following to your index.html in your web/ folder

```
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-firestore.js"></script>
  <script src="./init-firebase.js"></script>
```

Above your main.dart script

Then add the following file in the directory `init-firebase.js`

In that file you will need to add the config as well as initializing it.

```
var firebaseConfig = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: ""
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
```

**Comment by Arcturus122** [comment]
@TinusJ thank you very much it worked !

**Comment by HashemShepard** [comment]
im not using firebase and still getting white screen when i use
flutter run -d web
and when i use
flutter run -d chrome
"Unable to connect to Chrome debug port: 55184
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 55189"
Any help would be truly appreciated

**Comment by HashemShepard** [comment]
FIXED IT
switched to beta then back to dev using
flutter channel dev
flutter upgrade
then run via web
flutter run -d web

**Comment by kaiserleka** [comment]
@HashemShepard I have done your steps but still getting **white screen** 

[ERROR SCREEN](https://ibb.co/dLY3Qhz)

pubspec.yaml
```
name: myapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4+2
```

Body of index.html
```
<body>
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="/__/firebase/7.13.1/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="/__/firebase/7.13.1/firebase-analytics.js"></script>
  <script defer src="https://www.gstatic.com/firebasejs/7.13.1/firebase-firestore.js"></script>


  <!-- Initialize Firebase -->

  <script src="/__/firebase/init.js"></script>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <!-- Previously loaded Firebase SDKs -->

  <!-- ADD THIS BEFORE YOUR main.dart.js SCRIPT -->
  <script>
    // TODO: Replace the following with your app's Firebase project configuration.
    // See: https://support.google.com/firebase/answer/7015592
    var firebaseConfig = {
      // ... deleted lines for public access
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
  <!-- END OF FIREBASE INIT CODE -->
  <script src="main.dart.js" type="application/javascript"></script>
</body>
```

```
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.1 19B88, locale en-TR)
    • Flutter version 1.16.4-pre.33 at /Users/leventkantaroglu/Development/flutter
    • Framework revision aee9e94c21 (2 days ago), 2020-03-30 16:12:40 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/leventkantaroglu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by MahmoudiOussama** [comment]
Same issue: Chrome shows a blank page.
**Console shows below error : **
![image](https://user-images.githubusercontent.com/25067744/79278514-bc2c2480-7ea3-11ea-9aaa-cb7f9a486655.png)

**Flutter doctor command shows : **
![image](https://user-images.githubusercontent.com/25067744/79278672-188f4400-7ea4-11ea-9647-14a0d4d3e773.png)

**Comment by soulbliss** [comment]
> @Arcturus122 Add the following to your index.html in your web/ folder
> 
> ```
>   
>   <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-app.js"></script>
>   <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-auth.js"></script>
>   <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-firestore.js"></script>
>   <script src="./init-firebase.js"></script>
> ```
> 
> Above your main.dart script
> 
> Then add the following file in the directory `init-firebase.js`
> 
> In that file you will need to add the config as well as initializing it.
> 
> ```
> var firebaseConfig = {
>     apiKey: "",
>     authDomain: "",
>     databaseURL: "",
>     projectId: "",
>     storageBucket: "",
>     messagingSenderId: "",
>     appId: ""
> };
> // Initialize Firebase
> firebase.initializeApp(firebaseConfig);
> ```

^ this along with switching to the dev channel worked for me locally.

~~~
flutter channel dev
flutter upgrade
flutter run -d chrome
~~~
