### ISSUE TITLE
Input Formatter does not work on Android

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#41005]
The code [here](https://github.com/jkurtw/flutter_issues/tree/master/text_editing
) tries to format text input based on masking format, trying to display a credit card number format.
XXXX XXXX XXXX XXXX

It also tries to handle deletions, so

XXXX<Space>X

after deletion of the last X

becomes
XXXX

However, seems like this works on iOS and web, but not on Android.

formatTextInput seems to be called multiple times.

This seemed to be working 3 months ago.

Here is the behavior I'm seeing:

- iOS - can type in 4 numbers, then a space is automatically inserted. I can then type two more numbers before it stops accepting input (e.g. "1234 56")
- Android - can only type in four numbers before it stops accepting input (e.g. "1234")
- web - works the same as iOS

b/141279347

**Comment by HansMuller** [comment]
This regression was introduced in an August 19th engine roll: #38855.
The engine PR that's causing the problem is flutter/engine#9498.

It was also reported in #39047, #39182, #39485, #39487, #39223, #39738

This issue was fixed: see #39523, and flutter/engine#11720.

Closing this one as a duplicate.

**Comment by jkurtw** [comment]
Trying this again on dev channel. iOS and web got better, but Android still doesn't work correctly.

On iOS, you can now type a full set of numbers, like:
1234 1234 1234 1234

On web, you can the same behavior as iOS.

On Android, you can only type four numbers, before it stop accepting more input:
1234

```
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.10.5 at /Users/jkurtw/development/flutter
    • Framework revision 3cf88fed6d (7 days ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 cb80ea7ba9)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jkurtw/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!


```

**Comment by HansMuller** [comment]
I can confirm that the app fails as described, on tip of tree.

Thankfully, the old issue noted in https://github.com/flutter/flutter/issues/41005#issuecomment-534163039 remains fixed. 

Assuming that this is a regression, I'm going to see if I can sort out when this problem was introduced.

**Comment by HansMuller** [comment]
Using a slightly smaller (one file) version of your [test case](https://gist.github.com/HansMuller/b25a6d16301c95c0eabf6f8cde8e3091).

I've noticed that when the input formatter inserts a character, the formatEditUpdate calls are pretty confusing. For example upon adding '5' to '1234', 3 calls to formatEditUpdate are generated:

```
old="1234"   new="12345" => reformatted="1234 5"
old="1234 5" new="12345" (this used to trigger a delete)
old="12345"  new="1234 5" => reformatted="1234 5"
```

The second notification triggered the delete handler, which I've commented out for the moment. Without the delete handler it's possible to fill field the field.

**Comment by jkurtw** [comment]
From the internal bug, "It seems that this problem only occurs when the TextField's keyboardType is set to TextInputType.number"

**Comment by mehmetf** [comment]
@HansMuller  This has become a very important blocker for customer:money. They are expecting a fix by end of this week.

**Comment by HansMuller** [comment]
I'm looking at this issue again now.

**Comment by HansMuller** [comment]
When TextField's keyboardType: TextInputType.number, two incoming calls to TextInputClient.updateEditingState on the engine's TextInputConnection are generated for each character input. With the default keyboardType, only one call to TextInputClient.updateEditingState is generated, which is what's expected.

The second updateEditingState call can wreak havoc when it comes after the input formatter has inserted a character, for example when "12345" is transformed to "1234 5". In this case the extra "12345" notification looks like the user deleted a character, since the updateEditingState "12345" text is shorter that "1234 5".

A simple app that demos the problem in terms of EditableText (and without input formatters): https://gist.github.com/HansMuller/5d8b3573f446dafcb697da9f42206020

CC @cbracken @jason-simmons

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/engine/pull/13175, which rolled into Flutter in https://github.com/flutter/flutter/pull/42883

**Comment by Menelphor** [comment]
<h3>Overview:</h3>
There still is an Error with the Input Formatter on Flutter v 1.12:

When the user uses the special character keyboard to type numbers, the keyboard switches back to the default alphabetic style after the insert of the whitespace.

For the test i used a google pixel 3a with Android Q installed.

<h3>How to reproduce:</h3>

[Example](https://gist.github.com/Menelphor/8b7ad505bd181ae31ebb939795c86610) based on @HansMuller gist.


1. Tap on Textfield
2. Change Keyboard to special characters
3. Insert 5 digits (as no other characters will work)
4. after inserting the 5th. digit, the keyboard style will change back to alphabetic


<h3>Flutter doctor</h3>

```

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale de-DE)
    • Flutter version 1.12.13+hotfix.5 at /Users/mhein/Documents/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mhein/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Pixel 3a • 992AY1866K • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.


```
