### ISSUE TITLE
Images taken by rear camera disappear when scrolled to screen edge

### ISSUE THREAD

**Issue by Mugen0** [flutter/flutter#41065]
I came upon this weird issue that **images would suddenly disappear when scrolled to the edges of the screen**, as shown in the gif below.
![reproduce](https://user-images.githubusercontent.com/23414710/65394350-4fdebc00-ddbf-11e9-9e8c-bf97b218c53c.gif)

The strange part is, this only happens if the selected image was taken by the rear camera of an iPhone. Images took by the front camera or from other resources won't cause it. 
Tested environment: iPhone XR with iOS 13. Haven't tested on an Android device.

## Steps to Reproduce

1. Need an iOS device. Simulator won't reproduce. Not sure if iOS 13 is necessary.
2. Use the code below. **image_picker** is used, be sure to import it properly.

<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Image> _list = [];
  File _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () async {
                _image =
                    await ImagePicker.pickImage(source: ImageSource.gallery);
                if (_image != null) {
                  setState(() {
                    _list.add(Image.file(_image, gaplessPlayback: true));
                  });
                }
              },
            )
          ],
        ),
        body: ListView.builder(
          itemCount: _list.length,
          itemBuilder: (context, index) => _list[index],
        ));
  }
}
```
</details>

3. Install to an iOS device. Choose some photos that are taken by the rear camera from the gallery. Scroll the screen to see if they disappear.

**Comment by escamoteur** [comment]
Ok, my suspicion is that its because of the different aspect ratio of front and back camera which leads to different sizes of Tiles in the Listview. If you play with the fit parameter of Image you will get different results.
@HansMuller is this by design?

**Comment by escamoteur** [comment]
Does this only happen on iOS?
Could you please add the output of flutter doctor here?

**Comment by Mugen0** [comment]
> Does this only happen on iOS?
> Could you please add the output of flutter doctor here?

I don't have an Android device to test. Flutter doctor outputs are as follows.
'''
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (not installed)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
'''

**Comment by Mugen0** [comment]
> Ok, my suspicion is that its because of the different aspect ratio of front and back camera which leads to different sizes of Tiles in the Listview. If you play with the fit parameter of Image you will get different results.

It can't be aspect ratio. If the image was converted to other format and saved to the album, it won't cause the problem, even if the ratio remains the same.

**Comment by escamoteur** [comment]
What do you mean with converted to another format?

**Comment by Mugen0** [comment]
> What do you mean with converted to another format?

The photo taken by rear camera is a 4032 * 3024 HEIC file. When I convert it to 1440 * 1080 jpg, it does not cause the problem. The ratio remains the same.

**Comment by escamoteur** [comment]
This is an extremely important detail, thanks for the reply. Can you please tell me what resolution has your front camera?
It seems its more about the pure image size. 

Was it always like this? 

Could you please check if the problem is still there when you switch on the latest version of master? 

If you have the chance please install Android Studio and try if it happens on the Android Emulator too.

**Comment by Mugen0** [comment]
> Can you please tell me what resolution has your front camera?

I'm using iPhone XR, the front camera is 2316 * 3088.

> It seems its more about the pure image size.

It's quite complicated from my point of view. If the image is cropped _wider_(horizontal size is much bigger than vertical), it won't cause the problem. However, if it's cropped _thiner_, it will cause an even bigger problem, the listview will jump to another position when such an image is scrolled to the edge.

> Try master channel

I got a compile error with the master channel (some Thread 1: signal SIGABRT thing), so I couldn't try.

> If you have the chance please install Android Studio and try if it happens on the Android Emulator too.

I couldn't reproduce this on iOS simulator even if I use HEIC file in it, so I don't think Android will do.

**Comment by escamoteur** [comment]
Did you test with a release build?
Not sure if you have been on the latest master which is 1.10.6+29

**Comment by Mugen0** [comment]
> Did you test with a release build?

Since iOS13 I can only compile to a physical device with Xcode, otherwise, it gets an error as #37699 mentions. I'm not sure if that approach gets release build. 

> Not sure if you have been on the latest master which is 1.10.6+29
Sorry, switching channels are causing troubles for me, I'm using the stable channel now. 

Would you please try to reproduce this issue with code above? Or @ someone who is available.

**Comment by escamoteur** [comment]
To use iOS 13 you need to use the latest master till the bug is fixed.

According to your screenshot it is a release build unless you didn't remove the debug badge manually.
I can't reproduce it at the moment. We will have to wait till the flutter team has time.
I'm sorry for this problem.

**Comment by Mugen0** [comment]
I see. I'll try to switch to master channel and update.

**Comment by Mugen0** [comment]
@escamoteur I switched to master v1.10.6-pre.39 and tested a release build. The problem is still there.

**Comment by escamoteur** [comment]
Thanks a lot for trying.

**Comment by TahaTesser** [comment]
<details>
<summary>complete updated  runnable code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Image> _list = [];
  final picker = ImagePicker();
  File _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () async {
                final pickedFile =
                    await picker.getImage(source: ImageSource.gallery);

                if (pickedFile != null) {
                  setState(() {
                    _list.add(Image.file(File(pickedFile.path),
                        gaplessPlayback: true));
                  });
                }
              },
            )
          ],
        ),
        body: ListView.builder(
          itemCount: _list.length,
          itemBuilder: (context, index) => _list[index],
        ));
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.229, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.229 at /Users/tahatesser/Code/flutter_master
    • Framework revision 650b240634 (2 hours ago), 2021-01-27 21:39:06 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Verified this issue using latest versions on iOS device (iPhone 6s) and observed that the behavior is not replicable. The images don't disappear while scrolling.


https://user-images.githubusercontent.com/67046386/205911013-802570e3-b904-4863-847a-6f811b5489c6.mov

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-3.0.pre.33 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (2 hours ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Closing as fixed.
