### ISSUE TITLE
ext.flutter.structuredErrors doesn't call into original FlutterError.onError

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#41540]
## Steps to Reproduce

1. Create a flutter app and add a custom error handler in `main.dart`:

```dart
main() {
  FlutterError.onError = Crashlytics.instance.recordFlutterError;

  // Omitted part -- somewhere below:
  // Crashlytics.instance.enableInDevMode = true;
  // runApp(...);
}
```

2. Run flutter app in debug mode with default settings.
3. Observe that `recordFlutterError` is never called. Going to Dev Tools "Logging" and clearing "Show structured errors" checkbox fixes it, but doesn't look like documented behavior.

+cc @jacob314 @goderbauer @Hixie 

## Logs

```
$ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[!] Android Studio (not installed)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by dotdoom** [comment]
+cc @kroikie FYI: in case I'm not mistaken about this behavior change, this makes testing Crashlytics via `Crashlytics().crash();` slightly more complicated.

**Comment by jacob314** [comment]
We need to switch to a subscription based model to avoid one error listener trampling on the others.

**Comment by Hixie** [comment]
I have an informal design for something like this. Ping me tomorrow and I'll send you the link. I don't recall if it solves this exact issue but that's the idea.

**Comment by dotdoom** [comment]
@jacob314 or an error handler could be a good citizen and call into the previously installed handler once it's finished :)

@Hixie, ping!

**Comment by jacob314** [comment]
Calling the previous installed handler sounds like a risky API design. Sorry I was away on vacation. I'll follow up now.

**Comment by dotdoom** [comment]
Hi there! Hope you folks are all doing well. Do you happen to know if there has been any progress?

**Comment by dotdoom** [comment]
And here I am again, humbly reminding that this is still an issue. @jacob314 
@Hixie is your design something that can be shared externally?

**Comment by kroikie** [comment]
@dotdoom you are correct the issue I ran into was with onError not being called can be a result of Flutter Inspector catching the error before it gets to the onError callback.

If the app is run without the Flutter Inspector then the error is caught by onError as expected.

Having multiple onError listeners seems to be a reasonable solution to this.

**Comment by Hixie** [comment]
There's a design but it's a photo of my whiteboard. :-) I'll see if I can put it up somewhere. Ping me on Discord on Monday?

**Comment by rhalff** [comment]
It should at least be documented that in order to use a custom `Flutter.onError` in debug mode structured logging should be turned off in the IDE. (As suggested by point 3)

It took me some debugging time to arrive at the same conclusion as there are several open tickets not providing an answer.

The relevant code snippet is here:https://github.com/flutter/flutter/blob/1118d24794088119bbd649462e320d246533001e/packages/flutter/lib/src/widgets/widget_inspector.dart#L961-L971

And structured logging was enabled by default in this PR: flutter/flutter-intellij#3831

Perhaps it could be made so that if `Flutter.onError` has been overridden (`FlutterError.onError != FlutterError.dumpErrorToConsole`) it should not be overridden with the `structuredExceptionHandler`.

An additional suggestion is to have the structured logging checkbox be moved to the debug/console panel instead, which makes it a more conscious action to fiddle with the error logging behavior.

**Comment by dotdoom** [comment]
I believe it's fixed by #53843

**Comment by jamie1192** [comment]
`FlutterError.onError` still doesn't work on either current stable or dev branch.

**Comment by alexobviously** [comment]
@jamie1192 
To be clear, you're only changing one line here? If I try this, it doesn't change anything for me - I still get the same behaviour.

**Comment by Hixie** [comment]
https://flutter.dev/go/error-handling is the proposal for how to fix this.

**Comment by Hixie** [comment]
@jacob314 I think we should increase the priority here. I personally run into people who are confused by the WidgetInspector hijacking FlutterError.onError at least once a month, so who knows how many people it's really affecting.

**Comment by bitsydarel** [comment]
Any news ?

**Comment by snoopdoggy322** [comment]
What about this issue? Is there any solution?

**Comment by TahaTesser** [comment]
closing as duplicate of https://github.com/flutter/flutter/issues/48972
