### ISSUE TITLE
VM snapshot invalid and could not be inferred from settings crash SOMETIMES on Note 4 when using app-bundle on Android

### ISSUE THREAD

**Issue by lawonga** [flutter/flutter#41636]
## Steps to Reproduce

My environment:
- Note 4 on android 6.0.1.
- App is an add-to-app using the new embedded FlutterEngine. 
- **The FlutterEngine is being initialized on app start.**

1. Find a Note 4 or something like that. My Note 4 is running Android 6.0.1. Install the app on it.
2. Use bundletool to deliver a split apk (or beta channel through the play store) as a release build
3. Expect a 30-50% chance of the app randomly crashing on app start.

Using bundletool to cut open the installed apk does indeed show the appropriate `lipapp.so` files required. It makes sense too, since this app manages to successfully start once in a while and launch the appropriate flutter screens.
![image](https://user-images.githubusercontent.com/4753746/65911473-8e591580-e381-11e9-9351-7a6ff432feb8.png)

## Logs
```
09-30 12:48:13.995 461-461/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-30 12:48:13.995 461-461/? A/DEBUG: Build fingerprint: 'samsung/trltecan/trltecan:6.0.1/MMB29M/N910W8VLS1DPK1:user/release-keys'
09-30 12:48:13.995 461-461/? A/DEBUG: Revision: '12'
09-30 12:48:13.995 461-461/? A/DEBUG: ABI: 'arm'
09-30 12:48:13.995 461-461/? A/DEBUG: pid: 14696, tid: 14696, name: om.move.realtor  >>> com.move.realtor <<<
09-30 12:48:13.995 461-461/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-30 12:48:14.015 461-461/? A/DEBUG: Abort message: '[FATAL:flutter/shell/common/shell.cc(212)] Check failed: vm. Must be able to initialize the VM.
    '
09-30 12:48:14.015 461-461/? A/DEBUG:     r0 00000000  r1 00003968  r2 00000006  r3 b6fb4b94
09-30 12:48:14.015 461-461/? A/DEBUG:     r4 b6fb4b9c  r5 b6fb4b4c  r6 00000002  r7 0000010c
09-30 12:48:14.015 461-461/? A/DEBUG:     r8 bef43268  r9 bef43820  sl bef43850  fp bef43868
09-30 12:48:14.015 461-461/? A/DEBUG:     ip 00000006  sp bef42668  lr b6d14c01  pc b6d16ff0  cpsr 400f0010
09-30 12:48:14.025 461-461/? A/DEBUG: backtrace:
09-30 12:48:14.025 461-461/? A/DEBUG:     #00 pc 00041ff0  /system/lib/libc.so (tgkill+12)
09-30 12:48:14.025 461-461/? A/DEBUG:     #01 pc 0003fbfd  /system/lib/libc.so (pthread_kill+32)
09-30 12:48:14.025 461-461/? A/DEBUG:     #02 pc 0001c397  /system/lib/libc.so (raise+10)
09-30 12:48:14.025 461-461/? A/DEBUG:     #03 pc 00019615  /system/lib/libc.so (__libc_android_abort+34)
09-30 12:48:14.025 461-461/? A/DEBUG:     #04 pc 00017568  /system/lib/libc.so (abort+4)
09-30 12:48:14.025 461-461/? A/DEBUG:     #05 pc 0002353b  /data/app/com.move.realtor-1/split_config.armeabi_v7a.apk (offset 0xdb0000)
09-30 12:48:14.555 461-461/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
09-30 12:48:14.555 461-461/? E/DEBUG: AM write failed: Broken pipe
09-30 12:48:14.555 3765-3765/? E/audit: type=1701 msg=audit(1569856694.555:587): auid=4294967295 uid=10512 gid=10512 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=14696 comm="om.move.realtor" reason="memory violation" sig=6
```

#### Flutter Doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/awong/Documents/Programming/sdk/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/awong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM N910W8 • 3d4bc472 • android-arm • Android 6.0.1 (API 23)
```

**Comment by escamoteur** [comment]
See https://github.com/flutter/flutter/issues/40770

Could you please try with beta / master channel it should be fixed there.

**Comment by lawonga** [comment]
@escamoteur 

I have switched to `dev` channel, and after building it it is not fixed there:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G95, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.38.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by lawonga** [comment]
Crash using a build from the beta channel:

#### Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.38.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
```

#### Crash dump
```
10-01 10:05:04.202 15010-15010/? E/flutter: [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
10-01 10:05:04.202 15010-15010/? E/flutter: [ERROR:flutter/runtime/dart_vm.cc(245)] Could not setup VM data to bootstrap the VM from.
10-01 10:05:04.202 15010-15010/? E/flutter: [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
10-01 10:05:04.202 15010-15010/? A/flutter: [FATAL:flutter/shell/common/shell.cc(212)] Check failed: vm. Must be able to initialize the VM.
10-01 10:05:04.202 15010-15010/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 15010 (om.move.realtor)
10-01 10:05:04.302 465-465/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-01 10:05:04.302 465-465/? A/DEBUG: Build fingerprint: 'samsung/trltecan/trltecan:6.0.1/MMB29M/N910W8VLS1DPK1:user/release-keys'
10-01 10:05:04.302 465-465/? A/DEBUG: Revision: '12'
10-01 10:05:04.302 465-465/? A/DEBUG: ABI: 'arm'
10-01 10:05:04.302 465-465/? A/DEBUG: pid: 15010, tid: 15010, name: om.move.realtor  >>> com.move.realtor <<<
10-01 10:05:04.302 465-465/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-01 10:05:04.322 465-465/? A/DEBUG: Abort message: '[FATAL:flutter/shell/common/shell.cc(212)] Check failed: vm. Must be able to initialize the VM.
    '
10-01 10:05:04.322 465-465/? A/DEBUG:     r0 00000000  r1 00003aa2  r2 00000006  r3 b6f80b94
10-01 10:05:04.322 465-465/? A/DEBUG:     r4 b6f80b9c  r5 b6f80b4c  r6 00000002  r7 0000010c
10-01 10:05:04.322 465-465/? A/DEBUG:     r8 be991268  r9 be991820  sl be991850  fp be991868
10-01 10:05:04.322 465-465/? A/DEBUG:     ip 00000006  sp be990668  lr b6ce0c01  pc b6ce2ff0  cpsr 400f0010
10-01 10:05:04.332 465-465/? A/DEBUG: backtrace:
10-01 10:05:04.332 465-465/? A/DEBUG:     #00 pc 00041ff0  /system/lib/libc.so (tgkill+12)
10-01 10:05:04.332 465-465/? A/DEBUG:     #01 pc 0003fbfd  /system/lib/libc.so (pthread_kill+32)
10-01 10:05:04.332 465-465/? A/DEBUG:     #02 pc 0001c397  /system/lib/libc.so (raise+10)
10-01 10:05:04.332 465-465/? A/DEBUG:     #03 pc 00019615  /system/lib/libc.so (__libc_android_abort+34)
10-01 10:05:04.332 465-465/? A/DEBUG:     #04 pc 00017568  /system/lib/libc.so (abort+4)
10-01 10:05:04.332 465-465/? A/DEBUG:     #05 pc 0002353b  /data/app/com.move.realtor-1/split_config.armeabi_v7a.apk (offset 0xdb0000)
10-01 10:05:04.852 465-465/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
10-01 10:05:04.852 465-465/? E/DEBUG: AM write failed: Broken pipe
```

**Comment by blasten** [comment]
There's also this crash report https://github.com/flutter/flutter/issues/36822 on Android 6.0. 

cc @jason-simmons

**Comment by zmeggyesi** [comment]
Perhaps I should comment here, rather than a closed thread. I'm running into the same issue trying to run the app on a physical iPhone (as opposed to the XCode simulator).

I've tried removing the Flutter cache, re-running `doctor`, as well as running `flutter upgrade` to advance to `68587a0916`, but when trying to launch on a physical iPhone after `flutter build`, I get the following, and a white screen:
```
2019-11-25 20:08:08.361862+0100 Runner[732:33380] [VERBOSE-2:dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
2019-11-25 20:08:08.362089+0100 Runner[732:33380] [VERBOSE-2:dart_vm.cc(245)] Could not setup VM data to bootstrap the VM from.
2019-11-25 20:08:08.362183+0100 Runner[732:33380] [VERBOSE-2:dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
2019-11-25 20:08:08.362871+0100 Runner[732:33380] [VERBOSE-3:shell.cc(212)] Check failed: vm. Must be able to initialize the VM.
```

The upgrade command produced, eventually:
```
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (2 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

Output from Flutter Doctor:
```
👻 20:05:46 zmeggyesi@ShinyPlatform:[~/projects/site-overwatch/frontend]:
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (not installed)
[!] VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Comment by lawonga** [comment]
> Perhaps I should comment here, rather than a closed thread. I'm running into the same issue trying to run the app on a physical iPhone (as opposed to the XCode simulator).
> 
> I've tried removing the Flutter cache, re-running `doctor`, as well as running `flutter upgrade` to advance to `68587a0916`, but when trying to launch on a physical iPhone after `flutter build`, I get the following, and a white screen:
> 
> ```
> 2019-11-25 20:08:08.361862+0100 Runner[732:33380] [VERBOSE-2:dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
> 2019-11-25 20:08:08.362089+0100 Runner[732:33380] [VERBOSE-2:dart_vm.cc(245)] Could not setup VM data to bootstrap the VM from.
> 2019-11-25 20:08:08.362183+0100 Runner[732:33380] [VERBOSE-2:dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
> 2019-11-25 20:08:08.362871+0100 Runner[732:33380] [VERBOSE-3:shell.cc(212)] Check failed: vm. Must be able to initialize the VM.
> ```
> 
> The upgrade command produced, eventually:
> 
> ```
> Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 68587a0916 (2 months ago) • 2019-09-13 19:46:58 -0700
> Engine • revision b863200c37
> Tools • Dart 2.5.0
> ```
> 
> Output from Flutter Doctor:
> 
> ```
> 👻 20:05:46 zmeggyesi@ShinyPlatform:[~/projects/site-overwatch/frontend]:
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-GB)
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
>       You may also want to add it to your PATH environment variable.
> 
>  
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
> [!] Android Studio (not installed)
> [!] VS Code
>     ✗ Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 3 categories.
> ```

 Your issue is with an iPhone so I'm hesitant to suggest that your issue is the same as mine

**Comment by zmeggyesi** [comment]
Thought I could very well be wrong, going by the Dart VM error, I have a feeling they stem from the same root.

**Comment by singun-lxd** [comment]
@jmagman @chinmaygarde @matthew-carroll 

Same problem for me. I've published a new version of my app, suddenly a large percentage of crashes occurred(about 3.6%, last version is about 2‰). The difference between these two versions is that we added a lot of code to add ads(Google AdMob, Facebook Audince Network), resulting in an extra dex, and we need to add multi-dex support. Then it crashed. Before we add ads, this crash also occurred, only about 0.1‰.

The top crash devices is **NOT** Xiaomi Devices:
Huawei MYA L22 34.34%
OPPO CPH 1609 14.83%
OPPO CPH1701 11.90%
HUAWEI CAM L21 8.62%
HIAWEI KII-L21 4.42%

## StackTrace ##
```
#00 0x00000000000695f4 /system/lib64/libc.so (tgkill+8) [arm64-v8a]
#01 0x0000000000066d84 /system/lib64/libc.so (pthread_kill+68) [arm64-v8a]
#02 0x0000000000023878 /system/lib64/libc.so (raise+28) [arm64-v8a]
#03 0x000000000001e018 /system/lib64/libc.so (abort+60) [arm64-v8a]
#04 0x00000000002af058 /data/app/com.alhiwar-2/lib/arm64/libflutter.so [arm64-v8a]
fml::LogMessage::~LogMessage()
/b/s/w/ir/cache/builder/src/out/android_release_arm64/../../flutter/fml/logging.cc:92:5
#05 0x00000000002e0484 /data/app/com.alhiwar-2/lib/arm64/libflutter.so [arm64-v8a]
flutter::Shell::Create(flutter::TaskRunners, flutter::WindowData, flutter::Settings, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)>, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)>)
/b/s/w/ir/cache/builder/src/out/android_release_arm64/../../flutter/shell/common/shell.cc:268:3
#06 0x00000000002a4040 /data/app/com.alhiwar-2/lib/arm64/libflutter.so [arm64-v8a]
flutter::AndroidShellHolder::AndroidShellHolder(flutter::Settings, fml::jni::JavaObjectWeakGlobalRef, bool)
/b/s/w/ir/cache/builder/src/out/android_release_arm64/../../flutter/shell/platform/android/android_shell_holder.cc:111:7
std::__1::__unique_if<flutter::AndroidShellHolder>::__unique_single std::__1::make_unique<flutter::AndroidShellHolder, flutter::Settings const&, fml::jni::JavaObjectWeakGlobalRef&, unsigned char&>(flutter::Settings const&, fml::jni::JavaObjectWeakGlobalRef&, unsigned char&)
/b/s/w/ir/cache/builder/src/out/android_release_arm64/../../third_party/libcxx/include/memory:3003:0
flutter::AttachJNI(_JNIEnv*, _jclass*, _jobject*, unsigned char)
/b/s/w/ir/cache/builder/src/out/android_release_arm64/../../flutter/shell/platform/android/platform_view_android_jni.cc:153:0
#07 0x0000000001f0c500 /data/app/com.alhiwar-2/oat/arm64/base.odex (oatexec+17057024) [arm64-v8a]
```

## LogCat ##
```
06-30 16:39:40.474 18682 18682 E flutter : [ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
06-30 16:39:40.474 18682 18682 E flutter : [ERROR:flutter/runtime/dart_vm.cc(248)] Could not setup VM data to bootstrap the VM from.
06-30 16:39:40.474 18682 18682 E flutter : [ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
06-30 16:39:40.474 18682 18682 F flutter : [FATAL:flutter/shell/common/shell.cc(268)] Check failed: vm. Must be able to initialize the VM.
```

I tried the solution below, the crashes no longer happens

```
Warning: Recently, the Flutter team has received several reports from developers indicating they are experiencing app crashes on certain devices on Android 6.0. If you are targeting Android 6.0, use the following steps:

If you build an App Bundle Edit android/gradle.properties and add the flag: android.bundle.enableUncompressedNativeLibs=false.

If you build an APK Make sure android/app/src/AndroidManifest.xml doesn’t set android:extractNativeLibs=false in the <application> tag.

For more information, see the public issue.
```

I think this crash may **NOT** be a system problem of Xiaomi.

**Comment by darshankawar** [comment]
@lawonga 
Are you still facing this issue using latest Flutter version ?
If so, can you provide a minimal complete reproducible code sample that we can use to replicate it ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
