### ISSUE TITLE
[google_maps_flutter] getLatLng returns different results on iOS/Android

### ISSUE THREAD

**Issue by ivanryndyuk** [flutter/flutter#41653]
## Issue Description
Method `Future<LatLng> getLatLng(ScreenCoordinate screenCoordinate)` returns different results for the same `ScreenCoordinate` on iOS and Android.

## Steps to Reproduce
1. Add `GoogleMap` widget filling entire device screen.
2. Set `initialCameraPosition.target` to (lat; lng) coordinates.
3. Retrieve `GoogleMapController` in `onMapCreated` handler.
4. In `onCameraIdle` handler get center of current context and call `getLatLng()` on `GoogleMapController`

In the end you would expect latitude and longitude retrieved in step 4 to be equal to those set in step 2. This works as expected on iOS. But that's not the case for Android where you get the result with a weird offset:
iOS: https://drive.google.com/open?id=1MsxHHb59K2NqgKB3P17LVOk3ulHzANSE
Android: https://drive.google.com/open?id=1aYOuuSUqIkcFdV6WyN_6SDIEJPpSPWO9

## Workaround
As you can see in attached project I've found a workaround. I believe the problem is in different implementations of GMSProjection and Projection classes for iOS and Android. google_maps_flutter plugin uses these methods:
in iOS `(CLLocationCoordinate2D) coordinateForPoint:  (CGPoint)  point`:
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_projection.html#a4e912bf5b8778dec702e025ea2036d49
in Android `public LatLng fromScreenLocation (Point point)`:  https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/Projection.html#public-latlng-fromscreenlocation-point-point
The iOS method uses CGPoint that is relative to map view, and Android method takes actual screen location (screen pixels) which depend on device pixel density. So, the workaround is to use context width and height multiplied by `MediaQuery.of(context).devicePixelRatio` for Android and normal width and height for iOS.
```dart
final devicePixelRatio = Platform.isAndroid
   ? MediaQuery.of(context).devicePixelRatio
   : 1.0;

_latLng = await _mapController.getLatLng(
   // Center of a full screen GoogleMap widget.
   ScreenCoordinate(
      x: (context.size.width * devicePixelRatio) ~/ 2.0,
      y: (context.size.height * devicePixelRatio) ~/ 2.0,
   ),
);
```
Here is a sample project to view and play with the issue:
https://github.com/ivanryndyuk/google_maps_flutter_issue

## So, what's the point?
First of all, thank you all in Flutter team, Google and who help to develop and improve Flutter and additional plugins. You're doing a great job! 
It would be really nice to synchronize behavior of `getLatLng` method on both platforms, so that it would either use actual screen pixels or coordinates relative to widget. That would make life of many devs much more easier!

**Comment by AlexanderArendar** [comment]
The same is actual for the reverse method `GoogleMapController.getScreenCoordinate()`.
Would be great to have this bug fixed to make the API coherent.

**Comment by ianyon** [comment]
I think that the problem is that the Android API uses physical screen pixels, and the iOS API uses Points (Like DIP pixels), so as the `getLatLng` documentation states to use physical screen pixels, the workaround you proposed for Android is the correct way to use the method in both platforms and a fix is needed in iOS to conform to this specification. 

If this is true a change is needed [here](https://github.com/flutter/plugins/blob/af7f798ad79a1afbb6806050b6c200b11e6c1316/packages/google_maps_flutter/ios/Classes/GoogleMapController.m#L162) to fix this converting from real pixels to DIP for the iOS API.

**Comment by fluttercorner** [comment]
[How to Get Device Lat Long in Flutter](https://fluttercorner.com/how-to-get-device-lat-long-in-flutter/)

**Comment by Kurogoma4D** [comment]
> I think that the problem is that the Android API uses physical screen pixels, and the iOS API uses Points (Like DIP pixels),

I think so too, and I confirmed `GoogleMapController.getScreenCoordinate()` returns different result between iOS and Android, as mentioned above.
IMO this problem is same, so it should be fixed at same time.

**Comment by TahaTesser** [comment]
Hi @ivanryndyuk  @Kurogoma4D 
I am trying to reproduce the issue, I've updated the code sample to be able to run on the latest `google_maps_flutter: ^2.0.3`

I see the same result on both platforms when moving the camera (unlike this [screenshot ](https://github.com/ivanryndyuk/google_maps_flutter_issue/blob/master/screenshots/Android.png))


Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  Map<MarkerId, Marker> markers =
      <MarkerId, Marker>{}; // CLASS MEMBER, MAP OF MARKS

  @override
  Widget build(BuildContext context) {
    final devicePixelRatio =
        Platform.isAndroid ? MediaQuery.of(context).devicePixelRatio : 1.0;

    return new Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            mapType: MapType.hybrid,
            initialCameraPosition: _kGooglePlex,
            onMapCreated: (GoogleMapController controller) {
              _controller.complete(controller);
            },
            markers: Set<Marker>.of(markers.values),
            onTap: (latlng) async {
              final GoogleMapController controller = await _controller.future;
              var result = await controller.getScreenCoordinate(latlng);

              print(result);
            },
            onCameraIdle: () async {
              final GoogleMapController controller = await _controller.future;
              await controller
                  .getLatLng(ScreenCoordinate(
                x: (MediaQuery.of(context).size.width * devicePixelRatio) ~/
                    2.0,
                y: (MediaQuery.of(context).size.height * devicePixelRatio) ~/
                    2.0,
              ))
                  .then((coordinates) {
                var markerId = MarkerId('centerMarker');

                print(coordinates);

                setState(() {
                  // adding a new marker to map
                  markers[markerId] =
                      Marker(markerId: markerId, position: coordinates);
                });
              });
            },
          ),
          Center(
            child: Container(
              width: 40.0,
              height: 40.0,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(20.0),
                border: Border.all(
                  color: Colors.red,
                  width: 2.0,
                ),
              ),
              child: Center(
                child: Container(
                  width: 6.0,
                  height: 6.0,
                  decoration: BoxDecoration(
                    color: Colors.red,
                    borderRadius: BorderRadius.circular(3.0),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

``` 

</details>


Reproduced on the following channel
|  `stable` |
| :---: 
|  ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0
[✓] Connected device (3 available)
    • Taha's iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.5.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.212
• No issues found!
```
		
</details>

**Comment by TahaTesser** [comment]
Hi @ivanryndyuk

The issue didn't reproduce, if you've more details let us know thanks

**Comment by tirtha-o** [comment]
This issue is still not fixed, seriously I wasted my entire day figuring out this issue and fortunately, I found this. I kindly request the google team to fix this issue.

**Comment by Lapshin** [comment]
Hi @tirtha-o , I believe the issue will be fixed with https://github.com/flutter/plugins/pull/2225.
Without the changes we need to have a workaround, what I did for my project are:

```dart
class _MyHomePageState extends State<MyHomePage> {
  late final devicePixelRatio;

  @override
  void initState() {
    Future.delayed(Duration.zero,()
    {
      devicePixelRatio = Platform.isAndroid ? MediaQuery.of(context).devicePixelRatio : 1.0;
    });
    super.initState();
  }
}
```

After that, you can use getLatLng() like this:

```dart
ScreenCoordinate screenCoordinate = ScreenCoordinate(x: x * devicePixelRatio, y: y * devicePixelRatio);  // magic is here

final GoogleMapController controller = await _controller.future;
LatLng latLng = await controller.getLatLng(screenCoordinate);
```

This is a simplified answer from @TahaTesser, many thanks to him!
