### ISSUE TITLE
Flutter app flashes when backgrounded and brought into foreground from SIRI search screen

### ISSUE THREAD

**Issue by therealjohnsummer** [flutter/flutter#41679]
Issue originally mentioned here : https://github.com/flutter/flutter/issues/7246

This problem has resurfaced on ALL iOS devices. This only happens on Flutter built apps on iOS. Other apps on iOS do not exhibit the issue. I have also upgraded to iOS 13.1.2. Tested on physical devices - iPhone 7 Plus, iPhone X, iPhone 11 Pro Max, iPhone SE, iPad Pro.

To reproduce :

1. Deploy an app to a live device
2. Run the app
3. Put the app to the background
4. Swipe down on the device to show SIRI Suggestions/search.
5. Select your app that you backgrounded
6. Repeat steps 3,4,5 and you will see a horrible flash when the app is brought back to foreground.

Only seems to happen when app is brought back from SIRI/Search screen.

You will need to repeat steps 3,4,5 a few times to see this. On iPhone 11 pro max it is reproducible instantly. Have tested with Reflectly and we see this behaviour. Also the standard counter app.

Attached screencast shows the flash. Happens at 6, 8 and 10secs.
[flicker1.mp4.zip](https://github.com/flutter/flutter/files/3675585/flicker1.mp4.zip)

**Comment by escamoteur** [comment]
Does this only happen on physical devices?

Please paste the output of `flutter doctor -v` here

**Comment by therealjohnsummer** [comment]
I've seen also on simulators but its more reproducible on live devices. Flutter output is not necessary since you can take any flutter built app from the appStore (hence used Reflectly) and see the problem , however , here is my environment : 



```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/johnsummer/workspace/sdk/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/johnsummer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1
 
```

**Comment by sroddy** [comment]
The one in the video this looks like a completely different flash w.r.t. the original issue. As some of the elements keep their position and some other are resizing/repositioning for one single frame, it looks like there is a moment in which some Metrics are reported wrong, affecting the behaviour of dynamic elements.

**Comment by escamoteur** [comment]
@sroddy can you reproduce this?

**Comment by MsXam** [comment]
I have the same issue - can reproduce with apps I deploy to a live device. I also downloaded and installed Reflectly on a brand new phone with no previous Flutter apps installed and can reproduce whats in the video.

**Comment by bpaul7101** [comment]
Im using  iOS 13.x as just upgraded. This looks really bad when I bring my apps from background to foreground. I can confirm this has nothing to do with the version of Flutter i'm using - I have also deployed via xCode with the same issue. Furthermore - since everyone seems to be using Reflectly to verify the issue - I can confirm the latest version of Reflectly exhibits the same issue. The other thing I notice that hasnt been specified is that there is a black border on the ICON when you swipe the flutter app down to background it. This happens 100% of the time. The black border is only at the bottom of the ICON and approx 5 % of the sides.

**Comment by agreensh** [comment]
Also seen horrible flashes on iOS 13.1.1 and 13.1.2, iPhone X, but with a different scenario.

Any flutter app loaded from the AppStore (or installed locally), running in the foreground.
Pull down from the top of the screen to show the lock screen. Nasty flash(es) 3 out of 4 times.
But it only happens if the lock screen background is set to a photo. Doesn't happen for any non-flutter apps.

**Comment by therealjohnsummer** [comment]
@sroddy any update to this , is there anything you need to help you reproduce ?

**Comment by ssbaval** [comment]
Get this also. Any flutter app running on iOS 13.x - flashes when backgrounded and brought to foreground from SIRI search menu. Looks terrible.

**Comment by therealjohnsummer** [comment]
This is a show stopper for me and appears that no effort been placed on this for 2 months despite adequate reproducible steps being given (Just create the standard counter app and follow the steps mentioned to reproduce)  - unfortunately , Flutter seemed promising at first but its not mature enough for production ready apps - sadly, because of this issue  I will have to drop Flutter and move over to Xamarin

**Comment by MsXam** [comment]
I agree with @therealjohnsummer - This issue is severe but yet there has been little or no movement on this or other similar connected issues - Can one conclude that this has therefore been swept under the carpet until more from the flutter community notice and react ?

**Comment by jamesblasco** [comment]
I think the real problem of this is https://github.com/flutter/flutter/issues/43804
This problem occurs whenever the keyboard is raised in other apps and return to the app

**Comment by Hixie** [comment]
cc @jmagman any chance you can take a look at this? It seems to affect a lot of people.

**Comment by jmagman** [comment]
I can try to instrument it, but @gaaclarke would probably have more insight.

**Comment by Hixie** [comment]
@gaaclarke Any chance you can look at this? :-)

**Comment by MsXam** [comment]
This can easily be reproduced by just having the on screen keyboard open (Scroll down from a live device)   then just switch to an iOS app built with Flutter. The flutter app displays and then you see that the bottom half of the Flutter up moves to the middle of the screen and then back down again. Suggestions of not setting resizeToAvoidBottomInset=false within a Scaffold do not solve the issue.

The issue appears to have surfaced after 1.78 HF 4 and iOS 13. Any Flutter app - standard Counter app, will exhibit the issue.

**Comment by gaaclarke** [comment]
I responded to this issue many moons ago [[link]](https://github.com/flutter/flutter/issues/7246#issuecomment-537140638).

This appears to be a problem with the logic driving animations.  If you hook up an animation (like the rotation of the sun graphic) to the realtime clock, when you leave the app and come back you will get a skip in the animation since time progressed while you weren't rendering.

This is the reason that Unity3D has `Time.time` and `Time.realtimeSinceStartup` and you are suppose to tie your logic to `Time.time`.

Can you provide a minimal reproduction example.  Depending on how you are animating I can fix it from our end or point you in the right direction on how to do it correctly.

**Comment by gaaclarke** [comment]
I've been able to reproduce the flicker on the counter app, thanks to those that pointed out it can be reproduced there.

![ezgif-5-b153f2fbf66e](https://user-images.githubusercontent.com/30870216/73408261-8a49ef80-42b0-11ea-9f91-746ba441638c.gif)

**Comment by gaaclarke** [comment]
I've played with this a bit more.  It seems like having the keyboard visible before switching the app is key.  Since the incorrectly drawn frame is offset roughly the amount the UI would be offset if the keyboard was shown; that is suspicious.

I placed print statements in Window.updateWindowMetrics and got the following output.  It looks like there are a few instances where `viewInsetBottom = 432.0` which seems to match the visual glitch.

output:
```
2020-01-29 16:35:09.652703-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 0.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
2020-01-29 16:35:09.653328-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 0.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
2020-01-29 16:35:09.695941-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 0.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
2020-01-29 16:35:09.696795-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 0.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
2020-01-29 16:35:09.697259-0800 Runner[11176:3667221] Can't end BackgroundTask: no background task exists with identifier 31 (0x1f), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
2020-01-29 16:35:12.461935-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 432.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
2020-01-29 16:35:12.947956-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 432.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
2020-01-29 16:35:12.949079-0800 Runner[11176:3667344] flutter: _updateWindowMetrics:
  devicePixelRatio: 2.0
  width: 750.0
  height: 1334.0
  depth: 1.7976931348623157e+308
  viewPaddingTop: 40.0
  viewPaddingRight: 0.0
  viewPaddingBottom: 0.0
  viewPaddingLeft: 0.0
  viewInsetTop: 0.0
  viewInsetRight: 0.0
  viewInsetBottom: 0.0
  viewInsetLeft: 0.0
  systemGestureInsetTop: 0.0
  systemGestureInsetRight: 0.0
  systemGestureInsetBottom: 0.0
  systemGestureInsetLeft : 0.0
```

The print code:
```diff
diff --git a/lib/ui/hooks.dart b/lib/ui/hooks.dart
index 7972efc9f..960ecc75c 100644
--- a/lib/ui/hooks.dart
+++ b/lib/ui/hooks.dart
@@ -36,6 +36,24 @@ void _updateWindowMetrics(
   double systemGestureInsetBottom,
   double systemGestureInsetLeft,
 ) {
+  print('''_updateWindowMetrics:
+  devicePixelRatio: $devicePixelRatio
+  width: $width
+  height: $height
+  depth: $depth
+  viewPaddingTop: $viewPaddingTop
+  viewPaddingRight: $viewPaddingRight
+  viewPaddingBottom: $viewPaddingBottom
+  viewPaddingLeft: $viewPaddingLeft
+  viewInsetTop: $viewInsetTop
+  viewInsetRight: $viewInsetRight
+  viewInsetBottom: $viewInsetBottom
+  viewInsetLeft: $viewInsetLeft
+  systemGestureInsetTop: $systemGestureInsetTop
+  systemGestureInsetRight: $systemGestureInsetRight
+  systemGestureInsetBottom: $systemGestureInsetBottom
+  systemGestureInsetLeft : $systemGestureInsetLeft 
+  ''');
   window
     .._devicePixelRatio = devicePixelRatio
     .._physicalSize = Size(width, height)
```

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/blob/6061b804e3590457a09476757ab21fce75c131ea/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L820

Here is where the problem is happening.  When the keyboard is open outside of the app then we switch back to flutter, the iOS operating system fires UIKeyboardWillChangeFrameNotification to the Flutter app with the keyboard up, then quickly sends another with it gone.  Not what I would have expected either.  I'll see if I can come up with a way to suppress that.

**Comment by MsXam** [comment]
@gaaclarke - Yes , issue is only when the OSK is present and we switch back to a Flutter app. This only surfaced with iOS 13.  Would be simply awesome if we can get this resolved soon !!

**Comment by gaaclarke** [comment]
Fixed in https://github.com/flutter/engine/pull/16270

**Comment by athornz** [comment]
I'm running an app from the latest Flutter dev branch and still seeing this issue.
