### ISSUE TITLE
Bad code formatting in codelab doc

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#4215]
The last code snippet (`main.dart`) of https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#10 is

```dart
// Add the following code to the ChatScreenState class definition.

@override
void dispose() {
  for (ChatMessage message in _messages)
    message.animationController.dispose();
    super.dispose();
}
```

but should be :

```dart
// Add the following code to the ChatScreenState class definition.

@override
void dispose() {
  for (ChatMessage message in _messages)
    message.animationController.dispose();
  super.dispose();
}
```

**Comment by sethladd** [comment]
cc @collinjackson 

I think we'd take a pull request for this one :)

**Comment by a14n** [comment]
Where is the codelab repo ? I haven't found it.

**Comment by collinjackson** [comment]
https://github.com/flutter/firechat-flutter

**Comment by collinjackson** [comment]
It looks like the repo's fine, it's just the codelab instructions that need fixing. @qchong

**Comment by a14n** [comment]
I was talking about the repo that contain codelab instructions ;)

**Comment by collinjackson** [comment]
yeah, the codelab instructions aren't in github. thanks for filing an issue, we'll get it fixed.

**Comment by qchong** [comment]
Fixed in the doc source. The refreshed codelab instructions are [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#10).

**Comment by a14n** [comment]
I still see the indent issue on https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#10

**Comment by qchong** [comment]
Sorry, I sent out the comment too soon before the republish operation completed. The correctly indent code should show up now in the codelab.
