### ISSUE TITLE
Toolbar should use outermost Overlay

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#42774]
Using Flutter stable version 1.9.1, the text selection toolbar is broken whenever a nested Overlay exists in the widget tree.

The following assert fires from box.dart:
```
Size get size {
    assert(hasSize, 'RenderBox was not laid out: ${toString()}');
    assert(() {
      if (_size is _DebugSize) {
        final _DebugSize _size = this._size;
        assert(_size._owner == this);
        if (RenderObject.debugActiveLayout != null) {
          // We are always allowed to access our own size (for print debugging
          // and asserts if nothing else). Other than us, the only object that's
          // allowed to read our size is our parent, if they've said they will.
          // If you hit this assert trying to access a child's size, pass
          // "parentUsesSize: true" to that child's layout().
          assert(debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent));
        }
        assert(_size == this._size);
      }
      return true;
    }());
    return _size;
  }
```

The issue is that the iOS toolbar tries to get global coordinates during the layout phase, and as it goes up the tree, this assert fires once the first RenderBox is found.

I am pasting 2 patches below that fixes the issue, but I'm not sure if this would be the ultimate fix. It seems to me that having a nested overlay should work, seeing a nested navigator is something that is used readily, right?

**Comment by dannyvalentesonos** [comment]
cupertino/text_selection.dart patch
```
--- a/packages/flutter/lib/src/cupertino/text_selection.dart	2019-09-22 10:17:46.000000000 -0400
+++ b/packages/flutter/lib/src/cupertino/text_selection.dart	2019-10-09 09:58:27.000000000 -0400
@@ -79,7 +79,7 @@
   final bool _isArrowPointingDown;
 
   @override
-  _ToolbarRenderBox createRenderObject(BuildContext context) => _ToolbarRenderBox(_barTopY, _arrowTipX, _isArrowPointingDown, null);
+  _ToolbarRenderBox createRenderObject(BuildContext context) => _ToolbarRenderBox(_barTopY, _arrowTipX, _isArrowPointingDown, Overlay.of(context)?.context?.findRenderObject(), null);
 
   @override
   void updateRenderObject(BuildContext context, _ToolbarRenderBox renderObject) {
@@ -104,6 +104,7 @@
     this._barTopY,
     this._arrowTipX,
     this._isArrowPointingDown,
+    this._overlay,
     RenderBox child,
   ) : super(child);
 
@@ -141,6 +142,16 @@
     markNeedsSemanticsUpdate();
   }
 
+  RenderObject _overlay;
+  set overlay(RenderObject value) {
+    if (_overlay == value) {
+      return;
+    }
+    _overlay = value;
+    markNeedsLayout();
+    markNeedsSemanticsUpdate();
+  }
+
   final BoxConstraints heightConstraint = const BoxConstraints.tightFor(height: _kToolbarHeight);
 
   @override
@@ -164,7 +175,7 @@
     child.layout(heightConstraint.enforce(enforcedConstraint), parentUsesSize: true,);
     final _ToolbarParentData childParentData = child.parentData;
 
-    final Offset localTopCenter = globalToLocal(Offset(_arrowTipX, _barTopY));
+    final Offset localTopCenter = globalToLocal(Offset(_arrowTipX, _barTopY), ancestor: _overlay);
 
     // The local x-coordinate of the center of the toolbar.
     final double lowerBound = child.size.width/2 + _kToolbarScreenPadding;

```

**Comment by dannyvalentesonos** [comment]
text_selection.dart patch
```
--- a/packages/flutter/lib/src/widgets/text_selection.dart	2019-09-22 10:17:46.000000000 -0400
+++ b/packages/flutter/lib/src/widgets/text_selection.dart	2019-10-09 10:14:13.000000000 -0400
@@ -283,12 +283,12 @@
        assert(handlesVisible != null),
        _handlesVisible = handlesVisible,
        _value = value {
-    final OverlayState overlay = Overlay.of(context);
-    assert(overlay != null,
+    _overlay = Overlay.of(context, debugRequiredFor: debugRequiredFor);
+    assert(_overlay != null,
       'No Overlay widget exists above $context.\n'
       'Usually the Navigator created by WidgetsApp provides the overlay. Perhaps your '
       'app content was created above the Navigator with the WidgetsApp builder parameter.');
-    _toolbarController = AnimationController(duration: fadeDuration, vsync: overlay);
+    _toolbarController = AnimationController(duration: fadeDuration, vsync: _overlay);
   }
 
   /// The context in which the selection handles should appear.
@@ -361,6 +361,9 @@
 
   TextEditingValue _value;
 
+  /// The Overlay on which the toolbar and handles will be displayed
+  OverlayState _overlay;
+
   /// A pair of handles. If this is non-null, there are always 2, though the
   /// second is hidden when the selection is collapsed.
   List<OverlayEntry> _handles;
@@ -410,7 +413,7 @@
 
 
 
-    Overlay.of(context, debugRequiredFor: debugRequiredFor).insertAll(_handles);
+    _overlay.insertAll(_handles);
   }
 
   /// Destroys the handles by removing them from overlay.
@@ -426,7 +429,7 @@
   void showToolbar() {
     assert(_toolbar == null);
     _toolbar = OverlayEntry(builder: _buildToolbar);
-    Overlay.of(context, debugRequiredFor: debugRequiredFor).insert(_toolbar);
+    _overlay.insert(_toolbar);
     _toolbarController.forward(from: 0.0);
   }
 
@@ -528,8 +531,8 @@
         renderObject.getEndpointsForSelection(_selection);
 
     final Rect editingRegion = Rect.fromPoints(
-      renderObject.localToGlobal(Offset.zero),
-      renderObject.localToGlobal(renderObject.size.bottomRight(Offset.zero)),
+      renderObject.localToGlobal(Offset.zero, ancestor: _overlay.context?.findRenderObject()),
+      renderObject.localToGlobal(renderObject.size.bottomRight(Offset.zero), ancestor: _overlay.context?.findRenderObject()),
     );
 
     final bool isMultiline = endpoints.last.point.dy - endpoints.first.point.dy >

```

**Comment by LongCatIsLooong** [comment]
The exception should be fixed on master already, in this PR: https://github.com/flutter/flutter/pull/41326. It turned out the `localToGlobal` call wasn't needed at all as the menu was wrapped in a `CompositedTransformFollower`.

**Comment by dannyvalentesonos** [comment]
Thanks @LongCatIsLooong . I'll have to undo my patches and see if that patch actually works with a nested overlay.

**Comment by dannyvalentesonos** [comment]
I tried the PR, and it seems to work at first. But unfortunately, after playing with it a little, it causes all pointers to be ignored. I assume something gets put outer most overlay that absorbs the pointers.

**Comment by LongCatIsLooong** [comment]
That sounds really bad. Could you update this issue or create a new issue to include the steps/code that used to reproduce it?

**Comment by dannyvalentesonos** [comment]
ok, I've found that the nested Overlay is not the issue.
The stable version 1.9.1 has a bug in that just selecting text in a TextField and tapping on Cut or Copy from the toolbar causes everything to freeze.
The test I'm running is using the Add2App API (not sure if that matters).

The page is simply:
```
return Scaffold(
        body: Container(
            color: Colors.grey,
            child: Column(
              children: <Widget>[
                Expanded(child: Container()),
                TextField(

                ),
                Expanded(child: Container())
              ],
            )
        )
    );
```

**Comment by LongCatIsLooong** [comment]
@justinmc said he tried the above code on iOS simulator but couldn't reproduce the bug. We're wondering if you specified any parameter for the `TextField`?

**Comment by dannyvalentesonos** [comment]
That code above is what I used to repro this 100% of the time. I also ran it on an iOS simulator iPhone 6 running ios12.
I do normally pass parameters to the `TextField` but the above code as is also reproduces it. I don't know if it's specific to running in an Existing App setting though.

**Comment by dannyvalentesonos** [comment]
@LongCatIsLooong @justinmc I too cannot reproduce it in a simple flutter app.

**Comment by dannyvalentesonos** [comment]
@LongCatIsLooong Ok, I can no longer reproduce it now. I was applying the patch for the assert that you pointed me to by saving the flutter dart file directly and hot reloading, which normally works pretty well, but something must have really gotten into a bad state. After actually building my app completely, I no longer see this problem.

I can say that the original issue is fixed with the patch you pointed me to as well.

Thanks!

**Comment by justinmc** [comment]
I'm going to close this since it seems fixed now, but if you see the bug again please reopen!

**Comment by dannyvalentesonos** [comment]
@justinmc I can still reproduce this reliably (all touches being ignored after cutting the selection).

The following code, running on a flutter host app on an iPhone 6 running ios 12 reproduces this 100% of the time.

```
import 'package:flutter/material.dart';

class TextSelectionHomePage extends StatefulWidget {
  _TextSelectionHomePageSate createState() => _TextSelectionHomePageSate();
}

class _TextSelectionHomePageSate extends State<TextSelectionHomePage> {

  TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController(
      text: "This is a test that shows some odd behavior with Text Selection!"
    );

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    Overlay overlay = Overlay(
      initialEntries: [
        OverlayEntry(
          builder: (context) => Center(
              child: TextField(controller: _controller),
          )
        )
      ],
    );

    return Scaffold(
        body: Container(
          color: Colors.grey,
          child: Center(
              child: Container(
                  color: Colors.red,
                  width: 300,
                  height: 600,
                  child: overlay
              )
          ),
        )
    );
  }
}
```

Selecting the text "test" and hitting Cut reproduces it.

Can we reopen this bug please?

**Comment by dannyvalentesonos** [comment]
```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.14 at /Users/danny.valente/Library/flutter/1.10.14-dev
    • Framework revision 1946fc4da0 (3 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by justinmc** [comment]
I was able to reproduce this in the iOS simulator on master.  So any part of the selection menu that is outside of the Overlay is not interactive:

![overlay](https://user-images.githubusercontent.com/389558/68055146-5f0e2f00-fcc6-11e9-86e9-fdf9285aa1ca.gif)

**Comment by dannyvalentesonos** [comment]
@justinmc I have opened a separate bug for the tap detection and alignment issues which we are getting a PR ready for.
I asked for this bug to be reopened because it seems like the entire app freezes for me on iOS with this code.

**Comment by dannyvalentesonos** [comment]
#43787 is the bug I logged, which we have a PR coming.

**Comment by justinmc** [comment]
Oh hmm, I didn't get any freezing.  Well let's keep this open for now and see what happens after the PR is merged.

**Comment by Hixie** [comment]
@dannyvalentesonos Should I assign this to you?

**Comment by dannyvalentesonos** [comment]
Unfortunately, for this one, I wouldn't even know where to begin to figure out why it's freezing.

**Comment by Hixie** [comment]
Looking at the more recent descriptions, it sounds like the problem is that the toolbar is going outside its overlay, in which case the hit testing is _expected_ not to work, since the hits would only get to the toolbar if they're first inside the overlay. 

Seems like we probably just want to always use the outermost overlay ("rootmost" maybe) when displaying a toolbar?

**Comment by dannyvalentesonos** [comment]
@Hixie Thanks for the response. However, in my opinion, that is the wrong approach. There are actual applications where that just looks very bad. The solution I've proposed in #44018 works really well and looks really nice and expected.

Also, using the outermost overlay is not just going to fix all problems. See this bug I also logged #44005. If the screen is too small, the toolbar still gets cut off. That should be handled with an appropriate overflow menu.

So that, coupled with the actual fix I'm proposing for this works really nicely, and I think is exactly what developers would expect. I think we should rename this bug back to what it was.

Thoughts?
Thanks!

**Comment by dannyvalentesonos** [comment]
This bug I think should be closed, as I'm the only one that can reproduce the freezing. To be clear, it's not a HitTest problem. Nothing in the app works after I get the freezing. Even touches on the keyboard don't work. The entire app is frozen. But seeing I'm the only one that reproduces it, I would suggest it gets closed. The actual real problems are being tracked in #43787 and #44005.

Thanks

**Comment by Hixie** [comment]
Ok, I'll close this one. #44005 is definitely a bug, our fidelity is way off on these toolbars. #43787 sounds like what I thoughts this bug was, the nested overlay thing. I'll comment there.
