### ISSUE TITLE
Catalina - "idevice_id" can't be verified by default

### ISSUE THREAD

**Issue by lucasjohnston** [flutter/flutter#42969]
## Steps to Reproduce

1. Going through the macOS install tutorial for Flutter (https://flutter.dev/docs/get-started/install/macos), step-by-step, on a brand new MacBook running 10.15.
2. Any time a `flutter` command is called (eg. `flutter doctor` or `flutter create`), the following warning appears:
<img width="532" alt="Screenshot 2019-10-17 at 23 05 55" src="https://user-images.githubusercontent.com/24899791/67052129-25b9b900-f135-11e9-9fa4-39d5bceea97e.png">

## Logs

The process hangs until I acknowledge the window by clicking "Cancel", but the verbose logs don't actually show anything.
For example, for flutter doctor logs:

**Comment by lucasjohnston** [comment]
🛠 A quick fix around this is `sudo xattr -d com.apple.quarantine /YOUR_FLUTTER_PATH/bin/cache/artifacts/libimobiledevice/idevice_id`, but this really should work out the box :)

**Comment by lucasjohnston** [comment]
Update: it seems this is the case with more than just the `idevice_id` binary. Just had the same thing when trying to use a physical device - this time it's `ideviceinfo` that's playing up

**Comment by christopherfujino** [comment]
This is very strange. Can you run `codesign -vvv YOUR_FLUTTER_PATH/bin/cache/artifacts/libimobiledevice/idevice_id` for me and verify that it's signed?

**Comment by scruzlara** [comment]
I'm having the same problem as Lucas.

Christopher, I ran:

> This is very strange. Can you run `codesign -vvv YOUR_FLUTTER_PATH/bin/cache/artifacts/libimobiledevice/idevice_id` for me and verify that it's signed?

I obtained:

idevice_id: satisfies its Designated Requirement

So, it seems it is well signed.

**Comment by shijinliang** [comment]
I download zip from https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.5-stable.zip, idevice_id is error when i run 'flutter doctor'.

I use 'git clone https://github.com/flutter/flutter.git', and run 'flutter doctor'. It's work.

**Comment by scruzlara** [comment]
Thx for the fix. It works.

**Comment by sanchitrk** [comment]
I also got the same issue when I ran flutter doctor, I resolved it in **System Preferences** > **Security & Privacy** set to allow _device_id_

**Comment by lucasjohnston** [comment]
Apologies I've been inactive recently - @christopherfujino as said above, the binaries return signed:
```
/usr/local/flutter/bin/cache/artifacts/libimobiledevice/idevice_id: valid on disk

/usr/local/flutter/bin/cache/artifacts/libimobiledevice/idevice_id: satisfies its Designated Requirement
```
Same with other binaries like `ideviceinfo` which produce the same issue.

To be explicit for anyone reading this, the workarounds here are either:
1. Cloning from the git repo as @shijinliang mentioned
2. Resolving the issue by manually overriding macOS's block on the binary, which you can do by removing the attribute as I mentioned earlier ^ or by using the GUI as per @sanchitrk's instructions (which is far less overkill 😅)

**Comment by gdbjohnson** [comment]
Catalina's default security measures is infuriating.  Nothing is allowed now.

**Comment by jmagman** [comment]
I'm still seeing LUCI artifacts in these files.  When I try to launch:
```
com.apple.securityd	default	19:29:52.700660 -0800	trustd	asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (syspolicyd[138]/0#-1 LF=0)
com.apple.securityd	default	19:29:52.701453 -0800	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (syspolicyd[138]/0#-1 LF=0)
com.apple.securityd	default	19:29:52.706941 -0800	trustd	OCSPResponse: single response has extension(s).
com.apple.securityd	default	19:29:52.708504 -0800	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (syspolicyd[138]/0#-1 LF=0)
com.apple.securityd	default	19:29:52.708563 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
com.apple.securityd	default	19:29:52.713226 -0800	syspolicyd	MacOS error: -67002
com.apple.securityd	default	19:29:52.716382 -0800	syspolicyd	rule 11 applies - allow=1
com.apple.securityd	default	19:29:52.721247 -0800	trustd	OCSPResponse: single response has extension(s).
com.apple.securityd	default	19:29:52.723370 -0800	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (syspolicyd[138]/0#-1 LF=0)
com.apple.securityd	default	19:29:52.723437 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
com.apple.xprotect	default	19:29:52.729082 -0800	XprotectService	File /Users/m/Downloads/flutter/bin/cache/artifacts/libimobiledevice/idevice_id failed on loadCmd /b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-398c120_3/lib/libimobiledevice.6.dylib
```

That last line is `File /Users/m/Downloads/flutter/bin/cache/artifacts/libimobiledevice/idevice_id failed on loadCmd /b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-398c120_3/lib/libimobiledevice.6.dylib`

And the binary itself is loading dylibs from bogus LUCI paths like `/b/s/w/ir/k/homebrew/Cellar/`
```
otool -l flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo
...
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 128
         name /b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-398c120_3/lib/libimobiledevice.6.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 7.0.0
compatibility version 7.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /b/s/w/ir/k/homebrew/opt/openssl/lib/libssl.1.0.0.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /b/s/w/ir/k/homebrew/opt/openssl/lib/libcrypto.1.0.0.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1.0.0
compatibility version 1.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /b/s/w/ir/k/homebrew/opt/usbmuxd-flutter/lib/libusbmuxd.4.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 6.0.0
compatibility version 6.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist.3.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 5.0.0
compatibility version 5.0.0

```

So why is it working from git?

Even if that gets fixed...
https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG207
> If an app uses @rpath or an absolute path to link to a dynamic library outside of the app, the app will be rejected by Gatekeeper. This restriction applies to the app’s main executable and any other executable in the bundle, including libraries. This restriction applies even if the path does not exist (and normally causes the dynamic linker to fall back to a library inside the bundle).

**absolute path to link to a dynamic library outside of the app**

> This means that MyApp.app links against /foo/libLibrary.dylib. /foo is not a standard location for libraries on macOS, so the linkage isn’t allowed.

Solutions:
1. Publish the entire thing as a signed dmg where everything is loaded within the disk image or some bundle.
1. "Absolute path" seems critical.  Can we make those paths relative? They obviously ain't doin' anything on anyone's real machines now, and the tool is setting DYLD_LIBRARY_PATHs seemingly correctly?

In any case, if you context-click on any binary and open from the menu, you will get an Open button (you don't need to go through System Preferences).

**Comment by jmagman** [comment]
> So why is it working from git?

Oh right, quarantine.

https://stackoverflow.com/questions/37791355/gatekeeper-quarantine-issue-with-certificate/37800961#37800961
> But not all network download methods will apply the quarantine attribute. For example, copying a file over a file sharing connection (e.g. AFP or SMB) with the Finder will not mark it as being in quarantine. Also, command-line tools like curl and wget won't apply quarantine.

```
$ xattr ~/Downloads/flutter/bin/cache/artifacts/libimobiledevice/idevice_id 
com.apple.quarantine
```

**Comment by dpst99** [comment]
Here is simplest solution 
re enter flutter doctor command in terminal
then go to System preference-> Security & Privacy -> click allow 

then re enter flutter doctor command terminal this it ask for open instead to delete 
Click open & now you are good to go

**Comment by mdalameen** [comment]
Delete /flutter/bin/cache/artifacts directory and run flutter doctor in terminal

**Comment by AbdulelahZh** [comment]
The only solution that worked for me was @mdalameen's!
Thank you!

Next time I'll think twice before upgrading my macOS, so infuriating!

**Comment by engineerbaraazakariya** [comment]
Just go to this path: /your_flutter_directory/bin/cache/artifacts then right click on "idevice_id" and choose open, then click on Open, and run flutter doctor in terminal no errors will show and it will work well.

**Comment by MakingHistoryAgain** [comment]
This website will help: https://medium.com/@alexandrosbaramilis/setting-up-flutter-on-macos-catalina-d023df8845ae

Briefly:
For "idevice_id" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
For "ideviceinfo" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo
For "idevicesyslog" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog
For "iproxy" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/usbmuxd/iproxy

**Comment by edco29** [comment]
>@mdalameen comment worked for me

**Comment by jmagman** [comment]
`idevice_id` is gone as of https://github.com/flutter/flutter/pull/49854, which is in v1.15.2.  However, this is still an issue for `idevicescreenshot` and ``idevicesyslog` artifacts.

**Comment by jmagman** [comment]
I also see LUCI paths for `iproxy` `libusbmuxd` `ideviceinstaller`, and other artifacts.

**Comment by christopherfujino** [comment]
@jmagman once https://github.com/flutter/flutter/pull/50772 lands, we won't have to worry about `ideviceinstaller`.

**Comment by jmagman** [comment]
> @jmagman once #50772 lands, we won't have to worry about `ideviceinstaller`.

Oh right, I got it and `ios-deploy` mixed up.  I don't see any LUCI paths in `ios-deploy`.

**Comment by zanderso** [comment]
@christopherfujino @jmagman What is the work left to do on this issue? Is this related to https://github.com/flutter/flutter/issues/50299 ?

**Comment by jmagman** [comment]
Not sure static linking `--disable-shared` will work per https://github.com/libimobiledevice/usbmuxd/issues/47#issuecomment-602952316, though it's worth trying.

**Comment by Dev-SK** [comment]
Refer to this: 
https://www.macworld.co.uk/how-to/mac-software/mac-app-unidentified-developer-3669596/#:~:text=Open%20System%20Preferences.,developers'%20from%20just%20App%20Store.

**Comment by eahumada** [comment]
> This website will help: https://medium.com/@alexandrosbaramilis/setting-up-flutter-on-macos-catalina-d023df8845ae
> ...

Works for me.

**Comment by JamesVanWaza** [comment]
SOLUTION: Go to System Preferences -> Select Security and Privacy -> General under ** Allow apps downloaded from ** change it to ** App Store and identified developers ** then click the lock to make changes, then run `flutter doctor` it should work.

**Comment by keithshep** [comment]
I was having this issue with multiple executables. I just ran a recursive `sudo xattr -d -r com.apple.quarantine PATH/TO/FLUTTER` on the flutter directory and the problem went away.

**Comment by EternalYouth29** [comment]
In my case : Go to `System Preference -> Security and Privacy -> General` , right below the `App Store and identified developers` will have a same alert message as this topic ('iproxy' cannot be opened because the developer cannot be verified), click on `Allow Anyway` solved the problem.

**Comment by skbellevue** [comment]
I had the same issue.

- Run 'flutter upgrade'
- Run your project again. The same issue is likely to pop up
- In the dialog box, click 'Move to Bin'
- Exit your IDE
- Run 'flutter doctor'
- Open your IDE and run your project

It should just work!

**Comment by sunny-mittal** [comment]
For anyone else running into this, @skbellevue's answer worked without running all the terminal commands mentioned previously (which failed for me anyway cause the paths cited didn't exist). Sounds like the issue is you just need to delete the idevice_id file, which the dialog will do for you if you let it, and then let `flutter doctor` bring it back signed.

**Comment by burcus** [comment]
I tried numerous solutions for this and now @mdalameen's solution worked for me.

**Comment by jmagman** [comment]
If you are hitting this on versions 2.0.3 to 2.0.5 then likely you hit https://github.com/flutter/flutter/issues/81326, which has been resolved in 2.0.6.

**Comment by mtmk** [comment]
This fixed it for me on Flutter 2.5.1:
```
sudo xattr -d com.apple.quarantine /path/to/flutter/bin/cache/artifacts/usbmuxd/iproxy
```

**Comment by Jesus2312** [comment]
> In my case : Go to `System Preference -> Security and Privacy -> General` , right below the `App Store and identified developers` will have a same alert message as this topic ('iproxy' cannot be opened because the developer cannot be verified), click on `Allow Anyway` solved the problem.

This solved my problem on flutter 2.5.1 Thank you

**Comment by jmagman** [comment]
I think editing the `LC_LOAD_DYLIB` via `install_name_tool` would work.  I grabbed the absolute paths from `otool -L iproxy` and swapped them for paths relative to `@loader_path` (path to the executable):
```
install_name_tool -change "/b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist-2.0.3.dylib" "@loader_path/../libplist/libplist-2.0.3.dylib" iproxy
install_name_tool -change "/b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib" "@loader_path/../libusbmuxd-2.0.6.dylib" iproxy
```
I tried this locally, and re-codesigned.  I could then run `iproxy` without the pop up, and without setting `DYLD_LIBRARY_PATH`. 

Something like the above commands, and the same for `idevicescreenshot` and `idevicesyslog`, could be run right after [`InstallHomebrew`](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/ios-usb-dependencies.py#173).

In a run like https://ci.chromium.org/p/flutter/builders/prod/libimobiledevice/18 it would be after `11 installing libimobiledevice-flutter`

**Comment by jmagman** [comment]
I don't see a nicer machine output format for `otool`, so we'll have to regex it.  
### iproxy
Here's what the `iproxy` output looks like:
```
$ otool -L iproxy
iproxy:
	/b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```
```
install_name_tool -change "/b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib" "@loader_path/../libusbmuxd-2.0.6.dylib" iproxy
install_name_tool -change "/b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist-2.0.3.dylib" "@loader_path/../libplist/libplist-2.0.3.dylib" iproxy
```
Regex of path parsed from `otool`:
`\S.*libusbmuxd.*dylib` -> `@loader_path/../libusbmuxd-2.0.6.dylib`
`\S.*libplist.*dylib` -> `@loader_path/../libplist/libplist-2.0.3.dylib`

The names of the dylibs are already hardcoded in the recipe: [in `INSTALL_PKGS`](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/ios-usb-dependencies.py#30).

### idevicescreenshot and idevicesyslog
`idevicescreenshot` and `idevicesyslog` are the same.

```
$ otool -L idevicescreenshot
idevicescreenshot:
	/b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-2ba8188_3/lib/libimobiledevice-1.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/b/s/w/ir/k/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/b/s/w/ir/k/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/b/s/w/ir/k/homebrew/opt/usbmuxd-flutter/lib/libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.
```

```
install_name_tool -change /b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-2ba8188_3/lib/libimobiledevice-1.0.6.dylib "@loader_path/../libimobiledevice-1.0.6.dylib" idevicescreenshot
install_name_tool -change /b/s/w/ir/k/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib "@loader_path/../openssl/libssl.1.1.dylib" idevicescreenshot
install_name_tool -change /b/s/w/ir/k/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib  "@loader_path/../openssl/libcrypto.1.1.dylib" idevicescreenshot
install_name_tool -change /b/s/w/ir/k/homebrew/opt/usbmuxd-flutter/lib/libusbmuxd-2.0.6.dylib  "@loader_path/../usbmuxd/libusbmuxd-2.0.6.dylib" idevicescreenshot
install_name_tool -change /b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist-2.0.3.dylib "@loader_path/../libplist/libplist-2.0.3.dylib" idevicescreenshot
```

`\S.*libimobiledevice.*dylib` -> `@loader_path/../libimobiledevice-1.0.6.dylib`
`\S.*libssl.*dylib` -> `@loader_path/../openssl/libssl.1.1.dylib`
`\S.*libcrypto.*dylib` -> `@loader_path/../openssl/libcrypto.1.1.dylib`
`\S.*libusbmuxd.*dylib` -> `@loader_path/../usbmuxd/libusbmuxd-2.0.6.dylib`
`\S.*libplist.*dylib` -> `@loader_path/../libplist/libplist-2.0.3.dylib`

### libssl.1.1.dylib
`libssl` also links against `libcrypto` so it needs to be updated as well:
```
$ otool -L libssl.1.1.dylib
libssl.1.1.dylib:
	/b/s/w/ir/k/homebrew/opt/openssl-flutter/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/b/s/w/ir/k/homebrew/Cellar/openssl-flutter/HEAD-e2e09d9/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```
```
install_name_tool -change /b/s/w/ir/k/homebrew/Cellar/openssl-flutter/HEAD-e2e09d9/lib/libcrypto.1.1.dylib "@loader_path/libcrypto.1.1.dylib" libssl.1.1.dylib
```
`\S.*libcrypto.*dylib` -> `@loader_path/libcrypto.1.1.dylib`

**Comment by eli-front** [comment]
GUI Fix. Go into finder and locate your flutter sdk. Search for the `iproxy` executable. Right click and choose open. Try building again.

**Comment by christopherfujino** [comment]
> Hey @christopherfujino, wary it's been 2 years since I first opened this issue. Any update?

I have plans to get this finished this quarter. I've been busy though, I would happily review PRs :)

**Comment by nerdybunz** [comment]
@mdalameen comment worked for me

**Comment by quetool** [comment]
This is still an issue, I solved it with
```
sudo xattr -d com.apple.quarantine /YOUR_FLUTTER_PATH/bin/cache/artifacts/usbmuxd/iproxy
```

**Comment by jmagman** [comment]
Adding `team: infra`, the `install_name_tool` change https://github.com/flutter/flutter/issues/42969#issuecomment-933725997 is in in [the recipe](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/ios-usb-dependencies.py).

**Comment by christopherfujino** [comment]
I will not be able to fix this until January because of the infra code freeze (and my being on vacation).

Some notes for my future self:
 - the ios-usb-dependencies.py recipes needs to be updated to depend on `flutter/osx_sdk`
 - in the builder config, the recipe will have to enable the experimental luciexe runner, like: https://cs.opensource.google/flutter/infra/+/main:config/lib/recipes.star;l=17
 
 WIP recipe CL: https://flutter-review.googlesource.com/c/recipes/+/24460

**Comment by lukepighetti** [comment]
I'm having this with a fresh install with `brew install flutter` and a fresh install of macOS 12.1 (21C52)

**Comment by elemen3** [comment]
For Flutter 2.10.0

```
sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/usbmuxd/iproxy
sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/idevicescreenshot
sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/idevicesyslog
sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/ios-deploy/ios-deploy
```

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by hanifmhd** [comment]
You can press "cancel" first. Then on your mac open "System Preferences" -> "Security & Privacy" -> in "General tab" click "open anyway" to allow

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by christopherfujino** [comment]
I haven't been able to get to this, but I believe it is unblocked now that we've published a new CIPD package for the latest Xcode version.

I have work in progress CL's for:

 - recipes https://flutter-review.googlesource.com/c/recipes/+/24460
 - infra https://flutter-review.googlesource.com/c/infra/+/26000
 
 The recipes change depends on the infra change.

**Comment by tomyjwu** [comment]
tried on the new flutter 3 and still encounter this. need to manually allow it from apple warning dialog (GUI way or system preference way mentioned above).

**Comment by godofredoc** [comment]
@christopherfujino @keyonghan can we close this one once the changes for the new artifacts is complete?

**Comment by jmagman** [comment]
Yes, but they have not yet been published.  We still need to roll to a new version, validate, and codesign. I will close when it's done!

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by jmagman** [comment]
Even with the `LC_LOAD_DYLIB` remapped I'm still seeing that the developer cannot be verified.  If anyone wants to try, draft is at https://github.com/flutter/flutter/pull/115052

```
$ otool -L  ~/Projects/flutter/bin/cache/artifacts/libusbmuxd/iproxy
/Users/m/Projects/flutter/bin/cache/artifacts/libusbmuxd/iproxy:
	@loader_path/../libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libimobiledevice-glue-1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	@loader_path/../libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
```
which looks very similar to the loader paths in the binaries that are working, like `idevicescreenshot`:
```
$ otool -L ~/Projects/flutter/bin/cache/artifacts//libimobiledevice/idevicescreenshot
/Users/m/Projects/flutter/bin/cache/artifacts//libimobiledevice/idevicescreenshot:
	@loader_path/../libimobiledevice-1.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libimobiledevice-glue-1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	@loader_path/../libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	@loader_path/../libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1235.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1945.0.0)
```

The logging isn't complaining about the load paths anymore, it seems to be mad about the cert? But the cert looks fine to me, and the other artifacts built with the same cert in that PR are working, and it's notarized...

```
default	18:48:02.911086-0800	trustd	trustd	policy	com.apple.securityd	cert[0]: MissingIntermediate =(leaf)[force]> 0
default	18:48:02.911154-0800	trustd	trustd	policy	com.apple.securityd	cert[0]: SignatureHashAlgorithms =(path)[]> 0
default	18:48:02.911207-0800	trustd	trustd	policy	com.apple.securityd	cert[0]: OtherTrustValidityPeriod =(path)[]> 0
default	18:48:02.911226-0800	trustd	trustd	policy	com.apple.securityd	cert[0]: NonEmptySubject =(path)[]> 0
default	18:48:02.911334-0800	trustd	trustd	policy	com.apple.securityd	cert[0]: ServerAuthEKU =(path)[]> 0
...
default	18:48:03.674298-0800	syspolicyd	syspolicyd	default	com.apple.syspolicy.exec	GK evaluateScanResult: 1, PST: (path: /Users/m/Projects/flutter/bin/cache/artifacts/libusbmuxd/iproxy), (team: S8QB4VV633), (id: (null)), (bundle_id: (null)), 1, 0, 1, 0, 4, 4, 5
...
default	18:48:03.677757-0800	syspolicyd	syspolicyd	default	com.apple.syspolicy.exec	Prompt shown (8, 0), waiting for response: PST: (path: /Users/m/Projects/flutter/bin/cache/artifacts/libusbmuxd/iproxy), (team: S8QB4VV633), (id: (null)), (bundle_id: (null))
```

**Comment by jmagman** [comment]
Actually that `trustd` cert logging is a red herring, my machine is spewing that constantly, unrelated to running iproxy.

**Comment by jmagman** [comment]
> Though `bin/cache/artifacts/libimobiledevice/idevicesyslog` is exhibiting the same GK failure, but `idevicescreenshot` isn't...

Now when I try `idevicescreenshot` is too, and it's actually complaining about the relative path being incorrect:
```
dyld[89533]: Library not loaded: '@loader_path/../libimobiledevice-1.0.6.dylib'
  Referenced from: '/Users/m/Projects/flutter/bin/cache/artifacts/libimobiledevice/idevicescreenshot'
  Reason: tried: '/Users/m/Projects/flutter/bin/cache/artifacts/libimobiledevice/../libimobiledevice-1.0.6.dylib' (no such file), '/usr/lib/libimobiledevice-1.0.6.dylib' (no such file)
zsh: abort      ./libimobiledevice/idevicescreenshot
```
maybe I hadn't emptied the stale artifacts from my cache...?

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by tanis2000** [comment]
@jmagman this issue still holds true after all this time. 
In my case I can still see this error:

```
dyld[94147]: Library not loaded: /b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib
  Referenced from: <6D9DC549-703F-3A3D-8BB8-DD1A59F40A13> /opt/homebrew/Caskroom/flutter/3.0.5/flutter/bin/cache/artifacts/usbmuxd/iproxy
  Reason: tried: '/opt/homebrew/opt/openssl/lib/libusbmuxd-2.0.6.dylib' (no such file), '/libusbmuxd-2.0.6.dylib' (no such file), '/b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib' (no such file), '/b/s/w/ir/k/homebrew/Cellar/usbmuxd-flutter/HEAD-c7d7d1a_1/lib/libusbmuxd-2.0.6.dylib' (no such file), '/usr/lib/libusbmuxd-2.0.6.dylib' (no such file, not in dyld cache)
[1]    94147 abort
```

Is there anything experimental to try out to get this working again?

**Comment by vashworth** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/169863.

**Comment by ALI-BABAI** [comment]
i have same problem when i tried to debug on iphone 15 device.

first i caught these:
_Xcode build done.                                           48.6s
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode._

later i caught:
_Failed to find "/{user}/flutter/bin/cache/artifacts/usbmuxd/iproxy" in the search path.
Error launching application on iPhone._

Flutter 3.32.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6fba2447e9 (4 weeks ago) • 2025-06-12 19:03:56 -0700
Engine • revision 8cd19e509d (4 weeks ago) • 2025-06-12 16:30:12 -0700
Tools • Dart 3.8.1 • DevTools 2.45.1

I fixed it with doing next steps:

0. On macos toggle on setting switcher:
Settings -> Privacy & Security -> automation -> visual studio : toggle on switcher



<img width="705" height="226" alt="Image" src="https://github.com/user-attachments/assets/a2ea3074-d9ef-4334-915a-f337fdc1d687" />

1. Disconnect phone from PC
2. Remove trusted computers on iphone device (settings / developers)
3. on macOs terminal enter command:
`rm -r ~/Library/Developer/Xcode/iOS\ DeviceSupport`
4. on flutter project terminal execute these command:
```
flutter clean         
flutter pub get
cd ios
pod deintegrate
pod cache clean --all
rm -rf Pods
rm -rf Podfile.lock
pod install
```
5. and also execute in flutter project terminal this:
```
flutter % cd ~/flutter/bin/cache
rm -rf *
cd ~/flutter
flutter doctor
flutter precache --ios
```
6. open ur flutter project ios folder via xcode
7. pair device with pc via cable:
trust to computer and select your device on xcode

<img width="719" height="308" alt="Image" src="https://github.com/user-attachments/assets/d22584a9-df05-4b14-a3af-d3a3e5f9c50d" />

8. close xcode, reconnect device, open vsc, select ur device to debugging, start debugging, give access to find devices on local networcs

in my case these steps was solves problem and now i can debug project in vsc on real devices
