### ISSUE TITLE
 Hot reload fails after restarting app with Android back button, again

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#43164]
## Steps to Reproduce

Run a Flutter app in debug mode on Android. Press the back button to dismiss the app, then use the task swticher to swtich back to the app. Then do a hot reload.

```
Performing hot reload...
Syncing files to device LGM G600L...
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
```

**Android 9**
**LG G6**

## Logs

```
D:\dev\pavement>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.1006], locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at C:\tools\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code, 32-bit edition (version 1.37.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • LGM G600L • LGMG600Lf8469764 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
This was fixed by https://github.com/flutter/flutter/commit/315471bfb0d9accb026e8e138e26b2b4c9a632ba

**Comment by tapizquent** [comment]
This was not fixed. Still getting the same error with v1.17.0

**Comment by k4utech** [comment]
+1, i am also getting this.

**Comment by ollydixon** [comment]
Still not fixed. Making developing on the device extremely slow.
