### ISSUE TITLE
[google_sign_in] Google sign in crashes on iOS -[NSNull stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by subramanyamgv** [flutter/flutter#44564]
google_sign_in 4.0.11 plugin crashes on the IOS device with the exception, but it works OK on the simulator.

`PlatformException(google_sign_in, -[NSNull stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x38bb1978, NSInvalidArgumentException)`

Example:

```
final GoogleSignIn _googleSignIn = GoogleSignIn();
final googleUser = await _googleSignIn.signIn();  //Crashing here
```

**Comment by iapicca** [comment]
Hi @subramanyamgv 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by talent-apps** [comment]
Temp workaround:
Downgrading to `google_sign_in: 4.0.7` solves this crash.

**Comment by subramanyamgv** [comment]
@iapicca Please find the attached files as requested.

[Uploading flutter.run.verbose.txt…]()
[Uploading flutter.doctor.v.txt…]()

**Comment by subramanyamgv** [comment]
@iapicca Please find the attached files as requested.
[flutter.run.verbose.txt](https://github.com/flutter/flutter/files/3831536/flutter.run.verbose.txt)
[flutter.doctor.v.txt](https://github.com/flutter/flutter/files/3831537/flutter.doctor.v.txt)

**Comment by iapicca** [comment]
Hi @subramanyamgv 
I don't see any `google_sign_in `error in your logs,
you mentioned an error before, could you post the output?

```
final GoogleSignIn _googleSignIn = GoogleSignIn();
final googleUser = await _googleSignIn.signIn();  //Crashing here
```
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jmagman** [comment]
```
[+3682 ms] flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[        ] flutter: \^[[38;5;12m│ #0   Log.info (package:an_app/utils/log.dart:12:1<…>
[        ] flutter: \^[[38;5;12m│ #1   LogInBloc.mapEventToState (package:an_app/components/login/login_bloc.dart:48:1<…>
[   +2 ms] flutter: \^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
[        ] flutter: \^[[38;5;12m│ 💡 Google signin step1<…>
[   +3 ms] flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[ +217 ms] flutter: PlatformException(google_sign_in, -[NSNull stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x3b195978, NSInvalidArgumentException)
```
Unfortunately there's no callstack there.  Maybe `+[GTMOAuth2KeychainCompatibility encodedOAuthValueForString:]` is getting passed NSNull?  Or some OID token encoding?

Can we get the device crash log?  Reproduce the crash, and find the right crash log through the date and time at:
Xcode > Window > Devices and Simulators > your device > View Device Logs

**Comment by subramanyamgv** [comment]
[device.log](https://github.com/flutter/flutter/files/3843273/device.log)

Sample code that generate crash:
`final GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: ['email'],
);
final googleUser = await _googleSignIn.signIn();
        final googleAuth = await googleUser.authentication;
        final AuthCredential credential = GoogleAuthProvider.getCredential(
          accessToken: googleAuth.accessToken,
          idToken: googleAuth.idToken,
        );
        user =
            (await FirebaseAuth.instance.signInWithCredential(credential)).user;
`

**Comment by jmagman** [comment]
```
2   CoreFoundation                	0x1d9c0fcc -[NSObject+ 1048524 (NSObject) doesNotRecognizeSelector:] + 117
3   CoreFoundation                	0x1d9bf0be ___forwarding___ + 691
4   CoreFoundation                	0x1d8e7dc4 _CF_forwarding_prep_0 + 19
5   Foundation                    	0x1e31ef6c -[__NSConcreteURLComponents setQueryItems:] + 511
```
NSURLComponents queryItems are being set to NSNull.

\cc @collinjackson @cyanglaz

**Comment by subramanyamgv** [comment]
> Temp workaround:
> Downgrading to `google_sign_in: 4.0.7` solves this crash.

Didn't solve the issue.

**Comment by bayuramadeza** [comment]
yeah, i got this error crash after login or close signin webview 

> 0
Runner
GoogleSignInPlugin.m - Line 190
-[FLTGoogleSignInPlugin respondWithAccount:error:] + 190
1 Runner GoogleSignInPlugin.m - Line 161
-[FLTGoogleSignInPlugin signIn:didSignInForUser:withError:] + 161
2 Runner __37-[GIDSignIn addCallDelegateCallback:]_block_invoke + 116
3 Runner -[GIDCallbackQueue fire] + 148
4 Runner -[GIDCallbackQueue addCallback:] + 112
5 Runner -[GIDSignIn addCallDelegateCallback:] + 136
6 Runner __50-[GIDSignIn authenticateInteractivelyWithOptions:]_block_invoke + 864
7 AppAuth -[OIDAuthorizationSession didFinishWithResponse:error:] + 108
26 UIKitCore UIApplicationMain + 1936
27 Runner AppDelegate.swift - Line 6
main + 6

I got this error message from crashlytic

**Comment by iamgoddog** [comment]
I am running into this problem also it seems. Both on simulator and real device.

Crash happens at same spot as @subramanyamgv points out.

By debugging I was able to determine that last point in google_sign_in is in MethodChannelGoogleSignIn line 43:

``` 
  @override
  Future<GoogleSignInUserData> signIn() {
    return channel
        .invokeMapMethod<String, dynamic>('signIn') // here
        .then(getUserDataFromMap);
  }
```

but the app crashes while in `_DefaultBinaryMessenger._sendPlatformMessage()`.

Running the simulator produces this error in logs:
```
	[C1.1 8B05F11B-CD18-4A14-A057-EEFD1E49F8E8 192.168.1.33:64945<->216.58.204.78:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.238s, DNS @0.003s took 0.003s, TCP @0.008s took 0.042s, TLS took 0.093s
	bytes in/out: 4274/1042, packets in/out: 8/9, rtt: 0.040s, retransmitted packets: 0, out-of-order packets: 0
	[C2.1 667A5290-309D-47B6-ACE4-79BC806E75EE 192.168.1.33:64949<->216.58.204.78:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.163s, DNS @0.001s took 0.004s, TCP @0.007s took 0.042s, TLS took 0.063s
	bytes in/out: 4227/1439, packets in/out: 8/10, rtt: 0.040s, retransmitted packets: 0, out-of-order packets: 0
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23baa02c +[NSException raise:format:] + 188
	3   Runner                              0x000000010840ed75 -[GIDSignIn signInWithOptions:] + 276
	4   Runner                              0x000000010840e6aa -[GIDSignIn signIn] + 64
	5   Runner                              0x000000010843461a -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2410
	6   Flutter                             0x0000000109f5d4fd __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	7   Flutter                             0x0000000109ef6ec0 _ZNK7flut<…>
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"131","method":"resume","params":{"isolateId":"isolates/1065575175508039"}}
Failed to send request: {"jsonrpc":"2.0","id":"132","method":"getStack","params":{"isolateId":"isolates/1065575175508039"}}
Failed to send request: {"jsonrpc":"2.0","id":"133","method":"getObject","params":{"isolateId":"isolates/1065575175508039","objectId":"classes/1341"}}
```

Flutter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-IS)
    • Flutter version 1.9.1+hotfix.6 at ~/frameworks/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at ~/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro • 3422FA09-62AC-4365-87C6-3392439755D4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

! Doctor found issues in 2 categories.
```

And relevant part of pubspec.yaml:
```
environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: any
  provider: ^3.1.0+1
  shared_preferences:
  logger: ^0.7.0+2
  firebase_auth: ^0.14.0+9
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.8
  google_sign_in: ^4.0.7
  video_player: 0.10.2+5
  chewie_audio: 1.0.0+1
  cached_network_image: ^1.1.3
  flutter_bloc: ^2.0.0
  equatable: ^0.6.1
  meta: ^1.1.7
  font_awesome_flutter: ^8.5.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  uuid: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
```

**Comment by rodineijf** [comment]
<img width="698" alt="Screen Shot 2019-11-19 at 18 13 59" src="https://user-images.githubusercontent.com/24531420/69187382-42ad2780-0af9-11ea-9cff-c7842ff30852.png">

**Comment by marinat** [comment]
Same error only on simulator

**Comment by collinjackson** [comment]
It sounds like @iamgoddog has a solution of updating GoogleService-Info.plist. Can you tell us what was different about the old plist versus the new one?

If this is actually the issue, we might be able to detect that the GoogleService-Info.plist is out of date and provide a more useful error message.

**Comment by dalebulmer** [comment]
Same error. GoogleSrvice-Info.plist is updated, didn't help.

**Comment by iamgoddog** [comment]
@collinjackson I mistakenly said "up to date", it was actually just a wrong GoogleService-Info.plist file, with out of date information. I'll fix my previous update.

**Comment by ControlAdad** [comment]
I still have this crash, GoogleService-Info.plist is latest and downgrading to 4.0.7 doesn't help!

**Comment by cyanglaz** [comment]
@subramanyamgv I couldn't reproduce the crash using your code. Could you provide a complete reproducible test case? For example, a simple main.dart code that I can copy and paste to run?

**Comment by ControlAdad** [comment]
@cyanglaz 
There is a funny thing, I am using flutter_downloader too.
If I remove this line from main.dart, google_sign_in works and there is no crash:

await FlutterDownloader.initialize();

Any explanation?

**Comment by rodineijf** [comment]
@ControlAdad I'm using FlutterDownloader too, and removing the initialize
method made googleSignIn work again.

**Comment by collinjackson** [comment]
Removed the regression label because downgrading didn't resolve the crash.

**Comment by JCKodel** [comment]
Was working on High Sierra, but new Flutter requires new XCode (that requires new MacOS, that requires new hardware).

Now it doesn't work anymore...

Sick tired of Flutter.

**Comment by mingwugmail** [comment]
downgrade google_sign_in to 4.0.7, working now. 

(was from google_sign_in 4.0.14, and IOS Simulator on iPhone 5s.)

https://github.com/flutter/flutter/issues/46532

**Comment by JCKodel** [comment]
High  Sierra + 4.0.7 = Ok
Mojave + 4.0.7 = Bug. 4.0.14 = Bug. 4.0.0 = Ok

As my build takes forever, I'm too lazy to test 4.0.1 though 4.0.6

**Comment by collinjackson** [comment]
@JCKodel is `FlutterDownloader` required to reproduce the error or are you seeing it with just google_sign_in?

**Comment by rodineijf** [comment]
This error only occurs with FlutterDownloader here

**Comment by ezmegy** [comment]
I just saw this in my Crashlytics creeping in on:
- an iphone 6 with iOS 9
- google_sign_in plugin v4.0.6
- WITHOUT FlutterDownloader plugin
- flutter Channel stable, v1.9.1+hotfix.6, Xcode 11.2.1

(- And I couldn't reproduce it with an iPhone 11 , iOS 13 Simulator.)

**Comment by zigapk** [comment]
Same issue here, but only on 32-bit iPhone 5c, simulator and 64-bit iPhones work fine.

**Comment by jiverson** [comment]
I was having the same issue as @mingwugmail per https://github.com/flutter/flutter/issues/46532. The issue is that https://github.com/openid/AppAuth-iOS, which GoogleSignIn uses, updated to 1.3.0. That version added in support for Mac Catalyst which will only work with XCode 11+ afaik. So if you are like me, I am building on XCode 10+.

The work around is to downgrade AppAuth to version 1.2.0.

1. Add AppAuth to `ios/Podfile` after Plugin Pods
    - `pod 'AppAuth', '1.2.0'`
2. Then run:
    - `pod update GoogleSignIn`
3. Finally you may or may not need to update the config files:
	[Using Cocoapods libraries in Flutter iOS platform specific code](https://stackoverflow.com/questions/53630136/using-cocoapods-libraries-in-flutter-ios-platform-specific-code)

**Comment by timsneath** [comment]
Thanks for the workaround, @jiverson! 

Closing this issue with this workaround; please reopen if you're still experiencing the problem.

**Comment by martyfuhry** [comment]
I still get this error on my iPhone 5 (iOS 10.3.3), and none of the workarounds fix it for this device.

Downgrading to `google_sign_in: 4.0.7` did not solve it for me, redownloading my GoogleService-Info.plist did not help. 

`-[NSNull stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x390a5978
2020-01-07 13:19:22.241084-0500 Runner[346:24285] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x390a5978'`

**Comment by buuth** [comment]
All that manipulation with downgrading are wrong. You can keep all packages up-to-date. Problem is some genius developer forgot to check null before accessing variables, so you must use
GoogleSignIn googleSignIn = GoogleSignIn(
scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly'],
hostedDomain: "",
clientId: "",);
instead of
GoogleSignIn googleSignIn = GoogleSignIn(
scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly']);
each will lead to crash.
I lost one day of my life due to this silly bug. Hope you all doing better.

**Comment by jmagman** [comment]
@buuth re: "some genius developer" Please check out Flutter's [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) which requires actively pleasant behavior.

I'm going to hide your comment and re-open this issue based on what you've discovered.

**Comment by jmagman** [comment]
@buuth says the issue is a missing null check.

> so you must use
> 
> ```
> GoogleSignIn googleSignIn = GoogleSignIn(
> scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly'],
> hostedDomain: "",
> clientId: "",);
> ```
> 
> instead of
> 
> ```
> GoogleSignIn googleSignIn = GoogleSignIn(
> scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly']);
> ```
> 
> each will lead to crash.

Reopening.

**Comment by buuth** [comment]
> @buuth re: "some genius developer" Please check out Flutter's [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) which requires actively pleasant behavior.
> 
> I'm going to hide your comment and re-open this issue based on what you've discovered.
Thank you very much. That's my fault, I've edited my comment.

**Comment by hnvn** [comment]
Hey guys, I am the author of the FlutterDownloader plugin. I have tried to investigate this issue. Here's the solution to this issue in case of using along with FlutterDownloader:
In your `AppDelegate.m`, `registerPlugins` function, replace following snip codes:
```objc
[GeneratedPluginRegistrant registerWithRegistry:registry];
```
by:
```objc
 if (![registry hasPlugin:@"FlutterDownloaderPlugin"]) {
     [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterDownloaderPlugin"]];
 }
```
(It's Objective-C codes, you can find the Swift version in [README](https://github.com/fluttercommunity/flutter_downloader/blob/master/README.md) document. I already mentioned the reason in that document.)

**Comment by MattePalte** [comment]
I solved the problem by updating all the libraries to their last version and following the official guidelines in the official page https://pub.dev/packages/google_sign_in .
version 4.1.1
Namely, I did this:
1. First register your application.
1. Make sure the file you download in step 1 is named GoogleService-Info.plist.
1. Move or copy GoogleService-Info.plist into the [my_project]/ios/Runner directory.
1. Open Xcode, then right-click on Runner directory and select Add Files to "Runner".
1. Select GoogleService-Info.plist from the file manager.
1. A dialog will show up and ask you to select the targets, select the Runner target.

Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.
```
<!-- Put me in the [my_project]/ios/Runner/Info.plist file -->
<!-- Google Sign-in Section -->
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<!-- TODO Replace this value: -->
			<!-- Copied from GoogleService-Info.plist key REVERSED_CLIENT_ID -->
			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
		</array>
	</dict>
</array>
<!-- End of the Google Sign-in Section -->
```

**Comment by karmazinkd** [comment]
As of now, the current version of [google_sign_in](https://pub.dev/packages/google_sign_in) is 4.1.1 and this error still occurs.

I don't use FlutterDownloader and the downgrade to 4.0.7 doesn't work for me.

**But I can confirm that the answer by @buuth works!**

p.s. for those who want to use Google Sign-In just to ease log in process for their users, you probably would need just these two scopes: 'email' and 'profile'. More details [here](https://developers.google.com/identity/protocols/googlescopes)

**Comment by rafael-trevisan** [comment]
I confirm this solved my problem with `google_sign_in: ^4.1.4`

No need to downgrade or specify the scopes. The only that was missing on my case was adding the `CFBundleURLTypes` in `Info.plist`

Thanks @MattePalte 

> I solved the problem by updating all the libraries to their last version and following the official guidelines in the official page https://pub.dev/packages/google_sign_in .
> version 4.1.1
> Namely, I did this:
> 
> 1. First register your application.
> 2. Make sure the file you download in step 1 is named GoogleService-Info.plist.
> 3. Move or copy GoogleService-Info.plist into the [my_project]/ios/Runner directory.
> 4. Open Xcode, then right-click on Runner directory and select Add Files to "Runner".
> 5. Select GoogleService-Info.plist from the file manager.
> 6. A dialog will show up and ask you to select the targets, select the Runner target.
> 
> Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.
> 
> ```
> 
> 
> <key>CFBundleURLTypes</key>
> <array>
> 	<dict>
> 		<key>CFBundleTypeRole</key>
> 		<string>Editor</string>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			
> 			
> 			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
> 		</array>
> 	</dict>
> </array>
> 
> ```

**Comment by JigarKotak7** [comment]
Guy if anyone is still having a problem then try to make sure that REVERSED_CLIENT_ID from google-info.plist is copied in URL_scheme. Also if you are using both FB sign in & google sign in then which everyone you setup later will overnight the url scheme for the previous one and you will have to go in Xcode project settings / info and add 2nd URL scheme. 

Jigar Kotak

**Comment by magax** [comment]
Problem solved for me. I forgot to add these lines in the Info.plist file.

`

<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			
			
			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
		</array>
	</dict>
</array>
`

Don't forget to change `<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>` and add instead your `REVERSED_CLIENT_ID` that you'll find in the `GoogleService-Info.plist` file.

Cheers!

**Comment by talent-apps** [comment]
The crash still happens with `google_sign_in: 4.4.1` **on iOS 9 & 10 devices**.
```
final GoogleSignIn _googleSignIn = GoogleSignIn();
final googleUser = await _googleSignIn.signIn();  //Crashing here
```
When explicitly setting the `hostName`
```
final GoogleSignIn _googleSignIn = GoogleSignIn(hostName = "");
final googleUser = await _googleSignIn.signIn();
```
The crash is resolved on iOS 9 & 10 devices, but instead another crash appears on iOS 13 devices:
```
-[NSNull isEqualToString:]: unrecognized selector sent to instance 0x1cc6b3c30
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18ed86a48 __exceptionPreprocess
1  libobjc.A.dylib                0x18eaadfa4 objc_exception_throw
2  CoreFoundation                 0x18ec8a5a8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x18ed8aaf4 ___forwarding___
4  CoreFoundation                 0x18ed8ca7c _CF_forwarding_prep_0
5  Runner                         0x100b7eb68 -[GIDSignIn setHostedDomain:]
6  Runner                         0x100bab584 -[FLTGoogleSignInPlugin handleMethodCall:result:] + 80 (FLTGoogleSignInPlugin.m:80)
7  Flutter                        0x1016ead20 (Missing)
8  Flutter                        0x101688338 (Missing)
9  Flutter                        0x1016dbd5c (Missing)
10 Flutter                        0x101696f58 (Missing)
11 Flutter                        0x1016991dc (Missing)
12 CoreFoundation                 0x18ed0503c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
13 CoreFoundation                 0x18ed04d78 __CFRunLoopDoTimer
14 CoreFoundation                 0x18ed04448 __CFRunLoopDoTimers
15 CoreFoundation                 0x18ecff584 __CFRunLoopRun
16 CoreFoundation                 0x18ecfeadc CFRunLoopRunSpecific
17 GraphicsServices               0x198c9f328 GSEventRunModal
18 UIKitCore                      0x192e0c63c UIApplicationMain
19 Runner                         0x100389f2c main + 6 (AppDelegate.swift:6)
20 libdyld.dylib                  0x18eb88360 start
```

**Comment by tyirvine** [comment]
As with @rafael-trevisan and @MattePalte I can confirm this works. I'm currently using `google_sign_in: 4.4.4`.

As @magax mentions, be sure to replace the `REVERSE_CLIENT_ID` with your own from your `GoogleService-Info.plist` file

<br>**From @MattePalte** 
> I solved the problem by updating all the libraries to their last version and following the official guidelines in the official page https://pub.dev/packages/google_sign_in .
> version 4.1.1
> Namely, I did this:
> 
> 1. First register your application.
> 2. Make sure the file you download in step 1 is named GoogleService-Info.plist.
> 3. Move or copy GoogleService-Info.plist into the [my_project]/ios/Runner directory.
> 4. Open Xcode, then right-click on Runner directory and select Add Files to "Runner".
> 5. Select GoogleService-Info.plist from the file manager.
> 6. A dialog will show up and ask you to select the targets, select the Runner target.
> 
> Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.
> 
> ```
> 
> 
> <key>CFBundleURLTypes</key>
> <array>
> 	<dict>
> 		<key>CFBundleTypeRole</key>
> 		<string>Editor</string>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			
> 			
> 			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
> 		</array>
> 	</dict>
> </array>
> 
> ```

**Comment by vinnytwice** [comment]
@tyirvine Hi , what iOS version is the device you're using `google_sign_in: 4.4.4`on?
I have all the `info.plist` and in order and still crashes on iPad running iOS 9.3.5, not on simulator running iOS 12.2.  
Thanks

**Comment by tyirvine** [comment]
@vinnytwice I've been using iOS 13.3 with Xcode 11

**Comment by alexismoret** [comment]
Crash too using iOS 13.3 with iPhone 11 and `google_sign_in: 4.4.4`
Using new version of `Flutter 1.17`
```
0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e39d4c +[NSException raise:format:] + 188
	3   Runner                              0x000000010636686f -[GIDSignIn signInWithOptions:] + 276
	4   Runner                              0x00000001063661a4 -[GIDSignIn signIn] + 64
	5   Runner                              0x0000000106381334 -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2244
	6   Flutter                             0x000000010678db1f __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	7   Flutter                             0x000000010671c762 _ZNK7flut<…>
```

**Comment by tyirvine** [comment]
@alexismoret did you get this resolved? I am now running on 1.17.0 as well and am experiencing no issues with GoogleSignIn

**Comment by iapicca** [comment]
HI @subramanyamgv 
is this the [case](https://github.com/flutter/flutter/issues/44564#issuecomment-629799797) for you as well?
Thank you

**Comment by alexismoret** [comment]
> @alexismoret did you get this resolved? I am now running on 1.17.0 as well and am experiencing no issues with GoogleSignIn

Yes it works now, it was just a strange config issue in my Info.plist that came along with the update of Flutter. I'm really sorry about my post, thank to you !

**Comment by jmagman** [comment]
> Yes it works now, it was just a strange config issue in my Info.plist that came along with the update of Flutter.

If you think this was a Flutter bug, please let us know by filing a new GitHub issue!

**Comment by tyirvine** [comment]
@alexismoret nw, glad you got it resolved! Like @jmagman mentions, perhaps it was a bug

**Comment by ryanheise** [comment]
@iapicca it's been a while since I've tracked this bug, but @buuth explained the bug and how to fix it a while ago (https://github.com/flutter/flutter/issues/44564#issuecomment-575883100) and I implemented the fix in a PR back in February:

https://github.com/flutter/plugins/pull/2521

I don't know if there are multiple issues here, but that was certainly one of them. It causes a crash for anyone who doesn't pass in a non-null value for the `hostedDomain` parameter. If someone has that particular issue, they can also workaround the crash by passing in an empty string for this parameter to avoid the lack of a null check in the plugin.

Note: I no longer have this set up on my machine, so I don't know if this is already fixed. If not, and if there is something missing from my PR, hopefully you or someone else can fill in whatever else is required for it to pass review.

**Comment by hahai96** [comment]
The problem still appears on google_sign_in: ^4.5.1. It works when google_sign_in is directly below the materialapp, otherwise it will crash

**Comment by BuuTran-Savvycom** [comment]
> To be fair, I can barely keep up with the rate of new issues posted on my own projects so I can understand how this sort of situation will happen, and the problem also scales with the size of the organisation.
> 
> That said, it was a funny bot message given what came before it.
@ryanheise 
Unfortunately many critical bugs not fixed for 6 months or more. For example this one:
https://github.com/flutter/flutter/issues/43957
and many other.
I wish I have free time to contribute and fix those bugs, but I have full-time job and I need to support my family.

**Comment by Fatimamostafa** [comment]
My case was I updated `GoogleService-Info.plist `but forgot to update `CFBundleURLTypes` according to `REVERSED_CLIENT_ID`  in `Info.plist`.

**Comment by Yirmerah** [comment]
This work for me !

> My case was I updated GoogleService-Info.plist but forgot to update CFBundleURLTypes according to REVERSED_CLIENT_ID in Info.plist.

**Comment by guiguito** [comment]
I was facing the same issue and the proposed solution worked for me. 
It would be great to integrate the fix in the official release. Could save hours to devs. 

Thanks for the solution.

**Comment by ryanhoo95** [comment]
I have tried google_sign_in: 4.0.7, 4.4.4, 4.5.1 but still crashing on ios 10.3.3

**Comment by ryanhoo95** [comment]
Using google_sign_in: 4.5.1 and add the hosted domain can solve the crash:

final GoogleSignIn _googleSignIn = GoogleSignIn(hostedDomain: "");
final googleUser = await _googleSignIn.signIn();

Tested on iOS 10.3.3 and 13.5.1

**Comment by GedersonChiquesi** [comment]
Work's fine!

> Using google_sign_in: 4.5.1 and add the hosted domain can solve the crash:
> 
> final GoogleSignIn _googleSignIn = GoogleSignIn(hostedDomain: "");
> final googleUser = await _googleSignIn.signIn();
> 
> Tested on iOS 10.3.3 and 13.5.1

**Comment by iapicca** [comment]
Hi @subramanyamgv 
does the proposed [solution](https://github.com/flutter/flutter/issues/44564#issuecomment-655884103) works for you as well?
Thank you

**Comment by ryanheise** [comment]
> Hi @subramanyamgv
> does the proposed [solution](https://github.com/flutter/flutter/issues/44564#issuecomment-655884103) works for you as well?
> Thank you

@iapicca I would just like to acknowledge @buuth again who originally proposed this solution [back in January](https://github.com/flutter/flutter/issues/44564#issuecomment-575883100). Soon after that, I created a [PR](https://github.com/flutter/plugins/pull/2521) to fix the `hostedDomain` null check and also fixed another cause for crashing in iOS (there is more than one reason why this plugin can crash on iOS).

More recently I found that at least for me, the `hostedDomain` check was no longer necessary so I amended my PR by taking that check out. I had assumed the underlying native library was fixed so the workaround was no longer necessary. I guess it appears not.

I can add it back in, but someone will need to help explain how I can get the PR approved. The solution has been known about for a long while and my PR has been sitting there since February, so it would be good to get this wrapped up with your assistance. On the PR, the checks failed with "Cirrus CI / lint_darwin_plugins PLUGIN_SHARDING:--shardIndex 0 --shardCount 2" but that appears to be unrelated to anything I did.

**Comment by subramanyamgv** [comment]
@iapicca I see no crash when tested on ios devices running 10.3+ using GoogleSignIn plugin version: 4.0.14

**Comment by iapicca** [comment]
Hi @subramanyamgv
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by ryanheise** [comment]
Hi @iapicca Please reopen the issue since what you describe as a "solution" is really an "undocumented workaround" that will still crash if you aren't aware of the workaround. It's not appropriate for the plugin to crash if someone actually uses the plugin as documented but then has to implement a workaround that is undocumented to avoid the crash (how would they realistically know that the `hostedDomain` parameter needs to be set to an empty string to avoid a missing null check deeper in the plugin?)

The cause of this bug has been known and reported since January and a pull request was submitted by February. I would be happy to update my pull request based on the latest information reported in the last few comments (i.e. to bring back the `hostedDomain` check now that there are fresh reports that this is still an issue).

P.S. You have someone here who is willing to help to fix the bug. Why would you ignore that and then proceed to close the issue?

**Comment by congfandi** [comment]
i have been try all solution that you have been propose here guys.. but i still get the error :-( .. My device Iphone 8+ with ios 13.6
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by iapicca** [comment]
@TahaTesser

**Comment by ryanheise** [comment]
@congfandi can you try the fix in https://github.com/flutter/plugins/pull/2521? Test it by changing your google_sign_in dependency to:

```yaml
  google_sign_in:
    git:
      url: https://github.com/ryanheise/plugins.git
      ref: fix_google_sign_in_crash
```

**Comment by congfandi** [comment]
> ```yaml
> google_sign_in:
>     git:
>       url: https://github.com/ryanheise/plugins.git
>       ref: fix_google_sign_in_crash
> ```

i got some error

```Could not find a file named "pubspec.yaml" in https://github.com/ryanheise/plugins.git f6b409dc00d8ae0b02fbc3705a181b52cd5080e7.
pub get failed (1; Could not find a file named "pubspec.yaml" in https://github.com/ryanheise/plugins.git f6b409dc00d8ae0b02fbc3705a181b52cd5080e7.)

**Comment by ryanheise** [comment]
@congfandi Sorry I had left off the `path`. I've edited my previous comment to include it. Can you try again?

**Comment by congfandi** [comment]
> @congfandi Sorry I had left off the `path`. I've edited my previous comment to include it. Can you try again?

```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(concurrent-requests, Concurrent requests to account signin, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:361:48)
#4      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
#5      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:42)
<asynchronous suspension>
#6      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:297:16)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)<…>

i got another error dude

im using emuloator iphone xr

**Comment by ryanheise** [comment]
@congfandi Assuming that's an exception rather than a crash, it sounds like the PR is doing what it intended. Previously the plugin would "crash" your app completely rather than throw an exception to indicate what was wrong. If you're getting an exception that you can catch, it is now different from this "crash" issue and you should open a new issue with the stack trace etc.

Note that there already seems to be an issue submitted for your error (#57486 ) but it was closed because the person who submitted it didn't provide all necessary details to investigate. Basically, it looks like this error occurs because you are calling the API more than once concurrently, which sounds like something you can avoid by checking that your code doesn't call the API more than once. If it is happening even if you're not doing that, you can open a new issue (although see the above linked issue first to understand why it was closed and make sure you provide the necessary information)

**Comment by zjamshidi** [comment]
My iOS app is crashing too. I got the error as shown in [this comment](https://github.com/flutter/flutter/issues/44564#issuecomment-555720384)
![image](https://user-images.githubusercontent.com/3742220/90372901-c0a15d80-e08e-11ea-99ed-cec1c2c740e9.png)

GoogleService-Info.plist  is updated and REVERSED_CLIENT_ID has the updated value in Info.plist.

here is my dependency list:
```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.6
  sqflite: ^1.3.0+1
  youtube_player_flutter: ^7.0.0+6
  audio_service: ^0.13.0
  just_audio: ^0.3.3
  connectivity: ^0.4.9
  transparent_image: ^1.0.0
  animations: ^1.0.0+5
  flutter_email_sender: ^3.0.1
  firebase_dynamic_links: ^0.5.1
  progress_dialog: ^1.2.3
  share: ^0.6.4+3
  firebase_analytics: ^5.0.14
  firebase_crashlytics: ^0.1.3+3
  amplitude_flutter: ^2.0.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  sign_in_with_apple: ^2.5.2
  shared_preferences: ^0.5.7+3
  flutter_staggered_grid_view: ^0.3.0
  async: ^2.4.1
  url_launcher: ^5.4.11
  fluttertoast: ^6.0.0
  package_info: ^0.4.0+16
  flutter_local_notifications: ^1.4.4+2
  flutter_datetime_picker: ^1.3.8
  auto_size_text: ^2.1.0
  wave: ^0.0.8
  flutter_downloader: ^1.5.0
  purchases_flutter: ^1.2.1
  cached_network_image: ^2.2.0+1
```

Setting empty sting as hostname doesn't solve the crash. 

Users could use Google Sign In in several parts of the app, all of them work except the one in the audio player which has download button (using Flutter Downloader) 
@hnvn I have followed what you mentioned the plugin iOS integration.
```
import UIKit
import Flutter
import flutter_downloader

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
       FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
    }
}
```

Any suggestion?

**Comment by JigarKotak7** [comment]
<img width="867" alt="Screen Shot 2020-08-17 at 1 52 42 PM" src="https://user-images.githubusercontent.com/31124960/90374692-82f20400-e091-11ea-93af-44be49158f68.png">
Open Xcode go to project Setting - info and add URL Type and paste reverse ID in URL schemes where you see scratched out box.

**Comment by zjamshidi** [comment]
@JigarKotak7 Thanks for your reply. However, as I mentioned in my comment, I have already added it.
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>motiveex_dl</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.motiveex.app</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.XXXXXX</string>
			</array>
		</dict>
	</array>
```

**Comment by ryanheise** [comment]
Hi @zjamshidi 

Without a reproduction project, I've taken a guess at what might be wrong and updated my PR.

Can you try this?

```yaml
  google_sign_in:
    git:
      url: https://github.com/ryanheise/plugins.git
      ref: fix_google_sign_in_crash
      path: packages/google_sign_in/google_sign_in
```

**Comment by zjamshidi** [comment]
@ryanheise Thanks for your reply. Unfortunately, the crash is still happening:
![image](https://user-images.githubusercontent.com/3742220/90424224-624e9c00-e0db-11ea-9fdc-17375985072b.png)

In the logs I see:
```
Printing description of self->_accountRequest:
(FlutterResult) _accountRequest = (null)
```

**Comment by ryanheise** [comment]
@zjamshidi OK, I just wanted to check quickly if that was it. But it probably won't be practical for anyone to fix this particular crash without a reproduction project.

**Comment by zjamshidi** [comment]
Yes. It's understandable. I'm preparing it.

**Comment by congfandi** [comment]
Hello guys, i have been add this on iOS side and i dont get the error anymore.
the xxxx after google user content is the error that you get after try to login on your ios site.. its like some code missing and every singgle apps is got own code from google..
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.sample.sample</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.xxxxxx</string>
				<string>com.googleusercontent.apps.xxxx</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.xxxxx</string>
			</array>
		</dict>
	</array>
```

**Comment by truthmast** [comment]
I'm seeing this crash on iOS v10.3.3 (iPhone 5c). Adding `hostedDomain: ''` to the `GoogleSignIn` constructor does resolve it. 

I'm NOT seeing it on Simulator devices, and it seems the majority of our users aren't seeing this crash either.

**Comment by ammaratef45** [comment]
I've tried `google_sign_in: ^4.0.7` with `GoogleSignIn(hostedDomain: '')` and it still crashes

**Comment by ryanheise** [comment]
@zjamshidi did you manage to make a reproduction project or perhaps did your issue go away?

**Comment by zjamshidi** [comment]
Unfortunately, no. In fact, I noticed the crash is only happening in the audio player and sign-in is working fine in other parts of the app.
I have two main plugins in the audio player:  [flutter_downloader](https://pub.dev/packages/flutter_downloader) and [audio_service](https://pub.dev/packages/audio_service).
First, I disabled the flutter_downloader , but the crash was still happening.
Second, I bring the sign-in out of the audio-widget and now the sign-in is working fine.
So I guess the problem would be the conflict between audio_service and sign-in plugin. But my audio_service plugin is not up to date so I didn't report it there.

**Comment by ryanheise** [comment]
@zjamshidi interesting. That sheds some light on the matter. I'll take a look to see if google_sign_in has any issues being loaded into multiple FlutterEngines, since sometimes this is a problem for some plugins. Even if the app doesn't use the plugin in the background, all plugins are still loaded. But just to check, can you clarify whether you were using google_sign_in within the background isolate, or within the main isolate?

**Comment by zjamshidi** [comment]
I'm using the `google_sign_in` within the main isolate. 
You may want to change the `audio_service` demo and add sign in when the user taps on the pause button.

**Comment by cpboyd** [comment]
I found #46532 before this... I'm seeing this on the iOS 10.3.1 Simulator (the only iOS 10 simulator listed in XCode 12).
That seems to follow with @truthmast's comments regarding an iPhone 5c.

I'm not seeing this on iOS 11+ simulators.

**Comment by MiguelSOliveira** [comment]
I'm still having this exact problem on ios simulator 13.5. It crashes the simulator with no logs given (even when running on debug, it doesn't print anything). However, when I restart the application after the crash it seems to work, very weird.

I'm using sign in like this:
```
await GoogleSignIn(
      scopes: ["email"],
      hostedDomain: "",
      clientId: "",
    )
```

Like it was suggested above.. Still crashes.

Does it happen to anyone else?

**Comment by ryanheise** [comment]
@MiguelSOliveira try opening `Runner.xcworkspace` of your app in Xcode and then run the project from there. When it crashes, the debugger will appear and on the left you'll be able to browse through to the thread and through to the line of code where it crashed. If you can share that info here, it will help to investigate.

**Comment by MiguelSOliveira** [comment]
Okay I feel really dumb because I had no idea that Xcode would provide a different output than AndroidStudio or the Terminal.

Anyways, I ran the app on xcode and immediately found the problem:
`reason	__NSCFString *	"Your app is missing support for the following URL schemes: ....`

So I googled and within 30seconds found the solution:
https://developers.google.com/identity/sign-in/ios/start-integrating#add_a_url_scheme_to_your_project

In my case though, I had already done this and the problem was that I had accidentally copied or moved, a duplicated Google-Info.plist, so it was just a matter of deleting that file.

So i guess it wasn't related to this issue after all, thank you for saving me even more hours of googling @ryanheise, really wish I had known about xcode logging before though.

**Comment by jmagman** [comment]
@MiguelSOliveira You should see better logging in Android Studio and the terminal as of https://github.com/flutter/flutter/pull/66399, which is available on the master channel.

**Comment by MiguelSOliveira** [comment]
Ah I'm on the stable channel, that explains it then. I look forward to integrate those changes, thanks @jmagman.

**Comment by leidig54** [comment]
Same issue here. 


`2020-10-19 13:32:35.629963+0100 Runner[25586:3144487] -[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff8019dd30
2020-10-19 13:32:35.633743+0100 Runner[25586:3144851] flutter: PlatformException(google_sign_in, -[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff8019dd30, NSInvalidArgumentException, null)
2020-10-19 13:32:35.635060+0100 Runner[25586:3144487] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff8019dd30'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20448c6f +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff2043e666 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20440698 _CF_forwarding_prep_0 + 120
	5   Runner                              0x000000010ad97918 +[GIDSignInCallbackSchemes relevantURLSchemes] + 315
	6   Runner                              0x000000010ad97d58 -[GIDSignInCallbackSchemes unsupportedSchemes] + 118
	7   Runner                              0x000000010ad92b63 -[GIDSignIn signInWithOptions:] + 157
	8   Runner                              0x000000010ad9250f -[GIDSignIn signIn] + 64
	9   Runner                              0x000000010af2ba08 -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2392
	10  Flutter                             0x000000010c2605be __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	11  Flutter                             0x000000010ba47066 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	12  Flutter                             0x000000010ba4be08 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	13  Flutter                             0x000000010bd9861b _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	14  Flutter                             0x000000010ba53d46 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 160
	15  Flutter                             0x000000010ba58ab6 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	16  CoreFoundation                      0x00007fff203a9112 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	17  CoreFoundation                      0x00007fff203a8be5 __CFRunLoopDoTimer + 926
	18  CoreFoundation                      0x00007fff203a8198 __CFRunLoopDoTimers + 265
	19  CoreFoundation                      0x00007fff203a2826 __CFRunLoopRun + 1949
	20  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
	21  GraphicsServices                    0x00007fff2b773db3 GSEventRunModal + 139
	22  UIKitCore                           0x00007fff24660af3 -[UIApplication _run] + 912
	23  UIKitCore                           0x00007fff24665a04 UIApplicationMain + 101
	24  Runner                              0x000000010aa50a0b main + 75
	25  libdyld.dylib                       0x00007fff20257415 start + 1
	26  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff8019dd30'
terminating with uncaught exception of type NSException
CoreSimulator 732.17 - Device: iPhone 11 (2B43A4B3-F742-4762-98EF-8EA55BB49971) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11'


Flutter code (doesn't get past ' await googleSignIn.signIn();').

'final GoogleSignIn googleSignIn = GoogleSignIn(
    scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly'],
    hostedDomain: "",
    clientId: "",
  );'

`Future<void> signInWithGoogle() async {
    userUpdating = true;
    notifyListeners();

    GoogleSignInAccount googleSignInAccount;
    GoogleSignInAuthentication googleSignInAuthentication;
    AuthCredential credential;

    try {
      googleSignInAccount = await googleSignIn.signIn();
      print(googleSignInAccount);

      
    } catch (e) {
      userUpdating = false;
      print(e);
    }
  }`

My URL types etc are all correct. 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
 
[✓] Connected device (2 available)            

• No issues found!

**Comment by quentinleguennec** [comment]
Had this issue out of nowhere when the plugin was previously working.

The **SOLUTION** in our case was quite simple, a colleague added `CFBundleURLTypes` again at the bottom of the `Info.plist` file by mistake when adding some other plugin. Since `CFBundleURLTypes` was there twice only the last one was read, effectivelly erasing Google Sign In configs.
We just had to move everything in one single `CFBundleURLTypes` and it worked without changing anything else.

TL;DR double check `CFBundleURLTypes` is there only **once** in your `Info.plist`.

Tested on iOS 13 and 14, with google_sign_in: 4.5.5

**Comment by mirkancal** [comment]
@quentinleguennec I'm using Facebook sign in too and it has CFBundleURLTypes too. Do you know how to merge those two?

**Comment by mirkancal** [comment]
@quentinleguennec Thanks alot. I did the same mistake while adding Facebook OAuth config, I had 2 CFBundleURLTypes. I merge them and it solve the problem for me.

Basically put the <string>fbsomenumbers</string> under the google's value, <string>com.googleusercontent.apps.andsoon</string>

**Comment by adamkoch** [comment]
I think there seems to be 2 issues here that result in the same crash/error:

1. Misconfiguration of some sort of `Info.plist` and `CFBundleURLTypes` which causes crashes immediately, fixing the configuration as per the last few posts
2. Crash in Google Sign-In only on some older versions of iOS, seems to be iOS 10.x but no crashes on newer iOS versions

I see issue 2 with an app I have in production (I only see crashes coming in on iOS 10.3) -- I am able to reproduce this with the iOS 10.3 simulator. Adding `hostedDomain: ""` to the `GoogleSignIn()` appears to fix the problem for me. Not sure what other side effects that may have.

**Comment by mehemmelbachir** [comment]
> @congfandi can you try the fix in [flutter/plugins#2521](https://github.com/flutter/plugins/pull/2521)? Test it by changing your google_sign_in dependency to:
> 
> ```yaml
>   google_sign_in:
>     git:
>       url: https://github.com/ryanheise/plugins.git
>       ref: fix_google_sign_in_crash
>       path: packages/google_sign_in/google_sign_in
> ```

Hello @ryanheise, I am facing this issue since I added [audio_services](https://pub.dev/packages/audio_service),
I also tried your fork but still not working,
In my case the app still crashing and not throwing exception as expected. only in xcode I can see the following error:
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)`
Do you have any update on how to solve this problem?

**Comment by tonycesar** [comment]
> @ryanheise Thanks for your reply. Unfortunately, the crash is still happening:
> ![image](https://user-images.githubusercontent.com/3742220/90424224-624e9c00-e0db-11ea-9fdc-17375985072b.png)
> 
> In the logs I see:
> 
> ```
> Printing description of self->_accountRequest:
> (FlutterResult) _accountRequest = (null)
> ```

Hello, for fix this error, I modify this file FLTGoogleSignInPlugin.m.

In line 20 I added a static variable:
static FlutterResult AccountRequest;

And remove line FlutterResult _accountRequest;

Finally, replace _accountRequest by AccountRequest in other six ocurrences.

I dont kwno why but, debugging I saw that instance of FLTGoogleSignInPlugin  called in signIn in line 196 dont have the _accountRequest  variable assigned. But if extern this variable like static, this bug is fixed.

**Comment by sanekyy** [comment]
Same issue.

Thanks @tonycesar. It works!

**Comment by imepnja** [comment]
I have the same issue
Downgrading `google_sign_in` created even more errors...

Where do I find `CFBundleURLTypes`? I can't find them anywhere in my `info.plist` (ios/runner/info.plist is the right file?) and how can I change them?

I also have an `try/catch` block around `googleSignIn.signIn()` which completely fails. It doesn't catch any errors. The App crashes completely with message:`Exited (sigterm)`

**Comment by quentinleguennec** [comment]
@imepnja You need to write the `CFBundleURLTypes` info in your `ios/Runner/Info.plist`, else the plugin will not work.
See the doc for "iOS integration" at point 7:
https://pub.dev/packages/google_sign_in#ios-integration

**Comment by sanekyy** [comment]
you can use my fork with fix:

```dart
google_sign_in: #^4.5.9
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: ios-fix-sign-in
      path: packages/google_sign_in/google_sign_in
      ```

**Comment by colehorvitz** [comment]
> you can use my fork with fix:
> 
> ```dart
> google_sign_in: #^4.5.9
>     git:
>       url: git://github.com/sanekyy/plugins.git
>       ref: ios-fix-sign-in
>       path: packages/google_sign_in/google_sign_in
>       ```
> ```

This worked for me. Thanks!

**Comment by erperejildo** [comment]
> ```dart
> google_sign_in: #^4.5.9
>     git:
>       url: git://github.com/sanekyy/plugins.git
>       ref: ios-fix-sign-in
>       path: packages/google_sign_in/google_sign_in
> ```

I tried this but didn't work for me

**Comment by erperejildo** [comment]
> Had this issue out of nowhere when the plugin was previously working.
> 
> The **SOLUTION** in our case was quite simple, a colleague added `CFBundleURLTypes` again at the bottom of the `Info.plist` file by mistake when adding some other plugin. Since `CFBundleURLTypes` was there twice only the last one was read, effectivelly erasing Google Sign In configs.
> We just had to move everything in one single `CFBundleURLTypes` and it worked without changing anything else.
> 
> TL;DR double check `CFBundleURLTypes` is there only **once** in your `Info.plist`.
> 
> Tested on iOS 13 and 14, with google_sign_in: 4.5.5

I fixed it also by modifying the Info.plist but we careful with that affirmation. If we have sing-in methods with Google AND Facebook we need to have more than one `CFBundleURLTypes`

**Comment by imepnja** [comment]
> @imepnja You need to write the `CFBundleURLTypes` info in your `ios/Runner/Info.plist`, else the plugin will not work.
> See the doc for "iOS integration" at point 7:
> https://pub.dev/packages/google_sign_in#ios-integration

this fixed it for me

**Comment by mirrorlink** [comment]
I have as similar issue

I am using an iPad. If you tap outside of the webview to dismiss it when attempting to login, it will close the webview but the method

```
GoogleSignIn().signIn();
```

Never returns. If you tap the button again, then it will show

flutter: PlatformException(concurrent-requests, Concurrent requests to account signin, null, null)

So the STR is:

Use google_sign_in on and iPAD
When whe webview opens as a result ofGoogleSignIn().signIn(); , tap outside the webview to dismiss it
Try executing again GoogleSignIn().signIn();

Expected: GoogleSignIn().signIn(); should return with null

Whats happening: GoogleSignIn().signIn(); is not returning at all

```
flutter: pre signing
flutter: post signin //(I clicked cancel)
flutter: pre signing // (I tapped outside of the webview to dismiss it)
flutter: pre signing
flutter: runZonedGuarded: Caught error in my root zone.
flutter: Error: PlatformException(concurrent-requests, Concurrent requests to account signin, null, null)
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(concurrent-requests, Concurrent requests to account signin, null, null)
```

**Comment by codxse** [comment]
Are you running on apple silicon or intel one? if so, please check this thread https://github.com/firebase/firebase-ios-sdk/issues/7208#issuecomment-846537311

I am having this issue too with react-native. For now I am opening the xcode with roseta to solve this.

**Comment by sanekyy** [comment]
Hi there!
And news?

**Comment by ayuram** [comment]
To those still having issues:
The flutter fire documentation doesn't really make this clear, but you need to do Step 2, part 1 in this link:
[firebase documentation](https://firebase.google.com/docs/auth/ios/google-signin)
I followed it verbatim in combination with  [this](https://github.com/flutter/flutter/issues/44564#issuecomment-770322580) and now my app is working

**Comment by iosif-bancioiu** [comment]
This readme worked for me (version 5.0.7)
https://pub.dev/packages/google_sign_in

**Comment by ballahtech** [comment]
> This readme worked for me (version 5.0.7)
> https://pub.dev/packages/google_sign_in

oh I followed this, but i missed this comment
```
<!-- TODO Replace this value: -->
			<!-- Copied from GoogleService-Info.plist key REVERSED_CLIENT_ID -->
```

after replacing that value from the REVERSED_CLIENT_ID mine worked

**Comment by cyanglaz** [comment]
The issue should be fixed by https://github.com/flutter/flutter/issues/44564.

**Comment by Rahiche** [comment]
Hi @cyanglaz 
Did you mean to post the link of a PR ? the current link in your comment is for this issue it self

**Comment by cyanglaz** [comment]
@Rahiche  you are right, i'll edit my original post
