### ISSUE TITLE
[web] Another exception was thrown: Instance of 'minified:aN' - Only When Deployed

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#44912]
[✓] Flutter (Channel master, v1.11.1-pre.49, on Mac OS X 10.13.6 17G8037, locale zh-Hans-CN)
    • Flutter version 1.11.1-pre.49 at /Users/admin/Library/flutter
    • Framework revision c90d64b619 (7 hours ago), 2019-11-14 01:16:17 -0500
    • Engine revision 7c2a4ec97f
    • Dart version 2.7.0

error:
Another exception was thrown: Instance of 'minified:aN<void>'

i got that error when i demployed  my flutter web package in to nginx,but work in " flutter run -d chrome"

my project:
https://github.com/lyf571321556/ai-one-flutter

**Comment by iapicca** [comment]
Hi @lyf571321556 
could you please provide your `flutter run --verbose` or `flutter build --verbose` ?
Thank you

**Comment by lyf571321556** [comment]
@iapicca  

╭   liuyanfeng   …/FlutterWorkspace/ones_ai_flutter     master                                                     02:47   5.02G   62% (2:42)    192.168.1.213    00:06  15.11.19  
╰ flutter run --verbose
[  +22 ms] executing: [/Users/liuyanfeng/Library/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3d65c21a97a9e9028170db94907f2e5ef7a9ac50
[        ] executing: [/Users/liuyanfeng/Library/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.11.0-50-g3d65c21a97
[   +6 ms] executing: [/Users/liuyanfeng/Library/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/liuyanfeng/Library/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +38 ms] executing: [/Users/liuyanfeng/Library/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +8 ms] executing: sw_vers -productName
[  +11 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +22 ms] executing: /usr/bin/xcode-select --print-path
[   +6 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[  +81 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.2
           Build version 11B52
[  +54 ms] executing: /Users/liuyanfeng/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/liuyanfeng/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +12 ms] executing: /Users/liuyanfeng/Library/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +42 ms] /usr/bin/xcrun simctl list --json devices
[  +80 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +37 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
[        ] Web Server • web-server • web-javascript • Flutter Tools
[   +9 ms] "flutter run" took 403ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:582:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:507:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:497:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///Users/liuyanfeng/Library/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by iapicca** [comment]
nginx https://github.com/flutter/flutter/issues/40535

**Comment by yjbanov** [comment]
Can you please reproduce using a `--profile` build? It should give you a much more readable stack trace.

**Comment by lyf571321556** [comment]
it  was fixed? it works very well after flutter upgraded to newest version;

**Comment by yjbanov** [comment]
Apparently it was, but I don't know how. Thanks for checking!

**Comment by efichot** [comment]
I'm on the latest version of flutter and I have exactly the same problem when I deployed, the problems sounds not fixed... 😟

**Comment by yjbanov** [comment]
@efichot Could you please provide the details about your issue? It would be particularly useful to have information from a `--profile` build.

**Comment by VarmaTech** [comment]
Still the same , when i build the project and made like to surge domain and open web in IE10 browser.
its works well in firefox and chrome but not in IE
![image](https://user-images.githubusercontent.com/16360182/71566882-3b5a4000-2ae1-11ea-82fa-1b503fdb22e4.png)

**Comment by parnurzeal** [comment]
<img width="451" alt="Screen Shot 2563-02-11 at 00 25 43" src="https://user-images.githubusercontent.com/841616/74168698-1242d880-4c65-11ea-978c-9863c0522e31.png">
I also experience this problem. I use 


```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.15.2, on Mac OS X 10.15.3 19D76, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by speedlightwp** [comment]
I encounter similar type of issues:
Another exception was thrown: Instance of ty()
App able to start up and run fine, problem occurs after I switch to another page/dart file. One of the screen turn grey, it seems like codes in the initstate caused it but can't figure out why. There is no issues under "Run -> debug" mode, problem only appears in only Run -> Profile and Release.
 
I am using Flutter stable release - 1.17.0 and Beta - 1.17.0-3.4.pre, similar issues. The problem resolved after I switched to Flutter Dev - 1.19.0-0.0.pre. Guess I have to stick to Dev for now.

**Comment by LeonWehrhahn** [comment]
I am having the same problem.

**Comment by apgapg** [comment]
Yes same problem. It works in debug mode but fails in release mode

**Comment by speedlightwp** [comment]
Upgrade flutter version to Dev solved my issues.

**Comment by apgapg** [comment]
@speedlightwp  but i am on latest 'dev' version `1.20.0-0.0.pre`. Still it gives error

**Comment by ProfiroiuMihai** [comment]
I have the same error. It works in debug mode but fails in release mode. I tried to change to to every beach no result:
Channel master, 1.20.0-1.0.pre.156
Channel dev, 1.20.0-0.0.pre
Channel beta - latest

Also tried form my windows and my macbook same issues.
From windows:

[√] Flutter (Channel master, 1.20.0-1.0.pre.156, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[!] Android Studio (version 2.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Android Studio (version 3.2)
[√] VS Code (version 1.44.2)
[√] VS Code, 64-bit edition (version 1.23.1)
[√] Connected device (3 available)

From mac:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F72f, locale en-GB)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

**Comment by ProfiroiuMihai** [comment]
I search this on google and I found numerous issues opened on this matter on flutter.
https://github.com/flutter/flutter/issues/47880
https://github.com/flutter/flutter/issues/53487
https://github.com/flutter/flutter/issues/44912
https://github.com/flutter/flutter/issues/50467

Many people have the same problems please prioritize this bug.

**Comment by ProfiroiuMihai** [comment]
C:\Users\mike\Documents\GitHub\spire_web>flutter build web --verbose

[ +131 ms] executing: [C:\Users\mike\Desktop\fluterTot\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +72 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8c3b826ebd550008a23b4e2f50b249facff3004b
[   +1 ms] executing: [C:\Users\mike\Desktop\fluterTot\flutter/] git tag --contains HEAD
[ +267 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] executing: [C:\Users\mike\Desktop\fluterTot\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +100 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.20.0-0.0.pre-156-g8c3b826ebd
[  +10 ms] executing: [C:\Users\mike\Desktop\fluterTot\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Users\mike\Desktop\fluterTot\flutter/] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +86 ms] executing: [C:\Users\mike\Desktop\fluterTot\flutter/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +55 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +135 ms] Found plugin shared_preferences at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+2\
[   +8 ms] Found plugin shared_preferences_macos at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+8\
[   +5 ms] Found plugin shared_preferences_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+5\
[  +14 ms] Found plugin video_player at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\
[   +4 ms] Found plugin video_player_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3\
[  +75 ms] Found plugin shared_preferences at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+2\
[   +3 ms] Found plugin shared_preferences_macos at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+8\
[   +3 ms] Found plugin shared_preferences_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+5\
[  +13 ms] Found plugin video_player at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\
[   +3 ms] Found plugin video_player_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3\
[  +50 ms] Generating C:\Users\mike\Documents\GitHub\spire_web\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +88 ms] Found plugin shared_preferences at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+2\
[   +2 ms] Found plugin shared_preferences_macos at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+8\
[   +2 ms] Found plugin shared_preferences_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+5\
[   +7 ms] Found plugin video_player at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\
[   +2 ms] Found plugin video_player_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3\
[  +26 ms] Found plugin shared_preferences at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+2\
[   +2 ms] Found plugin shared_preferences_macos at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+8\
[   +3 ms] Found plugin shared_preferences_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+5\
[  +11 ms] Found plugin video_player at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\
[   +2 ms] Found plugin video_player_web at C:\Users\mike\Desktop\fluterTot\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3\
[  +11 ms] Generating C:\Users\mike\Documents\GitHub\spire_web\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +13 ms] Compiling lib\main.dart for the Web...
[  +14 ms] Initializing file store
[  +21 ms] Done initializing file store
[  +83 ms] Skipping target: gen_localizations
[  +19 ms] Skipping target: web_entrypoint
[ +670 ms] Skipping target: dart2js
[  +48 ms] invalidated build due to missing files: C:\Users\mike\Documents\GitHub\spire_web\DOES_NOT_EXIST_RERUN_FOR_WILDCARD728570050
[ +346 ms] web_release_bundle: Starting due to {InvalidatedReason.inputMissing}
[ +204 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +68 ms] web_release_bundle: Complete
[+1008 ms] Skipping target: web_service_worker
[   +1 ms] Persisting file store
[  +10 ms] Done persisting file store
[  +18 ms] Compiling lib\main.dart for the Web... (completed in 2.5s)
[   +2 ms] "flutter web" took 3,088ms.
[ +130 ms] ensureAnalyticsSent: 126ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0

**Comment by ProfiroiuMihai** [comment]
This is how it looks like on firebase hosting ( after flutter build web and Firebase deploy)
![image](https://user-images.githubusercontent.com/44637696/85385097-8f068d00-b54a-11ea-9395-5817efe26379.png)

This is how it looks like after I run chrome( works as should)
![image](https://user-images.githubusercontent.com/44637696/85385506-0c320200-b54b-11ea-91df-d8a4c46cb94f.png)

**Comment by ProfiroiuMihai** [comment]
Also I made sample of the code to be easier for you to reproduce.:


import 'package:flutter/material.dart';
import 'package:spire_web/util/simple_route.dart';

class Test1 extends StatelessWidget {

  static Route<dynamic> route() {
    return SimpleRoute(
      name: '/',
      title: 'Test1',
      builder: (_) => Test1(),
    );
  }


  @override
  Widget build(BuildContext context) {

    return         Scaffold(
      body: Container(
        margin: EdgeInsets.only(top: 25),
        child: Card(
          elevation: 0,
          color: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          child: Column(
            children: [
              Padding(
                padding: EdgeInsets.only(
                  top: 20,
                  left: 100,
                  right: 100,
                ),
                child: Row(
                  mainAxisAlignment:
                  MainAxisAlignment.spaceEvenly,
                  children: [
                    cardItem(
                        "assets/images/ruby_pass_icon_profile.png",
                        "15",
                        "Friends"),
                    Container(
                      height: 60,
                      color: Colors.red,
                      width: 1,
                    ),
                    cardItem(
                        "assets/images/ruby_pass_icon_money.png",
                        "1500",
                        "Earned"),
                  ],
                ),
              ),
              Padding(
                padding: EdgeInsets.only(
                    left: 100,
                    right: 100,
                    top: 20,
                    bottom: 40),
                child: Stack(
                  children: [
                    Expanded(
                      child: TextFormField(
                        controller: TextEditingController(text: "https://spirecard.com/spireuser-420"),
                        enabled: false,),
                    ),
                    Container(
                      alignment: Alignment.centerRight,
                      child: FlatButton(
                        child: Text("Copy"),onPressed: (){},
                      ),
                    )
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  cardItem(
      String icon,
      String number,
      String title,
      ) {
    return Container(
      padding: EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
          ),
          Row(
            children: [
              Image.asset(
                icon,
                height: 16,
              ),
              Padding(
                padding: EdgeInsets.all(2),
              ),
              Text(
                number,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

**Comment by jonnyjohnson1** [comment]
Running into the same issue. Works locally, fails when deployed to firebase hosting. I get the same error. 

"Another exception was thrown: Instance of 'minified:fa<void>'"

I was on beta channel then moved to dev per the comments, I tried to roll back to 1.19.1-0.0.pre and it didn't work.

Here's my flutter doctor.

`Flutter 1.20.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f73f498da1 (7 days ago) • 2020-06-18 08:23:22 -0700
Engine • revision c0d52b98d1
Tools • Dart 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.3 19D76, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android SDK file not found: adb.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.`

This is what I'm trying to do. This isn't reproducible. VideoElement code was from implementing Mariano's code from CodePen: https://codepen.io/mkiisoft/details/ZEboVgJ.

`class Tuple<F, S> {
    F first;
    S second;
    Tuple(this.first, this.second);
  }
  class Utils {
    static Tuple<Widget, html.VideoElement> video ( String url, id, bool autoPlay) {
      final video = html.VideoElement();
      video.autoplay = autoPlay;
      video.src = url;
      video.style.border = 'none';
      video.onClick.listen((event) => video.paused ? video.play() : video.pause());
      // ignore: undefined_prefixed_name
      ui.platformViewRegistry.registerViewFactory('video_tv$url$id', (int viewId) => video);
      return Tuple(HtmlElementView(key: UniqueKey(), viewType: 'video_tv$url$id'), video);
    }

class IframeScreen extends StatefulWidget {
  final String _livestreamURL;
  IframeScreen(this._livestreamURL);

  @override
  _IframeScreenState createState() => _IframeScreenState();
}

class _IframeScreenState extends State<IframeScreen> {

  final _video = Utils.video('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', '1', true);

  @override
  Widget build(BuildContext context) {
    SizeConfig().init(context);
    final _width = SizeConfig.blockSizeVertical * 100;
    final _height = SizeConfig.blockSizeVertical * 28;
    return Container(
      child: SizedBox(
        child: _video.first,
        ),
      ),
    );
  }
}
  }`

**Comment by Buildex** [comment]
Same error here, flutter doctor has no issues

**Comment by jonnyjohnson1** [comment]
I am having the error happen repeatedly. I'm not experienced enough to pinpoint exactly what is happening, but I think each time I see it, I have an error in state management, and when I run in debug mode, the mode forgives the error, and the deployed mode does not forgive the error.

I still haven't figured out how to resolve the issue.

**Comment by ianvillamia** [comment]
Any fix for this problem?

**Comment by jonnyjohnson1** [comment]
I found this solution this morning. I had an error in my widget tree. I had the minified, grey screen error on two separate instances on two different apps. All I ended up needing to do was remove an Expanded widget, and I got the scenario working.

This was what I saw that clued me in:
https://stackoverflow.com/questions/54905388/incorrect-use-of-parent-data-widget-expanded-widgets-must-be-placed-inside-flex

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
