### ISSUE TITLE
[web] not working on Microsoft Edge and Internet Explorer

### ISSUE THREAD

**Issue by andredealmei** [flutter/flutter#45162]
no samples work on https://flutter.github.io/samples/

**Comment by iapicca** [comment]
Hi @andredealmei 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose?
Thank you

**Comment by GowthamF** [comment]
@andredealmei Since Microsoft has stopped supporting Internet Explorer, it cannot be considered even most of the modern websites doesn't work. Edge does not support all the Javascript modules. As Microsoft is building Chromium Edge browser it is about to be released, it will be working with Flutter Web in the future.

**Comment by jonahwilliams** [comment]
@ferhatb are the samples up to date and using dart2js?

**Comment by juanjoserodrigolazaro** [comment]
only displays blank page when i open my webpage made with flutter web on edge! (tested on chorme and safari, both working fine)

**Comment by SebTardif** [comment]
I'm surprised a pull can occur without sanity check on common browser. Testing is free, https://www.browserstack.com/open-source?ref=pricing

**Comment by juanjoserodrigolazaro** [comment]
Is this resolved? I saw my page today still shows only blank...

**Comment by raviganwal** [comment]
I am facing this issue too with this https://raviganwal.github.io/ website I made in flutter. It does not load on edge or Microsoft Edge and Internet Explorer on PC or Samsung browser on mobile. Also, it lags too much in android chrome browser.

**Comment by ferhatb** [comment]
Verified that this is resolved in Edge but still causing issue in IE11. Fix landing shortly.

**Comment by juanjoserodrigolazaro** [comment]
this is not fixed... have you tested on microsoft edge on windows?

**Comment by carman247** [comment]
Doesn't work for my. running latest version of Edge on Windows 10

**Comment by Constans** [comment]
Yeap, it's not working when compiling on the master branch.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by nmacherey** [comment]
Hi I didi it here https://github.com/flutter/flutter/issues/54607

Regards
