### ISSUE TITLE
Crash when run on iOS device against latest engine

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4560]
## Steps to Reproduce

1. Run the gallery app on an iOS device against a local engine (currently synced to 8e475a9570520692e69f93e39e5fd7e918e4b0e4)
2. Click to the buttons component page, then back, repeatedly (really any use of the app for long enough will work).

## Notes

This does *not* seem to happen on Android or iOS simulator, nor does it seem to happen against a release engine.  I quality those statements because of the intermittent nature of the crash (so I can't be sure that the issue doesn't exist in those scenarios).

### Crash Report:
https://gist.github.com/tvolkert/c6db2cf0d6f48e1b3ba394ddf063b13e

### Stack when I ran this in XCode against an engine build with debug symbols:
https://gist.github.com/tvolkert/12b17b15e297341d2b081b2120328222

**Comment by tvolkert** [comment]
After extensive testing, confident that this only happens for *on-device* builds with runtime mode set to *debug*, which in turn means this only happens when using dbc (`dart_experimental_interpreter`)

/cc @chinmaygarde 
/cc @rmacnak-google

**Comment by tvolkert** [comment]
Stack when we crash is unpredictable but does point to an issue with recent changes to dbc:

```
#0	0x000000010183613c in dart::Simulator::Call(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../dart/runtime/vm/simulator_dbc.cc:1749
#1	0x000000010183613c in dart::Simulator::Call(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../dart/runtime/vm/simulator_dbc.cc:1749
#2	0x000000010183604c in dart::Simulator::Call(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../dart/runtime/vm/simulator_dbc.cc:1718
#3	0x0000000101602328 in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../dart/runtime/vm/dart_entry.cc:117
#4	0x00000001015181c8 in ::Dart_Invoke(Dart_Handle, Dart_Handle, int, Dart_Handle *) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../dart/runtime/vm/dart_api_impl.cc:4251
#5	0x00000001011e16d4 in blink::DartInvokeField(_Dart_Handle*, char const*, std::initializer_list<_Dart_Handle*>) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../flutter/tonic/dart_invoke.cc:18
#6	0x000000010196bf34 in blink::Window::BeginFrame(base::TimeTicks) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../sky/engine/core/window/window.cc:133
#7	0x00000001013ae7d0 in blink::SkyView::BeginFrame(base::TimeTicks) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../sky/engine/public/sky/sky_view.cc:89
#8	0x000000010096f544 in sky::shell::Engine::BeginFrame(base::TimeTicks) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../sky/shell/ui/engine.cc:69
#9	0x0000000100967808 in sky::shell::Animator::BeginFrame(long long) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../sky/shell/ui/animator.cc:95
#10	0x0000000100969e80 in base::internal::RunnableAdapter<void (sky::shell::Animator::*)(long long)>::Run(sky::shell::Animator*, long long const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/bind_internal.h:176
#11	0x000000010096ddc8 in base::internal::InvokeHelper<true, void, base::internal::RunnableAdapter<void (sky::shell::Animator::*)(long long)>, base::internal::TypeList<base::WeakPtr<sky::shell::Animator> const&, long long const&> >::MakeItSo(base::internal::RunnableAdapter<void (sky::shell::Animator::*)(long long)>, base::WeakPtr<sky::shell::Animator> const&, long long const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/bind_internal.h:303
#12	0x000000010096dd60 in base::internal::Invoker<base::IndexSequence<0ul>, base::internal::BindState<base::internal::RunnableAdapter<void (sky::shell::Animator::*)(long long)>, void (sky::shell::Animator*, long long), base::internal::TypeList<base::WeakPtr<sky::shell::Animator> > >, base::internal::TypeList<base::internal::UnwrapTraits<base::WeakPtr<sky::shell::Animator> > >, base::internal::InvokeHelper<true, void, base::internal::RunnableAdapter<void (sky::shell::Animator::*)(long long)>, base::internal::TypeList<base::WeakPtr<sky::shell::Animator> const&, long long const&> >, void (long long const&)>::Run(base::internal::BindStateBase*, long long const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/bind_internal.h:343
#13	0x000000010096e45c in base::Callback<void (long long)>::Run(long long const&) const at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/callback.h:396
#14	0x000000010096e2d8 in mojo::Callback<void (long long)>::RunnableAdapter<base::Callback<void (long long)> >::Run(long long) const at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/callback.h:79
#15	0x0000000100dcb58c in mojo::Callback<void (long long)>::Run(long long) const at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/callback.h:62
#16	0x0000000100dce2e4 in vsync::VSyncProvider_AwaitVSync_ForwardToCallback::Accept(mojo::Message*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/gen/mojo/services/vsync/interfaces/vsync.mojom.cc:48
#17	0x0000000100bee778 in mojo::internal::Router::HandleIncomingMessage(mojo::Message*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/router.cc:158
#18	0x0000000100bee28c in mojo::internal::Router::HandleIncomingMessageThunk::Accept(mojo::Message*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/router.cc:70
#19	0x0000000100beb9bc in mojo::ReadAndDispatchMessage(mojo::MessagePipeHandle, mojo::MessageReceiver*, bool*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/message.cc:108
#20	0x0000000100be6bc0 in mojo::internal::Connector::ReadSingleMessage(unsigned int*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/connector.cc:152
#21	0x0000000100be7194 in mojo::internal::Connector::ReadAllAvailableMessages() at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/connector.cc:180
#22	0x0000000100be714c in mojo::internal::Connector::OnHandleReady(unsigned int) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/connector.cc:130
#23	0x0000000100be7070 in mojo::internal::Connector::CallOnHandleReady(void*, unsigned int) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/public/cpp/bindings/lib/connector.cc:120
#24	0x00000001011cf65c in mojo::internal::(anonymous namespace)::OnHandleReady(mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/environment/default_async_waiter.cc:20
#25	0x00000001011cfe34 in base::internal::RunnableAdapter<void (*)(mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int)>::Run(mojo::common::HandleWatcher* const&, void (* const&)(void*, unsigned int), void* const&, unsigned int const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/bind_internal.h:157
#26	0x00000001011cfd10 in base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int)>, base::internal::TypeList<mojo::common::HandleWatcher* const&, void (* const&)(void*, unsigned int), void* const&, unsigned int const&> >::MakeItSo(base::internal::RunnableAdapter<void (*)(mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int)>, mojo::common::HandleWatcher* const&, void (* const&)(void*, unsigned int), void* const&, unsigned int const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/bind_internal.h:293
#27	0x00000001011cfc8c in base::internal::Invoker<base::IndexSequence<0ul, 1ul, 2ul>, base::internal::BindState<base::internal::RunnableAdapter<void (*)(mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int)>, void (mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int), base::internal::TypeList<mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*> >, base::internal::TypeList<base::internal::UnwrapTraits<mojo::common::HandleWatcher*>, base::internal::UnwrapTraits<void (*)(void*, unsigned int)>, base::internal::UnwrapTraits<void*> >, base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(mojo::common::HandleWatcher*, void (*)(void*, unsigned int), void*, unsigned int)>, base::internal::TypeList<mojo::common::HandleWatcher* const&, void (* const&)(void*, unsigned int), void* const&, unsigned int const&> >, void (unsigned int const&)>::Run(base::internal::BindStateBase*, unsigned int const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/bind_internal.h:343
#28	0x0000000100cf27a4 in base::Callback<void (unsigned int)>::Run(unsigned int const&) const at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/callback.h:396
#29	0x0000000100cf927c in mojo::common::HandleWatcher::StateBase::NotifyAndDestroy(unsigned int) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/handle_watcher.cc:347
#30	0x0000000100cf9458 in mojo::common::HandleWatcher::StateBase::NotifyHandleReady(unsigned int) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/handle_watcher.cc:332
#31	0x0000000100cf9420 in mojo::common::HandleWatcher::SameThreadWatchingState::StopWatchingAndNotifyReady(mojo::Handle const&, unsigned int) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/handle_watcher.cc:396
#32	0x0000000100cf9050 in mojo::common::HandleWatcher::SameThreadWatchingState::OnHandleReady(mojo::Handle const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/handle_watcher.cc:386
#33	0x0000000100cf90b4 in non-virtual thunk to mojo::common::HandleWatcher::SameThreadWatchingState::OnHandleReady(mojo::Handle const&) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/handle_watcher.cc:385
#34	0x0000000100cfcb10 in mojo::common::MessagePumpMojo::DoInternalWork(mojo::common::MessagePumpMojo::RunState const&, bool) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/message_pump_mojo.cc:201
#35	0x0000000100cfc374 in mojo::common::MessagePumpMojo::DoRunLoop(mojo::common::MessagePumpMojo::RunState*, base::MessagePump::Delegate*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/message_pump_mojo.cc:157
#36	0x0000000100cfc2d8 in mojo::common::MessagePumpMojo::Run(base::MessagePump::Delegate*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../mojo/message_pump/message_pump_mojo.cc:126
#37	0x0000000100a16388 in base::MessageLoop::RunHandler() at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/message_loop/message_loop.cc:445
#38	0x0000000100a4c2a0 in base::RunLoop::Run() at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/run_loop.cc:55
#39	0x0000000100a15808 in base::MessageLoop::Run() at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/message_loop/message_loop.cc:288
#40	0x0000000100ad1e34 in base::Thread::Run(base::MessageLoop*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/threading/thread.cc:198
#41	0x0000000100ad226c in base::Thread::ThreadMain() at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/threading/thread.cc:248
#42	0x0000000100abb7a4 in base::(anonymous namespace)::ThreadFunc(void*) at /Users/tvolkert/project/flutter/engine/src/out/ios_debug_unopt/../../base/threading/platform_thread_posix.cc:74
```

**Comment by eseidelGoogle** [comment]
You might consider pasting the entire crash log into a public gist, but then only pasting the crashing stack in the bug itself.

**Comment by rmacnak-google** [comment]
CC @zanderso

**Comment by zanderso** [comment]
There are some checked-mode failures in our test suite that I'll investigate that look like they probably have the same cause.

**Comment by zanderso** [comment]
This should be fixed by: https://github.com/dart-lang/sdk/commit/b3e5c5eeed62bf59740ef9a65175da650f3942f9

**Comment by tvolkert** [comment]
Synced to https://github.com/dart-lang/sdk/commit/d265a3db53d15a7739dae4567b64363a46baa056, I'm still getting intermittent crashes in DBC mode (EXC_BAD_ACCESS):

```
#0	0x0000000101603c20 in dart::Instance::CheckedHandle(dart::Zone*, dart::RawObject*) [inlined] at .../dart/runtime/vm/object.h:5407
#1	0x0000000101603bb0 in dart::Instance::CheckedHandle(dart::RawObject*) at .../dart/runtime/vm/object.h:5407
#2	0x00000001015fbd10 in dart::DRT_HelperInlineCacheMissHandlerOneArg(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) [inlined] at .../dart/runtime/vm/code_generator.cc:854
#3	0x00000001015fbd08 in dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments) at .../dart/runtime/vm/code_generator.cc:853
#4	0x00000001018546d8 in dart::Simulator::CallRuntime(dart::Thread*, dart::RawObject**, dart::RawObject**, unsigned int*, long, dart::RawObject**, dart::RawObject**, unsigned long) [inlined] at .../dart/runtime/vm/simulator_dbc.cc:493
#5	0x00000001018546a0 in dart::Simulator::InlineCacheMiss(int, dart::Thread*, dart::RawICData*, dart::RawObject**, dart::RawObject**, unsigned int*, dart::RawObject**, dart::RawObject**) [inlined] at .../dart/runtime/vm/simulator_dbc.cc:571
#6	0x0000000101854698 in dart::Simulator::InstanceCall1(dart::Thread*, dart::RawICData*, dart::RawObject**, dart::RawObject**, dart::RawArray**, dart::RawObjectPool**, unsigned int**, dart::RawObject***, dart::RawObject***) [inlined] at .../dart/runtime/vm/simulator_dbc.cc:611
#7	0x0000000101854698 in dart::Simulator::Call(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) at .../dart/runtime/vm/simulator_dbc.cc:1461
#8	0x00000001018546d8 in dart::Simulator::CallRuntime(dart::Thread*, dart::RawObject**, dart::RawObject**, unsigned int*, long, dart::RawObject**, dart::RawObject**, unsigned long) [inlined] at .../dart/runtime/vm/simulator_dbc.cc:493
#9	0x00000001018546a0 in dart::Simulator::InlineCacheMiss(int, dart::Thread*, dart::RawICData*, dart::RawObject**, dart::RawObject**, unsigned int*, dart::RawObject**, dart::RawObject**) [inlined] at .../dart/runtime/vm/simulator_dbc.cc:571
#10	0x0000000101854698 in dart::Simulator::InstanceCall1(dart::Thread*, dart::RawICData*, dart::RawObject**, dart::RawObject**, dart::RawArray**, dart::RawObjectPool**, unsigned int**, dart::RawObject***, dart::RawObject***) [inlined] at .../dart/runtime/vm/simulator_dbc.cc:611
#11	0x0000000101854698 in dart::Simulator::Call(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) at .../dart/runtime/vm/simulator_dbc.cc:1461
#12	0x000000010161c9cc in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) at .../dart/runtime/vm/dart_entry.cc:117
#13	0x00000001015318e8 in ::Dart_Invoke(Dart_Handle, Dart_Handle, int, Dart_Handle *) at .../dart/runtime/vm/dart_api_impl.cc:4253
#14	0x00000001011d8b48 in blink::DartInvokeField(_Dart_Handle*, char const*, std::initializer_list<_Dart_Handle*>) at .../flutter/tonic/dart_invoke.cc:17
#15	0x0000000101976654 in blink::Window::BeginFrame(base::TimeTicks) at .../sky/engine/core/window/window.cc:133
#16	0x00000001013a92d4 in blink::SkyView::BeginFrame(base::TimeTicks) at .../sky/engine/public/sky/sky_view.cc:89
#17	0x0000000100960090 in sky::shell::Engine::BeginFrame(base::TimeTicks) at .../sky/shell/ui/engine.cc:69
#18	0x0000000100958354 in sky::shell::Animator::BeginFrame(long long) at .../sky/shell/ui/animator.cc:95
```

**Comment by zanderso** [comment]
Yah, sorry, the change above just masked the underlying problem. This should *really* be fixed after https://github.com/dart-lang/sdk/commit/8eb3687bbd71cb936589f42f2bd15381fba97bf3.

**Comment by tvolkert** [comment]
Yep - looks like it's fixed.  Thanks!
