### ISSUE TITLE
[google_maps_flutter] Trying to create an already created platform view

### ISSUE THREAD

**Issue by Pebsie** [flutter/flutter#45695]
Hi,

When using the google_maps_flutter plugin I'm encountering some weirdness. 

When running the app in debug first time everything is fine, but attempts to load the map after a rebuild (just hitting Play on AndroidStudio) the following error is being thrown and the map is blacked out:

```
E/flutter (23023): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (23023): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (23023): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (23023): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (23023): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (23023): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (23023): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (23023): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23023): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (23023): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (23023): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/flutter (23023): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23023): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (23023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (23023): , null)
E/flutter (23023): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (23023): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (23023): <asynchronous suspension>
E/flutter (23023): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (23023): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (23023): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (23023): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (23023): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (23023): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (23023): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (23023): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #25     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3166:14)
E/flutter (23023): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (23023): #27     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (23023): #28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (23023): #29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (23023): #30     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
E/flutter (23023): #31     WidgetsBinding.drawFrame (package:flutter/src/w
```

If I hit the Stop button then rebuild it after a few moments the error is displayed again but the app loads and works just fine. It seems weird that an error is occurring during runtime then reoccurring during a build. Any advice on this? Sorry that I'm not more technically versed with this sort of thing.

**Comment by iapicca** [comment]
Hi @Pebsie 
could you please provide your updated  `flutter doctor -v` ?
Thank you

**Comment by Pebsie** [comment]
I switched from stable to master and this issue is no longer occurring.

**Comment by thiagotalma** [comment]
Same here. I upgraded to the master channel and the error remained.

flutter doctor -v:

```
[√] Flutter (Channel master, v1.13.4-pre.3, on Microsoft Windows [versÃ£o 10.0.18363.535], locale pt-BR)
    • Flutter version 1.13.4-pre.3 at C:\dev\flutter
    • Framework revision bd25f70c66 (7 hours ago), 2019-12-19 09:45:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • ONEPLUS A3000 • e1636bc6 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by cn-Meepo** [comment]
Hi,@thiagotalma! Same here.Have you did this problem?

**Comment by Lavkushwaha** [comment]
same here, didnt found any solution for this

**Comment by Lavkushwaha** [comment]
```
[✓] Flutter (Channel master, v1.13.6-pre.25, on Linux, locale en_IN)
    • Flutter version 1.13.6-pre.25 at /home/asus/Documents/Flutter_SDK/flutter
    • Framework revision b7af5e714d (72 minutes ago), 2019-12-25 23:49:55 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/asus/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • vivo 1723  • 49269ad3   • android-arm64  • Android 9 (API 28)
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by thiagotalma** [comment]
Hello @cn-Meepo ! I also couldn't solve this problem. Let's wait for the expert opinion.

Probably best to open a new issue.

What do you think, @iapicca ?

**Comment by Jenya222** [comment]
I have the same issue

**Comment by hedayet13** [comment]
i have the same issu here ? How to solve it ?

**Comment by sky126** [comment]
I have the same issue

**Comment by almodoen** [comment]
Same here from long time, but i'm trying to solve it now ...
i didn't try Master channel yet too ..

**Comment by Lavkushwaha** [comment]
[Stackoverflow issue link](https://stackoverflow.com/questions/59508799/flutter-google-maps-trying-to-create-an-already-created-platform-view-view-id)

**Comment by arfian14** [comment]
I have the same issue

**Comment by mohamedahmedhassan00** [comment]
i have the same issue

**Comment by 0DEX** [comment]
i have the same issue

**Comment by vishalgaurav610** [comment]
I have the same issue, anyone got solution for this one?

**Comment by iapicca** [comment]
Hi all,
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by cn-Meepo** [comment]
@iapicca hi!
flutter doctor -v
D:\project\juant_base>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.14393], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\java\flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\java\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\java\android-sdk
    • Java binary at: C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.5662.53
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] Connected device (1 available)
    • MI 6 • bc840644 • android-arm64 • Android 9 (API 28)

• No issues found!





E/flutter (31354): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (31354):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (31354):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (31354):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (31354):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (31354):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (31354):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (31354):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31354):      at android.os.MessageQueue.next(MessageQueue.java:332)
E/flutter (31354):      at android.os.Looper.loop(Looper.java:168)
E/flutter (31354):      at android.app.ActivityThread.main(ActivityThread.java:6878)
E/flutter (31354):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31354):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (31354):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/flutter (31354): , null)
E/flutter (31354): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (31354): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (31354): <asynchronous suspension>
E/flutter (31354): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (31354): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (31354): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (31354): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (31354): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (31354): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (31354): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31354): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (31354): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31354): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
E/flutter (31354): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31354): #13     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (31354): #14     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (31354): #15     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (31354): #16     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (31354): #17     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (31354): #18     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (31354): #19     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
E/flutter (31354): #20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
E/flutter (31354): #21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (31354): #22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (31354): #23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (31354): #24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
E/flutter (31354): #25     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (31354): #26     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (31354): #27     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (31354): #28     _invoke (dart:ui/hooks.dart:259:10)
E/flutter (31354): #29     _drawFrame (dart:ui/hooks.dart:217:3)
E/flutter (31354):

**Comment by devilishWei** [comment]
I have the same issue

**Comment by Lavkushwaha** [comment]
@iapicca

flutter run --verbose

```
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/746611116116959, name: main, number: 746611116116959}, timestamp:
1577706539960, extensionRPC: ext.flutter.inspector.isWidgetCreationTracked}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/746611116116959, name: main, number: 746611116116959}, timestamp:
1577706539960, extensionRPC: ext.flutter.inspector.screenshot}}
[+2148 ms] I/flutter ( 9922): location permission PermissionStatus.granted
[  +19 ms] E/flutter ( 9922): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view
id: 0
[   +1 ms] E/flutter ( 9922): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
[        ] E/flutter ( 9922): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
[        ] E/flutter ( 9922): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
[        ] E/flutter ( 9922): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/flutter ( 9922): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/flutter ( 9922): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] E/flutter ( 9922): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter ( 9922): 	at android.os.MessageQueue.next(MessageQueue.java:330)
[        ] E/flutter ( 9922): 	at android.os.Looper.loop(Looper.java:169)
[        ] E/flutter ( 9922): 	at android.app.ActivityThread.main(ActivityThread.java:7135)
[        ] E/flutter ( 9922): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter ( 9922): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
[        ] E/flutter ( 9922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
[        ] E/flutter ( 9922): , null)
[        ] E/flutter ( 9922): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter ( 9922): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] E/flutter ( 9922): <asynchronous suspension>
[        ] E/flutter ( 9922): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
[        ] E/flutter ( 9922): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
[        ] E/flutter ( 9922): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
[        ] E/flutter ( 9922): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
[        ] E/flutter ( 9922): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
[        ] E/flutter ( 9922): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter ( 9922): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #9      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
[        ] E/flutter ( 9922): #10     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] E/flutter ( 9922): #11     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
[        ] E/flutter ( 9922): #12     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
[        ] E/flutter ( 9922): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter ( 9922): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter ( 9922): #17     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
[        ] E/flutter ( 9922): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter ( 9922): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter ( 9922): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #23     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
[        ] E/flutter ( 9922): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #25     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
[        ] E/flutter ( 9922): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter ( 9922): #27     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
[        ] E/flutter ( 9922): #28     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] E/flutter ( 9922): #29     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
[        ] E/flutter ( 9922): #30     RenderCustomMultiChildLayoutB
[+7766 ms] I/flutter (27545): calling api here 
```

**Comment by zheliazkov** [comment]
I have the same problem too.

**Comment by zacps** [comment]
Also encountering this issue.

<details><summary><code>flutter doctor -v</code></summary>
<p>

```
[√] Flutter (Channel master, v1.13.6-pre.38, on Microsoft Windows [Version 10.0.18362.535], locale en-NZ)
    • Flutter version 1.13.6-pre.38 at C:\tools\flutter
    • Framework revision b28dd0c296 (3 days ago), 2019-12-28 10:33:01 +0800
    • Engine revision 5a730c60d3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 1db1a837f8)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Zac\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.41.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • ONEPLUS A6000 • a21aff4f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</p>
</details>

**Comment by xinoip** [comment]
This only happens for me when i do a full reload while in a page with the GoogleMap. 

<details open>
<summary>flutter doctor -v</summary>
<br>

> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/pionix/development/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/pionix/development/Android
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/pionix/development/Android
    • Java binary at: /home/pionix/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
[!] Android Studio (version 3.5)
    • Android Studio at /home/pionix/development/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)
! Doctor found issues in 1 category.
</details>

**Comment by Chris-CWZ** [comment]
same problem here, anybody has a solution?

**Comment by zacps** [comment]
So I did a bit of digging and I'm pretty sure this is an issue with the `PlatformView` implementation.

From my (probably flawed) understanding:

* After a reload the `AndroidView` is rebuilt (`lib\src\google_map.dart#226`)
* Which gets an ID from [`platformViewsRegistry`](https://api.flutter.dev/flutter/services/platformViewsRegistry.html).[`getNextPlatformViewId()`](https://api.flutter.dev/flutter/services/PlatformViewsRegistry/getNextPlatformViewId.html)
* This ID is `0` because the `platformViewRegistry` is disposed during the reload
* But the `PlatformViewsController` is not disposed (for some reason?) so the [`vdControllers`](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L66) still contains the old platform view

**Comment by hasanhasanov** [comment]
**I'm having the same problem**

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale tr-TR)
    • Flutter version 1.12.13+hotfix.5 at C:\src\Android\flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\ThinkPad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by zacps** [comment]
I tried to find exactly where this regressed but ran into issues because older project templates are often not compatible with new flutter versions.

I wasn't especially thorough and created a minimal new project where I ran into trouble. I found that this did not exhibit the same problem as a new template on some flutter versions.

Concretely, at 39c5f1ea29e351923fb9bce9ec8719b4ca7cf31c a project created from a recent master will fail, but one created from an earlier flutter version will not.

**Comment by rohitiskul** [comment]
Based on @zacps comment, I tried a test project with a simple View with old Flutter (1.9.1+hotfix.6) and this crash does not happen. It uses old `registerWith(Registrar registrar)` `static` method to register the channel.

**Comment by sevekim** [comment]
According to the [API][1], 

> Do not change the camera with this camera update until the map has undergone layout (in order for this method to correctly determine the appropriate bounding box and zoom level, the map must have a size). Otherwise an IllegalStateException will be thrown. 

I don't know how you have it set up, but you can have the `_mapController.complete(controller)` in a `future` and wait for it to finish.

In other words, you need to let the `onMapCreated` finish its thing before moving around on the map.

For example,

      ...
      onMapCreated: processOnMapCreated,
      ...

     Future<void> processOnMapCreated(GoogleMapController controller) async {
          await waitForMapToComplete(controller);
    
          //Wait for the map to complete, then do whatever you need to do
          nextThings();    
      }

     Future<void> waitForMapToComplete(GoogleMapController controller) async {
        _mapController.complete(controller);
     }

This should address the issue.

  [1]: https://developers.google.com/android/reference/com/google/android/gms/maps/CameraUpdateFactory

**Comment by raitucarp** [comment]
Sadly, I encounter this issue with WebView too.

**Comment by Zeeshan0201** [comment]
getting same issue!

**Comment by sevekim** [comment]
Based on this [answer](https://stackoverflow.com/a/59608338/4456697), I just put `Completer<GoogleMapController> mapController = Completer();` outside of the google map class, so there is only one key even if the widget gets rebuilt.

So far, it seems to work just fine.

Give it a try.

**Comment by mevos19** [comment]
Solution:
1 -Add a GlobalKey in your constructur:
HomePage({Key key}) : super(key: key);
2 - Create A global Key in the widget parent
GlobalKey key = GlobalKey();
3 - Send the key when you want to Navigate to this page.
Navigator.of(context).push(
MaterialPageRoute(
builder: () => HomePage(
key: _key,
)),
);

**Comment by rashedoz** [comment]
> Solution:
> 1 -Add a GlobalKey in your constructur:
> HomePage({Key key}) : super(key: key);
> 2 - Create A global Key in the widget parent
> GlobalKey key = GlobalKey();
> 3 - Send the key when you want to Navigate to this page.
> Navigator.of(context).push(
> MaterialPageRoute(
> builder: () => HomePage(
> key: _key,
> )),
> );

Can you explain where should I add the key and pass from?

**Comment by javico2609** [comment]
I have the same issue

**Comment by costela2002** [comment]
I have a project using Gmaps, I have the same problem. Time Gmaps works, time the platform bug happens.
Any solution?

**Comment by idulsky** [comment]
Encountered same issue when using GoogleMapController.
`Flutter (Channel master, v1.13.9-pre.59, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.13.9-pre.59 at C:\SDK\flutter_remote
    • Framework revision ab36346af6 (21 hours ago), 2020-01-11 14:20:05 -0500
    • Engine revision 3d37d39d95
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 395daaa3ec)
`

**Comment by cgbrucezjy** [comment]
> Solution:
> 1 -Add a GlobalKey in your constructur:
> HomePage({Key key}) : super(key: key);
> 2 - Create A global Key in the widget parent
> GlobalKey key = GlobalKey();
> 3 - Send the key when you want to Navigate to this page.
> Navigator.of(context).push(
> MaterialPageRoute(
> builder: () => HomePage(
> key: _key,
> )),
> );

What if I'm in a tabview (it's a real case), where I can't pass global key from a navigator

**Comment by scopendo** [comment]
> What if I'm in a tabview (it's a real case), where I can't pass global key from a navigator

An inherited widget should help there.  The [Provider package](https://pub.dev/packages/provider) makes this easy.

**Comment by sevekim** [comment]
According to the [API][1], 

> Do not change the camera with this camera update until the map has undergone layout (in order for this method to correctly determine the appropriate bounding box and zoom level, the map must have a size). Otherwise an IllegalStateException will be thrown. 

I had the same issue and after some debugging, it looks like whenever you hotreload while the map is in view, it will give the error. 

But you can prevent the error if you hot reload after disposing the map. 

In other words, it is there to prevent multiple instances of maps to be active. 

So I would suggest to dispose the map before hot reload while in development. 

In a production version, users won't be able to hot reload thus, they won't encounter the platform issue. 


  [1]: https://developers.google.com/android/reference/com/google/android/gms/maps/CameraUpdateFactory

**Comment by DenisBarzanov** [comment]
The error still gets persists with Flutter v1.13.9

**Comment by bero93** [comment]
I solved the problem by doing two things i don't know which one is the solution exactly:
1- enabled ios map API
2- flutter clean and flutter get packages
hope it help

**Comment by cyanglaz** [comment]
I am trying to reproduce this issue but I couldn't. Here are the steps:

1. Load a flutter app with google map

2. hot reload using `r` on keyboard or hot restart using `shift+r`

3. observed that no error was showing.

I am no flutter master, here's my flutter doctor -v

```
[✓] Flutter (Channel master, v1.14.4-pre.17, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.14.4-pre.17 at /Users/ychris/flutter/flutter
    • Framework revision 320c19e4b9 (2 days ago), 2020-01-21 20:03:02 -0800
    • Engine revision 79f898e61d
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ychris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ychris/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1
```

**Comment by zacps** [comment]
@cyanglaz I created a repo [here](https://github.com/zacps/maps_test) which contains a minimal reproducible example. To run this you will need to add your API key to `AndroidManifest.xml`.

The full instructions are:
1. `flutter create appname`
2. Add `google_maps_flutter: 0.5.21+15` to `pubspec.yml`
3. Import `google_maps_flutter` and instantiate `GoogleMap` somewhere in the widget tree
4. Run the app on an Android device or emulator
5. Restart (**not reload**) the app
6. `IllegalStateException`

**Comment by ishara** [comment]
This is working with ios simulator, not Android,

**Comment by szepetry** [comment]
Same issue here. Hope this gets addressed soon.

**Comment by cgbrucezjy** [comment]
>     The error still persists with `Flutter 1.13.10-pre.65 • channel master`
> It's really annoying, because this error has been with me ever since I started using the [`google_maps_flutter`](https://pub.dev/packages/google_maps_flutter) package.
> 
>     The error occurs during `hot restart` when the Google Map is in view. If, for example, the map is returned from a function and the function returns something else like a Button, the restart works as expected.

I haven't seen this error after I hot reload without google map in the view.  so this might be just an error in development

**Comment by szepetry** [comment]
> > The error still persists with `Flutter 1.13.10-pre.65 • channel master`
> > It's really annoying, because this error has been with me ever since I started using the [`google_maps_flutter`](https://pub.dev/packages/google_maps_flutter) package.
> >     The error occurs during `hot restart` when the Google Map is in view. If, for example, the map is returned from a function and the function returns something else like a Button, the restart works as expected.
> 
> I haven't seen this error after I hot reload without google map in the view. so this might be just an error in development

Ya I tried disposing the maps widget to stop this but couldn't get it to work.

**Comment by manoellribeiro** [comment]
Same issue here.

**Comment by lyseiha** [comment]
Same issues here 
<img width="713" alt="Screen Shot 2020-01-28 at 1 16 54 PM" src="https://user-images.githubusercontent.com/26889046/73240063-75962a80-41d0-11ea-824d-bfbb42e602ce.png">

**Comment by bero93** [comment]
Same issues here

**Comment by mzmmoazam** [comment]
I fixed this issue by using AutomaticKeepAliveClientMixin. In this case, the activity remains alive so the error doesn't occur.

**Comment by matthew-carroll** [comment]
@cyanglaz I would recommend seeing if this issue is resolved by 

https://github.com/flutter/engine/pull/15956

and 

https://github.com/flutter/engine/pull/15979

Those 2 PRs combined addressed a duplicate plugin registration issue. It's possible that this issue is related.

**Comment by cyanglaz** [comment]
@matthew-carroll  Thanks! I tested with master and it seems to be fixed. Can anyone confirm?

**Comment by fanick-ber** [comment]
@cyanglaz  @matthew-carroll  I just stumbled across this issue on stable channel and switching to master resolved the exception.
Thanks! :-)

**Comment by cyanglaz** [comment]
@fanick-ber Thanks for the quick confirmation. I'm going to close the issue as it is fixed on master.

**Comment by zacps** [comment]
I just upgraded (83d4d63a716ec8551f0d59f852a40925ddd73d8a) and I'm still experiencing the issue.

**Comment by szepetry** [comment]
> I just upgraded ([83d4d63](https://github.com/flutter/flutter/commit/83d4d63a716ec8551f0d59f852a40925ddd73d8a)) and I'm still experiencing the issue.

Yes I switched and upgraded to master channel but the problem still exists

**Comment by cyanglaz** [comment]
@zacps @szepetry can you post your `flutter doctor -v`?

**Comment by szepetry** [comment]
> @zacps @szepetry can you post your `flutter doctor -v`?

![image](https://user-images.githubusercontent.com/24851270/73561742-91732800-447f-11ea-8d6a-19cfc45cc6cb.png)

**Comment by cyanglaz** [comment]
@szepetry I still can't reproduce the issue on master. Could you provide a simple step to reproduce? possibly a sample app code?

**Comment by stimms** [comment]
Upgraded to master channel and the error disappeared for me. For anybody who needs the hint (like I did) run 

```
flutter channel master
flutter upgrade
```

**Comment by szepetry** [comment]
This is the project I am working with, The main file just calls this Homepage,dart file in the home parameter. The code is not clean as of now but this does give me `IllegalStateException`
```
import 'package:flutter/material.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'dart:async';
import 'package:geolocator/geolocator.dart';
// import 'package:flutter/services.dart';

Completer<GoogleMapController> _controller = Completer();

Marker marker;

Position _currentPosition;
// var geolocator = Geolocator();

// var locationOptions =
//     LocationOptions(accuracy: LocationAccuracy.high, distanceFilter: 10);

class Homepage extends StatefulWidget {
  @override
  _HomepageState createState() => _HomepageState();
}

class _HomepageState extends State<Homepage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: _FloatingActionButtonWidget(),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
        body: SlidingUpPanel(
            maxHeight: 600,
            minHeight: 100,
            isDraggable: true,
            backdropEnabled: true,
            borderRadius: BorderRadius.only(
                topLeft: Radius.circular(10.0),
                topRight: Radius.circular(10.0)),
            panel: _BottomPanelView(),
            body: _MainBodyStack()));
  }
}

//TODO:Main body of the application
class _MainBodyStack extends StatefulWidget {
  @override
  __MainBodyStackState createState() => __MainBodyStackState();
}

class __MainBodyStackState extends State<_MainBodyStack> {

  void initState(){
    super.initState();
    _getCurrentLocation();
  }

  Future<void> _getCurrentLocation() async {
    // final Geolocator geolocator = Geolocator()..forceAndroidLocationManager;

    Position position = await Geolocator()
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

    setState(() {
      _currentPosition = position;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        FireMap(),
        Align(
          alignment: Alignment.topRight,
          child: IconButton(
            tooltip: "Profile",
            icon: Icon(Icons.person),
            onPressed: () {},
          ),
        ),
        Positioned(
          bottom: 150,
          left: MediaQuery.of(context).size.width - 80,
          child: RawMaterialButton(
            onPressed: () {
              _getCurrentLocation();
            },
            child: Icon(
              Icons.gps_fixed,
            ),
            shape: CircleBorder(),
            elevation: 4.0,
            fillColor: Colors.red,
            padding: EdgeInsets.all(15.0),
          ),
        ),
        _currentPosition != null
            ? Text(
                "LAT: ${_currentPosition.latitude}, LNG: ${_currentPosition.longitude}")
            : CircularProgressIndicator(),
      ],
    );
  }
}

class _FloatingActionButtonWidget extends StatelessWidget {
  const _FloatingActionButtonWidget({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
      backgroundColor: Colors.red,
      onPressed: () {},
      child: Icon(Icons.offline_bolt),
    );
  }
}


class _BottomPanelView extends StatefulWidget {
  const _BottomPanelView({
    Key key,
  }) : super(key: key);

  @override
  __BottomPanelViewState createState() => __BottomPanelViewState();
}

class __BottomPanelViewState extends State<_BottomPanelView> {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Padding(
          padding: EdgeInsets.all(5.0),
        ),
        Divider(
          thickness: 4.0,
          indent: 150,
          endIndent: 150,
        ),
        Padding(
          padding: EdgeInsets.all(5.0),
        ),
        Expanded(child: Text(""),
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}

//TODO: Make bottom panel

//TODO: Integrate maps
class FireMap extends StatefulWidget {
  @override
  _FireMapState createState() => _FireMapState();
}

class _FireMapState extends State<FireMap> {

  CameraPosition _userLocation = CameraPosition(
    // Position position = await Geolocator().getLastKnownPosition(desiredAccuracy: LocationAccuracy.high);
    target: LatLng(12.9747141, 77.6071635),
    zoom: 20,
  );

  @override
  void initState() {
    super.initState();
    _getLocation();
  }

  Future<void> _getLocation() async {
    // final Geolocator geolocator = Geolocator()..forceAndroidLocationManager;

    Position position = await Geolocator()
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);


    setState(() {
      _currentPosition = position;
    });

    GoogleMapController mapController = await _controller.future;

    mapController.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(
      target: LatLng(_currentPosition.latitude, _currentPosition.longitude),
      zoom: 17.0,
      
    )));
  }


  @override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: GoogleMap(
        mapType: MapType.normal,
        initialCameraPosition: _userLocation,

        onMapCreated: (GoogleMapController controller1) async{
          _controller.complete(controller1);
          // controller1 = await _controller.future;
          // mapController = controller;
        },

        // markers: {
        //   // marker,
        // },
      ),
    );
  }
}

```

**Comment by cyanglaz** [comment]
@szepetry What should I do to see the exception? Also, could you try to reduce code to some simpler version if possible?

**Comment by szepetry** [comment]
> @szepetry What should I do to see the exception? Also, could you try to reduce code to some simpler version if possible?

This is the exception I see and I've edited the code to make it shorter above. 

```
Restarted application in 1,121ms.
E/flutter (32049): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (32049):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (32049):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (32049):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (32049):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (32049):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (32049):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (32049):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32049):      at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (32049):      at android.os.Looper.loop(Looper.java:160)
E/flutter (32049):      at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (32049):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32049):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (32049):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (32049): , null)
E/flutter (32049): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (32049): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (32049): <asynchronous suspension>
E/flutter (32049): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (32049): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
E/flutter (32049): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
E/flutter (32049): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (32049): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (32049): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter (32049): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (32049): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:264:13)
E/flutter (32049): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:555:15)
E/flutter (32049): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:264:13)
E/flutter (32049): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #16     RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:487:11)
E/flutter (32049): #17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:582:30)
E/flutter (32049): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #19     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
E/flutter (32049): #20     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (32049): #21     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
E/flutter (32049): #22     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
E/flutter (32049): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (32049): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (32049): #27     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1247:11)
E/flutter (32049): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (32049): #29     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (32049): #30     RenderObject.layout (package:flutter/src/rendering/object.d
```

**Comment by zacps** [comment]
@cyanglaz Minimal reproducible example from my [earlier comment](https://github.com/flutter/flutter/issues/45695#issuecomment-578317561) still works. You can use the `main.dart` from that repo with a new `flutter create` project as well.

<details><summary><code>flutter doctor -v</code></summary>
<p>

```
[√] Flutter (Channel master, v1.14.7-pre.58, on Microsoft Windows [Version 10.0.18362.592], locale en-NZ)
    • Flutter version 1.14.7-pre.58 at C:\tools\flutter
    • Framework revision 83d4d63a71 (19 hours ago), 2020-01-30 18:10:36 -0800
    • Engine revision e5209202fb
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Zac\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1
[√] Connected device (1 available)
    • ONEPLUS A6000 • a21aff4f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</p>
</details>

**Comment by cyanglaz** [comment]
Interesting. @zacps I don't see any exceptions running your example code. I used flutter run to run the app and shift+r to hot restart. I am not using any tools to run the app, just did a `flutter run` on terminal.

My `flutter doctor -v`

```
[✓] Flutter (Channel master, v1.14.7-pre.67, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.14.7-pre.67 at /Users/ychris/flutter/flutter
    • Framework revision 688948b778 (6 hours ago), 2020-01-31 23:03:29 +0530
    • Engine revision 804dca62a1
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)
```

**Comment by thiagotalma** [comment]
Mac....
It may be a Windows-only error?
🤷‍♂️

**Comment by zacps** [comment]
Scratch that, after updating again I can no longer reproduce it. Not sure what happened 🤷‍♂.

**Comment by szepetry** [comment]
> Scratch that, after updating again I can no longer reproduce it. Not sure what happened 🤷‍♂.

I just upgraded again and it started to work. What

**Comment by cyanglaz** [comment]
It seems the issue is resolved after update flutter to master. Closing the issue.

**Comment by danielmessi13** [comment]
I have the same problem too.

**Comment by irvine5k** [comment]
I have the same problem too.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by luckymehndiratta** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (12311): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (12311): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (12311): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (12311): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (12311): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (12311): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (12311): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (12311): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (12311): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (12311): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (12311): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12311): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (12311): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (12311): , null)
E/flutter (12311): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (12311): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (12311): <asynchronous suspension>
E/flutter (12311): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (12311): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (12311): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (12311): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (12311): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (12311): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (12311): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (12311): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (12311): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #13     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (12311): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #15     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (12311): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (12311): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #19     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (12311): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (12311): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (12311): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #25     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:492:13)
E/flutter (12311): #26     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter (12311): #27     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter (12311): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12311): #29     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
E/flutter (12311): #30     RenderSliverPadding.performLayout (package:flutter/src/rendering/

**Comment by raitucarp** [comment]
I think this issue can be reproduced when you are using hot reload.

**Comment by xEyad** [comment]
well, adding a key (unique one) to the widget (not it's state) solved the issue for me.

**Comment by zyllus17** [comment]
> me too had the same issue and flutter clean don't solve the issue for me (flutter version 1.12.13+hotfix 8)
> 
> Adding a key (unique one) to the widget (not it's state) solved the issue for me.

Can you show a code snippet how you used the key to remove the error?

**Comment by xEyad** [comment]
> 
> 
> > me too had the same issue and flutter clean don't solve the issue for me (flutter version 1.12.13+hotfix 8)
> > Adding a key (unique one) to the widget (not it's state) solved the issue for me.
> 
> Can you show a code snippet how you used the key to remove the error?

this the minimum i could use to demonstrate. please note that if their is any syntax error or so. i copied the code through mobile

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

main file
```
void main() => runApp(MyApp());

class MyApp extednds StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Map not crashing demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: LocationScreen(),
    );
  }
}

```

a screenHolder widget
```

class LocationScreen extends StatefulWidget 
{
  final Key _mapKey = UniqueKey();
  @override
  _LocationScreenState createState() => _LocationScreenState();
}

class _LocationScreenState extends State<LocationScreen> 
{
  @override
  Widget build(BuildContext context) 
  {
    return Scaffold(
      appBar: AppBar(title: const Text('Map not crashing demo')),
      body: TheMap(key:widget._mapKey)
    );
  }
}

```

google map code here
```
class TheMap extends StatefulWidget 
{
  ///key is required, otherwise map crashes on hot reload
  TheMap({ @required Key key})
  :
  super(key:key);
  
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<TheMap> 
{
  GoogleMapController _mapController ;
  
  void _onMapCreated(GoogleMapController controller) {
    _mapController = controller;
  }
  @override
  Widget build(BuildContext context) 
  {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: return GoogleMap(
          onMapCreated: _onMapCreated,
          markers: markers,
          initialCameraPosition: CameraPosition(
            target: const LatLng(30.0925973,31.3219982),
            zoom: 11.0,
          ),
        )
    );
  }
}
```

**Comment by flutter2k20** [comment]
I have had this same exception `Unhandled Exception: PlatformException`, in the widget where I am using this Google Maps plugin. 

What I have noticed is, if I do a hot re-load (Shift+R), I always get this exception but doing a restart of the app from the terminal `flutter run` or running the app normally (tapping the app icon and navigating to my google maps screen), I don't get any exception. My guess is, the hot reload is somehow messing up with how flutter and native/plugin code communicate.

My 2cents...

**Comment by AbbasKMoussa** [comment]
This needs to be reopened

**Comment by iapicca** [comment]
Hi @AbbasKMoussa @flutter2k20 
as mentioned [above](https://github.com/flutter/flutter/issues/45695#issuecomment-584011023) would be ideal to open a new issue 
addressing the specific circumstances
in which the issue occurs,
keeping in mind that the current one 
apparently has been [fixed in master](https://github.com/flutter/flutter/issues/45695#issuecomment-581602456)

**Comment by mathshenry** [comment]
> solved

Hi, could you please give us more specific details about what you did to solve this? thx

**Comment by ProgrammingLife** [comment]
Faced the same problem on linux after upgraded Flutter & Dart to the latest versions.

**Comment by jamesmwase** [comment]
Same issue here just after I have created new project in which I'm using the google map api's.

**Comment by OmkarSsawant** [comment]
> Mac....
> It may be a Windows-only error?

Nope

**Comment by OmkarSsawant** [comment]
I am getting the same error . On hot restart

**Comment by eqoram** [comment]
I am also getting this error in the emulator by hot reloading the app and on some older android devices when i restart the app after some time. This wont happen after switching to the master branch but as this is the most unstable branch and you shouldnt use it in production this is not really a fix.

**Comment by rahmanrezaee** [comment]
> I think this issue can be reproduced when you are using hot reload.
their not problem after build apk???
