### ISSUE TITLE
Buttons break on 11th click in Flutter Web

### ISSUE THREAD

**Issue by laoal11** [flutter/flutter#45792]
## Steps to Reproduce

1. Create a new Flutter web project
2. Add a FlatButton, MaterialButton or RaisedButton
3. Implement their onPressed() methods
4. On the 11th time the function is called, the function / button breaks

Here is an example file: https://gist.github.com/laoal11/64d0f9091f2c75456d1e2ba9708c934f

**Target Platform:Web**
**Target OS Windows 10/Google Chrome (78.0.3904.108):**

## Logs

The Google Chrome console log (Flutter does not throw an error):

Uncaught TypeError: Cannot read property 'Symbol(dartx.remove)' of null
    at _engine.DesktopSemanticsEnabler.new.tryEnableSemantics (semantics_helper.dart:124)
    at _engine.SemanticsHelper.new.shouldEnableSemantics (semantics_helper.dart:43)
    at _engine.EngineSemanticsOwner.__.receiveGlobalEvent (semantics.dart:1349)
    at HTMLElement.<anonymous> (pointer_binding.dart:172)

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.12.16-pre.19, on Microsoft Windows [Version 10.0.17763.864], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.40.2)
[√] Connected device (2 available)

Once the error was thrown, the application is frozen and can not be used any further.

**Comment by mbagusrd** [comment]
same here

**Comment by laoal11** [comment]
For me, this was fixed by the latest Flutter update

**Comment by s9th** [comment]
for me this is still relevant.
I have a tabbar and none of the buttons mentioned above. On the ninth click switching between tabs the application hangs. In the debug mode I get the same error. Moreover this error starts repeating endlessly whenever I move my mouse across the page.
The crash can be seen here https://album-tracker-d87a6.firebaseapp.com/#/ (switch between tabs n the top for several seconds and the page stops responding)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.12.16, on Microsoft Windows [Version 10.0.18362.476], locale uk-UA)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)
[√] Connected device (2 available)

• No issues found!

**Comment by ethael** [comment]
this still occures in current latest dev: 1.12.16. I have created new ticket linked to this one to reopen then issue: #46069
