### ISSUE TITLE
Text and icons do not render correctly in CanvasKit on older Android devices

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#46237]
On older Android devices, with the latest Chrome browser installed, text and icons either do not render correctly, or not at all, when built with CanvasKit support

Consider the test web app at http://mjohnsullivan.github.io/flutter_web_test

On a Pixel 2, it renders correctly:

![Screenshot_20191206-095242](https://user-images.githubusercontent.com/102488/70344462-aaa88100-180e-11ea-8d1b-8d1b67e7dc8f.png)

On a Nexus 6, the text and icons do not render:

![Screenshot_20191206-095306](https://user-images.githubusercontent.com/102488/70344490-b7c57000-180e-11ea-8184-fdd29aabb682.png)

Here's the details on the Nexus 6:

Device: Nexus 6
OS: Android 7.1.1
Chrome version: 78.0.3904.108
Flutter: Channel master, v1.12.17-pre.80, on Mac OS X 10.14.6 18G1012, locale en-US

**Comment by yjbanov** [comment]
@kjlubick we do not see any errors on our side. We're suspecting a CanvasKit bug.

**Comment by mjohnsullivan** [comment]
Happy to give you the Nexus 6 device if that would help testing.

**Comment by yjbanov** [comment]
This is reproducible on Nexus 5X as well, thanks.

**Comment by kjlubick** [comment]
Can you identify which CanvasKit calls are being invoked?  Is this using the Paragraph bits?

**Comment by yjbanov** [comment]
> Can you identify which CanvasKit calls are being invoked? Is this using the Paragraph bits?

@hterkelsen is there a way to get this instrumentation? Maybe instrument all JS-interop calls? I imagine it could be something similar to our [_debugDumpPaintCommands](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/recording_canvas.dart#L62).

> (silly question) Is surface.flush() being called correctly?

We do [flush the surface](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/compositor/surface.dart#L116).

**Comment by markusaksli-nc** [comment]
I can't get anything to load on Android 8.1.0 and 7.1.1 emulator with `--release --dart-define=FLUTTER_WEB_USE_SKIA=true` on the latest master `1.22.0-2.0.pre.93`.
<img src="https://user-images.githubusercontent.com/68219924/91446431-27d5c380-e880-11ea-924a-884745acf282.png" height="500" /><img src="https://user-images.githubusercontent.com/68219924/91446429-273d2d00-e880-11ea-854e-f1d880116841.png" height="500" />
Android 10 emulator for reference
<img src="https://user-images.githubusercontent.com/68219924/91446471-302dfe80-e880-11ea-8ca6-fe62137c40e0.png" height="500" />

<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.ac_unit),
                  Icon(Icons.refresh),
                  Icon(Icons.audiotrack),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.93, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.93 at C:\Development\flutter_master
    • Framework revision f35a8b7470 (4 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

**Comment by aseef17** [comment]
Are there any updates for this issue?
I understand that Flutter Web is not stable yet but the data itself not appearing on some devices is something that should be resolved soon 😅

**Comment by exaby73** [comment]
I can still reproduce this issue on Android API 25 (7.1.1) emulator. The following are the error logs from the chrome devtools:

<details>
<summary>Error logs</summary>

```console
flutter.js:335 Uncaught SyntaxError: Unexpected token ...
VM29:46 Uncaught ReferenceError: _flutter is not defined
    at VM29:46:7
```

</details>

Updating Chrome to the latest version available on the Play Store (107.0.5304.91) doesn't solve the issue.
