### ISSUE TITLE
Error when updating flutter to 1.12.13

### ISSUE THREAD

**Issue by komputerboy** [flutter/flutter#46573]
Somehow after i updating my flutter to 1.12.13 hotfix 3, i got this following error:

```
Launching lib\main.dart on Redmi 4X in debug mode...
E/flutter (26144): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (26144):
F/flutter (26144): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
E/flutter (28979): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (28979):
F/flutter (28979): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
E/flutter (29335): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (29335):
F/flutter (29335): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
E/flutter (29399): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (29399):
F/flutter (29399): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
√ Built build\app\outputs\apk\debug\app-debug.apk.
Lost connection to device.
Exited (sigterm)
```

But, there is no problem with the application though. 

## Steps to Reproduce
1. Upgrade flutter to 1.12.13 hotfix 3
2. start debug

**Target Platform:**
Android / VSCode
**Target OS version/browser:**
Windows 7
**Devices:**
Android - arm64 physical device

### Flutter run --verbose
```
[  +86 ms] executing: [H:\kuliah\sandroid\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +347 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] 57f2df76d75cff290cbe2765b07db1ad3e67b50d
[   +2 ms] executing: [H:\kuliah\sandroid\flutter\] git describe --match v*.*.* --first-parent --long --tags
[+1272 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.3-0-g57f2df76d
[  +28 ms] executing: [H:\kuliah\sandroid\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +98 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [H:\kuliah\sandroid\flutter\] git ls-remote --get-url origin
[  +91 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +233 ms] executing: [H:\kuliah\sandroid\flutter\] git rev-parse --abbrev-ref HEAD
[ +132 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +575 ms] executing: H:\kuliah\sandroid\sdk64\platform-tools\adb.exe devices -l
[  +70 ms] Exit code 0 from: H:\kuliah\sandroid\sdk64\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +34 ms] No supported devices connected.
[  +34 ms] "flutter run" took 840ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///H:/kuliah/sandroid/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
Analyzing abuba_iot...
No issues found! (ran in 13.6s)
```

```
[√] Flutter (Channel beta, v1.12.13+hotfix.3, on Microsoft Windows [Version 6.1.7601], locale id-ID)
    • Flutter version 1.12.13+hotfix.3 at H:\kuliah\sandroid\flutter
    • Framework revision 57f2df76d7 (3 days ago), 2019-12-05 21:23:21 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0
```

**Comment by iapicca** [comment]
Hi @komputerboy 
I need to ask, did you run `flutter clean` on your project?
thank you

**Comment by robertohuertasm** [comment]
Same issue here. Flutter clean, removed `.pub-cache` just in case... still looking for a solution. @komputerboy are you using any custom font? `CustomIcons.ttf`?

**Comment by milano23** [comment]
Same issue here.  I have run flutter clean and the issue still persists.  I am using CustomIcons.tff but it is working fine. No crashes when i go to the page using those icons.  

When i remove my Lexia font i downloaded from the web my application is no longer crashing.  There seems to be an issue with this font and the new upgrade with flutter.

**Comment by robertohuertasm** [comment]
Fixed it. It had to do with the name of the font. It had spaces in it. Remove them and it will work! 😊

**Comment by milano23** [comment]
@robertohuertasm Thank you.  That did fix the crashes.  I am able to use my previously downloaded font. 

Unfortunatley i am still receiving the following errors:
```
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
[FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
[FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
```

I have replaced my old fonts with google font OpenSans and i still receiving those errors, but the app is not crashing.  

Thanks again for suggesting to fix the spaces in the names.

**Comment by komputerboy** [comment]
i update it again to `1.12.13 + hotfix 6`
then, i run `flutter clean` now it is not showing any error again

**Comment by josedaniel-cb** [comment]
I solved it updating to v1.13.5 (dev channel)
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.13.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

`flutter version v1.13.5`
`flutter doctor`

**Comment by Gyoko** [comment]
Switching to beta 1.13.6 fixed the issue. I hate the fact that oftentimes beta is safer than 'stable' releases. But even their docs say that the diligence in testing isn't that different between the two channels, so feel free to switch
