### ISSUE TITLE
Flutter 1.12.13: wrong error message when building an app

### ISSUE THREAD

**Issue by Den163** [flutter/flutter#46815]
When building an app, there is an unrelated error message from the previous build on Android emulator. 

Steps to reproduce:
1. Create a new app.
2. Build it on Android emulator.
3. Change code to allow some runtime error (in my case null ref exception) and see the error log in the console.
4. Fix the runtime error to fully work code
4. Stop the Flutter process.
5. Build it again on Android. While building an app you can see an error log message from previous app starting

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code, 64-bit edition (version 1.40.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by vkammerer** [comment]
Same here. I have just upgraded to `1.12.13+hotfix.5` and noticed that logs of previous debugging sessions remain.

Flutter doctor:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B2106, locale en-NZ)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

• No issues found!
```

I have been searching for this issue for two hours but can't find anything related to this precise issue.

**Comment by DogeeeXD** [comment]
Same here. Build was successful before upgrading to v1.12.xx, after upgrade and I run build, it shows previous debugging log when I haven't fixed some bugs in the code.

**Comment by cataCostea** [comment]
Same here, the logs from previous debug session remain and they are showed in terminal on new app run.
flutter doctor:
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17134.1184], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)
[√] Connected device (1 available)

• No issues found!

**Comment by zanderso** [comment]
@blasten

**Comment by cataCostea** [comment]
any updates on this problem?

**Comment by IpotoniC** [comment]
same here

**Comment by Den163** [comment]
Is there any progress on the issue?

**Comment by wizdigitech** [comment]
same here, glad i am not the only one. all the old print() statement still showing in the console after delete days ago.

**Comment by workerbee22** [comment]
same here AS 3.5.3 Flutter 1.12.13+hotfix6 (Beta channel)

**Comment by AmareeshBP** [comment]
Same problem here, so I downgraded to v1.19.1+hotfix6

**Comment by dnfield** [comment]
As a work around, if you run `adb logcat -c` before launching your app, it will clear out old messages.

Be warned that it also clears previous log messages in general.

**Comment by vkammerer** [comment]
@dnfield thank you for the tip, do you know if there's any way to setup Android Studio so that this runs automatically before the app is launched?

**Comment by dnfield** [comment]
I don't work with that IDE much, but someone like @jacob314 might know.

**Comment by jacob314** [comment]
We've also seen what looks like a similar issue reported on the IntelliJ plugin
https://github.com/flutter/flutter-intellij/issues/4266
You can edit the run configuration in Android Studio to execute arbitrary external tools before each run.
![image](https://user-images.githubusercontent.com/1226812/72104361-1d11f280-32e0-11ea-81ac-1950ed3ac11c.png)

**Comment by vkammerer** [comment]
thank you @jacob314 , I just implemented this quickfix and it will do the trick until the issue is actually resolved. For anyone else interested in this solution with Android Studio, here is a more detailed list of steps you can take to implement it.
- click `Run External tool` as seen on the screenshot of the comment above
- click `+` to add a new tool
- enter the ADB path in the `Programm` field. (an easy way to get the adb path is to simply open a terminal and run `adb` in it. the first message it should log is `Installed as PATH`) <img width="452" alt="Screen Shot 2020-01-10 at 10 26 56 AM" src="https://user-images.githubusercontent.com/1177483/72106265-e72e4600-3393-11ea-9e18-7c936f16dc75.png">
- enter `logcat -c` in the `Arguments` field. Your screen should look like this: <img width="497" alt="Screen Shot 2020-01-10 at 10 24 42 AM" src="https://user-images.githubusercontent.com/1177483/72106244-e0073800-3393-11ea-86b9-cb82ff318859.png">
- click OK

**Comment by deandreamatias** [comment]
In Visual Studio, I make a equivalent implementation.

- In `.vscode/launch.json` write this:
<details>
    <summary>Code</summary>
    <pre>
<code> 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug",
            "preLaunchTask": "Clean",
        }
    ]
}
</code>
    </pre>
</details>

- With this, also make a `.vscode/task.json` file like this:
<details>
    <summary>Code</summary>
    <pre>
<code> 
{
    "version": "0.2.0",
    "configurations": [
        {
            "label": "Clean",
            "type": "shell",
            "command": "adb logcat -c",
            "group": "none",
            "promptOnClose": true,
            "presentation": {
                "clear": true,
                "reveal": "silent",
                "panel": "dedicated",
            }
        }
    ]
}
</code>
    </pre>
</details>

- Now when run a debug aplication, this task clean the log before build

**Comment by devoncarew** [comment]
I closed the associated IntelliJ bug, but note that that issue had 4 upvotes.

**Comment by dominic-deantonio** [comment]
Hello everyone, I was experiencing this issue as well after deleting older projects. One solution I found was to wipe the data from my AVD device (emulator) then reopen it. The logs from the previous builds did not reappear after that. Those are projects I also deleted from my windows file though, so if you need to keep them, I am not sure it will work.

**Comment by AmareeshBP** [comment]
This issue is fixed in  [flutter version 1.12.13+hotfix8](https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.8-stable.zip)

**Comment by vkammerer** [comment]
@Den163 this issue should be closed since it's been fixed

**Comment by huymichael** [comment]
I'm using Flutter 1.12.13+hotfix.8 but still seeing these logs when running the app guys,
![image](https://user-images.githubusercontent.com/9861551/76188453-a7a49e80-620a-11ea-83bd-bd230162e719.png)

**Comment by AmareeshBP** [comment]
> I'm using Flutter 1.12.13+hotfix.8 but still seeing these logs when running the app guys,
> ![image](https://user-images.githubusercontent.com/9861551/76188453-a7a49e80-620a-11ea-83bd-bd230162e719.png)

Is that the logs of the app that you are currently running or logs of some other app that you have run previously ?

**Comment by huymichael** [comment]
@AmareeshBP  surely that log on current running app, dunno every touch on the screen It also has this logline, any way to remove completely this log and previous log?
![image](https://user-images.githubusercontent.com/9861551/76189331-fd7a4600-620c-11ea-98d4-0b8a145f3728.png)

**Comment by AmareeshBP** [comment]
> @AmareeshBP surely that log on current running app, dunno every touch on the screen It also has this logline, any way to remove completely this log and previous log?
> ![image](https://user-images.githubusercontent.com/9861551/76189331-fd7a4600-620c-11ea-98d4-0b8a145f3728.png)

@huymichael Sorry this problem is off topic. I suggest you to create new issue to discuss this.

**Comment by huymichael** [comment]
@AmareeshBP  anyway for me to delete all previous app log while running another app?

**Comment by AmareeshBP** [comment]
> @AmareeshBP anyway for me to delete all previous app log while running another app?

@huymichael  https://github.com/flutter/flutter/issues/46815#issuecomment-571678229

**Comment by jonahwilliams** [comment]
Marking as fixed, since we hotfixed this
