### ISSUE TITLE
Android add-to-app build fails when using platform plugin that supports Desktop or Web

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#47055]
When building an existing app and embedding flutter, and using the latest version of the `url_launcher` plugin, the build will fail because the `url_launcher_web` and `url_launcher_macos` will get built by gradle, when building task ` assembleAndroidTest`.

```
> Task :url_launcher_web:transformClassesWithDexBuilderForDebugAndroidTest FAILED

...

> Task :url_launcher_macos:transformClassesWithDexBuilderForDebugAndroidTest FAILED

```

It's important to note the combination of using a plugin that supports multiple platforms, and building the ` assembleAndroidTest` task causes this problem. It basically prevents us from building our Debug flavors without tweaking the pubspec.yaml file of the plugin.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/danny.valente/Library/flutter/1.12.13+hotfix.5-stable
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by iapicca** [comment]
Hi @dannyvalentesonos 
can you please provide your `flutter run --verbose`?
Thank you

**Comment by dannyvalentesonos** [comment]
@iapicca This is an add2app scenario. We are basically building a Flutter module. Doesn't `flutter run` actually build the host app and run it? That does not work in our situation.
This bug causes the build itself to fail for existing app integration scenarios.
Please advise what `flutter run` will give and if it's needed?
Thanks.

**Comment by xster** [comment]
@blasten can you take a look?

**Comment by blasten** [comment]
I think this is already fixed. Would you mind trying again?

**Comment by dannyvalentesonos** [comment]
@blasten I still see the same build errors with the latest on the master branch.

**Comment by yjbanov** [comment]
@blasten can you please set an appropriate milestone to this issue?

**Comment by xster** [comment]
@blasten is OOO currently. @amirh may have some context too.

**Comment by amirh** [comment]
Which versions of the url_launcher packages are used? (You can check in pubspec.lock) can you try running 'flutter pub upgrade' to make sure you have the latest versions?

**Comment by dannyvalentesonos** [comment]
We are using the url_launcher 5.4.1. The issue is that the latest versions support multiple platforms. When we download the plugin and have it saved locally, changing the pubspec.yaml of the plugin like so allows the build to succeed:
```
name: url_launcher
description: Flutter plugin for launching a URL on Android and iOS. Supports
  web, phone, SMS, and email schemes.
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
version: 5.4.1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.urllauncher
    iosPrefix: FLT
    pluginClass: UrlLauncherPlugin

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

```

**Comment by dannyvalentesonos** [comment]
@amirh Ok I figured out the issue.
So, any plugin that has an Android platform component, we always have to download them and use them locally, because we need to modify their build.gradle files to add
```
android {
        compileOptions {
            sourceCompatibility 1.8
            targetCompatibility 1.8
        }
    }
```

Now, the url_launcher has a macos and web platform plugin. And I see that they had the extra noop /Android directory added. But turns out, if I download them both and use them locally, I can change their build.gradle files as well to add the above lines, and now the build succeeds.

I've been really surprised that the plugins have been released without those lines in their respective build.gradle files all this time and no one has complained. They have never worked for us like that ever. In fact, the flutter package itself had to add those lines to the flutter.gradle file.

If all the plugins could get updated to have those extra lines in their build.gradle files, everything would just work perfectly.

Do you think there's a possibility to get that done?

Thanks!

**Comment by dannyvalentesonos** [comment]
It might also help to explain why those lines are needed btw..
With the Add2App embedding API, there's a class in the API that causes an error, unless building with Java 1.8

Here's the error
```
Caused by: com.android.tools.r8.utils.AbortException: Error: Default interface methods are only supported starting with Android N (--min-api 24): boolean io.flutter.embedding.android.SplashScreen.doesSplashViewRememberItsTransition()
```

So this is specific to people who use these plugins with the Add2App scenario.

**Comment by kf6gpe** [comment]
Touching for triage 2020 experiment.

**Comment by dannyvalentesonos** [comment]
@blasten @amirh Any thoughts?

**Comment by blasten** [comment]
@dannyvalentesonos I was unable to reproduce this issue.

Here's what I did:
* added `url_launcher: 5.4.1` to the module's pubspec.yaml.
* ran `flutter pub get` in the module working directory to fetch the packages.
* used include_flutter.groovy
* Ensured the host app `build.gradle` contains:
```
   android {
       compileOptions {
           sourceCompatibility 1.8
           targetCompatibility 1.8
        }
   }
```
* built the host app APK `./gradlew app:assembleRelease`.

I'm not sure what is different or if this issue was already fixed. Could you please update the issue?

**Comment by dannyvalentesonos** [comment]
@blasten Thanks for looking into this. If I recall, you might have to build Debug to see the error. 
Also, you probably need to have code in the Android existing app that tries to set up a Flutter activity as well, seeing the compilation error is within the embedding code that gets pulled into the existing app.

**Comment by blasten** [comment]
I'm still unable to reproduce this issue. I used the add-to-app example https://github.com/flutter/samples/tree/master/add_to_app/android_fullscreen/app/src/main/java/dev/flutter/example/androidfullscreen. I'm able to build debug/release and launch it on the device successfully even if the module has a dependency on `url_launcher: 5.4.1` using Flutter `v1.12.13+hotfix.5`.  Would you mind verifying if this is still an issue and if yes, provide the steps to repro this issue?

**Comment by dannyvalentesonos** [comment]
Thanks @blasten . I've removed our workaround and it does seem to be working now. I'm really not sure what has changed as the versions are all the same... I'm going to see if any build failures start occurring in the next few days and will report back.
Thanks again.

**Comment by dannyvalentesonos** [comment]
Scratch that @blasten , we are still seeing the errors.
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':url_launcher_macos:mergeExtDexDebugAndroidTest'.

...

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':url_launcher_macos:debugAndroidTestRuntimeClasspath'

...

Caused by: com.android.tools.r8.utils.AbortException: Error: Default interface methods are only supported starting with Android N (--min-api 24): boolean io.flutter.embedding.android.SplashScreen.doesSplashViewRememberItsTransition()
```

I think it fails for me for debug builds only because we also run the `assembleAndroidTest` task in our Debug builds.

**Comment by blasten** [comment]
@dannyvalentesonos Would it be possible to share a repo where this issue can be reproduced? It's not clear to me if this is an issue in Flutter or something else in the host app project.

**Comment by dannyvalentesonos** [comment]
@blasten I'm going to attempt to separate those 2 build tasks, which I think will fix my problem. I'll report back here once I confirm.
Thanks.

**Comment by dannyvalentesonos** [comment]
@blasten Can you run your test by using the following command instead:
`./gradlew assembleDebug assembleAndroidTest`

We have a few things we add dependencies for in our build.gradle file, such as 
```
    androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:$espressoVersion"
```
When gradle starts building assembleAndroidTest, the flutter builds start to fail.
The weird thing is that I can find files in `.android/Flutter/build/intermediates/merged_native_libs/debugAndroidTest/out/lib`

**Comment by dannyvalentesonos** [comment]
@blasten I've got a super simple repro. 
1. Unzip the attached file.
2. In Add2AppTest/flutter_module
  run `flutter build bundle`
3. In Add2AppTest/Add2AppTest
  run `gradle assembleDebug assembleAndroidTest`

This will cause the failure to appear.

**Comment by dannyvalentesonos** [comment]
[Add2AppTest_failure.zip](https://github.com/flutter/flutter/files/4093078/Add2AppTest_failure.zip)

**Comment by dannyvalentesonos** [comment]
[Add2AppTest_failure.zip](https://github.com/flutter/flutter/files/4093096/Add2AppTest_failure.zip)

**Comment by blasten** [comment]
@dannyvalentesonos thanks for sharing. I was able to repro the issue if I run:
`gradle assembleAndroidTest`. However, it doesn't repro if I run `gradle app:assembleAndroidTest`. I diffed the execution graph (`assembleAndroidTest` in the left and `app:assembleAndroidTest` in the right), https://www.diffchecker.com/oTgCrznc.  I'm not sure what is going on in this case, but it's not due to the web/macOS plugin. 

The task that is failing is `:url_launcher:mergeExtDexDebugAndroidTest`:
```
> Transform artifact lifecycle-common-java8.jar (androidx.lifecycle:lifecycle-common-java8:2.0.0) with DexingNoClasspathTransform
AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)","sources":[{}],"tool":"D8"}

> Transform artifact flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695) with DexingNoClasspathTransform
AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): boolean io.flutter.embedding.android.SplashScreen.doesSplashViewRememberItsTransition()","sources":[{}],"tool":"D8"}

> Task :url_launcher:mergeExtDexDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':url_launcher:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':url_launcher:debugAndroidTestRuntimeClasspath'.
   > Failed to transform artifact 'flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=16, org.gradle.usage=java-runtime-jars}.
      > Execution failed for DexingNoClasspathTransform: /Users/egarciad/.gradle/caches/transforms-2/files-2.1/8daea69f7e177e03daa888005182f38c/jetified-flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.jar.
         > Error while dexing.
   > Failed to transform artifact 'lifecycle-common-java8.jar (androidx.lifecycle:lifecycle-common-java8:2.0.0)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=16, org.gradle.usage=java-runtime-jars}.
      > Execution failed for DexingNoClasspathTransform: /Users/egarciad/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common-java8/2.0.0/52cb9efc663d8bebc82f8979a7da30938bd05611/lifecycle-common-java8-2.0.0.jar.
         > Error while dexing.
```

**Comment by dannyvalentesonos** [comment]
Thanks @blasten. I know it's not the web or macos plugin that are the problem specifically. It's the fact that the plugins fail without having the extra java version options set in their build.gradle files, and after all the digging, I narrowed it down to the fact that it's because of the assembleAndroidTest. The reason this is hitting me now is because I have always added the java version options in the build.gradle files of the plugins I use, but now they include other platform specific plugins (such as macos and web) and those started failing my build.

I will try with the `app:assembleAndroidTest` and see if it works for our app. Is this what you suggest? Is that a temporary workaround?

Do you need anything else from me at the moment?

Thanks

**Comment by dannyvalentesonos** [comment]
@blasten I can confirm that building our app when we pass `app:assembleAndroidTest` works with no errors and I no longer need to add 
```
android {
        compileOptions {
            sourceCompatibility 1.8
            targetCompatibility 1.8
        }
    }
```

in all the plugin build.gradle files.

Should this bug get closed? Or is there something that you think can be done that doesn't need to add the `app:`?

**Comment by blasten** [comment]
> Should this bug get closed? Or is there something that you think can be done that doesn't need to add the app:?

Sounds good. In your case, I don't think calling `assembleAndroidTest` directly provides any advantage over `:app:assembleAndroidTest`.
