### ISSUE TITLE
TextField regains focus when dropdown is opened and closed

### ISSUE THREAD

**Issue by roxifas** [flutter/flutter#47128]
## Steps to Reproduce
1. Focus a TextField by tapping it
2. Open a dropdown menu by tapping DropdownButton, keyboard closes and the TextField looks unfocused (border color changes)
3. Close the menu by either selecting an option, or by tapping outside the menu's area
4. Now the focus returns to the TextField and the keyboard opens

I would expect that after closing the dropdown menu, the previously focused TextField would not regain focus. If this is actually normal and expected behaviour I would at least appreciate help in finding a workaround for this behaviour.

<details>
<summary>Minimal code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _State createState() => _State();
}

class _State extends State<MyHomePage> {
  int dropdownValue;
  @override
  Widget build(BuildContext context) {
    final items = [1, 2, 3]
        .map((i) => DropdownMenuItem(child: Text(i.toString()), value: i))
        .toList();
    return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      body: Column(
        children: <Widget>[
          TextField(),
          DropdownButton(
            items: items,
            value: dropdownValue,
            onChanged: (value) => setState(() => dropdownValue = value),
          ),
        ],
      ),
    );
  }
}
```
</details>

**Target Platform: Android, iOS**
**Target OS version/browser: doesn't seem to be bound to a specific version**
**Devices: tested with Android emulator and tablet, iPad**

## Logs
```
[√] Flutter (Channel beta, v1.12.13+hotfix.4, on Microsoft Windows [Version 10.0.18362.535], locale lt-LT)
    • Flutter version 1.12.13+hotfix.4 at C:\Users\Rokas\FlutterSDK\flutter
    • Framework revision fb60324e6f (7 days ago), 2019-12-09 15:58:15 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rokas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Rokas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by softronaut** [comment]
Replace this:
```
onChanged: (value) => setState(() => dropdownValue = value)
```
with:
```
onChanged: (value) {
  FocusScope.of(context).requestFocus(FocusNode());
  setState(() => dropdownValue = value);
}
```

**Comment by roxifas** [comment]
I believe the more correct way to do this would be with `FocusScope.of(context).unfocus();`. But still this will only work when an option is chosen, the problem will still occur when the menu is closed by tapping outside its' area.

**Comment by iapicca** [comment]
Hi @roxifas
This platform is not meant for assistance on personal code.
Please see https://flutter.dev/community for resources for asking questions like this,
you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by roxifas** [comment]
@iapicca I think that this is an issue within Flutter, because I don't think this is the intended default behaviour (I may be wrong, but this just does not seem 'normal' from a user's perspective). As @softronaut pointed out there is a workaround, but it would still not fix the cases where the dropdown is closed without selecting an item, to fix those cases modification of `DropdownButton` widget is needed as far as I understand. Sorry that this looked like a help request with my code, my wording may have been misleading, I guess.

**Comment by softronaut** [comment]
@iapicca I agree with @roxifas. Because `Dropdown` has also `FocusNode` and once you click there, previous `FocusNode`(which is `TextField` in our case) must `unfocus`. I reproduced this scenario and none of workarounds solves the problem. This is a `Flutter` issue.

**Comment by luyunyu** [comment]
@iapicca I agree with @roxifas. this is a  issue,   you should reopen it

**Comment by mkrishnappa** [comment]
is there a workaround for this issue?

**Comment by roxifas** [comment]
@mkrishnappa my current workaround for this is to copy the entire dropdown source file into my own project and add the code `FocusScope.of(context).unfocus();` into first line of function `_DropdownButtonState._handleTap` and use that dropdown in my project instead. Not sure if there's a more correct solution for this, but it works for me as a temporary fix.

**Comment by manojeeva** [comment]
Same Here. For me, the first input focuses always.
Not sure why first input gets focus every time I tap on the dropdown form field.

**Comment by Drongerman** [comment]
I have the same issue. And it also happens with Dismissible widget - after you confirm dismiss -  focus automatically returns to the previous TextFormField that had focus. And if you add 'unfocus' (like in a sample below) in 'confirmDismiss' or 'onDismissed' - it breaks 'Dismissible widget', which I presume, happens, because it causes rebuild of widget, therefore dismissed item occurs again with different key.

  ```
FocusScopeNode currentFocus = FocusScope.of(context);

if (!currentFocus.hasPrimaryFocus) {
  currentFocus.unfocus();
}
```

**Comment by cjszk** [comment]
I:m encountering the same, and I'm also using a way to track navigator pushes and pops. What I've found is that the dropdown when pulled up actually pushes another page, and when the dropdown goes away it pops that page. This may be causing the autofocus behavior to occur again (because of the pop)

**Comment by Drongerman** [comment]
@cjszk, @roxifas 
It seems that the issue with dropdown and dialog relates to https://github.com/flutter/flutter/issues/48464

**Comment by Muhammadwahab** [comment]
i have face similar issue today solve by above work around but one problem still occur text field remain focus when i  click outside of drop down menu.My work around of this issue is to add 
                  `FocusScope.of(context).requestFocus(new FocusNode());
in onTap Listener of DropdownButton now this problem is solve thanks`

**Comment by StephanMc** [comment]
`DropdownButton` has a `onTap` field. So this workaround using `FocusScope.of(context).unfocus()` worked for me 

```dart

DropdownButton<String>(
  onTap: () {
    FocusScope.of(context).unfocus(); // <--- add this
  },

// ... rest of your code

  value: _dropdownValue,
  onChanged: (String newValue) {
    setState(() {
      _dropdownValue = newValue;
    });
  }
  
  // ...
)
```

**Comment by acoutts** [comment]
> @cjszk, @roxifas
> It seems that the issue with dropdown and dialog relates to #48464
> 
> Adding onTap to DropdownButton with FocusManager.instance.primaryFocus.unfocus() inside - works like a charm:
> 
> ```
> onTap: () {
>  FocusManager.instance.primaryFocus.unfocus();
> },
> ```
> 
> This way of unfocusing works in all cases where I had the issue with textfields autofocusing after Navigator.pop
> 
> By some reason calling of currentFocus.unfocus(); inside a widget that has a child list with Dismissible items will cause an unwanted rebuild of Dismissible items when you will try to remove an item. The rebuild of item happens when you try to remove an item and the dismiss confirmation dialog occurs.
> 
> And when I click 'Yes' button in dialog - I got an exception below (because context where the dismiss confirmation dialog was built became lost due to item widget rebuild)
> `looking up a deactivated widget's ancestor is unsafe.`
> 
> With FocusManager.instance.primaryFocus.unfocus(); everything work fine in my cases :)
> 
> There is another interesting solution with NavigatorObserver for the whole MaterialApp [#48464 (comment)](https://github.com/flutter/flutter/issues/48464#issuecomment-586635827)

This worked great for me. I had wrapped my app in a GestureDetector to dismiss any active input when tapped outside. But I had a problem where when I'd use the following snippet, any time I pushed a new route after dismissing the keyboard, the keyboard would flash up/down for a second during navigation:
```dart
FocusScope.of(context).requestFocus(new FocusNode());
```

But your approach using `FocusManager` works flawlessly for me! Thank you.

**Comment by TahaTesser** [comment]
Issue is reproducible using https://github.com/flutter/flutter/issues/47128#issuecomment-627551073 workaround does solves issue 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _State createState() => _State();
}

class _State extends State<MyHomePage> {
  int dropdownValue;
  @override
  Widget build(BuildContext context) {
    final items = [1, 2, 3]
        .map((i) => DropdownMenuItem(child: Text(i.toString()), value: i))
        .toList();
    return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      body: Column(
        children: <Widget>[
          TextField(),
          DropdownButton(
              items: items,
              value: dropdownValue,
              onTap: () {
                FocusManager.instance.primaryFocus.unfocus();
              },
              onChanged: (value) {
                setState(() => dropdownValue = value);
              }),
        ],
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>stable flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (10 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details>

**Comment by ljmatan** [comment]
@TahaTesser unfortunately it doesn't solve the issue in my case. 

```
DropdownButton(
              value: _value,
              isExpanded: true,
              items: types.data ?? <DropdownMenuItem<String>>[],
              hint: _hint ?? LoadingText(),
              onTap: () => FocusManager.instance.primaryFocus.unfocus(),
              onChanged: (value) {
                TaskTypeSelection.change(value);
                TaskTypeSelection.setTypeString(
                    types.data.singleWhere((e) => e.value == value).child.data);
                setState(() => _value = value);
              },
            )
```

**Comment by asashour** [comment]
Unable to reproduce on `master` and `web`.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _State createState() => _State();
}

class _State extends State<MyHomePage> {
  Object? dropdownValue;
  @override
  Widget build(BuildContext context) {
    final items = [1, 2, 3]
        .map((i) => DropdownMenuItem(child: Text(i.toString()), value: i))
        .toList();
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Column(
        children: <Widget>[
          const TextField(),
          DropdownButton(
              items: items,
              value: dropdownValue,
              onChanged: (value) {
                setState(() => dropdownValue = value);
              }),
        ],
      ),
    );
  }
}
```
</details>

**Comment by ljmatan** [comment]
@asashour where's the TextField widget?

**Comment by TahaTesser** [comment]
@roxifas 
Hi everyone, as commented, the issue doesn't reproduce,

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by GabrieleSuzart** [comment]
Hi, I found this issue because I have a similar problem. I put a DropdownButton on the screen and then tested it with VoiceOver screen reader, after selecting a new option the reader focus is directed to the top of the screen, reading everything again, which makes the experience really bad for blind people.

Not all developers are concerned about testing accessibility for people with disabilities. I believe Flutter should solve this focus problem without relying on workarounds. This is a bug!

**Comment by asashour** [comment]
Hi @GabrieleSuzart 

A reproducible case would help the team to identify and fix the issue.

Please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample.

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by master-pojo** [comment]
This is still occurring for me.  Using the provided code sample do the following:
1. click on the text field.
2. click on the drop down.
3. select any value in the drop down.

At this point the text field gets focus again and opens the keyboard on mobile.  It will also cause the app to scroll to the text box if it was off screen. Logs attached.

<details><summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _State createState() => _State();
}

class _State extends State<MyHomePage> {
  Object? dropdownValue;
  @override
  Widget build(BuildContext context) {
    final items = [1, 2, 3]
        .map((i) => DropdownMenuItem(child: Text(i.toString()), value: i))
        .toList();
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Column(
        children: <Widget>[
          const TextField(),
          DropdownButton(
              items: items,
              value: dropdownValue,
              onChanged: (value) {
                setState(() => dropdownValue = value);
              }),
        ],
      ),
    );
  }
}
```
</details>

<details><summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at D:\Flutter\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\KyleRoth\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\AndroidStudio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
[log.txt](https://github.com/flutter/flutter/files/7035584/log.txt)

```
</details>

**Comment by ljmatan** [comment]
@TahaTesser please reopen.
