### ISSUE TITLE
[GoogleDataTransport] iOS build crashing

### ISSUE THREAD

**Issue by Gicminos** [flutter/flutter#47627]
When I try to run or build my current project I get this error (did not have it before updating flutter).

## Steps to Reproduce

My pubspec.yaml:
```yaml
version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: ^0.5.3+1
  
  # lib/utils/facebook_utils.dart:14:27: Error: The method 'logInWithReadPermissions' isn't defined for the class 'FacebookLogin'.
  flutter_facebook_login: 2.0.1
  
  google_sign_in: 4.0.16
  url_launcher: ^5.0.3
  scoped_model: ^1.0.1
  image_picker: ^0.5.0
  pdf: ^1.3.27
  path_provider: ^1.2.0
  share_extend: ^1.0.9
  cached_network_image: 2.0.0-rc
  quiver: '>=2.1.2+1 <3.0.0'
  open_file: ^2.1.1
  printing: ^2.1.8

  firebase_messaging: ^6.0.3
  flushbar: ^1.8.2
  webfeed: ^0.4.2


  # UX packages
  tinycolor: ^1.0.2
  random_color: ^1.0.3
  charts_flutter: ^0.6.0
  page_transition: ^1.1.4
  draggable_scrollbar: ^0.0.4
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.5.0
  flutter_svg: ^0.14.3
  auto_size_text: ^2.1.0
  marquee: ^1.3.1
  progress_indicators: ^0.1.4

  flutter_launcher_icons: ^0.7.4

dependency_overrides:
  intl: ^0.16.0
```

**Target Platform:** iOS
**Target OS version/browser:** 8.0
**Devices:** any simulator / build

## Logs

```
Running Xcode build...                                                  
                                                   
Xcode build done.                                            7.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:133:17: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    _view.frame = CGRectMake(0.0, 0.0, CGRectGetWidth(_view.bounds), 0.0);
                    ^
                    self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:133:67: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    _view.frame = CGRectMake(0.0, 0.0, CGRectGetWidth(_view.bounds), 0.0);
                                                                      ^
                                                                      self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:148:18: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    [_view sizeToFit];
                     ^
                     self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:189:13: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
            if (_navigationController) {
                ^
                self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:190:40: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                [self updateNavigationBarY:_view.statusBarHeight];
                                           ^
                                           self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:193:24: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
            CGRect frame = _view.frame;
                           ^
                           self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:195:9: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
            _view.frame = frame;
            ^
            self->
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererController.m:203:17: warning: block implicitly
    retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    _view.closed = YES;
                    ^
                    self->
    8 warnings generated.
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: error: duplicate protocol definition of 'GDTCORLifecycleProtocol' is ignored [-Werror,-Wduplicate-protocol]
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: previous definition is here
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:59:1: error: duplicate interface definition for class 'GDTCORLifecycle'
    @interface GDTCORLifecycle : NSObject <GDTCORApplicationDelegate>
    ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:59:12:
    note: previous definition is here
    @interface GDTCORLifecycle : NSObject <GDTCORApplicationDelegate>
               ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:51:40: error: reference to 'GDTCORLifecycleProtocol' is ambiguous
    @protocol GDTCORPrioritizer <NSObject, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
                                           ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:51:40: error: cannot find protocol declaration for 'GDTCORLifecycleProtocol'
    @protocol GDTCORPrioritizer <NSObject, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
                                           ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:21:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORU
    ploader.h:28:37: error: reference to 'GDTCORLifecycleProtocol' is ambiguous
    @protocol GDTCORUploader <NSObject, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
                                        ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:21:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORU
    ploader.h:28:37: error: cannot find protocol declaration for 'GDTCORLifecycleProtocol'
    @protocol GDTCORUploader <NSObject, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
                                        ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:26:40: error: reference to 'GDTCORLifecycleProtocol' is ambiguous
    @interface GDTCORRegistrar : NSObject <GDTCORLifecycleProtocol>
                                           ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:26:40: error: no type or protocol named 'GDTCORLifecycleProtocol'
    @interface GDTCORRegistrar : NSObject <GDTCORLifecycleProtocol>
                                           ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:22:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage_Private.h:17
    :
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h:27:54:
    error: reference to 'GDTCORLifecycleProtocol' is ambiguous
    @interface GDTCORStorage : NSObject <NSSecureCoding, GDTCORLifecycleProtocol>
                                                         ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:22:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage_Private.h:17
    :
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h:27:54:
    error: cannot find protocol declaration for 'GDTCORLifecycleProtocol'
    @interface GDTCORStorage : NSObject <NSSecureCoding, GDTCORLifecycleProtocol>
                                                         ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:23:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer_Private.
    h:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer.h:33:42:
    error: reference to 'GDTCORLifecycleProtocol' is ambiguous
    @interface GDTCORTransformer : NSObject <GDTCORLifecycleProtocol>
                                             ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:23:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer_Private.
    h:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer.h:33:42:
    error: no type or protocol named 'GDTCORLifecycleProtocol'
    @interface GDTCORTransformer : NSObject <GDTCORLifecycleProtocol>
                                             ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:24:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadCoordinator.h:
    33:33: error: reference to 'GDTCORLifecycleProtocol' is ambiguous
        : NSObject <NSSecureCoding, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
                                    ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:21:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORR
    egistrar.h:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORP
    rioritizer.h:19:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORL
    ifecycle.h:26:11: note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h:26:11:
    note: candidate found by name lookup is 'GDTCORLifecycleProtocol'
    @protocol GDTCORLifecycleProtocol <NSObject>
              ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:24:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadCoordinator.h:
    33:33: error: cannot find protocol declaration for 'GDTCORLifecycleProtocol'
        : NSObject <NSSecureCoding, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
                                    ^
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:74:41: error: no
    visible @interface for 'GDTCORTransformer' declares the selector 'appWillBackground:'
        [[GDTCORTransformer sharedInstance] appWillBackground:application];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:77:37: error: no
    visible @interface for 'GDTCORStorage' declares the selector 'appWillBackground:'
        [[GDTCORStorage sharedInstance] appWillBackground:application];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:80:47: error: no
    visible @interface for 'GDTCORUploadCoordinator' declares the selector 'appWillBackground:'
        [[GDTCORUploadCoordinator sharedInstance] appWillBackground:application];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:83:39: error: no
    visible @interface for 'GDTCORRegistrar' declares the selector 'appWillBackground:'
        [[GDTCORRegistrar sharedInstance] appWillBackground:application];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m:90:41: error: no
    visible @interface for 'GDTCORTransformer' declares the selector 'appWillForeground:'
        [[GDTCORTransformer sharedInstance] appWillForeground:application];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

## Flutter analyze

```
Analyzing itseccomp_mobile...                                           

   info • The value of the field '_comment' isn't used • lib/models/review.dart:15:10 • unused_field
   info • 'rootAncestorStateOfType' is deprecated and shouldn't be used. Use findRootAncestorStateOfType instead. This feature was deprecated
          after v1.12.1. • lib/widgets/drawer_action.dart:11:39 • deprecated_member_use
   info • 'TypeMatcher' is deprecated and shouldn't be used. TypeMatcher has been deprecated because it is no longer used in framework(only in
          deprecated methods). This feature was deprecated after v1.12.1. • lib/widgets/drawer_action.dart:12:17 • deprecated_member_use

3 issues found. (ran in 21.0s)
```

## Flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/mikael/development/flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 7002328D-BD3F-4F21-81D4-2ED28F453E67 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by Gicminos** [comment]
If it can help, on my Podfile I added `use_frameworks!` as required for https://pub.dev/packages/printing#installing

**Comment by asrinagesh** [comment]
I'm facing the same issue. I can run it fine locally but whenever I try to build it, that's when the error shows up.

**Comment by ernestomar** [comment]
I've fixed the problem setting the following:

In ios/Flutter/AppFrameworkInfo.plist

  <key>MinimumOSVersion</key>
  <string>9.0</string>

In  ios/Flutter/Flutter.podspec

   s.ios.deployment_target = '9.0'

In Podfile

    platform :ios, '9.0'

**Comment by Gicminos** [comment]
After the changes you suggested I still get this error:

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m:19:
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h:
    17:
    /Users/mikael/Documents/itseccomp_mobile/build/ios/Debug-iphoneos/GoogleDataTransport/GoogleDataTransport.framework/Headers/GDTCORRegistra
    r.h:26:1: error: duplicate interface definition for class 'GDTCORRegistrar'
    @interface GDTCORRegistrar : NSObject <GDTCORLifecycleProtocol>
    ^
    In file included from
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m:17:
    /Users/mikael/Documents/itseccomp_mobile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GDTCORRegistrar.h:26:12:
    note: previous definition is here
    @interface GDTCORRegistrar : NSObject <GDTCORLifecycleProtocol>
               ^
    1 error generated.

Encountered error while building for device.
```

**Comment by Gicminos** [comment]
I can now build the application after updating flutter_facebook_login, but still cannot run it with the same error.

**Comment by travellertech** [comment]
I have the same error when building for Ios..and the error messages are not really helpful.

**Comment by Gicminos** [comment]
Upgrading my packages and performing various clean helped me to temporary build it successfully.

Among what I did was running `flutter clean`, deleting `Podfile.lock` and `Pods` directory.

I am not sure at all what of those solved my issue, and at the same time I tried different procedures along many weeks that makes me very hard to tell what exactly solved the problem for me. 

Now one problem that occur to me is that even running the build with `--build-name` and `--build-number`,  XCode doesn't fetch the value and that required me to edit them in the `Info.plist` manually, but I am not sure that this is related.

**Comment by uny** [comment]
For add-to-app (module) project, I suspect the below part in the generated `ios/Podfile` might be the cause.

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Aggregate targets do not have a headers build phase.
    if target.respond_to?('headers_build_phase')
      target.headers_build_phase.files.each do |file|
        # Make headers public so they can be imported by the host application.
        file.settings = { 'ATTRIBUTES' => ['Public'] }
      end
    end
  end
end
```

Commenting out this part solves the issue.
This part is from https://github.com/flutter/flutter/pull/40927.

**Comment by jmagman** [comment]
@uny That was removed with https://github.com/flutter/flutter/pull/50536.  Try running `flutter clean` and re-building.

Sounds like @Gicminos  fixed by upgrading packages.  See also https://github.com/flutter/flutter/issues/45984.

Closing.

**Comment by azhar-rafiq** [comment]
I have a similar issue in #53215 . 
I've tried all the solutions from @ernestomar and @Gicminos and #45984 but errors still the same. Any suggestion? :(

**Comment by soonsam123** [comment]
@ernestomar suggestion +:

```
cd ios
pod deintegrate
cd ..
flutter clean
flutter build ios
```

worked!

**Comment by speedlightwp** [comment]
I am using Macbook. I am having similar errors too. I have to close my Android Studio and Simulator then run the command "flutter build ios" from my Terminal again. Those errors disappear. Why?

**Comment by ArtfulDodgerB92** [comment]
> I've fixed the problem setting the following:
> 
> In ios/Flutter/AppFrameworkInfo.plist
> 
> ```
> 
>   <key>MinimumOSVersion</key>
>   <string>9.0</string>
> ```
> 
> In ios/Flutter/Flutter.podspec
> 
> ` s.ios.deployment_target = '9.0'`
> 
> In Podfile
> 
> ```
> platform :ios, '9.0'
> ```

Should I have a Flutter.podspec file in this location??

On my whole mac I only have Flutter.podspec files located here:

<Flutter install directory>\bin\cache\artifacts\engine\ios\Flutter.podspec
<Flutter install directory>\bin\cache\artifacts\engine\ios-release\Flutter.podspec
<Flutter install directory>\bin\cache\artifacts\engine\ios-profile\Flutter.podspec
