### ISSUE TITLE
Long TwoLevelLists have poor performance (due to lack of viewporting)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4765]
@abarth says @Hixie has some ideas how to do so.

An internal customer also hit this (bug id 29643185).

**Comment by Hixie** [comment]
Said ideas are at https://github.com/flutter/flutter/issues/4430

**Comment by mehmetf** [comment]
Is this fixed with the addition of the new scrolling? I see we have viewporting in ListViews but not sure if TwoLevelLists do this yet.

**Comment by abarth** [comment]
Not fixed yet.  The machinery is in place, just not used yet.

**Comment by eseidelGoogle** [comment]
Let us know if this is blocking you.  Punting for now.  We know how to do this if necessary and have the tools to do it now.

**Comment by HansMuller** [comment]
The app below contains 500 items, 100 of which are ExpansionTiles with 10 children. Scrolling performance on a Nexus 5 seems quite good to me, even after expanded sublists for a while. The ExpansionTiles are created lazily (ListView) and so, unlike TwoLevelList, only the visible ones are built or rendered.

Let me know if this addresses the performance problem you reported. If so, I think we can close this issue.

```
import 'package:flutter/material.dart';

const int kItemCount = 500;
const int kItemChildCount = 10;

class ExpansionTilePerformance extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: const Text('ExpansionTile'),
      ),
      body: new ListView.builder(
        itemCount: kItemCount,
        itemBuilder: (BuildContext context, int index) {
          final Widget title = new Text('Item $index');
          if (index % 5 == 0) {
            return new ExpansionTile(
              title: title,
              key: new ValueKey<int>(index),
              children: new List.generate(kItemChildCount, (int childIndex) {
                return new ListTile(title: new Text('  Item $index.$childIndex'));
              }).toList(),
            );
          }
          return new ListTile(title: title);
        },
      ),
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new ExpansionTilePerformance()));
}
```

**Comment by mehmetf** [comment]
Yep this will work in the interim if we run into problems.

However as we had talked, the best solution would be the FixedExtent solution with auto-derived extents.

**Comment by HansMuller** [comment]
Excellent, I'll close this issue.  I'm working on adding support for auto-derived extents now.
