### ISSUE TITLE
App startup crash on android arm device

### ISSUE THREAD

**Issue by adhil-azeez** [flutter/flutter#47819]
Hi, I'm upgraded the flutter to latest version v1.12.13+hotfix.5.  After that every app crash on start up on real device and emulator of android_arm architecture. I tried on another PC of Macbook and the same issue happened.

I tried to the release apks and fat apk and the issue was still there. I also switched to dev channel and the issue happened for all projects. And add the ` ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'` in gradle, but it didn't solved.

## Steps to Reproduce

1. Run command `flutter create foo` 
2. Run command `cd foo`
3. Connect the **android_arm** device/emulator
4. Run command `flutter run`

## Logs

There isn't any log produced by flutter terminal instead of showing the below
```bash
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.foo/.MainActivity (has extras) }

Waiting for observatory port to be available
```

But the android logcat returns the below informations after opening the app and crashed on white screen.

```bash
> 12-26 18:50:51.436 8354-8354/com.example.foo E/Dart: ../../third_party/dart/runtime/vm/cpu_arm.cc: 181: error: Unrecognized ARM CPU architecture.
12-26 18:50:51.436 8354-8354/com.example.foo E/DartVM: version=2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "android_arm"
    thread=8354, isolate=vm-isolate(0xaba037f0)
12-26 18:50:51.436 8354-8354/com.example.foo E/DartVM:   pc 0x54d0ffcd fp 0xff903ab8 libflutter.so+0x1321fcd
12-26 18:50:51.436 8354-8354/com.example.foo E/DartVM: -- End of DumpStackTrace
12-26 18:50:51.436 8354-8354/com.example.foo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8354 (com.example.foo)
......

> 12-26 18:50:52.116 3121-8263/? E/WindowState: getStack: Window{1e48a1b3 u0 Starting com.example.foo} couldn't find taskId=57 Callers=com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10210 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop:9169 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLocked:9111 com.android.server.wm.WindowManagerService.executeAppTransition:4287 
12-26 18:50:52.116 3121-8263/? E/WindowState: getStack: Window{1e48a1b3 u0 Starting com.example.foo} couldn't find taskId=57 Callers=com.android.server.wm.WindowState.getDisplayContent:804 com.android.server.wm.WindowStateAnimator.updateSurfaceWindowCrop:1339 com.android.server.wm.WindowStateAnimator.setSurfaceBoundariesLocked:1532 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10298 
12-26 18:50:52.116 3121-8263/? E/WindowState: getStack: Window{1e48a1b3 u0 Starting com.example.foo} couldn't find taskId=57 Callers=com.android.server.wm.WindowState.getDisplayContent:804 com.android.server.wm.WindowState.isDefaultDisplay:1331 com.android.server.wm.WindowStateAnimator.updateSurfaceWindowCrop:1349 com.android.server.wm.WindowStateAnimator.setSurfaceBoundariesLocked:1532 
12-26 18:50:52.116 3121-8263/? E/WindowState: getStack: Window{1e48a1b3 u0 Starting com.example.foo} couldn't find taskId=57 Callers=com.android.server.wm.WindowState.getDisplayContent:804 com.android.server.wm.WindowState.getDisplayId:809 com.android.server.wm.InputMonitor.updateInputWindowsLw:294 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10549 
......

> 12-26 18:50:52.126 3121-8263/? E/WindowState: getStack: Window{1e48a1b3 u0 Starting com.example.foo} couldn't find taskId=57 Callers=com.android.server.wm.DisplayContent.setTouchExcludeRegion:237 com.android.server.wm.WindowManagerService.setFocusedStackFrame:4116 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10631 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop:9169 
```

flutter doctor -v

```console
> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Unicom\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

> [√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

> [√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Unicom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

> [√] Connected device (1 available)
    • SM G531F • 42003823dab65200 • android-arm • Android 5.1.1 (API 22)

```

**Comment by mraleph** [comment]
Could you run `adb shell cat /proc/cpuinfo` with the device connected and paste the output here?

**Comment by adhil-azeez** [comment]
`adb shell cat /proc/cpuinf`
```
Processor       : ARMv8 Processor rev 2 (v8l)
processor       : 0
processor       : 1
processor       : 2
processor       : 3
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32  half thumb fastmult edsp tls vfp vfpv3 vfpv4 neon idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 2

Hardware        : PXA1908
Revision        : 0001
```

**Comment by yrom** [comment]
My app have same issue on user's phone, the logcat:
```
E Dart : ../../third_party/dart/runtime/vm/cpu_arm.cc: 181: error: Unrecognized ARM CPU architecture.
```
But all of them are `armeabi-v7a`. 

And I notice that they are still using Android 4.4.4.

**Comment by mraleph** [comment]
This is fixed upstream by dart-lang/sdk@5581307ae6ade7a6a093a9643993b159f270ac56

**Comment by adhil-azeez** [comment]
> 
> 
> This is fixed upstream by [dart-lang/sdk@5581307](https://github.com/dart-lang/sdk/commit/5581307ae6ade7a6a093a9643993b159f270ac56)

The issue still exists. Updated the flutter to Channel stable, v1.12.13+hotfix.7. Created a new project and the issue is still found in same arm.

**Comment by mraleph** [comment]
@adhil-azeez I don't think this fix is going to reach stable channel any time soon. You should switch to master if you would like to try it out.

**Comment by ailic88** [comment]
@mraleph @zoechi  Can we somehow apply this fix on current stable versions v1.12.13+hotfix.7?
There are many plugins that can't be build with current master, so it is useless at the moment.
This is very urgent since many armeabi-v7a devices are not supported on Flutter  v2 , it should be apply as hotfix.

**Comment by mraleph** [comment]
@Hixie @eseidel @tvolkert - see the comment above. consider cherry picking Dart fix and making another stable release.

**Comment by tvolkert** [comment]
@pcsosinski here's an example candidate for hotfix

**Comment by tvolkert** [comment]
@christopherfujino is gonna take a look at hotfixing.

**Comment by christopherfujino** [comment]
Per #40443 it looks like to pick up the dart fix in flutter stable we would need to pick up additional upstream commits, which is too risky, unfortunately. We will pick this up in the next stable release, however.

**Comment by samardzija** [comment]
Ok, I'll write this here, as well. When is the new stable release planned for? Will this fix be on 1.12 or 1.14?
Is there any workaround? As far as I know, there is no acceptable option where we could disable the app for affected Android versions.

IMO, this is a showstopper for 1.12 version, app crashes on startup on real device and the version is useless with this bug. We, as a developers, can't do anything about it. It should be pushed to the stable as soon as possible.

**Comment by samardzija** [comment]
> My app have same issue on user's phone, the logcat:
> 
> ```
> E Dart : ../../third_party/dart/runtime/vm/cpu_arm.cc: 181: error: Unrecognized ARM CPU architecture.
> ```
> 
> But all of them are `armeabi-v7a`.
> 
> And I notice that they are still using Android 4.4.4.

Do you have more info on which device is this happening?
I have the same device as @adhil-azeez. We tried on some other that has CPU architecture 7 and its working on 
processor	: 0
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 38.40
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 0

Hardware	: Qualcomm Technologies, Inc MSM8916
Revision	: 0004
Serial		: 000000370000e0d2
Processor	: ARMv7 Processor rev 0 (v7l)

Now, I'm not sure what is root cause of the problem.

**Comment by yrom** [comment]
@samardzija See https://github.com/dart-lang/sdk/issues/40001, I think the possible root cause is that these strange devices provide an abnormal `cpuinfo`, and `cpu_arm.cc` does not recognize it properly.

**Comment by samardzija** [comment]
@yrom can you tell us on which chipset is crashing? 
For us is on Marvell ARMADA PXA1908 and all the phones having that chipset are at risk. 
http://phonedb.net/index.php?m=processor&id=573&c=marvell_armada_pxa1908

**Comment by yrom** [comment]
Most of them are very old, such as Marvell PXA1928, MediaTek MT6592, Qualcomm Snapdragon 410 MSM8916.

In addition, after cherry-picking the commit (https://github.com/dart-lang/sdk/commit/5581307ae6ade7a6a093a9643993b159f270ac56) in my local repo and recompiling Flutter Engine, I found that these old phones no longer crash, but what's confused, it occurred on some devices using arm64 chips. Such as [Hisilicon KIRIN659](http://phonedb.net/index.php?m=processor&id=717&c=hisilicon_honor_kirin659_hi6250), Hisilicon KIRIN950, MediaTek Helio X10 MT6795, Qualcomm Snapdragon 450. 😢 
```
02-10 02:51:35.593 15455 15455 E Dart : ../../third_party/dart/runtime/vm/cpu_arm.cc: 182: error: Unrecognized ARM CPU architecture.
```

**Comment by samardzija** [comment]
@yrom wow, tnx, that's great info. @christopherfujino or whoever, please take a look at the comment above. It looks like this issue is not fixed.

**Comment by mraleph** [comment]
@yrom could you provide `adb shell cat /proc/cpuinfo` from those devices where it crashes?

**Comment by yrom** [comment]
sorry I can't provide it. those are devices from users.&nbsp;



---Original---

**Comment by jvrodrigo-scnby** [comment]
I have the same issue with a Samsung Core Prime device, android 5.1.1 API 22.
Processor: Qualcomm MSM8916 Snapdragon 410
(<link>https://www.samsung.com/es/support/model/SM-G361FZWAPHE)
I'm using flutter method channels features and crashes on startup.
`$ adb shell cat /proc/cpuinfo`
Processor	: ARMv8 Processor rev 2 (v8l)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32  half thumb fastmult edsp tls vfp vfpv3 vfpv4 neon idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2
Hardware	: PXA1908
Revision	: 0002

**Logs**:
```
E/Dart: ../../third_party/dart/runtime/vm/cpu_arm.cc: 181: error: Unrecognized ARM CPU architecture.
E/DartVM: version=2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "android_arm"
    thread=23088, isolate=vm-isolate(0xab1cb758)
E/DartVM:   pc 0x54d16fcd fp 0xff87eb38 libflutter.so+0x1321fcd
E/DartVM: -- End of DumpStackTrace
```

**Comment by adhil-azeez** [comment]
The hotfix-8 is live for stable channel. But the issue still exists. Please do needful.

**Comment by tvolkert** [comment]
@mraleph hotfix.8 contains Dart SDK commit https://github.com/dart-lang/sdk/commit/4cc36055d6803b899667feaedc1216a96e9d1c72 - can you have a look?

**Comment by mraleph** [comment]
@tvolkert I reopened https://github.com/flutter/flutter/issues/48923 (which was cited on the original fix).

@adhil-azeez Is this crashing on the same device for which you shared cpuinfo from previously? The crash seems misformatted - are you sure you copied all the lines from the output.

**Comment by adhil-azeez** [comment]
> 
> 
> @tvolkert I reopened #48923 (which was cited on the original fix).
> 
> @adhil-azeez Is this crashing on the same device for which you shared cpuinfo from previously? The crash seems misformatted - are you sure you copied all the lines from the output.

Yes, The device is same. Below is the output from flutter debugger console

`D/FlutterActivity(29342): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(29342): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(29342): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
E/DartVM  (29342): version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "android_arm"
E/DartVM  (29342): thread=29342, isolate=vm-isolate(0xab756d40)
E/DartVM  (29342):   pc 0x54cf7fcd fp 0xffafa7c8 libflutter.so+0x1321fcd
E/DartVM  (29342): -- End of DumpStackTrace
`

**Comment by mraleph** [comment]
@adhil-azeez ah, wait. You need to try master channel. Stable channel is not going to contain a fix because it was decided against the cherry pick. So hotfix.8 is not going to fix this issue.

**Comment by inquisiteur** [comment]
I am facing the same Issue

**Comment by christopherfujino** [comment]
> I am facing the same Issue

Did you try the master channel, like the previous comment advised?
