### ISSUE TITLE
Flutter application which use canvas to build self-CustomPainter cannot work on browser if i used the release mode by command "flutter run -d chrome --release" or "flutter build web".

### ISSUE THREAD

**Issue by huoyingjianshen** [flutter/flutter#47967]
Flutter application which use canvas to build self-CustomPainter cannot work on browser if i was used the release mode by command `flutter run -d chrome --release` or `flutter build web`, 
but it is alright in debug mode with the command `flutter run -d chrome`.

The error information follow :
```bash
Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:aG<void>'
js_helper.dart:1342 Uncaught Unsupported operation: ProcessUtils._exit
    at Object.d (http://localhost:9140/main.dart.js:1787:3)
    at Object.a2d (http://localhost:9140/main.dart.js:4661:25)
    at Object.a3L (http://localhost:9140/main.dart.js:4663:19)
    at Sy.$1 (http://localhost:9140/main.dart.js:41112:3)
    at Ma.vt (http://localhost:9140/main.dart.js:32660:6)
    at Ma.vs (http://localhost:9140/main.dart.js:32661:30)
    at Ma.yr (http://localhost:9140/main.dart.js:32648:3)
    at Ma.FW (http://localhost:9140/main.dart.js:32630:13)
    at Object.eval (eval at VD (http://localhost:9140/main.dart.js:1922:8), <anonymous>:3:53)
    at Bh.ND (http://localhost:9140/main.dart.js:23317:33)

```

```console
flutter version : Flutter 1.13.5 • channel dev 
browser version : Google Chrome 79.0.3945.88
```

**Comment by jonahwilliams** [comment]
> js_helper.dart:1342 Uncaught Unsupported operation: ProcessUtils._exit

This is likely the error that is causing the crash, but without a sample that reproduces the issue no one will be able to help you. Are you calling `io.exit` in your application?

**Comment by huoyingjianshen** [comment]
> > js_helper.dart:1342 Uncaught Unsupported operation: ProcessUtils._exit
> 
> This is likely the error that is causing the crash, but without a sample that reproduces the issue no one will be able to help you. Are you calling `io.exit` in your application?

I've never call io.exit in my application,and the code can work correctly on the mobile phone or broswer with debug mode.I will upload the code to github soon.Please help me,thank you!

**Comment by huoyingjianshen** [comment]
> > js_helper.dart:1342 Uncaught Unsupported operation: ProcessUtils._exit
> 
> This is likely the error that is causing the crash, but without a sample that reproduces the issue no one will be able to help you. Are you calling `io.exit` in your application?

**Comment by huoyingjianshen** [comment]
> > js_helper.dart:1342 Uncaught Unsupported operation: ProcessUtils._exit
> 
> This is likely the error that is causing the crash, but without a sample that reproduces the issue no one will be able to help you. Are you calling `io.exit` in your application?

Code has been uploaded.[https://github.com/huoyingjianshen/flutter-exercise.git](url)

**Comment by jonahwilliams** [comment]
You're calling exit right here: https://github.com/huoyingjianshen/flutter-exercise/blob/b74f6bd47c2fb608b1abc751f0e06ccc3bbd6a6b/lib/main.dart#L14

**Comment by jonahwilliams** [comment]
This is in response to an uncaught exception - what is the unminified original exception? You can try running in profile mode to get unobfuscated JavaScript.

**Comment by huoyingjianshen** [comment]
> This is in response to an uncaught exception - what is the unminified original exception? You can try running in profile mode to get unobfuscated JavaScript.

The application is working in profile mode now (use command "flutter build web --profile"),thank you very much! But it is not correct in release mode, and i can't find any details of the exception with debugging tools of Chrome even i delete the code "if (kReleaseMode) exit(1)" in the main.dart file.

The Consle of Chrome follow : "Another exception was thrown: Instance of 'minified:az<void>' , 
Could not load content for org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_primitives.dart : HTTP status code: 404".

So the possible causes is that dart can't get some obfuscated JavaScript api in release mode ?

**Comment by yjbanov** [comment]
> > This is in response to an uncaught exception - what is the unminified original exception? You can try running in profile mode to get unobfuscated JavaScript.
> 
> 1.The application is working in profile mode now (use command "flutter build web --profile"),thank you very much! But it is not correct in release mode, and i can't find any details of the exception with debugging tools of Chrome even i delete the code "if (kReleaseMode) exit(1)" in the main.dart file.

Have you tried running `flutter clean` after you removed the code that calls `exit(1)`?

> 1. I also found that if i use a BoxDecoration to set the background image of Container,all of the Container's children will be coverd in web mode,but it is working correctly on mobile phone.

This issue is being fixed here: https://github.com/flutter/engine/pull/15114

**Comment by huoyingjianshen** [comment]
> > > This is in response to an uncaught exception - what is the unminified original exception? You can try running in profile mode to get unobfuscated JavaScript.
> > 
> > 
> > 1.The application is working in profile mode now (use command "flutter build web --profile"),thank you very much! But it is not correct in release mode, and i can't find any details of the exception with debugging tools of Chrome even i delete the code "if (kReleaseMode) exit(1)" in the main.dart file.
> 
> Have you tried running `flutter clean` after you removed the code that calls `exit(1)`?
> 
> > 1. I also found that if i use a BoxDecoration to set the background image of Container,all of the Container's children will be coverd in web mode,but it is working correctly on mobile phone.
> 
> This issue is being fixed here: [flutter/engine#15114](https://github.com/flutter/engine/pull/15114)



I have tried upgrade flutter and run "flutter clean",but all the issues still exist.

Flutter current version info :
   Flutter 1.13.7-pre.24 • channel master • https://github.com/flutter/flutter.git
   Framework • revision 0aed0b61a1 (2 days ago) • 2020-01-03 17:53:54 -0800
   Engine • revision eb139936eb
   Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 2f57602411)

**Comment by yjbanov** [comment]
Sorry, I should've been more clear. The box decoration fix hasn't landed yet, but it is being worked on. Are you still seeing the issue with `exit(1)`?

**Comment by huoyingjianshen** [comment]
> Sorry, I should've been more clear. The box decoration fix hasn't landed yet, but it is being worked on. Are you still seeing the issue with `exit(1)`?

Thank you very much,i'm still seeing the issue with 'exit(1)' and waiting for the fix with box decoration.

**Comment by yjbanov** [comment]
Can you try creating a clean workspace where `exit(1)` never appears in your code and try running the app in release mode again? I can't think of any reasons why you should see exit called other than some weird cache issues.

**Comment by huoyingjianshen** [comment]
> Can you try creating a clean workspace where `exit(1)` never appears in your code and try running the app in release mode again? I can't think of any reasons why you should see exit called other than some weird cache issues.

Release mode can work properly with no-CustomPainter in browser, but the page will be gray and none of the children widget can show on the page if you use release mode.

All of that (CustomPainter and box-decoration) are correct on the mobile phone in any mode. Looking forward the fix on dart2js.

**Comment by yjbanov** [comment]
Can you provide the code for a small app that reproduces this for you? We use custom painters all the time and haven't seen this.

**Comment by huoyingjianshen** [comment]
> Can you provide the code for a small app that reproduces this for you? We use custom painters all the time and haven't seen this.

Thank you for your help and the code follow : https://github.com/huoyingjianshen/flutter-exercise/blob/master/lib/exerciseframework/construction_2d/construction_2d.dart.

**Comment by ferhatb** [comment]
@huoyingjianshen 

We ran your code and reproduced the exit crash, pointing to the following code you have in main.dart:

void main() {
  setSystemUIOverlayStyle(); //设置系统UI风格
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
    if (kReleaseMode)
      exit(1);
  };
  runApp(MyApp());
}

Please use if (kReleaseMode && !kIsWeb).
Now if you run your app in release mode and select "Pause on caught exceptions" in chrome debugger , you should see that your code has a bug trying to access a method on a null object (TypeError: Cannot read property 'a' of undefined).

The cause of the failure is in : 
///数据解析工厂
class EntityFactory {
  static T generateOBJ<T>(json) {
    if (1 == 0) {
      return null;
    } else if (T.toString() == "Construction2DEntity") {
      /// 图形构造数据模型
      return Construction2DEntity.fromJson(json) as T;
    } else {
      return null;
    }
  }
}

In release mode everything is minified, the (T.toString() == "Construction2DEntity") comparison fails and you get entity null returned.

If you change the code to  (T ==Construction2DEntity) it will fix your app.
