### ISSUE TITLE
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1029/89AGRYqn_pA=/

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#48234]
`flutter run` fails on physical iPhone 7 with:
```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1029/89AGRYqn_pA=/
```

I already tried the `NO_PROXY` solution but it doesn't work. It works if I connect to different WiFi networks (Mac connected to some WiFi and physical phone to another WiFi).

I don't have `Connect via network` in `Devices & Simulators`.

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/tudor/dev/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Tudor’s iPhone 7 • 6c6f39c58d86256962f6a336f8ebef46f202225e • ios • iOS 13.3

! Doctor found issues in 1 category.
```

**Comment by iKK001** [comment]
Disconnect iPhone and LapTop from WiFi - then build and connect Flutter project. Maybe afterwards start WiFi again. Some people mentioned a network issue in Catalina. Otherwise might be doublicate of https://github.com/flutter/flutter/issues/48189

**Comment by VladyslavBondarenko** [comment]
Thanks @iKK001 !
@tudor07 does it help to you?

**Comment by tudor07** [comment]
@iKK001 @VladyslavBondarenko I can start the app that way (disconnecting and reconnecting WiFi), but then hot reload does not work, giving a similar error (Can not hot reload, failed to connect to...)

I had this issue on Mojave also.

**Comment by iKK001** [comment]
Oh yes, the hot reload goes, indeed. 

Check out this solution: https://github.com/flutter/flutter/issues/23442

I haven't investigated further since I did not need hot reload on my physical device.

**Comment by tudor07** [comment]
Not working

```
http_proxy=http://127.0.0.1:1032;https_proxy=http://127.0.0.1:1032;no_proxy=127.0.0.1,localhost flutter run --observatory-port 1032 -t lib/main_production.dart
 
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1032/R53dZ7jI-P0=/
```

```
http_proxy=http://127.0.0.1:1032;https_proxy=http://127.0.0.1:1032; flutter run --observatory-port 1032 -t lib/main_production.dart
 
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1032/R53dZ7jI-P0=/
```

**Comment by VladyslavBondarenko** [comment]
Possible related to [#47204](https://github.com/flutter/flutter/issues/47204)
@tudor07 what about [this comment](https://github.com/flutter/flutter/issues/47204#issuecomment-567303280)?

**Comment by tudor07** [comment]
@VladyslavBondarenko  I already specified I don't have that enabled

**Comment by iapicca** [comment]
Hi @tudor07 
could you please provide your `flutter run --verbose`?
thank you

related issue https://github.com/flutter/flutter/issues/44944

**Comment by genert** [comment]
Same problem here.

```
host_flutter git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15 19A583, locale en-GB)
    • Flutter version 1.12.13+hotfix.6 at /Users/xxx/flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • xxx's iPhone • xxxx • ios • iOS 13.1.3
    • iPhone X            • 6D7AD1A4-5621-4A9C-AA4F-1DE5D7B8FFB4     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

**Comment by tudor07** [comment]
@iapicca flutter run --verbose

```
[+1074 ms] Forwarded port ForwardedPort HOST:1035 to DEVICE:52756
[   +2 ms] Installing and launching... (completed in 23.5s)
[   +9 ms] Connecting to service protocol: http://127.0.0.1:1035/HVw3R9PfL9c=/
[ +130 ms] Fail to connect to service protocol: http://127.0.0.1:1035/HVw3R9PfL9c=/: HttpException: , uri =
http://127.0.0.1:1035/HVw3R9PfL9c=/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:1035/HVw3R9PfL9c=/
[   +2 ms] "flutter run" took 74,872ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._complete (dart:async/future_impl.dart:514:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#68     _rootRun (dart:async/zone.dart:1122:38)
#69     _CustomZone.run (dart:async/zone.dart:1023:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#80     _rootRun (dart:async/zone.dart:1122:38)
#81     _CustomZone.run (dart:async/zone.dart:1023:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#88     _StreamController.close (dart:async/stream_controller.dart:624:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#90     _rootRunUnary (dart:async/zone.dart:1138:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#96     _StreamController._add (dart:async/stream_controller.dart:642:7)
#97     _StreamController.add (dart:async/stream_controller.dart:588:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

**Comment by tudor07** [comment]
@genert can you thumbs up this issue please? they look at thumbs ups and not "me too" replies

**Comment by CoreyCole** [comment]
I've been having this issue for a couple days now (only on iOS)

- I have no environment variables related to proxy
- I've tried enabling & disabling the "Connect via network" flag in XCode > Devices
- I've tried unplugging/replugging the usb cable
- Sometimes I can side-step the issue by turning wifi off on my laptop... it builds & connects hot reload OK sometimes, but sometimes I STILL get the same issue even with wifi off
```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1069/GEHbGRVBkrY=/
```
<details>
<summary>flutter run --verbose</summary>
```
[+1014 ms] Forwarded port ForwardedPort HOST:1070 to DEVICE:54361
[   +1 ms] Installing and launching... (completed in 19.1s)
[   +8 ms] Connecting to service protocol: http://127.0.0.1:1069/GEHbGRVBkrY=/
[  +21 ms] Fail to connect to service protocol: http://127.0.0.1:1069/GEHbGRVBkrY=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1069/GEHbGRVBkrY=/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:1069/GEHbGRVBkrY=/
[   +5 ms] "flutter run" took 151,636ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._complete (dart:async/future_impl.dart:514:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#68     _rootRun (dart:async/zone.dart:1122:38)
#69     _CustomZone.run (dart:async/zone.dart:1023:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#80     _rootRun (dart:async/zone.dart:1122:38)
#81     _CustomZone.run (dart:async/zone.dart:1023:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#88     _StreamController.close (dart:async/stream_controller.dart:624:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#90     _rootRunUnary (dart:async/zone.dart:1138:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#96     _StreamController._add (dart:async/stream_controller.dart:642:7)
#97     _StreamController.add (dart:async/stream_controller.dart:588:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
</details>
<details>
<summary>Flutter doctor -v</summary>
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/corey/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/corey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/corey/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/corey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Evan’s iPhone    • 8d0324080561dd7f917d53392abb600b541154bc • ios • iOS 13.3
    • Pitch iPhone 1 X • 7fbde93a42aa7045b58d5544bbc6d70ade30cdf5 • ios • iOS 13.1.3

• No issues found!
```
</details>
Related issues I've read through with no solution working for me:
- #13747
- #47204
- #32651
- #25122

**Comment by VladyslavBondarenko** [comment]
@CoreyCole 
don't you face the issue when using previous version of flutter?
I can add `severe: regression` if it is so

**Comment by xvrh** [comment]
I hit this error too. I have been developing for several weeks without any problem with the exact same version of Flutter.
Now I cannot use hot reload with iOS devices.

Like described in this issue above, **it works when we turn off the Wi-fi on the mac or on the iOS device.**

**Comment by CoreyCole** [comment]
I've never faced this issue until recently. I will try downgrading my flutter version to see if it is a regression or not. I will also try updating XCode because mine is out of date (11.3)

**Comment by CoreyCole** [comment]
Updating XCode to 11.3.1 did not solve the problem.

However, after downgrading flutter to `v1.12.11` I'm now able to build on my iPhone 8 and iPhone X and I'm no longer getting the service protocol connection error.

(The problem persisted when I tried v1.12.13+hotfix.6, v1.12.13+hotfix.5, v1.12.13+hotfix.4, v1.12.13+hotfix.3, v1.12.13+hotfix.2, v1.12.13+hotfix.1, and v1.12.12)

This is my `flutter doctor -v` for what is now working for me without the error. I think it is indeed a regression @VladyslavBondarenko

<details>
  <summary> flutter doctor -v </summary>

  ```
[✓] Flutter (Channel unknown, v1.12.11, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.12.11 at /Users/corey/flutter
    • Framework revision f40dbf8ca0 (9 weeks ago), 2019-11-23 01:02:54 -0500
    • Engine revision d1cac77d5a
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/corey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/corey/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/corey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (4 available)
    • Pitch iPhone 1 X • 7fbde93a42aa7045b58d5544bbc6d70ade30cdf5 • ios            • iOS 13.1.3
    • Evan’s iPhone    • 8d0324080561dd7f917d53392abb600b541154bc • ios            • iOS 13.3
    • Chrome           • chrome                                   • web-javascript • Google Chrome 79.0.3945.117
    • Web Server       • web-server                               • web-javascript • Flutter Tools

• No issues found!
  ```
</details>

**Comment by CoreyCole** [comment]
I noticed "iproxy" processes sticking around after the `flutter run` exits. 1 for each device I was attempting to build for.

I thought maybe manually killing those processes before doing `flutter run' might help, but I'm still getting the same error.

**Comment by CoreyCole** [comment]
https://github.com/flutter/flutter/issues/47204#issuecomment-570832706

This workaround seems to have fixed the problem for me! 
<img width="589" alt="Screen Shot 2020-01-24 at 10 30 34 AM" src="https://user-images.githubusercontent.com/4467106/73094002-9723a900-3e94-11ea-89ed-2c176ec0120b.png">

Anyone more familiar with iOS know what is going on here? Is there anyone flutter can do to detect/prevent problems like this?

**Comment by CoreyCole** [comment]
I noticed this workaround on a previous issue: https://github.com/flutter/flutter/issues/47204#issuecomment-570832706

Every time I uninstall the app from the iPhone and then go to XCode I see these suggested fixes:

<img width="589" alt="Screen Shot 2020-01-24 at 10 30 34 AM" src="https://user-images.githubusercontent.com/4467106/73095542-b7089c00-3e97-11ea-819a-77be508ff7fc.png">

Anyone know what these are about? One of my plugins requires me to target 10.0 and I've made sure the iOS deployment target is 10.0 in XCode project > Pods and in my `flutter-project/ios/Podfile`

```
platform :ios, '10.0'
```

**Comment by jpeiffer** [comment]
I had this happen on multiple of my iDevices.

I did a factory reset and it fixed 3 of them.  I have 3 more that I won't have access to until Monday.

**Comment by tudor07** [comment]
Not fixed in `1.12.13+hotfix.7`

**Comment by CoreyCole** [comment]
@tudor07 I think this is the fix we are waiting for. It is currently in iOS review https://github.com/flutter/flutter/issues/46724

**Comment by BassamxMednini** [comment]
Same problem here

**Comment by CoreyCole** [comment]
https://github.com/flutter/flutter/issues/46705#issuecomment-585417974

The error has gone away for my on the dev channel!
```
flutter channel dev
```
Thank you flutter team!

**Comment by iapicca** [comment]
Hi @tudor07 
can you confirm that the problem is solved upgrading flutter?
thank you

(thanks @CoreyCole )

**Comment by tapeo** [comment]
I fixed this issue with the followings:

`sudo lsof -i :THE_PORT`

`sudo kill -9 THE_PID`

in `dev`channel but I think is valid for all channels.

**Comment by alivelee** [comment]
@iapicca i confirmed

**Comment by tapeo** [comment]
I'm on dev channel, iPhone 7, debug build, same issue.

`flutter doctor -v`

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.15 19A583, locale it-IT)
    • Flutter version 1.15.3 at /Users/matteo/development/flutter
    • Framework revision 67826bdce5 (5 days ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/matteo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/matteo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPhone di Matteo Ricupero • 3a6de1a4ba636b47cd55e0b60a23b9a497432245 • ios            • iOS 13.3
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server                               • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

**Comment by tapeo** [comment]
I found that there was a problem on iOS with a dependency that I use and it disconnect without errors.

So on `dev` channel I confirm that this issue is solved.

**Comment by lzhuor** [comment]
Encountered the same error on iPhone X iOS 13.3.1 with Flutter v1.12.8.

Switching to `dev` channel fixed it.
```
flutter channel dev
flutter upgrade
flutter doctor -v
```

It's on v1.15.3 right now and it solved the problem.

**Comment by mr-mmmmore** [comment]
Hi, I have the same problem as @tudor07, it's really annoying as it comes and go: sometimes it disappears, and then later it's back, and I didn't find steps to reproduce it each time (or solve it).

I don't plan to switch to the dev channel as this app is for production, will there be a fix on the stable channel too?

What has worked this morning is doing the following:

1. Disconnect the device from USB
2. Launch iTunes
3. After few seconds, the 

_I am on a mac running Mojave 10.14.6 with Flutter stable (1.12.13+hotfix.8) and Xcode 11.3.1. I encounter this error when trying to debug on a physical iPhone 6 connected through USB. As @tudor07, `Connect via network` is disabled in `Devices & Simulators`._

**Comment by mr-mmmmore** [comment]
Hi, I have the same problem as @tudor07, it's really annoying as it comes and go: sometimes it disappears, and then later it's back, and I haven't found steps to reproduce it each time (or solve it).

I am on a mac running Mojave 10.14.6 with Flutter stable (1.12.13+hotfix.8) and Xcode 11.3.1. I encounter this error when trying to debug on a physical iPhone 6 connected through USB. As @tudor07, Connect via network is disabled in Devices & Simulators.

I don't plan to switch to the dev channel as my app is for production, **will there be a fix on the stable channel too?**

Meanwhile, **I managed to get rid of the error this morning doing the following**:

1. Disconnect the device from USB
2. Launch iTunes
3. The device might appear in the "Devices" section of the left sidebar
4. Disconnect it by pressing the "eject" button that appears when hovering over the device's name in the sidebar
5. Connect the device on USB again
6. Debug

**Comment by CoreyCole** [comment]
@mr-mmmmore since this bug is only an issue for development (hot reload, console logs, etc), you might be able develop your app using the dev channel. You can switch back to stable when you are building in `--release` mode to submit to the store or do production testing.

**Comment by mr-mmmmore** [comment]
> @mr-mmmmore since this bug is only an issue for development (hot reload, console logs, etc), you might be able develop your app using the dev channel. You can switch back to stable when you are building in `--release` mode to submit to the store or do production testing.

Sounds too risky to me... The dev channel is far ahead of the stable one, many things could break when  switching back to stable.

**Comment by jmagman** [comment]
@CoreyCole @tapeo @lzhuor report this is fixed on the dev channel.
@tudor07 Can you also confirm?

**Comment by danilor** [comment]
I swiched to dev branchs and I am still having the issue. I ran the flutter clear and flutter doctor first.

**Comment by tudor07** [comment]
@jmagman I can confirm that it works for me on `dev` channel.

Would be nice to create a `stable` hotfix release with this fix since I can't use `dev`, but you know better if this is possible.

Anyway, thanks a lot for fixing this, it was a really painfull to me.

**Comment by vasilvestre** [comment]
Using emulator on flutter dev channel I still have the error

**Comment by eduardovalenzuela** [comment]
@vasilvestre Using different image worked!!!, thanks

**Comment by jmagman** [comment]
@tudor07 Probably fixed by https://github.com/flutter/flutter/pull/49735 in v1.15.3 then.
See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release for hotfix policy.
Closing.

**Comment by nicolaevladescu** [comment]
> Hi, I have the same problem as @tudor07, it's really annoying as it comes and go: sometimes it disappears, and then later it's back, and I haven't found steps to reproduce it each time (or solve it).
> 
> I am on a mac running Mojave 10.14.6 with Flutter stable (1.12.13+hotfix.8) and Xcode 11.3.1. I encounter this error when trying to debug on a physical iPhone 6 connected through USB. As @tudor07, Connect via network is disabled in Devices & Simulators.
> 
> I don't plan to switch to the dev channel as my app is for production, **will there be a fix on the stable channel too?**
> 
> Meanwhile, **I managed to get rid of the error this morning doing the following**:
> 
> 1. Disconnect the device from USB
> 2. Launch iTunes
> 3. The device might appear in the "Devices" section of the left sidebar
> 4. Disconnect it by pressing the "eject" button that appears when hovering over the device's name in the sidebar
> 5. Connect the device on USB again
> 6. Debug

This is still slightly (works 8 out of 10 times) accurate, only that I have to eject from the Music app.

I am on macOS Catalina with Xcode `11.4` and flutter `1.12.13+hotfix.8` on stable.

**Comment by synapticvoid** [comment]
Hi,

For me it didn't work either on the stable or dev channel (I'm using Android).

What made the difference is the system image variant : it works with a **non Google Play Services** image. 

I guess that the device is restricted with the Google Play Services, which breaks the communication with the Flutter debugger.

**Comment by geekfabio** [comment]
Hi, for me 

I created a new virtual device
and in the console project
> flutter clean

**Comment by valoriss** [comment]
_If you're using google services_
**This worked for me**
(I previously deleted my iOS folder, ran flutter create . etc)
The reason I was getting this error was because the GoogleService-Info.plist was missing from the Runner folder.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by mtovard** [comment]
I had the problem too. In my case it was fixd after I change from master->dev 1.18 and delete the facebook login plugin

**Comment by atishpaul** [comment]
Hi,
Check your plugins,
if you have flutter_inappwebview plugin installed,just remove it and do not forget to tap on pub get. and try again.

**Comment by talhashahab786** [comment]
The main issue is in XML's tag. As for my case it was imageView tag in launch_background.xml.
Comment it and then run the code. For my case, I was introducing splash screen for android and had added it in AndroidManifest.xml.

Thank me later :)

**Comment by tudor07** [comment]
Hey guys, I also updated macOS to `10.15.4` and now the problem only happens like 10% of the time. So the problem is not gone, but at least it's not as annoying.

**Comment by tudor07** [comment]
Still happens on Flutter `1.17.0`

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by igez** [comment]
> Hi, I have the same problem as @tudor07, it's really annoying as it comes and go: sometimes it disappears, and then later it's back, and I haven't found steps to reproduce it each time (or solve it).
> 
> I am on a mac running Mojave 10.14.6 with Flutter stable (1.12.13+hotfix.8) and Xcode 11.3.1. I encounter this error when trying to debug on a physical iPhone 6 connected through USB. As @tudor07, Connect via network is disabled in Devices & Simulators.
> 
> I don't plan to switch to the dev channel as my app is for production, **will there be a fix on the stable channel too?**
> 
> Meanwhile, **I managed to get rid of the error this morning doing the following**:
> 
> 1. Disconnect the device from USB
> 2. Launch iTunes
> 3. The device might appear in the "Devices" section of the left sidebar
> 4. Disconnect it by pressing the "eject" button that appears when hovering over the device's name in the sidebar
> 5. Connect the device on USB again
> 6. Debug

did the trick, thank you !!!

**Comment by sabifa** [comment]
After upgrading to flutter 1.17.0 I had the same issue using an emulator with API level 29, after I switched to level 27 it worked for me again!

**Comment by neobie** [comment]
Having this issue when connecting to my real iOS device.

**Comment by lookfirst** [comment]
Confirming that the iTunes/Music.app trick above worked for me.

**Comment by zmm2tysu** [comment]
try close the firewall,it works for me.
But I dont want it,does anybody have other solutions?

**Comment by mr-mmmmore** [comment]
@zmm2tysu If you're trying to debug on an iOS device, debugging can be done using Wifi or USB. If your firewall prevents debugging, then it seems that the connection is tryed using Wifi. The only way I have found to force the connection using USB is to follow the simple procedure [I gave earlier ](https://github.com/flutter/flutter/issues/48234#issuecomment-587383466) before debugging:

> 1. Disconnect the device from USB
> 2. Launch iTunes
> 3. The device might appear in the "Devices" section of the left sidebar
> 4. Disconnect it by pressing the "eject" button that appears when hovering over the device's name in the sidebar
> 5. Connect the device on USB again
> 6. Debug

**Comment by paulus85** [comment]
I have the same type of problem with a specific Flutter app using the `google_sign_in` plugin.
Tested on 2 different iOS devices (iOS 12 and iOS 13) from a Mac using macOS 10.14.6.
The app can launch, but after 1-2 seconds, the error message appears.
When WiFi is disabled it works.

Tried to do the steps described by @mr-mmmmore but unable to find any connected device on iTunes after I disconnected the device from USB.
---
Just before posting, without doing anything special, it seems to work (with WiFi activated). Seems quite unstable...

**Comment by djprawns** [comment]
I get the same problem, guys is there a proper fix for this? Its really taking a toll on my development.

**Comment by Oneknight** [comment]
I had this issue
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1025/
I'm new using flutter, but what I did was this: 
-Unplugged the iOS device first
-then clear, make a flutter clean
-Reconnect the device, and when it appears (iOS device), run again.
 I hope it's the same error, but that works for me.

**Comment by erluxman** [comment]
Open the Project in Xcode then,

Window > Devices & Simulators

1. Select the device and 
2. **Uncheck** *Connect Via network*.

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/yWwgz.gif

**Comment by chornbe** [comment]
I know it was said to file a new issue, but I think there's a sizable dataset here. Out of the blue this started - again - for no reason, with no recent updates, etc. Now I have to turn off Wifi to build and run, then turn it back on, and if I forget on subsequent runs, it's a real pain to keep switching back and forth. I rely on my network/wifi connection as my cell signal is pretty iffy here in my home office. If I can't hit an API during dev, then I can't really run my app. 

Very frustrating issue, and I'm not sure this gets us anywhere trying to blame Cataline; I had it in the previous OS versions, and it hasn't been a problem for at least 6 months. :(

**Comment by mr-mmmmore** [comment]
@erluxman I have already experienced the bug although I had unchecked Connect via network.

**Comment by felixlunzenfichter** [comment]
> _If you're using google services_
> **This worked for me**
> (I previously deleted my iOS folder, ran flutter create . etc)
> 
> The reason I was getting this error was because the `GoogleService-Info.plist` was **missing** from the Runner folder.
> 
> If `GoogleService-info.plist` is not missed, then:
> 
> 1. Deleted Derived Data from xCode
> 2. Flutter clean
> 3. Flutter run (this is crucial, in the background flutter run works differently than traditionally building)

Actually I don't really understand what this `GoogleService-Info.plist` is for. Could someone explain that? I had this error but after deleting the file the error was gone but all google cloud services still worked. I had assumed that this file was crucial in order for google cloud services to work.

**Comment by anushkapubudu** [comment]
I faced same error try to debug with android physical device.
I change my flutter channel to beta and run flutter upgrade after try to debug app it shows like that

`Error connecting to the service protocol: failed to connect to http://127.0.0.1:58391/x1UcR0183kk=/`

so find solutions online but i can't find solution 
i was try to run --profile and --debug but error is still same,
but using android emulator it was running nicely..

**Comment by kkhan** [comment]
pod install
pod repo update
sudo gem install cocoapods
pod setup

**Comment by sridattayalla** [comment]
In my case (I'm using android physical device), I restarted the android device then ran `flutter run` and the problem resolved.

**Comment by corteXnzt** [comment]
Tried every solutions on each google searches and issues here on github but can't still fix.  Im using android studio on ubuntu 20.04 and debugging on real device.

What I wonder is it works one time everytime I restart my device then after I stop the debugger and run again this issue occurs.

![Screenshot from 2021-03-28 21-58-33](https://user-images.githubusercontent.com/49268713/112756677-ee815400-9018-11eb-92d2-a583ba26832a.png)

It says here that he use https instead of http (maybe referring to observatory url) but I don't know where to edit the changes so the observatrory connect via https
https://fantashit.com/flutter-run-connection-closed-before-full-header-was-received/

**Comment by ixre** [comment]
I use lower version of android  emulator to resolve this problem!

**Comment by ceeyang** [comment]
I was used the iOS simulator.
````export no_proxy="127.0.0.1, localhost, *.org.in"``` solved my problem.

**Comment by jnknewaj** [comment]
Such a boring bug with flutter. No specific solution. I am facing this now with real device. Already Wwsted some hours looking for solution and found nothing specific.

**Comment by Max-Power-7** [comment]
Only unique solution for me is restart PC.
