### ISSUE TITLE
Flutter run on iOS simulator fails to connect to observatory: Error waiting for a debug connection: Bad state: No element

### ISSUE THREAD

**Issue by ejain** [flutter/flutter#48591]
## Steps to Reproduce

`flutter run` builds and runs the app on the iOS Simulator, but is unable to establish a debug connection.

## Logs

```
flutter run --verbose

...
[   +7 ms] executing: /usr/bin/xcrun simctl launch 8B899578-4FEB-4E74-AE2C-C2158899110E com.zenobase.durations
--enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +658 ms] com.zenobase.durations: 10233
[        ] Waiting for observatory port to be available...
[  +12 ms] Error waiting for a debug connection: Bad state: No element
[  +32 ms] Error launching application on iPad Pro (12.9-inch) (3rd generation).
[   +4 ms] "flutter run" took 36,976ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
...
```

```
flutter doctor --verbose

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/ejain/Flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPad Pro (12.9-inch) (3rd generation) • 8B899578-4FEB-4E74-AE2C-C2158899110E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
```

**Comment by ejain** [comment]
This may be an issue with simulated devices running iOS 13.3;  iOS 10.3 works fine.

**Comment by lordvidex** [comment]
I have the same issue on Android.. sometimes build works, sometimes it doesn't.. i reinstalled the flutter sdk as adviced on stack overflow and build worked for just one day only to start returning errors again..
'''
Error waiting for a debug connection: Bad state: No element
Error launching application on ${device.name}.
Exited (sigterm)
'''

**Comment by KevKipkemoi** [comment]
I have the same issue although in my case it runs the app on device before throwing the same exception.

**Comment by ejain** [comment]
Just to be clear, the app does start and work as expected, but the debug connection is terminated.

**Comment by lshaoshuai** [comment]
i have the same issue when i run flutter project in the vscode.

**Comment by corymalcolmtaylor** [comment]
I had this error last night when trying to debug -  on android - an app that used the speech_to_text plugin. On iOS it was not an issue.  I got past it by recreating the app passing in the --androidx flag and then editing the ./android/app/build.gradle file to include `minSdkVersion 21` which had in a new app been set to 16 (also weird -why 16?).   But in my case  the app was not loading any screen element - I was seeing a mostly black screen.

**Comment by hugoeiji** [comment]
I fixed it by updating from Mojave to Catalina. Also, I installed and configured cocoapods. After that, it started to work.

>  sudo gem install cocoapods
>  pod setup

**Comment by kopilim96** [comment]
Same issue here. Is problem solved ?

**Comment by surpriso1997** [comment]
> Same issue here. Is problem solved ?

I am also having the same problem with my test android phone. I reinstalled the flutter and android sdk but the problem still existed with my test phone. However this problem does not occur with my other phones. To be specific my test phone is redit note 8.

**Comment by jmagman** [comment]
@lordvidex @surpriso1997 This issue is tracking an issue connecting to an iOS simulator.  If you are having issues while debugging on an Android device, please file a new issue.

**Comment by jmagman** [comment]
@ejain Does your user have admin permissions?  You may be hitting https://github.com/flutter/flutter/issues/18409.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by ijazulrehman** [comment]
Try to change flutter channel to beta using
`flutter channel beta`

it worked for me to fix the issue which is because flutter version is updated to
Flutter 1.17.0-3.3.pre • channel beta
