### ISSUE TITLE
Error on render a TextFormField with data on controller

### ISSUE THREAD

**Issue by igor-rodrigues-ss** [flutter/flutter#49258]
Good evening

I'm new in flutter development, but i received this error when tried render a TextFormField with your controller with data. I think it would be interesting that this message be something more specific. Would be possible make this correction?  

```
I/flutter ( 3759): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 3759): The following assertion was thrown during paint():
I/flutter ( 3759): 'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
I/flutter ( 3759): 
I/flutter ( 3759): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3759): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3759): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3759):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 3759): 
I/flutter ( 3759): The relevant error-causing widget was:
I/flutter ( 3759):   TextFormField
I/flutter ( 3759):   file:///home/igor/study/flutter/qhouse/lib/widgets/pf/homePF/BtnAndTextSearch.widget.dart:90:18
I/flutter ( 3759): 
I/flutter ( 3759): When the exception was thrown, this was the stack:
I/flutter ( 3759): #2      new TextPosition (dart:ui/text.dart:1372:15)
I/flutter ( 3759): #3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
I/flutter ( 3759): #4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
I/flutter ( 3759): #5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
I/flutter ( 3759): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #12     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter ( 3759): #13     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4796:13)
I/flutter ( 3759): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #30     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 3759): #31     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 3759): #32     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter ( 3759): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter ( 3759): #34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #35     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:575:11)
I/flutter ( 3759): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #38     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #40     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 3759): #41     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 3759): #42     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter ( 3759): #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter ( 3759): #44     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #46     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 3759): #47     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 3759): #48     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter ( 3759): #49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter ( 3759): #50     _RenderDecoration.paint.doPaint (package:flutter/src/material/input_decorator.dart:1404:17)
I/flutter ( 3759): #51     _RenderDecoration.paint (package:flutter/src/material/input_decorator.dart:1439:12)
I/flutter ( 3759): #52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #54     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #61     RenderMouseRegion.paint (package:flutter/src/rendering/proxy_box.dart:2787:13)
I/flutter ( 3759): #62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #64     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #70     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 3759): #71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #73     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 3759): #74     RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
I/flutter ( 3759): #75     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #77     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #78     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter ( 3759): #79     PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:531:7)
I/flutter ( 3759): #80     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2191:25)
I/flutter ( 3759): #81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #83     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #84     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2193:15)
I/flutter ( 3759): #85     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #86     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #87     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 3759): #88     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:589:5)
I/flutter ( 3759): #89     RenderStack.paint (package:flutter/src/rendering/stack.dart:597:7)
I/flutter ( 3759): #90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #91     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #92     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 3759): #93     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:396:5)
I/flutter ( 3759): #94     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #95     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #96     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #97     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:530:11)
I/flutter ( 3759): #98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #100    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #101    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter ( 3759): #102    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1755:15)
I/flutter ( 3759): #103    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #104    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #105    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #106    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #107    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 3759): #108    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 3759): #109    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 3759): #110    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 3759): #111    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 3759): #112    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:937:29)
I/flutter ( 3759): #113    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 3759): #114    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter ( 3759): #115    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter ( 3759): #116    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter ( 3759): #117    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter ( 3759): #118    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter ( 3759): #122    _invoke (dart:ui/hooks.dart:259:10)
I/flutter ( 3759): #123    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter ( 3759): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 3759): 
I/flutter ( 3759): The following RenderObject was being processed when the exception was fired: RenderEditable#d4011 relayoutBoundary=up22:
I/flutter ( 3759):   creator: _Editable-[GlobalKey#7b5ee] ← Semantics ← CompositedTransformTarget ←
I/flutter ( 3759):     IgnorePointer-[GlobalKey#f5da0] ← Semantics ← _PointerListener ← Listener ←
I/flutter ( 3759):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#a8b3e] ← _PointerListener ← Listener
I/flutter ( 3759):     ← _ScrollableScope ← RepaintBoundary ← ⋯
I/flutter ( 3759):   parentData: <none> (can use size)
I/flutter ( 3759):   constraints: BoxConstraints(w=252.0, 0.0<=h<=708.0)
I/flutter ( 3759):   size: Size(252.0, 23.0)
I/flutter ( 3759):   cursorColor: Color(0x004285f4)
I/flutter ( 3759):   showCursor: ValueNotifier<bool>#e375e(true)
I/flutter ( 3759):   maxLines: 1
I/flutter ( 3759):   minLines: null
I/flutter ( 3759):   selectionColor: Color(0xfffff59d)
I/flutter ( 3759):   textScaleFactor: 1.0
I/flutter ( 3759):   locale: en_US
I/flutter ( 3759):   selection: TextSelection(baseOffset: 11, extentOffset: 11, affinity: null, isDirectional: false)
I/flutter ( 3759):   offset: ScrollPositionWithSingleContext#93748(offset: 0.0, range: 0.0..0.0, viewport: 252.0,
I/flutter ( 3759):     ScrollableState, ClampingScrollPhysics, IdleScrollActivity#06da9, ScrollDirection.idle)
I/flutter ( 3759): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 3759):     text: TextSpan
I/flutter ( 3759):       TextSpan
I/flutter ( 3759):       TextSpan
I/flutter ( 3759):       TextSpan
I/flutter ( 3759): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by VladyslavBondarenko** [comment]
Hi @igor-rodrigues-ss 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/47343
Try[ this workaround ](https://github.com/flutter/flutter/issues/47343#issuecomment-570432119)
Thumb up the mentioned issue, comment there if your case is different from described
I'm closing the current one as duplicate.
If you disagree please write in the comments here and I will reopen it.
Thank you

**Comment by igor-rodrigues1** [comment]
@VladyslavBondarenko I looked the issue #47343 and I not has sure if the erro from this issue is the same error reported here, because, the full error message is different.

**Comment by VladyslavBondarenko** [comment]
@igor-rodrigues-ss 
Can you post a sample code here to reproduce your case?

**Comment by igor-rodrigues-ss** [comment]
This is the code that is render with the error. When I clear the data from controller (textCtrl) the bug stopped occurring, i do not know is the correct solution, but works for me.

class BtnAndTextSearch extends StatefulWidget {
  Function cbChangePageMode;

  BtnAndTextSearch({this.cbChangePageMode});

  @override
  _BtnAndTextSearchState createState() => _BtnAndTextSearchState();
}

class _BtnAndTextSearchState extends State<BtnAndTextSearch>
    with SingleTickerProviderStateMixin {
  // SingleTickerProviderStateMixin - para usar vsync na animação
  bool searchMode = false;
  AnimationController _controller;
  Animation<Offset> _offsetAnimation;
  final _textCtlr = TextEditingController();

  void _prepareSlideTransition() {
    _controller = AnimationController(
      duration: Duration(milliseconds: 500),
      vsync:
          this, // este parametro impede que animação fora da tela consuma recurso desnecessario
    )..repeat(reverse: false);

    _offsetAnimation = Tween<Offset>(
      begin: const Offset(1.5, 0.0),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _controller,
      curve: Curves.easeInToLinear,
    ));
  }

  @override
  void initState() {
    super.initState();
    _prepareSlideTransition();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Widget InputText() {
    if (this.searchMode) {
      return Padding(
        padding: EdgeInsets.only(right: 12),
        child: Container(
          // color: Colors.yellow,
          width: MediaQuery.of(context).size.width * 0.7,
          child: TextFormField(
            controller: _textCtlr,
            keyboardType: TextInputType.text,
            decoration: InputDecoration(
              hintText: "Digite...",
            ),
            onTap: () {
              this.searchMode = true;
            },
            onChanged: (value) {
              empresaPFBLOC.input.add(value);
            },
            style: TextStyle(
                fontSize: 20,
                color: Colors.black45,
                fontWeight: FontWeight.w300),
          ),
        ),
      );
    }
    _textCtlr.clear();
    return Container();
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.end,
      mainAxisAlignment: MainAxisAlignment.end,
      children: <Widget>[
        InputText(),
        FloatingActionButton(
          backgroundColor: Color(0xfffdd835),
          onPressed: () {
            setState(() {
              // _controller.forward(); // iniciando a transition

              widget.cbChangePageMode();

              setState(() {
                this.searchMode = !this.searchMode;
              });
            });
          },
          child: iconBtn(this.searchMode),
        ),
      ],
    );
  }
}

**Comment by igor-rodrigues-ss** [comment]
This is the code that is render with the error. When I clear the data from controller (textCtrl) the bug stopped occurring, i do not know is the correct solution, but works for me.

```dart
class _BtnAndTextSearchState extends State<BtnAndTextSearch>
    with SingleTickerProviderStateMixin {
  bool searchMode = false;
  AnimationController _controller;
  Animation<Offset> _offsetAnimation;
  final _textCtlr = TextEditingController();

  void _prepareSlideTransition() {
    _controller = AnimationController(
      duration: Duration(milliseconds: 500),
      vsync:
          this,
    )..repeat(reverse: false);

    _offsetAnimation = Tween<Offset>(
      begin: const Offset(1.5, 0.0),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _controller,
      curve: Curves.easeInToLinear,
    ));
  }

  @override
  void initState() {
    super.initState();
    _prepareSlideTransition();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Widget InputText() {
    if (this.searchMode) {
      return Padding(
        padding: EdgeInsets.only(right: 12),
        child: Container(
          // color: Colors.yellow,
          width: MediaQuery.of(context).size.width * 0.7,
          child: TextFormField(
            controller: _textCtlr,
            keyboardType: TextInputType.text,
            decoration: InputDecoration(
              hintText: "Digite...",
            ),
            onTap: () {
              this.searchMode = true;
            },
            onChanged: (value) {
              empresaPFBLOC.input.add(value);
            },
            style: TextStyle(
                fontSize: 20,
                color: Colors.black45,
                fontWeight: FontWeight.w300),
          ),
        ),
      );
    }
    _textCtlr.clear();
    return Container();
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.end,
      mainAxisAlignment: MainAxisAlignment.end,
      children: <Widget>[
        InputText(),
        FloatingActionButton(
          backgroundColor: Color(0xfffdd835),
          onPressed: () {
            setState(() {
              // _controller.forward();

              widget.cbChangePageMode();

              setState(() {
                this.searchMode = !this.searchMode;
              });
            });
          },
          child: iconBtn(this.searchMode),
        ),
      ],
    );
  }
}
```

**Comment by kevto** [comment]
I've a similar setup of using a `TextEdittingController` instance multiple times and displaying a `TextField` on and off. I also receive the same error but this is how I fixed this, it doesn't look fancy neither am I happy with it but it works as intended.

1. Make your `_textCtrl` not final. It has to be reinstantiated every times it enters the `if (this.searchMode) {` clause;
2. Create a new `TextEdittingController` and set it to the `_textCtrl` field.

Alternatively, in your scenario, you can also get rid off the controller from your `TextFormField` because except for clearing the controller / `TextFormField` from input, you're not really using it extensively and I believe without the controller the behavior is the same.

Now it should work again.

**Comment by VladyslavBondarenko** [comment]
@igor-rodrigues-ss , @kevto 
does the issue still persist?
<details>
 <summary>I'm not experiencing it with this code (without _textCtlr.clear())</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: BtnAndTextSearch()));

class BtnAndTextSearch extends StatefulWidget {
  @override
  _BtnAndTextSearchState createState() => _BtnAndTextSearchState();
}

class _BtnAndTextSearchState extends State<BtnAndTextSearch>
    with SingleTickerProviderStateMixin {
  bool searchMode = false;
  AnimationController _controller;
  Animation<Offset> _offsetAnimation;
  final _textCtlr = TextEditingController();

  void _prepareSlideTransition() {
    _controller = AnimationController(
      duration: Duration(milliseconds: 500),
      vsync:
      this,
    )..repeat(reverse: false);

    _offsetAnimation = Tween<Offset>(
      begin: const Offset(1.5, 0.0),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _controller,
      curve: Curves.easeInToLinear,
    ));
  }

  @override
  void initState() {
    super.initState();
    _prepareSlideTransition();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Widget InputText() {
    if (this.searchMode) {
      return Padding(
        padding: EdgeInsets.only(right: 12),
        child: Container(
          // color: Colors.yellow,
          width: MediaQuery.of(context).size.width * 0.7,
          child: TextFormField(
            controller: _textCtlr,
            keyboardType: TextInputType.text,
            decoration: InputDecoration(
              hintText: "Digite...",
            ),
            onTap: () {
              this.searchMode = true;
            },
            onChanged: (value) {
//              empresaPFBLOC.input.add(value);
            },
            style: TextStyle(
                fontSize: 20,
                color: Colors.black45,
                fontWeight: FontWeight.w300),
          ),
        ),
      );
    }
//    _textCtlr.clear();
    return Container();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            InputText(),
            FloatingActionButton(
              backgroundColor: Color(0xfffdd835),
              onPressed: () {
                setState(() {
                  // _controller.forward();

//              widget.cbChangePageMode();

                  setState(() {
                    this.searchMode = !this.searchMode;
                  });
                });
              },
              child: IconButton(
                icon: Icon(Icons.search),
              )
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

Tried with current stable `1.17.5` and master `1.20.0-3.0.pre.114`.

could you provide a minimal complete reproducible code sample?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
