### ISSUE TITLE
BUG Newline not working with TextFormField/TextField on Android device with custom keyboard

### ISSUE THREAD

**Issue by Inf0rmatix** [flutter/flutter#49796]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
main.dart - Change Scaffold body to
```
TextFormField(
        initialValue: '',
        minLines: 2,
        maxLines: 4,
        onChanged: (value) => print(value),
      ),
```
3. ... 
Run the app on any Android device (Using a non-google keyboard). Enter the textfield and try to enter a text with line breaks by using the enter key on your software keyboard. Bug reproducable on Samsung Keyboard and SwiftKey Keyboard.

**Expected results:** 
A text with line breaks

**Actual results:** 
A text with no line breaks

<details>
  <summary>Logs</summary>

```
ok-Pro:multiline_fun paul$ flutter run --verbose
[  +19 ms] executing: [/Users/paul/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +35 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 92f7e16312d9c7c396c0100dcb699458c3f10172
[        ] executing: [/Users/paul/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +24 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-38-g92f7e1631
[   +6 ms] executing: [/Users/paul/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/paul/Development/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +40 ms] executing: [/Users/paul/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +5 ms] executing: sw_vers -productName
[  +17 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +25 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/paul/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           33006b57244db5fd       device usb:338952192X product:gtaxlwifixx model:SM_T580 device:gtaxlwifi transport_id:1
[  +19 ms] executing: /Users/paul/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +56 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +629 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 11.3.1
           Build version 11C504
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[ +100 ms] /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell getprop
[  +89 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +201 ms] Generating /Users/paul/StudioProjects/multiline_fun/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +19 ms] ro.hardware = samsungexynos7870
[  +34 ms] Launching lib/main.dart on SM T580 in debug mode...
[   +7 ms] executing: /Users/paul/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/paul/StudioProjects/multiline_fun/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +20 ms] Exit code 0 from: /Users/paul/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/paul/StudioProjects/multiline_fun/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.multiline_fun" (Raw: "com.example.multiline_fun")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="multiline_fun" (Raw: "multiline_fun")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.multiline_fun.MainActivity" (Raw: "com.example.multiline_fun.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell -x logcat -v time -t 1
[ +137 ms] Exit code 0 from: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell -x logcat -v time -t 1
[        ] --------- beginning of main
           01-30 16:42:30.045 E/adbd    (23917): recv: OPEN 00003090 00000000 001a:73 68 65 6C 6C 3A 6C 6F 67 63 61 74 20 2D 76 20 74 69 6D 65 20 2D 74 20 31 00
[   +8 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb version
[   +1 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd logcat -v time -T 01-30 16:42:30.045
[  +14 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /Users/paul/Library/Android/sdk/platform-tools/adb
[   +2 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb start-server
[   +6 ms] Building APK
[  +17 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /Users/paul/StudioProjects/multiline_fun/android/gradlew.
[        ] /Users/paul/StudioProjects/multiline_fun/android/gradlew mode: 33261 rwxr-xr-x.
[  +45 ms] executing: /usr/bin/plutil -convert json -o - /Users/paul/Applications/JetBrains Toolbox/Android Studio.app/Contents/Info.plist
[  +10 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/paul/Applications/JetBrains Toolbox/Android Studio.app/Contents/Info.plist
[        ] {"NSUIElement":false,"CFBundleIdentifier":"com.jetbrains.apps.activator.linkapp.pcom.jetbrains.apps.activator__ndroid_tudio_3_5_3","CFBundleInfoDictionaryVersion":"6.0","CFBundleLongVersionString":"3.5.3","CFBundleVersion":"3.5.3","CFBundleName":"Android Studio
3.5.3","CFBundleExecutable":"jetbrains-toolbox-launcher","CFBundleGetInfoString":"","NSHighResolutionCapable":true,"CFBundleSignature":"????","LSUIElement":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"icon.icns","JetBrainsToolboxApp":"\/Users\/paul\/Library\/Application
Support\/JetBrains\/Toolbox\/apps\/AndroidStudio\/ch-0\/191.6010548\/Android Studio.app","CFBundleDevelopmentRegion":"English","NSHumanReadableCopyright":"Copyright (c) JetBrains s.r.o.","CFBundleShortVersionString":"3.5.3"}
[   +5 ms] executing: /usr/bin/plutil -convert json -o - /Users/paul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/Info.plist
[   +7 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/paul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_P
ACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.5","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$A
PP_PACKAGE\/Contents"}},"LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-191.8026.42.35.6010548","CFBundleDevelopmentRegion":"English","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersio
nString":"3.5","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApp
licationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","CFBundleGetInfoString":"Android Studio 3.5, build AI-191.8026.42.35.6010548. Copyright JetBrains s.r.o., (c) 2000-2019"}
[   +5 ms] executing: /Users/paul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +67 ms] Exit code 0 from: /Users/paul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +1 ms] executing: [/Users/paul/StudioProjects/multiline_fun/android/] /Users/paul/StudioProjects/multiline_fun/android/gradlew -Pverbose=true -Ptarget=/Users/paul/StudioProjects/multiline_fun/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm assembleDebug
[ +771 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +185 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +96 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[  +73 ms] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 1s
[        ] 30 actionable tasks: 3 executed, 27 up-to-date
[ +354 ms] Running Gradle task 'assembleDebug'... (completed in 1,6s)
[  +32 ms] calculateSha: LocalDirectory: '/Users/paul/StudioProjects/multiline_fun/build/app/outputs/apk'/app.apk
[ +158 ms] calculateSha: reading file took 157us
[ +526 ms] calculateSha: computing sha took 525us
[   +3 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +2 ms] executing: /Users/paul/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/paul/StudioProjects/multiline_fun/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +8 ms] Exit code 0 from: /Users/paul/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/paul/StudioProjects/multiline_fun/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.multiline_fun" (Raw: "com.example.multiline_fun")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="multiline_fun" (Raw: "multiline_fun")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.multiline_fun.MainActivity" (Raw: "com.example.multiline_fun.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on SM T580.
[        ] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell am force-stop com.example.multiline_fun
[ +193 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell pm list packages com.example.multiline_fun
[ +953 ms] package:com.example.multiline_fun
[   +4 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell cat /data/local/tmp/sky.com.example.multiline_fun.sha1
[  +37 ms] d8daf5bffe6118256ecb9b327f67feb5510b86b7
[        ] Latest build already installed.
[        ] SM T580 startApp
[   +2 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.multiline_fun/com.example.multiline_fun.MainActivity
[ +118 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.multiline_fun/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +866 ms] Observatory URL on device: http://127.0.0.1:47044/vztAuCOxS5Y=/
[   +1 ms] executing: /Users/paul/Library/Android/sdk/platform-tools/adb -s 33006b57244db5fd forward tcp:0 tcp:47044
[   +8 ms] 58153
[        ] Forwarded host port 58153 to device port 47044 for Observatory
[  +11 ms] Connecting to service protocol: http://127.0.0.1:58153/vztAuCOxS5Y=/
[ +488 ms] Successfully connected to service protocol: http://127.0.0.1:58153/vztAuCOxS5Y=/
[   +3 ms] Sending to VM service: getVM({})
[   +6 ms] Result: {type: VM, name: vm, architectureBits: 32, hostCPU: Unknown, operatingSystem: android, targetCPU: arm, version: 2.8.0-dev.6.0.flutter-fc3af737c7 (Fri Jan 24 09:53:26 2020 +0000) on "android_arm", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: ...
[   +4 ms] Sending to VM service: getIsolate({isolateId: isolates/3640369962218979})
[   +3 ms] Sending to VM service: _flutter.listViews({})
[  +16 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe5166290, isolate: {type: @Isolate, fixedId: true, id: isolates/3640369962218979, name: main.dart$main-3640369962218979, number: 3640369962218979}}]}
[   +5 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: multiline_fun})
[  +67 ms] Result: {type: Isolate, id: isolates/3640369962218979, name: main, number: 3640369962218979, _originNumber: 3640369962218979, startTime: 1580398954222, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[  +12 ms] D/libGLESv2(23561): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.multiline_fun
[        ] Result: {type: FileSystem, name: multiline_fun, uri: file:///data/user/0/com.example.multiline_fun/code_cache/multiline_funHOEWQO/multiline_fun/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.multiline_fun/code_cache/multiline_funHOEWQO/multiline_fun/)
[   +1 ms] Updating assets
[  +99 ms] Syncing files to device SM T580...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +7 ms] /Users/paul/Development/flutter/bin/cache/dart-sdk/bin/dart /Users/paul/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/paul/Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--target=flutter -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/vs/h520s0yd1jlgwppdch09_m7h0000gn/T/flutter_tool.Dwhz0c/app.dill --packages /Users/paul/StudioProjects/multiline_fun/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[   +4 ms] <- compile package:multiline_fun/main.dart
[+3628 ms] D/ViewRootImpl@61907a3[MainActivity](23561): ViewPostIme pointer 0
[  +71 ms] D/ViewRootImpl@61907a3[MainActivity](23561): ViewPostIme pointer 1
[ +189 ms] D/InputMethodManager(23561): SSI - flag : 0 Pid : 23561 view : com.example.multiline_fun
[  +16 ms] V/InputMethodManager(23561): Starting input: tba=android.view.inputmethod.EditorInfo@1d4623d nm : com.example.multiline_fun ic=io.flutter.plugin.editing.InputConnectionAdaptor@58a9a32
[        ] D/InputMethodManager(23561): startInputInner - Id : 0
[        ] I/InputMethodManager(23561): startInputInner - mService.startInputOrWindowGainedFocus
[   +7 ms] D/InputTransport(23561): Input channel constructed: fd=90
[        ] D/InputTransport(23561): Input channel destroyed: fd=87
[  +58 ms] D/ViewRootImpl@61907a3[MainActivity](23561): MSG_RESIZED: frame=Rect(0, 0 - 1200, 1920) ci=Rect(0, 36 - 0, 557) vi=Rect(0, 36 - 0, 557) or=1
[  +29 ms] D/ViewRootImpl@61907a3[MainActivity](23561): Relayout returned: old=[0,0][1200,1920] new=[0,0][1200,1920] result=0x1 surface={valid=true 3279362048} changed=false
[ +806 ms] Updating files
[ +257 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device SM T580... (completed in 5.082ms, longer than expected)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +6 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe5166290, isolate: {type: @Isolate, fixedId: true, id: isolates/3640369962218979, name: main.dart$main-3640369962218979, number: 3640369962218979}}]}
[        ] <- accept
[        ] Connected to _flutterView/0xe5166290.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on SM T580 is available at: http://127.0.0.1:58153/vztAuCOxS5Y=/
[ +104 ms] I/flutter (23561): t
[ +337 ms] I/flutter (23561): te
[ +186 ms] I/flutter (23561): tes
[ +334 ms] I/flutter (23561): test
[ +898 ms] I/flutter (23561): Test
[+7548 ms] I/zygote  (23561): Do partial code cache collection, code=26KB, data=30KB
[        ] I/zygote  (23561): After code cache collection, code=26KB, data=30KB
[        ] I/zygote  (23561): Increasing code cache capacity to 128KB
[ +995 ms] I/flutter (23561): Testn
[ +870 ms] I/flutter (23561): Testne
[ +226 ms] I/flutter (23561): Testnew
[ +575 ms] I/flutter (23561): Testnewl
[ +303 ms] I/flutter (23561): Testnewli
[ +305 ms] I/flutter (23561): Testnewlin
[ +422 ms] I/flutter (23561): Testnewline
```

```
Pauls-MacBook-Pro:multiline_fun paul$ flutter analyze
Analyzing multiline_fun...                                              

   info • The value of the field '_counter' isn't used • lib/main.dart:47:7 • unused_field

1 issue found. (ran in 2.0s)
```

```
Pauls-MacBook-Pro:multiline_fun paul$ flutter doctor -v
[✓] Flutter (Channel master, v1.14.7-pre.38, on Mac OS X 10.15.3 19D76, locale de-DE)
    • Flutter version 1.14.7-pre.38 at /Users/paul/Development/flutter
    • Framework revision 92f7e16312 (14 hours ago), 2020-01-29 17:51:31 -0800
    • Engine revision 6007c17fd2
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/paul/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/paul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/paul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM T580 • 33006b57244db5fd • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

</details>

**Comment by Inf0rmatix** [comment]
I found a somewhat related issue in another project where they wrote their own input, experienced the same issue and fixed it with those lines:
https://github.com/memspace/zefyr/pull/195/commits/c5f34ce63bf9079e4dc21b48078fbba3a0def1d7

**Comment by lifenautjoe** [comment]
We're experiencing the same issue over at https://github.com/OkunaOrg/okuna-app since yesterday on the latest Flutter master branch.

People have reported this bug on the SwiftKey keyboard.

**Comment by crtl** [comment]
Having the same issue using just the defaults:

```
TextField(
  maxLines: 20,
  keyboardType: TextInputType.multiline,
),
```

Pressing the `Return` key has no effect.

I have created a basic demo: [crtl/flutter-text-field-return-demo](https://github.com/crtl/flutter-text-field-return-demo)

```
[√] Flutter (Channel master, v1.15.3-pre.58, on Microsoft Windows [Version 10.0.18362.657], locale en-DE)
    • Flutter version 1.15.3-pre.58 at D:\dev\flutter\sdk
    • Framework revision f769bcc5c4 (6 days ago), 2020-02-10 20:55:48 -0500
    • Engine revision e4f46f32f1
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 fd992e423e)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\dev\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\dev\Android\SDK
    • Java binary at: D:\Programms\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at D:\Programms
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM A520F   • 5210ae1cf4a7448d • android-arm64  • Android 8.0.0 (API 26)
    • Chrome     • chrome           • web-javascript • Google Chrome 80.0.3987.106
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!

```

**Comment by qiaoshouqing** [comment]
I had the same problem after updating

**Comment by SaranSundar** [comment]
Yah I can confirm it works with the default google keyboard but it's not working on SwiftKey for me either. I keep getting this error. 

E/SpannableStringBuilder(16503): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

And the fixes I see online for that error don't work here anymore.

**Comment by fantastxmw** [comment]
Not work with Gboard pinyin.

**Comment by GaryQian** [comment]
cc @gspencergoog

**Comment by SaranSundar** [comment]
Hmm, my issue isn't related to a Samsung keyboard though. I use a Google pixel 2xl with the Swipe keyboard.

**Comment by ElaineSchwner** [comment]
The same case.

I had to return to Flutter stable to publish the app.

**Comment by SaranSundar** [comment]
> The same case.
> 
> I had to return to Flutter stable to publish the app.

Are you saying this issue doesn't occur in flutter stable?

**Comment by ElaineSchwner** [comment]
It doesn’t occur on flutter stable. But another error occurs on flutter stable, when we type the text and after that a setstate occurs, the text disappears.
We have to choose between these two erros. Or the text is erased after setState or we can break lines.

**Comment by ElaineSchwner** [comment]
> > The same case.
> > I had to return to Flutter stable to publish the app.
> 
> Are you saying this issue doesn't occur in flutter stable?

I answered above.

**Comment by justinmc** [comment]
This should be fixed with https://github.com/flutter/engine/pull/16560.

If anyone is still seeing this bug on master, please let me know and I can reopen.

**Comment by aavgeen** [comment]
I am still seeing this issue with **Microsoft SwiftKey Keyboard** @justinmc

**Comment by ayush221b** [comment]
@justinmc @TahaTesser facing the same issue while using **Microsoft SwiftKey Keyboard**. The behaviour is perfect when using Gboard.

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.17.5 at /Users/ayushshekhar/development/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/ayushshekhar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/ayushshekhar/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by justinmc** [comment]
I couldn't reproduce this on Flutter master on a physical Pixel2 with Microsoft SwiftKey.  Can anyone reproduce this on master?  @ayush221b I see you're using an old Flutter version.

<details>
<summary>Code:</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(padding: EdgeInsets.all(4), child: TextField(minLines: 2, maxLines: 4)),
      ),
    );
  }
}
```

</details>

**Comment by ayush221b** [comment]
@justinmc Yes, this is fixed in latest stable (1.20.1). Thank you.

**Comment by justinmc** [comment]
Awesome!  Thanks for checking

**Comment by kristijorgji** [comment]
This bug still exist for me using, i cannot have "newline button" in ios
`Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git`


```
TextField(
                  controller: _textEditingController,
                  keyboardType: TextInputType.multiline,
                  textInputAction: TextInputAction.newline,
                  onSubmitted: _textMessageSubmitted,
    
```

**Comment by justinmc** [comment]
@kristijorgji Can you open a new issue with repro code and tag me?
