### ISSUE TITLE
Allow custom colors for the Icons.done used in the CheckedPopupMenuItem

### ISSUE THREAD

**Issue by hicnar** [flutter/flutter#50108]
If in the app the background color is dark the icon becomes indistinguishable.

**Comment by VladyslavBondarenko** [comment]
Hi @hicnar 
Could you send a code sample to reproduce your case?
Can't you use [color property for icons](https://api.flutter.dev/flutter/widgets/Icon/color.html)?

**Comment by hicnar** [comment]
Just create a PopupMenuButton and use CheckedPopupMenuItem's with dark background
No I cannot use color propterty for icons because it is hardcoded in the flutter code. Here's an excerpt from popup_menu.dart (code formatting does not seem to work in my browser)

@override
  Widget buildChild() {
    return ListTile(
      enabled: widget.enabled,
      leading: FadeTransition(
        opacity: _opacity,
        child: Icon(_controller.isDismissed ? null : Icons.done),
      ),
      title: widget.child,
    );
  }

**Comment by salihgueler** [comment]
`CheckedPopupMenuItem` is giving you a chance to create a check mark PopupMenuItem without dealing with the boiler plate. If you want to create a custom approach, you should use `PopupMenuItem` and implement it by yourself.

You can check the example that I created here.

https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

**Comment by hicnar** [comment]
@salihgueler unless you're talking about pretty recent code changes in flutter it does not give me such a chance. 

If you look at the code I pasted above which comes from flutter codebase you will see that the icon definition is hardcoded. There is no way I can pass the color to it. I've just worked around this by implementing my own CheckedPopupMenuItem with the only difference being 
`Icon(_controller.isDismissed ? null : Icons.done, color: iconColor)` instead of Icon(_controller.isDismissed ? null : Icons.done)

PS. Your link leads to a dart console with the standard "hello world" statefull widget based flutter app (click counting) - nothing related to PopupMenuItems there.

**Comment by salihgueler** [comment]
I don't know why Dartpad didn't work, but I removed the link to prevent confusion.

_I am not working in the Flutter team, I am just giving you my opinion :)_ 

As I stated above. You can't achieve what you want with `CheckedPopupMenuItem`, it's just there to give you a convenience widget to have a faster approach on that matter. Because when they give a color access,  they should give it for all the states as well in case some needs it. That's why what you ask is custom and that's why you can achieve it directly by using `PopupMenuItem`. 

The code below just creates the layout and gives you a chance to have the same layout. You just need to port the logic about it to a StatefulWidget and it should be fine. 

```
    PopupMenuItem<Commands>(
        child: ListTile(leading: Icon(Icons.check, color: Colors.white),   title: Text('Works'),
   ),
```

**Comment by hicnar** [comment]
Thanks for that! You see the problem is with the code you've pasted right above is that it defines the icon shown on the button when the menu is collapsed, and I am talking about the default Icons.done icon that is a part of `CheckedPopupMenuItem` class and appears to the left of your selection when the menu is expanded - please have a look at the attached image.

![Screenshot from 2020-02-04 14:10:50](https://user-images.githubusercontent.com/1816194/73752241-77c03200-4758-11ea-9973-478301743fd9.png)

After my workaround it is displayed in exactly the same color as the rest of the fonts, but before it would be displayed in the default grey and as such you would not be able to see it with black (or dark) background.

**Comment by VladyslavBondarenko** [comment]
@salihgueler thanks for the input!
@hicnar I'm glad the issue is solved, closing it
if you disagree please write in the comments (if it's still a proposal) and I will reopen it
Thank you

**Comment by hicnar** [comment]
@VladyslavBondarenko it certainly is NOT resolved as one should not have to implement a statefull widget looking almost exactly like one of the classes that already is a part of Flutter just so that an icon can be displayed in a desired color. The only thing that needs to be changed in the original Flutter code is allowing custom color to the icon constructor ex 'Icon(_controller.isDismissed ? null : Icons.done, color: iconColor)'
