### ISSUE TITLE
[App.framework] Linked and embedded framework 'App.framework' was built for iOS/iOS Simulator

### ISSUE THREAD

**Issue by JagandeepBrar** [flutter/flutter#50568]
## Steps to Reproduce

1. Prepare application for running
2. Run `flutter run` or `flutter run --debug`
3. Build fails

### Terminal Output

<img width="844" alt="Screen Shot 2020-02-11 at 9 28 03 AM" src="https://user-images.githubusercontent.com/3048295/74250852-d9c8ec00-4cb0-11ea-90f2-5cbe8f866e26.png">

### flutter doctor -v

```bash
➜ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.4 19E224g, locale en-CA)
    • Flutter version 1.12.13+hotfix.7 at /Users/jagandeepbrar/Development/flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jagandeepbrar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.4, Build version 11N111s
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 8 Plus • 934E82BE-9245-43CC-8A33-9E17C8806E78 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

## Notes

This appears to have started since upgrading to Catalina 10.15.4 beta with Xcode 13.4 beta, which also updated Simulator to 13.4 (921.4).

The application compiles and runs correctly on a physically attached device, but no simulators of any devices can pass this stage.

EDIT: Just attempted both Flutter beta and dev channels, and the same error occurs after rebuilding the tools and running `flutter clean` in the project root.

**Comment by JagandeepBrar** [comment]
As an update, just finished reinstalling the stable release of Xcode and using `xcode-select` to set it back to 11.3.1, and it works as expected. Launches in all emulators.

Something must have broken in 11.4 beta.

**Comment by jmagman** [comment]
I'm also on Xcode 11.4 beta and I just created a new app and was able to `flutter run -d <simulator>` without build errors on Flutter 1.12.13+hotfix.7.

1. Did you run `sudo xcodebuild -runFirstLaunch` after you `xcode-select` to Xcode 11.4?
1. Are you able to run on that simulator from `ios/Runner.xcworkspace` in Xcode?

**Comment by JagandeepBrar** [comment]
Hi @jmagman, thanks for responding. Yes, I did do the first run and I have tried running through Xcode as well and it is throwing me the same error.

<img width="700" alt="Screen Shot 2020-02-11 at 8 40 19 PM" src="https://user-images.githubusercontent.com/3048295/74298258-d2383000-4d0e-11ea-8e76-a013c6aa205f.png">

Let it be noted that it can build for generic iOS devices, and can run on physical devices, but is only showing this error on simulators.

With both Xcode's installed together, I can use the beta (11.4) simulator with stable Xcode (11.3.1) and it works correctly. So it must be something in Xcode 11.4 that is causing the issue.

**Comment by jmagman** [comment]
I briefly saw this error, and I'm not sure how to I got into or out of that state.

It's failing to even start the build to get to the script that would assemble the right variant.  We could [swap App.framework to App.xcframework](https://github.com/flutter/flutter/issues/36204) but that would be a nightmare of a project file migration...

**Comment by jmagman** [comment]
Does `rm -rf ios/Flutter/App.framework` get you unstuck?

**Comment by JagandeepBrar** [comment]
I reset my `ios` folder, which effectively deleted App.framework since it's in the .gitignore, and it seems to be working now! Works from both Xcode 11.4 and `flutter run -d <id>`.

**Comment by jmagman** [comment]
Glad you have a workaround, but this is concerning so I'm going to reopen until we understand how often this is happening.

Can you let us know if you see it again, and how you got in that state?

**Comment by JagandeepBrar** [comment]
I had another machine that had a copy of the project on it. Using the `App.framework` from that project causes the issue to reappear. I have attached an archive that contains both a working and non-working copy of App.framework. I hope that can help you with the debugging!

If there are any other files you may want please let me know!

[Issue 50568.zip](https://github.com/flutter/flutter/files/4189735/Issue.50568.zip)

**Comment by JagandeepBrar** [comment]
With the rebuilt `App.framework` I am not longer able to launch on my physical device. I now get this: 

<img width="1074" alt="Screen Shot 2020-02-11 at 10 11 07 PM" src="https://user-images.githubusercontent.com/3048295/74302459-3b727000-4d1c-11ea-8a15-154577897cd1.png">

It appears that the first build of `App.framework` causes it to only be compatible with the device type (simulator or physical) that is being used for that run.

Deleting `App.framework` will cause it to be rebuilt and it will work correctly until you switch device types again. Running just `flutter clean` isn't enough, but you'll have to run it when you delete `App.framework`.

Again this only occurs with Xcode 11.4/Simulator 11.4. I did a build for physical devices which created an `App.framework`. Attempted to launch with Simulator 11.4 running an iOS 13.4 image and it failed to launch. I switched the command line tools back to Xcode 11.3/Simulator 11.3, and without changing `App.framework` it still works.

**Comment by genert** [comment]
Can confirm, you have to remove "App.framework" when switching device that you are building for.

This only applies to >= XCode 11.4.

I guess the best solution is modify "flutter clean" that it removes "App.framework" when such XCode version is detected.

Also, it would be excellent to ask from Apple XCode team what exactly did they change that produced such behaviour. Change log does not give any such information - https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_beta_release_notes

Although they did add features how test frameworks are built, perhaps this feature is undocumented side effect of that.

**Comment by jmagman** [comment]
Xcode 11.4 seems very un-amenable to a thinned App.framework...
\cc @jonahwilliams

**Comment by jonahwilliams** [comment]
I don't think there is a technical limitation to building all of the simulator and device arches and lipoing them together ... provided that works, right?

**Comment by jmagman** [comment]
> I don't think there is a technical limitation to building all of the simulator and device arches and lipoing them together ... provided that works, right?

I think that's probably the best path forward.
Ideally we could create an App.xcframework, particularly since Xcode 11 is the new minimum version required.  However I don't know how to migrate existing Xcode projects to point update "App.framework" to "App.xcframework".

**Comment by jmagman** [comment]
`flutter clean` to remove `ios/Flutter/App.framework` is in https://github.com/flutter/flutter/issues/12631

**Comment by jmagman** [comment]
There's actually no reason to link on App.framework, it just needs to be embedded.

**Comment by jmagman** [comment]
But if you remove the link, the next error is:
```
 Building for iOS Simulator, but the embedded framework 'App.framework' was built for iOS.
```

**Comment by jmagman** [comment]
Hm why are we even copying any frameworks to `ios/Flutter` instead of just copying to `${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/`?  That would solve https://github.com/flutter/flutter/issues/37850 once and for all.  See also https://github.com/flutter/flutter/pull/33684.

**Comment by jmagman** [comment]
@JagandeepBrar @genert The fix was merged.  Would you mind trying this on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) by upgrading, then running `flutter build ios` in your project?

Note: the migration is destructive to the Xcode project, so you won't be able to switch to master and then switch back to other channels.  Make sure you are using source control to revert the Xcode project changes if you need to go back to dev, beta, or stable.

**Comment by Moosphan** [comment]
I had the same problem in my project, and i will try what you said and let u know after that.

**Comment by JagandeepBrar** [comment]
@jmagman I can confirm that it now works as expected. Switched to master branch, ran `flutter build ios` as requested, then `flutter run` with a simulator attached. Closed the simulator, connected my physical device, ran `flutter run` again and launched successfully!

**Comment by jmagman** [comment]
Thank you, @JagandeepBrar.

**Comment by jmagman** [comment]
If anyone is hitting this issue and the tool isn't automatically migrating you, please see manual migration instructions at https://flutter.dev/docs/development/ios-project-migration.

**Comment by genert** [comment]
Confirming here as well that it works. Nice job @jmagman !

**Comment by Moosphan** [comment]
YEAH, in latest version, it has been solved.

**Comment by Turaiiao** [comment]
It's a terrible problem. I ran successfully on the simulator, but I failed again on the real machine.
`error: Building for iOS, but the linked and embedded framework 'App.framework' was built for iOS Simulator. (in target 'Runner' from project 'Runner')
`

**Comment by jmagman** [comment]
@Turaiiao 
> If anyone is hitting this issue and the tool isn't automatically migrating you, please see manual migration instructions at https://flutter.dev/docs/development/ios-project-migration.

Nothing should be linking on `App.framework` after following those instructions.  You're still seeing the error?

**Comment by Turaiiao** [comment]
> YEAH，最新版本已解决。

哪个版本？

**Comment by Turaiiao** [comment]
> @Turaiiao
> 
> > If anyone is hitting this issue and the tool isn't automatically migrating you, please see manual migration instructions at https://flutter.dev/docs/development/ios-project-migration.
> 
> Nothing should be linking on `App.framework` after following those instructions. You're still seeing the error?

After I delete the app.framework, I can install it on the physical machine, but not the virtual machine. I'm trying to update the main branch and try again.

**Comment by Bathant** [comment]
I think you need to delete App.framework then make a build then add the framework again 
it will added successfully that's weird behaviour but it works for me .

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/51453 is in v1.15.4 and will be in the beta channel any second.  If you switch from beta, dev, or master back to stable, you may hit this issue.  Please try the migration steps at https://flutter.dev/docs/development/ios-project-migration.

@Bathant @Turaiiao the instructions don't say to delete the App.framework (your compiled dart code) from your machine, it says to remove the reference from Xcode.  Please follow those instructions, or stick to a Flutter version v1.15.4 or higher.

**Comment by blueberryparm** [comment]
I updated my iOS device to iOS 13.4 and macOS to Catalina 10.15.4 and application runs on simulator but not on physical device unless I remove the App.framework. Is this another bug? For every application I need to remove this file?

**Comment by JagandeepBrar** [comment]
@blueberryparm A documentation link was posted earlier ([here](https://flutter.dev/docs/development/ios-project-migration) on how to migrate the project to use the new build pattern.

**Comment by blueberryparm** [comment]
What a headache but I was able to make it work, thanks Juggy!!!

**Comment by ArthurKnight** [comment]
DO this and can't install app . No code signature found

**Comment by jmagman** [comment]
@ArthurKnight Did you follow the instructions in https://flutter.dev/docs/development/ios-project-migration?

Particularly the build phase:
```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
```

**Comment by eospi** [comment]
How can I account for the `shared_preferences` framework? I followed the guide, which fixed most everything except for this error:
 ```
flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+3/ios/Classes/SharedPreferencesPlugin.h:5:9: 'Flutter/Flutter.h' file not found
```
Thanks!

**Comment by jmagman** [comment]
@eospi that's unrelated, please file a new issue.

**Comment by leecommamichael** [comment]
My teammate was checking the status of a platform-view bug on the beta branch. He switched back to stable and reverted xcode project changed, but now the app renders, but is not interactive. The text fields on our login page cannot be focused when tapped.

**Comment by jmagman** [comment]
@leecommamichael This issue is closed and is tracking a linker error (fails during compilation).  Please file a new issue so the right team can look.

**Comment by dev-shanghai** [comment]
@jmagman Thanks for this.

**Comment by coduy96** [comment]
Open your Xcode
File
WorkSpaceSetting
Build System: Legacy build system

**Comment by Abhishek0116** [comment]
> Does `rm -rf ios/Flutter/App.framework` get you unstuck?

This is working perfectly.

**Comment by wangfeng211** [comment]
> > Does `rm -rf ios/Flutter/App.framework` get you unstuck?
> 
> This is working perfectly.

It worded for me

**Comment by jmagman** [comment]
> Open your Xcode
> File
> WorkSpaceSetting
> Build System: Legacy build system

Never use legacy build system, it causes different issues and is no longer supported.

**Comment by mbaleczny** [comment]
I'm having the same problem but while importing flutter module into my existing iOS project [add-to-app](https://flutter.dev/docs/development/add-to-app/ios/project-setup)

I tried with option B (with and without `--xcframework --no-universal`) and option C. I'm getting the same errors as above or `While building for iOS Simulator, no library for this platform was found in 'App.xcframework'.` when building with `--xcframework --no-universal`.

Flutter module created with flutter version as below (1.18.0). 

Any ideas on how to solve this case?

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.18.0 at /Users/user/development/flutter
    • Framework revision 14f3a36aba (3 days ago), 2020-04-03 17:06:01 -0700
    • Engine revision 09bc1fc45e
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 e736495eb7)
...
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
....
[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 9056AB1A-B0F1-4E98-8DF2-603A7FD5410A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.163
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jmagman** [comment]
@mbaleczny This issue is closed, please file a new issue.
