### ISSUE TITLE
resizeToAvoidBottomInset: true does not affect BottomNavigationBar or BottomAppBar

### ISSUE THREAD

**Issue by RoyARG02** [flutter/flutter#50564]
## Steps to Reproduce

- Tap the textfield.
- The soft keyboard is invoked, shifting the scaffold (as depicted by **resizeToAvoidBottomInset: true** and the docked FAB), but the BottomNavigationBar gets behind the keyboard.

![resizeToAvoidInsetIssue](https://user-images.githubusercontent.com/44899587/74243204-55548880-4d05-11ea-8826-0cabfe111201.gif)

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController _controller = TextEditingController();
  int _selectedTab = 0;
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          resizeToAvoidBottomInset: true,
          appBar: AppBar(title: Text('Example')),
          body: Center(
            child: SizedBox(
              child: TextField(
                decoration: InputDecoration(),
                controller: _controller,
              ),
            ),
          ),
          floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
          floatingActionButton: FloatingActionButton(
            child: Icon(Icons.clear),
            onPressed: () {},
          ),
          bottomNavigationBar: BottomNavigationBar(
            currentIndex: _selectedTab,
            unselectedItemColor: Colors.blueGrey,
            selectedItemColor: Colors.indigo,
            onTap: (i) {
              setState(() => _selectedTab = i);
            },
            items: [
              BottomNavigationBarItem(
                icon: Icon(Icons.edit),
                title: Text('Tab 1'),
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.question_answer),
                title: Text('Tab 2'),
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.edit),
                title: Text('Tab 3'),
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.account_box),
                title: Text('Tab 4'),
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.tab),
                title: Text('Tab 5'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

- The same behaviour is also exhibited by BottomAppBar as
```
 bottomNavigationBar: BottomAppBar(
            color: Colors.red,
            child: SizedBox(
              height: 50.0,
            ),
          ),
```
## Logs
No exceptions.
## Flutter Doctor
```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18363.628], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\anura\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\anura\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.42.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Mi A1 • 192.168.31.70:5555 • android-arm64 • Android 10 (API 29)
```

**Comment by nemoryoliver** [comment]
Same issue here even on the stable release.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (4 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

``` 

</details>

**Comment by RoyARG02** [comment]
According to [Material Design](https://material.io/components/app-bars-bottom#behavior):
> The bottom app bar can be covered by keyboards and other temporary surfaces. If your app requires frequent obstruction of the bar, another component should be used instead.

I didn't find anything similar for `BottomNavigationBar`, but I assume it is the same.
Still, overlapping the docked FAB shouldn't be a thing. #26100 tracks this.

**Comment by RoyARG02** [comment]
Closing issue as this is intended, and #26100 is fixed.

**Comment by N00nDay** [comment]
My use case is very simple and I am not sure why this isn't something that would me more widely used. I need to have a TextInput that grows up to 4 lines but still have a floating action button that stays above it properly. But the bottomNavigationBar is always covered by the keyboard. I have tried to move this setup to a column but the floating action buttons placement is not correct and sits to high.

What makes sense:
`
Scaffold
   resizeToAvoidBottomInset: true,
   bottomNavigationBar: ...
   floatingActionButton: ...
   body: ...
`

What we are currently made to do for some odd reason (which still does not work properly):
`
Column(
   children: [
      Expanded(
         child: Scaffold(
            floatingActionButton: ...
            body: ...
         ),
      ),
      BottomNavigationBar(),
   ],
)
`
