### ISSUE TITLE
[Web] [CanvasKit] WebGL context is not cleaned up / lost

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#50721]
When swiping through the pages in the example you see that they are disposed but the context is not lost / cleaned up. This leads to the following error:
`Too many active WebGL contexts. Oldest context will be lost.`

Notice how in this example the flutter logo disappears after the error occurred.

Related to https://github.com/flutter/flutter/issues/50719.

/cc @hterkelsen 

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  PageController pageController;

  @override
  void initState() {
    super.initState();
    pageController = PageController(initialPage: 1);
    ui.platformViewRegistry
        .registerViewFactory('xyz', (int viewId) => SpanElement());
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            FlutterLogo(size: 48),
            Flexible(
              child: PageView.builder(
                controller: pageController,
                itemCount: 20,
                itemBuilder: (context, index) => Page(index: index,),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class Page extends StatefulWidget {
  const Page({
    Key key,
    this.index,
  }) : super(key: key);

  final int index;

  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> {

  @override
  void dispose() {
    super.dispose();
    print('Page ${widget.index} disposed');
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Text('Page ${widget.index}'),
        Expanded(child: HtmlElementView(viewType: 'xyz')),
      ],
    );
  }
}
```

```
[✓] Flutter (Channel master, v1.15.4-pre.51, on Mac OS X 10.15.3 19D76, locale en-CH)
    • Flutter version 1.15.4-pre.51 at /Users/ben/flutter
    • Framework revision dc636069fc (6 hours ago), 2020-02-12 22:22:49 -0800
    • Engine revision e0ebaea590
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 e4c39721c4)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.100
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by muhleder** [comment]
I've got a fix for this but it depends on the proposed solution for cleaning up WebGL contexts on window resize here. https://github.com/flutter/flutter/issues/52485

I'm seeing a memory leak of up to several GBs due to this so it's a bit of a showstopper for using canvasKit.

Anyway, once canvasKit can clear up WebGL contexts, a fix for this issue is provided by this commit https://github.com/muhleder/engine/commit/3ff37dd49077911a14441bccaa117f83fca2581d

Note: we can't do `overlay.skSurface.dispose()` because the overlay.skSurface is the same object as overlay.surface._surface, and overlay.surface._surface is removed and replaced on window resize so we would end up trying to dispose the same skSurface object twice.

**Comment by cbenhagen** [comment]
@muhleder // @hterkelsen any ideas for a workaround we could use? This is currently the only issue blocking us from using Flutter Web.

**Comment by cbenhagen** [comment]
@hterkelsen thank you for the quick reaction. Unfortunately I can still reproduce the error using the above sample code.

```
Flutter 1.20.0-3.0.pre.192 • channel master • https://github.com/flutter/flutter.git
Framework • revision a9ea825abf (88 minutes ago) • 2020-07-08 21:26:03 -0700
Engine • revision 0ec6f6c3f2
```

**Comment by cbenhagen** [comment]
@hterkelsen can you please reopen this issue?

**Comment by cbenhagen** [comment]
@yjbanov is this somehow related to the recently closed https://github.com/flutter/flutter/issues/60401?

**Comment by yjbanov** [comment]
> @yjbanov is this somehow related to the recently closed #60401?

Could be. We'll need to retriage this one.

**Comment by yjbanov** [comment]
Looks like this was fixed by https://github.com/flutter/engine/pull/19546

**Comment by muhleder** [comment]
I think this is still not working because canvaskit doesn’t actually
dispose of the context. Pretty sure my comment from a while back still
applies
https://github.com/flutter/flutter/issues/52485#issuecomment-600617477

**Comment by AndrewGuenther** [comment]
@muhleder Have you tried upstreaming your change to Skia? I'm running into this issue as well. I was able to resolve my problems by applying your change locally: https://github.com/google/skia/compare/master...muhleder:master

**Comment by muhleder** [comment]
@AndrewGuenther Not sure how I would do that? The github Skia repo is just a mirror of https://skia.googlesource.com/skia and I don't see any way to create a pull request on that repo? 

/cc @yjbanov

**Comment by cbenhagen** [comment]
@muhleder have you been able to upstream your change yet?

**Comment by hterkelsen** [comment]
I am talking to the CanvasKit team now about adding a call to delete the context. From inspecting the code, however, it seems that calling `GL.deleteContext` in emscripten doesn't actually delete the context but just cleans up any DOM references to it and sets the current context to the no context. AFAICT there is no way to delete the context besides allowing the browser to GC it or delete it when there are too many active contexts, so you may still see the warning even after we call `GL.deleteContext`...

**Comment by darshankawar** [comment]
@cbenhagen 
Ran the code sample on latest master and swiped back and forth few times (0 to 19 and back to 0) but didn't see the error as mentioned.


```
Page 0 disposed
Page 1 disposed
Page 2 disposed
Page 3 disposed
Page 4 disposed
Page 5 disposed
Page 6 disposed
Page 7 disposed
Page 8 disposed
Page 9 disposed
Page 10 disposed
Page 11 disposed
Page 12 disposed
Page 13 disposed
Page 14 disposed
Page 15 disposed
Page 16 disposed
Page 17 disposed
Page 18 disposed
Page 19 disposed
Page 18 disposed
Page 17 disposed
Page 16 disposed
Page 15 disposed
Page 14 disposed
Page 13 disposed
Page 12 disposed
Page 11 disposed
Page 10 disposed
Page 9 disposed
Page 8 disposed
Page 7 disposed
Page 6 disposed
Page 5 disposed
Page 4 disposed
Page 3 disposed
Page 2 disposed
Page 1 disposed
Page 0 disposed
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.45, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-5.0.pre.45 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 81e1f7d1ed (10 hours ago), 2020-12-02 17:19:57 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

</details>

Can you confirm from your end ?

**Comment by cbenhagen** [comment]
@hterkelsen is there an open issue or PR on their end that I could follow? I don't mind having some warnings, as long as the UI does not crash like it currently does. It sounds like `GL.deleteContext` would fix this.

@darshankawar yes I can confirm that the error still appears in the browser console when using the latest master (1.25.0-5.0.pre.45). I updated the example to make the issue more obvious. Please notice how the flutter logo disappears after the error occurred. In our app the whole UI disappears after we created more than 15 WebGL contexts.

If you still can't reproduce, please make sure you enabled CanvasKit by running with `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`.

**Comment by cbenhagen** [comment]
@yjbanov may I ask you to re-open this issue? The example in the issue is still failing.

**Comment by yjbanov** [comment]
Hoping that 2nd time's the charm :)

**Comment by Iampato** [comment]
Same issue I am experiencing
`flutter doctor -v`
```
[√] Flutter (Channel dev, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-12.0.pre at C:\flutter
    • Framework revision a706cd2112 (2 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pato\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)       
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\pato\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.53 

```
