### ISSUE TITLE
DecorationImage's colorFilter is not applying on web

### ISSUE THREAD

**Issue by SunFoxx** [flutter/flutter#50897]
It seems like I can't apply colorFilter to any image when targeting web platform. Result is always the same as the source image, which is mean filters doing nothing to the image

## Steps to Reproduce
I have code like this
`Container(
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage("assets/images/me.jpg"),
                  fit: BoxFit.cover,
                  colorFilter: ColorFilter.mode(Colors.grey, BlendMode.saturation),
                ),
              ),
              height: 100,
            ),
`

You can also experiment with image types, different filters and colors. Result is always the same

**Expected results:** I want to see a widget to work as intended i.e. grayed out background image

**Actual results:** I see the same image as there is no filter at all

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale ru-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] VS Code (version 1.42.1)
[✓] Connected device (2 available)

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @SunFoxx 

![Screenshot_20200217-134026](https://user-images.githubusercontent.com/48603081/74635182-7bf24380-518b-11ea-9d37-9ff473727680.jpg)
![Annotation 2020-02-17 134142](https://user-images.githubusercontent.com/48603081/74635187-7eed3400-518b-11ea-96ed-3255b5e24532.png)

Definitely an issue
Thanks for your contribution

**Comment by matthew-carroll** [comment]
FYI @csells - I've got some Flutter training materials that involve `Image` `color` and `blendMode`. I was hoping to bring those little exercises over to DartPad to reduce education friction. This issue prevents me from doing that.

**Comment by csells** [comment]
cc @zoeyfan

**Comment by JRdufour** [comment]
I'm having this issue too and it's very frustrating. 

This is my widget:
Stack(
            children: <Widget>[
              Container(
                decoration: BoxDecoration(
                  image: DecorationImage(
                    fit: BoxFit.cover,
                    image: NetworkImage(_profileBloc.user.faveGame.bannerUrl),
                    colorFilter: ColorFilter.mode(Colors.pink, BlendMode.color)
                  )
                ),
              ),

            ],
          );
This is how it appears on mobile:
<img width="367" alt="Screen Shot 2020-04-20 at 1 51 17 PM" src="https://user-images.githubusercontent.com/28626866/79783152-362e3480-830e-11ea-985c-d8be06d8567d.png">

And on web:
<img width="501" alt="Screen Shot 2020-04-20 at 1 51 33 PM" src="https://user-images.githubusercontent.com/28626866/79783198-46461400-830e-11ea-9ed0-558abeea0f90.png">

**Comment by ferhatb** [comment]
@JRdufour, @matthew-carroll @csells , Update: fix for this is landing shortly, thanks for patience.

**Comment by ferhatb** [comment]
Fix landed in flutter master channel.

**Comment by madebyfrancisco** [comment]
I still have the same problem. Image appears normally without any color filter.
#
`
Container(
      decoration: BoxDecoration(
        image: DecorationImage(
          image: AssetImage("assets/img.jpeg"),
          colorFilter: ColorFilter.mode(Colors.grey, BlendMode.saturation),
          fit: BoxFit.cover
        ),
      )
);
`
#
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-PT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)

**Comment by romatroskin** [comment]
looks like still not working on the web as well

**Comment by ferhatb** [comment]
@romatroskin if you are seeing an issue please file a new one with a code snippet. The original bug at the very top with AssetImage including color filter was fixed and a test was added to flutter/engine. If you search for issues with label platform-web and colorfilter, you'll see that certain uses of ColorFilter have open issues we are working on, providing feedback there would be great.
