### ISSUE TITLE
flutter_windows_v1.12.13+hotfix.8-stable logging on every tap or when changing screens

### ISSUE THREAD

**Issue by 55ahmedsalah** [flutter/flutter#50892]
## Steps to Reproduce
1. Creating a new flutter project
2. Running the default app

## Logs
```
Launching lib\main.dart on XXXX in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(10399): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(10399): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(10399): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(10399): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(10399): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@500759f
D/FlutterActivityAndFragmentDelegate(10399): Executing Dart entrypoint: main, and sending initial route: /
Syncing files to device XXXX...
E/AccessibilityBridge(10399): VirtualView node must not be the root node.
```

Flutter Doctor:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (5 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • XXXX • XXXXXXXXXXX • android-arm64 • Android 7.0 (API 24)

• No issues found!

```

**Comment by as-Tony-Stark** [comment]
@55ahmedsalah  on which channel you're running flutter check it using `flutter channel` command

**Comment by 55ahmedsalah** [comment]
Running flutter channel gives:
```
Flutter channels:
  beta
  dev
  master
* stable
```
So I am on the stable channel.

**Comment by 55ahmedsalah** [comment]
@as-Tony-Stark 
Running flutter channel gives:
```
Flutter channels:
  beta
  dev
  master
* stable

```So I am on the stable channel.

**Comment by TahaTesser** [comment]
Hi @55ahmedsalah 
This could be related to [#50857](https://github.com/flutter/flutter/issues/50857) [](https://github.com/flutter/flutter/issues/44635)

**Comment by as-Tony-Stark** [comment]
@55ahmedsalah 
Try Upgrading flutter using `flutter upgrade`  lots of people resolved after upgrading it....and if not then try shifting your channel to `dev` branch using `flutter channel dev` then `flutter upgrade`

**Comment by 55ahmedsalah** [comment]
I already have latest stable build so `flutter upgrade` did nothing.
Switching to the `dev `channel did nothing too but creating a new app doesn't show a black screen between the splash screen and the main application which does appear on the `stable` channel.

**Comment by cfchris** [comment]
Just got back to Flutter today. VS Code said to update Flutter. So, I did `flutter upgrade`. I'm on the stable channel. Flutter doctor says "(Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)".

My logs are now flooded constantly with this message.

```
I/chatty  (20429): uid=10479(com.dealerpeak.dealerpeakcrm) identical 1 line
E/AccessibilityBridge(20429): VirtualView node must not be the root node.
E/AccessibilityBridge(20429): VirtualView node must not be the root node.
I/chatty  (20429): uid=10479(com.dealerpeak.dealerpeakcrm) identical 71 lines
E/AccessibilityBridge(20429): VirtualView node must not be the root node.
E/AccessibilityBridge(20429): VirtualView node must not be the root node.
I/chatty  (20429): uid=10479(com.dealerpeak.dealerpeakcrm) identical 9 lines
E/AccessibilityBridge(20429): VirtualView node must not be the root node.
E/AccessibilityBridge(20429): VirtualView node must not be the root node.
I/chatty  (20429): uid=10479(com.dealerpeak.dealerpeakcrm) identical 28 lines
```

It's going to be very difficult to see any actual debugging prints with my logs full of this.

**Comment by TahaTesser** [comment]
Hi @55ahmedsalah  @cfchris 
Could please try `flutter pub cache repair` and  `flutter clean` in your project?  and see if this issue this occurs
Thank you

**Comment by cfchris** [comment]
@TahaTesser , I ran both commands. Then, I ran our project again. Just clicking on stuff in the UI causes a flood of those errors.

So, to eliminate something in our code, I created a temp directory and did `flutter create ./` and `flutter run`. Then, I just clicked on the plus FAB in the default project a bunch of times and I got the following.

```E/AccessibilityBridge( 7593): VirtualView node must not be the root node.
E/AccessibilityBridge( 7593): VirtualView node must not be the root node.
I/chatty  ( 7593): uid=10480(com.example.tmp) identical 5 lines
E/AccessibilityBridge( 7593): VirtualView node must not be the root node.
E/AccessibilityBridge( 7593): VirtualView node must not be the root node.
I/chatty  ( 7593): uid=10480(com.example.tmp) identical 8 lines
E/AccessibilityBridge( 7593): VirtualView node must not be the root node.
```

**Comment by 55ahmedsalah** [comment]
> Hi @55ahmedsalah @cfchris
> Could please try `flutter pub cache repair` and `flutter clean` in your project? and see if this issue this occurs
> Thank you

Both commands (which are on a single project level) did nothing and as I mentioned this happens to all projects being run after the hotfix 8 update.

**Comment by azizk-araneux** [comment]
Yes, it does happen on every action taken on the screen. Even scrolling within Listview causes lots of such errors.
```
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
E/AccessibilityBridge(25354): VirtualView node must not be the root node.
```

**Comment by spitfire55** [comment]
I'm also getting flooded with these errors, along with `E/AccessibilityNodeInfo(24346): Rejecting attempt to make a View its own child` when I have a `google_maps_flutter` Google Maps view. Tried commenting out markers and other overlays, still getting the errors

**Comment by 55ahmedsalah** [comment]
@christopherfujino Any help here please

**Comment by christopherfujino** [comment]
@55ahmedsalah I'm looking into this.

**Comment by christopherfujino** [comment]
So, the accessibility warning was a bug that was fixed [in version 13.0](https://github.com/flutter/engine/pull/14079), unfortunately, after the latest stable was cut.

The reason this was only seen after hotfix 8 was release, was because there was a seperate regression that was over-aggressively filtering logs, which was obscuring legitimate logs (such as app crashes and this accessibility warning). Hotfix 8 [removed this log filtering](https://github.com/flutter/flutter/pull/50488), thus surfacing the accessibility warning.

We apologize for regressing the user experience in this way on the stable channel. This warning message has been fixed on the beta, dev, and master channels, and will be removed from the next stable release.

**Comment by eseidelGoogle** [comment]
@tvolkert @pcsosinski Did we consider this for a hot-fix candidate?  This appears to have been a regression from a hotfix.

**Comment by pcsosinski** [comment]
@eseidel looks like the actual fix is https://github.com/flutter/engine/pull/14079, which I do not believe came across the radar for a hotfix unfortunately (still showing up in .9: https://github.com/flutter/flutter/issues/54196)

**Comment by eseidelGoogle** [comment]
#53990 seemed to describe this as a *regression* in the hotfix itself.  But I don't have data one way or the other.

**Comment by tvolkert** [comment]
The hotfix fixed one bug, which exposed another latent bug (see https://github.com/flutter/flutter/issues/50892#issuecomment-593615696).  The latent bug was fixed by flutter/engine#14079, which was not (until now) raised as a candidate for cherrypick.

**Comment by eseidelGoogle** [comment]
I spoke with Todd and Patrick offline.  We have another stable release coming soon.  It's likely too close to that release for us to take the risk of trying to make a new hotfix including an engine release.

Thanks for flagging and sorry for all the log spam.  We're continuing to work on improving our release processes to catch bugs like this earlier.

The easiest workaround for now is to just use `flutter channel beta` to switch to the beta channel where we have resolved this bug.  Thanks!

**Comment by MichaelSowah** [comment]
thanks @eseidelGoogle and after reading this doc https://github.com/flutter/flutter/wiki/Flutter-build-release-channels critically again, I guess I can equally release a production app with beta as well, thanks again.
