### ISSUE TITLE
Crash report from wild: FileSystemException

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5137]
(Curious if and how we can use our measurements to help us build a more stable product.)

Looking at our analytics, we see a growth in exceptions. The message we have is: "FileSystemException; dart:io/file_impl.dart 807 _RandomAccessFile.writeFromSync dart:io/stdio.dart 2"

Apparently, this is the only exception we're reporting.

Top versions reporting this crash:

![screen shot 2016-07-29 at 9 52 32 am](https://cloud.githubusercontent.com/assets/5479/17256488/9311f542-5572-11e6-9e34-9aead87d5b22.png)

I can see crash counts, but I'm not seeing an obvious way to say "XX% of users are experiencing this crash". Still looking.

**Comment by damien-nd** [comment]
I don't know if I can help, but I just try the 3 first command : https://flutter.io/setup/
On 'flutter doctor' command I get:
`FileSystemException: Directory listing failed, path = '/opt/Android/android-sdk-macosx/platforms/' (OS Error: Permission denied, errno = 13)`
I can see the analytics message but if I run the command a second time, I get the same log file.

The error look like it's here:
`===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/runner/flutter_command_runner.dart 180  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 69                           Cache.lock.<async>`
But can paste all log file if need it.

**Comment by damien-nd** [comment]
Still continue the tutorial, have install everything and just have to fix ideviceinstaller and ios-deploy.

Now I can, I guess, run it but both on 'flutter run' command and atom interface, I get:
Running lib/main.dart on iPhone 6s...

And nothing start on the simulator.

**Comment by sethladd** [comment]
@damien-nd thanks for the feedback. I think you're running into something we also discovered (nothing start on the simulator) https://github.com/flutter/flutter/issues/5398

Are you running with the `master` branch? Curious if it's still happening for you. Would you be able to open a new issue for us if you're still seeing the issue?

**Comment by damien-nd** [comment]
On the Flutter setup page, the command is:
git clone https://github.com/flutter/flutter.git -b alpha

So I checkout on master and run doctor again.
On Atom I get one line after the running line:
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

On terminal, I get one line before the running line:
Running 'pub get' in myapp...

Do I miss something? If not I will open a new issue but look like the same as #5398.
Thank you.

**Comment by sethladd** [comment]
Hi Damien,

Let's open a new bug. I don't think you missed something. Sorry for the troubles, hope we can help sort them out.

**Comment by eseidelGoogle** [comment]
This is still our top crash with 150 reports in the last 7 days.  We don't have a full stack that I'm aware of.

**Comment by danrubel** [comment]
@damien-nd The `flutter doctor` exception should be addressed by https://github.com/flutter/flutter/pull/7167

**Comment by damien-nd** [comment]
@danrubel I didn't play with flutter a long time ago, but I try:
- pull the master repo
- `flutter doctor`
- and `flutter run` on the sample app I created
Looks like everything is working fine.

**Comment by eseidelGoogle** [comment]
We're still seeing this in `flutter` analytics.  FYI @tvolkert.

@yjbanov this should show up in your crash tracking work as soon as it goes live.

**Comment by Hixie** [comment]
This is not really actionable in its current state. Please file a new bug if it still occurs.
