### ISSUE TITLE
How to solve: Android license status unknown and also Android sdkmanager tool not found? Tried everything(as i think)

### ISSUE THREAD

**Issue by Nyanny** [flutter/flutter#51670]
## Steps to Reproduce

1. flutter doctor
```
C:\Users\Zheny>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.693], locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed      instructions.
[√] Android Studio (version 3.6)
[!] VS Code (version 1.42.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
2. flutter doctor --android-licenses
```
Android sdkmanager tool not found (C:\Users\Zheny\AppData\Local\Android\Sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.
```
3. Tried everything i had found. Also tried to re-install Android SDK(29) from Android Studio

4. Screens of my PATH's and folders
![1](https://user-images.githubusercontent.com/17166233/75594256-32fa9300-5a99-11ea-8553-1a4743e686fd.PNG)
![2](https://user-images.githubusercontent.com/17166233/75594262-368e1a00-5a99-11ea-8afa-12f556d66847.PNG)
![3](https://user-images.githubusercontent.com/17166233/75594265-3857dd80-5a99-11ea-87df-d9ee1d42b7b0.PNG)

## Logs

```
```

```
C:\Users\Zheny>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.693], locale ru-RU)
    • Flutter version 1.12.13+hotfix.8 at C:\Flutter SDK\flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Zheny\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Zheny\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.42.1)
    • VS Code at C:\Users\Zheny\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
```
```

**Comment by he0119** [comment]
I think I know the reason.
![image](https://user-images.githubusercontent.com/5219550/75605606-39cbe900-5b1f-11ea-8126-417c9b4fc8db.png)
The android sdk tool has been renamed to android sdk command-line tools, which is located in 
![image](https://user-images.githubusercontent.com/5219550/75605683-b8c12180-5b1f-11ea-9e2b-4ed57904e763.png)
So flutter can't find the sdkmanager. But I don't know how to solve this problem.

**Comment by yuankui** [comment]
+1

**Comment by mebden** [comment]
The answer is [here](https://stackoverflow.com/questions/28789556/android-studio-sdk-tools-directory-is-missing).

Uncheck `Hide Obsolete Packages` and you'll see `Android SDK Tools (Obsolete) 26.1.1`.

Hopefully this can be released in the next Flutter version?

**Comment by kisjinn** [comment]
For me,reinstalling the sdk Manager solved my problem.For this go to SDK Manager in Android Studio and uninstall all the sdk and related packages in sdk tools ,click on apply and then close the Android Studio.Now,again reinstall all the sdk tools.Now on command prompt ,run flutter doctor -v and then if some licenses r not accepted then accept those licenses by running flutter doctor --android-licenses.
     If this doesn't help you out check the jdk version ,it is recommended to have Java 8 installed,parallelly need to change the JAVA_HOME variable and point to Java 8.

**Comment by akshayupendran** [comment]
+1

![image](https://user-images.githubusercontent.com/18658247/75610027-ba94e000-5b33-11ea-8f3d-f625d4fd7c5c.png)

The flutter doctor always searches "sdkmanager" in Sdk\tools\bin\ but i want it to search for sdkmanager in Sdk\cmdline-tools\latest\

**Comment by bintoparambel** [comment]
Yes, installing `Android SDK Tools (Obsolete) 26.1.1` worked for me.

After this I was able to do
`flutter doctor --android-licenses` and select y.

**Comment by iapicca** [comment]
Hi @Nyanny 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51712) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by tvtoankgi** [comment]
> The answer is [here](https://stackoverflow.com/questions/60460429/android-studio-installs-without-sdkmanager).
> 
> Uncheck `Hide Obsolete Packages` and you'll see `Android SDK Tools (Obsolete) 26.1.1`.
> 
> Hopefully this can be released in the next Flutter version?

worked. Thank you very much.

**Comment by puentesdiaz** [comment]
> The answer is [here](https://stackoverflow.com/questions/60460429/android-studio-installs-without-sdkmanager).
> 
> Uncheck `Hide Obsolete Packages` and you'll see `Android SDK Tools (Obsolete) 26.1.1`.
> 
> Hopefully this can be released in the next Flutter version?

tks

**Comment by mauriciopettinate** [comment]
> > The answer is [here](https://stackoverflow.com/questions/60460429/android-studio-installs-without-sdkmanager).
> > Uncheck `Hide Obsolete Packages` and you'll see `Android SDK Tools (Obsolete) 26.1.1`.
> > Hopefully this can be released in the next Flutter version?
> 
> worked. Thank you very much.

Thank you very much for your help, it works for me!

**Comment by mauriciopettinate** [comment]
> I think I know the reason.
> ![image](https://user-images.githubusercontent.com/5219550/75605606-39cbe900-5b1f-11ea-8126-417c9b4fc8db.png)
> The android sdk tool has been renamed to android sdk command-line tools, which is located in
> ![image](https://user-images.githubusercontent.com/5219550/75605683-b8c12180-5b1f-11ea-9e2b-4ed57904e763.png)
> So flutter can't find the sdkmanager. But I don't know how to solve this problem.

https://stackoverflow.com/questions/60460429/android-studio-installs-without-sdkmanager

**Comment by ManuelAlanis** [comment]
> I think I know the reason.
> ![image](https://user-images.githubusercontent.com/5219550/75605606-39cbe900-5b1f-11ea-8126-417c9b4fc8db.png)
> The android sdk tool has been renamed to android sdk command-line tools, which is located in
> ![image](https://user-images.githubusercontent.com/5219550/75605683-b8c12180-5b1f-11ea-9e2b-4ed57904e763.png)
> So flutter can't find the sdkmanager. But I don't know how to solve this problem.

Yes, thats was the reason

**Comment by mauriciopettinate** [comment]
Its easy, but I spent many time to get the solution.

On your first screen, just uncheck the option “Hide obsolete packages”. So, you will see another sdk obsolete package you need install, just check that option, download it and the problem will be solved.

Let me know if its works.

Regards,

Mauricio Pettinate.

**Comment by windcloak** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/40670609/76348239-d89dd580-62d5-11ea-9b7b-18a05958bf80.jpg)
In Android Studio > SDK Manager > 
Appearance and behavior > system settings > Android SDK > SDK tools > uncheck 'Hide obsolete packages' and install Android SDK Tools (obsolete)

Then go to your flutter directory and run
`flutter doctor --android-licenses`
Press y to accept all licenses

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by AwesomeShani** [comment]
> Yes, installing `Android SDK Tools (Obsolete) 26.1.1` worked for me.
> 
> After this I was able to do
> `flutter doctor --android-licenses` and select y.

but did not work for, how can i get rid of it??

**Comment by eturk1** [comment]
recap from issue # 51712, which should keep working with new releases 
1. install the Android SDK Command Line Tools (which is not obsolete)
2. switch to master channel (as they've already added code to also look for the tools

Thanks for the help! Posting here as this was first result in search.

**Comment by jhasan94** [comment]
1.Scroll down and Download Command line tools only from this link . https://developer.android.com/studio#downloads
2.Put your Downloaded file (tools) in this location C:\Users\ABC\AppData\ABC\Android\Sdk
3.close your android studio , and again open android studio. And check update .
4.open command line and past (flutter doctor --android-licenses) ,don’t use parenthesis.
5. And press ‘y’ for accept 
6. Run flutter doctor you should be good.

**Comment by JacquesWaltz** [comment]
Still having this problem: ✗ Android license status unknown.

### Log:
1. Runned `flutter doctor`

`[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.`


2. Runned `flutter doctor --android-licenses`

`A newer version of the Android SDK is required. To update, run:
/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`

3. Runned `/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`

`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more`

Cannot update SDKmanager. (I've already tried re-installing all SDK tools via Android Studio).
So, what should I do now?

**Comment by JacquesWaltz** [comment]
Still having this problem: ✗ Android license status unknown.

### Log:
1. Runned `flutter doctor`

`[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.`


2. Runned `flutter doctor --android-licenses`

`A newer version of the Android SDK is required. To update, run:
/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`

3. Runned `/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`

`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more`

Cannot update SDKmanager. I've already tried re-installing all SDK tools (obsolete ones too) and via Android Studio.
So, what should I do now?

**Comment by eturk1** [comment]
@jhasan94 thanks, a little closer on having that directory but errors still:

error on: `flutter doctor --android-licenses`
`A newer version of the Android SDK is required. To update, run:
C:\Users\erolf\AppData\Local\Android\sdk\tools\bin\sdkmanager --update`

but running `sdkmanager --update` errors with:
`Warning: Could not create settings
java.lang.IllegalArgumentException
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)`

> 1.Scroll down and Download Command line tools only from this link . https://developer.android.com/studio#downloads
> 2.Put your Downloaded file (tools) in this location C:\Users\ABC\AppData\ABC\Android\Sdk
> 3.close your android studio , and again open android studio. And check update .
> 4.open command line and past (flutter doctor --android-licenses) ,don’t use parenthesis.
> 5. And press ‘y’ for accept
> 6. Run flutter doctor you should be good.

**Comment by JennCribbs** [comment]
Installing the obsolete tool worked for me too.  Thank you so much!!!

**Comment by wesleyPedroso32** [comment]
Hello 
I had the same problem that @JacquesWaltz 


> Still having this problem: ✗ Android license status unknown.
> 
> ### Log:
> 1. Runned `flutter doctor`
> 
> `[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1) ✗ Android license status unknown. Try re-installing or updating your Android SDK Manager. See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.`
> 
> 1. Runned `flutter doctor --android-licenses`
> 
> `A newer version of the Android SDK is required. To update, run: /Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> 
> 1. Runned `/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> 
> `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 5 more`
> 
> Cannot update SDKmanager. I've already tried re-installing all SDK tools (obsolete ones too) and via Android Studio.
> So, what should I do now?

![flutter_java1_11](https://user-images.githubusercontent.com/9440831/77609886-fbe49980-6eff-11ea-9cd3-f999c8156def.png)

![image](https://user-images.githubusercontent.com/9440831/77610054-639ae480-6f00-11ea-9226-d5336b3f641b.png)

That even downloading the path tools, don't work and the commander sdkmanager --update the error is `Exception in thread "main" java.lang.NoClassDefFoundError: 


So in my case, the problem was that I used Java JDK 11 to program web API.
But Android Studio uses 1.8, so I had to download JDK 1.8 and change the path of my JAVA_HOME now having to change always when I will use the other.
In my case, it's working.   

![image](https://user-images.githubusercontent.com/9440831/77610189-c5f3e500-6f00-11ea-91cd-09e434c633c5.png)

![flutter_java1 8](https://user-images.githubusercontent.com/9440831/77610209-d1471080-6f00-11ea-9915-5c669f7cf7af.png)

**Comment by jerriclynsjohn** [comment]
I faced the same problem, like mentioned above I tried these.
1. Installed JDK 1.8 and set my JAVA_HOME env to 1.8 - This did not work
2. My Android studio didn't show any "Android SDK Tools (Obsolete)" but had had an "Android SDK Tools"

This is what worked for me:
1. Delete the "Android SDK Tools" from SDK Manager
2. Reinstall it by first deselecting the "Hide Obsolete Packages"  and then select "Android SDK Tools (Obsolete)", install it.
3. run `flutter doctor --android-licenses` and select `y` for the prompts
4. run `flutter doctor` and everything will be fine!!!! 

It's high time flutter come as an installation package ensuring no configuration setup.

**Comment by FigueiredoStable** [comment]
Hy folks,

If you wont wana install obsolete packages, on Mac Os Catalina try this:

# go to your home folder in to Android default SDK folder:
$ cd Library/Android/sdk

# Create a link symbolic for the new folder for sdkmanager binary and others
$ ln -s /Users/figueiredo/Library/Android/sdk/cmdline-tools/latest/ tools

# Run flutter again
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

Now the command 'flutter doctor' was able to found de command and solve the problem.

**Comment by deepakrana24** [comment]
> Yes, installing `Android SDK Tools (Obsolete) 26.1.1` worked for me.
> 
> After this I was able to do
> `flutter doctor --android-licenses` and select y.

yes, it worked.i was trying for about a month but couldn`t fix it but thanks to you it worked .

**Comment by iAbdy** [comment]
Solved for me installing `Android SDK Tools (Obsolete) 26.1.1` .

**Comment by yore-imagine** [comment]
> Hello
> I had the same problem that @JacquesWaltz
> 
> > Still having this problem: ✗ Android license status unknown.
> > ### Log:
> > 
> > 1. Runned `flutter doctor`
> > 
> > `[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1) ✗ Android license status unknown. Try re-installing or updating your Android SDK Manager. See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.`
> > 
> > 1. Runned `flutter doctor --android-licenses`
> > 
> > `A newer version of the Android SDK is required. To update, run: /Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> > 
> > 1. Runned `/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> > 
> > `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 5 more`
> > Cannot update SDKmanager. I've already tried re-installing all SDK tools (obsolete ones too) and via Android Studio.
> > So, what should I do now?
> 
> ![flutter_java1_11](https://user-images.githubusercontent.com/9440831/77609886-fbe49980-6eff-11ea-9cd3-f999c8156def.png)
> 
> ![image](https://user-images.githubusercontent.com/9440831/77610054-639ae480-6f00-11ea-9226-d5336b3f641b.png)
> 
> That even downloading the path tools, don't work and the commander sdkmanager --update the error is `Exception in thread "main" java.lang.NoClassDefFoundError:
> 
> So in my case, the problem was that I used Java JDK 11 to program web API.
> But Android Studio uses 1.8, so I had to download JDK 1.8 and change the path of my JAVA_HOME now having to change always when I will use the other.
> In my case, it's working.
> 
> ![image](https://user-images.githubusercontent.com/9440831/77610189-c5f3e500-6f00-11ea-91cd-09e434c633c5.png)
> 
> ![flutter_java1 8](https://user-images.githubusercontent.com/9440831/77610209-d1471080-6f00-11ea-9915-5c669f7cf7af.png)

iam sorry sir,where can i the jdk 1.8?

**Comment by lucasproj** [comment]
> Its easy, but I spent many time to get the solution. On your first screen, just uncheck the option “Hide obsolete packages”. So, you will see another sdk obsolete package you need install, just check that option, download it and the problem will be solved. Let me know if its works. Regards, Mauricio Pettinate.
> […](#)
> Sent from my iPhone
> On 7 Mar 2020, at 23:05, Manuel Alanis ***@***.***> wrote: I think I know the reason. The android sdk tool has been renamed to android sdk command-line tools, which is located in So flutter can't find the sdkmanager. But I don't know how to solve this problem. Yes, thats was the reason — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

It works for me. Thank you very much!

**Comment by kalithon** [comment]
> For me,reinstalling the sdk Manager solved my problem.For this go to SDK Manager in Android Studio and uninstall all the sdk and related packages in sdk tools ,click on apply and then close the Android Studio.Now,again reinstall all the sdk tools.Now on command prompt ,run flutter doctor -v and then if some licenses r not accepted then accept those licenses by running flutter doctor --android-licenses.
> 
> ```
>  If this doesn't help you out check the jdk version ,it is recommended to have Java 8 installed,parallelly need to change the JAVA_HOME variable and point to Java 8.
> ```

thank you so much this is working after all

**Comment by iapicca** [comment]
Hi all
you may want to check the possible solution from this [issue](https://github.com/flutter/flutter/issues/51712)

if the problem persists please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by anthonygab** [comment]
So this is how I fixed the issue. I tried literally everything I found online, i tried reinstalling android studio, reinstalling jdk, deleting files here and there and reinstalling them, renaming things and nothing seemed to work. So I ended up backing up all my important files and doing a fresh install of Windows operating system and then reinstalled everything according the Flutter documentation and in the SDK manager to download the obsolete tools and that did the trick for me.  I would probaly only use this as a last resort to fixing the issue but it does work.

**Comment by JacquesWaltz** [comment]
As I mentioned, I was also struggling with Android licenses. But this week I got to update flutter and magically after the update everything was installed successfully and Flutter doctor was fine.

**Comment by byJeevan** [comment]
> On your first screen, just uncheck the option “Hide obsolete packages”. So, you will see another sdk obsolete package you need install, just check that option, download it and the problem will be solved.

Worked finally .... Many thanks

**Comment by AvanishCodes** [comment]
> > The answer is [here](https://stackoverflow.com/questions/60460429/android-studio-installs-without-sdkmanager).
> > Uncheck `Hide Obsolete Packages` and you'll see `Android SDK Tools (Obsolete) 26.1.1`.
> > Hopefully this can be released in the next Flutter version?
Where to do that?

**Comment by shohagcsediu** [comment]
Yes, installing Android SDK Tools (Obsolete) 26.1.1 worked for me.

After this I was able to do
flutter doctor --android-licenses and select y.

yes, it worked.i was trying for about a month but couldn`t fix it but thanks to you it worked .

**Comment by AmirGamilDev** [comment]
> 
> 
> Hello
> I had the same problem that @JacquesWaltz
> 
> > Still having this problem: ✗ Android license status unknown.
> > ### Log:
> > 
> > 1. Runned `flutter doctor`
> > 
> > `[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1) ✗ Android license status unknown. Try re-installing or updating your Android SDK Manager. See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.`
> > 
> > 1. Runned `flutter doctor --android-licenses`
> > 
> > `A newer version of the Android SDK is required. To update, run: /Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> > 
> > 1. Runned `/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> > 
> > `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 5 more`
> > Cannot update SDKmanager. I've already tried re-installing all SDK tools (obsolete ones too) and via Android Studio.
> > So, what should I do now?
> 
> ![flutter_java1_11](https://user-images.githubusercontent.com/9440831/77609886-fbe49980-6eff-11ea-9cd3-f999c8156def.png)
> 
> ![image](https://user-images.githubusercontent.com/9440831/77610054-639ae480-6f00-11ea-9226-d5336b3f641b.png)
> 
> That even downloading the path tools, don't work and the commander sdkmanager --update the error is `Exception in thread "main" java.lang.NoClassDefFoundError:
> 
> So in my case, the problem was that I used Java JDK 11 to program web API.
> But Android Studio uses 1.8, so I had to download JDK 1.8 and change the path of my JAVA_HOME now having to change always when I will use the other.
> In my case, it's working.
> 
> ![image](https://user-images.githubusercontent.com/9440831/77610189-c5f3e500-6f00-11ea-91cd-09e434c633c5.png)
> 
> ![flutter_java1 8](https://user-images.githubusercontent.com/9440831/77610209-d1471080-6f00-11ea-9915-5c669f7cf7af.png)

I had the same issue.  Had recently upgraded to JDK 11.  Changing JAVA_HOME to JDK8 fixed issue.  Workaround for now I guess.

**Comment by alexsodre1981** [comment]
desistala todos sdk do android studio, vai aparecer android_SDKTools(Obsolet). deu certo aqui pra mim dessa forma

**Comment by teekamsuthar** [comment]
> > Hello
> > I had the same problem that @JacquesWaltz
> > > Still having this problem: ✗ Android license status unknown.
> > > ### Log:
> > > 
> > > 1. Runned `flutter doctor`
> > > 
> > > `[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1) ✗ Android license status unknown. Try re-installing or updating your Android SDK Manager. See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.`
> > > 
> > > 1. Runned `flutter doctor --android-licenses`
> > > 
> > > `A newer version of the Android SDK is required. To update, run: /Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> > > 
> > > 1. Runned `/Users/x/Library/Android/sdk/tools/bin/sdkmanager --update`
> > > 
> > > `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 5 more`
> > > Cannot update SDKmanager. I've already tried re-installing all SDK tools (obsolete ones too) and via Android Studio.
> > > So, what should I do now?
> > 
> > 
> > ![flutter_java1_11](https://user-images.githubusercontent.com/9440831/77609886-fbe49980-6eff-11ea-9cd3-f999c8156def.png)
> > ![image](https://user-images.githubusercontent.com/9440831/77610054-639ae480-6f00-11ea-9226-d5336b3f641b.png)
> > That even downloading the path tools, don't work and the commander sdkmanager --update the error is `Exception in thread "main" java.lang.NoClassDefFoundError:
> > So in my case, the problem was that I used Java JDK 11 to program web API.
> > But Android Studio uses 1.8, so I had to download JDK 1.8 and change the path of my JAVA_HOME now having to change always when I will use the other.
> > In my case, it's working.
> > ![image](https://user-images.githubusercontent.com/9440831/77610189-c5f3e500-6f00-11ea-91cd-09e434c633c5.png)
> > ![flutter_java1 8](https://user-images.githubusercontent.com/9440831/77610209-d1471080-6f00-11ea-9915-5c669f7cf7af.png)
> 
> I had the same issue. Had recently upgraded to JDK 11. Changing JAVA_HOME to JDK8 fixed issue. Workaround for now I guess.

Thanks

**Comment by Biplovkumar** [comment]
> Yes, installing `Android SDK Tools (Obsolete) 26.1.1` worked for me.
> 
> After this I was able to do
> `flutter doctor --android-licenses` and select y.

thanks man.it helped.

**Comment by seqqueman** [comment]
The problems seems to be that in java 11 ( or 9 and 10 ) the jaxb libs are not included in the JDK and android studio sdkmanager can't read the licenses xml files. You have to include this libs on the classpath (if you are using Java 11), you can follow the instructions posted here (it worked for me in Windows 10)

https://medium.com/@parsher/flutter-android-sdkmanager-update-with-jdk-12-ad8098165472

The last step is not necessary. After included the classpath lines, run de flutter doctor and everything should be all right.

**Comment by SyedaSamia** [comment]
![Untitled](https://user-images.githubusercontent.com/22079190/83885458-340e2100-a768-11ea-90cf-f584c391045b.jpg)

**Comment by AtitMore** [comment]
Install Java8 work for me in this scenario. I tried to install `Android SDK Tools (Obsolete) 26.1.1` but was not working. In the end, I uninstall my new version of JDK and re-installed jdk8 into my system. And it worked.

But please don't just install the Jdk8 also set the environment variable in the system.

**Comment by viki2910** [comment]
i have same issue so i re-installed that obsolete sdk tools and it worked but it shows everyday to me again and again the same error..every time i am reinstalling sdk tools.. i am tired of this thing now please suggest solution

**Comment by youpage** [comment]
what a piece of shit, fking android.

**Comment by Mu7ammadRasul** [comment]
this helped me
>flutter channel master
>flutter config
p.s: i had all the issues up here and i solved all of them but when i checked out youtube that how android studio downloads so i got to this point that with these two line code all solved, once it failed re enter cmd and type >flutter doctor and wait for changes then your all doooone :)

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by youpage** [comment]
just make sure you use jdk8 for now, all other solutions are BS.

**Comment by Makemake037** [comment]
![20200726_163418.jpg](https://user-images.githubusercontent.com/66913764/88477475-e50d8c80-cf5d-11ea-894e-19a3976621f5.jpg)

**Comment by dymxin** [comment]
> this helped me
> 
> > flutter channel master
> > flutter config
> > p.s: i had all the issues up here and i solved all of them but when i checked out youtube that how android studio downloads so i got to this point that with these two line code all solved, once it failed re enter cmd and type >flutter doctor and wait for changes then your all doooone :)

This worked perfectly.

**Comment by xmonfort** [comment]
> I think I know the reason.
> ![image](https://user-images.githubusercontent.com/5219550/75605606-39cbe900-5b1f-11ea-8126-417c9b4fc8db.png)
> The android sdk tool has been renamed to android sdk command-line tools, which is located in
> ![image](https://user-images.githubusercontent.com/5219550/75605683-b8c12180-5b1f-11ea-9e2b-4ed57904e763.png)
> So flutter can't find the sdkmanager. But I don't know how to solve this problem.

Yes, I had the same problem, and installing sdk command tools is solved

**Comment by FRANCKWILFRIEDNGBO** [comment]
please guys i know this error is common but the solution can be different according to our PC,MAC and  the OS
i need someone who can help me to solve my problem of Android license status unknown 
![WhatsApp Image 2020-09-17 at 7 55 08 PM](https://user-images.githubusercontent.com/62740272/93596558-27d86780-f9d7-11ea-84d9-843098910ff5.jpeg)
![WhatsApp Image 2020-09-17 at 7 55 16 PM](https://user-images.githubusercontent.com/62740272/93596563-2ad35800-f9d7-11ea-90c1-87489bebdf55.jpeg)

**Comment by FRANCKWILFRIEDNGBO** [comment]
please guys i know this error is common but the solution can be different according to our PC,MAC and the OS
i need someone who can help me to solve my problem of Android license status unknown
i have tried a lot of combination like
*re installing my Android studio
*Uncheck obsolete package and check Andorid SDK tool 
*but i noticed that my sdkmanager.bat file is getting deleted alone so i had to uninstall all my antivirus 
but after all those things getting the same error
please i am lookimg forward to hear from you

**Comment by dassanjib** [comment]
I do exactly have the same issue what FRANCKWILFRIEDNGBO has explained above. 
I am using android-studio-ide-193.6626763-windows as IDE & flutter_windows_1.20.4-stable.
Already tried disabling antivirus & other solutions mentioned,  but no luck :(
Kindly help me, I am stuck.

**Comment by pmartinsons** [comment]
The solution for the problem describet [here](https://medium.com/@parsher/flutter-android-sdkmanager-update-with-jdk-12-ad8098165472) worked for me. 
In short: java versions more recent that 8 do not have javax tools. Install them, add to Android configurations and it works.

**Comment by dassanjib** [comment]
Thanks for your reply. I want through the steps given in that link. But in my windows system there is no sdkmanager file inside %LOCALAPPDATA%\Android\Sdk\tools\bin. It gets deleted automatically after installation.

**Comment by dassanjib** [comment]
My issue is fixed. Somehow I was not able to figure out this antivirus "segurazo" initially. After I uninstalled it things are working fine.

**Comment by ilhamatq** [comment]
![error](https://user-images.githubusercontent.com/39047721/96163685-66186680-0f44-11eb-9fbf-4151e5b4defe.PNG)
still did not solve my problem. i have installed android studio 4.1, JDK 15 and SDK 28, 29. How can I get rid of this?

**Comment by FRANCKWILFRIEDNGBO** [comment]
Hello friend even I spent more than 3 weeks trying to fix the issue .
This is what I have done to solve this problem.Actually the problem can be
caused by different things in your laptop.
1- your Antivirus delete the SDK manager instantly when it is downloaded so
to stop it uninstall your Antivirus if you have anyone for some period of
time to check if your problem is solved.then I can be also the your windows
defender if your are using a PC .
2- In Android studio you must go to settings>Android>then SDK tool>check
your Android SDK tool is downloaded >then if yes so unchecked the hide
obsolete case just down on right side >after you apply the changes and go
to  your CMD and run flutter doctor and check ,if it is coming like some
licenses   not accepted , you should manually accepted by just first
running flutter doctor --android-licenses and click Y to accept the
licenses .But in the other case if you still get an error .
3- try to see if you have your java >jdk 1.8 installed in your computer in
program file ,if not the case go to Oracle website and download jdk 1.8 and
installed in within a document that you can create called java which will
be in program files .
After having done this go the environment variables to enable the CMD to
locate the file so for that
Set JAVA_HOME and as location put the one of C:program files>java>jdk>...
Save go run and see
If you got correct fine but again if you get still errors at this stage you
need to reinstall your Operating system to use nicely Android studio and
all his facilities with no issues like I have done .

Thank you and never forgive
Regards FRANCK WILFRIED N'GBO

**Comment by iletai** [comment]
> I think I know the reason.
> ![image](https://user-images.githubusercontent.com/5219550/75605606-39cbe900-5b1f-11ea-8126-417c9b4fc8db.png)
> The android sdk tool has been renamed to android sdk command-line tools, which is located in
> ![image](https://user-images.githubusercontent.com/5219550/75605683-b8c12180-5b1f-11ea-9e2b-4ed57904e763.png)
> So flutter can't find the sdkmanager. But I don't know how to solve this problem.

Yes thank you, I try some solution but not resolved. 👯

**Comment by beyond-godlike** [comment]
> 
> 
> I think I know the reason.
> ![image](https://user-images.githubusercontent.com/5219550/75605606-39cbe900-5b1f-11ea-8126-417c9b4fc8db.png)
> The android sdk tool has been renamed to android sdk command-line tools, which is located in
> ![image](https://user-images.githubusercontent.com/5219550/75605683-b8c12180-5b1f-11ea-9e2b-4ed57904e763.png)
> So flutter can't find the sdkmanager. But I don't know how to solve this problem.

+1 SOLVED

**Comment by daniels042** [comment]
I updated my SDK and installed Android SDK Commandline-tools, Google Play Licensing Services and Google play Services. it worked

**Comment by ahmad-salman-pl** [comment]
I have applied all the given suggestions but nothing works. Finally I found out it was some windows problem which prevent the flutter.bat file to run. Looks stupid, but **here is what works for me**:

In windows Environment Variable I have added new variable with the name COMSPEC  and a value %SystemRoot%\system32\cmd.exe

By doing that the existing variable name (ComSpec) has changed to (COMSPEC) all in upper case. Then the problem resolved and the command (flutter doctor --android-licenses) works out.

**Comment by joyment2010** [comment]
hello,  **i have resolvered it**.
in different version of AS ide, the sdkManager ui may be different.
in the latest 4.0 AS, the tools options has been hiden.
But,
we could user command line "**./sdkmanager.bat tools**"
my sdkmanager is located in "sdk/cmdline-tools/latest/bin"

**Comment by PeterPaulez** [comment]
> Hy folks,
> 
> If you wont wana install obsolete packages, on Mac Os Catalina try this:
> 
> Go to your home folder in to Android default SDK folder:
> $ cd Library/Android/sdk
> 
> Create a link symbolic for the new folder for sdkmanager binary and others
> $ ln -s /Users/figueiredo/Library/Android/sdk/cmdline-tools/latest/ tools
> 
> Run flutter again
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-BR)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.43.2)
> [!] Connected device
> ! No devices available
> 
> ! Doctor found issues in 1 category.
> 
> Now the command 'flutter doctor' was able to found de command and solve the problem.

I could do it following next steps, it's working on my mac:

https://gist.github.com/PeterPaulez/42c1cd4d72243e0b9ea0efe5bd7bd68b

**Comment by exeptionerror** [comment]
[[Solved] Flutter.io Android License Status Unknown
](https://fluttercorner.com/flutter-io-android-license-status-unknown/)

**Comment by Coperbyte** [comment]
if the tools file has been updated, the folder will return the name cmdline-tools. this is what i experienced while updating to flutter 2.2.
so if you are lazy or don't install android studio, at least you have a backup of the old sdk folder then look for the tools folder and move the folder to the sdk directory.
if you have typed the command "fluter doctor" and "flutter doctor --android-license".
if there are other problems I don't know because this case worked with me.

![Screenshot (62)](https://user-images.githubusercontent.com/59157041/123735785-0abbb800-d8ca-11eb-9798-a0e000095ea9.png)

**Comment by Joebbit** [comment]
> The answer is [here](https://stackoverflow.com/questions/60460429/android-studio-installs-without-sdkmanager).
> 
> Uncheck `Hide Obsolete Packages` and you'll see `Android SDK Tools (Obsolete) 26.1.1`.
> 
> Hopefully this can be released in the next Flutter version?

Thank you so much, this really solved my problem!

**Comment by Yenniferh** [comment]
While trying to update Flutter from v1.8 to 2.2 I faced two problems when I was trying to exec `flutter doctor --android-licenses`:
1. The ` java.lang.NoClassDefFoundError`: I was using Java JDK 11 and I had to install Java JDK 8. That solved my problem.
2. The `could not find or load main class USER\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..` error: I uninstalled all the `Android SDK` related packages from Android Studio, as explained below. Then, I restarted Android Studio and reinstalled only the `Android SDK Build-Tool`. That package will install all that you need to run `flutter doctor --android-licenses`.

I hope this solution can help someone else.

![FIX-flutter](https://user-images.githubusercontent.com/19285706/126259028-22e0f41f-7f4a-4e93-b69d-1a50e3cc0e42.png)
