### ISSUE TITLE
On running default app, Flutter throws“ log reader stopped unexpectedly” after switching to Master

### ISSUE THREAD

**Issue by ajaytomgeorge** [flutter/flutter#52764]
```
PS D:\flutterApp\myapp> flutter run
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'... Done                       203.1s (!)
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         7.7s
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on Redmi Note 4.

```
Earlier it was **Error waiting for a debug connection: Bad state: No element,** I switched to **master** from **stable** and now it is throwing this error on run. App is getting installed andnot crashing but throwing this error. i tried Beta, it was **Bad state. No element issue again**. I tried flutter clean, flutter upgrade. . Nothing seems to work

**Comment by TahaTesser** [comment]
Hi @ajaytomgeorge 
please execute `flutter clean` in your project and make sure the device proper connected, cable is attached properly  and allow permission to launch on app Redmit Note 4, you should see dialog while launching the app.
Thank you

**Comment by ankitks2506** [comment]
@TahaTesser I have the same issue. The device is properly connected and cable is attached properly. The problem still persists after flutter clean also. 
Is it something to do with the adb?

**Comment by ajaytomgeorge** [comment]
Hi @TahaTesser . I have repeatedly switched branches Master-Stable-Beta and tried flutter clean many times. The app is getting installed and launching properly. But connection is getting lost by throwing this error. While Beta and Stable throws Bad state element issue, only Master throws this issue

**Comment by whitemay** [comment]
@TahaTesser . I'm not so sure it is the same issue. sure it seems might be.
My code works well on ios device. and also works on macos. the issue occue just when i active the NE related entitles on macos. and it work again if i remove these entitles.
i am pretty sure that this issue happens in latest 2 versions: 1.15.22/1.16.0. Before that, another error occured.

**Comment by joe733** [comment]
I'm on master channel (just updated). This Issue seen while building for Linux:
```dart
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.1, on Linux, locale en_GB.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
[FATAL:flutter/fml/icu_util.cc(97)] Check failed: context->IsValid(). Must be able to initialize the ICU context. Tried: /home/joe/Documents/Workspace/GitHub/TinkerHub/Training/Flutter/Day_001/Task_1/build/linux/debug/data/flutter_assets
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.

$ flutter clean
Deleting build...                                                   41ms
Deleting .dart_tool...                                               9ms
Deleting Generated.xcconfig...                                       2ms
Deleting flutter_export_environment.sh...                            1ms
Deleting ephemeral...                                               14ms

$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
[FATAL:flutter/fml/icu_util.cc(97)] Check failed: context->IsValid(). Must be able to initialize the ICU context. Tried: /home/joe/Documents/Workspace/GitHub/TinkerHub/Training/Flutter/Day_001/Task_1/build/linux/debug/data/flutter_assets
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
```

**Comment by zanderso** [comment]
The tool was updated to correctly report an issue with getting device logs from adb, and to fail right away instead of trying to continue a debug build when debugging won't be possible. I'm not sure we have the right trace messages currently in place to help debug this, but could you please post the results of running with the `-v` flag? Thanks!

**Comment by joe733** [comment]
It's pretty verbose, so I put it in the [pastebin](https://pastebin.com/0TWf3vXV).

**Comment by ankitks2506** [comment]
@zanderso @TahaTesser I faced a weird scenario, I had the same issue, while debugging the application on my mobile phone. It continued for a week and automatically while trying to debug after a week, the issue went away. It continued like that for another week and since yesterday the issue has popped up again. 
Its a really weird issue.

**Comment by joe733** [comment]
> **Update_**:
> Working on Flutter: v1.16.2-pre.46

@zanderso I'm not able to reproduce the issue, I'll post the log when I find the build fail like [this](https://github.com/flutter/flutter/issues/52764#issuecomment-602165589).

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by illiapoplawski** [comment]
I received this same error today as well.

[Pastebin](https://pastebin.com/haKdBTUR) of `flutter run -v`

flutter doctor --verbose
```[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.13.6 17G12034, locale en-CA)
    • Flutter version 1.17.0-3.2.pre at /Users/illiapoplawski/flutter
    • Framework revision 2a7bc389f2 (8 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/illiapoplawski/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • HD1905 • 192.168.2.58:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you

**Comment by rocaes** [comment]
Disconnect your phone, go to File: Invalidate Caches / Restart... and click on Invalidate and Restart, connect your phone and that should solve the problem

**Comment by joe733** [comment]
> Disconnect your phone, go to File: Invalidate Caches / Restart... and click on Invalidate and Restart, connect your phone and that should solve the problem

Is there any solution if it happens in VSCodium?

**Comment by Songeziwe** [comment]
Hello everyone, I'm also experiencing the same error. I did "flutter clean" but still having the same error. I just updated my flutter version yesterday and boom today it's giving me this problem.

Please find the error below:
Launching lib\main.dart on Hisense U962 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on Hisense U962.

The below output is for "flutter doctor -v":
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17134.1304], locale en-ZA)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Ntsikei\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.42.1)
    • VS Code at C:\Users\Ntsikei\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by jiaabid** [comment]
faced same issue but after flutter clean it is resolved

**Comment by dexterapps** [comment]
Hi. I was facing the same issue as well; the app would successfully launch but would lose the connection. I was able to fix this by updating my android SDK build tools and platform tools.

**Comment by Sansuihe** [comment]
- [ ]  I also encountered this problem on mac, but I have solved it。

Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on ONEPLUS A3010.

<img width="1009" alt="WeChat8521bed68fbccee875db7268f491f723" src="https://user-images.githubusercontent.com/48943865/83986929-16f86e80-a971-11ea-8310-54e698ea3a8d.png">

**Comment by Bronz0** [comment]
@TahaTesser 
Hello,
I got the same error while trying to run my app on a real device with android 10 (the app is running normally on an emulator), 
so here is the  whole stack trace

PS C:\Users\hp\Desktop\workspace\flutter\bloc_theming> flutter clean
PS C:\Users\hp\Desktop\workspace\flutter\bloc_theming> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [version 10.0.17763.1039], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.46.0)
[√] Connected device (1 available)

• No issues found!
PS C:\Users\hp\Desktop\workspace\flutter\bloc_theming> adb version
Android Debug Bridge version 1.0.41
Version 30.0.2-6538114
Installed as C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe
PS C:\Users\hp\Desktop\workspace\flutter\bloc_theming> flutter run -v
https://www.pastiebin.com/5ee34fd4c9fc9

**Comment by ngunjiri** [comment]
I have had the same problem for a whole week after upgrading to flutter 1.17....i did flutter clean and even downgraded to flutter 1.12 non of them worked...but when i upgraded my sdk tools(specifically flutter)the problem disappeared.

**Comment by zanderso** [comment]
@Bronz0 The log reader message is a red herring. The app stopped for some reason, which caused the log reader to stop. See:
```
[ +269 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.bronzo.bloc_theming/.MainActivity (has extras) }

                    Error type 3
                    Error: Activity class {com.bronzo.bloc_theming/com.bronzo.bloc_theming.MainActivity}
                    does not exist.
```
If you believe that this is an issue with Flutter and not with your app, please file a new issue.

@ngunjiri Please file a new issue with full details.
