### ISSUE TITLE
FSocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 52113

### ISSUE THREAD

**Issue by Flynn-X** [flutter/flutter#53338]
## Steps to Reproduce

1. dev channel v1.16.2 , run web Exception

## Logs

Launching lib\main.dart on Chrome in debug mode...
Building application for the web...
Finished with error: SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 52113

**Comment by VladyslavBondarenko** [comment]
Hi @Flynn-X 
can you please provide your `flutter doctor -v`?
did it happen only once or it repeats with different ports?

**Comment by Flynn-X** [comment]
> Hi @Flynn-X
> can you please provide your `flutter doctor -v`?
> did it happen only once or it repeats with different ports?

C:\Users\Administrator>flutter doctor -v
[âˆš] Flutter (Channel dev, v1.16.2, on Microsoft Windows [Version 6.1.7601
    locale zh-CN)
    â€¢ Flutter version 1.16.2 at D:\Android\flutter_windows_v1.16.2-dev\fl

    â€¢ Framework revision 58cad787d8 (4 days ago), 2020-03-23 08:33:41 -07
    â€¢ Engine revision 2d42c74a34
    â€¢ Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

[âˆš] Android toolchain - develop for Android devices (Android SDK version
2)
    â€¢ Android SDK at D:\Android\sdk
    â€¢ Android NDK location not configured (optional; useful for native pr
ng
      support)
    â€¢ Platform android-29, build-tools 29.0.2
    â€¢ ANDROID_HOME = D:\Android\sdk
    â€¢ Java binary at: D:\Android\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    â€¢ All Android licenses accepted.

[âˆš] Chrome - develop for the web
    â€¢ Chrome at
      C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome

[âˆš] Android Studio (version 3.5)
    â€¢ Android Studio at D:\Android\Android Studio
    â€¢ Flutter plugin version 44.0.1
    â€¢ Dart plugin version 191.8593
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    â€¢ IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2019.3
    X Flutter plugin not installed; this adds Flutter specific functionalit
    X Dart plugin not installed; this adds Dart specific functionality.
    â€¢ For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[âˆš] Connected device (2 available)
    â€¢ Chrome     â€¢ chrome     â€¢ web-javascript â€¢ Google Chrome 78.0
.108
    â€¢ Web Server â€¢ web-server â€¢ web-javascript â€¢ Flutter Tools

! Doctor found issues in 1 category.

**Comment by Flynn-X** [comment]
> Hi @Flynn-X
> can you please provide your `flutter doctor -v`?
> did it happen only once or it repeats with different ports?

Not only once and i it happend every time on my two computer， my computer system is windows 7  .

**Comment by hdjeong80** [comment]
i have same issue...

**Comment by stonega** [comment]
I have same issue too.
Flutter channel is beta, System is windows 10.
`PS E:\Flutter_Projects\stone_gate_web> flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale zh-CN)
    • Flutter version 1.15.17 at C:\src\flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\xijie\AppData\Local\Android\Sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\xijie\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\xijie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.162
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!`

**Comment by yjbanov** [comment]
@Flynn-X Could you please provide the exact command you ran? Please add the `-v` option to it and provide the log output.

**Comment by stonega** [comment]
Full log of mine
```[  +61 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +200 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[        ] executing: [C:\src\flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+2709 ms] Exit code 128 from: git fetch https://github.com/flutter/flutter.git --tags
[   +1 ms] fatal: unable to access 'https://github.com/flutter/flutter.git/': Failed to connect to 127.0.0.1 port 1090: Connection refused
[        ] executing: [C:\src\flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +184 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[  +12 ms] v1.15.17-0-g2294d75bfa
[  +15 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +175 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/beta
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +107 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +207 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +243 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +11 ms] beta
[ +142 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +86 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +47 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +84 ms] executing: C:\Users\xijie\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +79 ms] Exit code 0 from: C:\Users\xijie\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +25 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +72 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +736 ms] Generating E:\Flutter_Projects\stone_gate_web\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +263 ms] Launching lib\main.dart on Chrome in debug mode...
[ +157 ms] "flutter run" took 2,017ms.
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 2536

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:108:7)
<asynchronous suspension>
#2      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1502:12)
#9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#10     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#21     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#28     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#29     _rootRun (dart:async/zone.dart:1126:13)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by grouma** [comment]
I'm wondering if this would be resolved if you ran with administrative permissions?

**Comment by stonega** [comment]
> I'm wondering if this would be resolved if you ran with administrative permissions?

Nope, I tried, still same

**Comment by drean26** [comment]
I have same issue
flutter run -d chrome -v
[  +22 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +79 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d3ed9ec945f8869f0e136c357d0c2a6be2b60c98
[   +1 ms] executing: [C:\src\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +64 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.17.0-dev.3.1-0-gd3ed9ec94
[  +14 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +112 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +47 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: M:\sdk\platform-tools\adb.exe devices -l
[ +220 ms] List of devices attached
[  +36 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +111 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +278 ms] Generating M:\flutter\cms_flutter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +104 ms] Launching lib\main.dart on Chrome in debug mode...
[  +73 ms] "flutter run" took 1,029ms.
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 9013

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:221:7)
<asynchronous suspension>
#2      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:605:43)
#3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:426:44)
<asynchronous suspension>
#4      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart)
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZonedGuarded (dart:async/zone.dart:1608:12)
#10     runZoned (dart:async/zone.dart:1536:12)
#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#12     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:407:20)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:564:37)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _rootRunUnary (dart:async/zone.dart:1192:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#31     _rootRun (dart:async/zone.dart:1184:13)
#32     _CustomZone.run (dart:async/zone.dart:1077:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage `(dart:isolate-patch/isolate_patch.dart:169:5)```

**Comment by ZouZhuang** [comment]
I have two windows 10 computers, one has the same problem as you and the other can run web project normally. I found that the flutter package on the computer in question was upgraded by 'flutter channel beta & flutter upgrade' from 1.12.x stable to 1.17.0, the other computer is using the 1.17 zip package downloaded from flutter.dev. so i tried to remove the flutter document and unzip ‘flutter_windows_1.17.0-dev.3.1-beta.zip’ on the first computer, it works.

**Comment by stonega** [comment]
> I have two windows 10 computers, one has the same problem as you and the other can run web project normally. I found that the flutter package on the computer in question was upgraded by 'flutter channel beta & flutter upgrade' from 1.12.x stable to 1.17.0, the other computer is using the 1.17 zip package downloaded from flutter.dev. so i tried to remove the flutter document and unzip ‘flutter_windows_1.17.0-dev.3.1-beta.zip’ on the first computer, it works.

Appreciate your reply, but didn't work for me

**Comment by shenhuaxiyuan** [comment]
I have the same issue too. I just can't start the hello world.

**Comment by applemonkey496** [comment]
Same problem here, on Windows 10. I've followed all the instructions [here](https://flutter.dev/docs/get-started/test-drive?tab=terminal) but it doesn't seem to be working...

**Comment by grouma** [comment]
We've experienced similar problems with other Dart tools on Windows. The culprit was Kaspersky anti-virus. Could be related here?

See: https://github.com/dart-lang/sse/issues/16#issuecomment-613533268

**Comment by bassouma21001** [comment]
Same problem here, on Windows 10 :)

**Comment by bassouma21001** [comment]
> We've experienced similar problems with other Dart tools on Windows. The culprit was Kaspersky anti-virus. Could be related here?
> 
> See: [dart-lang/sse#16 (comment)](https://github.com/dart-lang/sse/issues/16#issuecomment-613533268) 
I do not think that problem .. I turned off the anti-virus, but the same problem I think it is in the release of Dart

**Comment by applemonkey496** [comment]
@grouma I have Sophos on my computer, could that be the problem in my case?

**Comment by maboumra** [comment]
No kaspersky related. I have it and the problem still occurs, even with protection deactivated.

**Comment by yjbanov** [comment]
@jonahwilliams is there a way we can detect whether the system allows localhost servers and produce a better warning message?

**Comment by jonahwilliams** [comment]
Perhaps we could do a doctor check?

**Comment by Jcdroid** [comment]
> 1.) on cmd run "ipconfig"
> 2.) after running the "ipconfig" get the value of IPv4 Address.
> 3.) then on the app run: flutter run -d chrome --web-port=8080 --web-hostname= the value of IPv4 Address

see also [this](https://stackoverflow.com/questions/60626062/reason-of-flutter-error-socketexception-failed-to-create-server-socket-os-err)

**Comment by stubborncoder** [comment]
Same problem here, windows 10, I switched from dev to beta channel it worked eventually. 

Then I shut down the server and stop debugging for a while, the next time I tried to debug the application again I got the message.

_Launching lib\main.dart on Web Server in debug mode...
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 56228
Exited (sigterm)_

Im not very experienced in flutter, but with the flutter run comand could you attach a debug session? I can run the app like that but I cannot debug it.

**Comment by abhishek-900** [comment]
I face the same issue . Anyone for help???????
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 57605

**Comment by brunoblsouza87** [comment]
> Tivemos problemas semelhantes com outras ferramentas Dart no Windows. O culpado foi o antivírus Kaspersky. Pode estar relacionado aqui?
> 
> Veja: [dart-lang / sse # 16 (comentário)](https://github.com/dart-lang/sse/issues/16#issuecomment-613533268)

It only worked for me by disabling Kaspersky

**Comment by ggalage** [comment]
> > 1.) on cmd run `ipconfig`
> > 2.) after running the `ipconfig` get the value of IPv4 Address.
> > 3.) then on the app run: `flutter run -d chrome --web-port=8080 --web-hostname=the value of IPv4 Address`
> 
> see also [this](https://stackoverflow.com/questions/60626062/reason-of-flutter-error-socketexception-failed-to-create-server-socket-os-err)

if you are using android studio, you can add those additional arguments under run -> Edit Configuration -> Run/Debug Configuration -> Additional arguments

**Comment by 123philip123** [comment]
@gglage Can you expand on what exactly we put in 'additional arguments' on android studio?

**Comment by ggalage** [comment]
> @gglage Can you expand on what exactly we put in 'additional arguments' on android studio?

--web-port=port number you want to use for e.g. 8080 --web-hostname=the value of your computer's IPv4 Address you got from ipconfig for e.g. 192.168.1.10

so in my case I would put the following,  --web-port=8080 --web-hostname=192.168.1.10

**Comment by fikrirazzaq** [comment]
This error is likely to happen when I use open public wifi. I use a VPN and the error doesn't occur anymore.

**Comment by yjbanov** [comment]
I changed the description of the issue. I think what we want to do here is quickly check that we are able to spawn a server on `localhost`, and if not produce a readable warning explaining what up and suggesting an alternative (e.g. use `127.0.0.1` instead of `localhost`).

**Comment by sweetlilmre** [comment]
On Windows 10 (specifically 20H2 in my case), IPV6 is now default so localhost resolves to ::1 not 127.0.0.1
Specifying 127.0.0.1 for --web-hostname works. The alternative is to make the change to the registry suggested in this Superuser post, which prioritises IPV4 over IPV6: https://superuser.com/questions/436574/ipv4-vs-ipv6-priority-in-windows-7/436944#436944
The **fix** would be to have the service understand an IPV6 address.

**Comment by KaneLeung** [comment]
In the Control Panel -> Network and Internet -> Network Connections -> Your Network Adapter -> Right Click ->Property -> Uncheck IPv6 and it will be working.
If your network adapter more than one, cancel IPv6 for all of them.

**Comment by sweetlilmre** [comment]
> In the Control Panel -> Network and Internet -> Network Connections -> Your Network Adapter -> Right Click ->Property -> Uncheck IPv6 and it will be working.
> If your network adapter more than one, cancel IPv6 for all of them.

Sure, that will work but is a fairly nuclear option. Ideally this is fixed to bind explicitly to IPv4 on the DNS look up or for the server to accept IPv6.

**Comment by Patrick386** [comment]
This issue is inconsistent and repeats itself.
It was working fine, but after the upgrade suddenly a problem occurred and it is not resolved.
Also, -d chrome --web-renderer canvaskit --web-port=8000 --web-hostname=192.168.0.46 << It worked, but there was a problem with Google login user authentication.

**Comment by cooler-king** [comment]
Is the `--web-hostname=127.0.0.1` workaround supposed to work for `flutter drive` as well as `flutter run`?

Because it is not for me and is preventing us from doing integration testing... and hence making a decision about whether we can migrate our app from Angular Dart to Flutter for the Web.

**Comment by cooler-king** [comment]
Is someone able to answer my question above?

**Comment by cooler-king** [comment]
Details of flutter drive failure on Windows host:
```INFO: [ +582 ms] "flutter drive" took 3,339ms.

SEVERE: [   +9 ms] Failed to bind web development server:
           SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 7222

SEVERE: [        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:212:7)
           <asynchronous suspension>
           #2      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:727:22)
           <asynchronous suspension>
           #3      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:285:25)
           <asynchronous suspension>
           #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
           <asynchronous suspension>```

**Comment by rho-cassiopeiae** [comment]
I used this command to check which ports are forbidden for my user:
```bash
netsh interface ipv4 show excludedportrange protocol=tcp
```
And then just picked a port that is not one of them. I think some freaking Windows update just randomly added port ranges to this list and broke my app. Thanks, Microsoft.
