### ISSUE TITLE
[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)

### ISSUE THREAD

**Issue by advancedngwarati** [flutter/flutter#53497]
When I leave the app open running on a real android device gets crushed.

Here is the crush captured.

```
E/GLConsumer(20462): [SurfaceTexture-0-20462-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
E/flutter (20462): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (20462):      at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (20462):      at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
E/flutter (20462): 
F/flutter (20462): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(129)] Check failed: CheckException(env). 
Lost connection to device.
```

Here is the output of doctor.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-ZW)
    • Flutter version 1.12.13+hotfix.8 at /Users/advancengwarati/Projects/flutter/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/advancengwarati/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/advancengwarati/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • SM G935F      • ce0117115d50e51505                   • android-arm64 • Android 8.0.0 (API 26)
    • iPhone 7 Plus • 9B6606A2-6493-4515-BC99-028F44191931 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @advancedngwarati 
Can you reproduce when running `flutter run --verbose` and provide the log?
and can you provide complete minimal code sample to reproduce it?

**Comment by advancedngwarati** [comment]
Sorry for the late reply, here is my app verbose
> flutter run --verbose

`
[  +51 ms] W/GLConsumer(24128): [SurfaceTexture-0-24128-0] bindTextureImage: clearing GL error: 0x505
[   +3 ms] D/InputMethodManager(24128): HSIFW - flag : 0 Pid : 24128
[ +140 ms] D/ViewRootImpl@400549c[MainActivity](24128): MSG_RESIZED: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
[  +28 ms] D/ViewRootImpl@400549c[MainActivity](24128): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 489691467776} changed=false
[  +17 ms] E/BufferQueueProducer(24128): [SurfaceTexture-0-24128-0] dequeueBuffer: attempting to exceed the max dequeued buffer count (1)
[   +7 ms] D/SurfaceView(24128): BG show() Surface(name=Background for - SurfaceView - Sys2037:com.example.app/com.example.app.MainActivity@26973b2@9)
com.google.maps.api.android.lib6.gmm6.api.au{26973b2 VFE...C.. ........ 0,0-1080,904}
[   +1 ms] D/SurfaceView(24128): surfaceDestroyed 1 com.google.maps.api.android.lib6.gmm6.api.au{26973b2 VFE...C.. ........ 0,0-1080,904}
[   +5 ms] E/BufferQueueProducer(24128): [SurfaceTexture-0-24128-0] dequeueBuffer: attempting to exceed the max dequeued buffer count (1)
[  +13 ms] E/BufferQueueProducer(24128): [SurfaceTexture-0-24128-0] dequeueBuffer: attempting to exceed the max dequeued buffer count (1)
[   +7 ms] D/SurfaceView(24128): BG destroy() Surface(name=Background for - SurfaceView - Sys2037:com.example.app/com.example.app.MainActivity@26973b2@9)
com.google.maps.api.android.lib6.gmm6.api.au{26973b2 VFE...C.. ........ 0,0-1080,904}
[  +21 ms] E/BufferQueueProducer(24128): [SurfaceTexture-0-24128-0] dequeueBuffer: attempting to exceed the max dequeued buffer count (1)
[  +57 ms] E/ion     (24128): ioctl c0084904 failed with code -1: Too many open files
[        ] E/gralloc (24128): invalid yuv format 1
[   +2 ms] E/GraphicBufferAllocator(24128): Failed to allocate (1080 x 1680) layerCount 1 format 1 usage 300: 3
[   +5 ms] E/BufferQueueProducer(24128): [SurfaceTexture-0-24128-0] dequeueBuffer: createGraphicBuffer failed
[        ] E/ion     (24128): ioctl c0084904 failed with code -1: Too many open files
[   +2 ms] E/gralloc (24128): invalid yuv format 1
[        ] E/GraphicBufferAllocator(24128): Failed to allocate (1080 x 1680) layerCount 1 format 1 usage 300: 3
[        ] E/BufferQueueProducer(24128): [SurfaceTexture-0-24128-0] dequeueBuffer: createGraphicBuffer failed
[  +77 ms] E/JavaBinder(24128): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 464)
[   +1 ms] E/ViewRootImpl@4c36340[MainActivity](24128): Failed mWindowSession.addToDisplay() mView = null
[  +11 ms] E/MethodChannel#flutter/platform_views(24128): Failed to handle method call
[        ] E/MethodChannel#flutter/platform_views(24128): java.lang.RuntimeException: Adding window failed
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.app.Dialog.show(Dialog.java:420)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.app.Presentation.show(Presentation.java:267)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:150)
[   +3 ms] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:180)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:129)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:66)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.os.MessageQueue.next(MessageQueue.java:325)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.os.Looper.loop(Looper.java:142)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
[        ] E/MethodChannel#flutter/platform_views(24128): Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.os.BinderProxy.transactNative(Native Method)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.os.BinderProxy.transact(Binder.java:763)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:841)
[        ] E/MethodChannel#flutter/platform_views(24128): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:918)
[        ] E/MethodChannel#flutter/platform_views(24128): 	... 18 more
[        ] E/Surface (24128): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
[        ] I/OpenGLRenderer(24128): Current Surface is null
[        ] F/OpenGLRenderer(24128): Failed to set damage region on surface 0x7227e41660, error=EGL_BAD_ACCESS
[  +62 ms] E/flutter (24128): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Adding window failed, null)
[        ] E/flutter (24128): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter (24128): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] E/flutter (24128): <asynchronous suspension>
[        ] E/flutter (24128): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:559:41)
[        ] E/flutter (24128): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
[        ] E/flutter (24128): #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
[        ] E/flutter (24128): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
[        ] E/flutter (24128): #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (24128): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter (24128): #8      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
[        ] E/flutter (24128): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] E/flutter (24128): #10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
[        ] E/flutter (24128): #11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] E/flutter (24128): #12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
[        ] E/flutter (24128): #13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
[        ] E/flutter (24128): #14     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
[        ] E/flutter (24128): #15     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] E/flutter (24128): #16     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
[        ] E/flutter (24128): #17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
[        ] E/flutter (24128): #18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
[        ] E/flutter (24128): #19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[        ] E/flutter (24128): #20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
[        ] E/flutter (24128): #21     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
[   +4 ms] E/flutter (24128): #22     _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (24128): #23     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (24128): #24     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter (24128): #25     _invoke (dart:ui/hooks.dart:259:10)
[        ] E/flutter (24128): #26     _drawFrame (dart:ui/hooks.dart:217:3)
[        ] E/flutter (24128): 
[   +9 ms] I/zygote64(24128): Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
[+2256 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.app/code_cache/appXKSHIX/app/)
[        ] Sending to VM service: _deleteDevFS({fsName: app})
[ +259 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +8 ms] "flutter run" took 783,977ms.`

**Comment by aviadavi** [comment]
Any solution to that? I'm getting it too.

**Comment by aviadavi** [comment]
I think crash is mentioned also in https://github.com/flutter/flutter/issues/26634

**Comment by noborder** [comment]
@VladyslavBondarenko  Any solution to that? I'm getting it too.

**Comment by chinmaygarde** [comment]
Based on the logs, this application seems to be using inline composition of external textures. While creating a new texture, the allocation fails because of too many open handles. The engine (maybe the texture is not collected when an OpenGL context is current) or the plugin could be leaking textures. cc @jason-simmons: Does that sound plausible?

Does this happen on all devices? Is there are reduced test case? What plugins are you using? Do those plugins use the Texture widget?

**Comment by atheist1** [comment]
I get the issue too. App crashed with log after i play a list of videos (may have lots of short time video) for a long time(about 9hours) .  
```
      I/ExoPlayerImpl( 1750): Release deeb4d0 [ExoPlayerLib/2.9.6] [mooncell_mid, mooncell_mid, rockchip, 25] [goog.exo.core]
E/GLConsumer( 1750): [SurfaceTexture-0-1750-4106] updateTexImage: GLConsumer is abandoned!
E/flutter ( 1750): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter ( 1750): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter ( 1750): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
E/flutter ( 1750):
F/flutter ( 1750): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(129)] Check failed: CheckException(env).
F/libc    ( 1750): Fatal signal 6 (SIGABRT), code -6 in tid 1769 (Thread-7)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/mooncell_mid/mooncell_mid:7.1.2/NHG47K/iflyin06161651:userdebug/test-keys'
Revision: '0'
ABI: 'arm64'
pid: 1750, tid: 1769, name: Thread-7  >>> cn.com.mooncell.mb.guardian <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(129)] Check failed: CheckException(env).
'
    x0   0000000000000000  x1   00000000000006e9  x2   0000000000000006  x3   0000000000000008
    x4   00000000000001eb  x5   0000008000000000  x6   00000078792ed000  x7   00000000012b9c60
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  0000000000000001  x13  0000000000000004  x14  00000000ffffffff  x15  00002fa97fa5c976
    x16  00000078781bbec8  x17  0000007878169af8  x18  0000000000000010  x19  00000078599f34f8
    x20  0000000000000006  x21  00000078599f3450  x22  000000000000003e  x23  0000000000000000
    x24  0000007850d7ae98  x25  0000000000000001  x26  000000000000002c  x27  0000000000000000
    x28  0000000000000001  x29  00000078599f15e0  x30  0000007878166f24
    sp   00000078599f15c0  pc   0000007878169b00  pstate 0000000060000000
backtrace:
    #00 pc 000000000006bb00  /system/lib64/libc.so (tgkill+8)
    #01 pc 0000000000068f20  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023f18  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c7d0  /system/lib64/libc.so (abort+52)
    #04 pc 0000000001235b50  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #05 pc 0000000001227490  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #06 pc 0000000001220e58  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #07 pc 0000000001220c88  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #08 pc 000000000122eed4  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #09 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #10 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #11 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #12 pc 000000000122c0dc  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #13 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #14 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #15 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #16 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #17 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #18 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #19 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #20 pc 000000000122c0dc  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #21 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #22 pc 000000000122e19c  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #23 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #24 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #25 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #26 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #27 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #28 pc 000000000122f188  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #29 pc 000000000122c6c8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #30 pc 000000000122cfc8  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #31 pc 000000000122a9b0  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #32 pc 0000000001269e34  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #33 pc 0000000001236454  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #34 pc 000000000123b338  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #35 pc 0000000000018308  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+916)
    #36 pc 0000000000017eb4  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
    #37 pc 0000000000011044  /system/lib64/libandroid.so (ALooper_pollOnce+100)
    #38 pc 000000000123b2bc  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #39 pc 00000000012363b4  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #40 pc 00000000012391f4  /data/app/cn.com.mooncell.mb.guardian-1/lib/arm64/libflutter.so (offset 0x1220000)
    #41 pc 0000000000068708  /system/lib64/libc.so (_ZL15__pthread_startPv+208)
    #42 pc 000000000001da3c  /system/lib64/libc.so (__start_thread+16)
Lost connection to device.
```
I just use one single VideoPlayer Widget with two controller for smooth transition between two video

```dart
Future<void> attachListenerAndInit(VideoPlayerController controller) async {
    if (!controller.hasListeners) {
      controller.addListener(() async {
        int dur = controller.value?.duration?.inMilliseconds ?? 0;
        int pos = controller.value?.position?.inMilliseconds;
        if (controller.value.hasError) {
          _videoOnErr();
          return;
        }
        int preparedTime = dur < 500 ? dur : 500;
        if (dur - pos <= preparedTime) {
          await nextVideo();
        }
      });
    }
    await controller.initialize().then((_) {
    });
    return;
  }
Future<void> nextVideo() async {
    File file;
    if (_changeLock) {
      return;
    }
    _changeLock = true;
   // all video was played
    if (index > widget.sourceList.length || _controllers.length == 1) {
      _changeLock = false;
      _controllers?.forEach((item) {
        item?.dispose().then((_) {
          _controllers.remove(item);
        });
      });
      return;
    }

    if (index != widget.sourceList.length) {
      file = new File(widget.sourceList[index].res);
      if (file != null && file.existsSync()) {
        _controllers.add(VideoPlayerController.file(file));
      } 
      await attachListenerAndInit(_controllers.last);
    }
   // dispose prev controller
    setState(() {
      _controllers.first?.pause();
      _controllers.first?.dispose();
      _controllers.removeAt(0);
    });
    index++;
    await _controllers.first.play();

    setState(() {
      _changeLock = false;
    });
  }
@override
  Widget build(BuildContext context) {
    // TODO: implement build
    return isErr
        ? Container(
            child: Text(errMsg),
          )
        :Container(
                    child: AspectRatio(
                    aspectRatio: _controllers.first.value.aspectRatio,
                    child: VideoPlayer(
                      _controllers.first,
                    ),
                  ))

  }
```

run flutter doctor ----
```
[✓] Flutter (Channel unknown, v1.14.0, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
    • Flutter version 1.14.0 at /Users/qitianle/Desktop/flutter
    • Framework revision bc6f270c58 (6 months ago), 2020-01-14 13:23:03 -0800
    • Engine revision fd269f60bf
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/qitianle/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/qitianle/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (1 available)
    • ASK AL00x • BGR6R20403000901 • android-arm64 • Android 9 (API 28)
```
The videoPlayer version is `video_player: ^0.10.11+1`

**Comment by Katekko** [comment]
I'm getting this error on emulator as well.

**Comment by patrick-fu** [comment]
🤣 I also encountered a similar crash and found that this issue is caused by `SurfaceTexture`'s thread safe problem, which has been fixed in this PR: [https://github.com/flutter/engine/pull/21777](https://github.com/flutter/engine/pull/21777) 🎉

Try to use version `1.24-candidate.2` or above (currently in the `beta` branch) to verify whether this crash is resolved.🕺

**Comment by tudorcodarnai** [comment]
Still having issues with this on **Android**. Flutter doctor attached bellow, I am on **Beta channel version 1.25.0-8.2.pre**. Clean build and everything nice... but still crashing from time to time.

I am **NOT** using ```WV.WebView.platform = WV.SurfaceAndroidWebView();``` because I don't have inputs/keyboard use and I see a major lag on scrolling when I use it. 

My **WebView** is **wrapped by a SingleChildScrollView** and I'm using js to get final height.

My WebView displays text, images, and iframes from social media (FB, YT, IG, Twitter).

```
E/flutter (20518): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(48)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (20518):      at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (20518):      at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
E/flutter (20518):      at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage()
E/flutter (20518): 
F/flutter (20518): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1196)] Check failed: CheckException(env). 
```

[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.2.pre at /usr/local/flutter
    • Framework revision b0a2299859 (8 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM G920F (mobile) • 041604a587d62d02 • android-arm64 • Android 7.0 (API 24)

**Comment by patrick-fu** [comment]
Are you building a release version? That may be caused by code confusion, please refer to [FAQ-4](https://github.com/zegoim/zego-express-flutter-sdk#4-android-building-release-crashes-with-noclassdeffounderror-when-flutter-is-upgraded-to-v110-or-above)

**Comment by tudorcodarnai** [comment]
Thanks for the response @patrick-fu. 

I am was building both for release and dev because there is another issue with iOS physical devices... that's another story (Flutter is getting annoying...) 

Found out it's because of the height of the container, as I am resizing based on JS channel post. It's crashing whenever I set the height >2048. This is so frustrating.

It is not due to the images, as I thought before.
