### ISSUE TITLE
I am having a problem in running all my apps in flutter

### ISSUE THREAD

**Issue by VineetMaker** [flutter/flutter#54198]
A day before when i ran my app on android studio then i got below error before that all my apps were running good :
**Attached below: 
1) ERROR output
2) Flutter doctor output
3) Method I tried to overcome this issue  (but none of them worked)
4) app>build.gradle code
5) Added flutter run --verbose error

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
     Required by:
         project :app
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11
e25047523c4e0c7e1f5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047
523c4e0c7e1f5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e
0c7e1f5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f
5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0
c7e1f5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5
d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0
c7e1f5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5
d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0
c7e1f5d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5
d408/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e2504752
3c4e0c7e1f5d408/arm64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c
7e1f5d408/arm64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d
408/arm64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/ar
m64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d4
08/arm64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm
64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d4
08/arm64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm
64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d4
08/arm64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm
64_v8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
   > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c
7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d
408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x8
6_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debu
g-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86
_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug
-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86
_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug
-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86
_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug
-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
   > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4
e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1
f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_6
4_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/
x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64
_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/
x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64
_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/
x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64
_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
 full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 22s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       684.0s (!)
Gradle task assembleDebug failed with exit code 1
```

```console
C:\Users\asus\AndroidStudioProjects\delete_me>gradle --version
'gradle' is not recognized as an internal or external command,
operable program or batch file.
```

My flutter doctor output:
```console
C:\Users\asus>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] VS Code (version 1.42.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

Things i tried to overcome this issue:
1. Deleted .packages file and run flutter pub get
2. No plugins
3. In project structure > module>Android SDK 29 & 28 tried with both
4.  In project structure > project> (then set project sdk to)Android API 29 platform
5. channel in use: stable (already tried beta channel)
6. Used commands like flutter clean , flutter upgrade .
7. Found some red lines in project > app > build.gradle and after some search on stackoverflow
    tried 1) Removing new before GradleException(........)
             2) Tried replacing GradleException with FileNotFoundException.

build.gradle Code:

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.vinp.delete"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
```

 flutter run --verbose error output:

```bash
C:\Users\asus\AndroidStudioProjects\delete_me>flutter run --verbose
[  +57 ms] executing: [C:\src\flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [C:\src\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +79 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +15 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter\] git ls-remote --get-url origin
[  +73 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +168 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[ +105 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +320 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +92 ms] Exit code 0 from: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           f93d0e84               device product:1951 model:vivo_1951 device:1951 transport_id:2
[  +34 ms] C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s f93d0e84 shell getprop
[ +484 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +473 ms] Generating
C:\Users\asus\AndroidStudioProjects\delete_me\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +71 ms] ro.hardware = qcom
[ +169 ms] Launching lib\main.dart on vivo 1951 in debug mode...
[  +41 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s f93d0e84 shell -x logcat -v time -t 1
[ +487 ms] Exit code 0 from: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s f93d0e84 shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           04-07 23:34:05.488 E/ThermalEngine(  932): vivo_thermal_parameter_config :VivoThermal:read type:1  buf: 1
           04-07 23:34:05.488 E/ThermalEngine(  932):
[  +16 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +6 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s f93d0e84 logcat -v time -T 04-07 23:34:05.488
[ +379 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +316 ms] Building APK
[  +55 ms] Running Gradle task 'assembleDebug'...
[  +12 ms] gradle.properties already sets `android.enableR8`
[  +22 ms] Using gradle from C:\Users\asus\AndroidStudioProjects\delete_me\android\gradlew.bat.
[  +56 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +505 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +12 ms] executing: [C:\Users\asus\AndroidStudioProjects\delete_me\android\]
C:\Users\asus\AndroidStudioProjects\delete_me\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\asus\AndroidStudioProjects\delete_me\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+4564 ms] Starting a Gradle Daemon, 4 busy and 1 stopped Daemons could not be reused, use --status for details
[+690172 ms] FAILURE: Build failed with an exception.
[  +48 ms] * What went wrong:
[   +2 ms] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[   +2 ms] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[   +3 ms]    > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +2 ms]      Required by:
[   +1 ms]          project :app
[   +1 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +3 ms]          > Could not get resource
'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/flutter_em
bedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +8 ms]             > Could not GET
'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/flutter_em
bedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +11 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +3 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/flutter_embedding_debu
g-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +15 ms]             > Could not GET
'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/flutter_embedding_debu
g-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +2 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +2 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +9 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +11 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +4 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +5 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408
/flutter_embedding_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +4 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[  +11 ms]    > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +4 ms]      Required by:
[   +1 ms]          project :app
[   +9 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v8a_debug-1.
0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +10 ms]             > Could not GET
'https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v8a_debug-1.
0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +9 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v8a_debug-1.0.0-af51afce
b8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +17 ms]             > Could not GET
'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v8a_debug-1.0.0-af51afce
b8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +11 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[  +20 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[  +15 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v
8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +22 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v
8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[ +107 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[  +89 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[  +11 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v
8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[ +179 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v
8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[ +117 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[ +132 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[  +20 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v
8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +10 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/arm64_v
8a_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +19 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[  +12 ms]    > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[  +14 ms]      Required by:
[   +6 ms]          project :app
[   +5 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[  +13 ms]          > Could not get resource
'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afce
b8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +50 ms]             > Could not GET
'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afce
b8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +5 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25
047523c4e0c7e1f5d408.pom'.
[   +3 ms]             > Could not GET
'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25
047523c4e0c7e1f5d408.pom'.
[  +15 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +4 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +2 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0
.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +4 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0
.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +4 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0
.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +11 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0
.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +3 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0
.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +5 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0
.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +8 ms]    > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[  +12 ms]      Required by:
[   +4 ms]          project :app
[   +4 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +2 ms]          > Could not get resource
'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af
51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +7 ms]             > Could not GET
'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af
51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886c
c11e25047523c4e0c7e1f5d408.pom'.
[   +2 ms]             > Could not GET
'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886c
c11e25047523c4e0c7e1f5d408.pom'.
[   +5 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +2 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_deb
ug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +4 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_deb
ug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[  +12 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_deb
ug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +3 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_deb
ug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +2 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_deb
ug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +5 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_deb
ug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.pom'.
[   +4 ms]                > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
[   +5 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 11m 34s
[ +638 ms] Running Gradle task 'assembleDebug'... (completed in 697.2s, longer than expected)
[  +28 ms] "flutter run" took 7,00,434ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by Kav47** [comment]
[https://github.com/flutter/flutter/issues/38751](Similar to this?) [https://github.com/flutter/flutter/issues/41553]( or this?) 

Have you tried running on different internet connection? I see lots of 
`Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect`
could be issue with your emulator, try restarting your emulator.

**Comment by VineetMaker** [comment]
@Kav47  Yeah i tried it on diffferent connection and even after proxy off and also both on my connected device and on emulator but its not working.
One more thing I went to File > Project structure > Project & Module & SDK (for all three categories in project structure) i set all three of them to API 29 is it right please check and tell.

**Comment by iapicca** [comment]
Hi @VineetMaker 
give this [PR](https://github.com/flutter/flutter/pull/52042)
could you please try running your project with the latest `dev channel`?
It's possible that the issue has been fixed
Thank you

https://github.com/flutter/flutter/issues/41553

**Comment by VineetMaker** [comment]
@iapicca 
@Kav47 
I tried it on dev channel but the issue remains the same.
After some change in build.gradle file my issue is reduced to :

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.6.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.6.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.6.2/gradle-3.6.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.6.2/gradle-3.6.2.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve com.android.tools.build:gradle:3.6.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.6.2/gradle-3.6.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.6.2/gradle-3.6.2.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
   > Could not resolve org.apache.httpcomponents:httpclient:4.5.3.
     Required by:
         project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > de.undercouch:gradle-download-task:3.4.3
      > Could not resolve org.apache.httpcomponents:httpclient:4.5.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect
      > Could not resolve org.apache.httpcomponents:httpclient:4.5.3.
         > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.pom'.
               > Connect to 10.10.10.2:8080 [/10.10.10.2] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 30s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by liudonghua123** [comment]
I just change `MAVEN_REPO` in `<flutter_home>/packages/flutter_tools/gradle/flutter.gradle` from `https://storage.googleapis.com/download.flutter.io` to `https://download.flutter.io`. Then run `flutter run`, after download `x86_debug:1.0.0-xxx`, I reset the changes in order to upgrade next time.

Not it is `https://download.flutter.io`, not `http://download.flutter.io`.

I changed the above configurations because I can not visit `https://storage.googleapis.com`.

**Comment by DamonChen117** [comment]
I had the same issue after upgrading flutter to v1.12.13+hotfix.9
Then I reverted back by command: flutter version v1.12.13+hotfix.8 , every is good again.

**Comment by VineetMaker** [comment]
So the issue is fixed either you can downgrade your flutter or if it also does not work then try reinstalling everything from scratch it will surely solve the problem.
Thank you everyone.

**Comment by longdw** [comment]
> I had the same issue after upgrading flutter to v1.12.13+hotfix.9
> Then I reverted back by command: flutter version v1.12.13+hotfix.8 , every is good again.

downgrade to v1.12.13+hotfix.8, solved my problem. thank you very much!

**Comment by liudonghua123** [comment]
See more discussion on https://github.com/flutter/flutter/issues/55134. tl;dr, update your flutter to the latest version.

**Comment by AmbujaAK** [comment]
I am getting the same issue after upgrading to Flutter 2.2.1.
I tried this solution #41553
But no luck.

any more solution ?
