### ISSUE TITLE
Flutter should continue making frames in iOS app switcher

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5449]
We presumably get some sort of lifecycle event from iOS when we get moved out of foreground and into the app-switcher.

At that time we stop making frames.  If we're in the middle of scrolling, we'll jump to the current/new scroll position when the app is brought forward again.  This is wrong.  Try scrolling the Settings app on iOS (or any app) and then double-tap the home button to bring up the app switcher.  The app will keep scrolling (as well as video will keep playing, etc).

Flutter doesn't keep scrolling in this mode, but should.   We just need slightly better lifecycle handling.

This is a small nit, but worth tracking.  FYI @chinmaygarde

**Comment by chinmaygarde** [comment]
The correct `AppLifecycleState` updates are sent to the framework from the platform layer already https://github.com/flutter/engine/blob/master/sky/shell/platform/ios/framework/Source/FlutterViewController.mm#L252.

**Comment by Hixie** [comment]
What controls whether we generate frames or not here is whether we're getting onBeginFrame callbacks. This ties in closely with the vsync work you were just doing.

**Comment by abarth** [comment]
The throttling here might well be in the C++ code.  We watch lifecycle events a pause the animator in various situations.  These might not be quite right for iOS.

**Comment by chinmaygarde** [comment]
There are two issues here:
* When the app switcher is engaged, the application resigns from the active status. At this point, the framework stops making requests for fresh frames.
* Even if the framework were to make requests for fresh frames, the VSync provider on iOS will refuse to engage because it too has detected that the application is no longer active.

All platforms now have fallback providers. So we can depend on that for the second case. I just need to reset the vsync providers on suspend and resume. @Hixie, is my first observation accurate?

**Comment by eseidelGoogle** [comment]
Curious how iOS keeps other apps scrolling when in the background, or playing video and why our app is different?  Would other OpenGL surface-based apps stop like ours does?

**Comment by chinmaygarde** [comment]
We can still use regular timer based fallbacks when not active.

**Comment by eseidelGoogle** [comment]
OK.  I wouldn't worry, current behavior is OK and we've not had anyone complain about this.

**Comment by Hixie** [comment]
@xster says this is fixed!

**Comment by xster** [comment]
Done in #11421

**Comment by gabdsg** [comment]
There is any fix for this? I still have this problem

**Comment by adeolaex** [comment]
@xster This still persists in current versions of Flutter. Was the fix scraped out ?
