### ISSUE TITLE
`flutter test` fills tmpfs and fails with: (OS Error: No space left on device, errno = 28)

### ISSUE THREAD

**Issue by nioncode** [flutter/flutter#55168]
After developing for some time and running tests regularly, `flutter test` will eventually fail with:
```
flutter test
00:01 +0 -1: loading /home/nion/app/test/AuthenticationService_test.dart [E]                            
  FileSystemException: Cannot copy file to '/run/user/1000/flutter_test_listener.SYBRHD/listener.dart.dill', path = '/run/user/1000/flutter_test_compiler.AWQONU/output.dill' (OS Error: No space left on device, errno = 28)
  dart:io/file_impl.dart 338:9                                  _File.copy.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134:38                                  _rootRunUnary
  dart:async/zone.dart 1031:19                                  _CustomZone.runUnary
  dart:async/future_impl.dart 139:18                            _FutureListener.handleValue
  dart:async/future_impl.dart 680:45                            Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 709:32                            Future._propagateToListeners
  dart:async/future_impl.dart 524:5                             Future._completeWithValue
  dart:async/future_impl.dart 554:7                             Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 175:5                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 275:23                            Future.then
  dart:io/file_impl.dart 336:57                                 _File.copy
  package:file/src/forwarding/forwarding_file.dart 27:66        ForwardingFile.copy
  package:flutter_tools/src/test/test_compiler.dart 157:56      TestCompiler._onCompilationRequest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/test_compiler.dart             TestCompiler._onCompilationRequest
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134:38                                  _rootRunUnary
  dart:async/zone.dart 1031:19                                  _CustomZone.runUnary
  dart:async/zone.dart 933:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 338:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 593:14                            _DelayedData.perform
  dart:async/stream_impl.dart 709:11                            _StreamImplEvents.handleNext
  dart:async/stream_impl.dart 669:7                             _PendingEvents.schedule.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 393:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 141:21                            _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 114:10                            new _BufferingStreamSubscription
  dart:async/stream_controller.dart 840:9                       new _ControllerSubscription
  dart:async/stream_controller.dart 672:51                      _StreamController._subscribe
  dart:async/stream_controller.dart 820:19                      _ControllerStream._createSubscription
  dart:async/stream_impl.dart 474:9                             _StreamImpl.listen
  package:flutter_tools/src/test/test_compiler.dart 54:31       new TestCompiler
  package:flutter_tools/src/test/flutter_platform.dart 459:22   FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart          FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 368:36   FlutterPlatform.loadChannel
  package:flutter_tools/src/test/flutter_platform.dart 321:46   FlutterPlatform.load
  package:test_core/src/runner/loader.dart 224:36               Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
  package:test_core/src/runner/loader.dart                      Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 98:31            new LoadSuite.<fn>.<fn>
  package:test_api/src/utils.dart 241:5                         invoke
  package:test_core/src/runner/load_suite.dart 97:7             new LoadSuite.<fn>
  package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                   new Timer
  dart:async/timer.dart 91:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 144:7               Invoker.guard
  package:test_api/src/backend/invoker.dart 428:15              Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
  dart:async/future.dart 202:37                                 new Future.microtask.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 175:5                   _RawReceivePortImpl._handleMessage
```

Tests in other test files (that should also be run as part of `flutter test`) simply take forever to load and seem to never timeout and I have to abort the tests manually.
This issues persist until I go into `/run/user/1000` and remove all `flutter_*` folders, each being roughly 30mb big (my `/run/user/1000` tmpfs is 1.6G big which gets regularly filled up by the `flutter_*`  folders):
```
--- /run/user/1000 --------------------------------------------------------------------------------------
   29.7 MiB [##########] /flutter_test_listener.XCCOIR
   29.7 MiB [##########] /flutter_test_listener.CTVXFD
   29.7 MiB [##########] /flutter_test_listener.QCBHYO
   29.7 MiB [##########] /flutter_test_listener.YMKBQX
   29.7 MiB [##########] /flutter_test_listener.CKULEK
   29.7 MiB [######### ] /flutter_test_compiler.MWGKUL
   29.7 MiB [######### ] /flutter_test_compiler.KTBNBO
   29.7 MiB [######### ] /flutter_test_compiler.GDMGUG
   29.7 MiB [######### ] /flutter_test_compiler.ICDFSA
   29.7 MiB [######### ] /flutter_test_compiler.WWPTMM
   29.7 MiB [######### ] /flutter_test_listener.WMWUWC
   29.7 MiB [######### ] /flutter_test_listener.MQGSTX
   29.7 MiB [######### ] /flutter_test_listener.MMQYMK
   29.7 MiB [######### ] /flutter_test_compiler.PVUKKD
   29.7 MiB [######### ] /flutter_test_listener.MBTQSW
   29.7 MiB [######### ] /flutter_test_listener.XXOVBN
   29.7 MiB [######### ] /flutter_test_listener.DVKTNI
   29.7 MiB [######### ] /flutter_test_compiler.XWFCBA
   29.7 MiB [######### ] /flutter_test_compiler.NUXDRO
   29.7 MiB [######### ] /flutter_test_compiler.SYTFAA
   29.2 MiB [######### ] /flutter_test_listener.CVBVQU
   29.2 MiB [######### ] /flutter_test_listener.EQKLNR
   29.2 MiB [######### ] /flutter_test_listener.NZXUNW
   29.2 MiB [######### ] /flutter_test_listener.NOCCDZ
   29.2 MiB [######### ] /flutter_test_listener.TGCJUF
   29.2 MiB [######### ] /flutter_test_listener.FJDMCF
   29.2 MiB [######### ] /flutter_test_listener.FMDYEV
   29.2 MiB [######### ] /flutter_test_listener.QWOBMK
   29.2 MiB [######### ] /flutter_test_listener.FNAEJD
   29.2 MiB [######### ] /flutter_test_listener.NYVLFJ
   29.2 MiB [######### ] /flutter_test_listener.IOISXB
   29.2 MiB [######### ] /flutter_test_listener.NOLBMZ
   29.2 MiB [######### ] /flutter_test_listener.NJYGQQ
   29.2 MiB [######### ] /flutter_test_listener.JRLFOO
   29.2 MiB [######### ] /flutter_test_compiler.HRLUJQ
   29.2 MiB [######### ] /flutter_test_compiler.XHTQSU
   29.2 MiB [######### ] /flutter_test_compiler.EUIHIE
   29.2 MiB [######### ] /flutter_test_compiler.FMRWVA
   29.2 MiB [######### ] /flutter_test_compiler.EYGDFA
   29.2 MiB [######### ] /flutter_test_compiler.FAUSGC
   29.2 MiB [######### ] /flutter_test_compiler.LXGSJF
   29.2 MiB [######### ] /flutter_test_compiler.REZYVZ
   29.2 MiB [######### ] /flutter_test_compiler.DWVOAO
   29.2 MiB [######### ] /flutter_test_compiler.ONQVWH
   29.2 MiB [######### ] /flutter_test_compiler.YXEYOF
   29.2 MiB [######### ] /flutter_test_compiler.PDKVGU
   29.2 MiB [######### ] /flutter_test_compiler.GSENCF
   29.2 MiB [######### ] /flutter_test_compiler.SXRVMN
   25.1 MiB [########  ] /flutter_tool.NQKBLU         
   25.1 MiB [########  ] /flutter_tool.LFMOOO
   23.8 MiB [########  ] /flutter_test_compiler.PWDCXU
```

`/run/user/1000` is `XDG_RUNTIME_DIR`, which the flutter tools probably uses to store temporary files. It seems like (sometimes?) those are not removed when the test ends and thus they will eventually fill up all available space in the tmpfs.

flutter doctor -v:
```
[  +28 ms] executing: [/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git describe --match
v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +4 ms] executing: [/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git rev-parse
--abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +29 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +21 ms] executing: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[  +50 ms] Exit code 0 from: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
-version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[  +16 ms] executing: [/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git ls-remote
--get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +15 ms] executing: [/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git -c
log.showSignature=false log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 10 weeks ago
[  +13 ms] executing: /home/nion/.cache/flutter/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[  +20 ms] Exit code 255 from: /home/nion/.cache/flutter/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[        ] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>             

           Common options:                                                             
           --help                                                                      
             Display this message (add --verbose for information about all VM options).
           --version                                                                   
             Print the VM version.                                                     

           To create a core snapshot:                                                  
           --snapshot_kind=core                                                        
           --vm_snapshot_data=<output-file>                                            
           --isolate_snapshot_data=<output-file>                                       
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as assembly suitable for compilation  
           as a static or dynamic library:                                             
           --snapshot_kind=app-aot-assembly                                            
           --assembly=<output-file>                                                    
           [--obfuscate]                                                               
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as an ELF shared library:             
           --snapshot_kind=app-aot-elf                                                 
           --elf=<output-file>                                                         
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           AOT snapshots can be obfuscated: that is all identifiers will be renamed    
           during compilation. This mode is enabled with --obfuscate flag. Mapping     
           between original and obfuscated names can be serialized as a JSON array     
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524       
           for implementation details and limitations of the obfuscation pass.
[  +19 ms] executing: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[  +44 ms] Exit code 0 from: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
-version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +2 ms] java -version
⣽[  +89 ms] executing: /home/nion/opt/android-sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /home/nion/opt/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached                                                                                               [   +4 ms] [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[   +1 ms]     • Flutter version 1.12.13+hotfix.8 at
/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped
[        ]     • Framework revision 0b8abb4724 (10 weeks ago), 2020-02-11 11:44:36 -0800
[        ]     • Engine revision e1e6ced81d
[        ]     • Dart version 2.7.0
⣽[  +10 ms] executing: /home/nion/opt/android-sdk/platform-tools/adb devices -l
[  +40 ms] List of devices attached
[  +26 ms] executing: /home/nion/opt/android-sdk/tools/bin/sdkmanager --licenses                                                   
[+2957 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[        ]     • Android SDK at /home/nion/opt/android-sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-29, build-tools 29.0.3
[        ]     • ANDROID_HOME = /home/nion/opt/android-sdk
[        ]     • Java binary at: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[        ]     • All Android licenses accepted.
[        ] [✓] Android Studio (version 3.6)
[        ]     • Android Studio at /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped
[        ]     • Flutter plugin version 45.0.1
[        ]     • Dart plugin version 192.7761
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[        ] [!] Connected device
[        ]     ! No devices available
[        ] ! Doctor found issues in 1 category.
[   +7 ms] "flutter doctor" took 3,470ms.
```

**Comment by TahaTesser** [comment]
Hi @nioncode 
can you please provide your `flutter doctor -v``?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by nioncode** [comment]
My `flutter doctor -v` output is already in the initial post.

I tried to reproduce the problem and was successful.

1. Create a simple test file with the following content. Note the use of a `testWidgets` in combination with `await`ing a Future. Since flutter test using a fake async zone, this test case will never complete.
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('timeout', (tester) async {
    await Future.delayed(Duration.zero);
  });
}
```

2. Run the test case in Android Studio.
3. After the test has successfully started, stop the test case in Android Studio.
4. Re-run the test case in Android Studio. Android Studio will pop up a dialog asking to stop and re-run the test, since it is already running. Confirm this.

For each restart of the test, a new tuple of `flutter_test_compiler_*`, `flutter_test_listener_*`, `flutter_test_fonts_*` directories gets created in `$XDG_RUNTIME_DIR`. Repeating these steps often enough will fill up the directory and let the next test run fail as explained in the initial post.

Interestingly I could not reproduce this with running the same command from the terminal `flutter --no-color test --machine --plain-name timeout test/timeout_test.dart` and trying to kill the process.
It seems like Android Studio fails to kill the process, since after stopping the test case in Android Studio, the `flutter_tester` process is still running and Android Studio prints the following log to the console:
```
2020-04-21 08:23:25,287 [3428731]   WARN - ion.process.UnixProcessManager - Error killing the process 
java.lang.IllegalStateException: IDE pid is not found in ps list(13567)
	at com.intellij.execution.process.UnixProcessManager.findChildProcesses(UnixProcessManager.java:194)
	at com.intellij.execution.process.UnixProcessManager.sendSignalToProcessTree(UnixProcessManager.java:141)
	at com.intellij.execution.process.UnixProcessManager.sendSignalToProcessTree(UnixProcessManager.java:129)
	at com.intellij.execution.process.UnixProcessManager.sendSignalToProcessTree(UnixProcessManager.java:117)
	at com.intellij.execution.process.UnixProcessManager.sendSigKillToProcessTree(UnixProcessManager.java:112)
	at com.intellij.execution.process.OSProcessUtil.killProcessTree(OSProcessUtil.java:54)
	at com.intellij.execution.process.impl.OSProcessManagerImpl.killProcessTree(OSProcessManagerImpl.java:20)
	at com.intellij.execution.process.OSProcessHandler.killProcessTreeSync(OSProcessHandler.java:221)
	at com.intellij.execution.process.OSProcessHandler.lambda$killProcessTree$0(OSProcessHandler.java:215)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Can you check if the flutter and flutter_tester processes get correctly terminated for you when you reproduce with the steps above?

**Comment by zanderso** [comment]
I started investigating cleaning up /tmp on receiving a signal, and found a Dart VM bug:

https://dart-review.googlesource.com/c/sdk/+/146080

I'll continue when that fix lands and rolls in.

**Comment by zanderso** [comment]
Found another prerequisite fix in the Dart VM https://dart-review.googlesource.com/c/sdk/+/147341.

**Comment by zanderso** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/55513

**Comment by nioncode** [comment]
@zanderso unfortunately, I can still reproduce from within Android Studio with the test case described above on current master (1.19.0-2.0.pre.73). The tool now creates a single folder (per test invocation) with subdirectories into the tmp dir, but this is not cleaned up when the test is stopped from within Android Studio.

Can you reproduce this with my test description from above?

**Comment by zanderso** [comment]
AndroidStudio is sending `SIGKILL` to the `flutter test` subprocess.

https://github.com/JetBrains/intellij-community/blob/master/platform/platform-util-io/src/com/intellij/execution/process/OSProcessUtil.java#L54

The signal is uncatchable, and so it is impossible for the tool to do any cleanup. If possible AndroidStudio should not send `SIGKILL` to the flutter tool, or should otherwise clear up any `flutter_tools.*` entries from the system temp directory itself. /cc @devoncarew @DanTup

**Comment by nioncode** [comment]
Maybe another viable strategy be would be to clean the stale folders on the next run of the tool? Otherwise, there might still be folders piling up if the caller does not clean up after killing the tool (or if the caller itself gets killed).

I don't know if there is a clean way to detect whether these folders are stale, though.

**Comment by DanTup** [comment]
FWIW in VS Code we start with a `SIGINT` the first time the user tries to stop (we also disabling breakpoints, disabling pause-on-exception, and resume, to increase the chances of things quitting cleanly). After 2s (or if the user clicks the stop button a second time) we have to terminate and can't wait, so we then send a `SIGKILL` (if we don't do this, we may end up orphaning Dart/Flutter processes).

I don't think having the IDE try to clean up is a good solution, as it doesn't know which folders are for the run it just terminated (the user could have other ongoing runs).

**Comment by zanderso** [comment]
Huh, okay. Thanks @DanTup. That's weird. I might not have access to my home office this week, but I'll give this another look when I get a chance.

In the meantime, @DanTup, do you know how killing the tool works on Windows?

**Comment by DanTup** [comment]
> Huh, okay. Thanks @DanTup. That's weird.

My comments were about VS Code (just an FYI) but the code you linked was Android Studio, so it's very possibly they have different behaviour.

> In the meantime, @DanTup, do you know how killing the tool works on Windows?

In VS Code we don't do anything differently on Windows, but it may be worth noting that we don't just terminate *the process that we launched* as this is often a shell process and I found that the signals often are not passed on reliably to the underlying Flutter/Dart/pub processes.

To fix this, we additionally collect the `pid`s that we see in the initial messages from Flutter/[package:test](https://github.com/dart-lang/test/pull/890)/observatory and when we send signals, we'll [also send them](https://github.com/Dart-Code/Dart-Code/blob/03a8c15045ae43a4ad42b3cbeda850f8dcdda21f/src/debug/dart_debug_impl.ts#L629) to all of those processes (if the pids are different to the pid we have a reference to).

**Comment by luishar0** [comment]
Hi @DanTup I recently switched to VS Code and after a few hours of running my Flutter app My Mac ran out of memory. It looks like there is 171 GB of "Other" files. Any idea how to clean this files in order to continue developing? As of right now I can't run my app, because of the full disk. Flutter doctor passes all the tests. Thanks for your contributions :)

**Comment by luishar0** [comment]
Could this be related to consuming lots of Firebase data? I switched to VS Code a few days ago. Today while running my app I received notificación that I used all my free limit of Firebase... few minutes later my Mac said the disk was full and I was not able to compile anymore due to the lack of space. 100 GB became available after restarting.

**Comment by jonahwilliams** [comment]
We could attempt to cleanup stale folders on a subsequent flutter run. To do so safely, we would need to leave some sort of lock/marker in directories that are tied to active flutter tool instances, to prevent the tool blowing away the tmp directory being used by another tool

**Comment by jonahwilliams** [comment]
Un-assigning as I haven't had time to work on this lately.

**Comment by praharshbhatt** [comment]
Having run into this, I restarted the system, and `flutter run` works fine now.

**Comment by jonahwilliams** [comment]
That reminded me, the correct fix for this would be to update IDEs to pass in a preconfigured temp directory location that the tool could use. Since the IDEs may send sigkill, they could still cleanup after the fact. FYI @devoncarew @DanTup

**Comment by DanTup** [comment]
That sounds reasonable to me - although it's worth noting in VS Code we try hard to avoid sending sigkill (first using sigint/sigterm and a delay to see if the process quits on its own) since sigkill can also leave other orphaned processes around that the IDE doesn't know to kill.
