### ISSUE TITLE
WebView freeze on iOS 13.4 with HereMaps

### ISSUE THREAD

**Issue by DFelten** [flutter/flutter#55292]
There is an issue with webview_flutter and HereMaps on iOS 13.4. First I thought it's related to [this bug](https://github.com/flutter/flutter/issues/53490), but @cyanglaz  told me to create an own issue for this bug.

When using [this site](https://www.camping.info/en/search-on-map) with a HereMaps integration within a WebView, the WebView is freezed when doing the following:

1. Zoom into the map till you see campsite marker 
2. Select a campsite on the map (Non-clustered map marker)
3. Info box appears
4. Clicking on the info box opens the detail page
5. WebView is freezed

It's working with older iOS versions, but with 13.4 the bug appears. The back button in the navigation bar still recognize touch inputs.

With the [Community Plugin for WebViews](https://pub.dev/packages/flutter_webview_plugin) the map is working on iOS 13.4.

Code example:
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(TestApp());

class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Title",
      home: Scaffold(
        appBar: AppBar(
          title: Text("Title"),
          leading: IconButton(
            icon: Icon(Icons.arrow_back_ios),
            onPressed: () => {},
          ),
        ),
        body: WebView(
          initialUrl: 'https://www.camping.info/en/search-on-map',
          javascriptMode: JavascriptMode.unrestricted,
        ),
      ),
    );
  }
}
```

**Comment by cyanglaz** [comment]
@DFelten Thanks for doing this! It may or maybe related to the other issue, I will take a look. If it is related, then we can close this issue and follow the other!

**Comment by bobppsureway** [comment]
I'm facing the same issue.
I use flutter web to create a google map page and drop some markers.
Then I use WebView to embed the web page in my app as a tab page.
But once markers' info window pops up the WebView page freezes.
Debug print nothing.
Web page behaves with no problems on Safari and Chrome browser.
iOS 13.4.1

**Comment by ztigunes** [comment]
i have same issue. are there any solution for this bug

**Comment by cyanglaz** [comment]
Someone mentioned a similar issue was fixed in ios 13.6. https://github.com/flutter/flutter/issues/53490#issuecomment-659394720

**Comment by kanal-altyapi** [comment]
I tried this, but it didn't solve the problem. Sorry, not all devices in Prod environment are iOS 13.6.

**Comment by kanal-altyapi** [comment]
Are there any solution for this. Same code working well on android but not working on ios. ios 13.6 upgrade did not solve my problem.

**Comment by ztigunes** [comment]
İ have same issue. Are there any solution except ios 13.6 upgrade ?

**Comment by ztigunes** [comment]
Other webview packages  also not working on ios. We had to delay the ios deployment because of this.  
webview_flutter not updated since May 21.  Do you have a road map for this bug? Thanks. Best regards.

**Comment by SoolyChristy** [comment]
iOS14 is good.

**Comment by stuartmorgan-g** [comment]
Given that this only happens in specific versions of iOS 13, this isn't something that we would invest resources in investigating further at this point.
