### ISSUE TITLE
Video player causes iOS app to run out of memory and crash

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#55784]
On iOS, leaving a video play long enough causes the app to crash because it runs out of memory.

This wasn't happening with Flutter 1.12-stable. I think this is related to Flutter starting to use Metal.

The following code will cause the crash:

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: VideoHomePage()
    );
  }
}

class VideoHomePage extends StatefulWidget {
  @override
  _VideoHomePageState createState() => _VideoHomePageState();
}

class _VideoHomePageState extends State<VideoHomePage> {
  
  VideoPlayerController _videoPlayerController;

  @override
  void initState() {
    super.initState();

    // use any video you have
    _videoPlayerController = VideoPlayerController.asset("videos/video.mp4");
    _videoPlayerController.setLooping(true);
    _videoPlayerController.play();
    _videoPlayerController.initialize();
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Material(
        type: MaterialType.transparency,
        elevation: 0,
        child: FittedBox(
          fit: BoxFit.fitWidth,
          child: Container(
              // these are the dimensions of my video
              width: 818.0,
              height: 864.0,
              child: VideoPlayer(_videoPlayerController)
          ),
        ),
    );
  }
}
```

Running this in Debug on an iPhone 6 or iPad Mini 3 will see it run out of memory and crash in less than 1 minute. Using a BoxFit.cover instead will make it crash in just a couple of seconds.

If running it from XCode, XCode's output shows this:
`Message from debugger: Terminated due to memory issue`

Using an AspectRatio widget also causes a crash, after it ran for 5 minutes.

This is happening on 1.18.0-dev.3.0-dev or later.

My flutter doctor:
985aeb8ceee6:all danny.valente$ flutter doctor --verbose
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.14.6 18G4032, locale en-US)
• Flutter version 1.18.0 at /Users/danny.valente/Library/flutter/1.18.0-dev.3.0-dev
• Framework revision de1e572 (3 weeks ago), 2020-04-06 16:15:07 -0700
• Engine revision df257e59c2
• Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/danny.valente/Library/Android/sdk
• Platform android-29, build-tools 29.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
• All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.3.1, Build version 11C505
! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade:
sudo gem install cocoapods

[✓] Android Studio (version 3.6)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 45.1.1
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by pcsosinski** [comment]
does this happen on 1.17 as well?

**Comment by dannyvalentesonos** [comment]
@pcsosinski Yes, just checked and it happens with as well.

Some output from Xcode when the crash is about to happen:

```
2020-04-28 10:32:32.557527-0400 Runner[338:6690] [Accessibility] ****************** Loading GAX Client Bundle ****************
2020-04-28 10:32:32.941879-0400 Runner[338:6690] Metal API Validation Enabled
2020-04-28 10:32:33.432839-0400 Runner[338:6911] TX and TY are 0. Rotation: 0. Natural width,height: 818.000000, 864.000000
2020-04-28 10:32:47.951981-0400 Runner[338:6690] Could not load IOSurface for time string. Rendering locally instead.
2020-04-28 10:33:00.010305-0400 Runner[338:6690] Could not load IOSurface for time string. Rendering locally instead.
Message from debugger: Terminated due to memory issue
```

#55783 also happens as well. I didn't think Metal was turned on in 1.17, but judging by the logs, it is, and my theory still holds that this was introduced by the change for Metal.

Thanks.

**Comment by Hixie** [comment]
I set a more or less random target milestone since it was assigned; please update as necessary. If this is a 1.17 blocker please coordinate with @pcsosinski for a hot fix. Thanks!

**Comment by chinmaygarde** [comment]
I haven't been able to reproduce this on iPhone X, 11 and XR with ToT today. This is using just the butterfly video in the video player plugin example looping over and over. I also couldn't observe any increase in memory usage over time either. What is the resolution of the video? In the meantime, I'll fetch the an iPhone 6 I have lying somewhere and report back on the results.

![Screen Shot 2020-04-28 at 8 42 21 PM](https://user-images.githubusercontent.com/44085/80558914-cc0e3300-8990-11ea-8d09-1d43700303e0.png)

**Comment by dannyvalentesonos** [comment]
@chinmaygarde the resolution of the video is 818.0 x 864.0 and it's about 11 seconds in length.
I re-tested today and on 1.12 it ran for 1 hour without issue. On 1.17 and 1.18 it crashed within seconds.

**Comment by chinmaygarde** [comment]
On an iPhone 6, it was fine for a while before running into a couple of memory spikes. So it does seem to be device specific. I think I have enough to investigate for now. Will report back with results.

![Screen Shot 2020-04-28 at 8 54 12 PM](https://user-images.githubusercontent.com/44085/80559552-bac62600-8992-11ea-8cf0-f5329ecf5268.png)

**Comment by dannyvalentesonos** [comment]
@chinmaygarde  Another thing to mention is that both my iPhone 6 and iPad Mini 2 have the problem, and they are both on iOS 12.

**Comment by chinmaygarde** [comment]
Sounds good. I haven't been able to reproduce this on any device above that either. I can't tell if this is device or OS version specific till I can access the device lab in the office. But we'll know once anyway once the cause has been identified. Instrumenting a few things now.

**Comment by chinmaygarde** [comment]
The spikes correspond to IOSurface creation runaways. Interestingly, these are the ones created when we wrap the onscreen surface (my instinct was that this would be around the pixel buffer for the external texture). Nothing obvious jumps out in the engine as being a leak but at least now I know what is leaking.

It is unlikely I will have this patched by EOD today. Will give another update tomorrow after further investigation. Currently my top priority.

![Screen Shot 2020-04-28 at 9 39 28 PM](https://user-images.githubusercontent.com/44085/80561364-15fb1700-8999-11ea-99d0-9c22bf04775f.png)

**Comment by ened** [comment]
Similarly happening on iPhone XS Max, iOS 13.4.1, when playing a video of resolution 848 x 480.

**Comment by chinmaygarde** [comment]
Figured it out. The drawables expect to be presented with a transaction. However, when the crashes happen, the transaction stack appears to be empty. So even though we released our reference on the drawable, it was still held in device memory waiting for a transaction that never came. Newer iOS devices seem to commit it anyway while older ones will till memory exhaustion. I have verified it on device. The test cases did not catch this because they were complicated enough to push an implicit transaction onto the transaction stack. Fix incoming.

On the iPhone 6 where this would crash after a few seconds, now it shows:

![Screen Shot 2020-04-30 at 4 52 45 PM](https://user-images.githubusercontent.com/44085/80769725-0861a080-8b03-11ea-98f4-c96c58f6cbfa.png)

**Comment by dannyvalentesonos** [comment]
That is great news. Thanks very much for looking into this quickly @chinmaygarde

**Comment by chinmaygarde** [comment]
This is a regression and is not related to Metal. This was introduced in https://github.com/flutter/engine/pull/17609#issuecomment-622214872.

**Comment by chinmaygarde** [comment]
Fix is pending in https://github.com/flutter/engine/pull/18076

**Comment by dannyvalentesonos** [comment]
> This is a regression and is not related to Metal. This was introduced in [flutter/engine#17609 (comment)](https://github.com/flutter/engine/pull/17609#issuecomment-622214872).

If that's the case, then I wonder if you're fixing the actual issue that I'm running into then, because I first found it on 1.18.0-dev.3.0, which was released on April 7th, which is before that Pull Request was merged @chinmaygarde.

**Comment by chinmaygarde** [comment]
Hmm, I verified on ToT and that patch I linked was a re-land after an initial revert. So I am not certain. I am going to check on 1.18.0-dev.3.0. Specifically, it was the bit about [conditionally adding the transactions ](https://github.com/flutter/engine/commit/68fd8334889610af08cbfc2828f91cf14faf3f1d#diff-0ca719a09eaf27569bc6435bb6e9bbc3R93)that caused the issue.

**Comment by dannyvalentesonos** [comment]
I looked at the change, and I think that only changed the gl surface code, and the Metal surface code never had the transaction at all possibly?

**Comment by timsneath** [comment]
@dannyvalentesonos can you test this on the latest beta release, please? We're extremely keen to be sure we've fixed this bug on Metal.

**Comment by dannyvalentesonos** [comment]
@timsneath I've just tested and had the video running for 30 minutes with no crash, using the latest beta (1.17.0-3.4.pre).

However, in that build, #55783 is not resolved. Is that expected?
