### ISSUE TITLE
link_stat "/Users/juico/Desktop/personalDev/bountyhunter/ios/Flutter/App.framework" failed: No such file or directory

### ISSUE THREAD

**Issue by nalnir** [flutter/flutter#56555]
It's been so great to work with flutter. Android works perfectly, but ios has been a bit of a frustration lately.

I'm on `master`channel and after `flutter run` I get this:

```
Iris-MacBook-Pro:bountyhunter juico$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                             11.0s
Running Xcode build...                                                  
Xcode build failed due to concurrent builds, will retry in 2 seconds.
Running Xcode build...                                                                                             
Xcode build done.                                           119.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:176:7: warning: 'UIGraphicsImageRendererFormat' is only available on iOS 10.0 or newer
    [-Wunguarded-availability]
          UIGraphicsImageRendererFormat* format = [UIGraphicsImageRendererFormat defaultFormat];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/juico/Desktop/personalDev/bountyhunter/ios/Pods/Target Support Files/google_maps_flutter/google_maps_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGraphicsImageRenderer.h:26:50: note:
    'UIGraphicsImageRendererFormat' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    UIKIT_EXTERN API_AVAILABLE(ios(10.0)) @interface UIGraphicsImageRendererFormat : UIGraphicsRendererFormat
                                                     ^
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:176:7: note: enclose 'UIGraphicsImageRendererFormat' in an @available check to silence this
    warning
          UIGraphicsImageRendererFormat* format = [UIGraphicsImageRendererFormat defaultFormat];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:176:78: warning: 'defaultFormat' is only available on iOS 10.0 or newer
    [-Wunguarded-availability]
          UIGraphicsImageRendererFormat* format = [UIGraphicsImageRendererFormat defaultFormat];
                                                                                 ^~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/juico/Desktop/personalDev/bountyhunter/ios/Pods/Target Support Files/google_maps_flutter/google_maps_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGraphicsRenderer.h:24:1: note: 'defaultFormat' has been marked as
    being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    + (instancetype)defaultFormat API_DEPRECATED_WITH_REPLACEMENT("preferredFormat", tvos(10.0, 11.0)) API_AVAILABLE(ios(10.0), watchos(3.0));
    ^
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:176:78: note: enclose 'defaultFormat' in an @available check to silence this warning
          UIGraphicsImageRendererFormat* format = [UIGraphicsImageRendererFormat defaultFormat];
                                                                                 ^~~~~~~~~~~~~~
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:176:48: warning: 'UIGraphicsImageRendererFormat' is only available on iOS 10.0 or newer
    [-Wunguarded-availability]
          UIGraphicsImageRendererFormat* format = [UIGraphicsImageRendererFormat defaultFormat];
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/juico/Desktop/personalDev/bountyhunter/ios/Pods/Target Support Files/google_maps_flutter/google_maps_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGraphicsImageRenderer.h:26:50: note:
    'UIGraphicsImageRendererFormat' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    UIKIT_EXTERN API_AVAILABLE(ios(10.0)) @interface UIGraphicsImageRendererFormat : UIGraphicsRendererFormat
                                                     ^
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:176:48: note: enclose 'UIGraphicsImageRendererFormat' in an @available check to silence this
    warning
          UIGraphicsImageRendererFormat* format = [UIGraphicsImageRendererFormat defaultFormat];
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:178:7: warning: 'UIGraphicsImageRenderer' is only available on iOS 10.0 or newer
    [-Wunguarded-availability]
          UIGraphicsImageRenderer* renderer =
          ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/juico/Desktop/personalDev/bountyhunter/ios/Pods/Target Support Files/google_maps_flutter/google_maps_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGraphicsImageRenderer.h:43:50: note: 'UIGraphicsImageRenderer'
    has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    UIKIT_EXTERN API_AVAILABLE(ios(10.0)) @interface UIGraphicsImageRenderer : UIGraphicsRenderer
                                                     ^
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:178:7: note: enclose 'UIGraphicsImageRenderer' in an @available check to silence this warning
          UIGraphicsImageRenderer* renderer =
          ^~~~~~~~~~~~~~~~~~~~~~~
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:179:13: warning: 'UIGraphicsImageRenderer' is only available on iOS 10.0 or newer
    [-Wunguarded-availability]
              [[UIGraphicsImageRenderer alloc] initWithSize:_mapView.frame.size format:format];
                ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/juico/Desktop/personalDev/bountyhunter/ios/Pods/Target Support Files/google_maps_flutter/google_maps_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGraphicsImageRenderer.h:43:50: note: 'UIGraphicsImageRenderer'
    has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    UIKIT_EXTERN API_AVAILABLE(ios(10.0)) @interface UIGraphicsImageRenderer : UIGraphicsRenderer
                                                     ^
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:179:13: note: enclose 'UIGraphicsImageRenderer' in an @available check to silence this warning
              [[UIGraphicsImageRenderer alloc] initWithSize:_mapView.frame.size format:format];
                ^~~~~~~~~~~~~~~~~~~~~~~
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:181:53: warning: 'UIGraphicsImageRendererContext' is only available on iOS 10.0 or newer
    [-Wunguarded-availability]
          UIImage* image = [renderer imageWithActions:^(UIGraphicsImageRendererContext* context) {
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/juico/Desktop/personalDev/bountyhunter/ios/Pods/Target Support Files/google_maps_flutter/google_maps_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGraphicsImageRenderer.h:39:50: note:
    'UIGraphicsImageRendererContext' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    UIKIT_EXTERN API_AVAILABLE(ios(10.0)) @interface UIGraphicsImageRendererContext : UIGraphicsRendererContext
                                                     ^
    /Users/juico/Downloads/dev tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.25+2/ios/Classes/GoogleMapController.m:181:53: note: enclose 'UIGraphicsImageRendererContext' in an @available check to silence this
    warning
          UIImage* image = [renderer imageWithActions:^(UIGraphicsImageRendererContext* context) {
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    6 warnings generated.
    The path  does not exist
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Using build description from disk
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

```

`flutter doctor -v` :
```
flutter doctor -v
[✓] Flutter (Channel master, v1.16.4-pre.20, on Mac OS X 10.15.3 19D76, locale en-IS)
    • Flutter version 1.16.4-pre.20 at /Users/juico/Downloads/dev tools/flutter
    • Framework revision 2d24998343 (6 weeks ago), 2020-03-29 16:41:01 -0400
    • Engine revision 946df02dc6
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/juico/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 5A6AACF5-D693-40E0-A5CA-2F377A2FE8F7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 81.0.4044.129
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

`pubspec.yaml`:
```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
    
  firebase_auth: ^0.14.0+5
  flutter_auth_buttons: ^0.6.0
  firebase_storage: ^3.1.3
  firebase_database: ^3.1.3
  # cloud_firestore: ^0.13.4+2
  # Facebook Login
  flutter_facebook_login: ^3.0.0
  # Password Packages
  flutter_password_strength: ^0.1.4
  password_strength: ^0.1.2
  # Font Awesome
  font_awesome_flutter: ^8.7.0
  # Image Picker
  image_picker: ^0.6.3+4
  # Money Parser
  flutter_masked_text: ^0.7.0
  # Google Maps
  google_maps_flutter: ^0.5.25+2
  #Geocode
  geocoder: ^0.2.1
  # Nanoid - ID generator
  nanoid: ^0.1.0
  # URL Launcher
  url_launcher: ^5.4.2
  # Charts
  multi_charts: ^0.2.0
  # Launcher Icons
  flutter_launcher_icons: ^0.7.4
  # Flare Animations
  flare_flutter: ^2.0.3


dependency_overrides:
  firebase_core: 0.4.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

I've tried flutter clean and running it again but same would happen

**Comment by VladyslavBondarenko** [comment]
Hi @nalnir 
could you try if you are experiencing this with the latest version google_maps_flutter 0.5.27+1?
should be fixed by https://github.com/flutter/flutter/issues/55258

**Comment by nalnir** [comment]
Thank a lot @VladyslavBondarenko
This actually solver the warnings, but the main issue still remains:
```
flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                             18.7s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           74.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    The path  does not exist
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

**Comment by VladyslavBondarenko** [comment]
@nalnir 
please follow up on https://github.com/flutter/flutter/issues/51395
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it

**Comment by nalnir** [comment]
@VladyslavBondarenko.
The #51395 thread touches on these 2 warnings, but the main problem remains.
Now when I do `flutter run` i get this:

```
Iris-MacBook-Pro:bountyhunter juico$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running Xcode build...                                                  
                                                   
Xcode build done.                                           35.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    building file list ... rsync: link_stat "/Users/juico/Desktop/personalDev/bountyhunter/ios/Flutter/App.framework" failed: No such file or directory (2)
    done

    sent 29 bytes  received 20 bytes  98.00 bytes/sec
    total size is 0  speedup is 0.00
    rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54/rsync/main.c(996) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

```

**Comment by VladyslavBondarenko** [comment]
@nalnir 
does this directory `/Users/juico/Desktop/personalDev/bountyhunter/ios/Flutter/App.framework` exist?

**Comment by nalnir** [comment]
@VladyslavBondarenko 
Sorry I haven't replied earlier, you can close the issue.
I deleted `ios` folder from my flutter project and `flutter create`. Then just Edited `info.plist`, added and edited `GoogleService-Info.plist`
`flutter clean`
`flutter ios build`
than clean a build in xcode and rebuild it again and everything works now.

**Comment by VladyslavBondarenko** [comment]
@nalnir Thank you for the input, closing

**Comment by PourErik** [comment]
@nalnir How did you edit your info.plist? What did you add?

**Comment by nalnir** [comment]
Hi @PourErik. It was a while ago, let me dig a bit, will let you know asap.

**Comment by nalnir** [comment]
> @nalnir How did you edit your info.plist? What did you add?
Are you struggling with the same error I did or are you asking regarding the Google Maps usage in your app?

**Comment by PourErik** [comment]
Thanks! Same error

**Comment by nalnir** [comment]
I am not sure exactly what change I made to info.plist, but I can paste the code here:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Bounty Hunter</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.7</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb454**********16</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>7</string>
	<key>FacebookAppID</key>
	<string>454**********16</string>
	<key>FacebookDisplayName</key>
	<string>Bounty Hunter</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>Privacy - Bounty Hunter requires usage of the camera for user to be able to take and post the images of their lost pets or other possessions for purposes of description and identification.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Privacy - Microphone Usage Description</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Privacy - Bounty Hunter requires usage of the photo library for user to be able to post the images of their lost pets or other possessions for purposes of description and identification.</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>
```

**Comment by nalnir** [comment]
@PourErik Please let me know if it helped in any way.

**Comment by PourErik** [comment]
Thanks @nalnir; I'll keep playing with it. Just a nightmare of errors here trying to get 2 build versions going (dev vs. prod).

**Comment by nalnir** [comment]
@PourErik Yeah I know the feeling man. It can get frustrating sometimes. Hope you'll solve it soon.
