### ISSUE TITLE
Flutter Web + CanvasKit crash

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#56938]
Apps running with CanvasKit that animate/redraw often seem to crash after a few minutes.

Code: https://github.com/luigi-rosso/canvaskit_issue

```
flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome
```
Let it run untouched, after 5-10 minutes it'll spew the console with warnings and the app will crash with a white (empty) screen:

![image](https://user-images.githubusercontent.com/454182/81605105-d57e9e80-9385-11ea-99a4-388e7a122075.png)

This is similar to #52447. 

If you let that example above run multiple times, you'll see that it randomly crashes in a few different areas, making it seem like a general instability/corruption that occurs. Usually related to text (either paragraph.layout or calling CanvasKit's ParagraphBuilder.Make).

Out of curiosity, I let a basic CanvasKit fiddle (no flutter) run for a while. It took considerably longer (almost an hour) but it eventually also threw an error (with no interaction), which is why I'm wondering if this is an underlying lower-level issue with web assembled Skia:
![image](https://user-images.githubusercontent.com/454182/81604358-9f8cea80-9384-11ea-945c-f47ab6468703.png)

CanvasKit fiddle is here:
https://jsfiddle.skia.org/canvaskit/56cb197c724dfdfad0c3d8133d4fcab587e4c4e7f31576e62c17251637d3745c

If you dig further into that stack, you'll see it also blew up when doing something text-related (when drawing a paragraph):
![image](https://user-images.githubusercontent.com/454182/81604801-51c4b200-9385-11ea-9258-6f35aeda7681.png)

Tried on both master and dev, currently on dev:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by hterkelsen** [comment]
@kjlubick possible memory leak or some other problem in CanvasKit?

**Comment by kjlubick** [comment]
That sounds like a memory leak to me. I think it's the font families (and ellipsis) that are causing leakage - we malloc those little strings on every frame, but never free them.

There's two options here - free the strings when ParagraphBuilder.Make returns or when we malloc the font family names and ellipsis the first time, we cache the pointers and never free them. This means if font families are 1) relatively few and 2) mostly constant, we can be a bit more performant and not have to malloc more than we have to.

Any inputs on what approach to take here?

**Comment by hterkelsen** [comment]
In most apps, I think font families _are_ indeed relatively few and mostly constant. In Flutter apps it's relatively rare to load fonts dynamically.

**Comment by luigi-rosso** [comment]
To test your theory, we commented out the font family and ellipsis setters from the Flutter engine side (so CanvasKit doesn't malloc) and our app has now been running 20 minutes without crashes (or text). So it definitely seems like that's the cause.

**Comment by kjlubick** [comment]
Fix landed in https://skia-review.googlesource.com/c/skia/+/289778

I want to check out one more bug related to Safari before cutting a new CanvasKit version for npm. I'll try to have it by end of day today.

**Comment by mariamhas** [comment]
needed to rollback update https://github.com/flutter/engine/pull/18600 due to an issue with the upgrade https://github.com/flutter/flutter/issues/58014

**Comment by mjohnsullivan** [comment]
Unfortunately, we're still seeing the issue on the latest Flutter master:

Flutter (Channel master, 1.20.0-1.0.pre.26, on Mac OS X 10.15.5 19F101, locale en-US).

In our app, we see this:

```
RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at Fa (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.js:137:66)
    at e (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.js:234:468)
    at https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.wasm:wasm-function[461]:0x8c30
    at https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.wasm:wasm-function[2688]:0xdcdd7
    at https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.wasm:wasm-function[9044]:0x311147
    at di (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.wasm:wasm-function[1623]:0x5cdad)
    at Wh (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.wasm:wasm-function[3625]:0x144054)
    at g.dynCall_ii (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.js:308:24)
    at dynCall_ii_556 (eval at Cc (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.js:1:1), <anonymous>:4:12)
    at SkPictureRecorder.A.jk.Ok.<computed> (https://unpkg.com/canvaskit-wasm@0.16.1/bin/canvaskit.js:223:304)
```

Running the test app referenced earlier in the issue, we're seeing this after roughly 5.5 minutes:

![Screen Shot 2020-06-11 at 2 49 54 PM](https://user-images.githubusercontent.com/102488/84443701-fd675900-abf4-11ea-9801-53f04a79a23d.png)

And when checking what version of CanvasKit it's using:

![Screen Shot 2020-06-11 at 3 07 07 PM](https://user-images.githubusercontent.com/102488/84443844-4fa87a00-abf5-11ea-9eff-eb3c5dfce272.png)

**Comment by hterkelsen** [comment]
This may be fixed in CanvasKit 0.16.2 (see [changelog](https://github.com/google/skia/blob/master/modules/canvaskit/CHANGELOG.md)). I'll make a PR rolling us to 0.16.2 while running your crash app in the background and see if that fixes it.

**Comment by hterkelsen** [comment]
Thanks for the useful repro app. I have been trying to debug this (so far the most effective way I've found to prevent the app from crashing is to set a breakpoint in the code ;) ) and I suspect that the SkFontMgr is becoming invalidated when WASM resizes memory. I will continue to look into this.

**Comment by mariamhas** [comment]
re opening as this issue still exists. please don't close it

**Comment by hardmode98** [comment]
I recently used this and had the same on my chrome for android and other browsers. The webpage get's stuck and nothing is responsive.

**Comment by MichealReed** [comment]
https://github.com/flutter/flutter/issues/50409 related?

**Comment by Hixie** [comment]
Downgrading to P2 since canvaskit is still experimental.

**Comment by MichealReed** [comment]
Sorry to report, but the memory leak and resulting crash still seems to be intact.

```
[√] Flutter (Channel master, 1.20.0-3.0.pre.98, on Microsoft Windows [Version 10.0.17758.4], locale en-US)
    • Flutter version 1.20.0-3.0.pre.98 at C:\src\flutter
    • Framework revision df98ad6b2e (84 minutes ago), 2020-06-29 21:33:01 -0400
    • Engine revision 2609ded48e
    • Dart version 2.9.0 (build 2.9.0-19.0.dev f91547d6dd)
```

**Comment by softmarshmallow** [comment]
Not related to flutter, but submitting here since it's the same canvaskit problem.
Working with canvaskit-wasm on react app, having this error when memory overload (i guess?)
```
rendering error RuntimeError: abort(undefined).
```
