### ISSUE TITLE
Flutter web does not handle pointer hover events.

### ISSUE THREAD

**Issue by Markzipan** [flutter/flutter#57347]
After some bisection, [this commit](https://github.com/flutter/flutter/commit/5fa1c60b174ee2eb8288cca6f68f9f3611133026), 
 results in `flutter/mousecursor` events being backlogged and never handled handled. Unhandled errors subsequently print: 
```
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
```

Messages keep being inserted into this queue [here](https://github.com/flutter/flutter/blob/master/packages/flutter_web_plugins/lib/src/plugin_registry.dart#L84) but never drained.

Trivially deleting the super call here fixes the issue for me, which seems to agree with that: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/mouse_tracking.dart#L580

```
Channel: master
Version: 1.19.0-2.0.pre.73
```

Flutter gallery confirmed working at commit: `c81449e5ab97fb63c9cf10c48744d700454ae5e8`

Flutter gallery confirmed failing at the subsequent commit: `5fa1c60b174ee2eb8288cca6f68f9f3611133026`

Steps to reproduce:

1. Check out flutter/flutter at `5fa1c60b174ee2eb8288cca6f68f9f3611133026` or later.
2. Run flutter gallery with `flutter run -d chrome`
3. Open Chrome Devtools's console
4. Move your mouse over the various onscreen Flutter Gallery items
5. Observe the console being cluttered with the aforementioned error.

**Comment by ja2375** [comment]
I can confirm this is not fixed in `1.19.0-2.0.pre.83` on `master` channel as well.

**Comment by TahaTesser** [comment]
Hi @Markzipan  @ja2375 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Markzipan** [comment]
Sorry about that - I've updated the original issue with repro steps

**Comment by TahaTesser** [comment]
```
Downloading Web SDK...                                              4.1s
Launching lib/main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:50592/-u2FvJWHk5Y=
A null value was passed into a non-nullable parameter value
This will become a failure when runtime null safety is enabled.
Null is not a subtype of FutureOr<ByteData>.
This will become a failure when runtime null safety is enabled.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Application finished.
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.114, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.19.0-2.0.pre.114 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 1cfd792a38 (8 hours ago), 2020-05-18 18:18:16 -0500
    • Engine revision 4b1a70e6a2
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details>

**Comment by dkwingsmt** [comment]
I have a corresponding engine change but I left it pending because I did not know that this backlog would cause such issue. I will have the change merged soon.

**Comment by ferhatb** [comment]
@dkwingsmt want to self assign and add milestone?

**Comment by dkwingsmt** [comment]
Fixed with https://github.com/flutter/engine/pull/17718.

**Comment by ayushin** [comment]
Still present in master on Mac OSX Safari Version 13.1 (15609.1.20.111.8)

Overflow on channel: flutter/mousecursor. Messages on this channel are being discarded in FIFO fashion. The engine may not be running or you need to adjust the buffer size if of the channel. SE — channel_buffers.dart:144

[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E287, locale en-CZ)

**Comment by ja2375** [comment]
I also keep getting this in latest master. @dkwingsmt Is there anything that we need to do to prevent this from happening?

**Comment by dkwingsmt** [comment]
The change needs to be rolled into Flutter. After https://github.com/flutter/flutter/pull/57861 is merged, you should no longer see the error on the master channel. If you’re using other channels, you’ll need a release on that channel. In the mean time, you’ll probably have to patch the framework by removing the call to the mousecursor channel.
