### ISSUE TITLE
App screen not shown correctly 

### ISSUE THREAD

**Issue by detinho** [flutter/flutter#5737]
## Steps to Reproduce

Installed flutter, atom, created an app and tried to run from command line.

Please tell us what you were doing and what went wrong.
I was following the flutter getting started guide and tried to run the app created by flutter create. The app is created and installed correctly, but the screen is very strange.
![screenshot_20160904-092515](https://cloud.githubusercontent.com/assets/631905/18231016/cb42a970-7282-11e6-8d89-009b04919af9.png)
## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/detinho/projetos/flutter/flutter
    • Framework revision 9a0a0d9903 (3 semanas atrás), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /home/detinho/Android/Sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
## Logs and Crash Reports

Please attach any relevent logs or crash reports.
I left the app open for some time and got this log message on terminal:
W/ActivityManager: Unable to start service Intent { cmp=com.google.android.gm.exchange/com.android.exchange.service.EasService } U=0: not found

This log message does not show immediately, only after some time. 

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
This looks like a bug @chinmaygarde fixed on master last week.  I'd recommend trying switching the branch to master (`git checkout master` inside the flutter sdk checkout) and seeing if that resolves the issue.

**Comment by detinho** [comment]
@eseidelGoogle I got the same results. I tried just switching to master and even cloned the repo again, but without success.

**Comment by eseidelGoogle** [comment]
@detinho I'm sorry to hear that.  Thank you for the update.  This type of failure is typically device specific.  Can you tell us what kind of device this is as well as the Android version?  `flutter devices` may include the necessary output, if not we'll update it to (cc @danrubel).  Thanks!

**Comment by detinho** [comment]
@eseidelGoogle here is the output of `flutter devices`
`MotoG3 • 0018687065 • android-arm`

Other info:
It's a Moto G 3rd gen smartphone.
Android version: 6.0
Kernel version: 3.10.49-gf9e7acc

I'll try to run on an emulator and see what happens.

**Comment by tjerkw** [comment]
Similar issue here on a moto g3:

`ronald@ronald-ThinkCentre-E73:~/workspace/flutter/examples/flutter_gallery$ flutter devices
1 connected device:

MotoG3 • ZY2222VVC7 • android-arm
ronald@ronald-ThinkCentre-E73:~/workspace/flutter/examples/flutter_gallery$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
   • Flutter at /home/ronald/workspace/flutter
   • Framework revision 9a0a0d9903 (4 weeks ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
   • Android SDK at /home/ronald/Android/Sdk
   • Platform android-23, build-tools 24.0.2
   • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
   • flutter plugin version 0.2.4
   • dartlang plugin version 0.6.38

[10:45]  
ronald@ronald-ThinkCentre-E73:~/workspace/flutter/examples/flutter_gallery$ flutter run --release
Building APK in release mode (android-arm-release)...      
Warning: signing the APK using the debug keystore.
Built build/app.apk (14.9MB).
Running lib/main.dart on MotoG3...
--------- beginning of main
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
w
Exception from flutter run: The null object does not have a getter 'firstIsolateId'.

NoSuchMethodError: method not found: 'firstIsolateId'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ResidentRunner._debugDumpApp.<_debugDumpApp_async_body> (package:flutter_tools/src/resident_runner.dart:50)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#5      StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#6      _rootRun (dart:async/zone.dart:1146)
#7      _CustomZone.run (dart:async/zone.dart:1026)
#8      _CustomZone.runGuarded (dart:async/zone.dart:924)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#10     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#11     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#12     _rootRun (dart:async/zone.dart:1150)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)`

I have a screenshot, how do i add it?

**Comment by tjerkw** [comment]
![screenshot_20160908-104230](https://cloud.githubusercontent.com/assets/818865/18343025/ce252ca8-75b1-11e6-8c55-ac8ce634b2a3.png)

**Comment by eseidelGoogle** [comment]
We had one such issue a few weeks back which has since been fixed on master, but not alpha (alpha is still about a month old).  If you haven't already, I might try updating to master.  Separately we're working on doing better smoke-testing across more device types so we catch these kind of bugs earlier.  FYI @chinmaygarde @jason-simmons

**Comment by eseidelGoogle** [comment]
Sorry, I dropped the ball here.  I don't have a moto g3 immediately on hand, but I can definitely get one.

We've made massive changes to our engine and Framework since this bug was filed.  I would expect things to work (or certainly work differently) now.  If either of you would be willing to try again that would be helpful!

**Comment by eseidelGoogle** [comment]
Moto G3 has a Adreno 306 gpu which is present in about 10% of smartphones according to unity's numbers and is definitely covered by Skia's testing.

I suspect we've fixed this, or we'd be getting a lot more complaints about it. Speculatively closing, please feel empowered to re-open with more info!

**Comment by jdwbell** [comment]
This issue still exists on my Moto G3 using the current version of Flutter Gallery in the app store.
Android version 6.0
Kernel version 3.10.49-g88eb8b3

An update is available for this phone now.  Some time next week I will update the phone and report back whether that resolves the issue.

**Comment by eseidelGoogle** [comment]
Yes, this is a known issue in the currently published (~6mo old iirc) Flutter Gallery.  We plan to publish a new version soon: https://github.com/flutter/flutter/issues/7983

Until then, you can run the latest version of the gallery by following flutter.io/setup and then running (using `flutter run --release`) the examples/flutter_gallery on your phone locally.

Our build bots also produce (release) apks for the Gallery on every checkin if you're curious to see what the latest gallery looks like w/o setting up flutter yourself:
https://build.chromium.org/p/client.flutter/builders/Linux
