### ISSUE TITLE
Text widget incorrectly wraps Korean text

### ISSUE THREAD

**Issue by doohickey-maker** [flutter/flutter#59284]
The Text widget breaks Korean words in the middle - see screenshot.  This does not happen with English text, where the lines break along spaces, as expected.

## Steps to Reproduce

@override
Widget build(BuildContext context) {
  return Text('조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고');

**Expected results:**

Lines break along spaces.

**Actual results:**

Lines break in middle of words.  See screenshot below.

![image](https://user-images.githubusercontent.com/66804265/84442793-4ecf1280-ac0c-11ea-917f-1998178a5817.png)

**Comment by TahaTesser** [comment]
![flutter_01](https://user-images.githubusercontent.com/48603081/84495151-52c06a80-acc8-11ea-8235-f34e9c2268f1.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
            child: Text(
                '조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고')),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (3 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (4 available)            
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
``` 

</details>

**Comment by doohickey-maker** [comment]
Bump, any update?  This is blocking internationalization on my app.  Also isn't this a pretty serious issue that affects all Flutter apps that show Korean text?  Surprised that it's not getting more attention.

**Comment by jpoh281** [comment]
please Korean word break.

**Comment by GoldenSoju** [comment]
Is there any way for this issue to get some more attention? Placing line-breaks manually has its limits...

**Comment by 06153** [comment]
For simple strings I ended up doing this:
`Wrap(
    children: '조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고'.split(' ').map((x) => Text(x)).toList()
);`

**Comment by jpoh281** [comment]
Oh. good idea

**Comment by kirimi** [comment]
It's now October 2021. Version 2.5.2

This issue has blocked our apps from being featured in the Google Play.  😢

Moderators wrote:
**Localization-Specific Issues:**
_[Korean]_
Issue#1 KO-1 (In-App] text has awkward line breaks)

We have over 800 localized text resources.

**Comment by sylfree** [comment]
Any updates on this?

**Comment by hyoungc** [comment]
No update in Flutter 3.0 regarding this issue yet
need to escalate this?

**Comment by justinmc** [comment]
I think [here](https://github.com/flutter/engine/blob/e0ba7c6f1df075e7a3869676aa7558eb45577182/third_party/txt/src/minikin/LineBreaker.cpp#L522) is where we compute line breaks, except for web which is [here](https://github.com/flutter/engine/blob/c12332bbd38d12ee248e592f3661361fa9bbb3d8/lib/web_ui/lib/src/engine/text/line_breaker.dart#L187).  (For web, I'm unsure if we use that code for actual text layout or if we let the browser do that, at least for inputs?  When I tested the example code here, I saw the same bug on the web for whatever it's worth.)

I also tried this out in plain HTML and it seemed to break the word in the same way.  Am I misunderstanding what should happen in my ignorance of Korean?

```html
<div style="width:475px;">
조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고
</div>
```

<img width="475" alt="Screen Shot 2022-05-23 at 1 35 39 PM" src="https://user-images.githubusercontent.com/389558/169901719-60c49001-073d-438c-bfd6-b6664578e4b3.png">



<details>

<summary>Example app with width set</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
            width: 385.0,
            child: Text(
                '조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고')),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

</details>

**Comment by karipe** [comment]
@justinmc 

Since Korean has spacing, Korean speakers expect the following results in that case.
![image](https://user-images.githubusercontent.com/763152/177280522-66dbd4a3-03b5-47f0-b082-ff77a91c0005.png)
Therefore, many Korean websites use the word-break: keep-all style of css.

```
<div style="width:475px;word-break: keep-all;">
조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고
</div>
```

Of course, depending on the situation, some long words such as '무구정광대다라니경' may require a line break in the middle of the word.
This is also similar to other languages with spacing. But I think this case can be solved using Zero Width Space(무구정광\u200B대다라니경).

**Comment by hyoungc** [comment]
This issue has nothing to do with how Web browser works. It doesn't matter whether the same thing is shown or not on Web.
The point is that Flutter doesn't break only Korean sentences by space even though it's not different from other languages at all on word separating by the space.

**Comment by note11g** [comment]
@justinmc 
dear flutter team, please reply this issue.
this issue is a very important issue. it can have a serious impact on UX.

**Comment by dohuon** [comment]
I loved and used Flutter for yea
rs. I used to promote Flutter fro
m my Youtube channel 작은개발
자. This issue is huge blocker an
d one of some reasons I say Flu
tter is still NOT ready for the pro
duciton. Flutter teams are proba
bly English speaker and never ha
d a chance to experience this pr
oblem but I want you to know m
any Korean developers are strug
gling with this issue.

**Comment by cbracken** [comment]
@jason-simmons do you have thoughts on this? 

> @justinmc's comment from above: I think [here](https://github.com/flutter/engine/blob/e0ba7c6f1df075e7a3869676aa7558eb45577182/third_party/txt/src/minikin/LineBreaker.cpp#L522) is where we compute line breaks, except for web which is [here](https://github.com/flutter/engine/blob/c12332bbd38d12ee248e592f3661361fa9bbb3d8/lib/web_ui/lib/src/engine/text/line_breaker.dart#L187).

**Comment by goderbauer** [comment]
Is this related to https://github.com/flutter/flutter/issues/19584, i.e. is Flutter's ICU data set maybe missing the relevant dictionaries to detect word breaks in Korean?

**Comment by cbracken** [comment]
See my comment here: https://github.com/flutter/flutter/issues/59284#issuecomment-1020435473

Korean text includes spaces, and those are potential linebreak sites, so I'd have thought it should be pretty straightforward to at least break on spaces.

I'm not familiar with the full extent of Korean linebreak rules; for example, my understanding is that there's no space between a verb and a particle, but I'm not sure if that's a potential linebreak site. That said, I believe breaking on spaces should at least cover a large subset of potential break points and significantly improve our behaviour here.

**Comment by justinmc** [comment]
Added the Skia label because @loic-sharma and @chunhtai pointed out that this is handled by Skia now ([here](https://github.com/google/skia/blob/a743a424c2c78b30006212463422638bac2847c8/modules/skparagraph/src/ParagraphImpl.cpp#L518)).

**Comment by GaryQian** [comment]
Cc @Rusino who wrote SkParagraph that seems to have carried this behavior forwards from LibTxt

**Comment by jason-simmons** [comment]
Flutter's text layout libraries use the ICU boundary analysis APIs to calculate line breaks.  For the text in the example above, the ICU API is saying that character positions midway through a sequence like `여러` are valid line breaks.

I get the same results from ICU if I replace the reduced Flutter `icudtl.dat` file with the full `//third_party/icu/common/icudtl.dat` file.

I also see similar line breaks applied if I render the example text as HTML with Chrome using the default `word-break: normal` style.

To get the requested behavior Flutter and SkParagraph would need to implement an option similar to `word-break: keep-all`.

An app could potentially work around this by inserting zero width joiner characters (`U+200D`) between any characters where line breaking should be prohibited.

I tried transforming the example text to insert a ZWJ between any pair of non-whitespace characters:
```
replaceAllMapped(RegExp(r'(\S)(?=\S)'), (m) => '${m[1]}\u200D')
```
With that change the line breaking results look similar to the behavior of `keep-all`.

**Comment by justinmc** [comment]
I've created a Skia bug here: https://bugs.chromium.org/p/skia/issues/detail?id=13723

**Comment by LongCatIsLooong** [comment]
Looks like it's been fixed upstream? [commit](https://github.com/unicode-org/icu/commit/05dc2ac924a0acd3f9a7ca65e8a6078f8f62d299), [issue](https://unicode-org.atlassian.net/browse/ICU-22119).

**Comment by KOSNOWMAN** [comment]
Can I use this package with RichText-TextSpan or Markdown, MarkdownBody ?

**Comment by danagbemava-nc** [comment]
This seems to be occurring in recent versions of flutter. 

Labeling for further investigation. 

<img width="300" alt="Screenshot 2023-03-17 at 09 54 43" src="https://user-images.githubusercontent.com/88313112/225872053-3e0fcd43-cc2b-430f-aa09-9be64693704b.png">

<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: const Center(
        child: Text(
            '조선시대의 인구 조사에 따르면 조선의 인구는 대체로 700만 명을 넘지 못했다. 조세와 부역 등을 피하려고 호구조사를 기피하는 등 여러 가지 요인으로 40% 가까이 누락되었을 것으로 추측되고'),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-9.0.pre.32, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-9.0.pre.32 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53dfd23b04 (4 hours ago), 2023-03-17 01:59:19 -0400
    • Engine revision d9e65441ea
    • Dart version 3.0.0 (build 3.0.0-339.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by TykanN** [comment]
This issue should be fixed ASAP.
it's critical to UX of Korean speaker. also CJK characters..

https://bugs.chromium.org/p/skia/issues/detail?id=13723
This Skia bug issue was reported almost a year ago. There isn't any action further more.
Skia is maintained by Google.. plz communicate to respond as quickly as possible.

**Comment by justinmc** [comment]
@LongCatIsLooong Any idea why https://github.com/unicode-org/icu/commit/05dc2ac924a0acd3f9a7ca65e8a6078f8f62d299 didn't fix this for us?

**Comment by dfdgsdfg** [comment]
@dohuon Could you make this to package and release on pub.dev?

In my research, to improve CJK (Chinese, Japanese, Korean) word breaking, it's necessary to update the underlying ICU (International Components for Unicode) native library.

https://github.com/flutter/flutter/issues/19584#issuecomment-1235005686

Before that, it'll be very useful to Korean developers and users.
