### ISSUE TITLE
TextField not rendering text

### ISSUE THREAD

**Issue by SuperMarcomen** [flutter/flutter#59897]
I am having a weird problem with Flutter. I have two TextField where the user can input some text that I will then save in a database. The app is working fine on the emulator, but on my phone I can't use the TextField more than once. I will explain better: I export the app as an APK and then I installed it on my phone. I use the TextField and the work fine, then I change widget and, when I come back, I can't write anymore. From my keyboard it seems that I am writing but it not displayed on the screen. There is only the "hint text" and it wont go away. If I run the app trough USB-Debug it's even worse: in this mode I can type in the TextField as many time as I want but, for some strange reason, the app will not save the data in the database.

```
C:\Users\marco\AndroidStudioProjects\vocabulary_app>flutter run --verbose
[ +147 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +283 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ab68721a5da013dff6a08854bdba5e1f3206f9cf
[   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +534 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.19.0-5.0.pre
           1.20.0-0.0.pre
           1.20.0-1.0.pre
[  +21 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +247 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +241 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +297 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
 +244 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master

[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +211 ms] List of devices attached
                    emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:4
[   +8 ms] C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +227 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +25 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +155 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +7 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +3 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +11 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.1\
[  +94 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +3 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +9 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.1\
[  +68 ms] Generating C:\Users\marco\AndroidStudioProjects\vocabulary_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +107 ms] ro.hardware = ranchu
[  +34 ms] Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +45 ms] Starting incremental build...
[   +4 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +5 ms] Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\marco\AppData\Local\Temp\flutter_tools.5ebfdd3d\flutter_tool.45d17dd1\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill.track.dill
[  +15 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[ +109 ms] Exit code 0 from: C:\Users\marco\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="marcodemartino.it.vocabularyapp" (Raw: "marcodemartino.it.vocabularyapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=19)
                 A: android:label(0x01010001)="vocabularyapp" (Raw: "vocabularyapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=24)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="marcodemartino.it.vocabularyapp.MainActivity" (Raw: "marcodemartino.it.vocabularyapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=48)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=52)
                     E: action (line=53)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=55)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=62)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +8 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +203 ms] Exit code 0 from: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           06-19 22:59:03.976 I/GnssLocationProvider( 1985): WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@e5d385c)
[ +268 ms] <- compile package:vocabularyapp/main.dart
[ +121 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +219 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.6-6198805
                    Installed as C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +194 ms] Building APK
[  +27 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from C:\Users\marco\AndroidStudioProjects\vocabulary_app\android\gradlew.bat.
[   +2 ms] C:\Users\marco\AndroidStudioProjects\vocabulary_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +11 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +196 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: [C:\Users\marco\AndroidStudioProjects\vocabulary_app\android/] C:\Users\marco\AndroidStudioProjects\vocabulary_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\marco\AndroidStudioProjects\vocabulary_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+4931 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [ +124 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +285 ms] [ +308 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] ab68721a5da013dff6a08854bdba5e1f3206f9cf
[   +1 ms] [        ] executing: [C:\flutter/] git tag --contains HEAD
[ +597 ms] [ +546 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] [        ] 1.19.0-5.0.pre
[   +1 ms]            1.20.0-0.0.pre
[   +1 ms]            1.20.0-1.0.pre
[   +2 ms] [  +15 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +192 ms] [ +257 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] [        ] origin/master
[   +2 ms] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +294 ms] [ +249 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[ +298 ms] [ +307 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +300 ms] [ +272 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] master
[   +1 ms] [  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] [  +35 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [  +87 ms] Initializing file store
[  +64 ms] [  +30 ms] Done initializing file store
[   +1 ms] [  +57 ms] Skipping target: gen_localizations
[+1098 ms] [+1112 ms] Skipping target: kernel_snapshot
[ +400 ms] [ +336 ms] Skipping target: debug_android_application
[   +3 ms] [   +1 ms] Persisting file store
[   +2 ms] [  +12 ms] Done persisting file store
[   +2 ms] [   +8 ms] build succeeded.
[   +1 ms] [  +15 ms] "flutter assemble" took 1.725ms.
[   +4 ms] [   +4 ms] ensureAnalyticsSent: 0ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[   +1 ms] [   +3 ms] exiting with code 0
[ +281 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :path_provider:preBuild UP-TO-DATE
[   +1 ms] > Task :path_provider:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :sqflite:preBuild UP-TO-DATE
[   +5 ms] > Task :sqflite:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :path_provider:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :sqflite:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +6 ms] > Task :app:cleanMergeDebugAssets
[  +72 ms] > Task :path_provider:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :sqflite:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +4 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :path_provider:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :path_provider:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :path_provider:packageDebugAssets UP-TO-DATE
[   +2 ms] > Task :sqflite:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :sqflite:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :sqflite:generateDebugAssets UP-TO-DATE
[  +74 ms] > Task :sqflite:packageDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +498 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :path_provider:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :path_provider:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :path_provider:generateDebugResources UP-TO-DATE
[   +2 ms] > Task :path_provider:packageDebugResources UP-TO-DATE
[   +1 ms] > Task :sqflite:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :sqflite:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :sqflite:generateDebugResources UP-TO-DATE
[  +84 ms] > Task :sqflite:packageDebugResources UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :path_provider:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :path_provider:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :sqflite:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :sqflite:processDebugManifest UP-TO-DATE
[ +191 ms] > Task :app:processDebugManifest
[   +2 ms] > Task :path_provider:parseDebugLibraryResources UP-TO-DATE
[   +2 ms] > Task :path_provider:generateDebugRFile UP-TO-DATE
[   +1 ms] > Task :sqflite:parseDebugLibraryResources UP-TO-DATE
[   +1 ms] > Task :sqflite:generateDebugRFile UP-TO-DATE
[ +992 ms] > Task :app:processDebugResources
[   +2 ms] > Task :path_provider:generateDebugBuildConfig UP-TO-DATE
[  +97 ms] > Task :path_provider:javaPreCompileDebug UP-TO-DATE
[   +2 ms] > Task :path_provider:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :path_provider:bundleLibCompileDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :sqflite:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :sqflite:bundleLibCompileDebug UP-TO-DATE
[+1191 ms] > Task :app:compileDebugKotlin
[   +2 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :path_provider:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :path_provider:bundleLibResDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:processDebugJavaRes NO-SOURCE
[  +92 ms] > Task :sqflite:bundleLibResDebug UP-TO-DATE
[   +2 ms] > Task :path_provider:bundleLibRuntimeDebug UP-TO-DATE
[   +1 ms] > Task :path_provider:createFullJarDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:bundleLibRuntimeDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:createFullJarDebug UP-TO-DATE
[  +93 ms] > Task :app:javaPreCompileDebug
[ +501 ms] > Task :app:compileDebugJavaWithJavac
[   +7 ms] > Task :app:compileDebugSources
[  +92 ms] > Task :app:checkDebugDuplicateClasses
[ +598 ms] > Task :app:transformClassesWithDexBuilderForDebug
[   +2 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +1 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeDebugJniLibFolders UP-TO-DATE
[  +93 ms] > Task :path_provider:mergeDebugNativeLibs UP-TO-DATE
[   +2 ms] > Task :path_provider:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :path_provider:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:mergeDebugJniLibFolders UP-TO-DATE
[   +1 ms] > Task :sqflite:mergeDebugNativeLibs UP-TO-DATE
[   +1 ms] > Task :sqflite:stripDebugDebugSymbols UP-TO-DATE
[   +2 ms] > Task :sqflite:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[  +89 ms] > Task :path_provider:extractDebugAnnotations UP-TO-DATE
[   +3 ms] > Task :path_provider:mergeDebugGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeDebugConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :path_provider:prepareLintJarForPublish UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeDebugJavaResource UP-TO-DATE
[   +2 ms] > Task :path_provider:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[   +2 ms] > Task :path_provider:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :path_provider:bundleDebugAar UP-TO-DATE
[   +1 ms] > Task :path_provider:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :path_provider:assembleDebug UP-TO-DATE
[   +6 ms] > Task :sqflite:extractDebugAnnotations UP-TO-DATE
[   +1 ms] > Task :sqflite:mergeDebugGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :sqflite:mergeDebugConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :sqflite:prepareLintJarForPublish UP-TO-DATE
[  +71 ms] > Task :sqflite:mergeDebugJavaResource UP-TO-DATE
[   +2 ms] > Task :sqflite:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[   +3 ms] > Task :sqflite:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:bundleDebugAar UP-TO-DATE
[   +1 ms] > Task :sqflite:compileDebugSources UP-TO-DATE
[   +4 ms] > Task :sqflite:assembleDebug UP-TO-DATE
[   +1 ms] > Task :app:desugarDebugFileDependencies
[  +85 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[  +98 ms] > Task :app:mergeDebugJavaResource
[ +400 ms] > Task :app:mergeDebugNativeLibs
[ +400 ms] Unable to strip library 'C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\intermediates\merged_native_libs\debug\out\lib\x86\libflutter.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
[ +100 ms] > Task :app:stripDebugDebugSymbols
[   +2 ms] Compatible side by side NDK version was not found.
[   +1 ms] Unable to strip library 'C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\intermediates\merged_native_libs\debug\out\lib\x86_64\libflutter.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
[   +1 ms] > Task :app:mergeDexDebug
[+2093 ms] > Task :app:packageDebug
[ +299 ms] > Task :app:assembleDebug
[   +2 ms] BUILD SUCCESSFUL in 17s
[   +2 ms] 87 actionable tasks: 18 executed, 69 up-to-date
[ +734 ms] Running Gradle task 'assembleDebug'... (completed in 18,5s)
[  +45 ms] calculateSha: LocalDirectory: 'C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\outputs\flutter-apk'/app.apk
[  +63 ms] calculateSha: reading file took 62us
[ +415 ms] calculateSha: computing sha took 414us
[  +16 ms] ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
[   +7 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[ +119 ms] Exit code 0 from: C:\Users\marco\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="marcodemartino.it.vocabularyapp" (Raw: "marcodemartino.it.vocabularyapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="vocabularyapp" (Raw: "vocabularyapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="marcodemartino.it.vocabularyapp.MainActivity" (Raw: "marcodemartino.it.vocabularyapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=36)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=46)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=50)
                     E: action (line=51)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=53)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=60)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on AOSP on IA Emulator.
[   +4 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop marcodemartino.it.vocabularyapp
[ +219 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages marcodemartino.it.vocabularyapp
[ +210 ms] package:marcodemartino.it.vocabularyapp
[   +4 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat /data/local/tmp/sky.marcodemartino.it.vocabularyapp.sha1
[ +203 ms] e5631c42765673ddce2ca7a181f4b847d52dcf5a
[   +2 ms] Installing APK.
[   +3 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +189 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.6-6198805
                    Installed as C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +187 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +2 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install -t -r C:\Users\marco\AndroidStudioProjects\vocabulary_app\build\app\outputs\flutter-apk\app.apk
[+1721 ms] Performing Streamed Install
                    Success
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 1,7s)
[   +3 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell echo -n 6dc12a81c442c00843594b3e10208babb408a5b5 > /data/local/tmp/sky.marcodemartino.it.vocabularyapp.sha1
[ +205 ms] AOSP on IA Emulator startApp
[   +4 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true
--ez verify-entry-points true marcodemartino.it.vocabularyapp/marcodemartino.it.vocabularyapp.MainActivity
[ +224 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=marcodemartino.it.vocabularyapp/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1042 ms] Observatory URL on device: http://127.0.0.1:36720/ibmSi4Spm6o=/
[   +3 ms] executing: C:\Users\marco\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:36720
[ +216 ms] 65295
[   +1 ms] Forwarded host port 65295 to device port 36720 for Observatory
[   +6 ms] Caching compiled dill
[  +34 ms] Connecting to service protocol: http://127.0.0.1:65295/ibmSi4Spm6o=/
[ +478 ms] Successfully connected to service protocol: http://127.0.0.1:65295/ibmSi4Spm6o=/
[   +2 ms] Waiting for AOSP on IA Emulator to report its views...
[  +11 ms] Waiting for AOSP on IA Emulator to report its views... (completed in 9ms)
[  +13 ms] DevFS: Creating new filesystem on the device (null)
[  +31 ms] DevFS: Created new filesystem on the device (file:///data/user/0/marcodemartino.it.vocabularyapp/code_cache/vocabulary_appPGTXHN/vocabulary_app/)
[   +4 ms] Updating assets
[ +157 ms] Syncing files to device AOSP on IA Emulator...
[   +3 ms] Scanning asset files
[   +4 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:vocabularyapp/main.dart f77db3ab-8a17-4164-ab6c-6f2610f01499
[        ] <- f77db3ab-8a17-4164-ab6c-6f2610f01499
[   +2 ms] D/EGL_emulation(10697): eglMakeCurrent: 0xd4f832a0: ver 3 1 (tinfo 0xe61e0740)
[   +1 ms] D/eglCodecCommon(10697): setVertexArrayObject: set vao to 0 (0) 1 0
[ +259 ms] Updating files
[ +113 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device AOSP on IA Emulator... (completed in 389ms)
[   +1 ms] Synced 0.9MB.
[   +1 ms] <- accept
[   +6 ms] Connected to _flutterView/0xe4f08310.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. ���
[   +2 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:65295/ibmSi4Spm6o=/
[  +26 ms] I/flutter (10697): 0
[+2664 ms] I/flutter (10697): Instance of 'Future<List<Word>>'
[+3433 ms] W/IInputConnectionWrapper(10697): beginBatchEdit on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(10697): getTextBeforeCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(10697): getTextAfterCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(10697): getSelectedText on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(10697): endBatchEdit on inactive InputConnection
[+6493 ms] I/flutter (10697): Instance of 'Future<List<Word>>'

```

```
C:\Users\marco\AndroidStudioProjects\vocabulary_app>flutter analyze
Analyzing vocabulary_app...

   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: InsertWord._editing, InsertWord._originalWord, InsertWord.screenWidth, InsertWord.screenHeight - lib\insert_word.dart:6:7
          - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: WordContainer.word - lib\word_manager.dart:99:7 - must_be_immutable

2 issues found. (ran in 9.8s)

```

```
C:\Users\marco\AndroidStudioProjects\vocabulary_app>flutter doctor -v
[√] Flutter (Channel master, 1.19.0-5.0.pre, on Microsoft Windows [Versione 10.0.18363.900], locale it-IT)
    • Flutter version 1.19.0-5.0.pre at C:\flutter
    • Framework revision ab68721a5d (2 weeks ago), 2020-06-05 14:02:07 -0700
    • Engine revision e87a05fbba
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 62903873df)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\marco\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30128.74
    • Windows 10 SDK version 10.0.16299.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.5731

[√] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    • Windows             • Windows       • windows-x64 • Microsoft Windows [Versione 10.0.18363.900]

! Doctor found issues in 1 category.

```

(All the commands were executed on my computer while my phone was disconnected)
[bug.zip](https://github.com/flutter/flutter/files/4806971/bug.zip)

**Comment by Chetan-Goyal** [comment]
What did you mean by "I change widget" ?

**Comment by Chetan-Goyal** [comment]
Earlier, I have also faced similar issue when i was using a TextField and a drop down menu.

To solve this, you have to use a function inside `onChanged:` to save the value to some variable(let's say _name here) every time when it is changed with **default value as empty string**. 
Also, You have to use another named argument, `controller: TextEditingController(text: _name)` to set the default text as the previous saved data.
Do the same thing with other TextField also with another variable to store the data of this TextField.

I hope it will work for you. If you have any queries or doubt, feel free to ask.  :)

**Comment by SuperMarcomen** [comment]
Thank you for your reply, but unfortunately, it still doesn't work. The second time I load this StatelessWidget I can click on the first TextField (There is two) and start typing (I can see that I'm typing because I can see suggestions on my keyboard) but it is not displayed on the TextField, there is only the hint text. As soon as I click on this TextField I can't do literally anything: I can't click on the other TextField, I can't click on the button that's on the StatelessWidget and I can't even go back neither with the IconButton nor with the function "back" of my phone.

The weirdest thing is that it works with no problem on the emulator. And what's maybe even weirder is that the app is even more broken if I install it trough debug usb (I have already described that problem).

**Comment by Chetan-Goyal** [comment]
You have to make it `StatefulWidget` and in `onChanged:` , you have to use `setState` to  set the value of the variable storing the data(initially empty string) and using controller, you can set the default text as the value stored.
You have to follow this same approach with other textField also.

**Comment by SuperMarcomen** [comment]
Can you please give me an example of what to do in `onChanged:`? I didn't get it.

**Comment by Chetan-Goyal** [comment]
Sure. lemme make a short script for it.

**Comment by Chetan-Goyal** [comment]
@SuperMarcomen I fixed this issue. For this, we can't use `onChanged:` but `onSubmitted:` has to be used. `onChanged:` worked for me though when i combined textField and dropdownmenu. 
Here is the working code, https://gist.github.com/Chetan-Goyal/b5852584565b932446afcfd4ddd710d3

the data of textField is stored in `nameOne` and `nameTwo`.

**Comment by SuperMarcomen** [comment]
I have made your changes but the text still isn't displayed in the TextField

**Comment by SuperMarcomen** [comment]
Here is a video showing what's happening (It's from an old version of the app, but what's happening is the same) and here is the code.
https://youtu.be/D3JcGthqT8A
https://github.com/SuperMarcomen/vocabulary_app

**Comment by SuperMarcomen** [comment]
Does anyone know how to fix this issue?

**Comment by Chetan-Goyal** [comment]
I am not being able to reproduce the issue as shown in the above video. I am getting an alert box with text, `Articolo invalido` with same input data.
I am using my device having android version 9 via ADB .

**Comment by SuperMarcomen** [comment]
The only valid inputs (As you can see from the code) for the first TextField are: "der", "die" and "das" (German articles).

**Comment by VladyslavBondarenko** [comment]
Hi @SuperMarcomen 
This is not an issue with TextField. You can notice that entire UI is blocked after saving first word. And it’s blocked not in insert_word page but in main page. Since [you use `Navigator.push`](https://github.com/SuperMarcomen/vocabulary_app/blob/master/lib/main.dart#L69) (not `Navigator.pushReplacement`), the main page reloads as well under word manager.
When you have one word in the list [this loop](https://github.com/SuperMarcomen/vocabulary_app/blob/master/lib/main.dart#L160) goes in cycles (you can see it with debugger). Change condition to `while (words.length > 1 && _oldWord != null && _oldWord.word == word.word)`.
Add `if (words == null) return null;` after [this line](https://github.com/SuperMarcomen/vocabulary_app/blob/master/lib/main.dart#L152), because later it’ll try to take length of null.
In insert word page replace `onSubmitted` with `onChanged`.
Can you confirm that it solves the problem?

**Comment by SuperMarcomen** [comment]
Thank you so much @VladyslavBondarenko, I can't believe you actually took the time to review the entire code of my app. It is finally working properly but I have a final question: why was it happening only on my Android device and not on the ADB?
The main issue was the while loop with no exit condition, but why did it work on the emulator?

**Comment by VladyslavBondarenko** [comment]
@SuperMarcomen I don't know how could it work with emulator, on Android 10 (API 29) (emulator) and iOS 13.5 simulator I had the same result as with real Android 9 device with current master and current beta (which is closed to version used by you).
Anyway closing as solved)
