### ISSUE TITLE
flutter run fails Xcode 12: fruitstrap_.py, in connect_command process = lldb.target.ConnectRemote(listener, connect_url, None, error) AttributeError: 'NoneType' object has no attribute 'ConnectRemote'

### ISSUE THREAD

**Issue by Seaony** [flutter/flutter#60072]
iOS: 14.0 beta

Flutter: 
```shell
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (5 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

I try to run 'shuttle run' and the result is

```shell
Launching lib/main.dart on Seaony 的iPhone in debug mode...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: ZSLQ5LJNGF
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        12.1s
Xcode build done.                                           25.5s
Traceback (most recent call last):                                      
  File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'      
Traceback (most recent call last):                                      
  File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'            
Traceback (most recent call last):                                      
  File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 74, in safequit_command
    process = lldb.target.process                                       
AttributeError: 'NoneType' object has no attribute 'process'            
Installing and launching...                                            ⣷
```

**Comment by Seaony** [comment]
It is worth mentioning that I am running on the real machine，Xcode has also been upgraded to the latest version

**Comment by Seaony** [comment]
flutter doctor -v result:

```shell
[✓] Flutter (Channel stable, v1.17.4, on macOS 10.16 20A4299v, locale zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/seaony/flutter
    • Framework revision 1ad9baa8b9 (5 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/seaony/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A6159
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Seaony 的iPhone             • 00008030-001E31660A82802E            • ios • iOS 14.0
    • iPhone SE (2nd generation) • 7FF9EC86-68FD-4DD6-BADF-335439BB426E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by Seaony** [comment]
it can work normally on the simulator

**Comment by JagandeepBrar** [comment]
Getting the exact same issue, physical device (iPhone 11 Pro) running iOS 14, Xcode 12.0.

```bash
Traceback (most recent call last):
  File "/tmp/6B9F6E42-9455-4B8E-A1F4-5D3BA42B15B4/fruitstrap_00008030_001839991150802E.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'
Traceback (most recent call last):
  File "/tmp/6B9F6E42-9455-4B8E-A1F4-5D3BA42B15B4/fruitstrap_00008030_001839991150802E.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'
Traceback (most recent call last):
  File "/tmp/6B9F6E42-9455-4B8E-A1F4-5D3BA42B15B4/fruitstrap_00008030_001839991150802E.py", line 74, in safequit_command
    process = lldb.target.process
AttributeError: 'NoneType' object has no attribute 'process'
```

**Comment by tomalabaster** [comment]
The same is happening on the master channel (1.20.0-1.0.pre.156) with the same versions and device as @JagandeepBrar 

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.156, on macOS 10.16 20A4299v, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.156 at /Users/tomalabaster/flutter
    • Framework revision 8c3b826ebd (5 hours ago), 2020-06-23 15:19:57 +1200
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tomalabaster/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A6159
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0
```

**Comment by EliasDeuss** [comment]
Might have to do with #60043 (xcode 12 issue)

**Comment by razvangeangu** [comment]
Same issue here

```
Xcode build done.                                           48.3s
Installing and launching...
Traceback (most recent call last):
  File "/tmp/XXXX/fruitstrap_00008020_001C050A3AE1002E.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'
Traceback (most recent call last):
  File "/tmp/XXXX/fruitstrap_00008020_001C050A3AE1002E.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'
Traceback (most recent call last):
  File "/tmp/XXXX/fruitstrap_00008020_001C050A3AE1002E.py", line 74, in safequit_command
    process = lldb.target.process
AttributeError: 'NoneType' object has no attribute 'process'
Exited
```

**Comment by jmagman** [comment]
Reproduces with Xcode 12 beta 1 on Catalina.  You can add a +1 if you're seeing this instead of adding "me too" comments.
$ xcrun lldb --version                                                                                                         
lldb-1200.0.18.8
Apple Swift version 5.3 (swiftlang-1200.0.16.9 clang-1200.0.22.5)
$ xcrun python --version
Python 2.7.16

https://github.com/ios-control/ios-deploy/blob/2306cc4a42e88ed0ceb906855c36b450d8a58400/src/scripts/lldb.py#L25

**Comment by jmagman** [comment]
Workaround is to `flutter run` to a simulator, or open `ios/Runner.xcworkspace` in Xcode and deploy to a real iOS device from there.

**Comment by razvangeangu** [comment]
Probably relevant is that DTDeviceKit returns null

```
2020-06-23 21:36:48.293 xcdevice[40516:215998]  DTDeviceKit: deviceType from SECRET_ID was NULL
2020-06-23 21:36:48.299 xcdevice[40516:215913] [MT] DTDeviceKit: deviceType from SECRET_ID was NULL
2020-06-23 21:36:49.990 xcdevice[40516:215984]  DVTAssertions: Warning in
/Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17125/DTDeviceKitBase/DTDeviceKitBase_Utilities.m:285
Details:  expected deviceType to be NSString, but was (null) ((null))
Function: NSString *DTDKUTIForDeviceType(NSString *__strong, NSString *__strong, NSString *__strong)
Thread:   <NSThread: 0x7fac306049c0>{number = 2, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2020-06-23 21:36:49.991 xcdevice[40516:215984]  DTDeviceKit: deviceType from SECRET_ID was NULL
2020-06-23 21:36:49.991 xcdevice[40516:215984]  DTDeviceKit: deviceType from SECRET_ID was NULL
```

**Comment by ZaurBilalov** [comment]
Same issue here. Flutter doctor is attached. I am using Catalina, but Xcode is updated to 12. I have to both build and deploy through Runner on Xcode. Flutter command can't build, run an already built package, nor can it attach to a device. 

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E266, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[!] Android Studio (not installed)
[✓] VS Code (version 1.46.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.`

**Comment by jmagman** [comment]
Xcode 12 Beta 2 didn't help.
I believe this was fixed with https://github.com/ios-control/ios-deploy/pull/464.

**Comment by ZaurBilalov** [comment]
> Xcode 12 Beta 2 didn't help.
> 
> I believe this was fixed with https://github.com/ios-control/ios-deploy/pull/464.

The new update on July 1st did not fix this either. I’m still getting the same error.

**Comment by gabebear** [comment]
I'll get a new beta of ios-deploy cut today with the Xcode12 fix in it [ios-deploy#464](https://github.com/ios-control/ios-deploy/pull/464). There are quite a new features since the last official release.

**Comment by SFrost007** [comment]
I've tried reinstalling the HEAD version of ios-deploy from brew (double checked and the commit hash is the latest, including that fix), which rebuilt from source with Xcode 12b2. This still didn't fix the issue - does flutter use its own bundled version of ios-deploy rather than the system version?

**Comment by gabebear** [comment]
I'm fairly certain Flutter does bundle it's own ios-deploy. The ios-deploy executable is a completely stand-alone binary(single binary file) so you should be able to find it and swap it.

I published a new beta version at https://github.com/ios-control/ios-deploy/releases/tag/1.11.0-beta.1

**Comment by christopherfujino** [comment]
> I'm fairly certain Flutter does bundle its own ios-deploy. The ios-deploy executable is a completely stand-alone binary file(it has no data files or library dependencies) so you should be able to find it and swap it.
> 
> I published a new beta version at https://github.com/ios-control/ios-deploy/releases/tag/1.11.0-beta.1

Thanks @gabebear! I'm working on updating our bundled version at the moment, but if you want to swap the upstream build, just place it in `//flutter/bin/cache/artifacts/ios-deploy/ios-deploy`.

**Comment by softmarshmallow** [comment]
> > I'm fairly certain Flutter does bundle its own ios-deploy. The ios-deploy executable is a completely stand-alone binary file(it has no data files or library dependencies) so you should be able to find it and swap it.
> > I published a new beta version at https://github.com/ios-control/ios-deploy/releases/tag/1.11.0-beta.1
> 
> Thanks @gabebear! I'm working on updating our bundled version at the moment, but if you want to swap the upstream build, just place it in `//flutter/bin/cache/artifacts/ios-deploy/ios-deploy`.

whre can we find ios-deploy file?
brew install -> ios-deploy--git folder/(where?)

**Comment by pnavarro1991** [comment]
Hi, everyone, it just happened to me, and what worked for me was first to check the flutter channel in which I was the one I found, which in my case was 1.17.5 stable, so I switch to the master channel and update flutter with this. I stop making the error and you can run my app from a device

From terminal runs:

$ flutter channel
Flutter channels:
  master
  dev
  beta
* stable

$ flutter channel master
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:  + 9b9b543d9...a2bde82fb beta             -> origin/beta  (forced update)
git:  * [new branch]          dds_reland_take6 -> origin/dds_reland_take6
git:    15a28159b..f25bd9c55  dev              -> origin/dev
git:  * [new branch]          dnfield-patch-1  -> origin/dnfield-patch-1
git:  * [new branch]          feature-bottomNavTextScaling -> origin/feature-bottomNavTextScaling
git:    0bffc8a39..0af027f80  flutter-1.20-candidate.3 -> origin/flutter-1.20-candidate.3
git:  * [new branch]          flutter-1.20-candidate.3.renyou_experiment -> origin/flutter-1.20-candidate.3.renyou_experiment
git:  * [new branch]          flutter-1.20-candidate.4 -> origin/flutter-1.20-candidate.4
git:  * [new branch]          flutter-1.20-candidate.5 -> origin/flutter-1.20-candidate.5
git:  * [new branch]          flutter-1.20-candidate.6 -> origin/flutter-1.20-candidate.6
git:  * [new branch]          flutter-1.20-candidate.7 -> origin/flutter-1.20-candidate.7
git:  * [new branch]          flutter-1.20-candidate.8 -> origin/flutter-1.20-candidate.8
git:  * [new branch]          flutter-1.21-candidate.0 -> origin/flutter-1.21-candidate.0
git:  * [new branch]          flutter-1.21-candidate.1 -> origin/flutter-1.21-candidate.1
git:  * [new branch]          flutter-1.21-candidate.2 -> origin/flutter-1.21-candidate.2
git:  * [new branch]          flutter-1.21-candidate.3 -> origin/flutter-1.21-candidate.3
git:  * [new branch]          flutter-1.21-candidate.4 -> origin/flutter-1.21-candidate.4
git:  * [new branch]          flutter-1.21-candidate.5 -> origin/flutter-1.21-candidate.5
git:    3f4f91532..fc72a5f10  master           -> origin/master
git:  * [new branch]          revert-61485-issues/59316-intrinsics -> origin/revert-61485-issues/59316-intrinsics
git:  * [new tag]             1.19.0-4.3.pre   -> 1.19.0-4.3.pre
git:  * [new tag]             1.20.0-3.0.pre   -> 1.20.0-3.0.pre
git:  * [new tag]             1.20.0-7.2.pre   -> 1.20.0-7.2.pre
git:  * [new tag]             1.21.0-1.0.pre   -> 1.21.0-1.0.pre
git:  * [new tag]             1.21.0-5.0.pre   -> 1.21.0-5.0.pre
git:  * [new tag]             1.20.0-7.0.pre   -> 1.20.0-7.0.pre
git:  * [new tag]             1.20.0-7.1.pre   -> 1.20.0-7.1.pre
git: Switched to a new branch 'master'
git: Branch 'master' set up to track remote branch 'master' from 'origin'.
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

$ flutter upgrade
Downloading Dart SDK from Flutter engine 4d720dd9e56ff5d008ed8cafff3a45676f403c23...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255M  100  255M    0     0  5830k      0  0:00:44  0:00:44 --:--:-- 5717k
Building flutter tool...
Flutter is already up to date on channel master
Flutter 1.21.0-6.0.pre.15 • channel master • https://github.com/flutter/flutter.git
Framework • revision fc72a5f105 (6 minutes ago) • 2020-07-23 14:17:27 -0700
Engine • revision 4d720dd9e5
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev fcd1c5b61a)

**Comment by jmagman** [comment]
Closing, resolved with https://github.com/flutter/flutter/pull/61983.

**Comment by softmarshmallow** [comment]
still happens on flutter master 1.20.1

**Comment by jmagman** [comment]
@softmarshmallow 1.20.1 is stable, not master.  https://github.com/flutter/flutter/pull/61983 is available in 1.21.0-5.0.pre, which at the moment is available in the [dev channel](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos).

**Comment by softmarshmallow** [comment]
@jmagman might be off topic, but dies dev support web and desktop builds?

**Comment by jmagman** [comment]
@softmarshmallow Yes, that's off topic and not my area of expertise.  😃

**Comment by markathomas** [comment]
is there any plan to downport this fix to the 1.17.x branch?  Requiring a full Flutter upgrade to support Xcode 12 seems presumptuous

**Comment by jmagman** [comment]
@markathomas https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
> Note that we only hotfix the latest version --- if you see bugs on older versions of the stable channel, please consider moving to the latest stable channel version.

**Comment by izaiasemjr** [comment]
I had the same probleme here. To works for me, I just applied changes in ios-deploy (https://github.com/ios-control/ios-deploy/releases/tag/1.11.0-beta.1)  and I updated flutter typing  flutter upgrade.  After, I just typed flutter clean && flutter run.

**Comment by shinriyo** [comment]
How did you install Xcode 12 then?
I installed Xcode 12 today.

`1.22.0-12.0.pre` works fine.

**Comment by gabebear** [comment]
You need the ios-deploy 1.11.2 for the released version of iOS14. https://github.com/ios-control/ios-deploy/releases/tag/1.11.2

**Comment by zhang52104** [comment]
After upgrade the ios - deploy the latest version, the file "/ usr/local/lib/node_modules/ios - deploy/build/Release/ios - deploy" replace "/ flutter/bin/cache/artifacts/ios - deploy"

**Comment by fsresponser** [comment]
flutter upgrade(1.20.3 - 1.20.4), then flutter clean and build works for me.

**Comment by jfk23** [comment]
> flutter upgrade(1.20.3 - 1.20.4), then flutter clean and build works for me.

Thanks! works for me.

**Comment by DhavalRKansara** [comment]
I have upgraded the ios-deploy version still getting below error.

```
Traceback (most recent call last):
  File "/tmp/76F3C24C-B608-4FE4-8725-C06FCD1E5269/fruitstrap_a8aaa158c9abce75fda523321c5535537c3eb9c2.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'
Traceback (most recent call last):
  File "/tmp/76F3C24C-B608-4FE4-8725-C06FCD1E5269/fruitstrap_a8aaa158c9abce75fda523321c5535537c3eb9c2.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'
Traceback (most recent call last):
  File "/tmp/76F3C24C-B608-4FE4-8725-C06FCD1E5269/fruitstrap_a8aaa158c9abce75fda523321c5535537c3eb9c2.py", line 74, in safequit_command
    process = lldb.target.process
AttributeError: 'NoneType' object has no attribute 'process'
```

**Comment by gabebear** [comment]
@DhavalRKansara You might do better opening a new bug. I haven't seen that exact failure before.

**Comment by shinriyo** [comment]
＠DhavalRKansara What version?

**Comment by DhavalRKansara** [comment]
> ＠DhavalRKansara What version?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.7 19H2, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2020.2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by wafahas** [comment]
Traceback (most recent call last):
  File "/tmp/967547A4-192A-470E-BF72-1D8EABDC15F6/fruitstrap_9c6086a86c2a023f819111004411193c63f5a11f.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'
Traceback (most recent call last):
  File "/tmp/967547A4-192A-470E-BF72-1D8EABDC15F6/fruitstrap_9c6086a86c2a023f819111004411193c63f5a11f.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'
Traceback (most recent call last):
  File "/tmp/967547A4-192A-470E-BF72-1D8EABDC15F6/fruitstrap_9c6086a86c2a023f819111004411193c63f5a11f.py", line 74, in safequit_command
    process = lldb.target.process
AttributeError: 'NoneType' object has no attribute 'process'


i got this error what shall i do

**Comment by samariotorres** [comment]
if you have homebrew (you should)

brew install --HEAD ios-deploy

then flutter channel stable
flutter upgrade 
flutter clean
flutter run -d device

**Comment by wafahas** [comment]
thanks samariotorres it works well now

**Comment by jmagman** [comment]
You shouldn't need to run `brew install --HEAD ios-deploy`, it's distributed in Flutter.

**Comment by Dawnhan** [comment]
I had the same problem，but I  can't upgrade flutter ,how can I solve this problem?
