### ISSUE TITLE
Flutter Logo typeface is not on-brand

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#60539]
The text [is rendered in Roboto](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/painting/flutter_logo.dart#L268), yet this font is unavailable on certain platforms and is not the Product Sans font that is specified for the logotype.

I took a few screenshots:

FlutterLogo widget on iPhone (looks like font fallback to San Francisco, colors wrong)
![image](https://user-images.githubusercontent.com/2319867/86043948-40e80280-b9fe-11ea-9941-045db32297c6.png)

FlutterLogo widget on web (looks like font is Roboto, colors wrong):
![image](https://user-images.githubusercontent.com/2319867/86044021-5ceba400-b9fe-11ea-9664-6ffb2db31b3c.png)

Flutter logo in go/flutter-logo: 
![image](https://user-images.githubusercontent.com/2319867/86044088-77258200-b9fe-11ea-90e5-4864eac09844.png)

I think we need to convert it to vector art, rather than use random fonts that may or may not be present on a given device. 

Also see https://github.com/flutter/flutter/issues/16713, which addresses a separate issue relating to the color of the 'F' marque.

**Comment by goderbauer** [comment]
I am trying to figure out what the right colors for the 'F' are. Do we have a branding guide for that? Or should I just color-pick them from https://drive.google.com/corp/drive/folders/1yaaGcIdNkba6VYT4xIwbvuwhHXzcQYov?

Also, in the docs for the FlutterLogo widget we recommend alternative color schemes if the main blue one does not work: https://master-api.flutter.dev/flutter/painting/FlutterLogoDecoration/lightColor.html. Are those recommendations still accurate? I can't find any references elsewhere to those alternative color schemes.

**Comment by goderbauer** [comment]
The colors are getting corrected in this PR: https://github.com/flutter/flutter/pull/62052

**Comment by TahaTesser** [comment]
### iOS
![Simulator Screen Shot - iPhone 11 - 2020-09-25 at 19 47 02](https://user-images.githubusercontent.com/48603081/94278088-0bed3c80-ff68-11ea-8b9a-9c361a77a1e0.png)

### Android
![Screenshot_1601042755](https://user-images.githubusercontent.com/48603081/94278194-2a533800-ff68-11ea-8d05-2a0baeba7388.png)

### Web
![image](https://user-images.githubusercontent.com/48603081/94278267-3dfe9e80-ff68-11ea-9a70-cc0c130bcd5c.png)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: FlutterLogo(
            style: FlutterLogoStyle.horizontal,
            size: 300,
          ),
        ),
      ),
    );
  }
}

```

</details> 



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.359, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.359 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision db6e2d8aa5 (3 hours ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details>

**Comment by exaby73** [comment]
I can still reproduce this issue on `Master (3.7.0-2.0.pre.9)`. For me, the web one has a more bolder font on MacOS. Updating labels to reflect the same

#### MacOS
<img width="368" alt="macos" src="https://user-images.githubusercontent.com/50555895/205295701-e5ad2891-3fb2-4887-8284-8f8a3e49d101.png">

#### Web (MacOS)
<img width="350" alt="web" src="https://user-images.githubusercontent.com/50555895/205295707-10817292-6def-47a4-bda3-2c4aff5228b3.png">

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was able to reproduce the issue using the provided code sample on both the `stable (3.29.3)` and `master (3.32.0-1.0.pre.514)` channels.

| | Stable | Master |
| --- | --- | --- |
| Android | ![Image](https://github.com/user-attachments/assets/18349d0c-9fd6-45bb-9a63-d937c7ed8a3e) | ![Image](https://github.com/user-attachments/assets/2f3836cf-5ed9-4b68-a8a4-e61d937bd064) |
| iOS | ![Image](https://github.com/user-attachments/assets/afaef95f-187d-4a1b-8723-7219133824b3) | ![Image](https://github.com/user-attachments/assets/cd4bbe34-69f8-440f-8ebf-d31678d220eb) |
| macOS | <img width="912" alt="Image" src="https://github.com/user-attachments/assets/516119e4-4c3a-484a-a1e7-879cc0e8c10c" /> | <img width="912" alt="Image" src="https://github.com/user-attachments/assets/47f31eb7-6203-48a9-ac3c-ba7f899b78ca" /> |
| web | <img width="1512" alt="Image" src="https://github.com/user-attachments/assets/0a2262d6-880d-4a5a-aa17-d06f260e0397" /> | <img width="1512" alt="Image" src="https://github.com/user-attachments/assets/71df9792-0438-4dea-b6a8-4025e4449625" /> |

Host: Mac

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(title: Text('Material App Bar')),
        body: Center(
          child: FlutterLogo(style: FlutterLogoStyle.horizontal, size: 300),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.514) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.514, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,266ms]
    • Flutter version 3.32.0-1.0.pre.514 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 149ac49583 (3 hours ago), 2025-05-12 22:41:39 -0400
    • Engine revision 149ac49583
    • Dart version 3.9.0 (build 3.9.0-114.0.dev)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [784ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [434ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.100.0) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.6s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.93

[✓] Network resources [553ms]
    • All expected network resources are available.

• No issues found!
```

</details>
