### ISSUE TITLE
Use runZonedGuarded instead of runZoned

### ISSUE THREAD

**Issue by pachecofc** [flutter/flutter#60784]
According to the [Flutter docs](https://flutter.dev/docs/cookbook/maintenance/error-reporting#5-catch-and-report-dart-errors), "With Flutter 1.17 which includes Dart 2.8, use runZonedGuarded instead".

**Comment by iapicca** [comment]
Hi @pachecofc 
could you please describe in detail where `runZoned` has been used instead of `runZonedGuarded`
thank you

**Comment by pachecofc** [comment]
Hi @iapicca 
In the pub.dev sentry package [page](https://pub.dev/packages/sentry#-readme-tab-) there is a section called "tips to catching errors".
They are using `runZone` instead of `runZonedGuarded` in the example code.

Thank you for your attention.

**Comment by iapicca** [comment]
HI @pachecofc 
thank you for reporting this

**Comment by bruno-garcia** [comment]
The Sentry package readme was fixed in this PR: https://github.com/flutter/sentry/pull/55
But no release was done yet. We'll push some breaking changes on the next major release.

**Comment by vbabaria** [comment]
with flutter v1.20.1 and dart v.2.9, i still get following error and flutter project is unable to find "runZonedGuarded" - am i missing something?

lib/main.dart:13:3: Error: Method not found: 'runZonedGuarded'.
  runZonedGuarded(
  ^^^^^^^^^^^^^^^

**Comment by Roshan13046** [comment]
is the issue active? if yes, can I work on it?

**Comment by bruno-garcia** [comment]
The GA was last Thursday: https://github.com/getsentry/sentry-dart/releases
