### ISSUE TITLE
Flutter Web: Blank Page Output

### ISSUE THREAD

**Issue by Arjun3010** [flutter/flutter#61464]
I am new to flutter web. I am using the default counter program. But, I get blank page in chrome and there are no errors in chrome console and flutter console.
### flutter run -d chrome:
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
16,903ms (!)

### flutter run -d chrome -v
[ +219 ms] executing: [E:\Softwares\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +147 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ce55e42f2b6d1f174a4e6326bb19d4af971301be
[   +1 ms] executing: [E:\Softwares\flutter/] git tag --contains HEAD
[ +312 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] executing: [E:\Softwares\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +98 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[   +1 ms] 1.20.0-7.0.pre-80-gce55e42f2
[  +13 ms] executing: [E:\Softwares\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +115 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [E:\Softwares\flutter/] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +490 ms] executing: [E:\Softwares\flutter/] git rev-parse --abbrev-ref HEAD
[  +84 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +118 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +27 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: E:\Softwares\sdk\platform-tools\adb.exe devices -l
[ +149 ms] List of devices attached
[  +11 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+2018 ms] Generating E:\Personal_Project\attempt\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +208 ms] Launching lib\main.dart on Chrome in debug mode...
[ +222 ms] Updating assets
[+4835 ms] Syncing files to device Chrome...
[ +152 ms] Generating E:\Personal_Project\attempt\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +99 ms] <- reset
[  +12 ms] E:\Softwares\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
E:\Softwares\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root E:\Softwares\flutter\bin\cache\flutter_web_sdk/   
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill     
C:\Users\Arjun\AppData\Local\Temp\flutter_tools.291f60d8\flutter_tool.8885aaa0\app.dill --libraries-spec
file:///E:/Softwares/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions    
--enable-asserts --track-widget-creation --filesystem-root C:\Users\Arjun\AppData\Local\Temp\flutter_tools.291f60d8\flutter_tools.945f70a3
--filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform
file:///E:/Softwares/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +58 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+31558 ms] Syncing files to device Chrome... (completed in 31,867ms, longer than expected)
[   +1 ms] Synced 23.7MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+4734 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:57598/devtools/browser/5f326541-6e8b-445d-91e2-31c872b346f2

### flutter doctor -v
[√] Flutter (Channel master, 1.20.0-8.0.pre.80, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 1.20.0-8.0.pre.80 at E:\Softwares\flutter
    • Framework revision ce55e42f2b (5 hours ago), 2020-07-14 07:40:29 -0400
    • Engine revision 1e23309a38
    • Dart version 2.9.0 (build 2.9.0-21.0.dev f997d62a6d)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at E:\Softwares\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = E:\Softwares\sdk
    • Java binary at: E:\Softwares\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at E:\Softwares\Android
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 83.0.4103.116
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 83.0.478.61

Please see the issue and reply ASAP.....

**Comment by TahaTesser** [comment]
Hi @Arjun3010 
Can you execute `flutter run -d Chome`  and then blank window launches, go to top menu -> more tools -> Developer Tools or Control +  Shift + I  and take screenshot of `console tab`. It might have some error 
Thank you

**Comment by Arjun3010** [comment]
![c1](https://user-images.githubusercontent.com/52970359/87539500-a05f3700-c6bb-11ea-95da-5aa412a4ed4e.PNG)
Check it out

**Comment by Arjun3010** [comment]
Used the master branch and also tried in other branches...

**Comment by yjbanov** [comment]
I'm unable to reproduce this on https://github.com/flutter/flutter/commit/5e1635b186fad4df125b272ecca3bff7e59b3018. I created a brand new app using `flutter create` and ran it using `flutter run -d chrome -v`.

Is there anything else you can tell us about your local setup?

**Comment by namnh06** [comment]
I'm using Windows 10 and I've got this.
Trying to switch to channel beta and dev but no luck.
With the MacOS, everything is just fine.

**Comment by Arjun3010** [comment]
In my local setup, android sdk and flutter is in E: drive.

**Comment by TavleenGill** [comment]
I am facing same issue, initially was working on beta channel had this issue, tried almost everything nothing worked finally had to reinstall everything .Then started with master channel, it was working fine till now but now facing same issue here as well.

Please help me out.

**Comment by yjbanov** [comment]
Sounds like a Windows-specific issue. We'll investigate.

**Comment by yjbanov** [comment]
In the meantime, can you please try the following workarounds:

- Use profile or release mode: `flutter run --profile ...` or `flutter run --release ...`.
- Add the `--dart-define=FLUTTER_WEB_USE_SKIA=true` option.

**Comment by Arjun3010** [comment]
Works in profile mode, but why ?

**Comment by Arjun3010** [comment]
This command '--dart-define=FLUTTER_WEB_USE_SKIA=true' didn't change anything??

**Comment by ferhatb** [comment]
Tried on lastest master with and without latest engine on Windows 18362.900, both examples and flutter gallery worked fine. 

@Arjun3010 , if you run using flutter run -d chrome --profile , then open developer tools do you see any warning/error other than maybe favicon load ?

**Comment by Arjun3010** [comment]
![c](https://user-images.githubusercontent.com/52970359/87768284-85b2cc80-c839-11ea-8ae1-d257b65f5f70.PNG)

I have no problems in profile mode. But, I want to work in debug mode.

**Comment by ferhatb** [comment]
@Arjun3010 , ok so it looks like it is DDC/debug specific. What do you see on your network tab in debug?
/cc @grouma : any recent dwds or related changes that may have affected windows ?

**Comment by grouma** [comment]
No recent changes. We've had similar reports in the past that were caused by anti-virus software: https://github.com/dart-lang/sse/issues/16#issuecomment-616599511

**Comment by ferhatb** [comment]
Thanks @grouma for link to see issue. Is there any way we can provide any diagnostics, warning message etc for users so they have a way to solve this? At least detecting the failure and pointing them to a doc would be very useful.

**Comment by grouma** [comment]
Not that I'm aware of. I don't have an environment to play around in either unfortunately.

**Comment by Arjun3010** [comment]
![image](https://user-images.githubusercontent.com/52970359/87815548-6c367280-c883-11ea-98c2-b75fe12c6eec.png)

Networks tab @ferhatb

**Comment by Arjun3010** [comment]
In debug mode

**Comment by grouma** [comment]
Yes this looks very familiar to other reports. The `$dwdsSseHandler` request is silently stalled out. In the past this was due to antivirus software. Do you have Kaspersky installed?

**Comment by Arjun3010** [comment]
Yes, but disabled it while running

**Comment by Arjun3010** [comment]
Ten, what to do???

**Comment by Arjun3010** [comment]
What to do ?

**Comment by grouma** [comment]
See if this helps: https://github.com/flutter/flutter/issues/53338#issuecomment-621348161

**Comment by Arjun3010** [comment]
![image](https://user-images.githubusercontent.com/52970359/87816810-88d3aa00-c885-11ea-93f3-a2de6a0570d4.png)

Didn't work

**Comment by Arjun3010** [comment]
I am master channel.

**Comment by brunoblsouza87** [comment]
It only worked for me by disabling Kaspersky

**Comment by PaulHMason** [comment]
I can confirm that Kaspersky causes this issue for me on Windows 10.

**Comment by brunoblsouza87** [comment]
It only worked after I added the URL localhost in Configuration -> Protection -> Web -> Advanced -> Trusted URLs

**Comment by ferhatb** [comment]
Dropped priority. But keeping it open, some diagnosis with tool to pointing user in right direction would be best, other option is to document this in FAQ or tool docs.

**Comment by eino-makitalo** [comment]
It seems to be Antivirus issue. In my computer I have F-secure and last option ("Advanced network") must be turned off to work

In My Windows 10 with flutter channel beta I'm not able to run 
1) flutter run -d edge -v  
2) flutter run -d chrome -v
but if I run
3) flutter run web -v  and I use url provided with chrome and edge , its working

Application is just basic counter app.  I tried to turn off f-secure and windows firewall
When I turned of Advanced network protection )
Sorry finnish page, but maybe someone using F-secure finds it helpful.
![image](https://user-images.githubusercontent.com/1835186/92476782-2b563c80-f1e8-11ea-9090-30ef116a2eb1.png)

**Comment by bdevay** [comment]
I had the same problem with my virus scanner (thanks @eino-makitalo) and the hello world app is working properly. But after fixing this issue I can see this in the verbose log:

[   +3 ms] MetadataProvider: Failed to read metadata: AbsoluteImportUriError:
'file:///C:/Users/bdeva/AndroidStudioProjects/gui/lib/screen/cadbasedproduction/CadBasedProduction.dart'
ERROR - 2020-11-15 21:56:05.140857
GET /main_module.bootstrap.js
Error thrown by handler.
AbsoluteImportUriError: 'file:///C:/Users/bdeva/AndroidStudioProjects/gui/lib/screen/cadbasedproduction/CadBasedProduction.dart'

I'm on the dev channel.
The web page is still blank.

**Comment by Paolo-N** [comment]
I had the same issue with Kaspersky and I solved it by adding *localhost* as attendible address in Kaspersky settings.

**Comment by grouma** [comment]
> [ +3 ms] MetadataProvider: Failed to read metadata: AbsoluteImportUriError:
> 'file:///C:/Users/bdeva/AndroidStudioProjects/gui/lib/screen/cadbasedproduction/CadBasedProduction.dart'
> ERROR - 2020-11-15 21:56:05.140857
> GET /main_module.bootstrap.js
> Error thrown by handler.
> AbsoluteImportUriError: 'file:///C:/Users/bdeva/AndroidStudioProjects/gui/lib/screen/cadbasedproduction/CadBasedProduction.dart'

You can't have absolute file imports. Change it to be relative and things should work.

**Comment by bdevay** [comment]
> You can't have absolute file imports. Change it to be relative and things should work.

It should have been obvious from the log message, sorry. Thanks.

**Comment by OsamaQureshi796** [comment]
i also have same issue. it is working on debug mode but it is empty in release mode.

**Comment by MohammedZ666** [comment]
I don't have Kaspersky, but Windows Defender. So, I fixed it by allowing all port through the Windows Defender Firewall
1.    Go to search> type "windows firewall" > Select "Windows Defender Firewall with Advanced Security"
2.   on the top left select "Outbound rules"
3.   on the top right select New Rule
4.   on the pop up window select port>  click next
5.   select all remote ports>  click next
6.   select "Allow the connection"> Click next twice
7.   provide a rule name (i. e: port rule)  
8.   Hit finish 
9.   Try running this time and wait for a while

**Comment by kngon** [comment]
In my case, I removed `<base href="/">`  and it works.

**Comment by grouma** [comment]
Are folks still seeing this issue with Kaspersky? I have an environment with Kaspersky enabled and I'm having difficulty reproducing the issue. For anybody that can reproduce the issue, can you share your Kaspersky settings?

**Comment by lumenier1** [comment]
I had the same issue on MacBook.
After adding localhost to the permitted list of my antivirus this problem gone. I've also allowed just one specific port required by Flutter's debug mode for web.
May be this extra step should be included in [docs](https://flutter.dev/docs/get-started/web)?

**Comment by grouma** [comment]
@lumenier1 what antivirus software are you using?

**Comment by lumenier1** [comment]
@grouma Eset Nod 32.
I've also noticed that debugger takes random port every time. What is the need for this? Can I specify just one port for web debugging manually?

**Comment by 271766152** [comment]
Has the problem been solved? I also encountered the same problem. After trying to re-download the SDK and IDE, the problem still exists.
I used "flutter run -d chrome --web-renderer html" and it worked perfectly. 
but, "--web-renderer canvaskit" is a blank screen.
The default value is canvaskit? Guess it may be a bug in canvas.

More information "https://flutter.dev/docs/development/tools/web-renderers"

**Comment by outersky** [comment]
blank screen when using default canvaskit mode on Deepin linux 20.1,
it's ok with html mode

**Comment by grouma** [comment]
> I've also noticed that debugger takes random port every time. What is the need for this?

We simply bind to an open port, that's why it's random.

> Can I manually specify just one port for web debugging?

Flutter Tools currently does not have an option for this. I suggest opening a different tracking issue for this request.

**Comment by veneris** [comment]
This problem also occurs in the Manjaro system.
`
flutter run -d chrome --web-renderer html` is invalid,
`flutter run -d chrome --profile` works.

**Comment by Garciconx** [comment]
> In my case, I removed `<base href="/">` and it works.

This resolve the issue for me, i'm deploying flutter website in ipfs.

**Comment by neon97** [comment]
Went opposite for me its working in debug mode !! but as I build the flutter web with "flutter build web".
On opening the index.html file its almost blank.
Looking forward for solving this issue asap.
Need to live a webpage. 💯

**Comment by rahulvyas** [comment]
> Went opposite for me its working in debug mode !! but as I build the flutter web with "flutter build web".
> On opening the index.html file its almost blank.
> Looking forward for solving this issue asap.
> Need to live a webpage. 💯

Same is happening with me

**Comment by karanivincent** [comment]
> In my case, I removed `<base href="/">` and it works.

From which file do you remove this?

**Comment by grouma** [comment]
> From which file do you remove this?

Your `index.html`.

**Comment by zzterrozz** [comment]
> Went opposite for me its working in debug mode !! but as I build the flutter web with "flutter build web".
> On opening the index.html file its almost blank.
> Looking forward for solving this issue asap.
> Need to live a webpage. 💯

Same issue. Anyone found a solution? 
flutter run works fine but deploying on firebase hosting is just a blank screen

**Comment by Lokesh002** [comment]
I have tried to delete <base href="/"> from index.html which I have served on node js server. when I run the server and try to open the URL for getting flutter web app on chrome, it still shows blank screen. 
Flutter debug run doesn't show blank screen and runs perfectly

**Comment by Data0Face** [comment]
Same problem here after saved my project on Kali Linux it shows the processing when Chrome opens but the output is a blank page. Main channel. Flutter 2.11

**Comment by Data0Face** [comment]
Same problem here after saved my project on Kali Linux it shows the processing when Chrome opens but the output is a blank page. Main channel. Flutter 2.11

**Comment by JaegerCodes** [comment]
This is how I fixed
flutter clean
flutter pub get

**Comment by ThorFjelldalen** [comment]
I tried removing `<base href="/">`, but it didn't work. I noticed that I was opening the `<project>/web` directory. When I instead switched to `<project>/build/web` and removed `<base href="/">` in that `index.html`, it showed the app.

**Comment by ranusu** [comment]
still blank, big why ? any solution ?

**Comment by collo54** [comment]
I had the same issue when running in debug mode. when I run the web app using **flutter run -d chrome --profile** it worked.

**Comment by josh-burton** [comment]
I was having this issue but solved it but deleting the .dart-tool folder. It seems there was some cached code using a absolute uri.

**Comment by elasticsearcher** [comment]
Removing only the following sub-folder works for me:
`.dart_tool/chrome-device/Default/Code Cache`

This lets you keep any cached browser data like cookies and localstorage.

This issue only started happening to me today. The only thing that I can think of that's changed is I've updated my Chrome to Version 94.0.4606.61 (Official Build) (64-bit). I'm on Flutter 2.2.1.

**Comment by acheronian** [comment]
Nothing of the above solution resolves the issue for me.

Same as @elasticsearcher, the issue started to appear after auto-updating to this specific chrome version. Manually downgrading the chrome version resolved it for me, but only until I re-open chrome, as it auto-updates to the most recent version -.-

**Comment by acheronian** [comment]
Ok, I just set "Disable cache" in chrome dev tools network tab to enabled and it started working again

**Comment by Teio07** [comment]
I get the exact same blank page running on a mobile devices (it works in release, profile and debug on my Macbook though). This only happens when using canvasKit as the renderer. Switching to html works...

This is what I run the app with :
`flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0 --web-renderer canvaskit --release`

Then on mobile I navigate to : 
http://<my-ip-address>:8080

Tried on an iPhone X, iPad Air 4 and a low-end Android phone. Same problem for all of them even with just a simple Scaffold(body: Text("Hello World"));

**Comment by stevenBang** [comment]
@Teio07 
How do you disable WebGL 2.0 ?
thanks

**Comment by BartOMan** [comment]
> Has the problem been solved? I also encountered the same problem. After trying to re-download the SDK and IDE, the problem still exists. I used "flutter run -d chrome --web-renderer html" and it worked perfectly. but, "--web-renderer canvaskit" is a blank screen. The default value is canvaskit? Guess it may be a bug in canvas.
> 
> More information "https://flutter.dev/docs/development/tools/web-renderers"

FOUND AN  OPTION THAT WORKED FOR ME
I ran everything under Windows 10 with Kaspersky
Flutter SDK, updated on Jan 7, 2022, with STABLE version.

For brevity, let:
K = kaspersky running;   KD = Kaspersky disabled
opt0 = -d chrome
opt1 =  --dart-define=FLUTTER_WEB_USE_SKIA=true 
opt2 = --web-renderer html
opt3 = --web-renderer canvaskit

W = web app runs correctly;   
F = web app fails, blank chrome window

COMMANDS:                                           CONDITIONS               RESULTS
flutter run  opt0                                       K                                   F
flutter run  opt0                                       KD                                 F
flutter run  opt0   opt1                             KD                                F
flutter run  opt0   opt3                             KD                                F
flutter run  opt0   opt1  opt3                    K                                  F
flutter run  opt0   opt2                             KD                                W     <== WORKS
flutter run  opt0   opt1 opt2                    KD                                W     <== WORKS
flutter run  opt0   opt2                             K                                  W     <== WORKS
flutter run  opt0   opt1 opt2                     K                                  W     <== WORKS
       
Tentative conclusion:    
On my system,  with Kaspersky running or disabled, the only option that was both necessary & sufficient by itself
to run the web app correctly was opt2  (--web-renderer html)

**Comment by fodor99** [comment]
I got white (empty/blank) screen on my M1-Air, when I move the browser window to the secondary (external) monitor. As I move it back, I can see the content. I am not sure this behavior is related to chrome, or flutter rendering engine.

**Comment by parkskier426** [comment]
> I got white (empty/blank) screen on my M1-Air, when I move the browser window to the secondary (external) monitor. As I move it back, I can see the content. I am not sure this behavior is related to chrome, or flutter rendering engine.

Yep, same issue on an M1 MBP using chrome.

**Comment by mmaia** [comment]
I have the same with Linux Pop OS 20.04 

flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on Pop!_OS 20.04 LTS 5.16.19-76051619-generic, locale en_US.UTF-8)
    • Flutter version 2.10.5 at /home/mmaia/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (13 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mmaia/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/lib/jvm/zulu11/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/mmaia/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210
    • Flutter plugin version 66.0.4
    • Dart plugin version 221.5588

[✓] VS Code (version 1.66.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by hodakl099** [comment]
> Has the problem been solved? I also encountered the same problem. After trying to re-download the SDK and IDE, the problem still exists. I used "flutter run -d chrome --web-renderer html" and it worked perfectly. but, "--web-renderer canvaskit" is a blank screen. The default value is canvaskit? Guess it may be a bug in canvas.
> 
> More information "https://flutter.dev/docs/development/tools/web-renderers"

this worked for me

**Comment by yitelee** [comment]
For me I have to turn off ADGUARD (a chrome extension) to solve it.

**Comment by 0xpussycat** [comment]
I also experience the problem when hosting on firebase using Github Actions.

Running locally works and deploying to firebase from local laptop works but when deploying from Github Actions. It shows the blank page. This is weird as I confirm that the command to `flutter build` are exactly the same. 

I tried different options and also all suggestions here but it still doesn't work.

**Comment by 0xpussycat** [comment]
I figured out. For my case, I need to stop using stable channel and use beta version to make this work.

**Comment by abcdOfficialzw** [comment]
Had the same issue on ubuntu 20.10 running flutter 3.3.5  issue solved by connecting my pc to the internet. I was previously running with airplane mode on.

**Comment by gi-nam-dev** [comment]
NOTHING WORKSSSSSS for me :')

**Comment by MelonPie** [comment]
Experiencing the same issue on my windows 10 machine. Tried to change the web-renderer to `html` and and removing the .dart_tool dir. Blank page in all cases.

**Comment by MelonPie** [comment]
I tried the other approaches as well. In the end the solution was to reload the page after the event `app.started` was logged in the debug console. Since the issue only occurs in the debug mode it is ok for now. However the problem was present in all branches and should be patched out.

**Comment by sittingbool** [comment]
Having this issue on Mac as well. Flutter doc says:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3 22E252 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by abcdOfficialzw** [comment]
Hey, I had this problem for the longest time. When you start a Flutter web app you're connected to the internet on your PC. 
Hope it helps, helped me ;)

**Comment by blob84** [comment]
I have the same problem.

**Comment by yongrim** [comment]
For those of you experiencing this issue please share your firebase.json. Mine looks like this:

```
{
  "hosting": {
    "public": "web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

I noticed that this happens if you answer 'y' to this question asked during 'firebase init hosting', which removes the "rewrites" field:

`> Configure as a single-page app (rewrite all urls to /index.html)?`

**Comment by AresVampire** [comment]
Finally, I figured out I needed to point out the hostname and port to make the flutter web run locally.

```
flutter run -d chrome --web-port=8080 --web-hostname=127.0.0.1
```

**Comment by derlarsschneider** [comment]
For everyone who is still looking for workaround as I was because none of the above was working:

```bash
$ flutter run -d chrome \
  --web-port=5000 \
  --web-browser-flag="--new-window" \
  --web-browser-flag="--user-data-dir=/tmp/chrome_test2" \
  --web-browser-flag="--enable-unsafe-swiftshader" \
  --web-browser-flag="--disable-software-rasterizer" \
  --web-browser-flag="--enable-gpu-rasterization" \
  --web-browser-flag="--enable-hardware-overlays" 
```

By default chrome was using software rendering causing problems with flutter web. The flags above enforce hardware acceleration.
