### ISSUE TITLE
typos in the tutorial

### ISSUE THREAD

**Issue by Omer1Yuval1** [flutter/flutter#62282]
In steps 4 and 5 of the tutortial (https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#5), the same name is sometimes referred to as _RandomWordState and sometimes as _RandomWordsState

**Comment by darshankawar** [comment]
![Screen Shot 2020-07-27 at 1 06 42 PM](https://user-images.githubusercontent.com/67046386/88515900-0a57d480-d00a-11ea-8ca4-0c6363d7c167.png)

`_RandomWordState` is mentioned once as above, while `_RandomWordsState` is mentioned at rest of places.

**Comment by avk29** [comment]
Hi @Omer1Yuval1 , I would like to fix this issue. Would appreciate if you could provide me with the follow-up steps.

**Comment by maheshmnj** [comment]
This seems to be corrected with this merge https://github.com/flutter/website/pull/4289

**Comment by darshankawar** [comment]
I still see the typo as mentioned originally, unless I am looking at wrong place.

https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#5

**Comment by Aman9026** [comment]
@TahaTesser I cross checked with another similar issue with the same codelab and found that the actual documents in the repo are updated and correct. I believe the website needs a poll scm trigger.

**Comment by TahaTesser** [comment]
@Aman9026 
That's true, please open an issue in flutter/website to update codelab for these changes

**Comment by Aman9026** [comment]
> @Aman9026
> That's true, please open an issue in flutter/website to update codelab for these changes

Done :smile: 
https://github.com/flutter/website/issues/4530
