### ISSUE TITLE
Re-enable DDS when Devtools is compatible

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#62507]
The `dart:html` implementation of `WebSocket` does not follow redirects and does not provide a way to do so. This will cause web apps like Devtools to be unable to connect to DDS and the VM service. The VM service will need to be able to forward SSE connections to DDS and Devtools will need to migrate to using SSE to connect to the VM service.

**Comment by jmagman** [comment]
@bkonyi was this fixed with https://github.com/flutter/flutter/pull/64847?

**Comment by bkonyi** [comment]
No, this was reverted and will still need to land when DDS has IPv6 support.

**Comment by bkonyi** [comment]
Resolved in https://github.com/flutter/flutter/pull/65873.

**Comment by justkawal** [comment]
@bkonyi 
Any proper solution for this DDS issue as I am also getting this error on iOS:

#71650 similar issue but with not proper resolution: **Fail to connect to service protocol: http://127.0.0.1:52..........**

**Comment by benedicte69** [comment]
Following the last updates, it seems that the problem is back

Devtools does not connect to VM,


it stops there:
{"event":"app.started","params":{"appId":"7cce3816-01c7-414d-88d2-b4c66aa9e919"}}]
[{"id":0,"result":{"value":"android","type":"_extensionType","method":"ext.flutter.platformOverride"}}]
[{"id":1,"result":{"timeDilation":"1.0","type":"_extensionType","method":"ext.flutter.timeDilation"}}]
[{"id":2,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaint"}}]
[{"id":3,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaintBaselinesEnabled"}}]
[{"id":4,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.repaintRainbow"}}]
[{"id":5,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.showPerformanceOverlay"}}]
[{"id":6,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugAllowBanner"}}]
[{"id":7,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":8,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.show"}}]
[{"id":9,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":10,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[{"id":11,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":12,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":13,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]

or there 


An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:61814/UNYPG_eq9Qg=/
The Flutter DevTools debugger and profiler on sdk gphone x86 is available at:
http://127.0.0.1:9108?uri=http%3A%2F%2F127.0.0.1%3A61814%2FUNYPG_eq9Qg%3D%2F


Could you help?

**Comment by justkawal** [comment]
> Resolved in #65873.

No it's not resolved, on Mac it's still a big issue.

**Comment by bkonyi** [comment]
@justkawal @benedicte69 the issues you're seeing are likely unrelated to this issue. If you're still running into connection issues, please file a new issue with more details and logs and cc me.

**Comment by benedicte69** [comment]
The fact is that when this problem occurred and as you can see, the content in my console is similar to that period.But I do not mind to open a new topic. Will do that later... when I will be motivated. I do not understand why some updates lead back to former problem.

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., avr. 6, 2021 à 18:50, Ben ***@***.***> a écrit :   


@justkawal @benedicte69 the issues you're seeing are likely unrelated to this issue. If you're still running into connection issues, please file a new issue with more details and logs and cc me.

**Comment by benedicte69** [comment]
Then flutter pub global activate DevTools or run DevTools works in itself but the links propulsed do not open or connect 🤔

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., avr. 6, 2021 à 18:59, ***@***.***> a écrit :   

The fact is that when this problem occurred and as you can see, the content in my console is similar to that period.But I do not mind to open a new topic. Will do that later... when I will be motivated. I do not understand why some updates lead back to former problem.

Envoyé depuis Yahoo Mail pour Android 
 
 Le mar., avr. 6, 2021 à 18:50, Ben ***@***.***> a écrit : 


@justkawal @benedicte69 the issues you're seeing are likely unrelated to this issue. If you're still running into connection issues, please file a new issue with more details and logs and cc me.
