### ISSUE TITLE
PlatformException(no_available_camera, No cameras available for taking pictures., null)

### ISSUE THREAD

**Issue by krupalbhardiya** [flutter/flutter#62669]
## Steps to Reproduce

Taking pictures using camera crashes the Plugin [(Image Picker by Flutter)](https://pub.dev/packages/image_picker)

    final pickedFile = await _picker.getImage(source: ImageSource.camera);

This plugin works in Emulator and Physical device with Android API <=29.

On Android Platform API 30, the plugin crashed with no available cameras exception.

I've used the system default camera app in Android API 30 and is opens up the camera and captures the image on the other hand, plugin shows exception of no cameras available for taking pictures.
All Runtime permissions are allowed and static manifest permissions are also declared.

**Expected results:** 
Open Camera and Take picture from system default Camera App. 

**Actual results:** 
PlatformException(no_available_camera, No cameras available for taking pictures., null)

<details>
  <summary>Logs</summary>
    PlatformException(no_available_camera, No cameras available for taking pictures., null)

```
```

```
```

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.17.5 at D:\flutter_sdk
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\android_sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • sdk gphone x86 64 • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

```
```

</details>

**Comment by tilay123** [comment]
I am having the same error.

**Comment by darshankawar** [comment]
Hi @krupalbhardiya,
I tried to replicate the issue on latest `master` and was able to successfully capture image from emulator's camera.
I tested on Pixel 3a emulator with api 30.

![62669_1](https://user-images.githubusercontent.com/67046386/89182008-6a262080-d5b2-11ea-99ca-f1a00c019cba.png)
![62669](https://user-images.githubusercontent.com/67046386/89182015-6d211100-d5b2-11ea-983c-b67cdce222cb.png)

I used `image_picker` plugin's official [example](https://pub.dev/packages/image_picker/example) as a code sample.

**Comment by krupalbhardiya** [comment]
@darsh

> Hi @krupalbhardiya,
> I tried to replicate the issue on latest `master` and was able to successfully capture image from emulator's camera.
> I tested on Pixel 3a emulator with api 30.
> 
> ![62669_1](https://user-images.githubusercontent.com/67046386/89182008-6a262080-d5b2-11ea-99ca-f1a00c019cba.png)
> ![62669](https://user-images.githubusercontent.com/67046386/89182015-6d211100-d5b2-11ea-983c-b67cdce222cb.png)
> 
> I used `image_picker` plugin's official [example](https://pub.dev/packages/image_picker/example) as a code sample.

@darshankawar this code runs well in debug builds but it crashes the App in release build. App can't even start. It crashes from the start. So I have to remove the whole code in order to start the App.

**Comment by darshankawar** [comment]
Hi @krupalbhardiya,
Can you try to upgrade your flutter stable version to latest and see if you experience the same issue ?
Thanks.

**Comment by krupalbhardiya** [comment]
@darshankawar should i switch to master branch ?

**Comment by krupalbhardiya** [comment]
@darshankawar after switching to master branch and creating the release build variant of the App no longer crashes the App.

**Comment by Knupper** [comment]
@darshankawar i have tried your solution, but i get the same error as @krupalbhardiya .

**Comment by krupalbhardiya** [comment]
@Knupper , issue is resolved in master branch. you can switch to master branch of flutter or wait till the latest version is available in stable branch.

**Comment by Knupper** [comment]
@krupalbhardiya i switched to the master branch, but have still the same output.

**Comment by Knupper** [comment]
I took another look into it, the example project works for me, but when i change the `targetSdkVersion` and `compileSdkVersion` to 30 there as well, i get the posted error. @krupalbhardiya maybe this helps you as well?

**Comment by farazk86** [comment]
I had the same error, my ``compileSdkVersion`` and ``targetSdkVersion`` were both 30. 

Changing these to 29 fixed the issue for me.

**Comment by ciprig** [comment]
The issue does still reproduce with targetSdkVersion 30 on Flutter Channel beta, 1.22.0-12.1.pre.
With targetSdkVersion 29 and compileSdkVersion 30 it's working.

**Comment by darshankawar** [comment]
This seems to be an issue with targeting api version to 30.
See [this](https://github.com/flutter/flutter/issues/63727#issuecomment-690070820) comment and related documentation on accessing apps targeted to api 30.
And according to the same comment, please try to add 
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>` in manifest and see if it resolves your issue
Thanks.

**Comment by Knupper** [comment]
@darshankawar i have tried it today, with this permission it works fine with tagetSdk30.

**Comment by darshankawar** [comment]
@Knupper 
Thanks for confirming. With that said, I am going ahead and closing this issue.
@ciprig , @farazk86 Please see above comment and solution, try again and see if it works for you.
If you still see the issue, please write in comments and I'll reopen.
Thanks.

**Comment by Zony-Zhao** [comment]
@darshankawar You are A LIFE-SAVER! Only way to compatible with two packages 'geolocator' and 'image_picker'.

**Comment by victor-semenovich** [comment]
Adding the \<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/> permission leads to the warning message:
> A \<queries> declaration should generally be used instead of QUERY_ALL_PACKAGES; see https://g.co/dev/packagevisibility for details

A better solution is to add \<queries> to the manifest file: https://stackoverflow.com/a/63246789/3129257

**Comment by omidraha** [comment]
Same issue here.

**Info**:
```
targetSdkVersion 30
compileSdkVersion 30
```

```
image_picker: ^0.7.4
```

```
Pixel 2 API 30 Android 11
```

```
$ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /**/sdk/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at **/sdk/android/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = **/sdk/android/
    • Java binary at: **/ide/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at **/ide/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = **/ide/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64   • Linux

! Doctor found issues in 1 categor
```

Related [SO](https://stackoverflow.com/questions/63953363/flutter-platformexceptionno-available-camera-no-cameras-available-for-taking).
