### ISSUE TITLE
LUCI should run the tests in a directory that contains a space character

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#62919]
Before we can migrate off LUCI, we need to reenable `dev/bots/test/sdk_directory_has_space_test.dart`.

cc @godofredoc

**Comment by godofredoc** [comment]
\cc @christopherfujino

**Comment by godofredoc** [comment]
This is fixed now!

**Comment by darrenaustin** [comment]
It looks like this is still a problem, no? As part of the skip test audit, I tried re-enabling the test in `sdk_directory_has_space_test.dart` and it fails with: 

```
00:04 +41 -1: test/sdk_directory_has_space_test.dart: We are in a directory with a space in it [E]                                                                                                     
  Expected: 'flutter sdk'
    Actual: <null>
     Which: not an <Instance of 'String'>
```

Is this a problem with the test or is this not working due to a revert? Should this be reopened?

**Comment by godofredoc** [comment]
@darrenaustin this may be a different issue can you please open a new bug and provide a link to the builder with the failure?
