### ISSUE TITLE
AnimationController has lost it's vsync.

### ISSUE THREAD

**Issue by tomosullivan8** [flutter/flutter#63088]
The AnimationController has lost it's `vsync` and is now requiring `TickerProvider`.

Error message:
 
```
Found this candidate, but the arguments don't match.
AnimationController({
^^^^^^^^^^^^^^^^^^^
```

![image](https://user-images.githubusercontent.com/36487764/89542548-ba41f480-d7f7-11ea-98da-3670d39d10dc.png)

I've checked the location of the AnimationController file and it's missing it's '@' before the required, I presume this is the issue and why it's caused my application to crash.

![image](https://user-images.githubusercontent.com/36487764/89542361-7ea72a80-d7f7-11ea-984e-21b84117f4f1.png)

Flutter Doctor output;

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.226, on Mac OS X 10.15.5 19F101, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
hI @tomosullivan8 
This is working on latest `master`

Please try this code sample

<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
  AnimationController _animationController;

  @override
  void initState() {
    super.initState();
    _animationController =
        AnimationController(vsync: this, duration: Duration(seconds: 1))
          ..forward()
          ..repeat(reverse: true);
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Center(
          child: AnimatedBuilder(
            animation: _animationController,
            builder: (context, child) {
              return Container(
                decoration: ShapeDecoration(
                    shape: CircleBorder(), color: Colors.white.withOpacity(.5)),
                child: Padding(
                  padding: EdgeInsets.all(8.0 * _animationController.value),
                  child: child,
                ),
              );
            },
            child: Container(
              decoration:
                  ShapeDecoration(shape: CircleBorder(), color: Colors.white),
              child: IconButton(
                  icon: Icon(
                    Icons.flight_takeoff,
                    size: 24,
                    color: Colors.black,
                  ),
                  onPressed: () {}),
            ),
          ),
        ),
      ),
    );
  }
}


``` 

</details> 


[Screen Recording 2020-08-06 at 8.23.00 PM.zip](https://github.com/flutter/flutter/files/5035655/Screen.Recording.2020-08-06.at.8.23.00.PM.zip)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.226, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.226 at /Users/taha/Code/flutter_master
    • Framework revision fa60f525f0 (3 hours ago), 2020-08-06 08:01:03 -0400
    • Engine revision 36db6cfdd1
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 14a6aac97b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (6 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details> 


Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by stefanodecillis** [comment]
Hello,

I have the lasest version of Flutter (same as the creator of this thread) and your code (the animationController statement) does not work. Vsync is still missing and asks for tickerProvider. Even if you give it, it will fail to compile. 
I attached what I (probably we) see. Instead of vsync, asks for ticketProvider.

![animation](https://user-images.githubusercontent.com/16707752/89547846-91752b80-d806-11ea-89cc-b005c539828a.png)

**Comment by tomosullivan8** [comment]
Hi @TahaTesser.

I've tried upgrading to the latest master version again, but as @stefanodecillis mentioned it's a definite error as the `vsync` has been removed. I do believe the issue lies with the code missing the `@` before the required, and as you can see in my screenshot the `vsync` is not an option.

If you have any other suggestions then let me know!

Thanks

Tom

**Comment by tomosullivan8** [comment]
Also, just to confirm, if I included the sample code I get the error message!

![image](https://user-images.githubusercontent.com/36487764/89557760-35f96c80-d80b-11ea-991c-c9503730b856.png)

**Comment by stefanodecillis** [comment]
I would also add that I tried to modify the @required in the class and so get the vsync attribute. The problem is that results not to be a good candidate. Give the error mentioned in my thread. From it, you can probably find the commits where the error was made by mistake since it was written for null safety purpose

**Comment by tomosullivan8** [comment]
@stefanodecillis if you switch to beta channel and then revert back to the master it seems to fix the problem! That's what I did and bingo the vsync is alive. If this fixes it for you please can you close this after.

**Comment by stefanodecillis** [comment]
Agree, the solution worked. Thank you!

**Comment by dooven** [comment]
This happened to me as well (im using flutter beta channel). I fixed it by updating dart.  Now im using `Dart SDK version: 2.10.0-4.0.dev (dev)`

**Comment by Zfinix** [comment]
> @stefanodecillis if you switch to beta channel and then revert back to the master it seems to fix the problem! That's what I did and bingo the vsync is alive. If this fixes it for you please can you close this after.

Switching to beta solves this issue

**Comment by nibo** [comment]
working as expected simply use "TickerProvider" now **AnimationController(TickerProvider: this);**

**Comment by nibo** [comment]
change minimum sdk to 2.8
run flutter upgrade
run flutter pub get
run flutter clean
restart IDE

**Comment by Zfinix** [comment]
> flutter clean

This worked

**Comment by bankenro** [comment]
> change minimum sdk to 2.8
> run flutter upgrade
> run flutter pub get
> run flutter clean
> restart IDE

not working for me.

solution for me stable and beta whit minimum sdk to 2.8
run:

- flutter version 1.20.2 
- flutter upgrade 
- flutter pub upgrade

good lucky

**Comment by Baluds** [comment]
> change minimum sdk to 2.8
> run flutter upgrade
> run flutter pub get
> run flutter clean
> restart IDE

Worked for me

**Comment by bgmf** [comment]
The important part seems to be to use the minimum SDK 2.8. The rest, apart from restarting Android Studio, was not that important to me.

**Comment by sudeshkumara** [comment]
This error occurred after I updated the stable channel. But none of these solutions worked for me. anyone can help me.

Flutter is already up to date on channel stable
Flutter 1.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (2 days ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1

------------------------------------------------------------------------------------------------------------

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.17763.1457], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.1)
[√] Connected device (3 available)

• No issues found!

**Comment by sudeshkumara** [comment]
If none of these work, check after restarting the PC. I've tried above mentioned all solutions even invalidate cache and restart option in android studio. But did not work. The issue has been resolved after the PC restarted.

**Comment by dasmikko** [comment]
I'm still having the issue. I've tried setting the min sdk, switching channels,  flutter clean. Nothing works. I keep getting the error.

**Comment by Yogi09** [comment]
It's late I think but if someone get this issue in future so can refere below solution.

class _onCreate extends State<ShakeAnimationPage> with TickerProviderStateMixin

**with TickerProviderStateMixin**

just add this line and it will work.

**Comment by it-one-mm** [comment]
Delete **.idea** folder and _reopen project_ and this _should work_ with **Android Studio**.

**Comment by wuwz98** [comment]
**JUST RESTART YOUR COMPUTER**
got the same problem using Dart 2.10.3 and Flutter 1.22.3.
there's nothing wrong with the code, yet I got an red underline just belwo vsync, thisproblem is solved after restaring the computer.

**Comment by bgmf** [comment]
> **JUST RESTART YOUR COMPUTER**
> got the same problem using Dart 2.10.3 and Flutter 1.22.3.
> there's nothing wrong with the code, yet I got an red underline just belwo vsync, thisproblem is solved after restaring the computer.

Are you from the **IT Crowd**? 😂
No, restarting the computer is, in contrary to popular belief, mystically resolve all of your problems... 😉

**Comment by RedCuckoo** [comment]
What you call "restart a computer" simply do an "Invalidate cache and restart" in Android Studio (it's under File).

**Comment by huynguyennovem** [comment]
just do `Invalid caches and restart Android Studio`

**Comment by qndincl** [comment]
There's a way to solve it without updating Dart SDK.  
If you go into **animation_controller.dart** file and look at the `required TickerProvider vsync` in AnimationController class.
then just put a  `@`  at the front of `required.`

I think it's a simple solution, but it may not be a complete answer.

**Comment by HeCorr** [comment]
Here we are, about a year later. With null-safety enabled this issue appeared again...

`sdk >= 2.8.0` gives an error
`flutter clean` doesn't fix it
`flutter upgrade` doesn't fix it either...

I guess I'm just not doing animations then.
