### ISSUE TITLE
DequeueBuffer: dequeueBuffer failed error, on few Android API levels

### ISSUE THREAD

**Issue by dms24081999** [flutter/flutter#63399]
- (DequeueBuffer: dequeueBuffer failed) error occurs on **API level 24**, but works fine on **API level 28** while debugging the app or using the build apk. Not sure if any other API levels are affected.
- App freezes with (DequeueBuffer: dequeueBuffer failed), when switching between another application and returning back to the Flutter App. (on API level 24)
- App freezes with (DequeueBuffer: dequeueBuffer failed), when app is minimized or when Screen goes off when the application is open/closed. (on API level 24)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Copy the below code in main.dart and run it on Android API level 24 (Android 7.0)
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hello World',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Welcome"),),
      body: TextField(),
    );
  }
}
```
3. The Application Run log, with DequeueBuffer: dequeueBuffer failed error, which occurs while switching to another app and returning back to the Flutter App on API level 24 (Not on API level 28 or above)
```
Launching lib\main.dart on Lenovo K33a42 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        39.9s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                11.0s
Waiting for Lenovo K33a42 to report its views...                    23ms
I/Choreographer(27903): Skipped 44 frames!  The application may be doing too much work on its main thread.
Syncing files to device Lenovo K33a42...                           651ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Lenovo K33a42 is available at: http://127.0.0.1:63805/67w7dsuFHNQ=/
V/BoostFramework(27903): mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
V/BoostFramework(27903): mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
V/BoostFramework(27903): mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
V/BoostFramework(27903): mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
V/BoostFramework(27903): mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
V/BoostFramework(27903): BoostFramework() : mPerf = com.qualcomm.qti.Performance@be0133d
W/IInputConnectionWrapper(27903): finishComposingText on inactive InputConnection
W/IInputConnectionWrapper(27903): reportFullscreenMode on inexistent InputConnection
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
I/Adreno  (27903): DequeueBuffer: dequeueBuffer failed
```

<details>
  <summary>Logs</summary>

```
[ +328 ms] executing: [F:\ProgramFiles\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +159 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +2 ms] executing: [F:\ProgramFiles\flutter/] git tag --contains HEAD
[ +454 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.1
[  +22 ms] executing: [F:\ProgramFiles\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +137 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [F:\ProgramFiles\flutter/] git ls-remote --get-url origin
[  +89 ms] Exit code 0 from: git ls-remote --get-url origin
[   +6 ms] https://github.com/flutter/flutter.git
[ +192 ms] executing: [F:\ProgramFiles\flutter/] git rev-parse --abbrev-ref HEAD
[ +186 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +8 ms] stable
[ +204 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +37 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +36 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +53 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +148 ms] List of devices attached
                    34c5d6ec               device product:karate model:Lenovo_K33a42 device:K33a42 transport_id:3
[  +41 ms] C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell getprop
[ +160 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +43 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +46 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +46 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +59 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +396 ms] Found plugin path_provider_linux at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +46 ms] Found plugin shared_preferences at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.8\
[  +19 ms] Found plugin shared_preferences_linux at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+1\
[   +7 ms] Found plugin shared_preferences_macos at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +9 ms] Found plugin shared_preferences_web at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[ +243 ms] Found plugin path_provider_linux at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +17 ms] Found plugin shared_preferences at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.8\
[  +54 ms] Found plugin shared_preferences_linux at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+1\
[   +3 ms] Found plugin shared_preferences_macos at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +6 ms] Found plugin shared_preferences_web at C:\Users\dms24\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[ +227 ms] Generating F:\Projects\Flutter\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +77 ms] ro.hardware = qcom
[ +188 ms] Starting incremental build...
[   +7 ms] Initializing file store
[  +91 ms] Skipping target: gen_localizations
[  +47 ms] complete
[  +63 ms] Launching lib\main.dart on Lenovo K33a42 in debug mode...
[  +66 ms] F:\ProgramFiles\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev F:\ProgramFiles\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
F:\ProgramFiles\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\dms24\AppData\Local\Temp\flutter_tools.aa518814\flutter_tool.16c238dd\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +94 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree F:\Projects\Flutter\hello_world\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +55 ms] Exit code 0 from: C:\Users\dms24\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree F:\Projects\Flutter\hello_world\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +56 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hello_world" (Raw: "com.example.hello_world")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello_world" (Raw: "hello_world")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello_world.MainActivity" (Raw: "com.example.hello_world.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[ +127 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell -x logcat -v time -t 1
[ +237 ms] Exit code 0 from: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           08-12 14:06:46.045 I/lenovokeyguard.log( 1796): (1796.0/main/1.5)[KeyguardViewMediator]{handleKeyguardDoneDrawing}
[  +38 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell -x logcat -v time -t 1
[ +212 ms] Exit code 0 from: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           08-12 14:06:46.495 W/ActivityManager( 1530): Expected user 10 in state RUNNING_LOCKED but was in state RUNNING_UNLOCKED
[  +29 ms] <- compile package:hello_world/main.dart
[  +39 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +214 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.3-6597393
                    Installed as C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +64 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +197 ms] Building APK
[ +115 ms] Running Gradle task 'assembleDebug'...
[   +9 ms] gradle.properties already sets `android.enableR8`
[  +97 ms] Using gradle from F:\Projects\Flutter\hello_world\android\gradlew.bat.
[  +67 ms] F:\Projects\Flutter\hello_world\android\gradlew.bat mode: 33279 rwxrwxrwx.
[ +134 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +421 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +82 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +310 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[ +213 ms] executing: [F:\Projects\Flutter\hello_world\android/] F:\Projects\Flutter\hello_world\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm -Ptarget=F:\Projects\Flutter\hello_world\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+6853 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +296 ms] executing: [F:\ProgramFiles\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +92 ms] [ +161 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +120 ms] [        ] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[  +48 ms] [   +1 ms] executing: [F:\ProgramFiles\flutter/] git tag --contains HEAD
[ +520 ms] [ +636 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] [        ] 1.20.1
[   +3 ms] [  +25 ms] executing: [F:\ProgramFiles\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +86 ms] [  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] [        ] origin/stable
[   +2 ms] [        ] executing: [F:\ProgramFiles\flutter/] git ls-remote --get-url origin
[ +144 ms] [  +79 ms] Exit code 0 from: git ls-remote --get-url origin
[ +190 ms] [        ] https://github.com/flutter/flutter.git
[ +127 ms] [ +210 ms] executing: [F:\ProgramFiles\flutter/] git rev-parse --abbrev-ref HEAD
[  +73 ms] [ +188 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ +110 ms] [        ] stable
[   +2 ms] [  +93 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +63 ms] [   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +14 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +61 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] [  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ +105 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +60 ms] [   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [  +63 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +175 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +80 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +53 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +149 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +61 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +37 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [ +409 ms] Initializing file store
[        ] [  +60 ms] Done initializing file store
[   +1 ms] [ +144 ms] Skipping target: gen_localizations
[+1010 ms] [+1305 ms] Skipping target: kernel_snapshot
[   +2 ms] [  +21 ms] invalidated build due to missing files: F:\Projects\Flutter\hello_world\DOES_NOT_EXIST_RERUN_FOR_WILDCARD17743013
[ +804 ms] [ +760 ms] debug_android_application: Starting due to {InvalidatedReason.inputMissing}
[ +498 ms] [ +488 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +1 ms] [  +59 ms] debug_android_application: Complete
[ +716 ms] [ +734 ms] Persisting file store
[  +86 ms] [  +56 ms] Done persisting file store
[   +1 ms] [  +24 ms] build succeeded.
[  +93 ms] [  +70 ms] "flutter assemble" took 4,250ms.
[  +25 ms] [  +13 ms] ensureAnalyticsSent: 1ms
[   +7 ms] [   +3 ms] Running shutdown hooks
[   +2 ms] [        ] Shutdown hooks complete
[ +201 ms] [  +13 ms] exiting with code 0
[ +196 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +15 ms] > Task :app:preBuild UP-TO-DATE
[   +2 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +50 ms] > Task :shared_preferences:preBuild UP-TO-DATE
[  +76 ms] > Task :shared_preferences:preDebugBuild UP-TO-DATE
[  +68 ms] > Task :shared_preferences:compileDebugAidl NO-SOURCE
[   +3 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :shared_preferences:packageDebugRenderscript NO-SOURCE
[  +58 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +9 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +43 ms] > Task :app:compileDebugShaders UP-TO-DATE
[  +53 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :shared_preferences:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :shared_preferences:packageDebugAssets UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugAssets
[ +164 ms] > Task :app:copyFlutterAssetsDebug
[   +3 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +40 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +4 ms] > Task :app:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :shared_preferences:compileDebugRenderscript NO-SOURCE
[  +16 ms] > Task :shared_preferences:generateDebugResources UP-TO-DATE
[  +52 ms] > Task :shared_preferences:packageDebugResources UP-TO-DATE
[   +6 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +72 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +83 ms] > Task :shared_preferences:checkDebugManifest UP-TO-DATE
[   +3 ms] > Task :shared_preferences:processDebugManifest UP-TO-DATE
[ +141 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +2 ms] > Task :shared_preferences:parseDebugLibraryResources UP-TO-DATE
[   +2 ms] > Task :shared_preferences:generateDebugRFile UP-TO-DATE
[   +2 ms] > Task :app:processDebugResources UP-TO-DATE
[   +3 ms] > Task :shared_preferences:generateDebugBuildConfig UP-TO-DATE
[  +89 ms] > Task :shared_preferences:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :shared_preferences:compileDebugJavaWithJavac UP-TO-DATE
[   +2 ms] > Task :shared_preferences:bundleLibCompileDebug UP-TO-DATE
[   +2 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +2 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +62 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[  +45 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +2 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :shared_preferences:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :shared_preferences:bundleLibResDebug UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :shared_preferences:bundleLibRuntimeDebug UP-TO-DATE
[   +2 ms] > Task :shared_preferences:createFullJarDebug UP-TO-DATE
[  +44 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +1 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +1 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[  +55 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +3 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugJniLibFolders UP-TO-DATE
[   +2 ms] > Task :shared_preferences:mergeDebugNativeLibs UP-TO-DATE
[  +77 ms] > Task :shared_preferences:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :shared_preferences:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +6 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[  +50 ms] > Task :app:packageDebug UP-TO-DATE
[   +1 ms] > Task :app:assembleDebug
[   +1 ms] > Task :shared_preferences:extractDebugAnnotations UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :shared_preferences:prepareLintJarForPublish UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugJavaResource UP-TO-DATE
[   +2 ms] > Task :shared_preferences:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[   +1 ms] > Task :shared_preferences:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[  +81 ms] > Task :shared_preferences:bundleDebugAar UP-TO-DATE
[  +41 ms] > Task :shared_preferences:compileDebugSources UP-TO-DATE
[   +2 ms] > Task :shared_preferences:assembleDebug UP-TO-DATE
[   +1 ms] BUILD SUCCESSFUL in 13s
[   +1 ms] 59 actionable tasks: 5 executed, 54 up-to-date
[ +416 ms] Running Gradle task 'assembleDebug'... (completed in 16.3s)
[ +121 ms] calculateSha: LocalDirectory: 'F:\Projects\Flutter\hello_world\build\app\outputs\flutter-apk'/app.apk
[ +107 ms] calculateSha: reading file took 105us
[+1061 ms] calculateSha: computing sha took 1060us
[  +17 ms] ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
[  +50 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree F:\Projects\Flutter\hello_world\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[ +113 ms] Exit code 0 from: C:\Users\dms24\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree F:\Projects\Flutter\hello_world\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +35 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hello_world" (Raw: "com.example.hello_world")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello_world" (Raw: "hello_world")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello_world.MainActivity" (Raw: "com.example.hello_world.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +55 ms] Stopping app 'app.apk' on Lenovo K33a42.
[   +2 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell am force-stop com.example.hello_world
[+1224 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell pm list packages com.example.hello_world
[+1593 ms] package:com.example.hello_world
[   +8 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell cat /data/local/tmp/sky.com.example.hello_world.sha1
[ +118 ms] 6f73fb2877aa14f3fdf6af75600aee6215d1d39f
[   +2 ms] Latest build already installed.
[  +35 ms] Lenovo K33a42 startApp
[   +9 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez     
enable-checked-mode true --ez verify-entry-points true com.example.hello_world/com.example.hello_world.MainActivity
[+1174 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.hello_world/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +789 ms] Observatory URL on device: http://127.0.0.1:60576/vt2pOeuEE1w=/
[   +3 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward tcp:0 tcp:60576
[ +104 ms] 64179
[   +2 ms] Forwarded host port 64179 to device port 60576 for Observatory
[  +15 ms] Caching compiled dill
[  +97 ms] Connecting to service protocol: http://127.0.0.1:64179/vt2pOeuEE1w=/
[ +668 ms] Successfully connected to service protocol: http://127.0.0.1:64179/vt2pOeuEE1w=/
[   +2 ms] Waiting for Lenovo K33a42 to report its views...
[  +26 ms] Waiting for Lenovo K33a42 to report its views... (completed in 23ms)
[  +46 ms] DevFS: Creating new filesystem on the device (null)
[  +92 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.hello_world/code_cache/hello_worldBSBNKD/hello_world/)
[  +51 ms] Updating assets
[ +318 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +18 ms] Syncing files to device Lenovo K33a42...
[  +40 ms] Scanning asset files
[  +16 ms] <- reset
[  +36 ms] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:hello_world/main.dart 52345d72-ab5c-4f22-8846-da82297c120d
[   +2 ms] <- 52345d72-ab5c-4f22-8846-da82297c120d
[ +201 ms] Updating files
[ +476 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Lenovo K33a42... (completed in 742ms)
[   +4 ms] Synced 1.3MB.
[  +40 ms] <- accept
[  +14 ms] Connected to _flutterView/0xa4106810.
[  +39 ms] Flutter run key commands.
[  +20 ms] r Hot reload. 🔥🔥🔥
[  +23 ms] R Hot restart.
[   +3 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on Lenovo K33a42 is available at: http://127.0.0.1:64179/vt2pOeuEE1w=/
[+2157 ms] V/BoostFramework(28503): mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
[   +1 ms] V/BoostFramework(28503): mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
[   +2 ms] V/BoostFramework(28503): mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
[  +47 ms] V/BoostFramework(28503): mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
[   +1 ms] V/BoostFramework(28503): mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
[   +1 ms] V/BoostFramework(28503): BoostFramework() : mPerf = com.qualcomm.qti.Performance@e2c16a6
[+5687 ms] W/IInputConnectionWrapper(28503): reportFullscreenMode on inexistent InputConnection
[+1876 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[+2542 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +158 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[  +58 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[  +26 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +132 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +141 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +497 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +510 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +492 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +503 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +500 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +499 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +503 ms] I/Adreno  (28503): DequeueBuffer: dequeueBuffer failed
[ +134 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.hello_world/code_cache/hello_worldBSBNKD/hello_world/)
[  +31 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.example.hello_world/code_cache/hello_worldBSBNKD/hello_world/)
[ +305 ms] Service protocol connection closed.
[   +2 ms] Application finished.
[   +8 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward --list
[  +75 ms] Exit code 0 from: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward --list
[  +15 ms] 34c5d6ec tcp:63805 tcp:58549
           34c5d6ec tcp:64179 tcp:60576
[   +5 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward --remove tcp:63805
[ +102 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward --remove tcp:64179
[  +68 ms] executing: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward --list
[  +55 ms] Exit code 0 from: C:\Users\dms24\AppData\Local\Android\sdk\platform-tools\adb.exe -s 34c5d6ec forward --list
[  +21 ms] "flutter run" took 46,324ms.
[ +175 ms] ensureAnalyticsSent: 166ms
[   +2 ms] Running shutdown hooks
[  +39 ms] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
Analyzing try1...
No issues found! (ran in 21.8s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (2 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Hi @dms24081999,
Please provide minimal complete reproducible code sample that shows the issue. Also elaborate on the steps you took when the error occurs.
Thanks.

**Comment by dms24081999** [comment]
> Hi @dms24081999,
> Please provide minimal complete reproducible code sample that shows the issue. Also elaborate on the steps you took when the error occurs.
> Thanks.
Yes @darshankawar Sir, I've updated it.

**Comment by darshankawar** [comment]
Hi @dms24081999,
There's similar open issue describing your case, [35900](https://github.com/flutter/flutter/issues/35900).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by dms24081999** [comment]
Alright @darshankawar Sir.
But #35900 issue is related to Android API level 28, and I guess this problem is fixed for API level 28 and above, as I've tested it on 2 Devices with API level 28 and API level 29.
The current issue for this problem is below API level 28 devices. And not on API level 28 and above as mentioned on #35900 logs.
Thanks.

**Comment by darshankawar** [comment]
@dms24081999,
In that case, you may comment on that ticket and mention that the issue still persists on api < 28 and provide logs.
Thanks.
