### ISSUE TITLE
Text gets truncated in Flutter Web

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#63467]
## Steps to Reproduce

1. Use Flutter version `1.21.0-8.0.pre.140`.
2. Build a Flutter app with `Text` widgets using `flutter build web --release`.
3. Run the app in Chrome.

**Expected results:** text should be displayed normally.

**Actual results:** text is cut off arbitrarily, i.e. sometimes words are missing at the end of text and sometimes letters are missing.

## Demo

1. `flutter create demo`
2. `cd demo`
3. `flutter build web --release`
4. `cd build/web`
5. `http-server` (Node package)
6. Open Flutter web app in Chrome on Mac.

This results in the following:

The `times:` text **at the end** is not rendered at some scales.  
See the [this **screen recording**](https://i.imgur.com/3vvy7i9.mp4).

**Comment by creativecreatorormaybenot** [comment]
This issue seems to have disappeared in `pre.140`.

**Comment by creativecreatorormaybenot** [comment]
In `1.21.0-8.0.pre.111` this issue is **not** present.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.21.0-8.0.pre.140`. I was able to reproduce this on Windows Firefox and MacOS Chrome, Firefox, and Safari. Did not reproduce on Windows Chrome or Edge. This seems to have regressed when comparing to beta.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.140, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-8.0.pre.140 at C:\Development\flutter_master
    • Framework revision c8d051295a (5 hours ago), 2020-08-11 00:26:02 -0400
    • Engine revision a62703778b
    • Dart version 2.10.0 (build 2.10.0-5.0.dev e2a67723ca)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

The issue also happens with `flutter run` debug build.

**Comment by yjbanov** [comment]
@mdebbar this looks as if we measure one thing using canvas then, when rendering using HTML, we render another thing. Would you be able to triage this?

**Comment by mdebbar** [comment]
Hmmm I was able to repro this. The issue is that canvas always returns the same measurements regardless of zoom level, but the text in DOM elements could change its width in different zoom levels (not always).

**Comment by creativecreatorormaybenot** [comment]
@mdebbar I am not able to reproduce this on Mac Chrome anymore - has this been fixed?

**Comment by markusaksli-nc** [comment]
@creativecreatorormaybenot I can still reproduce this on Windows Firefox on latest master `1.22.0-2.0.pre.105`.
![Annotation 2020-08-28 151939](https://user-images.githubusercontent.com/68219924/91560117-f3c2d700-e941-11ea-98d3-651deb8f3180.png)
@mdebbar why were the `found in release` and `regression` labels removed?
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.105, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.105 at C:\Development\flutter_master
    • Framework revision cad4d1333e (11 hours ago), 2020-08-27 17:48:05 -0700
    • Engine revision 77dd1c05b9
    • Dart version 2.10.0 (build 2.10.0-67.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```
</details>

**Comment by creativecreatorormaybenot** [comment]
@markusaksli-nc Yes, I can find it again as well, unfortunately.

**Comment by creativecreatorormaybenot** [comment]
@mdebbar Definitely still happens on `1.22.0-12.0.pre` (`dev` channel).

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.23.0-8.0.pre.164` in desktop Firefox (does not repro in Chromium browsers).
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.164, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.164 at C:\Development\flutter_master
    • Framework revision b3bd9e6924 (3 hours ago), 2020-10-05 19:52:03 -0700
    • Engine revision 284ef2217d
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.68

• No issues found!
```
</details>

**Comment by IoanaAlexandru** [comment]
This also happens when installing a Flutter app as a PWA. Tested it on a Pixel 4 device.

**Comment by ajbarry** [comment]
Also reported in #64904

**Comment by ajbarry** [comment]
We can confirm that this issue is the default experience (no manual zoom override needed) for PWAs and a flutter web app opened in a webview on andriod such as the result of using Google Lens to scan a QR code app url.

@mdebbar This is definitely a regression from our perspective and holding up a release because we are unable to find a work-around. We sincerely hope P4 doesn't mean this issue gets kicked to the basement.

**Comment by MichaelDark** [comment]
To temporary fix it, use this workaround: 

```dart
extension on TextStyle {
  /// Temporary fix the following Flutter Web issues
  /// https://github.com/flutter/flutter/issues/63467
  /// https://github.com/flutter/flutter/issues/64904#issuecomment-699039851
  /// https://github.com/flutter/flutter/issues/65526
  TextStyle get withZoomFix => copyWith(wordSpacing: 0);
}
...
textStyle.withZoomFix
...
TextStyle(...).withZoomFix
...
Theme.of(context).textTheme.bodyText1.withZoomFix
```

Related:
https://github.com/flutter/flutter/issues/63467
https://github.com/flutter/flutter/issues/64904#issuecomment-699039851
https://github.com/flutter/flutter/issues/65526

**Comment by wapchief** [comment]
Channel master, 1.23.0-14.0.pre.111 Same thing

**Comment by creativecreatorormaybenot** [comment]
@mdebbar This seems to happen on `stable` a lot more now, without zooming.

Is there still a flag to use different measurement?

**Comment by otopba** [comment]
Channel master, 1.24.0-8.0.pre.255
I have same issue

**Comment by mdebbar** [comment]
@creativecreatorormaybenot using canvaskit should fix this issue (i.e. `flutter run --web-renderer=canvaskit ...`).

**Comment by creativecreatorormaybenot** [comment]
@mdebbar That is true, however, https://github.com/flutter/flutter/issues/54330#issue-596967016 prevents us from doing it - not being able to render emojis is even worse than having text cut off when you have a lot of content using them.

**Comment by sanekyy** [comment]
@mdebbar 
We would be very happy to use CancasKit however we cannot because of https://github.com/flutter/flutter/issues/70620 and https://github.com/flutter/flutter/issues/70618

**Comment by mdebbar** [comment]
This issue should've been fixed some time ago. Could you verify and let me know if you still see it?

**Comment by creativecreatorormaybenot** [comment]
@mdebbar I am certain it still exists.

We have one production web app using the `beta` channel and one using the `dev` channel. For both of them we have been regularly receiving/experiencing behavior of the text being cut off for the last few months. The last time I remember maybe 2 weeks ago. They are both regularly deployed, always with the latest Flutter version on their respective channels.

I am not sure what information I can provide you with to aid resolving this issue. I suppose I could send screenshots or links, but I do not have a minimum reproducible sample.

**Comment by markusaksli-nc** [comment]
I'm not seeing this anywhere anymore using the default `flutter create` project on the latest master `1.27.0-5.0.pre.49`

**Comment by eli1stark** [comment]
Still have the issue on the master `1.27.0-5.0.pre.52`

**Comment by creativecreatorormaybenot** [comment]
@markusaksli-nc It does not happen with every device/browser/os combination. However, some users experience it all the time with certain apps.

**Comment by markusaksli-nc** [comment]
Any certain combination for me to test?

@eli1stark Can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and mention which browser on which os?

**Comment by eli1stark** [comment]
Here you go:

```
import 'package:flutter/material.dart';

void main() => runApp(ClippingText());

class ClippingText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          width: 300.0,
          height: 40.0,
          color: Colors.blue,
          child: Center(
            child: Text(
              'text',
              maxLines: 3,
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 9.0,
                color: Colors.white,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Result:
![Text Clipping](https://i.imgur.com/xC6P5Bl.png)

I noticed that possible roots of this problem are 
*  small `fontSize`, usually less than 9
* `maxLines` property

Solutions:
1. Increase `fontSize` of the text (will solve the problem)
2. Remove `maxLines` property (will solve the problem)
3. But if you need to use the exact small `fontSize` and `maxLines` property as I do then you can use my part-time fix below that will solve this problem until Flutter Team fix it

```
import 'package:flutter/material.dart';

void main() => runApp(ClippingText());

class ClippingText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          width: 300.0,
          height: 40.0,
          color: Colors.blue,
          child: Center(
            child: Column(
              children: [
                const Spacer(),
                ListView(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  children: [
                    Expanded(
                      child: Text(
                        'text',
                        maxLines: 3,
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          fontSize: 9.0,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ],
                ),
                const Spacer(),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by eli1stark** [comment]
Looks like this issue is solved in the 2.0.0 version of the Flutter.

**Comment by Bilonik** [comment]
> Looks like this issue is solved in the 2.0.0 version of the Flutter.

Still having the same issue on 2.0 and dev branch, had to modify text size to solve the problem

**Comment by alnah005** [comment]
Still having the same issue using Flutter 2.0.3 stable. Had to modify height or add Strut to fix the problem.

**Comment by ZhangLiuCheng** [comment]
> Still having the same issue on Android using Flutter 2.0.3 stable. Had to modify height or add Strut to fix the problem.

I have the same problem as you, so I revert the version back to  < 405c85fe7ee688156028e87a623c9153d05591b2 (HEAD -> beta, tag: 1.24.0-10.1.pre)>.

**Comment by TomasWeg** [comment]
Same here! Using `dart:developer` does not solve the problem, my logs are printed like so:
`[LOG] [26/03/2021 19:35:19] [DEBUG] Sending POST request…ccount/login with parameters null. Body: true
`

Using the same in a mobile app, nothing happens.

**Comment by dgurudot** [comment]
Having same issue even on latest stable, master and beta.

I see text in italics, some text getting cut off with ellipses.

Kindly suggest workarounds or fix

**Comment by dgurudot** [comment]
> To temporary fix it, use this workaround:
> 
> ```dart
> extension on TextStyle {
>   /// Temporary fix the following Flutter Web issues
>   /// https://github.com/flutter/flutter/issues/63467
>   /// https://github.com/flutter/flutter/issues/64904#issuecomment-699039851
>   /// https://github.com/flutter/flutter/issues/65526
>   TextStyle get withZoomFix => copyWith(wordSpacing: 0);
> }
> ...
> textStyle.withZoomFix
> ...
> TextStyle(...).withZoomFix
> ...
> Theme.of(context).textTheme.bodyText1.withZoomFix
> ```
> 
> Related:
> #63467
> [#64904 (comment)](https://github.com/flutter/flutter/issues/64904#issuecomment-699039851)
> #65526

@MichaelDark Are you suggesting to use this workaround all over in app where I am displaying text ? I am confused so can kindly provide more details ?

**Comment by MichaelDark** [comment]
@dgurudot Exactly, use it across the app, and/or add this fix to all fonts in your your `Theme` in `MaterialApp`

**Comment by mdebbar** [comment]
Is this still an issue?
