### ISSUE TITLE
package(google_sign_in): google auth (use redirect instead of popup) sign in

### ISSUE THREAD

**Issue by praveeno** [flutter/flutter#64457]
For Web Sign in with google_sign_in, I want to start login process with redirect instead of popup, 
same as signInWithRedirect instead of signInWithPopup.

I can't find a method or config for that?
Let me know what all are possible solutions.

**Comment by Abhishek01039** [comment]
Hi @praveeno 
can you please try this package https://pub.dev/packages/google_sign_in_web?
Thanks

**Comment by praveeno** [comment]
Hi @Abhishek01039, Thank you for suggest, although google_sign_in_web readme suggest that 

> it gets automatically added to your dependencies by depending on google_sign_in: ^4.1.0.

**Comment by ditman** [comment]
In order to implement this, there's two new configuration options that need to be passed to the [init of the plugin](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart#L68-L73):

`ux_mode='redirect'` and (optionally) `redirect_uri`. [See docs](https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig).

This would be considered as a new, web-only feature, since neither Android nor iOS seem to support different login flows.

**Comment by shashwatadi** [comment]
I found the way to do it using the example app in firebase_auth, but looks like the redirect triggers the main() again and all state is lost.

**Comment by ted-marozzi** [comment]
I am having the same issue. 

 A big reason for this is many browser block pop up, in I believe iOS now ships with pop ups block by default (without any indication that a pop up was attempted). I can however sign into non flutter web apps on the same browser as they navigate to a different page instead of trying to spawn a pop up.
 
 @shashwatadi how did you manage to do that?

**Comment by ted-marozzi** [comment]
@ditman or anyone, I will happily make a pull request if I work this out but right now I need some help.

i managed to expose the ux_mode and get the redirect oauth flow working, but when google navigated back to my app the callback url only had the id_token, but not the access_token. Thus I could authenicate with firebase but not access google apis.

I did some digging and found in the initial oauth url had the query parameter response_type=id_token permission, but the google identity docs say it needs to be set to response_type=token to get back the access_token. Manually modifying the url indeed did return the access_token but I am not sure how to do this in the dart code.

Could someone point me in the right direction?

From reading the underlying google js client library docs its not even clear if it supports the ux_mode redirect with access token.

Any info is appreciated!

**Comment by ted-marozzi** [comment]
Okay since my last comment I realised even if we could get the access token on the client side, we would have to manually refresh it. So the actual solution would involve the change ditman mentioned (exposing the ux_mode and redirect_uri params) and also a new method.

```dart
Future<GoogleSignInAccount?> getRedirectResults();
```

This method would be called by the client after the app has been redirected to the redirect_uri and would enable the client code to have access to the managed GoogleSignInAccount, this can then be used to authenticate with backend services and google apis in a completely managed way the same as the current signIn() method.

A similar approach was taken by the firebase team [sign in with redirect](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/signInWithRedirect.html) and [get redirect result](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/getRedirectResult.html)

If the team google thinks this is a good idea then I will attempt to implement it.

**Comment by ditman** [comment]
> A big reason for this is many browser block pop up, in I believe iOS now ships with pop ups block by default (without any indication that a pop up was attempted). I can however sign into non flutter web apps on the same browser as they navigate to a different page instead of trying to spawn a pop up.

Quick comment. This would only happen if the pop-up was triggered outside of user interaction. If you have a "Sign In" button that triggers the signIn method of the plugin, the pop-up should *not* be blocked.

Are you attempting to use `signIn` without the user doing anything? (there's a `silentSignIn` method for that instead, which attempts to recover the session).

**Comment by ted-marozzi** [comment]
Thanks for your reply @ditman I appreciate it. I was doing funky stuff with my state. I was using a user interaction to set state to a future builder which would sign in.
```dart
class _SignInWithGoogleState extends State<_SignInWithGoogle> {
  // This is used to prevent the future from
  bool signingIn = false;
  static final _logger = Logger("_SignInWithGoogle");

  @override
  Widget build(BuildContext context) {
    final googleSignInButtonView = Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Padding(
          padding: const EdgeInsets.only(top: 16.0, bottom: 16.0, right: 16.0),
          child: Image.asset("assets/images/icon/google-logo.png"),
        ),
        Padding(
          padding: const EdgeInsets.only(right: 16.0),
          child: Text(
            "Sign in with Google",
            style: Theme.of(context).textTheme.bodyText1,
          ),
        ),
      ],
    );
    _logger.finer("Build method called");
    return Column(
      children: [
        OutlinedButton(
          onPressed: () async {
            _logger.info("Sign in with google pressed");
            widget.analytics.logEvent(name: "sign_in_with_google_pressed");
            setState(() {
              signingIn = true;
            });
          },
          child: FutureBuilder(
            future: signingIn
                ? widget.controller.signInWithGoogle()
                : Future.value(false),
            builder: (context, AsyncSnapshot<bool> snapshot) {
              if (snapshot.hasError) {
                _logger.shout(
                    "googleSignIn() future builder returned an error or no data",
                    snapshot.error,
                    snapshot.stackTrace);
              }
              _logger.fine(
                  "googleSignIn() future builder called with connection state ${snapshot.connectionState} and with bool value: ${snapshot.data}");

              switch (snapshot.connectionState) {
                case ConnectionState.done:
                  return googleSignInButtonView;
                case ConnectionState.none:
                case ConnectionState.waiting:
                case ConnectionState.active:
                  return const CircularProgressIndicator();
              }
            },
          ),
        ),
        _TroubleSigningIn(analytics: widget.analytics),
      ],
    );
  }
}
```
I simplified to this and the pop up was no longer blocked.
```dart
class _SignInWithGoogleState extends State<_SignInWithGoogle> {
  bool _signingIn = false;
  static final _logger = Logger("_SignInWithGoogle");

  @override
  Widget build(BuildContext context) {
    final googleSignInButtonView = Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Padding(
          padding: const EdgeInsets.only(top: 16.0, bottom: 16.0, right: 16.0),
          child: Image.asset("assets/images/icon/google-logo.png"),
        ),
        Padding(
          padding: const EdgeInsets.only(right: 16.0),
          child: Text(
            "Sign in with Google",
            style: Theme.of(context).textTheme.bodyText1,
          ),
        ),
      ],
    );

    _logger.finer("Build method called");
    return Column(
      children: [
        OutlinedButton(
          onPressed: () async {
            _logger.info("Sign in with google pressed");
            widget.analytics.logEvent(name: "sign_in_with_google_pressed");
            setState(() {
              _signingIn = true;
            });
            await widget.controller.signInWithGoogle();
            setState(() {
              _signingIn = false;
            });
          },
          child: _signingIn
              ? const CircularProgressIndicator()
              : googleSignInButtonView,
        ),
        _TroubleSigningIn(analytics: widget.analytics),
      ],
    );
  }
}
```
Still, on desktop I believe its a better ux to allow redirect and would like to hear from the flutter team whether or not its worth my time to try implementing my solution above.

**Comment by ditman** [comment]
We have this big pending migration:

* https://github.com/flutter/flutter/issues/88084

But it also has ux_mode, so maybe this is worth the effort. 

(This feature also needs some cooperation from the routing strategy on the redirect after the user authenticates.)

**Comment by thailocnexle** [comment]
I have to write lib for this, try with this https://github.com/kunkaamd/google_sign_in_web_redirect

**Comment by ditman** [comment]
Wow, that looks great @thailocnexle!

**Comment by amorenew** [comment]
Is redirect mode will solve popup blockers?
<img width="317" alt="Screen Shot 2022-10-31 at 9 05 47 PM" src="https://user-images.githubusercontent.com/2842459/199176612-fdbad13d-7953-4ac0-842f-f8559a6efc47.png">

**Comment by amorenew** [comment]
@thailocnexle it works fine for me no need for popups anymore
after successful redirection, I used the id token in my firebase auth
```
         final idToken = GoogleSignWeb.instance?.token;
          final credential = GoogleAuthProvider.credential(
            idToken: idToken,
          );
          final authResult =
              await FirebaseAuth.instance.signInWithCredential(credential);

```

**Comment by ditman** [comment]
> Is redirect mode will solve popup blockers? <img alt="Screen Shot 2022-10-31 at 9 05 47 PM" width="317" src="https://user-images.githubusercontent.com/2842459/199176612-fdbad13d-7953-4ac0-842f-f8559a6efc47.png">

@amorenew popup blockers are solved by triggering the popup on a click handler, and not programmatically (for programmatic access use `signInSilently`).

**Comment by amorenew** [comment]
@ditman Click handler didn't solve the blockers issue, it works fine on localhost so I suspect it is maybe an extension or settings on chrome, for safari it blocks by default on my safari settings
So for most cases, the redirection will be the right solution 

<img width="522" alt="Untitled" src="https://user-images.githubusercontent.com/2842459/199311714-93538308-9ee7-40fa-9735-e8b8abafc738.png">

**Comment by ditman** [comment]
> Click handler didn't solve the blockers issue, it works fine on localhost so I suspect it is maybe an extension or settings on chrome, for safari it blocks by default on my safari settings

It's impossible to debug your issue if you don't show the code of your `onClick` handler for your sign-in button, or the errors that you may be getting in the JS console.

> **So for most cases, the redirection will be the right solution**

This is very inaccurate advice, and I won't endorse it. Popup sign-in works just fine, unless your click handler is doing stuff that consumes "user activation" before calling the `signIn` method. (Otherwise, our bug tracker would be on fire?)

**Comment by amorenew** [comment]
@ditman I tried your demo website from this comment
https://github.com/flutter/flutter/issues/54768#issuecomment-616748489
And this is the error I got is:
`Uncaught PlatformException(idpiframe_initialization_failed, Cookies are not enabled in current environment., google_sign_in)`
If the user is blocking third-party cookies then it will make an issue
https://github.com/flutter/flutter/issues/52338#issuecomment-642181625

Chrome while blocking third-party cookies
https://user-images.githubusercontent.com/2842459/199646617-da77cd1a-bbda-4023-b2cb-7a8d8cf94244.mp4

I found that the "HTTPS Everywhere" extension and other extensions blocks third-party cookies
From google blog:

> we now intend to begin phasing out third-parties cookies in Chrome in the second half of 2024

https://blog.google/products/chrome/update-testing-privacy-sandbox-web/
More info about blocking third-parties cookies by default in chrome 2024:
https://privacysandbox.com/intl/en_us/open-web/#proposals-for-the-web
<img width="583" alt="Screen Shot 2022-11-03 at 6 38 11 AM" src="https://user-images.githubusercontent.com/2842459/199648709-e1a9fabc-3cd8-45ca-a55c-ad0b3465896a.png">

**Comment by ditman** [comment]
> So the safest/reliable scenario is redirection mode

I think the new Google Identity Services SDK will enable authentication and authorization without relying on cookies, here's the announcement:

* https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html

**However**, now that Flutter web has custom URL strategies, the redirect ux_mode should be doable, and work purely client-side.

**Comment by amrgetment** [comment]
@ditman I tried your fix
```
  /// This method is only support on web platforms.
  Future<UserCredential> getRedirectResult() async {
    return UserCredential._(this, await _delegate.getRedirectResult());
  }

```

I wonder if you could make it nullable so I don't get an js error if no data

`Error: Expected a value of type 'FutureOr<UserCredentialJsImpl>', but got one of type 'Null'
`

**Comment by adar2378** [comment]
Yeah, we should have something like this in flutter as well
https://developers.google.com/identity/gsi/web/guides/display-button#redirect_mode

**Comment by amrgetment** [comment]
@ditman I made getRedirectResult() nullable on firebaseAuth
https://github.com/firebase/flutterfire/pull/12025

**Comment by amrgetment** [comment]
@adar2378 
open redirection to google page
```
  final GoogleAuthProvider authProvider = GoogleAuthProvider();
  googleSignInScopes.forEach(authProvider.addScope );
 
  await firebaseAuth.signInWithRedirect(authProvider);
```
receive the result by

`final Future<UserCredential?> userCredential = firebaseAuth.getRedirectResult();`

override dependency to use nullable getRedirectResult

```
dependency_overrides:
  # made getRedirectResult nullable so it won't stop the app
  firebase_auth:
    git:
      url: https://github.com/amrgetment/flutterfire.git
      ref: web_nullable_getRedirectResult
      path: packages/firebase_auth/firebase_auth
  firebase_auth_web:
    git:
      url: https://github.com/amrgetment/flutterfire.git
      ref: web_nullable_getRedirectResult
      path: packages/firebase_auth/firebase_auth_web


```

**Comment by adar2378** [comment]
> @adar2378
> 
> open redirection to google page
> 
> ```
> /// https://developers.google.com/identity/protocols/oauth2/scopes
> final List<String> googleSignInScopes = <String>[
>   'https://www.googleapis.com/auth/userinfo.email',
>   'https://www.googleapis.com/auth/userinfo.profile',
>   'openid',
> ];
> 
>   final GoogleAuthProvider authProvider = GoogleAuthProvider();
>   googleSignInScopes.forEach(authProvider.addScope );
>  
>   await firebaseAuth.signInWithRedirect(authProvider);
> ```
> 
> receive the result by
> 
> `final Future<UserCredential?> userCredential = firebaseAuth.getRedirectResult();`
> 
> override dependency to use nullable getRedirectResult
> 
> ```
> dependency_overrides:
>   # made getRedirectResult nullable so it won't stop the app
>   firebase_auth:
>     git:
>       url: https://github.com/amrgetment/flutterfire.git
>       ref: web_nullable_getRedirectResult
>       path: packages/firebase_auth/firebase_auth
>   firebase_auth_web:
>     git:
>       url: https://github.com/amrgetment/flutterfire.git
>       ref: web_nullable_getRedirectResult
>       path: packages/firebase_auth/firebase_auth_web
> ```

Thanks for the answer. I meant to say with only google_sign_in package is it possible to do? I don't want to use firebase_auth.

**Comment by amrgetment** [comment]
@adar2378 Not yet, as far as I know, but with firebase auth it works fine

**Comment by JohnCido** [comment]
Is there any update on this?

Our app does not use Firebase Auth since it uses internal auth API. And the use of [Flutter Rust Bridge](https://cjycode.com/flutter_rust_bridge/manual/miscellaneous/web-cross-origin) Buffer sharing feature requires the `Cross-Origin-Opener-Policy` header to be set to `same-origin`. Which will break the Google Sign In popup.

It would be really great if this is supported natively.
