### ISSUE TITLE
Gradle build failed to produce an .aab file when multiple flavorDimensions specified

### ISSUE THREAD

**Issue by brightknight08** [flutter/flutter#65264]
I was having trouble building a flutter app with `2 flavor dimensions` and `2 flavors` for each dimension (total of 4 variants, 
excluding the debug and release modes).

here's a minimal flutter app repo: https://github.com/brightknight08/flutter_build_appbundle_error to reproduce

when I do `flutter build appbundle --release --flavor signedprod`, it would display 
```clli

`flutter doctor -v`
```cli
PS E:\lab\flutter_build_appbundle_error> flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\asdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:\asdk
    • Java binary at: E:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at E:\as
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\tim_m\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • P[redacted]...droid-arm64 • Android 10 (API 29)

• No issues found!
PS E:\lab\flutter_build_appbundle_error>
```

**Comment by TahaTesser** [comment]
Hi @brightknight08 
Can you please this [solution](https://github.com/flutter/flutter/issues/52905#issuecomment-611306346)
Thank you

**Comment by brightknight08** [comment]
thank you for pointing me in that direction @TahaTesser . is this the supposed "fix"?

**Comment by TahaTesser** [comment]
Hi @brightknight08 
Wanted to make sure if it the same issue or not, if the workaround is working or not, it's for APK but after more testing, APK builds without using that workaround. The issue is only app bundle only.`.aab` file is generated if you go build but the tool can't locate 

<img width="289" alt="Screenshot 2020-09-09 at 2 08 17 PM" src="https://user-images.githubusercontent.com/48603081/92575422-eee91600-f2a5-11ea-9952-3bf935a16cf1.png">


`flutter build apk --release --flavor signedprod`
Interestingly,  it works with APK 
```bash
You are building a fat APK that includes binaries for android-arm,
android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app
bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform
        android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform
        android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configur
        e-abi-split
Removed unused resources: Binary resource data reduced from 46KB to 37KB: Removed 20%
Running Gradle task 'assembleSignedprodRelease'...                      
Running Gradle task 'assembleSignedprodRelease'... Done            15.3s
✓ Built build/app/outputs/flutter-apk/app-signedprod-release.apk (15.3MB)
```


`flutter build appbundle --release --flavor signedprod`
[appbundle_logs.txt](https://github.com/flutter/flutter/files/5193777/appbundle_logs.txt)



<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 216dee60c0 (8 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.107, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.107 at /Users/tahatesser/Code/flutter_master
    • Framework revision 54ade88365 (4 hours ago), 2020-09-08 22:08:57 -0700
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (3 available)            
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by brightknight08** [comment]
yes, apk build works flawlessly no questions about it. just for `appbundles`.
I tried the solution you pointed me too and it still can't find aab. I even changed the `.apk` to `.aab` to no avail.

```cli
...
 variant.assemble.doLast {
         def apkFile = variant.outputs.first().outputFile as File
         System.out.println("apk file: ${apkFile.path}")
         def flavorNames = variant.productFlavors.collect{flavor -> flavor.name}.toList()
         System.out.println("flavorNames: ${flavorNames.join('-')}")
         def targetApkFile = new File(apkFile.parentFile.path, 
             "app-${flavorNames.withIndex().collect{flavorName, index -> index == 0 ? 
                   flavorName : 
                   flavorName.capitalize()}.join('')}-${variant.buildType.name}.aab") // < [this one]
         System.out.println("target apk file: ${targetApkFile.path}")
...
```

**Comment by TahaTesser** [comment]
@brightknight08 
Thanks for the confirmation, same here that's why I labeled it.

**Comment by PiotrWpl** [comment]
Hi @TahaTesser ,

I found the root cause of the issue.
Let's use example from @brightknight08 with **--flavor signedprod**
Based on https://chromium.googlesource.com/external/github.com/flutter/flutter/+/master/packages/flutter_tools/lib/src/android/gradle.dart#926
Flutter tools are looking for output files here:
* outputs/bundle/release/app.aab
* outputs/bundle/release/app-release.aab
* outputs/bundle/signedprodrelease/app.aab
* outputs/bundle/signedprodrelease/app-**signedprod**-release.aab

But when we have multiple flavor dimensions, then they are split by "-" in the file name. So the output file is:
* outputs/bundle/signedprodrelease/app-**signed-prod**-release.aab

I hope that this information will help to resolve the issue on the Flutter tools side.

For now, I'm sharing my workaround:
In the android/app/build.gradle file please add
```
android {
(..)
  applicationVariants.all { variant ->
        variant.outputs.all {
          (..)
          def taskSuffix = variant.name.capitalize()
          def bundleTaskName = "bundle${taskSuffix}"
          if (tasks.findByName(bundleTaskName)) {
               def copyAABTask = tasks.create(name: "copyAndRenameAab${taskSuffix}", type: Copy) {
                    def bundleBuildDir = "${buildDir}/outputs/bundle"
                    def originalDirPath = "${variant.productFlavors.name.join()}${variant.buildType.name}"
                    def originalFileName = "${project.archivesBaseName}-${variant.productFlavors.name.join('-')}-${variant.buildType.name}.aab"
                    from "${bundleBuildDir}/${originalDirPath}/${originalFileName}"
                    into "${bundleBuildDir}/${variant.buildType.name}/"
                    rename ("${originalFileName}", "app.aab")
                }
                tasks[bundleTaskName].finalizedBy = [copyAABTask]
            }
       }
  }
}
```

Thanks to that, our final bundle file will be available here:
outputs/bundle/release/app.aab

so the flutter tool will not exit with the error.

**Comment by ValentinTaleb** [comment]
@PiotrWpl Thanks a lot. I struggled with this issue for weeks.

Any idea when a fix will be applied in Flutter so we don't have to use this workaround anymore?

**Comment by PiotrWpl** [comment]
Sorry, but I'm not a Flutter Tool dev, I just had a similar issue, and did some debugging. I have no idea how to fix that and create a PR directly in the Flutter.

**Comment by brunobowden** [comment]
# WORKAROUND

This is based on @PiotrWpl Oct [workaround](https://github.com/flutter/flutter/issues/65264#issuecomment-707013948) - thanks to them. I've added a lot more documentation and support for copying apks as well. I have an issue where `flutter build appbundle` works locally but fails on the CI. Otherwise it's been working well for me. You can see the merge PR in: https://github.com/WorldHealthOrganization/app/pull/1798.

```
    applicationVariants.all { variant ->
        variant.outputs.all {
            def taskSuffix = variant.name.capitalize()

            def bundleTaskName = "bundle${taskSuffix}"
            if (tasks.findByName(bundleTaskName)) {
                def copyAABTask = tasks.create(name: "copyAndRenameAab${taskSuffix}", type: Copy) {
                    // Cmd:     flutter build appbundle --release --flavor prod
                    // Depends: bundleProdRelease
                    // Task:    copyAndRenameAabProdRelease
                    // Src:     build/app/outputs/bundle/prodRelease/app-prod-release.aab
                    // Dst:     build/app/outputs/bundle/release/app.aab
                    def bundleBuildDir = "${buildDir}/outputs/bundle"
                    def originalDirPath = "${variant.productFlavors.name.join()}${variant.buildType.name}"
                    def originalFileName = "${project.archivesBaseName}-${variant.productFlavors.name.join('-')}-${variant.buildType.name}.aab"
                    from "${bundleBuildDir}/${originalDirPath}/${originalFileName}"
                    into "${bundleBuildDir}/${variant.buildType.name}/"
                    rename ("${originalFileName}", "app.aab")
                }
                tasks[bundleTaskName].finalizedBy = [copyAABTask]
            }

            def apkTaskName = "assemble${taskSuffix}"
            if (tasks.findByName(apkTaskName)) {
                def copyApkTask = tasks.create(name: "copyAndRenameApk${taskSuffix}", type: Copy) {
                    // Cmd:     flutter build apk --flavor prod --release
                    // Depends: assembleProdRelease (builds the apk)
                    // Task:    copyAndRenameApkProdRelease
                    // Src:     build/app/outputs/apk/prod/release/app-prod-release.apk
                    // Dst:     build/app/outputs/apk/release/app-release.apk
                    def bundleBuildDir = "${buildDir}/outputs/apk"
                    def originalDirPath = "${variant.productFlavors.name.join()}/${variant.buildType.name}"
                    def originalFileName = "${project.archivesBaseName}-${variant.productFlavors.name.join('-')}-${variant.buildType.name}.apk"
                    from "${bundleBuildDir}/${originalDirPath}/${originalFileName}"
                    into "${bundleBuildDir}/${variant.buildType.name}/"
                    rename ("${originalFileName}", "app-${variant.buildType.name}.apk")
                }
                tasks[apkTaskName].finalizedBy = [copyApkTask]
            }
        }
    }
```

**Comment by christopherfujino** [comment]
when we fix this bug, we should update the flavorsTest here: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flavors_test.dart

**Comment by btrautmann** [comment]
Leaving a note here because I spent a bunch of time debugging this today, and the cause turned out to be different. We only declare a single `flavorDimension` but do have 4 `productFlavors` (all with the same dimension)... However, we have camel-cased our `productFlavors` which doesn't seem to be too common place (we really don't want to be using product flavors in the first place, see https://github.com/flutter/flutter/issues/63041#issuecomment-1097033920).

Anyway, invoking `flutter build appbundle` locally (MacOS) succeeds, but it started failing on CI. The only discernible difference was the OS (was using linux on CI), so I changed that to use MacOS as well, and it succeeded. I finally determined (based on a hint from this thread) that the issue may be related to my flavor names.

Changing the flavor name from `myCoolFlavor` to `mycoolflavor` fixed the issue. I'm not sure if this should be considered its own bug, or a bug at all, since I'm not too sure how expected it is to use camelcase flavors. But I wanted to post this here in case other unfortunate souls run into the same thing.

Lastly, the fixes above (changing the `aab` output location) were not necessary for me.

**Comment by PritamSangani** [comment]
I have created a PR which should fix this. The gradle tool was not looking for the kebab/param-cased version of the bundle file and so was failing to find the bundle file at the end of the build.

**Comment by exaby73** [comment]
I can still reproduce this issue with `Master (3.10.0-7.0.pre.17)`.

<details>
<summary>Logs</summary>

```console
# Building appbundle fails
issue_65264 ❯ fl build appbundle --flavor signedprod

Upgrading build.gradle
Running Gradle task 'bundleSignedprodRelease'...
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1336 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Running Gradle task 'bundleSignedprodRelease'...                   34.0s
Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/nabeelparkar/dev/nevercode/issue_65264/build, but the tool couldn't find it.

# Building APK works fine
issue_65264 ❯ fl build apk --flavor signedprod

Running Gradle task 'assembleSignedprodRelease'...                  5.4s
✓  Built build/app/outputs/flutter-apk/app-signedprod-release.apk (17.0MB).
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.10.0-7.0.pre.17, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
    • Flutter version 3.10.0-7.0.pre.17 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3ba249a6b3 (77 minutes ago), 2023-04-18 10:46:33 +0530
    • Engine revision c4396f9f60
    • Dart version 3.1.0 (build 3.1.0-12.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 112.1.50.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by gnprice** [comment]
There's some experimentation and discussion on #124797 (thanks @pepompeu!) which I think will be helpful for resolving this issue.

See in particular @andrewkolos's repro recipe at https://github.com/flutter/flutter/pull/124797#issuecomment-1528652807, and my suggestion at https://github.com/flutter/flutter/pull/124797#issuecomment-1528666541 to have `--flavor` take a comma-separated list of flavors, as in `flutter build appbundle --flavor someFlavor,someOtherFlavor`.
