### ISSUE TITLE
I can't view build dashboard logs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#65912]
I'm trying to debug https://github.com/flutter/flutter/issues/65775
I go to https://flutter-dashboard.appspot.com/#/build
I click on one of the yellow squares.
If I click OPEN LOG FOR ATTEMPT #1, it eventually says I'm not allowed to see logs.
If I click DOWNLOAD ALL LOGS, it just spins idly.
If I click LOGIN it doesn't do anything.

I'm not really sure what I'm doing wrong? I'm pretty sure my account (ian.hickson@gmail.com) is allow-listed.

**Comment by godofredoc** [comment]
This is a problem with the authentication plugin. You'll need to click login and refresh when your name appears in the top right part of the dashboard you'll be able to download the logs.

**Comment by godofredoc** [comment]
@CaseyHillers can you please link to the auth plugin bug?

**Comment by Hixie** [comment]
I click "SIGN IN". A new window pops up, shows a progress indicator, and then goes away. I refresh the dashboard (with or without shift). It still says "SIGN IN" in the top right, not my name.

**Comment by CaseyHillers** [comment]
Thanks for filing this @Hixie 

I think this is similar to https://github.com/flutter/flutter/issues/59086

The Google sign in plugin has a race condition on web that causes it to crash https://github.com/flutter/flutter/issues/52338, and it was prevalent when auto sign in was on. Now the dashboard's auto sign in is disabled to mitigate the sign in crashes.

Can you share the error that is showing up in your browser's dev tools when you click the sign in button?

**Comment by Hixie** [comment]
I don't get any errors in the console. There's a couple of warnings about cross-site cookies being blocked.

**Comment by CaseyHillers** [comment]
According to https://github.com/flutter/flutter/issues/59086#issuecomment-690735904 blocking third party cookies causes issues for the sign in plugin.

\cc @ditman was there a new version of the google sign in web plugin that surfaces errors like this now?

**Comment by ditman** [comment]
@CaseyHillers that is correct, the latest version of the plugin should properly throw exceptions when things are breaking on the JS SDK. The changes were:

* almost all operations, (normally silentSignIn): may throw a PlatformException with code `idpiframe_initialization_failed` (see [this](https://developers.google.com/identity/sign-in/web/reference#error_codes)) if the init method failed.
* signIn(): may throw a PlatformException with different codes, depending on how the sign in failed. Mainly: `popup_closed_by_user` or `access_denied` (see [this](https://developers.google.com/identity/sign-in/web/reference#error_codes_2)).

It depends on how the app decides to handle those.

@Hixie what browser, version and OS are you using? I remember seeing warnings about cross-site cookies being blocked (in the future)

Another thing, when the dashboard enters this weird state, can you please run in the JS console?

`gapi.auth2.getAuthInstance()`

(That should *not* be null.)

**Comment by CaseyHillers** [comment]
This is great @ditman! I'll follow up today in Cocoon to update to the latest version and catch these errors to mitigate these issues.

**Comment by ditman** [comment]
Apologies for the breakage, @Hixie, @CaseyHillers, and thanks for your patience! This bug is being kind of hard to track down (especially because I haven't been able to reproduce it locally so far :/)

**Comment by CaseyHillers** [comment]
@Hixie the dashboard should now be logging all Google Sign in exceptions. Can you log them here?

**Comment by CaseyHillers** [comment]
@Hixie I believe the issues you saw with Google Sign In should be fixed with the try catch.

To follow up on the other issues:
https://github.com/flutter/flutter/issues/54509 is tracking stack driver logs being viewable by the Flutter community. With the migration to LUCI, this will no longer be needed.

https://github.com/flutter/flutter/issues/59086 is tracking the build dashboard sign in issues. I'm going to increase the priority as now it's possible to catch these exceptions.

Feel free to reopen if I missed anything.

**Comment by Hixie** [comment]
Sorry for the delay answering, the updates got buried in my inbox since I get too many notifications.

This still seems to happen as described above, and I still can't see devicelab logs.

> @Hixie what browser, version and OS are you using? I remember seeing warnings about cross-site cookies being blocked (in the future)

Chrome 81.0.4044.113 (Official Build) (64-bit)
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Linux
JavaScript | V8 8.1.307.28
Flash | 32.0.0.414 /home/ianh/.config/google-chrome/PepperFlash/32.0.0.414/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

**Comment by Hixie** [comment]
(I don't see any exceptions.)

**Comment by Hixie** [comment]
Full logs in the console from loading the build dashboard, clicking SIGN IN (which shows a spinner briefly):
```
A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/#/build:1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
canvaskit.js:311 Fetch finished loading: GET "https://unpkg.com/canvaskit-wasm@0.17.3/bin/canvaskit.wasm".
html_dart2js.dart:18175 XHR finished loading: GET "https://flutter-dashboard.appspot.com/assets/FontManifest.json".
html_dart2js.dart:32857 Fetch finished loading: GET "https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf".
cb=gapi.loaded_0:228 XHR finished loading: GET "https://content.googleapis.com/discovery/v1/apis/analytics/v3/rest?fields=k…Url%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid&pp=0".
html_dart2js.dart:32857 Fetch finished loading: GET "https://flutter-dashboard.appspot.com/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf".
html_dart2js.dart:32857 Fetch finished loading: GET "https://flutter-dashboard.appspot.com/assets/fonts/MaterialIcons-Regular.otf".
js_helper.dart:1857 [Violation] 'setTimeout' handler took 100ms
js_helper.dart:1857 [Violation] 'setTimeout' handler took 121ms
/#/build:1 A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/get-branches".
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/build-status?branch=master".
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/get-status?branch=master".
js_helper.dart:1857 [Violation] 'load' handler took 165ms
js_helper.dart:1857 [Violation] 'requestAnimationFrame' handler took 324ms
html_dart2js.dart:18175 XHR finished loading: GET "https://flutter-dashboard.appspot.com/assets/AssetManifest.json".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/8620741?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/1227763?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/682784?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/11690192?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/61075224?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/54371434?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars0.githubusercontent.com/u/8975114?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/32477115?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/389558?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/22987568?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars1.githubusercontent.com/u/211513?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/551196?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars1.githubusercontent.com/u/8357481?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars1.githubusercontent.com/u/37366956?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/16964204?v=4".
js_helper.dart:1857 [Violation] 'requestAnimationFrame' handler took 76ms
html_dart2js.dart:18175 XHR finished loading: GET "https://flutter-dashboard.appspot.com/assets/assets/chromium.png".
html_dart2js.dart:18175 XHR finished loading: GET "https://flutter-dashboard.appspot.com/assets/assets/apple.png".
html_dart2js.dart:18175 XHR finished loading: GET "https://flutter-dashboard.appspot.com/assets/assets/android.png".
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/get-status?lastCommitKey=a…dGVyL2FlNjMwYjQyYTZiMTM3NTAyYzFhNzc4ZDc0M2U3MDhlZjljM2M1MDIM&branch=master".
js_helper.dart:1857 [Violation] 'requestAnimationFrame' handler took 281ms
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars0.githubusercontent.com/u/6343103?v=4".
js_helper.dart:1857 [Violation] 'requestAnimationFrame' handler took 58ms
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/16854239?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars0.githubusercontent.com/u/38391570?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars3.githubusercontent.com/u/62214257?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars1.githubusercontent.com/u/19588?v=4".
html_dart2js.dart:18175 XHR finished loading: GET "https://avatars2.githubusercontent.com/u/122189?v=4".
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/get-branches".
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/build-status?branch=master".
html_dart2js.dart:18578 XHR finished loading: GET "https://flutter-dashboard.appspot.com/api/public/get-status?branch=master".
js_helper.dart:1857 [Violation] 'load' handler took 188ms
```

After doing this, I remain not signed in even after reloading.

**Comment by ditman** [comment]
One last test, @Hixie, can you run the following in the JS console, when your dashboard is in the weird state?

`gapi.auth2.getAuthInstance()`

(That should not be null.)

Thanks!

**Comment by Hixie** [comment]
I get back:
```
gapi.auth2.getAuthInstance()
Iw {fm: dx, mY: {…}, Te: ƒ, tj: ƒ, Fq: ƒ, …}
Fq: ƒ ()
LR: ƒ ()
Te: ƒ ()
YC: ƒ ()
attachClickHandler: ƒ ()
currentUser: sw {le: Cw, P1: rw, Yb: pw}
disconnect: ƒ ()
fm: dx {Ba: {…}, uS: "single_host_origin", uW: true, kv: true, Pq: null, …}
getInitialScopes: ƒ ()
grantOfflineAccess: ƒ ()
isSignedIn: sw {le: false, P1: rw, Yb: pw}
mY: {Te: ƒ, tj: ƒ, Fq: ƒ, uj: ƒ, uI: ƒ, …}
signIn: ƒ ()
signOut: ƒ ()
tj: ƒ ()
uI: ƒ ()
uj: ƒ ()
__proto__: Object
```
...but nothing particularly notable happens otherwise.

**Comment by CaseyHillers** [comment]
@ditman is there anything the dashboard app can do in this case?

**Comment by ditman** [comment]
Not sure, I'll take a look and see if I can repro the issue, then see where the breakage is (maybe it's some captured exception that we're not seeing anywhere)

**Comment by CaseyHillers** [comment]
@ditman i'm going to unassign myself for now as I'm not sure what more is needed on the cocoon side.

**Comment by godofredoc** [comment]
Moving out of the infra ticket queue as this may take some time to fix and infra depends on fixes to the plugin.

**Comment by Hixie** [comment]
Can we remove the authentication requirement then? I have to be able to see logs to do my work, as do plenty of other non-Googlers.

**Comment by dnfield** [comment]
See also: https://github.com/flutter/flutter/issues/49484

**Comment by pcsosinski** [comment]
what needs to happen to get this closed?

**Comment by CaseyHillers** [comment]
> what needs to happen to get this closed?

After the DeviceLab migration to LUCI, this will be obsolete. Logs on LUCI are public. Tracked in https://github.com/flutter/flutter/projects/151#card-51747372

**Comment by godofredoc** [comment]
Moving as P3, this bug is waiting on getting the devicelab migration to luci to get it closed.
