### ISSUE TITLE
Make focused element visible when keyboard appears

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6602]
1. Create a long form with input elements.
2. Tap on an input box close to the bottom.
3. Keyboard covers the form and the input is no longer visible.

On Android native, there's an explicit scroll to make the focused element visible when keyboard appears.

**Comment by eseidelGoogle** [comment]
This sounds like something we had working at one point.  @Hixie  or @mpcomplete would know.

**Comment by Hixie** [comment]
The code that wants to do this is:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/focus.dart#L195

**Comment by HansMuller** [comment]
I am unable to reproduce this; it's possible that the underlying problem has been fixed over the past couple of weeks.  Here's the test case I used (on Android):

```
import 'package:flutter/material.dart';

class FocusVisibilityDemo extends StatefulWidget {
  @override
  _FocusVisibilityDemoState createState() => new _FocusVisibilityDemoState();
}

class _FocusVisibilityDemoState extends State<FocusVisibilityDemo> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text('Focus Visibility Demo')),
      body: new Form(
        child: new Block(
          padding: const EdgeInsets.all(16.0),
          children: new List.generate(10, (index) {
            return new InputFormField(
              labelText: 'Input $index',
            );
          }).toList(),
        ),
      ),
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new FocusVisibilityDemo()));
}
```

**Comment by mehmetf** [comment]
This does not seem to happen anymore. Somehow it got fixed. Thanks for looking into it!

**Comment by 123qws** [comment]
This is not fixed yet if the Input elements are in the nested blocks:

For example:
```
import 'package:flutter/material.dart';

class FocusVisibilityDemo extends StatefulWidget {
  @override
  _FocusVisibilityDemoState createState() => new _FocusVisibilityDemoState();
}

class _FocusVisibilityDemoState extends State<FocusVisibilityDemo> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text('Focus Visibility Demo')),
        body: new Block(children: [
          new Card(
            child: new Block(
              padding: const EdgeInsets.all(16.0),
              children: new List.generate(10, (index) {
                return new Input(
                  labelText: 'Inputs $index',
                );
              }).toList(),
            ),
          ),
          new Card(child: new Text('666'))
        ]));
  }
}

void main() {
  runApp(new MaterialApp(home: new FocusVisibilityDemo()));
}
````

If you tap on any input box that is close to the bottom. It won't scroll down to make input box visible.

**Comment by eseidelGoogle** [comment]
I'm confused as to if this should be tagged for leafy or not.

It's not on the list of high-priority bugs @mehmetf sent me earlier this week, it looks like it mostly got fixed before but some edge cases remain?

**Comment by weisong0** [comment]
Looks like the issue is fixed after we uses new scrolling system, i.e, switches from nested blocks to SingleChildScrollView and BlockBody. Thanks Eric!

**Comment by eseidelGoogle** [comment]
Thanks!

**Comment by weisong0** [comment]
Hi team, this issue happened again. It seems like the current logic does not have a explicit scroll to make focused element visible.

https://github.com/flutter/flutter/blob/df1a01b3b3f3fa0203a07458079bff62e8820524/packages/flutter/lib/src/widgets/focus_manager.dart

Here's the test case:
```dart
import 'package:flutter/material.dart';

class FocusVisibilityDemo extends StatefulWidget {
  @override
  _FocusVisibilityDemoState createState() => new _FocusVisibilityDemoState();
}

class _FocusVisibilityDemoState extends State<FocusVisibilityDemo> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text('Focus Visibility Demo')),
      body: new Form(
        child: new SingleChildScrollView(
            child: new ListBody(
              children: new List.generate(10, (index) {
                return new Column(children: [
                  new Text(index.toString()),
                  new TextField()]);
              }).toList(),
            ),
          ),
        ),
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new FocusVisibilityDemo()));
}

```

**Comment by collinjackson** [comment]
@weisong0 I believe this is being tracked in https://github.com/flutter/flutter/issues/10826

**Comment by weisong0** [comment]
Thanks! @collinjackson

**Comment by Rishab-1065** [comment]
@collinjackson I have two form field inside a form and SingleChildScrollView as the parent container for all. When i click on textfield the keyboard pops up and hide the focused field.

**Comment by sethladd** [comment]
Thanks for the comment. Can you share a small repro case?

**Comment by collinjackson** [comment]
Is this issue a dupe of #10826? If so we should probably move the discussion there.

**Comment by Rishab-1065** [comment]
This is my whole view. Please have a look @sethladd @collinjackson 
 
       return new Scaffold(
        key: _scaffoldKey,
        body: new SingleChildScrollView(
            controller: scrollController,
            child: new Container(
              padding: new EdgeInsets.all(16.0),
              decoration: new BoxDecoration(image: backgroundImage),
              child: new Column(
                children: <Widget>[
                  new Container(
                    height: screenSize.height / 2,
                    child: new Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        new Center(
                            child: new Image(
                          image: logo,
                          width: (screenSize.width < 500)
                              ? 120.0
                              : (screenSize.width / 4) + 12.0,
                          height: screenSize.height / 4 + 20,
                        ))
                      ],
                    ),
                  ),
                  new Container(
                    height: screenSize.height / 2,
                    child: new Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        new Form(
                          key: formKey,
                          autovalidate: autovalidate,
                          child: new Column(
                            children: <Widget>[
                              new InputField(
                                  hintText: "Email",
                                  obscureText: false,
                                  textInputType: TextInputType.text,
                                  textStyle: textStyle,
                                  textFieldColor: textFieldColor,
                                  icon: Icons.mail_outline,
                                  iconColor: Colors.white,
                                  bottomMargin: 20.0,
                                  validateFunction: validations.validateEmail,
                                  onSaved: (String email) {}),
                              new InputField(
                                  hintText: "Password",
                                  obscureText: true,
                                  textInputType: TextInputType.text,
                                  textStyle: textStyle,
                                  textFieldColor: textFieldColor,
                                  icon: Icons.lock_open,
                                  iconColor: Colors.white,
                                  bottomMargin: 30.0,
                                  validateFunction:
                                      validations.validatePassword,
                                  onSaved: (String password) {}),
                              new RoundedButton(
                                buttonName: "Get Started",
                                onTap: _handleSubmitted,
                                width: screenSize.width,
                                height: 50.0,
                                bottomMargin: 10.0,
                                borderWidth: 0.0,
                                buttonColor: Theme.of(context).primaryColor,
                              ),
                            ],
                          ),
                        ),
                        new Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: <Widget>[
                            new TextButton(
                              buttonName: "Create Account",
                              onPressed: () => onPressed("/SignUp"),
                              buttonTextStyle: buttonTextStyle,
                              textAlign: TextAlign.center,
                            ),
                            new TextButton(
                              buttonName: "Need Help?",
                              onPressed: _onPressed,
                              buttonTextStyle: buttonTextStyle,
                              textAlign: TextAlign.center,
                            )
                          ],
                        )
                      ],
                    ),
                  )
                ],
              ),
            )));

**Comment by Hixie** [comment]
Progress is tracked in https://github.com/flutter/flutter/issues/10826.
There is no current progress to report, unfortunately. We've been focused on accessibility and internationalisation recently. I'll see if we can get this on the radar again.

**Comment by TheInitializer** [comment]
This isn't fixed for me. I have `TextField`s  as `title`s of `ListTile`s with `autofocus` set to `true`, and it doesn't autoscroll to make the text field visible.

I'm not experiencing the issue in #10826 (the keyboard seems to show just fine, and I can scroll down to make the text field visible, but it doesn't scroll down there automatically).

Also, if I'm at the top of the list and the TextField is being created off-screen at the bottom, it doesn't popup the keyboard at all until I scroll down enough so that the TextField is on the screen. Then there's a bit of a jittery glitch thing and the keyboard pops up, but the TextField is still behind the keyboard and I have to scroll down even more to see it.

**Comment by amaan75** [comment]
Got the  same issue, the keyboard hides the text input behind it, is there a workaround or a temp fix available?

**Comment by zoechi** [comment]
@amaan75 @anandgsaga this should be fixed in master #18291

**Comment by diegoveloper** [comment]
Same issue here using textfields inside a ListView

**Comment by rromley** [comment]
@Hixie 
Please reopen this issue.
Thanks

**Comment by shakil807g** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.6.3-pre.7, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.0)
[!] Connected devices
    ! No devices available

i am still facing this issue

**Comment by rromley** [comment]
@Hixie 
I've created a new issue. 
Please check:
https://github.com/flutter/flutter/issues/21046

Thanks!

**Comment by skeksk91** [comment]
I also got same issue when textfields are in Listview.

**Comment by pavankumarkatakam** [comment]
Im also having the same problem, my password field is not in any Listview or no nested scaffold.

**Comment by zoechi** [comment]
@pavankumarkatakam 

> my password field is not in any Listview

Wrapping it with a `ListView` or `SingleChildScrollView` is usually what fixes it.

**Comment by jyothyjohny** [comment]
add resizeToAvoidBottomPadding: true in Scaffold ..it would make the textfields visible
