### ISSUE TITLE
[iOS] adding autoFillHint to TextFormField breaks FocusScope.of(context).nextFocus()

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#66144]
In the following example the focus changes to the password field like expected but then quickly jumps back to the email field.

This happens on iOS 13.5 as well as on iOS 14 in the current master and beta versions. It seems to work on Android, macOS and web.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: AutofillGroup(
          child: Form(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  TextFormField(
                    decoration: InputDecoration(labelText: "E-Mail"),
                    textInputAction: TextInputAction.next,
                    autofillHints: [AutofillHints.username],
                    keyboardType: TextInputType.emailAddress,
                    onFieldSubmitted: (_) => FocusScope.of(context).nextFocus(),
                  ),
                  SizedBox(height: 8),
                  TextFormField(
                    decoration: InputDecoration(labelText: "Password"),
                    obscureText: true,
                    textInputAction: TextInputAction.done,
                    autofillHints: [AutofillHints.password],
                  ),
                  SizedBox(height: 8),
                  RaisedButton(
                    child: Text("Submit"),
                    onPressed: () {},
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.257, on Mac OS X 10.15.6 19G2021 x86_64, locale en-CH)
    • Flutter version 1.22.0-10.0.pre.257 at /Users/ben/flutter
    • Framework revision 7a4d8e190c (5 minutes ago), 2020-09-18 14:42:04 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 1691DB1F-88AF-4CE4-9472-842AE98D0373 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

**Comment by cbenhagen** [comment]
This also happens when using `TextField` or `CupertinoTextField`. Also explicitly requesting focus of a node has the same issue:
```dart
CupertinoTextField(
  placeholder: ("E-Mail"),
  textInputAction: TextInputAction.next,
  autofillHints: [AutofillHints.username],
  keyboardType: TextInputType.emailAddress,
  onSubmitted: (_) => FocusScope.of(context).requestFocus(fn),
),
```

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: AutofillGroup(
          child: Form(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  TextFormField(
                    decoration: InputDecoration(labelText: "E-Mail"),
                    textInputAction: TextInputAction.next,
                    // autofillHints: [AutofillHints.username],
                    keyboardType: TextInputType.emailAddress,
                    onFieldSubmitted: (_) => FocusScope.of(context).nextFocus(),
                  ),
                  SizedBox(height: 8),
                  TextFormField(
                    decoration: InputDecoration(labelText: "Password"),
                    obscureText: true,
                    textInputAction: TextInputAction.done,
                    autofillHints: [AutofillHints.password],
                  ),
                  SizedBox(height: 8),
                  RaisedButton(
                    child: Text("Submit"),
                    onPressed: () {},
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.269 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • iPhone 11 (mobile) • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by LongCatIsLooong** [comment]
It seems `unmarkText` sends an editing state update to the framework and the framework calls "requestKeyboard" in return. This couldn't have happened before because the email field has already dropped the connection by the time "unmarkText" was called. But now it's made possible by the ios text input plugin autofill mechanism that allows unfocused fields to send editing state updates. 

We should also update the framework `updateEditingValue` implementation to prevent requestKeyboard being called in this case.

**Comment by LongCatIsLooong** [comment]
Shouldn't be closed just yet. If the email field is not empty this still happens.

**Comment by GefaketHD** [comment]
I think the problem here is that TextInputAction.next does handle the focus of the next FormField by itself already. So actually the nextFocus() is called twice. Try removing the onFieldSubmitted from the first field and go again.

**Comment by GefaketHD** [comment]
I actually just found out that - at least on latest master 1.22.0-10.0-pre.340 - your code is working as expected. If I am not mistaken. But it doesn't matter here, if you put the onFieldSubmitted or not.

**Comment by Henrik-glt** [comment]
The issue seems to occur when **textInputAction** is set to **TextInputAction.next** AND **autofillHints** is set.
In my case **autofillHints** is set to: **autofillHints: [AutofillHints.username],**
@GefaketHD removing call to nextFocus() does not work unfortunately.

Hopes a hot fix is released asap

**Comment by lchwe** [comment]
I'm having this same issue as well. It gets buggy when combining a `Form` widget with a `AutofillGroup`. I have email and password fields, and after typing an email address, when the user taps on the password field, the email field remains focused, forcing the user to tap on the password field again to change focus. When `AutofillGroup` is removed, focus works as expected. This is only happening on iOS. Android works as expected. If`Form` is removed focus works as expected as well.

**Comment by donaldkg** [comment]
I am having this problem as well in iOS 14 and flutter version 1.22.1. I have two fields for login email and password TextFormField inside AutofillGroup and inside Form. After I type the email and click on password textfield, the focus jumps back to email field and start at the beginning. Is there any workaround?

**Comment by lzhuor** [comment]
> I am having this problem as well in iOS 14 and flutter version 1.22.1. I have two fields for login email and password TextFormField inside AutofillGroup and inside Form. After I type the email and click on password textfield, the focus jumps back to email field and start at the beginning. Is there any workaround?

Encountering the exact problem as described by @donaldkg. Working fine on Android but problematic on iOS. Removing `autofillHints` resolved it.

**Comment by christopherfujino** [comment]
This was fixed in https://github.com/flutter/flutter/pull/68043.

**Comment by LongCatIsLooong** [comment]
This bug is likely introduced in: https://github.com/flutter/flutter/pull/52126 (merged on April 20). It disrupts the user flow, as it moves the focus to the wrong text field.
However, it
- Supposedly only affects iOS.
- Is not devastating, as it does not seem to crash the app or render the app unusable.

Also as was pointed out in a comment, it's easy to mistake this issue for a different issue where they specified `TextInputAction.next` and called `nextFocus()` in `onSubmitted` at the same time, causing the focus to shift twice.

Risk:

#68043 has non-trivial changes that touches other parts of text input (~300 lines in non-test files, although most of them are code comments). 
It slightly changed the communication protocol between the engine text input plugin and the framework so there could be undetected bugs. 

https://github.com/flutter/engine/pull/21303 should make the bug harder to reproduce (engine roll: https://github.com/flutter/flutter/commit/fce475bd0fb86a464168cc76401849f99728dbb0).

**Comment by lchwe** [comment]
@christopherfujino This bug is still reproducible in v1.22.3.

**Comment by christopherfujino** [comment]
> @christopherfujino This bug is still reproducible in v1.22.3.

Yes. This issue was closed because it was resolved in master by PR https://github.com/flutter/flutter/pull/68043. By applying the `cp: 1.22` label, I requested that it be cherry-picked into stable. Please see [Flutter Cherrypick Process](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process) for more information.

**Comment by lzhuor** [comment]
Thank you @christopherfujino , may I ask where can we check what commits have been included in which version.

For example, I would like to check if this commit is in the 1.20.4-pre in the dev channel. Do you recommend us checking the Git repo commit tree or any other ways of checking it?

**Comment by LongCatIsLooong** [comment]
@lzhuor that can be found on the commit's github page. See https://github.com/flutter/flutter/wiki/Where%27s-my-Commit%3F.
