### ISSUE TITLE
Keyboard doesn't close on beta

### ISSUE THREAD

**Issue by JulyEve** [flutter/flutter#66873]

**Comment by zlfnn** [comment]
hi, i am also facing this problem, do you solve it?
In android, when the TextFormField is focused,  the close button of the keyboard is useless！！！

**Comment by JulyEve** [comment]
> hi, i am also facing this problem, do you solve it?
> In android, when the TextFormField is focused, the close button of the keyboard is useless！！！

**Comment by darshankawar** [comment]
@JulyEve 
See [this](https://github.com/flutter/flutter/issues/66791) issue for reference. The issue has been fixed in master and stable but may not have reached beta.
Please switch to latest master or stable and try again. It should work properly there.
Closing this issue, since the issue is already fixed in master and stable.
If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by cjng96** [comment]
@darshankawar Hello, It's reproduced with latest master on my galaxy S8+. 

I am not sure wether this bug is fixed and revived or not fixed on the master branch.
because I saw your comment on the issue(https://github.com/flutter/flutter/issues/66791)

the test flutter version you done on is 1.22.0-10.0.pre.405. but my current latest version is different.(channel master 1.22.0-10.0.pre.428)

<details>
<summary>flutter doctor</summary>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, **1.22.0-10.0.pre.428**, on Microsoft Windows [Version 10.0.19041.508], locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
[!] Android Studio (not installed)
[✓] VS Code (version 1.49.2)
[✓] Connected device (5 available)

! Doctor found issues in 1 category.
</details>

**Comment by darshankawar** [comment]
@JulyEve @zlfnn There's similar open issue describing your case, [66791](https://github.com/flutter/flutter/issues/66791).
Please follow-up there for updates.
Closing this as duplicate.
