### ISSUE TITLE
Web : TextField odd behavior when programmatically removing and adding text

### ISSUE THREAD

**Issue by NebulaFox** [flutter/flutter#67499]
DartPad example:
https://dartpad.dev/d4622f01ae17d19122d61e116b7224c5

There a couple of problems with TextField that my DartPad example can demonstrate. I believe these problems are related to each other.

## Problem 1

1. Type H in the text field. The code will then add a space and move the character to the end.
2. Backspace. The code will remove the space and the character H

**Expected results:** 

No characters

**Actual results:**

A non-deletable H

### Note

The example code running integrated in an app gives a different result, that the TextField clears itself correctly.

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.14.6 18G6032, locale en-GB)
    • Flutter version 1.22.0 at /usr/local/flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
```

## Problem 2

Comment out the line in `_updateText` results in the correct behaviour.

```
_shouldIgnoreNextTextChange = true;
```

This line ignores the next `_onTextChange()` **after** `_controller.clear()`

1. Type H in the text field. The code will then add a space and move the character to the end.
2. Backspace. 

**Expected results:** 

No characters

**Actual results:** 

A H and a space character remain. This is due to the an unexpected `_onTextChange` called after the `_controller.clear()`. To break this down:

1. Type H -> `_onTextChange` called with a H.
2. Code adds a space -> `_onTextChange` called with H and a space.
3. Type Backspace -> `_onTextChange` called with a H.
4. Code clears the text value -> `_onTextChange` called with empty string.
5. Unexpected `_onTextChange` called with a H.
6. Code adds a space -> `_onTextChange` called with H and a space.

## Working Case

I have found that only doing one add or only doing one take away results in the correct behaviour.

### Case 1

Restoring the DartPad example and commenting out the lines in `_updateText` results in the correct behaviour.

```
      final newText = text + ' ';
      _controller.value = TextEditingValue(
        text: newText,
        selection: TextSelection.collapsed(offset: newText.length),
        composing: TextRange.empty,
      );
```

1. Type H and Space
2. Type Backspace. Code clears text field.

### Case 2

Restoring the DartPad example and commenting out the lines in `_updateText` results in the correct behaviour.

```
      _controller.clear();
      _shouldIgnoreNextTextChange = true;
```

1. Type H. Code adds a space.
2. Backspace twice.

### Case 3

Restoring the DartPad example

1. Type H. Code adds a space.
2. Type a Space.
3. Backspace twice.

**Comment by darshankawar** [comment]
@NebulaFox 
Tried your code sample on latest beta and on Android device 8.1.0, but in both cases(after commenting and uncommenting _shouldIgnoreNextTextChange = true;), I was able to delete the character with space properly after tapping back button.

[67499.mp4.zip](https://github.com/flutter/flutter/files/5339601/67499.mp4.zip)

Which device are you seeing this behavior on ?

**Comment by NebulaFox** [comment]
Updated to include another case

@darshankawar Copied what you did, and yes can confirm on device the DartPad example works on device in both cases (after commenting and uncommenting `_shouldIgnoreNextTextChange = true;`). However, the app that I have pulled the example code from still has the problem. Looking into this issue further, the DartPad example on device can replicate the problem by using an emoji 🌙. If using the emoji replicates the problems, I will update the initial comment to reflect this.

Does the DartPad example work in your browser using H or an 🌙? I am on Firefox 81.0.1 (64-bit).

**Comment by darshankawar** [comment]
@NebulaFox You are correct.
It occurs on Chrome and Firefox both. Tested on latest beta.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0
    • Web Server (web)          • web-server                               •
      web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 86.0.4240.75

• No issues found!

```

</details>

**Comment by NebulaFox** [comment]
@darshankawar Did you find the example worked on the android device with the emoji?

**Comment by nturgut** [comment]
As far as I understand, you are only able to generate the problem in dartpad.

If the problem does not happen on the flutter/flutter head, I will close the issue. This means dartpad uses an earlier version of the framework and issue is fixed.

**Comment by NebulaFox** [comment]
Bug still exists on

```
Flutter (Channel beta, 1.22.1, on Mac OS X 10.14.6 18G6032, locale en-GB)
```

I will upload project with bug present and a video shortly.

**Comment by mdebbar** [comment]
When I tried this on master in my machine and couldn't reproduce. But you are right, the flutter version in dartpad can reproduce the issue.

So I did a bisect and it turns out this PR: https://github.com/flutter/flutter/pull/68043 fixed it. I'm not sure when DartPad will update the flutter version, but for now you can use flutter's master channel and it should work as expected.
