### ISSUE TITLE
Running apps with sound null safety from VSCode or Android Studio throws 

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#68627]
Running simple Flutter apps with null safety from VSCode or Android Studio triggers a throw in the WidgetInspectorService:

## Repro steps for VSCode

1. Create simple null safety app:
   ```
   flutter create nulltest
   cd nulltest
   dart migrate --apply-changes --no-web-preview
   ```
1. Open VSCode: `code .`
1. Open `lib/main.dart`
1. Open `launch.json` (cmd-shift-p + type launch.json)
1. Change:
   ```
            "type": "dart",
   ```
   to:
   ```
            "type": "dart",
            "args": [
                "--enable-experiment=non-nullable",
            ],

   ```
1. Hit F5

=>

```
[38;5;248mLaunching lib/main.dart on Android SDK built for x86 in debug mode...[39;49m
 lib/main.dart
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:53806/6tm7oVyrvok=/ws
D/EGL_emulation( 7933): eglMakeCurrent: 0xeec7eda0: ver 3 0 (tinfo 0xe3a8c350)

[38;5;248m════════ Exception caught by Flutter framework ═════════════════════════════════[39;49m
[38;5;244mThe following _CastError was thrown during a service extension callback for "ext.flutter.inspector.setPubRootDirectories":[39;49m
type 'Null' is not a subtype of type 'String' in type cast

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      List.length= (dart:core-patch/growable_array.dart:148:12)[39;49m
[38;5;244m#1      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>.<anonymous closure>[39;49m
 package:flutter/…/widgets/widget_inspector.dart
[38;5;244m#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)[39;49m
[38;5;244m#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>[39;49m
 package:flutter/…/widgets/widget_inspector.dart
[38;5;244m#4      BindingBase.registerServiceExtension.<anonymous closure>[39;49m
 package:flutter/…/foundation/binding.dart
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Error handling 'serviceExtension' custom request: ext.flutter.inspector.setPubRootDirectories: (-32000) Server error
{"exception":"type 'Null' is not a subtype of type 'String' in type cast","stack":"#0      List.length= (dart:core-patch/growable_array.dart:148:12)\n#1      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:889:20)\n#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)\n#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:885:20)\n#4      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:32)\n<asynchronous suspension>\n#5      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart)\n#6      _runExtension (dart:developer-patch/developer.dart:84:23)\n","method":"ext.flutter.inspector.setPubRootDirectories"}

```

## Repro steps for Android Studio

1. Step 1 from VSCode above
1. Open Android Studio
1. File > Open Existing Project + pick folder with project
1. Click Run > Edit Configurations, and in 'Additional arguments' add `--enable-experiment=non-nullable`
1. Hit F5

## Version information

mit-macbookpro4:foo mit$ flutter --version
Flutter 1.24.0-2.0.pre.86 • channel master • https://github.com/flutter/flutter.git
Framework • revision dde20448f7 (12 hours ago) • 2020-10-20 00:59:56 -0400
Engine • revision ea2aea1c61
Tools • Dart 2.11.0 (build 2.11.0-234.0.dev)

**Comment by mit-mit** [comment]
cc @jacob314

**Comment by vsmenon** [comment]
@mit-mit @pcsosinski - is this blocking TP2?  If so, we should mark P0.

@jacob314 - it looks like this is widget inspection code.  Can you please take a look?

**Comment by mit-mit** [comment]
Yes, I think it is. We'd like for the core workflows to work, and the README.md in the new null safety example has a step to open in VSCode and hit F5. That's how I found this.

**Comment by jacob314** [comment]
`flutter test --enable-experiment=non-nullable test/widgets/widget_inspector_test.dart`
has a lot of failures. I've fixed the specific error related to this test and I'm working on fixing the other errors so the tests pass.

**Comment by vsmenon** [comment]
@jacob314 - do we need to fix all of these for tp2?  Do you have a sense of how more there is?

**Comment by mit-mit** [comment]
With Flutter `1.24.0-2.0.pre.98`, this bug still throws for me, but with a slightly different stack trace:

```

When the exception was thrown, this was the stack
#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:894
#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:882
#4      BindingBase.registerServiceExtension.<anonymous closure>
package:flutter/…/foundation/binding.dart:546
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
Error handling 'serviceExtension' custom request: ext.flutter.inspector.setPubRootDirectories: (-32000) Server error
{"exception":"'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.","stack":"#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:894:16)\n#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:882:17)\n#4      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:32)\n<asynchronous suspension>\n","method":"ext.flutter.inspector.setPubRootDirectories"}

```

**Comment by DanTup** [comment]
I'm seeing this error on latest master too (without any specific opt-in of null safety - though I don't know if it's no by default). I tweaked it to print the arguments out and got this:

```
flutter: Exception: Index: 1, Params: {arg0: file:///Users/danny/Dev/TestStuff/foo, isolateId:
flutter: isolates/1397158588675607}
```

It seems like the code assumes that the number of arguments exactly matches the `argX` count, but there's also an `isolateId` in there so the count doesn't match.

It's not clear from the code whether the `isolateId` is supposed to be there though (it wouldn't be passed to `callback`) so I'm not sure what the fix should be.

**Comment by mit-mit** [comment]
Yes, @DanTup I also see that now. That is a regression. Null safety is *not* on by default in a new project created by `flutter create`, but opening a such in VSCode and hitting F5 leads to:

```
hen the exception was thrown, this was the stack
#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:894
#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:882
#4      BindingBase.registerServiceExtension.<anonymous closure>
package:flutter/…/foundation/binding.dart:546
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
Error handling 'serviceExtension' custom request: ext.flutter.inspector.setPubRootDirectories: (-32000) Server error
{"exception":"'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.","stack":"#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:894:16)\n#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:882:17)\n#4      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:32)\n<asynchronous suspension>\n","method":"ext.flutter.inspector.setPubRootDirectories"}
```

**Comment by pedromassangocode** [comment]
I'm seeing lots of waring after upgrade `master` channel.

@mit-mit should I open a new issue for those logs bellow or we can track it here?

![Screen Shot 2020-10-21 at 13 05 47](https://user-images.githubusercontent.com/67424416/96717331-3337fd80-139e-11eb-8174-569242916ea9.png)

**Comment by mit-mit** [comment]
@pedromassango @DanTup given this is a new regression that hits both apps with and without null safety, let's track it in a new issue. Please comment in https://github.com/flutter/flutter/issues/68705
