### ISSUE TITLE
[tool_crash] WebSocketChannelException

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69433]
## Command
```
flutter drive --device-timeout 5 --profile -t test_driver/transitions_perf_e2e.dart --driver test_driver/transitions_perf_e2e_test.dart -d 822ef7958bba573829d85eef4df6cbdd86593730
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WebSocketChannelException
```
#0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:84:24)
#1      _invokeErrorHandler (dart:async/async_error.dart:16:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#4      _rootRunBinary (dart:async/zone.dart:1214:47)
#5      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#10     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:812:19)
#11     _StreamController._addError (dart:async/stream_controller.dart:690:7)
#12     _rootRunBinary (dart:async/zone.dart:1214:47)
#13     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
#15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#18     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:812:19)
#19     _StreamController._addError (dart:async/stream_controller.dart:690:7)
#20     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:178:18)
#21     _rootRunBinary (dart:async/zone.dart:1214:47)
#22     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#23     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#24     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
```
```
[✓] Flutter (Channel unknown, 1.24.0-7.0.pre.31, on Mac OS X 10.14.6 18G6032 darwin-x64, locale en-US)
    • Flutter version 1.24.0-7.0.pre.31 at /Users/flutter/.cocoon/flutter
    • Framework revision 6ce36198ee (27 minutes ago), 2020-10-30 12:15:51 -0700
    • Engine revision 99cc50dfff
    • Dart version 2.11.0 (build 2.11.0-266.0.dev)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/share/android-sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    • ANDROID_HOME = /usr/local/share/android-sdk
    ✗ No valid Android SDK platforms found in /usr/local/share/android-sdk/platforms. Candidates were:
        - android-28
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-11.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone (mobile)  • 822ef7958bba573829d85eef4df6cbdd86593730 • ios            • iOS 9.3.6
    • macOS (desktop)  • macos                                    • darwin-x64     • Mac OS X 10.14.6 18G6032 darwin-x64
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 77.0.3865.90

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-2.0.0
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+5
device_info-0.4.2+9
integration_test-0.9.2+2
url_launcher-5.7.8
url_launcher_linux-0.0.1+3
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.5
url_launcher_windows-0.0.1+1
video_player-0.10.6
video_player_web-0.1.2+3

**Comment by jonahwilliams** [comment]
Because the tool does not use this package anywhere directly, I'm assuming this is from package:vm_service?

@bkonyi

**Comment by jonahwilliams** [comment]
NB: there are no references to dart sources in the stack trace, so this is an unhandled exception that cannot be caught regularly

**Comment by bkonyi** [comment]
Sounds like it might be DDS. Can you consistently reproduce this with the command in the issue or is it just flaky?

**Comment by jonahwilliams** [comment]
no, it failed as part of a devicelab run:

[flutter_gallery__transition_perf_e2e_ios32_6ce3619_2 (1).log](https://github.com/flutter/flutter/files/5467440/flutter_gallery__transition_perf_e2e_ios32_6ce3619_2.1.log)

**Comment by bkonyi** [comment]
Actual exception is: `WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:57995/ws`.

**Comment by SujathaBabu** [comment]
we too facing same issue using master branch while running automation testing. Issue Report  - https://github.com/flutter/flutter/issues/70083

**Comment by bkonyi** [comment]
Should be resolved by https://github.com/flutter/flutter/pull/70712.

**Comment by SujathaBabu** [comment]
We are still facing the same issue even after taking update for master branch.

**Comment by bkonyi** [comment]
@SujathaBabu has the error message changed at all? At the very least it should be wrapped in a `DartDevelopmentServiceException` if you've pulled and rebuilt.

**Comment by SujathaBabu** [comment]
@bkonyi we are facing the following error -
 **flutter has exited unexpectedly: "HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:60700/sKX4ep4b5dg=/ws".**

**Comment by SujathaBabu** [comment]
any updates on above reported issue?

**Comment by SujathaBabu** [comment]
Still we are facing error while running test using master branch. 
![image](https://user-images.githubusercontent.com/41573198/103646296-71958f80-4f7f-11eb-935e-8af3d42125aa.png)

√] Flutter (Channel master, 1.26.0-2.0.pre.179, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.26.0-2.0.pre.179 at D:\src\flutter
    • Framework revision a293c82251 (3 hours ago), 2021-01-05 04:04:03 -0500
    • Engine revision b7352132cd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

**Comment by bkonyi** [comment]
Can you provide a simple reproduction case for me @SujathaBabu?

**Comment by SujathaBabu** [comment]
[Flutter_Automation_Master_Issue.zip](https://github.com/flutter/flutter/files/5781502/Flutter_Automation_Master_Issue.zip)

Simple sample has been attached. Can you check and do the needful to resolve the reported issue.

**Comment by bkonyi** [comment]
@SujathaBabu I'm unable to reproduce on OSX but don't have access to my Windows machine at the moment. Can you provide full logs from `flutter drive --target=test_driver/main.dart --verbose`?

**Comment by SujathaBabu** [comment]
Logs using provided command has been attached. Can you check about that? 
[flutterlogs.txt](https://github.com/flutter/flutter/files/5786685/flutterlogs.txt)

We are facing this issue only in the Master branch.

**Comment by SujathaBabu** [comment]
any updates on above reported issues?

**Comment by bkonyi** [comment]
No meaningful progress, but I have something for you to try... would you mind rebooting the device you're running these tests on or running `adb logcat -b all -c`? I have a feeling this might be a bug in the tool where we're trying to connect to an old VM service URI that we're picking up from the logs.

**Comment by SujathaBabu** [comment]
@bkonyi - After running adb logcat -b all -c command, test cases are working fine. Thank you.
