### ISSUE TITLE
"RRect argument contained a NaN value" error occurs when using TextField inside a tabbar

### ISSUE THREAD

**Issue by drriguz** [flutter/flutter#70096]
Hi there,

I got an issue when using TextField inside a TabBarView, and I reproduced by using the same code of this issue:

https://github.com/flutter/flutter/issues/67142#issuecomment-703498525

# Code to re-produce:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Container(child: Center(child: TextField())),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}

```

# Reproduce steps

* Open the example (I'm using IOS simulator IPhone SE(2nd generation 14.1)
* Input something in the textfield
* Then just change from tab1 to another, if no error occurs, try multiple times, just switch between tab1 and tab2 again and again

One interesting fact is that, if you don't enter anything and just do step2, then no error will occur

# Full error log

```

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///Users/hfli/Downloads/example/lib/main.dart:26:46
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:37:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
#4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2042:14)
#5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
#6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#85a6f relayoutBoundary=up14
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, 0.0<=h<=519.0)
...  size: Size(375.0, 19.0)
...  cursorColor: Color(0x102196f3)
...  showCursor: ValueNotifier<bool>#1a587(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: TextAffinity.downstream, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#d9674(offset: 0.0, range: 0.0..0.0, viewport: 375.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#fea62, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "1"
RenderObject: RenderEditable#85a6f relayoutBoundary=up14
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, 0.0<=h<=519.0)
  size: Size(375.0, 19.0)
  cursorColor: Color(0x102196f3)
  showCursor: ValueNotifier<bool>#1a587(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#d9674(offset: 0.0, range: 0.0..0.0, viewport: 375.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#fea62, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "1"
════════════════════════════════════════════════════════════════════════════════════════════════════

```

# Flutter doctor

```
hfli@HaifengdeMacBook-Pro:~/Downloads $ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E287, locale en-CN)
    • Flutter version 1.22.3 at /Users/hfli/Documents/INFRAS/flutter
    • Framework revision 8874f21e79 (11 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/hfli/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 1304F1F8-8763-448F-9477-D8549AFAF79F
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @drriguz 
Thanks for creating the issue,  I can reproduce it on the `stable` channel. However, it doesn't reproduce on `beta` 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H15 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)           • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile)       • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 Pro Max (mobile) • 0A159C14-BF48-4DD7-8D91-F45A387EE4B2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 86.0.4240.183
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

</details>

Can you please upgrade to the latest  `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by drriguz** [comment]
Yeah, it works in `beta`, thanks a lot! So I guess it's a know issue. I'll close this and look forward to new the next stable release~

```
hfli@HaifengdeMacBook-Pro:3580EE2F-4EE6-4B72-80B6-9C8F25837C86/Documents $ flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 1.6s
Downloading android-arm-release/darwin-x64 tools...                 0.6s
Downloading android-arm64-profile/darwin-x64 tools...               0.6s
Downloading android-arm64-release/darwin-x64 tools...               0.7s
Downloading android-x64-profile/darwin-x64 tools...                 0.7s
Downloading android-x64-release/darwin-x64 tools...                 0.6s
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E287 x86_64,
    locale en-CN)
    • Flutter version 1.23.0-18.1.pre at /Users/hfli/Documents/INFRAS/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/hfli/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 1304F1F8-8763-448F-9477-D8549AFAF79F
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Thanks for the confirming @drriguz  
Let's keep the issue open for fix into stable channel

**Comment by TahaTesser** [comment]
CC @pcsosinski

**Comment by greysonDEV** [comment]
I can confirm that upgrading to the beta version using the upgrade process described by @TahaTesser, [here](https://github.com/flutter/flutter/issues/70096#issuecomment-724029864), works.

I was experiencing the error using a `TextFormField` inside of a `PageView`. I primarily received the error when navigating  to a different `PageView` page which also contained a `TextFormField`. After upgrading to the beta version, the error is not raised.
```
$ flutter --version

Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (5 days ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
```

**Comment by joj3000** [comment]
Hi, i have the same issue and i fixed it using `FocusScope.of(context).unfocus();`, maybe this will help.

Issue = `TextField` inside a `PageView` that gives this error when page changes :


```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'

The relevant error-causing widget was
TextField

When the exception was thrown, this was the stack
#2      _rrectIsValid (dart:ui/painting.dart:37:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
#4      RenderEditable._paintCaret
package:flutter/…/rendering/editable.dart:2042
#5      RenderEditable._paintContents
package:flutter/…/rendering/editable.dart:2224
#6      RenderEditable.paint
...
```


```
flutter --version

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (4 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

**Comment by marcellocamara** [comment]
@joj3000 

> Hi, i have the same issue and i fixed it using `FocusScope.of(context).unfocus();`, maybe this will help.

I did not understand how you fixed. Can you tell me an exemple of using this `unfocus()`? 
I've tried to call it on dispose and the issue persists when I change the page.

**Comment by joj3000** [comment]
> @joj3000
> 
> > Hi, i have the same issue and i fixed it using `FocusScope.of(context).unfocus();`, maybe this will help.
> 
> I did not understand how you fixed. Can you tell me an exemple of using this `unfocus()`?
> I've tried to call it on dispose and the issue persists when I change the page.

So i realised that when changing pages with a TextField focused (and maybe with some text manually typed in the TextField also), i had this error. What i did is, because i change pages manually with 2 buttons, on the onTap/onPressed method, i first of all call the `FocusScope.of(context).unfocus();`, like this :

```
//My Button

GestureDetector(
    onTap: () {
        FocusScope.of(context).unfocus();  // <--- first line of the on tap method
        //change page logic
    }
    child: ...
)
```

**Comment by marcellocamara** [comment]
>     onTap: () {
>         FocusScope.of(context).unfocus();  // <--- first line of the on tap method
>         //change page logic
>     }

@joj3000 this works like a charme on my bottomNavigation, thanks.

**Comment by deeeznuds** [comment]
I had the same issue when the data for charts was empty. The problem is when data is empty - the maximum parameter of the axis was 0. I just removed the maximum property from the axis parameters because in [documentation](https://help.syncfusion.com/flutter/cartesian-charts/axis-types) mentioned that without setting these parameters, the chart will be displayed neatly.

**Comment by nithishjipmer** [comment]
> > @joj3000
> > > Hi, i have the same issue and i fixed it using `FocusScope.of(context).unfocus();`, maybe this will help.
> > 
> > 
> > I did not understand how you fixed. Can you tell me an exemple of using this `unfocus()`?
> > I've tried to call it on dispose and the issue persists when I change the page.
> 
> So i realised that when changing pages with a TextField focused (and maybe with some text manually typed in the TextField also), i had this error. What i did is, because i change pages manually with 2 buttons, on the onTap/onPressed method, i first of all call the `FocusScope.of(context).unfocus();`, like this :
> 
> ```
> //My Button
> 
> GestureDetector(
>     onTap: () {
>         FocusScope.of(context).unfocus();  // <--- first line of the on tap method
>         //change page logic
>     }
>     child: ...
> )
> ```

Works amazing!!!

**Comment by maheshmnj** [comment]
@drriguz I verified the issue on stable 3.3 and master 3.7 and I am unable to reproduce the issue. I believe this issue is fixed.

https://user-images.githubusercontent.com/31410839/210706463-c5e6d80b-048e-4ec6-bc67-8ab60360d682.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

I am going to close this issue for now, Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.

Thank you.
