### ISSUE TITLE
My Flutter app showing white screen in release apk

### ISSUE THREAD

**Issue by AnanthanAn** [flutter/flutter#70558]
My flutter app runs fine on debug mode but when i create release apk its stuck on white screen.

<details>
  <summary>Logs</summary>

```
```

```
flutter analyze
Analyzing campgain_mobile...


   info - Unused import: 'package:campgain_mobile/src/models/api_models/notification_list_response.dart' - lib\src\bloc\post_bloc.dart:6:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/models/api_models/notification_list_response.dart' - lib\src\bloc\user_bloc.dart:3:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/bloc/comments_bloc.dart' - lib\src\models\api_models\get_activity_response_model.dart:7:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/bloc/comments_bloc.dart' - lib\src\models\api_models\get_comments_response_model.dart:7:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\src\models\api_models\get_feed_response_model.dart:60:10 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\models\api_models\get_feed_response_model.dart:79:16 - non_constant_identifier_names
   info - Unused import: 'package:flutter/cupertino.dart' - lib\src\models\api_models\get_groups_list_request_model.dart:3:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/bloc/comments_bloc.dart' - lib\src\models\api_models\get_groups_list_response_model.dart:3:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/bloc/comments_bloc.dart' - lib\src\models\api_models\get_localbody_response_model.dart:7:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/bloc/comments_bloc.dart' - lib\src\models\api_models\get_wards_response_model.dart:7:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\src\models\api_models\search_users_request_model.dart:14:20 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\models\api_models\search_users_request_model.dart:17:16 - non_constant_identifier_names
   info - Unused import: 'package:flutter/material.dart' - lib\src\models\model.dart:1:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/models/api_models/user_profile_response.dart' - lib\src\resource\api_providers\edit_profile_api_provider.dart:2:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/models/api_models/get_comments_request_model.dart' - lib\src\resource\api_providers\groups_list_api_provider.dart:1:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/models/api_models/get_comments_response_model.dart' - lib\src\resource\api_providers\groups_list_api_provider.dart:2:8 - unused_import
   info - Unused import: 'package:campgain_mobile/client/hive_names.dart' - lib\src\resource\api_providers\user_api_provider.dart:4:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/models/api_models/notification_list_response.dart' - lib\src\resource\api_providers\user_api_provider.dart:5:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/models/api_models/get_comments_request_model.dart' - lib\src\resource\api_providers\ward_api_provider.dart:1:8 - unused_import
   info - 'pickImage' is deprecated and shouldn't be used. Use imagePicker.getImage() method instead. - lib\src\ui\screens\Profile\edit_profile.dart:30:42 - deprecated_member_use
   info - Unused import: 'package:campgain_mobile/src/ui/widgets/custom_card_tile_for_listview.dart' - lib\src\ui\screens\Profile\profile.dart:6:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\src\ui\screens\auth\auth_service.dart:2:8 - unused_import
   info - This function has a return type of 'FutureOr<String>', but doesn't end with a return statement - lib\src\ui\screens\auth\auth_service.dart:170:18 - missing_return
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Login._auth, Login._authfb -
          lib\src\ui\screens\auth\login.dart:15:7 - must_be_immutable
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\login.dart:82:35 - deprecated_member_use
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\login.dart:111:35 - deprecated_member_use
   info - The value of the local variable 'dio' isn't used - lib\src\ui\screens\auth\login.dart:304:9 - unused_local_variable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: RegistrationScreen.auth, RegistrationScreen.authfb -
          lib\src\ui\screens\auth\registration.dart:13:7 - must_be_immutable
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\registration.dart:95:43 - deprecated_member_use
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\registration.dart:123:43 - deprecated_member_use
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\registration.dart:154:43 - deprecated_member_use
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\registration.dart:182:43 - deprecated_member_use
   info - 'autovalidate' is deprecated and shouldn't be used. Use autoValidateMode parameter which provide more specific behaviour related to auto validation. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\auth\registration.dart:210:43 - deprecated_member_use
   info - This method overrides a method annotated as '@mustCallSuper' in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden method - lib\src\ui\screens\comments\comments_screen.dart:72:10 -
          must_call_super
   info - Unused import: 'package:campgain_mobile/src/ui/screens/auth/auth_service.dart' - lib\src\ui\screens\home\home_page.dart:3:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/ui/screens/auth/login.dart' - lib\src\ui\screens\home\home_page.dart:4:8 - unused_import
   info - Unused import: 'package:campgain_mobile/src/utils/utils.dart' - lib\src\ui\screens\home\home_page.dart:9:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\src\ui\screens\home\home_page.dart:13:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: HomePage.auth, HomePage.authFb -
          lib\src\ui\screens\home\home_page.dart:15:7 - must_be_immutable
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\home\home_page.dart:102:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\home\home_page.dart:109:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\home\home_page.dart:116:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\home\home_page.dart:123:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0. -
          lib\src\ui\screens\home\home_page.dart:130:15 - deprecated_member_use
   info - Duplicate import - lib\src\ui\screens\post_feed\post_feed_item.dart:13:8 - duplicate_import
   info - Name non-constant identifiers using lowerCamelCase - lib\src\ui\screens\post_feed\post_feed_item.dart:25:16 - non_constant_identifier_names
   info - This function has a return type of 'String', but doesn't end with a return statement - lib\src\ui\screens\post_feed\post_feed_item.dart:149:10 - missing_return
   info - This function has a return type of 'String', but doesn't end with a return statement - lib\src\ui\widgets\custom_card_tile_for_listview.dart:96:10 - missing_return
   info - Equality operator `==` invocation with references of unrelated types - lib\src\ui\widgets\custom_card_tile_for_listview.dart:182:24 - unrelated_type_equality_checks
   info - Name non-constant identifiers using lowerCamelCase - lib\src\ui\widgets\custom_feed_for_profile_grid.dart:24:16 - non_constant_identifier_names
   info - This function has a return type of 'String', but doesn't end with a return statement - lib\src\ui\widgets\custom_feed_for_profile_grid.dart:120:10 - missing_return
   info - Unused import: 'package:campgain_mobile/src/models/api_models/get_activity_response_model.dart' - lib\src\utils\api_client.dart:3:8 - unused_import

52 issues found. (ran in 412.8s)
```

```
C:\Users\Ananthan\AndroidStudioProjects\campgain_mobile>flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-IN)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (2 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Ananthan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

</details>

**Comment by YazeedAlKhalaf** [comment]
we need more info:

please run `flutter run -v` and paste the output in a comment or a paste bin

**Comment by AnanthanAn** [comment]
i found the issue was with gradle version. i need to use gradle 3.5.4. Can anyone suggest compatible google sign in and fb sign in plugin versions for this

**Comment by pedromassangocode** [comment]
Hi @AnanthanAn 
Can you confirm that this issue is solved? 
Thank you

**Comment by AnanthanAn** [comment]
Its not resolved i rolled back to older gradle version but now that version (3.5.4) is not compatible with google sign in and Facebook sign in plugins so need help on that.

**Comment by pedromassangocode** [comment]
Hi @AnanthanAn 
Can you please provide your `flutter doctor -v`, your `flutter build appbundle --verbose` and a minimal complete reproducible project sample?

What Gradle version you were using?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by phanbaohuy96** [comment]
@pedromassangocode 
Currently, i meet this issues when i upgrade gradle version form `gradle-5.6.2-all` to `gradle-6.1.1-all` and build gradle `com.android.tools.build:gradle:3.5.0` to 'com.android.tools.build:gradle:4.0.1'.

Build command: `flutter build apk --flavor dev --release -t lib/main_dev.dart`

Here is my Flutter doctor:
```
[✓] Flutter (Channel unknown, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-VN)
    • Flutter version 1.22.5 at /Users/baohuy/files/sdks/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/baohuy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/baohuy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Redmi S2 (mobile) • 48209d3 • android-arm • Android 9 (API 28)
    • macOS (desktop)   • macos   • darwin-x64  • Mac OS X 10.15.7 19H15 darwin-x64
  ```

**Comment by phanbaohuy96** [comment]
Update:
the error caused by the shared_preference plugin.
`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

**Comment by pan0skou** [comment]
> 
> 
> Update:
> the error caused by the shared_preference plugin.
> `[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
> 
> **shared_preferences**: ^0.5.12+4
> **package_info**: ^0.4.3+2

How did you solve this?

**Comment by phanbaohuy96** [comment]
@pan0skou back gradle version to 4.5.0 that okay.
```
dependencies {
    classpath 'com.android.tools.build:gradle:3.5.0'
}
```
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
```

**Comment by pratikbutani** [comment]
I got same problem yesterday and I have tried all the solution. 

Finally I got the solution as I have added `--no-shrink` in command of building apk.

    flutter build apk --no-shrink

Hope it will work.

Thank you.

**Comment by dblanco-dev** [comment]
> I got same problem yesterday and I have tried all the solution.
> 
> Finally I got the solution as I have added `--no-shrink` in command of building apk.
> 
> ```
> flutter build apk --no-shrink
> ```
> 
> Hope it will work.
> 
> Thank you.

It works but now I have another problem, it does not work Dio.

**Comment by LSambo02** [comment]
> I got same problem yesterday and I have tried all the solution.
> 
> Finally I got the solution as I have added `--no-shrink` in command of building apk.
> 
> ```
> flutter build apk --no-shrink
> ```
> 
> Hope it will work.
> 
> Thank you.

Thank you @pratikbutani
this worked for me

**Comment by hiashutoshsingh** [comment]
> I got same problem yesterday and I have tried all the solution.
> 
> Finally I got the solution as I have added `--no-shrink` in command of building apk.
> 
> ```
> flutter build apk --no-shrink
> ```
> 
> Hope it will work.
> 
> Thank you.

this solution is not working for me...stuck on this past 7 days :(

**Comment by LSambo02** [comment]
Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
If so, you might want to check some of your flexible widgets placement.

**Comment by hiashutoshsingh** [comment]
> Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> If so, you might want to check some of your flexible widgets placement.

I solved it by downgrading by Gradle version.

PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.

**Comment by LSambo02** [comment]
> > Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> > If so, you might want to check some of your flexible widgets placement.
> 
> I solved it by downgrading by Gradle version.
> 
> PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.

Great.

**Comment by Abenezerfikadu** [comment]
> > Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> > If so, you might want to check some of your flexible widgets placement.
> 
> I solved it by downgrading by Gradle version.
> 
> PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.

can you tell us how?

**Comment by hiashutoshsingh** [comment]
> > > Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> > > If so, you might want to check some of your flexible widgets placement.
> > 
> > 
> > I solved it by downgrading by Gradle version.
> > PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.
> 
> can you tell us how?

I was using 4.0.1 gradle version..people were recommending to downgrade the grade version so i did..I downgrade my gradle version to 3.6.2

**Comment by Abenezerfikadu** [comment]
> > > > Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> > > > If so, you might want to check some of your flexible widgets placement.
> > > 
> > > 
> > > I solved it by downgrading by Gradle version.
> > > PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.
> > 
> > 
> > can you tell us how?
> 
> I was using 4.0.1 gradle version..people were recommending to downgrade the grade version so i did..I downgrade my gradle version to 3.6.2

I get this white screen because of this command 
`flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>`
does work for me ur advice I will let you know

**Comment by Abenezerfikadu** [comment]
> > > > Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> > > > If so, you might want to check some of your flexible widgets placement.
> > > 
> > > 
> > > I solved it by downgrading by Gradle version.
> > > PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.
> > 
> > 
> > can you tell us how?
> 
> I was using 4.0.1 gradle version..people were recommending to downgrade the grade version so i did..I downgrade my gradle version to 3.6.2

my gradle was 3.5.0

**Comment by sawirricardo** [comment]
hi, friends, I still experience this issue. I've conflicted with other package like file_picker which needs gradle 4.0.1
I tried solutions mentioned above
- downgrade gradle version to 3.5.4/3.6.4/4.0.1
- use --no-shrink

None of the above works

**Comment by LSambo02** [comment]
@sawirricardo  you may want to try to set this 
```
shrinkResources false
minifyEnabled false
useProguard false

on your app module build.gradle.
Somehow this can be related to R8 or Progguard messing with the code
Some references:
https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421
https://stackoverflow.com/a/65325458

Other possible solution might be 
Checking the internet access permission on your manifest, 
If set, try to remove and see what's the outcome.

Hope you find a solution!

**Comment by sawirricardo** [comment]
> @sawirricardo you may want to try to set this
> 
> ```
> shrinkResources false
> minifyEnabled false
> useProguard false 
> ```
> 
> on your app module `build.gradle.`
> Somehow this can be related to R8 or Progguard messing with the code
> Some references:
> https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421
> https://stackoverflow.com/a/65325458
> 
> Other possible solution might be
> Checking the internet access permission on your manifest,
> If set, try to remove and see what's the outcome.
> 
> Hope you find a solution!

Hi @LSambo02 thank you for your suggestions, however, It still doesn't work. still show white blank screen.

**Comment by NirmalaSudhirr** [comment]
> > Hi @hiashutoshsingh, does your console report any **Parent Widget** related error/warning?
> > If so, you might want to check some of your flexible widgets placement.
> 
> I solved it by downgrading by Gradle version.
> 
> PS: don't make a release build any from the 4.x.x version of gradle either lower or greater than this version.

Downgrading gradle works for me too:)

**Comment by funder7** [comment]
Thanks @LSambo02 , with your settings I've solved the problem, without downgrading gradle (I'm using gradle 6.7 && flutter stable 2.0.3)

**Comment by RubenDavid20** [comment]
In my case, I had a code in the main that not work and launch exception. In debug it works but in realease doesnt work.  How did I now it? I using eliminating technic until i found bad code. It was shared_preferences and change the verssion, (english no so good)

**Comment by funder7** [comment]
@RubenDavid20 if it runs in debug, but not in release mode, then it's more likely due to the apk building options reported in the previous posts... I wouldn't tell that it's because of shared_preferences, or at least, try a `flutter clean`before assuming that, sometimes cache leads to false positives, as far as I saw developing with Flutter. 
Cheers

**Comment by gOzaru** [comment]
> I got same problem yesterday and I have tried all the solution.
> 
> Finally I got the solution as I have added `--no-shrink` in command of building apk.
> 
> ```
> flutter build apk --no-shrink
> ```
> 
> Hope it will work.
> 
> Thank you.

Thanks, bro. This is working for me.

**Comment by kapil708** [comment]
> @sawirricardo you may want to try to set this
> 
> ```
> shrinkResources false
> minifyEnabled false
> useProguard false 
> ```
> 
> on your app module `build.gradle.`
> Somehow this can be related to R8 or Progguard messing with the code
> Some references:
> https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421
> https://stackoverflow.com/a/65325458
> 
> Other possible solution might be
> Checking the internet access permission on your manifest,
> If set, try to remove and see what's the outcome.
> 
> Hope you find a solution!

work for me thanks

**Comment by HASHI99M** [comment]
> @sawirricardo you may want to try to set this
> 
> ```
> shrinkResources false
> minifyEnabled false
> useProguard false 
> ```
> 
> on your app module `build.gradle.`
> Somehow this can be related to R8 or Progguard messing with the code
> Some references:
> https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421
> https://stackoverflow.com/a/65325458
> 
> Other possible solution might be
> Checking the internet access permission on your manifest,
> If set, try to remove and see what's the outcome.
> 
> Hope you find a solution!

it work  for me:)
thank you
latest version in flutter

**Comment by EvertonMJunior** [comment]
> @sawirricardo you may want to try to set this
> 
> ```
> shrinkResources false
> minifyEnabled false
> useProguard false 
> ```
> 
> on your app module `build.gradle.`
> Somehow this can be related to R8 or Progguard messing with the code
> Some references:
> https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421
> https://stackoverflow.com/a/65325458
> 
> Other possible solution might be
> Checking the internet access permission on your manifest,
> If set, try to remove and see what's the outcome.
> 
> Hope you find a solution!

Thanks! I had the same problem after adding file_picker and having to upgrade to Gradle 4.x. This solved it.

**Comment by tanzilzubair** [comment]
I've been having the same problem since yesterday. The first version of the app worked fine, but the update I related yesterday had this problem on one of the two devices I tested it on. So far the solutions I'm seeing here include downgrading the gradle version and special flags during compilation, but its all mixed results as far as I can see.

Also, which grade file do I edit to downgrade? There's multiple grade files.
And won't passing the` --no shrink ` flag or as per @LSambo02 's suggestion, these options 
` 
shrinkResources false     
minifyEnabled false
useProguard false
` enlarge the file size of the project ? 

I don't even have bundletool installed, so checking with each of these options isn't exactly viable since I have to publish  internal versions using Google Play many times just to be able to check. Does anyone know why exactly this is even happening?

**Comment by mhrjnamar** [comment]
I am also facing this issue. I have tried all the solutions mentioned in this issue but it is not working for me also why is this issue closed? I think there is no proper solution and reason mentioned for this issue.

**Comment by Jahn08** [comment]
In my case it happened because of an absent environmental variable in the release configuration (for the sentry_flutter package). To figure it out I ran `flutter run --release --verbose` and got the error. So, the trouble is likely to be specific for every case, and it might not be related to shrinking or something.

**Comment by mhrjnamar** [comment]
> In my case it happened because of an absent environmental variable in the release configuration (for the sentry_flutter package). To figure it out I ran `flutter run --release --verbose` and got the error. So, the trouble is likely to be specific for every case, and it might not be related to shrinking or something along those lines.

In my case, this was solved after upgrading my dependencies. I would have found the issue if I had tested with this command.

**Comment by johnmelodyme** [comment]
> 
> 
> I got same problem yesterday and I have tried all the solution.
> 
> Finally I got the solution as I have added `--no-shrink` in command of building apk.
> 
> ```
> flutter build apk --no-shrink
> ```
> 
> Hope it will work.
> 
> Thank you.

This actually Work
