### ISSUE TITLE
ElevatedButton and some other button missing parameter in editor

### ISSUE THREAD

**Issue by iqfareez** [flutter/flutter#70982]
## Steps to Reproduce

0. I'm using vsocde with Flutter and Dart plugin up-to-date.
1. Try to put ElevatedButton, RaisedButton etc.

The problem is:
1. No parameter such as child, onPressed etc.
2. Also when I try to put any parameeter, such as `child:`. The editor still returning error (`The named parameter 'child' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'child'.` But weirdly it's fine when run the app. ?.?

The code:
```
Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          children: [
            Text('Hojhoh'),
            ElevatedButton(),
          ],
        ),

      ),
    );
  }
```
![image](https://user-images.githubusercontent.com/60868965/99874334-22d7a480-2c22-11eb-9877-021de62f5ac6.png)

## Logs
```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-MY)
    • Flutter version 1.23.0-18.1.pre at C:\src\flutter\flutter
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\maple\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\maple\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • SM J730G (mobile) • 5200b38ceaf7a473 • android-arm    • Android 9 (API 28)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.41

• No issues found!
```

**Comment by sidrao2006** [comment]
Hey @iqfareez ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with the VSCode plugin, please close this issue and open it [here](https://github.com/dart-code/dart-code/issues) instead.

Thanks

**Comment by sidrao2006** [comment]
Also restarting the editor should solve this problem. 
This is a known issue which is reproduced when the SDK is upgraded

**Comment by iqfareez** [comment]
Thank you. I tried restarting the editor, but it didn't solve the issue. Anyway, I will try look up for the problems.
> Since this is an error/bug with the VSCode plugin, please close this issue and open it here instead.

Noted with thanks.

**Comment by darshankawar** [comment]
@iqfareez 
Verified on latest beta using Android Studio and was able to see required parameters for `ElevatedButton`.

```
ElevatedButton(
              child: Text('Test'),
              onPressed: null,
            ),
```

You may try to upgrade beta to latest and see if it resolves your issue. If not, then as suggested above, please open issue in vscode plugin repo.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.

<details>
<summary>beta flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (5 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.67

• No issues found!


```

</details>
