### ISSUE TITLE
TextFormField (and TextField) widgets do not wrap text correctly

### ISSUE THREAD

**Issue by benPesso** [flutter/flutter#71083]
Similar to the issues reported in #18761, the input fields in Flutter suffer from the same disfunction.

Currently, the text input fields in Flutter do not wrap their input correctly. Instead of breaking a word in the middle and wrapping the remainder to the next line, Flutter is breaking the string at the word boundary closest to the end of the line, which is non buono.

#### Flutter
<img width="240" alt="Screen Shot 2020-11-23 at 16 37 05" src="https://user-images.githubusercontent.com/921173/99974945-44fc2e80-2daa-11eb-9599-691eed55a0c6.png">

#### Chrome
Web browsers correctly split the string at the character that would otherwise overflow.
<img width="343" alt="Screen Shot 2020-11-23 at 16 44 58" src="https://user-images.githubusercontent.com/921173/99975781-5265e880-2dab-11eb-9d40-81ee07b07921.png">

#### Code snippet
```dart
TextFormField(
  decoration: InputDecoration(border: OutlineInputBorder()),
  minLines: null,
  maxLines: null,
  initialValue: 'https://www.example.com/some/thingweirdisgoingon.here',
)
```

**Comment by iapicca** [comment]
@benPesso 
how does this issue differ from the one you [referenced](https://github.com/flutter/flutter/issues/18761)?
isn't it a duplicate

**Comment by benPesso** [comment]
@iapicca That one is for Text (read-only) widgets, whereas this one is for input widgets. It's about the _wrapping_ of text. Not clipping. With input fields, you don't want to clip the text, but to wrap it, so it's 100% visible.

Here's another wacky example:
<img width="217" alt="Screen Shot 2020-11-23 at 17 40 30" src="https://user-images.githubusercontent.com/921173/99982398-2c444680-2db3-11eb-97e5-7378a623d40a.png">

**Comment by benPesso** [comment]
@Sembauke Not really, no. I haven't tested it in a while (after #18761 was resolved). If you're experiencing this, I guess that fix did not resolve this issue.

**Comment by Sembauke** [comment]
@benPesso This seems like it it fixed in the newest version of Flutter. But please confirm yourself.

**Comment by benPesso** [comment]
@Sembauke  Still not really working as expected.
https://github.com/flutter/flutter/assets/921173/07a721d1-319c-4ec9-8aaa-39aef3ec6b8c

**Comment by Sembauke** [comment]
are you sure you are on 3.10?

**Comment by benPesso** [comment]
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.0 22A380 darwin-x64, locale en-US)

**Comment by Sembauke** [comment]
> [✓] Flutter (Channel stable, 3.10.3, on macOS 13.0 22A380 darwin-x64, locale en-US)

Have you set the Dart SDK to 3.0 in your pubspec.yaml?

**Comment by benPesso** [comment]
Yes, I created a brand new project for it.
>  sdk: '>=3.0.3 <4.0.0'

The input field was set in a `FractionallySizedBox`:
```
FractionallySizedBox(
  widthFactor: .8,
  child: TextFormField(
    decoration: const InputDecoration(border: OutlineInputBorder()),
    minLines: null,
    maxLines: null,
    initialValue: 'https://www.example.com/some/thingweirdisgoingon.here',
  ),
),
```

**Comment by monkeyWie** [comment]
Same here.
