### ISSUE TITLE
Exception caught by gesture library (monodrag.dart)

### ISSUE THREAD

**Issue by marcellocamara** [flutter/flutter#71331]
Hello,

I think I had face the same issue as [#66454](https://github.com/flutter/flutter/issues/66454), #36350, [#37466](https://github.com/flutter/flutter/issues/37466) and #70371 But, they are all closed - except for the last one that I added in the edit mode (and the error is not fixed).

Steps to reproduce: 

1. Clone this exemplar repository that I've created: https://github.com/marcellocamara/FlutterGestureCrashExample
2. Run "flutter pub get"
3. Run "flutter run" or by your IDE (I'm using Android Studio)
4. With two fingers, simultaneously, click on the colored (blue) Container area

I've recorded an evidence video to this issue: https://youtu.be/U-_5wzee0VQ

Log:
```
════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following _CastError was thrown while dispatching a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321:60)
#1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
#3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
...
Event: PointerUpEvent#6b144(position: Offset(197.0, 354.8))
  position: Offset(197.0, 354.8)
Target: <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@95a89f4[MainActivity](16882): ViewPostIme pointer 0
D/ViewRootImpl@95a89f4[MainActivity](16882): ViewPostIme pointer 1

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor -v
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [versÃ£o 10.0.18363.1198], locale pt-BR)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marce\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\marce\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\marce\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • SM G950F (mobile) • ce12160ca9102e3405 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
@marcellocamara 
in your code sample you are using the 3rd party package [carousel_slider](https://pub.dev/packages/carousel_slider)
I see you already open an [issue](https://github.com/serenader2014/flutter_carousel_slider/issues/235) in the dedicated github;

moreover your statement is incorrect
> I think I had face the same issue as [#66454](https://github.com/flutter/flutter/issues/66454), #36350, [#37466](https://github.com/flutter/flutter/issues/37466) and #70371 But, they are all closed

they are not, at the time of writing this [issue](https://github.com/flutter/flutter/issues/70371)  is still open

please not the [comment](https://github.com/flutter/flutter/issues/70371#issuecomment-726061835)
> Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows this issue ?

I recommend you to close this issue as duplicate and provide the information requested on the issue already in triage process

**Comment by marcellocamara** [comment]
@iapicca I've decided to open this issue, and mention the others, because they are all incomplete, duplicated, as you mentioned that @darshankawar asked for some information.

I thought of creating it complete to avoid this kind of problem: https://github.com/flutter/flutter/issues/66454#issuecomment-711635220
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.

And this kind of problem too: https://github.com/flutter/flutter/issues/70371#issuecomment-726061835

> Can you provide flutter doctor -v and a minimal reproducible code sample that shows this issue ?

I've provided a complete project as example and the video, as evidence. 

My statement was incorrect at the time of editing because I edited and inserted the issue #70371 - minutes later I've inserted the text saying that this one is still opened.
See the first message before editing:

> I think I had face the same issue as #66454, #36350 and #37466. But, they are all closed (and the error is not fixed).

They are all closed, as I said.

I'm not here to criticize, but to seek help and help. 
I also open this issue in the 3rd party package because I can only reproduce this error with the 3rd party package. However, I imagine the error is in the monodrag.dart class (the logs does not mention any error from 3rd party package).

Waiting for instructions to how to proceed.

**Comment by iapicca** [comment]
@marcellocamara 
> I also open this issue in the 3rd party package because **_I can only reproduce this error with the 3rd party package_**. 

this seems to support the possibility that the specific issue you are describing is caused by  [carousel_slider](https://pub.dev/packages/carousel_slider)  and not flutter
and therefore should be addressed with the [issue](https://github.com/serenader2014/flutter_carousel_slider/issues/235) you opened in the dedicated repo,

nevertheless if you believe the issue is caused by flutter could and it's a different case form this [issue](https://github.com/flutter/flutter/issues/70371) 
please provide a code sample that does **_not_** include 3rd party packages

**Comment by darshankawar** [comment]
@marcellocamara 
As suggested by @iapicca above, we would need a minimal code sample without 3rd party plugin that still shows the exception you mentioned earlier.
Thanks.

**Comment by xu-baolin** [comment]
Although it may be a problem caused by a third-party package, I still want to investigate this.

**Comment by xu-baolin** [comment]
@marcellocamara I have posted a PR to fix the bug of the third-party package.

This is indeed a third-party bug and not a Flutter issue. Please close this issue and follow the third-party PR, thanks.

**Comment by marcellocamara** [comment]
Thanks for your help @xu-baolin !
