### ISSUE TITLE
The plugin google_maps_flutter could not be built due to the issue above.

### ISSUE THREAD

**Issue by TomerconDevelopers** [flutter/flutter#71347]
```
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:18: error: cannot find symbol
import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  symbol:   class DefaultLifecycleObserver
  location: package androidx.lifecycle
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:49: error: cannot find symbol
    implements DefaultLifecycleObserver,
               ^
  symbol: class DefaultLifecycleObserver
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapsPlugin.java:19: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:110: error: incompatible types: GoogleMapController cannot be converted to LifecycleObserver
    lifecycleProvider.getLifecycle().addObserver(this);
                                                 ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:477: error: incompatible types: GoogleMapController cannot be converted to LifecycleObserver
      lifecycle.removeObserver(this);
                               ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:510: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:518: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:526: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:534: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:542: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:550: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapController.java:552: error: incompatible types: GoogleMapController cannot be converted to LifecycleObserver
    owner.getLifecycle().removeObserver(this);
                                        ^
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.0.6\android\src\main\java\io\flutter\plugins\goog
lemaps\GoogleMapsPlugin.java:92: error: cannot find symbol
    lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
                ^
  symbol:   variable FlutterLifecycleAdapter
  location: class GoogleMapsPlugin
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
13 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
 full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by imeDevelopers** [comment]
enable androidX in your application

**Comment by Abhishek01039** [comment]
Hello @TomerconDevelopers 
Try the above solution and if still the problem is there then please send the `flutter doctor -v`, `flutter run -v`, and minimal reproduction code
Thanks.

**Comment by darshankawar** [comment]
@TomerconDevelopers 
If you were trying to hot restart or hot reload after adding `google_maps` plugin, then you first need to stop the app instance, run `flutter pub get` and then `flutter run`. You may also try `flutter clean` and then `flutter run` to see if it works.
If problem still persists, provide `flutter doctor -v`, `pubspec.yaml` and minimal code sample without any 3rd party plugins that shows the issue.
Thanks.

**Comment by TomerconDevelopers** [comment]
I fixed it by creating new project with latest flutter version, then moved code to new project.

**Comment by sanjeet3** [comment]
> I fixed it by creating new project with latest flutter version, then moved code to new project.

Yes its works, i have same issue and try lot of way, but create new project in different directory location and add plugin in pubsepc.yaml
google_maps_flutter: 
its working see in given image
![image](https://user-images.githubusercontent.com/40879757/101240201-c3928d80-3713-11eb-993a-60cde51b0e1e.png)

**Comment by kingmaster772** [comment]
I was create new project and add dependencies from my old `pubspec.yaml` but still not working. i got this errors. any clues? 

```
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:18: error: cannot find symbol import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  symbol:   class DefaultLifecycleObserver
  location: package androidx.lifecycle
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:49: error: cannot find symbol
    implements DefaultLifecycleObserver,
               ^
  symbol: class DefaultLifecycleObserver
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapsPlugin.java:19: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:110: error: incompatible types: GoogleMapController cannot be converted to LifecycleObserver
    lifecycleProvider.getLifecycle().addObserver(this);
                                                 ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:477: error: incompatible types: GoogleMapController cannot be converted to LifecycleObserver
      lifecycle.removeObserver(this);
                               ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:510: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:518: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:526: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:534: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:542: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:550: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapController.java:552: error: incompatible types: GoogleMapController cannot be converted to LifecycleObserver
    owner.getLifecycle().removeObserver(this);
                                        ^
C:\flutter_1.22\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-1.1.1\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapsPlugin.java:92: error: cannot find symbol
    lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
                ^
  symbol:   variable FlutterLifecycleAdapter
  location: class GoogleMapsPlugin
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output 13 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s


The plugin google_maps_flutter could not be built due to the issue above.
```
