### ISSUE TITLE
[Regression][Web] : Listview throws error:PersistedPhysicalShape: is in an unexpected state and freezes app

### ISSUE THREAD

**Issue by jinyuanqing** [flutter/flutter#72171]
**════════ Exception caught by scheduler library ═════════════════════════════════
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created**

flutter version:1.24.0-10.2.pre （beta）
doctor:all going well.

this my code:
_```
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home:MyHomePage(title: "ewr",) ,
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
           Friend()
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}



class Friend extends StatefulWidget {
  @override
  Friend11 createState() => new Friend11();
}

class Friend11 extends State<Friend> {
  TextEditingController _unameController = new TextEditingController();
  TextEditingController _pwdController = new TextEditingController();
  GlobalKey _formKey = new GlobalKey<FormState>();
  String mima1, mima2; //2次密码
  String shou_ji, yonghu_ming, you_xiang;
  String yonghu_ming1, mi_ma3, you_xiang1, shou_ji1;
  ScrollController controller1 = new ScrollController();
  @override
  void initState() {
    super.initState();
    //  zhu_ce_Dialog();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
        child: Container(
          height: 500,
            width: MediaQuery.of(context).size.width, //获取屏幕窗口的宽度,,
            color: Colors.black12,
            child: Padding(
                padding: EdgeInsets.all(10.0),
                // padding: const EdgeInsets.only(left: 8.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
               

                    // Container(
                    //     height: 500,
                    //     width:  MediaQuery.of(context).size.width , //获取屏幕窗口的宽度,,
                    //     child:
                    Expanded(
                        child: Scrollbar( 
    controller: controller1,

                            child: ListView.builder(
                    
                    
                                itemCount: 10 * 2, //message_send.length,
                                //itemExtent: 50.0, //强制高度为50.0,此处强制高度了,就会使发送过多的消息报错,高度溢出
                                itemBuilder: (BuildContext context, int index) {
                                  return Card(
                                    elevation: 10, //阴影
                                    color: Colors.white38,
                                    shadowColor: Colors.grey[100],
                                    // margin: EdgeInsets.all(10),
                                    child: Column(
                                      mainAxisAlignment:
                                          MainAxisAlignment.center,
                                      children: [
                                        // AspectRatio(
                                        //   aspectRatio:16 / 9,
                                        //   child: Icon(Icons.supervisor_account_rounded),
                                        // ),
                                        ListTile(
                                          title: Text(
                                            '用户名',
                                            style: TextStyle(fontSize: 22),
                                          ),
                                          subtitle: Text(
                                            '签名:我是一个新用户',
                                            overflow: TextOverflow.ellipsis,
                                          ),
                                          leading: CircleAvatar(
                                            child: Icon(Icons
                                                .supervisor_account_rounded),
                                          ),
                                        )
                                      ],
                                    ),
                                  );
                                })))
                  ],
                ))));
  }
}
```_
```

**Comment by darshankawar** [comment]
@jinyuanqing 
What platform do you see this error on ?

**Comment by jinyuanqing** [comment]
web platform.i found flutter 1.23 version is normal

**Comment by darshankawar** [comment]
@jinyuanqing 
When do you exactly get the error ? What are the steps to replicate the issue ?

**Comment by jinyuanqing** [comment]
When i slide the ListView up and down with mouse

**Comment by darshankawar** [comment]
@jinyuanqing 
With your code sample, I get below exception, but not consistently and also isn't same as what you shared earlier:

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/picture.dart:54:10
canvas == null || !_recycledCanvases.contains(canvas)
is not true

Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
```

Can you provide flutter run -d chrome -verbose logs to get complete error?

**Comment by jinyuanqing** [comment]
you So enthusiastic.now my flutter version is 1.23,not 1.24.so the error no found ,is normal.i think that flutter's version have a bug.

**Comment by darshankawar** [comment]
I am able to replicate the issue on latest beta and on latest master, by scrolling up and down a bit faster than usual after which the app freezes and throws below error log in the console:

<details>
<summary>error log</summary>

```

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/picture.dart:54:10
canvas == null || !_recycledCanvases.contains(canvas)
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/html/picture.dart 54:62                                    _recycleCanvas
lib/_engine/engine/html/picture.dart 591:5                                    discard
lib/_engine/engine/html/surface.dart 802:14                                   _discardActiveChildren
lib/_engine/engine/html/surface.dart 1149:5                                   discard
lib/_engine/engine/html/clip.dart 41:11                                       discard
lib/_engine/engine/html/surface.dart 802:14                                   _discardActiveChildren
lib/_engine/engine/html/surface.dart 1149:5                                   discard
lib/_engine/engine/html/surface.dart 802:14                                   _discardActiveChildren
lib/_engine/engine/html/surface.dart 1016:5                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/clip.dart 108:11                                      update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/clip.dart 329:11                                      update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/transform.dart 45:11                                  update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/scene_builder.dart 551:25                             <fn>
lib/_engine/engine/profiler.dart 36:18                                        timeAction
lib/_engine/engine/html/scene_builder.dart 547:12                             build
packages/flutter/src/rendering/layer.dart 770:35                              buildScene
packages/flutter/src/rendering/view.dart 231:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 458:18                            drawFrame
packages/flutter/src/widgets/binding.dart 895:13                              drawFrame
packages/flutter/src/rendering/binding.dart 320:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1055:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 971:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 892:13                            invoke
lib/_engine/engine/platform_dispatcher.dart 145:5                             invokeOnDrawFrame
lib/_engine/engine.dart 240:45                                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPicture: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

```

</details>

[72171_m125.mov.zip](https://github.com/flutter/flutter/files/5695547/72171_m125.mov.zip)

[72171_b124.mov.zip](https://github.com/flutter/flutter/files/5695549/72171_b124.mov.zip)

<details>
<summary>not working latest beta and master flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


[✓] Flutter (Channel master, 1.25.0-9.0.pre.57, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-9.0.pre.57 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f37969638d (8 hours ago), 2020-12-14 22:18:03 -0500
    • Engine revision 1749dbcc1b
    • Dart version 2.12.0 (build 2.12.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

</details>



Verified the same code sample on beta 1.23 on which the issue wasn't replicable after carrying out same / close to same steps.

[72171_b123.mov.zip](https://github.com/flutter/flutter/files/5695551/72171_b123.mov.zip)

<details>
<summary>working beta flutter doctor -v</summary>

```

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 198df796aa (9 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

</details>

Labeling it as regression, since the issue isn't replicable on beta 1.23 but is on 1.24 and on latest master 1.25.

**Comment by darshankawar** [comment]
The error log is similar to https://github.com/flutter/flutter/issues/70188, which was closed due to not reproducible.

**Comment by ferhatb** [comment]
Was fixed via https://github.com/flutter/engine/pull/23089 . Landed in Flutter master.

**Comment by darshankawar** [comment]
Per [this](https://github.com/flutter/flutter/issues/72813) issue and verification on latest master, the same error still persists. I am also able to replicate this issue using latest master:

```
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/picture.dart:54:10
canvas == null || !_recycledCanvases.contains(canvas)
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/html/picture.dart 54:62                                    _recycleCanvas
lib/_engine/engine/html/picture.dart 597:5                                    discard
lib/_engine/engine/html/surface.dart 802:14                                   _discardActiveChildren
lib/_engine/engine/html/surface.dart 1159:5                                   discard
lib/_engine/engine/html/clip.dart 41:11                                       discard
lib/_engine/engine/html/surface.dart 802:14                                   _discardActiveChildren
lib/_engine/engine/html/surface.dart 1159:5                                   discard
lib/_engine/engine/html/surface.dart 802:14                                   _discardActiveChildren
lib/_engine/engine/html/surface.dart 1016:5                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/clip.dart 108:11                                      update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/clip.dart 329:11                                      update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/offset.dart 49:11                                     update
lib/_engine/engine/html/surface.dart 945:17                                   [_updateManyToMany]
lib/_engine/engine/html/surface.dart 713:7                                    update
lib/_engine/engine/html/transform.dart 45:11                                  update
lib/_engine/engine/html/surface.dart 848:15                                   [_updateManyToOne]
lib/_engine/engine/html/surface.dart 709:7                                    update
lib/_engine/engine/html/scene_builder.dart 550:25                             <fn>
lib/_engine/engine/profiler.dart 36:18                                        timeAction
lib/_engine/engine/html/scene_builder.dart 546:12                             build
packages/flutter/src/rendering/layer.dart 770:35                              buildScene
packages/flutter/src/rendering/view.dart 231:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 458:18                            drawFrame
packages/flutter/src/widgets/binding.dart 903:13                              drawFrame
packages/flutter/src/rendering/binding.dart 320:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1144:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1082:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 998:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 896:13                            invoke
lib/_engine/engine/platform_dispatcher.dart 145:5                             invokeOnDrawFrame
lib/_engine/engine.dart 246:45                                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPicture: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.117, on Mac OS X 10.15.4 19E2269 darwin-x64, locale
    en-IN)
    • Flutter version 1.26.0-2.0.pre.117 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 15c009b805 (7 hours ago), 2020-12-22 20:09:03 -0500
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds
        to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f                     • android-arm
      • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64
      • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript
      • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

**Comment by darshankawar** [comment]
Cc : @ferhatb for visibility.

**Comment by ferhatb** [comment]
Note: verified that a crash happens in pointer_converter that causes PersistedPhysicalShape to get into invalid state.

**Comment by liubrandon** [comment]
I also am experiencing this crash when quickly scrolling through a CustomScrollView with a SliverChildBuilderDelegate on 1.25.0-8.1.pre. Switching to a pre-built list of SliverToBoxAdaptors is a temporary solution but is too memory intensive when the list becomes large

**Comment by ferhatb** [comment]
@darshankawar , master updated. Can you please try new build. thx!

**Comment by darshankawar** [comment]
@ferhatb Verified on latest master and don't see the error anymore. Thanks.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.220, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.220 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 01babcac16 (85 minutes ago), 2021-01-06 22:34:03 -0500
    • Engine revision 1758eaa4ed
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    •
      Android 11 (API 30) (emulator)
    • macOS (desktop)                  • macos         • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                     • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>
