### ISSUE TITLE
[camera] [crash] Methods marked with @UiThread must be executed on the main thread

### ISSUE THREAD

**Issue by xhu-ww** [flutter/flutter#72340]
## Problem

**Camera ^0.5.8+17** crashes during frequent creation and destruction on Android

```
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-13-thread-1
```

## Steps to Reproduce

1. Use BottomNavigationBar or PopupMenu to switch pages
2. switch between the camera page and other pages multiple times
3. crash

## Crash Logs

```
E/AndroidRuntime(24815): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-13-thread-1
E/AndroidRuntime(24815): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
E/AndroidRuntime(24815): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
E/AndroidRuntime(24815): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime(24815): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:363)
E/AndroidRuntime(24815): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:168)
E/AndroidRuntime(24815): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:221)
E/AndroidRuntime(24815): 	at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:49)
E/AndroidRuntime(24815): 	at io.flutter.plugins.camera.Camera$4.onConfigured(Camera.java:323)
E/AndroidRuntime(24815): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime(24815): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(24815): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(24815): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(24815): 	at java.lang.Thread.run(Thread.java:929)
```

## Flutter Doctor
```
wen:flutter_necsports wangwen$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.14.6 18G87 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Library/flutter
    • Framework revision 7891006299 (5 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/wangwen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/wangwen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[!] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • ELE AL00 (mobile) • 8KE0219323016342 • android-arm64 • Android 10 (API 29)

```

**Comment by pedromassangocode** [comment]
Hi @xhu-ww 
Can you please provide  a minimal complete reproducible code sample?
Thank you

**Comment by xhu-ww** [comment]
@pedromassangocode 

## main

```
import 'package:flutter/material.dart';
import 'package:flutter_app/camera_page.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Camera'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _pageIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [
          PopupMenuButton(
            onSelected: (value) => setState(() => _pageIndex = value),
            itemBuilder: (BuildContext context) =>
            <PopupMenuEntry<int>>[
              PopupMenuItem(value: 0, child: Text('Camera')),
              PopupMenuItem(value: 1, child: Text('Other'))
            ],
          ),
        ],
      ),
      body: _pageIndex == 0 ? CameraPage() : Container(),
    );
  }
}

```

## camera page

```
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CameraPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _CameraPageState();
}

class _CameraPageState extends State<CameraPage> {
  CameraController _cameraController;

  @override
  void initState() {
    super.initState();
    _initializeCamera();
  }

  void _initializeCamera() async {
    var _backCamera = await availableCameras().then((cameras) {
      return cameras.firstWhere(
        (camera) => camera.lensDirection == CameraLensDirection.back,
      );
    });

    _cameraController = CameraController(
      _backCamera,
      Platform.isIOS ? ResolutionPreset.medium : ResolutionPreset.high,
      enableAudio: false,
    );

    await _cameraController.initialize().then((value) {
      if (mounted) setState(() {});
    });

    _cameraController.startImageStream((image) {});
  }

  @override
  void dispose() {
    _cameraController.stopImageStream();
    // No matter whether this line of code is executed or not, it will crash
    _cameraController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _cameraController?.value?.isInitialized ?? false
        ? Stack(fit: StackFit.expand, children: [
            AspectRatio(
              aspectRatio: _cameraController.value.aspectRatio,
              child: CameraPreview(_cameraController),
            )
          ])
        : Container(
            color: Colors.black,
            child: Center(child: CircularProgressIndicator()),
          );
  }
}
```

**Comment by pedromassangocode** [comment]
Reproducible on latest version (`camera: ^0.5.8+17`).


<details><summary>Logs</summary>

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
Plugin project :path_provider_macos not found. Please update settings.gradle.
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:51877/L6uUGUByT3s=/ws
Syncing files to device sdk gphone x86 arm...
I/CameraManagerGlobal( 5556): Connecting to camera service
W/Gralloc4( 5556): allocator 3.x is not supported
I/evercode.triag( 5556): Background concurrent copying GC freed 2203(251KB) AllocSpace objects, 27(25MB) LOS objects, 49% free, 14MB/29MB, paused 1.058ms total 231.099ms
W/System  ( 5556): A resource failed to call release. 
I/evercode.triag( 5556): Background concurrent copying GC freed 562(82KB) AllocSpace objects, 27(22MB) LOS objects, 49% free, 12MB/25MB, paused 26us total 129.334ms
I/evercode.triag( 5556): Background concurrent copying GC freed 233(66KB) AllocSpace objects, 14(13MB) LOS objects, 49% free, 14MB/29MB, paused 23us total 189.126ms
I/evercode.triag( 5556): Background concurrent copying GC freed 330(79KB) AllocSpace objects, 13(11MB) LOS objects, 49% free, 21MB/43MB, paused 24us total 140.773ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 762(107KB) AllocSpace objects, 42(37MB) LOS objects, 37% free, 27MB/43MB, paused 26us total 130.607ms
I/evercode.triag( 5556): Background concurrent copying GC freed 316(79KB) AllocSpace objects, 12(11MB) LOS objects, 43% free, 31MB/55MB, paused 2.881ms total 333.559ms
I/evercode.triag( 5556): Background concurrent copying GC freed 1281(98KB) AllocSpace objects, 68(60MB) LOS objects, 49% free, 14MB/28MB, paused 202us total 213.564ms
I/evercode.triag( 5556): Background concurrent copying GC freed 249(82KB) AllocSpace objects, 8(8576KB) LOS objects, 49% free, 20MB/41MB, paused 25us total 202.950ms
I/evercode.triag( 5556): Background concurrent copying GC freed 761(99KB) AllocSpace objects, 37(30MB) LOS objects, 49% free, 16MB/33MB, paused 28us total 468.206ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 317(78KB) AllocSpace objects, 18(15MB) LOS objects, 0% free, 25MB/25MB, paused 9.780ms total 539.979ms
I/evercode.triag( 5556): Background concurrent copying GC freed 962(112KB) AllocSpace objects, 47(40MB) LOS objects, 49% free, 23MB/46MB, paused 22us total 981.242ms
I/Choreographer( 5556): Skipped 31 frames!  The application may be doing too much work on its main thread.
I/evercode.triag( 5556): Background young concurrent copying GC freed 1072(121KB) AllocSpace objects, 48(42MB) LOS objects, 51% free, 22MB/46MB, paused 22us total 245.053ms
I/evercode.triag( 5556): Background concurrent copying GC freed 690(98KB) AllocSpace objects, 30(26MB) LOS objects, 49% free, 12MB/25MB, paused 29us total 224.067ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 45(45KB) AllocSpace objects, 2(2708KB) LOS objects, 0% free, 20MB/20MB, paused 29us total 300.139ms
I/evercode.triag( 5556): Background concurrent copying GC freed 680(78KB) AllocSpace objects, 30(26MB) LOS objects, 49% free, 9667KB/18MB, paused 25us total 304.845ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 322(60KB) AllocSpace objects, 18(15MB) LOS objects, 0% free, 20MB/20MB, paused 3.343ms total 766.890ms
I/evercode.triag( 5556): Background concurrent copying GC freed 1077(130KB) AllocSpace objects, 37(32MB) LOS objects, 49% free, 13MB/27MB, paused 23us total 1.551s
I/evercode.triag( 5556): Background young concurrent copying GC freed 672(89KB) AllocSpace objects, 25(22MB) LOS objects, 72% free, 7883KB/27MB, paused 21.900ms total 189.334ms
I/evercode.triag( 5556): Background concurrent copying GC freed 1146(83KB) AllocSpace objects, 43(38MB) LOS objects, 46% free, 27MB/51MB, paused 26us total 945.425ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 972(89KB) AllocSpace objects, 49(43MB) LOS objects, 52% free, 21MB/45MB, paused 2.144ms total 168.731ms
I/evercode.triag( 5556): Background concurrent copying GC freed 1193(91KB) AllocSpace objects, 54(45MB) LOS objects, 41% free, 33MB/57MB, paused 22us total 224.797ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 1180(103KB) AllocSpace objects, 61(53MB) LOS objects, 33% free, 38MB/57MB, paused 8.196ms total 207.023ms
I/evercode.triag( 5556): Background concurrent copying GC freed 653(87KB) AllocSpace objects, 24(21MB) LOS objects, 49% free, 8778KB/17MB, paused 533us total 123.065ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 21(62KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 7417KB/7417KB, paused 6.073ms total 22.376ms
I/evercode.triag( 5556): Background concurrent copying GC freed 257(80KB) AllocSpace objects, 7(6324KB) LOS objects, 49% free, 11MB/23MB, paused 851us total 135.787ms
I/evercode.triag( 5556): Background concurrent copying GC freed 350(82KB) AllocSpace objects, 17(14MB) LOS objects, 45% free, 28MB/52MB, paused 20us total 518.407ms
I/evercode.triag( 5556): Background concurrent copying GC freed 837(98KB) AllocSpace objects, 36(31MB) LOS objects, 49% free, 6514KB/12MB, paused 663us total 237.018ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 244(77KB) AllocSpace objects, 12(10MB) LOS objects, 50% free, 7403KB/14MB, paused 6.302ms total 17.712ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 43(77KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 7401KB/7401KB, paused 5.195ms total 15.089ms
I/evercode.triag( 5556): Background concurrent copying GC freed 556(62KB) AllocSpace objects, 17(17MB) LOS objects, 49% free, 16MB/33MB, paused 26us total 222.148ms
I/evercode.triag( 5556): Background young concurrent copying GC freed 521(60KB) AllocSpace objects, 31(27MB) LOS objects, 36% free, 20MB/33MB, paused 5.695ms total 89.619ms
E/AndroidRuntime( 5556): FATAL EXCEPTION: pool-7-thread-1
E/AndroidRuntime( 5556): Process: com.nevercode.triage, PID: 5556
E/AndroidRuntime( 5556): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-7-thread-1
E/AndroidRuntime( 5556): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1149)
E/AndroidRuntime( 5556): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:782)
E/AndroidRuntime( 5556): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime( 5556): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:363)
E/AndroidRuntime( 5556): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:168)
E/AndroidRuntime( 5556): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:221)
E/AndroidRuntime( 5556): 	at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:49)
E/AndroidRuntime( 5556): 	at io.flutter.plugins.camera.Camera$4.onConfigured(Camera.java:323)
E/AndroidRuntime( 5556): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime( 5556): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime( 5556): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 5556): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 5556): 	at java.lang.Thread.run(Thread.java:923)
I/Process ( 5556): Sending signal. PID: 5556 SIG: 9
Lost connection to device.

```
</details>

**Comment by amelmusic** [comment]
Same thing happening for us on 0.6.0 as well.

**Comment by ephammer** [comment]
Same problem here with `camera: ^0.6.2+1`

**Comment by suvlime** [comment]
some workaround?

**Comment by leszekkrol** [comment]
Try 6.3.1

**Comment by AlexHartford** [comment]
Still an issue with `camera: ^0.6.3+2`

**Comment by NgYewChun** [comment]
any fix?

**Comment by pedromassangocode** [comment]
Using "add reaction" on the initial comment would increase priority while +1 comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself, use the [Subscribe] button to the top right instead.

**Comment by jdeltoft** [comment]
I have this same issue with   camera: ^0.5.8+17

I'm on dev branch of flutter:

Flutter is already up to date on channel dev
Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (3 weeks ago) • 2020-12-13 23:19:13 +0800
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)

My app uses camera fine once, but when I come back to that stateful widget it crashes very repeatably

**Comment by jsroest** [comment]
A 'quick' workaround may to clone the code and change this file:
camera-0.6.4+5/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java

From:
```
void send(EventType eventType, Map<String, Object> args) {
    if (channel == null) {
      return;
    }
    channel.invokeMethod(eventType.toString().toLowerCase(), args);
  }
```
To:
```
  void send(EventType eventType, Map<String, Object> args) {
    if (channel == null) {
      return;
    }
    new Handler(Looper.getMainLooper()).post(new Runnable () {
      @Override
      public void run () {
        channel.invokeMethod(eventType.toString().toLowerCase(), args);
      }
    });
  }
```

This seems to fix the crash for me but might introduce other issues. I have no idea about any side-effects.

**Comment by jsroest** [comment]
You can test if the workaround above fixes it for you:
```
dependencies:
  flutter:
    sdk: flutter
  camera:
    git:
      url: git@github.com:jsroest/plugins.git
      path: packages/camera/camera
      ref: camera-v0.6.4+5hotfix
```

**Comment by Aperico-com** [comment]
This happens often when switching from front to back camera for me during initialization of the camera and more specifically when doing: controller.startImageStream((CameraImage image) async {

0.6.4+5
flutter doctor -v
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale sv-SE)
    • Flutter version 1.25.0-8.2.pre at D:\flutter_sdk\flutter
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\dev\adtsdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\dev\adtsdk
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at D:\IntelliJ IDEA
    • Flutter plugin version 52.0.4
    • Dart plugin version 202.8070

[√] Connected device (1 available)
    • MRD LX1 (mobile) • 192.168.100.104:5555 • android-arm • Android 9 (API 28)

• No issues found!

Looking at the source code for camera I come to the same conclusion as @jsroest that there is no measures to address this issue [(https://github.com/flutter/flutter/issues/34993)]

**Comment by svenjacobs** [comment]
Same issue with version `0.6.4+5` on a Xiaomi Mi A1 with Android 9. Can't reproduce this crash on a Google Pixel 1 (Android 10) and Google Pixel 4XL (Android 11).

**Comment by yy1300326388** [comment]
I solved this problem like this.

![image](https://user-images.githubusercontent.com/8764899/104696992-094a6900-574a-11eb-895b-1e1f60ee84cc.png)
```java
package io.flutter.plugins.camera;

import android.os.Handler;
import android.os.Looper;
import android.text.TextUtils;

import androidx.annotation.Nullable;

import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.EventChannel;

import java.util.HashMap;
import java.util.Map;

class DartMessenger {
    @Nullable
    private EventChannel.EventSink eventSink;
    private Handler handler;

    enum EventType {
        ERROR,
        CAMERA_CLOSING,
    }

    DartMessenger(BinaryMessenger messenger, long eventChannelId) {
        new EventChannel(messenger, "flutter.io/cameraPlugin/cameraEvents" + eventChannelId)
                .setStreamHandler(
                        new EventChannel.StreamHandler() {
                            @Override
                            public void onListen(Object arguments, EventChannel.EventSink sink) {
                                eventSink = sink;
                                handler = new Handler(Looper.getMainLooper());
                            }

                            @Override
                            public void onCancel(Object arguments) {
                                eventSink = null;
                                handler.removeCallbacksAndMessages(null);
                                handler = null;
                            }
                        });
    }

    void sendCameraClosingEvent() {
        send(EventType.CAMERA_CLOSING, null);
    }

    void send(EventType eventType, @Nullable String description) {
        if (eventSink == null || handler == null) {
            return;
        }

        Map<String, String> event = new HashMap<>();
        event.put("eventType", eventType.toString().toLowerCase());
        // Only errors have a description.
        if (eventType == EventType.ERROR && !TextUtils.isEmpty(description)) {
            event.put("errorDescription", description);
        }

        handler.post(() -> eventSink.success(event));
    }
}
````

**Comment by petodavid** [comment]
**Same issue on Nokia 5.3 (Android 10), any working solution?**

**Comment by petodavid** [comment]
> I solved this problem like this.
> 
> ![image](https://user-images.githubusercontent.com/8764899/104696992-094a6900-574a-11eb-895b-1e1f60ee84cc.png)
> 
> ```java
> package io.flutter.plugins.camera;
> 
> import android.os.Handler;
> import android.os.Looper;
> import android.text.TextUtils;
> 
> import androidx.annotation.Nullable;
> 
> import io.flutter.plugin.common.BinaryMessenger;
> import io.flutter.plugin.common.EventChannel;
> 
> import java.util.HashMap;
> import java.util.Map;
> 
> class DartMessenger {
>     @Nullable
>     private EventChannel.EventSink eventSink;
>     private Handler handler;
> 
>     enum EventType {
>         ERROR,
>         CAMERA_CLOSING,
>     }
> 
>     DartMessenger(BinaryMessenger messenger, long eventChannelId) {
>         new EventChannel(messenger, "flutter.io/cameraPlugin/cameraEvents" + eventChannelId)
>                 .setStreamHandler(
>                         new EventChannel.StreamHandler() {
>                             @Override
>                             public void onListen(Object arguments, EventChannel.EventSink sink) {
>                                 eventSink = sink;
>                                 handler = new Handler(Looper.getMainLooper());
>                             }
> 
>                             @Override
>                             public void onCancel(Object arguments) {
>                                 eventSink = null;
>                                 handler.removeCallbacksAndMessages(null);
>                                 handler = null;
>                             }
>                         });
>     }
> 
>     void sendCameraClosingEvent() {
>         send(EventType.CAMERA_CLOSING, null);
>     }
> 
>     void send(EventType eventType, @Nullable String description) {
>         if (eventSink == null || handler == null) {
>             return;
>         }
> 
>         Map<String, String> event = new HashMap<>();
>         event.put("eventType", eventType.toString().toLowerCase());
>         // Only errors have a description.
>         if (eventType == EventType.ERROR && !TextUtils.isEmpty(description)) {
>             event.put("errorDescription", description);
>         }
> 
>         handler.post(() -> eventSink.success(event));
>     }
> }
> ```
> 
> * reference #34993

As is see this does not work at all.

**Comment by jsroest** [comment]
> **Same issue on Nokia 5.3 (Android 10), any working solution?**

Try my solution above....

**Comment by fuadarradhi** [comment]
same here, but error only when `stopImageStream()` on dispose,
no error if i not use that.

```
// _controller?.stopImageStream();
_controller?.dispose();
```

**Comment by jdeltoft** [comment]
@petodavid Thanks for sharing.  It took me a bit to find the right DartMessenger.java file.  In android studio it seems to only find the ios file.  Does ios have this issue btw?  I only tested so far on Android.  

Anyway, so far so good with the camera how I used to get crashes.  But then I let it sit for 5 min (I have a camera disable with no motion) and then I got a new error on picking up the phone.  Not sure yet if this is my issue or camera:

```
E/AndroidRuntime(30996): FATAL EXCEPTION: pool-202-thread-1
E/AndroidRuntime(30996): Process: com.myapp, PID: 30996
E/AndroidRuntime(30996): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.setRepeatingRequest(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
E/AndroidRuntime(30996):    at io.flutter.plugins.camera.Camera$4.onConfigured(Camera.java:318)
E/AndroidRuntime(30996):    at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime(30996):    at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(30996):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(30996):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(30996):    at java.lang.Thread.run(Thread.java:919)
I/Process (30996): Sending signal. PID: 30996 SIG: 9
Lost connection to device.
```

**Comment by jdeltoft** [comment]
@petodavid Are you sure you altered the proper file for the package version you're using and the os (ios or android)

**Comment by cyanglaz** [comment]
Looks like this is fixed by https://github.com/flutter/plugins/pull/3444. Should we close this issue? @mvanbeusekom

**Comment by mvanbeusekom** [comment]
Thanks for the reminder @cyanglaz it indeed can be closed. Doing so now.

**Comment by nateshmbhat** [comment]
This issue is still happening to me after updating to camera 0.7.0+1 version. 

```
E/SensorManager(30815): unregisterListenerImpl callingApp: com.application.example.card_scanner_example_app,callingPid:30815,callingUid:10765
E/AndroidRuntime(30815): FATAL EXCEPTION: pool-23-thread-1
E/AndroidRuntime(30815): Process: com.application.example.card_scanner_example_app, PID: 30815
E/AndroidRuntime(30815): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-23-thread-1
E/AndroidRuntime(30815): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
E/AndroidRuntime(30815): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
E/AndroidRuntime(30815): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime(30815): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:381)
E/AndroidRuntime(30815): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:179)
E/AndroidRuntime(30815): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:97)
E/AndroidRuntime(30815): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:107)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.DartMessenger.sendCameraErrorEvent(DartMessenger.java:90)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.Camera$2.lambda$onConfigured$0$Camera$2(Camera.java:321)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.-$$Lambda$Camera$2$qVh0Fkc7KexbRseEAqXXeil7smk.onError(Unknown Source:2)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:384)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.Camera.access$1300(Camera.java:73)
E/AndroidRuntime(30815): 	at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:320)
E/AndroidRuntime(30815): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime(30815): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(30815): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(30815): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(30815): 	at java.lang.Thread.run(Thread.java:919)
I/Process (30815): Sending signal. PID: 30815 SIG: 
```

Someone please help

**Comment by mvanbeusekom** [comment]
@nateshmbhat according to the stack trace you provided the error is caused on line [107](https://github.com/flutter/plugins/blob/04b0b4b13f59bea7b3375dbe2c5a013e6f0ed5a4/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java#L107) in DartMessenger.java. 

This line simply returns the `send` method since the `cameraChannel` is `null`, which cannot cause the actual exception you are receiving. This leads me to believe you have are running against an older cached version. Could you try the following:

1. Clear the Flutter build cache by running the `flutter clean` command;
2. Next run `flutter pub get` to make sure you download all Flutter dependencies;
3. Now try again.

Please let me know if this works.

**Comment by nateshmbhat** [comment]
@mvanbeusekom i have already run flutter clean , flutter pub get , flutter pub cache repair

**Comment by nateshmbhat** [comment]
in the project structure at the left side bar of android studio , when i look at the flutter plugin being used , it shows 0.7.0+1 itself 😕

**Comment by nateshmbhat** [comment]
Here's the error i'm getting now : 

```
E/SensorManager(13659): unregisterListenerImpl callingApp: com.application.example.card_scanner_example_app,callingPid:13659,callingUid:10767
E/AndroidRuntime(13659): FATAL EXCEPTION: pool-14-thread-1
E/AndroidRuntime(13659): Process: com.application.example.card_scanner_example_app, PID: 13659
E/AndroidRuntime(13659): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-14-thread-1
E/AndroidRuntime(13659): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
E/AndroidRuntime(13659): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
E/AndroidRuntime(13659): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime(13659): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:381)
E/AndroidRuntime(13659): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:179)
E/AndroidRuntime(13659): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:97)
E/AndroidRuntime(13659): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:107)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.DartMessenger.sendCameraErrorEvent(DartMessenger.java:90)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.Camera$2.lambda$onConfigured$0$Camera$2(Camera.java:321)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.-$$Lambda$Camera$2$qVh0Fkc7KexbRseEAqXXeil7smk.onError(Unknown Source:2)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:384)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.Camera.access$1300(Camera.java:73)
E/AndroidRuntime(13659): 	at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:320)
E/AndroidRuntime(13659): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime(13659): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(13659): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(13659): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(13659): 	at java.lang.Thread.run(Thread.java:919)
I/Process (13659): Sending signal. PID: 13659 SIG: 9
Lost connection to device.

```

**Comment by jsroest** [comment]
@nateshmbhat and @mvanbeusekom
I did have issues when I was using my own fork when using the 'git reference' (as described above). I had to right click the android studio project and then choose "Reload from disk". That was for me the only way to update the contents of "External Plugins => Flutter Plugins => camera" to the latest version. Maybe this is related?

**Comment by nateshmbhat** [comment]
its possible @jsroest , i just recloned the entire repo and flushed the pub cache. Now the crash is not happening based on my current tests. Looks like it was cache issue after all. 

i will update here if i find a crash like this again 👍🏻  Thanks for the support @mvanbeusekom

**Comment by mvanbeusekom** [comment]
@nateshmbhat good to know it is working now. I really think it had to do with a caching issue, since this error doesn't make any sense on the reported line in version 0.7.0+1 (it does however make sense on the previous version).
