### ISSUE TITLE
'IntegrationTest/IntegrationTestIosTest.h' file not found error after adding UI Test Target from xcode and trying to build for testing

### ISSUE THREAD

**Issue by kalsariyac** [flutter/flutter#72876]
## Steps to Reproduce

1. Install the `integration_test` package in the `dev_dependencies` section of pubspec.yaml.
2. Run the test case using the flutter command, working as expected.
3. Open Xcode project `ios/Runner.xcworkspace`. 
4. Create a UI Test target as named RunnerTests and change the code into RunnerTests.m.
```
#import <XCTest/XCTest.h>
#import <integration_test/IntegrationTestIosTest.h>

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
```

5. Goto Product -> Build For -> Testing 
**Expected results:**  It should be build successfully.

**Actual results:** getting error on import into RunnerTests.h file `'IntegrationTest/IntegrationTestIosTest.h' file not found`

<details>
  <summary>Logs</summary>
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E266 darwin-x64,
    locale en-GB)
    • Flutter version 1.22.5 at /Applications/flutter
    • Framework revision 7891006299 (13 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sunflower/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • A1ACE6FF-3C31-4937-8413-EBB48BE7DB80 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

**Comment by darshankawar** [comment]
@kalsariyac 
Tried your steps to replicate, but was able to build successfully.

<img width="754" alt="Screenshot 2020-12-28 at 12 35 39 PM" src="https://user-images.githubusercontent.com/67046386/103196037-74eaa480-4909-11eb-9136-96990428b91b.png">
<img width="743" alt="Screenshot 2020-12-28 at 12 37 22 PM" src="https://user-images.githubusercontent.com/67046386/103196045-77e59500-4909-11eb-9536-c5ec515354f5.png">


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available


```

</details>

I added `New -> Target -> UI Testing Bundle`.

**Comment by Purvik** [comment]
@kalsariyac  @darshankawar I tried at my end but not able to perform successful run. 
Check attached image. 
![Uploading image.png…](iOS Build Error)

**Comment by workerbee22** [comment]
Same problem ... which step should create the `IntegrationTestIosTest.h` file ?

**Comment by blaugold** [comment]
For me, the problem was that creating the test target did not set it up with the required configuration files:
<img width="766" alt="Screenshot 2020-12-31 at 11 51 29" src="https://user-images.githubusercontent.com/5929595/103407393-d8214480-4b5e-11eb-8a28-e30630be14d8.png">

After setting the same configuration files for `RunnerTests` as for `Runner` the tests compile and run:
<img width="766" alt="Screenshot 2020-12-31 at 11 51 45" src="https://user-images.githubusercontent.com/5929595/103407516-41a15300-4b5f-11eb-8b77-c4cd75da6c4e.png">

**Comment by workerbee22** [comment]
@blaugold This change did not fix the missing` IntegrationTestIosTest.h `file error for me

**Comment by blaugold** [comment]
@workerbee22 [IntegrationTestIosTest.h](https://github.com/flutter/plugins/blob/master/packages/integration_test/ios/Classes/IntegrationTestIosTest.h) is part of the iOS implementation of `integartion_test ` and should be on the search path for projects which depend on it.

**Comment by workerbee22** [comment]
@blaugold Yes it should be found and is in my project. But is clearly not being found.

@kalsariyac I'm using Xcode 12.3 are you also on that version? @blaugold and @darshankawar what version of Xcode are you using?

**Comment by kalsariyac** [comment]
@workerbee22 I am using XCode 12.0.1

**Comment by workerbee22** [comment]
Downgraded to Xcode 12.2 (from 12.3) and ran through the entire setup for **RunnerTests** again. Now works fine 👍

**Comment by kalsariyac** [comment]
Thanks, @blaugold  
By setting the test target required configuration solved the issue. now  I am able to build for testing.
https://github.com/flutter/flutter/issues/72876#issuecomment-752924127

**Comment by workerbee22** [comment]
@kalsariyac Now that you can also build for testing ... not part of this issue, but can you actually successfully run XCtests? I'm having loads of issues getting the tests to run successfully.

**Comment by darshankawar** [comment]
@kalsariyac Good to know your issue is resolved. I am going ahead and closing this based on your last comment.https://github.com/flutter/flutter/issues/72876#issuecomment-753294666

@workerbee22 feel free to open a new issue if you have any questions around documentation

**Comment by istornz** [comment]
Hello all!
@blaugold fix the file not found issue for me, test build successfully now. But when I try to launch it from Xcode I got
```
(dlopen_preflight(/var/containers/Bundle/Application/A2FE77B9-09D9-48F8-9636-5445206BB015/RunnerTests-Runner.app/PlugIns/RunnerTests.xctest/RunnerTests): Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /var/containers/Bundle/Application/A2FE77B9-09D9-48F8-9636-5445206BB015/RunnerTests-Runner.app/PlugIns/RunnerTests.xctest/RunnerTests
  Reason: image not found)
```

Any clues ?
Thanks 👍 

Note: I'm on Xcode 12.3

**Comment by workerbee22** [comment]
Bug is NOT fixed for me either. Note there is already an issue for 'unclear iOS instructions' on this issue here, from when it was previously called E2E:

https://github.com/flutter/flutter/issues/48600

**Comment by letsar** [comment]
Hi, I'm having the same issue, can we reopen this?

**Comment by Jonas-Sander** [comment]
Oh my god this documentation is not good and definitely has to be done better.    
I have to be honest: As a flutter user I don't exactly know the ins and outs of XCode and I need clear, reproducible and explainatory steps. Currently it is way too lacking to get set up on ios for me.

**Comment by Jonas-Sander** [comment]
https://github.com/flutter/flutter/issues/72876#issuecomment-752924127 did not fix it for me.

**Comment by Jonas-Sander** [comment]
tagging you @darshankawar because of the questions to reopen the ticket from several people including me

**Comment by lucasselani** [comment]
Hi, I'm having this issue too in Xcode 12.4. I've already tried #48600 and #72876 (comment).


```shell
fatal error: 'IntegrationTest/IntegrationTestIosTest.h' file not found
    #import <IntegrationTest/IntegrationTestIosTest.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by darshankawar** [comment]
Sorry for not getting back earlier to this issue. Reopening and keeping it opening for further insights.

**Comment by darshankawar** [comment]
Cc: @dnfield

**Comment by kf6gpe** [comment]
cc @jmagman and @xster, too.

**Comment by jmagman** [comment]
The actual instructions are at https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing

I suspect you're all missing the Podfile `inherit! :search_paths` change.
```
  target 'RunnerTests' do
    inherit! :search_paths
  end
```

@dnfield Should we unpublish https://pub.dev/packages/integration_test in favor of the SDK version?  It's already out of date.

**Comment by dnfield** [comment]
Once the ask version is available on stable we can mark it as discontinued

**Comment by jmagman** [comment]
> Once the ask version is available on stable we can mark it as discontinued

Should we copy over the SDK version to the plugins repo and keep it up to date on pub then?  I can't remember if there were any problems with that.

**Comment by dnfield** [comment]
Version constraint issues :(

**Comment by jmagman** [comment]
Closing this, I believe this was a documentation issue.
