### ISSUE TITLE
Hard to tap when resampling enabled on Samsung Galaxy S20 Ultra

### ISSUE THREAD

**Issue by ekasetiawans** [flutter/flutter#73286]
## Steps to Reproduce

1. Enable resampling by `GestureBinding.instance.resamplingEnabled = true;`
2. run app
3. every inkwell or button hard to tap.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
Last login: Mon Jan  4 17:06:17 on ttys147
ekasetiawans@MacBookPro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on macOS 11.1 20C69 darwin-x64,
    locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)
    ! Error: Errors were encountered while preparing your device for
      development. Please check the Devices and Simulators Window.  (code -1)

• No issues found!
ekasetiawans@MacBookPro ~ % 
```

</details>

Note:
I don't have the device, but this is based on the incoming reports from my app users. The app currently runs smoothly if I disable resampling.

**Comment by ekasetiawans** [comment]
the device has a display with 120hz

**Comment by pedromassangocode** [comment]
Hi @ekasetiawans 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Can you please elaborate what "hard to tap" means?

Thank you

**Comment by ekasetiawans** [comment]
@pedromassangocode I mean, we have to tap many times. But I just experienced this on the Samsung Galaxy S20 Ultra, haven't experienced it on other devices.

**Comment by ekasetiawans** [comment]
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GestureBinding.instance.resamplingEnabled = true;
  
  runApp(MyApp());
}
```

I just use that method to enable resampling. then all buttons, inkwell or gesture detectors become difficult to press.

**Comment by pedromassangocode** [comment]
Hi @ekasetiawans 
Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you

**Comment by ekasetiawans** [comment]
@pedromassangocode https://github.com/ekasetiawans/hard_tap_issue

**Comment by pedromassangocode** [comment]
Leaving this opened for further investigation because I don't have the mentioned device. I cannot reproduce this on Xiaomi Redmi 5Plus (Android 8) device.

Code taken from https://github.com/flutter/flutter/issues/73286#issuecomment-754578046.

<details><summary>Code</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GestureBinding.instance.resamplingEnabled = true;

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

**Comment by Benjy04** [comment]
Same issue here, but with every Samsung device. Not only the Galaxy S20 Ultra.

**Comment by ilkercankaya** [comment]
With flutter 2.0, my app broke when I used the line `GestureBinding.instance.resamplingEnabled = true;`, I could not tap any buttons. The buttons registers onTap If I spam it for 15 20 times.

**Comment by nemoryoliver** [comment]
I have the same issue. Compiled my app with Flutter 2.0 with GestureBinding.instance.resamplingEnabled = true; and it broke on all samsung device users.

**Comment by ajviera** [comment]
This doesn't only happen on Android or Samsung, it also happens to me and my team using any Simulator, in my case I use a Simulator with iPhone 12 Pro. Removing it solves it, but it would be nice not to have to remove it.

**Comment by kuhnroyal** [comment]
Having the same problem on all Samsung devices.

**Comment by andreystavitsky** [comment]
Same issue on Galaxy S20+ and Galaxy S21+

**Comment by mikeborodin** [comment]
I have exact same issue on Samsung S9 android 10. 
`GestureBinding.instance.resamplingEnabled = true;`
makes all buttons and other widgets 95% unclickable: buttons' `onPressed` is called very rarely. Removing the line  makes everything clickable again.
On Simulator/emulator, LG V20, Redmi Mi10Pro, ZTE Axon 7 everything works just fine.

 Did anyone find some workaround already?

**Comment by kuhnroyal** [comment]
> Did anyone find some workaround already?

Yes, disable `resamplingEnabled` :)

**Comment by Doflatango** [comment]
+1 on all Samsung devices.

**Comment by Shakle** [comment]
Confirm, the issue exists in Flutter 2.0.4. Had to switch off.
Reproduces on Samsung devices with flag true.

**Comment by sanjidbillah** [comment]
Same issue on Galaxy J7 Prime

**Comment by LinXiaoTao** [comment]
I think it was caused by this commit https://github.com/flutter/flutter/pull/67080.
When converting PointerDownEvent to PointerMoveEvent(**see code 1**), `buttons` are 0(**see code 2**), so the `stopTrackingPointer` method is executed(**see code 3**) and the tap callback is cancelled.
``` dart
// src/gestures/resampler.dart
if (event is! PointerMoveEvent && event is! PointerHoverEvent) {                                    
  // Add synthetics `move` or `hover` event if position has changed.                                
  // Note: Devices without `hover` events are expected to always have                               
  // `add` and `down` events with the same position and this logic will                             
  // therefor never produce `hover` events.                                                         
  if (position != _position) {                                                                      
    final Offset delta = position - _position; 
    // code 1                                                     
    callback(_toMoveOrHoverEvent(event, position, delta, _pointerIdentifier, sampleTime, wasDown)); 
    _position = position;                                                                           
  }                                                                                                 
  callback(event.copyWith(                                                                          
    position: position,                                                                             
    delta: Offset.zero,                                                                             
    pointer: pointerIdentifier,                                                                     
    timeStamp: sampleTime,                                                                          
  ));                                                                                               
} 

PointerEvent _toMoveEvent(                     
  PointerEvent event,                          
  Offset position,                             
  Offset delta,                                
  int pointerIdentifier,                       
  Duration timeStamp,                          
) { 
  // code 2                                           
  return PointerMoveEvent(                     
    timeStamp: timeStamp,                      
    pointer: pointerIdentifier,                
    kind: event.kind,                          
    device: event.device,                      
    position: position,                        
    delta: delta,                              
    buttons: event.buttons,                    
    obscured: event.obscured,                  
    pressure: event.pressure,                  
    pressureMin: event.pressureMin,            
    pressureMax: event.pressureMax,            
    distanceMax: event.distanceMax,            
    size: event.size,                          
    radiusMajor: event.radiusMajor,            
    radiusMinor: event.radiusMinor,            
    radiusMin: event.radiusMin,                
    radiusMax: event.radiusMax,                
    orientation: event.orientation,            
    tilt: event.tilt,                          
    platformData: event.platformData,          
    synthesized: event.synthesized,            
    embedderId: event.embedderId,              
  );                                           
}                                                                                                                                                
```
                                                      
``` dart
// src/gestures/tap.dart
@override                                                
void handlePrimaryPointer(PointerEvent event) {          
  if (event is PointerUpEvent) {                         
    _up = event;                                         
    _checkUp();                                          
  } else if (event is PointerCancelEvent) {              
    resolve(GestureDisposition.rejected);                
    if (_sentTapDown) {                                  
      _checkCancel(event, '');                           
    }                                                    
    _reset();                                            
  } else if (event.buttons != _down!.buttons) {          
    resolve(GestureDisposition.rejected); 
    // code 3          
    stopTrackingPointer(primaryPointer!);                
  }                                                      
}  
```

**Comment by admincode1** [comment]
> On Simulator/emulator, LG V20, Redmi Mi10Pro, ZTE Axon 7 everything works just fine.

Is it fixing the scrolling issue in these devices (with 120 HZ)?
Not able to test on Samsung S20 FE.

**Comment by nt4f04uNd** [comment]
I suppose the issue can be closed, since the fix has landed in master

**Comment by githubjin** [comment]
same issue for 2.0.6 @nt4f04uNd @dreveman 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Closing this as fixed in https://github.com/flutter/flutter/pull/81022. The fix is currently in Master and it may take some time to land on the stable channel.

**Comment by b1acKr0se** [comment]
@pedromassango Hello, this issue still persists in Flutter 2.2.3. Is there any plan on which version the fix will land in?

**Comment by nemoryoliver** [comment]
> @pedromassango Hello, this issue still persists in Flutter 2.2.3. Is there any plan on which version the fix will land in?

I can confirm as well. I assumed the issue was fixed already in Stable and published my new update.

**Comment by admincode1** [comment]
Unfortunately, it's not a complete fix, tested on Samsung S20 FE, works fine on 95%+ but for example, some onTaps not working.

Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)

**Comment by LinXiaoTao** [comment]
> Unfortunately, it's not a complete fix, tested on Samsung S20 FE, works fine on 95%+ but for example, some onTaps not working.
> 
> Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)

hi, can you provide more info?
