### ISSUE TITLE
[web] Broken gradient only when using  '--web-renderer html' only the master channel 

### ISSUE THREAD

**Issue by devanflores** [flutter/flutter#74137]
## Steps to Reproduce

1. Use a linear gradient in flutter web with web-rendering:html with the repeated tiling
2.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Container(
            height: 10,
            width: 10,
            decoration: BoxDecoration(
                gradient: LinearGradient(
              begin: Alignment.centerLeft,
              end: Alignment
                  .centerRight, // 10% of the width, so there are ten blinds.
              colors: [
                Colors.pink[300],
                Colors.deepOrange[400],
              ], // red to yellow
              tileMode:
                  TileMode.repeated, // repeats the gradient over the canvas
            ))),
      ),
    );
  }
}
```
</details>

**Expected results:** 
A gradient

**Actual results:** 
A broken  rendering of a gradient

<details>
  <summary>Logs</summary>

```console
[√] Flutter (Channel master, 1.26.0-2.0.pre.400, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-2.0.pre.400 at C:\Users\Devan\Downloads\flutter_windows_1.17.5-stable\flutter   
    • Framework revision be82bb8fdf (67 minutes ago), 2021-01-16 18:27:09 -0800
    • Engine revision 0716ca8943
    • Dart version 2.12.0 (build 2.12.0-234.0.dev) 

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Devan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 2 categories.

```

</details>

**Comment by iapicca** [comment]
testing with the code below


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.centerLeft,
                  end: Alignment
                      .centerRight, // 10% of the width, so there are ten blinds.
                  colors: [
                    Colors.pink[300],
                    Colors.deepOrange[400],
                  ], // red to yellow
                  tileMode:
                      TileMode.repeated, // repeats the gradient over the canvas
                ),
              ),
            ),
          ),
        ),
      ),
    );

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.401, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.401 at /home/francesco/snap/flutter/common/flutter
    • Framework revision da5a454d5c (2 hours ago), 2021-01-17 01:24:03 -0500
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 87.0.4280.141 snap

! Doctor found issues in 1 category.

```

</details>


<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/104835087-cd7be480-58ac-11eb-8bc7-b1aae204ecdd.png)


</details>

it seems to work just fine

**Comment by devanflores** [comment]
I think this issue might only show up when using web-renderer html

**Comment by TahaTesser** [comment]
Hi @devanflores 
Thanks for filing the issue, good catch. I can reproduce when executing `flutter run -d chrome --web-renderer html` but no issues with following commands
`flutter run -d chrome`
`flutter run -d chrome --web-renderer canvaskit`
`flutterm run --dart-define=FLUTTER_WEB_USE_SKIA=false -d chrome -v`
`flutterm run --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome -v`

and it only reproduces on `master`, no issues on `beta` or `dev`

| flutter run -d chrome | flutter run -d chrome --web-renderer html |
| --------------- | --------------- |
<img width="502" alt="Screenshot 2021-01-18 at 3 48 12 PM" src="https://user-images.githubusercontent.com/48603081/104902695-0c8d6100-59a5-11eb-874f-a2ec4677da8d.png">	| <img width="502" alt="Screenshot 2021-01-18 at 3 47 21 PM" src="https://user-images.githubusercontent.com/48603081/104902723-157e3280-59a5-11eb-8fc9-8e131e06ea56.png">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
              height: 100,
              width: 100,
              decoration: BoxDecoration(
                  gradient: LinearGradient(
                begin: Alignment.centerLeft,
                end: Alignment
                    .centerRight, // 10% of the width, so there are ten blinds.
                colors: [
                  Colors.pink[300],
                  Colors.deepOrange[400],
                ], // red to yellow
                tileMode:
                    TileMode.repeated, // repeats the gradient over the canvas
              ))),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.402 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2a188eeca3 (3 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

Thank you

**Comment by ferhatb** [comment]
@TahaTesser , can you please retry on master, i'm getting correct rendering. Likely fixed by https://github.com/flutter/engine/pull/23691 rolling into flutter.

**Comment by TahaTesser** [comment]
@ferhatb 


I can still reproduce it using ` flutter run -d chrome --web-renderer html` on 
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.179, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.26.0-13.0.pre.179 at /Users/tahatesser/Code/flutter_master
    • Framework revision fc9addb88b (4 hours ago), 2021-01-26 03:24:03 -0500
    • Engine revision f47ab4434d
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)
```

<img width="124" alt="Screenshot 2021-01-26 at 6 24 36 PM" src="https://user-images.githubusercontent.com/48603081/105847565-c323be00-6003-11eb-97b5-397386a3e037.png">


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.179, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.179 at /Users/tahatesser/Code/flutter_master
    • Framework revision fc9addb88b (5 hours ago), 2021-01-26 03:24:03 -0500
    • Engine revision f47ab4434d
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • DC25925E-876C-4CFE-A2F7-0640782D22A5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>
