### ISSUE TITLE
[web]: width not working on flutter web widgets (Container, SizeBox)

### ISSUE THREAD

**Issue by djaBalasbas** [flutter/flutter#74641]
## Steps to Reproduce

1. Flutter beta version updated(To be used for Flutter web), create flutter then run on flutter run -d chrome
2. Use either Container or SizedBox to change the width of a Card widget
3. Use Container or SizedBox width property, on my end its not working(Im using Google Chrome Browser)

**Expected results:** 
Width should work when using Container or SizeBox widgets
**Actual results:** 
No changes even after defining the width for Container and SizeBox

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19041.746], locale en-PH)
    • Flutter version 1.25.0-8.3.pre at C:\sdks\flutter
    • Framework revision 5d36f2e7f5 (11 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.1
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!

```
```

</details>

**Comment by iapicca** [comment]
@djaBalasbas 

running the code below everything seems to work as expected

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: Container(width: 200, color: Colors.blue),
          ),
        ),
      ),
    );

```

[screenshot](https://user-images.githubusercontent.com/45637986/105737325-7c1fc500-5f3e-11eb-9b58-e3a48327ce1e.png)

```console
[✓] Flutter (Channel master, 1.26.0-13.0.pre.144, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-13.0.pre.144 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 2007186d2e (20 hours ago), 2021-01-24 12:54:00 -0800
    • Engine revision fdddf87080
    • Dart version 2.12.0 (build 2.12.0-253.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.96 snap

! Doctor found issues in 1 category.

```

if the code sample does not represent the issue please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by djaBalasbas** [comment]
> @djaBalasbas
> 
> running the code below everything seems to work as expected
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(
>       MaterialApp(
>         home: Material(
>           child: Center(
>             child: Container(width: 200, color: Colors.blue),
>           ),
>         ),
>       ),
>     );
> ```
> 
> [screenshot](https://user-images.githubusercontent.com/45637986/105737325-7c1fc500-5f3e-11eb-9b58-e3a48327ce1e.png)
> 
> ```
> [✓] Flutter (Channel master, 1.26.0-13.0.pre.144, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.26.0-13.0.pre.144 at /home/francesco/snap/flutter/common/flutter
>     • Framework revision 2007186d2e (20 hours ago), 2021-01-24 12:54:00 -0800
>     • Engine revision fdddf87080
>     • Dart version 2.12.0 (build 2.12.0-253.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /home/francesco/Android/Sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
>     • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • CHROME_EXECUTABLE = /snap/bin/chromium
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
>     • cmake version 3.10.2
>     • ninja version 1.8.2
>     • pkg-config version 0.29.1
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
> 
> [✓] Connected device (3 available)
>     • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
>     • Linux (desktop)   • linux      • linux-x64      • Linux
>     • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.96 snap
> 
> ! Doctor found issues in 1 category.
> ```
> 
> if the code sample does not represent the issue please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thanks now I actually know what to do, Just wrapped them inside a center widget. I might be wrong but I think this is not expected behavior and it should still work without Center Widget. Nevertheless I now know that I just need to add center widget. Thanks.

Here is also a code comparing with and without Center Widget

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Scaffold(
            body: ListView(
              children: [
                Center(child: Container(width: 200, color: Colors.blue,child: Text('With Center Widget'),)),
                Container(width: 200,  color: Colors.green,child: Text('Without Center widget'),)
              ],
            ),
          ),
        ),
      ),
    );

![Screenshot (100)](https://user-images.githubusercontent.com/71002938/105740820-878de300-5f74-11eb-97c6-6507ce1e6e04.png)

**Comment by darshankawar** [comment]
@djaBalasbas 
Considering your above comment, it seems your issue is resolved (add center widget).
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by djaBalasbas** [comment]
> @djaBalasbas 
> Considering your above comment, it seems your issue is resolved (add center widget).
> Closing from here. If you disagree, write in comments and I'll reopen it.
> 

I think using Center Widget is just a work around and Container width is still not working as expected without center widget.

**Comment by darshankawar** [comment]
@djaBalasbas 
This isn't specific to web. Even on mobile (Android), you'll see the same behavior.

<img width="542" alt="Screenshot 2021-01-26 at 3 50 46 PM" src="https://user-images.githubusercontent.com/67046386/105832713-49350a00-5fee-11eb-8ba1-f741fa0ab027.png">

**Comment by djaBalasbas** [comment]
Yes it does show on Android also, well to be honest its a little inconvenient to wrap the container to center widget just to make its width property to work correctly when its height property works just fine. But more Importantly I've learned something to make it work. Thank you for the help

**Comment by djaBalasbas** [comment]
> @djaBalasbas
> This isn't specific to web. Even on mobile (Android), you'll see the same behavior.
> 
> <img alt="Screenshot 2021-01-26 at 3 50 46 PM" width="542" src="https://user-images.githubusercontent.com/67046386/105832713-49350a00-5fee-11eb-8ba1-f741fa0ab027.png">

Yes it does show on Android also, well to be honest its a little inconvenient to wrap the container to center widget just to make its width property to work correctly when its height property works just fine. But more Importantly I've learned something to make it work. Thank you for the help
