### ISSUE TITLE
Mouse button release isn't detected in engines fl_view gtk widget after calling gtk_window_begin_move_drag

### ISSUE THREAD

**Issue by cenomla** [flutter/flutter#74939]
After calling gtk_window_begin_move_drag from a native plugin the view doesn't respond to the next mouse click, the function call is triggered from a gesture detector widget. It seems like the fl_view widget isn't responding to the mouse button release and so it still thinks the mouse button is down when the next mouse button press happens. I might also be doing something wrong on my end as I'm not too experienced with gtk. 

## Steps to Reproduce
 - Call `gtk_window_begin_move_drag` from the Linux runner, native plugin or ffi interface
 - Click in the app window, the click doesn't register

Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions.
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @cenomla 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample in a repository
Thank you

**Comment by cenomla** [comment]
Here is the minimal repro project 
[fl_view_bug_repro.tar.gz](https://github.com/flutter/flutter/files/5896908/fl_view_bug_repro.tar.gz)

Log from `flutter run -d linux --verbose`
```
[  +59 ms] executing: [/home/cenomla/data/repo/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] executing: [/home/cenomla/data/repo/flutter/] git tag --points-at a706cd211240f27be3b61f06d70f958c7a4156fe
[  +11 ms] Exit code 0 from: git tag --points-at a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] 1.26.0-12.0.pre
[  +33 ms] executing: [/home/cenomla/data/repo/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/cenomla/data/repo/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter
[  +32 ms] executing: [/home/cenomla/data/repo/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[   +9 ms] Skipping pub get: version match.
[  +74 ms] Found plugin integration_test at /home/cenomla/data/repo/flutter/packages/integration_test/
[ +473 ms] Found plugin integration_test at /home/cenomla/data/repo/flutter/packages/integration_test/
[  +74 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +4 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/cenomla/data/repo/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/cenomla/data/repo/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/cenomla/data/repo/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill /tmp/flutter_tools.UACSWO/flutter_tool.YTONFP/app.dill --packages /home/cenomla/data/workspace/dart/fl_view_bug_repro/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +19 ms] Building Linux application...
[  +27 ms] <- compile package:fl_view_bug_repro/main.dart
[   +2 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/cenomla/data/workspace/dart/fl_view_bug_repro/linux
[  +10 ms] List of devices attached
[   +2 ms] List of devices attached
[  +31 ms] -- Configuring done
[   +3 ms] -- Generating done
[   +6 ms] -- Build files have been written to: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug
[   +3 ms] executing: ninja -C build/linux/debug install
[   +8 ms] ninja: Entering directory `build/linux/debug'
[+3367 ms] [1/5] Generating /home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/cenomla/data/workspace/dart/fl_view_bug_repro/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +4 ms] [  +70 ms] executing: [/home/cenomla/data/repo/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] [        ] executing: [/home/cenomla/data/repo/flutter/] git tag --points-at a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] [  +12 ms] Exit code 0 from: git tag --points-at a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] [        ] 1.26.0-12.0.pre
[        ] [  +41 ms] executing: [/home/cenomla/data/repo/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [/home/cenomla/data/repo/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] git@github.com:flutter/flutter
[        ] [  +35 ms] executing: [/home/cenomla/data/repo/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +40 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +82 ms] Initializing file store
[        ] [   +5 ms] Done initializing file store
[        ] [  +32 ms] Skipping target: gen_localizations
[        ] [+1629 ms] Skipping target: unpack_linux
[        ] [ +334 ms] Skipping target: kernel_snapshot
[        ] [ +239 ms] Skipping target: debug_bundle_linux_assets
[        ] [        ] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 2,403ms.
[        ] [ +202 ms] ensureAnalyticsSent: 199ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +534 ms] [2/5] Building CXX object CMakeFiles/fl_view_bug_repro.dir/flutter/generated_plugin_registrant.cc.o
[  +27 ms] [3/5] Building CXX object CMakeFiles/fl_view_bug_repro.dir/my_application.cc.o
[ +134 ms] [4/5] Linking CXX executable intermediates_do_not_run/fl_view_bug_repro
[        ] [4/5] Install the project...
[   +6 ms] -- Install configuration: "Debug"
[  +19 ms] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/fl_view_bug_repro
[        ] -- Set runtime path of "/home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/fl_view_bug_repro" to "$ORIGIN/lib"
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[  +87 ms] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +24 ms] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /home/cenomla/data/workspace/dart/fl_view_bug_repro/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[   +9 ms] Building Linux application... (completed in 4.3s)
[ +471 ms] Observatory URL on device: http://127.0.0.1:33145/R9uUks39tTA=/
[   +3 ms] Caching compiled dill
[  +37 ms] Connecting to service protocol: http://127.0.0.1:33145/R9uUks39tTA=/
[   +1 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:33145/R9uUks39tTA=/.
[ +150 ms] DDS is listening at http://127.0.0.1:39341/LdUTwAQHbAw=/.
[  +60 ms] Successfully connected to service protocol: http://127.0.0.1:33145/R9uUks39tTA=/
[ +550 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device (file:///tmp/fl_view_bug_reproPCVCQU/fl_view_bug_repro/)
[   +1 ms] Updating assets
[  +80 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:fl_view_bug_repro/main.dart 5a4a8be7-f089-42ec-bd91-079415fda9b0
[        ] <- 5a4a8be7-f089-42ec-bd91-079415fda9b0
[  +68 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 72ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +4 ms] Connected to _flutterView/0x55f16b1c5fa0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:39341/LdUTwAQHbAw=/
[        ]
           Flutter DevTools, a Flutter debugger and profiler, on Linux is available at: http://127.0.0.1:9106?uri=http%3A%2F%2F127.0.0.1%3A39341%2FLdUTwAQHbAw%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+13993 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///tmp/fl_view_bug_reproPCVCQU/fl_view_bug_repro/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +1 ms] "flutter run" took 20,839ms.
[ +173 ms] ensureAnalyticsSent: 170ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[        ] exiting with code 0
```

**Comment by TahaTesser** [comment]
Hi @cenomla 
Thanks for the project and the logs, I can reproduce it on PopOS 20.10


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.1.pre at /home/taha/Code/flutter_dev
    • Framework revision c40e5294dd (3 days ago), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```


```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.90, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.90 at /home/taha/Code/flutter_master
    • Framework revision 25134a16d1 (2 days ago), 2021-01-29 23:52:30 -0800
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by chinmaygarde** [comment]
cc @cbracken

**Comment by robert-ancell** [comment]
I've tried this with a locally built engine and can confirm that we're not receiving a GTK button release event when doing the window dragging. Will investigate why that is.

**Comment by robert-ancell** [comment]
Confirmed with the following GTK program that you do not get a button release event when you do a window drag (assuming the drag causes a grab that consumes the event). This suggests the bug is in the mouse processing code in Flutter - it's probably expecting that it should get a release event before the next press event.

```c
#include <gtk/gtk.h>

static GtkWidget *window = NULL;

static void
button_press_event_cb (GtkWidget *widget, GdkEventButton *event)
{
   g_printerr ("button_press %d\n", event->button);

   if (event->button == 1) {
      gint x, y;
      gdk_device_get_position (event->device, NULL, &x, &y);
      gtk_window_begin_move_drag(GTK_WINDOW (window), event->button, x, y, GDK_CURRENT_TIME);
   }
}

static void
button_release_event_cb (GtkWidget *widget, GdkEventButton *event)
{
   g_printerr ("button_release %d\n", event->button);
}

int main (int argc, char **argv)
{
   gtk_init (&argc, &argv);

   window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
   gtk_widget_show (window);

   GtkWidget *event_box = gtk_event_box_new ();
   g_signal_connect (event_box, "button-press-event", G_CALLBACK (button_press_event_cb), NULL);
   g_signal_connect (event_box, "button-release-event", G_CALLBACK (button_release_event_cb), NULL);
   gtk_widget_show (event_box);
   gtk_container_add (GTK_CONTAINER (window), event_box);

   gtk_main();
}
```

**Comment by robert-ancell** [comment]
The event is being dropped in `fl_view.cc`, because Flutter hits an assertion if we send two button press events:
```c
  if (event->type == GDK_BUTTON_PRESS) {
    // Drop the event if Flutter already thinks the button is down.
    if ((self->button_state & button) != 0) {
      return FALSE;
    }
```

If you remove the above check:
```
[ +118 ms] [FATAL:flutter/lib/ui/window/pointer_data_packet_converter.cc(129)] Check failed: !state.is_down. 
```

So we either need to simulate a button release event or make the Flutter event processor handle multiple button press events.

**Comment by chunhtai** [comment]
If we do handle it on the flutter side, we may run into a conflict if different platforms want different outcomes when they both send two down events. I think it will be the embeddings responsibility to provide reasonable events, i.e. issues a synthetic release.

**Comment by bitsdojo** [comment]
> I think it will be the embeddings responsibility to provide reasonable events, i.e. issues a synthetic release.

Totally agree with this.

I fixed this in my package by simulating a button release event:

https://github.com/bitsdojo/bitsdojo_window/blob/e79b2c7d82b95ffc05bd50d19a8f8d322675ad87/bitsdojo_window_linux/linux/window_impl.cpp#L256

**Comment by huycozy** [comment]
The issue persists on the latest Flutter stable and master channels.

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.6, on Ubuntu 22.04.3 LTS 6.5.0-26-generic, locale en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (2 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /snap/android-studio/current/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[!] Android Studio (version unknown)
    • Android Studio at /snap/android-studio/current
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir = /snap/android-studio/current
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.86.0

[✓] VS Code (version 1.88.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.86.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-26-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.22.0-14.0.pre.35, on Ubuntu 22.04.3 LTS 6.5.0-26-generic, locale en_US.UTF-8)
    • Flutter version 3.22.0-14.0.pre.35 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9feccd5f3b (2 hours ago), 2024-04-19 05:08:40 -0400
    • Engine revision 4ed7a2d6ae
    • Dart version 3.5.0 (build 3.5.0-77.0.dev)
    • DevTools version 2.35.0-dev.8
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /snap/android-studio/current/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[!] Android Studio (version unknown)
    • Android Studio at /snap/android-studio/current
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir = /snap/android-studio/current
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.86.0

[✓] VS Code (version 1.88.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.86.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-26-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>
