### ISSUE TITLE
[Samsung device][Android 6]: CameraController.stopVideoRecording() cause CameraException(videoRecordingFailed, Operation timed out in camera service)

### ISSUE THREAD

**Issue by JmyW** [flutter/flutter#75506]
I'm using the Camera **0.7.0+2** example code on my **Samsung Galaxy J7** phone. It can successfully take pictures, but failed on video record. Please refer details below: 
I did refer the closed issue [https://github.com/flutter/flutter/issues/63928] but seems different issue. The solution is not helping in my case. 
In this case, the Samsumg Galaxy J7 is Android 6.0.1. I also take another device HTC Desire 816 which is Android 6.0. The HTC one is workable but Samesung failed.
Could anyone help?

**[Reproduced Steps]**
Execute the example code
Tap video record icon
Tap "stop" icon
Program hang for 5 sec then logged message "Unhandled Exception: CameraException(videoRecordingFailed, Operation timed out in camera service)"
[Source Code] Just use the example code in GitHub
https://github.com/flutter/plugins/tree/master/packages/camera/camera/example

**[Device]** Samsung Galaxy J7 Prime
**[Error Code]**
```bash
E/CameraCaptureSession( 5434): Session 2: Failed to create capture session; configuration failed
E/flutter ( 5434): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: CameraException(videoRecordingFailed, Operation timed out in camera service)
E/flutter ( 5434): #0 CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:479:7)
E/flutter ( 5434):
E/flutter ( 5434): #1 _CameraExampleHomeState.onStopButtonPressed. (package:camera_example/main.dart)
E/flutter ( 5434):
```
**[Flutter doctor -v]**

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel dev, 1.26.0-17.2.pre, on Microsoft Windows [Version 10.0.18363.1316], locale zh-TW)
• Flutter version 1.26.0-17.2.pre at C:\flutter
• Framework revision 79b49b9 (2 days ago), 2021-02-03 15:33:39 -0800
• Engine revision 2c527d6c7e
• Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\Jemmy_Wu\AppData\Local\Android\sdk
• Platform android-30, build-tools 29.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
X Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
• SM G610Y (mobile) • 5210ff844cbc83f1 • android-arm • Android 6.0.1 (API 23)
• Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.146
• Edge (web) • edge • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
I tried the official camera [example](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) using latest plugin version on stable. Although I don't have Samsung Android 6.0 device, I used emulator 6.0 on which I was able to replicate the exception. Although, the exception isn't exactly the same, it still points to `Unhandled Exception: CameraException(videoRecordingFailed, The camera device has encountered a serious error)`.

I also tried the same on Android 8.1.0 device and S10 device on which I didn't get the exception, which may indicate that it could be OS + device specific issue.

<details>
<summary>emulator 6.0 log</summary>

```
E/BufferQueueProducer( 4195): [SurfaceTexture-1-4195-4] queueBuffer: BufferQueue has been abandoned
E/flutter ( 4195): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: CameraException(videoRecordingFailed, The camera device has encountered a serious error)
E/flutter ( 4195): #0      CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:479:7)
E/flutter ( 4195): <asynchronous suspension>
E/flutter ( 4195): #1      _CameraExampleHomeState.stopVideoRecording (package:camera_example/main.dart:616:25)
E/flutter ( 4195): #2      _CameraExampleHomeState.onStopButtonPressed (package:camera_example/main.dart:567:5)
E/flutter ( 4195): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 4195): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 4195): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 4195): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 4195): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 4195): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 4195): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 4195): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 4195): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 4195): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 4195): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 4195): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 4195): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 4195): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 4195): #17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 4195): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 4195): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 4195): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 4195): #21     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 4195): #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4195): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 4195): #24     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 4195): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 4195): 


```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM A260G (mobile)                  • 5200763ebcfa861f • android-arm •
      Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86 •
      Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
May be similar to https://github.com/flutter/flutter/issues/62564

**Comment by JmyW** [comment]
Thank for helping this issue analysis. Hopefully get solution asap. 
BTW, you're referring two issues : #62564 and #57196 , but the exception log seems different, just all happened on Samsung devices.

**Comment by acoutts** [comment]
This is potentially fixed by my PR here where I've reworked how capturing is started, fixing timeouts on some other devices. https://github.com/flutter/plugins/pull/3651

**Comment by JmyW** [comment]
Hi @darshankawar 
I use latest example which was updated 3 days ago in GitHub, guessingly it's 0.9.2+1. It's still the same issue on Samsung J7. 
Furthermore, I tried the following two builds also. They are same issue too. But this time I test more and found the failure is only happened on back camera, it works well on front camera. Any clue? 

camera:
    git:
      url: https://github.com/bottlepay/plugins.git
      path: packages/camera/camera
      ref: android-rework
      
camera:
    git:
      url: https://github.com/bottlepay/plugins.git
      ref: android-rework
      path: packages/camera/camera

**Comment by JmyW** [comment]
Here is the log
  :
  :
D/libEGL  ( 6902): eglInitialize EGLDisplay = 0xdc819f4c
D/libEGL  ( 6902): eglInitialize EGLDisplay = 0xdc819f4c
D/ViewRootImpl( 6902): ViewPostImeInputStage processPointer 0
D/ViewRootImpl( 6902): ViewPostImeInputStage processPointer 1
I/Camera  ( 6902): startPreview
I/Camera  ( 6902): closeCaptureSession
E/CameraCaptureSession( 6902): Session 2: Failed to create capture session; configuration failed
I/Choreographer( 6902): Skipped 446 frames!  The application may be doing too much work on its main thread.
I/Camera  ( 6902): open | onError
I/Camera  ( 6902): close
E/flutter ( 6902): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(videoRecordingFailed, Operation timed out in camera service)
E/flutter ( 6902): #0      CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:531:7)
E/flutter ( 6902): <asynchronous suspension>
E/flutter ( 6902):

**Comment by darshankawar** [comment]
@JmyW 
Revisiting the issue, although I don't have the exact device running on 6.0, but I tried on Samsung S10 running on 12.0 with camera example using latest plugin version and stable version with which I was able to record and stop the video properly without throwing any exception. 

Is there a way for you to verify this issue at your end on same device but with latest plugin and framework version (stable 3.19) to confirm if the exception still persists or not ?
