### ISSUE TITLE
[macOS] Bogus keys reported in RawKeyboard.instance.keysPressed

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#75627]
## Steps to Reproduce

1. Run `flutter create editable_text_keys`.
2. Update main.dart as follows:
```
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EditableText keys test',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _textController;
  FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _textController = TextEditingController(text: 'some\nmulti\nline\ntext\n\njust\na few\nlines\nmore\n...\n...\n');
    _focusNode = FocusNode(
      onKey: (_, RawKeyEvent keyEvent) {
        if (keyEvent is! RawKeyDownEvent) return false;
        final Set<LogicalKeyboardKey> keysPressed = LogicalKeyboardKey.collapseSynonyms(RawKeyboard.instance.keysPressed);
        print('FocusNode onKey RawKeyEvent: $keyEvent | keysPressed: $keysPressed');
        return false;
      }
    );
  }

  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('EditableText keys test')),
      body: Container(
        margin: EdgeInsets.all(10.0),
        child: EditableText(
          controller: _textController,
          focusNode: _focusNode,
          maxLines: null,
          autofocus: true,
          style: TextStyle(fontSize: 24.0, color: Colors.black),
          cursorColor: Colors.amber,
          backgroundCursorColor: Colors.grey,
        ),
      ),
    );
  }
}
```
3. Run the application on macOS. Press different keys, including arrow keys and observe in the printed logs if the RawKeyEvent and keysPressed match what's being pressed.
4. Switch to other applications. Then switch to a Chrome browser window. Navigate to a page with text input, enter some text, select all using Command+A, cut text using Command+X.
5. Switch back to the Flutter app window and repeat step 3.

**Expected results:** Only the actual keys being pressed are reported in the RawKeyboard.instance.keysPressed set.
```
[+3072 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#a196a(logicalKey: LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow
Left"), physicalKey: PhysicalKeyboardKey#70050(usbHidUsage: "0x00070050", debugName: "Arrow Left")) | keysPressed: {LogicalKeyboardKey#70050(keyId: "0x100070050",
keyLabel: "", debugName: "Arrow Left")}
```

**Actual results:** Sometimes, after a while, a bogus key 'A' is constantly reported in RawKeyboard.instance.keysPressed alongside the arrow keys pressed:
```
[+4243 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#54d29(logicalKey: LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow
Left"), physicalKey: PhysicalKeyboardKey#70050(usbHidUsage: "0x00070050", debugName: "Arrow Left")) | keysPressed: {LogicalKeyboardKey#70004(keyId: "0x100070004",
keyLabel: "Key A", debugName: "Key A"), LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left")}
```

<details>
  <summary>Logs</summary>

```
"flutter -run verbose" output too long - will attach as render_editable_keys_run_verbose_output.txt.
```

```
% flutter analyze      
Analyzing editable_text_keys...                                         
No issues found! (ran in 3.7s)
```

```
% flutter doctor -v    
[✓] Flutter (Channel master, 1.26.0-18.0.pre.212, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.212 at /Library/Frameworks/flutter
    • Framework revision 02d441ea55 (3 days ago), 2021-02-05 17:17:12 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.146

• No issues found!
```

</details>

**Comment by tgucio** [comment]
[render_editable_keys_run_verbose_output.txt](https://github.com/flutter/flutter/files/5943811/render_editable_keys_run_verbose_output.txt)

**Comment by tgucio** [comment]
When this issue is hit, arrow key navigation and other shortcuts stop working in text input. This is due to the following check in _handleKeyEvent():
```
    if (!_nonModifierKeys.contains(key) ||
        keysPressed.difference(isMacOS ? _macOsModifierKeys : _modifierKeys).length > 1 ||
        keysPressed.difference(_interestingKeys).isNotEmpty) {
      // If the most recently pressed key isn't a non-modifier key, or more than
      // one non-modifier key is down, or keys other than the ones we're interested in
      // are pressed, just ignore the keypress.
      return;
    }
```
The method returns here because the keysPressed.difference(_interestingKeys).isNotEmpty condition is always met.

Once in this state, with the 'A' key being reported as pressed constantly, pressing it appears to recover and the next time RawKeyboard.instance.keysPressed is read the key isn't included. This also unblocks key navigation in text input (there is another error issue described in https://github.com/flutter/flutter/issues/75562 with a proposed fix in https://github.com/flutter/flutter/pull/75614).

**Comment by TahaTesser** [comment]
Hi @tgucio 
Thanks for filing the issue and the details  I am not able to replicate the issue on the `master` change after typing in chrome 


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EditableText keys test',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _textController;
  FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _textController = TextEditingController(
        text:
            'some\nmulti\nline\ntext\n\njust\na few\nlines\nmore\n...\n...\n');
    _focusNode = FocusNode(onKey: (_, RawKeyEvent keyEvent) {
      if (keyEvent is! RawKeyDownEvent) return false;
      final Set<LogicalKeyboardKey> keysPressed =
          LogicalKeyboardKey.collapseSynonyms(RawKeyboard.instance.keysPressed);
      print(
          'FocusNode onKey RawKeyEvent: $keyEvent | keysPressed: $keysPressed');
      return false;
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('EditableText keys test')),
      body: Container(
        margin: EdgeInsets.all(10.0),
        child: EditableText(
          controller: _textController,
          focusNode: _focusNode,
          maxLines: null,
          autofocus: true,
          style: TextStyle(fontSize: 24.0, color: Colors.black),
          cursorColor: Colors.amber,
          backgroundCursorColor: Colors.grey,
        ),
      ),
    );
  }
}

```

</details>


<details>
<summary>logs</summary>

```bash
[+6520 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#156f5(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052",
keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70052(usbHidUsage: "0x00070052", debugName: "Arrow Up")) |
keysPressed: {LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
[ +365 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#b06c1(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051",
keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#70051(usbHidUsage: "0x00070051", debugName: "Arrow Down"))
| keysPressed: {LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
[ +297 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#ba87c(logicalKey: LogicalKeyboardKey#7004f(keyId: "0x10007004f",
keyLabel: "", debugName: "Arrow Right"), physicalKey: PhysicalKeyboardKey#7004f(usbHidUsage: "0x0007004f", debugName: "Arrow
Right")) | keysPressed: {LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right")}
[ +303 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#88fa1(logicalKey: LogicalKeyboardKey#70050(keyId: "0x100070050",
keyLabel: "", debugName: "Arrow Left"), physicalKey: PhysicalKeyboardKey#70050(usbHidUsage: "0x00070050", debugName: "Arrow Left"))
| keysPressed: {LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left")}
[+13393 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#0ee38(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052",
keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70052(usbHidUsage: "0x00070052", debugName: "Arrow Up")) |
keysPressed: {LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
[ +267 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#da597(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051",
keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#70051(usbHidUsage: "0x00070051", debugName: "Arrow Down"))
| keysPressed: {LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
[ +228 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#5621a(logicalKey: LogicalKeyboardKey#7004f(keyId: "0x10007004f",
keyLabel: "", debugName: "Arrow Right"), physicalKey: PhysicalKeyboardKey#7004f(usbHidUsage: "0x0007004f", debugName: "Arrow
Right")) | keysPressed: {LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right")}
[ +255 ms] flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#27ef7(logicalKey: LogicalKeyboardKey#70050(keyId: "0x100070050",
keyLabel: "", debugName: "Arrow Left"), physicalKey: PhysicalKeyboardKey#70050(usbHidUsage: "0x00070050", debugName: "Arrow Left"))
| keysPressed: {LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left")}





```

</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.212, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.212 at /Users/tahatesser/Code/flutter_master
    • Framework revision 02d441ea55 (3 days ago), 2021-02-05 17:17:12 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.146
! Doctor found issues in 2 categories.
```

</details>




Thank you

**Comment by tgucio** [comment]
Hi @TahaTesser,
In most cases the problem doesn't show immediately so it might need some switching back and forth between the Flutter desktop test app and other windows (including Chrome) as well as spending some time with the app in the background.

In case this also depends on macOS version: mine is 10.15.7 runing on a 2015 Macbook Pro.

**Comment by TahaTesser** [comment]
Hi @tgucio 
Thanks for the details, I tried to keep the app in the background for a couple of hours, tried multiple times, and use other apps including chrome while at it, wasn't able to replicate this

**Comment by tgucio** [comment]
No my Mac running 10.15.7 there are times where I can't reproduce for a (longish) while but typically when I restart the test app and start switching between its window and Chrome and Visual Studio Code I hit the problem.

I've added a few debug prints in raw_keyboard.dart and I can see something interesting:

1. Whenever the issue happens, it starts with a message handled in RawKeyboard  _handleKeyEvent() with keyCode=0 but with no explicit character data in the Map. It's decoded as RawKeyDownEvent and there's never a corresponding RawKeyUpEvent - hence keysPressed() will be reporting the 'A' key pressed forever and text input shortcuts won't work:

```
flutter: RawKeyboard _handleKeyEvent msg: {keymap: macos, modifiers: 256, type: keydown, keyCode: 0}
flutter: RawKeyboard _handleKeyEvent ev: RawKeyDownEvent#5496e(logicalKey: LogicalKeyboardKey#70004(keyId: "0x100070004", keyLabel: "Key A", debugName: "Key A"), physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: "0x00070004", debugName: "Key A"))
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#5496e(logicalKey: LogicalKeyboardKey#70004(keyId: "0x100070004", keyLabel: "Key A", debugName: "Key A"), physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: "0x00070004", debugName: "Key A")) | keysPressed: {LogicalKeyboardKey#70004(keyId: "0x100070004", keyLabel: "Key A", debugName: "Key A")}
flutter: RawKeyboard _handleKeyEvent msg: {keymap: macos, modifiers: 1048840, type: keydown, keyCode: 55}
flutter: RawKeyboard _handleKeyEvent ev: RawKeyDownEvent#030e4(logicalKey: LogicalKeyboardKey#700e3(keyId: "0x1000700e3", keyLabel: "", debugName: "Meta Left"), physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage: "0x000700e3", debugName: "Meta Left"))
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#030e4(logicalKey: LogicalKeyboardKey#700e3(keyId: "0x1000700e3", keyLabel: "", debugName: "Meta Left"), physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage: "0x000700e3", debugName: "Meta Left")) | keysPressed: {LogicalKeyboardKey#70004(keyId: "0x100070004", keyLabel: "Key A", debugName: "Key A"), LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta")}
[...from here on, keysPressed includes "Key A" forever and ever.
```

Now when I really press the "A" key, the event in RawKeyboard _handleKeyEvent() is different, the Map has charactersIgnoringModifiers/characters with the right data (I'd guess it comes from NSEvent): 

```
flutter: RawKeyboard _handleKeyEvent msg: {charactersIgnoringModifiers: a, keymap: macos, modifiers: 256, type: keydown, keyCode: 0, characters: a}
flutter: RawKeyboard _handleKeyEvent ev: RawKeyDownEvent#5d991(logicalKey: LogicalKeyboardKey#00061(keyId: "0x00000061", keyLabel: "a", debugName: "Key A"), physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: "0x00070004", debugName: "Key A"))
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#5d991(logicalKey: LogicalKeyboardKey#00061(keyId: "0x00000061", keyLabel: "a", debugName: "Key A"), physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: "0x00070004", debugName: "Key A")) | keysPressed: {LogicalKeyboardKey#00061(keyId: "0x00000061", keyLabel: "a", debugName: "Key A")}
flutter: RawKeyboard _handleKeyEvent msg: {charactersIgnoringModifiers: a, keymap: macos, modifiers: 256, type: keyup, keyCode: 0, characters: a}
flutter: RawKeyboard _handleKeyEvent ev: RawKeyUpEvent#7d363(logicalKey: LogicalKeyboardKey#00061(keyId: "0x00000061", keyLabel: "a", debugName: "Key A"), physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: "0x00070004", debugName: "Key A"))
```

For clarity - these are the two messages:
```
spurious "key A" causing the issue: {keymap: macos, modifiers: 256, type: keydown, keyCode: 0}
regular "key A" press: {charactersIgnoringModifiers: a, keymap: macos, modifiers: 256, type: keydown, keyCode: 0, characters: a}
```

**Comment by dkwingsmt** [comment]
This will probably be fixed by https://github.com/flutter/flutter/issues/44918

**Comment by tgucio** [comment]
This is still happening on master:

% flutter --version
Flutter 2.1.0-13.0.pre.207 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5d37734ea1 (8 hours ago) • 2021-03-22 23:30:00 -0700
Engine • revision d59a01d2d3
Tools • Dart 2.13.0 (build 2.13.0-150.0.dev)

Since the Shortcuts class EditableText migrated to also uses RawKeyboard.instance.keysPressed to match shortcuts, all text shortcuts also stop working.

**Comment by kenwei** [comment]
I've encountered the same issue too, still on 2.2.0-10.2.pre, revision b5017bf8de (8 days ago) • 2021-04-28 17:09:53

**Comment by venkatd** [comment]
@tgucio we are experiencing these issues on web. Have you found any workarounds for it?

**Comment by tgucio** [comment]
@venkatd I went for a not-so-pretty workaround with a change in RenderEditable - in editable.dart, _handleKeyEvent():
`
     Set<LogicalKeyboardKey> keysPressed = LogicalKeyboardKey.collapseSynonyms(RawKeyboard.instance.keysPressed);
     LogicalKeyboardKey key = keyEvent.logicalKey;
     (...)
+    if (keyEvent.data is RawKeyEventDataMacOs) {
+      keysPressed.removeWhere((key) => key.keyId == 0x100070004);
+    }
`

I also have a similar WAR in place for similar issues on Windows (#76857)

**Comment by dkwingsmt** [comment]
I'm not able to reproduce occasions with extra keys. However, with https://github.com/flutter/flutter/pull/80756 (merged Apr 26, 2021), extra keys shouldn't affect shortcuts any more. In fact, you can physically hold `Cmd+ArrowLeft` and press `ArrowRight` and the `Cmd+ArrowRight` shortcut will still be triggered.

Notice that the custom shortcuts in your apps must replace `LogicalKeySet` with `SingleActivator` whenever possible. `SingleActivator` applies to shortcuts that consists of a few (or no) modifier keys as well as a "trigger" key, such as `Ctrl+C`, `Shift+Delete`. `LogicalKeySet` has many problems and should not be used unless necessary and you know what you're doing.
