### ISSUE TITLE
Images are rendered at low quality at master branch

### ISSUE THREAD

**Issue by narumishi** [flutter/flutter#76513]
## Steps to Reproduce
1. create a widget to show one image(asset network images are all ok).
2. run app with `stable` and `master` branch of flutter
3. the image quality of stable branch is higher than master branch 

- left: built with some early version of flutter 1.26 (master), maybe one month ago
- right: built with latest master branch `1.27.0-5.0.pre.90`
<img width="900" alt="Screen Shot 2021-02-22 at 09 39 47" src="https://user-images.githubusercontent.com/56487872/108689971-bd52c700-7534-11eb-96a0-2a0a57e305c0.png">

(the shadow is because of macOS application window)

We can see the left one looks more smooth and text in image is more clear, all settings for `Image` widget are left default. This happens on all platforms including macOS/windows/android.

I checked these two months' commits of `flutter/lib/src/widgets/image.dart`, the only change maybe related is `filterQuality`. But changing to `FilterQuality.high` takes no sense. 

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.90, on Mac OS X 10.15.7 19H512
    darwin-x64, locale en-CN)
    • Flutter version 1.27.0-5.0.pre.90 at /Users/narumi/Library/flutter-master
    • Framework revision 371dd87aa0 (2 days ago), 2021-02-20 13:11:58 +0100
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/narumi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/202.7094744/Android
      Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 9F3B098B-85CD-4BBA-BC49-ABA7752723E7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H512 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment]
I can notice some quality difference between the Master and stable channel.

Tip: you may want to open the image to better notice the difference!

| Stable channel | Master channel |
|-|-|
|![Screen Shot 2021-02-22 at 12 16 51](https://user-images.githubusercontent.com/67424416/108701142-db560280-7507-11eb-8743-ac604530df3c.png)|![Screen Shot 2021-02-22 at 12 09 52](https://user-images.githubusercontent.com/67424416/108701161-e446d400-7507-11eb-92dc-a5a774e2c70a.png)|

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-5.0.pre.94 at /Users/pedromassango/Code/flutter_master
    • Framework revision 5642bed237 (4 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```
```bash

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by narumishi** [comment]
Actually I have already searched that issue/PR, but image quality is significantly reduced and cannot improve its quality by pass `FilterQuality.high`. Since I already use the master branch with  74854 merged, I wonder this is still a bug now or just I miss-understood something? Thanks.

**Comment by chinmaygarde** [comment]
This should be fixed by https://github.com/flutter/engine/commit/5dc0408e6c79f2e39f3ac6888ef216b665d9786c.

**Comment by narumishi** [comment]
Sadly, the problem is still here :(
```dart
Image(
  image: AssetImage("res/img/chaldea.png"),
  filterQuality: FilterQuality.high,
),
```
<img width="403" alt="Screen Shot 2021-02-23 at 07 36 55" src="https://user-images.githubusercontent.com/56487872/108784233-ea8d8c80-75a9-11eb-876d-dab764640947.png">
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.106, on Mac OS X 10.15.7 19H512
    darwin-x64, locale en-CN)
    • Flutter version 1.27.0-5.0.pre.106 at /Users/narumi/Library/flutter-master
    • Framework revision d69e2f10d8 (46 minutes ago), 2021-02-22 14:46:04 -0800
    • Engine revision 07afcf7d0f
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/narumi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/202.7094744/Android
      Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H512
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```
</details>

**Comment by chinmaygarde** [comment]
The engine revision has not rolled into the framework yet. Your `doctor` log shows the framework using an engine revision from [3 days ago](https://github.com/flutter/engine/commit/07afcf7d0f). [The patch I referenced](https://github.com/flutter/engine/commit/5dc0408e6c79f2e39f3ac6888ef216b665d9786c) landed 6 hours ago.

**Comment by narumishi** [comment]
Got it, I was unaware of the relations of framework and engine before. Thanks for your quick reply 👍
