### ISSUE TITLE
[Windows] Key event processing hung after typing character using AltGr

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#78005]
Hi,
In the demo application Flutter Folio for desktop (https://flutter.gskinner.com/#g-download) there is a serious problem, to enter the login in the application I had to type the character @, when it is pressed @ you can no longer continue typing, the problem is that it interferes in all windows and no longer you can type in any of the windows apps, only the ENTER key works ... 
Pressing characters in Notepad causes a line break. 
You need to restart your computer for the keyboard to work properly again. 
Spanish keyboard.
Windows 10 20H2
Check out the following video: https://recordit.co/pQTePNDduz
Regards,
Jose

**Comment by iapicca** [comment]
@Josua2012 
this issue should probably be addressed in [flutter-folio' s repo](https://github.com/gskinnerTeam/flutter-folio/issues)
if you believe the issue is caused by flutter please  provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Josua2012** [comment]
@iapicca 
It is clearly a Flutter 2.0 Windows bug.
It was not really necessary to do any example, you just had to put a TextField and write, for example: pepe@
I am sending you an example, the problem is that every time I do the test I have to restart my computer. :( 

[pruebaArrows.zip](https://github.com/flutter/flutter/files/6129353/pruebaArrows.zip)

Regards,
Jose.

**Comment by darshankawar** [comment]
@Josua2012 
Tried your code sample on Windows 10 desktop with spanish keyboard enabled and typed `@`, but didn't see the crash.

<img width="360" alt="Screenshot 2021-03-12 at 5 41 51 PM" src="https://user-images.githubusercontent.com/67046386/110938711-4aca4f80-835a-11eb-89ee-05ee70e65b2c.png">
<img width="212" alt="Screenshot 2021-03-12 at 5 42 04 PM" src="https://user-images.githubusercontent.com/67046386/110938717-4c941300-835a-11eb-99c3-4836d68173cf.png">

![IMG-0693](https://user-images.githubusercontent.com/67046386/110938728-50c03080-835a-11eb-895e-9d1bdeb278b8.JPG)

What spanish keyboard settings do you have ? I select the espanyol keyboard, not sure if any other setting is required ?

Also provide your `flutter doctor -v`.

**Comment by Josua2012** [comment]
@darshankawar,
The keyboard configuration of my computer is the standard keyboard configuration when installing a Spanish Windows 10 pro.
The configuration is: Español (España, Internacional)  In English: Spanish (Spain, International).
I have installed the English configuration on my computer and selecting it does not produce the error that I am telling you.
I have also tried to run the compiled program on another computer to be able to do more tests. Visual Studio Code and Visual Studio are not installed on this computer and when I try to run it it tells me that it cannot continue because it did not find VCRUNTIME140_1d.dll. I have installed VC_redist.x64.exe and VC_redist.x86.exe, but it tells me that it can't find VCRUNTIME140_1d.dll either.
What do I have to do to run the compiled program on a non-development computer? 
Other things, from what I see in the screenshot that you have sent me, you have not used the example program that I have sent you. Have you done the test with him?
The key combination for @ on a physical Spanish keyboard is to simultaneously press the ALT Gr + 2 key. I have taken a picture of my keyboard so that you can see which keys they are. 
I enclose many screenshots with the configuration of my computer, etc. 
![2021-03-12_13-50-49](https://user-images.githubusercontent.com/1523607/110947253-3711ef80-8340-11eb-90e8-64b431223b00.jpg)
![2021-03-12_13-51-10](https://user-images.githubusercontent.com/1523607/110947255-37aa8600-8340-11eb-8b82-32c4a2b56537.jpg)
![2021-03-12_13-57-53](https://user-images.githubusercontent.com/1523607/110947256-38dbb300-8340-11eb-8d46-09174792444f.jpg)
![1615555015047-2](https://user-images.githubusercontent.com/1523607/110947261-3a0ce000-8340-11eb-81f5-0c8b08ef7837.jpg)
![2021-03-12_13-42-31](https://user-images.githubusercontent.com/1523607/110947269-3bd6a380-8340-11eb-9e49-2b98185fc581.jpg)
![2021-03-12_13-43-35](https://user-images.githubusercontent.com/1523607/110947271-3c6f3a00-8340-11eb-8a1d-5da09e8fa810.jpg)
![2021-03-12_13-44-28](https://user-images.githubusercontent.com/1523607/110947273-3c6f3a00-8340-11eb-8dae-f37e388afcd9.jpg)
![2021-03-12_13-45-00](https://user-images.githubusercontent.com/1523607/110947275-3d07d080-8340-11eb-9351-be4996af254a.jpg)

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation.

**Comment by cbracken** [comment]
@Josua2012 thanks for reporting -- this may be a sub-case of https://github.com/flutter/flutter/issues/44918

/cc @dkwingsmt for thoughts.

**Comment by mortifia** [comment]
same bug with french keyboard (azerty)
win 10
flutter stable with null safety

key bug :
-  capslock (lock all key to minus)
- altGr ( unlock with Ctrl )( altGr + Ctrl + @ work ✨ )

**Comment by zsmiklos** [comment]
Similar or same problem in Hungarian Windows too:
In any Flutter app in a TextField widget, on Windows, pressing once the AltGr key will drive Windows keyboard crazy: after pressing AltGr, Windows behaves as if the ctrl key was pressed continuously in any application. (Pressing a simple v behaves like if the ctrl-v was pressed) Just double-pressing the left ctrl key will stop this strange state.

Thus, no Windows application written in flutter can be published because if the user presses the AltGr key, he will not understand why his keyboard will not work in any other application afterwards.

It can be reproduced every time, in every environment. On other Windows too. On other machine too. In release exe version too. E.g. in StaleFulWidget, and a TextField in it.

Windows version: Win 10 Pro 20H2 (build:19042.870) Hungarian version. In Hungarian keyboard the @ key is AltGr+v. So users can not type any email address.

Flutter versions: Flutter is already up to date on channel beta Flutter 2.1.0-12.2.pre • channel beta • https://github.com/flutter/flutter.git Framework • revision 5bedb7b1d5 (6 days ago) • 2021-03-17 17:06:30 -0700 Engine • revision 711ab3fda0 Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)

Flutter doctor is perfect. C:\flutter\bin\flutter.bat doctor --verbose 
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.870], locale hu-HU) • Flutter version 2.1.0-12.2.pre at C:\flutter • Framework revision 5bedb7b1d5 (6 days ago), 2021-03-17 17:06:30 -0700 • Engine revision 711ab3fda0 • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at C:\Users\zsmik\AppData\Local\Android\sdk • Platform android-30, build-tools 30.0.3 • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01) • All Android licenses accepted.

[√] Chrome - develop for the web • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2) • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community • Visual Studio Community 2019 version 16.9.31112.23 • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0) • Android Studio at C:\Program Files\Android\Android Studio • Flutter plugin can be installed from: https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available) • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.870] • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90 • Edge (web) • edge • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!

**Comment by herrmayr** [comment]
Same issue with German Keyboard layout!

**Comment by Appli-chic** [comment]
I confirm the issue with a french Azerty keyboard.

**Comment by cbracken** [comment]
@dkwingsmt how close are we on a fix for this?

**Comment by herrmayr** [comment]
> @dkwingsmt how close are we on a fix for this?

Also wondering - this seems to be fairly widespread, reproducable and severe in terms of show-stopping. For me, it‘s the one thing preventing me from shipping ...

**Comment by zsmiklos** [comment]
Today released new Flutter version (beta and dev) does not contains this bug fix. Could this problem be given a higher priority? As mentioned here https://github.com/flutter/flutter/issues/75768 , this is not a TextField dependent error, but affects Windows as a whole, where the user presses the AltGr key in a Flutter app.

**Comment by carmas123** [comment]
@zsmiklos this is right!! How we can think to start dev a simple windows app with this horrible bug. I have long been waiting for a new release of Flutter to correct this problem. I am disappointed that such a serious problem is not being addressed.

**Comment by Josua2012** [comment]
@zsmiklos
Indeed, it makes no sense that this horrible bug has not yet been corrected. But since it doesn't affect English keyboards, maybe that's the reason.
Although there are also other bugs in the introduction of characters that have not yet been corrected.
They may have other high priority matters. ;)
Until this bug is fixed, I cannot continue testing the desktop windows. It gives me the feeling of uselessness. :(
Regards,

**Comment by pasleto** [comment]
same bug with czech keyboard (qwertz, qwerty)
win 10 pro
flutter stable with null safety

pressing altGr freeze typing for whole system ( can be unlocked by pressing Ctrl )

**Comment by dkwingsmt** [comment]
Hi everyone! The author for the keyboard system here. I'm sorry for the frustration that this issue has been causing, and I'm aware that it's taking longer than expected. Just want to let everyone know that I'm fully working on the refined keyboard system that should resolve this issue as well as a number of others. Without guarantees, it's close to an end. I'm as eager for an easy-to-use keyboard as everyone, and that's why the system took a little more time.

**Comment by Josua2012** [comment]
@dkwingsmt
Thank you very much for your hard work.

**Comment by zsmiklos** [comment]
Today released new Flutter version (beta) does not contains this bug fix. So you cannot release a Windows app outside of USA since more than 2 months because of this keyboard error. This is very sad.

**Comment by Josua2012** [comment]
Really is very sad, it is not very logical that all the problems of the text input are not solved, time is passing and there is no news about these problems, it is very strange. I think it is a very high priority, but apparently they do not see these problems as a high priority. :(

**Comment by Coimbra1984** [comment]
Same problem here. I have a German keyboard. Unfortunately we're unable to release a windows app until the most basic user interaction (keyboard input) works properly. It's a **no-go** to tell the customer to reboot their machine if they try to input a '@' sign on username or password inputs (@ is AltGr+Q on our keyboard).
@dkwingsmt is there any update on the schedule? I know it is hard to predict but we should communicate something to our customer.

**Comment by rydmike** [comment]
The issue is the same with FIN/SWE keyboard. If you enter @ in a TextField (You use AltGr key + 2) to enter @ on a FIN/SWE keyboard. After doing this everything gets completely messed up. You cannot enter anything sensible after it in ANY app in Windows, even after killing the Flutter app. I had to reboot my Windows machine to get it restored to normal.

This is quite badly messed up!

**Comment by escamoteur** [comment]
@dkwingsmt could you explain use why this is to difficult and why a Flutter App seems to hook like this into the windows input system? Why can't you just use the keycodes the windows app receives in it's message loop?
I was really shocked that a Flutter up messes up the whole Keyboard handling on a Windows PC?

**Comment by DanOl98** [comment]
Same here in Italy. Pressing AltGr messes up the keyboard. Right Shift key messes up too (acts as some king of caps lock).

**Comment by escamoteur** [comment]
@DanOl98 the right shift problems seems to be solved on latest master

**Comment by rydmike** [comment]
@DanOl98 This is the fix for the right shift case, it has indeed landed in master, but not in dev yet.
https://github.com/flutter/engine/pull/25882

Of course it does not help with this quite bad AltGr issue.

**Comment by Coimbra1984** [comment]
> The issue is the same with FIN/SWE keyboard. If you enter @ in a TextField (You use AltGr key + 2) to enter @ on a FIN/SWE keyboard. After doing this everything gets completely messed up. You cannot enter anything sensible after it in ANY app in Windows, even after killing the Flutter app. I had to reboot my Windows machine to get it restored to normal.
> 
> This is quite badly messed up!

When I press the left CTRL key on my keyboard, windows behaves normal again, which at least prevents me from a reboot.

**Comment by imariman** [comment]
I need this fix urgently. One question for a quick fix; Is there any way we can pretend that the user had pressed ctrl too once user press to altgr button? I tried to do this with rawkeyboardlistener but it didn't work. (I got 164-162 (altgr-ctrl) data from listener but it did not act like user pressed ctrl from keyboard)

**Comment by rydmike** [comment]
@Coimbra1984 wrote:
> When I press the left CTRL key on my keyboard, windows behaves normal again, which at least prevents me from a reboot.

If that works, it is a very good find, since you can then at least use it to fix the mess if you accidentally use AltGr in a TextField on Windows. I'm going to try that later today, when I have time for a reboot, in case it does not work. Thanks for the tip!

**Comment by imariman** [comment]
Hello everyone!

Today I made a temporary quick fix for this bug. I know it is not the best solution for that problem, but at least I don't have any weird bugs once I press altgr or right shift buttons at the moment.

How to fix:
1- Go to services/raw_keyboard.dart
2- Find line 657 _handleKeyEvent
3- Put the code below at line 660 (after the "bool shouldDispatch=true" line)

 if (event.data.logicalKey == LogicalKeyboardKey.controlLeft ||
        event.data.logicalKey == LogicalKeyboardKey.shiftRight) {
      shouldDispatch = false;
    }

For now its working fine on my windows machine, please do your own tests before you use this code. Hope to see real permanent solution for these weird keyboard bugs soon. 

Thanks.

**Comment by zsmiklos** [comment]
@imariman Thank you very much! It seems it works.  I'am waiting for similar fix since 2-3 months (from the Flutter team). I converted an Android app from Java to Dart (in 2 months), near 100 000 rows and the result: everything worked except the buggy keyboard system handler. And congratulation @imariman ! Now I can publish my Windows app!!! :) :)

**Comment by Ionys320** [comment]
Hi @imariman !
Did you consider making a pull request? I don't know if you think your code could go in Flutter's framework, but even if it's a temporary fix, I think many users of Flutter can be concerned with this issue.

Thanks for your job!

**Comment by imariman** [comment]
@lonys320 no, this code is very ugly, lol. For a quick fix you can use it, but I don't think it can go in Flutter's framework. It would be better to wait for the permanent solution from the Flutter team. :)

**Comment by escamoteur** [comment]
@timsneath @csells please, your European users have a real problem here. Can't we add the above 'hack as a quick fix somehow?

**Comment by escamoteur** [comment]
The problem is if I make that change locally any `flutter upgrade` call will remove it again.

**Comment by csells** [comment]
@gspencergoog any thoughts on this?

**Comment by haitr** [comment]
I am using Korean Keyboard, a non-US keyboard, and had issues with AltGr (aka Right Alt) and Right Shift key on Windows and Flutter 2.2.2. However the solution from @imariman didn't work for me. After inspected, there are some reasons I found:

- On Right Shift  key pressed, it fired RawKeyDownEvent but no RawKeyUpEvent

- On AltGr key pressed, RawKeyDownEvent reported that it has keyCode 0x107000000e5 but RawKeyUpEvent is 0x10700000015

All of those messed up the key map. I agreed with @imariman that it should be fixed in engine level, we can just hotfix in our local Flutter codebase to make it work. Similar to his solution

1. Go to <flutter_directory>/packages/flutter/lib/src/services/raw_keyboard.dart
2. In function <_handleKeyEvent> line 657 (Flutter 2.2.2, it could be different)
3. Look at this block:
`
if (event is RawKeyDownEvent) {
   <something>
}
`
change into
`
if (event is RawKeyDownEvent) {
  if (event .data.logicalKey == LogicalKeyboardKey.shiftRight || event.data.logicalKey.keyId == 0x107000000e5) {
    shouldDispatch = false;
  } else
  <something>
}
`
Now I can release my Windows version

**Comment by furkan1023** [comment]
@haitr it didnt work for me :( . I changed

`
if (event is RawKeyDownEvent) {
      if (event.data.shouldDispatchEvent()) {
        _keysPressed[event.physicalKey] = event.logicalKey;
      } else {
        shouldDispatch = false;
        _hiddenKeysPressed.add(event.physicalKey);
      }
    } else if (event is RawKeyUpEvent) {
      if (!_hiddenKeysPressed.contains(event.physicalKey)) {
        // Use the physical key in the key up event to find the physical key from
        // the corresponding key down event and remove it, even if the logical
        // keys don't match.
        _keysPressed.remove(event.physicalKey);
      } else {
        _hiddenKeysPressed.remove(event.physicalKey);
        shouldDispatch = false;
      }
    }
`

to
`

if (event is RawKeyDownEvent) {
      if (event.data.logicalKey == LogicalKeyboardKey.shiftRight ||
          event.data.logicalKey.keyId == 0x107000000e5) {
        shouldDispatch = false;
      } else {
        if (event.data.shouldDispatchEvent()) {
          _keysPressed[event.physicalKey] = event.logicalKey;
        } else {
          shouldDispatch = false;
          _hiddenKeysPressed.add(event.physicalKey);
        }
      }
    } else if (event is RawKeyUpEvent) {
      if (!_hiddenKeysPressed.contains(event.physicalKey)) {
        // Use the physical key in the key up event to find the physical key from
        // the corresponding key down event and remove it, even if the logical
        // keys don't match.
        _keysPressed.remove(event.physicalKey);
      } else {
        _hiddenKeysPressed.remove(event.physicalKey);
        shouldDispatch = false;
      }
    }
`

maybe i did something wrong.

**Comment by haitr** [comment]
@furkan1023 it looks good. You have the problem on Right Alt, I guess? The main idea is completely block Right Shift and Right Alt, so maybe you need to add one more condition for `LogicalKeyboardKey.rightAlt`. On my keyboard, AltGr cannot be mapped into altRight but the 0x107000000e5 key. You can print out that key down event to see which key is pressed. 

Also, try to stop and re-run your app to reload `raw_keyboard.dart` file.

**Comment by MarcoGolin** [comment]
I have the same problem, this solution not work for me =(, any other code to test??

**Comment by Josua2012** [comment]
What seems quite incredible is that after 5 months we still do not have a solution directly in Flutter. :(

**Comment by phillausofia** [comment]
On my machine, what I noticed is that after you press AltGr, the computer thinks that Ctrl Left is still pressed. Something similar happens when you also press Shift Right. So, instead of changing the raw_keyboard.dart file - like above -, I think it's better to implement the solution for the Shift Right: https://github.com/flutter/flutter/issues/75675 Replacing the following code:
`        return event.physicalKey == PhysicalKeyboardKey.shiftRight ?
          KeyEventResult.handled : KeyEventResult.ignored;
`
with
`return [PhysicalKeyboardKey.shiftRight, PhysicalKeyboardKey.controlLeft].contains(event.physicalKey) ? KeyEventResult.handled : KeyEventResult.ignored;`

This way you fix both problems.

**Comment by escamoteur** [comment]
@csells any update here? Many non US keyboard users are affected here. I know Windows Desktop is still no release version but this is a regression it was working before and people including myself are using Windows Desktop in production. Not being able to enter an '@' sign is pretty dramatic for any login dialog.

**Comment by C4s4r** [comment]
@escamoteur I think it was resolved in this PR: https://github.com/flutter/engine/pull/27266
So it should be fixed within the next Flutter version.

**Comment by escamoteur** [comment]
ah, awesome, will have to check if its already in the current master

**Comment by dkwingsmt** [comment]
This PR should have been fixed by flutter/engine#27266 (I waited for a few days for it to be rolled into the framework). Please update to the latest framework version (master channel).

I'll close this issue for now but feel free comment if there are any other issues, and reopen the issue if deemed necessary (don't forget to append your Flutter version in the report).

Thank you for your patience.

**Comment by imariman** [comment]
We still have problems with the same buttons, unfortunately.

Problem 1 - (AltGr Button): I typed "johndoe@gmail.com" on the login form, and what I got is "johndoe@@ggmmaaiill..ccoomm". Once I press the "AltGr" button, it starts to type every character twice. To fix it, I need to press the AltGr button again.

Problem 2 - (Left Ctrl Button): Same here, once I press the left Ctrl button, it starts to type every character twice. To fix it, I need to press LCtrl button again.

My Flutter doctor logs:
 Flutter (Channel master, 2.4.0-1.0.pre.208, on Microsoft Windows [Version 10.0.19042.1083], locale en-US)
    • Flutter version 2.4.0-1.0.pre.208 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d2057d50c4 (74 minutes ago), 2021-07-13 11:01:03 -0700
    • Engine revision 07d04041d5
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

For your information.
Thanks for your helps in advance.

**Comment by dkwingsmt** [comment]
> We still have problems with the same buttons, unfortunately.
> 
> 
> 
> Problem 1 - (AltGr Button): I typed "johndoe@gmail.com" on the login form, and what I got is "johndoe@@ggmmaaiill..ccoomm". Once I press the "AltGr" button, it starts to type every character twice. To fix it, I need to press the AltGr button again.
> 
> 
> 
> Problem 2 - (Left Ctrl Button): Same here, once I press the left Ctrl button, it starts to type every character twice. To fix it, I need to press LCtrl button again.
> 
> 
> 
> My Flutter doctor logs:
> 
>  Flutter (Channel master, 2.4.0-1.0.pre.208, on Microsoft Windows [Version 10.0.19042.1083], locale en-US)
> 
>     • Flutter version 2.4.0-1.0.pre.208 at C:\src\flutter
> 
>     • Upstream repository https://github.com/flutter/flutter.git
> 
>     • Framework revision d2057d50c4 (74 minutes ago), 2021-07-13 11:01:03 -0700
> 
>     • Engine revision 07d04041d5
> 
>     • Dart version 2.14.0 (build 2.14.0-301.0.dev)
> 
> 
> 
> For your information.
> 
> Thanks for your helps in advance.

Thanks for the report. I don't think I've seen this issue when I was testing (I just use a text field), so can you provide a minimal example?

**Comment by MarcoGolin** [comment]
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#80cf2(logicalKey: LogicalKeyboardKey#00037(keyId: "0x50000000037", keyLabel: "Numpad 7", debugName: "Numpad 7"), physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left")) and its data: Instance of 'RawKeyEventDataWindows'
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 666 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

[√] Flutter (Channel master, 2.4.0-1.0.pre.212, on Microsoft Windows [VersiÃ³n 10.0.19042.1083], locale es-PY)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.   
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.1)
[√] Connected device (3 available)

the ERROR PERSIST

**Comment by dkwingsmt** [comment]
@MarcoGolin I believe that is a different issue. Can you file a new issue to describe this bug, including how to reproduce?

**Comment by imariman** [comment]
@dkwingsmt You can find the example code here ( https://github.com/imariman/login_form_bug_example ). Once you press either AltGr or LCtrl buttons, you can easily see the problem.  

Hope this helps,
Thanks.

**Comment by imariman** [comment]
AltGr + Q combination still has some problems. :) Once I try to type "johndoe@gmail.com", it types double "@" like "johndoe@@gmail.com". @dkwingsmt 

For your information.
Thanks for your helps in advance.

[√] Flutter (Channel master, 2.5.0-6.0.pre.57, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)

**Comment by dkwingsmt** [comment]
@imariman The engine hasn't been rolled into Flutter yet. Can you check back again in a few hours?

**Comment by imariman** [comment]
It works correctly now, thank you.

**Comment by valmorflores** [comment]
Problem in Linux. Altgr + @ sequenced by Ctrl (left)+@

![image](https://user-images.githubusercontent.com/7562848/129739813-569ad371-de11-416f-a311-53eed3cadc65.png)

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#34b0b(physicalKey: PhysicalKeyboardKey#7001f(usbHidUsage: "0x0007001f", debugName: "Digit 2"), logicalKey: LogicalKeyboardKey#00032(keyId: "0x00000032", keyLabel: "2", debugName: "Digit 2"), character: null, timeStamp: 26:51:57.783000) and the recorded logical key LogicalKeyboardKey#00040(keyId: "0x00000040", keyLabel: "@", debugName: "At")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'


==========

flutter doctor -v
[✓] Flutter (Channel master, 2.5.0-7.0.pre.105, on Linux Mint 19.2
    4.15.0-153-generic, locale pt_BR.UTF-8)
    • Flutter version 2.5.0-7.0.pre.105 at /home/valmor/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a2e33dec7c (8 hours ago), 2021-08-16 22:51:16 -0700
    • Engine revision 7dc8eba6ae
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/valmor/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 19.2
      4.15.0-153-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

**Comment by dkwingsmt** [comment]
@valmorflores Thank you, can you open a separate new issue so that it's easier to track?
