### ISSUE TITLE
[Web] [Null Safety] : CustomUrlStrategy: Expected a value of type 'Object', but got one of type 'Null' 

### ISSUE THREAD

**Issue by devj3ns** [flutter/flutter#78017]
When I run my flutter web app with `sound null safety` I get this error at the start. I am using the [url_strategy](https://pub.dev/packages/url_strategy) package:

```
Error: Expected a value of type 'Object', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:60029/dart_sdk.js:5032:11)
    at Object.castError (http://localhost:60029/dart_sdk.js:5005:15)
    at Object.cast [as as] (http://localhost:60029/dart_sdk.js:5314:17)
    at Function.as (http://localhost:60029/dart_sdk.js:6508:31)
    at Object._argumentErrors (http://localhost:60029/dart_sdk.js:5150:19)
    at Object._checkAndCall (http://localhost:60029/dart_sdk.js:5233:29)
    at Object.dcall (http://localhost:60029/dart_sdk.js:5242:17)
    at Object.ret [as replaceState] (http://localhost:60029/dart_sdk.js:57497:21)
    at _engine.CustomUrlStrategy.fromJs.replaceState (http://localhost:60029/dart_sdk.js:140910:28)
    at _engine.MultiEntriesBrowserHistory.new.tearDown (http://localhost:60029/dart_sdk.js:140622:42)
    at tearDown.next (<anonymous>)
    at runBody (http://localhost:60029/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:60029/dart_sdk.js:37260:7)
    at _engine.MultiEntriesBrowserHistory.new.tearDown (http://localhost:60029/dart_sdk.js:140609:20)
    at _engine.EngineSingletonFlutterWindow.new._useSingleEntryBrowserHistory (http://localhost:60029/dart_sdk.js:170475:76)
    at _useSingleEntryBrowserHistory.next (<anonymous>)
    at runBody (http://localhost:60029/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:60029/dart_sdk.js:37260:7)
    at _engine.EngineSingletonFlutterWindow.new.[_useSingleEntryBrowserHistory] (http://localhost:60029/dart_sdk.js:170469:20)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:60029/dart_sdk.js:170521:56)
    at handleNavigationMessage.next (<anonymous>)
    at runBody (http://localhost:60029/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:60029/dart_sdk.js:37260:7)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:60029/dart_sdk.js:170514:20)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:60029/dart_sdk.js:155384:68)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:60029/dart_sdk.js:155214:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:60029/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
    at _DefaultBinaryMessenger.send (http://localhost:60029/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:60029/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
    at _invokeMethod.next (<anonymous>)
```

The functionality, however, works fine. I am using Flutter 2.0.1 stable and version 0.2.0 of the package.

As the author says [here](https://github.com/simpleclub/url_strategy/issues/14) this has nothing to do with his package. Therefore, I opened this issue here.

<details>
  <summary>Flutter doctor -v output</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale de-DE)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\jensb\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\jensb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@devj3ns 
Added the said plugin and ran a sample app on latest stable (2.0.1) and on latest master (2.1.0) which compiled and built properly without throwing the exception you mentioned. 

<img width="1234" alt="Screenshot 2021-03-12 at 5 55 04 PM" src="https://user-images.githubusercontent.com/67046386/110940399-d93fd080-835c-11eb-95ac-7e5ccadfe9c3.png">

```
void main() {
  setPathUrlStrategy();
  runApp(MyApp());
}
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

I see that you are on Windows. Could that be a factor ?

**Comment by devj3ns** [comment]
Hey @darshankawar, thanks for testing. I also tested in a new project and there it works. 

So it's a problem with my project and not with flutter. Do you have an idea what could be wrong or how I can fix it?

**Comment by devj3ns** [comment]
When I run my web app with `--no-sound-null-safety` everything works. 

But all my code and dependencies are migrated. I don't understand why I get this error.

**Comment by darshankawar** [comment]
@devj3ns 


> So it's a problem with my project and not with flutter. Do you have an idea what could be wrong or how I can fix it?

May be you can try comparing new project with your project and see if you could find any config / setting that might be causing this issue.

**Comment by Ajmaljalal** [comment]
I encountered the same issue after using  url_strategy package.  the package owner says it is a flutter issue. 
I am using windows.

**Comment by creativecreatorormaybenot** [comment]
@Ajmaljalal to make it clear, all the package does is call a function:

https://github.com/simpleclub/url_strategy/blob/43cd81aee0e7cadf20944c0cdfe4524dd15c0a0b/url_strategy/lib/src/url_strategy_web.dart#L12

That is why I am confident in saying that this is not a problem with the package - because it is not expecting any types; just calling a function. If you look at the error log, you will see that the type error is in the **Flutter SDK function** that is called from the package.

**Comment by Azzeccagarbugli** [comment]
Just got the same issue, with `null-safety` enabled. That's pretty strange!

**Comment by devj3ns** [comment]
I think it would be good If you guys could all upvote this issue so that it gets more attention and hopefully fixed soon.

**Comment by darshankawar** [comment]
I was able to replicate the error on latest stable (2.0.3) using a sample app. The error occurs only when the app is running with sound null safety.

<details>
<summary>console error log</summary>

```
dhs@Dhss-MacBook-Pro web % flutter run -d chrome
Changing current working directory to: /Users/dhs/Documents/NCFlutter/int_test_demo
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             14.7s
Debug service listening on ws://127.0.0.1:50171/hgVZ6eABCvg=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Error: Expected a value of type 'Object', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:50149/dart_sdk.js:5032:11)
    at Object.castError (http://localhost:50149/dart_sdk.js:5005:15)
    at Object.cast [as as] (http://localhost:50149/dart_sdk.js:5314:17)
    at Function.as (http://localhost:50149/dart_sdk.js:6508:31)
    at Object._argumentErrors (http://localhost:50149/dart_sdk.js:5150:19)
    at Object._checkAndCall (http://localhost:50149/dart_sdk.js:5233:29)
    at Object.dcall (http://localhost:50149/dart_sdk.js:5242:17)
    at Object.ret [as replaceState] (http://localhost:50149/dart_sdk.js:57497:21)
    at _engine.CustomUrlStrategy.fromJs.replaceState (http://localhost:50149/dart_sdk.js:140910:28)
    at _engine.MultiEntriesBrowserHistory.new.tearDown (http://localhost:50149/dart_sdk.js:140622:42)
    at tearDown.next (<anonymous>)
    at runBody (http://localhost:50149/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:50149/dart_sdk.js:37260:7)
    at _engine.MultiEntriesBrowserHistory.new.tearDown (http://localhost:50149/dart_sdk.js:140609:20)
    at _engine.EngineSingletonFlutterWindow.new._useSingleEntryBrowserHistory (http://localhost:50149/dart_sdk.js:170475:76)
    at _useSingleEntryBrowserHistory.next (<anonymous>)
    at runBody (http://localhost:50149/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:50149/dart_sdk.js:37260:7)
    at _engine.EngineSingletonFlutterWindow.new.[_useSingleEntryBrowserHistory] (http://localhost:50149/dart_sdk.js:170469:20)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:50149/dart_sdk.js:170521:56)
    at handleNavigationMessage.next (<anonymous>)
    at runBody (http://localhost:50149/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:50149/dart_sdk.js:37260:7)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:50149/dart_sdk.js:170514:20)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:50149/dart_sdk.js:155384:68)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:50149/dart_sdk.js:155214:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
    at _DefaultBinaryMessenger.send (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:50149/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:50149/dart_sdk.js:37260:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:946:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:1078:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:1056:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:50149/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:50149/dart_sdk.js:37260:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:50149/packages/flutter/src/services/system_channels.dart.lib.js:1055:20)




```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by Abhishek01039** [comment]
hello @darshankawar 
I am still able to reproduce this issue on the latest stable branch.
I am trying this https://flutter.dev/docs/development/ui/navigation/url-strategies

**Comment by creativecreatorormaybenot** [comment]
@Abhishek01039 it was fixed on `master` only.

**Comment by Abhishek01039** [comment]
Thanks for your information @creativecreatorormaybenot

**Comment by vigneshksaithal** [comment]
I'm new to flutter. What should I do to solve this issue?

**Comment by devj3ns** [comment]
> I'm new to flutter. What should I do to solve this issue?

Hey, this issue is already solved. You just have to wait until the next Flutter release :)

**Comment by vigneshksaithal** [comment]
I still get this error even on Flutter 2.0.5-stable release.

**Comment by devj3ns** [comment]
> I still get this error even on Flutter 2.0.5-stable release.

Me too :(

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels. Fixes that land on master do not generally end up in bugfix releases to the existing stable version.

**Comment by rurickdev** [comment]
Just to anyone that gets here, I'm on 2.2.0 and the bug is still there

**Comment by kainjinez** [comment]
This still does not fix in a stable channel at my time.
