### ISSUE TITLE
Low Resolution in Camera Image Stream, ResolutionPreset Constructor Parameter is ignored

### ISSUE THREAD

**Issue by Joshua27** [flutter/flutter#78247]
Hi, 
I would like to process images from the camera while previewing the camera images using the camera plugin. I do not want to transform the preview image or draw anything on the previewed image.
From my understanding the function `CameraController#startImageStream()` is supposed to be used for such tasks.
This works as expected except of the point that the images send to the image stream only have 720p resolution or lower regardless what `ResolutionPreset` is set when constructing the `CameraController`

## Steps to Reproduce

**Goal**: Process images from the camera in best available resolution (send to isolates to not block the main isolate) while previewing the camera images.

**Most important parts of the implementation**:

Create controller:
```
_controller = CameraController(
  cameraDescription,
  ResolutionPreset.max,
  enableAudio: false,
);
```

Show camera preview using widget:
```
CameraPreview(_controller)
```

Listen to image stream:
```
_controller.startImageStream((image) {
        print("Image size: ${image.width}x${image.height}");
      });
```

The `CameraDescription` is provided by `onNewCameraSelected()` as demonstrated in the example provided along with this camera plugin.
To reproduce this issue you can run the example provided in this package and listen to the image stream while previewing the camera images. 

**Expected results**: Maximum available image resolution in the image stream. My devices should have 4k resolution (or at least Full-HD). 

**Actual results**: Always 720p (or lower if requested).

**Tested Devices**: Samsung Galaxy S10 and S10e

The constructor parameter of `CameraController` defining `ResolutionPreset` is ignored/overwritten if it is greater than `ResolutionPreset.high`.
As already pointed out in issue #49420, the following function in the camera plugin is the reason for this behavior:
```
static Size computeBestPreviewSize(String cameraName, ResolutionPreset preset) {
    if (preset.ordinal() > ResolutionPreset.high.ordinal()) {
      preset = ResolutionPreset.high;
    }
    CamcorderProfile profile =
        getBestAvailableCamcorderProfileForResolutionPreset(cameraName, preset);
    return new Size(profile.videoFrameWidth, profile.videoFrameHeight);
  }
```

I see the point that the resolution has to be scaled down for preview.
However, there should be a possibility to process the camera images in the specified resolution.
It should be up to the developer to not block the main thread when listening to an image stream.

My current workaround is to build the camera plugin locally and change `CameraUtils#computeBestPreviewSize()` as follows:
```
static Size computeBestPreviewSize(String cameraName, ResolutionPreset preset) {
    //if (preset.ordinal() > ResolutionPreset.high.ordinal()) {
    //  preset = ResolutionPreset.high;
    //}
    CamcorderProfile profile =
        getBestAvailableCamcorderProfileForResolutionPreset(cameraName, preset);
    return new Size(profile.videoFrameWidth, profile.videoFrameHeight);
  }
```
Of course, this now slows down the camera preview on older devices or is really slow if 4K resolution is used.
Yet, I couldn't find a way to downscale the image before being previewed using above initialization.
I was able to improve performance for previewing a little by changing line 35 of camera_preview.dart from
```
CameraPlatform.instance.buildPreview(controller.cameraId)
```
to 
```
Texture(textureId: controller.cameraId, filterQuality: FilterQuality.none)
```
The default setting of the parameter `filterQuality` is `FilterQuality.low`, which is currently used.
According to the documentation of `FilterQuality` the setting `FilterQuality.none` is faster. 

**Summary**: Is it currently possible to process the camera images with the requested resolution while previewing the camera images in a lower resolution?

If this is not the case, I would like to request the feature to add another image stream to `CameraController` which is not used for previewing as described above. The images in the stream used for previewing can be downscaled, that's fine.
Alternatively, one might be able to add an additional constructor parameter and field to `CameraController` which defines the preview size (use to downscale before actual preview) while the images send to the single image stream have the requested resolution. 
Of course, if I select a large preview size the performance is bad. But this decision should be adjustable and up to the developer.

<details>
<summary>Output of `flutter-doctor -v`</summary>
<br>
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale de_DE.UTF-8)
    • Flutter version 2.0.2 at /home/joshua/snap/flutter/common/flutter
    • Framework revision 8962f6dc68 (vor 4 Tagen), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/joshua/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /home/joshua/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6183.87
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/joshua/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G970F (mobile) • RF8M20WXQAA • android-arm64 • Android 10 (API 29)
    • SM G973F (mobile) • RF8N40DYR5Y • android-arm64 • Android 11 (API 30)

! Doctor found issues in 3 categories.
</details>

The issue #58163 seems to be related as well.

Greetings,
Joshua

**Comment by darshankawar** [comment]
Thanks @Joshua27 for a detailed report. It'd be great if you could also provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can directly use alongwith actual vs expected behavior to properly address this issue.

**Comment by Joshua27** [comment]
Thank you for the quick response. I created a minimum reproducible example which you can find here: https://github.com/Joshua27/flutter_issue_78247

**Comment by darshankawar** [comment]
Thanks for repo.

<details>
<summary>flutter doctor -v</summary>

```
Downloading darwin-x64/font-subset tools...                        292ms
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by tzvc** [comment]
Any updates on this ? Still running into the issue on 0.9.4+5

**Comment by datvimaru50** [comment]
I use the latest version but the problem still exist. The max resolution the android device can output is 1280x720

**Comment by exaby73** [comment]
## Updated triage report

As per https://github.com/flutter/flutter/issues/111172, this issue is still reproducible on the latest version of Flutter.

### Vesions reproducible on

- `Stable (3.3.1)`
- `Master (3.4.0-19.0.pre.192)`

### Info

<details>
<summary>(Smaller) Code Sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

late final List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  CameraController? controller;
  int? width;
  int? height;

  @override
  void initState() {
    super.initState();
    initCamera();
  }

  Future<void> initCamera() async {
    controller = CameraController(
      cameras.first,
      ResolutionPreset.max,
    );

    await controller!.initialize();
    controller!.startImageStream(
      (image) {
        setState(() {
          height = image.height;
          width = image.width;
        });
      },
    );
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: controller != null
                ? CameraPreview(controller!)
                : const SizedBox(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('height: $height\t\twidth: $width'),
            ],
          ),
        ],
      ),
    );
  }
}
```

</details>

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.918], locale en-US)
    • Flutter version 3.3.1 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (5 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on Microsoft Windows [Version 10.0.22000.918], locale en-US)
    • Flutter version 3.4.0-19.0.pre.192 on channel master at C:\Users\Nabeel\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4930444f4a (2 days ago), 2022-09-09 21:58:23 -0400
    • Engine revision f72107f457
    • Dart version 2.19.0 (build 2.19.0-183.0.dev)
    • DevTools version 2.17.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by slobodanmilinkovic** [comment]
Any news on this? Please, this is stopping my app from being published.

**Comment by gianlucasama** [comment]
I found the same issue while using the camera plugin. Shouldn't a core library, maintained by the Flutter team itself, have an issue like this resolved in no time? It's been 2 years since the first post.

**Comment by KerimYilPROCON** [comment]
Are there any fixes planned? The issue still exists with version ^0.10.4

**Comment by talalong** [comment]
It has been 2 years and I am still facing the issue with version 0.10.5+2. :(

**Comment by Joshua27** [comment]
Such comments have no effect.
Please upvote the top level comment to give this issue a higher priority.
See https://github.com/flutter/flutter/wiki/Issue-hygiene

**Comment by kishan2612** [comment]
its been so many years. becaused of this we cannot use this for our mlkit projects. need to rely on native code for camera customisation

**Comment by AwaisQazii** [comment]
This workaround fixed the low-quality image preview issue for me.
I overrode the camera_android_camerax dependency to the latest version, significantly improving the preview quality.

```
    dependencies:
      camera: ^0.11.0+2
    dependency_overrides:
      camera_android_camerax: ^0.6.10+3
```

**Comment by GregUAs** [comment]
> This workaround fixed the low-quality image preview issue for me. I overrode the camera_android_camerax dependency to the latest version, significantly improving the preview quality.
> 
> ```
>     dependencies:
>       camera: ^0.11.0+2
>     dependency_overrides:
>       camera_android_camerax: ^0.6.10+3
> ```

Works for me ! Thank you 💯
