### ISSUE TITLE
Memory leak with Stateless Widget

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#79605]
In this example, each time I press "Click", 50M of ram is allocated. It is never reclaimed, I can push 30 pages and take up 1.5gb, despite there only ever being 1 page on the nav stack. GC never kicks in. What's going on here?

I'm using Windows Task manager to watch the total RAM consumed by the Flutter App process.
![image](https://user-images.githubusercontent.com/736973/113374756-13343f00-932b-11eb-85dd-d26cbe669745.png)

Flutter (Channel master, 2.1.0-11.0.pre.122, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
```
void main() {
  runApp(MaterialApp(
    home: MemoryTest(),
  ));
}

class MemoryTest extends StatelessWidget {
  final List<EdgeInsets> insets = List.generate(
    1000000,
    (index) => EdgeInsets.all(0),
  );
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Column(
        children: [
          OutlinedButton(
            child: Text("CLICK"),
            onPressed: () {
              Navigator.of(context).pushReplacement(MaterialPageRoute(
                builder: (_) => MemoryTest(),
              ));
            },
          ),
        ],
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @esDotDev 
I can reproduce it, memory usage keeps increasing 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.444, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.1.0-13.0.pre.444 at C:\Users\Taha\Code\flutter_master
    • Framework revision 824b1ad3f8 (2 days ago), 2021-04-03 15:24:02 -0400
    • Engine revision e393800c63
    • Dart version 2.13.0 (build 2.13.0-196.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
	
</details>

Thanks for filing the issue

**Comment by chinmaygarde** [comment]
cc @goderbauer @Hixie

**Comment by Hixie** [comment]
This is probably debug-mode specific. I expect we're keeping widgets around for the inspector or the timeline or some such. If that's it, it's probably working as intended. Does it repro in `--profile` mode?

cc @jacob314

**Comment by esDotDev** [comment]
From my testing it works in profile and release mode. 

Here you can see me replicating it with a much more realworld example:
```
class MemoryTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Widget content = OutlinedButton(
      child: Text("CLICK"),
      onPressed: () {
        Navigator.of(context).pushReplacement(MaterialPageRoute(
          builder: (_) => MemoryTest(),
        ));
      },
    );
    for (var i = 10; i-- > 0; i) {
      content = Padding(padding: EdgeInsets.all(0), child: content);
    }
    return content;
  }
}
```
https://user-images.githubusercontent.com/736973/113609065-8af2ba00-9608-11eb-8089-052e84dc7478.mp4

As I add routes, memory just climbs. Also, as I resize the window, it also generates a ton of memory that is seemingly never reclaimed.

**Comment by Hixie** [comment]
If it's leaking in `--release` mode that's definitely an issue. cc @dnfield

**Comment by esDotDev** [comment]
It's certainly slower to increase in release mode, but I can still push it up from 20mb to 60mb of ram, by hammering on the btn for 30 seconds or so.

**Comment by dnfield** [comment]
I strongly suspect this is a bug in navigator code. Looking at the allocation profile and heapsnapshot, looks like something is retaining a reference to previous routes that have been replaced. The docs indicate that the previous route should be getting "disposed".

@chunhtai 

I'll try to take a little further look at this and see if I can find the retain.

**Comment by dnfield** [comment]
Bug is in the restoration code's interaction with navgiator. @goderbauer 

Will post a few more details in a few.

**Comment by goderbauer** [comment]
I am happy to take a look.

I am surprised the restoration code shows up in the profile at all since it looks like restoration is turned off in the example code given...

**Comment by dnfield** [comment]
Quick update - it is not the restoration code, I was wrong about that. This appears to be an issue with the navigator right now. Still looking into it with @goderbauer

**Comment by goderbauer** [comment]
I am puzzled by this. In the example below, if you hit the "PageRouteBuilder" button n times it appears that there's a memory leak because the instantiated MyBigObjects never seem to be deallocated according to the allocation profile in Observatory. However, if you hit any of the other buttons n times, no such leak can be observed. Of particular interest is that PageRouteBuilder2 does not show the leak. It's the only difference that it is factoring out the closure that builds the route's widget into a member method.

Also: When you hit any other button but the PageRouteBuilder button, suddenly the accumulated MyBigObjects are deallocated. 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MemoryTest(),
  ));
}

class MemoryTest extends StatelessWidget {
  final MyBigObject bigObj = MyBigObject();

  Widget _foo(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) => MemoryTest();

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Wrap(
        children: [
          OutlinedButton(
            child: Text("CTransition"),
            onPressed: () {
              Navigator.of(context).pushReplacement(CTransitionRoute());
            },
          ),
          OutlinedButton(
            child: Text("CModal"),
            onPressed: () {
              Navigator.of(context).pushReplacement(CModalRoute());
            },
          ),
          OutlinedButton(
            child: Text("PageRouteBuilder"),
            onPressed: () {
              Navigator.of(context).pushReplacement(PageRouteBuilder(
                pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) => MemoryTest(),
              ));
            },
          ),
          OutlinedButton(
            child: Text("PageRouteBuilder2"),
            onPressed: () {
              Navigator.of(context).pushReplacement(PageRouteBuilder(
                pageBuilder: _foo,
              ));
            },
          ),
          OutlinedButton(
            child: Text("CPageRoute"),
            onPressed: () {
              Navigator.of(context).pushReplacement(CPageRoute());
            },
          ),
          OutlinedButton(
            child: Text("CPageRouteBuilder"),
            onPressed: () {
              Navigator.of(context).pushReplacement(CPageRouteBuilder());
            },
          ),
        ],
      ),
    );
  }
}

class CTransitionRoute extends TransitionRoute {
  @override
  Iterable<OverlayEntry> createOverlayEntries() {
    return [OverlayEntry(builder: (_) => MemoryTest())];
  }

  @override
  bool get opaque => true;

  @override
  Duration get transitionDuration => const Duration(milliseconds: 300);
}

class CModalRoute extends ModalRoute {
  @override
  Color? get barrierColor => null;

  @override
  bool get barrierDismissible => false;

  @override
  String? get barrierLabel => '';

  @override
  Widget buildPage(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
    return MemoryTest();
  }

  @override
  bool get maintainState => true;

  @override
  bool get opaque => true;

  @override
  Duration get transitionDuration => const Duration(milliseconds: 300);
}

class CPageRoute extends PageRoute {
  @override
  Color? get barrierColor => null;

  @override
  String? get barrierLabel => '';

  @override
  Widget buildPage(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
    return MemoryTest();
  }

  @override
  bool get maintainState => true;

  @override
  Duration get transitionDuration => const Duration(milliseconds: 300);

}

class CPageRouteBuilder extends PageRouteBuilder {
  CPageRouteBuilder() : super(pageBuilder: _foo);

  static Widget _foo(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) => MemoryTest();
}

class MyBigObject {
  final List<int> ints = List<int>.filled(10000000, 1);
}
```

**Comment by jacob314** [comment]
Fyi @mraleph: is it expected that 
```dart
 onPressed: () {
              Navigator.of(context).pushReplacement(PageRouteBuilder(
                pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) => MemoryTest(),
              ));
            },
          ),
```
captures the `this` object of the surrounding `MemoryTest` class? @goderbauer's test makes it look like that is the case.
          
I believe there is a memory leak in the routing code for both the `"PageRouteBuilder"` and `"PageRouteBuilder2"` case but for the `"PageRouteBuilder"` case, the memory leak is much more noticeable.

**Comment by dnfield** [comment]
@mraleph @rmacnak-google - Goderbauer and I were also seeing strange things in the retain paths when trying to analyze this in the allocation profile dumps. Things that we're clearly seeing get set to null are not getting set to null. 

I'll try to tinker with getting a smaller repro of this, especially if it looks like this is related to tearoffs...

**Comment by dnfield** [comment]
s/tearoffs/closures. 

Also of note, this behavior happens in both AOT and JIT

**Comment by dnfield** [comment]
I've bisected this to #65528, which is unfortunately a fairly large patch.

Going to take a look through the changes to router/navigator related classes in there, which hopefully has some clue.

**Comment by mraleph** [comment]
Dart VM uses linked representation for closure contexts, in which parent contexts (representing parent scopes) are shared between sibling closures. So if you have one closure in the method which captures `this` so do *all* of them. Specifically in this example: 

```
          OutlinedButton(
            child: Text("PageRouteBuilder2"),
            onPressed: () {  // (*)
              Navigator.of(context).pushReplacement(PageRouteBuilder(
                pageBuilder: /* this. */_foo,  // (**)
              ));
            },
          ),
```

Closure marked with `*` captures `this` because it needs it to be able to create a tear-off `_foo` marked as `(**)`. Consequently all other closures capture `this` as well. See https://mrale.ph/blog/2012/09/23/grokking-v8-closures-for-fun.html (it gives some pictures for V8 representation of closures - Dart VM's is more or less the same and comes with similar problems).

We would like to try and fix this (upstream issue https://github.com/dart-lang/sdk/issues/36983), but so far we have not seen enough motivating cases do drive a huge re-engineering in this area. Such re-engineering might also come with a memory/code size/performance trade-off (if you don't share parent contexts each closure context becomes larger).

**Comment by dnfield** [comment]
I've narrowed the problem down to something in `lib/src/widgets/framework.dart`, but I'm not sure what more specifically yet.

**Comment by dnfield** [comment]
- This bug exists if `MemoryTest` is a `StatelessWidget` since at least 1.0. I'm not inclined to continue bisecting past that.
- This bug was introduced if `MemoryTest` is a `StatefulWidget` since #65528, but it's not clear to me which part(s) of that change introduced the problem, except that they live somewhere in `framework.dart`.

**Comment by mraleph** [comment]
I have tried to understand why original report leaks, but I am finding our memory tooling severely broken to the point where it is unusable for debugging this issue. Dev Tools don't even seem to have any sort of retaining paths functionality and Observatory is crashing the tab if I try to manually click through incomming references. @jacob314 is there some sort of issue tracking UX improvements for heap snapshot navigation?

**Comment by mraleph** [comment]
I have spent sometime looking at this, the leak is due to `context` (which is an `Element` representing previous version of the screen) being retained by inner `builder` closure - so you get a chain of `MemoryTest` objects formed through that:

```dart
  @override
  Widget build(BuildContext context) {
    return OutlinedButton(
      child: Text("CLICK"),
      onPressed: () {
        Navigator.of(context).pushReplacement(MaterialPageRoute(
          builder: (_) => MemoryTest(),  // <- this captures [context] even though it does not need it
        ));
      },
    );
  }
```

I don't think inner closure actually needs to capture `context` so we could fix this in the Dart VM. 

However this does not change the fact that you will still be able to accidentally capture `context` and thus leak previous "screens".

The way I approached this was to [build a converter](https://dart-review.googlesource.com/c/sdk/+/194065) from Observatory snapshots to V8 heap snapshots and then used Chrome Dev Tools to navigate around the snapshots. (Also discovered that we have [an issue](https://github.com/dart-lang/sdk/issues/45599) with field names when using Observatory with AOT builds). 

@dnfield NNBD migration has removed some `null`ing out in `StatefulElement.unmount` which used to look like this: 

```dart
@override
  void unmount() {
    // ...
    _state._element = null;
    _state = null;
  }
``` 

I would not be surprised that this is the change that alleviates memory leak.

**Comment by goderbauer** [comment]
@mraleph Thanks for looking into this!

> I don't think inner closure actually needs to capture context so we could fix this in the Dart VM.

Yes, the inner closure does not need the context. Can we fix this in the dart vm? Is there an issue for this?

> However this does not change the fact that you will still be able to accidentally capture context and thus leak previous "screens".

True, this should be rare, though. The builder closure is actually given a local BuildContext (the "_" expands to "BuildContext context") of you need one in there.

**Comment by mraleph** [comment]
> Yes, the inner closure does not need the context. Can we fix this in the dart vm? Is there an issue for this?

I will either fix this or file an issue today. 

> True, this should be rare, though. The builder closure is actually given a local BuildContext (the "_" expands to "BuildContext context") if you need one in there.

My concern was more about the code like this:

```dart
 @override
  Widget build(BuildContext context) {
    final something = ...;
    return OutlinedButton(
      child: Text("CLICK"),
      onPressed: () {
        Navigator.of(context).pushReplacement(MaterialPageRoute(
          builder: (_) => MemoryTest(something), 
        ));
      },
    );
  }
```

This will still accidentally capture `context` (because outer closure captures it) because inner closure captures something else from the same scope.

And fixing this is a major undertaking (with unclear cost / benefit balance) as explained in one of my other comments.

**Comment by goderbauer** [comment]
Oh, I see. That pattern is actually pretty common as well...

**Comment by jacob314** [comment]
For Flutter code, I expect the cost-benefit is there as many build methods contain multiple closures. We could generate some stats on how many g3 build methods match this pattern.
There were some memory leaks in g3 applications that I couldn't explain that follow this pattern as removing captured variables fixed issues in ways that I couldn't justify based on my incomplete mental model of what Dart captures.

While V8 has the issue @mraleph mentioned, I don't think Dart2JS will as it uses objects rather than functions to represent Dart closures. DDC (web debug builds) will have the issue as it uses JS functions.

Here is the DevTools issue for retained path display which I completely agree is a crucial feature for memory leak debugging.
https://github.com/flutter/devtools/issues/2428
Fyi @terrylucas

**Comment by esDotDev** [comment]
fwiw, I created this benchmark in the first place to measure the realworld impact of using things like `const EdgeInsets` vs `new EdgeInsets` across the lifetime of a long-lived app, thinking that it probably had next to no real impact because the GC would clean them up very quickly and they were very small allocations.

I didn't get past the first step of measuring the size of EdgeInsets in memory, and testing basic garbage collection, but the realworld version of this is just a regular app, with a whole bunch of non-const instances in every view. 

Regarding the inner context `_`, I'm not totally following the low-level details, but as end user, we rarely use this inner `BuildContext`, and almost always use the outer one when fetching dependencies or looking up inherited widgets. Really the only time we use the inner context here is `Builder` when we explicitly want one.

Regarding closures in general, we abuse the heck out of them, one of the defining features of dart is how aggressive you can be with closures and not have leaks, and boy do we go to town with it in Flutter :D

**Comment by dnfield** [comment]
@mraleph I was looking at that nulling out of `_state`, but adding it back didn't seem to resolve the issue.

**Comment by goderbauer** [comment]
(Presumably, above @dnfield is talking about a version where MemoryTest is a StatefulWidget, this post is about the originl problem where it is a StatelessWidget)

My current understanding is that the `builder` closure is retaining the `context` `BuildContext` object, which is really a `StatelessElement`. This stateless element retains the `MemoryTest` widget via its `_widget` property and that Widget retains the `MyBigObject` via its `bigObj` property. Based on that, I thought that we can somewhat mitigate the memory leak by nulling out the `_widget` property when the element is removed from the tree as that should make the MemoryTest widget of the previous screen and its MyBigObject gc-able. However, in a quick test where I null out _widget in StatelessElement.unmount (and verify that it gets called) all `MyBigObject`s are still retained....

This is the retaining path I am seeing (notice how `_widget` is null now):

![Screen Shot 2021-04-06 at 11 15 36 AM](https://user-images.githubusercontent.com/1227763/113759065-82ae8380-96c9-11eb-86b8-7ff987097355.png)

My limited understanding from that retaining path is that the `builder` closure is actually retaining more than just the BuildContext/StatelessElement `context`. It is also retaining `this`, which is the `MemoryTest` widget itself. Is that correct? @mraleph will the fix you talked about also address that or just the capture of `context`? (Presumably, the latter would not fix the memory leak?)

Another question about the retaining path above: Does somebody know what the "offset 3" (line 3) means?

**Comment by dnfield** [comment]
If we avoid capturing the `context` (i.e. the `BuildContext`), the leak is mitigated:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MemoryTest(),
  ));
}

class MemoryTest extends StatelessWidget {
  final List<EdgeInsets> insets = List.generate(
    1000000,
    (index) => EdgeInsets.all(0),
  );
  @override
  Widget build(BuildContext context) {
    final navigator = Navigator.of(context);
    return OutlinedButton(
      child: Text("CLICK"),
      onPressed: () {
        navigator.pushReplacement(MaterialPageRoute(
          builder: (_) => MemoryTest(),
        ));
      },
    );
  }
}
```

**Comment by goderbauer** [comment]
@rmacnak-google Was able to answer my "offset 3" question. It's the first element (at index 0) in the list I expanded in the screenshot above: offset 0 = length, offset 1 = parent, offset 2 = element 0, offset 3 = element 1, ...

**Comment by dnfield** [comment]
I think a good chunk of our problem here is that as a developer, it's very easy to not think about how `BuildContext` is an element, and if you do _anything_ to keep it alive longer than necessary bad things happen :\

**Comment by Hixie** [comment]
> I think a good chunk of our problem here is that as a developer, it's very easy to not think about how `BuildContext` is an element, and if you do _anything_ to keep it alive longer than necessary bad things happen :\

Yeah that's sort of working as intended (BuildContext was meant to hide Elements to discourage tree manipulation) but obviously it does have downsides...

**Comment by mraleph** [comment]
@goderbauer are you running your version of the test (from https://github.com/flutter/flutter/issues/79605#issuecomment-813743380) or the one from the very first comment (from https://github.com/flutter/flutter/issues/79605#issue-848917579)? The one in the very first comment does not capture `this` (at least in `profile` mode - but I can't fathom that `debug` would be different in that regard).

**Comment by esDotDev** [comment]
fwiw, the reason we tend to use the outer context is just because it often gets annoying naming the inner context, so it's just more convenient (faster to write) to do something like this.

As I understand it, this would cause the bug:
```
Widget build(BuildContext context){
  return LayoutBuilder(builder: (_, constraints, __){
        User user = context.watch(); // Leaky
   });
}
```
While this either of these would not?
```
Widget build(_){
  return LayoutBuilder(builder: (context, constraints, __){
        User user = context.watch(); // No leaks
   });
}
...
Widget build(BuildContext context){
  User user = context.watch(); // No leaks
  return LayoutBuilder(builder: (_, constraints, __){  
   });
}
```
That's pretty sneaky!

**Comment by goderbauer** [comment]
@mraleph Oh you're right. I was running the wrong example which did include a closure that required capturing `this`. I had't internalized yet that the pure presence of a closure that needs `this` causes `this` to be captured by all other closures as well (even if they are kinda unrelated and just siblings to each other)...

**Comment by dnfield** [comment]
@esDotDev  - yes, using the "outter" context in any closure can potentially lead to this (although it may not).

What's not 100% clear to me is what the retain path ends up looking like. I can't seem to come up with a more minimal example (e.g. one that doesn't use package:flutter). Dart is able to reclaim simple examples of circular orphaned memory usage.

It'd be nice to:

- Have a lint to warn users not to do this
- Have more help from the Dart memory debugging tools to identify when something like this happens

**Comment by goderbauer** [comment]
Now my original idea of nulling out Element.widget actually works in mitigating the memory leak somewhat for the case from the original message of the bug: https://github.com/flutter/flutter/commit/0a3e2ac6a2a4ed2678a12f08724d0cd5b2289342

With this, the widget and all things retained by it (including the large object in the example) are GCed. However, the Element itself (and some other things like the Route) are still retained and leak. Why the Route is retained deserves a separate investigation. 

I haven't checked the StatefulWidget case...

**Comment by goderbauer** [comment]
@dnfield Nulling out the state (https://github.com/goderbauer/flutter/commit/8449f48fe57094d6292d2f9a0da1c28e07a12885) does actually seem to work for me in mitigating the memory leak if I change the original example to use a StatefulWIdget instead of a StatelessWidget.

**Comment by dnfield** [comment]
I thought I had tried that but it's possible that I had some combination of factors involved in this issue incorrect :)

**Comment by dnfield** [comment]
@jacob314 - would your efforts around tracking whether disposed objects get GC'd have caught this?

**Comment by esDotDev** [comment]
fwiw, even this "best practice" approach, of defining a closure to accept context in a stateless widget seems to cause the leak:
`onPressed: () => _handleClick(context),`

**Comment by dnfield** [comment]
Correct - passing a `BuildContext` to _anything_ outside of a `build` method (a closure, another method, another object) can potentially cause this kind of problem.

In some cases, using `DisposableBuildContext` can help (you create that in a `State` and dispose of it in the state's dispose, and it prevents other callers from retaining it beyond necessary). But that doesn't always make sense.

**Comment by dnfield** [comment]
Also, I hope it's clear that I'm not thinking this is ideal.

There should be things that can be done to help mitigate this, or at least detect it and warn about it if it happens.

**Comment by esDotDev** [comment]
I'm certainly not getting that impression! 

The `onPressed: () => _handleClick(context)` is pretty worrying though, as I don't even think there is another way to support this common use case when you need Context in a StatelessWidget?

Even creating a local named method seems to cause it:  
```
Widget build(BuildContext context) {
    void handleClick() => this._handleClick(context);
    Widget content = OutlinedButton(child: Text("CLICK"), onPressed: () => handleClick());
    ...
}
```

If this does end up being some fact of life, one way it could be approached is to add `.context` onto StatelessWidget, and do a big announcement "We added this property, and here's why. It also comes with this linting rule.".

**Comment by jacob314** [comment]
@dnfield these are exactly the sorts of cases my leak detection tool detects. My leak tool does best for the leaking Element and State objects. For the StatelessWidget case, my tool can't detect the issue as there is not an explicit StatelessWidget lifecycle so there is no way to accurately know that a StatelessWidget should no longer be referenced. It wouldn't be as robust as for the true disposed object leak cases but we could do something for the StatelessWidget case as well by tracking StatelessWidget objects that were once attached to an Element but are no longer attached to an Element that have not been GCed.

**Comment by jacob314** [comment]
https://github.com/dart-lang/linter/issues/2206 Is another related lint for using BuildContext after an async gap. A prototype of that lint has been showing promising results although has a lot of false positives.

**Comment by dnfield** [comment]
Filed https://github.com/flutter/flutter/issues/79906

**Comment by z870248707** [comment]
Not sure if it is relative, I found keys of `_listeners` in `RouteObserver` will never be released.
In `unsubscribe`, I think we should remove the key of `_listeners` when `subscribers` is empty.

```
class RouteObserver<R extends Route<dynamic>> extends NavigatorObserver {
  final Map<R, Set<RouteAware>> _listeners = <R, Set<RouteAware>>{};

  /// Subscribe [routeAware] to be informed about changes to [route].
  ///
  /// Going forward, [routeAware] will be informed about qualifying changes
  /// to [route], e.g. when [route] is covered by another route or when [route]
  /// is popped off the [Navigator] stack.
  void subscribe(RouteAware routeAware, R route) {
    assert(routeAware != null);
    assert(route != null);
    final Set<RouteAware> subscribers = _listeners.putIfAbsent(route, () => <RouteAware>{});
    if (subscribers.add(routeAware)) {
      routeAware.didPush();
    }
  }

  /// Unsubscribe [routeAware].
  ///
  /// [routeAware] is no longer informed about changes to its route. If the given argument was
  /// subscribed to multiple types, this will unregister it (once) from each type.
  void unsubscribe(RouteAware routeAware) {
    assert(routeAware != null);
    for (final R route in _listeners.keys) {
      final Set<RouteAware>? subscribers = _listeners[route];
      subscribers?.remove(routeAware);
    }
  }
```

**Comment by givinkwon** [comment]
@dnfield
I don't think this problem has been solved yet...

Can I know the progress of this problem in detail?

Using "if (mounted)" or "final localVar = something (context)" produces boilerplate code and creates a new memory leak. As a result, developers are less productive.

**Comment by dam-ease** [comment]
This issue still persists on some platforms. I am able to reproduce this on only `macos` and `android`. Memory usage keeps increasing.
macOS, Android - Reproducible
Chrome Web, iOS - Non-reproducible

[Code Sample](https://github.com/flutter/flutter/issues/79605#issue-848917579)

<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (6 days ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • TECNO LC6a (mobile)        • 044882598G014637                     • android-arm    • Android 9 (API 28)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.10.0 on channel stable at /Users/dammya/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • TECNO LC6a (mobile)        • 044882598G014637                     • android-arm    • Android
      9 (API 28)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android
      11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```
</details>

**Comment by jacob314** [comment]
Fyi @polina-c. Would be good to verify that the leak_tracker package makes it easy to write memory leak tracking tests to catch this issue.

**Comment by polina-c** [comment]
Yes, this is the plan: https://github.com/flutter/devtools/issues/3951

**Comment by alienfractal** [comment]
I was working a making a game with flutter when half way down the road the memory consumption puzzled me and ended up on this thread. 
I thought canvas kit was to blame but ran my simple hello world app on Flame engine, the app is now a dark screen and let it idle, and memory consumption rises slowly on time for no good reason at all. 

I launched the app outside of VS code to be sure it was not a problem with the VS

`flutter run -d chrome --web-renderer html --profile`

![image](https://github.com/flutter/flutter/assets/8407437/ab5a2872-0eb0-4b1d-89e8-09c2c8cdd09d)

**Flutter doctor output :** 

√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3007], locale en-GB)
    • Flutter version 3.16.9 on channel stable at C:\lien\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (11 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\lien\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\lien\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 121.0.2277.98

[√] Network resources
    • All expected network resources are available.

Sample code : 

import 'package:flame/flame.dart';
import 'package:flame/game.dart';

void main()  {
  final game = FlameGame();
  runApp(GameWidget(game: game));
}

**Comment by Hixie** [comment]
@alienfractal As I understand it this issue is exclusively about a design decision that causes leaks in the Dart VM; when compiled to JS any similar leaks would be issues with the browser's VM, not Dart's.

**Comment by jacob314** [comment]
I agree that this is about a design decision that causes leaks in the Dart VM. However, it is a design decision made by most VMs. For example, if you were writing JS with the same pattern you would get a leak in V8. The only reason Dart doesn't get a leak when compiling to JS is because of quirks in how Dart closures get compiled to JS. I'm excited to see whether @polina-c's leak detection tooling is able to make it easier to catch and fix leaks like this.

**Comment by Hixie** [comment]
To be clear I didn't mean that statement to be a criticism of the Dart VM decision.

**Comment by iapicca** [comment]
does not occur on web-wasm

- `flutter build web --wasm`
- `dart pub global activate dhttpd`
- `dhttpd --path build/web/`
- `open http://localhost:8080/`
- click `click` as much as you like

<details>
  <summary>code sample</summary>
  
  ```dart
  
  import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Material(child: MemoryTest())));

class MemoryTest extends StatelessWidget {
  // ignore: unused_field, prefer_const_constructors
  final _insets = [for (var i = 0; i < 1000000; i++) EdgeInsets.all(0)];

  MemoryTest({super.key});
  @override
  Widget build(context) => Center(
        child: OutlinedButton(
          child: const Text('click'),
          onPressed: () => Navigator.of(context).pushReplacement(
            MaterialPageRoute(
              builder: (context) => MemoryTest(),
            ),
          ),
        ),
      );
}

  ```

</details>

<details>
  <summary>doctor</summary>
  
  ```console
  [✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (9 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

• No issues found!
  ```

</details>

<details>
  <summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/6b22a461-45ca-4e9b-ad78-eeb3b68a8faa)


</details>
