### ISSUE TITLE
App crash when doing startImageStream

### ISSUE THREAD

**Issue by wahyu-handayani** [flutter/flutter#80488]
I am using package of camera: ^0.5.8+5, when I debugging in Xiaomi device (android 10) it throws error like this, but when I debugging in Samsung device it works fine
```
E/libc    ( 3543): Access denied finding property "persist.vendor.camera.privapp.list"
W/cognitionpython( 3543): type=1400 audit(0.0:706377): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=27200 scontext=u:r:untrusted_app:s0:c43,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
W/Gralloc3( 3543): allocator 3.x is not supported
W/BpBinder( 3543): Slow Binder: BpBinder transact took 5273ms, interface=android.hardware.camera2.ICameraDeviceUser, code=14 oneway=false
E/CameraCaptureSession( 3543): Session 1: Failed to create capture session; configuration failed
E/AndroidRuntime( 3543): FATAL EXCEPTION: pool-6-thread-1
E/AndroidRuntime( 3543): Process: com.example.facerecognitionpython, PID: 3543
E/AndroidRuntime( 3543): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-6-thread-1
E/AndroidRuntime( 3543): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1150)
E/AndroidRuntime( 3543): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:782)
E/AndroidRuntime( 3543): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime( 3543): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:363)
E/AndroidRuntime( 3543): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:168)
E/AndroidRuntime( 3543): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:221)
E/AndroidRuntime( 3543): 	at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:49)
E/AndroidRuntime( 3543): 	at io.flutter.plugins.camera.Camera$4.onConfigureFailed(Camera.java:329)
E/AndroidRuntime( 3543): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigureFailed$1$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:64)
E/AndroidRuntime( 3543): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$gvbTsp9UPpKJAbdycdci_ZW5BeI.run(Unknown Source:4)
E/AndroidRuntime( 3543): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 3543): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 3543): 	at java.lang.Thread.run(Thread.java:919)
W/BpBinder( 3543): Slow Binder: BpBinder transact took 255ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false
I/flutter ( 3667): build dari home
4
I/flutter ( 3667): regis build
E/flutter ( 3667): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: CameraException(CameraAccess, CAMERA_ERROR (3): waitUntilIdle:1699: Camera 1: Error waiting to drain: Connection timed out (-110))
E/flutter ( 3667): #0      CameraController.startImageStream
package:camera/camera.dart:460
E/flutter ( 3667): <asynchronous suspension>
E/flutter ( 3667):
Lost connection to device.
```
is there a way to solve this?

**Comment by JagandeepBrar** [comment]
According to this issue: https://github.com/flutter/flutter/issues/54619, this bug should be fixed in a more recent version of the `camera` package.

**Comment by wahyu-handayani** [comment]
@JagandeepBrar I follow this issue https://github.com/flutter/flutter/issues/72961#issuecomment-751462864 
I change my current version of camera package from 0.5.8+5 into 0.6.4+5, but I still get the log error and the apps crash in Xiaomi android 10

**Comment by TahaTesser** [comment]
Hi @wahyu-handayani 
Can you please [official sample](https://pub.dev/packages/camera/example) with LATEST `camera: ^0.8.1`

If the problem persists, Can you please provide your `flutter doctor -v` and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by wahyu-handayani** [comment]
I will try it after upgrading my flutter sdk first and let you know the result as soon as possible

**Comment by wahyu-handayani** [comment]
I have tried using 0.8.1 version, at first the apps can run well, but whenever I click back button and click the button again to do ```startImageStream```, I get this exception
```
Exception has occurred.
CameraException (CameraException(CameraAccess, CAMERA_ERROR (3): waitUntilIdle:1699: Camera 1: Error waiting to drain: Connection timed out (-110)))
```
and here is the full log
```
Restarted application in 1,253ms.
I/flutter (17793): build dari home
I/flutter (17793): build dari scan}
I/Camera  (17793): [FPS Range Available] is:[15, 15]
I/Camera  (17793): [FPS Range Available] is:[8, 30]
I/Camera  (17793): [FPS Range Available] is:[30, 30]
I/Camera  (17793): [FPS Range] is:[8, 30]
W/Camera  (17793): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
E/libc    (17793): Access denied finding property "persist.vendor.camera.privapp.list"
W/cognitionpython(17793): type=1400 audit(0.0:730819): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=27200 scontext=u:r:untrusted_app:s0:c54,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
W/BpBinder(17793): Slow Binder: BpBinder transact took 261ms, interface=android.hardware.camera2.ICameraDeviceUser, code=14 oneway=false
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/System  (17793): A resource failed to call release.
I/chatty  (17793): uid=10310(com.example.facerecognitionpython) FinalizerDaemon identical 2 lines
W/System  (17793): A resource failed to call release.
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/BpBinder(17793): Slow Binder: BpBinder transact took 205ms, interface=android.hardware.camera2.ICameraDeviceUser, code=14 oneway=false
D/ViewRootImpl(17793): [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=1603196455, downTime=1603196455, deviceId=-1, source=0x101, displayId=-1 }
W/InputTransport(17793): Slow Input: 210ms so far, channel 'ClientState{92e117e uid=10310 pid=17793 displayId=0} (server)' publisher ~ publishKeyEvent: seq=3, deviceId=-1, source=0x101, action=0x0, flags=0x8, keyCode=4, scanCode=0, metaState=0x0, repeatCount=0,downTime=1603196455000000, eventTime=1603196455000000
D/ViewRootImpl(17793): [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=1603196455, downTime=1603196455, deviceId=-1, source=0x101, displayId=-1 }
W/InputTransport(17793): Slow Input: 212ms so far, channel 'ClientState{92e117e uid=10310 pid=17793 displayId=0} (server)' publisher ~ publishKeyEvent: seq=4, deviceId=-1, source=0x101, action=0x1, flags=0x8, keyCode=4, scanCode=0, metaState=0x0, repeatCount=0,downTime=1603196455000000, eventTime=1603196455000000
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/System  (17793): A resource failed to call release.
W/System  (17793): A resource failed to call release.
W/cognitionpytho(17793): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
I/flutter (17793): build dari scan}
I/Camera  (17793): [FPS Range Available] is:[15, 15]
I/Camera  (17793): [FPS Range Available] is:[8, 30]
I/Camera  (17793): [FPS Range Available] is:[30, 30]
I/Camera  (17793): [FPS Range] is:[8, 30]
W/Camera  (17793): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
E/libc    (17793): Access denied finding property "persist.vendor.camera.privapp.list"
W/cognitionpython(17793): type=1400 audit(0.0:730971): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=27200 scontext=u:r:untrusted_app:s0:c54,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
W/BpBinder(17793): Slow Binder: BpBinder transact took 5276ms, interface=android.hardware.camera2.ICameraDeviceUser, code=14 oneway=false
E/CameraCaptureSession(17793): Session 1: Failed to create capture session; configuration failed
W/BpBinder(17793): Slow Binder: BpBinder transact took 254ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false
E/flutter (17793): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: CameraException(CameraAccess, CAMERA_ERROR (3): waitUntilIdle:1699: Camera 1: Error waiting to drain: Connection timed out (-110))
[38;5;244mE/flutter (17793): #0      CameraController.startImageStream[39;49m
E/flutter (17793): <asynchronous suspension>
E/flutter (17793):
```

**Comment by TahaTesser** [comment]
Hi @JagandeepBrar 
Can you please provide your a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and complete `flutter run --verbose` logs running the minimal code sample? 
Thank you

**Comment by JagandeepBrar** [comment]
> Hi @JagandeepBrar 
> 
> Can you please provide your a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and complete `flutter run --verbose` logs running the minimal code sample? 
> 
> Thank you

I believe you mentioned the wrong person, and meant to mention @wahyu-handayani

**Comment by wahyu-handayani** [comment]
@TahaTesser so sorry for taking long time to reply, here is the sample code for FirstScreen.dart
```
@override
  void initState() {
    super.initState();
    sendData();
  }
sendData() async {
    try {
      List<CameraDescription> cameras = await availableCameras();
      cameraDescription = cameras.firstWhere(
        (CameraDescription camera) =>
            camera.lensDirection == CameraLensDirection.front,
      );
    } catch (err) {
      print("error:${err.toString()}");
    }
  }
```
for FirstScreen I just have a button that navigate user to second page with bring ```cameraDescription```
here is for SecondScreen.dart
```
@override
  void initState() {
    super.initState();
    initCamera();
  }

initCamera() async {
    start = next.begin(widget.cameraDescription);
    await start;
    val.value = Model(
        camerastart: true,
        namaUser: null,
        url: null,
        loading: false,
        stopStreaming: false,
        faceDetectedNotif: null,
        faceDetectedXNotif: null,
        imageSizeNotif: null);
    frameUser();
  }

Future begin(CameraDescription cameraDescription) async {
    this.cameraDescription = cameraDescription;
    this.cameraController = CameraController(
      this.cameraDescription,
      ResolutionPreset.high,
      enableAudio: false,
    );

    this._cameraRotation = rotationIntToImageRotation(
      this._cameraDescription.sensorOrientation,
    );
    return cameraController.initialize();
  }
```

**Comment by TahaTesser** [comment]
@wahyu-handayani 
The code snippet you provided is incomplete

Can you please provide your a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and complete `flutter run --verbose` logs running the minimal code sample? 
Thank you

**Comment by wahyu-handayani** [comment]
@TahaTesser I can not send you ```flutter run --verbose``` cause Xiaomi device is not in me now, but I can send you the log by using another device (Samsung), (app crash happens in Xiaomi), I will send it when Xiaomi device is in me

**Comment by wahyu-handayani** [comment]
@TahaTesser, Hi.. I am so sorry for taking long to reply your message, for now I Xiaomi device is still not in me, so I didn't able to send the log until now. For now, let me close this question and open again when Xiaomi is in me

**Comment by tigrenok00** [comment]
I have this reproducing with Xiaomi Mi10 device:

 +15 ms] I/CameraManagerGlobal(31966): Connecting to camera service
[   +2 ms] I/FeatureParser(31966): can't find apollo.xml in assets/device_features/,it may be in /vendor/etc/device_features
[   +7 ms] W/CameraManagerGlobal(31966): [soar.cts] ignore the status update of camera: 2
[        ] W/CameraManagerGlobal(31966): [soar.cts] ignore the status update of camera: 3
[        ] W/CameraManagerGlobal(31966): [soar.cts] ignore the status update of camera: 4
[        ] W/CameraManagerGlobal(31966): [soar.cts] ignore the status update of camera: 5
[        ] W/CameraManagerGlobal(31966): [soar.cts] ignore the status update of camera: 6
[        ] W/CameraManagerGlobal(31966): [soar.cts] ignore the status update of camera: 7
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 2
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 3
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 4
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 5
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 6
[        ] I/CameraMetadataJV(31966): setAppNameAndSensorId all [com.ludashi:0,add,9248x6944,33,false]
[        ] I/CameraMetadataJV(31966): setAppNameAndSensorId all [com.ludashi:1,add,5184x3880,33,false]
[        ] I/CameraMetadataJV(31966): setAppNameAndSensorId all [com.antutu:0,ssize,9248x6944,0,false]
[        ] I/CameraMetadataJV(31966): setAppNameAndSensorId all [com.antutu:1,ssize,5184x3880,0,false]
[        ] I/CameraMetadataJV(31966): setAppNameAndSensorId all [com.tencent.mobileqq:1,limit,1920x1080,0,false]
[  +89 ms] I/Camera  (31966): [FPS Range Available] is:[7, 7]
[        ] I/Camera  (31966): [FPS Range Available] is:[12, 12]
[        ] I/Camera  (31966): [FPS Range Available] is:[15, 15]
[        ] I/Camera  (31966): [FPS Range Available] is:[24, 24]
[        ] I/Camera  (31966): [FPS Range Available] is:[25, 25]
[        ] I/Camera  (31966): [FPS Range Available] is:[12, 30]
[        ] I/Camera  (31966): [FPS Range Available] is:[30, 30]
[        ] I/Camera  (31966): [FPS Range] is:[12, 30]
[  +15 ms] E/libc    (31966): Access denied finding property "persist.vendor.camera.privapp.list"
[   +1 ms] W/ce.smartdotscan(31966): type=1400 audit(0.0:44760521): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=17996
scontext=u:r:untrusted_app_27:s0:c52,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.evigence.smartdotscan
[  +12 ms] E/CameraManagerGlobal(31966): Camera 4 is not available. Ignore physical camera status change
[   +6 ms] E/CameraManagerGlobal(31966): Camera 5 is not available. Ignore physical camera status change
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 2
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 3
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 4
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 5
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 6
[ +560 ms] I/Choreographer(31966): Skipped 49 frames!  The application may be doing too much work on its main thread.
[        ] W/Looper  (31966): PerfMonitor doFrame : time=0ms vsyncFrame=34142399 latency=346ms procState=2 historyMsgCount=1
[ +258 ms] E/CameraCaptureSession(31966): Session 1: Exception while stopping repeating: 
[        ] E/CameraCaptureSession(31966): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
[        ] E/CameraCaptureSession(31966):       at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2328)
[        ] E/CameraCaptureSession(31966):       at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1277)
[        ] E/CameraCaptureSession(31966):       at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
[        ] E/CameraCaptureSession(31966):       at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1171)
[        ] E/CameraCaptureSession(31966):       at io.flutter.plugins.camera.Camera.close(Camera.java:1177)
[        ] E/CameraCaptureSession(31966):       at io.flutter.plugins.camera.Camera$1.onError(Camera.java:252)
[        ] E/CameraCaptureSession(31966):       at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1726)
[        ] E/CameraCaptureSession(31966):       at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
[        ] E/CameraCaptureSession(31966):       at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
[        ] E/CameraCaptureSession(31966):       at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
[        ] E/CameraCaptureSession(31966):       at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
[        ] E/CameraCaptureSession(31966):       at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
[        ] E/CameraCaptureSession(31966):       at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/CameraCaptureSession(31966):       at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/CameraCaptureSession(31966):       at android.os.Looper.loop(Looper.java:236)
[        ] E/CameraCaptureSession(31966):       at android.app.ActivityThread.main(ActivityThread.java:8057)
[        ] E/CameraCaptureSession(31966):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/CameraCaptureSession(31966):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
[        ] E/CameraCaptureSession(31966):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
[ +783 ms] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 2
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 3
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 4
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 5
[        ] W/CameraManagerGlobal(31966): ignore the torch status update of camera: 6
[        ] E/CameraManagerGlobal(31966): Camera 4 is not available. Ignore physical camera status change
[        ] W/BpBinder(31966): PerfMonitor binderTransact :  time=792ms interface=android.hardware.camera2.ICameraDeviceUser code=1
[        ] E/CameraManagerGlobal(31966): Camera 5 is not available. Ignore physical camera status change

**Comment by tigrenok00** [comment]
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (8 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (4 available)
    • M2007J3SY (mobile)          • e94cfa1a      • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!

**Comment by TahaTesser** [comment]
@tigrenok00
Please file a new issue and follow the template, provide all the details
