### ISSUE TITLE
[web] Use ShadowDOM slots to render HtmlElementViews

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#80524]
This is an umbrella task/progress report of this design doc: [Using `slot` to embed web Platform Views](https://flutter.dev/go/web-slot-content).

A partial breakdown of the tasks:

- [x] Wrap contents of scene in a ShadowDOM.
- [x] ~Add flag to opt-into the new rendering mechanism. **DO WE WANT THIS?? NO**~
- [x] Render views into the DOM in an unified way (this code should be identical both for canvaskit and html backends, since we're rendering *outside* of the ShadowDOM.
  - [x] Render SLOT on canvaskit backend
  - [x] Render SLOT on html backend
- [x] Testing. [WIP PR](https://github.com/flutter/engine/pull/25747).

**Comment by ludwiktrammer** [comment]
The link to the design doc appears to be broken (resulting in 404).

**Comment by ditman** [comment]
@ludwiktrammer you're right, [this](https://github.com/flutter/website/pull/5638) needed to be merged for the link to work. Can you please try again?

**Comment by ludwiktrammer** [comment]
@ditman I can see it now, thanks!

**Comment by gib40f** [comment]
I did an upgrade and changed to channel master and tried with the noddy test app and it does appear to be fixed and the pdf document doesn't flicker and restart at the beginning.

**Comment by ditman** [comment]
@gib40f the code is still not in master, so you probably fixed something on your end (probably the page layout) :)

**Comment by ditman** [comment]
I've deployed the example app in #71888 with the fix I'm working on, and it looks much more stable! The youtube video is not reloading anymore!

https://dit-iframe-reload-example.web.app

**Comment by ditman** [comment]
### ❓ Question to anybody following: Would it be useful to have a flag to enable/disable the slot-base rendering of Platform Views?

Disable would mean to keep the current (buggy) version of the rendering, with the problems described in the design doc, and having to opt-in (at flutter build time) into the feature with something like:

`flutter build web --dart-define=FLUTTER_WEB_USE_SLOTS=true`

Since the current version is buggy, except for the simplest of cases, we were thinking on moving on with a direct fix (no need to opt-in).

We still don't foresee any major breakage with the new structure, unless your code is using 3rd party JS code to access the contents of your platform views.

What do you think?

**Comment by creativecreatorormaybenot** [comment]
> What do you think?

The upside is that in case it **does** break existing behavior, you would still have adjustment time / a way to use the old behavior.

On the flip side, I really cannot imagine an actual use case that would break by fixing the bugs. If there really are no side effects, it seems like it should be fine to just move to it.

Both of the workarounds I built over the past months, i.e. one for the HTML renderer and one for CanvasKit, should still continue to work with slots (one inserts an `<iframe>`  element that it speaks to using post message and the other one inserts a `<div>` element directly in the `<body>`).

**Comment by gib40f** [comment]
That is odd as I didn't change my example project but just upgraded and changed to master.

Here is my flutter doctor output if it helps explain:

flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.373, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-AU)
    • Flutter version 1.24.0-8.0.pre.373 at /Users/gib40f/software/flutter
    • Framework revision 8de72126e9 (5 months ago), 2020-11-26 07:48:03 +0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gib40f/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/gib40f/Library/Android/
    • ANDROID_SDK_ROOT = /Users/gib40f/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] Connected device (3 available)
    • CSIRO iPhone (mobile) • 638e74cd60e7896e9c788d66d65edac38130207a • ios            • iOS 12.5.2
    • Web Server (web)      • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome 90.0.4430.72

• No issues found!

Simon Gibson
Software Engineer | The Australian e-Health Research Centre
CSIRO Health and Biosecurity

T: +61 7 3253 3613 |  M: 044 976 8823
E: ***@***.*** | www.csiro.au | www.aehrc.com
Address: Level 5 - UQ Health Sciences Building 901/16, Royal Brisbane and Women's Hospital,  Herston   Qld  4029
________________________________

**Comment by ditman** [comment]
@gib40f I commented in the issue where you originally supplied your example app, and explained there why the issue was not manifesting. Please, see [this comment](https://github.com/flutter/flutter/issues/77369#issuecomment-822699232) (and let's keep commenting there if you want to tweak the repro app?).

**Comment by ditman** [comment]
@creativecreatorormaybenot I knew you had been actively working around the issue lately, and was concerned about your fixes specifically. Are you setup to fiddle with flutter/engine? If so, you might be able to clone my engine branch and build your apps with the newest code, and see how bad it is for them (if it's any bad at all!)

**Comment by peerwaya** [comment]
if there will be no breaking changes and this is already looking promising, I suggest we do a direct fix.

**Comment by creativecreatorormaybenot** [comment]
>Are you setup to fiddle with flutter/engine?

I have read through [the article](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) before, but I have not yet needed it. If you really think it is worth it, I am sure I can find some time on the weekend to set it up.  
Otherwise, I am fairly certain the current workaround is not going to break. The only potential issue I see right now is that it would actually go into fullscreen with the fix and then you are in fullscreen but also have another instance of the player that is not fullscreen on top. That said, if fullscreen does work with the fix (for JW Player), I can just remove the workaround and we are good to go :)

So I think the most interesting test that I could do is whether it works with JW Player fullscreen (and whether JW Player works at all with slots).

**Comment by ditman** [comment]
> So I think the most interesting test that I could do is whether it works with JW Player fullscreen (and whether JW Player works at all with slots).

@creativecreatorormaybenot  If you have some sample code for the JWPlayer, I can give it a quick test; I think this is easier for both of us that I test another sample app, than making you set up the engine development environment if you don't have it already!

**Comment by ditman** [comment]
> if there will be no breaking changes and this is already looking promising, I suggest we do a direct fix.

@peerwaya that's what we're leaning towards. The change should *not* be breaking, unless you needed to do some fancy code to access via JS the contents of your HtmlViewElement after it's been rendered.

**Comment by tneotia** [comment]
I've been using `IframeElement` in my package and I experience this same bug when I have a bunch of dropdowns that render on top of the iframe. As far as I can tell this fix only applies to `HtmlElementView`?

I haven't heard of this widget before and I thought `IframeElement` was the only way to show a "webview" on Web.

**Comment by ditman** [comment]
> I use `window.postMessage()` in Dart and `window.parent.postMessage()` to communicate between the HtmlElementView and Dart.

@tneotia it depends on how you are getting a reference to the `targetWindow` of your `postMessage` call? (see [this](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#syntax)) 

Are you doing some selectors that use `flt-platform-view` and shadowRoot (with --web-renderer html), or some selectors on iframe (with --web-renderer canvaskit), or are you keeping an instance of the IframeElement you're injecting so you can use it later in your flutter code?

> Will this functionality be broken with this change?

No, `postMessage` will continue working as normal. This change will change the DOM layout of Flutter apps, so if you have something like: 

```dart
final myWindow = document.querySelector('flt-platform-view').shadowRoot.querySelector('iframe').contentWindow
```

That selector will break (because the iframe now lives elsewhere in the DOM of the page)

**Comment by tneotia** [comment]
> it depends on how you are getting a reference to the `targetWindow` of your `postMessage` call?

If I understand correctly I'm simply using:

```dart
import 'dart:html' as html;

html.window.postMessage("my message", "*");
```

in Dart and in JS: 

```javascript
window.parent.postMessage("my message", "*");
```

I just use `window` hardcoded. I dont use anything to get the iframe's content window. I also don't use any selectors or shadowRoot, I entirely use `postMessage`. So I guess my package should be compatible with this change.

Apologies in case I'm misunderstanding, webviews in Flutter Web aren't really my forte and I need to read up on them a bit.

**Comment by ditman** [comment]
@tneotia yes, I'm pretty sure you should be all right with your code without any changes!

> Apologies in case I'm misunderstanding, webviews in Flutter Web aren't really my forte and I need to read up on them a bit.

In this case the technology you're using is purely web, so it doesn't have much to do with Flutter itself. Here's some reading materials about `postMessage` and its [Security concerns](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns), an [OWASP entry about Testing Web Messaging](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/11-Testing_Web_Messaging)), and the [HTML5 Security Cheat Sheet on Web Messaging](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#web-messaging) for some best practices!

**Comment by tneotia** [comment]
Thanks a lot for the clarification and links @ditman . I need to figure out how I can get rid of using `*` and instead use a specific target origin. At the moment I use the `viewId` string I generate for the `IframeElement` in my `postMessage` to make sure the data I am receiving/modifying is the data that I want, but using an exact target origin can improve the security further.

**Comment by ditman** [comment]
@creativecreatorormaybenot check this out:

https://dit-jwplayer-fullscreen.web.app

I've had some trouble with the API keys and setup of the jwplayer, I hope that link works for a while (I had to create an account)

**Comment by creativecreatorormaybenot** [comment]
Thanks so much for validating it @ditman! Here is a recording of it working perfectly (in case the demo stops working):

https://user-images.githubusercontent.com/19204050/115624932-dc7a9480-a2ea-11eb-8529-bd1a18cd0588.mp4

I am sorry for the player script part - I intended to include the JW Player we use for our web app (because it is in the public HTML file anyway), but I copied the wrong tag on accident. Glad you were able to get it working anyway 🙏

**Comment by tihhmachado** [comment]
Hello everyone,

I am experiencing a problem in the web flutter when using an iframe in an HTMLElementView. as you can see in the video below, when opening the drawer menu it is not possible to close it by clicking on a area if it is the same area that the iframe occupies.  I found an answer in a comment on this issue https://github.com/rodydavis/easy_web_view/issues/7#issuecomment-752326934 that seemed to work for some, but not for me. When changing the value of the pointer-events attribute to the cited tag I can't interact with the page in the iframe. @ditman, it was not clear to me whether the fix are developing will also fix this problem. 


https://user-images.githubusercontent.com/39199884/115894967-43ee2c80-a430-11eb-83a3-ef23dcab7e90.mp4

**Comment by ditman** [comment]
@tihmachado in your case, I think the issue needs to be solved by the `pointer_interceptor` package; check it out:

https://pub.dev/packages/pointer_interceptor

**Comment by tihhmachado** [comment]
@ditman thanks for the feedback! I performed some tests using the example available on the package page, apparently the compartment is correct when using a DivElement, however when using an IFrameElement I still have the same problem, below a video to demonstrate:


https://user-images.githubusercontent.com/39199884/115928016-d0621480-a45b-11eb-944c-ba89ca048d1f.mp4

**Comment by ditman** [comment]
Let's go *without* a flag then. This'll eventually land fixed in `master`. People should be able to test their platformviews just by updating the Flutter version (temporarily) and see what changes are necessary. So far, we've made it so that there are *no* changes needed if Flutter is used in a standard way.

**Comment by ditman** [comment]
We've also discovered now that the `flt-glass-pane` that contains the whole flutter app is not a very descriptive name, so we might change that tag name to: `flutter-view` or similar, so it's clear what it's doing.

**Comment by creativecreatorormaybenot** [comment]
@ditman can you not just wrap the `flt-glass-pane` in another `div` if you want to change the name in a backwards-compatible manner?

**Comment by ditman** [comment]
> @ditman can you not just wrap the flt-glass-pane in another div if you want to change the name in a backwards-compatible manner?

@creativecreatorormaybenot yes, but the name of the flt-glass-pane would still be a lie. For now, I've made the name easily changeable through a constant in the dom_renderer, but won't flip the switch right now!

**Comment by dannnnthemannnn** [comment]
@ditman Awesome work, this is very exciting! Do you have any timeline/estimate for when you expect this to hit master and/or beta?

**Comment by ditman** [comment]
@dannnnthemannnn I'm still ironing out the last few tests (and then I need to write a few more unit tests), then it'd be a matter of having it reviewed so the whole team is on-board with the PR. I don't have a super-firm timeline, but I'd love this to be in `master` by (or around) Google I/O (in mid may).

The `master` -> `beta` timeline is a little bit harder to predict (depends not only on what I break, but also what *others* break :P ), so I'm not really sure when it can happen :/ (also, don't forget the intermediate stage: `dev`)

**Comment by bwysistemas** [comment]
@ditman there is some way to use the solution of this issue now? Because I'm having problem with iframe reloading when hovering mouse inside and outside iframe element. 
I've seen an example here (in this issue) where this is not happening.

**Comment by tneotia** [comment]
@bwysistemas have you tried using the `--web-renderer=html` flag? It is a lot better for my use case when I use that.

**Comment by bwysistemas** [comment]
@tneotia yes, I'm using html renderer. But I'm still having this problem.

**Comment by bwysistemas** [comment]
@ditman @tneotia just to exemplify:


https://user-images.githubusercontent.com/61891071/116745719-e4fd5a00-a9d1-11eb-8429-048b056cc8a5.mp4

I'm using Pointer Interceptor in this iFrame.
Another problem here is in the tabview. When I change the tab, iFrame reloads.

**Comment by ditman** [comment]
> @ditman there is some way to use the solution of this issue now? Because I'm having problem with iframe reloading when hovering mouse inside and outside iframe element.

@bwysistemas yes, but you need to setup a development environment for flutter/engine for web, and then recompile your app with that (that's how I've been building different examples to verify functionality). There's documentation to do this in the flutter/flutter CONTRIBUTING document, if I recall correctly!

**Comment by bwysistemas** [comment]
@ditman excellent! I will wait a few more days. I'm very excited with this fix.

**Comment by ditman** [comment]
@bwysistemas (and everybody else!) thanks for your patience!!

**Comment by msoham123** [comment]
@ditman We should be thanking you! You've been working on this for months and I can't even put into words how amazing this fix is going to be!

**Comment by jeannelim** [comment]
@ditman Is this fix in flutter master yet? I'm having some issues with HtmlElementView.

**Comment by ditman** [comment]
@jeannelim no, it is still not merged to the engine repo yet.

**Comment by ditman** [comment]
The flutter/engine PR has landed, we'll see if it sticks the landing or it gets reverted 🤞

**Comment by ditman** [comment]
Flutter engine roll into flutter/flutter incoming: https://github.com/flutter/flutter/pull/83066

**Comment by ditman** [comment]
This has landed into Flutter channel `master`. Automated testing is currently ongoing.

**Comment by wer-mathurin** [comment]
@ditman : Hooray!  It works for me using the master channel !

**Comment by msoham123** [comment]
@ditman It works! Yay!

**Comment by peerwaya** [comment]
@ditman  I am warning like this using url_launcher:link
```
html_dart2js.dart:40028 Width of Platform View type: [__url_launcher::link] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
Height of Platform View type: [__url_launcher::link] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
```
Also the Link is not clickable on web

**Comment by bwysistemas** [comment]
@ditman The best news I received today.

**Comment by gabrielscr** [comment]
Jesus... so slow to resolve

**Comment by gabrielscr** [comment]
Jesus... finally

**Comment by dannnnthemannnn** [comment]
@ditman amazing work!

Could you provide any sort of timeline for when this will hit beta channel? I'm trying to plan out if I should switch my project to master (and the risk that comes with that) or wait till it hits beta.

**Comment by ditman** [comment]
@dannnnthemannnn yes, that's a very good estimate for when this change will land in the different channels!

The next thing I'm going to work regarding this change is a "Migration Guide" (I broke one internal test with this, and that warrants some documentation).

Once the guide gets published, I'll close this ticket as fixed.

**Comment by dannnnthemannnn** [comment]
@ditman I know this is a little outside the scope of your change but just wanted to mention it. I have a situation where my platform views are to Video elements and before they are removed from the dom I wanted to remove the mediasource on them due to a bug in android chrome. I was doing this in the dispose of the widget that includes the HtmlElementView but I believe the slot code removes them from the dom itself and has no hook into before that happens. 

Anyway, I am using my own HtmlElementView widget which gives me that hook. Just wanted to mention in case I'm missing something or if this is something you all might want to support more natively.

```dart
class VideoVideoHtmlElementView extends StatelessWidget {
  /// Creates a platform view for Flutter Web.
  ///
  /// `viewType` identifies the type of platform view to create.
  const VideoVideoHtmlElementView({
    Key key,
    @required this.viewType,
    this.onDispose,
  })  : assert(viewType != null),
        assert(
            kIsWeb, 'VideoHtmlElementView is only available on Flutter Web.'),
        super(key: key);

  /// The unique identifier for the HTML view type to be embedded by this widget.
  ///
  /// A PlatformViewFactory for this type must have been registered.
  final String viewType;

  final void Function() onDispose;

  @override
  Widget build(BuildContext context) {
    return PlatformViewLink(
      viewType: viewType,
      onCreatePlatformView: _createVideoHtmlElementView,
      surfaceFactory:
          (BuildContext context, PlatformViewController controller) {
        return PlatformViewSurface(
          controller: controller,
          gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
          hitTestBehavior: PlatformViewHitTestBehavior.opaque,
        );
      },
    );
  }

  /// Creates the controller and kicks off its initialization.
  _VideoHtmlElementViewController _createVideoHtmlElementView(
      PlatformViewCreationParams params) {
    final _VideoHtmlElementViewController controller =
        _VideoHtmlElementViewController(params.id, viewType, onDispose);
    controller._initialize().then((_) {
      params.onPlatformViewCreated(params.id);
    });
    return controller;
  }
}

class _VideoHtmlElementViewController extends PlatformViewController {
  _VideoHtmlElementViewController(
    this.viewId,
    this.viewType,
    this.onDispose,
  );

  @override
  final int viewId;

  /// The unique identifier for the HTML view type to be embedded by this widget.
  ///
  /// A PlatformViewFactory for this type must have been registered.
  final String viewType;

  final void Function() onDispose;

  bool _initialized = false;

  Future<void> _initialize() async {
    final Map<String, dynamic> args = <String, dynamic>{
      'id': viewId,
      'viewType': viewType,
    };
    await SystemChannels.platform_views.invokeMethod<void>('create', args);
    _initialized = true;
  }

  @override
  Future<void> clearFocus() {
    // Currently this does nothing on Flutter Web.
    // TODO(het): Implement this. See https://github.com/flutter/flutter/issues/39496
  }

  @override
  Future<void> dispatchPointerEvent(PointerEvent event) {
    // We do not dispatch pointer events to HTML views because they may contain
    // cross-origin iframes, which only accept user-generated events.
  }

  @override
  Future<void> dispose() {
    if (_initialized) {
      onDispose();
      // Asynchronously dispose this view.
      SystemChannels.platform_views.invokeMethod<void>('dispose', viewId);
    }
  }
}

```

**Comment by ditman** [comment]
> I am using my own HtmlElementView widget which gives me that hook. Just wanted to mention in case I'm missing something or if this is something you all might want to support more natively.

@dannnnthemannnn that sounds like something that we could (maybe) expose to end users. After all, the `HtmlElementView` widget is purely for Flutter Web.

Can you please create a new feature request issue in `flutter/flutter` and tag it with `platform: web`? That way we can bring it up during the triage of the team!

**Comment by yjbanov** [comment]
Might be related: @dnfield is working on a `dispose` method for `RenderObject`, which may be the appropriate place for signalling that the `HtmlElementView` is about to be removed: https://github.com/flutter/flutter/pull/83920. I also don't see why this should be web-specific functionality. I imagine this can be useful on AOT platforms as well /cc @goderbauer

**Comment by dnfield** [comment]
The RenderObject.dispose patch is awaiting a reland here: https://github.com/flutter/flutter/pull/83920

The idea with that is dispose will be called when the RenderObject will not be used again in the tree,a nd it should drop any resources it's holding.

I don't think you need the picture part for this, right?

**Comment by ditman** [comment]
There's also this feature request from a while ago, which is asking about the opposite event, when the HtmlElementView is rendered into the DOM: https://github.com/flutter/flutter/issues/56181

**Comment by dnfield** [comment]
I think if you changed HtmlElementView from StatelessWidget to something that created an `Element`, you should be able to do that with `mount`/`unmount`, right?

**Comment by dnfield** [comment]
Alternatively make it a `StatefulWidget` and do this in `initState`/`dispose`.

**Comment by jeannelim** [comment]
Is it possible to get this fix included in the next hotfix for 2.2 version?

**Comment by ditman** [comment]
@jeannelim unlikely, we're just discussing it now.

**Comment by ditman** [comment]
> minimal code sample
> flutter doctor -v

@TahaTesser is this a reproduction of a bug or something? Can you provide more details with the code sample? Is this broken again?

**Comment by TahaTesser** [comment]
@ditman 
Yes, the issue reproduces on `stable` (I thought I added stable doctor-v, corrected the comment above)

**Comment by tneotia** [comment]
I don't think slot based rendering has made it to stable yet, maybe try on dev/master (don't know for sure where the PR has landed as of now).

**Comment by ditman** [comment]
@TahaTesser yes, @tneotia is correct. This hasn't rolled too far, it's probably not in beta yet!

**Comment by Akshaymain** [comment]
@ditman Can i know when will it be moved to stable channel?

**Comment by TahaTesser** [comment]
@ditman 
Can this be closed?

**Comment by tneotia** [comment]
@TahaTesser not David but I think he said he needs to publish a guide before closing this issue:

https://github.com/flutter/flutter/issues/80524#issuecomment-848375361

**Comment by bsp003** [comment]
> @ditman Can i know when will it be moved to stable channel?

@ditman Yes, desperately in need of this in stable channel. Please help!

**Comment by ditman** [comment]
Marking this as backwards breaking, here's the Migration Guide:

* https://flutter.dev/docs/release/breaking-changes/platform-views-using-html-slots-web

**Comment by jeannelim** [comment]
Any updates on this fix? Looks like it's still in master channel. We really need this fix.

**Comment by isamuninja** [comment]
Hello @ditman, good job.

Switching to the beta or dev channel solves the problem when resizing the window. 

But in my case I have a problem when I try to draw an iframe or webview tag with the Element.html() method, example
```dart
ui.platformViewRegistry.registerViewFactory(
  'hello-web',
  (int viewId) => dom.Element.html(
      '<iframe src="https://www.youtube.com/embed/NpEaa2P7qZI" height="150" width="640"></iframe>',
      validator: new dom.NodeValidatorBuilder()
        ..allowHtml5()
        ..allowElement('webview', attributes: ['*'])
        ..allowElement('iframe', attributes: ['*']))
    ..style.width = '100%'
    ..style.height = '100%',
);

Padding(
  padding: EdgeInsets.all(25),
  child: SizedBox(
    width: 640,
    height: 360,
    child: HtmlElementView(key: UniqueKey(), viewType: 'hello-web'),
  ),
),
```

Using the basic example of flutter and adding this html element, every time I click the button to increase the element is repainted. 

Do you know any way to fix this?
 
I attach the complete code used.
[Demo DartPad](https://dartpad.dev/embed-flutter.html?null_safety=true&id=173a46b2d227a641fedf61d377377bfa)
```dart
import 'package:flutter/material.dart';
import 'dart:html' as dom;
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  initState() {
    super.initState();

    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'hello-web',
      (int viewId) => dom.Element.html(
          '<iframe src="https://www.youtube.com/embed/NpEaa2P7qZI" height="150" width="640"></iframe>',
          validator: new dom.NodeValidatorBuilder()
            ..allowHtml5()
            ..allowElement('webview', attributes: ['*'])
            ..allowElement('iframe', attributes: ['*']))
        ..style.width = '100%'
        ..style.height = '100%',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Padding(
              padding: EdgeInsets.all(25),
              child: SizedBox(
                width: 640,
                height: 360,
                child: HtmlElementView(key: UniqueKey(), viewType: 'hello-web'),
              ),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

Thank you so much.

**Comment by ditman** [comment]
@isamuninja I haven't tried your code, but can you try removing the `UniqueKey` from the `key` of the video player? Every time that you set state, you're telling the framework that the video player is a different widget, and that's probably causing the repaint:

```dart
child: HtmlElementView(key: UniqueKey(), viewType: 'hello-web'),
```

to

```dart
child: HtmlElementView(viewType: 'hello-web'),
```

**Comment by isamuninja** [comment]
thank you very much @ditman, removing the key I no longer have the problem.

**Comment by ayazthemre** [comment]
Is there any date for this to release on stable version?

**Comment by ditman** [comment]
@ayazthemre I think this is already in the Beta channel. AFAIK there's no date for the next stable release. Beta to Stable happens [around once a quarter](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta).
