### ISSUE TITLE
When keyboard is opened, showModalBottomSheet be pushed up by the keyboard and TextField or other content is out of screen

### ISSUE THREAD

**Issue by 627974327** [flutter/flutter#80941]
## Steps to Reproduce

1. Upgrade flutter2.0.
2. Use showModalBottomSheet with a TextField inside
3. Select TextField to open keyboard
code
```
showModalBottomSheet(
        backgroundColor: Colors.white,
        context: context,
        isScrollControlled: true,  // !important
        builder: (BuildContext context) {
          return SizedBox(
              height: 1144.h,
              child:Container(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    TextField(
                      keyboardType: TextInputType.text,
                      autofocus: false,
                      decoration: InputDecoration(
                        hintText: "请输入",
                        counterText: "",
                      ),
                    ),
                  ],
                ),
              )
          );
        }
    );
```
**Expected results:** 

**Actual results:** 

https://user-images.githubusercontent.com/32918597/115707116-fa0a3580-a3a0-11eb-8123-1e55cbe2d1f2.mp4

```
```

```
```

I runned  `flutter doctor -v`

[✓] Flutter (Channel unknown, 2.0.1, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/raoliqin/Public/flutter2.0/flutter
    • Framework revision c5a4b4029c (7 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/raoliqin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/raoliqin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 11A556A3-894E-48F0-A577-CDD30EB1E476 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

**Comment by darshankawar** [comment]
@627974327 
Can you upgrade to latest stable (2.0.5) and try again to see if issue persists ?
Also, what's the expected behavior with your implementation ?

**Comment by sullenel** [comment]
This is fixed on master by https://github.com/flutter/flutter/pull/77286

**Comment by 627974327** [comment]
> @627974327
> Can you upgrade to latest stable (2.0.5) and try again to see if issue persists ?
> Also, what's the expected behavior with your implementation ?

I upgraded to latest stable (2.0.5) and try again, the issue persists

> This is fixed on master by #77286

**Comment by 627974327** [comment]
> This is fixed on master by #77286

When will the commit be merged into release?

**Comment by 627974327** [comment]
> @627974327
> Can you upgrade to latest stable (2.0.5) and try again to see if issue persists ?
> Also, what's the expected behavior with your implementation ?

I upgraded to latest stable (2.0.5) and try again, the issue persists.
This is fixed on master by #77286, When will the commit be merged into release?
