### ISSUE TITLE
Flutter build apk not working with flavors

### ISSUE THREAD

**Issue by niktses** [flutter/flutter#82262]
Cannot release apk for production!!!

After upgrading to null safety i needed to upgrade to gradle 4.0.

Same as https://github.com/flutter/flutter/issues/58247 which was opened over a year ago!!

Gradle expects a ../libs.jar for every combination of flavor - buildType (in new project needs 3 - release - debug - profile, in my project needs 48 so the 'solutions' (offered on the above issue) of running each one once is out of the question especially with dev-op).

This prevents us from any future action with our app. Can this be fixed maybe in a hotfix?

## Steps to Reproduce

- Run flutter create counter
- Add this to build.gradle:

`` 

	flavorDimensions "app"
	
	productFlavors {
		flavor1{
			dimension "app"
		}
		flavor2{
			dimension "app"
		}
	}

- Run flutter build apk --flavor flavor1

Output:

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:lintVitalFlavor1Release'.
> Could not resolve all artifacts for configuration ':app:flavor2ReleaseRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\nikts\Projects\counter\build\app\intermediates\flutter\flavor2Release\libs.jar.
         > Transform's input file does not exist: C:\Users\nikts\Projects\counter\build\app\intermediates\flutter\flavor2Release\libs.jar. (See https://issuetracker.google.com/issues/158753935)

flutter doctor:

C:\Users\nikts\Projects\counter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.0)
[√] Connected device (2 available)

• No issues found!

**Comment by darshankawar** [comment]
@niktses 
Meanwhile, can you try and follow this lead here and see if it helps ?

https://github.com/flutter/flutter/issues/81974#issuecomment-837345320

**Comment by blasten** [comment]
Another option to fix the issue is to add the following:

<app>/android/app/build.gradle:
```groovy
android {
  lintOptions {
    checkReleaseBuilds false
  }
}
```

No need to downgrade to an older version of AGP.

**Comment by mehtahardikr** [comment]
try to run with. Run 
`flutter build apk --flavor flavor1 --release` or `flutter build apk --flavor flavor1 --profile` this is working fine for me.

**Comment by niktses** [comment]
Why was this closed? it is not fixed

**Comment by darshankawar** [comment]
@niktses The fix is pushed to master and you will need to upgrade to latest master version to see the fix and wait for it to reach to stable.

**Comment by MaximilianFrick** [comment]
@darshankawar 
is it somehow foreseeable when this will get merged into stable?
i still have the problem with 2.2.3 
and i have to use gradle version 3.5.4 to get my release builds working with flavors

**Comment by flutteresbolivia** [comment]
I have the same problem, but it is solved when flavors are commented
