### ISSUE TITLE
Android Studio (the doctor check crashed)

### ISSUE THREAD

**Issue by OMigz** [flutter/flutter#83195]
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.3.0-13.0.pre.59, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2.0)
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = ''C:\Program.plugins' (OS Error: A sintaxe do nome do arquivo, do nome
      do diretório ou do rótulo do volume está incorreta.
      , errno = 123)
[√] VS Code (version 1.56.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
@OMigz could you provide the full stack trace by running `flutter doctor -vv` ?

**Comment by Ngonie69** [comment]
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = ''C:\Program.plugins' (OS Error: The filename, directory name, or
      volume label syntax is incorrect.
      , errno = 123)
    • #0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
      #1      ForwardingFileSystemEntity.existsSync
      (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
      #2      ErrorHandlingDirectory.existsSync.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:479:22)
      #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
      #4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:478:12)
      #5      AndroidStudio.pluginsPath (package:flutter_tools/src/android/android_studio.dart:186:52)
      #6      AndroidStudioValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:46:17)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #9      _rootRun (dart:async/zone.dart:1354:13)
      #10     _CustomZone.run (dart:async/zone.dart:1258:19)
      #11     _runZoned (dart:async/zone.dart:1789:10)
      #12     runZonedGuarded (dart:async/zone.dart:1777:12)
      #13     runZoned (dart:async/zone.dart:1708:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:199:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:303:47)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1192:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>


Full stack trace of the error

**Comment by Ngonie69** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.3.0-13.0.pre.59, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2.0)
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = ''C:\Program.plugins' (OS Error: A sintaxe do nome do arquivo, do nome
      do diretório ou do rótulo do volume está incorreta.
      , errno = 123)
[√] VS Code (version 1.56.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
`

**Comment by Ngonie69** [comment]
`☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = ''C:\Program.plugins' (OS Error: The filename, directory name, or
      volume label syntax is incorrect.
      , errno = 123)
    • #0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
      #1      ForwardingFileSystemEntity.existsSync
      (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
      #2      ErrorHandlingDirectory.existsSync.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:479:22)
      #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
      #4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:478:12)
      #5      AndroidStudio.pluginsPath (package:flutter_tools/src/android/android_studio.dart:186:52)
      #6      AndroidStudioValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:46:17)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #9      _rootRun (dart:async/zone.dart:1354:13)
      #10     _CustomZone.run (dart:async/zone.dart:1258:19)
      #11     _runZoned (dart:async/zone.dart:1789:10)
      #12     runZonedGuarded (dart:async/zone.dart:1777:12)
      #13     runZoned (dart:async/zone.dart:1708:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:199:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:303:47)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1192:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>`

**Comment by rnyetto** [comment]
I'm having the same issue.

**Comment by rnyetto** [comment]
So, I think i solve that first problem...
Try using in the CMD

flutter config --android-studio-dir=

run the doctor again!

**Comment by Quwaysim** [comment]
Same error here, ran `flutter config --android-studio-dir='C:\Program Files\Android\Android Studio'` in CMD, rebooted PC, same error

**Comment by felixpessoa** [comment]
I have the same problem, could someone help?

**Comment by guimalatesta** [comment]
I have the same error. I did run flutter config to set the correct directory to Android Studio, but now its not working

**Comment by AkankshaKS** [comment]
Faced the same problem, turned out the solution is to use:
**flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"** [Double Quotes for path to Android Studio]
It detected android successfully for me after running this,

**Comment by Farshad-Hasanpour** [comment]
> Faced the same problem, turned out the solution is to use:
> **flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"** [Double Quotes for path to Android Studio]
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.17134.2208], locale en-IN)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Android Studio
> [√] Connected device (3 available)
> 
> It detected android successfully for me after running this,

I had an extra space between `--android-studio-dir` and `=` that caused the crash.

**Comment by Quwaysim** [comment]
> > Faced the same problem, turned out the solution is to use:
> > **flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"** [Double Quotes for path to Android Studio]
> > 
> > Doctor summary (to see all details, run flutter doctor -v):
> > [√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.17134.2208], locale en-IN)
> > [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> > [√] Chrome - develop for the web
> > [√] Android Studio
> > [√] Connected device (3 available)
> > 
> > It detected android successfully for me after running this,
> 
> I had an extra space between `--android-studio-dir` and `=` that caused the crash.

Figured it was the space that caused the crash in mine too, thanks a lot. It's working now

**Comment by Kpray-Coder** [comment]
> > Faced the same problem, turned out the solution is to use:
> > **flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"** [Double Quotes for path to Android Studio]
> > Doctor summary (to see all details, run flutter doctor -v):
> > [√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.17134.2208], locale en-IN)
> > [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> > [√] Chrome - develop for the web
> > [√] Android Studio
> > [√] Connected device (3 available)
> > It detected android successfully for me after running this,
> I had an extra space between `--android-studio-dir` and `=` that caused the crash.

**Comment by KumarMonisankarBasu** [comment]
still not working for me

**Comment by KumarMonisankarBasu** [comment]
PS C:\Users\KUMAR MONISANKAR> flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"
Setting "android-studio-dir" value to "C:\Program Files\Android\Android Studio".

You may need to restart any open editors for them to read new settings.
PS C:\Users\KUMAR MONISANKAR> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.572], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Android\sdk\platform-tools\adb.exe

! Doctor found issues in 1 category.

**Comment by Quwaysim** [comment]
> PS C:\Users\KUMAR MONISANKAR> flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"
> Setting "android-studio-dir" value to "C:\Program Files\Android\Android Studio".
> 
> You may need to restart any open editors for them to read new settings.
> PS C:\Users\KUMAR MONISANKAR> flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.572], locale en-IN)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Android Studio
> [☠] Connected device (the doctor check crashed)
> X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
> about this issue at https://github.com/flutter/flutter/issues.
> X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
> C:\Android\sdk\platform-tools\adb.exe
> 
> ! Doctor found issues in 1 category.

Do you have the platform-tools for in your env variables? It's the dir that houses the adb executable file.

**Comment by KumarMonisankarBasu** [comment]
i add platform tools to environment variables path section

**Comment by KumarMonisankarBasu** [comment]
plz help me some body im stuck

**Comment by Quwaysim** [comment]
> plz help me some body im stuck

First, I'll suggest you remove the multiple variables you have set. If you try a fix and it doesn't work for you, it'll be better to reset it back to how it was before so as not create another problem as they may conflict.

In your Android Studio's settings, under the SDK Tools tab, do you have the **command-line-tools (latest)** checked (installed)? If no, install it.

Also, you may need to check the **platform-tools** dir to check if the **adb.exe** file is actually there.

**Comment by gamerboyelz** [comment]
> Faced the same problem, turned out the solution is to use:
> **flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"** [Double Quotes for path to Android Studio]
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.17134.2208], locale en-IN)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Android Studio
> [√] Connected device (3 available)
> 
> It detected android successfully for me after running this,

This worked 100% ... Thanks man

**Comment by masundareza123** [comment]
try this in cmd: flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"

**Comment by MichalTorma** [comment]
This issue happened to me right now after I set the Android studio path by 
` flutter config --android-studio-dir="C:\Program Files\Android\Android Studio\"` 
and then I fixed it by  
`flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"` Be careful of the last backslash.

**Comment by Akethaki** [comment]
hi there
i got an error as below

C:\WINDOWS\system32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.60.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

C:\Windows\System32>flutter config --android-sdk="E:\Android_SDK"
Setting "android-sdk" value to "E:\Android_SDK".

You may need to restart any open editors for them to read new settings.

C:\Windows\System32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Null check operator used on a null value
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.60.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.


can some one solve this for me

**Comment by TahaTesser** [comment]
Hi 
Anyone still reproducing the issue, please install the latest SDK from Android Studio including the `cmd-tools`, if you're not using Android Studio, please follow commands [here](https://github.com/flutter/flutter/issues/90579#issuecomment-927629209).

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
