### ISSUE TITLE
Flutter tool generates incorrect IPv6 addresses when deploying to Fuchsia

### ISSUE THREAD

**Issue by nmcain** [flutter/flutter#83609]
## Steps to Reproduce

1. Compile and build Fuchsia and open the emulator
2. With an application configured for Fuchsia with a valid component manifest, attempt to `flutter run -d fuchsia`
3. The application will build, but fails to deploy with the following logs, because it is adding %25 to the IP address in the wrong place. (done on line 612 of `flutter/packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart`) I was also told that it uses some sort of wrong name on the network interface.

## Logs

<details>
<summary>Logs</summary>

```
flutter run -d fuchsia --verbose
[  +91 ms] executing: uname -m
[  +47 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +11 ms] executing: [/home/nmcain/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c42ec8592f9c426cfc3d27a5cd4da3f49f42b396
[        ] executing: [/home/nmcain/flutter/] git tag --points-at c42ec8592f9c426cfc3d27a5cd4da3f49f42b396
[  +20 ms] Exit code 0 from: git tag --points-at c42ec8592f9c426cfc3d27a5cd4da3f49f42b396
[   +1 ms] executing: [/home/nmcain/flutter/] git describe --match *.*.* --long --tags c42ec8592f9c426cfc3d27a5cd4da3f49f42b396
[  +35 ms] Exit code 0 from: git describe --match *.*.* --long --tags c42ec8592f9c426cfc3d27a5cd4da3f49f42b396
[        ] 2.3.0-16.0.pre-120-gc42ec8592f
[  +11 ms] executing: [/home/nmcain/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/nmcain/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +125 ms] Unable to locate an Android SDK.
[   +7 ms] executing: [/home/nmcain/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +88 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +107 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/x64/ffx target list --format s
[ +263 ms] fe80::98bb:89e1:a5cf:daab%brqemu fuchsia_fimage
[   +2 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/x64/ffx target list --format a fuchsia_fimage
[ +313 ms] fe80::98bb:89e1:a5cf:daab%brqemu
[   +3 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu uname -m
[  +63 ms] x86_64
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] Skipping pub get: version match.
[ +164 ms] Generating /home/nmcain/Desktop/fimage-210528/demo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +84 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu cat
/pkgfs/packages/build-info/0/data/version
[ +124 ms] 2021-05-26T01:49:18+00:00
[  +56 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +8 ms] Skipping target: gen_dart_plugin_registrant
[  +17 ms] Skipping target: _composite
[   +2 ms] complete
[   +9 ms] Launching lib/main.dart on fuchsia_fimage in debug mode...
[   +7 ms] /home/nmcain/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/nmcain/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/nmcain/flutter/bin/cache/artifacts/flutter_runner/flutter/x64/debug/jit/flutter_runner_patched_sdk/ --incremental
--target=flutter_runner --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.QQEKMF/flutter_tool.ACZYXS/app.dill --packages /home/nmcain/Desktop/fimage-210528/demo/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +48 ms] <- compile package:demo/main.dart
[  +26 ms] Building Fuchsia application...
[   +5 ms] executing: /home/nmcain/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/nmcain/flutter/bin/cache/artifacts/flutter_runner/flutter/arm64/debug/jit/dart_binaries/kernel_compiler.snapshot --target
flutter_runner --platform
/home/nmcain/flutter/bin/cache/artifacts/flutter_runner/flutter/arm64/debug/jit/flutter_runner_patched_sdk/platform_strong.dill
--filesystem-scheme main-root --filesystem-root /home/nmcain/Desktop/fimage-210528/demo --packages main-root:///.packages --output
build/fuchsia/demo.dil --component-name demo --no-link-platform --split-output-by-packages --manifest build/fuchsia/demo.dilpmanifest
--embed-sources -DFLUTTER_WEB_AUTO_DETECT=true main-root:////home/nmcain/Desktop/fimage-210528/demo/lib/main.dart
[+24319 ms] Building Fuchsia application... (completed in 24.3s)
[        ] fuchsia-kernel-compile: 24342 ms.
[ +220 ms] fuchsia-build-assets: 220 ms.
[   +8 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm -o build/fuchsia/pkg -n demo init
[  +19 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm -o build/fuchsia/pkg -m build/fuchsia/pkg/package_manifest
build
[ +256 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm -o build/fuchsia/pkg -m build/fuchsia/pkg/package_manifest
archive
[ +152 ms] fuchsia-build-package: 436 ms.
[   +3 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu tiles_ctl list
[ +158 ms] Couldn't find tiles component in realm
                    To start a new instance of tiles, run 'tiles_ctl start'
[        ] tiles_ctl is not running
[        ] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu echo $SSH_CONNECTION
[  +32 ms] fe80::38e4:b1ff:fe18:c538%ethp0003 59990 fe80::98bb:89e1:a5cf:daab%ethp0003 22
[   +7 ms] Starting Fuchsia application demo...
[   +1 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu amber_ctl get_up -n tiles
[  +82 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu amber_ctl get_up -n
tiles_ctl
[  +98 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm newrepo -repo build/fuchsia/.pkg-repo
[ +598 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm serve -repo build/fuchsia/.pkg-repo -l
[fe80::38e4:b1ff:fe18:c538%25ethp0003]:40279
[   +6 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm publish -a -r build/fuchsia/.pkg-repo -f
build/fuchsia/pkg/demo-0.far
[  +13 ms] listen tcp [fe80::38e4:b1ff:fe18:c538%25ethp0003]:40279: bind: no such device
[   +5 ms] Error running Fuchsia pm tool "serve" command
[ +490 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm publish -a -r build/fuchsia/.pkg-repo -f
/home/nmcain/flutter/bin/cache/artifacts/flutter_runner/flutter/x64/debug/jit/flutter_jit_runner-0.far
[ +469 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu amber_ctl add_repo_cfg -n
flutter_tool -f http://[fe80::38e4:b1ff:fe18:c538%25ethp0003]:40279/config.json
[ +102 ms] 2021/05/29 21:59:29 error adding repo: failed to GET file: Get "http://[fe80::38e4:b1ff:fe18:c538%25ethp0003]:40279/config.json":
dial tcp [fe80::38e4:b1ff:fe18:c538%ethp0003]:40279: errno(111)
[        ] Failed to teach amber about the package server
[        ] Shutting down the tool's package server.
[        ] Removing the tool's package repo: at build/fuchsia/.pkg-repo
[  +12 ms] Starting Fuchsia application demo... (completed in 1,881ms)
[        ] Error launching application on fuchsia_fimage.
[   +5 ms] "flutter run" took 28,555ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +120 ms] ensureAnalyticsSent: 118ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
flutter doctor --verbose
[✓] Flutter (Channel master, 2.3.0-17.0.pre.120, on Ubuntu 20.04.2 LTS 5.8.0-53-generic, locale en_US.UTF-8)
    • Flutter version 2.3.0-17.0.pre.120 at /home/nmcain/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c42ec8592f (20 hours ago), 2021-05-28 22:34:02 -0400
    • Engine revision aca8aa2335
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.56.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • fuchsia_fimage (null) • fe80::98bb:89e1:a5cf:daab%brqemu • fuchsia-x64    • Fuchsia 2021-05-26T01:49:18+00:00
    • Linux (desktop)       • linux                            • linux-x64      • Ubuntu 20.04.2 LTS 5.8.0-53-generic
    • Chrome (web)          • chrome                           • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 2 categories.

```

</details>

**Comment by nmcain** [comment]
By fixing that replaceAll() on line 612 of flutter/packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart, I now get this error regarding it, so it may not be that %25

```[  +26 ms] listen tcp [fe80::38e4:b1ff:fe18:c538%ethp0003]:36897: bind: invalid argument
[   +6 ms] Error running Fuchsia pm tool "serve" command
[ +504 ms] executing: /home/nmcain/flutter/bin/cache/artifacts/fuchsia/tools/pm publish -a -r build/fuchsia/.pkg-repo -f
/home/nmcain/flutter/bin/cache/artifacts/flutter_runner/flutter/x64/debug/jit/flutter_jit_runner-0.far
[ +519 ms] executing: ssh -F /home/nmcain/Desktop/fimage-210528/ssh/ssh_config fe80::98bb:89e1:a5cf:daab%brqemu amber_ctl add_repo_cfg -n
flutter_tool -f http://[fe80::38e4:b1ff:fe18:c538%ethp0003]:36897/config.json
[  +60 ms] 2021/05/29 22:25:24 error adding repo: failed to open file: open http://[fe80::38e4:b1ff:fe18:c538%ethp0003]:36897/config.json:
ErrNotFound: http:/[fe80::38e4:b1ff:fe18:c538%ethp0003]:36897/config.json
[        ] Failed to teach amber about the package server
[        ] Shutting down the tool's package server.
[        ] Removing the tool's package repo: at build/fuchsia/.pkg-repo
[  +12 ms] Starting Fuchsia application demo... (completed in 2,066ms)
[        ] Error launching application on fuchsia_fimage.
[   +4 ms] "flutter run" took 35,876ms.
[   +4 ms] 
```

**Comment by nmcain** [comment]
Disabling IPv6 on the host provides another error, but it may be easier to work with:
```[  +11 ms] ssh: connect to host fe80::98bb:89e1:a5cf:daab%6 port 22:
Cannot assign requested address
[        ] tiles_ctl is not running
[        ] executing: ssh -F
/home/nmcain/Desktop/fimage-210528/ssh/ssh_config
fe80::98bb:89e1:a5cf:daab%6 echo $SSH_CONNECTION
[  +10 ms] ssh: connect to host fe80::98bb:89e1:a5cf:daab%6 port 22:
Cannot assign requested address
[   +9 ms] Exception: Failed to get local address, aborting.
           ssh: connect to host fe80::98bb:89e1:a5cf:daab%6 port 22:
Cannot
           assign requested address
[   +3 ms] "flutter run" took 27,831ms.
[   +9 ms] 
           #0      throwToolExit
           (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>

(package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
           (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous
closure>

(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand

(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +132 ms] ensureAnalyticsSent: 123ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by allansrc** [comment]
I think you guys @chaselatta @arbreng could helps w that.

**Comment by michaellee8** [comment]
@nmcain The %25 issues should have been fixed by my pr a year ago, now we are fixing the issue caused by the difference between the network address in host and emulator, please apply my pr at #84759 if you want a quick fix.

**Comment by nmcain** [comment]
I saw that mentioned on the Fuchsia issue, I will have to revise this accordingly. I was told that the %25 was still an issue, but I guess not, if thats been fixed?

**Comment by michaellee8** [comment]
> I saw that mentioned on the Fuchsia issue, I will have to revise this accordingly. I was told that the %25 was still an issue, but I guess not, if thats been fixed?

I remember that I have tried the %25 fix for pm serve, but it actually won't work, since it is trying to bind to the wrong interface anyway. My solution is just to simply bind to all interfaces and it is what has been done in the pr.

As mentioned in the pr, there are no obvious way to find out the specific ip address and interface to bind to here. Binding to localhost won't work as well sincd that emulator is not considered as localhost. Trying to get that ip address and interface for binding is possible, but it would require some scripting and I am unsure if it works in macOS, so I decided to simply bind to all interfaces instead.

**Comment by chaselatta** [comment]
https://github.com/flutter/flutter/commit/6dd9e8c153783a12b60a9c5ee78ac1de655e54c9 should fix the immediate issue of the serve call crashing but flutter run needs to be taught how to work with the session framework if we want this to work on the workstation product.

**Comment by michaellee8** [comment]
> [6dd9e8c](https://github.com/flutter/flutter/commit/6dd9e8c153783a12b60a9c5ee78ac1de655e54c9) should fix the immediate issue of the serve call crashing but flutter run needs to be taught how to work with the session framework if we want this to work on the workstation product.

I am actually wondering how do you start an cmx in ermine. It looks like there are no amber_ctl in workstation.

**Comment by nmcain** [comment]
I will have to check but I believe I was able to include amber_ctl in workstation, at least the binary is present

**Comment by michaellee8** [comment]
> I will have to check but I believe I was able to include amber_ctl in workstation, at least the binary is present

My miskate, I shouldn't be saying amber_ctl, I was trying to say tiles_ctl. It turns out session_control is what we need here for workstation, let me do the coding.

**Comment by nmcain** [comment]
Both of those appear to be present, but I believe I built my workstation image with a longer than default command, something along the lines of --with-base iirc

**Comment by michaellee8** [comment]
> Both of those appear to be present, but I believe I built my workstation image with a longer than default command, something along the lines of --with-base iirc

I assume that you have kitchen_sink build? Either way, tiles_ctl should not work with ermine, we will need session_control anyway.

**Comment by nmcain** [comment]
I see what you mean.

```

[+5235 ms] resolving fuchsia-pkg://flutter_tool/demo with the selectors []
                    package contents:
                    /meta/contents
                    /meta/demo.cmx
                    /meta/package
                    /data/demo/AssetManifest.json
                    /data/demo/FontManifest.json
                    /data/demo/NOTICES.Z
                    /data/demo/app.dilplist
                    /data/demo/app.frameworkversion
                    /data/demo/characters.dilp
                    /data/demo/collection.dilp
                    /data/demo/demo.dilp
                    /data/demo/flutter.dilp
                    /data/demo/main.dilp
                    /data/demo/meta.dilp
                    /data/demo/typed_data.dilp
                    /data/demo/vector_math.dilp
                    /data/demo/fonts/MaterialIcons-Regular.otf
                    /data/demo/packages/cupertino_icons/assets/CupertinoIcons.t
                    tf
[   +1 ms] executing: ssh -F
/home/nmcain/Downloads/fimage-210528/ssh/ssh_config
fe80::98bb:89e1:a5cf:daab%brqemu tiles_ctl list
[  +53 ms] Couldn't find tiles component in realm
           To start a new instance of tiles, run 'tiles_ctl start'
[   +1 ms] executing: ssh -F
/home/nmcain/Downloads/fimage-210528/ssh/ssh_config
fe80::98bb:89e1:a5cf:daab%brqemu tiles_ctl start
[  +50 ms] executing: ssh -F
/home/nmcain/Downloads/fimage-210528/ssh/ssh_config
fe80::98bb:89e1:a5cf:daab%brqemu tiles_ctl add
fuchsia-pkg://flutter_tool/demo#meta/demo.cmx
[  +75 ms] Couldn't open tile service directory
[        ] Failed to add the app to tiles
[   +1 ms] executing: ssh -F
/home/nmcain/Downloads/fimage-210528/ssh/ssh_config
fe80::98bb:89e1:a5cf:daab%brqemu pkgctl repo rm fuchsia-pkg://flutter_tool
[  +99 ms] Shutting down the tool's package server.
[   +1 ms] Removing the tool's package repo: at build/fuchsia/.pkg-repo
[  +16 ms] Starting Fuchsia application demo... (completed in 60.5s)
[        ] Error launching application on fuchsia_fimage.
[   +8 ms] "flutter run" took 90,710ms.
[   +8 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:671:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +151 ms] ensureAnalyticsSent: 149ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

**Comment by chaselatta** [comment]
Workstation is built on the session framework (https://fuchsia.dev/fuchsia-src/concepts/session/introduction?hl=en) which doesn't give access to the root presenter which is why tiles_ctl doesn't work. The session framework introduces 2 protocols which facilitate the launching of graphical applications. The first is the ElementProposer which is a protocol that the workstation session implements. The second is the GraphicalPresenter which is what ermine implements. When you want to launch an application you tell the element proposer what application you want to launch and it in turn will tell the graphical presenter to display it.

In the workstation, you can launch some select applications with the ermine ask bar, the `session_control` tool if you are on a device or you can use `ffx session add` (ffx session might still be experimental so may need some configuration flags, I can't remember.) If you are using session_control or `ffx session` the built package needs to be published to a package repository for the system to resolve it. The flutter tool currently publishes the package for you but it still tries to use tiles_ctl. 

All of this works really well if you are using a build system that knows how to serve and publish packages because you can just build and run independent of the underlying language. This means that when you are developing you start a long running package server then get in a build/run loop where running could be something like `run-test-component`, `run`, `session_control add` or `tiles_ctl add` depending on what product or area of the system you are targeting.  This doesn't really work all that well with the flutter tool because it only knows that you are targeting a fuchsia device but doesn't know if you are targeting something like workstation or the terminal product. This is something that we need to resolve but I haven't thought enough about the problem to have any good answers. 

For the time being, you can probably just apply a local patch that replaces tiles_ctl with session_control to see if you can make it work locally for you but, unfortunately, you will probably run into other issues unless you are really careful about keeping versions in sync. The problem you are likely to run into has to do with Dart's abi compatibility. Flutter applications must be built against a version of dart that has abi compatibility with the vm that is embedded in the runner. This isn't an issue for non-fuchsia flutter applications because they embed their own runner in each application but fuchsia is built using a model where flutter applications share a runner. If you try to build a flutter application with a dart that is not compatible with the version that ermine was built with it will try to launch the application in the runner that is running ermine and will crash with an error complaining about version mismatches. This is a problem that I have thought a lot about and I'm working on some proposals but I'm not sure when they will land. We really need to fix this problem but we currently just build everything at the same time so it usually works out.

**Comment by michaellee8** [comment]
> Workstation is built on the session framework (https://fuchsia.dev/fuchsia-src/concepts/session/introduction?hl=en) which doesn't give access to the root presenter which is why tiles_ctl doesn't work. The session framework introduces 2 protocols which facilitate the launching of graphical applications. The first is the ElementProposer which is a protocol that the workstation session implements. The second is the GraphicalPresenter which is what ermine implements. When you want to launch an application you tell the element proposer what application you want to launch and it in turn will tell the graphical presenter to display it.
> 
> In the workstation, you can launch some select applications with the ermine ask bar, the `session_control` tool if you are on a device or you can use `ffx session add` (ffx session might still be experimental so may need some configuration flags, I can't remember.) If you are using session_control or `ffx session` the built package needs to be published to a package repository for the system to resolve it. The flutter tool currently publishes the package for you but it still tries to use tiles_ctl.
> 
> All of this works really well if you are using a build system that knows how to serve and publish packages because you can just build and run independent of the underlying language. This means that when you are developing you start a long running package server then get in a build/run loop where running could be something like `run-test-component`, `run`, `session_control add` or `tiles_ctl add` depending on what product or area of the system you are targeting. This doesn't really work all that well with the flutter tool because it only knows that you are targeting a fuchsia device but doesn't know if you are targeting something like workstation or the terminal product. This is something that we need to resolve but I haven't thought enough about the problem to have any good answers.
> 
> For the time being, you can probably just apply a local patch that replaces tiles_ctl with session_control to see if you can make it work locally for you but, unfortunately, you will probably run into other issues unless you are really careful about keeping versions in sync. The problem you are likely to run into has to do with Dart's abi compatibility. Flutter applications must be built against a version of dart that has abi compatibility with the vm that is embedded in the runner. This isn't an issue for non-fuchsia flutter applications because they embed their own runner in each application but fuchsia is built using a model where flutter applications share a runner. If you try to build a flutter application with a dart that is not compatible with the version that ermine was built with it will try to launch the application in the runner that is running ermine and will crash with an error complaining about version mismatches. This is a problem that I have thought a lot about and I'm working on some proposals but I'm not sure when they will land. We really need to fix this problem but we currently just build everything at the same time so it usually works out.

Thank you for your input, this is pretty insightful.

I plan to let flutter_tool decide whether it will use tiles_ctl or session_control by making it run `cat /config/build-info/product` and check it it is running on a workstation build. Then flutter_tool can then tiles_ctl or session_control accordingly. 

The runtime version issue is an interesting problem here. I have faced it serveral times when trying to run flutter apps on fuchsia, may I have a look at your existing proposals?

**Comment by michaellee8** [comment]
I have done the coding to teach flutter_tools about session_control in https://github.com/flutter/flutter/pull/85450, it went well that the app actually laucnhed on the workstation build vm, but then there are some strange problem which I will discuss below. Please forgive me for not adding test yet, I will do it when I have done the debugging. 

It seems that when these code in startApp is ran, 

```dart
    // In a debug or profile build, try to find the observatory uri.
    final FuchsiaIsolateDiscoveryProtocol discovery =
        getIsolateDiscoveryProtocol(appName);
    try {
      final Uri observatoryUri = await discovery.uri;
      return LaunchResult.succeeded(observatoryUri: observatoryUri);
    } finally {
      discovery.dispose();
    }
```

This warning will be thrown: 

```
Warning: Failed to start DDS: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = ::1, port = 45464
```

And then this exception will be thrown:

```
Oops; flutter has exited unexpectedly: "LateInitializationError: Field '_server@413427471' has not been initialized.".
```

Interestingly, if I attach to the flutter_tools process and setup a breakpoint on `/home/michaellee8/.pub-cache/hosted/pub.dartlang.org/dds-2.0.1/lib/src/dds_impl.dart:73`, flutter_tools won't crash, but then there will be some non-stop:

```
[  +14 ms] Launching a Dart Developer Service (DDS) instance at http://[::1]:0, connecting to VM service at http://[::1]:44237.
[+9273 ms] DDS is listening at http://[::1]:33753/.
[ +115 ms] Launching a Dart Developer Service (DDS) instance at http://[::1]:0, connecting to VM service at http://[::1]:40227.
[+3735 ms] DDS is listening at http://[::1]:45219/.
[  +11 ms] Waiting for a connection from gallery on fuchsia-5254-0063-5e7a... (completed in 14.6s)
[   +1 ms] Caching compiled dill
[ +186 ms] Connecting to service protocol: http://127.0.0.1:45219/
[  +11 ms] Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 47228
[        ] This was attempt #1. Will retry in 0:00:00.100000.
[ +102 ms] Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 47230
[        ] This was attempt #2. Will retry in 0:00:00.200000.
[ +204 ms] Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 47234
[        ] This was attempt #3. Will retry in 0:00:00.400000.
[ +403 ms] Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 47236
[        ] This was attempt #4. Will retry in 0:00:00.800000.
[ +804 ms] Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 47240
[        ] This was attempt #5. Will retry in 0:00:01.600000.
[+1604 ms] Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 47242
```

And hot reload will not work anyway. 

I have also found that even doing `flutter run ` on `qemu-x64` flavour will have produced the above `Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused` error message anway. So there are actually two related bugs here:

1. With launching app with session_control, the DDS won;t start and will crash the flutter_tools process.
2. Even with the original (master) code, the DDS wouldn;t have been started properly and won't accept connection anyway. It just "seems" to be started during the `startApp` process so flutter_tools won't complain yet.

I am still trying to find the problem here, any input would be very welcome.

**Comment by chaselatta** [comment]
@michaellee8 I added a comment to your PR but I'd rather not have the flutter tool know anything about a specific product configuration but rather know what framework is running. There could in the future be other product configurations that are not the workstation that run on the session framework.

**Comment by michaellee8** [comment]
Interesting, it looks like there is a small but impactful bug in dart sdk, in https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/http_headers.dart#L438. When it tries to parse for port number in a ip address, it tries to split the address by the first `:`, and take the later part as the port. This would have been working in ipv4, since the host part of an ipv4 address will not have `:`, but it will break in ipv6, which the host part is consist of multiple `:`. The code here makes the assumption that the address must be ipv4 which is not the case. 

![Screenshot from 2021-06-29 15-24-45](https://user-images.githubusercontent.com/16556558/123757480-9ba58a00-d8f0-11eb-9205-1b6f33a403d4.png)


Interesting ref from golang: https://golang.org/src/net/ip.go?s=15720:15745#L668

btw debugging future/async errors is really hard in dart, stackframe only show the future stack but not the actual caller stack.

**Comment by michaellee8** [comment]
@chaselatta I have submitted a CL here https://dart-review.googlesource.com/c/sdk/+/205280, can you help reviewing it? Thx in advance.

**Comment by michaellee8** [comment]
I have got some progress here, you can see https://youtu.be/XCaNaxVI1hI to see my working code.

**Comment by michaellee8** [comment]
I have some thoughts here. It looks like that fuchsia runs all rlutter apps on the same runner. I have concerns about whether this would be the most secure isolation if third-party apps (think of play store) is introduced into Fuchsia? So far the flutter engine mostly runs trusted code since it is embeeded withing each package in Andorid and iOS, but Flutter apps in Fuchsia ares supposed to use the same flutter runner.

**Comment by michaellee8** [comment]
@nmcain You can use this PR if you want working flutter run on Fuchsia.

https://github.com/flutter/flutter/pull/85450

**Comment by nmcain** [comment]
Thanks!
