### ISSUE TITLE
Does not `flutter build aar` command  support sound null safety ?

### ISSUE THREAD

**Issue by sh4wn** [flutter/flutter#84488]
When i build apk:
```sh
$flutter build apk

outputs "💪 Building with sound null safety 💪"
```

but build aar:
```sh
$ flutter build aar
outputs  "Building without sound null safety"
```

flutter doctor says:

```log
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.57.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@sh4wn 
This was fixed with this issue, https://github.com/flutter/flutter/issues/79956.
Can you try to upgrade to latest stable or master and try again to see if it works ?

**Comment by sh4wn** [comment]
> @sh4wn
> This was fixed with this issue, #79956.
> Can you try to upgrade to latest stable or master and try again to see if it works ?

I have upgrade Flutter to 2.2.2 ,but the problem is still there.

```log
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/bac/DEV/flutter
    • Framework revision d79295af24 (3 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by darshankawar** [comment]
@sh4wn 
The fix I linked earlier seems to be only available on master. I tried running `flutter build aar` on latest master and it showed below as expected:

```
dhs@Dhss-MacBook-Pro macbug % flutter build aar

💪 Building with sound null safety 💪


```

So you'll need to switch to latest master and try again.


<details>
<summary>flutter doctor -v</summary>

```console
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 2.3.0-17.0.pre.366, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.366 at /Users/dhs/Documents/Fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db930ba32f (5 hours ago), 2021-06-14 18:29:03 -0700
    • Engine revision e1d2d4b264
    • Dart version 2.14.0 (build 2.14.0-210.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.106

• No issues found!

```
</details>

I am going ahead and closing this as already fixed and available on master. If you disagree, write in comments and I'll reopen.
