### ISSUE TITLE
`flutter test` stack traces are truncated when `pumpAndSettle` timeouts

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#84966]
Unless otherwise specified, the following examples are executed with `flutter
test`, which has `--chain-stack-traces` [enabled](https://github.com/flutter/flutter/blob/757c3add1470b54fbc7dab8993dc14c7163fde13/packages/flutter_tools/lib/src/test/runner.dart#L127).

(There may be other instances of this problem besides `pumpAndSettle`)

Consider the following:

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';

void main() {
  testWidgets('foo', (tester) async {
    await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        // Infinite animation so [pumpAndSettle] will timeout.
        child: LinearProgressIndicator(),
      ),
    );
    await tester.pumpAndSettle();
  });
}
```

Because a `LinearProgressIndicator` that animates infinitely, `pumpAndSettle` will never terminate. The following is the stack trace for the timeout:

```
The following assertion was thrown running a test:
pumpAndSettle timed out

When the exception was thrown, this was the stack:
#0      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:650:11)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

Observe that the current file is not referenced in this stack trace, which is problematic because it is difficult for users to find the line where the timeout happens.

## More Minimal Repro

The following is a more minimal repro that distils a particular pattern in `TestAsyncUtils.guard`, [used by](https://github.com/flutter/flutter/blob/757c3add1470b54fbc7dab8993dc14c7163fde13/packages/flutter_test/lib/src/widget_tester.dart#L645) `pumpAndSettle` and many other test methods under the hood causes the problem.

```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('repro', (tester) async {
    await problem()
        .then((x) => x, onError: (error, stack) => Future.error(error, stack));
  });
}

Future<void> problem() async {
  await null;
  throw Exception('Some error');
}
```

Error:

```
The following _Exception was thrown running a test:
Exception: Some error

When the exception was thrown, this was the stack:
#0      problem (file:///Users/jiahaog/dev/hello_flutter/test/widget_test.dart:12:3)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

Again, we see that L5 does not appear in the stack trace.

This is the same pattern appearing in `TestAsyncUtils.guard`:

https://github.com/flutter/flutter/blob/757c3add1470b54fbc7dab8993dc14c7163fde13/packages/flutter_test/lib/src/test_async_utils.dart#L114-L120

## Possible Fix

`--chain-stack-traces` is enabled Flutter open source users, but is not enabled internally. It is also not enabled in raw-Dart projects using `package:test` (relevant https://github.com/dart-lang/test/issues/1505).

This proposed fix only works when `--chain-stack-traces` is **disabled**.

Instead of using raw futures, the `TestAsyncUtils.guard` can be changed to use try-catches.

```dart
try {
  resultValue = await result;
  return completionHandler(null, null);
} catch (error, stackTrace) {
  return completionHandler(error, stackTrace);
}
```

To fix the minimal repro above, we would do the following instead:

```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('minimal repro fixed', (tester) async {
    try {
      return await problem();
    } catch (error, stack) {
      return Future.error(error, stack);
    }
  });
}

Future<void> problem() async {
  await null;
  throw Exception('Some error');
}
```

This may be a deeper bug in `package:stack_trace`. 

@natebosch - do you know if there are any plans to stop using `--chain-stack-traces` for `flutter test`? If so, we may be able to move forward with this proposed fix.

## Alternative Fix

Again, this only works when `--chain-stack-traces` is **disabled**.

`TestAsyncUtils.guard` was added a while ago and may already be superseded by the [`unawaited_futures`](https://dart-lang.github.io/linter/lints/unawaited_futures.html) lint, though this is not enabled by default for new Flutter projects.

**Comment by tvolkert** [comment]
@xster was also looking at this I think

ref: https://github.com/dart-lang/sdk/issues/46326

**Comment by darshankawar** [comment]
```
Testing started at 7:23 PM ...
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color test --machine --start-paused test/widget_test.dart

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
pumpAndSettle timed out

When the exception was thrown, this was the stack:
#0      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:650:11)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  foo
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: foo


```

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-17.0.pre.414, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.414 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 757c3add14 (7 hours ago), 2021-06-20 22:29:02 -0400
    • Engine revision 9520bb15b3
    • Dart version 2.14.0 (build 2.14.0-228.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!

```

</details>

**Comment by natebosch** [comment]
> @natebosch - do you know if there are any plans to stop using `--chain-stack-traces` for `flutter test`? If so, we may be able to move forward with this proposed fix.

I don't have any info on plans for `flutter test` flag usage. @jonahwilliams  might.

**Comment by jonahwilliams** [comment]
I enabled the flag to allow rolling flutter test in without breaking expectations. I have no plans to remove it but would happily review a PR that did so

**Comment by jiahaog** [comment]
I don't think we can remove it yet until https://github.com/dart-lang/test/issues/1505 is fixed, or the following will appear in all stack traces:

```
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'pub run test --chain-stack-traces'.
```

**Comment by Gustl22** [comment]
@jiahaog seems like https://github.com/dart-lang/test/issues/1505 is fixed. Any plans to tackle this issue and #89138. Would be much appreciated :) thank you.

**Comment by jiahaog** [comment]
I looked briefly into this and it seems like the prompt telling users to pass `--chain-stack-traces` still appears. I think we would need some way to either propagate this flag when users run it with `flutter test`, or find some other way to disable the message.

**Comment by acoutts** [comment]
Is there any way we can make `--chain-stack-traces` false so we can see the stack traces in our test runs?
