### ISSUE TITLE
Add Mac M1 ARM machines to the prod pool

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#87508]
flutter-devicelab-mac-4 and flutter-devicelab-mac-5 are now in the staging pool as of https://github.com/flutter/flutter/issues/79430.  Promote to the prod pool once all existing tests pass on those machines.

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-4
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-5

Blocked by https://github.com/flutter/flutter/issues/85654.

**Comment by zanderso** [comment]
Sorry for the delayed response. The list from @jmagman lgtm.

**Comment by keyonghan** [comment]
From benchmark point view, this should not be blocked. 
We can view trending charts based on `task name` by simply filtering `arch: m1`.

**Comment by eggfly** [comment]
This is also our team wanted. Please make this last step to support macOS M1 platform on native ARM machine code, looking forward to it. 💪

**Comment by keyonghan** [comment]
Now tests are running in staging pool, but most tests hit pod install error. @jmagman any insight on how to workaround the issue?
```
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout:                Don't forget to include the Crash Report log file under
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout:                DiagnosticReports directory in bug reports.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: 
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: 
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [+3181 ms] Exception: Error running pod install
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] "flutter run" took 5,518ms.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [   +1 ms] 
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:688:9)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #10     main (package:flutter_tools/executable.dart:94:3)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: 
```

**Comment by jmagman** [comment]
It's hitting something like https://github.com/flutter/flutter/issues/70796. On those machines, before the gem install, we'll have to first run:
```
arch -x86_64 sudo gem install ffi
```
Hmm, the tool should be printing that, but I don't see it https://github.com/flutter/flutter/pull/94385.

See also https://stackoverflow.com/a/65334677.

**Comment by keyonghan** [comment]
Tried installing `ffi` before the gem bundle install, it still failed: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/196359aeabbf1620525eac7f6dc32cd7b142767ab762aeb7546e1504bb0aad42/+/build.proto

Then tried uninstall coacopods and reinstall it following https://stackoverflow.com/questions/66644365/cocoapods-on-m1-apple-silicon-fails-with-ffi-wrong-architecture, it failed again: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/43613c2bda68ffbcd0e4679d0a985bd912dd897013a663541a1e389b811da1f7/+/build.proto

BTW: replaced `-x86_64` with `-arm64` for our case.

**Comment by jmagman** [comment]
> BTW: replaced `-x86_64` with `-arm64` for our case.

I think that's the problem, confusingly it needs to be `-x86_64` in our case.

**Comment by godofredoc** [comment]
If this is needed for arm machines I'd suggest that we add it to the salt state packages for M1.

**Comment by keyonghan** [comment]
> > BTW: replaced `-x86_64` with `-arm64` for our case.
> 
> I think that's the problem, confusingly it needs to be `-x86_64` in our case.

Switched to `-arm64` when hitting below error with `-x86_64` ([a new build example](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/90280a016c5aac458167b4f7e27554173620b192a0f6d64f2bfa479bd38d14fb/+/build.prot)):
```
arch: posix_spawnp: gem: Bad CPU type in executable
```
BTW: from the salt side (how we provision devicelab hosts), we have been using `-arm64`.

**Comment by keyonghan** [comment]
> If this is needed for arm machines I'd suggest that we add it to the salt state packages for M1.

These are host only bots maintained by chromium team.

**Comment by godofredoc** [comment]
Is there a way to workaround this? maybe updating the dependency version or something similar? updating dependencies manually will force us to manage the mac machines ourselves.

**Comment by jmagman** [comment]
> BTW: from the salt side (how we provision devicelab hosts), we have been using -arm64.

`-arm64` makes sense, except the `ffi` workaround is to _force_ it to use a x64 binary, because the arm64 variant doesn't work out of the box 

> arch: posix_spawnp: gem: Bad CPU type in executable

That may mean Rosetta isn't installed on that machine?

**Comment by keyonghan** [comment]
Filed a chromium bug to track: [crbug.com/1298673](https://bugs.chromium.org/p/chromium/issues/detail?id=1298673)

**Comment by keyonghan** [comment]
> ```
> $ sudo softwareupdate --install-rosetta --agree-to-license
> ```

With that, the installation parts get through! but we still hitting the pod install error. Anything else we may still missing? Here is the build run: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/fd8b5d9f2ea20d5de984bcc4864ab0ff341f2e398f5db67a8df45144c8eb724f/+/build.proto

**Comment by jmagman** [comment]
Grrr this is so annoying https://github.com/CocoaPods/CocoaPods/issues/9907, our poor users hit similar issues...

There's more hints in https://github.com/CocoaPods/CocoaPods/issues/9907 that may lead you something useable without Rosetta and the `-arch -x86_64` workaround.

**Comment by keyonghan** [comment]
Yeah, you are right. Our bot's ruby shows same info:
```
OS: darwin20
Arch: universal-darwin20
Host CPU: x86_64
Build CPU: x86_64
Target CPU: universal
```

Unfortunately, there is no brew installed on the bot, and I am not able to run `git clone https://github.com/Homebrew/brew.git /opt/homebrew` to install the `brew` either. Seems some restriction on permissions. Followed up in the chromium bug.

**Comment by keyonghan** [comment]
Yeah, it was suggested by chromium team to support a separate ruby version in cipd. Some security process needs to pass through. I will follow up.

**Comment by keyonghan** [comment]
Tried a couple of things:

- Built a M1 Ruby on a M1 bot from source (here we need to specify a `--prefix=<prefix ruby dir>` which will build the new Ruby to the specified `<prefix ruby dir>`)
- Pushed the new Ruby to https://chrome-infra-packages.appspot.com/p/flutter/ruby/mac-arm64/+/
- Ran `LED` to get the new Ruby and tried installing `cocoapods`
  - I have to be careful about the `<prefix ruby dir>`: it needs to be the same as installed from `recipes` side, so I used `/opt/s/w/ir/cache/ruby`, otherwise it will complain when gem installing
```
-bash: <recipe ruby dir>/bin/gem: <prefix ruby dir>/bin/ruby: bad interpreter: No such file or directory
```
  - An led run based on `/opt/s/w/ir/cache/ruby`: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/9544982c95bd93ca577583788268a58531b4b45656619682f5a6704fc9e992ac/+/build.proto, it complains 
```
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
```
From a basic search, this is due to new OS deprecating openssl be default https://stackoverflow.com/questions/37336573/unable-to-require-openssl-install-openssl-and-rebuild-ruby-preferred-or-use-n)

Want to check here to see if this is the right track before digging further /cc @jmagman

**Comment by jmagman** [comment]
While we need to figure out how to get an M1 version of Ruby on these machines, in the meantime we could reduce the M1 test list to the projects that don't have plugins, and therefore don't need to run `pod install`.  That will get us some coverage that M1 is working...
For example, `run_hello_world_ios__compile` should pass (I think) because it has no plugins, but is failing because no iOS devices are tethered?
```
"reason": "Task failed: DeviceException: No connected physical iOS devices found."
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818983061070547841/+/u/run_hello_world_ios__compile/test_stdout

**Comment by jmagman** [comment]
Any of the Android tests should also work, like `run_hello_world_android__compile`, which is failing with:
```
Task result:
{
  "success": false,
  "reason": "Task failed: DeviceException: The ANDROID_SDK_ROOT environment variable is missing. The variable must point to the Android SDK directory containing platform-tools."
}
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818973605315359905/+/u/run_hello_world_android__compile/test_stdout

**Comment by keyonghan** [comment]
Do these two tests `hello_world_android__compile` and `hello_world_ios__compile` need phones? Now they are running in host only mode.

But they have been running with phones on intel bots.

**Comment by jmagman** [comment]
Those should work hostonly...
`hello_world_android__compile` is complaining about `ANDROID_SDK_ROOT`.  
`hello_world_ios__compile` shouldn't need a physical device, but it looks like it is trying to unlock a tethered phone:
https://github.com/flutter/flutter/blob/5bc9340233b5c8e5d52ae9ae6b72b54f4585cc4c/dev/devicelab/lib/tasks/perf_tests.dart#L1267-L1268
Is it possible the ones on intel bots all happen to have a tethered device?

**Comment by keyonghan** [comment]
> Any of the Android tests should also work, like `run_hello_world_android__compile`, which is failing with:
> 
> ```
> Task result:
> {
>   "success": false,
>   "reason": "Task failed: DeviceException: The ANDROID_SDK_ROOT environment variable is missing. The variable must point to the Android SDK directory containing platform-tools."
> }
> ```
> 
> https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818973605315359905/+/u/run_hello_world_android__compile/test_stdout

Android tests is being blocked: https://github.com/flutter/flutter/issues/98532

**Comment by jmagman** [comment]
`Mac_arm64_staging build_ios_framework_module_test` is failing with:
```
stderr: Found "Xcode 12.3, Build version 12C33". Xcode 13 or greater is required to develop for iOS.
```
The staging Xcode version to be updated to match prod 13a233.

**Xcode too old**
Mac_arm64_staging build_ios_framework_module_test
Mac_arm64_staging ios_content_validation_test
Mac_arm64_staging ios_app_with_extensions_test

**Compile test, physical device not found** (should be fixed by https://github.com/flutter/flutter/pull/100571)
Mac_arm64_staging flutter_gallery_ios__compile

**Ruby failures**
Mac_arm64_staging native_ui_tests_macos
Mac_arm64_staging plugin_lint_mac

**ANDROID_SDK_ROOT environment variable is missing**
Mac_arm64_staging integration_test_test

hot_mode_dev_cycle_macos_target__benchmark
flutter_gallery_ios__compile
hello_world_ios__compile
native_ui_tests_macos
native_ui_tests_ios
module_test_ios
build_ios_framework_module_test
plugin_lint_mac
run_release_test
integration_test_test
hello_world_android__compile
ios_app_with_extensions_test
ios_content_validation_test
macos_chrome_dev_mode
build_aar_module_test

**Comment by keyonghan** [comment]
> The staging Xcode version needs to be updated to match prod 13a233.

https://bugs.chromium.org/p/chromium/issues/detail?id=1309183 to request bot upgrade to 12.2 to support xcode 13a233.

**Comment by keyonghan** [comment]
Some updates:
**Configs**
All M1 bots are now with 12.2 and builders are with xcode 13a233 (same as prod).

**Ruby**
Finally have a customized working [arm64 version](https://chrome-infra-packages.appspot.com/p/flutter/ruby/mac-arm64/+/P1b-yT8l6N4J6TbVI5fJDqmbWIKP6WhKcLfITjWZ2ZEC). (do be submitted in recipes)

**Validation**
Now we have three issues (after running on latest configs):

- No android 
  - [Mac_arm64_staging hello_world_android__compile](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20hello_world_android__compile/366/overview)
  - [Mac_arm64_staging integration_test_test](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20integration_test_test/366/overview)
  - [Mac_arm64_staging run_release_test](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20run_release_test/366/overview)
- Pod install issue
  - Mac_arm64_staging hot_mode_dev_cycle_macos_target__benchmark ([before arm64 ruby](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20hot_mode_dev_cycle_macos_target__benchmark/368/overview), [with arm64 ruby](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b64f327e5cfcccab4e4bb6d16d9fccfa0ec3455f13cdff07ff4dfcbe28d80ac2/+/build.proto) - success)
  - Mac_arm64_staging native_ui_tests_macos ([before arm64 ruby](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20native_ui_tests_macos/364/blamelist), [with arm64 ruby](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/e33c752d0157e40e23fe702b1df0818a3d1e7799b294fc1f8aa3ee6fc1fb64d5/+/build.proto) - failure, https://github.com/flutter/flutter/issues/100636)
  - Mac_arm64_staging build_ios_framework_module_test ([before arm64 ruby](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20build_ios_framework_module_test/365/overview), [with arm64 ruby](https://chromium-swarm.appspot.com/task?id=59cdd5ab7a577b10), failure, https://github.com/flutter/flutter/issues/100637)
  - Mac_arm64_staging plugin_lint_mac ([before arm64 ruby](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20plugin_lint_mac/366/overview), [with arm64 ruby](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/74c2c0b1de7440efecaa0796e7dcb386aad3563310fb202b41ac08f62e829084/+/build.proto), failure, https://github.com/flutter/flutter/issues/100638)
  - Mac_arm64_staging ios_app_with_extensions_test ([before arm64 ruby](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20ios_app_with_extensions_test/367/overview)  , [with arm64 ruby](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/55d7f92dd27aea6758ff7295016c73072f14e18457fd5aed5c9d54ad987afc15/+/build.proto), hit code signing issue)
- iOS simulator without code signing, https://github.com/flutter/flutter/issues/100639
  - [Mac_arm64_staging flutter_gallery_ios__compile](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20flutter_gallery_ios__compile/365/overview)
  - [Mac_arm64_staging hello_world_ios__compile](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20hello_world_ios__compile/367/overview)
  - [Mac_arm64_staging native_ui_tests_ios](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20native_ui_tests_ios/366/overview)
  - [Mac_arm64_staging module_test_ios](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20module_test_ios/365/overview)  
  - [Mac_arm64_staging ios_content_validation_test](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20ios_content_validation_test/368/overview)

**Comment by jmagman** [comment]
Wow @keyonghan looks like you got a lot of these passing now. Could we move the passing ones over to prod?

**Passing:**
[hot_mode_dev_cycle_macos_target__benchmark](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20hot_mode_dev_cycle_macos_target__benchmark/490)
[flutter_gallery_ios__compile](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20flutter_gallery_ios__compile/486)
[hello_world_ios__compile](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20hello_world_ios__compile/488)
[native_ui_tests_ios](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20native_ui_tests_ios/490)
[module_test_ios](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20module_test_ios/488)
[build_ios_framework_module_test](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20build_ios_framework_module_test/488)
[run_release_test_macos](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20run_release_test_macos/121)
[ios_app_with_extensions_test](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20ios_app_with_extensions_test/491)
[ios_content_validation_test](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20ios_content_validation_test/492)
[macos_chrome_dev_mode](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20macos_chrome_dev_mode/486)

Failing
[native_ui_tests_macos](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20native_ui_tests_macos/485)
[plugin_lint_mac](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20plugin_lint_mac/489)
[run_release_test](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20run_release_test/488)
[integration_test_test](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20integration_test_test/491)
[hello_world_android__compile](https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_arm64_staging%20hello_world_android__compile/488)

**Comment by keyonghan** [comment]
It turns out that we have been using intel built python (https://github.com/flutter/flutter/issues/98057) to run the swarming server, which schedules/runs our builds.

At this moment, I have manually brought up mac41 and mac42 in staging to run and pass these tests. But we need to enable these changes in our `salt` so that it can provision all bots with same python+pyobjc. As of now, these two bots may get back to old non-working python version if a salt refresh happens.

Working on a CL to push the salt change.

**Comment by keyonghan** [comment]
> Could we move the passing ones over to prod?

I prefer to hold on this before we have a stable working python on the bots.

**Comment by jmagman** [comment]
@keyonghan can we also add `Mac tool_integration_tests_*` and `Mac tool_tests_commands` to `Mac_arm64`?
/cc @christopherfujino

**Comment by jmagman** [comment]
> @keyonghan can we also add `Mac tool_integration_tests_*` and `Mac tool_tests_commands` to `Mac_arm64`?

@christopherfujino do you agree with adding these shards? You expressed concerns that only a subset of these probably need to run on arm64, and you didn't want the extra noise of double the flaky reports.

**Comment by christopherfujino** [comment]
> > @keyonghan can we also add `Mac tool_integration_tests_*` and `Mac tool_tests_commands` to `Mac_arm64`?
> 
> @christopherfujino do you agree with adding these shards? You expressed concerns that only a subset of these probably need to run on arm64, and you didn't want the extra noise of double the flaky reports.

started an internal chat thread to discuss

**Comment by keyonghan** [comment]
There are still 6 Mac/ios tests failing consistently:

- [ ] `Mac_arm64_staging native_ui_tests_macos`: Platform unit tests failed (https://github.com/flutter/flutter/issues/101721)
- [ ] `Mac_arm64_staging module_test_ios`: Platform unit tests failed (https://github.com/flutter/flutter/issues/101722)
- [ ] No android SDK found for `Mac_arm64_staging plugin_lint_mac`, `Mac_arm64_staging run_release_test`, `Mac_arm64_staging integration_test_test`, and `Mac_arm64_staging hello_world_android__compile`.

/cc @jmagman could you help take a look at the first two?

**Comment by keyonghan** [comment]
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4673717 to add half M1/ios test beds to prod, with which we can migrate those passing tests. /cc @jmagman (somehow I cannot add you to the CL as a reviewer. Maybe because you have never touched that repo before)

**Comment by jmagman** [comment]
@keyonghan some are failing with the Ruby ffi error again:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8817040220041221425/+/u/run_module_test_ios/test_stdout

**Comment by jmagman** [comment]
@keyonghan what happened with your attempts to install x86 version of the `ffi` gem? That should resolve the `ffi` error.
https://github.com/flutter/flutter/issues/87508#issuecomment-1041062441

**Comment by keyonghan** [comment]
Four tests are still failing:

- [ ] Mac_arm64_staging module_test_ios fails with Platform unit tests failed, https://github.com/flutter/flutter/issues/101722
- [ ] Mac arm64 test native_ui_tests_macos fails with Platform unit tests failed, https://github.com/flutter/flutter/issues/101721#
- [ ] Mac_arm64_staging plugin_lint_mac failed with xcodebuild failure, https://github.com/flutter/flutter/issues/102108

**Comment by keyonghan** [comment]
All requested tests have been available and running in prod. To sum up:

Enabled arm64 android tests:
- hello_world_android__compile
- integration_test_test
- run_release_test

Enabled arm64 ios tests:
- build_ios_framework_module_test
- module_test_ios
- plugin_lint_mac
- flutter_gallery_ios__compile
- hello_world_ios__compile
- hot_mode_dev_cycle_macos_target__benchmark
- ios_app_with_extensions_test
- ios_content_validation_test
- macos_chrome_dev_mode
- run_release_test_macos

Marking this as fixed.
