### ISSUE TITLE
Mac_staging plugin_test_ios keeps failing in staging

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88794]
`Mac_staging plugin_test_ios` was recently enabled in staging, but keeps failing with the following log.

Related: https://github.com/flutter/flutter/issues/86802
Example build: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_staging%20plugin_test_ios/58/overview

Seems we need a higher version of xcode:
```
[plugin_test_ios] [STDOUT] stderr: [  +20 ms] Found "Xcode 12.0, Build version 12A7209". Xcode 12.0.1 or greater is required to develop for iOS.
[plugin_test_ios] [STDOUT] stdout: [   +3 ms] "flutter ios" took 5,064ms.
[plugin_test_ios] [STDOUT] stderr: [   +3 ms] Encountered error while building for device.
[plugin_test_ios] [STDOUT] stderr: [        ] 
[plugin_test_ios] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[plugin_test_ios] [STDOUT] stderr:            #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:277:7)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #10     main (package:flutter_tools/executable.dart:92:3)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
```

**Comment by keyonghan** [comment]
which xcode version shall we use here? /cc @jmagman @stuartmorgan

**Comment by jmagman** [comment]
@keyonghan 
12c* https://github.com/flutter/infra/pull/358

The engine needs a different version than the other builders.  Maybe we need an extra tag on the Xcode cipd package to make that clearer?

**Comment by keyonghan** [comment]
Thanks. Yeah, seems now we use only specific version numbers. It would be helpful at least we put notes somewhere (not sure if we already have that info somewhere though).

I will submit a cl to include the 12c version.

**Comment by keyonghan** [comment]
Does this test need a device?

```
[plugin_test_ios] [STDOUT] stdout: [   +5 ms] executing: security find-identity -p codesigning -v
[plugin_test_ios] [STDOUT] stdout: [  +21 ms]      0 valid identities found
[plugin_test_ios] [STDOUT] stderr: [   +3 ms] ════════════════════════════════════════════════════════════════════════════════
[plugin_test_ios] [STDOUT] stderr:            No valid code signing certificates were found
[plugin_test_ios] [STDOUT] stderr:            You can connect to your Apple Developer account by signing in with your Apple ID
[plugin_test_ios] [STDOUT] stderr:            in Xcode and create an iOS Development Certificate as well as a Provisioning 
[plugin_test_ios] [STDOUT] stderr:            Profile for your project by:
[plugin_test_ios] [STDOUT] stderr:              1- Open the Flutter project's Xcode target with
[plugin_test_ios] [STDOUT] stderr:                   open ios/Runner.xcworkspace
[plugin_test_ios] [STDOUT] stderr:              2- Select the 'Runner' project in the navigator then the 'Runner' target
[plugin_test_ios] [STDOUT] stderr:                 in the project settings
[plugin_test_ios] [STDOUT] stderr:              3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
[plugin_test_ios] [STDOUT] stderr:                 You may need to:
[plugin_test_ios] [STDOUT] stderr:                     - Log in with your Apple ID in Xcode first
[plugin_test_ios] [STDOUT] stderr:                     - Ensure you have a valid unique Bundle ID
[plugin_test_ios] [STDOUT] stderr:                     - Register your device with your Apple Developer Account
[plugin_test_ios] [STDOUT] stderr:                     - Let Xcode automatically provision a profile for your app
[plugin_test_ios] [STDOUT] stderr:              4- Build or run your project again
[plugin_test_ios] [STDOUT] stderr:              5- Trust your newly created Development Certificate on your iOS device
[plugin_test_ios] [STDOUT] stderr:                 via Settings > General > Device Management > [your new certificate] > Trust
[plugin_test_ios] [STDOUT] stderr: 
[plugin_test_ios] [STDOUT] stderr:            For more information, please visit:
[plugin_test_ios] [STDOUT] stderr:              https://developer.apple.com/library/content/documentation/IDEs/Conceptual/
[plugin_test_ios] [STDOUT] stderr:              AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html
[plugin_test_ios] [STDOUT] stderr: 
[plugin_test_ios] [STDOUT] stderr:            Or run on an iOS simulator without code signing
[plugin_test_ios] [STDOUT] stderr:            ════════════════════════════════════════════════════════════════════════════════
[plugin_test_ios] [STDOUT] stdout: [   +3 ms] "flutter ios" took 6,186ms.
[plugin_test_ios] [STDOUT] stderr: [   +3 ms] No development certificates available to code sign app for device deployment
[plugin_test_ios] [STDOUT] stderr: [        ] 
[plugin_test_ios] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[plugin_test_ios] [STDOUT] stderr:            #1      _chooseSigningIdentity (package:flutter_tools/src/ios/code_signing.dart:217:5)
[plugin_test_ios] [STDOUT] stderr:            #2      getCodeSigningIdentityDevelopmentTeam (package:flutter_tools/src/ios/code_signing.dart:153:41)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:188:26)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #4      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:264:37)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr:            #13     main (package:flutter_tools/executable.dart:92:3)
[plugin_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[plugin_test_ios] [STDOUT] stderr: 
[plugin_test_ios] [STDOUT] stderr: 
```

**Comment by jmagman** [comment]
I guess this was only ever run in the devicelab which has the provisioning profiles set up.  That test is missing a `--no-codesign`.  I'll put that out for review (sorry about that!)

**Comment by jmagman** [comment]
I'm able to reproduce this.  It's only on the macOS part of the test  It only happens when the app is built right before `flutter test` is run.  If I comment out the `app.build(buildTarget)` lines the tests pass.
https://github.com/flutter/flutter/blob/413f88f20906dbb1f7da85f0349996e6138222b9/dev/devicelab/lib/tasks/plugin_tests.dart#L53-L56

**Comment by jmagman** [comment]
When it works the `PACKAGE_CONFIG` is `.packages`.  When it fails, the `PACKAGE_CONFIG` is `/absolute/path/to/plugintestapp/.dart_tool/package_config.json`.

**Comment by stuartmorgan** [comment]
> It only happens when the app is built right before `flutter test` is run. If I comment out the `app.build(buildTarget)` lines the tests pass.

Does the app include path_provider by any chance? This sounds suspiciously like https://github.com/flutter/flutter/pull/87991#issuecomment-900412165

**Comment by jmagman** [comment]
> Does the app include path_provider by any chance?

Wow, yes it does!

https://github.com/flutter/flutter/blob/413f88f20906dbb1f7da85f0349996e6138222b9/dev/devicelab/lib/tasks/plugin_tests.dart#L52

**Comment by stuartmorgan** [comment]
I'm hoping to get back to that PR soon; fixing that issue is the remaining work to unblock it.

**Comment by bsr203** [comment]
Hi. Just wanted to leave a comment as a search in the repo gave similar error. All my tests are failing after upgrading to latest flutter.

```
$ flutter test test/model
00:02 +0: .../test/model/modelx_test.dart     Shell: [D]  AppLoad()
Shell: [D]  AppLoad()
00:03 +0: .../test/model/modelx_test.dart     Shell: getStoreState
Shell: getStoreState
Shell: [D]  Bloc Transition {  event: AppLoad()
Shell: [D]  Bloc Transition {  event: AppLoad()
00:03 +0 -1: loading /Users/xyz/test/model/model_test.dart [E]
  Failed to load "/Users/xyz/test/model/model_test.dart": Shell subprocess ended cleanly. Did main() call exit()?
00:03 +0 -2: loading /Users/xyz/test/model/modelx_test.dart [E]
  Failed to load "/Users/xyz/test/model/modelx_test.dart": Shell subprocess ended cleanly. Did main() call exit()?
00:03 +0 -2: Some tests failed.   
```

hope the root case is same.

**Comment by stuartmorgan** [comment]
@bsr203 Are you building for a desktop platform?

**Comment by bsr203** [comment]
thanks for getting back so quick. Well, I have enabled android, ios, web and macOS. I develop in macOS as it is faster to load. Is that what you mean?

**Comment by stuartmorgan** [comment]
Yes, if you are building for macOS you are probably hitting this error. You can check by finding the `generated_main.dart` file in your build directory and deleting it, then running the tests again. If it works, then it's this problem.

**Comment by bsr203** [comment]
yup

```
~/work/xyz on master [!]
$ find . -name generated_main.dart
./.dart_tool/flutter_build/generated_main.dart

~/work/xyz on master [!]
$ rm ./.dart_tool/flutter_build/generated_main.dart

~/work/xyz on master [!]
$ flutter test test/model
00:04 +49: All tests passed!      
```
Hurray !!!

thank you.

**Comment by stuartmorgan** [comment]
@jmagman @keyonghan This test should be able to move out of staging now that my fix landed.

**Comment by keyonghan** [comment]
Seems recent commits after the fix are still failing: https://ci.chromium.org/p/flutter/builders/staging/Mac_staging%20plugin_test_ios

**Comment by stuartmorgan** [comment]
That's a new unrelated failure:
```
 Task result:
 {
   "success": false,
   "reason": "Update this test to match plugin minimum ios deployment version"
 }
```

I'll restore the original issue title and re-open.

**Comment by keyonghan** [comment]
> That's a new unrelated failure:
> 
> ```
>  Task result:
>  {
>    "success": false,
>    "reason": "Update this test to match plugin minimum ios deployment version"
>  }
> ```
> 
> I'll restore the original issue title and re-open.

FWIW: checked commits prior to the above fix, this error seems have been there consistently for a while.

**Comment by jmagman** [comment]
Another one: https://github.com/flutter/flutter/pull/91324

**Comment by jmagman** [comment]
It went green! https://ci.chromium.org/p/flutter/builders/staging/Mac_staging%20plugin_test_ios/451

@keyonghan How can we move this into prod?
