### ISSUE TITLE
[camera] Orientation issues for the camera and the taken file

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#89216]
After 0.9.0 there are a lot of orientation issues have been solved, but we still got a few:

- [ ] Unable to get the orientation during the rotation if the *Auto rotate* is locked in the system.
- [ ] Unable to get the orientation of the captured file.

## Steps to Reproduce

1. Run the example of the camera plugin.
2. Lock the *Auto rotate* for the device.
3. Take a new photo.
4. (Optional) Run [the example of the `wechat_camera_picker` plugin](https://github.com/fluttercandies/flutter_wechat_camera_picker) which is more clear about what happened.

**Actual results:**

Below screenshots are all taken with landscape:

| Capture with rotated | Capture with rotated | Preview after captured |
| ---- | ---- | ---- |
| ![image](https://user-images.githubusercontent.com/15884415/131508390-97356b42-f886-421a-a47e-da1f6c7be9cc.png) | ![image](https://user-images.githubusercontent.com/15884415/131508492-fc6aa7de-cc48-473c-9ba9-69c9c873d26b.png) | ![image](https://user-images.githubusercontent.com/15884415/131508539-c792d797-ca65-4939-97ae-2516efab3657.png) |

**Comment by AlexV525** [comment]
cc @BeMacized

**Comment by BeMacized** [comment]
> cc @BeMacized

I'd love to take a further look into this, but sadly I don't think I have the hours available to do so currently.

**Comment by AlexV525** [comment]
> I don't think I have the hours available to do so currently.

Take your time, there are some alternative solutions like use some other sensor plugin to integrate along with this plugin, but those are not good for nested controls.

**Comment by AlexV525** [comment]
Added a new issue about the orientation in the top comment, which is related with iOS.

**Comment by behlsoft** [comment]
camera: 0.9.3

Hey Team am facing issue in iOS only .. where user's phone auto rotation is ON/Unlocked and orientation of camera screen is set to 
SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);

in iphone now if user changes phone's orientation to landscape, camera orientation also changes ..nothing else (no other widgets). In addition to this if autorotation is locked all goes well no orientation change. When it comes to android everything seems fine no change in camera or widgets orientation in both cases ..auto-rotation locked or not

**Comment by BeMacized** [comment]
I've taken a quick look and have some thoughts: 

#### Unable to get the orientation during the rotation if the Auto rotate is locked in the system.
Not 100% sure, but from what I understand this _should_ be correct. Since 0.9.0, the `deviceOrientation` property is supposed to only reflect the UI orientation, rather than the physical orientation. As such, when auto rotate is locked, `deviceOrientation` reflects the same UI orientation, regardless of in which way the device is held.

#### Preview is rotated with orientations even if the device is not support for those orientations on iOS.
There is a bug here. It seems the preview rotation functions correctly when the orientation is locked either using the system lock, or the capture orientation lock, but fails when locking the orientation using `SystemChrome.setPreferredOrientations`. 
From what I gather, the notifications on iOS for `UIDeviceOrientationDidChangeNotification`, report all orientations when using `setPreferredOrientations`, which is incorrect. What should happen, is that only the UI orientation is reported, like when the system orientation lock is active. 
I am currently not yet sure how to fix this. From what it looks like it's not possible to query SystemChrome for its current configuration, that could maybe be used to filter the orientations on the dart side. I'll continue to search, but if anyone has a clue, help would be appreciated. 

#### Unable to get the orientation of the captured file.
This indeed looks incorrect. I think captures should always be rotated according to the physical orientation of the device, unless this is overridden by the capture orientation lock. I haven't looked into why this is happening yet, but I'll see if I can produce a fix for this.

**Comment by AbhishekDoshi26** [comment]
This issue has been already added: https://github.com/flutter/flutter/issues/80881 and here's the PR for the same: https://github.com/flutter/plugins/pull/3970#issuecomment-920023879
Just need someone to write the test cases :)

**Comment by stijnie2210** [comment]
Any news on this? I've ran into this on a project recently described in the issue above and the fact I cannot get the physical orientation on Android but I can on iOS is pretty blocking at the moment

**Comment by hassank1** [comment]
Hi! I would also like to know if there are any solutions to this problem. I am also experiencing this problem only on IOS.

**Comment by AntoineChauviere** [comment]
Any solutions or updates? 
Currently I can lock the camera on android but not on iOS....

**Comment by hassank1** [comment]
You can find more up-to-date information about this issue in #111063. But no solution has been found yet.

**Comment by AntoineChauviere** [comment]
OK thanks. So currently there is no way to lock the camera to prevent it from turning in landscape mode...?

**Comment by camsim99** [comment]
> /cc @camsim99 Maybe you can take this issue? This actually makes the camera unavailable in relevant cases.

In terms of Android, it seems like you can access the orientation via the `CameraValue`. Is there another problem with the Android camera plugin concerning this issue?

**Comment by AlexV525** [comment]
> In terms of Android, it seems like you can access the orientation via the `CameraValue`. Is there another problem with the Android camera plugin concerning this issue?

They are all invalid in the cases I've described above, especially when the orientation lock is locked. The current behavior is not like any real-world cameras.

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin, so please try it out!

If you find a similar issue with that implementation (or any other issues), please feel free to file a separate issue.

**Comment by orestesgaolin** [comment]
I'm still having issues with image showing at incorrect orientation when capturing with camera plugin `0.11.0` (using camerax) on Android 14 with Flutter 3.22.1.

Please see attached video, the resulting image is rotated anti-clockwise compared to the orientation.

https://github.com/flutter/flutter/assets/16854239/56fd6578-7424-49ae-a68e-9ea7f4824241


My pseudo-code implementation is:

```dart
final xFile = await cameraController.takePicture();
final file = File(path);
if (xFile == null) {
  throw Exception('XFile provided by camera controller is null');
}

await file.writeAsBytes(await xFile.readAsBytes());
if (file.existsSync()) {
  return file;
} else {
  logger.w('Picture file does not exist');
  return null;
}
```

The image is then previewed in:

```dart
Image.file(
  output.file,
  fit: BoxFit.cover,
),
```


After some tinkering I was able to achieve it with manual call to `await cameraController.lockCaptureOrientation();`, but the documentation claims it's using device orientation anyways.

**Comment by lutsenko92** [comment]
Please will fix it on ios

**Comment by xinhc-yuanye** [comment]
if this issue has been fixed？

**Comment by bombicod** [comment]
> Please will fix it on ios

https://github.com/flutter/flutter/issues/111063#issuecomment-1876698275

**Comment by Vadaski** [comment]
Any updates？ Still can repoduce this issue at Flutter 3.27.4

**Comment by balint-kada** [comment]
i have made a pretty reliable workaround, that is in the case of using both SystemChrome.setPreferredOrientations and also using cameraController.lockCaptureOrientation and locking the camera to portraitUp, while using native device orientation for handling the output file orientation!

here are the codes for the fix: 
`
// Preview widget: 

class _CameraPreview extends StatelessWidget {
  const _CameraPreview(this.controller);

  final CameraController controller;

  @override
  Widget build(BuildContext context) {
    return controller.value.isInitialized
        ? ValueListenableBuilder<CameraValue>(
            valueListenable: controller,
            builder: (BuildContext context, Object? value, Widget? child) {
              if (!controller.value.isInitialized ||
                  controller.value.previewSize == null) {
                return const SizedBox.shrink();
              }
              return SizedBox.expand(
                child: FittedBox(
                  fit: BoxFit.cover,
                  clipBehavior: Clip.hardEdge,
                  child: SizedBox(
                    width: _isLandscape()
                        ? controller.value.previewSize!.width
                        : controller.value.previewSize!.height,
                    height: _isLandscape()
                        ? controller.value.previewSize!.height
                        : controller.value.previewSize!.width,
                    child: controller.buildPreview(),
                  ),
                ),
              );
            },
          )
        : Container();
  }

  bool _isLandscape() {
    return <DeviceOrientation>[
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ].contains(_getApplicableOrientation());
  }

  // Since capture orientation is locked to portraitUp (via both
  // lockCaptureOrientation and SystemChrome.setPreferredOrientations),
  // always treat the preview as portrait so SizedBox dimensions stay
  // consistent when controller.value.deviceOrientation updates with the
  // physical device rotation on iOS.
  DeviceOrientation _getApplicableOrientation() {
    return DeviceOrientation.portraitUp;
  }
}


// Setting preferred orientation in widget:
@override
  void initState() {
    super.initState();
    if (!kIsWeb) {
      unawaited(
        SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]),
      );
    }

  }

  
  @override
  void dispose() {
    if (!kIsWeb) {
      unawaited(SystemChrome.setPreferredOrientations([]));
    }
     super.dispose();
  }


// Handling camera controller locking after initialization: 
await controller.initialize();

      // Lock capture orientation to portraitUp so stream-frame metadata is
      // consistent.
      // On iOS and Android this keeps ML Kit bounding-box coordinates stable.
      if (!CameraUtils.isWeb && (Platform.isIOS || Platform.isAndroid)) {
        try {
          await controller.lockCaptureOrientation(DeviceOrientation.portraitUp);
        } on Exception catch (_) {}
      }

// Handling capturing image and baking in correct orientation into EXIF data:
final controller = state.cameraController;
    if (controller == null || !controller.value.isInitialized) return;
    if (controller.value.isTakingPicture) return;

    try {
      // Stop image stream if running (required on Android before takePicture)
      if (controller.value.isStreamingImages) {
        await controller.stopImageStream();
      }

      // 1. Emit Capturing State (Shows Black Mask UI)
      emit(state.copyWith(status: CameraStatus.capturing));

      // Small delay to allow the UI to paint the masking overlay
      await Future.delayed(
        const Duration(milliseconds: _captureMaskDelayMs),
        () {},
      );

      // Lock Orientation
      // Ensures the saved file has the correct EXIF tag (e.g., Rotation 90).
      if (!CameraUtils.isWeb && (Platform.isAndroid || Platform.isIOS)) {
        await controller.lockCaptureOrientation(event.orientation);
      }

      var file = await controller.takePicture();

      // 4. Restore orientation
      // On iOS lock back to portraitUp for consistent stream metadata.
      // On Android simply unlock.
      if (!CameraUtils.isWeb && (Platform.isAndroid || Platform.isIOS)) {
        await controller.lockCaptureOrientation(DeviceOrientation.portraitUp);
      }

      // 5. Post-Process (Bake Orientation)
      // On iOS, we bake the EXIF rotation into the pixels.
      // This makes the image physically upright (Orientation 1),
      // so ML Kit works correctly.
      if (!CameraUtils.isWeb && Platform.isIOS) {
        file = await ImageFixer.fixOrientation(file.path);
      }
`

i hope this fixed the issues for you guys also. i only tested on capturing photo, since i have that use case, not sure if it's correctly working with videos also.
