### ISSUE TITLE
Double cursor using iOS floating cursor (keyboard cursor move with spacebar)

### ISSUE THREAD

**Issue by Curvel** [flutter/flutter#89228]
I created this Issue for the [last bug](https://github.com/flutter/flutter/issues/17030#issuecomment-803130790) described in #17030, which we also just encountered, because the #17030 got closed. 

## Steps to Reproduce

OS: iOs and iPadOS

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

Enter so much text into the TextField, that the TextField starts scrolling. Then try to scroll with two fingers, on the spacebar, horizontally through the text.

**Expected results:** The curser moves with the fingers and scrolls horizontal through the TextField.

**Actual results:** A second curser appears, which moves separately to the original curser, and the TextField doesn't scroll horizontally.

<details>
  <summary>Logs</summary>

```

[+18718 ms] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2820c7700 h=--& v=--& _UIButtonBarButton:0x10888cf40.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f8aa0 _UIUCBKBSelectionBackground:0x10888d860.bottom == _UIButtonBarButton:0x10888cf40.bottom - 6   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f88c0 V:|-(6)-[_UIUCBKBSelectionBackground:0x10888d860]   (active, names: '|':_UIButtonBarButton:0x10888cf40 )>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2820f8aa0 _UIUCBKBSelectionBackground:0x10888d860.bottom == _UIButtonBarButton:0x10888cf40.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2820fb610 h=--& v=--& _UIButtonBarButton:0x10888b3c0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f82d0 V:|-(6)-[_UIUCBKBSelectionBackground:0x10888bc60]   (active, names: '|':_UIButtonBarButton:0x10888b3c0 )>",
[        ]     "<NSLayoutConstraint:0x2820fbe30 _UIUCBKBSelectionBackground:0x10888bc60.bottom == _UIButtonBarButton:0x10888b3c0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2820fbe30 _UIUCBKBSelectionBackground:0x10888bc60.bottom == _UIButtonBarButton:0x10888b3c0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2820f8a50 h=--& v=--& _UIButtonBarButton:0x10888bde0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f8dc0 V:|-(6)-[_UIUCBKBSelectionBackground:0x10888c5e0]   (active, names: '|':_UIButtonBarButton:0x10888bde0 )>",
[        ]     "<NSLayoutConstraint:0x2820f8d70 _UIUCBKBSelectionBackground:0x10888c5e0.bottom == _UIButtonBarButton:0x10888bde0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2820f8d70 _UIUCBKBSelectionBackground:0x10888c5e0.bottom == _UIButtonBarButton:0x10888bde0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.


```
```

Analyzing bug...                                                        
No issues found! (ran in 3.5s)

```
```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.2.3 at /Users/curvel/dev/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/curvel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Curvel’s iPad (mobile) • 00008027-001E08420C22002E            • ios            • iOS 14.6
    • iPhone 12 (mobile)     • AB9878B8-38E4-4250-B538-BAA98837CFA5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

```

**Comment by danagbemava-nc** [comment]
Hi @Curvel, thanks for filing the issue. 
I can reproduce it on `master 2.6.0-1.0.pre.152` and `stable 2.2.3`. 

The issue can be seen with both `CupertinoTextField` and `TextField` widgets. 

See attached images below: 


| CupertinoTextField | TextField |
|------------------- | ----------|
|![IMG_2884](https://user-images.githubusercontent.com/88313112/131626669-ba19fab0-d6f0-4449-9a11-98c6dd0be822.PNG)| ![IMG_2885](https://user-images.githubusercontent.com/88313112/131626657-b1d9c23f-87ba-49bc-b7a6-fe9efadc0244.PNG)|
| ![IMG_2883](https://user-images.githubusercontent.com/88313112/131626672-b8a1caee-7948-413e-b9d3-2ae09558dd3d.PNG)|![IMG_2882](https://user-images.githubusercontent.com/88313112/131626677-0d0a2d8e-9a00-4b3d-9771-7e9cf2592123.PNG)|

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.152, on macOS 11.5.1 20G80
    darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.152 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56c5f13035 (4 hours ago), 2021-08-31 23:26:02 -0400
    • Engine revision aab40c8d5d
    • Dart version 2.15.0 (build 2.15.0-66.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6 18F72
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.159

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.159

• No issues found!
```
</details>

**Comment by Curvel** [comment]
@danagbemava-nc thanks for classifying the issue. Could you tell me which priority an issue like this one has for your team?

**Comment by danagbemava-nc** [comment]
Hi @Curvel, unfortunately that isn't information I can provide at this moment. The issue needs to go through secondary triage before the appropriate priority label can be applied.

**Comment by Curvel** [comment]
Okay. @danagbemava-nc thanks for your response :)

**Comment by justinmc** [comment]
CC @LongCatIsLooong, possible fixed by your upcoming cursor refactor.

**Comment by nilscc** [comment]
In 3.7.3 this issue is still there, at least on the single line text field. Unfortunately I don't have a Mac to debug this. :(

**Comment by gnprice** [comment]
There are two different symptoms here, which sound like probably separate issues that will have separate fixes:

> A second curser appears, which moves separately to the original curser,

> and the TextField doesn't scroll horizontally.

I've retitled this thread to focus on the first issue, because that's the one demonstrated by @danagbemava-nc's handy screenshots above at https://github.com/flutter/flutter/issues/89228#issuecomment-910001376 . I'll file the other as a separate issue pointing to this one.

**Comment by gnprice** [comment]
One observation on the double-cursor issue:

I actually see similar behavior in a native iOS app, but only in a limited way. There,
* when I use the dragging-the-keyboard cursor (what we sometimes call the "floating cursor"),
* if I drag to a point where there isn't actually any text — like off the end of a line —
* then in addition to the cursor I'm dragging, which is in a themed color like yellow, I also see a second cursor in gray.
* That second cursor marks the spot where the cursor would actually land if I released my finger there ­— e.g. it's at the end of the line, when the cursor I'm dragging is off to the right beyond the end of the line.

What's different in Flutter's behavior is that the gray "where the cursor would actually land if you let go right now" cursor is always present, even when the highlighted continuously-dragged cursor is right over some text and so the gray cursor is right next to it, less than a character's width away. In that circumstance, the gray cursor is just noise and doesn't add anything, and it'd be good to suppress it like iOS does.

I guess in two of @danagbemava-nc's screenshots above (the ones in single-line inputs), the gray cursor is *far* away from the highlighted cursor, and for no good reason because there's text right under the highlighted cursor too. I don't seem to reproduce that issue now. If it does still reproduce for someone, it would probably make sense to file as a separate issue.

**Comment by justinmc** [comment]
FYI @moffatman since you recently merged a floating cursor PR (https://github.com/flutter/engine/pull/36643).
