### ISSUE TITLE
flutter run --> chmod error

### ISSUE THREAD

**Issue by erythana** [flutter/flutter#90137]
## Steps to Reproduce
"flutter run" in my project directory

```
[chris@chris-Linux rearviewcam]$ flutter run
Launching lib/main.dart on SM A515F in debug mode...
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/AssetManifest.json': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/FontManifest.json': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/fonts': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/fonts/MaterialIcons-Regular.otf': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/isolate_snapshot_data': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/kernel_blob.bin': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/NOTICES.Z': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/packages': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/packages/cupertino_icons': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/packages/cupertino_icons/assets': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf': Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für '/run/media/chris/Fast-Storage/Programming/rearviewcam/build/app/intermediates/flutter/debug/flutter_assets/vm_snapshot_data': Die Operation ist nicht erlaubt

FAILURE: Build failed with an exception.

* Where:
Script '/home/chris/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 752

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'chmod'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...                              3,9s
Exception: Gradle task assembleDebug failed with exit code 1

```
flutter doctor -v
```
[chris@chris-Linux rearviewcam]$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on Manjaro Linux 5.13.13-1-MANJARO, locale de_AT.UTF-8)
    • Flutter version 2.5.0 at /home/chris/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (vor 8 Tagen), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/chris/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/chris/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/chris/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • SM A515F (mobile) • R58N92TMFZA • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux       • linux-x64      • Manjaro Linux 5.13.13-1-MANJARO
    • Chrome (web)      • chrome      • web-javascript • Chromium 93.0.4577.63 Arch Linux

• No issues found!
```

</details>

Hello,
new to flutter. When trying to run my fresh created project i get the error message tsaying "chmod: error setting permissions for 'path' - Operation not allowed"
I already tried to set the permission to 777 on one of these directories to see if that resolves that but unfortunately, still the same error.
Appreciate help

Edit: It works when i place it somewhere in my home drive, for example. I don't get why though. I have write access and all on the drive i mentioned :/

**Comment by darshankawar** [comment]
@erythana 
I see that you have used `snap` to install flutter. `/home/chris/snap/flutter/common/flutter`
There were some issues using it filed by others, maybe it could be due to it.
But now since your issue is resolved, is it safe to close this issue ?

**Comment by erythana** [comment]
@darshankawar 
Yes i did. Hmm i guess so, not a problem with flutter itself so jeah, fine with that.
Thanks :)

**Comment by erythana** [comment]
Just in case someone stumbles upon this: I figured out why, for some reason this was on a ntfs drive on my linux machine - even though i could write files something was still not working. Reformatted to ext4 and works like a charm :100:
