### ISSUE TITLE
TextFormField focus issue

### ISSUE THREAD

**Issue by briblanch** [flutter/flutter#9282]
## Steps to Reproduce
The following code produces an issue when the `TextFormField` is focused it will immediately loose focus. This code is almost identical to the `TextFormFieldDemo` in the `flutter_gallery` app but I cannot get it to reproduce there. Here is a gif of the issue I am seeing: ![](http://g.recordit.co/jNEFmSx1Bc.gif).

```dart
   return new Scaffold(
      key: _scaffoldKey,
      appBar: new AppBar(title: new Text('Welcome'), elevation: 1),
      body: new Form(
        key: _formKey,
        autovalidate: _autoValidate,
        child: new ListView(
          padding: new EdgeInsets.symmetric(horizontal: 16.0),
          children: <Widget>[
            new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.person),
                  hintText: 'Please enter your username',
                  labelText: 'Username',
                ),
                onSaved: (String value) => _username = value,
                validator: _validateUsername),
            new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.security),
                  hintText: 'Please enter your password',
                  labelText: 'Password',
                ),
                onSaved: (String value) => _password = value,
                validator: _validatePassword,
                obscureText: true),
            new FlatButton(onPressed: _handleSubmit, child: new Text('SUBMIT')),
          ],
        ),
      ),
    );
```

## Logs

```bash
Launching lib/main.dart on iPhone 7 in debug mode...
CoreSimulatorBridge: Requesting installation of file:///Users/brianblanchard/workspaces/wf/w_inbox/build/ios/Release-iphonesimulator/Runner.app/ with options: {
	    CFBundleIdentifier = "com.yourcompany.wInbox";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/brianblanchard/Library/Developer/CoreSimulator/Devices/587CFD50-FA2D-48B8-934C-1263DD694F75/data";
	}
	state->old_bundle: /Users/brianblanchard/Library/Developer/CoreSimulator/Devices/587CFD50-FA2D-48B8-934C-1263DD694F75/data/Containers/Bundle/Application/D41FAE73-32A2-4BD6-9140-3FE05586DEBA/Runner.app
	state->new_bundle: /Users/brianblanchard/workspaces/wf/w_inbox/build/ios/Release-iphonesimulator/Runner.app
	state->dst_bundle: /Users/brianblanchard/Library/Developer/CoreSimulator/Devices/587CFD50-FA2D-48B8-934C-1263DD694F75/data/Library/Caches/com.apple.mobile.installd.staging/temp.bCSYgu/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/brianblanchard/Library/Developer/CoreSimulator/Devices/587CFD50-FA2D-48B8-934C-1263DD694F75/data/Library/Caches/com.apple.mobile.installd.staging/temp.bCSYgu/extracted
CoreSimulatorBridge: Requesting launch of com.yourcompany.wInbox with options: {
	    arguments =     (
	        "--enable-dart-profiling",
	        "--flx=/Users/brianblanchard/workspaces/wf/w_inbox/build/app.flx",
	        "--dart-main=/Users/brianblanchard/workspaces/wf/w_inbox/lib/main.dart",
	        "--packages=/Users/brianblanchard/workspaces/wf/w_inbox/.packages",
	        "--enable-checked-mode",
	        "--start-paused",
	        "--observatory-port=8100",
	        "--diagnostic-port=8101"
	    );
	    environment =     {
	    };
	}
CoreSimulatorBridge: Beginning launch sequence for bundle 'com.yourcompany.wInbox'
		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
	Simulator booted at: 2017-04-07 14:56:15 +0000
	Current time: 2017-04-07 14:59:18 +0000
	Within boot leeway: NO
CoreSimulatorBridge: Launch attempt #0 for bundle 'com.yourcompany.wInbox', have been trying to launch for 0 seconds. Modern launch services = YES
CoreSimulatorBridge: Got LSBundleProxy for 'com.yourcompany.wInbox', sequenceNumber 248, cacheGUID 5FC7C218-17DF-43AB-937C-E0EF64F01F09
CoreSimulatorBridge: [Common] [FBSSystemService][0xc1c4] Sending request to open "com.yourcompany.wInbox"
CoreSimulatorBridge: [Common] [FBSSystemService][0xc1c4] Request successful: <BSProcessHandle: 0x7fd834214a50; Runner:26739; valid: YES>
CoreSimulatorBridge: Launch successful for 'com.yourcompany.wInbox'
[WARNING:../../flutter/shell/common/platform_view.cc(162)] WARNING: Could not setup an OpenGL context on the resource loader.
```

## Flutter Doctor

```bash
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/brianblanchard/workspaces/personal/flutter
    • Framework revision c1bdf5e032 (15 hours ago), 2017-04-06 16:56:00 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.5

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/brianblanchard/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.0.beta.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4006
    • Flutter plugin version 12.1

[-] WebStorm (version 2016.2.4)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • iPhone 7 • 587CFD50-FA2D-48B8-934C-1263DD694F75 • ios • iOS 10.3 (simulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@abarth would know.  Unlikely to be related to https://github.com/flutter/flutter/issues/9231 but it reminded me of that.

**Comment by collinjackson** [comment]
Are you still seeing this? I tried your code in the simulator just now and it did not repro for me.

**Comment by briblanch** [comment]
No I am not longer experiencing this. This issue can be closed.

**Comment by collinjackson** [comment]
Thanks for reporting it.

**Comment by VolodymyrLykhonis** [comment]
I am having same issue, it happens when a form key is supplied. Once form key is removed, it works (a keyboard does not get dismissed).

### Widget
```dart
new Scaffold(
  body: new Form(
    key: _formKey,
    child: new ListView(
      children: <Widget>[
        new TextFormField(),
      ],
    ),
  ),
);
```

### Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/Vladimir/Library/flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/Vladimir/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.0.0.beta.5

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by Hixie** [comment]
cc @cbracken

**Comment by garfieldcoked** [comment]
Had a similar issue, none of the workarounds mentioned in https://github.com/flutter/flutter/issues/10826 and other places did not work. In my case I had a scaffold key and form key, I had to remove both for it to work.

**Comment by garfieldcoked** [comment]
After a bunch of tinkering around, I have concluded that removing form key resolves my issue I was creating form key like so `final _formKey = new GlobalKey<FormState>();` but form was not in a state or StatefulWidget (just a StatelessWidget with a form that has a form key). I moved my code to a state class which is referenced by a Stateful class and the issue went a way.

It makes sense, but I think the form needs to be in a state object.

**Comment by zoechi** [comment]
@santosh12345 Use something like `onPressed: () => setState(() => textValue = 'newValue'),` and then when the widget is rebuilt (`build() {...}` is run again) assign `textValue` again to the TextFormField`.

**Comment by dyardyGIT** [comment]
Still having this issue. The form key is required so how can you just remove it?

**Comment by DFreds** [comment]
I am also having this issue.

**Comment by rostIvan** [comment]
Hi, guys
I just solved this issue without deleting _scaffoldKey. I passed _orderFormKey as key TextField
```dart
static final _orderFormKey = GlobalKey<FormFieldState<String>>();
TextField(
   key: _orderFormKey,
   controller: controller,
   style: TextStyle(fontSize: 18.0, color: Colors.black)
);
```
it can be useful for you too :)

**Comment by rostIvan** [comment]
But in some cases it will not be a good solution. 
Thanks @garfieldcoked, i solved this issue by using next steps:
1. Create StatefulWidget and add to it _scaffoldKey, and then pass _scaffoldKey to state class
```dart
class SomePage extends StatefulWidget {
  final _scaffoldKey = GlobalKey<ScaffoldState>();

  SelectionPage({Key key}) : super(key: key);

  @override
  SomePageState createState() => SomePageState(_scaffoldKey);
}
```
2. Now create state class and use this key,  for example like a showMessage method
```dart
class SomePageState extends State<SelectionPage> {
  final GlobalKey<ScaffoldState> _scaffoldKey;
  SomePageState(this._scaffoldKey);

@override
  Widget build(BuildContext context) => Scaffold(
      key: _scaffoldKey, 
      body: _buildBody()
  );

  Widget _buildBody() => TextField(
      onChanged: (text) => _search(text),
  );

  void showMessage(message) {
    _scaffoldKey.currentState.showSnackBar(new SnackBar(content: new Text(message)));
  }
}
```

**Comment by PeterHo249** [comment]
I've got the same issue with my login form. In the past, it worked properly but not today.
`[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17763.195], locale en-US)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\PeterHo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!`

I also tried above solutions but no solution work for me. Every time I tapped on textformfiled, the widget is disposeState, initState and build.

**Comment by Rahuvich** [comment]
I have the same issue, but after Navigator pushes another page. 

![Gif of the issue described](https://media.giphy.com/media/1rK674TsF186Rq3Pnn/giphy.gif)

I have the following code to reproduce the issue:

```

class MockPage extends StatefulWidget {
  @override
  _MockPageState createState() => _MockPageState();
}

class _MockPageState extends State<MockPage> {
  @override
  Widget build(BuildContext context) {
    FocusScope.of(context).requestFocus(new FocusNode());

    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: <Widget>[
          TextField(
            autofocus: true,
          ),
          IconButton(
            icon: Icon(Icons.arrow_forward_ios),
            onPressed: () {
              Navigator.pushReplacement(
                context,
                MaterialPageRoute(
                  builder: (context) => MockPage(),
                ),
              );
            },
          ),
        ],
      ),
    );
  }
}

```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/raul/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/raul/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/71/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/71/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
@Rahuvich run 
```
flutter channel master
flutter doctor
```
and try again.

**Comment by Rahuvich** [comment]
@zoechi I run both commands and tried again:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.2.2-pre.22, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
Now I can't write on any text field, nor the first one. All text fields seems to focus but keyboard does not appear:
![issueflutter](https://user-images.githubusercontent.com/20211760/53195390-e1156680-3615-11e9-9eae-62f32a3eb156.gif)

**Comment by zoechi** [comment]
@Rahuvich can you please post a complete running minimal reproduction (incl. `main(){...}`, imports, ...)?

**Comment by Rahuvich** [comment]
@zoechi I uploaded the project to [github](https://github.com/Rahuvich/textFieldsIssue) .

Also noticed this instruction does not work in master channel, (it works on stable):
```
SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark));
```

**Comment by zoechi** [comment]
> Also noticed this instruction does not work

Please create a new issue also with a minimal reproduction.

**Comment by zoechi** [comment]
I can not reproduce with your project.

This code should not be in `build()`. Build should be a pure function that builds the widget tree and returns the result but does not have other side effects.

```dart
FocusScope.of(context).requestFocus(new FocusNode());
```

**Comment by Rahuvich** [comment]
> I can not reproduce with your project.
> 
> This code should not be in `build()`. Build should be a pure function that builds the widget tree and returns the result but does not have other side effects.
> 
> ```dart
> FocusScope.of(context).requestFocus(new FocusNode());
> ```
Forgot to delete that line, I was testing if that line works.

Mmmh seems weird... I have tried to reproduce with another emulator and I still have this issue.

```
flutter doctor -v
[✓] Flutter (Channel master, v1.2.2-pre.22, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.2-pre.22 at /home/raul/flutter
    • Framework revision dd23be3936 (2 days ago), 2019-02-19 21:35:31 -0800
    • Engine revision f45572e95f
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/raul/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/71/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/71/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by zoechi** [comment]
@Rahuvich Right, I wanted to post 
```
[✓] Flutter (Channel master, v1.2.3-pre.5, on Mac OS X 10.14.3 18D42, locale en-AT)
```
but I had expected it to work with your version as well. You could still try `flutter upgrade`

**Comment by zoechi** [comment]
@Rahuvich there was a related fix very recently though

**Comment by Rahuvich** [comment]
@zoechi You are right, I thought I had the lastest version. Now it works like a charm (also works the SystemChrome.setSystemUIOverlayStyle instruction).
Btw, how stable is master branch for development?

**Comment by williamdias** [comment]
I had this same problem when a new page (with a Form and a GlobalKey) was pushed to the Navigator. The whole page was recreated when a TextFormField was focused. So, instead of instantiating a new page each time, I declared the page as final variable in the beginning of my classe.

```
final _mockPage = MockPage();

...

Navigator.pushReplacement(context,
  MaterialPageRoute(builder: (context) => _mockPage),
);
```

**Comment by Rahuvich** [comment]
I have the same issue as before but it works well on the tiny project I made with mockpage. In my personal project the issue is persisting and can't figure out how to reproduce it on the tiny one.

@williamdias Could you paste flutter doctor -v? Just to check your flutter version

**Comment by zoechi** [comment]
@williamdias that should be fixed in `master` (probably in `dev` as well already)

**Comment by williamdias** [comment]
@Rahuvich @zoechi 

I upgraded flutter using the master branch, but it did not solve the problem.

```
[✓] Flutter (Channel master, v1.2.3-pre.31, on Mac OS X 10.13.6 17G65, locale en-BR)
    • Flutter version 1.2.3-pre.31 at 
    • Framework revision 3423c831b9 (21 hours ago), 2019-02-24 21:48:50 +0100
    • Engine revision 0546e1e5e9
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by zoechi** [comment]
@williamdias please create a new issue

**Comment by williamdias** [comment]
@zoechi I tried to reproduce the error using @Rahuvich's project and noticed that the problem only happens if the widget pushed to the navigator is a ``StatelessWidget``.  In my case, I was using a BLoC (from flutter_bloc package) to handle state so I used a ``StatelessWidget``. Should I make this widget a ``StatefullWidget`` to prevent this ``Form`` and ``GlobalKey`` issue or is the solution I mentioned earlier better?

Another thing I noticed is that the widget is recreated when ``TextFormField`` is focused only if it has been pushed to the ``Navigator``. I created a [repo](https://github.com/williamdias/flutter_textformfield_issue) to test all these behaviours.

My ``PageMain`` has a ``Form`` with a ``GlobalKey``, but it's not recreated when the ``TextFormField`` gains focus. On the other hand, all the other pages, which are pushed to the ``Navigator``, are recreated once the ``TextFormField`` is focused. Is this an expected behaviour?

**Comment by zoechi** [comment]
@williamdias I don't know if this should work with a stateless widget.
I'd suggest to create a new issue for the specialists for this area to have a look.

**Comment by AzarouAmine** [comment]
When you push to a new page using Navigator.push(... MaterialPageRoute( build: ...)) and the new page has a form with a formKey, you must set this latter to static. I don't know the reason why is this happening, but this was the solution that worked for me. (Removing the formKey also works, but if you need it to stick around, make it static).

**Comment by Achileas** [comment]
I don't know if it helps but I moved out my GlobalKey definition from the build method.

`final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();`

**Comment by CharlesCCC** [comment]
> The whole page was recreated when a `TextFormField` was focused.

holy cow, you saved my day, I was struggling all day trying to figure this one out. Until now, saw your answer. but i'm curious why would `The whole page was recreated when a TextFormField was focused.` ??? this seems really strange behavior.

**Comment by rgb1380** [comment]
This issue is not full resolved and needs to be reopened. 

In my case, I am using a ListView which takes a complex widget as its item, let's call it the ItemWidget. The ItemWidget includes a picture, and a number of TextFields. Since the ItemWidget is being instantiated multiple times (depending on the size of the list), it is not possible to create a static key and assign it to the TextFields (the app crashes if you do as the static key gets used by multiple widgets). ItemWidget must have a GlobalKey itself and removing that is not an option. 

The solutions discussed here are to either remove the GlobalKey from the parent widget or to assign the TextField a static GlobalKey. Neither of which are possible in my case. 

Can this issue be reopened and properly dealt with as bug in Flutter?

**Comment by eseidelGoogle** [comment]
@rgb1380 Since this issue has been closed for almost a year, and there are multiple problems expressed in the comments here, I suggest instead of re-opening this one, that someone open a new separate issue which describes the exact difficulties with the current API.  I believe a new separate issue is more likely to lead to quick resolution.  Make sense?

**Comment by rgb1380** [comment]
@eseidelGoogle thanks for the quick response. I have opened issue #46773 as suggested.

**Comment by araams** [comment]
Most of the time the issue will be fixed if you place your Textfield/TextFormField as child of Form. There should not be any widget in between Form and TextField. Above in somecases there are listviews getting used. Please try to use as below,

child: Form(
                    key: widget._formKey,
                    child: TextFormField(
                      onFieldSubmitted: (val) {
                        print("On Submitted");
                      },
                      focusNode: _node,
                      controller: widget.myController,
                      obscureText: widget.bIsPasswordField,
                      cursorColor: Colors.grey,
                      style: TextStyle(
                        fontSize: 15,
                      ),
                      decoration: InputDecoration(
                        hintText: widget.strHintText,
                        hintStyle: TextStyle(
                          color: Colors.grey[400],
                          fontSize: 12,
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.all(Radius.zero),
                          borderSide: BorderSide.none,
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.all(Radius.zero),
                          borderSide: BorderSide.none,
                        ),
                      ),
                    ),
                  ),

**Comment by huybuidac** [comment]
For anyone is facing the issue. It dues to navigationKey. You just need to define it in your `MainApp`

```dart
class MyApp extends StatelessWidget {
  final rootNavigation = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      navigatorKey: rootNavigation,
    );
  }
}
```

**Comment by wiesnerbernard** [comment]
Form the problem was a case of simply declaring the key in the wrong position, i.e. in a widget which renders when focus is placed on an input field. I simple moved the key declaration up the widget tree to a point where it wouldn't be re-invoked when the user taps on an input field. I also made sure to declare the key outside of build methods.
