### ISSUE TITLE
Mac/android tests are failing consistently in staging pool

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#92859]
Four Mac/android tests keep failing:
https://ci.chromium.org/p/flutter/builders/staging/Mac_android_staging%20tiles_scroll_perf__timeline_summary
https://ci.chromium.org/p/flutter/builders/staging/Mac_android_staging%20complex_layout__start_up
https://ci.chromium.org/p/flutter/builders/staging/Mac_android_staging%20complex_layout_scroll_perf__timeline_summary
https://ci.chromium.org/p/flutter/builders/staging/Mac_android_staging%20complex_layout_scroll_perf__memory

**Comment by keyonghan** [comment]
Failing message:
```
[complex_layout_scroll_perf__memory] [STDOUT] stdout: [ +895 ms] Daemon will be stopped at the end of the build 
[complex_layout_scroll_perf__memory] [STDOUT] adb logcat: --------- beginning of main
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [+2809 ms] FAILURE: Build failed with an exception.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] * Where:
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] Build file '/opt/s/w/ir/x/w/recipe_cleanup/tmpa52A2u/flutter sdk/dev/benchmarks/complex_layout/android/app/build.gradle' line: 18
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] * What went wrong:
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] A problem occurred evaluating project ':app'.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] > Failed to apply plugin 'com.android.internal.application'.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ]    > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ]      You can try some of the following options:
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ]        - changing the IDE settings.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ]        - changing the JAVA_HOME environment variable.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ]        - changing `org.gradle.java.home` in `gradle.properties`.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] * Try:
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] * Get more help at https://help.gradle.org
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [        ] BUILD FAILED in 4s
[complex_layout_scroll_perf__memory] [STDOUT] stdout: [        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[complex_layout_scroll_perf__memory] [STDOUT] stdout: [        ] Use '--warning-mode all' to show the individual deprecation warnings.
[complex_layout_scroll_perf__memory] [STDOUT] stdout: [        ] See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
[complex_layout_scroll_perf__memory] [STDOUT] stdout: [+2450 ms] Running Gradle task 'assembleRelease'... (completed in 6.8s)
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [   +2 ms] Exception: Gradle task assembleRelease failed with exit code 1
[complex_layout_scroll_perf__memory] [STDOUT] stdout: [   +1 ms] "flutter run" took 7,629ms.
[complex_layout_scroll_perf__memory] [STDOUT] stderr: [   +3 ms] 
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            #10     main (package:flutter_tools/executable.dart:93:3)
[complex_layout_scroll_perf__memory] [STDOUT] stderr:            <asynchronous suspension>
```

**Comment by godofredoc** [comment]
@blasten do we need to revert the changes to upgrade gradle in this three tests?

**Comment by blasten** [comment]
No, it used to work. ci.yaml is setting the java11 dependency. Is this a bug in the recipe?

https://github.com/flutter/flutter/blob/master/.ci.yaml#L1484

**Comment by blasten** [comment]
@CaseyHillers re-assigning to investigate why the dependency in ci.yaml is ignored.

**Comment by blasten** [comment]
https://github.com/flutter/flutter/pull/92535 reverts the migration to Gradle 7, so it should fix this issue.
Note that we still need to address the underlying issue where .ci.yaml dependencies seem to be ignored now.

**Comment by CaseyHillers** [comment]
I expect to have https://github.com/flutter/flutter/issues/91319 fixed and rolled out this week

**Comment by CaseyHillers** [comment]
https://github.com/flutter/flutter/issues/91319 is fixed (feature rolled out).

Let me know if there's anything else I can do to help.

**Comment by blasten** [comment]
The tasks are still failing: https://ci.chromium.org/p/flutter/builders/staging/Mac_android_staging%20complex_layout__start_up

do we know why the java11 dependency isn't honored? https://github.com/flutter/flutter/blob/34dbee66de8b2ef176ec39d80c3eca5feb70572e/.ci.yaml#L2610

**Comment by keyonghan** [comment]
Staging builders are not supported by existing .ci.yaml. They are currently controlled by a separate staging star in flutter/infar: https://flutter.googlesource.com/infra/+/refs/heads/main/config/devicelab_staging_config.star#283

We need to update the version in the staging.star to enable it.

**Comment by CaseyHillers** [comment]
To clarify, staging is supported by ci.yaml (any target marked `bringup: true` is in staging). However, these configs have not been migrated from the starlark into yaml.

@blasten I'll share with you a spreadsheet of the staging builders left in starlark. If you have time to go through it, I'd like to get it down from 100 tests to 25. Then I can go through and those to the ci.yaml.

**Comment by yusuf-goog** [comment]
FYI, seeing these errors on win staging bots as well: https://chromium-swarm.appspot.com/task?id=57479ab9e235d710

**Comment by godofredoc** [comment]
Mac_android tests are being removed from staging.

**Comment by godofredoc** [comment]
CL for removing mac_android: https://flutter-review.googlesource.com/c/infra/+/21900
