### ISSUE TITLE
Ubuntu Platform Bug Report: Offset argument contained a NaN value. 'dart:ui/painting.dart':

### ISSUE THREAD

**Issue by generalzzd** [flutter/flutter#93188]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press 1 to select Linux Platform 
3. Show up App window but got a exception 

**Expected results:** 
NO EXCEPTIONS log show up on console

**Actual results:** 
EXCEPTIONS!

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
      theme: ThemeData(
          elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          primary: Colors.blue,
        ),
      )),
      home: Scaffold(
        body: Center(child: Text('Test')), 
      )));
}

```

</details>

<details>
  <summary>Logs</summary>

```
An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:39657/yyPXTy8X_4o=/

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///home/zidi/Documents/ProjectPiao/PiaoPiao/piao_app/lib/main.dart:6:10

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:52:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4466:12)
#4      TextPainter.paint (package:flutter/src/painting/text_painter.dart:642:12)
#5      BannerPainter.paint (package:flutter/src/widgets/banner.dart:147:18)
#6      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#7      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:610:7)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#13     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#22     RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#24     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#25     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#26     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#27     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#32     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderCustomPaint#2a752:
  needs compositing
  creator: CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ←
    _LocalizationsScope-[GlobalKey#9d572] ← Semantics ← Localizations ← MediaQuery ←
    _MediaQueryFromWindow ← _FocusMarker ← Focus ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1280.0, h=720.0)
  size: Size(1280.0, 720.0)
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderPointerListener#93936
      child: RenderAbsorbPointer#1027e
        child: RenderSemanticsAnnotations#327e0
          child: _RenderTheatre#cca13
            onstage 1: RenderIgnorePointer#af29b
            onstage 2: RenderSemanticsAnnotations#6cc21
            no offstage children
════════════════════════════════════════════════════════════════════════════════════════════════════
Activating Dart DevTools...                                         3.3s
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:39657/yyPXTy8X_4o=/
Lost connection to device.
```

```
Analyzing piao_app...                                                   

   info • Prefer const with constant constructors • lib/main.dart:14:13 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:15:15 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:15:29 • prefer_const_constructors
```

```
Machine Configurations
Kernel: Linux MYPCNAME 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
OS: Ubuntu 20.04.3 LTS
Type: 64-bits
Memory: 32GB
CPU: AMD 5900x
GPU: NVIDIA GTX 1080 Ti
GPU Driver: NVIDIA driver metapackage nvidia-driver-460
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale zh_CN.UTF-8)
    • Flutter version 2.5.3 at /home/zidi/Documents/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 周前), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.61.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshmnj** [comment]
Hi @generalzzd, thanks for filing the issue. I could not reproduce the issue. Can you please try running 
`flutter clean` and re run the app and if the issue persists can you please verify if this issue occurs with new flutter project too by running
```
flutter create sample
flutter run
```
and also verify if this happens only on linux or other platforms too (web / Android).

<details>
<summary>flutter doctor -v</summary>

```
✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/flutter_sdk/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by generalzzd** [comment]
@maheshmnj Hi, today I set up two brand new Ubuntu 20.04 LTS OS in VM in order to help you reproduce this bug.  First, install an English Version Ubuntu and download Flutter and do 'create sample' and run. It's running properly.  However, then I install a Chinese Version of Ubuntu and set up Flutter, and this bug show up. Probably, it causes by the Ubuntu Chinese Language pack. Reproduce methods are pretty straightforward that select a Chinese language pack when you install Ubuntu. Thanks.

**Comment by maheshmnj** [comment]
@generalzzd Are you able to run the counter app (newly created flutter app) on the "Chinese version of Ubuntu"? Can you please share the link of the ISO file you installed which reproduces this issue?

Thanks

**Comment by generalzzd** [comment]
@maheshmnj Yes, I can run the counter app but the same exception show up as we mention before. (It can run but keep popping up exceptions!)

I download the Chinese Ubuntu ISO file from the official website. https://ubuntu.com/download/desktop
Please manually select the language pack when you install it. (DO NOT use VMware quick install)
![微信截图_20211110135321](https://user-images.githubusercontent.com/7807155/141057803-f11c89ef-5e26-4db2-a3dd-a05d37456f0b.png)

![微信截图_20211110135344](https://user-images.githubusercontent.com/7807155/141057769-7730f98d-9952-4213-9a8c-1cda922a4009.png)

In Chrome, the counter app shows a blank window.  Sometimes It works in Chrome, Sometimes it is blank. I do not have Android I cannot help you with it.

![微信截图_20211110141309](https://user-images.githubusercontent.com/7807155/141060053-294db9e9-537e-4f98-ad11-4d888b18ce55.png)

![微信截图_20211110141624](https://user-images.githubusercontent.com/7807155/141060148-8e81f72e-fc51-4f4b-baa3-324753fdeac5.png)


```

zidi@zidi-virtual-machine:~/文档/sample$ flutter run
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-40-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1

Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Syncing files to device Linux...                                   100ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:37481/2VQtbJSKpTw=/

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY
╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should
provide substantially
more information in this error message to help you determine and fix the
underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///home/zidi/%E6%96%87%E6%A1%A3/sample/lib/main.dart:13:12

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:52:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4466:12)
#4      TextPainter.paint
(package:flutter/src/painting/text_painter.dart:642:12)
#5      BannerPainter.paint (package:flutter/src/widgets/banner.dart:147:18)
#6      RenderCustomPaint._paintWithPainter
(package:flutter/src/rendering/custom_paint.dart:563:13)
#7      RenderCustomPaint.paint
(package:flutter/src/rendering/custom_paint.dart:610:7)
#8      RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#9      PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#11     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#12     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#13     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#14     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#15     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#16     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#17     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#18     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#19     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#20     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#21     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#22     RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#23     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#24     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:141:11)
#25     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:100:5)
#26     PipelineOwner.flushPaint
(package:flutter/src/rendering/object.dart:979:29)
#27     RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:455:19)
#28     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:883:13)
#29     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:319:5)
#30     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1143:15)
#31     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1080:9)
#32     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class
_Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired:
RenderCustomPaint#f2b3a:
  needs compositing
  creator: CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ←
    _LocalizationsScope-[GlobalKey#78a53] ← Semantics ← Localizations ←
    MediaQuery ←
    _MediaQueryFromWindow ← _FocusMarker ← Focus ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1280.0, h=720.0)
  size: Size(1280.0, 720.0)
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderPointerListener#38f83
      child: RenderAbsorbPointer#efd76
        child: RenderSemanticsAnnotations#17cec
          child: _RenderTheatre#04cb2
            onstage 1: RenderIgnorePointer#a12f8
            onstage 2: RenderSemanticsAnnotations#3c5ea
            no offstage children
════════════════════════════════════════════════════════════════════════════════
════════════════════

The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:37481/2VQtbJSKpTw=/



```

**Comment by maheshmnj** [comment]
@generalzzd I found this similar issue https://github.com/flutter/flutter/issues/91379 and it looks like this is fixed on master channel. Could you please try switching to master channel and verify this by running 

```
flutter channel master
flutter upgrade
```

Thanks

**Comment by generalzzd** [comment]
@maheshmnj  Switch to Flutter master channel. Still get exceptions and blank webpage. :(


Linux Desktop
```
zidi@zidi-virtual-machine:~/文档/flutter_master_test$ flutter upgrade
Flutter is already up to date on channel master
Flutter 2.6.0-12.0.pre.685 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 7e05d103e9 (9 小时前) • 2021-11-10 19:43:02 -0500
Engine • revision 6abca28955
Tools • Dart 2.15.0 (build 2.15.0-285.0.dev)
zidi@zidi-virtual-machine:~/文档/flutter_master_test$ flutter create sample
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
Downloading package sky_engine...                                   4.3s
Downloading flutter_patched_sdk tools...                            9.5s
Downloading flutter_patched_sdk_product tools...                   37.2s
Downloading linux-x64 tools...                                     46.7s
Downloading linux-x64/font-subset tools...                          4.6s
Creating project sample...
Running "flutter pub get" in sample...                              4.1s
Wrote 87 files.

All done!
In order to run your application, type:

  $ cd sample
  $ flutter run

Your application code is in sample/lib/main.dart.

zidi@zidi-virtual-machine:~/文档/flutter_master_test$ cd sample 
zidi@zidi-virtual-machine:~/文档/flutter_master_test/sample$ flutter run
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
Downloading Web SDK...                                             65.6s
Downloading CanvasKit...                                           11.9s
Downloading linux-x64/linux-x64-flutter-gtk tools...               24.2s
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...        18.6s
Downloading linux-x64-release/linux-x64-flutter-gtk tools...        14.8s
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-40-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1

Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Syncing files to device Linux...                                   146ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:37005/PkpMLp1Q7yY=/

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY
╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should
provide substantially
more information in this error message to help you determine and fix the
underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///home/zidi/%E6%96%87%E6%A1%A3/flutter_master_test/sample/li
  b/main.dart:13:12

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:52:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4596:12)
#4      TextPainter.paint
(package:flutter/src/painting/text_painter.dart:695:12)
#5      BannerPainter.paint (package:flutter/src/widgets/banner.dart:147:18)
#6      RenderCustomPaint._paintWithPainter
(package:flutter/src/rendering/custom_paint.dart:563:13)
#7      RenderCustomPaint.paint
(package:flutter/src/rendering/custom_paint.dart:610:7)
#8      RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2403:7)
#9      PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#11     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2403:7)
#12     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#13     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#14     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2403:7)
#15     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#16     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#17     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2403:7)
#18     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#19     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#20     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2403:7)
#21     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#22     RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#23     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2403:7)
#24     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:141:11)
#25     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:100:5)
#26     PipelineOwner.flushPaint
(package:flutter/src/rendering/object.dart:973:29)
#27     RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:499:19)
#28     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:883:13)
#29     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:363:5)
#30     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1145:15)
#31     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1082:9)
#32     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class
_Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired:
RenderCustomPaint#88fcd:
  needs compositing
  creator: CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ←
    _LocalizationsScope-[GlobalKey#da8e0] ← Semantics ← Localizations ←
    MediaQuery ←
    _MediaQueryFromWindow ← _FocusMarker ← Focus ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1280.0, h=720.0)
  size: Size(1280.0, 720.0)
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderPointerListener#f9fa4
      child: RenderAbsorbPointer#ca8ba
        child: RenderSemanticsAnnotations#cb525
          child: _RenderTheatre#0cfd9
            onstage 1: RenderIgnorePointer#ffd2d
            onstage 2: RenderSemanticsAnnotations#cd779
            no offstage children
════════════════════════════════════════════════════════════════════════════════
════════════════════
The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:37005/PkpMLp1Q7yY=/

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.

Another exception was thrown: Offset argument contained a NaN value.
```

web 

![企业微信截图_20211111095309](https://user-images.githubusercontent.com/7807155/141223011-b02f10b0-9b5a-41d4-9d8c-bd391cc46f11.png)


flutter doctor -v
```
zidi@zidi-virtual-machine:~/文档/flutter_master_test/sample$ flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.685, on Ubuntu 20.04.3 LTS
    5.11.0-40-generic, locale zh_CN.UTF-8)
    • Flutter version 2.6.0-12.0.pre.685 at /home/zidi/文档/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e05d103e9 (9 小时前), 2021-11-10 19:43:02 -0500
    • Engine revision 6abca28955
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.62.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS
      5.11.0-40-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 2 categories.
```

**Comment by maheshmnj** [comment]
Hi @generalzzd, changing the system language to chinese simplified, I was able to reproduce the issue. The app does run normally but the exception is thrown.

![image](https://user-images.githubusercontent.com/31410839/141271034-833f6833-0f4d-4915-99e3-174a52b0e9f2.png)

<details>
<summary>flutter doctor -v</summary>

```
✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale zh_CN.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/flutter_sdk/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 周前), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.689, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale zh_CN.UTF-8)
    • Flutter version 2.6.0-12.0.pre.689 at /home/mahesh/flutter_sdk/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 51e7c618ab (3 小时前), 2021-11-11 01:23:05 -0500
    • Engine revision d5cadd28b0
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>


<details>
<summary>logs</summary>

```
Launching lib/main.dart on Linux in debug mode...
Connecting to VM Service at ws://127.0.0.1:37191/JQXjsoPDJB0=/ws

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
MaterialApp
When the exception was thrown, this was the stack
#2      _offsetIsValid (dart:ui/painting.dart:52:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4466:12)
#4      TextPainter.paint
#5      BannerPainter.paint
#6      RenderCustomPaint._paintWithPainter
#7      RenderCustomPaint.paint
#8      RenderObject._paintWithContext
#9      PaintingContext.paintChild
#10     RenderProxyBoxMixin.paint
#11     RenderObject._paintWithContext
#12     PaintingContext.paintChild
#13     RenderProxyBoxMixin.paint
#14     RenderObject._paintWithContext
#15     PaintingContext.paintChild
#16     RenderProxyBoxMixin.paint
#17     RenderObject._paintWithContext
#18     PaintingContext.paintChild
#19     RenderProxyBoxMixin.paint
#20     RenderObject._paintWithContext
#21     PaintingContext.paintChild
#22     RenderView.paint
#23     RenderObject._paintWithContext
#24     PaintingContext._repaintCompositedChild
#25     PaintingContext.repaintCompositedChild
#26     PipelineOwner.flushPaint
#27     RendererBinding.drawFrame
#28     WidgetsBinding.drawFrame
#29     RendererBinding._handlePersistentFrameCallback
#30     SchedulerBinding._invokeFrameCallback
#31     SchedulerBinding.handleDrawFrame
#32     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#c9ec5
RenderObject: RenderCustomPaint#c9ec5
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=1280.0, h=720.0)
    size: Size(1280.0, 720.0)
    child: RenderPointerListener#83b26
        needs compositing
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=1280.0, h=720.0)
        size: Size(1280.0, 720.0)
        behavior: deferToChild
        listeners: down, up, cancel
        child: RenderAbsorbPointer#997f1
            needs compositing
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=1280.0, h=720.0)
            size: Size(1280.0, 720.0)
            absorbing: false
            ignoringSemantics: implicitly false
            child: RenderSemanticsAnnotations#1e04e
                needs compositing
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=1280.0, h=720.0)
                size: Size(1280.0, 720.0)
                child: _RenderTheatre#8e4cb
                    needs compositing
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=1280.0, h=720.0)
                    size: Size(1280.0, 720.0)
                    skipCount: 0
                    textDirection: ltr
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

The relevant error-causing widget was
MaterialApp
════════════════════════════════════════════════════════════════════════════════

```

</details>

**Comment by gspencergoog** [comment]
cc @cbracken
