### ISSUE TITLE
[tool] flutter doctor throws ` FormatException: Unexpected extension byte` when using `IntelliJ IDEA  2021.3`  and `Dart` plugin

### ISSUE THREAD

**Issue by woprandi** [flutter/flutter#94060]
## Steps to Reproduce

1. Install new IntelliJ IDEA 2021.3 RC and Dart plugin
2. Run `flutter doctor`

**Expected results:** 

No problem with doctor

**Actual results:** 

```
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
```

The crash come from https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/intellij/intellij.dart#L130 with `Dart.jar` as file

<details>
  <summary>Logs</summary>

```
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-12.0.pre.790, on Fedora Linux 35 (KDE Plasma) 5.14.18-300.fc35.x86_64, locale fr_FR.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

```

**Comment by danagbemava-nc** [comment]
<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.826, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.826 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c1455a23a (11 hours ago), 2021-11-23 21:13:05 -0500
    • Engine revision 539239e256
    • Dart version 2.16.0 (build 2.16.0-42.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.8.0-3.1.pre, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0-3.1.pre at /Users/nexus/dev/sdks/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3dab555040 (12 days ago), 2021-11-12 11:50:00 -0800
    • Engine revision 09f1520e8b
    • Dart version 2.15.0 (build 2.15.0-268.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1289:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```
</details>

**Comment by woprandi** [comment]
The 2021.3 is now the current stable version

**Comment by christopherfujino** [comment]
action item for myself: we should catch FormatException and then fail the validator, hinting that their editor installation is likely corrupted (or maybe just their extension)

**Comment by woprandi** [comment]
It's strange since the extension seems to work as usual

**Comment by christopherfujino** [comment]
@stevemessick do you have any insight in to why we're failing to decode a zip here?

**Comment by stevemessick** [comment]
I don't have any direct knowledge. I'd assume it (the Dart code) needs to unpack the META-INF/plugin.xml file from Dart.jar and look at the <version> tag. Perhaps the file encoding changed in 2021.3? If the Dart plugin works (and it must if Flutter does) then the Dart.jar file itself is probably fine.

**Comment by noordawod** [comment]
Same issue here, the doctor says:

```
$ flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.978, on Fedora Linux 35 (Thirty Five) 5.15.6-200.fc35.x86_64, locale en_US.utf8)
    • Flutter version 2.6.0-12.0.pre.978 at /path/to/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9ff3204f9 (25 minutes ago), 2021-12-09 09:29:11 -0500
    • Engine revision 59778ae91c
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /path/to/AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /path/to/AndroidSDK
    • Java binary at: /path/to/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /path/to/studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /path/to/studio-canary
    • Flutter plugin version 57.0.3
    • Dart plugin version 203.8173
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] Connected device (2 available)
    • Pixel 4a 5G (mobile) • XXXXXXXXXXX • android-arm64  • Android 12 (API 31)
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
@christopherfujino @stevemessick 

I just tried to read the same jar files from IntelliJ IDEA 2021.3 stable
Looks like `dart.jar` cannot be read, while `flutter-intellij-63.1.4.jar` reads just fine using [archive](https://pub.dev/packages/archive), which is used in `intellij.dart`.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/intellij/intellij.dart#L5

As you can see archive sample code. just reading `Dart.jar` throws the error.

### Code sample
```dart
import 'dart:io';
import 'package:archive/archive.dart';
import 'package:archive/archive_io.dart';

void main() {
  // final Archive archive = ZipDecoder().decodeBytes(File('assets/flutter-intellij-63.1.4.jar').readAsBytesSync());
  final Archive archive = ZipDecoder().decodeBytes(File('assets/Dart.jar').readAsBytesSync());

  // print('intellij plugin: ${archive.files}');
  print('dart plugin: ${archive.files}');
}
```
```yaml
  assets:
    - assets/Dart.jar
    - assets/flutter-intellij-63.1.4.jar
```

### Logs
```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 5)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      InputStream.readString
package:archive/…/util/input_stream.dart:207
#3      new ZipDirectory.read
package:archive/…/zip/zip_directory.dart:40
#4      ZipDecoder.decodeBuffer
package:archive/src/zip_decoder.dart:19
#5      ZipDecoder.decodeBytes
package:archive/src/zip_decoder.dart:14
#6      main
package:triage/main.dart:7
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:130:25)
#8      _rootRun (dart:async/zone.dart:1426:13)
#9      _CustomZone.run (dart:async/zone.dart:1328:19)
#10     _runZoned (dart:async/zone.dart:1861:10)
#11     runZonedGuarded (dart:async/zone.dart:1849:12)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

### Intellij code sample
```dart
import 'dart:io';
import 'package:archive/archive.dart';
import 'package:archive/archive_io.dart';

void main() {
  final Archive archive = ZipDecoder().decodeBytes(File('assets/flutter-intellij-63.1.4.jar').readAsBytesSync());
  // final Archive archive = ZipDecoder().decodeBytes(File('assets/Dart.jar').readAsBytesSync());

  print('intellij plugin: ${archive.files}');
  // print('dart plugin: ${archive.files}');
}
```

### Logs (no error)
```console
flutter: intellij plugin: [META-INF/, META-INF/MANIFEST.MF]

```

### Jar assets location
```console
    Directory: C:\Users\Taha\StudioProjects\triage\assets


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        12/14/2021  10:35 AM        5876573 Dart.jar
-a----        12/14/2021  10:35 AM            261 flutter-intellij-63.1.4.ja
```

Related https://github.com/brendan-duncan/archive/issues/158

**Comment by sigpoggy** [comment]
I have noticed that I did not get the exception when I updated on my mac yesterday, but today when I updated on windows I do get the exception there.

**Comment by christopherfujino** [comment]
> 

Can you share your `Dart.jar` file?

**Comment by sbidolach** [comment]
I have a similar issue:

- IntelliJ IDEA - Build #IC-213.5744.223, built on November 27, 2021
- Flutter 2.5.0
- Flutter Plugin 63.2.4
- Dart Plugin 213.5744.122

```
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>
```

**Comment by sigpoggy** [comment]
I thought I had updated both Intellij and the sdk on my mac, but I had only updated the sdk. Intellij was version 2021.2.3

I updated my post to explain my error

**Comment by sigpoggy** [comment]
Sorry, replied to you by mistake

-Sigpoggy

**Comment by TahaTesser** [comment]
@christopherfujino 

Here you go 
[Dart.zip](https://github.com/flutter/flutter/files/7722988/Dart.zip)
[flutter-intellij-63.1.4.zip](https://github.com/flutter/flutter/files/7722990/flutter-intellij-63.1.4.zip)

**Comment by Danoctum** [comment]
Experiencing this issue too.

In the meantime:
Is there another way of creating a flutter project that gives the same result as IntelliJ's 'new flutter project' does?

**Comment by sittingbool** [comment]
@Danoctum you can create a flutter project the documented way using the flutter cli. The command would be `$  flutter create my_app`. Despite encountering the error building the app worked fine in the IDE afterwards. But the cli would also offer commands for that.

**Comment by TahaTesser** [comment]
@christopherfujino 

I did further testing, looks like 213+ versions are the ones that crashing in `archive`

https://plugins.jetbrains.com/plugin/6351-dart/versions

![image](https://user-images.githubusercontent.com/48603081/146423156-d9885025-38fa-4d65-8a24-0624c948a589.png)


I also notice the version that has no crash contains more than `Dart,jar` files, while 2.13 contains an only jar file 


### 212 zip which doesn't crash
![Screenshot 2021-12-16 194859](https://user-images.githubusercontent.com/48603081/146423233-83d13a63-7173-48f6-ad66-0531f2877853.png)


### 213 zip which crashes
![Screenshot 2021-12-16 194924](https://user-images.githubusercontent.com/48603081/146423356-9b1560f0-03d5-4bbc-8340-7be5e3980847.png)

**Comment by aurc** [comment]
Seems to still crash on arm64 - Downloaded version 212 as above - no success.

**Comment by indyant** [comment]
The same problem occurred to me in both windows 11 and macos 12.1. So I downgraded IntelliJ to 2021.2.3.
The problem has gone now. 
I think I have to stick to IntelliJ 2021.2 version until this problem is resolved.

**Comment by noordawod** [comment]
There's no apparent side effects on Dart/Flutter operation, though, so for me I'm staying with 2021.3 until this is resolved.

**Comment by nileshmahant** [comment]
> @christopherfujino
> 
> Here you go [Dart.zip](https://github.com/flutter/flutter/files/7722988/Dart.zip) [flutter-intellij-63.1.4.zip](https://github.com/flutter/flutter/files/7722990/flutter-intellij-63.1.4.zip)

this plugin works!

**Comment by desy83** [comment]
Same issue here
- MacOS 11.6.2 - 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
- IntelliJ Ultimate 2021.3 Build #IU-213.5744.223
- Dart Plugin 213.5744.122
- Flutter Plugin 63.2.4
- Flutter version 2.8.1
- Dart version 2.15.1

**Comment by VGerris** [comment]
Same issue, caused by Flutter, not Dart.
Dart Plugin 213.5744.122
Flutter Plugin 63.2.4
IntelliJ CE Build #IC-213.5744.223, built on November 27, 2021

Small additional detail: error keeps coming when Flutter plugin is uninstalled and IDE is restarted.
Need to uninstall Dart plugin and restart IDE for check to pass.
Then when only installing Dart plugin and not restarting, no error, error after restart.
So seems like it's the Dart plugin.
I was somehow able to just install the Flutter plugin, then the error does not occur.

is it because of the build not matching the latest (minor 122 not 223?
https://plugins.jetbrains.com/plugin/6351-dart/versions/stable

Newer versions don't work either.
So perhaps flutter can reach out to Jetbrains and negotiate a fix? perhaps their build robot had a hickup.

**Comment by studiofuga** [comment]
Same issue here.
Simply disabling and restarting IDE does't seem to work, you need to uninstall the plugins to pass the tests.
Hope that helps.

**Comment by erlangparasu** [comment]
FormatException: Unexpected extension byte (at offset 5)

**Comment by pathw0rk3r** [comment]
How is any of this useful?  Please when you write an answer consider people new to the tool.  Fine, so I have to replace flutter-intellij-63.1.4.zip and Dart.zip.  How am I supposed to know where they go?  I can't find them.  I'll try uninstalling and install 2021.2.3 instead.  If that doesn't work, I'll move onto a different tool.

**Comment by VladimirSrednikh** [comment]
well, Flutter fail to read Dart.jar as an archive, while 7Zip and java read it without problems.
So, it seems that the problem is in Flutter's archive's library

**Comment by bidimensional** [comment]
Same issue here with IntelliJ IDEA 2021.3. Hot reload has worked perfectly until it hasn't.

I am able to reproduce though.

This works:
`class FHACKIT extends StatelessWidget {
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Row(
            children: [txtList[1]],
        ));
  }
}`

This doesn't work:
`class FHACKIT extends StatelessWidget {
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Row(
            children: txtList,
        ));
  }
}`

txtList is quite a big list. If I try to render a few elements hot reload works, if I try to render all of it crashes the hot reload, and I need to re-run the app to have it working again. Hope it helps.

`[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>
`

**Comment by Fareed-Ahmad7** [comment]
same issue

**Comment by mandudeman** [comment]
I am new to flutter. I am having the same problem. May I know how exactly or specifically you guys solve this problem? What files are to be replaced and where to put them? Thanks in advance!

**Comment by tvkoz** [comment]
The problem seems to be partially fixed with [archive:3.18](https://github.com/brendan-duncan/archive/releases/tag/3.1.8).
There seems to be a problem fetching the latest version somewhere in flutter,
however, someone can manually use the latest version by going to "FLUTTER_HOME/packages/flutter_tools/pubspec.yaml" and change (line 10) from archive: "3.1.x" to "archive 3.1.**8**"
Then just execute "flutter update-packages --force-upgrade" as instructed in that pubspec.yaml

cheers,

**Comment by tvkoz** [comment]
The problem seems to be partially fixed with [archive:3.1.8](https://github.com/brendan-duncan/archive/releases/tag/3.1.8).
All there is left to do is to use that version to make the error go away, thus, you can manually use the latest version by going to "FLUTTER_HOME/packages/flutter_tools/pubspec.yaml" and change (line 10) to "archive 3.1.**8**"
Then just execute "flutter update-packages --force-upgrade" as instructed in that pubspec.yaml

cheers,

**Comment by noordawod** [comment]
After doing these changes, `flutter doctor -v` doesn't report a problem anymore. So very good! Thanks @tvkoz :)

However, now it becomes a problem to upgrade Flutter:

```bash
$ flutter upgrade
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove local changes, then re-run this command with "--force".
```

Any ideas?

**Comment by tvkoz** [comment]
@noordawod, you can do as instructed to purge local changes.
Otherwise, "cd" to FLUTTER_HOME and execute "git reset --hard; git clean -fd". Then "flutter doctor -v" will build the flutter tools once again, but will produce the initial error as well.
At this point you are free to do "flutter upgrade", if the error persists, then simply repeat the above "patch".

**Comment by noordawod** [comment]
Well, I know how to "forget" the patch. I was interesting more in "keeping the patch" and also being able to upgrade Flutter without the need to re-patch.

**Comment by TahaTesser** [comment]
Hi everyone
I can confirm updating `archive` in tools does solve the issue (thanks @brendan-duncan for fixing the `archive` issue)
This change should be landed by https://github.com/flutter/flutter/pull/96325, thanks for the patience 

```
[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122
```

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/96325.

**Comment by omidshojaee** [comment]
The issue is not fixed for me. And I've the latest stable version:

```
C:\Users\omids>flutter upgrade --force
Flutter is already up to date on channel stable
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (5 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by TylerMutai** [comment]
> The issue is not fixed for me. And I've the latest stable version:
> 
> ```
> C:\Users\omids>flutter upgrade --force
> Flutter is already up to date on channel stable
> Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 77d935af4d (5 weeks ago) • 2021-12-16 08:37:33 -0800
> Engine • revision 890a5fca2e
> Tools • Dart 2.15.1
> ```

Same here

**Comment by danagbemava-nc** [comment]
To anyone else who experiences this issue on `stable 2.8.1`, the fix for this is on the `master` channel and it should roll out to stable sometime in the future. 

Please be patient. 

Thank you

**Comment by johnaaronrose** [comment]
I do not understand how to fix this bug. I've tried running 'flutter update-packages --force-upgrade' as sort-of-instructed in 96018. That completes Ok but 'flutter doctor' still gives the same problem. Could someone please put simple instructions on this thread detailing how to fix this bug?

**Comment by omidshojaee** [comment]
Currently the only workaround is to switch to Master channel. I don't
recommend that because the code in that channel is not tested. But if you
have no choice then run 'flutter channel master' and then run doctor again.

**Comment by johnaaronrose** [comment]
Thanks, omidshojaee. I don't have any choice if I want to install flutter. Do you know when the fix will be deployed on stable? Presumably, I can switch back to stable by running "flutter channel stable" when the fix is deployed to stable: is that correct?

**Comment by danagbemava-nc** [comment]
Hi @johnaaronrose, you should be able to install and use flutter just fine. Is there anything you're running into that is preventing you from installing/using flutter?

**Comment by omidshojaee** [comment]
READ THE TITLE OF THIS THREAD TO  UNDERSTAND WHAT IS PREVENTING US.

**Comment by omidshojaee** [comment]
Roughly every quarter from Beta to Stable, and every month from Master to
Beta, according to wiki
<https://github.com/flutter/flutter/wiki/Flutter-build-release-channels>.

And yes you can switch back to stable whenever you want.

Once again, I'm not recommending the master channel. Try VSCode or
Android Studio.

**Comment by johnaaronrose** [comment]
I want use flutter & dart and the instructions (at https://docs.flutter.dev/get-started/install/linux) say to use IntelliJ Idea as well as having Android Studio installed. The flutter installation instructions (at https://docs.flutter.dev/get-started/install/linux) say "fix this problem and then rerun flutter doctor":
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)

Also, when I try "flutter channel master", I get a lot of output including:
git: error: Your local changes to the following files would be overwritten by checkout:
git: Please commit your changes or stash them before you switch branches.
git: Aborting
Switching channels failed with error code 1.

I have NO experience of git, so I don't know what to do. Please advise.

**Comment by jmagman** [comment]
As @danagbemava-nc politely said, #96325 is available on the master channel.  Which means at some point in the future it will be available in a future beta and stable release.  You can follow along with that commit to see what tags are added, which will tell you which release it will be in https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F#finding-the-versions-that-contain-framework-commit-x

See our documentation at https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels for how to change to the master channel, if you would like the fix before it reaches stable.  `update-packages --force-upgrade` has absolutely nothing to do with changing channels.

If you continue to see this issue, or are seeing an unrelated issue with changing channels, please file a new GitHub issue.

Locking.

**Comment by timsneath** [comment]
Seeing quite a few instances of this; is it something that we might be able to cherry-pick, @jmagman. If not, then LMK and we can add a temporary note to the install instructions that this version is incompatible.

**Comment by christopherfujino** [comment]
> Seeing quite a few instances of this; is it something that we might be able to cherry-pick, @jmagman? If not, then LMK and we can add a temporary note to the install instructions that this version is incompatible.

Let me look into the feasibility of cherry-picking this (pub package cherrypicks are tricky)
