### ISSUE TITLE
flutter doctor check throws `FormatException: Unexpected extension byte (at offset 5)`

### ISSUE THREAD

**Issue by michael-shields** [flutter/flutter#94478]
After update Flutter is no longer supported in this version.  Flutter doctor reports [x] due to an error, the doctor check did not complete, FormatException: Unexpected extension byte (at offset 5), IntelliJ Version (2021.3 Ultimate Edition), flutter version 2.6.0-12.0.pre.871.

**Comment by meike02** [comment]
Same problem...

**Comment by bernaferrari** [comment]
Duplicate of https://github.com/flutter/flutter-intellij/issues/5872

**Comment by bernaferrari** [comment]
Fixed.

**Comment by michael-shields** [comment]
I’m a little confused?  What, where and how?  I don’t see a fix in IntelliJ and rebuilt the Flutter tool, after the build the Flutter doctor repots a crash still.  Can you elaborate on your ‘Fixed’ statement?  Regards.

**Comment by michael-shields** [comment]
Yes, I just loaded the new Flutter PLUGIN and my Flutter has been re-established as it was.  Regards and thank you.

**Comment by meike02** [comment]
thank you soooooooooooo much！！！！！！

**Comment by darshankawar** [comment]
Closing this as fixed in dedicated plugin and per above comments.

**Comment by darshankawar** [comment]
Reopening this, as this seems to be a Flutter tool issue and have received several reports on it:


/cc @christopherfujino

**Comment by danagbemava-nc** [comment]
Duplicate of #94060
