### ISSUE TITLE
Failed to find assets path for "Frameworks/App.framework/flutter_assets" from flutter module

### ISSUE THREAD

**Issue by ayansg** [flutter/flutter#94481]
I'm having some issue only with the add to app scenario where an existing module is failing to load with error message "Failed to find assets path for "Frameworks/App.framework/flutter_assets". I found that this happened a lot before with others but seemed like the team fixed it lately. However, it still appeared for me for a previously functional module under the latest "stable" channel (and "master") of flutter. Below are the techical details for your reference:

Output of flutter doctor -v
---
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/asengupta/Development/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/asengupta/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/asengupta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (6 available)
    • Redmi 4 (mobile)       • 6b90d397d440                             • android-arm64  • Android 7.1.2 (API 25)
    • Ayan’s iPhone (mobile) • 4c5147f0659468f98e0102e8a0d2673d5d7ca141 • ios            • iOS 15.1 19B74
    • iPhone 8 (mobile)      • C52B73E0-8DD3-4DE3-98B5-8297D3077B5A     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • iPhone 12 (mobile)     • 365C1886-D896-4391-9E30-8EE8260D0452     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 96.0.4664.55
    ! Error: Ayan’s iPhone is busy: Fetching debug symbols for Ayan’s iPhone. Xcode will continue when Ayan’s iPhone is finished. (code -10)
    ! Error: Ayan’s NGS iPhone is not connected. Xcode will continue when Ayan’s NGS iPhone is connected. (code -13)

• No issues found!
---

Xcode version: 13.1
Cocoapods version: 1.11.2

What I have tried so far:
---
1. Cleaning flutter module with `flutter clean` and reapplying `flutter pub get` followed by `pod install --clean-install`
2. Cleaning host Xcode app and rebuilding.
3. Checked build phases of the host Xcode target and Runner target and verified both of them are showing expected settings
<img width="1125" alt="Screenshot 2021-12-01 at 10 01 09 AM" src="https://user-images.githubusercontent.com/1812245/144172141-e3bf2c0b-145d-47c6-8e5f-d73eaddcbbb2.png">
<img width="1260" alt="Screenshot 2021-12-01 at 10 02 55 AM" src="https://user-images.githubusercontent.com/1812245/144172323-75777dee-576f-4fd2-bb21-f1a09fee5e93.png">
<img width="1082" alt="Screenshot 2021-12-01 at 10 03 38 AM" src="https://user-images.githubusercontent.com/1812245/144172386-642c18df-7007-4560-b8d5-c489c631d337.png">
4. Deleting the content of the .ios folder and repairing the module with `flutter create -t module .` 
5. Switching to master channel from stable and back. Didn't work on both.

When I investigated further I found:
1. The App.framework is being produced properly in the build directory on workspace build with relevant flutter_assets subfolder.
2. However, it is not being embedded into the app bundle. I checked the Frameworks folder under the generated app bundle and no App.framework was there though it has the Flutter.framework in place.
3. I then checked the "Targets Support Files/Pods-<myappname>/Pods-<myappname>-frameworks.sh" under the "Pods" project of my app and confirmed that there is no "App.framework" listed under the list of embeddable frameworks though I noticed the "Flutter.framework" was there.

So it seems like to me that add to app scenario is somehow failing to embed the App.framework at least under my setup. Can you guys please let me know what I might be missing?

**Comment by darshankawar** [comment]
@ayansg 
Did you follow any option (A,B) from the [document](https://docs.flutter.dev/development/add-to-app/ios/project-setup#link-on-the-frameworks) ?  Can you also confirm if you have correctly set up as mentioned in it along with podfile ?
If yes to both questions, can you provide `flutter run --verbose` ? The log will be huge, so you can put that in a text file and share it here.
Thanks.

**Comment by ayansg** [comment]
Thanks @darshankawar for getting back and sorry I didn't follow it up lately.

To answer your first question, yes I followed the method A described in the document and the module actually was  functional previously, till the start of 2021 (if I remember it correctly). The project got stalled in the mean time to address some higher priority ones and I put my hands back into it recently. And I started to face the issue with the latest versions of Flutter/Xcode/CocoaPods that I upgraded for other projects in the mean time (not sure who is the actual culprit here :)).

So as far as I know it was configured properly and used to be a functional module without no recent changes (except `flutter pub upgrade`, `flutter clean`, `flutter pub get`, etc). Actually it is still functional if I run it as a standalone using `flutter run` from VSCode (certainly doesn't behave in the same way when embedded to the host app) and only fails to embed itself in the host for some weird reason.

PFA the verbose log from `flutter run --verbose`
[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/7644857/flutter_run_verbose.txt)

Thank you once again!

**Comment by ayansg** [comment]
I created a demo add-to-app flutter module and seems like it is happening for newer projects as well. Or I could be missing something absolutely trivial but desperately need your help to figure that out. Attached is a cleaned up version of the demo app and module. One need to run `flutter pub get` on the module before trying it out.
[module_dummy.zip](https://github.com/flutter/flutter/files/7645080/module_dummy.zip)
.

**Comment by darshankawar** [comment]
@ayansg 
Thanks for the details and demo code. I tried to run by following steps:

1. cd module1
2. flutter pub get
3. flutter run which builds properly but unable to install on the device.

When do you actually get the error `Failed to find assets path for "Frameworks/App.framework/flutter_assets"` ?
Check these similar issues and see if they help:

https://github.com/flutter/flutter/issues/93208
https://github.com/flutter/flutter/issues/93461

**Comment by ayansg** [comment]
Hello again @darshankawar! I'm not sure why the demo app failed for you with `flutter run` but that's somewhat unrelated because usually modules are intended to run from inside the host app bundle and not as a standalone. And also this demo app is just for demonstration purpose, not my existing production-ready module (as that supposed to be :(). I think you can try running the host app from Xcode, after running `flutter pub get` on the demo module and running `pod install` on the host project thereafter or try creating a module from scratch.

Coming to the your second question, I get this error in the Xcode console when I run the host ios app and try to run the flutter engine for the first time. And all I get is an blank screen after this error is reported. This is quite expected, since the module is not available in the app bundle at all in form of App.framework as reported in the error message.

Regarding the issue links that you have sent:
1. #93208 most likely talks about option B of add-to-app methods that tells about manually embedding the App.framework instead of using CocoaPods to take care of that. This is already in my workaround list if nothing really works for me. But I am using the option A (that is, embedding the App.framework through CocoaPods) which actually seems to be broken.

2. #93461 says that it was missing a script from one of its build phases, namely, `"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin` script was missing for the reporter. However, that script is pretty much present in my case and it's under the intended build phase as well. Reposting the relevant screenshot in case that doesn't show up for you from my initial post:

<img width="1082" alt="144172386-642c18df-7007-4560-b8d5-c489c631d337" src="https://user-images.githubusercontent.com/1812245/144692350-e5fe8a7e-1d20-4530-b361-6f9485ae18b7.png">

Also like @jmagman mentioned in his reply:
[You shouldn't need to call embed_and_thin, CocoaPods should be embedding the frameworks for you.](https://github.com/flutter/flutter/issues/93461#issuecomment-969195556), I'm also not making any explicit call to the above script.

So all I'm getting is that the option A of add-to-app scenario for flutter modules is actually broken either by the flutter tools responsible for embedding the App.framework to the main app bundle or by CocoaPods itself. I have attached the screenshot of my Podfile that shows how I am attaching my module with CocoaPods and the screenshot of "Generated.xcconfig" file from the module itself that shows how the build environment variables like "$FLUTTER_ROOT" has successfully been exported. So frankly I am not finding anything missing from my side if not something really trivial that I'm still overlooking.
<img width="1293" alt="Screenshot 2021-12-04 at 7 23 55 AM" src="https://user-images.githubusercontent.com/1812245/144693046-156ae050-9baf-45f6-be86-1566bab258db.png">
<img width="1655" alt="Screenshot 2021-12-04 at 7 28 08 AM" src="https://user-images.githubusercontent.com/1812245/144693060-e7e7fcac-cced-4162-9892-0553dfe5b012.png">

Thank you for following up!

**Comment by jmagman** [comment]
I ran the demo host app and it works:
![Screen Shot 2021-12-03 at 7 37 50 PM](https://user-images.githubusercontent.com/682784/144695577-17f2588f-4607-4bd4-b87e-19a7a93c26e2.png)

In Xcode can you `Product > Clean Build Folder` in your production host project, run your app, then export the build logs
<img width="1248" alt="Screen Shot 2021-12-03 at 7 39 24 PM" src="https://user-images.githubusercontent.com/682784/144695619-20f367c1-0ce0-47e8-bbe0-61052bf70a30.png">

**Comment by ayansg** [comment]
Hi @jmagman. Unfortunately I cannot provide you the full Xcode build log from our production app for some confidentiality reasons. Really sorry about that.

However, I have attached the output of the test app (module_dummy) here which is failing with the same error as the production app and is actually functional for you as I can see from your screenshots. So I hope this will help you to narrow down the reason of this issue.
[Build module_dummy_2021-12-05T03-23-42.txt](https://github.com/flutter/flutter/files/7654770/Build.module_dummy_2021-12-05T03-23-42.txt)

Thank you and will appreciate if you can spend some time to take a look into it.

**Comment by darshankawar** [comment]
Thank for the details. I had an issue at my end locally that I fixed after which I was able to run the module_dummy app you shared earlier.

<img width="914" alt="Screenshot 2021-12-06 at 11 33 35 AM" src="https://user-images.githubusercontent.com/67046386/144795730-226a50c4-31e8-4860-836f-4b8dcba08610.png">

<details>
<summary> stable flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!


```

</details>

**Comment by ayansg** [comment]
@darshankawar in that case can you please review my build log to point out what I might be missing? Because it still doesn't work for me.

**Comment by ayansg** [comment]
Option C (and maybe Option B) of add-to-app module integration scenario also seems broken for me that I have reported at #94700. Not a showstopper par se and I have workarounds but would like to mention here if that is something related.

**Comment by darshankawar** [comment]
@ayansg 
Thanks for being patient on this. I looked at the logs you shared earlier, but don't see any exact error entries in it. Moreover it seems to be building fine per below:

```
Project /Users/asengupta/Development/iOS/module_dummy/flutter/module1 built and packaged successfully.

Build succeeded  
```



> I have attached the output of the test app (module_dummy) here which is failing with the same error as the production app

The failure entries doesn't seem to be in the log you shared. Is it possible to share the xcode build logs that has the failure entries ?

**Comment by ayansg** [comment]
@darshankawar 

the full Xcode build log is already attached to this post. Please let me know if you are looking for anything else.

https://github.com/flutter/flutter/issues/94481#issuecomment-986099046
> Hi @jmagman. Unfortunately I cannot provide you the full Xcode build log from our production app for some confidentiality reasons. Really sorry about that.
> 
> However, I have attached the output of the test app (module_dummy) here which is failing with the same error as the production app and is actually functional for you as I can see from your screenshots. So I hope this will help you to narrow down the reason of this issue. [Build module_dummy_2021-12-05T03-23-42.txt](https://github.com/flutter/flutter/files/7654770/Build.module_dummy_2021-12-05T03-23-42.txt)
> 
> Thank you and will appreciate if you can spend some time to take a look into it.

**Comment by darshankawar** [comment]
Thanks for digging in. Keeping it open for further insights from team.

/cc @jmagman

**Comment by jmagman** [comment]
CocoaPods should be handling embedding the framework, and if it's not, then I think you have an issue in your particular setup or environment.

You can see our integration test that validates a host app injecting a Flutter module with CocoaPods embeds the App.framework:
https://github.com/flutter/flutter/blob/6b51924de3575d889802baeb609e1b346c53c297/dev/devicelab/bin/tasks/module_test_ios.dart#L288-L295

I just tried manually with the sample app https://github.com/flutter/samples/tree/master/add_to_app/plugin and CocoaPods does embed the App.framework in the bundle:
<img width="1946" alt="Screen Shot 2021-12-09 at 7 57 50 PM" src="https://user-images.githubusercontent.com/682784/145514899-9c0a08ff-6b68-4d2a-bbee-8628391206fd.png">
![Screen Shot 2021-12-09 at 7 56 46 PM](https://user-images.githubusercontent.com/682784/145514848-4bfa1362-d3e9-4792-aff2-5676fb59003a.png)

This is handled by the `flutter_module_using_plugin` pod, which should be added to your project from `install_all_flutter_pods` in your Podfile.
```
Pod::Spec.new do |s|
  s.name                  = 'flutter_module_using_plugin'
  s.version               = '0.0.1'
  s.summary               = 'Flutter module'
  s.description           = 'Flutter module - flutter_module_using_plugin'
  s.homepage              = 'https://flutter.dev'
  s.license               = { :type => 'BSD' }
  s.author                = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source                = { :path => '.' }
  s.ios.deployment_target = '9.0'
  s.vendored_frameworks   = 'App.framework'
  s.dependency 'Flutter'
end
```
The `module_dummy` project zip you attached doesn't include the `flutter/module1/.ios` directory.  And as I said in https://github.com/flutter/flutter/issues/94481#issuecomment-985959765 I can run the host app fine in the test project you provided.

Can you run `flutter pub get` in that `module1` directory and attach it again?

**Comment by ayansg** [comment]
Hello again @jmagman and @darshankawar and sorry I didn't follow it up lately.

Actually I dug it further days back and realized this is the exact same issue mentioned in https://github.com/flutter/flutter/issues/93461 with the exact same workaround. And I am really sorry that I posted the wrong pictures of the build phases from my `Runner.xcodeproj` by mistake, instead of the actual host app that I am using the module in.

When I compared my host app with the Runner I realized the "Thin Binary" build phase is actually missing from the host app even after everything is properly set up and installed. So I created it manually and added the following in that phase and voila! everything worked as expected.

> set -eu
> source "${SRCROOT}/FlutterComponents/mica/.ios/Flutter/flutter_export_environment.sh"
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin

So this time I dug further into the generated (by `flutter pub get`) `podhelper.rb` where we actually have the `install_all_flutter_pods` method that in turn calls the `install_flutter_application_pod` method referencing the App.framework. However, I realized `install_flutter_application_pod` merely supplies a placeholder App.framework to CocoaPods so that it doesn't complain  and adds a build phase to actually assemble and build the add-to-app module using `xcode_backend`. The embedding part is still the responsibility of "Thin Binary" phase, again by the same `xcode_backend` script (that @jmagman, I believe, you are a contributor of :) and so you know it way better) but this time with `embed_and_thin`.

So frankly I didn't find any script, at least in my generated `podhelper.rb`, that actually adds the "Thin Binary" build phase to a host project taking care of the `embed_and_thin` operation. I have attached it herewith for you to look into:
[podhelper.txt](https://github.com/flutter/flutter/files/7698187/podhelper.txt)

It made me much more curious what actually makes "Thin Binary" phase available to the Runner while avoiding it altogether for existing native host apps. So I explored a bit more inside the source and finally realized the "Thin Binary" phase comes out of the box with the module template itself, shipped with the SDK and it is located right inside of `$FLUTTER_ROOT/packages/flutter_tools/templates/module/ios/host_app_ephemeral/Runner.xcodeproj.tmpl/project.pbxproj.tmpl`.

So no wonder it is not already in my existing host app and only inside the Runner and since the Runner runs on the device/simulator when I use `flutter run`, it actually works.

So like I said manually adding the build phase to an existing app is a workaround for now but I am really wondering if this an issue with some kind of version conflict on my end because all I can see `podhelper.rb` doesn't take care of it by any means.

**Comment by ayansg** [comment]
> CocoaPods should be handling embedding the framework, and if it's not, then I think you have an issue in your particular setup or environment.
> 
> You can see our integration test that validates a host app injecting a Flutter module with CocoaPods embeds the App.framework:
> 
> https://github.com/flutter/flutter/blob/6b51924de3575d889802baeb609e1b346c53c297/dev/devicelab/bin/tasks/module_test_ios.dart#L288-L295
> 
> I just tried manually with the sample app https://github.com/flutter/samples/tree/master/add_to_app/plugin and CocoaPods does embed the App.framework in the bundle: <img alt="Screen Shot 2021-12-09 at 7 57 50 PM" width="1946" src="https://user-images.githubusercontent.com/682784/145514899-9c0a08ff-6b68-4d2a-bbee-8628391206fd.png"> ![Screen Shot 2021-12-09 at 7 56 46 PM](https://user-images.githubusercontent.com/682784/145514848-4bfa1362-d3e9-4792-aff2-5676fb59003a.png)
> 
> This is handled by the `flutter_module_using_plugin` pod, which should be added to your project from `install_all_flutter_pods` in your Podfile.
> 
> ```
> Pod::Spec.new do |s|
>   s.name                  = 'flutter_module_using_plugin'
>   s.version               = '0.0.1'
>   s.summary               = 'Flutter module'
>   s.description           = 'Flutter module - flutter_module_using_plugin'
>   s.homepage              = 'https://flutter.dev'
>   s.license               = { :type => 'BSD' }
>   s.author                = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
>   s.source                = { :path => '.' }
>   s.ios.deployment_target = '9.0'
>   s.vendored_frameworks   = 'App.framework'
>   s.dependency 'Flutter'
> end
> ```
> 
> The `module_dummy` project zip you attached doesn't include the `flutter/module1/.ios` directory. And as I said in [#94481 (comment)](https://github.com/flutter/flutter/issues/94481#issuecomment-985959765) I can run the host app fine in the test project you provided.
> 
> Can you run `flutter pub get` in that `module1` directory and attach it again?

The output becomes excessively large after I run `flutter pub get` and try to attach the whole project. So I stripped out the generated stuffs previously. I can upload it to GDrive and send you a link here if you want.

**Comment by jmagman** [comment]
Thanks for digging into this!

> The embedding part is still the responsibility of "Thin Binary" phase, again by the same `xcode_backend` script (that @jmagman, I believe, you are a contributor of :) and so you know it way better) but this time with `embed_and_thin`.

During `xcode_backend build` (not `embed_and_thin`) App.framework and Flutter.framework are moved to your HOST app's `BUILT_PRODUCTS_DIR`: #70224
Thinning happens there as well: #77007 #76665
Bitcode thinning #77329 

That logic is in [`packages/flutter_tools/lib/src/build_system/targets/ios.dart`](https://github.com/flutter/flutter/blob/e56c83a1ac60c4ebc42e0272d6db89645a034db6/packages/flutter_tools/lib/src/build_system/targets/ios.dart).

I can see that work being detected in your build logs (at the time `BUILT_PRODUCTS_DIR` was in `~/Library/Developer/Xcode/DerivedData/module_dummy-cpbhmnhvghbwxkcdjdlrkkopnost/Build/Products/Debug-iphonesimulator`
```
debug_ios_bundle_flutter_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing: /Users/asengupta/Library/Developer/Xcode/DerivedData/module_dummy-cpbhmnhvghbwxkcdjdlrkkopnost/Build/Products/Debug-iphonesimulator/App.framework/flutter_assets/vm_snapshot_data
...
```

Then CocoaPods (I'm also on 1.11.2) should copy and codesign those frameworks from your Host app's `BUILT_PRODUCTS_DIR` to the frameworks directory in your app it in the `[CP] Embed Pods Framework` phase, not anything in your `podhelper.rb`.  When I run your `module_dummy` it does so:

<img width="1994" alt="Screen Shot 2021-12-13 at 10 04 16 AM" src="https://user-images.githubusercontent.com/682784/145864819-f1b70f0c-5e57-429f-8bac-7060fc739746.png">

You can see the CocoaPods shell script being called in your own app.

> The sample app you have used in your example uses plugins and not modules.

[The sample app I used](https://github.com/flutter/samples/tree/master/add_to_app/plugin) is testing integrating add-to-app modules, that happen to have plugins, into a host app. And as I said in https://github.com/flutter/flutter/issues/94481#issuecomment-985959765 I also tested it in the `module_dummy.zip` host app you provided, and the module loaded correctly.

So is Flutter not actually generating an `App.framework` in your Host app's `BUILT_PRODUCTS_DIR`?

**Comment by ayansg** [comment]
@jmagman while it is actually embedding "App.framework" during the `[CP]\ Embed Pods Frameworks` build phase for you it's not behaving in the same manner for me and you can check that out in my build log that I already had sent. Here is the relevant section of the log that shows it does no embedding of "App.framework" but only the "Flutter.framework":

<img width="1786" alt="Screenshot 2021-12-15 at 8 33 34 PM" src="https://user-images.githubusercontent.com/1812245/146211683-a203d04c-e007-4c6b-ad11-d26c2e13d713.png">

I further noticed the "App.framework" embedding is being performed only in the `embedFlutterFrameworks` method of `xcode_backend.dart` (at least with my flutter tools installation), at line #178 and this function is being called only if `embed`/`embed_and_thin` is passed on as command line flag to `xcode_backend`. But since CocoaPods is not emitting that command for me by any means it's always failing to embed "App.framework".

<img width="1266" alt="Screenshot 2021-12-14 at 4 27 57 PM" src="https://user-images.githubusercontent.com/1812245/146350209-c38c901d-07bf-474e-b657-8f7255c4e7b7.png">

Regarding the following section

> debug_ios_bundle_flutter_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing: /Users/asengupta/Library/Developer/Xcode/DerivedData/module_dummy-cpbhmnhvghbwxkcdjdlrkkopnost/Build/Products/Debug-iphonesimulator/App.framework/flutter_assets/vm_snapshot_data
> ...

that you have mentioned in your answer has nothing to do with `embed_and_thin` parameter of `xcode_build` rather it's actually the output of `flutter assemble` that actually generates the "App.framework" with embedded assets and it's invoked with `xcode_backend build` which is also present in my build phase. So "App.framework" gets generated perfectly for me but without that missing `embed_and_thin`, it merely fails the embedding part.

This is the screenshot of my generated "App.framework" under `BUILT_PRODUCTS_DIR` which seems perfectly fine to me

<img width="836" alt="Screenshot 2021-12-16 at 3 30 59 PM" src="https://user-images.githubusercontent.com/1812245/146350523-813da44f-56bc-4617-bc6d-a19db54a5fd4.png">

So can you please review it once more?

**Comment by ayansg** [comment]
Any update on this?

**Comment by jmagman** [comment]
I was able to reproduce this issue on CocoaPods 1.10.2, but not 1.11.
As you pointed out:
```
3. I then checked the "Targets Support Files/Pods-<myappname>/Pods-<myappname>-frameworks.sh" under the "Pods" project of my app and confirmed that there is no "App.framework" listed under the list of embeddable frameworks though I noticed the "Flutter.framework" was there.
```

When I'm on 1.11 I see:
```sh
  install_framework "${PODS_ROOT}/../../multiple_flutters_module/.ios/Flutter/App.framework"
  install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/Flutter/Flutter.framework"
```

However, when I switch to 1.10.2 the `App.framework` line isn't generated:
```sh
  install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/Flutter/Flutter.framework"
```

That shell file gets generated during `pod install`, before any Flutter code runs.  So Flutter is putting it in the right spot, `BUILT_PRODUCTS_DIR`, just as it's putting `Flutter.framework` in the right spot, but the script that's supposed to embed the framework just doesn't have the `App.framework` line.

Trying to figure out how else to debug this on 1.11, or what could be up with that module spec that's making CocoaPods not embed it...

**Comment by jmagman** [comment]
Can you try https://github.com/flutter/flutter/pull/97689 ?

Either apply the patch, or open `.ios/Flutter/podhelper.rb` and change the following line:
```diff
-    `echo "static const int Moo = 88;" | xcrun clang -x c -dynamiclib -o "#{app_framework_dylib}" -`
+    sdk_path = `xcrun --sdk iphoneos --show-sdk-path`.strip
+    `echo "static const int Moo = 88;" | xcrun clang -x c -arch arm64 -dynamiclib -miphoneos-version-min=9.0 -isysroot "#{sdk_path}" -o "#{app_framework_dylib}" -`
```
Then in your module, run `flutter clean && fluter pub get` and in your host app re-run `pod install`.

**Comment by jmagman** [comment]
@ayansg @xiaochenghua https://github.com/flutter/flutter/pull/97689 has merged.  Can you confirm this fixes your issue on the master channel?  Once you upgrade, run `flutter clean` in your module, then try to reproduce.

**Comment by jmagman** [comment]
Also @figbin

**Comment by Yongle-Fu** [comment]
same issue

**Comment by jmagman** [comment]
@Yongle-Fu

> Can you confirm this fixes your issue on the master channel?  Once you upgrade, run `flutter clean` in your module, then try to reproduce.

**Comment by ljmatan** [comment]
@jmagman 

Updating to the latest master results in this error when building: 
```
cocoapods is only supported on the dev, beta, or stable channels. Detected
version is 2.11.0-0.0.pre.493
```

**Comment by ljmatan** [comment]
@jmagman 

And if I use option B, I'm still running into the same issue 

```
2022-02-09 14:49:19.152312+0100 ADAC_target_structure_iOS[38995:375026] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2022-02-09 14:49:19.152621+0100 ADAC_target_structure_iOS[38995:375026] Metal API Validation Enabled
2022-02-09 14:49:19.229378+0100 ADAC_target_structure_iOS[38995:375293] [VERBOSE-2:engine.cc(195)] Engine run configuration was invalid.
2022-02-09 14:49:19.229448+0100 ADAC_target_structure_iOS[38995:375293] [VERBOSE-2:shell.cc(580)] Could not launch engine with configuration.
2022-02-09 14:49:19.295407+0100 ADAC_target_structure_iOS[38995:375318] flutter: Observatory listening on http://127.0.0.1:57553/JYGktHlu4Qc=/
```

**Comment by ljmatan** [comment]
Sorry, I was actually back to 2.5.3 stable as otherwise the app crashes due to another issue. 

Having said that and having done flutter clean etc., it still doesn't work on the latest master channel with option B.

**Comment by ljmatan** [comment]
Works now with new projects on the latest master channel with option B.
