### ISSUE TITLE
[CanvasKit] readPixels on images created using MakeLazyImageFromTextureSource returns null

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#94895]
The workaround is to keep the `VideoFrame` and use `copyTo` to get pixels.

Filing this to track https://bugs.chromium.org/p/skia/issues/detail?id=12721.

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/103612

**Comment by BennyKirschner** [comment]
Hi, any updates on this or ways we can help? 
Pretty critical issue, since it broke parts of the core functionality within my web app.

**Comment by shofizone** [comment]
> Hi, any updates on this or ways we can help? Pretty critical issue, since it broke parts of the core functionality within my web app.
There is a way, you can use flutter 3. But you won't get new optimized image decoding. I am also waiting for their solutions.
https://github.com/flutter/flutter/issues/103612#issuecomment-1135343624

**Comment by topex-psy** [comment]
Any updates on this? This is very important for my production application as not many people use Firefox & Safari.

**Comment by bitbendergames** [comment]
Any updates on this? Very annoying bug still.

**Comment by ValentinVignal** [comment]
Hello, is there a work around for https://github.com/flutter/flutter/issues/103612 while we wait for the fix?

**Comment by passsy** [comment]
I tried the `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false` fix suggested in the [skia issue](https://bugs.chromium.org/p/skia/issues/detail?id=12721) without luck :(

This makes it impossible for [Wiredash](http://wiredash.io/) to take useful screenshots of Flutter Apps.

**Comment by oliverbytes** [comment]
> I tried the `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false` fix suggested in the [skia issue](https://bugs.chromium.org/p/skia/issues/detail?id=12721) without luck :(
> 
> This makes it impossible for [Wiredash](http://wiredash.io/) to take useful screenshots of Flutter Apps.

it must be run on --release mode. Have you tried?

**Comment by passsy** [comment]
> it must be run on --release mode. Have you tried?

Awesome, it's working in release mode! Check out our [demo](https://demo.wiredash.io/)

**Comment by oliverbytes** [comment]
> > it must be run on --release mode. Have you tried?
> 
> Awesome, it's working in release mode! Check out our [demo](https://demo.wiredash.io/)

So, all this time you didn't know it will work on release mode? 😁 I'm happy you fixed your issue already 👍

**Comment by jtmcdole** [comment]
With `Flutter 3.4.0-17.2.pre • channel beta` and flags:

```
flutter build web --web-renderer canvaskit --release --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false
```

I'm seeing the following errors on mobile chrome:


<details><summary>chrome://inspect console</summary>

```
flutter.js:280 Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:66:11)
    at FlutterLoader.loadEntrypoint (flutter.js:278:33)
    at (index):46:23
(anonymous) @ flutter.js:280
Promise.catch (async)
loadEntrypoint @ flutter.js:278
(anonymous) @ (index):46
load (async)
(anonymous) @ (index):44
main.dart.js:10082 Flutter Web Bootstrap: Programmatic
main.dart.js:10082 NoSuchMethodError: method not found: 'readPixels' on null
main.dart.js:10082     at http://10.1.10.2:8080/main.dart.js:11766:5
main.dart.js:10082     at M1.a (http://10.1.10.2:8080/main.dart.js:3577:62)
main.dart.js:10082     at M1.$2 (http://10.1.10.2:8080/main.dart.js:16985:14)
main.dart.js:10082     at Object.L (http://10.1.10.2:8080/main.dart.js:3563:10)
main.dart.js:10082     at k0.DS (http://10.1.10.2:8080/main.dart.js:11775:10)
main.dart.js:10082     at k0.lX (http://10.1.10.2:8080/main.dart.js:11757:21)
main.dart.js:10082     at Object.Qj (http://10.1.10.2:8080/main.dart.js:5757:20)
main.dart.js:10082     at http://10.1.10.2:8080/main.dart.js:6269:14
main.dart.js:10082     at M1.a (http://10.1.10.2:8080/main.dart.js:3577:62)
main.dart.js:10082     at M1.$2 (http://10.1.10.2:8080/main.dart.js:16985:14)
29WebGL: INVALID_OPERATION: delete: object does not belong to this context
13WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context
13[.WebGL-0x2030f3f00]RENDER WARNING: there is no texture bound to the unit 0
```
</details>

This happens while simply trying to build an image atlas from a group of images (for later drawAtlas calls) - in the picture.toImage.

**Comment by jtmcdole** [comment]
>  NoSuchMethodError: method not found: 'readPixels' on null

I believe this is due to Android Chrome having a texture limitation of 4K and the atlas textures I was building were not rect-packing. Maybe room for improvement: how to discover these limitations so a Game could choose to downscale textures?

**Comment by hterkelsen** [comment]
This should be fixed in the latest master. Please reopen if you can repro the problem on master.

**Comment by asif786ka** [comment]
Hi Resolution Team. The issue is still observed on master and it is impacting our production app in web. Do you think anyone can help?
