### ISSUE TITLE
[iOS] SIGABRT GrMtlCommandBuffer Crash on production app

### ISSUE THREAD

**Issue by curls** [flutter/flutter#96757]
Hi,

Our production App encountered a `SIGABRT GrMtlCommandBuffer...` crash and happened many times, but we can't reproduce it.

<details>
  <summary>Logs</summary>

```
0 libsystem_kernel.dylib ___pthread_kill + 8
8 AGXMetalA12 0x00000001f36e6000 + 208220
9 Flutter GrMtlCommandBuffer::getRenderCommandEncoder(MTLRenderPassDescriptor*, GrMtlPipelineState const*, GrMtlOpsRenderPass*) (GrMtlCommandBuffer.mm:88)
10 Flutter GrMtlOpsRenderPass::precreateCmdEncoder() (GrMtlOpsRenderPass.mm:40)
11 Flutter GrMtlOpsRenderPass::GrMtlOpsRenderPass(GrMtlGpu*, GrRenderTarget*, GrSurfaceOrigin, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&) (GrMtlOpsRenderPass.mm:244)
12 Flutter GrMtlGpu::onGetOpsRenderPass(GrRenderTarget*, GrAttachment*, GrSurfaceOrigin, SkIRect const&, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&, SkTArray<GrSurfaceProxy*, true> const&, GrXferBarrierFlags) (GrMtlGpu.mm:213)
13 Flutter GrOpsTask::onExecute(GrOpFlushState*) (GrOpsTask.cpp:625)
14 Flutter GrDrawingManager::flush(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) (GrDrawingManager.cpp:308)
15 Flutter GrDrawingManager::flushSurfaces(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) (GrDrawingManager.cpp:498)
16 Flutter SkCanvas::onFlush() (GrDirectContext.cpp:398)
17 Flutter _ZNSt3__110__function6__funcIZN7flutter15GPUSurfaceMetal28AcquireFrameFromCAMetalLayerERK7SkISizeE3$_0NS_9allocatorIS7_EEFbRKNS2_12SurfaceFrameEP8SkCanvasEEclESC_OSE_ (gpu_surface_metal.mm:93)
18 Flutter flutter::SurfaceFrame::Submit() (surface_frame.cc:43)
19 Flutter flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (functional:1902)
20 Flutter _ZNSt3__110__function6__funcIZN7flutter10Rasterizer4DrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEENS_8functionIFbRS7_EEEE3$_1NS_9allocatorISE_EEFvNS_10unique_ptrIS7_NS_14default_deleteIS7_EEEEEEclEOSK_ (rasterizer.cc:356)
Flutter flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>) (memory:2648)
22 Flutter _ZNSt3__110__function6__funcIZN7flutter5Shell14OnAnimatorDrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEENS4_9TimePointEE4$_35NS_9allocatorISB_EEFvvEEclEv (functional:1818)
23 Flutter fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:121)
24 Flutter fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
25 CoreFoundation ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
29 CoreFoundation _CFRunLoopRunSpecific + 600
30 Flutter fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
31 Flutter _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:0)
32 libsystem_pthread.dylib __pthread_start + 148
```

```
MacBook-Pro-2:~ venus$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code
      -13)
    ! Error: iPhone8😍 is not connected. Xcode will continue when iPhone8😍 is connected.
      (code -13)
    ! Error: iphoneX😂 is not connected. Xcode will continue when iphoneX😂 is connected.
      (code -13)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@curls 
From the log you provided, it seems to be similar to https://github.com/flutter/flutter/issues/90743 which has been fixed and should be available on recent / latest versions (e.g latest master). Since you are on 2.2.3, you'll need to upgrade to latest version to see the fix.https://github.com/flutter/flutter/issues/90743#issuecomment-940469390.
Closing this as already fixed. If after upgrade to latest master you still see same exception, write in comments and I'll reopen.

**Comment by curls** [comment]
@darshankawar 
We have upgraded to flutter v2.8.0, but the exception still exists.

**Comment by curls** [comment]
it seems to be similar to #97049 #89171, but still open
