### ISSUE TITLE
[stable 2.10] New material icons are not properly rendered

### ISSUE THREAD

**Issue by shashkiranr** [flutter/flutter#97767]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 
official Material Icons

**Actual results:** 
Mismatched Icons

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const IconDemo());

class IconDemo extends StatelessWidget {
  const IconDemo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'IconDemo Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('IconDemo Demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: const [
              Icon(
                Icons.edit_calendar,
              ),
              SizedBox(height:10),
               Icon(
                Icons.edit_calendar_outlined,
              ),
              SizedBox(height:10),
               Icon(
                Icons.edit_calendar_rounded,
              ),
               SizedBox(height:10),
               Icon(
                Icons.edit_calendar_sharp,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Screen Shot -** 

![Screen Shot 2022-02-03 at 22 36 06 PM](https://user-images.githubusercontent.com/4161647/152468050-1d183f0d-9ae5-4cc2-962c-8baf10897262.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

I use the new M1 Max Macbook Pro

</details>

**Comment by maheshmnj** [comment]
Hi @shashkiranr, Thanks for filing the issue. I am able to reproduce the issue the icons are incorrectly rendered and do not render at all on Android. This issue is only on the stable 2.10 and the icons are properly rendered on the master channel. Looks like the issue is only with the newly added icons in `stable 2.10`, I tried a few old icons and they are properly rendered. 

### Stable 2.8.1

![image](https://user-images.githubusercontent.com/31410839/152514832-e9a872d3-ad2f-46f0-a5f2-a2b8487b9d1d.png)

### Master

![image](https://user-images.githubusercontent.com/31410839/152515706-3a5569c7-e244-44b4-90af-a5e45f555350.png)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API
      30)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.371, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.371 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1285eef1b (2 days ago), 2022-02-02 00:50:20 -0500
    • Engine revision 5bbdb7a6f7
    • Dart version 2.17.0 (build 2.17.0-74.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API
      30)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
cc: @guidezpl

**Comment by guidezpl** [comment]
Yeah, that's unfortunate. 

https://github.com/flutter/flutter/commit/99977cea1c4ab14dbd46866df8711d5a91af16f9#diff-13290fa2f68af119d9ef83fe8b8b112cac99f00b50b7e44da05446b1e2bb8e73 made it in 2.10 but was reverted due to an issue. Neither the revert (https://github.com/flutter/flutter/commit/73fb2e653dd058e97dfc81954aa944a15c2dae5b#diff-13290fa2f68af119d9ef83fe8b8b112cac99f00b50b7e44da05446b1e2bb8e73) nor the correct update (https://github.com/flutter/flutter/commit/e9b8a6efb22246e5e7428adcc64a6d324d48a792#diff-13290fa2f68af119d9ef83fe8b8b112cac99f00b50b7e44da05446b1e2bb8e73) made it in to 2.10.

I'm going to look at possible cherry-picking options for a fix.

**Comment by wfinken** [comment]
Windows build also does not render the new icons, it instead renders nothing.

**Comment by chrias** [comment]
file_open icon is broken on 2.10
![image](https://user-images.githubusercontent.com/58785256/152636754-6a147bfa-7c0c-4c9a-b774-e7bc22702e3f.png)

**Comment by guidezpl** [comment]
For the cp review, #95966 is the revert, #96115 is the subsequent fixed update.

**Comment by longtimedeveloper** [comment]
None of the key icons renderer either.  

![155218591-8245282c-3e4d-47c7-8367-cb326b02d7aa](https://user-images.githubusercontent.com/79998776/155338284-adca593a-8c9b-4aa8-8a44-e9165570f2f4.png)

![155218176-a50eefa4-8d03-48a6-80d5-02a5c467cac4](https://user-images.githubusercontent.com/79998776/155338647-11a61e99-c170-4061-b2d9-f649de1d478a.png)

![155218291-73c9e028-b7c4-42b3-bd69-893c64432eb8](https://user-images.githubusercontent.com/79998776/155338680-cf783bc6-79ee-457e-be85-610a3e51835f.png)

![155218248-7be7a6c7-4c1f-4e6e-9e04-56649058dec2](https://user-images.githubusercontent.com/79998776/155338699-54058190-ae0a-439b-9bbd-932303758d22.png)

**Comment by maheshmnj** [comment]
The fix is available on `stable 2.10.3`

**Comment by Rodrigolmti** [comment]
Hello, I just updated my flutter to 2.10.3 and the problem still happens.

**Comment by maheshmnj** [comment]
@Rodrigolmti Please specify the icons which do not render as expected.

**Comment by nombrekeff** [comment]
@maheshmnj In my case this icons do not render correctly:
* format_overline
* format_overline_outlined
* format_overline_rounded
* format_overline_sharp
* forum

I have not encountered more, I will update your if I find any more!

**Comment by maheshmnj** [comment]
@nombrekeff I see the icons rendering fine on `stable 2.10.3` (Output in same order as your bullets)

### Flutter 

<img width="257" alt="image" src="https://user-images.githubusercontent.com/31410839/159480898-a94a6a8b-01e2-4c99-8733-f4bd90752341.png">


### fonts.google.com

https://user-images.githubusercontent.com/31410839/159480949-7c294458-bec3-416a-b746-4dc204d3b2d9.mov


Can you also attach the output that you are seeing ?

**Comment by nombrekeff** [comment]
Ohh, I'm on 2.10.1 actually, might upgrade and try again.

**Comment by nombrekeff** [comment]
@maheshmnj Just upgraded and it's rendering correctly now! My bad 😅
