### ISSUE TITLE
onGenerateRoute not called for universal links on iOS

### ISSUE THREAD

**Issue by MatthewPatience** [flutter/flutter#97976]
## Steps to Reproduce

1. Implement universal links for iOS
2. Implement onGenerateRoute in MaterialApp
3. Invoke a universal link in iOS (Example for our app: `https://mytestapp.web.app/listings?lid=21QTrKrRFyblWRLz9G5R`)

**Expected results:**
Application should launch and onGenerateRoute should receive a RouteSettings object with `name` parameter set to the URI of the invoked universal link. This is the functionality that is defined here: https://docs.flutter.dev/development/ui/navigation/deep-linking

**Actual results:**
Application resumes, but onGenerateRoute is not called. However, this functionality works perfectly on Android. 

<details>
<summary>Code sample</summary>

```dart
Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      theme: AppTheme.generateDarkTheme(),
      onGenerateInitialRoutes: _onGenerateInitialRoutes,
      onGenerateRoute: _onGenerateRoute,
      initialRoute: "/",
    );
}

List<Route<dynamic>> saveInitialRoute(String initialRouteName) {
    return [
      MaterialPageRoute(builder: (BuildContext context) => Root())
    ];
}

MaterialPageRoute getRoute(RouteSettings settings) {
    print("Get Route: ${settings.name}"); //This function is not called when universal links are invoked and the app resumes
    return _route(settings);
}
```

</details>

<details>
  <summary>Logs</summary>

Interestingly, the following output is logged. The `lid` parameter is the query parameter attached to our invoked universal link. The Firebase Analytics package appears to be capable of receiving the universal link.

```
8.11.0 - [Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    lid = 21QTrKrRFyblWRLz9G5R;
}
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-CA)
    • Flutter version 2.8.1 at /Users/matthewpatience/fluttersdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/matthewpatience/Library/Android/sdk
    • Platform android-Sv2, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Matthew’s iPhone (mobile) • bfda425abaaeda015b15954eabf432ba7c31331d • ios            • iOS 14.6 18F72
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@MatthewPatience 
Please check [this](https://github.com/flutter/flutter/issues/82550) similar issue that was fixed few months back and see if the fix made to it helps you to resolve the issue you reported.

**Comment by MatthewPatience** [comment]
Thanks @darshankawar , I checked and it seems that fix was already merged, yet the issue still persists for me. Is it possible this was fixed for Navigator 2.0, but not Navigator 1.0?
