### ISSUE TITLE
App becomes unresponsive after a few seconds with a gif and CupertinoDatePicker

### ISSUE THREAD

**Issue by yoniker** [flutter/flutter#98275]
## Steps to Reproduce

Simply run the minimal code I've attached on an emulator or a real device, and wait up to 20 seconds. The screen will become not responsive(almost completely stuck,not just missing a few frames), and the gif will stop playing or play extremely slowly. 
 
The problem is consistent when changing the gif, changing the gif to be an asset image instead of network image, and was even when trying totally different development environments (Linux desktop to windows laptop)

**Expected results:** 
a working gif and a responsive date picker

**Actual results:** 
The app is completely stuck

<details>
<summary>Code sample</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const BirthdayOnboardingScreen(),
    );
  }
}

class BirthdayOnboardingScreen extends StatefulWidget {
  static String routeName = '/birthday_onboarding';

  const BirthdayOnboardingScreen({Key? key}) : super(key: key);

  @override
  _BirthdayOnboardingScreenState createState() =>
      _BirthdayOnboardingScreenState();
}

class _BirthdayOnboardingScreenState extends State<BirthdayOnboardingScreen> {
  DateTime selectedDate = DateTime(1990, 1,
      1);

  final firstDate = DateTime(1900, 1);
  final lastDate = DateTime.now();

  @override
  Widget build(BuildContext context) {
    double screenHeight = MediaQuery.of(context).size.height;

    return SafeArea(
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        body: Column(
          children: [
            Image.network('https://c.tenor.com/52lufF4B6ogAAAAd/happy-birthday-to-me-my-birthday.gif'),
             Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                SizedBox(
                  height:

                  screenHeight * 0.18,
                  child: CupertinoDatePicker(
                      mode: CupertinoDatePickerMode.date,
                      initialDateTime: selectedDate,
                      minimumDate: firstDate,
                      maximumDate: lastDate,
                      onDateTimeChanged: (newDate) {
                        setState(() {
                          selectedDate = newDate;
                        });
                      }),
                ),

              ],
            ),

          ],
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
(server_env) yoni@Papush:~/Projects/try_gif$ flutter run --verbose
[  +42 ms] executing: uname -m
[  +19 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +3 ms] executing: [/home/yoni/Software/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] executing: [/home/yoni/Software/flutter/] git tag --points-at d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[   +7 ms] Exit code 0 from: git tag --points-at d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] executing: [/home/yoni/Software/flutter/] git describe --match *.*.* --long --tags d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[  +29 ms] Exit code 0 from: git describe --match *.*.* --long --tags d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] 2.10.0-0.0.pre-517-gd6d3283c8d
[   +5 ms] executing: [/home/yoni/Software/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/yoni/Software/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [/home/yoni/Software/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] executing: /home/yoni/Android/Sdk/platform-tools/adb devices -l
[  +24 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[   +4 ms] /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +15 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +74 ms] Skipping pub get: version match.
[  +40 ms] Generating /home/yoni/Projects/try_gif/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +30 ms] ro.hardware = ranchu
[   +7 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software
rendering with
           "--enable-software-rendering".
[  +16 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/yoni/Projects/try_gif/.dart_tool/package_config_subset}
[  +13 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +2 ms] /home/yoni/Software/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/yoni/Software/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/yoni/Software/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.TUXLJV/flutter_tool.FRPQSC/app.dill
--packages /home/yoni/Projects/try_gif/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[   +5 ms] executing: /home/yoni/Android/Sdk/build-tools/31.0.0-rc2/aapt dump xmltree
/home/yoni/Projects/try_gif/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +4 ms] Exit code 0 from: /home/yoni/Android/Sdk/build-tools/31.0.0-rc2/aapt dump xmltree
/home/yoni/Projects/try_gif/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.try_gif" (Raw: "com.example.try_gif")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="try_gif" (Raw: "try_gif")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.try_gif.MainActivity" (Raw: "com.example.try_gif.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +4 ms] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +9 ms] <- compile package:try_gif/main.dart
[  +11 ms] --------- beginning of main
           02-11 20:13:57.344 I/DeviceStateChecker( 2533): DeviceStateChecker cancelled
[   +7 ms] executing: /home/yoni/Android/Sdk/platform-tools/adb version
[   +7 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as /home/yoni/Android/Sdk/platform-tools/adb
[        ] executing: /home/yoni/Android/Sdk/platform-tools/adb start-server
[   +4 ms] Building APK
[   +9 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] Using gradle from /home/yoni/Projects/try_gif/android/gradlew.
[  +10 ms] executing: /home/yoni/Software/android-studio-new/jre/bin/java -version
[  +49 ms] Exit code 0 from: /home/yoni/Software/android-studio-new/jre/bin/java -version
[        ] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
           OpenJDK 64-Bit Server VM (build 11.0.8+0-b944-6842174, mixed mode)
[        ] executing: /home/yoni/Software/android-studio/jre/bin/java -version
[  +78 ms] Exit code 0 from: /home/yoni/Software/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[        ] executing: /home/yoni/Software/android-studio/jre/bin/java -version
[  +79 ms] Exit code 0 from: /home/yoni/Software/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +1 ms] executing: [/home/yoni/Projects/try_gif/android/] /home/yoni/Projects/try_gif/android/gradlew -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=/home/yoni/Projects/try_gif/lib/main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +525 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
[   +1 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
[+1996 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +44 ms] executing: uname -m
[        ] [  +20 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +3 ms] executing: [/home/yoni/Software/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] [        ] executing: [/home/yoni/Software/flutter/] git tag --points-at d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] [   +8 ms] Exit code 0 from: git tag --points-at d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] [        ] executing: [/home/yoni/Software/flutter/] git describe --match *.*.* --long --tags
d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] [  +27 ms] Exit code 0 from: git describe --match *.*.* --long --tags d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9
[        ] [        ] 2.10.0-0.0.pre-517-gd6d3283c8d
[        ] [   +5 ms] executing: [/home/yoni/Software/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/yoni/Software/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +36 ms] executing: [/home/yoni/Software/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +56 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +26 ms] Initializing file store
[        ] [  +12 ms] Skipping target: gen_localizations
[        ] [   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated
contents: /home/yoni/Projects/try_gif/.dart_tool/package_config_subset}
[        ] [  +28 ms] gen_dart_plugin_registrant: Complete
[        ] [        ] kernel_snapshot: Starting due to {}
[        ] [   +6 ms] /home/yoni/Software/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/yoni/Software/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/yoni/Software/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform
--packages /home/yoni/Projects/try_gif/.dart_tool/package_config.json --output-dill
/home/yoni/Projects/try_gif/.dart_tool/flutter_build/9926ca25c00fbb68fbeeb929766d2fe6/app.dill --depfile
/home/yoni/Projects/try_gif/.dart_tool/flutter_build/9926ca25c00fbb68fbeeb929766d2fe6/kernel_snapshot.d package:try_gif/main.dart
[+4693 ms] [+6190 ms] kernel_snapshot: Complete
[ +400 ms] [ +334 ms] debug_android_application: Starting due to {}
[  +99 ms] [  +99 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see
#56466.
[        ] [  +25 ms] debug_android_application: Complete
[ +499 ms] [ +544 ms] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[ +100 ms] [   +5 ms] "flutter assemble" took 7,362ms.
[  +99 ms] [ +189 ms] ensureAnalyticsSent: 187ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +199 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +199 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[  +52 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 8s
[        ] 32 actionable tasks: 5 executed, 27 up-to-date
[ +340 ms] Running Gradle task 'assembleDebug'... (completed in 9.4s)
[  +42 ms] calculateSha: LocalDirectory: '/home/yoni/Projects/try_gif/build/app/outputs/flutter-apk'/app.apk
[ +612 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /home/yoni/Android/Sdk/build-tools/31.0.0-rc2/aapt dump xmltree
/home/yoni/Projects/try_gif/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +5 ms] Exit code 0 from: /home/yoni/Android/Sdk/build-tools/31.0.0-rc2/aapt dump xmltree
/home/yoni/Projects/try_gif/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.try_gif" (Raw: "com.example.try_gif")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="try_gif" (Raw: "try_gif")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.try_gif.MainActivity" (Raw: "com.example.try_gif.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +1 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.try_gif
[ +153 ms] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.try_gif
[ +140 ms] package:com.example.try_gif
[   +1 ms] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.try_gif.sha1
[   +8 ms] e2ce33888fc0447e5dfd020ac087b100b81dee6a
[        ] Latest build already installed.
[        ] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +10 ms] --------- beginning of main
           02-11 20:14:10.105 W/MessageQueue(13379): Handler (android.os.Handler) {3cc474c} sending message to a Handler on a dead thread
           02-11 20:14:10.105 W/MessageQueue(13379): java.lang.IllegalStateException: Handler (android.os.Handler) {3cc474c} sending message
           to a Handler on a dead thread
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.Handler.enqueueMessage(Handler.java:643)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.Handler.sendMessageAtTime(Handler.java:612)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.Handler.sendMessageDelayed(Handler.java:582)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.Handler.post(Handler.java:338)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
           02-11 20:14:10.105 W/MessageQueue(13379): 	at android.os.Binder.execTransact(Binder.java:565)
[   +6 ms] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000
--ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.try_gif/com.example.try_gif.MainActivity
[ +143 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.try_gif/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +121 ms] Observatory URL on device: http://127.0.0.1:50692/QiKQHrHhCUs=/
[        ] executing: /home/yoni/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:50692
[   +5 ms] 43149
[        ] Forwarded host port 43149 to device port 50692 for Observatory
[   +3 ms] Caching compiled dill
[  +24 ms] Connecting to service protocol: http://127.0.0.1:43149/QiKQHrHhCUs=/
[ +113 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:43149/QiKQHrHhCUs=/.
[  +65 ms] DDS is listening at http://127.0.0.1:39667/ozcWeKOmlcs=/.
[  +39 ms] Successfully connected to service protocol: http://127.0.0.1:43149/QiKQHrHhCUs=/
[  +26 ms] DevFS: Creating new filesystem on the device (null)
[  +12 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.try_gif/code_cache/try_gifMCJSBQ/try_gif/)
[   +2 ms] Updating assets
[  +44 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Syncing files to device Android SDK built for x86...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:try_gif/main.dart 70e65b05-0c03-422f-82fc-363874ae7505
[        ] <- 70e65b05-0c03-422f-82fc-363874ae7505
[        ] Bundle processing done.
[  +55 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 58ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0xa72aa310.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:39667/ozcWeKOmlcs=/
[ +427 ms] The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
                    http://127.0.0.1:9100?uri=http://127.0.0.1:39667/ozcWeKOmlcs=/
[  +10 ms] D/EGL_emulation(13411): eglMakeCurrent: 0xa4f9e240: ver 2 0 (tinfo 0xa542e900)

```

```
Analyzing try_gif...                                                    

   info • Prefer typing uninitialized variables and fields • lib/onboarding_column.dart:8:9 • prefer_typing_uninitialized_variables
   info • Prefer declaring const constructors on `@immutable` classes • lib/onboarding_column.dart:9:3 •
          prefer_const_constructors_in_immutables
   info • Use key in widget constructors • lib/onboarding_column.dart:9:3 • use_key_in_widget_constructors
   info • Prefer using if null operators • lib/onboarding_column.dart:25:20 • prefer_if_null_operators
   info • Prefer const with constant constructors • lib/onboarding_consts.dart:44:30 • prefer_const_constructors
   info • The operand can't be null, so the condition is always true • lib/onboarding_consts.dart:72:19 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/onboarding_consts.dart:73:22 • unnecessary_null_comparison
   info • Use isNotEmpty instead of length • lib/onboarding_consts.dart:78:9 • prefer_is_empty
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't
          final: RoundedButton.elvation, RoundedButton.showBorder, RoundedButton.decoration, RoundedButton.onTap,
          RoundedButton.addControlerAnimation • lib/rounded_button.dart:4:7 • must_be_immutable
   info • Use key in widget constructors • lib/rounded_button.dart:5:3 • use_key_in_widget_constructors
   info • The value of the local variable 'screenWidth' isn't used • lib/rounded_button.dart:30:18 • unused_local_variable
   info • Prefer const with constant constructors • lib/rounded_button.dart:41:18 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/rounded_button.dart:57:34 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/rounded_button.dart:69:19 • prefer_const_constructors
   info • Avoid `print` calls in production code • lib/screen_size.dart:10:5 • avoid_print

15 issues found. (ran in 1.2s)

```

```(server_env) yoni@Papush:~/Projects/try_gif$ flutter doctor -v
[✓] Flutter (Channel master, 2.11.0-0.0.pre.517, on Ubuntu 20.04.3 LTS 5.11.0-36-generic, locale en_IL)
    • Flutter version 2.11.0-0.0.pre.517 at /home/yoni/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6d3283c8d (9 hours ago), 2022-02-11 11:40:14 +0200
    • Engine revision bed591d394
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /home/yoni/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc2
    • Java binary at: /home/yoni/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/yoni/Software/android-studio-new
    • Flutter plugin version 54.0.2
    • Dart plugin version 202.8443
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/yoni/Software/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /home/yoni/Software/idea-IC-212.4746.92
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.4746.57

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /home/yoni/Software/idea-IC-213.5744.223
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

This is a very surprising bug since usually, Flutter is awesome!
I've uploaded a youtube video for your convenience:
https://youtu.be/rjRlLpoKpTs

Hopefully, you can fix this weird bug soon

**Comment by danagbemava-nc** [comment]
Hi @yoniker, does this issue reproduce when you run the app in either `release`/`profile` mode? 

Also, does this issue occur with only the gif or the `CupertinoDatePicker` is also required to reproduce it?

**Comment by yoniker** [comment]
This issue reproduces in release mode too.
You can copy-paste the code to dartpad (https://dartpad.dev/) and wait for (up to) 20 seconds - that's another way you can see this issue.

Pages with a gif only actually work - which make this issue even more interesting.

**Comment by danagbemava-nc** [comment]
Hi @yoniker, what device did you test this on? 

I tried on my Pixel 4a emulator, iOS simulator, and my physical device (Poco X3 NFC), for over 10 minutes and the app was still responsive after that. 

The only place I could reproduce this was on the web (haven't tried desktop yet), but even in that case, it took more than 5 minutes.

**Comment by jason-simmons** [comment]
I was able to reproduce this on a Moto G4 using the current tip-of-tree Flutter engine.  It does not reproduce consistently though.

When this happens, the raster thread is not making any progress.

The display list renderer is calling `SkCanvas::drawTextBlob`, and it's spending a lot of time in repeated calls to `GrTextBlobRedrawCoordinator::internalCheckPurge`.  Each call to `internalCheckPurge` is taking 15-20 seconds.

The `internalCheckPurge` loop is iterating through the fBlobList trying to remove the stale blobs.  But each call to `internalRemove` fails because `stillExists` is null.  So the `internalCheckPurge` loop keeps iterating through the entire list.

`GrTextBlobRedrawCoordinator::internalAdd` then adds the new blob to `fBlobList`, which seems to grow unbounded.  In the debugger it looked like `fCurrentSize` had reached a size of 4.2MB and was continuing to grow.  Each `internalAdd` added ~200 bytes to `fCurrentSize`, implying ~20K blobs in the list.

@herbderby

Stack trace:
```
#0  0x93c8f2ce in GrTextBlob::Key::operator== (this=0x8c6a8520, that=...)
    at ../../third_party/skia/src/gpu/text/GrTextBlob.cpp:1661
#1  0x93c9c9ca in GrTextBlobRedrawCoordinator::BlobIDCacheEntry::findBlobIndex
    (this=0x8c6976b0, key=...)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:245
#2  0x93c9c2d4 in GrTextBlobRedrawCoordinator::BlobIDCacheEntry::find (
    this=0x8c6976b0, key=...)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:239
#3  0x93c9c344 in GrTextBlobRedrawCoordinator::internalRemove (
    this=0x86376060, blob=0x7c9f3600)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:106
#4  0x93c9c776 in GrTextBlobRedrawCoordinator::internalCheckPurge (
    this=0x86376060, blob=0x7cf49580)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:180
#5  0x93c9c282 in GrTextBlobRedrawCoordinator::internalAdd (this=0x86376060, 
    blob=...)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:206
#6  0x93c9c166 in GrTextBlobRedrawCoordinator::addOrReturnExisting (
    this=0x86376060, glyphRunList=..., blob=...)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:75
#7  0x93c9bffc in GrTextBlobRedrawCoordinator::drawGlyphRunList (
    this=0x86376060, canvas=0x86342e00, clip=0x91ca3118, viewMatrix=..., 
    glyphRunList=..., paint=..., sdc=0x86119600)
    at ../../third_party/skia/src/gpu/text/GrTextBlobRedrawCoordinator.cpp:65
#8  0x93d0fcd4 in skgpu::v1::SurfaceDrawContext::drawGlyphRunList (this=0x86119600, canvas=0x86342e00, clip=0x91ca3118, viewMatrix=..., glyphRunList=..., paint=...) at ../../third_party/skia/src/gpu/v1/SurfaceDrawContext.cpp:378
#9  0x93d09c62 in skgpu::v1::Device::onDrawGlyphRunList (this=0x91ca3000, canvas=0x86342e00, glyphRunList=..., paint=...) at ../../third_party/skia/src/gpu/v1/Device.cpp:965
#10 0x93951f22 in SkBaseDevice::drawGlyphRunList (this=0x91ca3000, canvas=0x86342e00, glyphRunList=..., paint=...) at ../../third_party/skia/src/core/SkDevice.cpp:434
#11 0x9392d9ac in SkCanvas::onDrawGlyphRunList (this=0x86342e00, glyphRunList=..., paint=...) at ../../third_party/skia/src/core/SkCanvas.cpp:2300
#12 0x9392d936 in SkCanvas::onDrawTextBlob (this=0x86342e00, blob=0xa268a3c0, x=12, y=59.7799988, paint=...) at ../../third_party/skia/src/core/SkCanvas.cpp:2290
#13 0x9392e3b2 in SkCanvas::drawTextBlob (this=0x86342e00, blob=0xa268a3c0, x=12, y=59.7799988, paint=...) at ../../third_party/skia/src/core/SkCanvas.cpp:2440
#14 0x93ace4e2 in SkCanvas::drawTextBlob (this=0x86342e00, blob=..., x=12, y=59.7799988, paint=...) at ../../third_party/skia/include/core/SkCanvas.h:1849
#15 0x93e31294 in flutter::DisplayListCanvasDispatcher::drawTextBlob (this=0x91afdbe0, blob=<error reading variable: Cannot access memory at address 0xff000000>, x=12, y=59.7799988) at ../../flutter/display_list/display_list_canvas_dispatcher.cc:243
#16 0x93e21fdc in flutter::DrawTextBlobOp::dispatch (this=0x89386390, dispatcher=...) at ../../flutter/display_list/display_list_ops.h:821
#17 0x93e212bc in flutter::DisplayList::Dispatch (this=0x8d3fba70, dispatcher=..., ptr=0x893863a0 "\241\216\b\222p\334~\210f\251\006\222\240\334~\210C\020", end=0x893863a0 "\241\216\b\222p\334~\210f\251\006\222\240\334~\210C\020") at ../../flutter/display_list/display_list.cc:82
#18 0x93e20dc2 in flutter::DisplayList::Dispatch (this=0x8d3fba70, ctx=...) at ../../flutter/display_list/display_list.h:215
#19 0x93e2214c in flutter::DisplayList::RenderTo (this=0x8d3fba70, canvas=0x86342e00, opacity=0.447058827) at ../../flutter/display_list/display_list.cc:185
#20 0x93e17b44 in flutter::DisplayListLayer::Paint (this=0x905cef40, context=...) at ../../flutter/flow/layers/display_list_layer.cc:135
...
```

**Comment by jason-simmons** [comment]
Actually this does reproduce reliably using the attached app.

If you add logging of `fCurrentSize` to `GrTextBlobRedrawCoordinator::internalAdd` you'll see that it increases on every frame.  Once `fCurrentSize` crosses the `fSizeBudget` threshold then the `internalCheckPurge` calls start and the frame rate drops noticeably.

`internalCheckPurge` is not deleting the blobs because the `GrTextBlob::Key::operator==` implementation is always returning false for keys where `fPositionMatrix.hasPerspective()` is true.

The text blobs drawn by the `CupertinoDatePicker` widget have that kind of matrix.  So any attempt by `internalRemove` to find those blob keys in the `BlobIDCacheEntry` list will fail

**Comment by danagbemava-nc** [comment]
At the moment, I have been able to reproduce on  `web` and `macOS`.
The behavior on `stable` is much better than that of `master`. 
Code sample can be found in https://github.com/flutter/flutter/issues/98275#issue-1132944017. 

Labeling for further insight. 

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (7 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.11.0-0.0.pre.582, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.582 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9514106108 (5 hours ago), 2022-02-16 00:00:11 -0500
    • Engine revision b09cf53269
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by jason-simmons** [comment]
Filed a Skia bug: https://bugs.chromium.org/p/skia/issues/detail?id=12966

**Comment by moffatman** [comment]
I made a fix to Skia. I'll monitor and update when it makes it into flutter master branch. 
https://skia.googlesource.com/skia/+/b64749807264274906269606a050599911782006

**Comment by moffatman** [comment]
Fix should be in `flutter/master` now

**Comment by Bashar-gh** [comment]
@moffatman 
Same problem is happening to me on windows version 
The app freezes with no exceptions 
Raster thread taking about 30 seconds each frame
Before flutter 3 update every thing was fine and silky smooth

**Comment by moffatman** [comment]
@Bashar-gh Did you try in `flutter/master` within the last 1 day? I believe it should be fixed now.

**Comment by Bashar-gh** [comment]
> @Bashar-gh Did you try in `flutter/master` within the last 1 day? I believe it should be fixed now. 
Looks like fixed to me
Thanks a lot 😁

**Comment by lqmminh** [comment]
still this problem

**Comment by ozz-rjq** [comment]
I have a similar issue when using `Transform` widget

**Comment by ozz-rjq** [comment]
it does seem like the issue went away when using lates beta `[3.1.0-9.0.pre]` (androind and ios), haven't try web yet

**Comment by moffatman** [comment]
Should be OK on the web version now. @apalala-dev do you still see it on latest `flutter/master`?

**Comment by apalala-dev** [comment]
I tested both with the reproduction repo that I shared here and with a more complex project where it occurred a lot and the issue seems resolved for my use cases.
Performances are still not as good as on MacOS or mobile, but it stops becoming unresponsive.
Thank you!

**Comment by PiotrMitkowski** [comment]
I got the exact same issue with Flutter 3.0.4. I've also tested it with the most recent version on `master` channel and it seems to be fixed on my end. How I can track when the fix will become available in the `stable` channel?

**Comment by NotHolst** [comment]
Still present on 3.0.5 as well. 
Like the person above, i would also like to know "How I can track when the fix will become available in the stable channel?"

**Comment by sargntpi** [comment]
After upgrading to 3.3.0 this appears to be resolved (was having issues on 3.0.5 too)

**Comment by memishood** [comment]
It has been fixed with 3.3.0 (stable channel)

**Comment by wchslr** [comment]
Yup, I can confirm this issue is in stable version 3.0.5. still present... 

fixed in stable version 3.3.0 👍 😃

**Comment by danagbemava-nc** [comment]
I can no longer reproduce this on my end either and given the responses above, I feel it is safe to close this issue. 

If anyone runs into this issue, kindly file a new issue and provide detailed steps to reproduce. 

Closing this as fixed. 

Thank you
