### ISSUE TITLE
I am facing an error in Android Studio "Android Studio has stopped working" after installing & launching flutter application

### ISSUE THREAD

**Issue by bahman2000** [flutter/flutter#99497]
Hello, I click to run application in debug mode. After installing & launching the application, a dialog is displayed immediately: 

"Android Studio has stopped working
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

The remarkable point is that when i click to run application in release mode, everything is ok and error dialog is not displayed!

Android Studio Vesrsion: 2021.1.1

Flutter Version: Flutter 2.10.2  channel stable

Flutter Doctor: 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 6.3.9600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these

      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Hi @bahman2000, Thanks for filing the issue. Does this happen when running from the Android studio's terminal too? Can you also check if this happens with a newly created flutter project?  Additionally, please try upgrading flutter to `2.10.3`.

**Comment by bahman2000** [comment]
Hi @maheshmnj, Thank you for your consideration. I used the command "flutter run lib/main.dart" in the terminal and problem fixed. But in this case, I don't have access to "Flutter Hot Reload" icon and it is disabled!

Also I checked to see if "Android Studio has stopped working" happens with a newly created flutter project and unfortunately, there was still this problem.

**Comment by maheshmnj** [comment]
Thanks for the info, I am unable to reproduce this issue app runs fine in debug mode.

Could you please share the complete output of `flutter doctor -v` which shares more details about the android studio?

**Comment by bahman2000** [comment]
Below is the complete output of ### flutter doctor -v.

[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 2.10.2 at F:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at G:\Android_Studio\SDK
    • Platform android-31, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
    • Visual Studio at F:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these

      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 6.3.9600]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by bahman2000** [comment]
Also it is better to say that error dialog(Android Studio has stopped working) in android studio displayed exactly when the terminal is in the following condition:

```
Launching lib\main.dart on SM A520F in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Syncing files to device SM A520F...
```

And the executed application displays only a white screen!
َدی

**Comment by maheshmnj** [comment]
> Also it is better to say that error dialog "Android Studio has stopped working" in android studio displayed exactly when the terminal is in the following condition:

I see, @bahman2000 could you please share the complete logs of `flutter run  -v --debug`. The output will be longer, so please share it in a text file. 

Also, it would be great if you could check if this issue occurs only when targeting Android or other platforms too (Windows/web)?

**Comment by bahman2000** [comment]
Below is the complete output of `flutter run -v --debug`.

[output.txt](https://github.com/flutter/flutter/files/8198390/output.txt)

**Comment by maheshmnj** [comment]
Thanks for the update @bahman2000, Are these logs of your project or a newly created project? 

> ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
           The following assertion was thrown during performLayout():
           BoxConstraints forces an infinite height.

The logs seem to suggest that there is an issue in your widget tree, Since you are able to reproduce the issue with a newly created project, please share the logs of newly created project by running `flutter run -v`

**Comment by bahman2000** [comment]
`flutter run -v` in a newly created project:
[output.txt](https://github.com/flutter/flutter/files/8204865/output.txt)

**Comment by maheshmnj** [comment]
Thanks for the logs @bahman2000, The logs look fine to me, The app successfully gets downloaded and installed on the device, I am quite not sure if this issue is related to flutter, I am labelling this issue for further investigation.

**Comment by christopherfujino** [comment]
> Thanks for the logs @bahman2000, The logs look fine to me, The app successfully builds and gets installed on the device, I am quite not sure if this issue is related to flutter, I am labelling this issue for further investigation.

I agree with @maheshmnj. @stevemessick does Android Studio by any chance log to a file when it crashes?

**Comment by stevemessick** [comment]
@christopherfujino Yes, in Android Studio the log file can be found via a menu `Help > Show Log in Finder` (on Mac). It is slightly different for Windows, but should be recognizable.

@bahman2000 Could you reproduce the problem, then attach the log file here?

**Comment by bahman2000** [comment]
@stevemessick Thanks for your suggestion, I reproduced the problem in a newly created project and below is the log file:
[idea.log](https://github.com/flutter/flutter/files/8213056/idea.log)
Also i checked this file and i did not find any logs related to problem when the problem reproduced (
2022-03-09 12:07:05).

**Comment by bahman2000** [comment]
@stevemessick, @maheshmnj
After several tries to reproduce problem, an error registrated in the log file:
[idea.log](https://github.com/flutter/flutter/files/8308958/idea.log)

**Comment by bahman2000** [comment]
@stevemessick, @maheshmnj, @christopherfujino
Also, I checked the event logs on windows and below is the complete log:

`Faulting application name: studio64.exe, version: 2021.1.0.0, time stamp: 0x5d71842b
Faulting module name: EasyRedirect64.dll, version: 2.3.3.1, time stamp: 0x54eef9bc
Exception code: 0xc0000417
Fault offset: 0x0000000000044670
Faulting process id: 0x25ec
Faulting application start time: 0x01d83c5e8b654114
Faulting application path: C:\Program Files\Android\Android Studio\bin\studio64.exe
Faulting module path: C:\Windows\system32\EasyRedirect64.dll
Report Id: f0131a6c-a851-11ec-8287-782bcbdee349
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by bahman2000** [comment]
Finally, I fixed the problem by uninstalling any IP-Altering program! For example "Easy-Hide-IP" program. Uninstall that, and reboot, and you should be fine to use Android Studio!

**Comment by christopherfujino** [comment]
> Finally, I fixed the problem by uninstalling any IP-Altering program! For example "Easy-Hide-IP" program. Uninstall that, and reboot, and you should be fine to use Android Studio! It took me a long time to solve this problem, but I hope it will useful for someone who's facing this problem.

Thanks for following up @bahman2000! I will close this, but it should still show up in search queries in case anyone else experiences this same issue.
