### ISSUE TITLE
[Windows][Desktop]: textfield caret position is not consistent when traversing Chinese text

### ISSUE THREAD

**Issue by coolit** [flutter/flutter#99511]
Below problems occurred on windows 10 desktop version.
- put a long Chinese article which consists of multiple paragraphs into a textfield, and try to move caret by using keyboard. And soon you will find some weird caret position problems. E.g. the caret positions will suddenly go to unexpected positions etc. This might be relevant to the next problem.

- If mouse is used, soemtimes you just cannot click into the blank line in between the paragraphs. Seems if the newline is pasted from outside or read from db then it cannnot be clicked into. If the newline is originally made in textfield, no problem.

- When you try to select a specific piece of text segment by mouse, the caret will sometimes quickly move over the selected segment leaving nothing selected.

- When I copied a article from a text editor (like emeditor) to textfield in flutter, all the characters become blocks. Then If I selected carefully from the very first character to the last and then paste into textfield, there will be no blocks at all. So I guess some special marks made all its trailing characters unrecognizable. 

<details>
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.11.0-0.0.pre.753, on Microsoft Windows [Version 10.0.19041.1415], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.0)
[√] Connected device (3 available)
[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host:
</details>

**Comment by darshankawar** [comment]
Thanks for the report. Based on it, I came up with below code sample and used below mentioned long chinese text that shows the behavior reported above. 
The caret position while traversing through the text is not consistent and it jumps randomly while using keyboard and mouse, 



<details>
<summary> complete code sample </summary>

```

import 'package:flutter/material.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Web Views',
      theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: "Arial",
          textTheme: TextTheme(
              button: TextStyle(color: Colors.white, fontSize: 18.0),
              subtitle1: TextStyle(color: Colors.red))),
      home: Scaffold(
          body: Center(
              child: TextField(
                  maxLines: 20,
                  decoration: InputDecoration(
                      hintText: 'enter'
                  )
              )
          )
      ),
    );
  }
}

```

</details>

<details>

<summary> Sample chinese long text used:  </summary>

```
Jiǎntǐzì hé fántǐzì shì shǔyú wénzì fànchóu de wèntí. Dànshi xiànzài wǎng shàng guānyú zhè gè wèntí de yǒuxiē shuōfa chángcháng bǎ yǔyán hé wénzì hùn zài yīqǐ, yě yǒu rén bǎ wénhuà, chuántǒng děngděng dà màozi kòu zài zhè gè wèntí shàng, jiéguǒ líkāi tímù hěn yuǎn, yě déchū yīxiē bù zhèngquè de jiélùn.

Yǔyán jīběnshàng shì shuó de huà, yònglái gēn biéren jiāoliú huòzhě gōutōng, yě shì gèrén sīkǎo de gōngjù. Bùguò gēn biéren jiāoliú huòzhě gōutōng yībān bìxū fāchū shēngyīn (lóng-yǎ rénshì yībān yào yòng shǒuyǔ). Wǒmen sīkǎo de shíhou, biéren tīngbujiàn, zìjǐ tīngdào de shì bù zìjué de ànyǎ shēngyīn. Yǐqián kǒutóu jiāoliú bìxū dāngmiàn jìnxíng. Xiànzài yǒu diànhuà děngděng jīqì, gézhe tàikōng yě kěyǐ jiǎnghuà. Bùguǎn zěnmeyàng, yǔyán shì yǐ fāyīn wéi jīchǔ de; lián yǐqián yòulóngyòuyǎ de Helen Keller dōu néng xuéhuì yòng yǒu shēngyīn de Yīngyǔ yǎnjiǎng hé gēn rén jiāotán (bùguò děi yòng shǒu mōzhe duìfāng de liǎn, cái zhīdao duìfāng shuōle xiē shénme).

“Language” shì “yǔyán” de Yīngwén fānyì, yībān zhǐ kǒuyǔ, gēn jiǎntǐzì hé fántǐzì shì liǎng mǎ shìqing. Jíbiàn shì shūmiànyǔ (written language) yě gēn jiǎntǐzì hé fántǐzì méi yǒu bìrán de guānxi. Yīnwei kěyǐ yòng biéde fúhào xiě, bǐfangshuō “Hànyǔ pīnyīn”.

Wénzì shì bǎ yǔyán xiě xiàlái de fúhào. Guǎn nǐ shì Aījí shèngshū, Liǎng Hé Liúyù de dīngtóuzì, Nánměi Mǎyàwén, Ālābówén (yòng Ālābó zìmǔ), Éwén (yòng Cyrillic zìmù), Yīngwén (yòng Luómǎ zìmù), Fǎwén (yòng Luómǎ zìmù), Déwén (yòng Luómǎ zìmù), Yìdàlìwén (yòng Luómǎ zìmù), Xībānyáwén (yòng Luómǎ zìmù), yǐjí Zhōngguó de jiǎgǔwén, jīnwén, shígǔwén, zhuànshū, lìshū, kǎishū, xíngshū, cǎoshū, fántǐzì (jīběnshàng shì kǎishū), jiǎntǐzì, děngděng dōu shì shūxiě yǔyán de fúhào. Zhèxiē bùtóng fúhào de “mǔqin” shì gèzhǒng yǔyán. Méi yǒu yǔyán, zhèxiē fúhào zhǐ shì túxíng. Bìngqiě fúhào yuè fùzá kùnnán, zhǎngwò de rén jiù yuè shǎo, yě yuè róngyì gēn zìrán de yǔyán fēnjiā. Guòqù Zhōngguó zhǎngwò Hànzì de rén jíduān shǎo, shūmiànyǔ yě chéngle gēn zìrán yǔyán fēnjiā de wényánwén.

Wénzì shì yī gè guójiā mínzú de wénhuà hé chuántǒng bùfen, yǔyán gèng shì yī gè guójiā mínzú de wénhuà hé chuántǒng bùfen. Dànshì yǔyán xiān fāshēng, yǒu zìjǐ de shēngmìng, fāzhǎn hěn kuài. Zài jiāotōng fādá de xiàndài, gèzhǒng bùtóng de yǔyán hùxiāng yǐngxiǎng, chǎnshēng biànhuà. Wèile gēn dàduōshù de rén gōutōng jiāoliú, rénmen yě kāishǐ yāoqiú zìjǐ néng zhǎngwò yī ge bǐjiào tōngyòng de yǔyán, jíshǐ nàge yǔyán bù shì zìjǐ de mǔyǔ.

Dàgài yīnwei Zhōngguó de yǔyán tài duō, tài fēnqí, Zhōngguó zhīshi fènzǐ yīlái zhǐ kànzhòng wénzì (Hànzì), hūlüè yǔyán, chángcháng fēnbuqīng Zhōngguó yǔyán hé wénzì de qūbié, shènzhì yǐwéi Hànzì jiùshì Hànyǔ. Yóuyú duì Hànyǔ méi yǒu zúgòu de rènshi, zhídào xiànzài, xǔduō shǐyòng Hànzì de Zhōng-Wài zhīshi fènzǐ lián Hànyǔ “cí” de gàiniàn yě méi yǒu, rènwéi yī ge Hànzì jiùshì yī gè cí. Zuìjìn Niǔyuē Shíbào yǒu piān guānyú [Zhōngguó wénzì gǎigé de wénzhāng](http://roomfordebate.blogs.nytimes.com/2009/05/02/chinese-language-ever-evolving/). Yǒu wèi jiào Nelson dúzhě de pínglùn jiù jiējìn zhè yīlèi de kànfa. Tā shuō, “As a native Chinese speaker from Hong Kong, I can attest that perusing modern Chinese novels and articles in traditional characters takes little effort, for every character has meaning.” Rúguǒ ànzhào gèbié Hànzì de yìyì lái kàn xiàndài Guóyǔ (mùqián fántǐzì shūxiě de wéiyī de zài Táiwān hé hǎiwài yīxiē Táiwān qiáobāo zhōngjiān tōngxíng de xiàndài Hànyǔ) shūmiànyǔ, huì chǎnsheng hěn dà de wèntí. Wǒ céngjīng qǐng yī wèi xiě dé yīshǒu juānxiù Hànzì de Rìběn xiǎojie fānyì yī piān wénzhāng de tímù. Zhè gè tímù zhǐ yǒu liù gè fántǐzì: 粉碎血腥鎮壓 (“Fěnsuì Xuèxīng Zhènyā”). Tā bù zhīdao zhè liù gè Hànzì shíjìshang shì sān gè shuāngyīnjié cí, jiù yī ge zì yī ge zì de fānyì chūlái. Tā de fānyì shì: “powder — broken — blood — (?) — little town — pressure.”

Tán Zhōngguó “yǔ” hé “wén” de wèntí, wǒ juéde zuìhǎo néng xiān liǎojiě yīxià zài Zhōngguó tōngyòng de yǔyán. Zhōngguó de zhǔyào yǔyán yǒu nǎxiē? Wèishénme wǒ shuō zhège, ér bù shuō nàge? Yīnwei huánjìng? Yīnwei bèi qiǎngpò? Yīnwei wǒ ài zhège yǔyán? Yīnwei yǒu bìyào? Yīnwei zhè ge yǔyán hěn zhòngyào? Yě xiǎngxiang shénme shì Zhōngguórén de gòngtóng yǔyán? Yòng yīge gòngtóng yǔyán yǒu bìyào ma? Weishenme? Biéde Hànyǔ de qùxiàng huì zěnmeyàng? Rúguǒ nǐ shǐyòng Zhōngguó de gòng tóng yǔyán Pǔtónghuà, nǐ liǎojiě zhège yǔyán de yǔfǎ (bǐrú “de” hé “le” de bùtóng yǒngfǎ) ma? Zhīdao zhège yǔyán de jīběn yīnjié (bù bàokuò shēngdiào) zhǐ yǒu 408 ge ma?

Tán wénhuà, tán chuántǒng, yě gāi xiǎngxiang zìjǐ dúle duōshao gǔdài hé xiàndài de Zhōngwén shū hé diǎnjí, duì Zhōngguó de lìshǐ, wénxué, zhéxué, sīxiǎng, měishù, yīxué, zōngjiào, pēngrèn, zhèngzhi, jīngjì, jiàoyu, mínsú, kējì, chuántǒng (bǐrú xiàojìng fùmǔ) děngděng liǎojiě duōshao. Yī zhǒng wénhuà, yī zhǒng chuántǒng, bùyīdìng yǒngyuǎn shì hǎo de. Línlǐ hùxiāng bāngzhù de wénhuà hé chuántǒng shì kěqǔ de, bùqī’ànshì de wénhuà yě shì kěqǔ de. Dànshì rènwéi núlì zhìdù hélǐ de wénhuà hé chuántǒng shì yàobude de, bīpò xiǎo nǚhái bāo xiǎojiǎo de wénhuà hé chuántǒng yě shì yàobude de. Ér bàozhe yī ge wénzì fúhào lái zhèngmíng zìjǐ yǒu wénhuà xiūyǎng suīrán bìng méi yǒu cuò, dànshì wèimiǎn yǒudiǎn tōulǎn ba.

```

</details>

<details>
<summary> stable, master flutter doctor </summary>

```



[√] Flutter (Channel master, 2.11.0-0.0.pre.731, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.62.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by coolit** [comment]
Another problem is, when today an external text was pasted into a textfield, its newline marks were displayed as blocks. These marks must be special marks which wasn't rendered as new lines in textfield.

**Comment by coolit** [comment]
@darshankawar 
For those newlines which cannot be clicked into. It seems to be due to textfield not compatible with \r. And replacing \r\n with \n. This problem is gone.

**Comment by gspencergoog** [comment]
cc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
I have no problem navigating Chinese text on macOS:

https://user-images.githubusercontent.com/31859944/158487030-695b11cb-5c1c-4d65-8337-d2a74cd288ec.mov

I suspect it has to do with the extra CR for newlines on windows.

**Comment by LongCatIsLooong** [comment]
> @darshankawar For those newlines which cannot be clicked into. It seems to be due to textfield not compatible with \r. And replacing \r\n with \n. This problem is gone. And I tried with your sample piece. After replacing the same, seemed the caret problem was gone too.

Ah that makes sense. @cbracken does the text input plugin handle CR on windows?

**Comment by coolit** [comment]
@LongCatIsLooong 
Could you also take a look at the third above-mentnioned problem. Below is how to reproduce it on windows 10:
Click inside a text, either English or non-English, long press it, then move your mouse to select a piece of text, you will find nothing is selected.

**Comment by cbracken** [comment]
@coolit is the textfield caret position still and issue on the `master` branch today? There are a few potentially-related multiline textfield issues that I can see, some of which are fixed:
* https://github.com/flutter/flutter/issues/93373
* https://github.com/flutter/flutter/issues/96726

**Comment by coolit** [comment]
@cbracken  
I have just build using Flutter 3.0.4 • channel stable, but the problem is still there.
